classdef CorrectnessSuiteCampaignSelectionTest < ...
        matlab.unittest.TestCase
    %CORRECTNESSSUITECAMPAIGNSELECTIONTEST Guards campaign scope defaults.

    properties (SetAccess = private)
        RepositoryRoot (1, 1) string
    end

    methods (TestClassSetup)
        function addRegressionTestsToPath(testCase)
            testCase.RepositoryRoot = string(fileparts(fileparts( ...
                fileparts(fileparts(mfilename("fullpath"))))));
            regressionRoot = fullfile( ...
                testCase.RepositoryRoot, "regression-tests");
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture(regressionRoot));
        end
    end

    methods (Test)
        function routineScopeKeepsShortBazziAndExcludesFullProfile( ...
                testCase)
            import matlab.unittest.selectors.HasTag

            allBazziTests = matlab.unittest.TestSuite.fromClass( ...
                ?v2xsimregression.paper.bazzi2020blindspots. ...
                Bazzi2020BlindSpotTest);
            [routineSuite, excludedCount] = ...
                v2xsimtest.execution.selectRegressionCampaigns( ...
                    allBazziTests, false);

            shortSuite = allBazziTests.selectIf( ...
                HasTag("ShortCampaign"));
            publicationSuite = allBazziTests.selectIf( ...
                HasTag("PublicationCampaign"));
            testCase.verifyNumElements(shortSuite, 1);
            testCase.verifyNumElements(publicationSuite, 1);
            testCase.verifyEqual(excludedCount, 1);
            testCase.verifyEqual( ...
                string({routineSuite.Name}), ...
                string({shortSuite.Name}));
        end

        function publicationOptInPreservesEntireSuite(testCase)
            allBazziTests = matlab.unittest.TestSuite.fromClass( ...
                ?v2xsimregression.paper.bazzi2020blindspots. ...
                Bazzi2020BlindSpotTest);
            [selectedSuite, excludedCount] = ...
                v2xsimtest.execution.selectRegressionCampaigns( ...
                    allBazziTests, true);

            testCase.verifyEqual( ...
                string({selectedSuite.Name}), ...
                string({allBazziTests.Name}));
            testCase.verifyEqual(excludedCount, 0);
        end

        function runnerDefaultsToRoutineCampaignScope(testCase)
            runnerFile = fullfile( ...
                testCase.RepositoryRoot, "tests", ...
                "runCorrectnessSuite.m");
            source = fileread(runnerFile);

            defaultPattern = ...
                "options\.IncludePublicationCampaigns\s*" + ...
                "\(1,\s*1\)\s*logical\s*=\s*false";
            selectorCallPattern = ...
                "selectRegressionCampaigns\s*\(\s*\.\.\.\s*" + ...
                "regressionSuite\s*,\s*" + ...
                "options\.IncludePublicationCampaigns\s*\)";
            dependencyPattern = ...
                "options\.IncludePublicationCampaigns\s*&&\s*" + ...
                "\.\.\.\s*~options\.IncludeRegressionTests";

            testCase.verifyNotEmpty( ...
                regexp(source, defaultPattern, "once"));
            testCase.verifyNotEmpty( ...
                regexp(source, selectorCallPattern, "once"));
            testCase.verifyNotEmpty( ...
                regexp(source, dependencyPattern, "once"));
            testCase.verifySubstring( ...
                source, ...
                "PublicationCampaignsRequireRegressionTests");
        end
    end
end
