classdef AllocatorFactoryTest < matlab.unittest.TestCase
    %ALLOCATORFACTORYTEST Tests the sole runtime composition branch.

    methods (TestClassSetup)
        function addConstantsPath(testCase)
            projectRoot = fileparts(fileparts(fileparts(fileparts( ...
                mfilename("fullpath")))));
            initializationPath = fullfile( ...
                projectRoot,"old_src","MatFilesInit");
            originalPath = path;
            testCase.addTeardown(@() path(originalPath));
            addpath(initializationPath);
        end
    end

    methods (Test)
        function testFactoryCreatesEveryNamedAllocator(testCase)
            types = [ ...
                "ReuseDistance", ...
                "MaximumReuseDistance", ...
                "MinimumReusePower", ...
                "ThreeGppAutonomous", ...
                "RandomBenchmark", ...
                "OrderedBenchmark"];
            expectedClasses = [ ...
                "v2xsim.resource.ReuseDistanceAllocator", ...
                "v2xsim.resource.MaximumReuseDistanceAllocator", ...
                "v2xsim.resource.MinimumReusePowerAllocator", ...
                "v2xsim.resource.ThreeGppAutonomousAllocator", ...
                "v2xsim.resource.RandomBenchmarkAllocator", ...
                "v2xsim.resource.OrderedBenchmarkAllocator"];
            expectedContracts = [ ...
                "Centralized", ...
                "Centralized", ...
                "Centralized", ...
                "ThreeGpp", ...
                "Basic", ...
                "Centralized"];

            for index = 1:numel(types)
                [simParams,phyParams,appParams] = ...
                    testCase.createParameters(types(index));

                allocator = v2xsim.resource.createAllocator( ...
                    simParams,phyParams,appParams);

                testCase.verifyClass(allocator,expectedClasses(index));
                testCase.verifyEqual(allocator.Type,types(index));
                testCase.verifyEqual( ...
                    allocator.ContextContract, ...
                    expectedContracts(index));
                testCase.verifyEqual( ...
                    allocator.Grid.NetworkSliceId, ...
                    v2xsim.network.NetworkSliceId("global"));
            end
        end

        function testFactoryRejectsUnknownType(testCase)
            [simParams,phyParams,appParams] = ...
                testCase.createParameters("Unknown");

            testCase.verifyError( ...
                @() v2xsim.resource.createAllocator( ...
                    simParams,phyParams,appParams), ...
                "v2xsim:resource:UnknownAllocatorType");
        end

        function testFactoryRoundsValidatedDecimalCycleRatio(testCase)
            [simParams,phyParams,appParams] = ...
                testCase.createParameters("MaximumReuseDistance");
            simParams.Treassign = 0.3;
            appParams.allocationPeriod = 0.1;

            allocator = v2xsim.resource.createAllocator( ...
                simParams,phyParams,appParams);

            testCase.verifyEqual(allocator.ReassignmentCycleCount,3);
        end

        function testMetadataIncludesResolvedAllocatorOptions(testCase)
            [simParams,phyParams,appParams] = ...
                testCase.createParameters("ThreeGppAutonomous");
            simParams.minRandValueMode4 = 6;
            allocator = v2xsim.resource.createAllocator( ...
                simParams,phyParams,appParams);

            metadata = allocator.metadata();

            testCase.verifyEqual(metadata.RandomSeed,7);
            testCase.verifyEqual( ...
                metadata.Options.MinimumReselectionCounter,6);
            testCase.verifyEqual( ...
                metadata.Options.MaximumReselectionCounter,15);
            testCase.verifyEqual( ...
                metadata.Options.KeepResourceProbability,0.8);
            testCase.verifyEqual( ...
                metadata.Options.SensingThresholdWatts,1e-14);
        end
    end

    methods (Static, Access = private)
        function [simParams,phyParams,appParams] = ...
                createParameters(type)
            grid = v2xsim.resource.BRResourceGrid( ...
                v2xsim.network.NetworkSliceId("global"),2,2,0.001);
            simParams = struct( ...
                brResourceGrid=grid, ...
                resourceAllocationRandomSeed=7, ...
                resourceAllocationType=type, ...
                Treassign=0.1, ...
                knownShadowing=false, ...
                minRandValueMode4=-1, ...
                maxRandValueMode4=-1, ...
                probResKeep=0.8, ...
                ratioSelectedAutonomousMode=0.2, ...
                ratioSelectedL2=0.2, ...
                L2active=true, ...
                dynamicScheduling=false, ...
                resourceReEvaluation=false, ...
                reEvalAfterEmptyResource=false, ...
                powerThresholdAutonomous=1e-14, ...
                mode5G=constants.MODE_LTE);
            phyParams = struct( ...
                Rreuse=100, ...
                cv2xNumberOfReplicasMax=1);
            appParams = struct(allocationPeriod=0.1);
        end
    end
end
