classdef AllocationContextTest < matlab.unittest.TestCase
    %ALLOCATIONCONTEXTTEST Tests centralized and autonomous input contracts.

    methods (Test)
        function testBaseContextNormalizesRowKeysAndMasks(testCase)
            sliceId = testCase.createSliceId();
            context = v2xsim.resource.ResourceAllocationContext( ...
                sliceId, ["ue-1", "ue-2"], 0, [true, false], ...
                true(2, 4));

            testCase.verifyEqual(context.UeIds, ["ue-1"; "ue-2"]);
            testCase.verifyEqual(context.NewPacketMask, [true; false]);
            testCase.verifyEqual(context.CurrentSlot, 0);
        end

        function testBaseContextCarriesPerUeSelectionOrigins(testCase)
            context = v2xsim.resource.ResourceAllocationContext( ...
                testCase.createSliceId(),["ue-1";"ue-2"],8, ...
                false(2,1),true(2,4),[3;7]);

            testCase.verifyEqual(context.SelectionOriginSlot,[3;7]);
            testCase.verifyError( ...
                @() v2xsim.resource.ResourceAllocationContext( ...
                    testCase.createSliceId(),["ue-1";"ue-2"],8, ...
                    false(2,1),true(2,4),3), ...
                "v2xsim:resource:ContextRowCountMismatch");
        end

        function testBaseContextRejectsDuplicateAndMisalignedRows(testCase)
            sliceId = testCase.createSliceId();

            testCase.verifyError( ...
                @() v2xsim.resource.ResourceAllocationContext( ...
                    sliceId, ["ue-1", "ue-1"], 0, [true, false], ...
                    true(2, 4)), ...
                "v2xsim:resource:DuplicateUeId");
            testCase.verifyError( ...
                @() v2xsim.resource.ResourceAllocationContext( ...
                    sliceId, ["ue-1", "ue-2"], 0, true, true(2, 4)), ...
                "v2xsim:resource:ContextRowCountMismatch");
        end

        function testCentralizedContextAcceptsAlignedObservations(testCase)
            sliceId = testCase.createSliceId();
            context = v2xsim.resource.CentralizedAllocationContext( ...
                sliceId, ["ue-1"; "ue-2"], 4, [true; false], ...
                true(2, 4), [10; 20], [0, 5; 5, 0], ...
                [0, 4; 4, 0], [Inf, 1; 2, Inf], zeros(2));

            testCase.verifyEqual(context.X, [10; 20]);
            testCase.verifyEqual(context.EstimatedDistanceMeters(1, 2), 5);
            testCase.verifyEqual( ...
                context.ReceivedPowerWattsPerMHz(1, 1), Inf);
        end

        function testCentralizedContextRejectsMalformedMatrices(testCase)
            sliceId = testCase.createSliceId();
            constructor = @() ...
                v2xsim.resource.CentralizedAllocationContext( ...
                    sliceId, ["ue-1"; "ue-2"], 4, [true; false], ...
                    true(2, 4), [10; 20], zeros(2), zeros(2), ...
                    zeros(2, 1), zeros(2));

            testCase.verifyError(constructor, ...
                "v2xsim:resource:CentralizedContextSizeMismatch");
        end

        function testSensingSnapshotValidatesSliceAndShape(testCase)
            sliceId = testCase.createSliceId();
            snapshot = v2xsim.resource.SensingSnapshot( ...
                sliceId, ["ue-1"; "ue-2"], ...
                [0, Inf, 1, 2; 1, 2, 3, 4], false(2, 4));
            context = v2xsim.resource.AutonomousAllocationContext( ...
                sliceId, ["ue-1"; "ue-2"], 0, [true; false], ...
                true(2, 4), snapshot);

            testCase.verifyEqual(context.SensingSnapshot, snapshot);

            otherSlice = v2xsim.network.NetworkSliceId("other");
            testCase.verifyError( ...
                @() v2xsim.resource.AutonomousAllocationContext( ...
                    otherSlice, ["ue-1"; "ue-2"], 0, ...
                    [true; false], true(2, 4), snapshot), ...
                "v2xsim:resource:NetworkSliceMismatch");
        end

        function testSensingSnapshotRejectsNaNAndNegativeEnergy(testCase)
            sliceId = testCase.createSliceId();

            testCase.verifyError( ...
                @() v2xsim.resource.SensingSnapshot( ...
                    sliceId, "ue-1", NaN, false), ...
                "v2xsim:resource:InvalidSensedEnergy");
            testCase.verifyError( ...
                @() v2xsim.resource.SensingSnapshot( ...
                    sliceId, "ue-1", -1, false), ...
                "v2xsim:resource:InvalidSensedEnergy");
        end
    end

    methods (Access = private)
        function sliceId = createSliceId(~)
            sliceId = v2xsim.network.NetworkSliceId("global");
        end
    end
end
