classdef AllocatorFactoryTest < matlab.unittest.TestCase
    %ALLOCATORFACTORYTEST Tests compiled-plan allocator composition.

    methods (Test)
        function testFactoryMapsEveryRedesignedType(testCase)
            configuredTypes = [ ...
                "ReuseDistance", ...
                "MaximumReuseDistance", ...
                "MinimumReusePower", ...
                "SensingBased", ...
                "Random", ...
                "Ordered"];
            expectedClasses = [ ...
                "v2xsim.resource.ReuseDistanceAllocator", ...
                "v2xsim.resource.MaximumReuseDistanceAllocator", ...
                "v2xsim.resource.MinimumReusePowerAllocator", ...
                "v2xsim.resource.ThreeGppAutonomousAllocator", ...
                "v2xsim.resource.RandomBenchmarkAllocator", ...
                "v2xsim.resource.OrderedBenchmarkAllocator"];
            expectedAllocatorTypes = [ ...
                "ReuseDistance", ...
                "MaximumReuseDistance", ...
                "MinimumReusePower", ...
                "ThreeGppAutonomous", ...
                "RandomBenchmark", ...
                "OrderedBenchmark"];
            expectedContracts = [ ...
                "Centralized", ...
                "Centralized", ...
                "Centralized", ...
                "ThreeGpp", ...
                "Basic", ...
                "Centralized"];

            for index = 1:numel(configuredTypes)
                plan = testCase.createPlan(configuredTypes(index));
                grid = testCase.createGrid();

                allocator = v2xsim.resource.createAllocator(plan, grid);

                testCase.verifyClass(allocator, expectedClasses(index));
                testCase.verifyEqual( ...
                    allocator.Type, expectedAllocatorTypes(index));
                testCase.verifyEqual( ...
                    allocator.ContextContract, ...
                    expectedContracts(index));
                testCase.verifyEqual(allocator.Grid, grid);
            end
        end

        function testConfigurationRejectsUnknownTypeBeforeFactory(testCase)
            [data, provenance] = ...
                testCase.createConfigurationData("Unknown");
            testCase.verifyError( ...
                @() testCase.compile(data, provenance), ...
                "v2xsim:config:InvalidEnumValue");
        end

        function testFactoryRoundsValidatedDecimalCycleRatio(testCase)
            [data, provenance] = ...
                testCase.createConfigurationData( ...
                    "MaximumReuseDistance");
            data.ResourceAllocation.MaximumReuseDistance. ...
                ReassignmentIntervalSeconds = 0.3;
            data.Application.ResourceReservationIntervalSeconds = 0.1;
            plan = testCase.compile(data, provenance);

            allocator = v2xsim.resource.createAllocator( ...
                plan, testCase.createGrid());

            testCase.verifyEqual(allocator.ReassignmentCycleCount, 3);
        end

        function testFactoryRejectsNonintegralCycleRatio(testCase)
            [data, provenance] = ...
                testCase.createConfigurationData( ...
                    "MaximumReuseDistance");
            data.ResourceAllocation.MaximumReuseDistance. ...
                ReassignmentIntervalSeconds = 0.25;
            data.Application.ResourceReservationIntervalSeconds = 0.1;
            testCase.verifyError( ...
                @() testCase.compile(data, provenance), ...
                "v2xsim:config:NonIntegralInterval");
        end

        function testFactoryControlsMaximumReuseDiagnostics(testCase)
            [data, provenance] = ...
                testCase.createConfigurationData( ...
                    "MaximumReuseDistance");
            data.Outputs.ControllerDiagnostics.Enabled = true;
            plan = testCase.compile(data, provenance);

            allocator = v2xsim.resource.createAllocator( ...
                plan, testCase.createGrid());

            testCase.verifyTrue(allocator.DiagnosticsEnabled);
            testCase.verifyTrue( ...
                allocator.metadata().Options.DiagnosticsEnabled);
        end

        function testMinimumReusePowerUsesSelectedBranch(testCase)
            [data, provenance] = ...
                testCase.createConfigurationData( ...
                    "MinimumReusePower");
            data.ResourceAllocation.MinimumReusePower. ...
                KnownShadowingEnabled = true;
            plan = testCase.compile(data, provenance);

            allocator = v2xsim.resource.createAllocator( ...
                plan, testCase.createGrid());

            testCase.verifyTrue(allocator.KnownShadowingEnabled);
        end

        function testSensingMetadataUsesResolvedOptions(testCase)
            [data, provenance] = ...
                testCase.createConfigurationData("SensingBased");
            branch = data.ResourceAllocation.SensingBased;
            branch.ReselectionCounterMinimum = 6;
            branch.MaximumConsecutiveReservationIntervals = 5;
            branch.SensingThresholdDbm = -100;
            branch.ReevaluationEnabled = true;
            data.ResourceAllocation.SensingBased = branch;
            data.Radio = testCase.nrRadio(data.Radio);
            data.Radio.Sidelink.MaximumTransmissionCount = 2;
            plan = testCase.compile(data, provenance);

            allocator = v2xsim.resource.createAllocator( ...
                plan, testCase.createGrid());
            metadata = allocator.metadata();

            testCase.verifyEqual(metadata.RandomSeed, 7);
            testCase.verifyEqual(metadata.MaximumTransmissionCount, 2);
            testCase.verifyEqual( ...
                metadata.Options.MinimumReselectionCounter, 6);
            testCase.verifyEqual( ...
                metadata.Options.MaximumReselectionCounter, 15);
            testCase.verifyEqual( ...
                metadata.Options.KeepResourceProbability, 0.8);
            testCase.verifyEqual( ...
                metadata.Options. ...
                MaximumConsecutiveReservationIntervals, 5);
            testCase.verifyEqual( ...
                metadata.Options.SensingThresholdWatts, ...
                db2pow(-100 - 30), AbsTol=eps);
            testCase.verifyTrue(metadata.Options.IsNr);
            testCase.verifyTrue( ...
                metadata.Options.ResourceReevaluationEnabled);
        end

        function testDetectsNrSidelinkWithinCoexistence(testCase)
            [data, provenance] = ...
                testCase.createConfigurationData("SensingBased");
            data.Radio = testCase.coexistenceRadio(data.Radio);
            plan = testCase.compile(data, provenance);

            allocator = v2xsim.resource.createAllocator( ...
                plan, testCase.createGrid());

            testCase.verifyTrue(allocator.IsNr);
        end

        function testPreservesSensingThresholdValidation(testCase)
            [data, provenance] = ...
                testCase.createConfigurationData("SensingBased");
            data.ResourceAllocation.SensingBased. ...
                SensingThresholdDbm = -109;
            testCase.verifyError( ...
                @() testCase.compile(data, provenance), ...
                "v2xsim:config:InvalidSensingThreshold");
        end

        function testPreservesStrictCounterOrdering(testCase)
            [data, provenance] = ...
                testCase.createConfigurationData("SensingBased");
            data.ResourceAllocation.SensingBased. ...
                ReselectionCounterMinimum = 10;
            data.ResourceAllocation.SensingBased. ...
                ReselectionCounterMaximum = 10;
            testCase.verifyError( ...
                @() testCase.compile(data, provenance), ...
                "v2xsim:config:InvalidReselectionCounter");
        end

        function testWarnsForNonstandardKeepProbability(testCase)
            [data, provenance] = ...
                testCase.createConfigurationData("SensingBased");
            data.ResourceAllocation.SensingBased. ...
                KeepResourceProbability = 0.9;
            plan = testCase.compile(data, provenance);

            testCase.verifyWarning( ...
                @() v2xsim.resource.createAllocator( ...
                    plan, testCase.createGrid()), ...
                "v2xsim:resource:NonstandardKeepProbability");
        end

        function testDerivesReuseDistanceFromResolvedLinkBudget( ...
                testCase)
            [data, provenance] = ...
                testCase.createConfigurationData("ReuseDistance");
            data.Awareness.RangesMeters = 100;
            data.Radio.BandwidthMHz = 10;
            data.Radio.TransmitPowerDbm = 30;
            data.Radio.TransmitAntennaGainDb = 0;
            data.Radio.ReceiveAntennaGainDb = 0;
            data.Radio.ReceiverNoiseFigureDb = 0;
            data.Channel.PacketError.SidelinkLosThresholdDb = 0;
            data.Channel.PathLoss.Model = "SingleSlope";
            data.Channel.PathLoss.ReferenceLossAtOneMeterDb = 40;
            data.Channel.PathLoss.Exponent1 = 2;
            data.ResourceAllocation.ReuseDistance. ...
                ReuseMarginMeters = 10;
            plan = testCase.compile(data, provenance);

            allocator = v2xsim.resource.createAllocator( ...
                plan, testCase.createGrid());

            noiseWattsPerMHz = 1.38e-23 * 290 * 1e6;
            transmitWattsPerMHz = 10^((30 - 10 - 30) / 10);
            distanceBase = 1 - ...
                (noiseWattsPerMHz / transmitWattsPerMHz) * ...
                (10^(40 / 10) * 100^2);
            expectedDistance = ...
                max(100 + 100 / sqrt(distanceBase), 200) + 10;
            testCase.verifyEqual( ...
                allocator.ReuseDistanceMeters, ...
                expectedDistance, RelTol=1e-12);
        end

        function testRejectsUncompiledAutomaticSinrThreshold(testCase)
            [data, provenance] = ...
                testCase.createConfigurationData("ReuseDistance");
            data.Channel.PacketError = rmfield( ...
                data.Channel.PacketError, ...
                "SidelinkLosThresholdDb");
            plan = testCase.compile(data, provenance);

            testCase.verifyError( ...
                @() v2xsim.resource.createAllocator( ...
                    plan, testCase.createGrid()), ...
                "v2xsim:resource:ReuseDistanceLinkBudgetUnavailable");
        end

        function testRejectsUncompiledVariablePowerDensity(testCase)
            [data, provenance] = ...
                testCase.createConfigurationData("ReuseDistance");
            data.Radio.FixedPowerDensityEnabled = false;
            plan = testCase.compile(data, provenance);

            testCase.verifyError( ...
                @() v2xsim.resource.createAllocator( ...
                    plan, testCase.createGrid()), ...
                "v2xsim:resource:ReuseDistanceLinkBudgetUnavailable");
        end
    end

    methods (Static, Access = private)
        function plan = createPlan(type)
            [data, provenance] = ...
                v2xsimtest.resource.AllocatorFactoryTest. ...
                    createConfigurationData(type);
            plan = ...
                v2xsimtest.resource.AllocatorFactoryTest. ...
                    compile(data, provenance);
        end

        function [data, provenance] = createConfigurationData(type)
            configuration = v2xsim.config.defaults();
            data = configuration.Data;
            provenance = configuration.Provenance;

            data.Application.ResourceReservationIntervalSeconds = 0.1;
            data.Radio.Type = "LteV2X";
            data.Radio.Sidelink.MaximumTransmissionCount = 1;
            data.Channel.PacketError.SidelinkLosThresholdDb = 0;
            data.Outputs.ControllerDiagnostics.Enabled = false;

            allocation = struct( ...
                "Type", type, ...
                "RandomSeed", 7, ...
                "FullDuplex", struct( ...
                    "SelfInterferenceThresholdMultiplier", Inf));
            switch type
                case "ReuseDistance"
                    allocation.ReuseDistance = struct( ...
                        "PositionError95PercentileMeters", 0, ...
                        "PositionUpdateIntervalSeconds", 0.1, ...
                        "ReuseMarginMeters", 0, ...
                        "ReassignmentIntervalSeconds", 0.1);
                case "MaximumReuseDistance"
                    allocation.MaximumReuseDistance = struct( ...
                        "ReassignmentIntervalSeconds", 0.1);
                case "MinimumReusePower"
                    allocation.MinimumReusePower = struct( ...
                        "ReassignmentIntervalSeconds", 0.1, ...
                        "KnownShadowingEnabled", false);
                case "SensingBased"
                    allocation.SensingBased = struct( ...
                        "ReevaluationEnabled", false, ...
                        "ReevaluateAfterSkippedTransmissionEnabled", ...
                            false, ...
                        "ReselectEveryPacketEnabled", false, ...
                        "KeepResourceProbability", 0.8, ...
                        "MaximumConsecutiveReservationIntervals", Inf, ...
                        "MinimumCandidateFraction", 0.2, ...
                        "L2CandidateFraction", 0.2, ...
                        "L2RankingEnabled", true, ...
                        "AverageSensingEnabled", true, ...
                        "SensingWindowSeconds", 1, ...
                        "SensingThresholdDbm", -110, ...
                        "SelectionWindowEndMilliseconds", 100);
                case "Random"
                    allocation.Random = struct( ...
                        "SelectionWindowEndMilliseconds", 100);
                case "Ordered"
                    allocation.Ordered = struct();
            end
            data.ResourceAllocation = allocation;
        end

        function plan = compile(data, ~)
            provenance = ...
                v2xsim.config.internal.Operations.provenanceForData( ...
                    data, "Test");
            configuration = ...
                v2xsim.config.ResolvedConfiguration(data, provenance);
            plan = v2xsim.runtime.compile(configuration);
        end

        function grid = createGrid()
            grid = v2xsim.resource.BRResourceGrid( ...
                v2xsim.network.NetworkSliceId("global"), ...
                2, 2, 0.001);
        end

        function radio = nrRadio(radio)
            radio = rmfield(radio, "LteV2X");
            radio.Type = "NrV2X";
            radio.NrV2X = struct( ...
                "SubcarrierSpacingKilohertz", 15, ...
                "DmrsResourceElementCountPerSlot", 24, ...
                "Mcs", 7, ...
                "SciSymbolCount", 3, ...
                "SciResourceBlockCount", 10);
        end

        function radio = coexistenceRadio(~)
            patch = v2xsim.config.patch(struct( ...
                Radio=struct( ...
                    Type="Coexistence", ...
                    Coexistence=struct( ...
                        SidelinkType="NrV2X", ...
                        InterferenceModel="Independent"))));
            configuration = ...
                v2xsim.config.ConfigurationTemplate( ...
                    struct(SchemaVersion=1)).resolve(Patch=patch);
            radio = configuration.Data.Radio;
        end
    end
end
