classdef ConcreteAllocatorTest < matlab.unittest.TestCase
    %CONCRETEALLOCATORTEST Tests concrete allocator lifecycle behavior.

    methods (Test)
        function testScheduledCentralizedAllocatorsWaitForBoundary(testCase)
            allocators = { ...
                v2xsim.resource.ReuseDistanceAllocator( ...
                    testCase.createGrid(),1,1,5), ...
                v2xsim.resource.MaximumReuseDistanceAllocator( ...
                    testCase.createGrid(),2,1), ...
                v2xsim.resource.MinimumReusePowerAllocator( ...
                    testCase.createGrid(),3,1,false)};

            for index = 1:numel(allocators)
                allocator = allocators{index}.synchronizeUes( ...
                    ["ue-1";"ue-2"]);
                context = testCase.createCentralizedContext( ...
                    allocator.Grid,0,[10;20]);
                [allocator,~] = allocator.initialize(context);
                [allocator,result] = allocator.step(context);
                testCase.verifyEmpty(result.DecisionUeIds);
                testCase.verifyTrue( ...
                    all(isnan(allocator.Assignments.ResourceIds),"all"));

                boundaryContext = testCase.createCentralizedContext( ...
                    allocator.Grid,1,[10;20]);
                [allocator,result] = allocator.step(boundaryContext);
                testCase.verifyEqual( ...
                    sort(result.DecisionUeIds),["ue-1";"ue-2"]);
                testCase.verifyTrue(all(isfinite( ...
                    allocator.Assignments.ResourceIds),"all"));
            end
        end

        function testOrderedBenchmarkUsesLongitudinalOrder(testCase)
            grid = testCase.createGrid();
            allocator = v2xsim.resource.OrderedBenchmarkAllocator(grid,1);
            allocator = allocator.synchronizeUes(["ue-1";"ue-2"]);
            initialContext = testCase.createCentralizedContext( ...
                grid,0,[20;10]);
            [allocator,~] = allocator.initialize(initialContext);
            boundaryContext = testCase.createCentralizedContext( ...
                grid,1,[20;10]);

            [allocator,result] = allocator.step(boundaryContext);

            testCase.verifyEqual( ...
                allocator.Assignments.ResourceIds,[3;1]);
            testCase.verifyEqual( ...
                sort(result.DecisionUeIds),["ue-1";"ue-2"]);
        end

        function testMaximumReuseUsesEstimateAndShadowDoesNotMutate( ...
                testCase)
            grid = v2xsim.resource.BRResourceGrid( ...
                v2xsim.network.NetworkSliceId("global"),2,1,0.001);
            ueIds = ["a";"b";"c"];
            apparent = [0 1 2;1 0 3;2 3 0];
            truth = [0 3 2;3 0 1;2 1 0];
            liveAllocator = ...
                v2xsim.resource.MaximumReuseDistanceAllocator( ...
                    grid,5,1,DiagnosticsEnabled=true). ...
                    synchronizeUes(ueIds);
            estimateControl = ...
                v2xsim.resource.MaximumReuseDistanceAllocator( ...
                    grid,5,1,DiagnosticsEnabled=true). ...
                    synchronizeUes(ueIds);
            initialLive = testCase.createThreeUeCentralizedContext( ...
                grid,ueIds,0,apparent,truth);
            initialControl = testCase.createThreeUeCentralizedContext( ...
                grid,ueIds,0,apparent,apparent);
            [liveAllocator,~] = liveAllocator.initialize(initialLive);
            [estimateControl,~] = ...
                estimateControl.initialize(initialControl);

            liveContext = testCase.createThreeUeCentralizedContext( ...
                grid,ueIds,1,apparent,truth);
            controlContext = testCase.createThreeUeCentralizedContext( ...
                grid,ueIds,1,apparent,apparent);
            [liveAllocator,liveResult] = ...
                liveAllocator.step(liveContext);
            [estimateControl,controlResult] = ...
                estimateControl.step(controlContext);

            testCase.verifyEqual( ...
                liveResult.Assignments,controlResult.Assignments);
            testCase.verifyNotEqual( ...
                liveResult.Assignments.ResourceIds, ...
                liveResult.Diagnostics. ...
                    OracleAssignments.ResourceIds);

            nextLive = testCase.createThreeUeCentralizedContext( ...
                grid,ueIds,3,apparent,truth);
            nextControl = testCase.createThreeUeCentralizedContext( ...
                grid,ueIds,3,apparent,apparent);
            [liveAllocator,nextLiveResult] = ...
                liveAllocator.step(nextLive);
            [estimateControl,nextControlResult] = ...
                estimateControl.step(nextControl);
            testCase.verifyEqual( ...
                nextLiveResult.Assignments, ...
                nextControlResult.Assignments);
            testCase.verifyEqual( ...
                liveAllocator.Assignments, ...
                estimateControl.Assignments);
        end

        function testRandomBenchmarkAllocatesOnlyForNewPackets(testCase)
            grid = testCase.createGrid();
            allocator = v2xsim.resource.RandomBenchmarkAllocator(grid,9,2);
            allocator = allocator.synchronizeUes(["ue-1";"ue-2"]);
            noPacketContext = v2xsim.resource.ResourceAllocationContext( ...
                grid.NetworkSliceId,["ue-1";"ue-2"],0, ...
                false(2,1),true(2,grid.ResourceCount));
            [allocator,~] = allocator.initialize(noPacketContext);
            eligibility = logical([0 1 0 0;1 1 1 1]);
            packetContext = v2xsim.resource.ResourceAllocationContext( ...
                grid.NetworkSliceId,["ue-1";"ue-2"],1, ...
                [true;false],eligibility);

            [allocator,result] = allocator.step(packetContext);

            testCase.verifyEqual( ...
                allocator.Assignments.ResourceIds(1,1),2);
            testCase.verifyTrue( ...
                isnan(allocator.Assignments.ResourceIds(1,2)));
            testCase.verifyTrue(all(isnan( ...
                allocator.Assignments.ResourceIds(2,:))));
            testCase.verifyEqual(result.DecisionUeIds,"ue-1");
        end

        function testRandomBenchmarkOrdersReplicasAcrossGridWrap(testCase)
            grid = testCase.createGrid();
            allocator = v2xsim.resource.RandomBenchmarkAllocator(grid,9,2);
            allocator = allocator.synchronizeUes("ue-1");
            initialContext = v2xsim.resource.ResourceAllocationContext( ...
                grid.NetworkSliceId,"ue-1",0,false, ...
                true(1,grid.ResourceCount),0);
            [allocator,~] = allocator.initialize(initialContext);
            eligibility = logical([1 0 1 0]);
            packetContext = v2xsim.resource.ResourceAllocationContext( ...
                grid.NetworkSliceId,"ue-1",0,true,eligibility,0);

            [allocator,~] = allocator.step(packetContext);

            testCase.verifyEqual( ...
                allocator.Assignments.ResourceIds,[3 1]);
        end

        function testRandomBenchmarkHarqOccurrencesStrictlyIncrease( ...
                testCase)
            grid = testCase.createGrid();
            allocator = ...
                v2xsim.resource.RandomBenchmarkAllocator(grid,17,2);
            allocator = allocator.synchronizeUes("ue-1");
            initialContext = v2xsim.resource.ResourceAllocationContext( ...
                grid.NetworkSliceId,"ue-1",0,false, ...
                true(1,grid.ResourceCount),0);
            [allocator,~] = allocator.initialize(initialContext);
            packetContext = v2xsim.resource.ResourceAllocationContext( ...
                grid.NetworkSliceId,"ue-1",0,true, ...
                true(1,grid.ResourceCount),0);

            [allocator,~] = allocator.step(packetContext);

            resources = allocator.Assignments.ResourceIds;
            resourceSlots = ceil( ...
                resources / grid.NumberFrequencyResources);
            futureSlots = resourceSlots;
            futureSlots(resourceSlots <= grid.periodicSlot(0)) = ...
                futureSlots(resourceSlots <= grid.periodicSlot(0)) + ...
                grid.NumberTimeSlots;
            testCase.verifyGreaterThan(diff(futureSlots),0);
        end

        function testThreeGppInitializationHonorsEligibility(testCase)
            grid = testCase.createGrid();
            allocator = testCase.createThreeGppAllocator(grid);
            allocator = allocator.synchronizeUes(["ue-1";"ue-2"]);
            eligibility = logical([0 1 0 0;0 0 1 0]);
            context = testCase.createThreeGppContext( ...
                grid,0,false(2,1),eligibility);

            [allocator,result] = allocator.initialize(context);

            testCase.verifyEqual( ...
                allocator.Assignments.ResourceIds,[2;3]);
            testCase.verifyEqual( ...
                sort(result.DecisionUeIds),["ue-1";"ue-2"]);
            testCase.verifyEqual(height(result.Reservations),2);
        end

        function testThreeGppRejectsInfiniteUnreservedEnergy(testCase)
            grid = testCase.createGrid();
            allocator = testCase.createThreeGppAllocator(grid);
            allocator = allocator.synchronizeUes("ue-1");
            snapshot = v2xsim.resource.SensingSnapshot( ...
                grid.NetworkSliceId,"ue-1", ...
                [Inf 0 0 0],false(1,grid.ResourceCount));
            context = v2xsim.resource.ThreeGppAllocationContext( ...
                grid.NetworkSliceId,"ue-1",0,false, ...
                logical([1 0 0 0]),snapshot, ...
                false,false,false,1,0);

            [allocator,result] = allocator.initialize(context);

            testCase.verifyTrue( ...
                isnan(allocator.Assignments.ResourceIds));
            testCase.verifyEqual(result.BlockedUeIds,"ue-1");
        end

        function testThreeGppExcludesInfiniteEnergyFromCandidateFloor( ...
                testCase)
            grid = v2xsim.resource.BRResourceGrid( ...
                v2xsim.network.NetworkSliceId("global"),10,1,0.001);
            allocator = testCase.createThreeGppAllocator(grid);
            allocator = allocator.synchronizeUes("ue-1");
            snapshot = v2xsim.resource.SensingSnapshot( ...
                grid.NetworkSliceId,"ue-1", ...
                [0 Inf(1,9)],false(1,grid.ResourceCount));
            context = v2xsim.resource.ThreeGppAllocationContext( ...
                grid.NetworkSliceId,"ue-1",0,false, ...
                true(1,grid.ResourceCount),snapshot, ...
                false,false,false,1,0);

            [allocator,result] = allocator.initialize(context);

            testCase.verifyEqual( ...
                allocator.Assignments.ResourceIds,1);
            testCase.verifyEmpty(result.BlockedUeIds);
        end

        function testThreeGppOrdersInitialHarqFromPacketOrigin(testCase)
            grid = testCase.createGrid();
            allocator = testCase.createThreeGppAllocator(grid,2);
            allocator = allocator.synchronizeUes("ue-1");
            snapshot = v2xsim.resource.SensingSnapshot( ...
                grid.NetworkSliceId,"ue-1", ...
                zeros(1,grid.ResourceCount), ...
                false(1,grid.ResourceCount));
            context = v2xsim.resource.ThreeGppAllocationContext( ...
                grid.NetworkSliceId,"ue-1",0,false, ...
                logical([1 0 1 0]),snapshot,false,false,false,2,0);

            [allocator,~] = allocator.initialize(context);

            testCase.verifyEqual( ...
                allocator.Assignments.ResourceIds,[3 1]);
        end

        function testThreeGppReordersHarqForNewPacketOrigin(testCase)
            grid = v2xsim.resource.BRResourceGrid( ...
                v2xsim.network.NetworkSliceId("global"),4,1,0.001);
            allocator = testCase.createThreeGppAllocator(grid,2);
            allocator = allocator.synchronizeUes("ue-1");
            snapshot = v2xsim.resource.SensingSnapshot( ...
                grid.NetworkSliceId,"ue-1",zeros(1,4),false(1,4));
            initialContext = v2xsim.resource.ThreeGppAllocationContext( ...
                grid.NetworkSliceId,"ue-1",0,false, ...
                logical([0 1 0 1]),snapshot,false,false,false,2,0);
            [allocator,~] = allocator.initialize(initialContext);
            testCase.verifyEqual( ...
                allocator.Assignments.ResourceIds,[2 4]);

            newPacketContext = ...
                v2xsim.resource.ThreeGppAllocationContext( ...
                    grid.NetworkSliceId,"ue-1",2,true, ...
                    logical([0 1 0 1]),snapshot,false,false,true,2,2);
            [allocator,result] = allocator.step(newPacketContext);

            testCase.verifyEqual( ...
                allocator.Assignments.ResourceIds,[4 2]);
            testCase.verifyEqual(result.ReassignedUeIds,"ue-1");
        end

        function testThreeGppPreallocatesConfiguredHarqColumns(testCase)
            grid = v2xsim.resource.BRResourceGrid( ...
                v2xsim.network.NetworkSliceId("global"),4,1,0.001);
            allocator = testCase.createThreeGppAllocator(grid,2);
            allocator = allocator.synchronizeUes("ue-1");
            snapshot = v2xsim.resource.SensingSnapshot( ...
                grid.NetworkSliceId,"ue-1",zeros(1,4),false(1,4));
            oneAttemptContext = ...
                v2xsim.resource.ThreeGppAllocationContext( ...
                    grid.NetworkSliceId,"ue-1",0,false, ...
                    logical([0 1 0 1]),snapshot, ...
                    false,false,false,1,0);

            [allocator,~] = allocator.initialize(oneAttemptContext);

            testCase.verifyEqual( ...
                allocator.Assignments.ResourceIds,[2 4]);

            twoAttemptContext = ...
                v2xsim.resource.ThreeGppAllocationContext( ...
                    grid.NetworkSliceId,"ue-1",0,true, ...
                    logical([0 1 0 1]),snapshot, ...
                    false,false,true,2,0);
            [allocator,result] = allocator.step(twoAttemptContext);
            testCase.verifyEmpty(result.DecisionUeIds);
            testCase.verifyEqual( ...
                allocator.Assignments.ResourceIds,[2 4]);
        end

        function testThreeGppReevaluationKeepsAcceptedPair(testCase)
            [allocator,snapshot] = ...
                testCase.initializeReevaluationPair();
            grid = allocator.Grid;
            context = v2xsim.resource.ThreeGppAllocationContext( ...
                grid.NetworkSliceId,"ue-1",0,false, ...
                logical([0 0 1 1 1]),snapshot, ...
                false,false,true,2,0);

            [allocator,result] = allocator.step(context);

            testCase.verifyEqual( ...
                allocator.Assignments.ResourceIds,[4 5]);
            testCase.verifyEqual(result.DecisionUeIds,"ue-1");
            testCase.verifyEmpty(result.ReassignedUeIds);
        end

        function testThreeGppReevaluationReplacesOnlyRejectedMember( ...
                testCase)
            [allocator,snapshot] = ...
                testCase.initializeReevaluationPair();
            grid = allocator.Grid;
            context = v2xsim.resource.ThreeGppAllocationContext( ...
                grid.NetworkSliceId,"ue-1",0,false, ...
                logical([0 0 1 1 0]),snapshot, ...
                false,false,true,2,0);

            [allocator,result] = allocator.step(context);

            testCase.verifyEqual( ...
                allocator.Assignments.ResourceIds,[3 4]);
            testCase.verifyEqual(result.ReassignedUeIds,"ue-1");
        end

        function testThreeGppFailedReevaluationPreservesAssignment( ...
                testCase)
            [allocator,snapshot] = ...
                testCase.initializeReevaluationPair();
            grid = allocator.Grid;
            context = v2xsim.resource.ThreeGppAllocationContext( ...
                grid.NetworkSliceId,"ue-1",0,false, ...
                false(1,grid.ResourceCount),snapshot, ...
                false,false,true,2,0);

            [allocator,result] = allocator.step(context);

            testCase.verifyEqual( ...
                allocator.Assignments.ResourceIds,[4 5]);
            testCase.verifyEmpty(result.ReassignedUeIds);
            testCase.verifyEmpty(result.BlockedUeIds);
        end

        function testThreeGppRejectsTransmissionCountAboveMaximum( ...
                testCase)
            grid = testCase.createGrid();
            allocator = testCase.createThreeGppAllocator(grid,1);
            allocator = allocator.synchronizeUes("ue-1");
            snapshot = v2xsim.resource.SensingSnapshot( ...
                grid.NetworkSliceId,"ue-1", ...
                zeros(1,grid.ResourceCount), ...
                false(1,grid.ResourceCount));
            context = v2xsim.resource.ThreeGppAllocationContext( ...
                grid.NetworkSliceId,"ue-1",0,false, ...
                true(1,grid.ResourceCount),snapshot, ...
                false,false,false,2,0);

            testCase.verifyError( ...
                @() allocator.initialize(context), ...
                "v2xsim:resource:TransmissionCountMismatch");
        end

        function testCounterReselectionDoesNotUseReevaluationRetention( ...
                testCase)
            grid = v2xsim.resource.BRResourceGrid( ...
                v2xsim.network.NetworkSliceId("global"),5,1,0.001);
            allocator = v2xsim.resource.ThreeGppAutonomousAllocator( ...
                grid,3,1, ...
                MinimumReselectionCounter=1, ...
                MaximumReselectionCounter=1, ...
                KeepResourceProbability=0, ...
                MinimumCandidateFraction=0.2, ...
                L2CandidateFraction=1, ...
                L2RankingEnabled=false, ...
                DynamicSchedulingEnabled=false, ...
                ResourceReevaluationEnabled=true, ...
                ReevaluateAfterSkippedTransmissionEnabled=false, ...
                SensingThresholdWatts=1e-10, ...
                IsNr=true);
            allocator = allocator.synchronizeUes("ue-1");
            snapshot = v2xsim.resource.SensingSnapshot( ...
                grid.NetworkSliceId,"ue-1",zeros(1,5),false(1,5));
            initialContext = v2xsim.resource.ThreeGppAllocationContext( ...
                grid.NetworkSliceId,"ue-1",0,false, ...
                logical([0 0 0 1 0]),snapshot,false,false,false,1,0);
            [allocator,~] = allocator.initialize(initialContext);
            reselectionContext = ...
                v2xsim.resource.ThreeGppAllocationContext( ...
                    grid.NetworkSliceId,"ue-1",0,true, ...
                    logical([1 0 0 1 0]),snapshot,true,false,true,1,0);

            [allocator,~] = allocator.step(reselectionContext);

            testCase.verifyEqual(allocator.Assignments.ResourceIds,1);
        end

        function testThreeGppRejectsGenericAutonomousContext(testCase)
            grid = testCase.createGrid();
            allocator = testCase.createThreeGppAllocator(grid);
            allocator = allocator.synchronizeUes("ue-1");
            snapshot = v2xsim.resource.SensingSnapshot( ...
                grid.NetworkSliceId,"ue-1", ...
                zeros(1,grid.ResourceCount), ...
                false(1,grid.ResourceCount));
            context = v2xsim.resource.AutonomousAllocationContext( ...
                grid.NetworkSliceId,"ue-1",0,false, ...
                true(1,grid.ResourceCount),snapshot);

            testCase.verifyError( ...
                @() allocator.initialize(context), ...
                "v2xsim:resource:InvalidAllocationContextType");
        end

        function testThreeGppDirectOptionsEnforceConfigurationContract( ...
                testCase)
            grid = testCase.createGrid();

            testCase.verifyError( ...
                @() testCase.createCustomThreeGppAllocator( ...
                    grid,MinimumCandidateFraction=0.1), ...
                "v2xsim:resource:InvalidAllocatorOption");
            testCase.verifyError( ...
                @() testCase.createCustomThreeGppAllocator( ...
                    grid,DynamicSchedulingEnabled=true, ...
                    KeepResourceProbability=0.5), ...
                "v2xsim:resource:InvalidKeepProbability");
            testCase.verifyError( ...
                @() testCase.createCustomThreeGppAllocator( ...
                    grid,ResourceReevaluationEnabled=true,IsNr=false), ...
                "v2xsim:resource:NrOptionForLte");
            testCase.verifyError( ...
                @() testCase.createCustomThreeGppAllocator( ...
                    grid, ...
                    ReevaluateAfterSkippedTransmissionEnabled=true), ...
                "v2xsim:resource:InvalidReevaluationOptions");
        end
    end

    methods (Static, Access = private)
        function grid = createGrid()
            grid = v2xsim.resource.BRResourceGrid( ...
                v2xsim.network.NetworkSliceId("global"),2,2,0.001);
        end

        function context = createCentralizedContext(grid,currentSlot,x)
            ueIds = ["ue-1";"ue-2"];
            distance = [0 10;10 0];
            power = [0 1;1 0];
            context = v2xsim.resource.CentralizedAllocationContext( ...
                grid.NetworkSliceId,ueIds,currentSlot,false(2,1), ...
                true(2,grid.ResourceCount),x,distance,distance, ...
                power,zeros(2));
        end

        function context = createThreeUeCentralizedContext( ...
                grid,ueIds,currentSlot,estimatedDistance,trueDistance)
            power = ones(3);
            power(1:4:end) = 0;
            context = v2xsim.resource.CentralizedAllocationContext( ...
                grid.NetworkSliceId,ueIds,currentSlot,false(3,1), ...
                true(3,grid.ResourceCount),(1:3).', ...
                estimatedDistance,trueDistance,power,zeros(3));
        end

        function allocator = createThreeGppAllocator( ...
                grid,maximumTransmissionCount)
            arguments (Input)
                grid (1,1) v2xsim.resource.BRResourceGrid
                maximumTransmissionCount (1,1) double = 1
            end
            allocator = v2xsim.resource.ThreeGppAutonomousAllocator( ...
                grid,4,maximumTransmissionCount, ...
                MinimumReselectionCounter=2, ...
                MaximumReselectionCounter=3, ...
                KeepResourceProbability=0, ...
                MinimumCandidateFraction=0.2, ...
                L2CandidateFraction=0.2, ...
                L2RankingEnabled=false, ...
                DynamicSchedulingEnabled=false, ...
                ResourceReevaluationEnabled=false, ...
                ReevaluateAfterSkippedTransmissionEnabled=false, ...
                SensingThresholdWatts=1e-10, ...
                IsNr=false);
        end

        function context = createThreeGppContext( ...
                grid,currentSlot,newPackets,eligibility)
            ueIds = ["ue-1";"ue-2"];
            snapshot = v2xsim.resource.SensingSnapshot( ...
                grid.NetworkSliceId,ueIds, ...
                zeros(2,grid.ResourceCount), ...
                false(2,grid.ResourceCount));
            context = v2xsim.resource.ThreeGppAllocationContext( ...
                grid.NetworkSliceId,ueIds,currentSlot,newPackets, ...
                eligibility,snapshot,false(2,1),false(2,1), ...
                false(2,1),ones(2,1));
        end

        function [allocator,snapshot] = initializeReevaluationPair()
            grid = v2xsim.resource.BRResourceGrid( ...
                v2xsim.network.NetworkSliceId("global"),5,1,0.001);
            allocator = v2xsim.resource.ThreeGppAutonomousAllocator( ...
                grid,1,2, ...
                MinimumReselectionCounter=2, ...
                MaximumReselectionCounter=3, ...
                KeepResourceProbability=0, ...
                MinimumCandidateFraction=0.2, ...
                L2CandidateFraction=1, ...
                L2RankingEnabled=false, ...
                DynamicSchedulingEnabled=false, ...
                ResourceReevaluationEnabled=true, ...
                ReevaluateAfterSkippedTransmissionEnabled=false, ...
                SensingThresholdWatts=1e-10, ...
                IsNr=true);
            allocator = allocator.synchronizeUes("ue-1");
            snapshot = v2xsim.resource.SensingSnapshot( ...
                grid.NetworkSliceId,"ue-1",zeros(1,5),false(1,5));
            initialContext = v2xsim.resource.ThreeGppAllocationContext( ...
                grid.NetworkSliceId,"ue-1",0,false, ...
                logical([0 0 0 1 1]),snapshot, ...
                false,false,false,2,0);
            [allocator,~] = allocator.initialize(initialContext);
        end

        function allocator = createCustomThreeGppAllocator(grid,options)
            arguments (Input)
                grid (1,1) v2xsim.resource.BRResourceGrid
                options.MinimumCandidateFraction (1,1) double = 0.2
                options.KeepResourceProbability (1,1) double = 0
                options.DynamicSchedulingEnabled (1,1) logical = false
                options.ResourceReevaluationEnabled (1,1) logical = false
                options.ReevaluateAfterSkippedTransmissionEnabled ...
                    (1,1) logical = false
                options.IsNr (1,1) logical = true
            end
            reevaluateAfterSkipped = ...
                options.ReevaluateAfterSkippedTransmissionEnabled;
            allocator = v2xsim.resource.ThreeGppAutonomousAllocator( ...
                grid,1,1, ...
                MinimumReselectionCounter=2, ...
                MaximumReselectionCounter=3, ...
                KeepResourceProbability= ...
                    options.KeepResourceProbability, ...
                MinimumCandidateFraction= ...
                    options.MinimumCandidateFraction, ...
                L2CandidateFraction=0.2, ...
                L2RankingEnabled=false, ...
                DynamicSchedulingEnabled= ...
                    options.DynamicSchedulingEnabled, ...
                ResourceReevaluationEnabled= ...
                    options.ResourceReevaluationEnabled, ...
                ReevaluateAfterSkippedTransmissionEnabled= ...
                    reevaluateAfterSkipped, ...
                SensingThresholdWatts=1e-10, ...
                IsNr=options.IsNr);
        end
    end
end
