classdef ResourcePressureTest < matlab.unittest.TestCase
    %RESOURCEPRESSURETEST Tests slice-local artificial BR eligibility.

    methods (Test)
        function testConfigurationDefaultsAndRejectsOutOfRangePercent( ...
                testCase)
            configuration = v2xsim.config.defaults();
            pressure = configuration.Data.Radio.Sidelink.ResourcePool. ...
                ResourcePressure;

            testCase.verifyEqual(pressure.TimeAvailabilityPercent,100);
            testCase.verifyEqual( ...
                pressure.FrequencyAvailabilityPercent,100);
            testCase.verifyError( ...
                @() v2xsim.config.ConfigurationTemplate(struct( ...
                SchemaVersion=1,Radio=struct(Sidelink=struct( ...
                ResourcePool=struct(ResourcePressure=struct( ...
                TimeAvailabilityPercent=0)))))), ...
                "v2xsim:config:ValueOutOfRange");
        end

        function testBuildsEvenlyDistributedCartesianMask(testCase)
            grid = testCase.createGrid();
            pressure = v2xsim.resource.ResourcePressure(grid,50,60);

            testCase.verifyEqual( ...
                pressure.TimeSlotMask,logical([0 1 0 1]));
            testCase.verifyEqual( ...
                pressure.FrequencyResourceMask,logical([0 1 0 1 1]));
            testCase.verifyEqual(pressure.AvailableTimeSlotCount,2);
            testCase.verifyEqual( ...
                pressure.AvailableFrequencyResourceCount,3);
            testCase.verifyEqual(pressure.AvailableResourceCount,6);
            testCase.verifyEqual( ...
                pressure.EffectiveResourceAvailabilityPercent,30);
            testCase.verifyEqual(pressure.ResourceMask,logical([ ...
                0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 0 1 1]));
            testCase.verifyEqual(pressure.eligibilityMask(2), ...
                repmat(pressure.ResourceMask,2,1));
        end

        function testPolicyRetainsSliceIdentity(testCase)
            grid = v2xsim.resource.BRResourceGrid( ...
                v2xsim.network.NetworkSliceId("slice-a"),4,5,0.001);
            pressure = v2xsim.resource.ResourcePressure(grid,100,100);

            testCase.verifyEqual(pressure.NetworkSliceId,grid.NetworkSliceId);
            testCase.verifyTrue(all(pressure.ResourceMask));
            testCase.verifyEqual( ...
                pressure.metadata().NetworkSliceId,"slice-a");
        end

        function testResourceAlgorithmsHonorEligibility(testCase)
            grid = testCase.createGrid();
            pressure = v2xsim.resource.ResourcePressure(grid,50,60);
            eligibility = pressure.eligibilityMask(3);
            stream = RandStream("mt19937ar",Seed=7);

            [ordered,~] = v2xsim.resource.algorithm.assignByPositionOrder( ...
                [1;2;3],[4 5],eligibility);
            [reuse,~] = v2xsim.resource.algorithm.assignByReuseDistance( ...
                nan(3,1),(1:3).',zeros(3),grid.ResourceCount,0, ...
                stream,eligibility);
            [maximum,~] = v2xsim.resource.algorithm. ...
                assignByMaximumReuseDistance( ...
                nan(3,1),(1:3).',ones(3) - eye(3),[4 5],stream, ...
                EligibilityMask=eligibility);
            [minimum,~] = v2xsim.resource.algorithm. ...
                assignByMinimumReceivedPower( ...
                nan(3,1),(1:3).',zeros(3),zeros(3),false,[4 5], ...
                stream,eligibility);
            [random,~,blocked] = ...
                v2xsim.resource.algorithm.assignRandomResources( ...
                eligibility,1,stream,grid.NumberFrequencyResources);

            testCase.verifyEmpty(blocked);
            testCase.verifyTrue(all(pressure.ResourceMask(ordered)));
            testCase.verifyTrue(all(pressure.ResourceMask(reuse)));
            testCase.verifyTrue(all(pressure.ResourceMask(maximum)));
            testCase.verifyTrue(all(pressure.ResourceMask(minimum)));
            testCase.verifyTrue(all(pressure.ResourceMask(random)));
        end

        function testThreeGppInitializationHonorsPressureAndHarq(testCase)
            grid = testCase.createGrid();
            pressure = v2xsim.resource.ResourcePressure(grid,50,60);
            ueIds = ["ue-1";"ue-2"];
            eligibility = pressure.eligibilityMask(numel(ueIds));
            allocator = v2xsim.resource.ThreeGppAutonomousAllocator( ...
                grid,4,2, ...
                MinimumReselectionCounter=2, ...
                MaximumReselectionCounter=3, ...
                KeepResourceProbability=0, ...
                MinimumCandidateFraction=0.2, ...
                L2CandidateFraction=0.2, ...
                L2RankingEnabled=false, ...
                DynamicSchedulingEnabled=false, ...
                ResourceReevaluationEnabled=false, ...
                ReevaluateAfterSkippedTransmissionEnabled=false, ...
                SensingThresholdWatts=1e-10, ...
                IsNr=false);
            allocator = allocator.synchronizeUes(ueIds);
            snapshot = v2xsim.resource.SensingSnapshot( ...
                grid.NetworkSliceId,ueIds, ...
                zeros(numel(ueIds),grid.ResourceCount), ...
                false(numel(ueIds),grid.ResourceCount));
            context = v2xsim.resource.ThreeGppAllocationContext( ...
                grid.NetworkSliceId,ueIds,0,false(2,1),eligibility, ...
                snapshot,false(2,1),false(2,1),false(2,1), ...
                2 * ones(2,1));

            [~,result] = allocator.initialize(context);
            assigned = result.Assignments.ResourceIds;
            assigned = assigned(~isnan(assigned));
            testCase.verifyTrue(all(pressure.ResourceMask(assigned)));
            testCase.verifyTrue(all(pressure.ResourceMask( ...
                result.Reservations.ResourceId)));
        end
    end

    methods (Access = private)
        function grid = createGrid(~)
            grid = v2xsim.resource.BRResourceGrid( ...
                v2xsim.network.NetworkSliceId("global"),4,5,0.001);
        end
    end
end
