classdef ThreeGppRetentionCapTest < matlab.unittest.TestCase
    %THREEGPPRETENTIONCAPTEST Tests bounded SPS resource retention.

    methods (Test)
        function testDefaultAndExplicitInfinityHaveIdenticalSequence( ...
                testCase)
            grid = testCase.createGrid(4);
            implicit = testCase.createAllocator( ...
                grid,KeepResourceProbability=1,OmitCap=true);
            explicit = testCase.createAllocator( ...
                grid,KeepResourceProbability=1, ...
                MaximumConsecutiveReservationIntervals=Inf);

            [implicit,explicit] = testCase.initializePair( ...
                implicit,explicit,true(1,grid.ResourceCount));
            for stepIndex = 1:8
                context = testCase.createContext( ...
                    grid,"ue-1",stepIndex,true, ...
                    true(1,grid.ResourceCount),true,false,false);
                [implicit,implicitResult] = implicit.step(context);
                [explicit,explicitResult] = explicit.step(context);
                testCase.verifyEqual( ...
                    implicit.Assignments,explicit.Assignments);
                testCase.verifyEqual( ...
                    implicitResult.DecisionUeIds, ...
                    explicitResult.DecisionUeIds);
            end
        end

        function testDefaultMatchesPreCapGoldenTrace(testCase)
            grid = testCase.createGrid(4);
            allocator = testCase.createAllocator( ...
                grid, KeepResourceProbability=0.8, OmitCap=true);
            allocator = allocator.synchronizeUes("ue-1");
            initial = testCase.createContext( ...
                grid, "ue-1", 0, false, true(1, grid.ResourceCount), ...
                false, false, false);
            [allocator, ~] = allocator.initialize(initial);

            actualTrace = zeros(30, 3);
            for stepIndex = 1:30
                context = testCase.createContext( ...
                    grid, "ue-1", stepIndex, true, ...
                    true(1, grid.ResourceCount), true, false, false);
                [allocator, result] = allocator.step(context);
                actualTrace(stepIndex, :) = [ ...
                    allocator.Assignments.ResourceIds, ...
                    ~isempty(result.DecisionUeIds), ...
                    ~isempty(result.ReassignedUeIds)];
            end

            % Resource ID, decision flag, and reassignment flag captured
            % from the uncapped pre-change allocator on MATLAB R2026a.
            expectedTrace = [ ...
                2 0 0; 2 0 0; 2 0 0; 2 0 0; 1 1 1; ...
                1 0 0; 1 0 0; 1 0 0; 1 0 0; 1 0 0; ...
                1 0 0; 1 0 0; 1 0 0; 1 0 0; 1 0 0; ...
                1 0 0; 1 0 0; 1 0 0; 1 0 0; 1 0 0; ...
                1 0 0; 4 1 1; 4 0 0; 4 0 0; 4 0 0; ...
                3 1 1; 3 0 0; 3 0 0; 3 0 0; 3 0 0];
            testCase.verifyEqual(actualTrace, expectedTrace);
        end

        function testCapOneMatchesZeroKeepProbabilitySequence(testCase)
            grid = testCase.createGrid(4);
            capped = testCase.createAllocator( ...
                grid,KeepResourceProbability=1, ...
                MaximumConsecutiveReservationIntervals=1);
            zeroKeep = testCase.createAllocator( ...
                grid,KeepResourceProbability=0, ...
                MaximumConsecutiveReservationIntervals=Inf);

            [capped,zeroKeep] = testCase.initializePair( ...
                capped,zeroKeep,true(1,grid.ResourceCount));
            for stepIndex = 1:8
                context = testCase.createContext( ...
                    grid,"ue-1",stepIndex,true, ...
                    true(1,grid.ResourceCount),true,false,false);
                [capped,cappedResult] = capped.step(context);
                [zeroKeep,zeroKeepResult] = zeroKeep.step(context);
                testCase.verifyEqual( ...
                    capped.Assignments,zeroKeep.Assignments);
                testCase.verifyEqual( ...
                    cappedResult.DecisionUeIds, ...
                    zeroKeepResult.DecisionUeIds);
                testCase.verifyEqual( ...
                    cappedResult.ReassignedUeIds, ...
                    zeroKeepResult.ReassignedUeIds);
            end
        end

        function testCapForcesReselectionAfterConfiguredIntervals( ...
                testCase)
            grid = testCase.createGrid(4);
            allocator = testCase.createAllocator( ...
                grid,KeepResourceProbability=1, ...
                MaximumConsecutiveReservationIntervals=2);
            allocator = allocator.synchronizeUes("ue-1");
            initial = testCase.createContext( ...
                grid,"ue-1",0,false,logical([1 0 0 0]), ...
                false,false,false);
            [allocator,~] = allocator.initialize(initial);

            retained = testCase.createContext( ...
                grid,"ue-1",1,true,true(1,4),true,false,false);
            [allocator,firstResult] = allocator.step(retained);
            [allocator,secondResult] = allocator.step(retained);
            [~,thirdResult] = allocator.step(retained);

            testCase.verifyEmpty(firstResult.DecisionUeIds);
            testCase.verifyEmpty(secondResult.DecisionUeIds);
            testCase.verifyEqual(thirdResult.DecisionUeIds,"ue-1");
        end

        function testForcedReselectionResetsIntervalCount(testCase)
            grid = testCase.createGrid(4);
            allocator = testCase.createAllocator( ...
                grid,KeepResourceProbability=1, ...
                MaximumConsecutiveReservationIntervals=2);
            allocator = allocator.synchronizeUes("ue-1");
            initial = testCase.createContext( ...
                grid,"ue-1",0,false,logical([1 0 0 0]), ...
                false,false,false);
            [allocator,~] = allocator.initialize(initial);

            retainFirst = testCase.createContext( ...
                grid,"ue-1",1,true,logical([1 0 0 0]), ...
                true,false,false);
            [allocator,~] = allocator.step(retainFirst);
            forceSecond = testCase.createContext( ...
                grid,"ue-1",2,true,logical([0 1 0 0]), ...
                true,false,false);
            [allocator,forcedResult] = allocator.step(forceSecond);
            testCase.verifyEqual(forcedResult.DecisionUeIds,"ue-1");
            testCase.verifyEqual(allocator.Assignments.ResourceIds,2);

            retainAfterReset = testCase.createContext( ...
                grid,"ue-1",3,true,logical([0 1 0 0]), ...
                true,false,false);
            [allocator,firstAfterReset] = ...
                allocator.step(retainAfterReset);
            [~,secondAfterReset] = ...
                allocator.step(retainAfterReset);

            testCase.verifyEmpty(firstAfterReset.DecisionUeIds);
            testCase.verifyEmpty(secondAfterReset.DecisionUeIds);
        end

        function testSynchronizationPreservesCountsByUeIdentity(testCase)
            grid = testCase.createGrid(2);
            allocator = testCase.createAllocator( ...
                grid,KeepResourceProbability=1, ...
                MaximumConsecutiveReservationIntervals=2);
            allocator = allocator.synchronizeUes(["a";"b"]);
            initial = testCase.createContext( ...
                grid,["a";"b"],0,false(2,1),logical(eye(2)), ...
                false(2,1),false(2,1),false(2,1));
            [allocator,~] = allocator.initialize(initial);

            retainBoth = testCase.createContext( ...
                grid,["a";"b"],1,true(2,1),logical(eye(2)), ...
                true(2,1),false(2,1),false(2,1));
            [allocator,~] = allocator.step(retainBoth);
            forceB = testCase.createContext( ...
                grid,["a";"b"],2,true(2,1), ...
                logical([1 0;1 0]),true(2,1), ...
                false(2,1),false(2,1));
            [allocator,~] = allocator.step(forceB);

            allocator = allocator.synchronizeUes(["b";"a"]);
            reordered = testCase.createContext( ...
                grid,["b";"a"],3,true(2,1), ...
                logical([1 0;1 0]),true(2,1), ...
                false(2,1),false(2,1));
            [~,result] = allocator.step(reordered);

            testCase.verifyEqual(result.DecisionUeIds,"a");
        end

        function testChangedNrReevaluationStartsNewIntervalChain( ...
                testCase)
            [allocator,grid] = testCase.initializeNrReevaluationAllocator();

            changed = testCase.createContext( ...
                grid,"ue-1",0,false,logical([0 0 1 0 0]), ...
                false,false,true);
            [allocator,reevaluationResult] = allocator.step(changed);
            testCase.verifyEqual( ...
                reevaluationResult.ReassignedUeIds,"ue-1");
            testCase.verifyEqual(allocator.Assignments.ResourceIds,3);

            transmission = testCase.createContext( ...
                grid,"ue-1",1,true,logical([0 0 1 0 0]), ...
                true,false,false);
            [allocator,~] = allocator.step(transmission);
            [allocator,secondResult] = allocator.step(transmission);
            [~,thirdResult] = allocator.step(transmission);

            testCase.verifyEmpty(secondResult.DecisionUeIds);
            testCase.verifyEqual(thirdResult.DecisionUeIds,"ue-1");
        end

        function testRetainedNrReevaluationDoesNotResetIntervalChain( ...
                testCase)
            [allocator,grid] = testCase.initializeNrReevaluationAllocator();

            retained = testCase.createContext( ...
                grid,"ue-1",0,false,logical([0 0 0 1 0]), ...
                false,false,true);
            [allocator,reevaluationResult] = allocator.step(retained);
            testCase.verifyEmpty(reevaluationResult.ReassignedUeIds);

            transmission = testCase.createContext( ...
                grid,"ue-1",1,true,logical([0 0 0 1 0]), ...
                true,false,false);
            [allocator,firstResult] = allocator.step(transmission);
            [~,secondResult] = allocator.step(transmission);

            testCase.verifyEmpty(firstResult.DecisionUeIds);
            testCase.verifyEqual(secondResult.DecisionUeIds,"ue-1");
        end

        function testRejectsInvalidCapsWithStableIdentifier(testCase)
            grid = testCase.createGrid(4);
            invalidValues = {0,-1,1.5,NaN,-Inf,"2",[1 2],1 + 1i};

            for index = 1:numel(invalidValues)
                value = invalidValues{index};
                testCase.verifyError( ...
                    @() testCase.createAllocator( ...
                        grid, ...
                        MaximumConsecutiveReservationIntervals=value), ...
                    "v2xsim:resource:" + ...
                    "InvalidMaximumConsecutiveReservationIntervals");
            end
        end

        function testMetadataMakesUnlimitedValueJsonExplicit(testCase)
            grid = testCase.createGrid(4);
            unlimited = testCase.createAllocator(grid,OmitCap=true);
            unlimitedOptions = unlimited.metadata().Options;

            testCase.verifyEqual( ...
                unlimitedOptions. ...
                MaximumConsecutiveReservationIntervals,Inf);
            testCase.verifyTrue( ...
                unlimitedOptions. ...
                MaximumConsecutiveReservationIntervalsIsUnlimited);

            json = jsonencode( ...
                unlimited.metadata(),ConvertInfAndNaN=true);
            decoded = jsondecode(json);
            testCase.verifyTrue( ...
                decoded.Options. ...
                MaximumConsecutiveReservationIntervalsIsUnlimited);
            testCase.verifyEmpty( ...
                decoded.Options.MaximumConsecutiveReservationIntervals);

            finite = testCase.createAllocator( ...
                grid,MaximumConsecutiveReservationIntervals=5);
            finiteOptions = finite.metadata().Options;
            testCase.verifyEqual( ...
                finiteOptions.MaximumConsecutiveReservationIntervals,5);
            testCase.verifyFalse( ...
                finiteOptions. ...
                MaximumConsecutiveReservationIntervalsIsUnlimited);
        end
    end

    methods (Static, Access = private)
        function grid = createGrid(timeSlotCount)
            grid = v2xsim.resource.BRResourceGrid( ...
                v2xsim.network.NetworkSliceId("global"), ...
                timeSlotCount,1,0.001);
        end

        function allocator = createAllocator(grid,options)
            arguments (Input)
                grid (1,1) v2xsim.resource.BRResourceGrid
                options.KeepResourceProbability = 1
                options.MaximumConsecutiveReservationIntervals = Inf
                options.OmitCap (1,1) logical = false
                options.ResourceReevaluationEnabled (1,1) logical = false
                options.ReevaluateAfterSkippedTransmissionEnabled ...
                    (1,1) logical = false
            end

            commonOptions = { ...
                "MinimumReselectionCounter",2, ...
                "MaximumReselectionCounter",2, ...
                "KeepResourceProbability", ...
                    options.KeepResourceProbability, ...
                "MinimumCandidateFraction",0.2, ...
                "L2CandidateFraction",1, ...
                "L2RankingEnabled",false, ...
                "DynamicSchedulingEnabled",false, ...
                "ResourceReevaluationEnabled", ...
                    options.ResourceReevaluationEnabled, ...
                "ReevaluateAfterSkippedTransmissionEnabled", ...
                    options.ReevaluateAfterSkippedTransmissionEnabled, ...
                "SensingThresholdWatts",1e-10, ...
                "IsNr",options.ResourceReevaluationEnabled};
            if options.OmitCap
                allocator = ...
                    v2xsim.resource.ThreeGppAutonomousAllocator( ...
                    grid,23,1,commonOptions{:});
            else
                allocator = ...
                    v2xsim.resource.ThreeGppAutonomousAllocator( ...
                    grid,23,1,commonOptions{:}, ...
                    MaximumConsecutiveReservationIntervals= ...
                    options.MaximumConsecutiveReservationIntervals);
            end
        end

        function context = createContext( ...
                grid,ueIds,currentSlot,newPacket,eligibility, ...
                firstTransmission,skippedReserved,packetPending)
            snapshot = v2xsim.resource.SensingSnapshot( ...
                grid.NetworkSliceId,ueIds, ...
                zeros(numel(ueIds),grid.ResourceCount), ...
                false(numel(ueIds),grid.ResourceCount));
            context = v2xsim.resource.ThreeGppAllocationContext( ...
                grid.NetworkSliceId,ueIds,currentSlot,newPacket, ...
                eligibility,snapshot,firstTransmission, ...
                skippedReserved,packetPending, ...
                ones(numel(ueIds),1),zeros(numel(ueIds),1));
        end

        function [left,right] = initializePair( ...
                left,right,eligibility)
            ueId = "ue-1";
            left = left.synchronizeUes(ueId);
            right = right.synchronizeUes(ueId);
            context = ...
                v2xsimtest.resource.ThreeGppRetentionCapTest. ...
                createContext( ...
                left.Grid,ueId,0,false,eligibility, ...
                false,false,false);
            [left,~] = left.initialize(context);
            [right,~] = right.initialize(context);
        end

        function [allocator,grid] = ...
                initializeNrReevaluationAllocator()
            grid = ...
                v2xsimtest.resource.ThreeGppRetentionCapTest. ...
                createGrid(5);
            allocator = ...
                v2xsimtest.resource.ThreeGppRetentionCapTest. ...
                createAllocator( ...
                grid,KeepResourceProbability=1, ...
                MaximumConsecutiveReservationIntervals=2, ...
                ResourceReevaluationEnabled=true, ...
                ReevaluateAfterSkippedTransmissionEnabled=true);
            allocator = allocator.synchronizeUes("ue-1");
            initial = ...
                v2xsimtest.resource.ThreeGppRetentionCapTest. ...
                createContext( ...
                grid,"ue-1",0,false,logical([0 0 0 1 0]), ...
                false,false,false);
            [allocator,~] = allocator.initialize(initial);

            % Complete one retained interval and mark the next reservation
            % for NR reevaluation after a skipped transmission.
            retainAndSkip = ...
                v2xsimtest.resource.ThreeGppRetentionCapTest. ...
                createContext( ...
                grid,"ue-1",1,true,logical([0 0 0 1 0]), ...
                true,true,false);
            [allocator,~] = allocator.step(retainAndSkip);
        end
    end
end
