classdef AfterNeighborGraphUpdatedInvocation < ...
        v2xsim.hook.invocation.Invocation
    %AFTERNEIGHBORGRAPHUPDATEDINVOCATION Distances and neighbor summaries.

    properties (SetAccess = immutable)
        SimulationTimeSeconds (1, 1) double ...
            {mustBeReal, mustBeFinite, mustBeNonnegative}
        UeIds (:, 1) double ...
            {mustBeReal, mustBeFinite, mustBeInteger, mustBePositive}
        Cv2xUeIds (:, 1) double ...
            {mustBeReal, mustBeFinite, mustBeInteger, mustBePositive}
        ItsG5UeIds (:, 1) double ...
            {mustBeReal, mustBeFinite, mustBeInteger, mustBePositive}
        DistanceMatrixMeters (:, :) double ...
            {mustBeReal, mustBeNonnegative}
        AwarenessRangesMeters (1, :) double ...
            {mustBeReal, mustBeFinite, mustBePositive}
        AverageCv2xNeighbors (1, :) double ...
            {mustBeReal, mustBeFinite, mustBeNonnegative}
        AverageItsG5Neighbors (1, :) double ...
            {mustBeReal, mustBeFinite, mustBeNonnegative}
    end

    methods
        function obj = AfterNeighborGraphUpdatedInvocation( ...
                simulationTimeSeconds, ueIds, cv2xUeIds, ...
                itsG5UeIds, distanceMatrixMeters, ...
                awarenessRangesMeters, averageCv2xNeighbors, ...
                averageItsG5Neighbors)
            arguments (Input)
                simulationTimeSeconds (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative}
                ueIds (:, 1) double ...
                    {mustBeReal, mustBeFinite, ...
                    mustBeInteger, mustBePositive}
                cv2xUeIds (:, 1) double ...
                    {mustBeReal, mustBeFinite, ...
                    mustBeInteger, mustBePositive}
                itsG5UeIds (:, 1) double ...
                    {mustBeReal, mustBeFinite, ...
                    mustBeInteger, mustBePositive}
                distanceMatrixMeters (:, :) double ...
                    {mustBeReal, mustBeNonnegative}
                awarenessRangesMeters (1, :) double ...
                    {mustBeReal, mustBeFinite, mustBePositive}
                averageCv2xNeighbors (1, :) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative}
                averageItsG5Neighbors (1, :) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative}
            end

            ueCount = numel(ueIds);
            if ~isequal(size(distanceMatrixMeters), [ueCount, ueCount])
                error( ...
                    "v2xsim:hook:invocations:DistanceMatrixSizeMismatch", ...
                    "DistanceMatrixMeters must be square with one row " + ...
                    "and column per UeId.");
            end
            if any(~isfinite( ...
                    distanceMatrixMeters(~isinf(distanceMatrixMeters))))
                error( ...
                    "v2xsim:hook:invocations:InvalidDistance", ...
                    "Distances must be finite or positive infinity.");
            end
            if numel(unique(ueIds)) ~= ueCount || ...
                    ~all(ismember(cv2xUeIds, ueIds)) || ...
                    ~all(ismember(itsG5UeIds, ueIds)) || ...
                    ~isempty(intersect(cv2xUeIds, itsG5UeIds))
                error( ...
                    "v2xsim:hook:invocations:InvalidTechnologyPartition", ...
                    "Technology-specific UE IDs must form disjoint " + ...
                    "subsets of UeIds.");
            end
            rangeCount = numel(awarenessRangesMeters);
            if numel(averageCv2xNeighbors) ~= rangeCount || ...
                    numel(averageItsG5Neighbors) ~= rangeCount
                error( ...
                    "v2xsim:hook:invocations:NeighborSummarySizeMismatch", ...
                    "Neighbor summaries must contain one value per " + ...
                    "awareness range.");
            end

            obj.SimulationTimeSeconds = simulationTimeSeconds;
            obj.UeIds = ueIds;
            obj.Cv2xUeIds = cv2xUeIds;
            obj.ItsG5UeIds = itsG5UeIds;
            obj.DistanceMatrixMeters = distanceMatrixMeters;
            obj.AwarenessRangesMeters = awarenessRangesMeters;
            obj.AverageCv2xNeighbors = averageCv2xNeighbors;
            obj.AverageItsG5Neighbors = averageItsG5Neighbors;
        end
    end
end
