classdef AfterPacketFatesDeterminedInvocation < ...
        v2xsim.hook.invocation.Invocation
    %AFTERPACKETFATESDETERMINEDINVOCATION Typed packet-link outcomes.
    %   Transmitters requires TransmitterId, Channel, PacketType, and
    %   GenerationTimeSeconds. Links requires TransmitterId, ReceiverId,
    %   DistanceMeters, and Outcome. Outcome is one of "none", "correct",
    %   "error", or "blocked". One row is supplied for every candidate
    %   receiver link.
    %
    %   The legacy required columns remain accepted. Producers may also
    %   attach stable string UE identities, packet/attempt identifiers,
    %   allocation-resource identifiers, and an explicit terminal flag.
    %   Optional metadata is validated when present and is retained
    %   verbatim for identity-preserving packet diagnostics.

    properties (SetAccess = immutable)
        SimulationTimeSeconds (1, 1) double ...
            {mustBeReal, mustBeFinite, mustBeNonnegative}
        Technology (1, 1) string
        MaximumUeId (1, 1) double ...
            {mustBeReal, mustBeFinite, mustBeInteger, mustBePositive} = 1
        AwarenessRangesMeters (1, :) double ...
            {mustBeReal, mustBeFinite, mustBePositive}
        Transmitters table
        Links table
    end

    methods
        function obj = AfterPacketFatesDeterminedInvocation( ...
                simulationTimeSeconds, technology, maximumUeId, ...
                awarenessRangesMeters, transmitters, links)
            arguments (Input)
                simulationTimeSeconds (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative}
                technology (1, 1) string
                maximumUeId (1, 1) double ...
                    {mustBeReal, mustBeFinite, ...
                    mustBeInteger, mustBePositive}
                awarenessRangesMeters (1, :) double ...
                    {mustBeReal, mustBeFinite, mustBePositive}
                transmitters table
                links table
            end

            technology = validatestring( ...
                technology, ["11p", "LTE", "5G"]);
            v2xsim.hook.invocations. ...
                AfterPacketFatesDeterminedInvocation. ...
                validateTransmitters(transmitters, maximumUeId);
            v2xsim.hook.invocations. ...
                AfterPacketFatesDeterminedInvocation. ...
                validateLinks(links, transmitters, maximumUeId);

            obj.SimulationTimeSeconds = simulationTimeSeconds;
            obj.Technology = technology;
            obj.MaximumUeId = maximumUeId;
            obj.AwarenessRangesMeters = awarenessRangesMeters;
            obj.Transmitters = transmitters;
            obj.Links = links;
        end
    end

    methods (Static, Access = private)
        function validateTransmitters(transmitters, maximumUeId)
            requiredNames = [ ...
                "TransmitterId", "Channel", "PacketType", ...
                "GenerationTimeSeconds"];
            optionalNames = [ ...
                "TransmitterUeId", "PacketSequence", ...
                "AttemptNumber", "ResourceId", ...
                "TimeResourceId", "FrequencyResourceId", ...
                "AllocationEpoch", "IsPacketComplete"];
            actualNames = string( ...
                transmitters.Properties.VariableNames);
            if ~all(ismember(requiredNames, actualNames)) || ...
                    any(~ismember( ...
                        actualNames, [requiredNames, optionalNames]))
                error( ...
                    "v2xsim:hook:invocations:InvalidTransmitters", ...
                    "Transmitters must contain %s and only supported " + ...
                    "packet metadata.", ...
                    strjoin(requiredNames, ", "));
            end
            ids = transmitters.TransmitterId;
            channels = transmitters.Channel;
            packetTypes = transmitters.PacketType;
            generationTimes = transmitters.GenerationTimeSeconds;
            if ~iscolumn(ids) || ~isnumeric(ids) || ...
                    any(~isfinite(ids)) || any(ids < 1) || ...
                    any(ids > maximumUeId) || any(fix(ids) ~= ids) || ...
                    numel(unique(ids)) ~= numel(ids) || ...
                    ~iscolumn(channels) || ~isnumeric(channels) || ...
                    any(~isfinite(channels)) || any(channels < 1) || ...
                    any(fix(channels) ~= channels) || ...
                    ~iscolumn(packetTypes) || ~isnumeric(packetTypes) || ...
                    any(~isfinite(packetTypes)) || ...
                    any(packetTypes < 1) || ...
                    any(fix(packetTypes) ~= packetTypes) || ...
                    ~iscolumn(generationTimes) || ...
                    ~isnumeric(generationTimes) || ...
                    any(~isfinite(generationTimes)) || ...
                    any(generationTimes < 0)
                error( ...
                    "v2xsim:hook:invocations:InvalidTransmitters", ...
                    "Transmitter metadata contains invalid values.");
            end

            if ismember("TransmitterUeId", actualNames)
                ueIds = transmitters.TransmitterUeId;
                if ~isstring(ueIds) || ~iscolumn(ueIds) || ...
                        any(ismissing(ueIds)) || ...
                        any(strlength(strip(ueIds)) == 0) || ...
                        any(ueIds ~= strip(ueIds)) || ...
                        numel(unique(ueIds)) ~= numel(ueIds)
                    error( ...
                        "v2xsim:hook:invocations:" + ...
                        "InvalidTransmitters", ...
                        "Stable transmitter UE identities must be " + ...
                        "unique, nonblank string values.");
                end
            end

            if ismember("IsPacketComplete",actualNames) && ...
                    (~islogical(transmitters.IsPacketComplete) || ~iscolumn(transmitters.IsPacketComplete))
                error("v2xsim:hook:invocations:InvalidTransmitters", ...
                    "IsPacketComplete must be a logical column.");
            end
            integerMetadata = [ ...
                "PacketSequence", "AttemptNumber", "ResourceId", ...
                "TimeResourceId", "FrequencyResourceId", ...
                "AllocationEpoch"];
            for variableName = integerMetadata( ...
                    ismember(integerMetadata, actualNames))
                allowZero = variableName == "AttemptNumber" || ...
                    variableName == "AllocationEpoch";
                v2xsim.hook.invocations. ...
                    AfterPacketFatesDeterminedInvocation. ...
                    validateOptionalIntegerMetadata( ...
                        transmitters.(variableName), ...
                        variableName, allowZero);
            end
            if ismember("IsPacketComplete",actualNames) && any(transmitters.IsPacketComplete) && ...
                    (~ismember("PacketSequence",actualNames) || ...
                     any(isnan(transmitters.PacketSequence(transmitters.IsPacketComplete))))
                error("v2xsim:hook:invocations:InvalidTransmitters", ...
                    "Completed packets require explicit packet sequences.");
            end
        end

        function validateLinks(links, transmitters, maximumUeId)
            requiredNames = [ ...
                "TransmitterId", "ReceiverId", ...
                "DistanceMeters", "Outcome"];
            optionalNames = [ ...
                "TransmitterUeId", "ReceiverUeId", "IsTerminal"];
            actualNames = string(links.Properties.VariableNames);
            if ~all(ismember(requiredNames, actualNames)) || ...
                    any(~ismember( ...
                        actualNames, [requiredNames, optionalNames]))
                error( ...
                    "v2xsim:hook:invocations:InvalidLinks", ...
                    "Links must contain %s and only supported packet " + ...
                    "metadata.", ...
                    strjoin(requiredNames, ", "));
            end
            txIds = links.TransmitterId;
            rxIds = links.ReceiverId;
            distances = links.DistanceMeters;
            outcomes = string(links.Outcome);
            validOutcomes = ["none", "correct", "error", "blocked"];
            if ~iscolumn(txIds) || ~isnumeric(txIds) || ...
                    any(~isfinite(txIds)) || any(fix(txIds) ~= txIds) || ...
                    any(~ismember(txIds, transmitters.TransmitterId)) || ...
                    ~iscolumn(rxIds) || ~isnumeric(rxIds) || ...
                    any(~isfinite(rxIds)) || any(rxIds < 1) || ...
                    any(rxIds > maximumUeId) || ...
                    any(fix(rxIds) ~= rxIds) || ...
                    any(txIds == rxIds) || ...
                    ~iscolumn(distances) || ~isnumeric(distances) || ...
                    any(~isfinite(distances)) || any(distances < 0) || ...
                    ~iscolumn(outcomes) || ...
                    any(~ismember(outcomes, validOutcomes))
                error( ...
                    "v2xsim:hook:invocations:InvalidLinks", ...
                    "Packet-link metadata contains invalid values.");
            end

            stableIdNames = ["TransmitterUeId", "ReceiverUeId"];
            for variableName = stableIdNames( ...
                    ismember(stableIdNames, actualNames))
                ueIds = links.(variableName);
                if ~isstring(ueIds) || ~iscolumn(ueIds) || ...
                        any(ismissing(ueIds)) || ...
                        any(strlength(strip(ueIds)) == 0) || ...
                        any(ueIds ~= strip(ueIds))
                    error( ...
                        "v2xsim:hook:invocations:InvalidLinks", ...
                        "Stable packet-link UE identities must be " + ...
                        "nonblank string values.");
                end
            end
            if all(ismember( ...
                    ["TransmitterUeId", "ReceiverUeId"], actualNames))
                if any(links.TransmitterUeId == links.ReceiverUeId)
                    error( ...
                        "v2xsim:hook:invocations:InvalidLinks", ...
                        "A packet link cannot use the same stable " + ...
                        "identity at both endpoints.");
                end
            end
            if ismember("TransmitterUeId", actualNames) && ...
                    ismember( ...
                        "TransmitterUeId", ...
                        string( ...
                            transmitters.Properties.VariableNames))
                [~, transmitterRows] = ismember( ...
                    txIds, transmitters.TransmitterId);
                if any( ...
                        links.TransmitterUeId ~= ...
                        transmitters.TransmitterUeId( ...
                            transmitterRows))
                    error( ...
                        "v2xsim:hook:invocations:InvalidLinks", ...
                        "Numeric and stable transmitter identities " + ...
                        "must agree.");
                end
            end
            if ismember("IsTerminal", actualNames)
                isTerminal = links.IsTerminal;
                if ~islogical(isTerminal) || ...
                        ~iscolumn(isTerminal) || ...
                        any(isTerminal ~= (outcomes ~= "none"))
                    error( ...
                        "v2xsim:hook:invocations:InvalidLinks", ...
                        "IsTerminal must be logical and true exactly " + ...
                        "for correct, error, and blocked outcomes.");
                end
            end
        end

        function validateOptionalIntegerMetadata( ...
                values, variableName, allowZero)
            if ~isnumeric(values) || ~iscolumn(values)
                error( ...
                    "v2xsim:hook:invocations:" + ...
                    "InvalidTransmitters", ...
                    "%s must be a numeric column.", variableName);
            end
            knownValues = ~isnan(values);
            minimumValue = 1;
            if allowZero
                minimumValue = 0;
            end
            if any(~isfinite(values(knownValues))) || ...
                    any(values(knownValues) < minimumValue) || ...
                    any(fix(values(knownValues)) ~= values(knownValues))
                error( ...
                    "v2xsim:hook:invocations:" + ...
                    "InvalidTransmitters", ...
                    "%s must contain integer identifiers or NaN.", ...
                    variableName);
            end
        end
    end
end
