classdef AfterVehicleKinematicsUpdatedInvocation < ...
        v2xsim.hook.invocation.Invocation
    %AFTERVEHICLEKINEMATICSUPDATEDINVOCATION Vehicle-kinematics snapshot.
    %   Vehicle identities are the table row names. The table uses the
    %   canonical Scenario variables X, Y, vX, vY, aX, and aY.

    properties (SetAccess = immutable)
        SimulationTimeSeconds (1, 1) double ...
            {mustBeReal, mustBeFinite, mustBeNonnegative}
        VehicleKinematics table
    end

    methods
        function obj = AfterVehicleKinematicsUpdatedInvocation( ...
                simulationTimeSeconds, vehicleKinematics)
            arguments (Input)
                simulationTimeSeconds (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative}
                vehicleKinematics table
            end

            expectedVariables = ["X", "Y", "vX", "vY", "aX", "aY"];
            actualVariables = string( ...
                vehicleKinematics.Properties.VariableNames);
            if ~isequal(actualVariables, expectedVariables)
                error( ...
                    "v2xsim:hook:invocations:" + ...
                        "InvalidVehicleKinematicsVariables", ...
                    "VehicleKinematics must contain exactly X, Y, " + ...
                    "vX, vY, aX, and aY, in that order.");
            end

            v2xsim.vehicle.scenario.validation. ...
                mustBe2DKinematicsTable(vehicleKinematics);

            rowNames = string( ...
                vehicleKinematics.Properties.RowNames);
            if height(vehicleKinematics) > 0 && ...
                    (numel(rowNames) ~= height(vehicleKinematics) || ...
                    any(strlength(rowNames) == 0))
                error( ...
                    "v2xsim:hook:invocations:MissingVehicleIds", ...
                    "VehicleKinematics must provide one nonempty, " + ...
                    "unique row name for every vehicle.");
            end

            obj.SimulationTimeSeconds = simulationTimeSeconds;
            obj.VehicleKinematics = vehicleKinematics;
        end
    end
end
