classdef AfterPacketFatesDeterminedInvocation < ...
        v2xsim.hook.invocation.Invocation
    %AFTERPACKETFATESDETERMINEDINVOCATION Typed packet-link outcomes.
    %   Links contains TransmitterId, ReceiverId, DistanceMeters, and
    %   Outcome. Outcome is one of "none", "correct", "error", or
    %   "blocked". One row is supplied for every candidate receiver link.

    properties (SetAccess = immutable)
        SimulationTimeSeconds (1, 1) double ...
            {mustBeReal, mustBeFinite, mustBeNonnegative}
        Technology (1, 1) string
        MaximumUeId (1, 1) double ...
            {mustBeReal, mustBeFinite, mustBeInteger, mustBePositive} = 1
        AwarenessRangesMeters (1, :) double ...
            {mustBeReal, mustBeFinite, mustBePositive}
        Transmitters table
        Links table
    end

    methods
        function obj = AfterPacketFatesDeterminedInvocation( ...
                simulationTimeSeconds, technology, maximumUeId, ...
                awarenessRangesMeters, transmitters, links)
            arguments (Input)
                simulationTimeSeconds (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative}
                technology (1, 1) string
                maximumUeId (1, 1) double ...
                    {mustBeReal, mustBeFinite, ...
                    mustBeInteger, mustBePositive}
                awarenessRangesMeters (1, :) double ...
                    {mustBeReal, mustBeFinite, mustBePositive}
                transmitters table
                links table
            end

            technology = validatestring( ...
                technology, ["11p", "LTE", "5G"]);
            v2xsim.hook.invocations. ...
                AfterPacketFatesDeterminedInvocation. ...
                validateTransmitters(transmitters, maximumUeId);
            v2xsim.hook.invocations. ...
                AfterPacketFatesDeterminedInvocation. ...
                validateLinks(links, transmitters, maximumUeId);

            obj.SimulationTimeSeconds = simulationTimeSeconds;
            obj.Technology = technology;
            obj.MaximumUeId = maximumUeId;
            obj.AwarenessRangesMeters = awarenessRangesMeters;
            obj.Transmitters = transmitters;
            obj.Links = links;
        end
    end

    methods (Static, Access = private)
        function validateTransmitters(transmitters, maximumUeId)
            expectedNames = [ ...
                "TransmitterId", "Channel", "PacketType", ...
                "GenerationTimeSeconds"];
            if ~isequal( ...
                    string(transmitters.Properties.VariableNames), ...
                    expectedNames)
                error( ...
                    "v2xsim:hook:invocations:InvalidTransmitters", ...
                    "Transmitters must contain exactly %s.", ...
                    strjoin(expectedNames, ", "));
            end
            ids = transmitters.TransmitterId;
            channels = transmitters.Channel;
            packetTypes = transmitters.PacketType;
            generationTimes = transmitters.GenerationTimeSeconds;
            if ~iscolumn(ids) || ~isnumeric(ids) || ...
                    any(~isfinite(ids)) || any(ids < 1) || ...
                    any(ids > maximumUeId) || any(fix(ids) ~= ids) || ...
                    numel(unique(ids)) ~= numel(ids) || ...
                    ~iscolumn(channels) || ~isnumeric(channels) || ...
                    any(~isfinite(channels)) || any(channels < 1) || ...
                    any(fix(channels) ~= channels) || ...
                    ~iscolumn(packetTypes) || ~isnumeric(packetTypes) || ...
                    any(~isfinite(packetTypes)) || ...
                    any(packetTypes < 1) || ...
                    any(fix(packetTypes) ~= packetTypes) || ...
                    ~iscolumn(generationTimes) || ...
                    ~isnumeric(generationTimes) || ...
                    any(~isfinite(generationTimes)) || ...
                    any(generationTimes < 0)
                error( ...
                    "v2xsim:hook:invocations:InvalidTransmitters", ...
                    "Transmitter metadata contains invalid values.");
            end
        end

        function validateLinks(links, transmitters, maximumUeId)
            expectedNames = [ ...
                "TransmitterId", "ReceiverId", ...
                "DistanceMeters", "Outcome"];
            if ~isequal( ...
                    string(links.Properties.VariableNames), ...
                    expectedNames)
                error( ...
                    "v2xsim:hook:invocations:InvalidLinks", ...
                    "Links must contain exactly %s.", ...
                    strjoin(expectedNames, ", "));
            end
            txIds = links.TransmitterId;
            rxIds = links.ReceiverId;
            distances = links.DistanceMeters;
            outcomes = string(links.Outcome);
            validOutcomes = ["none", "correct", "error", "blocked"];
            if ~iscolumn(txIds) || ~isnumeric(txIds) || ...
                    any(~isfinite(txIds)) || any(fix(txIds) ~= txIds) || ...
                    any(~ismember(txIds, transmitters.TransmitterId)) || ...
                    ~iscolumn(rxIds) || ~isnumeric(rxIds) || ...
                    any(~isfinite(rxIds)) || any(rxIds < 1) || ...
                    any(rxIds > maximumUeId) || ...
                    any(fix(rxIds) ~= rxIds) || ...
                    any(txIds == rxIds) || ...
                    ~iscolumn(distances) || ~isnumeric(distances) || ...
                    any(~isfinite(distances)) || any(distances < 0) || ...
                    ~iscolumn(outcomes) || ...
                    any(~ismember(outcomes, validOutcomes))
                error( ...
                    "v2xsim:hook:invocations:InvalidLinks", ...
                    "Packet-link metadata contains invalid values.");
            end
        end
    end
end
