classdef AfterPositionErrorChainAppliedInvocation < ...
        v2xsim.hook.invocation.Invocation
    %AFTERPOSITIONERRORCHAINAPPLIEDINVOCATION Position-error snapshots.

    properties (SetAccess = immutable)
        SimulationTimeSeconds (1, 1) double ...
            {mustBeReal, mustBeFinite, mustBeNonnegative} = 0
        PositionsBeforeErrorChain table ...
            {v2xsim.positioning.validation.mustBe2DPositionTable} = ...
            table( ...
                zeros(0, 1), zeros(0, 1), ...
                VariableNames=["X", "Y"])
        PositionsAfterErrorChain table ...
            {v2xsim.positioning.validation.mustBe2DPositionTable} = ...
            table( ...
                zeros(0, 1), zeros(0, 1), ...
                VariableNames=["X", "Y"])
    end

    methods
        function obj = AfterPositionErrorChainAppliedInvocation( ...
                positionsBeforeErrorChain, ...
                positionsAfterErrorChain, ...
                simulationTimeSeconds)
            arguments (Input)
                positionsBeforeErrorChain table ...
                    {v2xsim.positioning.validation. ...
                    mustBe2DPositionTable}
                positionsAfterErrorChain table ...
                    {v2xsim.positioning.validation. ...
                    mustBe2DPositionTable}
                simulationTimeSeconds (1, 1) double ...
                    {mustBeReal, mustBeFinite, ...
                    mustBeNonnegative} = 0
            end

            beforeVehicleIds = string( ...
                positionsBeforeErrorChain.Properties.RowNames);
            afterVehicleIds = string( ...
                positionsAfterErrorChain.Properties.RowNames);
            if ~isequal( ...
                    sort(beforeVehicleIds), ...
                    sort(afterVehicleIds))
                error( ...
                    "v2xsim:hook:invocations:VehicleSetChanged", ...
                    "The positions before and after the error chain " + ...
                    "must identify the same vehicles.");
            end

            obj.PositionsBeforeErrorChain = ...
                positionsBeforeErrorChain;
            obj.PositionsAfterErrorChain = ...
                positionsAfterErrorChain( ...
                    cellstr(beforeVehicleIds), :);
            obj.SimulationTimeSeconds = simulationTimeSeconds;
        end
    end
end
