classdef AfterInterferenceEvidenceDeterminedInvocation < ...
        v2xsim.hook.invocation.Invocation
    %AFTERINTERFERENCEEVIDENCEDETERMINEDINVOCATION Terminal C-V2X PHY evidence.
    %   TERMINALATTEMPTS contains one row per terminal directed radio
    %   attempt. COUNTERFACTUALS contains one row per nonzero concurrent
    %   C-V2X interference source removed from that attempt. Aggregate
    %   cross-technology interference is deliberately not assigned a fake
    %   UE identity; such attempts set EvidenceIsExhaustive false.

    properties (SetAccess = immutable)
        SimulationTimeSeconds (1,1) double ...
            {mustBeReal,mustBeFinite,mustBeNonnegative}
        Technology (1,1) string
        MaximumUeId (1,1) double ...
            {mustBeReal,mustBeFinite,mustBeInteger,mustBePositive} = 1
        UeIds (:,1) string
        Transmitters table
        TerminalAttempts table
        Counterfactuals table
    end

    methods
        function obj = AfterInterferenceEvidenceDeterminedInvocation( ...
                simulationTimeSeconds,technology,maximumUeId, ...
                ueIds,transmitters,terminalAttempts,counterfactuals)
            arguments (Input)
                simulationTimeSeconds (1,1) double ...
                    {mustBeReal,mustBeFinite,mustBeNonnegative}
                technology (1,1) string
                maximumUeId (1,1) double ...
                    {mustBeReal,mustBeFinite, ...
                    mustBeInteger,mustBePositive}
                ueIds (:,1) string
                transmitters table
                terminalAttempts table
                counterfactuals table
            end

            technology = validatestring(technology,["LTE","5G"]);
            obj.validateUeIds(ueIds,maximumUeId);
            obj.validateTransmitters( ...
                transmitters,ueIds,maximumUeId);
            obj.validateTerminalAttempts( ...
                terminalAttempts,transmitters,maximumUeId);
            obj.validateCounterfactuals( ...
                counterfactuals,terminalAttempts,maximumUeId);

            obj.SimulationTimeSeconds = simulationTimeSeconds;
            obj.Technology = technology;
            obj.MaximumUeId = maximumUeId;
            obj.UeIds = ueIds;
            obj.Transmitters = transmitters;
            obj.TerminalAttempts = terminalAttempts;
            obj.Counterfactuals = counterfactuals;
        end
    end

    methods (Static)
        function rows = emptyTerminalAttempts()
            rows = table( ...
                zeros(0,1),zeros(0,1),strings(0,1), ...
                zeros(0,1),zeros(0,1),zeros(0,1), ...
                zeros(0,1),false(0,1), ...
                VariableNames=[ ...
                    "TransmitterId","ReceiverId","Outcome", ...
                    "ObservedSinrDb","DecodeThresholdDb", ...
                    "SinrWithoutAllInterferersDb", ...
                    "InterfererCount","EvidenceIsExhaustive"]);
        end

        function rows = emptyCounterfactuals()
            rows = table( ...
                zeros(0,1),zeros(0,1),zeros(0,1), ...
                zeros(0,1),zeros(0,1),strings(0,1), ...
                zeros(0,1),zeros(0,1), ...
                VariableNames=[ ...
                    "TransmitterId","ReceiverId","InterfererId", ...
                    "InterfererResourceId", ...
                    "InterfererFrequencyResourceId", ...
                    "ResourceRelation","RemovedInterferencePower", ...
                    "SinrWithoutInterfererDb"]);
        end
    end

    methods (Static, Access = private)
        function validateUeIds(ueIds,maximumUeId)
            if numel(ueIds) ~= maximumUeId || ...
                    any(ismissing(ueIds)) || ...
                    any(strlength(strip(ueIds)) == 0) || ...
                    any(ueIds ~= strip(ueIds)) || ...
                    numel(unique(ueIds)) ~= numel(ueIds)
                error( ...
                    "v2xsim:hook:invocations:" + ...
                    "InvalidInterferenceUeIds", ...
                    "UeIds must uniquely map every dense UE identifier.");
            end
        end

        function validateTransmitters( ...
                transmitters,denseUeIds,maximumUeId)
            expectedNames = [ ...
                "TransmitterId","TransmitterUeId", ...
                "GenerationTimeSeconds","AttemptNumber", ...
                "ResourceId","FrequencyResourceId", ...
                "AllocationEpoch"];
            if ~isequal( ...
                    string(transmitters.Properties.VariableNames), ...
                    expectedNames)
                error( ...
                    "v2xsim:hook:invocations:" + ...
                    "InvalidInterferenceTransmitters", ...
                    "Interference transmitter metadata must contain %s.", ...
                    strjoin(expectedNames,", "));
            end

            ids = transmitters.TransmitterId;
            transmitterUeIds = transmitters.TransmitterUeId;
            generationTimes = transmitters.GenerationTimeSeconds;
            if ~isnumeric(ids) || ~iscolumn(ids) || ...
                    any(~isfinite(ids)) || any(ids < 1) || ...
                    any(ids > maximumUeId) || any(fix(ids) ~= ids) || ...
                    numel(unique(ids)) ~= numel(ids) || ...
                    ~isstring(transmitterUeIds) || ...
                    ~iscolumn(transmitterUeIds) || ...
                    any(ismissing(transmitterUeIds)) || ...
                    any(strlength(strip(transmitterUeIds)) == 0) || ...
                    any(transmitterUeIds ~= ...
                        strip(transmitterUeIds)) || ...
                    numel(unique(transmitterUeIds)) ~= ...
                        numel(transmitterUeIds) || ...
                    ~isnumeric(generationTimes) || ...
                    ~iscolumn(generationTimes) || ...
                    any(~isfinite(generationTimes)) || ...
                    any(generationTimes < 0)
                error( ...
                    "v2xsim:hook:invocations:" + ...
                    "InvalidInterferenceTransmitters", ...
                    "Interference transmitter identities and " + ...
                    "generation times are invalid.");
            end
            if any( ...
                    denseUeIds(ids) ~= ...
                    transmitterUeIds)
                error( ...
                    "v2xsim:hook:invocations:" + ...
                    "InvalidInterferenceTransmitters", ...
                    "Numeric and stable transmitter identities " + ...
                    "must agree.");
            end

            positiveIntegerNames = [ ...
                "AttemptNumber","ResourceId", ...
                "FrequencyResourceId"];
            for variableName = positiveIntegerNames
                values = transmitters.(variableName);
                if ~isnumeric(values) || ~iscolumn(values) || ...
                        any(~isfinite(values)) || any(values < 1) || ...
                        any(fix(values) ~= values)
                    error( ...
                        "v2xsim:hook:invocations:" + ...
                        "InvalidInterferenceTransmitters", ...
                        "%s must contain positive integer values.", ...
                        variableName);
                end
            end
            epochs = transmitters.AllocationEpoch;
            if ~isnumeric(epochs) || ~iscolumn(epochs) || ...
                    any(~isfinite(epochs)) || any(epochs < 0) || ...
                    any(fix(epochs) ~= epochs)
                error( ...
                    "v2xsim:hook:invocations:" + ...
                    "InvalidInterferenceTransmitters", ...
                    "AllocationEpoch must contain nonnegative integers.");
            end
        end

        function validateTerminalAttempts( ...
                attempts,transmitters,maximumUeId)
            expectedNames = string( ...
                v2xsim.hook.invocations. ...
                AfterInterferenceEvidenceDeterminedInvocation. ...
                emptyTerminalAttempts().Properties.VariableNames);
            if ~isequal( ...
                    string(attempts.Properties.VariableNames), ...
                    expectedNames)
                error( ...
                    "v2xsim:hook:invocations:" + ...
                    "InvalidTerminalInterferenceEvidence", ...
                    "Terminal-attempt evidence must contain %s.", ...
                    strjoin(expectedNames,", "));
            end

            txIds = attempts.TransmitterId;
            rxIds = attempts.ReceiverId;
            outcomes = attempts.Outcome;
            if ~isnumeric(txIds) || ~iscolumn(txIds) || ...
                    any(~ismember(txIds,transmitters.TransmitterId)) || ...
                    ~isnumeric(rxIds) || ~iscolumn(rxIds) || ...
                    any(~isfinite(rxIds)) || any(rxIds < 1) || ...
                    any(rxIds > maximumUeId) || ...
                    any(fix(rxIds) ~= rxIds) || ...
                    any(txIds == rxIds) || ...
                    ~isstring(outcomes) || ~iscolumn(outcomes) || ...
                    any(~ismember(outcomes,["correct","error"]))
                error( ...
                    "v2xsim:hook:invocations:" + ...
                    "InvalidTerminalInterferenceEvidence", ...
                    "Terminal-attempt identities or outcomes are invalid.");
            end

            sinrNames = [ ...
                "ObservedSinrDb","DecodeThresholdDb", ...
                "SinrWithoutAllInterferersDb"];
            for variableName = sinrNames
                values = attempts.(variableName);
                if ~isnumeric(values) || ~iscolumn(values) || ...
                        ~isreal(values) || any(isnan(values))
                    error( ...
                        "v2xsim:hook:invocations:" + ...
                        "InvalidTerminalInterferenceEvidence", ...
                        "%s must contain real non-NaN values.", ...
                        variableName);
                end
            end
            counts = attempts.InterfererCount;
            exhaustive = attempts.EvidenceIsExhaustive;
            if ~isnumeric(counts) || ~iscolumn(counts) || ...
                    any(~isfinite(counts)) || any(counts < 0) || ...
                    any(fix(counts) ~= counts) || ...
                    ~islogical(exhaustive) || ~iscolumn(exhaustive)
                error( ...
                    "v2xsim:hook:invocations:" + ...
                    "InvalidTerminalInterferenceEvidence", ...
                    "Interferer counts and evidence provenance are invalid.");
            end
            if height(unique( ...
                    attempts(:,["TransmitterId","ReceiverId"]), ...
                    "rows")) ~= height(attempts)
                error( ...
                    "v2xsim:hook:invocations:" + ...
                    "DuplicateTerminalInterferenceEvidence", ...
                    "A terminal attempt may contain each directed link once.");
            end
        end

        function validateCounterfactuals( ...
                rows,terminalAttempts,maximumUeId)
            expectedNames = string( ...
                v2xsim.hook.invocations. ...
                AfterInterferenceEvidenceDeterminedInvocation. ...
                emptyCounterfactuals().Properties.VariableNames);
            if ~isequal( ...
                    string(rows.Properties.VariableNames), ...
                    expectedNames)
                error( ...
                    "v2xsim:hook:invocations:" + ...
                    "InvalidInterferenceCounterfactuals", ...
                    "Interference counterfactuals must contain %s.", ...
                    strjoin(expectedNames,", "));
            end

            txIds = rows.TransmitterId;
            rxIds = rows.ReceiverId;
            interfererIds = rows.InterfererId;
            if ~isnumeric(txIds) || ~iscolumn(txIds) || ...
                    ~isnumeric(rxIds) || ~iscolumn(rxIds) || ...
                    ~isnumeric(interfererIds) || ...
                    ~iscolumn(interfererIds) || ...
                    any(~isfinite(interfererIds)) || ...
                    any(interfererIds < 1) || ...
                    any(interfererIds > maximumUeId) || ...
                    any(fix(interfererIds) ~= interfererIds) || ...
                    any(interfererIds == txIds)
                error( ...
                    "v2xsim:hook:invocations:" + ...
                    "InvalidInterferenceCounterfactuals", ...
                    "Counterfactual endpoint identities are invalid.");
            end
            if ~isempty(rows)
                [isTerminal,terminalRows] = ismember( ...
                    [txIds,rxIds], ...
                    terminalAttempts{:, ...
                        ["TransmitterId","ReceiverId"]},"rows");
                if ~all(isTerminal)
                    error( ...
                        "v2xsim:hook:invocations:" + ...
                        "OrphanInterferenceCounterfactual", ...
                        "Every counterfactual must identify a terminal link.");
                end
                expectedCounts = accumarray( ...
                    terminalRows,1, ...
                    [height(terminalAttempts),1]);
                if any( ...
                        expectedCounts ~= ...
                        terminalAttempts.InterfererCount)
                    error( ...
                        "v2xsim:hook:invocations:" + ...
                        "InterferenceCountMismatch", ...
                        "Terminal interferer counts must match " + ...
                        "counterfactual rows.");
                end
            elseif any(terminalAttempts.InterfererCount ~= 0)
                error( ...
                    "v2xsim:hook:invocations:" + ...
                    "InterferenceCountMismatch", ...
                    "Terminal interferer counts must match " + ...
                    "counterfactual rows.");
            end

            integerNames = [ ...
                "InterfererResourceId", ...
                "InterfererFrequencyResourceId"];
            for variableName = integerNames
                values = rows.(variableName);
                if ~isnumeric(values) || ~iscolumn(values) || ...
                        any(~isfinite(values)) || any(values < 1) || ...
                        any(fix(values) ~= values)
                    error( ...
                        "v2xsim:hook:invocations:" + ...
                        "InvalidInterferenceCounterfactuals", ...
                        "%s must contain positive integer values.", ...
                        variableName);
                end
            end
            relations = rows.ResourceRelation;
            removedPower = rows.RemovedInterferencePower;
            withoutSinr = rows.SinrWithoutInterfererDb;
            if ~isstring(relations) || ~iscolumn(relations) || ...
                    any(~ismember( ...
                        relations, ...
                        ["cochannel","adjacent_channel", ...
                        "half_duplex","other"])) || ...
                    ~isnumeric(removedPower) || ...
                    ~iscolumn(removedPower) || ...
                    ~isreal(removedPower) || ...
                    any(isnan(removedPower)) || ...
                    any(removedPower <= 0) || ...
                    ~isnumeric(withoutSinr) || ...
                    ~iscolumn(withoutSinr) || ...
                    ~isreal(withoutSinr) || any(isnan(withoutSinr))
                error( ...
                    "v2xsim:hook:invocations:" + ...
                    "InvalidInterferenceCounterfactuals", ...
                    "Counterfactual relations, powers, or SINRs are invalid.");
            end
            if any( ...
                    (relations == "half_duplex") ~= ...
                    (interfererIds == rxIds))
                error( ...
                    "v2xsim:hook:invocations:" + ...
                    "InvalidHalfDuplexEvidence", ...
                    "Half-duplex evidence must identify the actually " + ...
                    "transmitting receiver UE.");
            end
            if height(unique( ...
                    rows(:,[ ...
                        "TransmitterId","ReceiverId","InterfererId"]), ...
                    "rows")) ~= height(rows)
                error( ...
                    "v2xsim:hook:invocations:" + ...
                    "DuplicateInterferenceCounterfactual", ...
                    "Each terminal link may remove an interferer once.");
            end
        end
    end
end
