classdef AfterResourceAllocationDecisionInvocation < ...
        v2xsim.hook.invocation.Invocation
    %AFTERRESOURCEALLOCATIONDECISIONINVOCATION One sealed allocator step.

    properties (SetAccess = immutable)
        SimulationTimeSeconds (1,1) double ...
            {mustBeReal,mustBeFinite,mustBeNonnegative}
        AllocationEpoch (1,1) uint64 = uint64(0)
        Context
        Result
    end

    methods
        function obj = AfterResourceAllocationDecisionInvocation( ...
                simulationTimeSeconds,allocationEpoch,context,result)
            arguments (Input)
                simulationTimeSeconds (1,1) double ...
                    {mustBeReal,mustBeFinite,mustBeNonnegative}
                allocationEpoch (1,1) uint64
                context (1,1) ...
                    v2xsim.resource.ResourceAllocationContext
                result (1,1) ...
                    v2xsim.resource.ResourceAllocationResult
            end

            if context.NetworkSliceId ~= result.NetworkSliceId
                error( ...
                    "v2xsim:hook:invocations:" + ...
                    "ResourceAllocationSliceMismatch", ...
                    "The allocation context and result must belong " + ...
                    "to the same network slice.");
            end
            if ~isequal( ...
                    sort(context.UeIds), ...
                    sort(result.Assignments.UeId))
                error( ...
                    "v2xsim:hook:invocations:" + ...
                    "ResourceAllocationUeSetMismatch", ...
                    "The allocation context and result must contain " + ...
                    "the same UE identities.");
            end

            obj.SimulationTimeSeconds = simulationTimeSeconds;
            obj.AllocationEpoch = allocationEpoch;
            obj.Context = context;
            obj.Result = result;
        end
    end
end
