function [engineArguments, roadsideUnits] = compileEngineArguments( ...
        plan, runOptions)
%COMPILEENGINEARGUMENTS Compile a V7 plan for the established radio engine.
%   This is a one-way runtime compiler. The public configuration contract is
%   the typed, resolved TOML tree; legacy configuration files and arbitrary
%   dotted overrides are not accepted at the public boundary.

arguments (Input)
    plan (1, 1) v2xsim.runtime.CompiledSimulationPlan
    runOptions (1, 1) v2xsim.runtime.RunOptions
end

engineArguments = cell(1, 0);

append("simulation.RandomSeed", plan.Simulation.RandomSeed);
append("simulation.DurationSeconds", plan.Simulation.DurationSeconds);
append("simulation.RadioAccessMode", radioAccessMode(plan.Radio));
append("simulation.RunLabel", runOptions.RunLabel);
append("scenario.UpdateIntervalSeconds", ...
    plan.Scenario.UpdateIntervalSeconds);

scenarioType = plan.Scenario.Type;
scenario = plan.Scenario.(scenarioType);
append("scenario.Type", scenarioClassName(scenarioType));
append("scenarioOptions.RandomSeed", scenario.RandomSeed);
appendPresentScenarioOptions(scenarioType, scenario);
appendPositioning(plan.Positioning);

application = plan.Application;
packetGeneration = application.PacketGeneration;
append("application.ResourceReservationIntervalSeconds", ...
    application.ResourceReservationIntervalSeconds);
append("application.PacketGeneration.IntervalSeconds", ...
    packetGeneration.IntervalSeconds);
append("application.PacketGeneration.RandomComponentMeanSeconds", ...
    packetGeneration.RandomComponentMeanSeconds);
if packetGeneration.Mode == "EtsiCam"
    append("application.PacketGeneration.IntervalVariationSeconds", -1);
    discretization = packetGeneration.Cam.IntervalDiscretization;
    append("application.Cam.IntervalDiscretization", ...
        legacyCamDiscretization(discretization));
    if discretization ~= "Continuous"
        append("application.Cam.MaximumIntervalIncreasePercent", ...
            packetGeneration.Cam.MaximumIntervalIncreasePercent);
    end
else
    append("application.PacketGeneration.IntervalVariationSeconds", ...
        packetGeneration.IntervalVariationSeconds);
end
append("application.PacketSizeBytes", application.PacketSizeBytes);
append("channelLoad.Enabled", application.ChannelLoad.Enabled);
if application.ChannelLoad.Enabled
    append("channelLoad.MeasurementWindowSeconds", ...
        application.ChannelLoad.MeasurementWindowSeconds);
    append("channelLoad.UpdateStepsPerWindow", ...
        application.ChannelLoad.UpdateStepsPerWindow);
    append("congestionControl.Enabled", ...
        application.CongestionControl.Enabled);
    if application.CongestionControl.Enabled
        append("sidelink.CongestionControl." + ...
            "ChannelOccupancyLimitScale", ...
            application.CongestionControl.ChannelOccupancyLimitScale);
    end
end

radio = plan.Radio;
append("radio.BandwidthMHz", radio.BandwidthMHz);
append("radio.TransmitPowerDbm", radio.TransmitPowerDbm);
append("radio.FixedPowerDensityEnabled", ...
    radio.FixedPowerDensityEnabled);
append("radio.TransmitAntennaGainDb", radio.TransmitAntennaGainDb);
append("radio.ReceiveAntennaGainDb", radio.ReceiveAntennaGainDb);
append("radio.ReceiverNoiseFigureDb", radio.ReceiverNoiseFigureDb);
append("awareness.RangesMeters", plan.Awareness.RangesMeters);

if radio.Type == "Ieee80211p" || radio.Type == "Coexistence"
    appendIeee80211p(radio.Ieee80211p);
end
if radio.Type == "LteV2X" || ...
        (radio.Type == "Coexistence" && ...
         radio.Coexistence.SidelinkType == "LteV2X")
    append("lteV2x.Mcs", radio.LteV2X.Mcs);
    append("lteV2x.AdjacentPscchAndPsschEnabled", ...
        radio.LteV2X.AdjacentPscchAndPsschEnabled);
end
if radio.Type == "NrV2X" || ...
        (radio.Type == "Coexistence" && ...
         radio.Coexistence.SidelinkType == "NrV2X")
    appendNrV2x(radio.NrV2X);
end
if radio.Type ~= "Ieee80211p"
    appendSidelink(radio.Sidelink);
end

appendChannel(plan.Channel);
if radio.Type ~= "Ieee80211p"
    appendResourceAllocation(plan.ResourceAllocation);
end
appendOutputs(plan.Outputs);
if radio.Type == "Coexistence"
    appendCoexistence(plan.Coexistence, radio);
end

append("output.Directory", runOptions.OutputDirectory);
roadsideUnits = plan.Infrastructure.RoadsideUnits;

    function append(name, value)
        engineArguments(end + 1:end + 2) = {char(name), value};
    end

    function appendIfPresent(name, source, field)
        if isfield(source, field)
            append(name, source.(field));
        end
    end

    function appendPresentScenarioOptions(type, values)
        switch type
            case "BrownianMotion"
                fields = [ ...
                    "VehicleCount", "SimulationAreaSize", ...
                    "MeanVehicleSpeed", ...
                    "VehicleSpeedStandardDeviation"];
            case "BidirectionalHighway"
                fields = [ ...
                    "VehicleCount", "NLanes", "LaneWidth", ...
                    "RoadLength", "CentralDividerWidth", ...
                    "MeanVehicleSpeed", ...
                    "VehicleSpeedStandardDeviation", ...
                    "RerollSpeedOnWrapAround"];
            case "EtsiHighway"
                fields = [ ...
                    "TrafficModel", "Placement", ...
                    "MinimumRoadLength"];
            case "ExitRampHighway"
                fields = [ ...
                    "VehicleCount", "NLanes", "LaneWidth", ...
                    "RoadLength", "CentralDividerWidth", ...
                    "MeanVehicleSpeed", ...
                    "VehicleSpeedStandardDeviation", ...
                    "RerollSpeedOnWrapAround", ...
                    "ExitProbability", "MergeDistance"];
            case "Roundabout"
                fields = [ ...
                    "VehicleCount", "ExitLengths", "RoadWidth", ...
                    "InnerCircleDiameter", "MeanVehicleSpeed", ...
                    "VehicleSpeedStandardDeviation", ...
                    "RerollSpeedOnWrapAround"];
        end
        for field = fields
            append("scenarioOptions." + field, values.(field));
        end
    end

    function appendPositioning(values)
        errors = values.Errors;
        if isempty(errors)
            return
        end

        errorTypes = cellfun( ...
            @(positionError) positionError.Type, errors, ...
            UniformOutput=false);
        append("positioning.ErrorModules", ...
            char(join(string(errorTypes), ",")));

        for errorIndex = 1:numel(errors)
            positionError = errors{errorIndex};
            prefix = "positioning." + positionError.Type + ".";
            switch positionError.Type
                case "Gaussian"
                    fields = [ ...
                        "MeanMagnitudeMeters", ...
                        "StandardDeviationMeters", ...
                        "DisplacementRandomSeed", ...
                        "AffectedVehicleProbability", ...
                        "SelectionRandomSeed", ...
                        "ResetAfterSeconds"];
                    for field = fields
                        append(prefix + field, positionError.(field));
                    end
                    append(prefix + "ActiveRoutes", ...
                        char(join(positionError.ActiveRoutes, ",")));
                case "Delay"
                    append(prefix + "DelaySeconds", ...
                        positionError.DelaySeconds);
                case {"FalseExit", "FalseMerge"}
                    fields = [ ...
                        "AffectedVehicleProbability", ...
                        "ResetAfterSeconds", ...
                        "DisplacementScale", ...
                        "SelectionRandomSeed"];
                    for field = fields
                        append(prefix + field, positionError.(field));
                    end
            end
        end
    end

    function appendIeee80211p(values)
        append("ieee80211p.PreambleSensitivityDbm", ...
            values.PreambleSensitivityDbm);
        append("ieee80211p.LtePhysicalLayerEnabled", ...
            values.PhysicalLayer == "LteSurrogate");
        if values.PhysicalLayer == "LteSurrogate"
            append("ieee80211p.LtePhysicalLayerMcs", ...
                values.LteSurrogateMcs);
        else
            append("ieee80211p.Mcs", values.Mcs);
        end
        append("ieee80211p.RelativeInterferenceLevelModelEnabled", ...
            values.RelativeInterferenceLevelModelEnabled);
        append("ieee80211p.ContentionWindow", values.ContentionWindow);
        append("ieee80211p.AifsSlotCount", values.AifsSlotCount);
        append("ieee80211p.CcaThresholdWithoutDecodedPreambleDbm", ...
            values.CcaThresholdWithoutDecodedPreambleDbm);
        append("ieee80211p.CcaThresholdWithDecodedPreambleDbm", ...
            values.CcaThresholdWithDecodedPreambleDbm);

        repetitionModes = ["Static", "Deterministic", "Probabilistic"];
        repetitionMode = find( ...
            repetitionModes == values.Repetition.Mode, 1) - 1;
        append("itsG5.Repetition.Mode", repetitionMode);
        append("itsG5.Repetition.MaximumTransmissionCount", ...
            values.Repetition.MaximumTransmissionCount);
        append("itsG5.Repetition.BackoffMicroseconds", ...
            values.Repetition.BackoffMicroseconds);
        thresholds = values.Repetition.CbrThresholds;
        append("itsG5.Repetition.LowCbrThreshold", thresholds(1));
        append("itsG5.Repetition.MediumCbrThreshold", thresholds(2));
        append("itsG5.Repetition.HighCbrThreshold", thresholds(3));
    end

    function appendNrV2x(values)
        append("nrV2x.SubcarrierSpacingKilohertz", ...
            values.SubcarrierSpacingKilohertz);
        append("nrV2x.DmrsResourceElementCountPerSlot", ...
            values.DmrsResourceElementCountPerSlot);
        append("nrV2x.Mcs", values.Mcs);
        append("nrV2x.SciSymbolCount", values.SciSymbolCount);
        append("nrV2x.SciResourceBlockCount", ...
            values.SciResourceBlockCount);
    end

    function appendSidelink(values)
        if values.DuplexMode == "Half"
            duplexMode = "HD";
        else
            duplexMode = "FD";
        end
        append("sidelink.DuplexMode", duplexMode);
        if values.DuplexMode == "Full"
            append("sidelink.FullDuplex.ResidualSelfInterferenceDb", ...
                values.FullDuplex.ResidualSelfInterferenceDb);
        end
        append("sidelink.InBandEmissionEnabled", ...
            values.InBandEmissionEnabled);
        append("sidelink.Harq.MaximumTransmissionCount", ...
            values.MaximumTransmissionCount);
        append("sidelink.SciDecodeSinrThresholdDb", ...
            values.SciDecodeSinrThresholdDb);

        pool = values.ResourcePool;
        append("resourcePool.V2vSharePercent", pool.V2vSharePercent);
        appendIfPresent( ...
            "resourcePool.SubchannelSizeResourceBlocks", ...
            pool, "SubchannelSizeResourceBlocks");
        appendIfPresent( ...
            "resourcePool.MaximumFrequencyDomainBeaconResources", ...
            pool, "MaximumFrequencyDomainResources");
        append("resourcePool.PartialFrequencyOverlapEnabled", ...
            pool.PartialFrequencyOverlapEnabled);
    end

    function appendChannel(values)
        append("channel.RayleighFadingEnabled", ...
            values.RayleighFadingEnabled);
        packetError = values.PacketError;
        if packetError.Model == "Curves"
            append("channel.PacketErrorRateCurveDirectory", ...
                packetError.CurveDirectory);
            appendIfPresent( ...
                "channel.NlosPacketErrorRateCurveDirectory", ...
                packetError, "NlosCurveDirectory");
        else
            appendIfPresent( ...
                "ieee80211p.LosPacketDecodeSinrThresholdDb", ...
                packetError, "Ieee80211pLosThresholdDb");
            appendIfPresent( ...
                "sidelink.LosPacketDecodeSinrThresholdDb", ...
                packetError, "SidelinkLosThresholdDb");
        end

        pathLoss = values.PathLoss;
        models = [ ...
            "WinnerPlusB1", "SingleSlope", "TwoSlope", ...
            "ThreeSlope", "NrV2VNlos"];
        append("channel.PathLoss.Model", ...
            find(models == pathLoss.Model, 1) - 1);
        appendIfPresent( ...
            "channel.PathLoss.ReferenceLossAtOneMeterDb", ...
            pathLoss, "ReferenceLossAtOneMeterDb");
        appendIfPresent( ...
            "channel.PathLoss.Exponent1", pathLoss, "Exponent1");
        appendIfPresent( ...
            "channel.PathLoss.Exponent2", pathLoss, "Exponent2");
        appendIfPresent( ...
            "channel.PathLoss.Exponent3", pathLoss, "Exponent3");
        appendIfPresent( ...
            "channel.PathLoss.BreakpointDistance1Meters", ...
            pathLoss, "BreakpointDistance1Meters");
        appendIfPresent( ...
            "channel.PathLoss.BreakpointDistance2Meters", ...
            pathLoss, "BreakpointDistance2Meters");
        if values.Obstacles.BuildingAttenuationDbPerMeter ~= 0.4 || ...
                values.Obstacles.WallAttenuationDb ~= 6
            error( ...
                "v2xsim:runtime:UnsupportedObstacleConfiguration", ...
                "Obstacle attenuation is unavailable because V7 no " + ...
                "longer supports map-backed trace scenarios.");
        end
        append("channel.Shadowing.LosStandardDeviationDb", ...
            values.Shadowing.LosStandardDeviationDb);
        append("channel.Shadowing.NlosStandardDeviationDb", ...
            values.Shadowing.NlosStandardDeviationDb);
    end

    function appendResourceAllocation(values)
        typeMap = struct( ...
            ReuseDistance="ReuseDistance", ...
            MaximumReuseDistance="MaximumReuseDistance", ...
            MinimumReusePower="MinimumReusePower", ...
            SensingBased="ThreeGppAutonomous", ...
            Random="RandomBenchmark", ...
            Ordered="OrderedBenchmark");
        append("resourceAllocation.Type", typeMap.(values.Type));
        append("resourceAllocation.RandomSeed", values.RandomSeed);
        if plan.Radio.Type ~= "Ieee80211p" && ...
                plan.Radio.Sidelink.DuplexMode == "Full"
            append("resourceAllocation.FullDuplex." + ...
                "SelfInterferenceThresholdMultiplier", ...
                values.FullDuplex.SelfInterferenceThresholdMultiplier);
        end

        selected = values.(values.Type);
        switch values.Type
            case "ReuseDistance"
                append("resourceAllocation.Controlled." + ...
                    "PositionError95PercentileMeters", ...
                    selected.PositionError95PercentileMeters);
                append("resourceAllocation.Controlled." + ...
                    "PositionUpdateIntervalSeconds", ...
                    selected.PositionUpdateIntervalSeconds);
                append("resourceAllocation.Controlled.ReuseMarginMeters", ...
                    selected.ReuseMarginMeters);
                append("resourceAllocation.Controlled." + ...
                    "ReassignmentIntervalSeconds", ...
                    selected.ReassignmentIntervalSeconds);
            case "MaximumReuseDistance"
                append("resourceAllocation.Controlled." + ...
                    "ReassignmentIntervalSeconds", ...
                    selected.ReassignmentIntervalSeconds);
            case "MinimumReusePower"
                append("resourceAllocation.Controlled." + ...
                    "ReassignmentIntervalSeconds", ...
                    selected.ReassignmentIntervalSeconds);
                append("resourceAllocation.Controlled." + ...
                    "KnownShadowingEnabled", ...
                    selected.KnownShadowingEnabled);
            case "SensingBased"
                appendSensingBased(selected);
            case "Random"
                appendIfPresent( ...
                    "resourceAllocation.Autonomous." + ...
                        "SelectionWindowStartMilliseconds", ...
                    selected, "SelectionWindowStartMilliseconds");
                append("resourceAllocation.Autonomous." + ...
                    "SelectionWindowEndMilliseconds", ...
                    selected.SelectionWindowEndMilliseconds);
        end
    end

    function appendSensingBased(values)
        mappings = [ ...
            "ReevaluationEnabled", "ReevaluationEnabled"; ...
            "ReevaluateAfterSkippedTransmissionEnabled", ...
                "ReevaluateAfterSkippedTransmissionEnabled"; ...
            "ReselectEveryPacketEnabled", "ReselectEveryPacketEnabled"; ...
            "KeepResourceProbability", "KeepResourceProbability"; ...
            "MaximumConsecutiveReservationIntervals", ...
                "MaximumConsecutiveReservationIntervals"; ...
            "MinimumCandidateFraction", "MinimumCandidateFraction"; ...
            "L2CandidateFraction", "L2CandidateFraction"; ...
            "L2RankingEnabled", "L2RankingEnabled"; ...
            "AverageSensingEnabled", "AverageSensingEnabled"; ...
            "SensingWindowSeconds", "SensingWindowSeconds"; ...
            "ReselectionCounterMinimum", "ReselectionCounterMinimum"; ...
            "ReselectionCounterMaximum", "ReselectionCounterMaximum"; ...
            "SensingThresholdDbm", "SensingThresholdDbm"; ...
            "SelectionWindowStartMilliseconds", ...
                "SelectionWindowStartMilliseconds"; ...
            "SelectionWindowEndMilliseconds", ...
                "SelectionWindowEndMilliseconds"];
        for mappingIndex = 1:height(mappings)
            field = mappings(mappingIndex, 1);
            appendIfPresent( ...
                "resourceAllocation.Autonomous." + ...
                    mappings(mappingIndex, 2), ...
                values, field);
        end
    end

    function appendOutputs(values)
        append("output.AverageNeighborCount.Enabled", ...
            values.AverageNeighborCount.Enabled);
        append("output.VehicleKinematics.Enabled", ...
            values.VehicleKinematics.Enabled);
        append("output.PositionErrorTrace.Enabled", ...
            values.PositionErrorTrace.Enabled);
        append("output.PositionErrorTrace.FlushRowCount", ...
            values.PositionErrorTrace.FlushRowCount);
        append("output.ControllerDiagnostics.Enabled", ...
            values.ControllerDiagnostics.Enabled);
        append("output.ControllerDiagnostics.TopK", ...
            values.ControllerDiagnostics.TopK);
        append("output.ControllerDiagnostics.RankDisplacementEnabled", ...
            values.ControllerDiagnostics.RankDisplacementEnabled);
        append("output.ControllerDiagnostics.FlushRowCount", ...
            values.ControllerDiagnostics.FlushRowCount);
        append("output.PacketFateTrace.Enabled", ...
            values.PacketFateTrace.Enabled);
        append("output.PacketFateTrace.FlushRowCount", ...
            values.PacketFateTrace.FlushRowCount);
        append("output.PacketFateTrace.FileFormat", ...
            values.PacketFateTrace.FileFormat);
        append("output.InterferenceClassification.Enabled", ...
            values.InterferenceClassification.Enabled);
        append("output.UpdateDelay.Enabled", values.UpdateDelay.Enabled);
        append("output.WirelessBlindSpot.Enabled", ...
            values.WirelessBlindSpot.Enabled);
        if values.WirelessBlindSpot.Enabled
            append("output.WirelessBlindSpot.MaximumDelaySeconds", ...
                values.WirelessBlindSpot.MaximumDelaySeconds);
            append("output.WirelessBlindSpot.BinWidthSeconds", ...
                values.WirelessBlindSpot.BinWidthSeconds);
        end
        append("output.PacketDelay.Enabled", values.PacketDelay.Enabled);
        append("output.DataAge.Enabled", values.DataAge.Enabled);
        if values.UpdateDelay.Enabled || values.PacketDelay.Enabled || ...
                values.DataAge.Enabled
            append("output.DelayMetrics.BinWidthSeconds", ...
                values.DelayMetrics.BinWidthSeconds);
        end
        append("output.PacketReceptionRatio.Enabled", ...
            values.PacketReceptionRatio.Enabled);
        if values.PacketReceptionRatio.Enabled
            append("output.PacketReceptionRatio.DistanceBinWidthMeters", ...
                values.PacketReceptionRatio.DistanceBinWidthMeters);
        end
        append("output.ChannelBusyRatio.Enabled", ...
            values.ChannelBusyRatio.Enabled);
    end

    function appendCoexistence(values, radioValues)
        append("coexistence.VehiclePattern.SidelinkVehicleCount", ...
            values.VehiclePattern.SidelinkVehicleCount);
        append("coexistence.VehiclePattern.ItsG5VehicleCount", ...
            values.VehiclePattern.ItsG5VehicleCount);
        if radioValues.Coexistence.InterferenceModel == "Independent"
            return
        end
        methodMap = struct( ...
            Standard="0", MethodA="A", MethodB="B", ...
            MethodC="C", MethodF="F");
        append("coexistence.Method", ...
            char(methodMap.(values.Method)));
        if values.Method ~= "Standard"
            append("coexistence.Superframe.DurationSeconds", ...
                values.Superframe.DurationSeconds);
            append("coexistence.Superframe.SlotAllocationMode", ...
                char(lower(values.Superframe.SlotManagement)));
            if values.Superframe.SlotManagement == "Static"
                appendIfPresent( ...
                    "coexistence.Superframe.SidelinkPortionEndSeconds", ...
                    values.Superframe, "SidelinkPortionEndSeconds");
            end
            selected = values.(values.Method);
            switch values.Method
                case "MethodA"
                    appendIfPresent( ...
                        "coexistence.MethodA.GuardIntervalSeconds", ...
                        selected, "GuardIntervalSeconds");
                    append("coexistence.MethodA.EnhancementVariant", ...
                        selected.EnhancementVariant);
                    append("coexistence.MethodA." + ...
                        "SynchronizationErrorSeconds", ...
                        selected.SynchronizationErrorSeconds);
                    append("coexistence.MethodA." + ...
                        "LegacyItsG5NodesEnabled", ...
                        selected.LegacyItsG5NodesEnabled);
                    appendIfPresent( ...
                        "coexistence.MethodA." + ...
                            "ItsG5PerceivedSidelinkEndSeconds", ...
                        selected, "ItsG5PerceivedSidelinkEndSeconds");
                case "MethodB"
                    appendIfPresent( ...
                        "coexistence.MethodB.EnergySignalLeadTimeSeconds", ...
                        selected, "EnergySignalLeadTimeSeconds");
                    append("coexistence.MethodB." + ...
                        "AllNodesTransmitInEmptySubframes", ...
                        selected.AllNodesTransmitInEmptySubframes);
                case "MethodC"
                    append("coexistence.MethodC.TimeGapVariant", ...
                        selected.TimeGapVariant);
                    append("coexistence.MethodC." + ...
                        "DetectAndCancelItsG5Enabled", ...
                        selected.DetectAndCancelItsG5Enabled);
                    append("coexistence.MethodC." + ...
                        "ModifiedContentionWindowEnabled", ...
                        selected.ModifiedContentionWindowEnabled);
                    append("coexistence.MethodC." + ...
                        "MultipleSubframeIndicationEnabled", ...
                        selected.MultipleSubframeIndicationEnabled);
                case "MethodF"
                    append("coexistence.MethodF.GuardIntervalEnabled", ...
                        selected.GuardIntervalEnabled);
            end
        end
        append("coexistence.Cbr.SidelinkVariant", ...
            values.ChannelLoad.SidelinkVariant);
        append("coexistence.Cbr.TotalVariant", ...
            values.ChannelLoad.TotalVariant);
    end
end

function result = radioAccessMode(radio)
switch radio.Type
    case "Ieee80211p"
        result = "80211p";
    case "LteV2X"
        result = "LTE-V2X";
    case "NrV2X"
        result = "NR-V2X";
    case "Coexistence"
        if radio.Coexistence.InterferenceModel == "Independent"
            if radio.Coexistence.SidelinkType == "LteV2X"
                result = "COEX-NO-INTERF";
            else
                result = "COEX-NO-INTERF-5G";
            end
        elseif radio.Coexistence.SidelinkType == "LteV2X"
            result = "COEX-STD-INTERF";
        else
            result = "COEX-STD-INTERF-5G";
        end
end
end

function result = scenarioClassName(type)
switch type
    case "BrownianMotion"
        result = "BrownianMotionScenario";
    case "BidirectionalHighway"
        result = "BidirectionalHighwayScenario";
    case "EtsiHighway"
        result = "EtsiHighwayScenario";
    case "ExitRampHighway"
        result = "ExitRampHighwayScenario";
    case "Roundabout"
        result = "RoundaboutScenario";
end
end

function result = legacyCamDiscretization(value)
switch value
    case "Continuous"
        result = "null";
    case "AllSteps"
        result = "allSteps";
    case "AllocationAligned"
        result = "allocationAligned";
end
end
