%% 10 - Run NR-V2X Mode 2 and inspect the beacon-resource grid
% The configuration authors every public SensingBased option. It is a
% spelling and provenance reference, not a universally optimal parameter set.

exampleScriptDirectory = fileparts(mfilename("fullpath"));
[exampleResults,exampleOutputDirectory] = runExample( ...
    exampleScriptDirectory);
clear exampleScriptDirectory

disp(exampleResults.Overview)
disp(exampleResults.Grid)
fprintf("Completed output: %s\n",exampleOutputDirectory);

function [results,outputDirectory] = runExample(exampleDirectory)
timer = tic;
configurationFile = fullfile( ...
    exampleDirectory,"10_nr_mode2_all_options.toml");
outputDirectory = string(tempname);
template = v2xsim.config.load(configurationFile);
configuration = template.resolve();
simulationTimer = tic;
simulationResult = v2xsim.runSimulation( ...
    configuration, ...
    OutputDirectory=outputDirectory, ...
    RunLabel="nr-mode2-all-options");
simulationElapsedSeconds = toc(simulationTimer);
outputDirectory = simulationResult.RunDirectory;
summary = jsondecode(fileread(fullfile( ...
    simulationResult.RunDirectory,"simulation_summary.json")));

metadata = summary.Configuration.ResourceAllocation.Metadata;
assert(string(summary.Configuration.RadioAccessMode) == "NR-V2X", ...
    "The Mode 2 example did not run NR-V2X.");
assert(string(metadata.Type) == "SensingBased", ...
    "The Mode 2 example did not select SensingBased allocation.");
assert(string(metadata.Category) == "Autonomous", ...
    "The Mode 2 example did not use autonomous allocation.");

pool = summary.Configuration.ResourcePool;
gridSummary = table( ...
    metadata.NumberTimeSlots, ...
    metadata.NumberFrequencyResources, ...
    pool.BeaconResourceCount, ...
    metadata.SlotDurationSeconds, ...
    pool.PhysicalResourceBlockCount, ...
    pool.SubchannelCount, ...
    VariableNames=[ ...
        "TimeSlots","FrequencyResources","TotalBeaconResources", ...
        "SlotDurationSeconds","BeaconPhysicalResourceBlocks", ...
        "SubchannelsPerBeacon"]);
assert( ...
    gridSummary.TotalBeaconResources == ...
        gridSummary.TimeSlots * gridSummary.FrequencyResources, ...
    "The recorded beacon-resource dimensions are inconsistent.");

prrFiles = dir(fullfile( ...
    outputDirectory,"packet_reception_ratio_*.csv"));
assert(isscalar(prrFiles), ...
    "The NR Mode 2 example did not produce its PRR artifact.");
prr = readPrr(fullfile(prrFiles(1).folder,prrFiles(1).name));

overview = table( ...
    string(summary.Configuration.RadioAccessMode), ...
    string(metadata.Type), ...
    string(metadata.Category), ...
    metadata.MaximumTransmissionCount, ...
    summary.Results.CellularSidelink.AverageUeCount, ...
    cellularPacketReceptionRatio(summary), ...
    VariableNames=[ ...
        "RadioAccessMode","Allocator","Category", ...
        "MaximumTransmissionCount","AverageUeCount", ...
        "PacketReceptionRatio"]);

figure(Name="V7 NR Mode 2 quickstart");
plot( ...
    prr.DistanceUpperBoundMeters,prr.PacketReceptionRatio, ...
    "o-",LineWidth=1.2);
grid on
xlabel("Distance upper bound (m)")
ylabel("Packet reception ratio")
ylim([0,1])
title("NR-V2X autonomous Mode 2")

elapsedSeconds = toc(timer);
if elapsedSeconds > 30
    warning( ...
        "v2xsimexample:SlowExample", ...
        "This example took %.1f seconds on this computer.", ...
        elapsedSeconds);
end

results = struct( ...
    SimulationResult=simulationResult, ...
    Summary=summary, ...
    Overview=overview, ...
    Grid=gridSummary, ...
    PacketReceptionRatio=prr, ...
    SimulationElapsedSeconds=simulationElapsedSeconds, ...
    ElapsedSeconds=elapsedSeconds);
end

function result = readPrr(filename)
values = readmatrix(filename);
result = array2table( ...
    values, ...
    VariableNames=[ ...
        "DistanceUpperBoundMeters","CorrectCount","ErrorCount", ...
        "BlockedCount","OpportunityCount","PacketReceptionRatio"]);
end

function ratio = cellularPacketReceptionRatio(summary)
metrics = summary.Results.CellularSidelink.AwarenessRangeMetrics;
if iscell(metrics)
    metric = metrics{end};
else
    metric = metrics(end);
end
ratio = metric.PacketReceptionRatio;
if isempty(ratio)
    ratio = NaN;
end
end
