%% 10 - Run NR-V2X Mode 2 and inspect the beacon-resource grid
% The configuration authors every public SensingBased option. It is a
% spelling and provenance reference, not a universally optimal parameter set.

exampleScriptDirectory = fileparts(mfilename("fullpath"));
[exampleResults,exampleOutputDirectory] = runExample( ...
    exampleScriptDirectory);
clear exampleScriptDirectory

disp(exampleResults.Overview)
disp(exampleResults.Grid)
fprintf("Completed output: %s\n",exampleOutputDirectory);

function [results,outputDirectory] = runExample(exampleDirectory)
timer = tic;
configurationFile = fullfile( ...
    exampleDirectory,"10_nr_mode2_all_options.toml");
outputDirectory = string(tempname);
template = v2xsim.config.load(configurationFile);
repetitionCount = 5;
baseSeed = template.Data.Simulation.RandomSeed;
prrRows = table();
simulationTimer = tic;
for repetition = 1:repetitionCount
    configuration = template.resolve(Patch=v2xsim.config.patch(struct( ...
        "Simulation",struct("RandomSeed",baseSeed + repetition - 1))));
    repetitionOutputDirectory = string(tempname);
    simulationResult = v2xsim.runSimulation( ...
        configuration, ...
        OutputDirectory=repetitionOutputDirectory, ...
        RunLabel="nr-mode2-all-options-repetition-" + repetition);
    outputDirectory = simulationResult.RunDirectory;
    prrRows = [prrRows; ...
        v2xsim.analysis.readDeliveryPrrArtifact(outputDirectory)]; %#ok<AGROW>
end
simulationElapsedSeconds = toc(simulationTimer);
summary = jsondecode(fileread(fullfile( ...
    simulationResult.RunDirectory,"simulation_summary.json")));

metadata = summary.Configuration.ResourceAllocation.Metadata;
assert(string(summary.Configuration.RadioAccessMode) == "NR-V2X", ...
    "The Mode 2 example did not run NR-V2X.");
assert(string(metadata.Type) == "SensingBased", ...
    "The Mode 2 example did not select SensingBased allocation.");
assert(string(metadata.Category) == "Autonomous", ...
    "The Mode 2 example did not use autonomous allocation.");

pool = summary.Configuration.ResourcePool;
gridSummary = table( ...
    metadata.NumberTimeSlots, ...
    metadata.NumberFrequencyResources, ...
    pool.BeaconResourceCount, ...
    metadata.SlotDurationSeconds, ...
    pool.PhysicalResourceBlockCount, ...
    pool.SubchannelCount, ...
    VariableNames=[ ...
        "TimeSlots","FrequencyResources","TotalBeaconResources", ...
        "SlotDurationSeconds","BeaconPhysicalResourceBlocks", ...
        "SubchannelsPerBeacon"]);
assert( ...
    gridSummary.TotalBeaconResources == ...
        gridSummary.TimeSlots * gridSummary.FrequencyResources, ...
    "The recorded beacon-resource dimensions are inconsistent.");

prr = v2xsim.analysis.poolPacketReceptionCounts(prrRows, ...
    GroupVariables=strings(1,0));
[deliveryPrrRangeMeters,deliveryPrrRangeStatus,plotCurve] = ...
    v2xsim.analysis.prrThresholdRange(prr);

overview = table( ...
    string(summary.Configuration.RadioAccessMode), ...
    string(metadata.Type), ...
    string(metadata.Category), ...
    metadata.MaximumTransmissionCount, ...
    summary.Results.CellularSidelink.AverageUeCount, ...
    cellularPacketReceptionRatio(summary), ...
    VariableNames=[ ...
        "RadioAccessMode","Allocator","Category", ...
        "MaximumTransmissionCount","AverageUeCount", ...
        "PacketReceptionRatio"]);

figure(Name="V7 NR Mode 2 quickstart");
plot( ...
    plotCurve.DistanceMeters,plotCurve.DeliveryPrr, ...
    "o-",LineWidth=1.2,DisplayName="Delivery PRR");
hold on
yline(0.9,"--",DisplayName="90% threshold");
if isfinite(deliveryPrrRangeMeters)
    xline( ...
        deliveryPrrRangeMeters,":", ...
        "90% range: " + string(sprintf( ...
            "%.1f m (%s)",deliveryPrrRangeMeters, ...
            char(deliveryPrrRangeStatus))), ...
        DisplayName="90% range");
    if deliveryPrrRangeStatus == "Crossed"
        plot( ...
            deliveryPrrRangeMeters,0.9,"o", ...
            DisplayName="Threshold crossing");
    end
else
    text(0.02,0.08,"90% range unavailable: incomplete distance grid", ...
        Units="normalized");
end
hold off
grid on
xlabel("Distance (m)")
ylabel("Delivery PRR")
ylim([0,1])
title("NR-V2X autonomous Mode 2: delivery PRR")
legend(Location="best")

elapsedSeconds = toc(timer);
if elapsedSeconds > 30
    warning( ...
        "v2xsimexample:SlowExample", ...
        "This example took %.1f seconds on this computer.", ...
        elapsedSeconds);
end

results = struct( ...
    SimulationResult=simulationResult, ...
    Summary=summary, ...
    Overview=overview, ...
    Grid=gridSummary, ...
    PacketReceptionRatio=prr, ...
    DeliveryPrrByDistance=prr, ...
    DeliveryPrrRangeMeters=deliveryPrrRangeMeters, ...
    DeliveryPrrRangeStatus=deliveryPrrRangeStatus, ...
    RepetitionCount=repetitionCount, ...
    SimulationElapsedSeconds=simulationElapsedSeconds, ...
    ElapsedSeconds=elapsedSeconds);
end

function ratio = cellularPacketReceptionRatio(summary)
metrics = summary.Results.CellularSidelink.AwarenessRangeMetrics;
if iscell(metrics)
    metric = metrics{end};
else
    metric = metrics(end);
end
ratio = metric.PacketReceptionRatio;
if isempty(ratio)
    ratio = NaN;
end
end
