%% 08 - Sweep the three 3GPP freeway traffic presets with NR Mode 1
% The run is intentionally short. It demonstrates a campaign layout and
% paired seed policy, not a statistically supported density conclusion.

exampleScriptDirectory = fileparts(mfilename("fullpath"));
[exampleResults,exampleOutputDirectory] = runExample( ...
    exampleScriptDirectory);
clear exampleScriptDirectory

disp(exampleResults.Campaign)
fprintf("Completed outputs: %s\n",exampleOutputDirectory);

function [results,outputDirectory] = runExample(exampleDirectory)
timer = tic;
configurationFile = fullfile( ...
    exampleDirectory,"config","08_nr_mode1_etsi_campaign.toml");
outputDirectory = string(tempname);
trafficModels = [ ...
    "HighSpeedLowDensity"; ...
    "MediumSpeedMediumDensity"; ...
    "LowSpeedHighDensity"];

averageVehicleCount = zeros(size(trafficModels));
packetReceptionRatio = zeros(size(trafficModels));
simulationElapsedSeconds = zeros(size(trafficModels));
runDirectories = strings(size(trafficModels));
summaries = cell(size(trafficModels));

for modelIndex = 1:numel(trafficModels)
    trafficModel = trafficModels(modelIndex);
    runDirectories(modelIndex) = fullfile(outputDirectory,trafficModel);
    patchData = struct( ...
        Scenario=struct(EtsiHighway=struct( ...
            TrafficModel=trafficModel)), ...
        Simulation=struct(RandomSeed=18), ...
        ResourceAllocation=struct(RandomSeed=208));
    [summary,simulationElapsedSeconds(modelIndex)] = ...
        runV7ExampleSimulation( ...
            configurationFile,runDirectories(modelIndex), ...
            patchData,"etsi-" + trafficModel);
    summaries{modelIndex} = summary;
    averageVehicleCount(modelIndex) = ...
        summary.Results.CellularSidelink.AverageUeCount;
    packetReceptionRatio(modelIndex) = ...
        cellularPacketReceptionRatio(summary);
end

campaign = table( ...
    trafficModels,averageVehicleCount,packetReceptionRatio,runDirectories, ...
    VariableNames=[ ...
        "TrafficModel","AverageVehicleCount", ...
        "PacketReceptionRatio","RunDirectory"]);

figure(Name="V7 NR Mode 1 ETSI campaign");
plot( ...
    campaign.AverageVehicleCount,campaign.PacketReceptionRatio, ...
    "o-",LineWidth=1.2);
grid on
xlabel("Average vehicle count")
ylabel("Packet reception ratio")
ylim([0,1])
title("Short workflow check across traffic presets")

elapsedSeconds = toc(timer);
warnIfSlowV7Example(elapsedSeconds);
results = struct( ...
    Summaries={summaries}, ...
    Campaign=campaign, ...
    SimulationElapsedSeconds=simulationElapsedSeconds, ...
    ElapsedSeconds=elapsedSeconds);
end
