%% 01 - Run a first V7 simulation
% A configuration file supplies the experiment baseline. The script supplies
% a fresh output directory because every V7 run exclusively owns its output.

exampleScriptDirectory = fileparts(mfilename("fullpath"));
[exampleResults,exampleOutputDirectory] = runExample( ...
    exampleScriptDirectory);
clear exampleScriptDirectory

disp(exampleResults.Overview)
fprintf("Completed output: %s\n",exampleOutputDirectory);

function [results,outputDirectory] = runExample(exampleDirectory)
timer = tic;
configurationFile = fullfile( ...
    exampleDirectory,"config","01_basic_nr_v2x.toml");
outputDirectory = string(tempname);

[summary,simulationElapsedSeconds] = runV7ExampleSimulation( ...
    configurationFile,outputDirectory,struct(),"v7-first-run");
assert(summary.SchemaVersion == 2, ...
    "The example expected completion-summary schema version 2.");

overview = table( ...
    string(summary.Run.RunLabel), ...
    string(summary.Configuration.RadioAccessMode), ...
    string(summary.Configuration.Scenario.Type), ...
    summary.Results.CellularSidelink.AverageUeCount, ...
    cellularPacketReceptionRatio(summary), ...
    VariableNames=[ ...
        "RunLabel","RadioAccessMode","Scenario", ...
        "AverageUeCount","PacketReceptionRatio"]);
elapsedSeconds = toc(timer);
warnIfSlowV7Example(elapsedSeconds);

results = struct( ...
    Summary=summary, ...
    Overview=overview, ...
    SimulationElapsedSeconds=simulationElapsedSeconds, ...
    ElapsedSeconds=elapsedSeconds);
end
