%% 03 - Compare named cellular-sidelink resource allocators
% V7 selects allocators by descriptive names instead of numeric algorithm IDs.

exampleScriptDirectory = fileparts(mfilename("fullpath"));
[exampleResults,exampleOutputDirectory] = runExample( ...
    exampleScriptDirectory);
clear exampleScriptDirectory

disp(exampleResults.Allocators)
fprintf("Completed outputs: %s\n",exampleOutputDirectory);

function [results,outputDirectory] = runExample(exampleDirectory)
timer = tic;
configurationFile = fullfile( ...
    exampleDirectory,"config","03_named_allocators.cfg");
outputDirectory = string(tempname);
allocatorTypes = [ ...
    "ReuseDistance", ...
    "MaximumReuseDistance", ...
    "MinimumReusePower", ...
    "ThreeGppAutonomous", ...
    "RandomBenchmark", ...
    "OrderedBenchmark"];

category = strings(numel(allocatorTypes),1);
networkSliceId = strings(numel(allocatorTypes),1);
randomSeed = zeros(numel(allocatorTypes),1);
packetReceptionRatio = zeros(numel(allocatorTypes),1);
simulationElapsedSeconds = zeros(numel(allocatorTypes),1);
summaries = cell(numel(allocatorTypes),1);
for allocatorIndex = 1:numel(allocatorTypes)
    allocatorType = allocatorTypes(allocatorIndex);
    runDirectory = fullfile(outputDirectory,allocatorType);
    [summary,simulationElapsedSeconds(allocatorIndex)] = ...
        runV7ExampleSimulation( ...
            configurationFile,runDirectory, { ...
                "resourceAllocation.Type",allocatorType});
    metadata = summary.Configuration.ResourceAllocation.Metadata;
    assert(string(metadata.Type) == allocatorType, ...
        "The summary did not retain the requested allocator type.");
    summaries{allocatorIndex} = summary;
    category(allocatorIndex) = string(metadata.Category);
    networkSliceId(allocatorIndex) = string(metadata.NetworkSliceId);
    randomSeed(allocatorIndex) = metadata.RandomSeed;
    packetReceptionRatio(allocatorIndex) = ...
        cellularPacketReceptionRatio(summary);
end

allocatorTable = table( ...
    allocatorTypes.',category,networkSliceId,randomSeed, ...
    packetReceptionRatio, ...
    VariableNames=[ ...
        "Allocator","Category","NetworkSliceId","RandomSeed", ...
        "PacketReceptionRatio"]);
elapsedSeconds = toc(timer);
warnIfSlowV7Example(elapsedSeconds);
results = struct( ...
    Summaries={summaries}, ...
    Allocators=allocatorTable, ...
    SimulationElapsedSeconds=simulationElapsedSeconds, ...
    ElapsedSeconds=elapsedSeconds);
end
