%% 02 - Reproduce traffic independently of radio randomness
% Both runs use the same scenarioOptions.RandomSeed but different simulation
% and resource-allocation seeds. Their vehicle trajectories remain identical.

exampleScriptDirectory = fileparts(mfilename("fullpath"));
[exampleResults,exampleOutputDirectory] = runExample( ...
    exampleScriptDirectory);
clear exampleScriptDirectory

disp(exampleResults.Comparison)
fprintf("Completed outputs: %s\n",exampleOutputDirectory);

function [results,outputDirectory] = runExample(exampleDirectory)
timer = tic;
configurationFile = fullfile( ...
    exampleDirectory,"02_reproducible_traffic.toml");
outputDirectory = string(tempname);
runDirectories = fullfile(outputDirectory,["radio-seed-21","radio-seed-22"]);

template = v2xsim.config.load(configurationFile);
firstPatch = v2xsim.config.patch(struct( ...
    Simulation=struct(RandomSeed=21), ...
    ResourceAllocation=struct(RandomSeed=221)));
firstConfiguration = template.resolve(Patch=firstPatch);
simulationTimer = tic;
firstSimulationResult = v2xsim.runSimulation( ...
    firstConfiguration, ...
    OutputDirectory=runDirectories(1), ...
    RunLabel="radio-seed-21");
firstElapsed = toc(simulationTimer);
firstSummary = jsondecode(fileread(fullfile( ...
    firstSimulationResult.RunDirectory,"simulation_summary.json")));

secondPatch = v2xsim.config.patch(struct( ...
    Simulation=struct(RandomSeed=22), ...
    ResourceAllocation=struct(RandomSeed=222)));
secondConfiguration = template.resolve(Patch=secondPatch);
simulationTimer = tic;
secondSimulationResult = v2xsim.runSimulation( ...
    secondConfiguration, ...
    OutputDirectory=runDirectories(2), ...
    RunLabel="radio-seed-22");
secondElapsed = toc(simulationTimer);
secondSummary = jsondecode(fileread(fullfile( ...
    secondSimulationResult.RunDirectory,"simulation_summary.json")));
runDirectories = [ ...
    firstSimulationResult.RunDirectory, ...
    secondSimulationResult.RunDirectory];

firstKinematics = readtable( ...
    fullfile(runDirectories(1),"vehicle_kinematics.csv"), ...
    TextType="string");
secondKinematics = readtable( ...
    fullfile(runDirectories(2),"vehicle_kinematics.csv"), ...
    TextType="string");
sortVariables = ["SimulationTimeSeconds","VehicleId"];
firstKinematics = sortrows(firstKinematics,sortVariables);
secondKinematics = sortrows(secondKinematics,sortVariables);
trajectoryVariables = ["SimulationTimeSeconds","VehicleId", ...
    "X","Y","vX","vY","aX","aY"];
trajectoriesMatch = isequaln( ...
    firstKinematics(:,trajectoryVariables), ...
    secondKinematics(:,trajectoryVariables));
assert(trajectoriesMatch, ...
    "The scenario-owned seed did not reproduce the traffic trajectory.");

comparison = table( ...
    [firstSummary.Run.RandomSeed;secondSummary.Run.RandomSeed], ...
    [firstSummary.Configuration.Scenario.Options.RandomSeed; ...
        secondSummary.Configuration.Scenario.Options.RandomSeed], ...
    [firstSummary.Configuration.ResourceAllocation.Metadata.RandomSeed; ...
        secondSummary.Configuration.ResourceAllocation.Metadata.RandomSeed], ...
    repmat(trajectoriesMatch,2,1), ...
    VariableNames=[ ...
        "SimulationSeed","ScenarioSeed","AllocatorSeed", ...
        "TrajectoriesMatch"]);

vehicleId = firstKinematics.VehicleId(1);
firstVehicle = firstKinematics(firstKinematics.VehicleId == vehicleId,:);
secondVehicle = secondKinematics(secondKinematics.VehicleId == vehicleId,:);
figure(Name="V7 reproducible traffic");
plot(firstVehicle.X,firstVehicle.Y,"o-",DisplayName="run 1");
hold on
plot(secondVehicle.X,secondVehicle.Y,"x--",DisplayName="run 2");
hold off
axis equal
grid on
xlabel("X (m)")
ylabel("Y (m)")
title("Identical trajectory for vehicle " + vehicleId)
legend(Location="best")

elapsedSeconds = toc(timer);
if elapsedSeconds > 30
    warning( ...
        "v2xsimexample:SlowExample", ...
        "This example took %.1f seconds on this computer.", ...
        elapsedSeconds);
end
results = struct( ...
    SimulationResults={{firstSimulationResult,secondSimulationResult}}, ...
    Summaries={{firstSummary,secondSummary}}, ...
    Comparison=comparison, ...
    TrajectoriesMatch=trajectoriesMatch, ...
    SimulationElapsedSeconds=[firstElapsed,secondElapsed], ...
    ElapsedSeconds=elapsedSeconds);
end
