classdef ExitRampPositionErrorContext < ...
        v2xsim.positioning.RoutePositionErrorContext
    %EXITRAMPPOSITIONERRORCONTEXT Snapshot for exit-ramp error modules.
    %   In addition to generic timing and ground-truth positions, this
    %   context exposes the exit-ramp geometry, lane topology, current lane
    %   coordinates, and current route state for every vehicle.

    properties (SetAccess = immutable)
        Geometry (1, 1) ...
            v2xsim.vehicle.scenario.highway.ExitRampGeometry = ...
            v2xsim.vehicle.scenario.highway.ExitRampGeometry( ...
                2, 1, 1, 0, 0)
        LaneNetwork (1, 1) ...
            v2xsim.vehicle.scenario.highway.LaneNetwork = ...
            v2xsim.vehicle.scenario.highway.LaneNetwork()
        VehicleLaneStates table ...
            {v2xsim.vehicle.scenario.validation.mustBeVehicleLaneStateTable} = ...
            table( ...
                strings(0, 1), zeros(0, 1), zeros(0, 1), ...
                VariableNames=[ ...
                    "LaneId", "Progress", "LateralOffsetMeters"])
        VehicleRouteStates table = table()
    end

    methods
        function obj = ExitRampPositionErrorContext( ...
                scenario, simulationTimeSeconds, ...
                timeStepSeconds, simulationDurationSeconds)
            arguments (Input)
                scenario (1, 1) ...
                    v2xsim.vehicle.scenarios.ExitRampHighwayScenario
                simulationTimeSeconds (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative}
                timeStepSeconds (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBePositive}
                simulationDurationSeconds (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBePositive}
            end

            actualPositions = ...
                scenario.VehicleKinematics(:, ["X", "Y"]);
            obj = obj@v2xsim.positioning.RoutePositionErrorContext( ...
                actualPositions, ...
                simulationTimeSeconds, ...
                timeStepSeconds, ...
                simulationDurationSeconds);

            vehicleLaneStates = scenario.VehicleLaneStates;
            vehicleRouteStates = scenario.VehicleRouteStates;
            obj.validateVehicleState( ...
                actualPositions, vehicleLaneStates, vehicleRouteStates);

            rowNames = actualPositions.Properties.RowNames;
            obj.Geometry = scenario.Geometry;
            obj.LaneNetwork = scenario.LaneNetwork;
            obj.VehicleLaneStates = vehicleLaneStates(rowNames, :);
            obj.VehicleRouteStates = vehicleRouteStates(rowNames, :);
        end
    end

    methods (Access = protected)
        function projection = buildRouteProjection( ...
                obj, errorType, vehicleIds)
            rowNames = cellstr(vehicleIds);
            actualPositions = obj.ActualPositions(rowNames, :);
            routeStates = obj.VehicleRouteStates(rowNames, :);
            trueRoute = routeStates.Route;
            isEligible = trueRoute ~= "Regular";
            targetPositions = [ ...
                actualPositions.X, actualPositions.Y];

            switch errorType
                case "FalseExit"
                    isApplicable = ...
                        trueRoute == "Merge" | ...
                        trueRoute == "Adjacent";
                    targetPositions(isApplicable, :) = ...
                        obj.calculateFalseExitPositions( ...
                            actualPositions(isApplicable, :), ...
                            routeStates(isApplicable, :));
                case "FalseMerge"
                    isApplicable = trueRoute == "Ramp";
                    targetPositions(isApplicable, :) = ...
                        obj.calculateFalseMergePositions( ...
                            actualPositions(isApplicable, :), ...
                            routeStates(isApplicable, :));
            end

            projection = table( ...
                trueRoute, isEligible, isApplicable, ...
                targetPositions(:, 1), targetPositions(:, 2), ...
                VariableNames=[ ...
                    "TrueRoute", "IsEligible", "IsApplicable", ...
                    "TargetX", "TargetY"], ...
                RowNames=rowNames);
        end
    end

    methods (Static, Access = private)
        function validateVehicleState( ...
                actualPositions, vehicleLaneStates, vehicleRouteStates)
            expectedRouteVariables = ["TravelDirection", "Route"];
            actualRouteVariables = string( ...
                vehicleRouteStates.Properties.VariableNames);
            validRouteSchema = istable(vehicleRouteStates) && ...
                isequal(actualRouteVariables, expectedRouteVariables) && ...
                isa(vehicleRouteStates.TravelDirection, "double") && ...
                size(vehicleRouteStates.TravelDirection, 2) == 1 && ...
                all(abs(vehicleRouteStates.TravelDirection) == 1) && ...
                isstring(vehicleRouteStates.Route) && ...
                size(vehicleRouteStates.Route, 2) == 1 && ...
                all(ismember( ...
                    vehicleRouteStates.Route, ...
                    ["Regular", "Outer", "Ramp", "Merge", "Adjacent"]));
            if ~validRouteSchema
                error( ...
                    "v2xsim:positioning:InvalidExitRampRouteState", ...
                    "Exit-ramp route state must contain valid " + ...
                    "TravelDirection and Route columns.");
            end

            actualVehicleIds = string( ...
                actualPositions.Properties.RowNames);
            laneVehicleIds = string( ...
                vehicleLaneStates.Properties.RowNames);
            routeVehicleIds = string( ...
                vehicleRouteStates.Properties.RowNames);
            if ~isequal(sort(actualVehicleIds), sort(laneVehicleIds)) || ...
                    ~isequal(sort(actualVehicleIds), sort(routeVehicleIds))
                error( ...
                    "v2xsim:positioning:ContextVehicleSetMismatch", ...
                    "Actual positions, lane state, and route state " + ...
                    "must identify the same vehicles.");
            end
        end
    end

    methods (Access = private)
        function falsePositions = calculateFalseExitPositions( ...
                obj, actualPositions, routeStates)
            direction = routeStates.TravelDirection;
            distancePastFork = direction .* ...
                (actualPositions.X - obj.Geometry.ForkX);
            rampProgress = distancePastFork ./ ...
                (obj.Geometry.RoadLength ./ 2);
            rampProgress = min(max(rampProgress, 0), 1);
            rampLaneIds = obj.Geometry.getRampLaneId(direction);
            falsePositions = obj.LaneNetwork.evaluate( ...
                rampLaneIds, rampProgress);
        end

        function falsePositions = calculateFalseMergePositions( ...
                obj, actualPositions, routeStates)
            direction = routeStates.TravelDirection;
            distancePastFork = direction .* ...
                (actualPositions.X - obj.Geometry.ForkX);
            distancePastFork = min(max( ...
                distancePastFork, 0), obj.Geometry.RoadLength ./ 2);

            onMergeConnector = false(height(actualPositions), 1);
            if obj.Geometry.MergeDistance > 0
                onMergeConnector = ...
                    distancePastFork <= obj.Geometry.MergeDistance;
            end
            falsePositions = zeros(height(actualPositions), 2);

            if any(onMergeConnector)
                mergeLaneIds = obj.Geometry.getMergeLaneId( ...
                    direction(onMergeConnector));
                mergeProgress = ...
                    distancePastFork(onMergeConnector) ./ ...
                    obj.Geometry.MergeDistance;
                falsePositions(onMergeConnector, :) = ...
                    obj.LaneNetwork.evaluate( ...
                        mergeLaneIds, mergeProgress);
            end

            onAdjacentLane = ~onMergeConnector;
            if any(onAdjacentLane)
                adjacentLaneIds = obj.Geometry.getMainlineLaneId( ...
                    direction(onAdjacentLane), ...
                    (obj.Geometry.NLanes - 1) .* ...
                    ones(nnz(onAdjacentLane), 1));
                mainlineProgress = ...
                    actualPositions.X(onAdjacentLane) ./ ...
                    obj.Geometry.RoadLength;
                negativeDirection = direction(onAdjacentLane) < 0;
                mainlineProgress(negativeDirection) = ...
                    1 - mainlineProgress(negativeDirection);
                falsePositions(onAdjacentLane, :) = ...
                    obj.LaneNetwork.evaluate( ...
                        adjacentLaneIds, mainlineProgress);
            end
        end
    end
end
