classdef (Abstract) FalseRoutePositionErrorStatusEffect < ...
        v2xsim.positioning.PositionErrorStatusEffect
    %FALSEROUTEPOSITIONERRORSTATUSEFFECT Persistent false-route effect.

    properties (SetAccess = immutable)
        DisplacementScale (1, 1) double ...
            {mustBeReal, mustBeFinite, mustBeNonnegative} = 1
    end

    properties (SetAccess = immutable, GetAccess = protected)
        RouteErrorType (1, 1) string = "FalseExit"
    end

    methods (Access = protected)
        function obj = FalseRoutePositionErrorStatusEffect( ...
                routeErrorType, affectedVehicleProbability, resetAfterSeconds, ...
                displacementScale, selectionRandomSeed, ...
                selectionRandomStream)
            arguments (Input)
                routeErrorType (1, 1) string
                affectedVehicleProbability (1, 1) double
                resetAfterSeconds (1, 1) double
                displacementScale (1, 1) double
                selectionRandomSeed (1, 1) double
                selectionRandomStream
            end

            if ~ismember(routeErrorType, ["FalseExit", "FalseMerge"])
                error( ...
                    "v2xsim:positioning:UnknownRouteErrorType", ...
                    "Route error type must be FalseExit or FalseMerge.");
            end
            if affectedVehicleProbability > 1
                error( ...
                    "v2xsim:positioning:" + ...
                    "InvalidAffectedVehicleProbability", ...
                    "AffectedVehicleProbability must lie between " + ...
                    "zero and one, inclusive.");
            end
            if displacementScale > 1
                error( ...
                    "v2xsim:positioning:InvalidDisplacementScale", ...
                    "DisplacementScale must lie between zero and one, " + ...
                    "inclusive.");
            end

            obj = obj@v2xsim.positioning.PositionErrorStatusEffect( ...
                affectedVehicleProbability, selectionRandomSeed, ...
                resetAfterSeconds, selectionRandomStream);
            obj.RouteErrorType = routeErrorType;
            obj.DisplacementScale = displacementScale;
        end
    end

    methods
        function [eligible, applicable] = classifyTargets( ...
                obj, inputPositions, context)
            obj.mustUseRouteContext(context);
            vehicleIds = reshape( ...
                string(inputPositions.Properties.RowNames), [], 1);
            projection = context.getRouteProjection( ...
                obj.RouteErrorType, vehicleIds);
            eligible = projection.IsEligible;
            applicable = projection.IsApplicable;
        end

        function [obj, outputPositions] = applyToPositions( ...
                obj, inputPositions, context, activeMask)
            obj.mustUseRouteContext(context);
            outputPositions = inputPositions;
            if ~any(activeMask)
                return
            end

            vehicleIds = reshape( ...
                string(inputPositions.Properties.RowNames), [], 1);
            actualPositions = context.ActualPositions( ...
                cellstr(vehicleIds), :);
            projection = context.getRouteProjection( ...
                obj.RouteErrorType, vehicleIds);
            outputPositions.X(activeMask) = ...
                inputPositions.X(activeMask) + ...
                obj.DisplacementScale .* ...
                (projection.TargetX(activeMask) - ...
                actualPositions.X(activeMask));
            outputPositions.Y(activeMask) = ...
                inputPositions.Y(activeMask) + ...
                obj.DisplacementScale .* ...
                (projection.TargetY(activeMask) - ...
                actualPositions.Y(activeMask));
        end
    end

    methods (Access = private)
        function mustUseRouteContext(~, context)
            if ~isa( ...
                    context, ...
                    "v2xsim.positioning.RoutePositionErrorContext")
                error( ...
                    "v2xsim:positioning:UnsupportedErrorContext", ...
                    "False-route position effects require an " + ...
                    "RoutePositionErrorContext.");
            end
        end
    end
end
