classdef FalseExitPositionErrorStatusEffect < ...
        v2xsim.positioning.FalseRoutePositionErrorStatusEffect
    %FALSEEXITPOSITIONERRORSTATUSEFFECT Show merge traffic on the ramp.

    methods
        function obj = FalseExitPositionErrorStatusEffect( ...
                affectedVehicleProbability, options)
            arguments (Input)
                affectedVehicleProbability (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative}
                options.ResetAfterSeconds (1, 1) double ...
                    {mustBeReal, mustBeNonnegative} = Inf
                options.DisplacementScale (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative} = 1
                options.SelectionRandomSeed (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeInteger, ...
                    mustBeNonnegative} = 0
                options.SelectionRandomStream = []
            end

            obj = obj@v2xsim.positioning. ...
                FalseRoutePositionErrorStatusEffect( ...
                    affectedVehicleProbability, ...
                    options.ResetAfterSeconds, ...
                    options.DisplacementScale, ...
                    options.SelectionRandomSeed, ...
                    options.SelectionRandomStream);
        end
    end

    methods (Access = protected)
        function applicable = isAffectedRoute(~, route)
            applicable = route == "Merge" | route == "Adjacent";
        end

        function falsePositions = calculateFalsePositions( ...
                ~, actualPositions, routeStates, context)
            geometry = context.Geometry;
            direction = routeStates.TravelDirection;
            distancePastFork = direction .* ...
                (actualPositions.X - geometry.ForkX);
            rampProgress = distancePastFork ./ ...
                (geometry.RoadLength ./ 2);
            rampProgress = min(max(rampProgress, 0), 1);
            rampLaneIds = geometry.getRampLaneId(direction);
            falsePositions = context.LaneNetwork.evaluate( ...
                rampLaneIds, rampProgress);
        end
    end
end
