classdef (Abstract) FalseRoutePositionErrorStatusEffect < ...
        v2xsim.positioning.PositionErrorStatusEffect
    %FALSEROUTEPOSITIONERRORSTATUSEFFECT Persistent false-route effect.

    properties (SetAccess = immutable)
        DisplacementScale (1, 1) double ...
            {mustBeReal, mustBeFinite, mustBeNonnegative} = 1
    end

    methods (Access = protected)
        function obj = FalseRoutePositionErrorStatusEffect( ...
                affectedVehicleProbability, resetAfterSeconds, ...
                displacementScale, selectionRandomSeed, ...
                selectionRandomStream)
            if affectedVehicleProbability > 1
                error( ...
                    "v2xsim:positioning:" + ...
                    "InvalidAffectedVehicleProbability", ...
                    "AffectedVehicleProbability must lie between " + ...
                    "zero and one, inclusive.");
            end
            if displacementScale > 1
                error( ...
                    "v2xsim:positioning:InvalidDisplacementScale", ...
                    "DisplacementScale must lie between zero and one, " + ...
                    "inclusive.");
            end

            obj = obj@v2xsim.positioning.PositionErrorStatusEffect( ...
                affectedVehicleProbability, selectionRandomSeed, ...
                resetAfterSeconds, selectionRandomStream);
            obj.DisplacementScale = displacementScale;
        end
    end

    methods
        function [eligible, applicable] = classifyTargets( ...
                obj, inputPositions, context)
            obj.mustUseExitRampContext(context);
            routeStates = context.VehicleRouteStates( ...
                inputPositions.Properties.RowNames, :);
            eligible = routeStates.Route ~= "Regular";
            applicable = obj.isAffectedRoute(routeStates.Route);
        end

        function [obj, outputPositions] = applyToPositions( ...
                obj, inputPositions, context, activeMask)
            obj.mustUseExitRampContext(context);
            outputPositions = inputPositions;
            if ~any(activeMask)
                return
            end

            rowNames = inputPositions.Properties.RowNames;
            actualPositions = context.ActualPositions(rowNames, :);
            routeStates = context.VehicleRouteStates(rowNames, :);
            falsePositions = obj.calculateFalsePositions( ...
                actualPositions(activeMask, :), ...
                routeStates(activeMask, :), context);
            outputPositions.X(activeMask) = ...
                inputPositions.X(activeMask) + ...
                obj.DisplacementScale .* ...
                (falsePositions(:, 1) - ...
                actualPositions.X(activeMask));
            outputPositions.Y(activeMask) = ...
                inputPositions.Y(activeMask) + ...
                obj.DisplacementScale .* ...
                (falsePositions(:, 2) - ...
                actualPositions.Y(activeMask));
        end
    end

    methods (Access = private)
        function mustUseExitRampContext(~, context)
            if ~isa( ...
                    context, ...
                    "v2xsim.positioning.ExitRampPositionErrorContext")
                error( ...
                    "v2xsim:positioning:UnsupportedErrorContext", ...
                    "False-route position effects require an " + ...
                    "ExitRampPositionErrorContext.");
            end
        end
    end

    methods (Abstract, Access = protected)
        applicable = isAffectedRoute(obj, route)
        falsePositions = calculateFalsePositions( ...
            obj, actualPositions, routeStates, context)
    end
end
