classdef FalseMergePositionErrorStatusEffect < ...
        v2xsim.positioning.FalseRoutePositionErrorStatusEffect
    %FALSEMERGEPOSITIONERRORSTATUSEFFECT Show ramp traffic on the mainline.

    methods
        function obj = FalseMergePositionErrorStatusEffect( ...
                affectedVehicleProbability, options)
            arguments (Input)
                affectedVehicleProbability (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative}
                options.ResetAfterSeconds (1, 1) double ...
                    {mustBeReal, mustBeNonnegative} = Inf
                options.DisplacementScale (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative} = 1
                options.SelectionRandomSeed (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeInteger, ...
                    mustBeNonnegative} = 0
                options.SelectionRandomStream = []
            end

            obj = obj@v2xsim.positioning. ...
                FalseRoutePositionErrorStatusEffect( ...
                    affectedVehicleProbability, ...
                    options.ResetAfterSeconds, ...
                    options.DisplacementScale, ...
                    options.SelectionRandomSeed, ...
                    options.SelectionRandomStream);
        end
    end

    methods (Access = protected)
        function applicable = isAffectedRoute(~, route)
            applicable = route == "Ramp";
        end

        function falsePositions = calculateFalsePositions( ...
                ~, actualPositions, routeStates, context)
            geometry = context.Geometry;
            direction = routeStates.TravelDirection;
            distancePastFork = direction .* ...
                (actualPositions.X - geometry.ForkX);
            distancePastFork = min(max( ...
                distancePastFork, 0), geometry.RoadLength ./ 2);

            onMergeConnector = false(height(actualPositions), 1);
            if geometry.MergeDistance > 0
                onMergeConnector = ...
                    distancePastFork <= geometry.MergeDistance;
            end
            falsePositions = zeros(height(actualPositions), 2);

            if any(onMergeConnector)
                mergeLaneIds = geometry.getMergeLaneId( ...
                    direction(onMergeConnector));
                mergeProgress = ...
                    distancePastFork(onMergeConnector) ./ ...
                    geometry.MergeDistance;
                falsePositions(onMergeConnector, :) = ...
                    context.LaneNetwork.evaluate( ...
                        mergeLaneIds, mergeProgress);
            end

            onAdjacentLane = ~onMergeConnector;
            if any(onAdjacentLane)
                adjacentLaneIds = geometry.getMainlineLaneId( ...
                    direction(onAdjacentLane), ...
                    (geometry.NLanes - 1) .* ...
                    ones(nnz(onAdjacentLane), 1));
                mainlineProgress = ...
                    actualPositions.X(onAdjacentLane) ./ ...
                    geometry.RoadLength;
                negativeDirection = direction(onAdjacentLane) < 0;
                mainlineProgress(negativeDirection) = ...
                    1 - mainlineProgress(negativeDirection);
                falsePositions(onAdjacentLane, :) = ...
                    context.LaneNetwork.evaluate( ...
                        adjacentLaneIds, mainlineProgress);
            end
        end
    end
end
