classdef FalseMergePositionErrorStatusEffect < ...
        v2xsim.positioning.FalseRoutePositionErrorStatusEffect
    %FALSEMERGEPOSITIONERRORSTATUSEFFECT Show ramp traffic on the mainline.

    methods
        function obj = FalseMergePositionErrorStatusEffect( ...
                affectedVehicleProbability, options)
            arguments (Input)
                affectedVehicleProbability (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative}
                options.ResetAfterSeconds (1, 1) double ...
                    {mustBeReal, mustBeNonnegative} = Inf
                options.DisplacementScale (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative} = 1
                options.SelectionRandomSeed (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeInteger, ...
                    mustBeNonnegative} = 0
                options.SelectionRandomStream = []
            end

            obj = obj@v2xsim.positioning. ...
                FalseRoutePositionErrorStatusEffect( ...
                    "FalseMerge", ...
                    affectedVehicleProbability, ...
                    options.ResetAfterSeconds, ...
                    options.DisplacementScale, ...
                    options.SelectionRandomSeed, ...
                    options.SelectionRandomStream);
        end
    end
end
