classdef IsotropicGaussianPositionErrorStatusEffect < ...
        v2xsim.positioning.PositionErrorStatusEffect
    %ISOTROPICGAUSSIANPOSITIONERRORSTATUSEFFECT Radial Gaussian error.
    %   Each application draws one Gaussian radial displacement and one
    %   independent uniform direction for every input row before applying
    %   the active mask. A negative radial draw reverses the direction, so
    %   the realized nonnegative magnitude is folded normal. Drawing the
    %   full vectors preserves deterministic stream alignment across
    %   cohorts.

    properties (SetAccess = immutable)
        MeanMagnitudeMeters (1, 1) double ...
            {mustBeReal, mustBeFinite, mustBeNonnegative} = 0
        StandardDeviationMeters (1, 1) double ...
            {mustBeReal, mustBeFinite, mustBeNonnegative} = 0
        DisplacementRandomSeed (1, 1) double ...
            {mustBeReal, mustBeFinite, mustBeInteger, ...
            mustBeNonnegative} = 0
        ActiveRoutes (1, :) string = strings(1, 0)
    end

    properties (Access = private)
        DisplacementRandomStream (1, 1) RandStream = ...
            RandStream("mt19937ar", Seed=0)
    end

    methods
        function obj = IsotropicGaussianPositionErrorStatusEffect( ...
                standardDeviationMeters, options)
            arguments (Input)
                standardDeviationMeters (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative}
                options.MeanMagnitudeMeters (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative} = 0
                options.AffectedVehicleProbability (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative} = 1
                options.SelectionRandomSeed (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeInteger, ...
                    mustBeNonnegative} = 0
                options.SelectionRandomStream = []
                options.ResetAfterSeconds (1, 1) double ...
                    {mustBeReal, mustBeNonnegative} = Inf
                options.DisplacementRandomSeed (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeInteger, ...
                    mustBeNonnegative} = 0
                options.DisplacementRandomStream = []
                options.ActiveRoutes (1, :) string = strings(1, 0)
            end

            if options.AffectedVehicleProbability > 1
                error( ...
                    "v2xsim:positioning:" + ...
                    "InvalidAffectedVehicleProbability", ...
                    "AffectedVehicleProbability must lie between " + ...
                    "zero and one, inclusive.");
            end
            activeRoutes = reshape(options.ActiveRoutes, 1, []);
            supportedRoutes = ["Ramp", "Merge", "Adjacent"];
            if any(~ismember(activeRoutes, supportedRoutes)) || ...
                    numel(unique(activeRoutes)) ~= numel(activeRoutes)
                error( ...
                    "v2xsim:positioning:InvalidActiveRoutes", ...
                    "ActiveRoutes must contain unique Ramp, Merge, " + ...
                    "or Adjacent route names.");
            end

            obj = obj@v2xsim.positioning.PositionErrorStatusEffect( ...
                options.AffectedVehicleProbability, ...
                options.SelectionRandomSeed, ...
                options.ResetAfterSeconds, ...
                options.SelectionRandomStream);
            obj.MeanMagnitudeMeters = options.MeanMagnitudeMeters;
            obj.StandardDeviationMeters = standardDeviationMeters;
            [obj.DisplacementRandomStream, ...
                obj.DisplacementRandomSeed] = ...
                v2xsim.positioning.internal.createOwnedRandomStream( ...
                    options.DisplacementRandomSeed, ...
                    options.DisplacementRandomStream);
            obj.ActiveRoutes = activeRoutes;
        end

        function [eligible, applicable] = classifyTargets( ...
                obj, inputPositions, context)
            vehicleCount = height(inputPositions);
            if isempty(obj.ActiveRoutes)
                eligible = true(vehicleCount, 1);
                applicable = true(vehicleCount, 1);
                return
            end

            if ~isa( ...
                    context, ...
                    "v2xsim.positioning.ExitRampPositionErrorContext")
                error( ...
                    "v2xsim:positioning:UnsupportedErrorContext", ...
                    "Gaussian ActiveRoutes require an " + ...
                    "ExitRampPositionErrorContext.");
            end
            vehicleIds = inputPositions.Properties.RowNames;
            route = context.VehicleRouteStates(vehicleIds, :).Route;
            eligible = route ~= "Regular";
            applicable = ismember(route, obj.ActiveRoutes);
        end

        function [obj, outputPositions] = applyToPositions( ...
                obj, inputPositions, ~, activeMask)
            vehicleCount = height(inputPositions);
            [obj.DisplacementRandomStream, ~] = ...
                v2xsim.positioning.internal.createOwnedRandomStream( ...
                    obj.DisplacementRandomSeed, ...
                    obj.DisplacementRandomStream);
            radialDisplacement = obj.MeanMagnitudeMeters + ...
                obj.StandardDeviationMeters .* randn( ...
                    obj.DisplacementRandomStream, vehicleCount, 1);
            directionRadians = 2 .* pi .* rand( ...
                obj.DisplacementRandomStream, vehicleCount, 1);
            orderedDisplacement = radialDisplacement .* ...
                [cos(directionRadians), sin(directionRadians)];
            vehicleIds = string(inputPositions.Properties.RowNames);
            [~, stableOrder] = sort(vehicleIds);
            displacement = zeros(vehicleCount, 2);
            displacement(stableOrder, :) = orderedDisplacement;

            outputPositions = inputPositions;
            outputPositions.X(activeMask) = ...
                inputPositions.X(activeMask) + ...
                displacement(activeMask, 1);
            outputPositions.Y(activeMask) = ...
                inputPositions.Y(activeMask) + ...
                displacement(activeMask, 2);
        end
    end
end
