classdef PositionPacketLossError < ...
        v2xsim.positioning.PositionErrorModule
    %POSITIONPACKETLOSSERROR Hold positions when network updates are lost.
    %   Each distinct simulation time is one update opportunity per
    %   present vehicle. A lost update returns that vehicle's last
    %   successfully received apparent position. The first observation of
    %   an identity establishes its initial controller position without a
    %   random draw. Repeated applications at the same time reuse the
    %   original delivery decision.

    properties (SetAccess = immutable)
        LossProbability (1, 1) double ...
            {mustBeReal, mustBeFinite, mustBeNonnegative} = 0
        RandomSeed (1, 1) double ...
            {mustBeReal, mustBeFinite, mustBeInteger, ...
            mustBeNonnegative} = 0
    end

    properties (Access = private)
        VehicleStates table = table( ...
            zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
            zeros(0, 1), false(0, 1), strings(0, 1), ...
            VariableNames=[ ...
                "LastReceivedX", "LastReceivedY", ...
                "LastReceivedTimeSeconds", ...
                "LastDecisionTimeSeconds", ...
                "LastDecisionWasLoss", ...
                "LastDecisionOutcome"])
        RandomStream (1, 1) RandStream = ...
            RandStream("mt19937ar", Seed=0)
        LastSimulationTimeSeconds (1, 1) double = NaN
        LastNetworkUpdateOutcome (:, 1) string = strings(0, 1)
        LastOutputSourceTimeSeconds (:, 1) double = zeros(0, 1)
    end

    methods
        function obj = PositionPacketLossError(lossProbability, options)
            arguments (Input)
                lossProbability (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative}
                options.RandomSeed (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeInteger, ...
                    mustBeNonnegative} = 0
                options.RandomStream = []
            end

            if lossProbability > 1
                error( ...
                    "v2xsim:positioning:InvalidLossProbability", ...
                    "LossProbability must lie between zero and one, " + ...
                    "inclusive.");
            end

            obj.LossProbability = lossProbability;
            [obj.RandomStream, obj.RandomSeed] = ...
                v2xsim.positioning.internal.createOwnedRandomStream( ...
                    options.RandomSeed, options.RandomStream);
        end
    end

    methods (Access = protected)
        function [obj, outputPositions] = doApply( ...
                obj, inputPositions, context)
            currentTime = context.SimulationTimeSeconds;
            if ~isnan(obj.LastSimulationTimeSeconds) && ...
                    currentTime < obj.LastSimulationTimeSeconds
                error( ...
                    "v2xsim:positioning:" + ...
                    "PositionPacketLossTimeReversed", ...
                    "PositionPacketLossError requires nondecreasing " + ...
                    "simulation times.");
            end
            obj.LastSimulationTimeSeconds = currentTime;

            vehicleIds = reshape( ...
                string(inputPositions.Properties.RowNames), [], 1);
            vehicleCount = numel(vehicleIds);
            if vehicleCount == 0
                outputPositions = inputPositions;
                obj.LastNetworkUpdateOutcome = strings(0, 1);
                obj.LastOutputSourceTimeSeconds = zeros(0, 1);
                return
            end

            knownVehicleIds = string( ...
                obj.VehicleStates.Properties.RowNames);
            firstObservation = ...
                ~ismember(vehicleIds, knownVehicleIds);
            obj = obj.addFirstObservations( ...
                inputPositions, vehicleIds, firstObservation, currentTime);

            stateVehicleIds = string( ...
                obj.VehicleStates.Properties.RowNames);
            [~, stateIndices] = ismember(vehicleIds, stateVehicleIds);
            requiresDecision = ~firstObservation & ...
                obj.VehicleStates.LastDecisionTimeSeconds( ...
                    stateIndices) < currentTime;
            obj = obj.drawLossDecisions( ...
                vehicleIds, stateIndices, requiresDecision, currentTime);

            wasLost = obj.VehicleStates.LastDecisionWasLoss( ...
                stateIndices);
            wasReceived = ~wasLost;
            receivedStateIndices = stateIndices(wasReceived);
            obj.VehicleStates.LastReceivedX(receivedStateIndices) = ...
                double(inputPositions.X(wasReceived));
            obj.VehicleStates.LastReceivedY(receivedStateIndices) = ...
                double(inputPositions.Y(wasReceived));
            obj.VehicleStates.LastReceivedTimeSeconds( ...
                receivedStateIndices) = currentTime;

            outputPositions = inputPositions;
            lostStateIndices = stateIndices(wasLost);
            outputPositions.X(wasLost) = cast( ...
                obj.VehicleStates.LastReceivedX(lostStateIndices), ...
                "like", outputPositions.X);
            outputPositions.Y(wasLost) = cast( ...
                obj.VehicleStates.LastReceivedY(lostStateIndices), ...
                "like", outputPositions.Y);

            obj.LastNetworkUpdateOutcome = ...
                obj.VehicleStates.LastDecisionOutcome(stateIndices);
            obj.LastOutputSourceTimeSeconds = ...
                obj.VehicleStates.LastReceivedTimeSeconds(stateIndices);
        end

        function diagnostics = buildDiagnostics( ...
                obj, inputPositions, outputPositions, context)
            diagnostics = v2xsim.positioning.diagnostics.createRows( ...
                inputPositions, outputPositions, ...
                context.SimulationTimeSeconds, string(class(obj)));
            diagnostics.NetworkUpdateOutcome = ...
                obj.LastNetworkUpdateOutcome;
            diagnostics.OutputSourceTimeSeconds = ...
                obj.LastOutputSourceTimeSeconds;
            diagnostics.OutputAgeSeconds = ...
                context.SimulationTimeSeconds - ...
                obj.LastOutputSourceTimeSeconds;
        end
    end

    methods (Access = private)
        function obj = addFirstObservations( ...
                obj, inputPositions, vehicleIds, firstObservation, ...
                currentTime)
            if ~any(firstObservation)
                return
            end

            newVehicleIds = vehicleIds(firstObservation);
            newVehicleCount = numel(newVehicleIds);
            newStates = table( ...
                double(inputPositions.X(firstObservation)), ...
                double(inputPositions.Y(firstObservation)), ...
                repmat(currentTime, newVehicleCount, 1), ...
                repmat(currentTime, newVehicleCount, 1), ...
                false(newVehicleCount, 1), ...
                repmat("BootstrapReceived", newVehicleCount, 1), ...
                VariableNames=obj.VehicleStates.Properties.VariableNames, ...
                RowNames=cellstr(newVehicleIds));
            obj.VehicleStates = [obj.VehicleStates; newStates];
        end

        function obj = drawLossDecisions( ...
                obj, vehicleIds, stateIndices, requiresDecision, ...
                currentTime)
            decisionInputIndices = find(requiresDecision);
            if isempty(decisionInputIndices)
                return
            end

            [~, stableOrder] = sort( ...
                vehicleIds(decisionInputIndices));
            orderedInputIndices = ...
                decisionInputIndices(stableOrder);
            decisionCount = numel(orderedInputIndices);

            if obj.LossProbability == 0
                orderedWasLost = false(decisionCount, 1);
            elseif obj.LossProbability == 1
                orderedWasLost = true(decisionCount, 1);
            else
                [obj.RandomStream, ~] = ...
                    v2xsim.positioning.internal. ...
                    createOwnedRandomStream( ...
                        obj.RandomSeed, obj.RandomStream);
                orderedWasLost = rand( ...
                    obj.RandomStream, decisionCount, 1) < ...
                    obj.LossProbability;
            end

            orderedStateIndices = stateIndices(orderedInputIndices);
            obj.VehicleStates.LastDecisionTimeSeconds( ...
                orderedStateIndices) = currentTime;
            obj.VehicleStates.LastDecisionWasLoss( ...
                orderedStateIndices) = orderedWasLost;
            orderedOutcome = repmat("Received", decisionCount, 1);
            orderedOutcome(orderedWasLost) = "Dropped";
            obj.VehicleStates.LastDecisionOutcome( ...
                orderedStateIndices) = orderedOutcome;
        end
    end
end
