classdef RoundaboutPositionErrorContext < ...
        v2xsim.positioning.RoutePositionErrorContext
    %ROUNDABOUTPOSITIONERRORCONTEXT Route projection for a four-arm circle.
    %   FalseExit projects a circulating vehicle onto the outbound arm it
    %   most recently skipped. Geometry owns the equal-distance lane
    %   mapping; this immutable context validates and exposes its snapshot
    %   to the scenario-neutral false-route status effect.

    properties (SetAccess = immutable)
        Geometry (1, 1) ...
            v2xsim.vehicle.scenario.roundabout.Geometry = ...
            v2xsim.vehicle.scenario.roundabout.Geometry(500, 4, 60)
        LaneNetwork (1, 1) ...
            v2xsim.vehicle.scenario.highway.LaneNetwork = ...
            v2xsim.vehicle.scenario.highway.LaneNetwork()
        VehicleLaneStates table ...
            {v2xsim.vehicle.scenario.validation.mustBeVehicleLaneStateTable} = ...
            table( ...
                strings(0, 1), zeros(0, 1), zeros(0, 1), ...
                VariableNames=[ ...
                    "LaneId", "Progress", "LateralOffsetMeters"])
        VehicleRouteStates table = table( ...
            strings(0, 1), strings(0, 1), strings(0, 1), ...
            VariableNames=["EntryArm", "ExitArm", "Stage"])
    end

    methods
        function obj = RoundaboutPositionErrorContext( ...
                scenario, simulationTimeSeconds, ...
                timeStepSeconds, simulationDurationSeconds)
            arguments (Input)
                scenario (1, 1) ...
                    v2xsim.vehicle.scenarios.RoundaboutScenario
                simulationTimeSeconds (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative}
                timeStepSeconds (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBePositive}
                simulationDurationSeconds (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBePositive}
            end

            actualPositions = ...
                scenario.VehicleKinematics(:, ["X", "Y"]);
            obj = obj@v2xsim.positioning.RoutePositionErrorContext( ...
                actualPositions, simulationTimeSeconds, ...
                timeStepSeconds, simulationDurationSeconds);

            vehicleLaneStates = scenario.VehicleLaneStates;
            vehicleRouteStates = scenario.VehicleRouteStates;
            obj.validateVehicleState( ...
                actualPositions, vehicleLaneStates, vehicleRouteStates);

            rowNames = actualPositions.Properties.RowNames;
            obj.Geometry = scenario.Geometry;
            obj.LaneNetwork = scenario.LaneNetwork;
            obj.VehicleLaneStates = vehicleLaneStates(rowNames, :);
            obj.VehicleRouteStates = vehicleRouteStates(rowNames, :);
        end
    end

    methods (Access = protected)
        function projection = buildRouteProjection( ...
                obj, errorType, vehicleIds)
            if errorType ~= "FalseExit"
                error( ...
                    "v2xsim:positioning:UnsupportedErrorContext", ...
                    "FalseMerge position errors are not supported by " + ...
                    "RoundaboutPositionErrorContext.");
            end

            rowNames = cellstr(vehicleIds);
            actualPositions = obj.ActualPositions(rowNames, :);
            laneStates = obj.VehicleLaneStates(rowNames, :);
            routeStates = obj.VehicleRouteStates(rowNames, :);
            trueRoute = routeStates.EntryArm + "->" + ...
                routeStates.ExitArm;
            isEligible = true(numel(vehicleIds), 1);
            [isApplicable, targetLaneIds, targetProgress] = ...
                obj.Geometry.getFalseExitLaneCoordinates( ...
                    laneStates, routeStates);
            targetPositions = [ ...
                actualPositions.X, actualPositions.Y];
            if any(isApplicable)
                targetPositions(isApplicable, :) = ...
                    obj.LaneNetwork.evaluate( ...
                        targetLaneIds(isApplicable), ...
                        targetProgress(isApplicable));
            end

            projection = table( ...
                trueRoute, isEligible, isApplicable, ...
                targetPositions(:, 1), targetPositions(:, 2), ...
                VariableNames=[ ...
                    "TrueRoute", "IsEligible", "IsApplicable", ...
                    "TargetX", "TargetY"], ...
                RowNames=rowNames);
        end
    end

    methods (Static, Access = private)
        function validateVehicleState( ...
                actualPositions, vehicleLaneStates, vehicleRouteStates)
            expectedRouteVariables = ["EntryArm", "ExitArm", "Stage"];
            routeVariables = string( ...
                vehicleRouteStates.Properties.VariableNames);
            vehicleCount = height(actualPositions);
            arms = ["North", "East", "South", "West"];
            stages = [ ...
                "Inbound", "EntryConnector", "Circulating", ...
                "ExitConnector", "Outbound"];
            validRouteSchema = istable(vehicleRouteStates) && ...
                isequal(routeVariables, expectedRouteVariables) && ...
                isstring(vehicleRouteStates.EntryArm) && ...
                isequal( ...
                    size(vehicleRouteStates.EntryArm), ...
                    [vehicleCount, 1]) && ...
                isstring(vehicleRouteStates.ExitArm) && ...
                isequal( ...
                    size(vehicleRouteStates.ExitArm), ...
                    [vehicleCount, 1]) && ...
                isstring(vehicleRouteStates.Stage) && ...
                isequal( ...
                    size(vehicleRouteStates.Stage), ...
                    [vehicleCount, 1]) && ...
                all(ismember(vehicleRouteStates.EntryArm, arms)) && ...
                all(ismember(vehicleRouteStates.ExitArm, arms)) && ...
                all(ismember(vehicleRouteStates.Stage, stages));
            if ~validRouteSchema
                error( ...
                    "v2xsim:positioning:InvalidRoundaboutRouteState", ...
                    "Roundabout route state must contain valid EntryArm, " + ...
                    "ExitArm, and Stage string columns.");
            end

            actualVehicleIds = string( ...
                actualPositions.Properties.RowNames);
            laneVehicleIds = string( ...
                vehicleLaneStates.Properties.RowNames);
            routeVehicleIds = string( ...
                vehicleRouteStates.Properties.RowNames);
            if ~isequal(sort(actualVehicleIds), sort(laneVehicleIds)) || ...
                    ~isequal( ...
                        sort(actualVehicleIds), sort(routeVehicleIds))
                error( ...
                    "v2xsim:positioning:ContextVehicleSetMismatch", ...
                    "Actual positions, lane state, and route state " + ...
                    "must identify the same vehicles.");
            end
        end
    end
end
