classdef (Abstract) RoutePositionErrorContext < ...
        v2xsim.positioning.PositionErrorContext
    %ROUTEPOSITIONERRORCONTEXT Scenario-neutral false-route projections.
    %   Route-aware scenarios expose counterfactual route positions through
    %   GETROUTEPROJECTION. Returned rows follow the requested vehicle-ID
    %   order and distinguish one-time selection eligibility from the
    %   portion of a route on which the position error is applicable.

    methods (Access = protected)
        function obj = RoutePositionErrorContext( ...
                actualPositions, simulationTimeSeconds, ...
                timeStepSeconds, simulationDurationSeconds)
            arguments (Input)
                actualPositions table ...
                    {v2xsim.positioning.validation.mustBe2DPositionTable}
                simulationTimeSeconds (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative}
                timeStepSeconds (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBePositive}
                simulationDurationSeconds (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBePositive}
            end

            obj = obj@v2xsim.positioning.PositionErrorContext( ...
                actualPositions, simulationTimeSeconds, ...
                timeStepSeconds, simulationDurationSeconds);
        end
    end

    methods (Sealed)
        function projection = getRouteProjection( ...
                obj, errorType, vehicleIds)
            %GETROUTEPROJECTION Return a validated counterfactual snapshot.
            arguments (Input)
                obj (1, 1)
                errorType (1, 1) string
                vehicleIds (:, 1) string
            end

            supportedTypes = ["FalseExit", "FalseMerge"];
            if ismissing(errorType) || ...
                    ~ismember(errorType, supportedTypes)
                error( ...
                    "v2xsim:positioning:UnknownRouteErrorType", ...
                    "Route error type must be FalseExit or FalseMerge.");
            end
            if any( ...
                    ismissing(vehicleIds) | strlength(vehicleIds) == 0) || ...
                    numel(unique(vehicleIds)) ~= numel(vehicleIds)
                error( ...
                    "v2xsim:positioning:InvalidRouteProjectionVehicleIds", ...
                    "Projection vehicle IDs must be unique, nonmissing, " + ...
                    "and nonempty.");
            end

            contextVehicleIds = reshape( ...
                string(obj.ActualPositions.Properties.RowNames), [], 1);
            if any(~ismember(vehicleIds, contextVehicleIds))
                error( ...
                    "v2xsim:positioning:UnknownRouteProjectionVehicle", ...
                    "Every projection vehicle must belong to the context.");
            end

            projection = obj.buildRouteProjection( ...
                errorType, vehicleIds);
            obj.validateProjection(projection, vehicleIds);
        end
    end

    methods (Access = private)
        function validateProjection(~, projection, vehicleIds)
            expectedVariables = [ ...
                "TrueRoute", "IsEligible", "IsApplicable", ...
                "TargetX", "TargetY"];
            validSchema = istable(projection) && ...
                isequal( ...
                    string(projection.Properties.VariableNames), ...
                    expectedVariables) && ...
                height(projection) == numel(vehicleIds);
            if ~validSchema
                error( ...
                    "v2xsim:positioning:InvalidRouteProjection", ...
                    "A route projection must contain exactly TrueRoute, " + ...
                    "IsEligible, IsApplicable, TargetX, and TargetY, " + ...
                    "with one row per requested vehicle.");
            end

            projectionVehicleIds = reshape( ...
                string(projection.Properties.RowNames), [], 1);
            if ~isequal(projectionVehicleIds, vehicleIds)
                error( ...
                    "v2xsim:positioning:InvalidRouteProjection", ...
                    "Route projection row names must equal the requested " + ...
                    "vehicle IDs in the requested order.");
            end

            trueRoutesAreValid = ...
                isstring(projection.TrueRoute) && ...
                isequal(size(projection.TrueRoute), [numel(vehicleIds), 1]) && ...
                all( ...
                    ~ismissing(projection.TrueRoute) & ...
                    strlength(projection.TrueRoute) > 0);
            masksAreValid = ...
                islogical(projection.IsEligible) && ...
                isequal( ...
                    size(projection.IsEligible), ...
                    [numel(vehicleIds), 1]) && ...
                islogical(projection.IsApplicable) && ...
                isequal( ...
                    size(projection.IsApplicable), ...
                    [numel(vehicleIds), 1]) && ...
                ~any( ...
                    projection.IsApplicable & ...
                    ~projection.IsEligible);
            targetsAreValid = ...
                v2xsim.positioning.RoutePositionErrorContext. ...
                    isFiniteDoubleColumn( ...
                    projection.TargetX, numel(vehicleIds)) && ...
                v2xsim.positioning.RoutePositionErrorContext. ...
                    isFiniteDoubleColumn( ...
                    projection.TargetY, numel(vehicleIds));
            if ~trueRoutesAreValid || ...
                    ~masksAreValid || ~targetsAreValid
                error( ...
                    "v2xsim:positioning:InvalidRouteProjection", ...
                    "Route projection values must have valid column " + ...
                    "types, applicable rows must be eligible, and target " + ...
                    "coordinates must be finite.");
            end
        end
    end

    methods (Static, Access = private)
        function valid = isFiniteDoubleColumn(value, expectedHeight)
            valid = isa(value, "double") && isreal(value) && ...
                isequal(size(value), [expectedHeight, 1]) && ...
                all(isfinite(value));
        end
    end

    methods (Abstract, Access = protected)
        projection = buildRouteProjection(obj, errorType, vehicleIds)
    end
end
