function dispatchAfterNeighborGraphUpdated( ...
        simValues,timeManagement,stationManagement, ...
        positionManagement,phyParams, ...
        neighborsCv2xByRange,neighborsItsG5ByRange)
%DISPATCHAFTERNEIGHBORGRAPHUPDATED Publish one complete neighbor snapshot.

if ~isfield(simValues, "hookDispatcher")
    return
end

if isempty(stationManagement.activeIDsCV2X)
    averageCv2xNeighbors = zeros(size(neighborsCv2xByRange));
else
    averageCv2xNeighbors = ...
        neighborsCv2xByRange ./ ...
        numel(stationManagement.activeIDsCV2X);
end
if isempty(stationManagement.activeIDs11p)
    averageItsG5Neighbors = zeros(size(neighborsItsG5ByRange));
else
    averageItsG5Neighbors = ...
        neighborsItsG5ByRange ./ ...
        numel(stationManagement.activeIDs11p);
end

activeIds = stationManagement.activeIDs(:);
invocation = v2xsim.hook.invocations. ...
    AfterNeighborGraphUpdatedInvocation( ...
        timeManagement.timeNow, activeIds, ...
        stationManagement.activeIDsCV2X(:), ...
        stationManagement.activeIDs11p(:), ...
        positionManagement.distanceReal(activeIds, activeIds), ...
        phyParams.Raw(:).', ...
        averageCv2xNeighbors(:).', ...
        averageItsG5Neighbors(:).');
simValues.hookDispatcher.dispatch( ...
    v2xsim.hook.points.AfterNeighborGraphUpdated, invocation);
end
