%% 09 - Explore every public traffic scenario
% Each short run uses the same NR-V2X centralized-allocation baseline. The
% plots illustrate mobility geometry; they are not performance comparisons.

exampleScriptDirectory = fileparts(mfilename("fullpath"));
[exampleResults,exampleOutputDirectory] = runExample( ...
    exampleScriptDirectory);
clear exampleScriptDirectory

disp(exampleResults.Scenarios)
fprintf("Completed outputs: %s\n",exampleOutputDirectory);

function [results,outputDirectory] = runExample(exampleDirectory)
timer = tic;
configurationFile = fullfile( ...
    exampleDirectory,"09_traffic_scenario_gallery.toml");
outputDirectory = string(tempname);
template = v2xsim.config.load(configurationFile);
scenarioTypes = [ ...
    "BrownianMotion"; ...
    "BidirectionalHighway"; ...
    "EtsiHighway"; ...
    "ExitRampHighway"];

vehicleCount = zeros(size(scenarioTypes));
simulationElapsedSeconds = zeros(size(scenarioTypes));
runDirectories = strings(size(scenarioTypes));
kinematics = cell(size(scenarioTypes));
summaries = cell(size(scenarioTypes));
simulationResults = cell(size(scenarioTypes));

figure(Name="V7 traffic scenario gallery");
layout = tiledlayout(2,2,TileSpacing="compact");
title(layout,"Short trajectories; geometry only")
for scenarioIndex = 1:numel(scenarioTypes)
    scenarioType = scenarioTypes(scenarioIndex);
    runDirectories(scenarioIndex) = fullfile(outputDirectory,scenarioType);
    patch = v2xsim.config.patch(scenarioPatch(scenarioType));
    configuration = template.resolve(Patch=patch);
    simulationTimer = tic;
    simulationResult = v2xsim.runSimulation( ...
        configuration, ...
        OutputDirectory=runDirectories(scenarioIndex), ...
        RunLabel="scenario-" + scenarioType);
    simulationElapsedSeconds(scenarioIndex) = toc(simulationTimer);
    runDirectories(scenarioIndex) = simulationResult.RunDirectory;
    summary = jsondecode(fileread(fullfile( ...
        simulationResult.RunDirectory,"simulation_summary.json")));
    summaries{scenarioIndex} = summary;
    simulationResults{scenarioIndex} = simulationResult;

    rows = readtable( ...
        fullfile(runDirectories(scenarioIndex), ...
            "vehicle_kinematics.csv"), ...
        TextType="string");
    rows = sortrows(rows,["VehicleId","SimulationTimeSeconds"]);
    kinematics{scenarioIndex} = rows;
    vehicleCount(scenarioIndex) = numel(unique(rows.VehicleId));

    nexttile
    plotTrajectories(rows)
    title(scenarioType,Interpreter="none")
end

scenarios = table( ...
    scenarioTypes,vehicleCount,runDirectories, ...
    VariableNames=["Scenario","VehicleCount","RunDirectory"]);
elapsedSeconds = toc(timer);
if elapsedSeconds > 30
    warning( ...
        "v2xsimexample:SlowExample", ...
        "This example took %.1f seconds on this computer.", ...
        elapsedSeconds);
end
results = struct( ...
    SimulationResults={simulationResults}, ...
    Summaries={summaries}, ...
    Scenarios=scenarios, ...
    Kinematics={kinematics}, ...
    SimulationElapsedSeconds=simulationElapsedSeconds, ...
    ElapsedSeconds=elapsedSeconds);
end

function patchData = scenarioPatch(scenarioType)
switch scenarioType
    case "BrownianMotion"
        options = struct( ...
            RandomSeed=109, ...
            VehicleCount=12, ...
            SimulationAreaSize=300, ...
            MeanVehicleSpeed=20, ...
            VehicleSpeedStandardDeviation=2);
    case "BidirectionalHighway"
        options = struct( ...
            RandomSeed=109, ...
            VehicleCount=12, ...
            NLanes=2, ...
            LaneWidth=4, ...
            RoadLength=400, ...
            CentralDividerWidth=0, ...
            MeanVehicleSpeed=20, ...
            VehicleSpeedStandardDeviation=2, ...
            RerollSpeedOnWrapAround=false);
    case "EtsiHighway"
        options = struct( ...
            RandomSeed=109, ...
            TrafficModel="HighSpeedLowDensity", ...
            Placement="Gaussian", ...
            MinimumRoadLength=2000);
    case "ExitRampHighway"
        options = struct( ...
            RandomSeed=109, ...
            VehicleCount=12, ...
            NLanes=2, ...
            LaneWidth=4, ...
            RoadLength=400, ...
            CentralDividerWidth=0, ...
            MeanVehicleSpeed=20, ...
            VehicleSpeedStandardDeviation=2, ...
            RerollSpeedOnWrapAround=false, ...
            ExitProbability=0.5, ...
            MergeDistance=80);
    otherwise
        error( ...
            "v2xsimexample:UnsupportedScenario", ...
            "Unsupported scenario: %s",scenarioType);
end

scenario = struct(Type=scenarioType);
scenario.(scenarioType) = options;
patchData = struct(Scenario=scenario);
end

function plotTrajectories(rows)
vehicleIds = unique(rows.VehicleId);
hold on
for vehicleIndex = 1:numel(vehicleIds)
    mask = rows.VehicleId == vehicleIds(vehicleIndex);
    plot(rows.X(mask),rows.Y(mask),".-");
end
hold off
axis equal
grid on
xlabel("X (m)")
ylabel("Y (m)")
end
