function results = runPublishedCampaigns( ...
        simulatorRoot, outputDirectory, options)
%RUNPUBLISHEDCAMPAIGNS Run the Zhuofei et al. repetition campaigns.
%   RESULTS contains one row per pooled configuration. The runner samples
%   the conclusions behind Figures 3-5 instead of reproducing every point
%   in the paper's full Monte Carlo sweep.

arguments (Input)
    simulatorRoot (1, 1) string {mustBeNonzeroLengthText}
    outputDirectory (1, 1) string {mustBeNonzeroLengthText}
    options.Figures (1, :) double ...
        {mustBeInteger, mustBeMember(options.Figures, [3, 4, 5])} = ...
        [3, 4, 5]
    options.RandomSeeds (1, :) double ...
        {mustBeInteger, mustBePositive} = 10:11
    options.SimulationTimeSeconds (1, 1) double ...
        {mustBeReal, mustBeFinite, mustBePositive} = ...
        defaultSimulationTimeSeconds()
    options.Figure3PreambleSensitivitiesDbm (1, :) double ...
        {mustBeReal, mustBeFinite} = [-100, -103, -120]
    options.Figure3TransmissionCounts (1, :) double ...
        {mustBeInteger, ...
        mustBeMember(options.Figure3TransmissionCounts, 1:4)} = [1, 4]
    options.LoadDensitiesVehiclesPerKilometer (1, :) double ...
        {mustBeReal, mustBeFinite, mustBePositive} = [5, 40, 80]
    options.StaticTransmissionCounts (1, :) double ...
        {mustBeInteger, ...
        mustBeMember(options.StaticTransmissionCounts, 1:4)} = 1:4
    options.AdaptiveStrategies (1, :) string = ...
        ["deterministic", "probabilistic"]
    options.IncludeEccPropagation (1, 1) logical = true
    options.EccDensitiesVehiclesPerKilometer (1, :) double ...
        {mustBeReal, mustBeFinite, mustBePositive} = [5, 80]
    options.EccTransmissionCounts (1, :) double ...
        {mustBeInteger, ...
        mustBeMember(options.EccTransmissionCounts, 1:4)} = [1, 4]
    options.ExecutionMode (1, 1) string {mustBeMember( ...
        options.ExecutionMode, ["auto", "serial", "parallel"])} = "auto"
    options.MaxWorkers (1, 1) double { ...
        v2xsimregression.execution.mustBeWorkerLimit} = Inf
end

arguments (Output)
    results table
end

validateCampaignOptions(options);
[simulatorDirectory, fixtureDirectory, packetErrorRateDirectory] = ...
    resolveSimulatorDirectories(simulatorRoot);
validateSimulatorRoot( ...
    simulatorRoot, simulatorDirectory, fixtureDirectory, ...
    packetErrorRateDirectory);
prepareOutputDirectory(outputDirectory);

originalPath = path;
randomStream = RandStream.getGlobalStream();
originalRandomState = randomStream.State;
environmentCleanup = onCleanup( ...
    @() restoreEnvironment( ...
        originalPath, randomStream, originalRandomState));

addpath(fullfile(simulatorRoot, "src"));
addpath(simulatorDirectory);

configurations = createConfigurations( ...
    fixtureDirectory, outputDirectory, options);
workItems = cell(1, 0);
workLabels = strings(1, 0);
for configurationIndex = 1:numel(configurations)
    configuration = configurations{configurationIndex};
    for randomSeed = options.RandomSeeds
        seedDirectory = fullfile( ...
            configuration.OutputDirectory, ...
            compose("seed-%d", randomSeed));
        workItem = struct( ...
            SimulatorDirectory=simulatorDirectory, ...
            PacketErrorRateDirectory=packetErrorRateDirectory, ...
            Configuration=configuration, ...
            OutputDirectory=seedDirectory, ...
            RandomSeed=randomSeed, ...
            SimulationTimeSeconds=options.SimulationTimeSeconds);
        workItems{end + 1} = workItem; %#ok<AGROW>
        workLabels(end + 1) = compose( ...
            "case=%s,seed=%d", configuration.CaseName, ...
            randomSeed); %#ok<AGROW>
    end
end

additionalPaths = [ ...
    fullfile(simulatorRoot, "regression-tests"), ...
    fullfile(simulatorRoot, "src"), ...
    simulatorDirectory];
seedDirectoryOutputs = ...
    v2xsimregression.execution.runWorkItems( ...
        workItems, @runSeedWorkItem, ...
        Labels=workLabels, ...
        ExecutionMode=options.ExecutionMode, ...
        MaxWorkers=options.MaxWorkers, ...
        AdditionalPaths=additionalPaths);

results = createEmptyResults(0);
workIndex = 0;
for configurationIndex = 1:numel(configurations)
    configuration = configurations{configurationIndex};
    seedRange = workIndex + (1:numel(options.RandomSeeds));
    seedDirectories = string(seedDirectoryOutputs(seedRange)).';
    workIndex = workIndex + numel(options.RandomSeeds);
    summary = summarizeConfiguration( ...
        configuration.PaperFigures, configuration.CaseName, ...
        configuration.Density, configuration.ChannelModel, ...
        configuration.SensitivityDbm, configuration.Strategy, ...
        configuration.TransmissionCount, options.RandomSeeds, ...
        options.SimulationTimeSeconds, ...
        configuration.OutputDirectory, seedDirectories);
    results = [results; summary]; %#ok<AGROW>
end

writetable(results, fullfile(outputDirectory, "campaign-summary.csv"));
end

function validateCampaignOptions(options)
if isempty(options.Figures) || isempty(options.RandomSeeds)
    error( ...
        "v2xsimregression:zhuofei2023repetition:EmptyCampaign", ...
        "Figures and RandomSeeds must both be nonempty.");
end

uniqueOptions = { ...
    options.Figures, ...
    options.RandomSeeds, ...
    options.Figure3PreambleSensitivitiesDbm, ...
    options.Figure3TransmissionCounts, ...
    options.LoadDensitiesVehiclesPerKilometer, ...
    options.StaticTransmissionCounts, ...
    options.AdaptiveStrategies, ...
    options.EccDensitiesVehiclesPerKilometer, ...
    options.EccTransmissionCounts};
optionNames = [ ...
    "Figures", ...
    "RandomSeeds", ...
    "Figure3PreambleSensitivitiesDbm", ...
    "Figure3TransmissionCounts", ...
    "LoadDensitiesVehiclesPerKilometer", ...
    "StaticTransmissionCounts", ...
    "AdaptiveStrategies", ...
    "EccDensitiesVehiclesPerKilometer", ...
    "EccTransmissionCounts"];
for optionIndex = 1:numel(uniqueOptions)
    values = uniqueOptions{optionIndex};
    if numel(unique(values)) ~= numel(values)
        error( ...
            "v2xsimregression:zhuofei2023repetition:DuplicateOption", ...
            "%s must not contain duplicates.", ...
            optionNames(optionIndex));
    end
end

if any(options.Figure3PreambleSensitivitiesDbm >= 0)
    error( ...
        "v2xsimregression:zhuofei2023repetition:InvalidSensitivity", ...
        "Preamble sensitivities must be negative values in dBm.");
end

supportedStrategies = ["deterministic", "probabilistic"];
if any(~ismember(options.AdaptiveStrategies, supportedStrategies))
    unsupportedStrategies = options.AdaptiveStrategies( ...
        ~ismember(options.AdaptiveStrategies, supportedStrategies));
    error( ...
        "v2xsimregression:zhuofei2023repetition:UnsupportedStrategy", ...
        "Unsupported repetition strategy or strategies: %s.", ...
        join(unsupportedStrategies, ", "));
end
if ismember(5, options.Figures) && isempty(options.AdaptiveStrategies)
    error( ...
        "v2xsimregression:zhuofei2023repetition:MissingStrategy", ...
        "Figure 5 requires at least one adaptive strategy.");
end
end

function configurations = createConfigurations( ...
        fixtureDirectory, outputDirectory, options)
configurations = cell(1, 0);
configurationFile = fullfile(fixtureDirectory, "figure3.cfg");

if ismember(3, options.Figures)
    for sensitivityDbm = options.Figure3PreambleSensitivitiesDbm
        for transmissionCount = options.Figure3TransmissionCounts
            caseName = compose( ...
                "preamble-%d-static-transmissions-%d", ...
                abs(sensitivityDbm), transmissionCount);
            caseOutputDirectory = fullfile( ...
                outputDirectory, "figure-3", caseName);
            configuration = createConfiguration( ...
                "3", caseName, 5, "WINNER+ B1", sensitivityDbm, ...
                "static", transmissionCount, configurationFile, ...
                caseOutputDirectory);
            configurations{end + 1} = configuration; %#ok<AGROW>
        end
    end
end

if ~any(ismember(options.Figures, [4, 5]))
    return
end

configurationFile = fullfile(fixtureDirectory, "figures4and5.cfg");
hasFigure4 = ismember(4, options.Figures);
hasFigure5 = ismember(5, options.Figures);

if hasFigure4 && hasFigure5
    staticPaperFigures = "4,5";
elseif hasFigure4
    staticPaperFigures = "4";
else
    staticPaperFigures = "5";
end

for density = options.LoadDensitiesVehiclesPerKilometer
    for transmissionCount = options.StaticTransmissionCounts
        configuration = createLoadConfiguration( ...
            configurationFile, outputDirectory, ...
            staticPaperFigures, density, "WINNER+ B1", -100, ...
            "static", transmissionCount);
        configurations{end + 1} = configuration; %#ok<AGROW>
    end
end

if hasFigure4 && options.IncludeEccPropagation
    for density = options.EccDensitiesVehiclesPerKilometer
        for transmissionCount = options.EccTransmissionCounts
            configuration = createLoadConfiguration( ...
                configurationFile, outputDirectory, ...
                "4", density, "ECC rural", -100, ...
                "static", transmissionCount);
            configurations{end + 1} = configuration; %#ok<AGROW>
        end
    end
end

if hasFigure5
    for density = options.LoadDensitiesVehiclesPerKilometer
        for strategy = options.AdaptiveStrategies
            configuration = createLoadConfiguration( ...
                configurationFile, outputDirectory, ...
                "5", density, "WINNER+ B1", -100, ...
                strategy, 4);
            configurations{end + 1} = configuration; %#ok<AGROW>
        end
    end
end
end

function configuration = createLoadConfiguration( ...
        configurationFile, outputDirectory, paperFigures, ...
        density, channelModel, sensitivityDbm, strategy, ...
        transmissionCount)
caseName = compose( ...
    "%s-density-%g-%s-transmissions-%d", ...
    channelSlug(channelModel), density, strategy, transmissionCount);
caseOutputDirectory = fullfile( ...
    outputDirectory, "figures-4-5", caseName);
configuration = createConfiguration( ...
    paperFigures, caseName, density, channelModel, ...
    sensitivityDbm, strategy, transmissionCount, configurationFile, ...
    caseOutputDirectory);
end

function configuration = createConfiguration( ...
        paperFigures, caseName, density, channelModel, ...
        sensitivityDbm, strategy, transmissionCount, ...
        configurationFile, outputDirectory)
configuration = struct( ...
    PaperFigures=paperFigures, ...
    CaseName=caseName, ...
    Density=density, ...
    ChannelModel=channelModel, ...
    SensitivityDbm=sensitivityDbm, ...
    Strategy=strategy, ...
    TransmissionCount=transmissionCount, ...
    ConfigurationFile=configurationFile, ...
    OutputDirectory=outputDirectory);
end

function seedDirectory = runSeedWorkItem(workItem)
configuration = workItem.Configuration;
seedDirectory = workItem.OutputDirectory;
    runSimulation( ...
        workItem.SimulatorDirectory, ...
        configuration.ConfigurationFile, ...
        workItem.PacketErrorRateDirectory, seedDirectory, ...
        configuration.Density, configuration.ChannelModel, ...
        configuration.SensitivityDbm, configuration.Strategy, ...
        configuration.TransmissionCount, workItem.RandomSeed, ...
        workItem.SimulationTimeSeconds);
end

function runSimulation( ...
        simulatorDirectory, configurationFile, ...
        packetErrorRateDirectory, outputDirectory, ...
        paperDensity, channelModel, sensitivityDbm, strategy, ...
        transmissionCount, randomSeed, simulationTimeSeconds)
prepareOutputDirectory(outputDirectory);
[roadLengthMeters, simulatedDensity, pathLossModel] = ...
    channelDefinition(paperDensity, channelModel);
vehicleCount = round( ...
    simulatedDensity .* roadLengthMeters ./ 1000);

simulationArguments = { ...
    configurationFile, ...
    "simulation.RequiredVersion", "V7", ...
    "simulation.RandomSeed", randomSeed, ...
    "scenarioOptions.RandomSeed", randomSeed, ...
    "simulation.DurationSeconds", simulationTimeSeconds, ...
    "simulation.RadioAccessMode", "80211p", ...
    "scenario.Type", "BidirectionalHighwayScenario", ...
    "scenarioOptions.VehicleCount", vehicleCount, ...
    "scenarioOptions.NLanes", 3, ...
    "scenarioOptions.LaneWidth", 4, ...
    "scenarioOptions.RoadLength", roadLengthMeters, ...
    "scenarioOptions.CentralDividerWidth", 0, ...
    "scenarioOptions.MeanVehicleSpeed", 120 ./ 3.6, ...
    "scenarioOptions.VehicleSpeedStandardDeviation", 12 ./ 3.6, ...
    "scenarioOptions.RerollSpeedOnWrapAround", false, ...
    "application.PacketSizeBytes", 350, ...
    "application.ResourceReservationIntervalSeconds", 0.1, ...
    "application.PacketGeneration.IntervalSeconds", 0.1, ...
    "application.PacketGeneration.IntervalVariationSeconds", 0, ...
    "channelLoad.Enabled", true, ...
    "channelLoad.MeasurementWindowSeconds", 0.1, ...
    "channelLoad.UpdateStepsPerWindow", 100, ...
    "congestionControl.Enabled", false, ...
    "radio.ReceiverNoiseFigureDb", 6, ...
    "ieee80211p.PreambleSensitivityDbm", sensitivityDbm, ...
    "ieee80211p.RelativeInterferenceLevelModelEnabled", true, ...
    "ieee80211p.Mcs", 2, ...
    "channel.PacketErrorRateCurveDirectory", ...
        packetErrorRateDirectory, ...
    "channel.PathLoss.Model", pathLossModel, ...
    "itsG5.Repetition.Mode", strategyCode(strategy), ...
    "itsG5.Repetition.MaximumTransmissionCount", transmissionCount, ...
    "itsG5.Repetition.BackoffMicroseconds", 32, ...
    "itsG5.Repetition.LowCbrThreshold", 0.03, ...
    "itsG5.Repetition.MediumCbrThreshold", 0.05, ...
    "itsG5.Repetition.HighCbrThreshold", 0.09, ...
    "awareness.RangesMeters", 300, ...
    "output.PacketReceptionRatio.Enabled", true, ...
    "output.PacketReceptionRatio.DistanceBinWidthMeters", 10, ...
    "output.ChannelBusyRatio.Enabled", true, ...
    "output.AverageNeighborCount.Enabled", false, ...
    "output.UpdateDelay.Enabled", false, ...
    "output.PacketDelay.Enabled", false, ...
    "output.DataAge.Enabled", false, ...
    "simulation.RunLabel", compose( ...
        "Zhuofei2023 repetition: density=%g, channel=%s, " + ...
        "sensitivity=%g, strategy=%s, transmissions=%d, seed=%d", ...
        paperDensity, channelModel, sensitivityDbm, strategy, ...
        transmissionCount, randomSeed), ...
    "output.Directory", outputDirectory};

if channelModel == "ECC rural"
    eccArguments = { ...
        "channel.PathLoss.ReferenceLossAtOneMeterDb", 47.85, ...
        "channel.PathLoss.Exponent1", 2, ...
        "channel.PathLoss.BreakpointDistance1Meters", 128, ...
        "channel.PathLoss.Exponent2", 2.8, ...
        "channel.PathLoss.BreakpointDistance2Meters", 512, ...
        "channel.PathLoss.Exponent3", 3.3};
    simulationArguments = [simulationArguments, eccArguments]; %#ok<NASGU>
end

evalc("WiLabV2Xsim(simulationArguments{:});");
validateSimulationOutputs(outputDirectory);

if ~contains(which("WiLabV2Xsim"), simulatorDirectory)
    error( ...
        "v2xsimregression:zhuofei2023repetition:WrongSimulator", ...
        "WiLabV2Xsim resolved outside the requested simulator: %s", ...
        which("WiLabV2Xsim"));
end
end

function validateSimulationOutputs(outputDirectory)
expectedFiles = [ ...
    "MainOut.xls", ...
    "packet_reception_ratio_1_11p.csv", ...
    "CBRstatistic_1_11p.csv"];
for expectedFile = expectedFiles
    expectedPath = fullfile(outputDirectory, expectedFile);
    if ~isfile(expectedPath)
        error( ...
            "v2xsimregression:zhuofei2023repetition:MissingOutput", ...
            "The simulator did not create the expected file: %s", ...
            expectedPath);
    end
end
end

function summary = summarizeConfiguration( ...
        paperFigures, caseName, paperDensity, channelModel, ...
        sensitivityDbm, strategy, transmissionCount, ...
        randomSeeds, simulationTimeSeconds, ...
        caseOutputDirectory, seedDirectories)
[roadLengthMeters, simulatedDensity, ~, maximumScoreDistanceMeters] = ...
    channelDefinition(paperDensity, channelModel);
vehicleCount = round( ...
    simulatedDensity .* roadLengthMeters ./ 1000);
prrFiles = fullfile( ...
    seedDirectories, "packet_reception_ratio_1_11p.csv");
cbrFiles = fullfile(seedDirectories, "CBRstatistic_1_11p.csv");
[normalizedPrrScore, rangeAt90Meters] = summarizePrr( ...
    prrFiles, maximumScoreDistanceMeters);
meanNetCbr = summarizeCbr(cbrFiles);

if strategy == "static"
    repetitionCount = transmissionCount - 1;
else
    repetitionCount = NaN;
end

seedCount = numel(randomSeeds);
summary = table( ...
    paperFigures, caseName, channelModel, ...
    paperDensity, simulatedDensity, roadLengthMeters, vehicleCount, ...
    sensitivityDbm, strategy, transmissionCount, repetitionCount, ...
    seedCount, simulationTimeSeconds, maximumScoreDistanceMeters, ...
    normalizedPrrScore, rangeAt90Meters, meanNetCbr, ...
    caseOutputDirectory, ...
    VariableNames=[ ...
        "PaperFigures", "CaseName", "ChannelModel", ...
        "PaperDensityVehiclesPerKilometer", ...
        "SimulatedDensityVehiclesPerKilometer", ...
        "RoadLengthMeters", "VehicleCount", ...
        "PreambleSensitivityDbm", "Strategy", ...
        "MaximumTransmissionCount", "RepetitionCount", ...
        "SeedCount", "SimulationTimeSeconds", ...
        "MaximumScoreDistanceMeters", ...
        "NormalizedPrrScore", "RangeAt90Meters", "MeanNetCbr", ...
        "OutputDirectory"]);
end

function [normalizedPrrScore, rangeAt90Meters] = ...
        summarizePrr(prrFiles, maximumScoreDistanceMeters)
distanceBinWidthMeters = 50;
allDistancesMeters = zeros(0, 1);
fileData = cell(numel(prrFiles), 1);
for fileIndex = 1:numel(prrFiles)
    prrData = readmatrix( ...
        prrFiles(fileIndex), FileType="text", Delimiter=",");
    fileData{fileIndex} = prrData;
    allDistancesMeters = [ ...
        allDistancesMeters; prrData(:, 1)]; %#ok<AGROW>
end

allDistancesMeters = unique(allDistancesMeters);
correctPackets = zeros(size(allDistancesMeters));
totalPackets = zeros(size(allDistancesMeters));
for fileIndex = 1:numel(fileData)
    prrData = fileData{fileIndex};
    [hasDistance, pooledRow] = ismember( ...
        prrData(:, 1), allDistancesMeters);
    correctPackets(pooledRow(hasDistance)) = ...
        correctPackets(pooledRow(hasDistance)) + ...
        prrData(hasDistance, 2);
    totalPackets(pooledRow(hasDistance)) = ...
        totalPackets(pooledRow(hasDistance)) + ...
        prrData(hasDistance, 5);
end

isScoredDistance = ...
    allDistancesMeters > 0 & ...
    allDistancesMeters <= maximumScoreDistanceMeters;
scoredDistancesMeters = allDistancesMeters(isScoredDistance);
scoredCorrectPackets = correctPackets(isScoredDistance);
scoredTotalPackets = totalPackets(isScoredDistance);
distanceGroup = ceil( ...
    scoredDistancesMeters ./ distanceBinWidthMeters);
groupCount = floor( ...
    maximumScoreDistanceMeters ./ distanceBinWidthMeters);
groupCorrectPackets = accumarray( ...
    distanceGroup, scoredCorrectPackets, [groupCount, 1]);
groupTotalPackets = accumarray( ...
    distanceGroup, scoredTotalPackets, [groupCount, 1]);
groupDistancesMeters = ...
    (distanceBinWidthMeters: ...
    distanceBinWidthMeters:maximumScoreDistanceMeters).';
hasSamples = groupTotalPackets > 0;
groupDistancesMeters = groupDistancesMeters(hasSamples);
packetReceptionRatios = ...
    groupCorrectPackets(hasSamples) ./ groupTotalPackets(hasSamples);

if isempty(groupDistancesMeters)
    error( ...
        "v2xsimregression:zhuofei2023repetition:MissingPrrSamples", ...
        "No pooled PRR samples were available within the score range.");
end

normalizedPrrScore = trapz( ...
    [0; groupDistancesMeters], ...
    [1; packetReceptionRatios]) ./ maximumScoreDistanceMeters;
rangeAt90Meters = firstThresholdCrossing( ...
    groupDistancesMeters, packetReceptionRatios, 0.9);
end

function crossingDistance = firstThresholdCrossing( ...
        distances, values, threshold)
firstBelowThreshold = find(values < threshold, 1);
if isempty(firstBelowThreshold)
    crossingDistance = distances(end);
elseif firstBelowThreshold == 1
    crossingDistance = 0;
else
    leftIndex = firstBelowThreshold - 1;
    rightIndex = firstBelowThreshold;
    crossingDistance = interp1( ...
        values([leftIndex, rightIndex]), ...
        distances([leftIndex, rightIndex]), threshold);
end
end

function meanNetCbr = summarizeCbr(cbrFiles)
seedMeans = zeros(numel(cbrFiles), 1);
for fileIndex = 1:numel(cbrFiles)
    cbrData = readmatrix( ...
        cbrFiles(fileIndex), FileType="text", Delimiter=",");
    isFiniteRow = all(isfinite(cbrData(:, 1:2)), 2);
    cbrValues = cbrData(isFiniteRow, 1);
    empiricalCdf = cbrData(isFiniteRow, 2);
    if isempty(cbrValues) || empiricalCdf(end) < 0.999
        error( ...
            "v2xsimregression:zhuofei2023repetition:InvalidCbrOutput", ...
            "The CBR empirical distribution is empty or incomplete: %s", ...
            cbrFiles(fileIndex));
    end
    probabilityMass = diff([0; empiricalCdf]);
    seedMeans(fileIndex) = sum(cbrValues .* probabilityMass);
end
meanNetCbr = mean(seedMeans);
end

function results = createEmptyResults(rowCount)
results = table( ...
    Size=[rowCount, 18], ...
    VariableTypes=[ ...
        "string", "string", "string", ...
        "double", "double", "double", "double", ...
        "double", "string", "double", "double", ...
        "double", "double", "double", ...
        "double", "double", "double", "string"], ...
    VariableNames=[ ...
        "PaperFigures", "CaseName", "ChannelModel", ...
        "PaperDensityVehiclesPerKilometer", ...
        "SimulatedDensityVehiclesPerKilometer", ...
        "RoadLengthMeters", "VehicleCount", ...
        "PreambleSensitivityDbm", "Strategy", ...
        "MaximumTransmissionCount", "RepetitionCount", ...
        "SeedCount", "SimulationTimeSeconds", ...
        "MaximumScoreDistanceMeters", ...
        "NormalizedPrrScore", "RangeAt90Meters", "MeanNetCbr", ...
        "OutputDirectory"]);
end

function code = strategyCode(strategy)
if strategy == "static"
    code = 0;
elseif strategy == "deterministic"
    code = 1;
elseif strategy == "probabilistic"
    code = 2;
else
    error( ...
        "v2xsimregression:zhuofei2023repetition:UnsupportedStrategy", ...
        "Unsupported repetition strategy: %s.", strategy);
end
end

function slug = channelSlug(channelModel)
if channelModel == "WINNER+ B1"
    slug = "winner-b1";
elseif channelModel == "ECC rural"
    slug = "ecc-rural";
else
    error( ...
        "v2xsimregression:zhuofei2023repetition:UnsupportedChannel", ...
        "Unsupported channel model: %s.", channelModel);
end
end

function [roadLengthMeters, simulatedDensity, pathLossModel, ...
        maximumScoreDistanceMeters] = ...
        channelDefinition(paperDensity, channelModel)
if channelModel == "WINNER+ B1"
    roadLengthMeters = 2000;
    simulatedDensity = paperDensity;
    pathLossModel = 0;
    maximumScoreDistanceMeters = 650;
elseif channelModel == "ECC rural"
    roadLengthMeters = 8000;
    simulatedDensity = paperDensity ./ 4;
    pathLossModel = 3;
    maximumScoreDistanceMeters = 2000;
else
    error( ...
        "v2xsimregression:zhuofei2023repetition:UnsupportedChannel", ...
        "Unsupported channel model: %s.", channelModel);
end
end

function [simulatorDirectory, fixtureDirectory, ...
        packetErrorRateDirectory] = ...
        resolveSimulatorDirectories(simulatorRoot)
simulatorDirectory = fullfile(simulatorRoot, "old_src");
fixtureDirectory = fullfile(fileparts(mfilename("fullpath")), "config");
packetErrorRateDirectory = fullfile( ...
    simulatorDirectory, "PERcurves", "G5-HighwayLOS");
end

function validateSimulatorRoot( ...
        simulatorRoot, simulatorDirectory, fixtureDirectory, ...
        packetErrorRateDirectory)
if ~isfolder(simulatorRoot)
    error( ...
        "v2xsimregression:zhuofei2023repetition:MissingSimulatorRoot", ...
        "SimulatorRoot is not a directory: %s", simulatorRoot);
end
if ~isfile(fullfile(simulatorDirectory, "WiLabV2Xsim.m"))
    error( ...
        "v2xsimregression:zhuofei2023repetition:MissingSimulator", ...
        "WiLabV2Xsim.m was not found under: %s", ...
        simulatorDirectory);
end
requiredConfigurations = [ ...
    fullfile(fixtureDirectory, "figure3.cfg"), ...
    fullfile(fixtureDirectory, "figures4and5.cfg")];
for requiredConfiguration = requiredConfigurations
    if ~isfile(requiredConfiguration)
        error( ...
            "v2xsimregression:zhuofei2023repetition:MissingConfiguration", ...
            "A regression configuration was not found: %s", ...
            requiredConfiguration);
    end
end
if ~isfolder(packetErrorRateDirectory)
    error( ...
        "v2xsimregression:zhuofei2023repetition:MissingPerCurves", ...
        "The paper's PER curves were not found under: %s", ...
        packetErrorRateDirectory);
end
if ~isfolder(fullfile(simulatorRoot, "src", "+v2xsim"))
    error( ...
        "v2xsimregression:zhuofei2023repetition:MissingRefactoredSource", ...
        "The simulator root requires src/+v2xsim under: %s", ...
        simulatorRoot);
end
end

function prepareOutputDirectory(outputDirectory)
if isfolder(outputDirectory)
    directoryEntries = dir(outputDirectory);
    isContent = ~ismember({directoryEntries.name}, {".", ".."});
    if any(isContent)
        error( ...
            "v2xsimregression:zhuofei2023repetition:OutputNotEmpty", ...
            "Refusing to append results in nonempty folder: %s", ...
            outputDirectory);
    end
else
    [wasCreated, message] = mkdir(outputDirectory);
    if ~wasCreated
        error( ...
            "v2xsimregression:zhuofei2023repetition:" + ...
            "OutputCreationFailed", ...
            "Could not create output folder %s: %s", ...
            outputDirectory, message);
    end
end
end

function simulationTimeSeconds = defaultSimulationTimeSeconds()
configuredValue = string(getenv( ...
    "V2XSIM_PAPER_SIMULATION_TIME_SECONDS"));
if configuredValue == ""
    simulationTimeSeconds = 5;
    return
end

simulationTimeSeconds = str2double(configuredValue);
if ~isscalar(simulationTimeSeconds) || ...
        ~isfinite(simulationTimeSeconds) || simulationTimeSeconds <= 0
    error( ...
        "v2xsimregression:zhuofei2023repetition:InvalidDuration", ...
        ["V2XSIM_PAPER_SIMULATION_TIME_SECONDS must contain a ", ...
        "positive finite number."]);
end
end

function restoreEnvironment( ...
        originalPath, randomStream, originalRandomState)
path(originalPath);
RandStream.setGlobalStream(randomStream);
randomStream.State = originalRandomState;
end
