function results = runPublishedCampaigns( ...
        simulatorRoot, outputDirectory, options)
%RUNPUBLISHEDCAMPAIGNS Run the Zhuofei et al. repetition campaigns.
%   RESULTS contains one row per pooled configuration. The runner samples
%   the conclusions behind Figures 3-5 instead of reproducing every point
%   in the paper's full Monte Carlo sweep.

arguments (Input)
    simulatorRoot (1, 1) string {mustBeNonzeroLengthText}
    outputDirectory (1, 1) string {mustBeNonzeroLengthText}
    options.Figures (1, :) double ...
        {mustBeInteger, mustBeMember(options.Figures, [3, 4, 5])} = ...
        [3, 4, 5]
    options.RandomSeeds (1, :) double ...
        {mustBeInteger, mustBePositive} = 10:11
    options.SimulationTimeSeconds (1, 1) double ...
        {mustBeReal, mustBeFinite, mustBePositive} = ...
        defaultSimulationTimeSeconds()
    options.Figure3PreambleSensitivitiesDbm (1, :) double ...
        {mustBeReal, mustBeFinite} = [-100, -103, -120]
    options.Figure3TransmissionCounts (1, :) double ...
        {mustBeInteger, ...
        mustBeMember(options.Figure3TransmissionCounts, 1:4)} = [1, 4]
    options.LoadDensitiesVehiclesPerKilometer (1, :) double ...
        {mustBeReal, mustBeFinite, mustBePositive} = [5, 40, 80]
    options.StaticTransmissionCounts (1, :) double ...
        {mustBeInteger, ...
        mustBeMember(options.StaticTransmissionCounts, 1:4)} = 1:4
    options.AdaptiveStrategies (1, :) string = ...
        ["deterministic", "probabilistic"]
    options.IncludeEccPropagation (1, 1) logical = true
    options.EccDensitiesVehiclesPerKilometer (1, :) double ...
        {mustBeReal, mustBeFinite, mustBePositive} = [5, 80]
    options.EccTransmissionCounts (1, :) double ...
        {mustBeInteger, ...
        mustBeMember(options.EccTransmissionCounts, 1:4)} = [1, 4]
    options.ExecutionMode (1, 1) string {mustBeMember( ...
        options.ExecutionMode, ["auto", "serial", "parallel"])} = "auto"
    options.MaxWorkers (1, 1) double { ...
        v2xsimregression.execution.mustBeWorkerLimit} = Inf
end

arguments (Output)
    results table
end

validateCampaignOptions(options);
[sourceDirectory, fixtureDirectory, packetErrorRateDirectory, ...
    tomlDirectory] = ...
    resolveSimulatorDirectories(simulatorRoot);
validateSimulatorRoot( ...
    simulatorRoot, fixtureDirectory, ...
    packetErrorRateDirectory);
prepareOutputDirectory(outputDirectory);

originalPath = path;
randomStream = RandStream.getGlobalStream();
originalRandomState = randomStream.State;
environmentCleanup = onCleanup( ...
    @() restoreEnvironment( ...
        originalPath, randomStream, originalRandomState));

addpath(sourceDirectory);
addpath(tomlDirectory);

configurations = createConfigurations( ...
    fixtureDirectory, outputDirectory, options);
assertUniqueConfigurationDirectories(configurations);
workItems = cell(1, 0);
workLabels = strings(1, 0);
for configurationIndex = 1:numel(configurations)
    configuration = configurations{configurationIndex};
    for randomSeed = options.RandomSeeds
        seedDirectory = fullfile( ...
            configuration.OutputDirectory, ...
            compose("seed-%d", randomSeed));
        workItem = struct( ...
            SourceDirectory=sourceDirectory, ...
            PacketErrorRateDirectory=packetErrorRateDirectory, ...
            Configuration=configuration, ...
            OutputDirectory=seedDirectory, ...
            RandomSeed=randomSeed, ...
            SimulationTimeSeconds=options.SimulationTimeSeconds);
        workItems{end + 1} = workItem; %#ok<AGROW>
        workLabels(end + 1) = compose( ...
            "case=%s,seed=%d", configuration.CaseName, ...
            randomSeed); %#ok<AGROW>
    end
end

additionalPaths = [ ...
    fullfile(simulatorRoot, "regression-tests"), ...
    sourceDirectory, ...
    tomlDirectory];
seedDirectoryOutputs = ...
    v2xsimregression.execution.runWorkItems( ...
        workItems, @runSeedWorkItem, ...
        Labels=workLabels, ...
        ExecutionMode=options.ExecutionMode, ...
        MaxWorkers=options.MaxWorkers, ...
        AdditionalPaths=additionalPaths);

results = createEmptyResults(0);
workIndex = 0;
for configurationIndex = 1:numel(configurations)
    configuration = configurations{configurationIndex};
    seedRange = workIndex + (1:numel(options.RandomSeeds));
    seedDirectories = string(seedDirectoryOutputs(seedRange)).';
    workIndex = workIndex + numel(options.RandomSeeds);
    summary = summarizeConfiguration( ...
        configuration.PaperFigures, configuration.CaseName, ...
        configuration.Density, configuration.ChannelModel, ...
        configuration.SensitivityDbm, configuration.Strategy, ...
        configuration.TransmissionCount, options.RandomSeeds, ...
        options.SimulationTimeSeconds, ...
        configuration.OutputDirectory, seedDirectories);
    results = [results; summary]; %#ok<AGROW>
end

writetable(results, fullfile(outputDirectory, "campaign-summary.csv"));
end

function validateCampaignOptions(options)
if isempty(options.Figures) || isempty(options.RandomSeeds)
    error( ...
        "v2xsimregression:zhuofei2023repetition:EmptyCampaign", ...
        "Figures and RandomSeeds must both be nonempty.");
end

uniqueOptions = { ...
    options.Figures, ...
    options.RandomSeeds, ...
    options.Figure3PreambleSensitivitiesDbm, ...
    options.Figure3TransmissionCounts, ...
    options.LoadDensitiesVehiclesPerKilometer, ...
    options.StaticTransmissionCounts, ...
    options.AdaptiveStrategies, ...
    options.EccDensitiesVehiclesPerKilometer, ...
    options.EccTransmissionCounts};
optionNames = [ ...
    "Figures", ...
    "RandomSeeds", ...
    "Figure3PreambleSensitivitiesDbm", ...
    "Figure3TransmissionCounts", ...
    "LoadDensitiesVehiclesPerKilometer", ...
    "StaticTransmissionCounts", ...
    "AdaptiveStrategies", ...
    "EccDensitiesVehiclesPerKilometer", ...
    "EccTransmissionCounts"];
for optionIndex = 1:numel(uniqueOptions)
    values = uniqueOptions{optionIndex};
    if numel(unique(values)) ~= numel(values)
        error( ...
            "v2xsimregression:zhuofei2023repetition:DuplicateOption", ...
            "%s must not contain duplicates.", ...
            optionNames(optionIndex));
    end
end

if any(options.Figure3PreambleSensitivitiesDbm >= 0)
    error( ...
        "v2xsimregression:zhuofei2023repetition:InvalidSensitivity", ...
        "Preamble sensitivities must be negative values in dBm.");
end

supportedStrategies = ["deterministic", "probabilistic"];
if any(~ismember(options.AdaptiveStrategies, supportedStrategies))
    unsupportedStrategies = options.AdaptiveStrategies( ...
        ~ismember(options.AdaptiveStrategies, supportedStrategies));
    error( ...
        "v2xsimregression:zhuofei2023repetition:UnsupportedStrategy", ...
        "Unsupported repetition strategy or strategies: %s.", ...
        join(unsupportedStrategies, ", "));
end
if ismember(5, options.Figures) && isempty(options.AdaptiveStrategies)
    error( ...
        "v2xsimregression:zhuofei2023repetition:MissingStrategy", ...
        "Figure 5 requires at least one adaptive strategy.");
end
end

function configurations = createConfigurations( ...
        fixtureDirectory, outputDirectory, options)
configurations = cell(1, 0);
configurationFile = fullfile(fixtureDirectory, "figure3.toml");

if ismember(3, options.Figures)
    for sensitivityDbm = options.Figure3PreambleSensitivitiesDbm
        for transmissionCount = options.Figure3TransmissionCounts
            caseName = compose( ...
                "preamble-%d-static-transmissions-%d", ...
                abs(sensitivityDbm), transmissionCount);
            caseOutputDirectory = fullfile( ...
                outputDirectory, "figure-3", caseName);
            configuration = createConfiguration( ...
                "3", caseName, 5, "WINNER+ B1", sensitivityDbm, ...
                "static", transmissionCount, configurationFile, ...
                caseOutputDirectory);
            configurations{end + 1} = configuration; %#ok<AGROW>
        end
    end
end

if ~any(ismember(options.Figures, [4, 5]))
    return
end

configurationFile = fullfile(fixtureDirectory, "figures4and5.toml");
hasFigure4 = ismember(4, options.Figures);
hasFigure5 = ismember(5, options.Figures);

if hasFigure4 && hasFigure5
    staticPaperFigures = "4,5";
elseif hasFigure4
    staticPaperFigures = "4";
else
    staticPaperFigures = "5";
end

for density = options.LoadDensitiesVehiclesPerKilometer
    for transmissionCount = options.StaticTransmissionCounts
        configuration = createLoadConfiguration( ...
            configurationFile, outputDirectory, ...
            staticPaperFigures, density, "WINNER+ B1", -100, ...
            "static", transmissionCount);
        configurations{end + 1} = configuration; %#ok<AGROW>
    end
end

if hasFigure4 && options.IncludeEccPropagation
    for density = options.EccDensitiesVehiclesPerKilometer
        for transmissionCount = options.EccTransmissionCounts
            configuration = createLoadConfiguration( ...
                configurationFile, outputDirectory, ...
                "4", density, "ECC rural", -100, ...
                "static", transmissionCount);
            configurations{end + 1} = configuration; %#ok<AGROW>
        end
    end
end

if hasFigure5
    for density = options.LoadDensitiesVehiclesPerKilometer
        for strategy = options.AdaptiveStrategies
            configuration = createLoadConfiguration( ...
                configurationFile, outputDirectory, ...
                "5", density, "WINNER+ B1", -100, ...
                strategy, 4);
            configurations{end + 1} = configuration; %#ok<AGROW>
        end
    end
end
end

function configuration = createLoadConfiguration( ...
        configurationFile, outputDirectory, paperFigures, ...
        density, channelModel, sensitivityDbm, strategy, ...
        transmissionCount)
caseName = compose( ...
    "%s-density-%s-%s-transmissions-%d", ...
    channelSlug(channelModel), numericPathToken(density), ...
    strategy, transmissionCount);
caseOutputDirectory = fullfile( ...
    outputDirectory, "figures-4-5", caseName);
configuration = createConfiguration( ...
    paperFigures, caseName, density, channelModel, ...
    sensitivityDbm, strategy, transmissionCount, configurationFile, ...
    caseOutputDirectory);
end

function configuration = createConfiguration( ...
        paperFigures, caseName, density, channelModel, ...
        sensitivityDbm, strategy, transmissionCount, ...
        configurationFile, outputDirectory)
configuration = struct( ...
    PaperFigures=paperFigures, ...
    CaseName=caseName, ...
    Density=density, ...
    ChannelModel=channelModel, ...
    SensitivityDbm=sensitivityDbm, ...
    Strategy=strategy, ...
    TransmissionCount=transmissionCount, ...
    ConfigurationFile=configurationFile, ...
    OutputDirectory=outputDirectory);
end

function token = numericPathToken(value)
token = compose("%.17g",value);
token = replace(token,["-", "+", "."],["m", "p", "d"]);
end

function assertUniqueConfigurationDirectories(configurations)
outputDirectories = strings(1, numel(configurations));
for configurationIndex = 1:numel(configurations)
    outputDirectories(configurationIndex) = ...
        string(configurations{configurationIndex}.OutputDirectory);
end
if numel(unique(outputDirectories)) ~= numel(outputDirectories)
    error( ...
        "v2xsimregression:zhuofei2023repetition:" + ...
        "OutputDirectoryCollision", ...
        "Campaign options generated duplicate run output directories.");
end
end

function seedDirectory = runSeedWorkItem(workItem)
configuration = workItem.Configuration;
seedDirectory = workItem.OutputDirectory;
    runSimulation( ...
        workItem.SourceDirectory, ...
        configuration.ConfigurationFile, ...
        workItem.PacketErrorRateDirectory, seedDirectory, ...
        configuration.Density, configuration.ChannelModel, ...
        configuration.SensitivityDbm, configuration.Strategy, ...
        configuration.TransmissionCount, workItem.RandomSeed, ...
        workItem.SimulationTimeSeconds);
end

function runSimulation( ...
        sourceDirectory, configurationFile, ...
        packetErrorRateDirectory, outputDirectory, ...
        paperDensity, channelModel, sensitivityDbm, strategy, ...
        transmissionCount, randomSeed, simulationTimeSeconds)
[roadLengthMeters, simulatedDensity, pathLossModel] = ...
    channelDefinition(paperDensity, channelModel);
vehicleCount = round( ...
    simulatedDensity .* roadLengthMeters ./ 1000);

pathLoss = struct(Model=pathLossModel);
if channelModel == "ECC rural"
    pathLoss.ReferenceLossAtOneMeterDb = 47.85;
    pathLoss.Exponent1 = 2;
    pathLoss.BreakpointDistance1Meters = 128;
    pathLoss.Exponent2 = 2.8;
    pathLoss.BreakpointDistance2Meters = 512;
    pathLoss.Exponent3 = 3.3;
end

patchData = struct( ...
    Simulation=struct( ...
        RandomSeed=randomSeed, ...
        DurationSeconds=simulationTimeSeconds), ...
    Scenario=struct( ...
        Type="BidirectionalHighway", ...
        BidirectionalHighway=struct( ...
            RandomSeed=randomSeed, ...
            VehicleCount=vehicleCount, ...
            NLanes=3, ...
            LaneWidth=4, ...
            RoadLength=roadLengthMeters, ...
            CentralDividerWidth=0, ...
            MeanVehicleSpeed=120 ./ 3.6, ...
            VehicleSpeedStandardDeviation=12 ./ 3.6, ...
            RerollSpeedOnWrapAround=false)), ...
    Application=struct( ...
        PacketSizeBytes=350, ...
        ResourceReservationIntervalSeconds=0.1, ...
        PacketGeneration=struct( ...
            IntervalSeconds=0.1, ...
            IntervalVariationSeconds=0), ...
        ChannelLoad=struct( ...
            Enabled=true, ...
            MeasurementWindowSeconds=0.1, ...
            UpdateStepsPerWindow=100), ...
        CongestionControl=struct(Enabled=false)), ...
    Radio=struct( ...
        Type="Ieee80211p", ...
        ReceiverNoiseFigureDb=6, ...
        Ieee80211p=struct( ...
            PreambleSensitivityDbm=sensitivityDbm, ...
            RelativeInterferenceLevelModelEnabled=true, ...
            Mcs=2, ...
            Repetition=struct( ...
                Mode=strategyType(strategy), ...
                MaximumTransmissionCount=transmissionCount, ...
                BackoffMicroseconds=32, ...
                CbrThresholds=[0.03, 0.05, 0.09]))), ...
    Channel=struct( ...
        PacketError=struct( ...
            Model="Curves", ...
            CurveDirectory=packetErrorRateDirectory), ...
        PathLoss=pathLoss), ...
    Awareness=struct(RangesMeters=300), ...
    Outputs=struct( ...
        PacketReceptionRatio=struct( ...
            Enabled=true, ...
            DistanceBinWidthMeters=10), ...
        ChannelBusyRatio=struct(Enabled=true), ...
        AverageNeighborCount=struct(Enabled=false), ...
        UpdateDelay=struct(Enabled=false), ...
        PacketDelay=struct(Enabled=false), ...
        DataAge=struct(Enabled=false)));
template = v2xsim.config.load(configurationFile);
configuration = template.resolve( ...
    Patch=v2xsim.config.patch(patchData)); %#ok<NASGU>
runLabel = compose( ...
    "Zhuofei2023 repetition: density=%g, channel=%s, " + ...
    "sensitivity=%g, strategy=%s, transmissions=%d, seed=%d", ...
    paperDensity, channelModel, sensitivityDbm, strategy, ...
    transmissionCount, randomSeed); %#ok<NASGU>
evalc("v2xsim.runSimulation(configuration," + ...
    "OutputDirectory=outputDirectory,RunLabel=runLabel);");
validateSimulationOutputs(outputDirectory);

resolvedEntrypoint = string(which("v2xsim.runSimulation"));
if ~startsWith(resolvedEntrypoint, sourceDirectory)
    error( ...
        "v2xsimregression:zhuofei2023repetition:WrongSimulator", ...
        "v2xsim.runSimulation resolved outside the requested simulator: %s", ...
        resolvedEntrypoint);
end
end

function validateSimulationOutputs(outputDirectory)
expectedFiles = [ ...
    "simulation_summary.json", ...
    "packet_reception_ratio_11p.csv", ...
    "CBRstatistic_11p.csv"];
for expectedFile = expectedFiles
    expectedPath = fullfile(outputDirectory, expectedFile);
    if ~isfile(expectedPath)
        error( ...
            "v2xsimregression:zhuofei2023repetition:MissingOutput", ...
            "The simulator did not create the expected file: %s", ...
            expectedPath);
    end
end
end

function summary = summarizeConfiguration( ...
        paperFigures, caseName, paperDensity, channelModel, ...
        sensitivityDbm, strategy, transmissionCount, ...
        randomSeeds, simulationTimeSeconds, ...
        caseOutputDirectory, seedDirectories)
[roadLengthMeters, simulatedDensity, ~, maximumScoreDistanceMeters] = ...
    channelDefinition(paperDensity, channelModel);
vehicleCount = round( ...
    simulatedDensity .* roadLengthMeters ./ 1000);
prrFiles = fullfile( ...
    seedDirectories, "packet_reception_ratio_11p.csv");
cbrFiles = fullfile(seedDirectories, "CBRstatistic_11p.csv");
[normalizedPrrScore, rangeAt90Meters] = summarizePrr( ...
    prrFiles, maximumScoreDistanceMeters);
meanNetCbr = summarizeCbr(cbrFiles);

if strategy == "static"
    repetitionCount = transmissionCount - 1;
else
    repetitionCount = NaN;
end

seedCount = numel(randomSeeds);
summary = table( ...
    paperFigures, caseName, channelModel, ...
    paperDensity, simulatedDensity, roadLengthMeters, vehicleCount, ...
    sensitivityDbm, strategy, transmissionCount, repetitionCount, ...
    seedCount, simulationTimeSeconds, maximumScoreDistanceMeters, ...
    normalizedPrrScore, rangeAt90Meters, meanNetCbr, ...
    caseOutputDirectory, ...
    VariableNames=[ ...
        "PaperFigures", "CaseName", "ChannelModel", ...
        "PaperDensityVehiclesPerKilometer", ...
        "SimulatedDensityVehiclesPerKilometer", ...
        "RoadLengthMeters", "VehicleCount", ...
        "PreambleSensitivityDbm", "Strategy", ...
        "MaximumTransmissionCount", "RepetitionCount", ...
        "SeedCount", "SimulationTimeSeconds", ...
        "MaximumScoreDistanceMeters", ...
        "NormalizedPrrScore", "RangeAt90Meters", "MeanNetCbr", ...
        "OutputDirectory"]);
end

function [normalizedPrrScore, rangeAt90Meters] = ...
        summarizePrr(prrFiles, maximumScoreDistanceMeters)
distanceBinWidthMeters = 50;
allDistancesMeters = zeros(0, 1);
fileData = cell(numel(prrFiles), 1);
for fileIndex = 1:numel(prrFiles)
    prrData = readmatrix( ...
        prrFiles(fileIndex), FileType="text", Delimiter=",");
    fileData{fileIndex} = prrData;
    allDistancesMeters = [ ...
        allDistancesMeters; prrData(:, 1)]; %#ok<AGROW>
end

allDistancesMeters = unique(allDistancesMeters);
correctPackets = zeros(size(allDistancesMeters));
totalPackets = zeros(size(allDistancesMeters));
for fileIndex = 1:numel(fileData)
    prrData = fileData{fileIndex};
    [hasDistance, pooledRow] = ismember( ...
        prrData(:, 1), allDistancesMeters);
    correctPackets(pooledRow(hasDistance)) = ...
        correctPackets(pooledRow(hasDistance)) + ...
        prrData(hasDistance, 2);
    totalPackets(pooledRow(hasDistance)) = ...
        totalPackets(pooledRow(hasDistance)) + ...
        prrData(hasDistance, 5);
end

isScoredDistance = ...
    allDistancesMeters > 0 & ...
    allDistancesMeters <= maximumScoreDistanceMeters;
scoredDistancesMeters = allDistancesMeters(isScoredDistance);
scoredCorrectPackets = correctPackets(isScoredDistance);
scoredTotalPackets = totalPackets(isScoredDistance);
distanceGroup = ceil( ...
    scoredDistancesMeters ./ distanceBinWidthMeters);
groupCount = floor( ...
    maximumScoreDistanceMeters ./ distanceBinWidthMeters);
groupCorrectPackets = accumarray( ...
    distanceGroup, scoredCorrectPackets, [groupCount, 1]);
groupTotalPackets = accumarray( ...
    distanceGroup, scoredTotalPackets, [groupCount, 1]);
groupDistancesMeters = ...
    (distanceBinWidthMeters: ...
    distanceBinWidthMeters:maximumScoreDistanceMeters).';
hasSamples = groupTotalPackets > 0;
groupDistancesMeters = groupDistancesMeters(hasSamples);
packetReceptionRatios = ...
    groupCorrectPackets(hasSamples) ./ groupTotalPackets(hasSamples);

if isempty(groupDistancesMeters)
    error( ...
        "v2xsimregression:zhuofei2023repetition:MissingPrrSamples", ...
        "No pooled PRR samples were available within the score range.");
end

normalizedPrrScore = trapz( ...
    [0; groupDistancesMeters], ...
    [1; packetReceptionRatios]) ./ maximumScoreDistanceMeters;
rangeAt90Meters = firstThresholdCrossing( ...
    groupDistancesMeters, packetReceptionRatios, 0.9);
end

function crossingDistance = firstThresholdCrossing( ...
        distances, values, threshold)
firstBelowThreshold = find(values < threshold, 1);
if isempty(firstBelowThreshold)
    crossingDistance = distances(end);
elseif firstBelowThreshold == 1
    crossingDistance = 0;
else
    leftIndex = firstBelowThreshold - 1;
    rightIndex = firstBelowThreshold;
    crossingDistance = interp1( ...
        values([leftIndex, rightIndex]), ...
        distances([leftIndex, rightIndex]), threshold);
end
end

function meanNetCbr = summarizeCbr(cbrFiles)
seedMeans = zeros(numel(cbrFiles), 1);
for fileIndex = 1:numel(cbrFiles)
    cbrData = readmatrix( ...
        cbrFiles(fileIndex), FileType="text", Delimiter=",");
    isFiniteRow = all(isfinite(cbrData(:, 1:2)), 2);
    cbrValues = cbrData(isFiniteRow, 1);
    empiricalCdf = cbrData(isFiniteRow, 2);
    if isempty(cbrValues) || empiricalCdf(end) < 0.999
        error( ...
            "v2xsimregression:zhuofei2023repetition:InvalidCbrOutput", ...
            "The CBR empirical distribution is empty or incomplete: %s", ...
            cbrFiles(fileIndex));
    end
    probabilityMass = diff([0; empiricalCdf]);
    seedMeans(fileIndex) = sum(cbrValues .* probabilityMass);
end
meanNetCbr = mean(seedMeans);
end

function results = createEmptyResults(rowCount)
results = table( ...
    Size=[rowCount, 18], ...
    VariableTypes=[ ...
        "string", "string", "string", ...
        "double", "double", "double", "double", ...
        "double", "string", "double", "double", ...
        "double", "double", "double", ...
        "double", "double", "double", "string"], ...
    VariableNames=[ ...
        "PaperFigures", "CaseName", "ChannelModel", ...
        "PaperDensityVehiclesPerKilometer", ...
        "SimulatedDensityVehiclesPerKilometer", ...
        "RoadLengthMeters", "VehicleCount", ...
        "PreambleSensitivityDbm", "Strategy", ...
        "MaximumTransmissionCount", "RepetitionCount", ...
        "SeedCount", "SimulationTimeSeconds", ...
        "MaximumScoreDistanceMeters", ...
        "NormalizedPrrScore", "RangeAt90Meters", "MeanNetCbr", ...
        "OutputDirectory"]);
end

function type = strategyType(strategy)
if strategy == "static"
    type = "Static";
elseif strategy == "deterministic"
    type = "Deterministic";
elseif strategy == "probabilistic"
    type = "Probabilistic";
else
    error( ...
        "v2xsimregression:zhuofei2023repetition:UnsupportedStrategy", ...
        "Unsupported repetition strategy: %s.", strategy);
end
end

function slug = channelSlug(channelModel)
if channelModel == "WINNER+ B1"
    slug = "winner-b1";
elseif channelModel == "ECC rural"
    slug = "ecc-rural";
else
    error( ...
        "v2xsimregression:zhuofei2023repetition:UnsupportedChannel", ...
        "Unsupported channel model: %s.", channelModel);
end
end

function [roadLengthMeters, simulatedDensity, pathLossModel, ...
        maximumScoreDistanceMeters] = ...
        channelDefinition(paperDensity, channelModel)
if channelModel == "WINNER+ B1"
    roadLengthMeters = 2000;
    simulatedDensity = paperDensity;
    pathLossModel = "WinnerPlusB1";
    maximumScoreDistanceMeters = 650;
elseif channelModel == "ECC rural"
    roadLengthMeters = 8000;
    simulatedDensity = paperDensity ./ 4;
    pathLossModel = "ThreeSlope";
    maximumScoreDistanceMeters = 2000;
else
    error( ...
        "v2xsimregression:zhuofei2023repetition:UnsupportedChannel", ...
        "Unsupported channel model: %s.", channelModel);
end
end

function [sourceDirectory, fixtureDirectory, ...
        packetErrorRateDirectory, tomlDirectory] = ...
        resolveSimulatorDirectories(simulatorRoot)
sourceDirectory = fullfile(simulatorRoot, "src");
fixtureDirectory = fullfile(fileparts(mfilename("fullpath")), "config");
packetErrorRateDirectory = fullfile( ...
    simulatorRoot, "resources", "per-curves", "G5-HighwayLOS");
tomlDirectory = fullfile(simulatorRoot, "lib", "matlab-toml");
end

function validateSimulatorRoot( ...
        simulatorRoot, fixtureDirectory, packetErrorRateDirectory)
if ~isfolder(simulatorRoot)
    error( ...
        "v2xsimregression:zhuofei2023repetition:MissingSimulatorRoot", ...
        "SimulatorRoot is not a directory: %s", simulatorRoot);
end
if ~isfile(fullfile( ...
        simulatorRoot, "src", "+v2xsim", "runSimulation.m"))
    error( ...
        "v2xsimregression:zhuofei2023repetition:MissingSimulator", ...
        "v2xsim.runSimulation was not found under: %s", ...
        simulatorRoot);
end
requiredConfigurations = [ ...
    fullfile(fixtureDirectory, "figure3.toml"), ...
    fullfile(fixtureDirectory, "figures4and5.toml")];
for requiredConfiguration = requiredConfigurations
    if ~isfile(requiredConfiguration)
        error( ...
            "v2xsimregression:zhuofei2023repetition:MissingConfiguration", ...
            "A regression configuration was not found: %s", ...
            requiredConfiguration);
    end
end
if ~isfolder(packetErrorRateDirectory)
    error( ...
        "v2xsimregression:zhuofei2023repetition:MissingPerCurves", ...
        "The paper's PER curves were not found under: %s", ...
        packetErrorRateDirectory);
end
if ~isfolder(fullfile(simulatorRoot, "src", "+v2xsim"))
    error( ...
        "v2xsimregression:zhuofei2023repetition:MissingRefactoredSource", ...
        "The simulator root requires src/+v2xsim under: %s", ...
        simulatorRoot);
end
end

function prepareOutputDirectory(outputDirectory)
if isfolder(outputDirectory)
    directoryEntries = dir(outputDirectory);
    entryNames = string({directoryEntries.name});
    isContent = ~ismember(entryNames, [".", ".."]);
    if any(isContent)
        error( ...
            "v2xsimregression:zhuofei2023repetition:OutputNotEmpty", ...
            "Refusing to append results in nonempty folder: %s", ...
            outputDirectory);
    end
else
    [wasCreated, message] = mkdir(outputDirectory);
    if ~wasCreated
        error( ...
            "v2xsimregression:zhuofei2023repetition:" + ...
            "OutputCreationFailed", ...
            "Could not create output folder %s: %s", ...
            outputDirectory, message);
    end
end
end

function simulationTimeSeconds = defaultSimulationTimeSeconds()
configuredValue = string(getenv( ...
    "V2XSIM_PAPER_SIMULATION_TIME_SECONDS"));
if configuredValue == ""
    simulationTimeSeconds = 5;
    return
end

simulationTimeSeconds = str2double(configuredValue);
if ~isscalar(simulationTimeSeconds) || ...
        ~isfinite(simulationTimeSeconds) || simulationTimeSeconds <= 0
    error( ...
        "v2xsimregression:zhuofei2023repetition:InvalidDuration", ...
        ["V2XSIM_PAPER_SIMULATION_TIME_SECONDS must contain a ", ...
        "positive finite number."]);
end
end

function restoreEnvironment( ...
        originalPath, randomStream, originalRandomState)
path(originalPath);
RandStream.setGlobalStream(randomStream);
randomStream.State = originalRandomState;
end
