classdef Zhuofei2023RepetitionTest < matlab.unittest.TestCase
    %ZHUOFEI2023REPETITIONTEST Conclusion-level paper regressions.
    %   Reasserts the conclusions behind Figures 3-5 from Zhuofei et al.
    %   (2023), rather than matching individual Monte Carlo samples.

    properties (Constant, Access = private)
        SingleTransmissionSensitivityTolerance = 0.015
        MinimumRealisticRepetitionGain = 0.08
        MinimumImprovedPreambleGain = 0.04
        MinimumIdealPreambleGain = 0.01
        LowLoadCbrUpperBound = 0.03
        HighLoadCbrLowerBound = 0.09
        MinimumWinnerLowLoadGain = 0.08
        MinimumEccLowLoadGain = 0.005
        MinimumHighLoadPenalty = 0.05
        MinimumHighLoadOneRepeatPenalty = 0.01
        AdaptiveBestGapTolerance = 0.06
        AdaptiveStrategyTolerance = 0.05
    end

    properties (SetAccess = private)
        SimulatorRoot (1, 1) string
        OutputDirectory (1, 1) string
    end

    methods (TestClassSetup)
        function configureCampaign(testCase)
            testCase.SimulatorRoot = getSimulatorRoot();
            temporaryFolder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            testCase.OutputDirectory = string(temporaryFolder.Folder);
        end
    end

    methods (Test, TestTags = {'ShortCampaign'})
        function testFigure3SupportsPreambleDetectionConclusion(testCase)
            results = ...
                v2xsimregression.paper.zhuofei2023repetition. ...
                runPublishedCampaigns( ...
                    testCase.SimulatorRoot, ...
                    fullfile(testCase.OutputDirectory, "figure-3"), ...
                    Figures=3, ...
                    RandomSeeds=10:12, ...
                    SimulationTimeSeconds=5);

            oneTransmissionScores = zeros(1, 3);
            sensitivitiesDbm = [-100, -103, -120];
            for sensitivityIndex = 1:numel(sensitivitiesDbm)
                row = selectRow( ...
                    results, "WINNER+ B1", 5, "static", 1, ...
                    sensitivitiesDbm(sensitivityIndex));
                oneTransmissionScores(sensitivityIndex) = ...
                    row.NormalizedPrrScore;
            end
            testCase.verifyLessThanOrEqual( ...
                max(oneTransmissionScores) - min(oneTransmissionScores), ...
                testCase.SingleTransmissionSensitivityTolerance, ...
                ["With no repetition, changing the preamble threshold ", ...
                "must not materially change the PRR curve."]);

            realisticOne = selectRow( ...
                results, "WINNER+ B1", 5, "static", 1, -100);
            realisticFour = selectRow( ...
                results, "WINNER+ B1", 5, "static", 4, -100);
            improvedFour = selectRow( ...
                results, "WINNER+ B1", 5, "static", 4, -103);
            idealFour = selectRow( ...
                results, "WINNER+ B1", 5, "static", 4, -120);

            testCase.verifyGreaterThan( ...
                realisticFour.NormalizedPrrScore - ...
                    realisticOne.NormalizedPrrScore, ...
                testCase.MinimumRealisticRepetitionGain, ...
                "Repetition must improve PRR even with realistic detection.");
            testCase.verifyGreaterThan( ...
                improvedFour.NormalizedPrrScore - ...
                    realisticFour.NormalizedPrrScore, ...
                testCase.MinimumImprovedPreambleGain, ...
                ["Lowering the detection threshold from -100 to -103 dBm ", ...
                "must unlock additional combining gain."]);
            testCase.verifyGreaterThan( ...
                idealFour.NormalizedPrrScore - ...
                    improvedFour.NormalizedPrrScore, ...
                testCase.MinimumIdealPreambleGain, ...
                ["Ideal preamble detection must retain a measurable ", ...
                "advantage over the improved realistic receiver."]);
        end

        function testFigures4And5SupportAdaptiveLoadTradeoff(testCase)
            results = ...
                v2xsimregression.paper.zhuofei2023repetition. ...
                runPublishedCampaigns( ...
                    testCase.SimulatorRoot, ...
                    fullfile(testCase.OutputDirectory, "figures-4-5"), ...
                    Figures=[4, 5], ...
                    RandomSeeds=10:11, ...
                    SimulationTimeSeconds=5);

            for channelModel = ["WINNER+ B1", "ECC rural"]
                lowOne = selectRow( ...
                    results, channelModel, 5, "static", 1, -100);
                lowFour = selectRow( ...
                    results, channelModel, 5, "static", 4, -100);
                highOne = selectRow( ...
                    results, channelModel, 80, "static", 1, -100);
                highFour = selectRow( ...
                    results, channelModel, 80, "static", 4, -100);

                testCase.verifyLessThan( ...
                    max([lowOne.MeanNetCbr, lowFour.MeanNetCbr]), ...
                    testCase.LowLoadCbrUpperBound, ...
                    compose( ...
                        "%s low-load cases must remain below CBR 0.03.", ...
                        channelModel));
                testCase.verifyGreaterThan( ...
                    min([highOne.MeanNetCbr, highFour.MeanNetCbr]), ...
                    testCase.HighLoadCbrLowerBound, ...
                    compose( ...
                        "%s high-load cases must exceed CBR 0.09.", ...
                        channelModel));

                if channelModel == "WINNER+ B1"
                    minimumLowLoadGain = ...
                        testCase.MinimumWinnerLowLoadGain;
                else
                    minimumLowLoadGain = ...
                        testCase.MinimumEccLowLoadGain;
                end
                testCase.verifyGreaterThan( ...
                    lowFour.NormalizedPrrScore - ...
                        lowOne.NormalizedPrrScore, ...
                    minimumLowLoadGain, ...
                    compose( ...
                        "At low %s load, three repetitions must " + ...
                        "improve the PRR curve.", channelModel));
                testCase.verifyGreaterThan( ...
                    highOne.NormalizedPrrScore - ...
                        highFour.NormalizedPrrScore, ...
                    testCase.MinimumHighLoadPenalty, ...
                    compose( ...
                        "At high %s load, three repetitions must expose " + ...
                        "their collision cost.", channelModel));
            end

            highOne = selectRow( ...
                results, "WINNER+ B1", 80, "static", 1, -100);
            highTwo = selectRow( ...
                results, "WINNER+ B1", 80, "static", 2, -100);
            testCase.verifyGreaterThan( ...
                highOne.NormalizedPrrScore - highTwo.NormalizedPrrScore, ...
                testCase.MinimumHighLoadOneRepeatPenalty, ...
                ["Above the paper's CBR 0.09 crossover, zero repetitions ", ...
                "must outperform one repetition."]);

            middleOne = selectRow( ...
                results, "WINNER+ B1", 40, "static", 1, -100);
            middleTwo = selectRow( ...
                results, "WINNER+ B1", 40, "static", 2, -100);
            middleFour = selectRow( ...
                results, "WINNER+ B1", 40, "static", 4, -100);
            testCase.verifyGreaterThan( ...
                middleTwo.NormalizedPrrScore, ...
                middleOne.NormalizedPrrScore, ...
                "One repetition must still help near the crossover.");
            testCase.verifyGreaterThan( ...
                middleTwo.NormalizedPrrScore, ...
                middleFour.NormalizedPrrScore, ...
                "Near the crossover, always using three repetitions hurts.");

            for density = [5, 40, 80]
                fixedRows = results( ...
                    results.ChannelModel == "WINNER+ B1" & ...
                    results.PaperDensityVehiclesPerKilometer == density & ...
                    results.Strategy == "static", :);
                bestFixedScore = max(fixedRows.NormalizedPrrScore);
                deterministic = selectRow( ...
                    results, "WINNER+ B1", density, ...
                    "deterministic", 4, -100);
                probabilistic = selectRow( ...
                    results, "WINNER+ B1", density, ...
                    "probabilistic", 4, -100);

                for strategy = ["deterministic", "probabilistic"]
                    adaptive = selectRow( ...
                        results, "WINNER+ B1", density, ...
                        strategy, 4, -100);
                    testCase.verifyGreaterThanOrEqual( ...
                        adaptive.NormalizedPrrScore, ...
                        bestFixedScore - ...
                            testCase.AdaptiveBestGapTolerance, ...
                        compose( ...
                            "%s adaptation at %g vehicles/km must track " + ...
                            "the best fixed repetition count.", ...
                            adaptive.Strategy, density));
                end
                testCase.verifyLessThanOrEqual( ...
                    abs(deterministic.NormalizedPrrScore - ...
                        probabilistic.NormalizedPrrScore), ...
                    testCase.AdaptiveStrategyTolerance, ...
                    compose( ...
                        "Deterministic and probabilistic strategies at " + ...
                        "%g vehicles/km must provide comparable PRR.", ...
                        density));
            end
        end
    end
end

function simulatorRoot = getSimulatorRoot()
simulatorRoot = string(getenv("V2XSIM_PAPER_SIMULATOR_ROOT"));
if simulatorRoot == ""
    simulatorRoot = string(fileparts(fileparts(fileparts(fileparts( ...
        fileparts(mfilename("fullpath")))))));
end
end

function selectedRow = selectRow( ...
        results, channelModel, density, strategy, ...
        transmissionCount, sensitivityDbm)
isSelected = ...
    results.ChannelModel == channelModel & ...
    results.PaperDensityVehiclesPerKilometer == density & ...
    results.Strategy == strategy & ...
    results.MaximumTransmissionCount == transmissionCount & ...
    results.PreambleSensitivityDbm == sensitivityDbm;
selectedRow = results(isSelected, :);
if height(selectedRow) ~= 1
    error( ...
        "v2xsimregression:zhuofei2023repetition:NonuniqueSelection", ...
        "Expected one campaign row but selected %d.", ...
        height(selectedRow));
end
end
