function rows = buildReuseCandidateRows( ...
        liveAssignments,oracleAssignments,gridSize,options)
%BUILDREUSECANDIDATEROWS Build sparse exact- and interference-pair evidence.
%   Maximum-reuse allocation has one resource per UE. Resource labels are
%   retained as evidence, while CandidateType depends only on the pairwise
%   exact-resource graphs produced by classifyReuseCandidates.
%
%   The explicit live/oracle resource relations additionally distinguish
%   cochannel, adjacent-channel, and farther same-time resources. Physical
%   overlap is determined by the supplied PHY frequency-coupling matrix. A
%   row is retained when either the exact-resource graph changes or the
%   interference-overlap graph changes. Allocation summaries retain the
%   all-pair denominator.

arguments (Input)
    liveAssignments table
    oracleAssignments table
    gridSize (1,2) double {mustBeInteger,mustBePositive}
    options.FrequencyInterferenceCoupling (:,:) double ...
        {mustBeReal,mustBeFinite,mustBeNonnegative} = zeros(0,0)
end

if size(liveAssignments,2) ~= 2 || ...
        size(oracleAssignments,2) ~= 2 || ...
        ~ismember("ResourceIds", ...
            string(liveAssignments.Properties.VariableNames)) || ...
        ~ismember("ResourceIds", ...
            string(oracleAssignments.Properties.VariableNames)) || ...
        size(liveAssignments.ResourceIds,2) ~= 1 || ...
        size(oracleAssignments.ResourceIds,2) ~= 1
    error( ...
        "v2xsim:resource:metrics:" + ...
        "UnsupportedReuseCandidateTransmissionCount", ...
        "Controller reuse-candidate rows require one resource per UE.");
end
resourceCount = prod(gridSize);
validateResourceIds(liveAssignments.ResourceIds,resourceCount,"live");
validateResourceIds(oracleAssignments.ResourceIds,resourceCount,"oracle");

candidates = v2xsim.analysis.classifyReuseCandidates( ...
    liveAssignments,oracleAssignments);
[liveFirstFound,liveFirstRows] = ismember( ...
    candidates.FirstUeId,liveAssignments.UeId);
[liveSecondFound,liveSecondRows] = ismember( ...
    candidates.SecondUeId,liveAssignments.UeId);
[oracleFirstFound,oracleFirstRows] = ismember( ...
    candidates.FirstUeId,oracleAssignments.UeId);
[oracleSecondFound,oracleSecondRows] = ismember( ...
    candidates.SecondUeId,oracleAssignments.UeId);
if ~all( ...
        liveFirstFound & liveSecondFound & ...
        oracleFirstFound & oracleSecondFound)
    error( ...
        "v2xsim:resource:metrics:ControllerIdentityMismatch", ...
        "Reuse-candidate endpoints must occur in both assignments.");
end

liveFirstResourceIds = ...
    liveAssignments.ResourceIds(liveFirstRows);
liveSecondResourceIds = ...
    liveAssignments.ResourceIds(liveSecondRows);
oracleFirstResourceIds = ...
    oracleAssignments.ResourceIds(oracleFirstRows);
oracleSecondResourceIds = ...
    oracleAssignments.ResourceIds(oracleSecondRows);
frequencyCount = gridSize(2);
frequencyInterferenceCoupling = resolveFrequencyInterferenceCoupling( ...
    options.FrequencyInterferenceCoupling,frequencyCount);
liveResourceRelation = resourceRelations( ...
    liveFirstResourceIds,liveSecondResourceIds,frequencyCount);
oracleResourceRelation = resourceRelations( ...
    oracleFirstResourceIds,oracleSecondResourceIds,frequencyCount);
liveInterferenceOverlap = isInterferenceOverlap( ...
    liveFirstResourceIds,liveSecondResourceIds, ...
    frequencyCount,frequencyInterferenceCoupling);
oracleInterferenceOverlap = isInterferenceOverlap( ...
    oracleFirstResourceIds,oracleSecondResourceIds, ...
    frequencyCount,frequencyInterferenceCoupling);
isHarmfulInterferenceOverlap = ...
    liveInterferenceOverlap & ~oracleInterferenceOverlap;
isMissedInterferenceOverlap = ...
    ~liveInterferenceOverlap & oracleInterferenceOverlap;
isDirectionalExactCandidate = ismember( ...
    candidates.CandidateType,["harmful_reuse","missed_reuse"]);
retain = isDirectionalExactCandidate | ...
    isHarmfulInterferenceOverlap | ...
    isMissedInterferenceOverlap;

rows = table( ...
    candidates.FirstUeId(retain), ...
    candidates.SecondUeId(retain), ...
    candidates.CandidateType(retain), ...
    candidates.LiveOverlap(retain), ...
    candidates.OracleOverlap(retain), ...
    liveResourceRelation(retain), ...
    oracleResourceRelation(retain), ...
    isHarmfulInterferenceOverlap(retain), ...
    isMissedInterferenceOverlap(retain), ...
    liveFirstResourceIds(retain), ...
    liveSecondResourceIds(retain), ...
    oracleFirstResourceIds(retain), ...
    oracleSecondResourceIds(retain), ...
    VariableNames=[ ...
        "FirstUeId","SecondUeId","CandidateType", ...
        "LiveSameResource","OracleSameResource", ...
        "LiveResourceRelation","OracleResourceRelation", ...
        "IsHarmfulInterferenceOverlap", ...
        "IsMissedInterferenceOverlap", ...
        "LiveFirstResourceId","LiveSecondResourceId", ...
        "OracleFirstResourceId","OracleSecondResourceId"]);
end

function validateResourceIds(resourceIds,resourceCount,label)
assigned = ~isnan(resourceIds);
if any(~isfinite(resourceIds(assigned))) || ...
        any(resourceIds(assigned) < 1) || ...
        any(resourceIds(assigned) > resourceCount) || ...
        any(mod(resourceIds(assigned),1) ~= 0)
    error( ...
        "v2xsim:resource:metrics:InvalidResourceId", ...
        "%s resource IDs must be NaN or valid positive grid IDs.", ...
        label);
end
end

function relation = resourceRelations( ...
        firstResourceIds,secondResourceIds,frequencyCount)
pairCount = numel(firstResourceIds);
relation = repmat("unassigned",pairCount,1);
assigned = ~isnan(firstResourceIds) & ~isnan(secondResourceIds);
sameResource = assigned & ...
    firstResourceIds == secondResourceIds;
relation(sameResource) = "cochannel";

firstTimes = ceil(firstResourceIds / frequencyCount);
secondTimes = ceil(secondResourceIds / frequencyCount);
separateTime = assigned & firstTimes ~= secondTimes;
relation(separateTime) = "separate_time";

sameTimeSeparated = assigned & ...
    firstTimes == secondTimes & ~sameResource;
firstFrequencies = ...
    mod(firstResourceIds - 1,frequencyCount) + 1;
secondFrequencies = ...
    mod(secondResourceIds - 1,frequencyCount) + 1;
adjacent = sameTimeSeparated & ...
    abs(firstFrequencies - secondFrequencies) == 1;
relation(adjacent) = "adjacent_channel";
relation(sameTimeSeparated & ~adjacent) = "other_same_time";
end

function overlap = isInterferenceOverlap( ...
        firstResourceIds,secondResourceIds, ...
        frequencyCount,frequencyInterferenceCoupling)
assigned = ~isnan(firstResourceIds) & ...
    ~isnan(secondResourceIds);
firstTimes = ceil(firstResourceIds / frequencyCount);
secondTimes = ceil(secondResourceIds / frequencyCount);
sameTime = assigned & firstTimes == secondTimes;
firstFrequencies = ...
    mod(firstResourceIds - 1,frequencyCount) + 1;
secondFrequencies = ...
    mod(secondResourceIds - 1,frequencyCount) + 1;
firstFrequencies(~assigned) = 1;
secondFrequencies(~assigned) = 1;
forwardIndex = sub2ind( ...
    size(frequencyInterferenceCoupling), ...
    firstFrequencies,secondFrequencies);
reverseIndex = sub2ind( ...
    size(frequencyInterferenceCoupling), ...
    secondFrequencies,firstFrequencies);
overlap = sameTime & ( ...
    frequencyInterferenceCoupling(forwardIndex) > 0 | ...
    frequencyInterferenceCoupling(reverseIndex) > 0);
end

function coupling = resolveFrequencyInterferenceCoupling( ...
        coupling,frequencyCount)
if isempty(coupling)
    frequencyIds = (1:frequencyCount).';
    coupling = double( ...
        abs(frequencyIds - frequencyIds.') <= 1);
elseif ~isequal(size(coupling),[frequencyCount frequencyCount])
    error( ...
        "v2xsim:resource:metrics:" + ...
        "FrequencyInterferenceCouplingSizeMismatch", ...
        "FrequencyInterferenceCoupling must match the frequency " + ...
        "dimension of GridSize.");
end
end
