function rows = buildControllerDiagnosticRows( ...
        simulationTimeSeconds,allocationEpoch,context,result, ...
        neighborRangesMeters,topK,options)
%BUILDCONTROLLERDIAGNOSTICROWS Build format-neutral controller tables.

arguments (Input)
    simulationTimeSeconds (1,1) double ...
        {mustBeReal,mustBeFinite,mustBeNonnegative}
    allocationEpoch (1,1) uint64
    context (1,1) v2xsim.resource.CentralizedAllocationContext
    result (1,1) v2xsim.resource.ResourceAllocationResult
    neighborRangesMeters (1,:) double ...
        {mustBeReal,mustBeFinite,mustBePositive}
    topK (1,1) double {mustBeInteger,mustBePositive} = 10
    options.RankDisplacementEnabled (1,1) logical = true
    options.FrequencyInterferenceCoupling (:,:) double ...
        {mustBeReal,mustBeFinite,mustBeNonnegative} = zeros(0,0)
end

diagnostics = result.Diagnostics;
requiredFields = [ ...
    "SchemaVersion","Kind","UeIds","GridSize", ...
    "AssignmentsBefore","OracleAssignments", ...
    "LiveDecisionTrace","OracleDecisionTrace"];
if ~all(isfield(diagnostics,requiredFields)) || ...
        string(diagnostics.Kind) ~= "MaximumReuseDistance"
    error( ...
        "v2xsim:resource:metrics:MissingControllerDiagnostics", ...
        "The allocation result does not contain maximum-reuse " + ...
        "controller diagnostics.");
end

ueIds = diagnostics.UeIds(:);
[knownUes,contextRows] = ismember(ueIds,context.UeIds);
[knownAssignments,resultRows] = ...
    ismember(ueIds,result.Assignments.UeId);
[knownOracle,oracleRows] = ...
    ismember(ueIds,diagnostics.OracleAssignments.UeId);
[knownBefore,beforeRows] = ...
    ismember(ueIds,diagnostics.AssignmentsBefore.UeId);
if ~all(knownUes) || ~all(knownAssignments) || ~all(knownOracle)
    error( ...
        "v2xsim:resource:metrics:ControllerIdentityMismatch", ...
        "Context, live, and oracle UE identities must agree.");
end
if ~all(knownBefore)
    error( ...
        "v2xsim:resource:metrics:ControllerIdentityMismatch", ...
        "Pre-decision assignments must contain every diagnostic UE.");
end
apparentDistanceMeters = ...
    context.EstimatedDistanceMeters(contextRows,contextRows);
trueDistanceMeters = ...
    context.TrueDistanceMeters(contextRows,contextRows);
liveResourceIds = ...
    result.Assignments.ResourceIds(resultRows,1);
oracleResourceIds = ...
    diagnostics.OracleAssignments.ResourceIds(oracleRows,1);
previousResourceIds = ...
    diagnostics.AssignmentsBefore.ResourceIds(beforeRows,1);

topology = v2xsim.resource.metrics.compareNeighborTopology( ...
    ueIds,apparentDistanceMeters,trueDistanceMeters, ...
    TopK=topK,NeighborRangesMeters=neighborRangesMeters, ...
    IncludeRankDisplacement= ...
        options.RankDisplacementEnabled);
allocation = v2xsim.resource.metrics.compareAllocations( ...
    ueIds,liveResourceIds,oracleResourceIds, ...
    trueDistanceMeters,diagnostics.GridSize, ...
    DecisionUeIds=result.DecisionUeIds, ...
    PreviousResourceIds=previousResourceIds, ...
    FrequencyInterferenceCoupling= ...
        options.FrequencyInterferenceCoupling);
liveAssignments = table( ...
    ueIds,liveResourceIds, ...
    VariableNames=["UeId","ResourceIds"]);
oracleAssignments = table( ...
    ueIds,oracleResourceIds, ...
    VariableNames=["UeId","ResourceIds"]);
reuseCandidates = ...
    v2xsim.resource.metrics.buildReuseCandidateRows( ...
        liveAssignments,oracleAssignments,diagnostics.GridSize, ...
        FrequencyInterferenceCoupling= ...
            options.FrequencyInterferenceCoupling);
decisionTrace = ...
    v2xsim.resource.metrics.evaluateMaximumReuseDistanceTrace( ...
        diagnostics.LiveDecisionTrace, ...
        diagnostics.AssignmentsBefore,trueDistanceMeters, ...
        diagnostics.GridSize);
[foundOracle,oracleTraceRows] = ismember( ...
    decisionTrace.UeId,diagnostics.OracleDecisionTrace.UeId);
if ~all(foundOracle)
    error( ...
        "v2xsim:resource:metrics:ControllerIdentityMismatch", ...
        "Live and oracle decision traces must contain the same UEs.");
end
oracleSelectedResourceId = ...
    diagnostics.OracleDecisionTrace.SelectedResourceId( ...
        oracleTraceRows);
exactOracleDecisionMatch = ...
    decisionTrace.SelectedResourceId == oracleSelectedResourceId;
liveAssignmentChanged = ~sameResource( ...
    decisionTrace.PreviousResourceId, ...
    decisionTrace.SelectedResourceId);
oracleAssignmentChanged = ~sameResource( ...
    decisionTrace.PreviousResourceId, ...
    oracleSelectedResourceId);
decisionTrace = addvars( ...
    decisionTrace,oracleSelectedResourceId, ...
    exactOracleDecisionMatch,liveAssignmentChanged, ...
    oracleAssignmentChanged, ...
    NewVariableNames=[ ...
        "OracleSelectedResourceId","ExactOracleDecisionMatch", ...
        "LiveAssignmentChanged","OracleAssignmentChanged"]);

sliceId = string(context.NetworkSliceId);
slot = context.CurrentSlot;
rows = struct( ...
    "Topology",addMetadata( ...
        topology.Topology,simulationTimeSeconds, ...
        allocationEpoch,slot,sliceId), ...
    "RankDisplacement",addMetadata( ...
        topology.RankDisplacement, ...
        simulationTimeSeconds,allocationEpoch,slot,sliceId), ...
    "RangeTopology",addMetadata( ...
        topology.RangeTopology, ...
        simulationTimeSeconds,allocationEpoch,slot,sliceId), ...
    "AllocationDecision",addMetadata( ...
        decisionTrace,simulationTimeSeconds, ...
        allocationEpoch,slot,sliceId), ...
    "AllocationSummary",addMetadata( ...
        allocation.Summary,simulationTimeSeconds, ...
        allocationEpoch,slot,sliceId), ...
    "CoUser",addMetadata( ...
        allocation.CoUser,simulationTimeSeconds, ...
        allocationEpoch,slot,sliceId), ...
    "ReuseCandidate",addMetadata( ...
        reuseCandidates,simulationTimeSeconds, ...
        allocationEpoch,slot,sliceId));
end

function same = sameResource(left,right)
same = left == right | (isnan(left) & isnan(right));
end

function output = addMetadata( ...
        input,timeSeconds,allocationEpoch,slot,sliceId)
rowCount = height(input);
output = addvars( ...
    input,repmat(timeSeconds,rowCount,1), ...
    repmat(allocationEpoch,rowCount,1), ...
    repmat(slot,rowCount,1),repmat(sliceId,rowCount,1), ...
    Before=1, ...
    NewVariableNames=[ ...
        "SimulationTimeSeconds","AllocationEpoch", ...
        "AbsoluteSlot","NetworkSliceId"]);
end
