function comparison = compareAllocations( ...
        ueIds,liveResourceIds,oracleResourceIds, ...
        trueDistanceMeters,gridSize,options)
%COMPAREALLOCATIONS Compare allocations with label-invariant pair graphs.

arguments (Input)
    ueIds string
    liveResourceIds (:,1) double
    oracleResourceIds (:,1) double
    trueDistanceMeters (:,:) double {mustBeReal,mustBeNonnegative}
    gridSize (1,2) double {mustBeInteger,mustBePositive}
    options.DecisionUeIds string = strings(0,1)
    options.PreviousResourceIds (:,1) double = zeros(0,1)
    options.FrequencyInterferenceCoupling (:,:) double ...
        {mustBeReal,mustBeFinite,mustBeNonnegative} = zeros(0,0)
end

ueIds = ueIds(:);
v2xsim.resource.validation.mustBeUeIds(ueIds);
ueCount = numel(ueIds);
if numel(liveResourceIds) ~= ueCount || ...
        numel(oracleResourceIds) ~= ueCount || ...
        ~isequal(size(trueDistanceMeters),[ueCount ueCount]) || ...
        any(isnan(trueDistanceMeters),"all")
    error( ...
        "v2xsim:resource:metrics:AllocationSizeMismatch", ...
        "Allocations and true distances must align with UeIds.");
end
resourceCount = prod(gridSize);
validateResourceIds(liveResourceIds,resourceCount);
validateResourceIds(oracleResourceIds,resourceCount);
hasPreviousAssignments = ~isempty(options.PreviousResourceIds);
if hasPreviousAssignments
    if numel(options.PreviousResourceIds) ~= ueCount
        error( ...
            "v2xsim:resource:metrics:AllocationSizeMismatch", ...
            "PreviousResourceIds must align with UeIds.");
    end
    previousResourceIds = options.PreviousResourceIds;
    validateResourceIds(previousResourceIds,resourceCount);
else
    previousResourceIds = nan(ueCount,1);
end
decisionMask = true(ueCount,1);
if ~isempty(options.DecisionUeIds)
    decisionUeIds = options.DecisionUeIds(:);
    v2xsim.resource.validation.mustBeUeIds(decisionUeIds);
    if ~all(ismember(decisionUeIds,ueIds))
        error( ...
            "v2xsim:resource:metrics:UnknownDecisionUeId", ...
            "DecisionUeIds must be a subset of UeIds.");
    end
    decisionMask = ismember(ueIds,decisionUeIds);
end

frequencyCount = gridSize(2);
frequencyInterferenceCoupling = resolveFrequencyInterferenceCoupling( ...
    options.FrequencyInterferenceCoupling,frequencyCount);
liveTimes = resourceTimes(liveResourceIds,frequencyCount);
oracleTimes = resourceTimes(oracleResourceIds,frequencyCount);
liveFrequencies = resourceFrequencies( ...
    liveResourceIds,frequencyCount);
oracleFrequencies = resourceFrequencies( ...
    oracleResourceIds,frequencyCount);
exactMatches = valuesMatch(liveResourceIds,oracleResourceIds);
timeMatches = valuesMatch(liveTimes,oracleTimes);
liveAssignmentChanged = false(ueCount,1);
oracleAssignmentChanged = false(ueCount,1);
if hasPreviousAssignments
    liveAssignmentChanged = ...
        ~valuesMatch(previousResourceIds,liveResourceIds);
    oracleAssignmentChanged = ...
        ~valuesMatch(previousResourceIds,oracleResourceIds);
end

[liveResourceGraph,liveTimeGraph,liveInterferenceGraph] = ...
    pairGraphs( ...
        liveResourceIds,liveTimes,liveFrequencies, ...
        frequencyInterferenceCoupling);
[oracleResourceGraph,oracleTimeGraph,oracleInterferenceGraph] = ...
    pairGraphs( ...
        oracleResourceIds,oracleTimes,oracleFrequencies, ...
        frequencyInterferenceCoupling);
pairMask = triu(true(ueCount),1);
totalUnorderedUePairCount = nnz(pairMask);
harmfulReuseCandidateCount = nnz( ...
    pairMask & liveResourceGraph & ~oracleResourceGraph);
missedReuseCandidateCount = nnz( ...
    pairMask & ~liveResourceGraph & oracleResourceGraph);
harmfulReuseCandidateRate = pairRate( ...
    harmfulReuseCandidateCount,totalUnorderedUePairCount);
missedReuseCandidateRate = pairRate( ...
    missedReuseCandidateCount,totalUnorderedUePairCount);
harmfulInterferenceOverlapCandidateCount = nnz( ...
    pairMask & liveInterferenceGraph & ...
    ~oracleInterferenceGraph);
missedInterferenceOverlapCandidateCount = nnz( ...
    pairMask & ~liveInterferenceGraph & ...
    oracleInterferenceGraph);
harmfulInterferenceOverlapCandidateRate = pairRate( ...
    harmfulInterferenceOverlapCandidateCount, ...
    totalUnorderedUePairCount);
missedInterferenceOverlapCandidateRate = pairRate( ...
    missedInterferenceOverlapCandidateCount, ...
    totalUnorderedUePairCount);

liveNearest = nearestCoUserDistances( ...
    liveResourceGraph,trueDistanceMeters);
oracleNearest = nearestCoUserDistances( ...
    oracleResourceGraph,trueDistanceMeters);
trueDistanceRegret = distanceDifference( ...
    oracleNearest,liveNearest);

coUserJaccard = nan(ueCount,1);
for egoRow = 1:ueCount
    liveCoUsers = find(liveResourceGraph(egoRow,:));
    oracleCoUsers = find(oracleResourceGraph(egoRow,:));
    coUserJaccard(egoRow) = ...
        setJaccard(liveCoUsers,oracleCoUsers);
end

comparison.Decisions = table( ...
    ueIds,decisionMask,previousResourceIds, ...
    liveResourceIds,oracleResourceIds, ...
    liveTimes,oracleTimes,exactMatches,timeMatches, ...
    liveAssignmentChanged,oracleAssignmentChanged, ...
    liveNearest,oracleNearest,trueDistanceRegret, ...
    VariableNames=[ ...
        "UeId","WasDecisionUe","PreviousResourceId", ...
        "LiveResourceId","OracleResourceId", ...
        "LiveTimeSlot","OracleTimeSlot", ...
        "ExactResourceMatch","TimeSlotMatch", ...
        "LiveAssignmentChanged","OracleAssignmentChanged", ...
        "LiveNearestTrueCoUserDistanceMeters", ...
        "OracleNearestTrueCoUserDistanceMeters", ...
        "TrueDistanceRegretMeters"]);
comparison.CoUser = table( ...
    ueIds,coUserJaccard, ...
    sum(liveResourceGraph,2),sum(oracleResourceGraph,2), ...
    VariableNames=[ ...
        "UeId","CoUserJaccard","LiveCoUserCount", ...
        "OracleCoUserCount"]);

decisionCount = nnz(decisionMask);
if decisionCount == 0
    exactDisagreementRate = NaN;
    timeDisagreementRate = NaN;
else
    exactDisagreementRate = ...
        mean(~exactMatches(decisionMask));
    timeDisagreementRate = ...
        mean(~timeMatches(decisionMask));
end
liveChurnRate = NaN;
oracleChurnRate = NaN;
if hasPreviousAssignments && decisionCount > 0
    liveChurnRate = mean(liveAssignmentChanged(decisionMask));
    oracleChurnRate = mean(oracleAssignmentChanged(decisionMask));
end
[resourceXorCount,resourceXorRate,resourceJaccard] = ...
    comparePairGraphs( ...
        liveResourceGraph,oracleResourceGraph,pairMask);
[timeXorCount,timeXorRate,timeJaccard] = ...
    comparePairGraphs(liveTimeGraph,oracleTimeGraph,pairMask);
[interferenceXorCount,interferenceXorRate, ...
        interferenceJaccard] = comparePairGraphs( ...
            liveInterferenceGraph, ...
            oracleInterferenceGraph,pairMask);
livePairDistances = trueDistanceMeters( ...
    pairMask & liveResourceGraph);
oraclePairDistances = trueDistanceMeters( ...
    pairMask & oracleResourceGraph);
comparison.Summary = table( ...
    ueCount,decisionCount,exactDisagreementRate, ...
    timeDisagreementRate,liveChurnRate,oracleChurnRate, ...
    totalUnorderedUePairCount, ...
    harmfulReuseCandidateCount,harmfulReuseCandidateRate, ...
    missedReuseCandidateCount,missedReuseCandidateRate, ...
    harmfulInterferenceOverlapCandidateCount, ...
    harmfulInterferenceOverlapCandidateRate, ...
    missedInterferenceOverlapCandidateCount, ...
    missedInterferenceOverlapCandidateRate, ...
    resourceXorCount,resourceXorRate, ...
    resourceJaccard,timeXorCount,timeXorRate,timeJaccard, ...
    interferenceXorCount,interferenceXorRate, ...
    interferenceJaccard, ...
    finiteMinimum(livePairDistances), ...
    finiteMinimum(oraclePairDistances), ...
    lowerQuantile(livePairDistances,0.1), ...
    lowerQuantile(oraclePairDistances,0.1), ...
    mean(coUserJaccard,"omitmissing"), ...
    mean(trueDistanceRegret(isfinite(trueDistanceRegret)), ...
        "omitmissing"), ...
    VariableNames=[ ...
        "UeCount","DecisionUeCount", ...
        "ExactDecisionDisagreementRate", ...
        "TimeSlotDecisionDisagreementRate", ...
        "LiveAssignmentChurnRate","OracleAssignmentChurnRate", ...
        "TotalUnorderedUePairCount", ...
        "HarmfulReuseCandidateCount","HarmfulReuseCandidateRate", ...
        "MissedReuseCandidateCount","MissedReuseCandidateRate", ...
        "HarmfulInterferenceOverlapCandidateCount", ...
        "HarmfulInterferenceOverlapCandidateRate", ...
        "MissedInterferenceOverlapCandidateCount", ...
        "MissedInterferenceOverlapCandidateRate", ...
        "ResourcePairGraphXorCount", ...
        "ResourcePairGraphXorRate","ResourcePairGraphJaccard", ...
        "TimePairGraphXorCount","TimePairGraphXorRate", ...
        "TimePairGraphJaccard", ...
        "InterferenceOverlapPairGraphXorCount", ...
        "InterferenceOverlapPairGraphXorRate", ...
        "InterferenceOverlapPairGraphJaccard", ...
        "LiveMinimumTrueCoResourceDistanceMeters", ...
        "OracleMinimumTrueCoResourceDistanceMeters", ...
        "LiveLowerTailTrueCoResourceDistanceMeters", ...
        "OracleLowerTailTrueCoResourceDistanceMeters", ...
        "MeanCoUserJaccard","MeanFiniteTrueDistanceRegretMeters"]);
end

function rate = pairRate(count,pairCount)
if pairCount == 0
    rate = NaN;
else
    rate = count / pairCount;
end
end

function validateResourceIds(resourceIds,resourceCount)
assigned = ~isnan(resourceIds);
if any(~isfinite(resourceIds(assigned))) || ...
        any(resourceIds(assigned) < 1) || ...
        any(resourceIds(assigned) > resourceCount) || ...
        any(mod(resourceIds(assigned),1) ~= 0)
    error( ...
        "v2xsim:resource:metrics:InvalidResourceId", ...
        "Resource IDs must be NaN or valid positive grid IDs.");
end
end

function times = resourceTimes(resourceIds,frequencyCount)
times = nan(size(resourceIds));
assigned = ~isnan(resourceIds);
times(assigned) = ceil(resourceIds(assigned) / frequencyCount);
end

function frequencies = resourceFrequencies( ...
        resourceIds,frequencyCount)
frequencies = nan(size(resourceIds));
assigned = ~isnan(resourceIds);
frequencies(assigned) = ...
    mod(resourceIds(assigned) - 1,frequencyCount) + 1;
end

function matches = valuesMatch(left,right)
matches = left == right | (isnan(left) & isnan(right));
end

function [resourceGraph,timeGraph,interferenceGraph] = ...
        pairGraphs( ...
            resourceIds,timeSlots,frequencies, ...
            frequencyInterferenceCoupling)
assignedResources = ~isnan(resourceIds);
assignedTimes = ~isnan(timeSlots);
resourceGraph = ...
    resourceIds == resourceIds.' & ...
    assignedResources & assignedResources.';
timeGraph = ...
    timeSlots == timeSlots.' & assignedTimes & assignedTimes.';
safeFrequencies = frequencies;
safeFrequencies(~isfinite(safeFrequencies)) = 1;
directedCoupling = frequencyInterferenceCoupling( ...
    safeFrequencies,safeFrequencies.');
interferenceGraph = timeGraph & ...
    (directedCoupling > 0 | directedCoupling.' > 0);
resourceGraph(1:size(resourceGraph,1) + 1:end) = false;
timeGraph(1:size(timeGraph,1) + 1:end) = false;
interferenceGraph( ...
    1:size(interferenceGraph,1) + 1:end) = false;
end

function coupling = resolveFrequencyInterferenceCoupling( ...
        coupling,frequencyCount)
if isempty(coupling)
    frequencyIds = (1:frequencyCount).';
    coupling = double( ...
        abs(frequencyIds - frequencyIds.') <= 1);
elseif ~isequal(size(coupling),[frequencyCount frequencyCount])
    error( ...
        "v2xsim:resource:metrics:" + ...
        "FrequencyInterferenceCouplingSizeMismatch", ...
        "FrequencyInterferenceCoupling must match the frequency " + ...
        "dimension of GridSize.");
end
end

function nearest = nearestCoUserDistances(graph,distanceMeters)
ueCount = size(graph,1);
nearest = inf(ueCount,1);
for row = 1:ueCount
    coUsers = graph(row,:);
    if any(coUsers)
        nearest(row) = min(distanceMeters(row,coUsers));
    end
end
end

function difference = distanceDifference(left,right)
difference = left - right;
bothInfinite = isinf(left) & isinf(right) & sign(left) == sign(right);
difference(bothInfinite) = 0;
end

function [xorCount,xorRate,jaccard] = ...
        comparePairGraphs(left,right,pairMask)
left = left(pairMask);
right = right(pairMask);
xorCount = nnz(xor(left,right));
if isempty(left)
    xorRate = NaN;
else
    xorRate = xorCount / numel(left);
end
unionCount = nnz(left | right);
if unionCount == 0
    jaccard = 1;
else
    jaccard = nnz(left & right) / unionCount;
end
end

function value = finiteMinimum(values)
values = values(isfinite(values));
if isempty(values)
    value = NaN;
else
    value = min(values);
end
end

function value = lowerQuantile(values,probability)
values = sort(values(isfinite(values)));
if isempty(values)
    value = NaN;
    return
end
if isscalar(values)
    value = values;
    return
end
position = 1 + (numel(values) - 1) * probability;
lowerIndex = floor(position);
upperIndex = ceil(position);
weight = position - lowerIndex;
value = ...
    values(lowerIndex) * (1 - weight) + ...
    values(upperIndex) * weight;
end

function value = setJaccard(left,right)
unionCount = numel(union(left,right));
if unionCount == 0
    value = 1;
else
    value = numel(intersect(left,right)) / unionCount;
end
end
