function trace = evaluateMaximumReuseDistanceTrace( ...
        decisionTrace,assignmentsBefore,trueDistanceMeters,gridSize)
%EVALUATEMAXIMUMREUSEDISTANCETRACE Score live decisions in true geometry.

arguments (Input)
    decisionTrace table
    assignmentsBefore table
    trueDistanceMeters (:,:) double {mustBeReal,mustBeNonnegative}
    gridSize (1,2) double {mustBeInteger,mustBePositive}
end

expectedTraceVariables = [ ...
    "UeId","DecisionOrder","PreviousResourceId", ...
    "SelectedResourceId","SelectedTimeSlot", ...
    "SelectedFrequencyResource","SelectionScoreMeters", ...
    "WinningTimeMarginMeters","WinningFrequencyMarginMeters", ...
    "WitnessUeId"];
if ~isequal( ...
        string(decisionTrace.Properties.VariableNames), ...
        expectedTraceVariables)
    error( ...
        "v2xsim:resource:metrics:InvalidDecisionTrace", ...
        "DecisionTrace does not have the maximum-reuse schema.");
end
ueIds = assignmentsBefore.UeId;
ueCount = numel(ueIds);
if ~isequal(size(trueDistanceMeters),[ueCount ueCount])
    error( ...
        "v2xsim:resource:metrics:DistanceMatrixSizeMismatch", ...
        "True distances must align with AssignmentsBefore.");
end
[knownDecisionUes,decisionRows] = ...
    ismember(decisionTrace.UeId,ueIds);
if ~all(knownDecisionUes) || ...
        numel(unique(decisionRows)) ~= numel(decisionRows)
    error( ...
        "v2xsim:resource:metrics:InvalidDecisionTrace", ...
        "DecisionTrace must contain unique known UE identifiers.");
end

resourceIds = assignmentsBefore.ResourceIds(:,1);
resourceIds(decisionRows) = NaN;
rowCount = height(decisionTrace);
trueResourceRank = nan(rowCount,1);
trueTimeRank = nan(rowCount,1);
trueSelectionScore = nan(rowCount,1);
trueTimeScore = nan(rowCount,1);
trueTimeRegret = nan(rowCount,1);
trueWitnessUeId = strings(rowCount,1);

[~,traceOrder] = sort(decisionTrace.DecisionOrder);
for traceIndex = reshape(traceOrder,1,[])
    ueRow = decisionRows(traceIndex);
    selectedResourceId = ...
        decisionTrace.SelectedResourceId(traceIndex);
    quality = resourceQuality( ...
        ueRow,resourceIds,trueDistanceMeters,gridSize, ...
        selectedResourceId,ueIds);
    trueResourceRank(traceIndex) = quality.ResourceRank;
    trueTimeRank(traceIndex) = quality.TimeRank;
    trueSelectionScore(traceIndex) = quality.ResourceScoreMeters;
    trueTimeScore(traceIndex) = quality.TimeScoreMeters;
    trueTimeRegret(traceIndex) = quality.TimeRegretMeters;
    trueWitnessUeId(traceIndex) = quality.WitnessUeId;
    resourceIds(ueRow) = selectedResourceId;
end

trace = addvars( ...
    decisionTrace,trueResourceRank,trueTimeRank, ...
    trueSelectionScore,trueTimeScore,trueTimeRegret, ...
    trueWitnessUeId, ...
    NewVariableNames=[ ...
        "TrueResourceRank","TrueTimeRank", ...
        "TrueSelectionScoreMeters","TrueTimeScoreMeters", ...
        "TrueTimeRegretMeters","TrueWitnessUeId"]);
end

function quality = resourceQuality( ...
        ueRow,resourceIds,distanceMeters,gridSize, ...
        selectedResourceId,ueIds)
timeCount = gridSize(1);
frequencyCount = gridSize(2);
assignedRows = find(~isnan(resourceIds));
assignedTimes = ceil(resourceIds(assignedRows) / frequencyCount);
assignedFrequencies = ...
    mod(resourceIds(assignedRows) - 1,frequencyCount) + 1;
timeScores = inf(timeCount,1);
resourceScores = inf(prod(gridSize),1);

for timeSlot = 1:timeCount
    rowsAtTime = assignedRows(assignedTimes == timeSlot);
    if ~isempty(rowsAtTime)
        timeScores(timeSlot) = ...
            min(distanceMeters(ueRow,rowsAtTime));
    end
    for frequency = 1:frequencyCount
        resourceId = ...
            (timeSlot - 1) * frequencyCount + frequency;
        rowsAtResource = assignedRows( ...
            assignedTimes == timeSlot & ...
            assignedFrequencies == frequency);
        if ~isempty(rowsAtResource)
            resourceScores(resourceId) = ...
                min(distanceMeters(ueRow,rowsAtResource));
        end
    end
end

selectedTime = ceil(selectedResourceId / frequencyCount);
selectedTimeScore = timeScores(selectedTime);
selectedResourceScore = resourceScores(selectedResourceId);
timeRank = 1 + nnz(timeScores > selectedTimeScore);
resourceTimes = ceil((1:prod(gridSize)).' / frequencyCount);
resourceRank = 1 + nnz( ...
    timeScores(resourceTimes) > selectedTimeScore | ...
    (timeScores(resourceTimes) == selectedTimeScore & ...
    resourceScores > selectedResourceScore));
bestTimeScore = max(timeScores);
timeRegret = distanceRegret(bestTimeScore,selectedTimeScore);

coUserRows = assignedRows(assignedTimes == selectedTime);
if isempty(coUserRows)
    witnessUeId = string(missing);
else
    witnessTable = table( ...
        distanceMeters(ueRow,coUserRows).', ...
        ueIds(coUserRows),coUserRows, ...
        VariableNames=["Distance","UeId","RowIndex"]);
    witnessTable = sortrows( ...
        witnessTable,["Distance","UeId","RowIndex"]);
    witnessUeId = witnessTable.UeId(1);
end
quality = struct( ...
    "ResourceRank",resourceRank, ...
    "TimeRank",timeRank, ...
    "ResourceScoreMeters",selectedResourceScore, ...
    "TimeScoreMeters",selectedTimeScore, ...
    "TimeRegretMeters",timeRegret, ...
    "WitnessUeId",witnessUeId);
end

function regret = distanceRegret(best,selected)
if isinf(best) && isinf(selected)
    regret = 0;
else
    regret = best - selected;
end
end
