classdef AverageNeighborCountRecorderTest < matlab.unittest.TestCase
    methods (Test)
        function writesTechnologySpecificLongFormFiles(testCase)
            outputDirectory = testCase.makeOutputDirectory();
            invocation = testCase.makeInvocation( ...
                0.5, (1:6).', (1:3).', (4:6).', ...
                testCase.mixedTechnologyDistances(), ...
                [5, 10], [2 / 3, 2 / 3], [2 / 3, 4 / 3]);
            technologies = ["all", "cv2x", "itsg5"];
            expectedAverages = [ ...
                2 / 3, 1; ...
                2 / 3, 2 / 3; ...
                2 / 3, 4 / 3];

            for technologyIndex = 1:numel(technologies)
                hook = v2xsim.hooks.common. ...
                    AverageNeighborCountRecorder( ...
                        technologies(technologyIndex));
                hook = testCase.buildHook( ...
                    hook, outputDirectory, 91);
                hook = hook.invoke(invocation);
                hook.cleanup();
            end

            listing = dir(fullfile(outputDirectory, "*.csv"));
            actualNames = sort(string({listing.name}));
            expectedNames = sort([ ...
                "average_neighbor_count_over_time_all_91.csv", ...
                "average_neighbor_count_over_time_cv2x_91.csv", ...
                "average_neighbor_count_over_time_itsg5_91.csv", ...
                "average_neighbor_count_simulation_wide_all_91.csv", ...
                "average_neighbor_count_simulation_wide_cv2x_91.csv", ...
                "average_neighbor_count_simulation_wide_itsg5_91.csv"]);
            testCase.verifyEqual(actualNames, expectedNames);

            for technologyIndex = 1:numel(technologies)
                technology = technologies(technologyIndex);
                overTime = testCase.readOverTimeOutput( ...
                    outputDirectory, technology, 91);
                testCase.verifyEqual( ...
                    overTime{:, :}, ...
                    [ ...
                        0.5, 0, 5, ...
                            expectedAverages(technologyIndex, 1); ...
                        0.5, 5, 10, ...
                            expectedAverages(technologyIndex, 2)], ...
                    AbsTol=1e-12);

                simulationWide = ...
                    testCase.readSimulationWideOutput( ...
                        outputDirectory, technology, 91);
                testCase.verifyEqual( ...
                    simulationWide{:, :}, ...
                    [ ...
                        0, 5, ...
                            expectedAverages(technologyIndex, 1); ...
                        5, 10, ...
                            expectedAverages(technologyIndex, 2)], ...
                    AbsTol=1e-12);
            end
        end

        function weightsSimulationWideAverageByUeCount(testCase)
            outputDirectory = testCase.makeOutputDirectory();
            hook = v2xsim.hooks.common. ...
                AverageNeighborCountRecorder("cv2x");
            hook = testCase.buildHook(hook, outputDirectory, 92);
            firstInvocation = testCase.makeInvocation( ...
                0.1, [1; 2; 3], [1; 2; 3], zeros(0, 1), ...
                [0, 2, 7; 2, 0, 8; 7, 8, 0], ...
                [5, 10], [2 / 3, 4 / 3], [0, 0]);
            secondInvocation = testCase.makeInvocation( ...
                0.2, 4, 4, zeros(0, 1), 0, ...
                [5, 10], [0, 0], [0, 0]);

            hook = hook.invoke(firstInvocation);
            hook = hook.invoke(secondInvocation);
            hook.cleanup();

            overTime = testCase.readOverTimeOutput( ...
                outputDirectory, "cv2x", 92);
            testCase.verifyEqual( ...
                overTime{:, :}, ...
                [ ...
                    0.1, 0, 5, 2 / 3; ...
                    0.1, 5, 10, 4 / 3; ...
                    0.2, 0, 5, 0; ...
                    0.2, 5, 10, 0], ...
                AbsTol=1e-12);

            simulationWide = testCase.readSimulationWideOutput( ...
                outputDirectory, "cv2x", 92);
            testCase.verifyEqual( ...
                simulationWide{:, :}, ...
                [0, 5, 0.5; 5, 10, 1], ...
                AbsTol=1e-12);

            filename = fullfile( ...
                outputDirectory, ...
                "average_neighbor_count_over_time_cv2x_92.csv");
            lines = readlines(filename);
            testCase.verifyEqual( ...
                sum(startsWith( ...
                    lines, "SimulationTimeSeconds,")), 1);
        end

        function excludesEmptyTechnologyPopulationFromAverage(testCase)
            outputDirectory = testCase.makeOutputDirectory();
            hook = v2xsim.hooks.common. ...
                AverageNeighborCountRecorder("itsg5");
            hook = testCase.buildHook(hook, outputDirectory, 93);
            noItsG5Ues = testCase.makeInvocation( ...
                0.1, [1; 2], [1; 2], zeros(0, 1), ...
                [0, 2; 2, 0], [5, 10], [1, 0], [0, 0]);
            twoItsG5Ues = testCase.makeInvocation( ...
                0.2, [3; 4], zeros(0, 1), [3; 4], ...
                [0, 2; 2, 0], [5, 10], [0, 0], [1, 0]);

            hook = hook.invoke(noItsG5Ues);
            hook = hook.invoke(twoItsG5Ues);
            hook.cleanup();

            overTime = testCase.readOverTimeOutput( ...
                outputDirectory, "itsg5", 93);
            testCase.verifyEqual( ...
                overTime{:, :}, ...
                [ ...
                    0.1, 0, 5, 0; ...
                    0.1, 5, 10, 0; ...
                    0.2, 0, 5, 1; ...
                    0.2, 5, 10, 0], ...
                AbsTol=1e-12);

            simulationWide = testCase.readSimulationWideOutput( ...
                outputDirectory, "itsg5", 93);
            testCase.verifyEqual( ...
                simulationWide{:, :}, ...
                [0, 5, 1; 5, 10, 0], ...
                AbsTol=1e-12);
        end

        function writesZeroWhenNoApplicableUesAreObserved(testCase)
            outputDirectory = testCase.makeOutputDirectory();
            hook = v2xsim.hooks.common. ...
                AverageNeighborCountRecorder("all");
            hook = testCase.buildHook(hook, outputDirectory, 94);
            invocation = testCase.makeInvocation( ...
                0.1, zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
                zeros(0), [5, 10], [0, 0], [0, 0]);

            hook = hook.invoke(invocation);
            hook.cleanup();

            overTime = testCase.readOverTimeOutput( ...
                outputDirectory, "all", 94);
            testCase.verifyEqual( ...
                overTime{:, :}, ...
                [0.1, 0, 5, 0; 0.1, 5, 10, 0], ...
                AbsTol=1e-12);
            testCase.verifyFalse(any(isnan(overTime{:, :}), "all"));

            simulationWide = testCase.readSimulationWideOutput( ...
                outputDirectory, "all", 94);
            testCase.verifyEqual( ...
                simulationWide{:, :}, ...
                [0, 5, 0; 5, 10, 0], ...
                AbsTol=1e-12);
            testCase.verifyFalse( ...
                any(isnan(simulationWide{:, :}), "all"));
        end

        function rejectsChangedAwarenessRanges(testCase)
            outputDirectory = testCase.makeOutputDirectory();
            hook = v2xsim.hooks.common. ...
                AverageNeighborCountRecorder("cv2x");
            hook = testCase.buildHook(hook, outputDirectory, 95);
            firstInvocation = testCase.makeInvocation( ...
                0.1, [1; 2], [1; 2], zeros(0, 1), ...
                [0, 2; 2, 0], [5, 10], [1, 0], [0, 0]);
            changedRangesInvocation = testCase.makeInvocation( ...
                0.2, [1; 2], [1; 2], zeros(0, 1), ...
                [0, 2; 2, 0], [5, 20], [1, 0], [0, 0]);
            hook = hook.invoke(firstInvocation);

            testCase.verifyError( ...
                @() hook.invoke(changedRangesInvocation), ...
                "v2xsim:hook:outputs:AwarenessRangesChanged");
        end
    end

    methods (Access = private)
        function outputDirectory = makeOutputDirectory(testCase)
            fixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            outputDirectory = string(fixture.Folder);
        end

        function hook = buildHook( ...
                ~, hook, outputDirectory, simulationIdentifier)
            hook = hook.build( ...
                v2xsim.hook.dependencies.OutputDirectory( ...
                    outputDirectory), ...
                v2xsim.hook.dependencies.SimulationIdentifier( ...
                    simulationIdentifier));
        end

        function invocation = makeInvocation( ...
                ~, simulationTimeSeconds, ueIds, cv2xUeIds, ...
                itsG5UeIds, distanceMatrixMeters, ...
                awarenessRangesMeters, averageCv2xNeighbors, ...
                averageItsG5Neighbors)
            invocation = v2xsim.hook.invocations. ...
                AfterNeighborGraphUpdatedInvocation( ...
                    simulationTimeSeconds, ueIds, cv2xUeIds, ...
                    itsG5UeIds, distanceMatrixMeters, ...
                    awarenessRangesMeters, averageCv2xNeighbors, ...
                    averageItsG5Neighbors);
        end

        function distances = mixedTechnologyDistances(~)
            distances = inf(6);
            distances(1:7:end) = 0;
            connectedPairs = [ ...
                1, 2, 2; ...
                1, 3, 7; ...
                4, 5, 2; ...
                4, 6, 7; ...
                5, 6, 8];
            for pairIndex = 1:size(connectedPairs, 1)
                firstUeIndex = connectedPairs(pairIndex, 1);
                secondUeIndex = connectedPairs(pairIndex, 2);
                distance = connectedPairs(pairIndex, 3);
                distances(firstUeIndex, secondUeIndex) = distance;
                distances(secondUeIndex, firstUeIndex) = distance;
            end
        end

        function output = readOverTimeOutput( ...
                testCase, outputDirectory, technology, ...
                simulationIdentifier)
            filename = fullfile( ...
                outputDirectory, ...
                sprintf( ...
                    "average_neighbor_count_over_time_%s_%d.csv", ...
                    technology, simulationIdentifier));
            testCase.verifyTrue(isfile(filename));
            output = readtable(filename);
            testCase.verifyEqual( ...
                string(output.Properties.VariableNames), ...
                [ ...
                    "SimulationTimeSeconds", ...
                    "AwarenessRangeLowerBoundMeters", ...
                    "AwarenessRangeUpperBoundMeters", ...
                    "AverageNeighborCount"]);
        end

        function output = readSimulationWideOutput( ...
                testCase, outputDirectory, technology, ...
                simulationIdentifier)
            filename = fullfile( ...
                outputDirectory, ...
                sprintf( ...
                    "average_neighbor_count_simulation_wide_%s_%d.csv", ...
                    technology, simulationIdentifier));
            testCase.verifyTrue(isfile(filename));
            output = readtable(filename);
            testCase.verifyEqual( ...
                string(output.Properties.VariableNames), ...
                [ ...
                    "AwarenessRangeLowerBoundMeters", ...
                    "AwarenessRangeUpperBoundMeters", ...
                    "AverageNeighborCount"]);
        end
    end
end
