classdef ControllerDiagnosticsRecorderTest < ...
        matlab.unittest.TestCase
    %CONTROLLERDIAGNOSTICSRECORDERTEST Tests bounded long-form output.

    methods (Test)
        function writesJoinableControllerTables(testCase)
            outputDirectory = testCase.makeOutputDirectory();
            [context,result] = testCase.createDiagnosticAllocation();
            invocation = v2xsim.hook.invocations. ...
                AfterResourceAllocationDecisionInvocation( ...
                    0.002,uint64(9),context,result);
            recorder = ...
                v2xsim.hooks.common.ControllerDiagnosticsRecorder( ...
                    [1.5 2.5],TopK=2,FlushRowCount=1, ...
                    RankDisplacementEnabled=true, ...
                    FilenamePrefix="study");
            recorder = recorder.build( ...
                v2xsim.hook.dependencies.OutputDirectory( ...
                    outputDirectory));

            [recorder,returnedInvocation] = ...
                recorder.invoke(invocation);
            recorder.cleanup();

            testCase.verifyEqual(returnedInvocation,invocation);
            expectedSuffixes = [ ...
                "state","topology","rank_displacement","range_topology", ...
                "allocation_decision","allocation_summary","co_user", ...
                "reuse_candidate"];
            for suffix = expectedSuffixes
                testCase.verifyTrue(isfile(fullfile( ...
                    outputDirectory, ...
                    "study_" + suffix + ".csv")));
            end
            topology = readtable(fullfile( ...
                outputDirectory,"study_topology.csv"), ...
                TextType="string");
            allocation = readtable(fullfile( ...
                outputDirectory,"study_allocation_summary.csv"), ...
                TextType="string");
            reuseCandidates = readtable(fullfile( ...
                outputDirectory,"study_reuse_candidate.csv"), ...
                TextType="string");
            testCase.verifyEqual(height(topology),3);
            state = readtable(fullfile(outputDirectory,"study_state.csv"), ...
                TextType="string");
            testCase.verifyEqual(state.UeId,result.Diagnostics.UeIds);
            testCase.verifyEqual(state.EstimatedXMeters,context.X);
            testCase.verifyEqual(state.LiveResourceId,result.Assignments.ResourceIds);
            testCase.verifyEqual(state.OracleResourceId, ...
                result.Diagnostics.OracleAssignments.ResourceIds);
            testCase.verifyEqual(state.RandomPlanFingerprint, ...
                repmat(result.Diagnostics.RandomPlanFingerprint,3,1));
            testCase.verifyEqual(state.AllocationEpoch,repmat(9,3,1));
            testCase.verifyEqual(state.SimulationTimeSeconds,repmat(0.002,3,1));
            testCase.verifyEqual( ...
                topology.AllocationEpoch,repmat(9,3,1));
            testCase.verifyEqual( ...
                allocation.ResourcePairGraphXorCount,2);
            testCase.verifyEqual( ...
                allocation.NetworkSliceId,"global");
            testCase.verifyEqual(height(reuseCandidates),2);
            testCase.verifyEqual( ...
                sort(reuseCandidates.CandidateType), ...
                sort(["harmful_reuse";"missed_reuse"]));
            testCase.verifyEqual( ...
                allocation.HarmfulReuseCandidateCount,1);
            testCase.verifyEqual( ...
                allocation.MissedReuseCandidateCount,1);
            testCase.verifyEqual( ...
                allocation.HarmfulReuseCandidateRate,1/3, ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                allocation.MissedReuseCandidateRate,1/3, ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                allocation. ...
                    HarmfulInterferenceOverlapCandidateCount,1);
            testCase.verifyEqual( ...
                allocation. ...
                    MissedInterferenceOverlapCandidateCount,1);
            testCase.verifyEqual( ...
                allocation. ...
                    InterferenceOverlapPairGraphXorRate,2/3, ...
                AbsTol=1e-12);
            testCase.verifyTrue(all(ismember( ...
                [ ...
                    "LiveResourceRelation", ...
                    "OracleResourceRelation", ...
                    "IsHarmfulInterferenceOverlap", ...
                    "IsMissedInterferenceOverlap"], ...
                string( ...
                    reuseCandidates.Properties.VariableNames))));
        end

        function compactDefaultOmitsRankAndWritesEmptyPairSchema( ...
                testCase)
            outputDirectory = testCase.makeOutputDirectory();
            [context,result] = testCase.createDiagnosticAllocation();
            diagnostics = result.Diagnostics;
            diagnostics.OracleAssignments = result.Assignments;
            [~,assignmentRows] = ismember( ...
                diagnostics.OracleDecisionTrace.UeId, ...
                result.Assignments.UeId);
            diagnostics.OracleDecisionTrace.SelectedResourceId = ...
                result.Assignments.ResourceIds(assignmentRows,1);
            result = v2xsim.resource.ResourceAllocationResult( ...
                result.NetworkSliceId,result.Assignments, ...
                result.DecisionUeIds,result.ReassignedUeIds, ...
                result.BlockedUeIds,result.Reservations,diagnostics);
            invocation = v2xsim.hook.invocations. ...
                AfterResourceAllocationDecisionInvocation( ...
                    0.002,uint64(4),context,result);
            recorder = ...
                v2xsim.hooks.common.ControllerDiagnosticsRecorder( ...
                    [1.5 2.5],FlushRowCount=1);
            testCase.verifyFalse( ...
                recorder.RankDisplacementEnabled);
            recorder = recorder.build( ...
                v2xsim.hook.dependencies.OutputDirectory( ...
                    outputDirectory));

            [recorder,~] = recorder.invoke(invocation);
            recorder.cleanup();

            testCase.verifyFalse(isfile(fullfile( ...
                outputDirectory, ...
                "controller_rank_displacement.csv")));
            candidateFilename = fullfile( ...
                outputDirectory,"controller_reuse_candidate.csv");
            testCase.verifyTrue(isfile(candidateFilename));
            candidates = readtable( ...
                candidateFilename,TextType="string");
            summary = readtable(fullfile( ...
                outputDirectory, ...
                "controller_allocation_summary.csv"));
            testCase.verifyEmpty(candidates);
            testCase.verifyEqual( ...
                summary.HarmfulReuseCandidateCount,0);
            testCase.verifyEqual( ...
                summary.MissedReuseCandidateCount,0);
            testCase.verifyEqual( ...
                summary.HarmfulReuseCandidateRate,0);
            testCase.verifyEqual( ...
                summary.MissedReuseCandidateRate,0);
            testCase.verifyEqual( ...
                summary. ...
                    HarmfulInterferenceOverlapCandidateCount,0);
            testCase.verifyEqual( ...
                summary. ...
                    MissedInterferenceOverlapCandidateCount,0);
            testCase.verifyEqual( ...
                summary. ...
                    InterferenceOverlapPairGraphXorRate,0);
        end

        function stateRowsAlignIdentitiesAndUseWrappedTrueGeometry(testCase)
            grid = v2xsim.resource.BRResourceGrid( ...
                v2xsim.network.NetworkSliceId("global"),2,2,0.001);
            ids = ["a";"b";"c";"d"];
            x = [98;2;4;40];
            linear = abs(x-x.');
            wrapped = min(linear,100-linear);
            % Force two co-resource users and a third on another frequency
            % in the same slot, with the final UE alone in its time slot.
            mask = logical([1 0 0 0;1 0 0 0;0 1 0 0;0 0 1 0]);
            order = [3 1 4 2];
            consumedX = [198;-98;4;40];
            context = v2xsim.resource.CentralizedAllocationContext( ...
                grid.NetworkSliceId,ids(order),1,false(4,1),mask(order,:), ...
                consumedX(order),wrapped(order,order),wrapped(order,order), ...
                zeros(4),zeros(4));
            allocator = v2xsim.resource.MaximumReuseDistanceAllocator( ...
                grid,7,1,DiagnosticsEnabled=true).synchronizeUes(ids);
            [allocator,~] = allocator.initialize(context);
            [~,result] = allocator.step(context);
            originalRows = v2xsim.resource.metrics.buildControllerDiagnosticRows( ...
                0.3,uint64(3),context,result,10);
            % Independently reorder all named tables, including pre-state.
            diagnostics = result.Diagnostics;
            diagnostics.AssignmentsBefore = diagnostics.AssignmentsBefore([4 3 2 1],:);
            diagnostics.OracleAssignments = diagnostics.OracleAssignments(order,:);
            diagnostics.LiveDecisionTrace = diagnostics.LiveDecisionTrace(order,:);
            diagnostics.OracleDecisionTrace = diagnostics.OracleDecisionTrace([4 2 1 3],:);
            result = v2xsim.resource.ResourceAllocationResult( ...
                result.NetworkSliceId,result.Assignments(order,:), ...
                result.DecisionUeIds,result.ReassignedUeIds,result.BlockedUeIds, ...
                result.Reservations,diagnostics);
            rows = v2xsim.resource.metrics.buildControllerDiagnosticRows( ...
                0.3,uint64(3),context,result,10);
            testCase.verifyEqual(rows.State,originalRows.State);
            testCase.verifyEqual(sortrows(rows.AllocationDecision,"UeId"), ...
                sortrows(originalRows.AllocationDecision,"UeId"));
            testCase.verifyEqual(rows.State.UeId,ids);
            testCase.verifyEqual(rows.State.EstimatedXMeters,consumedX);
            testCase.verifyEqual(rows.State.LiveResourceId,[1;1;2;3]);
            testCase.verifyEqual(rows.State.OracleResourceId,[1;1;2;3]);
            testCase.verifyEqual(rows.State.NearestTrueCoResourceMeters,[4;4;Inf;Inf]);
            testCase.verifyEqual(rows.State.NearestTrueSameSlotMeters,[4;2;2;Inf]);
            testCase.verifyEqual(rows.AllocationDecision.TrueTimeRegretMeters,zeros(4,1));
            testCase.verifyEqual(rows.State.AbsoluteSlot,ones(4,1));
            testCase.verifyEqual(rows.State.NetworkSliceId,repmat("global",4,1));
        end

        function bufferedStateAppendsEachEpochOnce(testCase)
            outputDirectory = testCase.makeOutputDirectory();
            [context,result] = testCase.createDiagnosticAllocation();
            recorder = v2xsim.hooks.common.ControllerDiagnosticsRecorder( ...
                2,FlushRowCount=100000);
            recorder = recorder.build( ...
                v2xsim.hook.dependencies.OutputDirectory(outputDirectory));
            for epoch = 1:2
                invocation = v2xsim.hook.invocations. ...
                    AfterResourceAllocationDecisionInvocation( ...
                        0.1*epoch,uint64(epoch),context,result);
                [recorder,returned] = recorder.invoke(invocation);
                testCase.verifyEqual(returned,invocation);
            end
            recorder = recorder.cleanup();
            recorder.cleanup();
            state = readtable(fullfile(outputDirectory,"controller_state.csv"), ...
                TextType="string");
            testCase.verifyEqual(height(state),6);
            testCase.verifyEqual(state.AllocationEpoch,[1;1;1;2;2;2]);
            testCase.verifyEqual(state.UeId,repmat(result.Diagnostics.UeIds,2,1));
        end

        function ignoresAllocatorsWithoutDiagnostics(testCase)
            outputDirectory = testCase.makeOutputDirectory();
            grid = v2xsim.resource.BRResourceGrid( ...
                v2xsim.network.NetworkSliceId("global"),1,1,0.001);
            context = v2xsim.resource.CentralizedAllocationContext( ...
                grid.NetworkSliceId,"a",0,false,true,0,0,0,0,0);
            assignments = table( ...
                "a",1,VariableNames=["UeId","ResourceIds"]);
            result = v2xsim.resource.ResourceAllocationResult( ...
                grid.NetworkSliceId,assignments, ...
                strings(0,1),strings(0,1),strings(0,1), ...
                v2xsim.resource.ResourceAllocationResult. ...
                    emptyReservations());
            invocation = v2xsim.hook.invocations. ...
                AfterResourceAllocationDecisionInvocation( ...
                    0,uint64(0),context,result);
            recorder = ...
                v2xsim.hooks.common.ControllerDiagnosticsRecorder(1);
            recorder = recorder.build( ...
                v2xsim.hook.dependencies.OutputDirectory( ...
                    outputDirectory));

            [recorder,~] = recorder.invoke(invocation);
            recorder.cleanup();

            testCase.verifyEmpty(dir(fullfile( ...
                outputDirectory,"controller_*.csv")));
        end
    end

    methods (Access = private)
        function outputDirectory = makeOutputDirectory(testCase)
            fixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            outputDirectory = string(fixture.Folder);
        end

        function [context,result] = createDiagnosticAllocation(~)
            grid = v2xsim.resource.BRResourceGrid( ...
                v2xsim.network.NetworkSliceId("global"),2,1,0.001);
            ueIds = ["a";"b";"c"];
            apparent = [0 1 2;1 0 3;2 3 0];
            truth = [0 3 2;3 0 1;2 1 0];
            power = ones(3);
            power(1:4:end) = 0;
            initialContext = ...
                v2xsim.resource.CentralizedAllocationContext( ...
                    grid.NetworkSliceId,ueIds,0,false(3,1), ...
                    true(3,2),(1:3).',apparent,truth, ...
                    power,zeros(3));
            allocator = ...
                v2xsim.resource.MaximumReuseDistanceAllocator( ...
                    grid,5,1,DiagnosticsEnabled=true);
            allocator = allocator.synchronizeUes(ueIds);
            [allocator,~] = allocator.initialize(initialContext);
            context = v2xsim.resource.CentralizedAllocationContext( ...
                grid.NetworkSliceId,ueIds,1,false(3,1), ...
                true(3,2),(1:3).',apparent,truth,power,zeros(3));
            [~,result] = allocator.step(context);
        end
    end
end
