classdef ControllerDiagnosticsRecorderTest < ...
        matlab.unittest.TestCase
    %CONTROLLERDIAGNOSTICSRECORDERTEST Tests bounded long-form output.

    methods (Test)
        function writesJoinableControllerTables(testCase)
            outputDirectory = testCase.makeOutputDirectory();
            [context,result] = testCase.createDiagnosticAllocation();
            invocation = v2xsim.hook.invocations. ...
                AfterResourceAllocationDecisionInvocation( ...
                    0.002,uint64(9),context,result);
            recorder = ...
                v2xsim.hooks.common.ControllerDiagnosticsRecorder( ...
                    [1.5 2.5],TopK=2,FlushRowCount=1, ...
                    RankDisplacementEnabled=true, ...
                    FilenamePrefix="study");
            recorder = recorder.build( ...
                v2xsim.hook.dependencies.OutputDirectory( ...
                    outputDirectory));

            [recorder,returnedInvocation] = ...
                recorder.invoke(invocation);
            recorder.cleanup();

            testCase.verifyEqual(returnedInvocation,invocation);
            expectedSuffixes = [ ...
                "topology","rank_displacement","range_topology", ...
                "allocation_decision","allocation_summary","co_user", ...
                "reuse_candidate"];
            for suffix = expectedSuffixes
                testCase.verifyTrue(isfile(fullfile( ...
                    outputDirectory, ...
                    "study_" + suffix + ".csv")));
            end
            topology = readtable(fullfile( ...
                outputDirectory,"study_topology.csv"), ...
                TextType="string");
            allocation = readtable(fullfile( ...
                outputDirectory,"study_allocation_summary.csv"), ...
                TextType="string");
            reuseCandidates = readtable(fullfile( ...
                outputDirectory,"study_reuse_candidate.csv"), ...
                TextType="string");
            testCase.verifyEqual(height(topology),3);
            testCase.verifyEqual( ...
                topology.AllocationEpoch,repmat(9,3,1));
            testCase.verifyEqual( ...
                allocation.ResourcePairGraphXorCount,2);
            testCase.verifyEqual( ...
                allocation.NetworkSliceId,"global");
            testCase.verifyEqual(height(reuseCandidates),2);
            testCase.verifyEqual( ...
                sort(reuseCandidates.CandidateType), ...
                sort(["harmful_reuse";"missed_reuse"]));
            testCase.verifyEqual( ...
                allocation.HarmfulReuseCandidateCount,1);
            testCase.verifyEqual( ...
                allocation.MissedReuseCandidateCount,1);
            testCase.verifyEqual( ...
                allocation.HarmfulReuseCandidateRate,1/3, ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                allocation.MissedReuseCandidateRate,1/3, ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                allocation. ...
                    HarmfulInterferenceOverlapCandidateCount,1);
            testCase.verifyEqual( ...
                allocation. ...
                    MissedInterferenceOverlapCandidateCount,1);
            testCase.verifyEqual( ...
                allocation. ...
                    InterferenceOverlapPairGraphXorRate,2/3, ...
                AbsTol=1e-12);
            testCase.verifyTrue(all(ismember( ...
                [ ...
                    "LiveResourceRelation", ...
                    "OracleResourceRelation", ...
                    "IsHarmfulInterferenceOverlap", ...
                    "IsMissedInterferenceOverlap"], ...
                string( ...
                    reuseCandidates.Properties.VariableNames))));
        end

        function compactDefaultOmitsRankAndWritesEmptyPairSchema( ...
                testCase)
            outputDirectory = testCase.makeOutputDirectory();
            [context,result] = testCase.createDiagnosticAllocation();
            diagnostics = result.Diagnostics;
            diagnostics.OracleAssignments = result.Assignments;
            [~,assignmentRows] = ismember( ...
                diagnostics.OracleDecisionTrace.UeId, ...
                result.Assignments.UeId);
            diagnostics.OracleDecisionTrace.SelectedResourceId = ...
                result.Assignments.ResourceIds(assignmentRows,1);
            result = v2xsim.resource.ResourceAllocationResult( ...
                result.NetworkSliceId,result.Assignments, ...
                result.DecisionUeIds,result.ReassignedUeIds, ...
                result.BlockedUeIds,result.Reservations,diagnostics);
            invocation = v2xsim.hook.invocations. ...
                AfterResourceAllocationDecisionInvocation( ...
                    0.002,uint64(4),context,result);
            recorder = ...
                v2xsim.hooks.common.ControllerDiagnosticsRecorder( ...
                    [1.5 2.5],FlushRowCount=1);
            testCase.verifyFalse( ...
                recorder.RankDisplacementEnabled);
            recorder = recorder.build( ...
                v2xsim.hook.dependencies.OutputDirectory( ...
                    outputDirectory));

            [recorder,~] = recorder.invoke(invocation);
            recorder.cleanup();

            testCase.verifyFalse(isfile(fullfile( ...
                outputDirectory, ...
                "controller_rank_displacement.csv")));
            candidateFilename = fullfile( ...
                outputDirectory,"controller_reuse_candidate.csv");
            testCase.verifyTrue(isfile(candidateFilename));
            candidates = readtable( ...
                candidateFilename,TextType="string");
            summary = readtable(fullfile( ...
                outputDirectory, ...
                "controller_allocation_summary.csv"));
            testCase.verifyEmpty(candidates);
            testCase.verifyEqual( ...
                summary.HarmfulReuseCandidateCount,0);
            testCase.verifyEqual( ...
                summary.MissedReuseCandidateCount,0);
            testCase.verifyEqual( ...
                summary.HarmfulReuseCandidateRate,0);
            testCase.verifyEqual( ...
                summary.MissedReuseCandidateRate,0);
            testCase.verifyEqual( ...
                summary. ...
                    HarmfulInterferenceOverlapCandidateCount,0);
            testCase.verifyEqual( ...
                summary. ...
                    MissedInterferenceOverlapCandidateCount,0);
            testCase.verifyEqual( ...
                summary. ...
                    InterferenceOverlapPairGraphXorRate,0);
        end

        function ignoresAllocatorsWithoutDiagnostics(testCase)
            outputDirectory = testCase.makeOutputDirectory();
            grid = v2xsim.resource.BRResourceGrid( ...
                v2xsim.network.NetworkSliceId("global"),1,1,0.001);
            context = v2xsim.resource.CentralizedAllocationContext( ...
                grid.NetworkSliceId,"a",0,false,true,0,0,0,0,0);
            assignments = table( ...
                "a",1,VariableNames=["UeId","ResourceIds"]);
            result = v2xsim.resource.ResourceAllocationResult( ...
                grid.NetworkSliceId,assignments, ...
                strings(0,1),strings(0,1),strings(0,1), ...
                v2xsim.resource.ResourceAllocationResult. ...
                    emptyReservations());
            invocation = v2xsim.hook.invocations. ...
                AfterResourceAllocationDecisionInvocation( ...
                    0,uint64(0),context,result);
            recorder = ...
                v2xsim.hooks.common.ControllerDiagnosticsRecorder(1);
            recorder = recorder.build( ...
                v2xsim.hook.dependencies.OutputDirectory( ...
                    outputDirectory));

            [recorder,~] = recorder.invoke(invocation);
            recorder.cleanup();

            testCase.verifyEmpty(dir(fullfile( ...
                outputDirectory,"controller_*.csv")));
        end
    end

    methods (Access = private)
        function outputDirectory = makeOutputDirectory(testCase)
            fixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            outputDirectory = string(fixture.Folder);
        end

        function [context,result] = createDiagnosticAllocation(~)
            grid = v2xsim.resource.BRResourceGrid( ...
                v2xsim.network.NetworkSliceId("global"),2,1,0.001);
            ueIds = ["a";"b";"c"];
            apparent = [0 1 2;1 0 3;2 3 0];
            truth = [0 3 2;3 0 1;2 1 0];
            power = ones(3);
            power(1:4:end) = 0;
            initialContext = ...
                v2xsim.resource.CentralizedAllocationContext( ...
                    grid.NetworkSliceId,ueIds,0,false(3,1), ...
                    true(3,2),(1:3).',apparent,truth, ...
                    power,zeros(3));
            allocator = ...
                v2xsim.resource.MaximumReuseDistanceAllocator( ...
                    grid,5,1,DiagnosticsEnabled=true);
            allocator = allocator.synchronizeUes(ueIds);
            [allocator,~] = allocator.initialize(initialContext);
            context = v2xsim.resource.CentralizedAllocationContext( ...
                grid.NetworkSliceId,ueIds,1,false(3,1), ...
                true(3,2),(1:3).',apparent,truth,power,zeros(3));
            [~,result] = allocator.step(context);
        end
    end
end
