classdef InterferenceEvidenceRecorderTest < matlab.unittest.TestCase
    methods (Test)
        function preservesPacketSequenceAcrossSuccessOnlyPacket( ...
                testCase)
            fixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            recorder = v2xsim.hooks.common. ...
                InterferenceEvidenceRecorder(FlushRowCount=1);
            recorder = recorder.build( ...
                v2xsim.hook.dependencies.OutputDirectory( ...
                    string(fixture.Folder)));

            recorder = recorder.invoke( ...
                testCase.packetInvocation(0.1,"error"));
            recorder = recorder.invoke( ...
                testCase.evidenceInvocation(0.1));
            recorder = recorder.invoke( ...
                testCase.packetInvocation(0.2,"correct"));
            recorder = recorder.invoke( ...
                testCase.packetInvocation(0.3,"error"));
            recorder = recorder.invoke( ...
                testCase.evidenceInvocation(0.3));
            recorder = recorder.cleanup();

            attempts = recorder.terminalAttempts();
            counterfactuals = recorder.counterfactuals();
            testCase.verifyEqual( ...
                attempts.PacketSequence,[1;3]);
            testCase.verifyTrue(all( ...
                attempts.PacketSequenceAligned));
            testCase.verifyEqual( ...
                counterfactuals.PacketSequence,[1;3]);
            testCase.verifyEqual( ...
                counterfactuals.ResourceRelation, ...
                ["cochannel";"cochannel"]);
            testCase.verifyEqual( ...
                counterfactuals.ReusePairFirstUeId, ...
                ["ue4";"ue4"]);
            testCase.verifyEqual( ...
                counterfactuals.ReusePairSecondUeId, ...
                ["ue5";"ue5"]);

            attemptFiles = dir(fullfile( ...
                fixture.Folder, ...
                "interference_attempts_*.csv"));
            counterfactualFiles = dir(fullfile( ...
                fixture.Folder, ...
                "interference_counterfactuals_*.csv"));
            testCase.verifyNumElements(attemptFiles,2);
            testCase.verifyNumElements(counterfactualFiles,2);
        end

        function validatesDenseIdentityForNoncontiguousTransmitters( ...
                testCase)
            ueIds = "ue" + string((1:6).');
            transmitters = table( ...
                [2;5],ueIds([2;5]),[0.1;0.1],[1;1], ...
                [2;5],[2;2],[4;4], ...
                VariableNames=[ ...
                    "TransmitterId","TransmitterUeId", ...
                    "GenerationTimeSeconds","AttemptNumber", ...
                    "ResourceId","FrequencyResourceId", ...
                    "AllocationEpoch"]);
            attempts = ...
                v2xsim.hook.invocations. ...
                AfterInterferenceEvidenceDeterminedInvocation. ...
                emptyTerminalAttempts();
            counterfactuals = ...
                v2xsim.hook.invocations. ...
                AfterInterferenceEvidenceDeterminedInvocation. ...
                emptyCounterfactuals();

            invocation = v2xsim.hook.invocations. ...
                AfterInterferenceEvidenceDeterminedInvocation( ...
                    0.2,"LTE",6,ueIds,transmitters, ...
                    attempts,counterfactuals);

            testCase.verifyEqual( ...
                invocation.Transmitters.TransmitterUeId, ...
                ["ue2";"ue5"]);
        end
    end

    methods (Access = private)
        function invocation = packetInvocation( ...
                ~,generationTime,outcome)
            transmitters = table( ...
                5,"ue5",1,1,generationTime,nan,1,7,nan,2,9, ...
                VariableNames=[ ...
                    "TransmitterId","TransmitterUeId", ...
                    "Channel","PacketType","GenerationTimeSeconds", ...
                    "PacketSequence","AttemptNumber","ResourceId", ...
                    "TimeResourceId","FrequencyResourceId", ...
                    "AllocationEpoch"]);
            links = table( ...
                5,"ue5",2,"ue2",30,string(outcome),true, ...
                VariableNames=[ ...
                    "TransmitterId","TransmitterUeId", ...
                    "ReceiverId","ReceiverUeId", ...
                    "DistanceMeters","Outcome","IsTerminal"]);
            invocation = v2xsim.hook.invocations. ...
                AfterPacketFatesDeterminedInvocation( ...
                    generationTime + 0.01,"LTE",6,300, ...
                    transmitters,links);
        end

        function invocation = evidenceInvocation( ...
                ~,generationTime)
            ueIds = "ue" + string((1:6).');
            transmitters = table( ...
                5,"ue5",generationTime,1,7,2,9, ...
                VariableNames=[ ...
                    "TransmitterId","TransmitterUeId", ...
                    "GenerationTimeSeconds","AttemptNumber", ...
                    "ResourceId","FrequencyResourceId", ...
                    "AllocationEpoch"]);
            attempts = ...
                v2xsim.hook.invocations. ...
                AfterInterferenceEvidenceDeterminedInvocation. ...
                emptyTerminalAttempts();
            attempts(1,:) = { ...
                5,2,"error",-5,0,3,1,true};
            counterfactuals = ...
                v2xsim.hook.invocations. ...
                AfterInterferenceEvidenceDeterminedInvocation. ...
                emptyCounterfactuals();
            counterfactuals(1,:) = { ...
                5,2,4,7,2,"cochannel",3,2};
            invocation = v2xsim.hook.invocations. ...
                AfterInterferenceEvidenceDeterminedInvocation( ...
                    generationTime + 0.01,"LTE",6,ueIds, ...
                    transmitters,attempts,counterfactuals);
        end
    end
end
