classdef PacketMetricRecordersTest < matlab.unittest.TestCase
    methods (Test)
        function writesPacketDelayByAwarenessRange(testCase)
            outputDirectory = testCase.makeOutputDirectory();
            hook = v2xsim.hooks.common.PacketDelayRecorder(0.1, 0.2);
            hook = testCase.buildHook(hook,outputDirectory);
            invocation = testCase.makeInvocation( ...
                0.19, 0, [50; 150], ["correct"; "correct"], ...
                [100, 200]);

            hook = hook.invoke(invocation);
            hook.cleanup();

            values = readmatrix(fullfile( ...
                outputDirectory, "packet_delay_11p.csv"), ...
                FileType="text", Delimiter=",");
            testCase.verifyEqual( ...
                values(2, [1, 2, 4, 6]), ...
                [0.2, 1, 1, 2], AbsTol=1e-12);
        end

        function writesUpdateDelayBetweenSuccessfulReceptions(testCase)
            outputDirectory = testCase.makeOutputDirectory();
            hook = v2xsim.hooks.common.UpdateDelayRecorder( ...
                0.1, MaximumDelaySeconds=0.3);
            hook = testCase.buildHook(hook,outputDirectory);

            hook = hook.invoke(testCase.makeInvocation( ...
                0.1, 0.05, 50, "correct", 100));
            hook = hook.invoke(testCase.makeInvocation( ...
                0.31, 0.25, 50, "correct", 100));
            hook.cleanup();

            values = readmatrix(fullfile( ...
                outputDirectory, "update_delay_11p.csv"), ...
                FileType="text", Delimiter=",");
            testCase.verifyEqual( ...
                values(3, :), [0.3, 1, 1], AbsTol=1e-12);
        end

        function writesAgeFromPreviousPacketGeneration(testCase)
            outputDirectory = testCase.makeOutputDirectory();
            hook = v2xsim.hooks.common.DataAgeRecorder( ...
                0.1, MaximumAgeSeconds=0.3);
            hook = testCase.buildHook(hook,outputDirectory);

            hook = hook.invoke(testCase.makeInvocation( ...
                0.1, 0.04, 50, "correct", 100));
            hook = hook.invoke(testCase.makeInvocation( ...
                0.35, 0.3, 50, "correct", 100));
            hook.cleanup();

            values = readmatrix(fullfile( ...
                outputDirectory, "data_age_11p.csv"), ...
                FileType="text", Delimiter=",");
            testCase.verifyEqual( ...
                values(4, :), [0.4, 1, 1], AbsTol=1e-12);
        end

        function writesPacketReceptionOutcomesByDistanceBin(testCase)
            outputDirectory = testCase.makeOutputDirectory();
            hook = v2xsim.hooks.common. ...
                PacketReceptionRatioRecorder(10, 30, "11p");
            hook = testCase.buildHook(hook,outputDirectory);
            invocation = testCase.makeInvocation( ...
                0.1, 0.05, [5; 10; 15; 25], ...
                ["correct"; "correct"; "error"; "blocked"], 100);

            hook = hook.invoke(invocation);
            hook.cleanup();

            values = readmatrix(fullfile( ...
                outputDirectory, ...
                "packet_reception_ratio_11p.csv"), ...
                FileType="text", Delimiter=",");
            testCase.verifyEqual( ...
                values, [ ...
                    10, 1, 0, 0, 1, 1; ...
                    20, 1, 1, 0, 2, 0.5; ...
                    30, 0, 0, 1, 1, 0], ...
                AbsTol=1e-12);
        end
    end

    methods (Access = private)
        function outputDirectory = makeOutputDirectory(testCase)
            fixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            outputDirectory = string(fixture.Folder);
        end

        function hook = buildHook(~,hook,outputDirectory)
            hook = hook.build( ...
                v2xsim.hook.dependencies.OutputDirectory( ...
                    outputDirectory));
        end

        function invocation = makeInvocation( ...
                ~, simulationTime, generationTime, distances, ...
                outcomes, awarenessRanges)
            distances = distances(:);
            outcomes = string(outcomes(:));
            receiverIds = (2:numel(distances) + 1).';
            transmitters = table( ...
                1, 1, 1, generationTime, ...
                VariableNames=[ ...
                    "TransmitterId", "Channel", "PacketType", ...
                    "GenerationTimeSeconds"]);
            links = table( ...
                ones(numel(distances), 1), receiverIds, ...
                distances, outcomes, ...
                VariableNames=[ ...
                    "TransmitterId", "ReceiverId", ...
                    "DistanceMeters", "Outcome"]);
            invocation = v2xsim.hook.invocations. ...
                AfterPacketFatesDeterminedInvocation( ...
                    simulationTime, "11p", numel(distances) + 1, ...
                    awarenessRanges, transmitters, links);
        end
    end
end
