classdef PacketFateTraceRecorderTest < matlab.unittest.TestCase
    methods (Test)
        function waitingDropCanPrecedeOlderPacketCompletion(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            recorder = v2xsim.hooks.common.PacketFateTraceRecorder(FlushRowCount=2);
            recorder = recorder.build(v2xsim.hook.dependencies.OutputDirectory(string(fixture.Folder)));
            first = testCase.makeInvocation(0.1,0,1,4,1,["correct";"none"]);
            first = testCase.withIdentity(first,1,false);
            recorder = recorder.invoke(first);
            dropped = testCase.makeInvocation(0.2,0.15,0,nan,1,["blocked";"blocked"]);
            recorder = recorder.invoke(testCase.withIdentity(dropped,2,true));
            % A repeated success for the still-live older packet stays deduplicated.
            recorder = recorder.invoke(first);
            last = testCase.makeInvocation(0.3,0,2,4,1,["none";"error"]);
            recorder = recorder.invoke(testCase.withIdentity(last,1,true));
            recorder = recorder.cleanup();
            fates = recorder.terminalFates();
            testCase.verifyEqual(fates.PacketSequence,[1;2;2;1]);
            testCase.verifyEqual(fates.Outcome,["correct";"blocked";"blocked";"error"]);
        end

        function reconcilesAttemptsAndFlushesBoundedChunks(testCase)
            fixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            recorder = v2xsim.hooks.common. ...
                PacketFateTraceRecorder(FlushRowCount=2);
            recorder = recorder.build( ...
                v2xsim.hook.dependencies.OutputDirectory( ...
                    string(fixture.Folder)));

            recorder = recorder.invoke(testCase.makeInvocation( ...
                0.1,0.05,1,4,7, ...
                ["none";"correct"]));
            recorder = recorder.invoke(testCase.makeInvocation( ...
                0.2,0.05,2,5,7, ...
                ["error";"none"]));
            % A repeated terminal report must be idempotent.
            recorder = recorder.invoke(testCase.makeInvocation( ...
                0.2,0.05,2,5,7, ...
                ["error";"none"]));
            recorder = recorder.invoke(testCase.makeInvocation( ...
                0.3,0.25,0,nan,8, ...
                ["blocked";"blocked"]));
            recorder = recorder.cleanup();

            fates = recorder.terminalFates();
            testCase.verifyEqual(height(fates),4);
            testCase.verifyEqual( ...
                fates.TransmitterUeId,repmat("alpha",4,1));
            testCase.verifyEqual( ...
                fates.ReceiverUeId, ...
                ["gamma";"beta";"beta";"gamma"]);
            testCase.verifyEqual( ...
                fates.PacketSequence,[1;1;2;2]);
            testCase.verifyEqual( ...
                fates.Outcome, ...
                ["correct";"error";"blocked";"blocked"]);
            testCase.verifyEqual( ...
                fates.AttemptNumber,[1;2;0;0]);
            testCase.verifyEqual( ...
                fates.ResourceId,[4;5;nan;nan]);
            testCase.verifyEqual( ...
                fates.AllocationEpoch,[7;7;8;8]);

            files = dir(fullfile( ...
                fixture.Folder,"packet_fates_*.csv"));
            testCase.verifyNumElements(files,2);
            for file = files.'
                rows = readtable( ...
                    fullfile(file.folder,file.name));
                testCase.verifyLessThanOrEqual(height(rows),2);
            end
        end

        function legacyInvocationReceivesSyntheticStableIds(testCase)
            fixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            recorder = v2xsim.hooks.common. ...
                PacketFateTraceRecorder(FlushRowCount=10);
            recorder = recorder.build( ...
                v2xsim.hook.dependencies.OutputDirectory( ...
                    string(fixture.Folder)));
            transmitters = table( ...
                1,1,1,0.1, ...
                VariableNames=[ ...
                    "TransmitterId","Channel","PacketType", ...
                    "GenerationTimeSeconds"]);
            links = table( ...
                1,2,10,"correct", ...
                VariableNames=[ ...
                    "TransmitterId","ReceiverId", ...
                    "DistanceMeters","Outcome"]);
            invocation = v2xsim.hook.invocations. ...
                AfterPacketFatesDeterminedInvocation( ...
                    0.2,"11p",2,100,transmitters,links);

            recorder = recorder.invoke(invocation);
            fates = recorder.terminalFates();

            testCase.verifyEqual( ...
                fates.TransmitterUeId,"UE1");
            testCase.verifyEqual(fates.ReceiverUeId,"UE2");
            testCase.verifyEqual(fates.PacketSequence,1);
        end

        function writesParquetChunks(testCase)
            fixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            recorder = v2xsim.hooks.common. ...
                PacketFateTraceRecorder( ...
                    FlushRowCount=10,FileFormat="parquet");
            recorder = recorder.build( ...
                v2xsim.hook.dependencies.OutputDirectory( ...
                    string(fixture.Folder)));
            recorder = recorder.invoke(testCase.makeInvocation( ...
                0.2,0.05,1,5,3, ...
                ["correct";"error"]));

            recorder = recorder.cleanup();
            fates = recorder.terminalFates();

            testCase.verifyEqual(height(fates),2);
            testCase.verifyEqual( ...
                fates.Outcome,["correct";"error"]);
            files = dir(fullfile( ...
                fixture.Folder,"packet_fates_*.parquet"));
            testCase.verifyNumElements(files,1);
        end

        function allocatorBlockSurvivesLaterRadioFate( ...
                testCase)
            fixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            recorder = v2xsim.hooks.common. ...
                PacketFateTraceRecorder(FlushRowCount=10);
            recorder = recorder.build( ...
                v2xsim.hook.dependencies.OutputDirectory( ...
                    string(fixture.Folder)));
            recorder = recorder.invoke(testCase.makeInvocation( ...
                0.1,0.05,0,nan,1, ...
                ["blocked";"blocked"]));
            recorder = recorder.invoke(testCase.makeInvocation( ...
                0.2,0.05,1,5,1, ...
                ["correct";"error"],[11;21]));

            recorder = recorder.cleanup();
            fates = recorder.terminalFates();

            testCase.verifyEqual(height(fates),4);
            testCase.verifyEqual( ...
                fates.Outcome, ...
                ["blocked";"blocked";"correct";"error"]);
            testCase.verifyEqual( ...
                fates.PacketSequence,[1;1;1;1]);
            testCase.verifyEqual( ...
                fates.TrueDistanceMeters,[10;20;11;21]);
        end

        function packetsWithoutCandidateLinksAdvanceSequence(testCase)
            fixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            recorder = v2xsim.hooks.common. ...
                PacketFateTraceRecorder(FlushRowCount=10);
            recorder = recorder.build( ...
                v2xsim.hook.dependencies.OutputDirectory( ...
                    string(fixture.Folder)));
            recorder = recorder.invoke( ...
                testCase.makeEmptyInvocation(0.1,0.05));
            recorder = recorder.invoke(testCase.makeInvocation( ...
                0.2,0.15,1,5,1, ...
                ["correct";"error"]));

            fates = recorder.terminalFates();

            testCase.verifyEqual( ...
                fates.PacketSequence,[2;2]);
        end
    end

    methods (Access = private)
        function result = withIdentity(~,invocation,sequence,complete)
            tx = invocation.Transmitters;
            tx.PacketSequence(:) = sequence;
            tx.IsPacketComplete = complete;
            result = v2xsim.hook.invocations.AfterPacketFatesDeterminedInvocation( ...
                invocation.SimulationTimeSeconds,invocation.Technology,invocation.MaximumUeId, ...
                invocation.AwarenessRangesMeters,tx,invocation.Links);
        end

        function invocation = makeInvocation( ...
                ~,fateTime,generationTime,attempt,resource, ...
                allocationEpoch,outcomes,distances)
            if nargin < 8
                distances = [10;20];
            end
            transmitters = table( ...
                1,"alpha",1,1,generationTime,nan, ...
                attempt,resource,nan,nan,allocationEpoch, ...
                VariableNames=[ ...
                    "TransmitterId","TransmitterUeId", ...
                    "Channel","PacketType","GenerationTimeSeconds", ...
                    "PacketSequence","AttemptNumber","ResourceId", ...
                    "TimeResourceId","FrequencyResourceId", ...
                    "AllocationEpoch"]);
            links = table( ...
                [1;1],["alpha";"alpha"],[2;3],["beta";"gamma"], ...
                distances,outcomes,outcomes~="none", ...
                VariableNames=[ ...
                    "TransmitterId","TransmitterUeId", ...
                    "ReceiverId","ReceiverUeId", ...
                    "DistanceMeters","Outcome","IsTerminal"]);
            invocation = v2xsim.hook.invocations. ...
                AfterPacketFatesDeterminedInvocation( ...
                    fateTime,"LTE",3,100,transmitters,links);
        end

        function invocation = makeEmptyInvocation( ...
                ~,fateTime,generationTime)
            transmitters = table( ...
                1,"alpha",1,1,generationTime,nan, ...
                0,nan,nan,nan,1, ...
                VariableNames=[ ...
                    "TransmitterId","TransmitterUeId", ...
                    "Channel","PacketType","GenerationTimeSeconds", ...
                    "PacketSequence","AttemptNumber","ResourceId", ...
                    "TimeResourceId","FrequencyResourceId", ...
                    "AllocationEpoch"]);
            links = table( ...
                zeros(0,1),strings(0,1), ...
                zeros(0,1),strings(0,1), ...
                zeros(0,1),strings(0,1),false(0,1), ...
                VariableNames=[ ...
                    "TransmitterId","TransmitterUeId", ...
                    "ReceiverId","ReceiverUeId", ...
                    "DistanceMeters","Outcome","IsTerminal"]);
            invocation = v2xsim.hook.invocations. ...
                AfterPacketFatesDeterminedInvocation( ...
                    fateTime,"LTE",3,100,transmitters,links);
        end
    end
end
