classdef PositionErrorTraceRecorderTest < matlab.unittest.TestCase
    %POSITIONERRORTRACERECORDERTEST Tests bounded trace serialization.

    methods (Test)
        function testRowsForInvocationSynthesizesIdentityModule( ...
                testCase)
            positions = testCase.createPositions();
            invocation = v2xsim.hook.invocations. ...
                AfterPositionErrorChainAppliedInvocation( ...
                    positions, positions, 0.25);

            rows = v2xsim.hooks.common. ...
                PositionErrorTraceRecorder.rowsForInvocation(invocation);

            testCase.verifyEqual(height(rows), 2);
            testCase.verifyEqual(rows.ModuleIndex, zeros(2, 1));
            testCase.verifyEqual( ...
                rows.DisplacementMagnitudeMeters, zeros(2, 1));
            testCase.verifyEqual( ...
                rows.NetworkUpdateOutcome, strings(2, 1));
            testCase.verifyTrue(all(isnan( ...
                rows.OutputSourceTimeSeconds)));
            testCase.verifyTrue(all(isnan(rows.OutputAgeSeconds)));
        end

        function testFlushesBoundedNumberedChunks(testCase)
            outputDirectory = testCase.makeOutputDirectory();
            hook = v2xsim.hooks.common. ...
                PositionErrorTraceRecorder(FlushEveryRows=3);
            hook = hook.build( ...
                v2xsim.hook.dependencies.OutputDirectory( ...
                    outputDirectory));
            positions = testCase.createPositions();

            for simulationTime = [0, 0.1]
                after = positions;
                after.X = after.X + simulationTime + 1;
                diagnostics = ...
                    v2xsim.positioning.diagnostics.createRows( ...
                        positions, after, simulationTime, ...
                        "v2xsim.positioning.TestModule");
                if simulationTime == 0
                    diagnostics.NetworkUpdateOutcome(:) = ...
                        "BootstrapReceived";
                    diagnostics.OutputSourceTimeSeconds(:) = 0;
                    diagnostics.OutputAgeSeconds(:) = 0;
                else
                    diagnostics.NetworkUpdateOutcome = ...
                        ["Received"; "Dropped"];
                    diagnostics.OutputSourceTimeSeconds = [0.1; 0];
                    diagnostics.OutputAgeSeconds = [0; 0.1];
                end
                invocation = v2xsim.hook.invocations. ...
                    AfterPositionErrorChainAppliedInvocation( ...
                        positions, after, simulationTime, diagnostics);
                hook = hook.invoke(invocation);
            end

            firstFilename = fullfile( ...
                outputDirectory, ...
                "position_error_trace_000001.csv");
            testCase.verifyTrue(isfile(firstFilename));
            testCase.verifyEqual(height(hook.Records), 1);
            hook = hook.cleanup();
            secondFilename = fullfile( ...
                outputDirectory, ...
                "position_error_trace_000002.csv");
            testCase.verifyTrue(isfile(secondFilename));
            testCase.verifyEmpty(hook.Records);
            firstRows = readtable(firstFilename, TextType="string");
            secondRows = readtable(secondFilename, TextType="string");
            testCase.verifyEqual(height(firstRows), 3);
            testCase.verifyEqual(height(secondRows), 1);
            writtenRows = [firstRows; secondRows];
            testCase.verifyEqual( ...
                string(writtenRows.Properties.VariableNames), ...
                string(v2xsim.positioning.diagnostics. ...
                    emptyTable().Properties.VariableNames));
            testCase.verifyEqual( ...
                writtenRows.NetworkUpdateOutcome, ...
                ["BootstrapReceived"; "BootstrapReceived"; ...
                    "Received"; "Dropped"]);
            testCase.verifyEqual( ...
                writtenRows.OutputSourceTimeSeconds, [0; 0; 0.1; 0]);
            testCase.verifyEqual( ...
                writtenRows.OutputAgeSeconds, [0; 0; 0; 0.1]);
        end
    end

    methods (Access = private)
        function positions = createPositions(~)
            positions = table( ...
                [1; 2], [3; 4], ...
                VariableNames=["X", "Y"], ...
                RowNames=["V1", "V2"]);
        end

        function outputDirectory = makeOutputDirectory(testCase)
            fixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            outputDirectory = string(fixture.Folder);
        end
    end
end
