classdef SnapshotRecordersTest < matlab.unittest.TestCase
    methods (Test)
        function writesAllVehicleKinematicsAsLongFormCsv(testCase)
            outputDirectory = testCase.makeOutputDirectory();
            hook = v2xsim.hooks.common.VehicleKinematicsRecorder();
            hook = testCase.buildHook(hook,outputDirectory);
            vehicleKinematics = testCase.kinematicsTable( ...
                [ ...
                    10, 20, 3, 4, 0.5, -0.5; ...
                    30, 40, NaN, NaN, NaN, NaN], ...
                ["vehicle-B"; "vehicle-A"]);

            hook.invoke( ...
                v2xsim.hook.invocations. ...
                    AfterVehicleKinematicsUpdatedInvocation( ...
                        0.25, vehicleKinematics));

            filename = fullfile( ...
                outputDirectory, "vehicle_kinematics.csv");
            testCase.verifyTrue(isfile(filename));

            actual = testCase.readKinematicsOutput(filename);
            expected = testCase.outputRows( ...
                0.25,vehicleKinematics);
            testCase.verifyEqual( ...
                string(actual.Properties.VariableNames), ...
                [ ...
                    "SimulationTimeSeconds", ...
                    "VehicleId", ...
                    "X", ...
                    "Y", ...
                    "vX", ...
                    "vY", ...
                    "aX", ...
                    "aY"]);
            testCase.verifyEqual( ...
                actual.SimulationTimeSeconds, ...
                expected.SimulationTimeSeconds);
            testCase.verifyEqual(actual.VehicleId,expected.VehicleId);
            testCase.verifyTrue(isequaln( ...
                actual{:,3:end},expected{:,3:end}));
        end

        function supportsChangingMembershipOrderAndEmptySnapshots( ...
                testCase)
            outputDirectory = testCase.makeOutputDirectory();
            hook = v2xsim.hooks.common.VehicleKinematicsRecorder();
            hook = testCase.buildHook(hook,outputDirectory);
            firstKinematics = testCase.kinematicsTable( ...
                [ ...
                    1, 11, 2, 12, 3, 13; ...
                    4, 14, 5, 15, 6, 16], ...
                ["A"; "B"]);
            emptyKinematics = testCase.kinematicsTable( ...
                zeros(0,6),strings(0,1));
            secondKinematics = testCase.kinematicsTable( ...
                [ ...
                    7, 17, 8, 18, 9, 19; ...
                    40, 140, 50, 150, 60, 160], ...
                ["C"; "B"]);

            hook = hook.invoke( ...
                v2xsim.hook.invocations. ...
                    AfterVehicleKinematicsUpdatedInvocation( ...
                        0.1,firstKinematics));
            hook = hook.invoke( ...
                v2xsim.hook.invocations. ...
                    AfterVehicleKinematicsUpdatedInvocation( ...
                        0.15,emptyKinematics));
            hook.invoke( ...
                v2xsim.hook.invocations. ...
                    AfterVehicleKinematicsUpdatedInvocation( ...
                        0.2,secondKinematics));

            filename = fullfile( ...
                outputDirectory,"vehicle_kinematics.csv");
            actual = testCase.readKinematicsOutput(filename);
            expected = [ ...
                testCase.outputRows(0.1,firstKinematics); ...
                testCase.outputRows(0.2,secondKinematics)];

            testCase.verifyEqual(height(actual),4);
            testCase.verifyEqual( ...
                actual.SimulationTimeSeconds, ...
                expected.SimulationTimeSeconds);
            testCase.verifyEqual(actual.VehicleId,["A";"B";"C";"B"]);
            testCase.verifyTrue(isequaln( ...
                actual{:,3:end},expected{:,3:end}));
            testCase.verifyEqual(sum( ...
                startsWith( ...
                    readlines(filename), ...
                    "SimulationTimeSeconds,")),1);
        end

        function writesChannelBusyRatioAsCsv(testCase)
            outputDirectory = testCase.makeOutputDirectory();
            hook = v2xsim.hooks.common. ...
                ChannelBusyRatioRecorder(0.1, 1);
            hook = testCase.buildHook(hook,outputDirectory);

            hook = hook.invoke( ...
                v2xsim.hook.invocations. ...
                    AfterChannelBusyRatioSampledInvocation( ...
                        0.2, "5G", [1; 2], [1; 1], ...
                        [0.2; 0.4], [0.1; 0.2]));
            hook.cleanup();

            filename = fullfile( ...
                outputDirectory, ...
                "CBRofGenericVehicle_5G.csv");
            testCase.verifyTrue(isfile(filename));
            testCase.verifyFalse(isfile(fullfile( ...
                outputDirectory, ...
                "coex_cv2xOnly_CBRstatistic_5G.csv")));
            testCase.verifyEqual( ...
                readmatrix( ...
                    filename, FileType="text", Delimiter=","), ...
                [1.2, 0.2], AbsTol=1e-12);
        end

        function writesCoexistenceCv2xOnlyStatisticSeparately(testCase)
            outputDirectory = testCase.makeOutputDirectory();
            hook = v2xsim.hooks.common. ...
                ChannelBusyRatioRecorder( ...
                    0.1, 1, ...
                    WriteTechnologyOnlyStatistic=true);
            hook = testCase.buildHook(hook,outputDirectory);

            hook = hook.invoke( ...
                v2xsim.hook.invocations. ...
                    AfterChannelBusyRatioSampledInvocation( ...
                        0.2, "5G", [1; 2], [1; 1], ...
                        [0.6; 0.8], [0.2; 0.3]));
            hook.cleanup();

            standardFilename = fullfile( ...
                outputDirectory, "CBRstatistic_5G.csv");
            coexistenceFilename = fullfile( ...
                outputDirectory, ...
                "coex_cv2xOnly_CBRstatistic_5G.csv");
            testCase.verifyTrue(isfile(standardFilename));
            testCase.verifyTrue(isfile(coexistenceFilename));

            standardValues = readmatrix( ...
                standardFilename, FileType="text", Delimiter=",");
            coexistenceValues = readmatrix( ...
                coexistenceFilename, FileType="text", Delimiter=",");
            testCase.verifySize(standardValues, [3, 2]);
            testCase.verifySize(coexistenceValues, [3, 2]);
            testCase.verifyEqual( ...
                coexistenceValues(end, :), [0.3, 1], ...
                AbsTol=1e-12);
        end

        function configuredMultichannelCbrUsesChannelSuffix( ...
                testCase)
            outputDirectory = testCase.makeOutputDirectory();
            hook = v2xsim.hooks.common. ...
                ChannelBusyRatioRecorder( ...
                    0.1, 1, ChannelCount=2);
            hook = testCase.buildHook(hook,outputDirectory);

            hook = hook.invoke( ...
                v2xsim.hook.invocations. ...
                    AfterChannelBusyRatioSampledInvocation( ...
                        0.2, "5G", 1, 2, 0.4));
            hook.cleanup();

            testCase.verifyTrue(isfile(fullfile( ...
                outputDirectory, "CBRstatistic_5G_C2.csv")));
            testCase.verifyFalse(isfile(fullfile( ...
                outputDirectory, "CBRstatistic_5G.csv")));
        end
    end

    methods (Access = private)
        function vehicleKinematics = kinematicsTable( ...
                ~,values,vehicleIds)
            vehicleKinematics = array2table( ...
                values, ...
                VariableNames=["X","Y","vX","vY","aX","aY"]);
            if ~isempty(vehicleIds)
                vehicleKinematics.Properties.RowNames = ...
                    cellstr(vehicleIds);
            end
        end

        function rows = outputRows( ...
                ~,simulationTimeSeconds,vehicleKinematics)
            vehicleCount = height(vehicleKinematics);
            rows = table( ...
                repmat(simulationTimeSeconds,vehicleCount,1), ...
                string(vehicleKinematics.Properties.RowNames), ...
                vehicleKinematics.X, ...
                vehicleKinematics.Y, ...
                vehicleKinematics.vX, ...
                vehicleKinematics.vY, ...
                vehicleKinematics.aX, ...
                vehicleKinematics.aY, ...
                VariableNames=[ ...
                    "SimulationTimeSeconds", ...
                    "VehicleId", ...
                    "X", ...
                    "Y", ...
                    "vX", ...
                    "vY", ...
                    "aX", ...
                    "aY"]);
        end

        function output = readKinematicsOutput(~,filename)
            output = readtable(filename,TextType="string");
            output.VehicleId = string(output.VehicleId);
        end

        function outputDirectory = makeOutputDirectory(testCase)
            fixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            outputDirectory = string(fixture.Folder);
        end

        function hook = buildHook(~,hook,outputDirectory)
            hook = hook.build( ...
                v2xsim.hook.dependencies.OutputDirectory( ...
                    outputDirectory));
        end
    end
end
