classdef WirelessBlindSpotRecorderTest < matlab.unittest.TestCase
    methods (Test)
        function preservesEntryTimeForNoncontiguousUeIds(testCase)
            outputDirectory = testCase.makeOutputDirectory();
            hook = testCase.buildHook(outputDirectory);

            hook = testCase.invokeNeighborSnapshot(hook, 0);
            hook = testCase.invokeNeighborSnapshot(hook, 0.5);
            hook = testCase.invokeNeighborSnapshot(hook, 1.1);
            hook.cleanup();

            values = readmatrix(fullfile( ...
                outputDirectory, ...
                "wireless_blind_spot_11p.csv"), ...
                FileType="text", Delimiter=",");
            testCase.verifyEqual(values(1, 1:3), [1, 2, 0]);
            testCase.verifyEqual(values(1, 4), 1, AbsTol=1e-12);
        end

        function consumesOnlyFirstCorrectFateForOnePacket(testCase)
            outputDirectory = testCase.makeOutputDirectory();
            hook = testCase.buildHook(outputDirectory);

            hook = testCase.invokeNeighborSnapshot(hook, 0);
            hook = testCase.invokeCorrectFate(hook, 0.2, 0.1);
            hook = testCase.invokeNeighborSnapshot(hook, 0.7);
            hook = testCase.invokeCorrectFate(hook, 0.8, 0.1);
            hook = testCase.invokeNeighborSnapshot(hook, 1.3);
            hook.cleanup();

            values = readmatrix(fullfile( ...
                outputDirectory, ...
                "wireless_blind_spot_11p.csv"), ...
                FileType="text", Delimiter=",");
            testCase.verifyEqual(values(1, 1:3), [1, 2, 1]);
            testCase.verifyEqual( ...
                values(1, 4), 2 / 3, AbsTol=1e-6);
        end
    end

    methods (Access = private)
        function outputDirectory = makeOutputDirectory(testCase)
            fixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            outputDirectory = string(fixture.Folder);
        end

        function hook = buildHook(~,outputDirectory)
            hook = v2xsim.hooks.common. ...
                WirelessBlindSpotRecorder(1, 1);
            hook = hook.build( ...
                v2xsim.hook.dependencies.OutputDirectory( ...
                    outputDirectory));
        end

        function hook = invokeNeighborSnapshot( ...
                ~, inputHook, timeSeconds)
            invocation = v2xsim.hook.invocations. ...
                AfterNeighborGraphUpdatedInvocation( ...
                    timeSeconds, [2; 5], zeros(0, 1), [2; 5], ...
                    [0, 10; 10, 0], 20, 0, 1);
            hook = inputHook.invoke(invocation);
        end

        function hook = invokeCorrectFate( ...
                ~, inputHook, timeSeconds, generationTimeSeconds)
            transmitters = table( ...
                2, 1, 1, generationTimeSeconds, ...
                VariableNames=[ ...
                    "TransmitterId", "Channel", "PacketType", ...
                    "GenerationTimeSeconds"]);
            links = table( ...
                2, 5, 10, "correct", ...
                VariableNames=[ ...
                    "TransmitterId", "ReceiverId", ...
                    "DistanceMeters", "Outcome"]);
            hook = inputHook.invoke( ...
                v2xsim.hook.invocations. ...
                    AfterPacketFatesDeterminedInvocation( ...
                        timeSeconds, "11p", 5, 20, ...
                        transmitters, links));
        end
    end
end
