classdef V7ExamplesTest < matlab.unittest.TestCase
    %V7EXAMPLESTEST End-to-end checks for the progressive V7 examples.

    properties (SetAccess = private)
        ExampleDirectory (1,1) string
    end

    methods (TestClassSetup)
        function locateExamples(testCase)
            projectRoot = fileparts(fileparts(fileparts(fileparts( ...
                mfilename("fullpath")))));
            testCase.ExampleDirectory = fullfile( ...
                projectRoot,"examples","v7");
        end
    end

    methods (TestMethodSetup)
        function preserveProcessState(testCase)
            originalPath = path;
            originalDirectory = string(pwd);
            originalStream = RandStream.getGlobalStream();
            originalStreamState = originalStream.State;
            originalWarningState = warning;
            originalFigureVisibility = get( ...
                groot,"DefaultFigureVisible");
            testCase.addTeardown(@() restoreProcessState( ...
                originalPath,originalDirectory, ...
                originalStream,originalStreamState, ...
                originalWarningState,originalFigureVisibility));

            warning( ...
                "error","v2xsim:parameters:DeprecatedV6Name");
            set(groot,"DefaultFigureVisible","off");
        end
    end

    methods (Test)
        function testFirstSimulationPublishesSummary(testCase)
            [results,outputDirectory] = testCase.executeExample( ...
                "v7_01_run_first_simulation.m");

            testCase.verifyEqual(results.Summary.SchemaVersion,2);
            testCase.verifyEqual( ...
                string(results.Summary.Configuration.RadioAccessMode), ...
                "NR-V2X");
            testCase.verifyEqual( ...
                string(results.Summary.Configuration.Scenario.Type), ...
                "BidirectionalHighwayScenario");
            testCase.verifyTrue(isfile(fullfile( ...
                outputDirectory,"simulation_summary.json")));
        end

        function testTrafficRandomnessIsIndependent(testCase)
            [results,~] = testCase.executeExample( ...
                "v7_02_reproduce_traffic.m");

            testCase.verifyTrue(results.TrajectoriesMatch);
            testCase.verifyEqual( ...
                results.Comparison.ScenarioSeed,[102;102]);
            testCase.verifyEqual( ...
                results.Comparison.SimulationSeed,[21;22]);
            testCase.verifyEqual( ...
                results.Comparison.AllocatorSeed,[221;222]);
        end

        function testEveryNamedAllocatorRuns(testCase)
            [results,~] = testCase.executeExample( ...
                "v7_03_compare_named_allocators.m");

            expectedTypes = [ ...
                "ReuseDistance"; ...
                "MaximumReuseDistance"; ...
                "MinimumReusePower"; ...
                "ThreeGppAutonomous"; ...
                "RandomBenchmark"; ...
                "OrderedBenchmark"];
            testCase.verifyEqual(results.Allocators.Allocator,expectedTypes);
            testCase.verifyEqual( ...
                results.Allocators.NetworkSliceId, ...
                repmat("global",numel(expectedTypes),1));
            testCase.verifyEqual( ...
                results.Allocators.Category, ...
                ["Centralized";"Centralized";"Centralized"; ...
                    "Autonomous";"Benchmark";"Benchmark"]);
        end

        function testPositionErrorsProduceOrderedTrace(testCase)
            [results,outputDirectory] = testCase.executeExample( ...
                "v7_04_apply_position_errors.m");

            testCase.verifyEqual(results.Modules.ModuleIndex,[1;2;3]);
            testCase.verifyGreaterThan( ...
                results.Modules.ActiveRowCount(1),0);
            testCase.verifyGreaterThan( ...
                results.Modules.ActiveRowCount(2),0);
            testCase.verifyNotEmpty(results.Trajectory);
            testCase.verifyNotEmpty(dir(fullfile( ...
                outputDirectory,"position_error_trace_*.csv")));
        end

        function testOptionalOutputsAreReadable(testCase)
            [results,~] = testCase.executeExample( ...
                "v7_05_inspect_output_artifacts.m");

            expectedArtifacts = [ ...
                "simulation_summary.json"; ...
                "vehicle_kinematics.csv"; ...
                "average_neighbor_count_over_time_cv2x.csv"; ...
                "controller_allocation_summary.csv"; ...
                "packet_fates_000001.csv"; ...
                "packet_reception_ratio_LTE.csv"];
            testCase.verifyTrue(all(ismember( ...
                expectedArtifacts,results.Artifacts.Artifact)));
            testCase.verifyNotEmpty(results.PacketReceptionRatio);
            testCase.verifyEqual( ...
                results.Summary.SchemaVersion,2);
        end

        function testSweepUsesOneDirectoryPerCase(testCase)
            [results,outputDirectory] = testCase.executeExample( ...
                "v7_06_run_density_sweep.m");

            testCase.verifyEqual( ...
                results.Sweep.VehicleCount,[4;8;12]);
            testCase.verifyEqual( ...
                numel(unique(results.Sweep.RunDirectory)),3);
            testCase.verifyTrue(all(arrayfun( ...
                @(directory) isfile(fullfile( ...
                    directory,"simulation_summary.json")), ...
                results.Sweep.RunDirectory)));
            testCase.verifyTrue(all(startsWith( ...
                results.Sweep.RunDirectory,outputDirectory)));
        end
    end

    methods (Access = private)
        function [results,outputDirectory] = executeExample( ...
                testCase,scriptName)
            scriptFile = fullfile( ...
                testCase.ExampleDirectory,scriptName);
            run(scriptFile);
            results = exampleResults;
            outputDirectory = string(exampleOutputDirectory);
            testCase.addTeardown(@() removeOutput(outputDirectory));
        end
    end
end

function restoreProcessState( ...
        originalPath,originalDirectory, ...
        originalStream,originalStreamState, ...
        originalWarningState,originalFigureVisibility)
close all force
path(originalPath);
cd(originalDirectory);
RandStream.setGlobalStream(originalStream);
originalStream.State = originalStreamState;
warning(originalWarningState);
set(groot,"DefaultFigureVisible",originalFigureVisibility);
end

function removeOutput(outputDirectory)
if isfolder(outputDirectory)
    rmdir(outputDirectory,"s");
end
end
