classdef V7ExamplesTest < matlab.unittest.TestCase
    %V7EXAMPLESTEST End-to-end checks for the progressive V7 examples.

    properties (SetAccess = private)
        ExampleDirectory (1,1) string
    end

    methods (TestClassSetup)
        function locateExamples(testCase)
            projectRoot = fileparts(fileparts(fileparts(fileparts( ...
                mfilename("fullpath")))));
            testCase.ExampleDirectory = fullfile( ...
                projectRoot,"examples");
        end
    end

    methods (TestMethodSetup)
        function preserveProcessState(testCase)
            originalPath = path;
            originalDirectory = string(pwd);
            originalStream = RandStream.getGlobalStream();
            originalStreamState = originalStream.State;
            originalWarningState = warning;
            originalFigureVisibility = get( ...
                groot,"DefaultFigureVisible");

            temporaryFolder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            cd(temporaryFolder.Folder);
            testCase.addTeardown(@() restoreProcessState( ...
                originalPath,originalDirectory, ...
                originalStream,originalStreamState, ...
                originalWarningState,originalFigureVisibility));

            warning( ...
                "error","v2xsim:parameters:DeprecatedV6Name");
            set(groot,"DefaultFigureVisible","off");
        end
    end

    methods (Test)
        function tutorialsAreDirectAndSelfContained(testCase)
            entries = dir(fullfile( ...
                testCase.ExampleDirectory,"*","*.m"));
            testCase.verifyNumElements(entries,17);
            tutorialFiles = string(fullfile( ...
                {entries.folder},{entries.name})).';

            for tutorialFile = tutorialFiles.'
                tutorialText = string(fileread(tutorialFile));
                testCase.verifyTrue(contains( ...
                    tutorialText,"v2xsim.runSimulation("), ...
                    "Tutorial does not call the public entrypoint: " + ...
                        tutorialFile);
                testCase.verifyFalse(contains( ...
                    tutorialText,"runV7ExampleSimulation"), ...
                    "Tutorial still uses the removed execution helper: " + ...
                    tutorialFile);
                testCase.verifyTrue(contains(tutorialText,"DeliveryPrr"), ...
                    "Tutorial does not expose delivery PRR: " + tutorialFile);
                testCase.verifyTrue(contains(tutorialText,"plot("), ...
                    "Tutorial does not display a PRR-versus-distance plot: " + ...
                    tutorialFile);
            end

            nestedMatlabFiles = dir(fullfile( ...
                testCase.ExampleDirectory,"**","*.m"));
            nestedMatlabFiles = string(fullfile( ...
                {nestedMatlabFiles.folder},{nestedMatlabFiles.name})).';
            testCase.verifyEqual(sort(nestedMatlabFiles),sort(tutorialFiles), ...
                "Each tutorial folder must contain only its tutorial .m file.");

            [requiredFiles,~] = ...
                matlab.codetools.requiredFilesAndProducts( ...
                    cellstr(tutorialFiles));
            requiredFiles = string(requiredFiles(:));
            examplePrefix = testCase.ExampleDirectory + filesep;
            exampleDependencies = requiredFiles( ...
                startsWith(requiredFiles,examplePrefix) & ...
                endsWith(requiredFiles,".m"));
            testCase.verifyEqual( ...
                sort(exampleDependencies),sort(tutorialFiles));
            testCase.verifyEmpty(which("run_first_simulation"));
        end

        function testFirstSimulationPublishesSummary(testCase)
            [results,outputDirectory] = testCase.executeExample( ...
                fullfile("01_run_first_simulation","run_first_simulation.m"));

            testCase.verifyEqual(results.Summary.SchemaVersion,2);
            testCase.verifyClass( ...
                results.SimulationResult, ...
                "v2xsim.runtime.SimulationResult");
            testCase.verifyEqual( ...
                results.SimulationResult.RunDirectory,outputDirectory);
            testCase.verifyEqual( ...
                string(results.Summary.Configuration.RadioAccessMode), ...
                "NR-V2X");
            testCase.verifyEqual( ...
                string(results.Summary.Configuration.Scenario.Type), ...
                "BidirectionalHighwayScenario");
            testCase.verifyTrue(isfile(fullfile( ...
                outputDirectory,"simulation_summary.json")));
        end

        function testTrafficRandomnessIsIndependent(testCase)
            [results,~] = testCase.executeExample( ...
                fullfile("02_reproduce_traffic","reproduce_traffic.m"));

            testCase.verifyTrue(results.TrajectoriesMatch);
            testCase.verifyEqual( ...
                results.Comparison.ScenarioSeed,[102;102]);
            testCase.verifyEqual( ...
                results.Comparison.SimulationSeed,[21;22]);
            testCase.verifyEqual( ...
                results.Comparison.AllocatorSeed,[221;222]);
        end

        function testEveryNamedAllocatorRuns(testCase)
            [results,~] = testCase.executeExample( ...
                fullfile("03_compare_named_allocators","compare_named_allocators.m"));

            expectedTypes = [ ...
                "ReuseDistance"; ...
                "MaximumReuseDistance"; ...
                "MinimumReusePower"; ...
                "SensingBased"; ...
                "Random"; ...
                "Ordered"];
            testCase.verifyEqual(results.Allocators.Allocator,expectedTypes);
            testCase.verifyEqual( ...
                results.Allocators.NetworkSliceId, ...
                repmat("global",numel(expectedTypes),1));
            testCase.verifyEqual( ...
                results.Allocators.Category, ...
                ["Centralized";"Centralized";"Centralized"; ...
                    "Autonomous";"Benchmark";"Benchmark"]);
        end

        function testPositionErrorsProduceOrderedTrace(testCase)
            [results,outputDirectory] = testCase.executeExample( ...
                fullfile("04_apply_position_errors","apply_position_errors.m"));

            testCase.verifyEqual(results.Modules.ModuleIndex,[1;2;3;4;5]);
            testCase.verifyGreaterThan( ...
                results.Modules.ActiveRowCount(1),0);
            testCase.verifyGreaterThan( ...
                results.Modules.ActiveRowCount(2),0);
            testCase.verifyTrue(any( ...
                endsWith(results.Modules.StatusEffectType, ...
                    "FalseMergePositionErrorStatusEffect")));
            packetLossRow = results.Modules.ModuleType == ...
                "v2xsim.positioning.PositionPacketLossError";
            testCase.verifyEqual(sum(packetLossRow),1);
            testCase.verifyGreaterThan( ...
                results.Modules.NetworkUpdateRowCount(packetLossRow),0);
            testCase.verifyGreaterThan( ...
                results.Modules.DroppedUpdateRowCount(packetLossRow),0);
            testCase.verifyNotEmpty(results.RouteActivity);
            testCase.verifyNotEmpty(results.Trajectory);
            testCase.verifyNotEmpty(dir(fullfile( ...
                outputDirectory,"position_error_trace_*.csv")));
        end

        function testOptionalOutputsAreReadable(testCase)
            [results,~] = testCase.executeExample( ...
                fullfile("05_inspect_output_artifacts","inspect_output_artifacts.m"));

            expectedArtifacts = [ ...
                "simulation_summary.json"; ...
                "vehicle_kinematics.csv"; ...
                "average_neighbor_count_over_time_cv2x.csv"; ...
                "controller_allocation_summary.csv"; ...
                "packet_fates_000001.csv"; ...
                "packet_reception_ratio_LTE.csv"];
            testCase.verifyTrue(all(ismember( ...
                expectedArtifacts,results.Artifacts.Artifact)));
            testCase.verifyNotEmpty(results.PacketReceptionRatio);
            testCase.verifyEqual( ...
                results.Summary.SchemaVersion,2);
        end

        function testSweepUsesOneDirectoryPerCase(testCase)
            [results,outputDirectory] = testCase.executeExample( ...
                fullfile("06_run_density_sweep","run_density_sweep.m"));

            testCase.verifyEqual( ...
                results.Sweep.VehicleCount,[200;400;600]);
            testCase.verifyEqual( ...
                numel(unique(results.Sweep.RunDirectory)),3);
            testCase.verifyTrue(all(arrayfun( ...
                @(directory) isfile(fullfile( ...
                    directory,"simulation_summary.json")), ...
                results.Sweep.RunDirectory)));
            testCase.verifyTrue(all(startsWith( ...
                results.Sweep.RunDirectory,outputDirectory)));
        end

        function testNrMode1QuickstartIsCentralized(testCase)
            [results,outputDirectory] = testCase.executeExample( ...
                fullfile("07_run_nr_mode1","run_nr_mode1.m"));

            testCase.verifyEqual( ...
                results.Overview.RadioAccessMode,["NR-V2X";"NR-V2X"]);
            testCase.verifyEqual( ...
                results.Overview.Category,["Centralized";"Centralized"]);
            testCase.verifyEqual( ...
                results.Overview.Allocator, ...
                ["MaximumReuseDistance";"MaximumReuseDistance"]);
            testCase.verifyEqual(results.Overview.AverageUeCount,[200;200]);
            testCase.verifyEqual( ...
                results.Overview.AwarenessRangeLowerBoundMeters,[0;100]);
            testCase.verifyEqual( ...
                results.Overview.AwarenessRangeUpperBoundMeters,[100;200]);
            testCase.verifyTrue(all(isfinite(results.Overview.RadioPrr)));
            testCase.verifyTrue(all(isfinite(results.Overview.BlockingRate)));
            testCase.verifyNotEmpty(results.DeliveryPrrByDistance);
            validPrr = results.DeliveryPrrByDistance.OpportunityCount > 0;
            testCase.verifyTrue(any( ...
                results.DeliveryPrrByDistance.DeliveryPrr(validPrr) < 1));
            testCase.verifyTrue(isfile(fullfile( ...
                outputDirectory,"packet_reception_ratio_5G.csv")));
        end

        function testEtsiCampaignRunsAllTrafficModels(testCase)
            [results,outputDirectory] = testCase.executeExample( ...
                fullfile("08_run_nr_mode1_etsi_campaign","run_nr_mode1_etsi_campaign.m"));

            expectedModels = [ ...
                "HighSpeedLowDensity"; ...
                "MediumSpeedMediumDensity"; ...
                "LowSpeedHighDensity"];
            testCase.verifyEqual( ...
                results.Campaign.TrafficModel,expectedModels);
            testCase.verifyEqual( ...
                results.Campaign.AverageVehicleCount,[72;126;252], ...
                AbsTol=1e-12);
            testCase.verifyTrue(all(arrayfun( ...
                @(directory) isfile(fullfile( ...
                    directory,"simulation_summary.json")), ...
                results.Campaign.RunDirectory)));
            testCase.verifyTrue(all(startsWith( ...
                results.Campaign.RunDirectory,outputDirectory)));
        end

        function testTrafficGalleryCoversEveryScenario(testCase)
            [results,~] = testCase.executeExample( ...
                fullfile("09_explore_traffic_scenarios","explore_traffic_scenarios.m"));

            expectedScenarios = [ ...
                "BrownianMotion"; ...
                "BidirectionalHighway"; ...
                "EtsiHighway"; ...
                "ExitRampHighway"; ...
                "Roundabout"];
            testCase.verifyEqual(results.Scenarios.Scenario,expectedScenarios);
            testCase.verifyGreaterThan(results.Scenarios.VehicleCount,0);
            testCase.verifyEqual(numel(results.Kinematics),5);
            testCase.verifyTrue(all(cellfun( ...
                @(rows) ~isempty(rows),results.Kinematics)));
        end

        function testNrMode2AuthorsAllOptionsAndReportsGrid(testCase)
            [results,outputDirectory] = testCase.executeExample( ...
                fullfile("10_run_nr_mode2","run_nr_mode2.m"));

            testCase.verifyEqual( ...
                results.Overview.RadioAccessMode,"NR-V2X");
            testCase.verifyEqual(results.Overview.Allocator,"SensingBased");
            testCase.verifyEqual(results.Overview.Category,"Autonomous");
            testCase.verifyEqual( ...
                results.Overview.MaximumTransmissionCount,2);
            testCase.verifyEqual( ...
                results.Grid.TotalBeaconResources, ...
                results.Grid.TimeSlots .* ...
                    results.Grid.FrequencyResources);
            testCase.verifyGreaterThan( ...
                results.Grid.BeaconPhysicalResourceBlocks,0);
            testCase.verifyTrue(isfile(fullfile( ...
                outputDirectory,"simulation_summary.json")));
        end

        function testLteModeExampleRunsMode3AndMode4(testCase)
            [results,~] = testCase.executeExample( ...
                fullfile("11_compare_lte_modes","compare_lte_modes.m"));

            testCase.verifyEqual(results.Modes.Mode,["Mode 3";"Mode 4"]);
            testCase.verifyEqual( ...
                results.Modes.Category,["Centralized";"Autonomous"]);
            testCase.verifyEqual( ...
                results.Modes.Allocator, ...
                ["MaximumReuseDistance";"SensingBased"]);
        end

        function testIeeeExampleCoversPhyAndRepetition(testCase)
            [results,~] = testCase.executeExample( ...
                fullfile("12_compare_ieee80211p","compare_ieee80211p.m"));

            testCase.verifyEqual(height(results.Cases),3);
            testCase.verifyTrue(any( ...
                results.Cases.PhysicalLayer == "LteSurrogate"));
            testCase.verifyTrue(any( ...
                results.Cases.RepetitionMode == "Probabilistic"));
        end

        function testCoexistenceExampleRunsEveryMethod(testCase)
            [results,~] = testCase.executeExample( ...
                fullfile("13_compare_coexistence_methods","compare_coexistence_methods.m"));

            testCase.verifyEqual( ...
                results.Methods.Method, ...
                ["Standard";"MethodA";"MethodB";"MethodC";"MethodF"]);
        end

        function testChannelExampleCoversThresholdAndCurves(testCase)
            [results,~] = testCase.executeExample( ...
                fullfile("14_compare_channel_models","compare_channel_models.m"));

            testCase.verifyTrue(any(results.Cases.PacketError == "Curves"));
            testCase.verifyTrue(any(results.Cases.Rayleigh));
            testCase.verifyTrue(any(results.Cases.PathLoss == "SingleSlope"));
        end

        function testApplicationExampleCoversEtsiCamAndDcc(testCase)
            [results,~] = testCase.executeExample( ...
                fullfile("15_compare_application_traffic","compare_application_traffic.m"));

            testCase.verifyEqual( ...
                results.Cases.GenerationMode,["Periodic";"EtsiCam"]);
            testCase.verifyEqual( ...
                results.Cases.CongestionControl,[false;true]);
        end

        function testRoadsideUnitProducesDirectedFates(testCase)
            [results,~] = testCase.executeExample( ...
                fullfile("16_run_roadside_unit","run_roadside_unit.m"));

            testCase.verifyNotEmpty(results.RoadsideUnitFates);
            testCase.verifyTrue(all( ...
                results.RoadsideUnitFates.TransmitterUeId == "rsu-west" | ...
                results.RoadsideUnitFates.ReceiverUeId == "rsu-west"));
        end

        function testAnalysisExampleReducesTerminalFates(testCase)
            [results,~] = testCase.executeExample( ...
                fullfile("17_reduce_packet_fates","reduce_packet_fates.m"));

            testCase.verifyNotEmpty(results.TerminalFates);
            testCase.verifyNotEmpty(results.Curve);
            testCase.verifyTrue( ...
                isscalar(results.NormalizedPrrAuc));
        end
    end

    methods (Access = private)
        function [results,outputDirectory] = executeExample( ...
                testCase,scriptName)
            scriptFile = fullfile( ...
                testCase.ExampleDirectory,scriptName);
            run(scriptFile);
            results = exampleResults;
            outputDirectory = string(exampleOutputDirectory);
            testCase.addTeardown(@() removeOutput(outputDirectory));
        end
    end
end

function restoreProcessState( ...
        originalPath,originalDirectory, ...
        originalStream,originalStreamState, ...
        originalWarningState,originalFigureVisibility)
close all force
path(originalPath);
cd(originalDirectory);
RandStream.setGlobalStream(originalStream);
originalStream.State = originalStreamState;
warning(originalWarningState);
set(groot,"DefaultFigureVisible",originalFigureVisibility);
end

function removeOutput(outputDirectory)
if isfolder(outputDirectory)
    rmdir(outputDirectory,"s");
end
end
