function [seedResults, comparisons] = runControlledCampaign( ...
        simulatorRoot, outputDirectory, options)
%RUNCONTROLLEDCAMPAIGN Compare PRR under a vehicle-count-only load sweep.
%   Every technology, vehicle-count, and seed tuple is an independent work
%   item. Geometry, motion, packet generation, channel parameters, and
%   resource-allocation parameters remain fixed across the three loads.

arguments (Input)
    simulatorRoot (1, 1) string {mustBeNonzeroLengthText}
    outputDirectory (1, 1) string {mustBeNonzeroLengthText}
    options.Technologies (1, :) string {mustBeMember( ...
        options.Technologies, ["LTE-V2X", "NR-V2X", "80211p"])} = ...
        ["LTE-V2X", "NR-V2X", "80211p"]
    options.RandomSeeds (1, :) double { ...
        mustBeInteger, mustBePositive} = 10:29
    options.SimulationTimeSeconds (1, 1) double { ...
        mustBeReal, mustBeFinite, mustBePositive} = 2
    options.ExecutionMode (1, 1) string {mustBeMember( ...
        options.ExecutionMode, ["auto", "serial", "parallel"])} = "auto"
    options.MaxWorkers (1, 1) double { ...
        v2xsimregression.execution.mustBeWorkerLimit} = Inf
    options.BootstrapSampleCount (1, 1) double { ...
        mustBeInteger, mustBePositive} = 10000
end

arguments (Output)
    seedResults table
    comparisons table
end

if isempty(options.Technologies) || isempty(options.RandomSeeds)
    error( ...
        "v2xsimregression:density:EmptyManifest", ...
        "Technologies and RandomSeeds must both be nonempty.");
end
if numel(unique(options.Technologies)) ~= numel(options.Technologies)
    error( ...
        "v2xsimregression:density:DuplicateTechnology", ...
        "Technologies must not contain duplicates.");
end
if numel(unique(options.RandomSeeds)) ~= numel(options.RandomSeeds)
    error( ...
        "v2xsimregression:density:DuplicateRandomSeed", ...
        "RandomSeeds must not contain duplicates.");
end
if options.BootstrapSampleCount < 40
    error( ...
        "v2xsimregression:density:InsufficientBootstrapSamples", ...
        "BootstrapSampleCount must be at least 40.");
end

callerWorkingDirectory = string(pwd);
simulatorRoot = absolutePath( ...
    simulatorRoot, callerWorkingDirectory);
outputDirectory = absolutePath( ...
    outputDirectory, callerWorkingDirectory);
configurationFile = fullfile( ...
    simulatorRoot, "tests", "+v2xsimtest", "+fixtures", ...
    "config", "EtsiHighwayMediumMode1.toml");
validateSimulator(simulatorRoot, configurationFile);

originalPath = path;
originalStream = RandStream.getGlobalStream();
originalStreamState = originalStream.State;
originalWarningState = warning;
environmentCleanup = onCleanup(@() restoreEnvironment( ...
    originalPath, originalStream, originalStreamState, ...
    originalWarningState));

addpath(fullfile(simulatorRoot, "src"));
addpath(fullfile(simulatorRoot, "lib", "matlab-toml"));
if ~isfolder(outputDirectory)
    [created, message] = mkdir(outputDirectory);
    if ~created
        error( ...
            "v2xsimregression:density:OutputDirectoryCreationFailed", ...
            "Could not create output directory ""%s"": %s", ...
            outputDirectory, message);
    end
end

manifest = createManifest( ...
    configurationFile, outputDirectory, options.Technologies, ...
    options.RandomSeeds, options.SimulationTimeSeconds);
workItems = arrayfun(@(workItem) {workItem}, manifest);
labels = string({manifest.Label});
additionalPaths = [ ...
    fullfile(simulatorRoot, "regression-tests"), ...
    fullfile(simulatorRoot, "src"), ...
    fullfile(simulatorRoot, "lib", "matlab-toml")];
resultCells = v2xsimregression.execution.runWorkItems( ...
    workItems, @runWorkItem, ...
    Labels=labels, ...
    ExecutionMode=options.ExecutionMode, ...
    MaxWorkers=options.MaxWorkers, ...
    AdditionalPaths=additionalPaths, ...
    CollectAllFailures=true);
seedResults = vertcat(resultCells{:});
comparisons = compareBookends( ...
    seedResults, options.Technologies, ...
    options.RandomSeeds, options.BootstrapSampleCount);

environmentCleanup; %#ok<VUNUS>
end

function manifest = createManifest( ...
        configurationFile, outputDirectory, technologies, ...
        randomSeeds, simulationTimeSeconds)
vehicleCounts = [72, 126, 252];
manifest = repmat(struct( ...
    "ConfigurationFile", configurationFile, ...
    "OutputDirectory", "", ...
    "Technology", "", ...
    "VehicleCount", 0, ...
    "RandomSeed", 0, ...
    "SimulationTimeSeconds", simulationTimeSeconds, ...
    "Label", ""), ...
    1, numel(technologies) .* numel(vehicleCounts) .* ...
        numel(randomSeeds));

workIndex = 0;
for technology = technologies
    technologyDirectory = technologyPathToken(technology);
    for vehicleCount = vehicleCounts
        for randomSeed = randomSeeds
            workIndex = workIndex + 1;
            label = compose( ...
                "%s/vehicles-%d/seed-%d", ...
                technology, vehicleCount, randomSeed);
            manifest(workIndex).OutputDirectory = fullfile( ...
                outputDirectory, technologyDirectory, ...
                compose("vehicles-%d", vehicleCount), ...
                compose("seed-%d", randomSeed));
            manifest(workIndex).Technology = technology;
            manifest(workIndex).VehicleCount = vehicleCount;
            manifest(workIndex).RandomSeed = randomSeed;
            manifest(workIndex).Label = label;
        end
    end
end
end

function result = runWorkItem(workItem)
radio = radioPatch(workItem.Technology);
patchData = struct( ...
    Simulation=struct( ...
        RandomSeed=workItem.RandomSeed, ...
        DurationSeconds=workItem.SimulationTimeSeconds), ...
    Scenario=struct( ...
        Type="BidirectionalHighway", ...
        BidirectionalHighway=struct( ...
            RandomSeed=workItem.RandomSeed, ...
            VehicleCount=workItem.VehicleCount, ...
            NLanes=3, ...
            LaneWidth=4, ...
            RoadLength=2100, ...
            CentralDividerWidth=0, ...
            MeanVehicleSpeed=140 ./ 3.6, ...
            VehicleSpeedStandardDeviation=0, ...
            RerollSpeedOnWrapAround=false)), ...
    Application=struct( ...
        ResourceReservationIntervalSeconds=0.1, ...
        PacketGeneration=struct( ...
            IntervalVariationSeconds=0, ...
            IntervalSeconds=0.1, ...
            RandomComponentMeanSeconds=0)), ...
    Radio=radio, ...
    Awareness=struct(RangesMeters=300), ...
    Outputs=struct( ...
        PacketReceptionRatio=struct( ...
            Enabled=true, ...
            DistanceBinWidthMeters=25), ...
        UpdateDelay=struct(Enabled=false), ...
        PacketDelay=struct(Enabled=false), ...
        DataAge=struct(Enabled=false), ...
        WirelessBlindSpot=struct(Enabled=false), ...
        AverageNeighborCount=struct(Enabled=false), ...
        ChannelBusyRatio=struct(Enabled=false)));
if workItem.Technology ~= "80211p"
    patchData.ResourceAllocation = struct( ...
        Type="SensingBased", ...
        RandomSeed=workItem.RandomSeed, ...
        SensingBased=struct(KeepResourceProbability=0.4));
end
template = v2xsim.config.load(workItem.ConfigurationFile);
configuration = template.resolve( ...
    Patch=v2xsim.config.patch(patchData)); %#ok<NASGU>
evalc("v2xsim.runSimulation(configuration," + ...
    "OutputDirectory=workItem.OutputDirectory," + ...
    "RunLabel=workItem.Label);");

if ~isfile(fullfile( ...
        workItem.OutputDirectory, "simulation_summary.json"))
    error( ...
        "v2xsimregression:density:MissingSimulationSummary", ...
        "Simulation did not publish a summary for %s.", ...
        workItem.Label);
end

prrFile = fullfile( ...
    workItem.OutputDirectory, ...
    prrFilename(workItem.Technology));
[normalizedPrrAuc, counts] = scorePrrFile(prrFile, 300);
result = table( ...
    workItem.Technology, workItem.VehicleCount, ...
    workItem.RandomSeed, workItem.SimulationTimeSeconds, ...
    normalizedPrrAuc, counts(1), counts(2), counts(3), ...
    sum(counts), workItem.OutputDirectory, ...
    VariableNames=[ ...
        "Technology", "VehicleCount", "RandomSeed", ...
        "SimulationTimeSeconds", "NormalizedPrrAuc", ...
        "CorrectCount", "ErrorCount", "BlockedCount", ...
        "TotalCount", "OutputDirectory"]);
end

function radio = radioPatch(technology)
switch technology
    case "LTE-V2X"
        radio = struct( ...
            Type="LteV2X", ...
            LteV2X=struct( ...
                Mcs=7, ...
                AdjacentPscchAndPsschEnabled=true));
    case "NR-V2X"
        radio = struct(Type="NrV2X", NrV2X=struct());
    case "80211p"
        radio = struct(Type="Ieee80211p", Ieee80211p=struct());
end
end

function [normalizedPrrAuc, counts] = ...
        scorePrrFile(prrFile, maximumScoreDistanceMeters)
if ~isfile(prrFile)
    error( ...
        "v2xsimregression:density:MissingPrrOutput", ...
        "Expected packet-reception output was not created: %s", ...
        prrFile);
end
prrData = readmatrix(prrFile);
if size(prrData, 2) ~= 6 || isempty(prrData)
    error( ...
        "v2xsimregression:density:InvalidPrrOutput", ...
        "Packet-reception output must contain six numeric columns: %s", ...
        prrFile);
end
if any(~isfinite(prrData(:, 1:5)), "all") || ...
        any(prrData(:, 1:5) < 0, "all")
    error( ...
        "v2xsimregression:density:InvalidPrrOutput", ...
        "Packet-reception distances and counts must be finite and nonnegative.");
end
if any(prrData(:, 2:5) ~= fix(prrData(:, 2:5)), "all")
    error( ...
        "v2xsimregression:density:InvalidPrrOutput", ...
        "Packet-reception counts must be integers.");
end
if any(prrData(:, 5) ~= sum(prrData(:, 2:4), 2))
    error( ...
        "v2xsimregression:density:InconsistentPrrCounts", ...
        "Every PRR row must satisfy total = correct + error + blocked.");
end

isScored = prrData(:, 1) > 0 & ...
    prrData(:, 1) <= maximumScoreDistanceMeters;
scored = prrData(isScored, :);
expectedDistances = (25:25:maximumScoreDistanceMeters).';
if isempty(scored) || ...
        ~isequal(scored(:, 1), expectedDistances) || ...
        any(scored(:, 5) == 0)
    error( ...
        "v2xsimregression:density:IncompletePrrCurve", ...
        "Every 25 m distance bin through %g m must contain samples.", ...
        maximumScoreDistanceMeters);
end

packetReceptionRatios = scored(:, 2) ./ scored(:, 5);
normalizedPrrAuc = trapz( ...
    [0; scored(:, 1)], ...
    [1; packetReceptionRatios]) ./ maximumScoreDistanceMeters;
counts = sum(scored(:, 2:4), 1);
end

function comparisons = compareBookends( ...
        seedResults, technologies, randomSeeds, bootstrapSampleCount)
vehicleCounts = [72, 126, 252];
comparisonCells = cell(1, numel(technologies));
for technologyIndex = 1:numel(technologies)
    technology = technologies(technologyIndex);
    scores = zeros(numel(randomSeeds), numel(vehicleCounts));
    for countIndex = 1:numel(vehicleCounts)
        selected = seedResults( ...
            seedResults.Technology == technology & ...
            seedResults.VehicleCount == vehicleCounts(countIndex), :);
        [isPresent, rowOrder] = ismember( ...
            randomSeeds(:), selected.RandomSeed);
        if ~all(isPresent)
            error( ...
                "v2xsimregression:density:UnpairedSeeds", ...
                "Technology %s does not contain every manifest seed.", ...
                technology);
        end
        scores(:, countIndex) = ...
            selected.NormalizedPrrAuc(rowOrder);
    end

    pairedDifferences = scores(:, 1) - scores(:, 3);
    bootstrapSeed = 91000 + technologyIndex;
    confidenceInterval = pairedBootstrapMeanInterval( ...
        pairedDifferences, bootstrapSampleCount, bootstrapSeed);
    comparisonCells{technologyIndex} = table( ...
        technology, numel(randomSeeds), ...
        mean(scores(:, 1)), mean(scores(:, 2)), ...
        mean(scores(:, 3)), mean(pairedDifferences), ...
        confidenceInterval(1), confidenceInterval(2), ...
        VariableNames=[ ...
            "Technology", "SeedCount", ...
            "LowDensityMeanAuc", "MediumDensityMeanAuc", ...
            "HighDensityMeanAuc", "MeanLowMinusHighAuc", ...
            "Lower95ConfidenceBound", ...
            "Upper95ConfidenceBound"]);
end
comparisons = vertcat(comparisonCells{:});
end

function confidenceInterval = pairedBootstrapMeanInterval( ...
        pairedDifferences, bootstrapSampleCount, randomSeed)
stream = RandStream("mt19937ar", Seed=randomSeed);
seedCount = numel(pairedDifferences);
sampleRows = randi( ...
    stream, seedCount, seedCount, bootstrapSampleCount);
bootstrapMeans = sort(mean(pairedDifferences(sampleRows), 1));
lowerIndex = max(1, ceil(0.025 .* bootstrapSampleCount));
upperIndex = min( ...
    bootstrapSampleCount, ...
    floor(0.975 .* bootstrapSampleCount));
confidenceInterval = [ ...
    bootstrapMeans(lowerIndex), ...
    bootstrapMeans(upperIndex)];
end

function filename = prrFilename(technology)
if technology == "LTE-V2X"
    filename = "packet_reception_ratio_LTE.csv";
elseif technology == "NR-V2X"
    filename = "packet_reception_ratio_5G.csv";
else
    filename = "packet_reception_ratio_11p.csv";
end
end

function token = technologyPathToken(technology)
token = lower(replace(technology, "-V2X", ""));
end

function validateSimulator(simulatorRoot, configurationFile)
if ~isfolder(simulatorRoot)
    error( ...
        "v2xsimregression:density:MissingSimulatorRoot", ...
        "Simulator root is not a directory: %s", simulatorRoot);
end
if ~isfile(fullfile( ...
        simulatorRoot, "src", "+v2xsim", "runSimulation.m"))
    error( ...
        "v2xsimregression:density:MissingSimulator", ...
        "v2xsim.runSimulation was not found below %s.", simulatorRoot);
end
if ~isfile(configurationFile)
    error( ...
        "v2xsimregression:density:MissingConfiguration", ...
        "Baseline configuration was not found: %s", ...
        configurationFile);
end
end

function restoreEnvironment( ...
        originalPath, originalStream, originalStreamState, ...
        originalWarningState)
path(originalPath);
RandStream.setGlobalStream(originalStream);
originalStream.State = originalStreamState;
warning(originalWarningState);
end

function pathValue = absolutePath(pathValue, baseDirectory)
if ~isAbsolutePath(pathValue)
    pathValue = fullfile(baseDirectory, pathValue);
end
end

function tf = isAbsolutePath(pathValue)
if ispc
    tf = ~isempty(regexp( ...
        pathValue, "^[A-Za-z]:[\\/]|^\\\\", "once"));
else
    tf = startsWith(pathValue, "/");
end
end
