classdef RunWorkItemsTest < matlab.unittest.TestCase
    %RUNWORKITEMSTEST Contracts for regression campaign scheduling.

    methods (Test)
        function testSerialExecutionPreservesOrderAndEnvironment(testCase)
            originalPath = path;
            originalWorkingDirectory = string(pwd);
            originalStream = RandStream.getGlobalStream();
            originalState = originalStream.State;
            warningIdentifier = ...
                "v2xsimregression:test:EnvironmentMutation";
            originalWarning = warning("query", warningIdentifier);
            environmentVariableName = ...
                "V2XSIM_RUN_WORK_ITEMS_TEST_VALUE";
            originalEnvironmentValue = getenv(environmentVariableName);
            testCleanup = onCleanup(@() restoreTestEnvironment( ...
                originalPath, originalWorkingDirectory, ...
                originalStream, originalState, ...
                originalWarning, environmentVariableName, ...
                originalEnvironmentValue));
            warning("on", warningIdentifier);
            setenv(environmentVariableName, "original-value");

            workItems = num2cell([4, 1, 3, 2]);
            outputs = v2xsimregression.execution.runWorkItems( ...
                workItems, @mutateEnvironmentAndSquare, ...
                ExecutionMode="serial", ...
                EnvironmentVariableNames=environmentVariableName);

            testCase.verifyEqual(cell2mat(outputs), [16, 1, 9, 4]);
            testCase.verifyEqual(string(pwd), originalWorkingDirectory);
            testCase.verifyEqual(path, originalPath);
            testCase.verifyTrue( ...
                isequal(RandStream.getGlobalStream(), originalStream));
            testCase.verifyEqual(originalStream.State, originalState);
            testCase.verifyEqual( ...
                string(warning("query", warningIdentifier).state), "on");
            testCase.verifyEqual( ...
                string(getenv(environmentVariableName)), ...
                "original-value");

            testCleanup; %#ok<VUNUS>
        end

        function testWorkItemFailureIncludesLabelAndCause(testCase)
            try
                v2xsimregression.execution.runWorkItems( ...
                    {17}, @failWorkItem, ...
                    Labels="seed-17", ExecutionMode="serial");
                testCase.assertFail("The work item should have failed.");
            catch exception
                testCase.verifyEqual( ...
                    string(exception.identifier), ...
                    "v2xsimregression:execution:WorkItemFailed");
                testCase.verifySubstring(exception.message, "seed-17");
                testCase.verifyNumElements(exception.cause, 1);
                testCase.verifyEqual( ...
                    string(exception.cause{1}.identifier), ...
                    "v2xsimregression:test:ExpectedFailure");
            end
        end

        function testWrongLabelCountIsRejected(testCase)
            testCase.verifyError( ...
                @() v2xsimregression.execution.runWorkItems( ...
                    {1, 2}, @identity, Labels="one", ...
                    ExecutionMode="serial"), ...
                "v2xsimregression:execution:WrongLabelCount");
        end

        function testInvalidEnvironmentVariableNameIsRejected(testCase)
            testCase.verifyError( ...
                @() v2xsimregression.execution.runWorkItems( ...
                    {1}, @identity, ExecutionMode="serial", ...
                    EnvironmentVariableNames=""), ...
                "v2xsimregression:execution:" + ...
                    "InvalidEnvironmentVariableName");
        end

        function testAdditionalPathsAreScopedToEachWorkItem(testCase)
            additionalPath = createAdditionalPathProbe(testCase);
            originalPath = path;

            outputs = v2xsimregression.execution.runWorkItems( ...
                {4,1}, @callAdditionalPathProbe, ...
                ExecutionMode="serial", ...
                AdditionalPaths=additionalPath);

            testCase.verifyEqual(cell2mat(outputs),[104 101]);
            testCase.verifyEqual(path,originalPath);
            testCase.verifyEmpty(which("v2xsimAdditionalPathProbe"));
        end

        function testInvalidAdditionalPathIsRejected(testCase)
            testCase.verifyError( ...
                @() v2xsimregression.execution.runWorkItems( ...
                    {1}, @identity, ExecutionMode="serial", ...
                    AdditionalPaths=""), ...
                "v2xsimregression:execution:InvalidAdditionalPath");
        end

        function testCollectAllFailuresReportsEveryLabelInOrder(testCase)
            try
                v2xsimregression.execution.runWorkItems( ...
                    num2cell(1:4), @failOddWorkItems, ...
                    Labels="item-" + string(1:4), ...
                    ExecutionMode="serial", ...
                    CollectAllFailures=true);
                testCase.assertFail("Odd work items should have failed.");
            catch exception
                testCase.verifyEqual( ...
                    string(exception.identifier), ...
                    "v2xsimregression:execution:MultipleWorkItemsFailed");
                testCase.verifyNumElements(exception.cause, 2);
                testCase.verifySubstring( ...
                    exception.cause{1}.message, "item-1");
                testCase.verifySubstring( ...
                    exception.cause{2}.message, "item-3");
                testCase.verifyEqual( ...
                    string(exception.cause{1}.cause{1}.identifier), ...
                    "v2xsimregression:test:ExpectedFailure");
                testCase.verifyEqual( ...
                    string(exception.cause{2}.cause{1}.identifier), ...
                    "v2xsimregression:test:ExpectedFailure");
            end
        end

        function testFailureRestoresDeclaredEnvironment(testCase)
            warningIdentifier = ...
                "v2xsimregression:test:EnvironmentMutation";
            originalPath = path;
            originalWorkingDirectory = string(pwd);
            originalStream = RandStream.getGlobalStream();
            originalStreamState = originalStream.State;
            originalWarning = warning("query", warningIdentifier);
            environmentVariableName = ...
                "V2XSIM_RUN_WORK_ITEMS_TEST_VALUE";
            originalEnvironmentValue = getenv(environmentVariableName);
            testCleanup = onCleanup(@() restoreTestEnvironment( ...
                originalPath, originalWorkingDirectory, ...
                originalStream, originalStreamState, ...
                originalWarning, environmentVariableName, ...
                originalEnvironmentValue));
            warning("on", warningIdentifier);
            setenv(environmentVariableName, "before-failure");

            testCase.verifyError( ...
                @() v2xsimregression.execution.runWorkItems( ...
                    {1}, @mutateEnvironmentAndFail, ...
                    ExecutionMode="serial", ...
                    EnvironmentVariableNames=environmentVariableName), ...
                "v2xsimregression:execution:WorkItemFailed");
            testCase.verifyEqual(string(pwd), originalWorkingDirectory);
            testCase.verifyEqual(path, originalPath);
            testCase.verifyTrue( ...
                isequal(RandStream.getGlobalStream(), originalStream));
            testCase.verifyEqual( ...
                originalStream.State, originalStreamState);
            testCase.verifyEqual( ...
                string(warning("query", warningIdentifier).state), "on");
            testCase.verifyEqual( ...
                string(getenv(environmentVariableName)), ...
                "before-failure");

            testCleanup; %#ok<VUNUS>
        end

        function testInvalidWorkerLimitIsRejected(testCase)
            testCase.verifyError( ...
                @() v2xsimregression.execution.mustBeWorkerLimit(0), ...
                "v2xsimregression:execution:InvalidMaxWorkers");
            testCase.verifyError( ...
                @() v2xsimregression.execution.mustBeWorkerLimit(1.5), ...
                "v2xsimregression:execution:InvalidMaxWorkers");
            testCase.verifyError( ...
                @() v2xsimregression.execution.mustBeWorkerLimit(-Inf), ...
                "v2xsimregression:execution:InvalidMaxWorkers");
            v2xsimregression.execution.mustBeWorkerLimit(Inf);
            v2xsimregression.execution.mustBeWorkerLimit(2);
        end

        function testParallelExecutionPreservesOrder(testCase)
            testCase.assumeTrue( ...
                ~isempty(ver("parallel")) && ...
                license("test", "Distrib_Computing_Toolbox"), ...
                "Parallel Computing Toolbox is unavailable.");

            originalPool = gcp("nocreate");
            testCase.assumeTrue( ...
                isempty(originalPool) || ...
                isa(originalPool,"parallel.ProcessPool"), ...
                "The caller owns a non-process parallel pool.");
            additionalPath = createAdditionalPathProbe(testCase);
            outputs = v2xsimregression.execution.runWorkItems( ...
                num2cell([4, 1, 3, 2]), @callAdditionalPathProbe, ...
                ExecutionMode="parallel", MaxWorkers=2, ...
                AdditionalPaths=additionalPath);

            testCase.verifyEqual( ...
                cell2mat(outputs), [104, 101, 103, 102]);
            if isempty(originalPool)
                testCase.verifyEmpty(gcp("nocreate"), ...
                    "A scheduler-owned process pool must be closed.");
            else
                testCase.verifyTrue(isvalid(originalPool), ...
                    "A caller-owned pool must remain open.");
            end
        end

        function testExplicitParallelModeRequiresToolbox(testCase)
            testCase.assumeFalse( ...
                ~isempty(ver("parallel")) && ...
                license("test", "Distrib_Computing_Toolbox"), ...
                "Parallel Computing Toolbox is available.");

            testCase.verifyError( ...
                @() v2xsimregression.execution.runWorkItems( ...
                    {1, 2}, @identity, ExecutionMode="parallel"), ...
                "v2xsimregression:execution:ParallelUnavailable");
        end
    end
end

function output = identity(input)
output = input;
end

function output = callAdditionalPathProbe(input)
probe = str2func("v2xsimAdditionalPathProbe");
output = probe(input);
end

function additionalPath = createAdditionalPathProbe(testCase)
temporaryFolder = testCase.applyFixture( ...
    matlab.unittest.fixtures.TemporaryFolderFixture);
additionalPath = string(temporaryFolder.Folder);
functionFile = fullfile( ...
    additionalPath,"v2xsimAdditionalPathProbe.m");
writelines( ...
    [ ...
        "function output = v2xsimAdditionalPathProbe(input)"; ...
        "output = input + 100;"; ...
        "end"], ...
    functionFile);
end

function output = mutateEnvironmentAndSquare(input)
addpath(tempdir);
cd(tempdir);
RandStream.setGlobalStream(RandStream("mrg32k3a", Seed=input));
warning("off", "v2xsimregression:test:EnvironmentMutation");
setenv("V2XSIM_RUN_WORK_ITEMS_TEST_VALUE", "mutated-value");
output = input .^ 2;
end

function output = failOddWorkItems(input)
if mod(input, 2) == 1
    failWorkItem(input);
end
output = input;
end

function mutateEnvironmentAndFail(~)
addpath(tempdir);
cd(tempdir);
RandStream.setGlobalStream(RandStream("mrg32k3a",Seed=911));
warning("off", "v2xsimregression:test:EnvironmentMutation");
setenv("V2XSIM_RUN_WORK_ITEMS_TEST_VALUE", "failure-value");
failWorkItem([]);
end

function output = failWorkItem(~) %#ok<STOUT>
error( ...
    "v2xsimregression:test:ExpectedFailure", ...
    "Expected scheduler test failure.");
end

function restoreTestEnvironment( ...
        pathValue, workingDirectory, stream, streamState, warningState, ...
        environmentVariableName, environmentVariableValue)
cd(workingDirectory);
path(pathValue);
RandStream.setGlobalStream(stream);
stream.State = streamState;
warning(warningState);
setenv(environmentVariableName, environmentVariableValue);
end
