function meanMagnitudeMeters = falseRouteMeanMagnitudeAtFullScale( ...
        roadLengthMeters, laneWidthMeters, mergeDistanceMeters)
%FALSEROUTEMEANMAGNITUDEATFULLSCALE Analytic mean active route error.
%   The result assumes vehicles are sampled uniformly over the post-fork
%   half-road and the route displacement uses the ramp highway's smooth
%   merge connector.

arguments (Input)
    roadLengthMeters double ...
        {mustBeReal, mustBeFinite, mustBePositive}
    laneWidthMeters double ...
        {mustBeReal, mustBeFinite, mustBeNonnegative}
    mergeDistanceMeters double ...
        {mustBeReal, mustBeFinite, mustBeNonnegative}
end

if ~isequal( ...
        size(roadLengthMeters), ...
        size(laneWidthMeters), ...
        size(mergeDistanceMeters))
    error( ...
        "v2xsim:positioning:calibration:IncompatibleSizes", ...
        "Road length, lane width, and merge distance must have " + ...
        "identical sizes.");
end
if any(mergeDistanceMeters > roadLengthMeters ./ 2, "all")
    error( ...
        "v2xsim:positioning:calibration:InvalidMergeDistance", ...
        "Merge distance cannot exceed half of the road length.");
end

meanMagnitudeMeters = ...
    roadLengthMeters ./ 4 + ...
    laneWidthMeters .* ...
        (1 - mergeDistanceMeters ./ roadLengthMeters);
end
