function scale = falseRouteDisplacementScale( ...
        targetMeanMagnitudeMeters, roadLengthMeters, ...
        laneWidthMeters, mergeDistanceMeters)
%FALSEROUTEDISPLACEMENTSCALE Scale full route error to a target mean.

arguments (Input)
    targetMeanMagnitudeMeters double ...
        {mustBeReal, mustBeFinite, mustBeNonnegative}
    roadLengthMeters double ...
        {mustBeReal, mustBeFinite, mustBePositive}
    laneWidthMeters double ...
        {mustBeReal, mustBeFinite, mustBeNonnegative}
    mergeDistanceMeters double ...
        {mustBeReal, mustBeFinite, mustBeNonnegative}
end

fullScaleMean = v2xsim.positioning.calibration. ...
    falseRouteMeanMagnitudeAtFullScale( ...
        roadLengthMeters, laneWidthMeters, mergeDistanceMeters);
if ~isequal(size(targetMeanMagnitudeMeters), size(fullScaleMean))
    error( ...
        "v2xsim:positioning:calibration:IncompatibleSizes", ...
        "Target mean magnitude and geometry inputs must have " + ...
        "identical sizes.");
end

scale = targetMeanMagnitudeMeters ./ fullScaleMean;
if any(scale > 1, "all")
    error( ...
        "v2xsim:positioning:calibration:TargetExceedsFullScale", ...
        "Target mean magnitude cannot exceed the full-scale route " + ...
        "error mean.");
end
end
