classdef AutonomousAllocationContext < ...
        v2xsim.resource.ResourceAllocationContext
    %AUTONOMOUSALLOCATIONCONTEXT UE-local observations for an allocator.

    properties (SetAccess = immutable)
        SensingSnapshot (1, 1) v2xsim.resource.SensingSnapshot
    end

    methods
        function obj = AutonomousAllocationContext( ...
                networkSliceId, ueIds, currentSlot, ...
                newPacketMask, eligibilityMask, sensingSnapshot, ...
                selectionOriginSlot)
            arguments (Input)
                networkSliceId (1, 1) v2xsim.network.NetworkSliceId
                ueIds string
                currentSlot (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeInteger, ...
                    mustBeNonnegative}
                newPacketMask logical
                eligibilityMask (:, :) logical
                sensingSnapshot (1, 1) ...
                    v2xsim.resource.SensingSnapshot
                selectionOriginSlot double = []
            end

            obj = obj@v2xsim.resource.ResourceAllocationContext( ...
                networkSliceId, ueIds, currentSlot, ...
                newPacketMask, eligibilityMask,selectionOriginSlot);

            if sensingSnapshot.NetworkSliceId ~= networkSliceId
                error( ...
                    "v2xsim:resource:NetworkSliceMismatch", ...
                    "The sensing snapshot and allocation context must " + ...
                    "belong to the same network slice.");
            end
            if ~isequal(sensingSnapshot.UeIds, obj.UeIds) || ...
                    size(sensingSnapshot.EnergyWattsPerMHz, 2) ~= ...
                    size(obj.EligibilityMask, 2)
                error( ...
                    "v2xsim:resource:AutonomousContextSizeMismatch", ...
                    "The sensing snapshot must align with the context " + ...
                    "UE order and resource count.");
            end

            obj.SensingSnapshot = sensingSnapshot;
        end
    end
end
