function allocator = createAllocator(simParams,phyParams,appParams)
%CREATEALLOCATOR Compose one named allocator for the global slice.
%   This is the only algorithm-selection branch in the runtime.

arguments (Input)
    simParams (1,1) struct
    phyParams (1,1) struct
    appParams (1,1) struct
end

grid = simParams.brResourceGrid;
seed = simParams.resourceAllocationRandomSeed;
type = simParams.resourceAllocationType;

switch type
    case "ReuseDistance"
        allocator = v2xsim.resource.ReuseDistanceAllocator( ...
            grid,seed,round( ...
                simParams.Treassign / appParams.allocationPeriod), ...
            phyParams.Rreuse);
    case "MaximumReuseDistance"
        diagnosticsEnabled = false;
        if isfield(simParams,"controllerDiagnosticsEnabled")
            diagnosticsEnabled = ...
                simParams.controllerDiagnosticsEnabled;
        end
        allocator = ...
            v2xsim.resource.MaximumReuseDistanceAllocator( ...
                grid,seed, ...
                round( ...
                    simParams.Treassign / ...
                    appParams.allocationPeriod), ...
                DiagnosticsEnabled=diagnosticsEnabled);
    case "MinimumReusePower"
        allocator = v2xsim.resource.MinimumReusePowerAllocator( ...
            grid,seed,round( ...
                simParams.Treassign / appParams.allocationPeriod), ...
            simParams.knownShadowing);
    case "ThreeGppAutonomous"
        [minimumCounter,maximumCounter] = ...
            reselectionCounterRange( ...
                appParams.allocationPeriod,simParams);
        allocator = v2xsim.resource.ThreeGppAutonomousAllocator( ...
            grid,seed,phyParams.cv2xNumberOfReplicasMax, ...
            MinimumReselectionCounter=minimumCounter, ...
            MaximumReselectionCounter=maximumCounter, ...
            KeepResourceProbability=simParams.probResKeep, ...
            MaximumConsecutiveReservationIntervals= ...
                simParams.resourceAllocation.Autonomous. ...
                MaximumConsecutiveReservationIntervals, ...
            MinimumCandidateFraction= ...
                simParams.ratioSelectedAutonomousMode, ...
            L2CandidateFraction=simParams.ratioSelectedL2, ...
            L2RankingEnabled=simParams.L2active, ...
            DynamicSchedulingEnabled=simParams.dynamicScheduling, ...
            ResourceReevaluationEnabled= ...
                simParams.resourceReEvaluation, ...
            ReevaluateAfterSkippedTransmissionEnabled= ...
                simParams.reEvalAfterEmptyResource, ...
            SensingThresholdWatts= ...
                simParams.powerThresholdAutonomous, ...
            IsNr=simParams.mode5G == constants.MODE_5G);
    case "RandomBenchmark"
        allocator = v2xsim.resource.RandomBenchmarkAllocator( ...
            grid,seed,phyParams.cv2xNumberOfReplicasMax);
    case "OrderedBenchmark"
        allocator = v2xsim.resource.OrderedBenchmarkAllocator(grid,seed);
    otherwise
        error( ...
            "v2xsim:resource:UnknownAllocatorType", ...
            "Unknown resource allocator type ""%s"".",type);
end
end

function [minimumCounter,maximumCounter] = ...
        reselectionCounterRange(reservationIntervalSeconds,simParams)
if reservationIntervalSeconds >= 0.1
    minimumCounter = 5;
    maximumCounter = 15;
elseif reservationIntervalSeconds >= 0.05
    minimumCounter = 10;
    maximumCounter = 30;
else
    minimumCounter = 25;
    maximumCounter = 75;
end

if simParams.minRandValueMode4 ~= -1
    minimumCounter = simParams.minRandValueMode4;
end
if simParams.maxRandValueMode4 ~= -1
    maximumCounter = simParams.maxRandValueMode4;
end
if maximumCounter <= minimumCounter
    error( ...
        "v2xsim:resource:InvalidReselectionCounter", ...
        "The maximum reselection counter must exceed the minimum.");
end
end
