function reuseDistanceMeters = deriveReuseDistanceMeters( ...
        radioPlan, channelPlan, awarenessPlan, reuseMarginMeters)
%DERIVEREUSEDISTANCEMETERS Derive controlled reuse distance from link budget.
%   This is a pure V7 translation of the controlled-allocation derivation
%   historically performed by deriveRanges. Automatic MCS/PER threshold
%   resolution and variable-density beacon bandwidth must be compiled
%   before this boundary; the helper rejects those unresolved cases rather
%   than approximating a scientifically meaningful distance.

arguments (Input)
    radioPlan (1, 1) struct
    channelPlan (1, 1) struct
    awarenessPlan (1, 1) struct
    reuseMarginMeters (1, 1) double ...
        {mustBeReal, mustBeFinite, mustBeNonnegative}
end
arguments (Output)
    reuseDistanceMeters (1, 1) double
end

if ~radioPlan.FixedPowerDensityEnabled
    error( ...
        "v2xsim:resource:ReuseDistanceLinkBudgetUnavailable", ...
        "ReuseDistance with variable transmit-power density requires " + ...
        "a compiled beacon-resource bandwidth.");
end
if ~isfield(channelPlan.PacketError, ...
        "SidelinkLosThresholdDb")
    error( ...
        "v2xsim:resource:ReuseDistanceLinkBudgetUnavailable", ...
        "ReuseDistance requires a compiled sidelink LOS SINR " + ...
        "threshold; automatic MCS/PER resolution is not available " + ...
        "at the allocator factory boundary.");
end

awarenessRangeMeters = max(awarenessPlan.RangesMeters, [], "all");
sinrThreshold = ...
    db2pow(channelPlan.PacketError.SidelinkLosThresholdDb);
transmitPowerDensityDbmPerMHz = ...
    radioPlan.TransmitPowerDbm + ...
    radioPlan.TransmitAntennaGainDb - ...
    10 * log10(radioPlan.BandwidthMHz);
transmitPowerDensityWattsPerMHz = ...
    db2pow(transmitPowerDensityDbmPerMHz - 30);
receiveGain = db2pow(radioPlan.ReceiveAntennaGainDb);

% Thermal noise density follows the simulator's established 290 K
% reference and 1 MHz integration bandwidth.
boltzmannConstantJoulesPerKelvin = 1.38e-23;
referenceTemperatureKelvin = 290;
noiseWattsPerMHz = ...
    boltzmannConstantJoulesPerKelvin * ...
    referenceTemperatureKelvin * 1e6 * ...
    db2pow(radioPlan.ReceiverNoiseFigureDb);

[farReferenceLoss, farExponent] = ...
    farPathLoss(channelPlan.PathLoss);
interferenceDistanceBase = ...
    1 / sinrThreshold - ...
    (noiseWattsPerMHz / transmitPowerDensityWattsPerMHz) * ...
    (farReferenceLoss * ...
    awarenessRangeMeters^farExponent) / receiveGain;
if interferenceDistanceBase <= 0
    error( ...
        "v2xsim:resource:AwarenessRangeExceedsLinkBudget", ...
        "The maximum awareness range exceeds the resolved sidelink " + ...
        "LOS link budget.");
end

interferenceLimitedDistance = ...
    awarenessRangeMeters + awarenessRangeMeters / ...
    interferenceDistanceBase^(1 / farExponent);
minimumReuseDistance = max( ...
    interferenceLimitedDistance, 2 * awarenessRangeMeters);
reuseDistanceMeters = minimumReuseDistance + reuseMarginMeters;
end

function [referenceLoss, exponent] = farPathLoss(pathLossPlan)
model = pathLossPlan.Model;

switch model
    case "WinnerPlusB1"
        antennaHeightMeters = 1.5;
        effectiveAntennaHeightMeters = antennaHeightMeters - 1;
        carrierFrequencyGigahertz = 5.9;
        referenceLoss = db2pow( ...
            7.56 - 34.6 * log10(effectiveAntennaHeightMeters) + ...
            2.7 * log10(carrierFrequencyGigahertz));
        exponent = 4;
    case "SingleSlope"
        referenceLoss = db2pow( ...
            pathLossPlan.ReferenceLossAtOneMeterDb);
        exponent = pathLossPlan.Exponent1;
    case "TwoSlope"
        referenceLoss = db2pow( ...
            pathLossPlan.ReferenceLossAtOneMeterDb) * ...
            pathLossPlan.BreakpointDistance1Meters^( ...
            pathLossPlan.Exponent1 - pathLossPlan.Exponent2);
        exponent = pathLossPlan.Exponent2;
    case "ThreeSlope"
        referenceLoss = db2pow( ...
            pathLossPlan.ReferenceLossAtOneMeterDb) * ...
            pathLossPlan.BreakpointDistance1Meters^( ...
            pathLossPlan.Exponent1 - pathLossPlan.Exponent2) * ...
            pathLossPlan.BreakpointDistance2Meters^( ...
            pathLossPlan.Exponent2 - pathLossPlan.Exponent3);
        exponent = pathLossPlan.Exponent3;
    case "NrV2VNlos"
        carrierFrequencyGigahertz = 5.9;
        referenceLoss = db2pow( ...
            pathLossPlan.ReferenceLossAtOneMeterDb + ...
            20 * log10(carrierFrequencyGigahertz));
        exponent = pathLossPlan.Exponent1;
    otherwise
        error( ...
            "v2xsim:resource:UnsupportedPathLossModel", ...
            "Unsupported path-loss model ""%s"".", model);
end
end
