classdef MaximumReuseDistanceAllocator < ...
        v2xsim.resource.ScheduledCentralizedResourceAllocator
    %MAXIMUMREUSEDISTANCEALLOCATOR Controlled farthest-neighbor reuse.

    properties (Constant)
        Type = "MaximumReuseDistance"
        Description = ...
            "Controlled allocation maximizing reuse distance"
    end

    methods
        function obj = MaximumReuseDistanceAllocator( ...
                grid,randomSeed,reassignmentCycleCount)
            arguments (Input)
                grid (1,1) v2xsim.resource.BRResourceGrid
                randomSeed (1,1) double ...
                    {mustBeInteger,mustBeNonnegative}
                reassignmentCycleCount (1,1) double ...
                    {mustBeInteger,mustBePositive}
            end

            obj = obj@v2xsim.resource. ...
                ScheduledCentralizedResourceAllocator( ...
                    grid,randomSeed,reassignmentCycleCount);
        end
    end

    methods (Access = protected)
        function [resourceIds,decisionRows] = allocate( ...
                obj,resourceIds,scheduledRows,context, ...
                allocatorRows,randomStream)
            distance = context.TrueDistanceMeters( ...
                allocatorRows,allocatorRows);
            [resourceIds,decisionRows] = v2xsim.resource.algorithm. ...
                assignByMaximumReuseDistance( ...
                    resourceIds,scheduledRows,distance, ...
                    [obj.Grid.NumberTimeSlots, ...
                    obj.Grid.NumberFrequencyResources],randomStream);
        end
    end
end
