classdef MaximumReuseDistanceAllocator < ...
        v2xsim.resource.ScheduledCentralizedResourceAllocator
    %MAXIMUMREUSEDISTANCEALLOCATOR Controlled farthest-neighbor reuse.

    properties (Constant)
        Type = "MaximumReuseDistance"
        Description = ...
            "Controlled allocation maximizing reuse distance"
    end

    properties (SetAccess = immutable)
        DiagnosticsEnabled (1,1) logical = false
    end

    methods
        function obj = MaximumReuseDistanceAllocator( ...
                grid,randomSeed,reassignmentCycleCount,options)
            arguments (Input)
                grid (1,1) v2xsim.resource.BRResourceGrid
                randomSeed (1,1) double ...
                    {mustBeInteger,mustBeNonnegative}
                reassignmentCycleCount (1,1) double ...
                    {mustBeInteger,mustBePositive}
                options.DiagnosticsEnabled (1,1) logical = false
            end

            obj = obj@v2xsim.resource. ...
                ScheduledCentralizedResourceAllocator( ...
                    grid,randomSeed,reassignmentCycleCount);
            obj.DiagnosticsEnabled = options.DiagnosticsEnabled;
        end
    end

    methods (Access = protected)
        function [resourceIds,decisionRows] = allocate( ...
                obj,resourceIds,scheduledRows,context, ...
                allocatorRows,randomStream)
            distance = context.EstimatedDistanceMeters( ...
                allocatorRows,allocatorRows);
            [resourceIds,decisionRows] = v2xsim.resource.algorithm. ...
                assignByMaximumReuseDistance( ...
                    resourceIds,scheduledRows,distance, ...
                    [obj.Grid.NumberTimeSlots, ...
                    obj.Grid.NumberFrequencyResources],randomStream, ...
                    UeIds=obj.UeIds, ...
                    EligibilityMask=context.EligibilityMask(allocatorRows,:));
        end

        function diagnostics = buildAllocationDiagnostics( ...
                obj,resourceIdsBefore,liveResourceIds, ...
                scheduledRows,decisionRows,context,allocatorRows, ...
                allocationRandomState)
            if ~obj.DiagnosticsEnabled
                diagnostics = struct();
                return
            end
            apparentDistanceMeters = ...
                context.EstimatedDistanceMeters( ...
                    allocatorRows,allocatorRows);
            trueDistanceMeters = context.TrueDistanceMeters( ...
                allocatorRows,allocatorRows);
            gridSize = [ ...
                obj.Grid.NumberTimeSlots, ...
                obj.Grid.NumberFrequencyResources];
            replayStream = RandStream( ...
                obj.RandomGeneratorType,Seed=obj.RandomSeed);
            replayStream.State = allocationRandomState;
            [replayedResourceIds,replayedDecisionRows, ...
                liveDecisionTrace,randomPlan] = ...
                v2xsim.resource.algorithm. ...
                    assignByMaximumReuseDistance( ...
                        resourceIdsBefore,scheduledRows, ...
                        apparentDistanceMeters,gridSize,replayStream, ...
                        UeIds=obj.UeIds, ...
                        EligibilityMask=context.EligibilityMask(allocatorRows,:));
            if ~isequaln(replayedResourceIds,liveResourceIds) || ...
                    ~isequal(replayedDecisionRows,decisionRows)
                error( ...
                    "v2xsim:resource:MaximumReuseShadowDiverged", ...
                    "The apparent-geometry replay diverged from the " + ...
                    "committed live allocation.");
            end
            shadowStream = RandStream( ...
                obj.RandomGeneratorType,Seed=obj.RandomSeed);
            [oracleResourceIds,oracleDecisionRows, ...
                oracleDecisionTrace] = ...
                v2xsim.resource.algorithm. ...
                    assignByMaximumReuseDistance( ...
                        resourceIdsBefore,scheduledRows, ...
                        trueDistanceMeters,gridSize,shadowStream, ...
                        UeIds=obj.UeIds,RandomPlan=randomPlan, ...
                        EligibilityMask=context.EligibilityMask(allocatorRows,:));
            if ~isequal(oracleDecisionRows,decisionRows)
                error( ...
                    "v2xsim:resource:MaximumReuseShadowDiverged", ...
                    "Live and oracle decision UE sets must be equal.");
            end

            oracleAssignments = table( ...
                obj.UeIds,oracleResourceIds, ...
                VariableNames=["UeId","ResourceIds"]);
            diagnostics = struct( ...
                "SchemaVersion",1, ...
                "Kind","MaximumReuseDistance", ...
                "UeIds",obj.UeIds, ...
                "GridSize",gridSize, ...
                "AssignmentsBefore",obj.Assignments, ...
                "OracleAssignments",oracleAssignments, ...
                "LiveDecisionTrace",liveDecisionTrace, ...
                "OracleDecisionTrace",oracleDecisionTrace);
        end

        function value = configurationMetadata(obj)
            value = configurationMetadata@v2xsim.resource.ScheduledCentralizedResourceAllocator(obj);
            value.DiagnosticsEnabled = obj.DiagnosticsEnabled;
        end
    end
end
