classdef ResourceAllocationResult
    %RESOURCEALLOCATIONRESULT Validated slice-scoped allocator output.
    %   Assignments has variables UeId and ResourceIds. Reservations has
    %   variables UeId and ResourceId.

    properties (SetAccess = immutable)
        NetworkSliceId (1, 1) v2xsim.network.NetworkSliceId
        Assignments table = table()
        DecisionUeIds (:, 1) string = strings(0, 1)
        ReassignedUeIds (:, 1) string = strings(0, 1)
        BlockedUeIds (:, 1) string = strings(0, 1)
        Reservations table = table()
    end

    methods
        function obj = ResourceAllocationResult( ...
                networkSliceId, assignments, decisionUeIds, ...
                reassignedUeIds, blockedUeIds, reservations)
            arguments (Input)
                networkSliceId (1, 1) v2xsim.network.NetworkSliceId
                assignments table
                decisionUeIds string
                reassignedUeIds string
                blockedUeIds string
                reservations table
            end

            identifierInputs = { ...
                decisionUeIds, reassignedUeIds, blockedUeIds};
            for index = 1:numel(identifierInputs)
                if ~isvector(identifierInputs{index}) && ...
                        ~isempty(identifierInputs{index})
                    error( ...
                        "v2xsim:resource:InvalidAllocationResultIdentity", ...
                        "Allocator outcome identifiers must be vectors.");
                end
            end
            decisionUeIds = decisionUeIds(:);
            reassignedUeIds = reassignedUeIds(:);
            blockedUeIds = blockedUeIds(:);
            v2xsim.resource.ResourceAllocationResult ...
                .validateAssignments(assignments);
            v2xsim.resource.validation.mustBeUeIds(decisionUeIds);
            v2xsim.resource.validation.mustBeUeIds(reassignedUeIds);
            v2xsim.resource.validation.mustBeUeIds(blockedUeIds);
            v2xsim.resource.ResourceAllocationResult ...
                .validateReservations(reservations);

            assignmentUeIds = assignments.UeId;
            if ~all(ismember(decisionUeIds, assignmentUeIds)) || ...
                    ~all(ismember(reassignedUeIds, decisionUeIds)) || ...
                    ~all(ismember(blockedUeIds, decisionUeIds)) || ...
                    any(ismember(reassignedUeIds, blockedUeIds)) || ...
                    ~all(ismember(reservations.UeId, assignmentUeIds))
                error( ...
                    "v2xsim:resource:InvalidAllocationResultIdentity", ...
                    "Decision, outcome, reservation, and assignment UE " + ...
                    "identities are inconsistent.");
            end

            obj.NetworkSliceId = networkSliceId;
            obj.Assignments = assignments;
            obj.DecisionUeIds = decisionUeIds;
            obj.ReassignedUeIds = reassignedUeIds;
            obj.BlockedUeIds = blockedUeIds;
            obj.Reservations = reservations;
        end
    end

    methods (Static)
        function assignments = emptyAssignments(resourceColumnCount)
            arguments (Input)
                resourceColumnCount (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeInteger, mustBePositive} = 1
            end

            assignments = table( ...
                strings(0, 1), nan(0, resourceColumnCount), ...
                VariableNames=["UeId", "ResourceIds"]);
        end

        function reservations = emptyReservations()
            reservations = table( ...
                strings(0, 1), zeros(0, 1), ...
                VariableNames=["UeId", "ResourceId"]);
        end
    end

    methods (Static, Access = private)
        function validateAssignments(assignments)
            expectedNames = ["UeId", "ResourceIds"];
            actualNames = string(assignments.Properties.VariableNames);
            if ~isequal(actualNames, expectedNames) || ...
                    ~isstring(assignments.UeId) || ...
                    size(assignments.UeId, 2) ~= 1 || ...
                    ~isnumeric(assignments.ResourceIds) || ...
                    size(assignments.ResourceIds, 2) == 0
                error( ...
                    "v2xsim:resource:InvalidAssignmentsSchema", ...
                    "Assignments must contain string UeId and numeric " + ...
                    "ResourceIds variables.");
            end

            v2xsim.resource.validation.mustBeUeIds(assignments.UeId);
            resourceIds = assignments.ResourceIds;
            assigned = ~isnan(resourceIds);
            if any(~isfinite(resourceIds(assigned))) || ...
                    any(resourceIds(assigned) <= 0) || ...
                    any(mod(resourceIds(assigned), 1) ~= 0)
                error( ...
                    "v2xsim:resource:InvalidResourceId", ...
                    "Assigned resource identifiers must be positive " + ...
                    "finite integers; use NaN for unassigned resources.");
            end
            if size(resourceIds,2) > 1 && any( ...
                    isnan(resourceIds(:,1:end - 1)) & ...
                    ~isnan(resourceIds(:,2:end)),"all")
                error( ...
                    "v2xsim:resource:NoncontiguousTransmissionAssignments", ...
                    "Assigned transmissions must occupy contiguous " + ...
                    "columns beginning with the primary resource.");
            end
        end

        function validateReservations(reservations)
            expectedNames = ["UeId", "ResourceId"];
            actualNames = string(reservations.Properties.VariableNames);
            if ~isequal(actualNames, expectedNames) || ...
                    ~isstring(reservations.UeId) || ...
                    size(reservations.UeId, 2) ~= 1 || ...
                    ~isnumeric(reservations.ResourceId) || ...
                    size(reservations.ResourceId, 2) ~= 1
                error( ...
                    "v2xsim:resource:InvalidReservationsSchema", ...
                    "Reservations must contain string UeId and numeric " + ...
                    "ResourceId variables.");
            end

            v2xsim.resource.validation.mustBeUeIds( ...
                reservations.UeId + "#" + string(reservations.ResourceId));
            if any(~isfinite(reservations.ResourceId)) || ...
                    any(reservations.ResourceId <= 0) || ...
                    any(mod(reservations.ResourceId, 1) ~= 0)
                error( ...
                    "v2xsim:resource:InvalidResourceId", ...
                    "Reserved resource identifiers must be positive " + ...
                    "finite integers.");
            end
            if any(ismissing(reservations.UeId)) || ...
                    any(strlength(strip(reservations.UeId)) == 0) || ...
                    any(reservations.UeId ~= strip(reservations.UeId))
                error( ...
                    "v2xsim:resource:InvalidUeIds", ...
                    "Reservation UE identifiers must be nonblank.");
            end
        end
    end
end
