classdef ThreeGppAutonomousAllocator < ...
        v2xsim.resource.AutonomousResourceAllocator
    %THREEGPPAUTONOMOUSALLOCATOR 3GPP LTE Mode 4 / NR Mode 2 SPS.

    properties (Constant)
        Type = "ThreeGppAutonomous"
        Description = ...
            "3GPP autonomous sensing-based semi-persistent scheduling"
        ContextContract = "ThreeGpp"
        UsesSelectionWindow = true
    end

    properties (SetAccess = immutable)
        MinimumReselectionCounter (1,1) double ...
            {mustBeInteger,mustBePositive} = 1
        MaximumReselectionCounter (1,1) double ...
            {mustBeInteger,mustBePositive} = 1
        KeepResourceProbability (1,1) double
        MinimumCandidateFraction (1,1) double
        L2CandidateFraction (1,1) double
        L2RankingEnabled (1,1) logical
        DynamicSchedulingEnabled (1,1) logical
        ResourceReevaluationEnabled (1,1) logical
        ReevaluateAfterSkippedTransmissionEnabled (1,1) logical
        SensingThresholdWatts (1,1) double ...
            {mustBeFinite,mustBePositive} = 1
        IsNr (1,1) logical
    end

    properties (Access = private)
        UeState table = table( ...
            strings(0,1),nan(0,1),false(0,1), ...
            VariableNames=[ ...
            "UeId","ReselectionCounter","NewDataIndicator"])
    end

    methods
        function obj = ThreeGppAutonomousAllocator( ...
                grid,randomSeed,maximumTransmissionCount,options)
            arguments (Input)
                grid (1,1) v2xsim.resource.BRResourceGrid
                randomSeed (1,1) double ...
                    {mustBeInteger,mustBeNonnegative}
                maximumTransmissionCount (1,1) double ...
                    {mustBeInteger,mustBePositive}
                options.MinimumReselectionCounter (1,1) double ...
                    {mustBeInteger,mustBePositive}
                options.MaximumReselectionCounter (1,1) double ...
                    {mustBeInteger,mustBePositive}
                options.KeepResourceProbability (1,1) double
                options.MinimumCandidateFraction (1,1) double
                options.L2CandidateFraction (1,1) double
                options.L2RankingEnabled (1,1) logical
                options.DynamicSchedulingEnabled (1,1) logical
                options.ResourceReevaluationEnabled (1,1) logical
                options.ReevaluateAfterSkippedTransmissionEnabled ...
                    (1,1) logical
                options.SensingThresholdWatts (1,1) double ...
                    {mustBeFinite,mustBePositive}
                options.IsNr (1,1) logical
            end

            if maximumTransmissionCount > 2
                error( ...
                    "v2xsim:resource:UnsupportedMultipleTransmissions", ...
                    "3GPP allocation supports at most two transmissions.");
            end
            if options.MaximumReselectionCounter < ...
                    options.MinimumReselectionCounter
                error( ...
                    "v2xsim:resource:InvalidReselectionCounter", ...
                    "MaximumReselectionCounter cannot be smaller " + ...
                    "than MinimumReselectionCounter.");
            end
            validateFraction( ...
                options.KeepResourceProbability,0,1, ...
                "KeepResourceProbability");
            validateFraction( ...
                options.MinimumCandidateFraction,0.2,1, ...
                "MinimumCandidateFraction");
            validateFraction( ...
                options.L2CandidateFraction,0,1, ...
                "L2CandidateFraction");
            if options.L2CandidateFraction == 0
                error( ...
                    "v2xsim:resource:InvalidAllocatorOption", ...
                    "L2CandidateFraction must be greater than zero.");
            end
            if options.DynamicSchedulingEnabled && ...
                    options.KeepResourceProbability ~= 0
                error( ...
                    "v2xsim:resource:InvalidKeepProbability", ...
                    "KeepResourceProbability must be zero when every " + ...
                    "packet reselects.");
            end
            reevaluationConfigured = ...
                options.ResourceReevaluationEnabled || ...
                options.ReevaluateAfterSkippedTransmissionEnabled;
            if reevaluationConfigured && ~options.IsNr
                error( ...
                    "v2xsim:resource:NrOptionForLte", ...
                    "Resource reevaluation options require NR-V2X.");
            end
            if options.ReevaluateAfterSkippedTransmissionEnabled && ...
                    ~options.ResourceReevaluationEnabled
                error( ...
                    "v2xsim:resource:InvalidReevaluationOptions", ...
                    "ReevaluateAfterSkippedTransmission requires " + ...
                    "resource reevaluation.");
            end

            obj = obj@v2xsim.resource.AutonomousResourceAllocator( ...
                grid,randomSeed,maximumTransmissionCount);
            obj.MinimumReselectionCounter = ...
                options.MinimumReselectionCounter;
            obj.MaximumReselectionCounter = ...
                options.MaximumReselectionCounter;
            obj.KeepResourceProbability = ...
                options.KeepResourceProbability;
            obj.MinimumCandidateFraction = ...
                options.MinimumCandidateFraction;
            obj.L2CandidateFraction = options.L2CandidateFraction;
            obj.L2RankingEnabled = options.L2RankingEnabled;
            obj.DynamicSchedulingEnabled = ...
                options.DynamicSchedulingEnabled;
            obj.ResourceReevaluationEnabled = ...
                options.ResourceReevaluationEnabled;
            obj.ReevaluateAfterSkippedTransmissionEnabled = ...
                options.ReevaluateAfterSkippedTransmissionEnabled;
            obj.SensingThresholdWatts = ...
                options.SensingThresholdWatts;
            obj.IsNr = options.IsNr;
        end
    end

    methods (Access = protected)
        function value = configurationMetadata(obj)
            value = struct( ...
                "MinimumReselectionCounter", ...
                    obj.MinimumReselectionCounter, ...
                "MaximumReselectionCounter", ...
                    obj.MaximumReselectionCounter, ...
                "KeepResourceProbability", ...
                    obj.KeepResourceProbability, ...
                "MinimumCandidateFraction", ...
                    obj.MinimumCandidateFraction, ...
                "L2CandidateFraction", ...
                    obj.L2CandidateFraction, ...
                "L2RankingEnabled",obj.L2RankingEnabled, ...
                "DynamicSchedulingEnabled", ...
                    obj.DynamicSchedulingEnabled, ...
                "ResourceReevaluationEnabled", ...
                    obj.ResourceReevaluationEnabled, ...
                "ReevaluateAfterSkippedTransmissionEnabled", ...
                    obj.ReevaluateAfterSkippedTransmissionEnabled, ...
                "SensingThresholdWatts", ...
                    obj.SensingThresholdWatts, ...
                "SensingThresholdDbm", ...
                    10 * log10(obj.SensingThresholdWatts) + 30, ...
                "IsNr",obj.IsNr);
        end

        function obj = doSynchronizeUes(obj,~,~)
            previous = obj.UeState;
            [retained,locations] = ismember(obj.UeIds,previous.UeId);
            counters = nan(numel(obj.UeIds),1);
            newData = true(numel(obj.UeIds),1);
            counters(retained) = ...
                previous.ReselectionCounter(locations(retained));
            newData(retained) = ...
                previous.NewDataIndicator(locations(retained));
            obj.UeState = table( ...
                obj.UeIds,counters,newData, ...
                VariableNames=[ ...
                "UeId","ReselectionCounter","NewDataIndicator"]);
        end

        function [obj,result] = doInitialize( ...
                obj,context,randomStream)
            validateThreeGppContext(context);
            obj.validateTransmissionCounts(context);
            obj = obj.initializeMissingCounters(randomStream);
            rows = v2xsim.resource.internal.contextRows( ...
                obj.UeIds,context.UeIds);
            decisionRows = (1:numel(obj.UeIds)).';
            [resourceIds,~] = obj.allocateRows( ...
                obj.Assignments.ResourceIds,decisionRows, ...
                context,rows,zeros(0,1),randomStream);
            obj.UeState.NewDataIndicator(:) = true;
            reservations = obj.buildReservations(resourceIds);
            result = v2xsim.resource.internal.buildResult( ...
                obj.Grid,obj.Assignments,resourceIds, ...
                decisionRows,reservations);
        end

        function [obj,result] = doStep(obj,context,randomStream)
            if ~isa(context,"v2xsim.resource.ThreeGppAllocationContext")
                error( ...
                    "v2xsim:resource:InvalidAllocationContextType", ...
                    "ThreeGppAutonomous requires ThreeGppAllocationContext.");
            end
            obj.validateTransmissionCounts(context);

            obj = obj.initializeMissingCounters(randomStream);
            rows = v2xsim.resource.internal.contextRows( ...
                obj.UeIds,context.UeIds);
            newPacket = context.NewPacketMask(rows);
            firstTransmission = context.FirstTransmissionMask(rows);
            packetPending = context.PacketPendingMask(rows);
            skippedReserved = ...
                context.SkippedReservedTransmissionMask(rows);
            eligibility = context.EligibilityMask(rows,:);
            transmissionCount = context.TransmissionCount(rows);
            selectionOrigin = context.SelectionOriginSlot(rows);
            resourceIds = obj.Assignments.ResourceIds;

            reevaluationRows = obj.reevaluationRows( ...
                resourceIds,packetPending,context.CurrentSlot);

            obj.UeState.ReselectionCounter = ...
                obj.UeState.ReselectionCounter - firstTransmission;
            obj.UeState.NewDataIndicator(firstTransmission) = false;

            keepCheckRows = find( ...
                firstTransmission & ...
                obj.UeState.ReselectionCounter == 1);
            keepRows = zeros(0,1);
            if ~isempty(keepCheckRows) && obj.KeepResourceProbability > 0
                keepRows = keepCheckRows( ...
                    rand(randomStream,numel(keepCheckRows),1) < ...
                    obj.KeepResourceProbability);
            end

            forcedRows = find( ...
                newPacket & ...
                ~obj.assignedResourcesValid( ...
                    resourceIds,eligibility,transmissionCount, ...
                    selectionOrigin));
            counterRows = find( ...
                newPacket & obj.UeState.ReselectionCounter <= 0);
            reselectionRows = unique( ...
                [forcedRows;counterRows],"stable");
            decisionRows = unique( ...
                [reselectionRows;reevaluationRows],"stable");
            reevaluationOnlyRows = setdiff( ...
                reevaluationRows,reselectionRows,"stable");

            restartRows = unique( ...
                [reselectionRows;keepRows],"stable");
            obj = obj.restartCounters(restartRows,randomStream);

            [resourceIds,~] = obj.allocateRows( ...
                resourceIds,decisionRows,context,rows, ...
                reevaluationOnlyRows,randomStream);
            obj.UeState.NewDataIndicator(reselectionRows) = true;
            if obj.ReevaluateAfterSkippedTransmissionEnabled
                obj.UeState.NewDataIndicator(skippedReserved) = true;
            end

            reservations = obj.buildReservations(resourceIds);
            result = v2xsim.resource.internal.buildResult( ...
                obj.Grid,obj.Assignments,resourceIds, ...
                decisionRows,reservations);

            % A reevaluation that found the existing reservation acceptable
            % is a decision but not a reassignment; buildResult derives that
            % distinction from the unchanged resource row.
        end
    end

    methods (Access = private)
        function validateTransmissionCounts(obj,context)
            if any( ...
                    context.TransmissionCount > ...
                    obj.MaximumTransmissionCount)
                error( ...
                    "v2xsim:resource:TransmissionCountMismatch", ...
                    "Per-UE transmission counts cannot exceed the " + ...
                    "allocator maximum.");
            end
        end

        function obj = initializeMissingCounters(obj,stream)
            missing = isnan(obj.UeState.ReselectionCounter);
            obj = obj.restartCounters(find(missing),stream);
        end

        function obj = restartCounters(obj,rows,stream)
            if isempty(rows)
                return
            end
            if obj.DynamicSchedulingEnabled
                obj.UeState.ReselectionCounter(rows) = 1;
            else
                range = obj.MaximumReselectionCounter - ...
                    obj.MinimumReselectionCounter + 1;
                obj.UeState.ReselectionCounter(rows) = ...
                    obj.MinimumReselectionCounter - 1 + ...
                    randi(stream,range,numel(rows),1);
            end
        end

        function rows = reevaluationRows( ...
                obj,resourceIds,packetPending,currentSlot)
            if ~obj.ResourceReevaluationEnabled
                rows = zeros(0,1);
                return
            end
            primary = resourceIds(:,1);
            offset = inf(size(primary));
            assigned = ~isnan(primary);
            resourceTime = ceil( ...
                primary(assigned) / ...
                obj.Grid.NumberFrequencyResources);
            periodicSlot = obj.Grid.periodicSlot(currentSlot);
            offset(assigned) = mod( ...
                resourceTime - periodicSlot - 1, ...
                obj.Grid.NumberTimeSlots) + 1;
            rows = find( ...
                offset == 3 & packetPending & ...
                obj.UeState.NewDataIndicator);
        end

        function [resourceIds,successfulRows] = allocateRows( ...
                obj,resourceIds,decisionRows,context,contextRows, ...
                retentionRows,stream)
            successfulRows = zeros(0,1);
            sensing = context.SensingSnapshot;
            energy = sensing.EnergyWattsPerMHz(contextRows,:);
            reserved = sensing.ReservedMask(contextRows,:);
            eligibility = context.EligibilityMask(contextRows,:);
            selectionOrigin = context.SelectionOriginSlot(contextRows);

            for row = reshape(decisionRows,1,[])
                previous = resourceIds(row,:);
                bestResources = obj.selectionSet( ...
                    energy(row,:),reserved(row,:), ...
                    eligibility(row,:),stream);
                if isempty(bestResources)
                    if ~ismember(row,retentionRows)
                        resourceIds(row,:) = NaN;
                    end
                    continue
                end

                isRetention = ismember(row,retentionRows);
                assignedPrevious = previous(~isnan(previous));
                previousAccepted = ...
                    ismember(assignedPrevious,bestResources);
                if isRetention && ...
                        numel(assignedPrevious) == ...
                            obj.MaximumTransmissionCount && ...
                        all(previousAccepted)
                    successfulRows(end + 1,1) = row; %#ok<AGROW>
                    continue
                elseif isRetention && any(previousAccepted)
                    retained = assignedPrevious( ...
                        find(previousAccepted,1));
                    primary = retained;
                else
                    primary = bestResources( ...
                        randi(stream,numel(bestResources)));
                end
                resourceIds(row,:) = NaN;
                resourceIds(row,1) = primary;

                if obj.MaximumTransmissionCount > 1
                    secondary = obj.selectSecondary( ...
                        primary,bestResources,selectionOrigin(row),stream);
                    if ~isnan(secondary)
                        resources = [primary secondary];
                        futureSlots = obj.futureSlots( ...
                            resources,selectionOrigin(row));
                        [~,order] = sort(futureSlots);
                        resourceIds(row,1:2) = resources(order);
                    end
                end
                successfulRows(end + 1,1) = row; %#ok<AGROW>
            end
        end

        function valid = assignedResourcesValid( ...
                obj,resourceIds,eligibility,transmissionCount, ...
                selectionOrigin)
            valid = true(size(resourceIds,1),1);
            for row = 1:size(resourceIds,1)
                requiredCount = transmissionCount(row);
                requiredResources = ...
                    resourceIds(row,1:requiredCount);
                if any(isnan(requiredResources)) || ...
                        ~all(eligibility(row,requiredResources))
                    valid(row) = false;
                    continue
                end

                future = obj.futureSlots( ...
                    requiredResources,selectionOrigin(row));
                valid(row) = all(diff(future) > 0);
            end
        end

        function bestResources = selectionSet( ...
                obj,energy,reserved,eligible,stream)
            possible = eligible & isfinite(energy);
            possibleCount = nnz(possible);
            minimumUsable = ceil( ...
                possibleCount * obj.MinimumCandidateFraction);
            if possibleCount == 0 || minimumUsable == 0
                bestResources = zeros(1,0);
                return
            end

            threshold = obj.SensingThresholdWatts;
            usable = false(size(eligible));
            for iteration = 1:64
                usable = possible & ( ...
                    energy * 0.015 < threshold | ~reserved);
                if nnz(usable) >= minimumUsable
                    break
                end
                threshold = threshold * 2;
            end
            if nnz(usable) < minimumUsable
                bestResources = zeros(1,0);
                return
            end

            permutation = randperm(stream,obj.Grid.ResourceCount);
            candidates = permutation(usable(permutation));
            [~,energyOrder] = sort(energy(candidates),"ascend");
            candidates = candidates(energyOrder);
            if obj.L2RankingEnabled
                selectionCount = min( ...
                    numel(candidates), ...
                    ceil(possibleCount * obj.L2CandidateFraction));
            else
                selectionCount = numel(candidates);
            end
            bestResources = candidates(1:selectionCount);
        end

        function secondary = selectSecondary( ...
                obj,primary,bestResources,selectionOriginSlot,stream)
            primaryTime = ceil( ...
                primary / obj.Grid.NumberFrequencyResources);
            candidateTimes = ceil( ...
                bestResources / obj.Grid.NumberFrequencyResources);
            candidates = bestResources(candidateTimes ~= primaryTime);
            if isempty(candidates)
                secondary = NaN;
                return
            end

            primaryFuture = obj.futureSlots( ...
                primary,selectionOriginSlot);
            candidateFuture = obj.futureSlots( ...
                candidates,selectionOriginSlot);
            if obj.IsNr
                maximumSeparation = 31;
            else
                maximumSeparation = 15;
            end
            candidates = candidates( ...
                abs(candidateFuture - primaryFuture) <= ...
                maximumSeparation);
            if isempty(candidates)
                secondary = NaN;
            else
                secondary = candidates(randi(stream,numel(candidates)));
            end
        end

        function future = futureSlots( ...
                obj,resourceIds,selectionOriginSlot)
            timeSlots = ceil( ...
                resourceIds / obj.Grid.NumberFrequencyResources);
            periodicSlot = obj.Grid.periodicSlot(selectionOriginSlot);
            future = timeSlots;
            future(timeSlots <= periodicSlot) = ...
                future(timeSlots <= periodicSlot) + ...
                obj.Grid.NumberTimeSlots;
        end

        function reservations = buildReservations(obj,resourceIds)
            reservingRows = find( ...
                obj.UeState.ReselectionCounter > 1);
            ueIds = strings(0,1);
            reservedIds = zeros(0,1);
            for row = reshape(reservingRows,1,[])
                ids = resourceIds(row,:);
                ids = ids(~isnan(ids));
                ueIds = [ueIds; ...
                    repmat(obj.UeIds(row),numel(ids),1)]; %#ok<AGROW>
                reservedIds = [reservedIds;ids(:)]; %#ok<AGROW>
            end
            reservations = table( ...
                ueIds,reservedIds, ...
                VariableNames=["UeId","ResourceId"]);
        end
    end
end

function validateFraction(value,minimum,maximum,name)
if ~isfinite(value) || value < minimum || value > maximum
    error( ...
        "v2xsim:resource:InvalidAllocatorOption", ...
        "%s must be between %g and %g.",name,minimum,maximum);
end
end

function validateThreeGppContext(context)
if ~isa(context,"v2xsim.resource.ThreeGppAllocationContext")
    error( ...
        "v2xsim:resource:InvalidAllocationContextType", ...
        "ThreeGppAutonomous requires ThreeGppAllocationContext.");
end
end
