function [registry,dispatcher] = composeOutputHooks( ...
        outputHookOptions,outParams,simParams,appParams,phyParams)
%COMPOSEOUTPUTHOOKS Translate text output settings into hook registrations.
%   This is a composition-root adapter. Runtime simulator code receives
%   only the returned dispatcher.

container = v2xsim.hook.dependency.ServiceContainer();
container.provideConstant( ...
    ?v2xsim.hook.dependencies.OutputDirectory, ...
    v2xsim.hook.dependencies.OutputDirectory( ...
        outParams.outputFolder));
container.provideConstant( ...
    ?v2xsim.hook.dependencies.SimulationIdentifier, ...
    v2xsim.hook.dependencies.SimulationIdentifier( ...
        outParams.simID));

registry = v2xsim.hook.HookRegistry(container);
if outputHookOptions.VehicleKinematicsEnabled
    registry.register( ...
        v2xsim.hooks.common.VehicleKinematicsRecorder(), ...
        v2xsim.hook.points.AfterVehicleKinematicsUpdated);
end
if outputHookOptions.AverageNeighborCountEnabled
    if simParams.technology == constants.TECH_ONLY_CV2X
        neighborCountTechnologies = "cv2x";
    elseif simParams.technology == constants.TECH_ONLY_11P
        neighborCountTechnologies = "itsg5";
    else
        neighborCountTechnologies = ["all", "cv2x", "itsg5"];
    end
    for technology = neighborCountTechnologies
        registry.register( ...
            v2xsim.hooks.common. ...
                AverageNeighborCountRecorder(technology), ...
            v2xsim.hook.points.AfterNeighborGraphUpdated);
    end
end
if outputHookOptions.UpdateDelayEnabled
    registry.register( ...
        v2xsim.hooks.common.UpdateDelayRecorder( ...
            outputHookOptions.DelayBinWidthSeconds, ...
            ChannelCount=phyParams.nChannels), ...
        v2xsim.hook.points.AfterPacketFatesDetermined);
end
if outputHookOptions.DataAgeEnabled
    registry.register( ...
        v2xsim.hooks.common.DataAgeRecorder( ...
            outputHookOptions.DelayBinWidthSeconds, ...
            ChannelCount=phyParams.nChannels), ...
        v2xsim.hook.points.AfterPacketFatesDetermined);
end
if outputHookOptions.PacketDelayEnabled
    registry.register( ...
        v2xsim.hooks.common.PacketDelayRecorder( ...
            outputHookOptions.DelayBinWidthSeconds, ...
            appParams.allocationPeriod, ...
            ChannelCount=phyParams.nChannels), ...
        v2xsim.hook.points.AfterPacketFatesDetermined);
end
if outputHookOptions.PacketReceptionRatioEnabled
    if simParams.technology ~= constants.TECH_ONLY_CV2X
        registry.register( ...
            v2xsim.hooks.common. ...
                PacketReceptionRatioRecorder( ...
                    outputHookOptions. ...
                        PacketReceptionRatioDistanceBinWidthMeters, ...
                    phyParams.RawMax11p, "11p", ...
                    ChannelCount=phyParams.nChannels), ...
            v2xsim.hook.points.AfterPacketFatesDetermined);
    end
    if simParams.technology ~= constants.TECH_ONLY_11P
        registry.register( ...
            v2xsim.hooks.common. ...
                PacketReceptionRatioRecorder( ...
                    outputHookOptions. ...
                        PacketReceptionRatioDistanceBinWidthMeters, ...
                    phyParams.RawMaxCV2X, ...
                    string(simParams.stringCV2X), ...
                    ChannelCount=phyParams.nChannels), ...
            v2xsim.hook.points.AfterPacketFatesDetermined);
    end
end
if outputHookOptions.WirelessBlindSpotEnabled
    cv2xTechnology = "";
    if isfield(simParams, "stringCV2X")
        cv2xTechnology = string(simParams.stringCV2X);
    end
    registry.register( ...
        v2xsim.hooks.common.WirelessBlindSpotRecorder( ...
            outputHookOptions. ...
                WirelessBlindSpotMaximumDelaySeconds, ...
            outputHookOptions.WirelessBlindSpotBinWidthSeconds, ...
            Cv2xTechnology=cv2xTechnology), ...
        [ ...
            v2xsim.hook.points.AfterNeighborGraphUpdated, ...
            v2xsim.hook.points.AfterPacketFatesDetermined]);
end
if outputHookOptions.ChannelBusyRatioEnabled
    isCoexistence = ~ismember( ...
        simParams.technology, ...
        [constants.TECH_ONLY_CV2X, constants.TECH_ONLY_11P]);
    registry.register( ...
        v2xsim.hooks.common.ChannelBusyRatioRecorder( ...
            simParams.cbrSensingInterval, ...
            simParams.simulationTime, ...
            WriteTechnologyOnlyStatistic=isCoexistence), ...
        v2xsim.hook.points.AfterChannelBusyRatioSampled);
end

dispatcher = registry.createDispatcher();
end
