function [simParams,varargin] = initiatePositionErrorChain( ...
        simParams,fileCfg,varargin)
%INITIATEPOSITIONERRORCHAIN Parse an ordered positioning-error pipeline.
%   [positionErrorModules] is a comma-separated list containing Gaussian,
%   Delay, FalseExit, and/or FalseMerge. Module-specific options use the
%   positionErrorOptions.<Module>.<Option> namespace.

[simParams,varargin] = addNewParam( ...
    simParams,'positionErrorModules','None', ...
    'Ordered position error modules','string',fileCfg,varargin{1});
moduleNames = parseModuleNames(simParams.positionErrorModules);

usesFalseExit = any(moduleNames == "FalseExit");
falseExitScenario = ismember( ...
    string(simParams.typeOfScenario), ...
    ["ExitRampHighwayScenario","RoundaboutScenario"]);
if usesFalseExit && ~falseExitScenario
    error( ...
        'v2xsim:legacy:IncompatiblePositionErrorModule', ...
        ['FalseExit position errors require ExitRampHighwayScenario ', ...
        'or RoundaboutScenario.']);
end
usesFalseMerge = any(moduleNames == "FalseMerge");
if usesFalseMerge && ...
        ~strcmp(simParams.typeOfScenario,'ExitRampHighwayScenario')
    error( ...
        'v2xsim:legacy:IncompatiblePositionErrorModule', ...
        'FalseMerge position errors require ExitRampHighwayScenario.');
end

modules = cell(1,numel(moduleNames));
for moduleIndex = 1:numel(moduleNames)
    switch moduleNames(moduleIndex)
        case "Gaussian"
            [simParams,remainingArguments] = parseGaussianOptions( ...
                simParams,fileCfg,varargin{1});
            varargin = {remainingArguments};
            options = simParams.positionErrorOptions.Gaussian;
            activeRoutes = parseActiveRoutes(options.ActiveRoutes);
            if ~isempty(activeRoutes) && ...
                    ~strcmp( ...
                        simParams.typeOfScenario, ...
                        'ExitRampHighwayScenario')
                error( ...
                    'v2xsim:legacy:IncompatiblePositionErrorModule', ...
                    ['Gaussian ActiveRoutes require ', ...
                    'ExitRampHighwayScenario.']);
            end
            effect = ...
                v2xsim.positioning. ...
                IsotropicGaussianPositionErrorStatusEffect( ...
                    options.StandardDeviationMeters, ...
                    MeanMagnitudeMeters=options.MeanMagnitudeMeters, ...
                    DisplacementRandomSeed= ...
                        options.DisplacementRandomSeed, ...
                    AffectedVehicleProbability= ...
                        options.AffectedVehicleProbability, ...
                    SelectionRandomSeed= ...
                        options.SelectionRandomSeed, ...
                    ResetAfterSeconds=options.ResetAfterSeconds, ...
                    ActiveRoutes=activeRoutes);
            modules{moduleIndex} = ...
                v2xsim.positioning. ...
                PositionErrorStatusEffectInflictor(effect);

        case "Delay"
            [simParams,varargin] = addNewParam( ...
                simParams, ...
                'positionErrorOptions.Delay.DelaySeconds', ...
                0,'Position observation delay (s)', ...
                'double',fileCfg,varargin{1});
            modules{moduleIndex} = ...
                v2xsim.positioning.PositionDelayError( ...
                    simParams.positionErrorOptions.Delay.DelaySeconds);

        case "FalseExit"
            [simParams,remainingArguments] = parseFalseRouteOptions( ...
                simParams,fileCfg,varargin{1},"FalseExit");
            varargin = {remainingArguments};
            options = simParams.positionErrorOptions.FalseExit;
            effect = ...
                v2xsim.positioning. ...
                FalseExitPositionErrorStatusEffect( ...
                    options.AffectedVehicleProbability, ...
                    ResetAfterSeconds=options.ResetAfterSeconds, ...
                    DisplacementScale=options.DisplacementScale, ...
                    SelectionRandomSeed= ...
                        options.SelectionRandomSeed);
            modules{moduleIndex} = ...
                v2xsim.positioning. ...
                PositionErrorStatusEffectInflictor(effect);

        case "FalseMerge"
            [simParams,remainingArguments] = parseFalseRouteOptions( ...
                simParams,fileCfg,varargin{1},"FalseMerge");
            varargin = {remainingArguments};
            options = simParams.positionErrorOptions.FalseMerge;
            effect = ...
                v2xsim.positioning. ...
                FalseMergePositionErrorStatusEffect( ...
                    options.AffectedVehicleProbability, ...
                    ResetAfterSeconds=options.ResetAfterSeconds, ...
                    DisplacementScale=options.DisplacementScale, ...
                    SelectionRandomSeed= ...
                        options.SelectionRandomSeed);
            modules{moduleIndex} = ...
                v2xsim.positioning. ...
                PositionErrorStatusEffectInflictor(effect);
    end
end

simParams.positionErrorModuleNames = moduleNames;
simParams.positionErrorChain = ...
    v2xsim.positioning.PositionErrorChain(modules);
end

function [simParams,remainingArguments] = parseGaussianOptions( ...
        simParams,fileCfg,remainingArguments)
[simParams,wrappedArguments] = addNewParam( ...
    simParams, ...
    'positionErrorOptions.Gaussian.MeanMagnitudeMeters', ...
    0,'Gaussian radial mean magnitude (m)', ...
    'double',fileCfg,remainingArguments);
remainingArguments = wrappedArguments{1};
[simParams,wrappedArguments] = addNewParam( ...
    simParams, ...
    'positionErrorOptions.Gaussian.StandardDeviationMeters', ...
    0,'Gaussian radial standard deviation (m)', ...
    'double',fileCfg,remainingArguments);
remainingArguments = wrappedArguments{1};
[simParams,wrappedArguments] = addNewParam( ...
    simParams, ...
    'positionErrorOptions.Gaussian.DisplacementRandomSeed', ...
    defaultPositioningSeed(simParams,104729), ...
    'Gaussian displacement random seed', ...
    'integer',fileCfg,remainingArguments);
remainingArguments = wrappedArguments{1};
[simParams,wrappedArguments] = addNewParam( ...
    simParams, ...
    'positionErrorOptions.Gaussian.AffectedVehicleProbability', ...
    1,'Fraction of vehicles selected for Gaussian error', ...
    'double',fileCfg,remainingArguments);
remainingArguments = wrappedArguments{1};
[simParams,wrappedArguments] = addNewParam( ...
    simParams,'positionErrorOptions.Gaussian.SelectionRandomSeed', ...
    defaultPositioningSeed(simParams,130363), ...
    'Gaussian cohort-selection random seed', ...
    'integer',fileCfg,remainingArguments);
remainingArguments = wrappedArguments{1};
[simParams,wrappedArguments] = addNewParam( ...
    simParams,'positionErrorOptions.Gaussian.ResetAfterSeconds', ...
    Inf,'Gaussian status-effect reset duration (s)', ...
    'double',fileCfg,remainingArguments);
remainingArguments = wrappedArguments{1};
[simParams,wrappedArguments] = addNewParam( ...
    simParams,'positionErrorOptions.Gaussian.ActiveRoutes', ...
    'All','Exit-ramp routes on which Gaussian error is active', ...
    'string',fileCfg,remainingArguments);
remainingArguments = wrappedArguments{1};

options = simParams.positionErrorOptions.Gaussian;
validateProbability( ...
    options.AffectedVehicleProbability, ...
    "positioning.Gaussian.AffectedVehicleProbability");
validateRandomSeed( ...
    options.DisplacementRandomSeed, ...
    "positioning.Gaussian.DisplacementRandomSeed");
validateRandomSeed( ...
    options.SelectionRandomSeed, ...
    "positioning.Gaussian.SelectionRandomSeed");
validateResetDuration( ...
    options.ResetAfterSeconds, ...
    "positioning.Gaussian.ResetAfterSeconds");
parseActiveRoutes(options.ActiveRoutes);
end

function moduleNames = parseModuleNames(configuredValue)
configuredValue = string(configuredValue);
if ~isscalar(configuredValue)
    error( ...
        'v2xsim:legacy:InvalidPositionErrorModules', ...
        '[positionErrorModules] must be one comma-separated string.');
end

configuredValue = strip(configuredValue);
if strlength(configuredValue)==0 || strcmpi(configuredValue,"None")
    moduleNames = strings(1,0);
    return
end

configuredNames = strip(split(configuredValue,","));
moduleNames = strings(size(configuredNames));
for moduleIndex = 1:numel(configuredNames)
    switch lower(configuredNames(moduleIndex))
        case "gaussian"
            moduleNames(moduleIndex) = "Gaussian";
        case "delay"
            moduleNames(moduleIndex) = "Delay";
        case "falseexit"
            moduleNames(moduleIndex) = "FalseExit";
        case "falsemerge"
            moduleNames(moduleIndex) = "FalseMerge";
        otherwise
            error( ...
                'v2xsim:legacy:UnknownPositionErrorModule', ...
                ['Unknown position error module "%s". Supported ', ...
                'modules are Gaussian, Delay, FalseExit, and ', ...
                'FalseMerge.'],configuredNames(moduleIndex));
    end
end
moduleNames = reshape(moduleNames,1,[]);

if numel(unique(moduleNames))~=numel(moduleNames)
    error( ...
        'v2xsim:legacy:DuplicatePositionErrorModule', ...
        ['Each position error module type may appear at most once ', ...
        'in [positionErrorModules].']);
end
end

function [simParams,remainingArguments] = parseFalseRouteOptions( ...
        simParams,fileCfg,remainingArguments,moduleName)
probabilityField = sprintf( ...
    'positionErrorOptions.%s.AffectedVehicleProbability',moduleName);
resetField = sprintf( ...
    'positionErrorOptions.%s.ResetAfterSeconds',moduleName);
scaleField = sprintf( ...
    'positionErrorOptions.%s.DisplacementScale',moduleName);
seedField = sprintf( ...
    'positionErrorOptions.%s.SelectionRandomSeed',moduleName);
[simParams,wrappedArguments] = addNewParam( ...
    simParams,probabilityField,0, ...
    sprintf('%s affected-vehicle probability',moduleName), ...
    'double',fileCfg,remainingArguments);
remainingArguments = wrappedArguments{1};
[simParams,wrappedArguments] = addNewParam( ...
    simParams,resetField,Inf, ...
    sprintf('%s reset duration (s)',moduleName), ...
    'double',fileCfg,remainingArguments);
remainingArguments = wrappedArguments{1};
[simParams,wrappedArguments] = addNewParam( ...
    simParams,scaleField,1, ...
    sprintf('%s false-route displacement scale',moduleName), ...
    'double',fileCfg,remainingArguments);
remainingArguments = wrappedArguments{1};
seedSalt = 155921;
if moduleName == "FalseMerge"
    seedSalt = 180503;
end
[simParams,wrappedArguments] = addNewParam( ...
    simParams,seedField,defaultPositioningSeed(simParams,seedSalt), ...
    sprintf('%s cohort-selection random seed',moduleName), ...
    'integer',fileCfg,remainingArguments);
remainingArguments = wrappedArguments{1};

options = simParams.positionErrorOptions.(moduleName);
validateProbability( ...
    options.AffectedVehicleProbability, ...
    "positioning." + moduleName + ...
        ".AffectedVehicleProbability");
validateResetDuration( ...
    options.ResetAfterSeconds, ...
    "positioning." + moduleName + ".ResetAfterSeconds");
if options.DisplacementScale < 0 || options.DisplacementScale > 1
    error( ...
        'v2xsim:legacy:InvalidFalseRouteDisplacementScale', ...
        'positioning.%s.DisplacementScale must lie between zero and one.', ...
        moduleName);
end
validateRandomSeed( ...
    options.SelectionRandomSeed, ...
    "positioning." + moduleName + ".SelectionRandomSeed");
end

function routes = parseActiveRoutes(configuredValue)
configuredValue = strip(string(configuredValue));
if ~isscalar(configuredValue) || ismissing(configuredValue)
    error( ...
        'v2xsim:legacy:InvalidGaussianActiveRoutes', ...
        'positioning.Gaussian.ActiveRoutes must be one string.');
end
if strlength(configuredValue) == 0 || ...
        strcmpi(configuredValue, "All")
    routes = strings(1, 0);
    return
end

configuredRoutes = strip(split(configuredValue, ","));
routes = strings(size(configuredRoutes));
for routeIndex = 1:numel(configuredRoutes)
    route = lower(configuredRoutes(routeIndex));
    switch route
        case "ramp"
            routes(routeIndex) = "Ramp";
        case "merge"
            routes(routeIndex) = "Merge";
        case "adjacent"
            routes(routeIndex) = "Adjacent";
        otherwise
            error( ...
                'v2xsim:legacy:InvalidGaussianActiveRoutes', ...
                ['Gaussian active routes must contain only Ramp, ', ...
                'Merge, or Adjacent.']);
    end
end
routes = unique(reshape(routes, 1, []), "stable");
end

function seed = defaultPositioningSeed(simParams,salt)
baseSeed = 0;
if isfield(simParams, "seed")
    baseSeed = simParams.seed;
end
seed = mod(double(baseSeed) + salt, double(intmax("uint32")) + 1);
end

function validateRandomSeed(seed,parameterName)
if seed < 0 || seed > double(intmax("uint32"))
    error( ...
        'v2xsim:legacy:InvalidPositionErrorRandomSeed', ...
        '%s must fit in an unsigned 32-bit integer.',parameterName);
end
end

function validateProbability(probability,parameterName)
if probability < 0 || probability > 1
    error( ...
        'v2xsim:legacy:InvalidPositionErrorProbability', ...
        '%s must lie between zero and one.',parameterName);
end
end

function validateResetDuration(durationSeconds,parameterName)
if isnan(durationSeconds) || durationSeconds < 0
    error( ...
        'v2xsim:legacy:InvalidStatusEffectResetDuration', ...
        '%s must be nonnegative or Inf.',parameterName);
end
end
