function [simParams,phyParams,varargin] = initiateBRAssignmentAlgorithm( ...
        simParams,phyParams,reservationIntervalSeconds,fileCfg,varargin)
%INITIATEBRASSIGNMENTALGORITHM Parse the v7 resource-allocation contract.
%   Algorithm selection is string based. Numeric v6/v7-preview algorithm
%   identifiers are deliberately rejected instead of being translated.

fprintf("Settings of resource assignment algorithm\n");

rejectRemovedConfiguration(fileCfg,varargin{1});

defaultSeed = 1;
if isfield(simParams,"seed")
    defaultSeed = simParams.seed;
end

[simParams,varargin] = addNewParam( ...
    simParams,"resourceAllocationType","ThreeGppAutonomous", ...
    "Resource allocation strategy","string",fileCfg,varargin{1});
[simParams,varargin] = addNewParam( ...
    simParams,"resourceAllocationRandomSeed",defaultSeed, ...
    "Resource allocator random seed","integer",fileCfg,varargin{1});
if simParams.resourceAllocationRandomSeed < 0 || ...
        simParams.resourceAllocationRandomSeed > double(intmax("uint32"))
    error( ...
        "v2xsim:resource:InvalidRandomSeed", ...
        "resourceAllocation.RandomSeed must fit in an unsigned 32-bit integer.");
end

simParams.resourceAllocationType = canonicalType( ...
    simParams.resourceAllocationType);

[phyParams,varargin] = addNewParam( ...
    phyParams,"minSCIsinr",0, ...
    "Minimum SCI decode SINR (dB)","double",fileCfg,varargin{1});
phyParams.minSCIsinrDb = phyParams.minSCIsinr;
phyParams.minSCIsinr = db2pow(phyParams.minSCIsinr);

% Defaults shared by code outside the allocator configuration.
simParams.posError95 = 0;
simParams.sigmaPosError = 0;
simParams.Tupdate = reservationIntervalSeconds;
simParams.Mreuse = 0;
simParams.Treassign = reservationIntervalSeconds;
simParams.knownShadowing = false;

switch simParams.resourceAllocationType
    case "ReuseDistance"
        [simParams,varargin] = parseReuseDistance( ...
            simParams,reservationIntervalSeconds,fileCfg,varargin{1});
    case {"MaximumReuseDistance","MinimumReusePower"}
        [simParams,varargin] = parseScheduledAllocator( ...
            simParams,reservationIntervalSeconds,fileCfg,varargin{1});
        if simParams.resourceAllocationType == "MinimumReusePower"
            [simParams,varargin] = addNewParam( ...
                simParams,"knownShadowing",false, ...
                "Whether centralized received-power estimates remove shadowing", ...
                "bool",fileCfg,varargin{1});
        end
    case "ThreeGppAutonomous"
        [simParams,phyParams,varargin] = parseThreeGpp( ...
            simParams,phyParams,fileCfg,varargin{1});
    case "RandomBenchmark"
        [simParams,varargin] = parseSelectionWindow( ...
            simParams,phyParams,fileCfg,varargin{1});
    case "OrderedBenchmark"
        % No algorithm-specific options.
end

validateCapabilities(simParams,phyParams);
fprintf("\n");
end

function [simParams,varargin] = parseReuseDistance( ...
        simParams,reservationIntervalSeconds,fileCfg,varargin)
[simParams,varargin] = addNewParam( ...
    simParams,"posError95",0, ...
    "Controlled positioning error at the 95th percentile (m)", ...
    "double",fileCfg,varargin{1});
if simParams.posError95 < 0
    error( ...
        "v2xsim:resource:InvalidPositionError", ...
        "Controlled position error cannot be negative.");
end
simParams.sigmaPosError = simParams.posError95 / 1.96;

[simParams,varargin] = addNewParam( ...
    simParams,"Tupdate",reservationIntervalSeconds, ...
    "Controlled position-update interval (s)", ...
    "double",fileCfg,varargin{1});
validateExactInterval( ...
    simParams.Tupdate,reservationIntervalSeconds, ...
    "resourceAllocation.Controlled.PositionUpdateIntervalSeconds");

[simParams,varargin] = addNewParam( ...
    simParams,"Mreuse",0,"Reuse-distance margin (m)", ...
    "double",fileCfg,varargin{1});
if simParams.Mreuse < 0
    error( ...
        "v2xsim:resource:InvalidReuseMargin", ...
        "The reuse-distance margin cannot be negative.");
end

[simParams,varargin] = parseScheduledAllocator( ...
    simParams,reservationIntervalSeconds,fileCfg,varargin{1});
end

function [simParams,varargin] = parseScheduledAllocator( ...
        simParams,reservationIntervalSeconds,fileCfg,varargin)
[simParams,varargin] = addNewParam( ...
    simParams,"Treassign",reservationIntervalSeconds, ...
    "Controlled reassignment interval (s)", ...
    "double",fileCfg,varargin{1});
validateExactInterval( ...
    simParams.Treassign,reservationIntervalSeconds, ...
    "resourceAllocation.Controlled.ReassignmentIntervalSeconds");
end

function [simParams,phyParams,varargin] = parseThreeGpp( ...
        simParams,phyParams,fileCfg,varargin)
[simParams,varargin] = addNewParam( ...
    simParams,"resourceReEvaluation",false, ...
    "Enable NR resource reevaluation","bool",fileCfg,varargin{1});
[simParams,varargin] = addNewParam( ...
    simParams,"reEvalAfterEmptyResource",false, ...
    "Reevaluate after a skipped NR transmission", ...
    "bool",fileCfg,varargin{1});
if (simParams.resourceReEvaluation || ...
        simParams.reEvalAfterEmptyResource) && ...
        simParams.mode5G ~= constants.MODE_5G
    error( ...
        "v2xsim:resource:NrOptionForLte", ...
        "Resource reevaluation options require NR-V2X.");
end
if simParams.reEvalAfterEmptyResource && ...
        ~simParams.resourceReEvaluation
    error( ...
        "v2xsim:resource:InvalidReevaluationOptions", ...
        "ReevaluateAfterSkippedTransmission requires reevaluation.");
end

[simParams,varargin] = addNewParam( ...
    simParams,"dynamicScheduling",false, ...
    "Reselect a resource for every packet","bool",fileCfg,varargin{1});
[simParams,varargin] = addNewParam( ...
    simParams,"probResKeep",0.8 * ~simParams.dynamicScheduling, ...
    "Probability of retaining the current resource", ...
    "double",fileCfg,varargin{1});
if simParams.probResKeep < 0 || simParams.probResKeep > 1
    error( ...
        "v2xsim:resource:InvalidKeepProbability", ...
        "KeepResourceProbability must be between zero and one.");
end
if simParams.dynamicScheduling && simParams.probResKeep ~= 0
    error( ...
        "v2xsim:resource:InvalidKeepProbability", ...
        "KeepResourceProbability must be zero when every packet reselects.");
end
if simParams.probResKeep > 0.8
    warning( ...
        "v2xsim:resource:NonstandardKeepProbability", ...
        "3GPP specifies a keep probability no greater than 0.8.");
end
[simParams,varargin] = addNewParam( ...
    simParams, ...
    "resourceAllocation.Autonomous." + ...
        "MaximumConsecutiveReservationIntervals", ...
    Inf,"Maximum consecutive SPS reservation intervals", ...
    "double",fileCfg,varargin{1});
maximumIntervals = simParams.resourceAllocation.Autonomous. ...
    MaximumConsecutiveReservationIntervals;
validMaximumIntervals = isnumeric(maximumIntervals) && ...
    isreal(maximumIntervals) && isscalar(maximumIntervals) && ...
    ~isnan(maximumIntervals) && maximumIntervals > 0 && ...
    (isinf(maximumIntervals) || mod(maximumIntervals,1) == 0);
if ~validMaximumIntervals
    error( ...
        "v2xsim:resource:" + ...
        "InvalidMaximumConsecutiveReservationIntervals", ...
        "MaximumConsecutiveReservationIntervals must be a positive " + ...
        "integer or Inf.");
end

[simParams,varargin] = addNewParam( ...
    simParams,"ratioSelectedAutonomousMode",0.2, ...
    "Minimum fraction surviving reservation filtering", ...
    "double",fileCfg,varargin{1});
if simParams.ratioSelectedAutonomousMode < 0.2 || ...
        simParams.ratioSelectedAutonomousMode > 1
    error( ...
        "v2xsim:resource:InvalidCandidateFraction", ...
        "MinimumCandidateFraction must be between 0.2 and one.");
end
[simParams,varargin] = addNewParam( ...
    simParams,"ratioSelectedL2", ...
    simParams.ratioSelectedAutonomousMode, ...
    "Fraction retained by L2 energy ranking", ...
    "double",fileCfg,varargin{1});
if simParams.ratioSelectedL2 <= 0 || simParams.ratioSelectedL2 > 1
    error( ...
        "v2xsim:resource:InvalidCandidateFraction", ...
        "L2CandidateFraction must be greater than zero and at most one.");
end

[simParams,varargin] = addNewParam( ...
    simParams,"L2active",~simParams.mode5G, ...
    "Enable L2 energy ranking","bool",fileCfg,varargin{1});
[simParams,varargin] = addNewParam( ...
    simParams,"averageSensingActive",~simParams.mode5G, ...
    "Average energy over the sensing window","bool",fileCfg,varargin{1});
[simParams,varargin] = addNewParam( ...
    simParams,"TsensingPeriod",1, ...
    "Sensing-window duration (s)","double",fileCfg,varargin{1});
if simParams.TsensingPeriod <= 0
    error( ...
        "v2xsim:resource:InvalidSensingWindow", ...
        "The sensing window must be positive.");
end

[simParams,varargin] = addNewParam( ...
    simParams,"minRandValueMode4",-1, ...
    "Minimum reselection-counter value","integer",fileCfg,varargin{1});
[simParams,varargin] = addNewParam( ...
    simParams,"maxRandValueMode4",-1, ...
    "Maximum reselection-counter value","integer",fileCfg,varargin{1});
if simParams.minRandValueMode4 ~= -1 && ...
        simParams.minRandValueMode4 <= 0
    error( ...
        "v2xsim:resource:InvalidReselectionCounter", ...
        "The minimum reselection counter must be positive or -1.");
end
if simParams.maxRandValueMode4 ~= -1 && ...
        simParams.maxRandValueMode4 <= simParams.minRandValueMode4
    error( ...
        "v2xsim:resource:InvalidReselectionCounter", ...
        "The maximum reselection counter must exceed the minimum.");
end

[simParams,varargin] = addNewParam( ...
    simParams,"powerThresholdAutonomous",-110, ...
    "RSRP exclusion threshold (dBm)","double",fileCfg,varargin{1});
thresholdDbm = simParams.powerThresholdAutonomous;
if thresholdDbm < -128 || thresholdDbm > -2 || mod(thresholdDbm,2) ~= 0
    error( ...
        "v2xsim:resource:InvalidSensingThreshold", ...
        "SensingThresholdDbm must be from -128 to -2 in 2 dB steps.");
end
simParams.powerThresholdAutonomousDbm = thresholdDbm;
simParams.powerThresholdAutonomous = db2pow(thresholdDbm - 30);

[simParams,varargin] = parseSelectionWindow( ...
    simParams,phyParams,fileCfg,varargin{1});
end

function [simParams,varargin] = parseSelectionWindow( ...
        simParams,phyParams,fileCfg,varargin)
if phyParams.muNumerology == 0
    defaultT1 = 1;
    parameterType = "integer";
    maximumT1 = 4;
elseif phyParams.muNumerology == 1
    defaultT1 = 0.5;
    parameterType = "double";
    maximumT1 = 3;
elseif phyParams.muNumerology == 2
    defaultT1 = 0.5;
    parameterType = "double";
    maximumT1 = 2.75;
else
    error( ...
        "v2xsim:resource:UnsupportedNumerology", ...
        "Resource allocation supports numerologies 0, 1, and 2.");
end

[simParams,varargin] = addNewParam( ...
    simParams,"T1autonomousMode",defaultT1, ...
    "Selection-window start (ms)",parameterType,fileCfg,varargin{1});
if simParams.T1autonomousMode < defaultT1 || ...
        simParams.T1autonomousMode > maximumT1
    error( ...
        "v2xsim:resource:InvalidSelectionWindow", ...
        "SelectionWindowStartMilliseconds is invalid for this numerology.");
end
[simParams,varargin] = addNewParam( ...
    simParams,"T2autonomousMode",100, ...
    "Selection-window end (ms)","integer",fileCfg,varargin{1});
if simParams.T2autonomousMode < 20 || simParams.T2autonomousMode > 100
    error( ...
        "v2xsim:resource:InvalidSelectionWindow", ...
        "SelectionWindowEndMilliseconds must be between 20 and 100.");
end

slotsPerMillisecond = 2^phyParams.muNumerology;
windowStartSlots = ...
    simParams.T1autonomousMode * slotsPerMillisecond;
windowEndSlots = ...
    simParams.T2autonomousMode * slotsPerMillisecond;
slotAlignmentTolerance = 16 * eps(max( ...
    1,max(abs([windowStartSlots,windowEndSlots]))));
if abs(windowStartSlots - round(windowStartSlots)) > ...
        slotAlignmentTolerance || ...
        abs(windowEndSlots - round(windowEndSlots)) > ...
        slotAlignmentTolerance
    error( ...
        "v2xsim:resource:InvalidSelectionWindow", ...
        "Selection-window bounds must align with slots for the " + ...
        "configured numerology.");
end
simParams.T1autonomousModeTTIs = round(windowStartSlots);
simParams.T2autonomousModeTTIs = round(windowEndSlots);
end

function type = canonicalType(value)
if isnumeric(value) || islogical(value)
    removedNumericAlgorithm();
end
value = string(value);
if ~isscalar(value) || ismissing(value)
    error( ...
        "v2xsim:resource:UnknownAllocatorType", ...
        "resourceAllocation.Type must be a string scalar.");
end
if ~isempty(regexp(value,"^[+-]?\\d+$","once"))
    removedNumericAlgorithm();
end

validTypes = [ ...
    "ReuseDistance", ...
    "MaximumReuseDistance", ...
    "MinimumReusePower", ...
    "ThreeGppAutonomous", ...
    "RandomBenchmark", ...
    "OrderedBenchmark"];
match = find(strcmpi(value,validTypes),1);
if isempty(match)
    error( ...
        "v2xsim:resource:UnknownAllocatorType", ...
        "Unknown resource allocator type ""%s"". Valid types are: %s.", ...
        value,strjoin(validTypes,", "));
end
type = validTypes(match);
end

function validateCapabilities(simParams,phyParams)
type = simParams.resourceAllocationType;
supportsOverlapAndReplicas = ...
    ismember(type,["ThreeGppAutonomous","RandomBenchmark"]);
if phyParams.BRoverlapAllowed && ~supportsOverlapAndReplicas
    error( ...
        "v2xsim:resource:UnsupportedPartialOverlap", ...
        "Partial frequency overlap is supported only by 3GPP and Random.");
end
if phyParams.cv2xNumberOfReplicasMax > 1 && ...
        ~supportsOverlapAndReplicas
    error( ...
        "v2xsim:resource:UnsupportedMultipleTransmissions", ...
        "Multiple transmissions are supported only by 3GPP and Random.");
end
if type == "ThreeGppAutonomous" && ...
        phyParams.cv2xNumberOfReplicasMax > 2
    error( ...
        "v2xsim:resource:UnsupportedMultipleTransmissions", ...
        "3GPP resource allocation supports at most two transmissions.");
end

hasSameBandMitigation = ...
    isfield(simParams,"technology") && ...
    simParams.technology == constants.TECH_COEX_STD_INTERF && ...
    isfield(simParams,"coexMethod") && ...
    simParams.coexMethod ~= constants.COEX_METHOD_NON;
if hasSameBandMitigation && type ~= "ThreeGppAutonomous"
    error( ...
        "v2xsim:resource:UnsupportedCoexistenceAllocator", ...
        "Same-band coexistence mitigation requires ThreeGppAutonomous.");
end
end

function validateExactInterval(value,baseValue,parameterName)
ratio = value / baseValue;
if value <= 0 || ...
        abs(ratio - round(ratio)) > 16 * eps(max(1,abs(ratio)))
    error( ...
        "v2xsim:resource:NonIntegralInterval", ...
        "%s must be a positive exact multiple of %.15g seconds.", ...
        parameterName,baseValue);
end
end

function rejectRemovedConfiguration(fileCfg,arguments)
removedAlgorithmNames = ["resourceAllocation.Algorithm","BRAlgorithm"];
removedFeatureNames = [ ...
    "resourceAllocation.Asynchrony.Mode","asynMode", ...
    "resourceAllocation.Asynchrony.VehicleFraction","percAsynUser", ...
    "resourceAllocation.FullDuplex.Algorithm","FDalgorithm", ...
    "resourceAllocation.FullDuplex.DynamicThresholdMode","dynamicPDelta"];

argumentNames = string(arguments(1:2:end));
if any(ismember(lower(argumentNames),lower(removedAlgorithmNames)))
    removedNumericAlgorithm();
end
typeIndex = find( ...
    strcmpi(argumentNames,"resourceAllocation.Type"),1);
if ~isempty(typeIndex) && ...
        isNumericAlgorithmValue(arguments{2 * typeIndex})
    removedNumericAlgorithm();
end
if any(ismember(lower(argumentNames),lower(removedFeatureNames)))
    error( ...
        "v2xsim:resource:RemovedAllocationFeature", ...
        "Asynchronous and full-duplex allocation enhancements were removed.");
end

for parameterName = removedAlgorithmNames
    [~,found] = searchParamInCfgFile(fileCfg,parameterName,"string");
    if found
        removedNumericAlgorithm();
    end
end
for parameterName = removedFeatureNames
    [~,found] = searchParamInCfgFile(fileCfg,parameterName,"string");
    if found
        error( ...
            "v2xsim:resource:RemovedAllocationFeature", ...
            "Configuration parameter [%s] was removed.",parameterName);
    end
end
[configuredType,typeFound] = searchParamInCfgFile( ...
    fileCfg,"resourceAllocation.Type","string");
if typeFound && isNumericAlgorithmValue(configuredType)
    removedNumericAlgorithm();
end
end

function removedNumericAlgorithm()
error( ...
    "v2xsim:resource:RemovedNumericAlgorithm", ...
    "Numeric resource-allocation algorithms were removed; use " + ...
    "resourceAllocation.Type with a named allocator.");
end

function result = isNumericAlgorithmValue(value)
if isnumeric(value) || islogical(value)
    result = true;
    return
end
if ~ischar(value) && ~isstring(value)
    result = false;
    return
end
value = string(value);
result = isscalar(value) && ~ismissing(value) && ...
    ~isempty(regexp(strip(value),"^[+-]?\d+$","once"));
end
