function [outParams,varargin,outputHookOptions] = ...
        initiateOutParameters(simParams,~,fileCfg,varargin)
% function [outParams,varargin] = initiateOutParameters(fileCfg,varargin)
%
% Settings of the outputs
% It takes in input the name of the (possible) file config and the inputs
% of the main function
% It returns the structure "outParams"

fprintf('Output settings\n');

outputHookOptions = struct( ...
    AverageNeighborCountEnabled=false, ...
    VehicleKinematicsEnabled=false, ...
    PositionErrorTraceEnabled=false, ...
    PositionErrorTraceFlushRowCount=10000, ...
    ControllerDiagnosticsEnabled=false, ...
    ControllerDiagnosticsTopK=10, ...
    ControllerDiagnosticsRankDisplacementEnabled=false, ...
    ControllerDiagnosticsFlushRowCount=5000, ...
    PacketFateTraceEnabled=false, ...
    PacketFateTraceFlushRowCount=10000, ...
    PacketFateTraceFileFormat="parquet", ...
    InterferenceClassificationEnabled=false, ...
    UpdateDelayEnabled=false, ...
    WirelessBlindSpotEnabled=false, ...
    WirelessBlindSpotMaximumDelaySeconds=10, ...
    WirelessBlindSpotBinWidthSeconds=0.1, ...
    PacketDelayEnabled=false, ...
    DataAgeEnabled=false, ...
    DelayBinWidthSeconds=0.001, ...
    PacketReceptionRatioEnabled=false, ...
    PacketReceptionRatioDistanceBinWidthMeters=10, ...
    ChannelBusyRatioEnabled=false);

% [outputFolder]
% Directory exclusively owned by this simulation run. The orchestration
% boundary creates and reserves it after all parameters have been parsed.
[outParams,varargin]= addNewParam([],'outputFolder','Output','Folder for the output files','string',fileCfg,varargin{1});
fprintf('Requested output directory = %s\n',outParams.outputFolder);

% [output.AverageNeighborCount.Enabled]
[averageNeighborCountOutput,varargin] = addNewParam( ...
    [],'output.AverageNeighborCount.Enabled',false, ...
    'Record average neighbor counts over time and across the simulation', ...
    'bool',fileCfg,varargin{1});
outputHookOptions.AverageNeighborCountEnabled = ...
    averageNeighborCountOutput.output.AverageNeighborCount.Enabled;

% [output.VehicleKinematics.Enabled]
[vehicleKinematicsOutput,varargin] = addNewParam( ...
    [],'output.VehicleKinematics.Enabled',false, ...
    'Record vehicle kinematics to a long-form CSV file', ...
    'bool',fileCfg,varargin{1});
outputHookOptions.VehicleKinematicsEnabled = ...
    vehicleKinematicsOutput.output.VehicleKinematics.Enabled;

% [output.PositionErrorTrace.*]
[positionErrorTraceOutput,varargin] = addNewParam( ...
    [],'output.PositionErrorTrace.Enabled',false, ...
    'Record per-vehicle positioning-error and lifecycle diagnostics', ...
    'bool',fileCfg,varargin{1});
[positionErrorTraceOutput,varargin] = addNewParam( ...
    positionErrorTraceOutput,'output.PositionErrorTrace.FlushRowCount', ...
    10000,'Maximum buffered position-error rows per output chunk', ...
    'integer',fileCfg,varargin{1});
if positionErrorTraceOutput.output.PositionErrorTrace. ...
        FlushRowCount < 1
    error( ...
        "v2xsim:hook:InvalidTraceFlushRowCount", ...
        "output.PositionErrorTrace.FlushRowCount must be positive.");
end
outputHookOptions.PositionErrorTraceEnabled = ...
    positionErrorTraceOutput.output.PositionErrorTrace.Enabled;
outputHookOptions.PositionErrorTraceFlushRowCount = ...
    positionErrorTraceOutput.output.PositionErrorTrace.FlushRowCount;

% [output.ControllerDiagnostics.*]
[controllerDiagnosticsOutput,varargin] = addNewParam( ...
    [],'output.ControllerDiagnostics.Enabled',false, ...
    'Record apparent-versus-true controller topology and allocation', ...
    'bool',fileCfg,varargin{1});
[controllerDiagnosticsOutput,varargin] = addNewParam( ...
    controllerDiagnosticsOutput,'output.ControllerDiagnostics.TopK',10, ...
    'Nearest-neighbor set size used by controller diagnostics', ...
    'integer',fileCfg,varargin{1});
[controllerDiagnosticsOutput,varargin] = addNewParam( ...
    controllerDiagnosticsOutput, ...
    'output.ControllerDiagnostics.RankDisplacementEnabled',false, ...
    'Record O(N^2) per-neighbor rank-displacement detail', ...
    'bool',fileCfg,varargin{1});
[controllerDiagnosticsOutput,varargin] = addNewParam( ...
    controllerDiagnosticsOutput, ...
    'output.ControllerDiagnostics.FlushRowCount',5000, ...
    'Maximum buffered controller-diagnostic rows', ...
    'integer',fileCfg,varargin{1});
if controllerDiagnosticsOutput.output.ControllerDiagnostics.TopK < 1 || ...
        controllerDiagnosticsOutput.output.ControllerDiagnostics. ...
            FlushRowCount < 1
    error( ...
        "v2xsim:hook:InvalidControllerDiagnosticOption", ...
        "Controller TopK and FlushRowCount must be positive.");
end
outputHookOptions.ControllerDiagnosticsEnabled = ...
    controllerDiagnosticsOutput.output.ControllerDiagnostics.Enabled;
outputHookOptions.ControllerDiagnosticsTopK = ...
    controllerDiagnosticsOutput.output.ControllerDiagnostics.TopK;
outputHookOptions.ControllerDiagnosticsRankDisplacementEnabled = ...
    controllerDiagnosticsOutput.output.ControllerDiagnostics. ...
        RankDisplacementEnabled;
outputHookOptions.ControllerDiagnosticsFlushRowCount = ...
    controllerDiagnosticsOutput.output.ControllerDiagnostics. ...
        FlushRowCount;

% [output.PacketFateTrace.*]
[packetFateTraceOutput,varargin] = addNewParam( ...
    [],'output.PacketFateTrace.Enabled',false, ...
    'Record terminal directed packet outcomes with stable UE identity', ...
    'bool',fileCfg,varargin{1});
[packetFateTraceOutput,varargin] = addNewParam( ...
    packetFateTraceOutput,'output.PacketFateTrace.FlushRowCount',10000, ...
    'Maximum buffered packet-fate rows per output chunk', ...
    'integer',fileCfg,varargin{1});
if packetFateTraceOutput.output.PacketFateTrace.FlushRowCount < 1
    error( ...
        "v2xsim:hook:InvalidTraceFlushRowCount", ...
        "output.PacketFateTrace.FlushRowCount must be positive.");
end
outputHookOptions.PacketFateTraceEnabled = ...
    packetFateTraceOutput.output.PacketFateTrace.Enabled;
outputHookOptions.PacketFateTraceFlushRowCount = ...
    packetFateTraceOutput.output.PacketFateTrace.FlushRowCount;
[packetFateTraceOutput,varargin] = addNewParam( ...
    packetFateTraceOutput,'output.PacketFateTrace.FileFormat','parquet', ...
    'Packet-fate trace chunk format: parquet or csv', ...
    'string',fileCfg,varargin{1});
packetFateTraceFileFormat = lower(string( ...
    packetFateTraceOutput.output.PacketFateTrace.FileFormat));
if ~isscalar(packetFateTraceFileFormat) || ...
        ~ismember(packetFateTraceFileFormat,["parquet","csv"])
    error( ...
        "v2xsim:hook:InvalidPacketFateTraceFormat", ...
        "output.PacketFateTrace.FileFormat must be parquet or csv.");
end
outputHookOptions.PacketFateTraceFileFormat = ...
    packetFateTraceFileFormat;

% [output.InterferenceClassification.Enabled]
% This enables the allocator, packet, and causal C-V2X PHY evidence
% traces. Exposed-terminal labels still require an explicit complete
% shadow decode-probability model in the analysis layer.
[interferenceClassificationOutput,varargin] = addNewParam( ...
    [],'output.InterferenceClassification.Enabled',false, ...
    'Record causal C-V2X interference evidence and source traces', ...
    'bool',fileCfg,varargin{1});
outputHookOptions.InterferenceClassificationEnabled = ...
    interferenceClassificationOutput.output. ...
        InterferenceClassification.Enabled;
if outputHookOptions.InterferenceClassificationEnabled
    outputHookOptions.PositionErrorTraceEnabled = true;
    outputHookOptions.ControllerDiagnosticsEnabled = true;
    outputHookOptions.PacketFateTraceEnabled = true;
end

% [printUpdateDelay]
% Boolean to activate the print to file of the update delay between received beacons
[outParams,varargin]= addNewParam(outParams,'printUpdateDelay',false,'Activate the print to file of the update delay between received beacons','bool',fileCfg,varargin{1});
outputHookOptions.UpdateDelayEnabled = outParams.printUpdateDelay;

% [printWirelessBlindSpotProb]
% Boolean to activate the print to file of the wireless blind spot probability
[outParams,varargin]= addNewParam(outParams,'printWirelessBlindSpotProb',false,'Activate the print to file of the wireless blind spot probability','bool',fileCfg,varargin{1});
outputHookOptions.WirelessBlindSpotEnabled = ...
    outParams.printWirelessBlindSpotProb;
if outParams.printWirelessBlindSpotProb
    % [delayWBSmax]
    % Maximum recordable delay for wireless blind spot probability (s)
    [outParams,varargin]= addNewParam(outParams,'delayWBSmax',10,'Maximum recordable delay for wireless blind spot probability (s)','double',fileCfg,varargin{1});
    if outParams.delayWBSmax<=0
        error('Error: "outParams.delayWBSmax" cannot be <= 0');
    end
    outputHookOptions.WirelessBlindSpotMaximumDelaySeconds = ...
        outParams.delayWBSmax;
    % [delayWBSresolution]
    % Maximum recordable delay for wireless blind spot probability (s)
    [outParams,varargin]= addNewParam(outParams,'delayWBSresolution',0.1,'Resolution of wireless blind spot probability (s)','double',fileCfg,varargin{1});
    if outParams.delayWBSresolution > outParams.delayWBSmax
        error('Error: "outParams.delayWBSresolution > outParams.delayWBSmax" not acceptable');
    end
    outputHookOptions.WirelessBlindSpotBinWidthSeconds = ...
        outParams.delayWBSresolution;
end

% [printPacketDelay]
% Boolean to activate the print to file of the packet delay between received beacons
[outParams,varargin]= addNewParam(outParams,'printPacketDelay',false,'Activate the print to file of the packet delay between received beacons','bool',fileCfg,varargin{1});
outputHookOptions.PacketDelayEnabled = outParams.printPacketDelay;

% [printDataAge]
% Boolean to activate the print to file of the data age of received beacons
[outParams,varargin]= addNewParam(outParams,'printDataAge',false,'Activate the print to file of data age of beacons','bool',fileCfg,varargin{1});
outputHookOptions.DataAgeEnabled = outParams.printDataAge;

% [delayResolution]
% Delay resolution (s)
if outParams.printUpdateDelay || outParams.printDataAge || ...
        outParams.printPacketDelay
    [outParams,varargin]= addNewParam(outParams,'delayResolution',0.001,'Delay resolution (s)','double',fileCfg,varargin{1});
    if outParams.delayResolution<=0
        error('Error: "outParams.delayResolution" cannot be <= 0');
    end
    outputHookOptions.DelayBinWidthSeconds = ...
        outParams.delayResolution;
end

% [printPacketReceptionRatio]
% Boolean to activate the print to file of the details for distances from 0
% up to the maximum awareness range
[outParams,varargin]= addNewParam(outParams,'printPacketReceptionRatio',false,'Activate the print to file of detailed PRR up to the maximum awareness range','bool',fileCfg,varargin{1});
outputHookOptions.PacketReceptionRatioEnabled = ...
    outParams.printPacketReceptionRatio;

if outParams.printPacketReceptionRatio
    % [prrResolution]
    [outParams,varargin]= addNewParam(outParams,'prrResolution',10,'Step of the distance for the calculation of the pdr [m]','integer',fileCfg,varargin{1});
    if outParams.prrResolution<1
        error('prrResolution cannot be zero or negative');
    end
    outputHookOptions.PacketReceptionRatioDistanceBinWidthMeters = ...
        outParams.prrResolution;
end

% [printCBR]
% Boolean to activate the print to file of the channel busy ratio
[outParams,varargin]= addNewParam(outParams,'printCBR',false,'Activate the print to file of the channel busy ratio','bool',fileCfg,varargin{1});
outputHookOptions.ChannelBusyRatioEnabled = outParams.printCBR;
if outParams.printCBR && ~simParams.cbrActive
    error( ...
        "v2xsim:hook:OutputRequiresChannelLoad", ...
        "output.ChannelBusyRatio.Enabled requires " + ...
        "channelLoad.Enabled.");
end

% [message]
[outParams,varargin]= addNewParam(outParams,'message', 'None', 'Message during simulation','string',fileCfg,varargin{1});

% Hook-backed settings are composition inputs, not runtime output state.
hookSettingFields = [ ...
    "printUpdateDelay", ...
    "printWirelessBlindSpotProb", ...
    "delayWBSmax", ...
    "delayWBSresolution", ...
    "printPacketDelay", ...
    "printDataAge", ...
    "delayResolution", ...
    "printPacketReceptionRatio", ...
    "prrResolution", ...
    "printCBR"];
fieldsToRemove = intersect( ...
    string(fieldnames(outParams)),hookSettingFields,"stable");
outParams = rmfield(outParams,cellstr(fieldsToRemove));
fprintf('\n');
%
%%%%%%%%%
