classdef BidirectionalHighwayScenarioTest < matlab.unittest.TestCase
    %BIDIRECTIONALHIGHWAYSCENARIOTEST Tests highway motion invariants.

    methods (TestMethodSetup)
        function preserveGlobalRandomStream(testCase)
            randomStream = RandStream.getGlobalStream();
            originalState = randomStream.State;
            testCase.addTeardown( ...
                @() restoreRandomStreamState(randomStream, originalState));
        end
    end

    methods (Test)
        function testDefaultsCreateValidHighway(testCase)
            scenario = ...
                v2xsim.vehicle.scenarios.BidirectionalHighwayScenario( ...
                    200, RandomSeed=100);
            kinematics = scenario.VehicleKinematics;

            testCase.verifyEqual(scenario.NLanes, 1);
            testCase.verifyEqual(scenario.LaneWidth, 2.5);
            testCase.verifyEqual(scenario.RoadLength, 2000);
            testCase.verifyEqual(scenario.CentralDividerWidth, 0);
            testCase.verifyEqual(scenario.MeanVehicleSpeed, 22.2);
            testCase.verifyEqual( ...
                scenario.VehicleSpeedStandardDeviation, 2.78);
            testCase.verifyTrue(scenario.RerollSpeedOnWrapAround);
            testCase.verifyClass( ...
                scenario.Geometry, ...
                "v2xsim.vehicle.scenario.highway.Geometry");
            testCase.verifyClass( ...
                scenario.PlacementStrategy, ...
                "v2xsim.vehicle.scenario.highway.placement.Random");
            testCase.verifyClass( ...
                scenario.MobilityModel, ...
                "v2xsim.vehicle.scenario.highway.mobility.RerollingSpeed");
            testCase.verifyTrue(isa( ...
                scenario, "v2xsim.vehicle.scenario.LanedScenario"));
            testCase.verifyEqual(scenario.LaneNetwork.LaneCount, 2);
            testCase.verifyEqual( ...
                height(scenario.VehicleLaneStates), height(kinematics));
            testCase.verifyLaneStateMatchesKinematics(scenario);
            testCase.verifyEqual(height(kinematics), 200);
            testCase.verifyGreaterThanOrEqual(kinematics.X, 0);
            testCase.verifyLessThanOrEqual(kinematics.X, 2000);
            testCase.verifyEqual(kinematics.vY, zeros(200, 1));
            testCase.verifyEqual(abs(kinematics.Y), 1.25 .* ones(200, 1));
            testCase.verifyEqual(sign(kinematics.vX), sign(kinematics.Y));
        end

        function testVehiclesSpawnAtValidLaneCenters(testCase)
            nLanes = 4;
            laneWidth = 3.5;
            dividerWidth = 2;
            expectedAbsoluteY = ...
                dividerWidth ./ 2 + ((1:nLanes) - 0.5) .* laneWidth;

            scenario = ...
                v2xsim.vehicle.scenarios.BidirectionalHighwayScenario( ...
                    1000, ...
                    RandomSeed=200, ...
                    NLanes=nLanes, ...
                    LaneWidth=laneWidth, ...
                    CentralDividerWidth=dividerWidth);
            actualAbsoluteY = abs(scenario.VehicleKinematics.Y);

            testCase.verifyTrue(all( ...
                ismember(actualAbsoluteY, expectedAbsoluteY)));
        end

        function testLaneInvariantsHoldAcrossManyWraps(testCase)
            scenario = ...
                v2xsim.vehicle.scenarios.BidirectionalHighwayScenario( ...
                    250, ...
                    RandomSeed=300, ...
                    NLanes=3, ...
                    LaneWidth=3, ...
                    RoadLength=50, ...
                    CentralDividerWidth=1, ...
                    MeanVehicleSpeed=80, ...
                    VehicleSpeedStandardDeviation=10, ...
                    RerollSpeedOnWrapAround=true);
            initialY = scenario.VehicleKinematics.Y;

            for stepIndex = 1:20
                scenario = scenario.step(0.75);
                kinematics = scenario.VehicleKinematics;

                testCase.verifyEqual(kinematics.Y, initialY, ...
                    sprintf("Y changed at step %d.", stepIndex));
                testCase.verifyEqual(kinematics.vY, zeros(250, 1), ...
                    sprintf("vY was nonzero at step %d.", stepIndex));
                testCase.verifyGreaterThanOrEqual(kinematics.X, 0);
                testCase.verifyLessThanOrEqual(kinematics.X, 50);
                testCase.verifyLaneStateMatchesKinematics(scenario);
            end
        end

        function testDisabledRerollPreservesSpeedAndWrapsPosition(testCase)
            scenario = ...
                v2xsim.vehicle.scenarios.BidirectionalHighwayScenario( ...
                    100, ...
                    RandomSeed=400, ...
                    RoadLength=25, ...
                    RerollSpeedOnWrapAround=false);
            initialKinematics = scenario.VehicleKinematics;
            deltaTime = 10;
            expectedX = mod( ...
                initialKinematics.X + initialKinematics.vX .* deltaTime, ...
                scenario.RoadLength);

            scenario = scenario.step(deltaTime);

            testCase.verifyEqual(scenario.VehicleKinematics.X, expectedX, ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                abs(scenario.VehicleKinematics.vX), ...
                abs(initialKinematics.vX));
            testCase.verifyEqual( ...
                scenario.VehicleKinematics.Y, initialKinematics.Y);
        end

        function testEnabledRerollChangesSpeedAfterWrapping(testCase)
            scenario = ...
                v2xsim.vehicle.scenarios.BidirectionalHighwayScenario( ...
                    50, ...
                    RandomSeed=500, ...
                    RoadLength=0.01, ...
                    MeanVehicleSpeed=10, ...
                    VehicleSpeedStandardDeviation=2, ...
                    RerollSpeedOnWrapAround=true);
            initialSpeed = abs(scenario.VehicleKinematics.vX);

            scenario = scenario.step(0.1);
            finalSpeed = abs(scenario.VehicleKinematics.vX);

            testCase.verifyTrue(any(finalSpeed ~= initialSpeed));
        end

        function testSameSeedMakesStochasticEvolutionRepeatable(testCase)
            firstScenario = ...
                v2xsim.vehicle.scenarios.BidirectionalHighwayScenario( ...
                    100, ...
                    RandomSeed=600, ...
                    NLanes=2, ...
                    RoadLength=5);
            secondScenario = ...
                v2xsim.vehicle.scenarios.BidirectionalHighwayScenario( ...
                    100, ...
                    RandomSeed=600, ...
                    NLanes=2, ...
                    RoadLength=5);

            testCase.verifyEqual( ...
                firstScenario.VehicleKinematics, ...
                secondScenario.VehicleKinematics);

            for stepIndex = 1:5
                firstScenario = firstScenario.step(0.25);
                secondScenario = secondScenario.step(0.25);

                testCase.verifyEqual( ...
                    firstScenario.VehicleKinematics, ...
                    secondScenario.VehicleKinematics, ...
                    sprintf( ...
                        "Traffic diverged at step %d.", stepIndex));
                testCase.verifyEqual( ...
                    firstScenario.VehicleLaneStates, ...
                    secondScenario.VehicleLaneStates);
            end
        end

        function testDifferentSeedsCreateDifferentTraffic(testCase)
            firstScenario = ...
                v2xsim.vehicle.scenarios.BidirectionalHighwayScenario( ...
                    100, RandomSeed=600, NLanes=2);
            secondScenario = ...
                v2xsim.vehicle.scenarios.BidirectionalHighwayScenario( ...
                    100, RandomSeed=601, NLanes=2);

            testCase.verifyNotEqual( ...
                firstScenario.VehicleKinematics{:, :}, ...
                secondScenario.VehicleKinematics{:, :});
        end

        function testFixedSeedIsIndependentOfGlobalStream(testCase)
            globalStream = RandStream.getGlobalStream();
            stateBeforeFirstScenario = globalStream.State;

            firstScenario = ...
                v2xsim.vehicle.scenarios.BidirectionalHighwayScenario( ...
                    100, RandomSeed=602, RoadLength=5);
            firstScenario = firstScenario.step(0.25);

            testCase.verifyEqual( ...
                globalStream.State, stateBeforeFirstScenario);

            rand(globalStream, 100, 1);
            stateAfterGlobalConsumption = globalStream.State;

            secondScenario = ...
                v2xsim.vehicle.scenarios.BidirectionalHighwayScenario( ...
                    100, RandomSeed=602, RoadLength=5);
            secondScenario = secondScenario.step(0.25);

            testCase.verifyEqual( ...
                secondScenario.VehicleKinematics, ...
                firstScenario.VehicleKinematics);
            testCase.verifyEqual( ...
                globalStream.State, stateAfterGlobalConsumption);
        end
    end

    methods (Access = private)
        function verifyLaneStateMatchesKinematics(testCase, scenario)
            laneStates = scenario.VehicleLaneStates;
            expectedPositions = scenario.LaneNetwork.evaluate( ...
                laneStates.LaneId, laneStates.Progress);
            actualPositions = [ ...
                scenario.VehicleKinematics.X, ...
                scenario.VehicleKinematics.Y];

            testCase.verifyEqual( ...
                actualPositions, expectedPositions, AbsTol=1e-10);
        end
    end
end

function restoreRandomStreamState(randomStream, state)
randomStream.State = state;
end
