classdef ExitRampHighwayScenarioTest < matlab.unittest.TestCase
    %EXITRAMPHIGHWAYSCENARIOTEST Tests diverge and merge invariants.

    methods (TestMethodSetup)
        function preserveGlobalRandomStream(testCase)
            randomStream = RandStream.getGlobalStream();
            originalState = randomStream.State;
            testCase.addTeardown( ...
                @() restoreRandomStreamState(randomStream, originalState));
        end
    end

    methods (Test)
        function testDefaultsExposeComposedRampModel(testCase)
            scenario = ...
                v2xsim.vehicle.scenarios.ExitRampHighwayScenario( ...
                    200, ...
                    RandomSeed=100);

            testCase.verifyClass( ...
                scenario.Geometry, ...
                "v2xsim.vehicle.scenario.highway.ExitRampGeometry");
            testCase.verifyClass( ...
                scenario.MobilityModel, ...
                "v2xsim.vehicle.scenario.highway.mobility.ExitRamp");
            testCase.verifyClass( ...
                scenario.PlacementStrategy, ...
                "v2xsim.vehicle.scenario.highway.placement.ExitRampRandom");
            testCase.verifyEqual(scenario.NLanes, 2);
            testCase.verifyEqual(scenario.ExitProbability, 0.5);
            testCase.verifyEqual(scenario.MergeDistance, 100);
            testCase.verifyEqual(scenario.Geometry.ForkX, 1000);
            testCase.verifyEqual( ...
                scenario.Geometry.RampAngleDegrees, 45);
            testCase.verifyEqual( ...
                scenario.Geometry.RampLength, 2000 ./ sqrt(2), ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                height(scenario.MobilityModel.VehicleRoutes), 200);
            testCase.verifyEqual( ...
                scenario.VehicleRouteStates, ...
                scenario.MobilityModel.VehicleRoutes(:, ...
                    ["TravelDirection", "Route"]));
            testCase.verifyTrue(isa( ...
                scenario, "v2xsim.vehicle.scenario.LanedScenario"));
            testCase.verifyEqual(scenario.LaneNetwork.LaneCount, 8);
            testCase.verifyEqual( ...
                height(scenario.LaneNetwork.Connections), 6);
            testCase.verifyLaneStateMatchesKinematics(scenario);
        end

        function testExitOnlyVehiclesFollowRampAndRetainHomeLanes(testCase)
            scenario = ...
                v2xsim.vehicle.scenarios.ExitRampHighwayScenario( ...
                    1000, ...
                    RandomSeed=200, ...
                    RoadLength=200, ...
                    MeanVehicleSpeed=20, ...
                    VehicleSpeedStandardDeviation=0, ...
                    RerollSpeedOnWrapAround=false, ...
                    ExitProbability=1, ...
                    MergeDistance=40);
            initialRoutes = scenario.MobilityModel.VehicleRoutes;

            for stepIndex = 1:10
                scenario = scenario.step(0.75);
                routes = scenario.MobilityModel.VehicleRoutes;

                testCase.verifyEqual( ...
                    routes.HomeLaneIndex, initialRoutes.HomeLaneIndex);
                testCase.verifyEqual( ...
                    routes.TravelDirection, initialRoutes.TravelDirection);
                testCase.verifyFalse(any( ...
                    ismember(routes.Route, ["Merge", "Adjacent"])));
                testCase.verifyRampRouteInvariants(scenario);
                testCase.verifyLaneStateMatchesKinematics(scenario);
            end
        end

        function testNonExitingVehiclesMergeSmoothly(testCase)
            scenario = ...
                v2xsim.vehicle.scenarios.ExitRampHighwayScenario( ...
                    1000, ...
                    RandomSeed=300, ...
                    RoadLength=200, ...
                    MeanVehicleSpeed=20, ...
                    VehicleSpeedStandardDeviation=0, ...
                    RerollSpeedOnWrapAround=false, ...
                    ExitProbability=0, ...
                    MergeDistance=40);
            routes = scenario.MobilityModel.VehicleRoutes;
            mergeVehicles = routes.Route == "Merge";

            testCase.verifyTrue(any(mergeVehicles));
            testCase.verifyFalse(any(routes.Route == "Ramp"));
            testCase.verifyMergeRouteInvariants(scenario);

            initialHomeLanes = routes.HomeLaneIndex;
            for stepIndex = 1:10
                scenario = scenario.step(0.75);
                routes = scenario.MobilityModel.VehicleRoutes;
                testCase.verifyEqual(routes.HomeLaneIndex, initialHomeLanes);
                testCase.verifyFalse(any(routes.Route == "Ramp"));
                testCase.verifyMergeRouteInvariants(scenario);
                testCase.verifyLaneStateMatchesKinematics(scenario);
            end
        end

        function testZeroMergeDistanceSnapsAtFork(testCase)
            scenario = ...
                v2xsim.vehicle.scenarios.ExitRampHighwayScenario( ...
                    1000, ...
                    RandomSeed=400, ...
                    RoadLength=100, ...
                    MeanVehicleSpeed=20, ...
                    VehicleSpeedStandardDeviation=0, ...
                    RerollSpeedOnWrapAround=false, ...
                    ExitProbability=0, ...
                    MergeDistance=0);
            laneCenters = scenario.Geometry.getAbsoluteLaneCenters();
            testCase.verifyEqual(scenario.LaneNetwork.LaneCount, 6);
            testCase.verifyEqual( ...
                height(scenario.LaneNetwork.Connections), 4);

            for stepIndex = 1:5
                routes = scenario.MobilityModel.VehicleRoutes;
                testCase.verifyFalse(any(routes.Route == "Merge"));
                testCase.verifyFalse(any(routes.Route == "Ramp"));
                testCase.verifyTrue(all(ismember( ...
                    abs(scenario.VehicleKinematics.Y), laneCenters)));
                testCase.verifyEqual( ...
                    scenario.VehicleKinematics.vY, zeros(1000, 1));
                testCase.verifyLaneStateMatchesKinematics(scenario);
                scenario = scenario.step(0.5);
            end
        end

        function testRampEndpointRecyclesWithRemainingStepTime(testCase)
            speed = 10;
            roadLength = 200;
            scenario = ...
                v2xsim.vehicle.scenarios.ExitRampHighwayScenario( ...
                    500, ...
                    RandomSeed=500, ...
                    RoadLength=roadLength, ...
                    MeanVehicleSpeed=speed, ...
                    VehicleSpeedStandardDeviation=0, ...
                    RerollSpeedOnWrapAround=false, ...
                    ExitProbability=1, ...
                    MergeDistance=20);
            routes = scenario.MobilityModel.VehicleRoutes;
            vehicleIndex = find(routes.Route == "Ramp", 1);
            testCase.assertNotEmpty(vehicleIndex);

            rowName = routes.Properties.RowNames{vehicleIndex};
            direction = routes.TravelDirection(vehicleIndex);
            horizontalProgress = direction .* ...
                (scenario.VehicleKinematics.X(vehicleIndex) - ...
                scenario.Geometry.ForkX);
            timeToRampEndpoint = sqrt(2) .* ...
                (roadLength ./ 2 - horizontalProgress) ./ speed;
            extraTime = 1;

            scenario = scenario.step(timeToRampEndpoint + extraTime);
            route = scenario.MobilityModel.VehicleRoutes(rowName, :);
            kinematics = scenario.VehicleKinematics(rowName, :);
            upstreamX = (direction < 0) .* roadLength;

            testCase.verifyEqual(route.Route, "Outer");
            testCase.verifyEqual( ...
                kinematics.X, upstreamX + direction .* speed .* extraTime, ...
                AbsTol=1e-10);
            testCase.verifyEqual( ...
                kinematics.Y, ...
                direction .* scenario.Geometry.OuterLaneCenter, ...
                AbsTol=1e-10);
        end

        function testSameSeedMakesStochasticEvolutionRepeatable(testCase)
            firstScenario = ...
                v2xsim.vehicle.scenarios.ExitRampHighwayScenario( ...
                    200, ...
                    RandomSeed=600, ...
                    RoadLength=50, ...
                    MeanVehicleSpeed=20, ...
                    VehicleSpeedStandardDeviation=3, ...
                    ExitProbability=0.5, ...
                    MergeDistance=10);
            secondScenario = ...
                v2xsim.vehicle.scenarios.ExitRampHighwayScenario( ...
                    200, ...
                    RandomSeed=600, ...
                    RoadLength=50, ...
                    MeanVehicleSpeed=20, ...
                    VehicleSpeedStandardDeviation=3, ...
                    ExitProbability=0.5, ...
                    MergeDistance=10);

            testCase.verifyEqual( ...
                firstScenario.VehicleKinematics, ...
                secondScenario.VehicleKinematics);
            testCase.verifyEqual( ...
                firstScenario.MobilityModel.VehicleRoutes, ...
                secondScenario.MobilityModel.VehicleRoutes);

            for stepIndex = 1:5
                firstScenario = firstScenario.step(0.5);
                secondScenario = secondScenario.step(0.5);

                testCase.verifyEqual( ...
                    firstScenario.VehicleKinematics, ...
                    secondScenario.VehicleKinematics, ...
                    sprintf( ...
                        "Traffic diverged at step %d.", stepIndex));
                testCase.verifyEqual( ...
                    firstScenario.VehicleLaneStates, ...
                    secondScenario.VehicleLaneStates);
                testCase.verifyEqual( ...
                    firstScenario.MobilityModel.VehicleRoutes, ...
                    secondScenario.MobilityModel.VehicleRoutes);
            end
        end

        function testDifferentSeedsCreateDifferentTraffic(testCase)
            firstScenario = ...
                v2xsim.vehicle.scenarios.ExitRampHighwayScenario( ...
                    200, RandomSeed=600, RoadLength=200);
            secondScenario = ...
                v2xsim.vehicle.scenarios.ExitRampHighwayScenario( ...
                    200, RandomSeed=601, RoadLength=200);

            testCase.verifyNotEqual( ...
                firstScenario.VehicleKinematics{:, :}, ...
                secondScenario.VehicleKinematics{:, :});
            testCase.verifyNotEqual( ...
                firstScenario.VehicleRouteStates.Route, ...
                secondScenario.VehicleRouteStates.Route);
        end

        function testFixedSeedIsIndependentOfGlobalStream(testCase)
            globalStream = RandStream.getGlobalStream();
            stateBeforeFirstScenario = globalStream.State;

            firstScenario = ...
                v2xsim.vehicle.scenarios.ExitRampHighwayScenario( ...
                    200, ...
                    RandomSeed=602, ...
                    RoadLength=50, ...
                    MeanVehicleSpeed=20, ...
                    VehicleSpeedStandardDeviation=3, ...
                    ExitProbability=0.5, ...
                    MergeDistance=10);
            firstScenario = firstScenario.step(0.5);

            testCase.verifyEqual( ...
                globalStream.State, stateBeforeFirstScenario);

            rand(globalStream, 100, 1);
            stateAfterGlobalConsumption = globalStream.State;

            secondScenario = ...
                v2xsim.vehicle.scenarios.ExitRampHighwayScenario( ...
                    200, ...
                    RandomSeed=602, ...
                    RoadLength=50, ...
                    MeanVehicleSpeed=20, ...
                    VehicleSpeedStandardDeviation=3, ...
                    ExitProbability=0.5, ...
                    MergeDistance=10);
            secondScenario = secondScenario.step(0.5);

            testCase.verifyEqual( ...
                secondScenario.VehicleKinematics, ...
                firstScenario.VehicleKinematics);
            testCase.verifyEqual( ...
                secondScenario.MobilityModel.VehicleRoutes, ...
                firstScenario.MobilityModel.VehicleRoutes);
            testCase.verifyEqual( ...
                globalStream.State, stateAfterGlobalConsumption);
        end

        function testRejectsInvalidRampConfiguration(testCase)
            testCase.verifyError( ...
                @() v2xsim.vehicle.scenarios.ExitRampHighwayScenario( ...
                    10, NLanes=1), ...
                "v2xsim:scenario:highway:ExitRampNeedsTwoLanes");
            testCase.verifyError( ...
                @() v2xsim.vehicle.scenarios.ExitRampHighwayScenario( ...
                    10, RoadLength=100, MergeDistance=51), ...
                "v2xsim:scenario:highway:MergeDistanceTooLong");
            testCase.verifyError( ...
                @() v2xsim.vehicle.scenarios.ExitRampHighwayScenario( ...
                    10, ExitProbability=1.1), ...
                "v2xsim:scenario:highway:InvalidExitProbability");
        end
    end

    methods (Access = private)
        function verifyRampRouteInvariants(testCase, scenario)
            routes = scenario.MobilityModel.VehicleRoutes;
            kinematics = scenario.VehicleKinematics;
            onRamp = routes.Route == "Ramp";
            direction = routes.TravelDirection(onRamp);
            horizontalProgress = direction .* ...
                (kinematics.X(onRamp) - scenario.Geometry.ForkX);

            testCase.verifyGreaterThanOrEqual(horizontalProgress, 0);
            testCase.verifyLessThanOrEqual( ...
                horizontalProgress, scenario.RoadLength ./ 2);
            testCase.verifyEqual( ...
                kinematics.Y(onRamp), ...
                direction .* (scenario.Geometry.OuterLaneCenter + ...
                horizontalProgress), ...
                AbsTol=1e-10);
            testCase.verifyEqual( ...
                kinematics.vX(onRamp), kinematics.vY(onRamp), ...
                AbsTol=1e-10);
        end

        function verifyMergeRouteInvariants(testCase, scenario)
            routes = scenario.MobilityModel.VehicleRoutes;
            kinematics = scenario.VehicleKinematics;
            onMerge = routes.Route == "Merge";
            direction = routes.TravelDirection(onMerge);
            horizontalProgress = direction .* ...
                (kinematics.X(onMerge) - scenario.Geometry.ForkX);
            expectedY = scenario.Geometry.getMergeY( ...
                direction, horizontalProgress);

            testCase.verifyGreaterThanOrEqual(horizontalProgress, 0);
            testCase.verifyLessThanOrEqual( ...
                horizontalProgress, scenario.MergeDistance);
            testCase.verifyEqual( ...
                kinematics.Y(onMerge), expectedY, AbsTol=1e-10);
            testCase.verifyLessThanOrEqual( ...
                direction .* kinematics.vY(onMerge), 0);
        end

        function verifyLaneStateMatchesKinematics(testCase, scenario)
            laneStates = scenario.VehicleLaneStates;
            expectedPositions = scenario.LaneNetwork.evaluate( ...
                laneStates.LaneId, laneStates.Progress);
            actualPositions = [ ...
                scenario.VehicleKinematics.X, ...
                scenario.VehicleKinematics.Y];

            testCase.verifyEqual( ...
                actualPositions, expectedPositions, AbsTol=1e-9);
        end
    end
end

function restoreRandomStreamState(randomStream, state)
randomStream.State = state;
end
