classdef RoundaboutScenarioTest < matlab.unittest.TestCase
    %ROUNDABOUTSCENARIOTEST Route, stepping, and randomness contracts.

    methods (TestMethodSetup)
        function preserveGlobalRandomStream(testCase)
            randomStream = RandStream.getGlobalStream();
            originalState = randomStream.State;
            testCase.addTeardown( ...
                @() restoreRandomStreamState(randomStream, originalState));
        end
    end

    methods (Test)
        function testDefaultsExposeNormalizedRoundaboutState(testCase)
            scenario = ...
                v2xsim.vehicle.scenarios.RoundaboutScenario(4096);

            testCase.verifyEqual( ...
                scenario.ExitLengths, [500, 500, 500, 500]);
            testCase.verifySize(scenario.ExitLengths, [1, 4]);
            testCase.verifyEqual(scenario.RoadWidth, 4);
            testCase.verifyEqual(scenario.InnerCircleDiameter, 60);
            testCase.verifyEqual(scenario.MeanVehicleSpeed, 20);
            testCase.verifyEqual( ...
                scenario.VehicleSpeedStandardDeviation, 2);
            testCase.verifyTrue(scenario.RerollSpeedOnWrapAround);
            testCase.verifyFalse(scenario.CAN_STEP_BACKWARD);
            testCase.verifyFalse(scenario.PROVIDES_ACCELERATION);
            testCase.verifyTrue(scenario.PROVIDES_VELOCITY);
            testCase.verifyFalse(scenario.IS_VEHICLE_COUNT_DYNAMIC);
            testCase.verifyEqual(scenario.LaneNetwork.LaneCount, 16);
            testCase.verifyEqual( ...
                height(scenario.LaneNetwork.Connections), 16);

            routes = scenario.VehicleRouteStates;
            testCase.verifyEqual( ...
                string(routes.Properties.VariableNames), ...
                ["EntryArm", "ExitArm", "Stage"]);
            testCase.verifyTrue(all(ismember( ...
                routes.EntryArm, scenario.Geometry.ArmNames)));
            testCase.verifyTrue(all(ismember( ...
                routes.ExitArm, scenario.Geometry.ArmNames)));
            expectedStages = [ ...
                "Inbound", "EntryConnector", "Circulating", ...
                "ExitConnector", "Outbound"];
            testCase.verifyTrue(all(ismember(routes.Stage, expectedStages)));
            testCase.verifyEqual(sort(unique(routes.Stage)), ...
                sort(expectedStages(:)));
            testCase.verifyLaneStateAndVelocityCoherence(scenario);
        end

        function testColumnExitLengthsNormalizeInPublicProperty(testCase)
            scenario = ...
                v2xsim.vehicle.scenarios.RoundaboutScenario( ...
                    10, ExitLengths=[100; 200; 300; 400]);

            testCase.verifyEqual( ...
                scenario.ExitLengths, [100, 200, 300, 400]);
            testCase.verifySize(scenario.ExitLengths, [1, 4]);
        end

        function testUniformSamplingIncludesAllSixteenRoutesAndUTurns( ...
                testCase)
            vehicleCount = 8192;
            scenario = ...
                v2xsim.vehicle.scenarios.RoundaboutScenario( ...
                    vehicleCount, RandomSeed=700);
            routes = scenario.VehicleRouteStates;
            expectedPerRoute = vehicleCount ./ 16;

            routeCount = 0;
            for entryArm = scenario.Geometry.ArmNames
                for exitArm = scenario.Geometry.ArmNames
                    count = nnz(routes.EntryArm == entryArm & ...
                        routes.ExitArm == exitArm);
                    testCase.verifyGreaterThan(count, ...
                        0.8 .* expectedPerRoute);
                    testCase.verifyLessThan(count, ...
                        1.2 .* expectedPerRoute);
                    routeCount = routeCount + double(count > 0);
                end
            end

            testCase.verifyEqual(routeCount, 16);
            testCase.verifyTrue(any( ...
                routes.EntryArm == routes.ExitArm));

            normalizedDistance = zeros(vehicleCount, 1);
            for vehicleIndex = 1:vehicleCount
                route = routes(vehicleIndex, :);
                entryIndex = find( ...
                    scenario.Geometry.ArmNames == route.EntryArm, 1);
                exitIndex = find( ...
                    scenario.Geometry.ArmNames == route.ExitArm, 1);
                exitStep = mod(exitIndex - entryIndex - 1, 4) + 1;
                totalDistance = ...
                    scenario.Geometry.ApproachLaneLengths(entryIndex) + ...
                    exitStep .* ...
                    scenario.Geometry.EntryToExitArcLength + ...
                    (exitStep - 1) .* ...
                    scenario.Geometry.ExitToEntryArcLength + ...
                    scenario.Geometry.ExitLaneLengths(exitIndex);
                remainingDistance = ...
                    testCase.getRemainingRouteDistance( ...
                        scenario.Geometry, ...
                        scenario.VehicleLaneStates(vehicleIndex, :), ...
                        route);
                normalizedDistance(vehicleIndex) = ...
                    1 - remainingDistance ./ totalDistance;
            end
            binCounts = histcounts(normalizedDistance, 0:0.1:1);
            expectedPerBin = vehicleCount ./ 10;
            testCase.verifyGreaterThan( ...
                binCounts, 0.8 .* expectedPerBin);
            testCase.verifyLessThan( ...
                binCounts, 1.2 .* expectedPerBin);
            testCase.verifyEqual( ...
                mean(normalizedDistance), 0.5, AbsTol=0.02);
        end

        function testRecycleConsumesLeftoverTimeOnNewRoute(testCase)
            speed = 10;
            scenario = ...
                v2xsim.vehicle.scenarios.RoundaboutScenario( ...
                    1, ...
                    RandomSeed=701, ...
                    ExitLengths=100, ...
                    MeanVehicleSpeed=speed, ...
                    VehicleSpeedStandardDeviation=0, ...
                    RerollSpeedOnWrapAround=false);
            laneState = scenario.VehicleLaneStates(1, :);
            routeState = scenario.VehicleRouteStates(1, :);
            distanceToOutboundEnd = ...
                testCase.getRemainingRouteDistance( ...
                    scenario.Geometry, laneState, routeState);
            extraDistance = 1;

            scenario = scenario.step( ...
                (distanceToOutboundEnd + extraDistance) ./ speed);

            newRoute = scenario.VehicleRouteStates(1, :);
            newLaneState = scenario.VehicleLaneStates(1, :);
            entryIndex = find( ...
                scenario.Geometry.ArmNames == newRoute.EntryArm, 1);
            testCase.verifyEqual( ...
                newLaneState.LaneId, ...
                scenario.Geometry.getApproachLaneId(newRoute.EntryArm));
            testCase.verifyEqual( ...
                newLaneState.Progress, ...
                extraDistance ./ ...
                scenario.Geometry.ApproachLaneLengths(entryIndex), ...
                AbsTol=1e-10);
            testCase.verifyEqual( ...
                scenario.MobilityModel.VehicleRoutes.Speed, speed);
            testCase.verifyLaneStateAndVelocityCoherence(scenario);
        end

        function testLargeStepPreservesFixedPopulationAndLaneCoherence( ...
                testCase)
            scenario = ...
                v2xsim.vehicle.scenarios.RoundaboutScenario( ...
                    64, ...
                    RandomSeed=702, ...
                    ExitLengths=25, ...
                    MeanVehicleSpeed=25, ...
                    VehicleSpeedStandardDeviation=0, ...
                    RerollSpeedOnWrapAround=false);
            originalRows = sort(string( ...
                scenario.VehicleKinematics.Properties.RowNames));

            [scenario, transitions] = scenario.step(1000);

            testCase.verifyEqual( ...
                sort(string( ...
                scenario.VehicleKinematics.Properties.RowNames)), ...
                originalRows);
            testCase.verifyEqual(height(scenario.VehicleKinematics), 64);
            testCase.verifyEqual(height(transitions), 64);
            testCase.verifyTrue(all(isfinite([ ...
                scenario.VehicleKinematics.X; ...
                scenario.VehicleKinematics.Y; ...
                scenario.VehicleKinematics.vX; ...
                scenario.VehicleKinematics.vY])));
            testCase.verifyLaneStateAndVelocityCoherence(scenario);
        end

        function testSameSeedIsRepeatableAndDoesNotUseGlobalRng(testCase)
            globalStream = RandStream.getGlobalStream();
            stateBefore = globalStream.State;
            options = { ...
                "RandomSeed", 703, ...
                "ExitLengths", 25, ...
                "MeanVehicleSpeed", 20, ...
                "VehicleSpeedStandardDeviation", 3};

            first = v2xsim.vehicle.scenarios.RoundaboutScenario( ...
                200, options{:});
            first = first.step(100);
            testCase.verifyEqual(globalStream.State, stateBefore);

            rand(globalStream, 100, 1);
            stateAfterConsumption = globalStream.State;
            second = v2xsim.vehicle.scenarios.RoundaboutScenario( ...
                200, options{:});
            second = second.step(100);

            testCase.verifyEqual( ...
                second.VehicleKinematics, first.VehicleKinematics);
            testCase.verifyEqual( ...
                second.VehicleLaneStates, first.VehicleLaneStates);
            testCase.verifyEqual( ...
                second.MobilityModel.VehicleRoutes, ...
                first.MobilityModel.VehicleRoutes);
            testCase.verifyEqual( ...
                second.VehicleRouteStates, first.VehicleRouteStates);
            testCase.verifyEqual( ...
                globalStream.State, stateAfterConsumption);
        end

        function testDifferentSeedsProduceDifferentTraffic(testCase)
            first = v2xsim.vehicle.scenarios.RoundaboutScenario( ...
                200, RandomSeed=705);
            second = v2xsim.vehicle.scenarios.RoundaboutScenario( ...
                200, RandomSeed=706);

            testCase.verifyFalse(isequal( ...
                first.VehicleRouteStates(:, ["EntryArm", "ExitArm"]), ...
                second.VehicleRouteStates(:, ["EntryArm", "ExitArm"])));
            testCase.verifyFalse(isequal( ...
                first.VehicleKinematics, second.VehicleKinematics));
        end

        function testConfiguredRerollChangesSpeedsAfterRecycle(testCase)
            scenario = ...
                v2xsim.vehicle.scenarios.RoundaboutScenario( ...
                    32, ...
                    RandomSeed=707, ...
                    ExitLengths=25, ...
                    MeanVehicleSpeed=20, ...
                    VehicleSpeedStandardDeviation=3, ...
                    RerollSpeedOnWrapAround=true);
            initialSpeed = scenario.MobilityModel.VehicleRoutes.Speed;

            scenario = scenario.step(100);
            finalSpeed = scenario.MobilityModel.VehicleRoutes.Speed;

            testCase.verifyTrue(any(finalSpeed ~= initialSpeed));
            testCase.verifyGreaterThanOrEqual(finalSpeed, zeros(32, 1));
            testCase.verifyLaneStateAndVelocityCoherence(scenario);
        end

        function testZeroSpeedVehiclesRemainStationary(testCase)
            scenario = ...
                v2xsim.vehicle.scenarios.RoundaboutScenario( ...
                    50, ...
                    RandomSeed=704, ...
                    MeanVehicleSpeed=0, ...
                    VehicleSpeedStandardDeviation=0);
            originalKinematics = scenario.VehicleKinematics;
            originalLaneStates = scenario.VehicleLaneStates;
            originalRoutes = scenario.VehicleRouteStates;

            scenario = scenario.step(1000);

            testCase.verifyEqual( ...
                scenario.VehicleKinematics, originalKinematics);
            testCase.verifyEqual( ...
                scenario.VehicleLaneStates, originalLaneStates);
            testCase.verifyEqual( ...
                scenario.VehicleRouteStates, originalRoutes);
        end

        function testRejectsInvalidRoundaboutGeometry(testCase)
            testCase.verifyError( ...
                @() v2xsim.vehicle.scenarios.RoundaboutScenario( ...
                    10, ExitLengths=[100, 200]), ...
                "v2xsim:scenario:roundabout:InvalidExitLengths");
            testCase.verifyError( ...
                @() v2xsim.vehicle.scenarios.RoundaboutScenario( ...
                    10, RoadWidth=4, InnerCircleDiameter=7.9), ...
                "v2xsim:scenario:roundabout:InnerCircleTooSmall");
            reference = ...
                v2xsim.vehicle.scenario.roundabout.Geometry(500, 4, 60);
            testCase.verifyError( ...
                @() v2xsim.vehicle.scenarios.RoundaboutScenario( ...
                    10, ...
                    ExitLengths=reference.MinimumExitLength - 1e-6), ...
                "v2xsim:scenario:roundabout:ExitLengthTooShort");
        end
    end

    methods (Access = private)
        function verifyLaneStateAndVelocityCoherence(testCase, scenario)
            laneStates = scenario.VehicleLaneStates;
            expectedPositions = scenario.LaneNetwork.evaluate( ...
                laneStates.LaneId, laneStates.Progress);
            actualPositions = [ ...
                scenario.VehicleKinematics.X, ...
                scenario.VehicleKinematics.Y];
            testCase.verifyEqual( ...
                actualPositions, expectedPositions, AbsTol=1e-9);

            tangents = scenario.Geometry.getLaneTangent( ...
                laneStates.LaneId, laneStates.Progress);
            speed = scenario.MobilityModel.VehicleRoutes( ...
                laneStates.Properties.RowNames, :).Speed;
            expectedVelocity = speed .* tangents;
            actualVelocity = [ ...
                scenario.VehicleKinematics.vX, ...
                scenario.VehicleKinematics.vY];
            testCase.verifyEqual( ...
                actualVelocity, expectedVelocity, AbsTol=1e-10);
        end

        function remaining = getRemainingRouteDistance( ...
                ~, geometry, laneState, routeState)
            entryIndex = find( ...
                geometry.ArmNames == routeState.EntryArm, 1);
            exitIndex = find( ...
                geometry.ArmNames == routeState.ExitArm, 1);
            laneId = laneState.LaneId;
            progress = laneState.Progress;

            if laneId == geometry.getApproachLaneId(routeState.EntryArm)
                exitStep = mod(exitIndex - entryIndex - 1, 4) + 1;
                remaining = ...
                    (1 - progress) .* ...
                    geometry.ApproachLaneLengths(entryIndex) + ...
                    exitStep .* geometry.EntryToExitArcLength + ...
                    (exitStep - 1) .* ...
                    geometry.ExitToEntryArcLength + ...
                    geometry.ExitLaneLengths(exitIndex);
                return
            end
            if laneId == geometry.getExitLaneId(routeState.ExitArm)
                remaining = (1 - progress) .* ...
                    geometry.ExitLaneLengths(exitIndex);
                return
            end

            for armIndex = 1:4
                arm = geometry.ArmNames(armIndex);
                exitStep = mod(exitIndex - armIndex - 1, 4) + 1;
                if laneId == ...
                        geometry.getCirculatingLaneIdAfterEntry(arm)
                    remaining = ...
                        (1 - progress) .* ...
                        geometry.EntryToExitArcLength + ...
                        (exitStep - 1) .* ( ...
                        geometry.ExitToEntryArcLength + ...
                        geometry.EntryToExitArcLength) + ...
                        geometry.ExitLaneLengths(exitIndex);
                    return
                end
                if laneId == ...
                        geometry.getCirculatingLaneIdAfterExit(arm)
                    remaining = ...
                        (1 - progress) .* ...
                        geometry.ExitToEntryArcLength + ...
                        exitStep .* geometry.EntryToExitArcLength + ...
                        (exitStep - 1) .* ...
                        geometry.ExitToEntryArcLength + ...
                        geometry.ExitLaneLengths(exitIndex);
                    return
                end
            end

            error("Unexpected roundabout lane in test fixture.");
        end
    end
end

function restoreRandomStreamState(randomStream, state)
randomStream.State = state;
end
