function result = resolve(template, options)
%RESOLVE Merge an optional patch, apply defaults, and validate.

arguments (Input)
    template (1, 1) v2xsim.config.ConfigurationTemplate
    options.Patch (1, 1) v2xsim.config.ConfigurationPatch = ...
        v2xsim.config.ConfigurationPatch()
end

template = v2xsim.config.merge(template, options.Patch);
schema = v2xsim.config.schema();
v2xsim.config.internal.Operations.validateAuthoredActivity( ...
    template.Data, schema);
data = v2xsim.config.internal.Operations.applyDefaults( ...
    template.Data, schema);
data = v2xsim.config.internal.Operations.applyDerivedDefaults( ...
    data, template.Data);
v2xsim.config.internal.Operations.validateResolved(data, schema);

defaultProvenance = ...
    v2xsim.config.internal.Operations.provenanceForData(data, "Default");
provenance = v2xsim.config.internal.Operations.overlayProvenance( ...
    defaultProvenance, template.Provenance);
derivedPaths = ...
    v2xsim.config.internal.Operations.derivedDefaultPaths( ...
        data, template.Data);
provenance = v2xsim.config.internal.Operations.markSources( ...
    provenance, derivedPaths, "Derived");
provenance = ...
    v2xsim.config.internal.Operations.retainProvenanceForData( ...
        provenance, data);
result = v2xsim.config.ResolvedConfiguration(data, provenance);
end
