function result = schema()
%SCHEMA Declarative definition of the V7 TOML configuration contract.
%   The returned tree is data: it contains no parser or simulator state.
%   Every node has a Kind, default policy, admissible enum values, children,
%   and optional discriminator metadata used by the generic resolver.

persistent cachedSchema
if ~isempty(cachedSchema)
    result = cachedSchema;
    return
end

scenarioBranches = [ ...
    "BrownianMotion", ...
    "BidirectionalHighway", ...
    "EtsiHighway", ...
    "ExitRampHighway", ...
    "Roundabout"];
scenario = tableNode(struct( ...
    Type=enumLeaf("BidirectionalHighway", scenarioBranches), ...
    UpdateIntervalSeconds=positiveDouble(0.1), ...
    BrownianMotion=tableNode(struct( ...
        RandomSeed=seedLeaf(1), ...
        VehicleCount=positiveInteger(100), ...
        SimulationAreaSize=positiveDouble(1000), ...
        MeanVehicleSpeed=nonnegativeDouble(50), ...
        VehicleSpeedStandardDeviation=nonnegativeDouble(10))), ...
    BidirectionalHighway=highwayNode(1, 22.2, 2.78), ...
    EtsiHighway=tableNode(struct( ...
        RandomSeed=seedLeaf(1), ...
        TrafficModel=enumLeaf( ...
            "HighSpeedLowDensity", ...
            ["HighSpeedLowDensity", "MediumSpeedMediumDensity", ...
             "LowSpeedHighDensity"]), ...
        Placement=enumLeaf("Uniform", ["Uniform", "Gaussian"]), ...
        MinimumRoadLength=boundedDouble(2000, 2000, inf))), ...
    ExitRampHighway=exitRampNode(), ...
    Roundabout=roundaboutNode()), ...
    "Type", scenarioBranches, scenarioBranches);

packetGeneration = tableNode(struct( ...
    IntervalSeconds=positiveDouble(0.1), ...
    IntervalVariationSeconds=nonnegativeDouble(0), ...
    RandomComponentMeanSeconds=nonnegativeDouble(0), ...
    Mode=enumLeaf("Periodic", ["Periodic", "EtsiCam"]), ...
    Cam=tableNode(struct( ...
        IntervalDiscretization=enumLeaf( ...
            "Continuous", ...
            ["Continuous", "AllSteps", "AllocationAligned"]), ...
        MaximumIntervalIncreasePercent=boundedDouble(20, 0, 100)))), ...
    "Mode", ["Periodic", "EtsiCam"], ["", "Cam"]);

application = tableNode(struct( ...
    ResourceReservationIntervalSeconds=positiveDouble(0.1), ...
    PacketSizeBytes=boundedInteger(190, 1, 10000), ...
    PacketBuffer=tableNode(struct(CapacityPackets=boundedInteger(1, 1, flintmax))), ...
    PacketGeneration=packetGeneration, ...
    ChannelLoad=tableNode(struct( ...
        Enabled=logicalLeaf(false), ...
        MeasurementWindowSeconds=positiveDouble(0.1), ...
        UpdateStepsPerWindow=positiveInteger(100))), ...
    CongestionControl=tableNode(struct( ...
        Enabled=logicalLeaf(false), ...
        ChannelOccupancyLimitScale=positiveDouble(1)))));

repetitionCbrThresholds = ...
    boundedNumericArray([0.03, 0.05, 0.09], 0, 1);
repetitionCbrThresholds.MinimumCount = 3;
repetitionCbrThresholds.MaximumCount = 3;
ieee80211p = tableNode(struct( ...
    PhysicalLayer=enumLeaf("Native", ["Native", "LteSurrogate"]), ...
    PreambleSensitivityDbm=finiteDouble(-100), ...
    Mcs=boundedInteger(2, 0, 7), ...
    LteSurrogateMcs=boundedInteger(3, 0, 28), ...
    RelativeInterferenceLevelModelEnabled=logicalLeaf(false), ...
    ContentionWindow=enumIntegerLeaf(15, [3, 7, 15, 31, 63]), ...
    AifsSlotCount=nonnegativeInteger(6), ...
    CcaThresholdWithoutDecodedPreambleDbm=finiteDouble(-65), ...
    CcaThresholdWithDecodedPreambleDbm=finiteDouble(-85), ...
    Repetition=tableNode(struct( ...
        Mode=enumLeaf( ...
            "Static", ["Static", "Deterministic", "Probabilistic"]), ...
        MaximumTransmissionCount=boundedInteger(1, 1, 4), ...
        BackoffMicroseconds=nonnegativeInteger(0), ...
        CbrThresholds=repetitionCbrThresholds))));

sidelink = tableNode(struct( ...
    DuplexMode=enumLeaf("Half", ["Half", "Full"]), ...
    InBandEmissionEnabled=logicalLeaf(true), ...
    MaximumTransmissionCount=boundedInteger(1, 1, 2), ...
    SciDecodeSinrThresholdDb=finiteDouble(0), ...
    FullDuplex=tableNode(struct( ...
        ResidualSelfInterferenceDb=finiteDouble(-110))), ...
    ResourcePool=tableNode(struct( ...
        V2vSharePercent=boundedInteger(100, 1, 100), ...
        SubchannelSizeResourceBlocks=optionalPositiveInteger(), ...
        MaximumFrequencyDomainResources=optionalPositiveInteger(), ...
        ResourcePressure=tableNode(struct( ...
            TimeAvailabilityPercent=boundedInteger(100, 1, 100), ...
            FrequencyAvailabilityPercent=boundedInteger(100, 1, 100))), ...
        PartialFrequencyOverlapEnabled=logicalLeaf(false)))));

radioBranches = ["Ieee80211p", "LteV2X", "NrV2X", "Coexistence"];
radio = tableNode(struct( ...
    Type=enumLeaf("LteV2X", radioBranches), ...
    BandwidthMHz=enumDoubleLeaf(10, [1.4, 5, 10, 20]), ...
    TransmitPowerDbm=finiteDouble(23), ...
    FixedPowerDensityEnabled=logicalLeaf(true), ...
    TransmitAntennaGainDb=finiteDouble(3), ...
    ReceiveAntennaGainDb=finiteDouble(3), ...
    ReceiverNoiseFigureDb=finiteDouble(9), ...
    Ieee80211p=ieee80211p, ...
    LteV2X=tableNode(struct( ...
        Mcs=boundedInteger(3, 0, 28), ...
        AdjacentPscchAndPsschEnabled=logicalLeaf(true))), ...
    NrV2X=tableNode(struct( ...
        SubcarrierSpacingKilohertz=enumIntegerLeaf(15, [15, 30, 60]), ...
        DmrsResourceElementCountPerSlot= ...
            enumIntegerLeaf(24, [12, 15, 18, 21, 24]), ...
        Mcs=boundedInteger(7, 0, 28), ...
        SciSymbolCount=enumIntegerLeaf(3, [2, 3]), ...
        SciResourceBlockCount= ...
            enumIntegerLeaf(10, [10, 12, 15, 20, 25]))), ...
    Coexistence=tableNode(struct( ...
        SidelinkType=enumLeaf("LteV2X", ["LteV2X", "NrV2X"]), ...
        InterferenceModel=enumLeaf( ...
            "Independent", ["Independent", "Cochannel"]))), ...
    Sidelink=sidelink), ...
    "Type", radioBranches, radioBranches);

pathLossModels = [ ...
    "WinnerPlusB1", "SingleSlope", "TwoSlope", ...
    "ThreeSlope", "NrV2VNlos"];
channel = tableNode(struct( ...
    RayleighFadingEnabled=logicalLeaf(false), ...
    PacketError=tableNode(struct( ...
        Model=enumLeaf("Threshold", ["Threshold", "Curves"]), ...
        CurveDirectory=optionalString(), ...
        NlosCurveDirectory=optionalString(), ...
        Ieee80211pLosThresholdDb=optionalFiniteDouble(), ...
        SidelinkLosThresholdDb=optionalFiniteDouble())), ...
    PathLoss=tableNode(struct( ...
        Model=enumLeaf("WinnerPlusB1", pathLossModels), ...
        ReferenceLossAtOneMeterDb=positiveDouble(47.86), ...
        Exponent1=positiveDouble(2.20), ...
        Exponent2=positiveDouble(2.20), ...
        Exponent3=positiveDouble(2.20), ...
        BreakpointDistance1Meters=boundedDouble(10, 1, inf), ...
        BreakpointDistance2Meters=positiveDouble(10))), ...
    Obstacles=tableNode(struct( ...
        BuildingAttenuationDbPerMeter=nonnegativeDouble(0.4), ...
        WallAttenuationDb=nonnegativeDouble(6))), ...
    Shadowing=tableNode(struct( ...
        LosStandardDeviationDb=nonnegativeDouble(3), ...
        NlosStandardDeviationDb=nonnegativeDouble(4)))));

allocatorBranches = [ ...
    "ReuseDistance", "MaximumReuseDistance", "MinimumReusePower", ...
    "SensingBased", "Random", "Ordered"];
selectionWindow = struct( ...
    SelectionWindowStartMilliseconds=optionalNonnegativeDouble(), ...
    SelectionWindowEndMilliseconds=boundedInteger(100, 20, 100));
resourceAllocation = tableNode(struct( ...
    Type=enumLeaf("SensingBased", allocatorBranches), ...
    RandomSeed=seedLeaf(1), ...
    ReuseDistance=tableNode(struct( ...
        PositionError95PercentileMeters=nonnegativeDouble(0), ...
        PositionUpdateIntervalSeconds=positiveDouble(0.1), ...
        ReuseMarginMeters=nonnegativeDouble(0), ...
        ReassignmentIntervalSeconds=positiveDouble(0.1))), ...
    MaximumReuseDistance=tableNode(struct( ...
        ReassignmentIntervalSeconds=positiveDouble(0.1))), ...
    MinimumReusePower=tableNode(struct( ...
        ReassignmentIntervalSeconds=positiveDouble(0.1), ...
        KnownShadowingEnabled=logicalLeaf(false))), ...
    SensingBased=tableNode(struct( ...
        ReevaluationEnabled=logicalLeaf(false), ...
        ReevaluateAfterSkippedTransmissionEnabled=logicalLeaf(false), ...
        ReselectEveryPacketEnabled=logicalLeaf(false), ...
        KeepResourceProbability=boundedDouble(0.8, 0, 1), ...
        MaximumConsecutiveReservationIntervals= ...
            positiveIntegerOrInfinity(inf), ...
        MinimumCandidateFraction=boundedDouble(0.2, 0.2, 1), ...
        L2CandidateFraction=boundedDouble(0.2, 0, 1), ...
        L2RankingEnabled=logicalLeaf(true), ...
        AverageSensingEnabled=logicalLeaf(true), ...
        SensingWindowSeconds=positiveDouble(1), ...
        ReselectionCounterMinimum=optionalPositiveInteger(), ...
        ReselectionCounterMaximum=optionalPositiveInteger(), ...
        SensingThresholdDbm=finiteDouble(-110), ...
        SelectionWindowStartMilliseconds= ...
            selectionWindow.SelectionWindowStartMilliseconds, ...
        SelectionWindowEndMilliseconds= ...
            selectionWindow.SelectionWindowEndMilliseconds)), ...
    Random=tableNode(selectionWindow), ...
    Ordered=tableNode(struct()), ...
    FullDuplex=tableNode(struct( ...
        SelfInterferenceThresholdMultiplier= ...
            positiveDoubleOrInfinity(inf)))), ...
    "Type", allocatorBranches, allocatorBranches);

coexistenceMethodValues = [ ...
    "Standard", "MethodA", "MethodB", "MethodC", "MethodF"];
coexistence = tableNode(struct( ...
    Method=enumLeaf( ...
        "Standard", coexistenceMethodValues), ...
    VehiclePattern=tableNode(struct( ...
        SidelinkVehicleCount=nonnegativeInteger(1), ...
        ItsG5VehicleCount=nonnegativeInteger(1))), ...
    Superframe=tableNode(struct( ...
        DurationSeconds=positiveDouble(0.01), ...
        SlotManagement=enumLeaf("Static", ["Static", "Dynamic"]), ...
        SidelinkPortionEndSeconds=optionalNonnegativeDouble())), ...
    MethodA=tableNode(struct( ...
        GuardIntervalSeconds=optionalNonnegativeDouble(), ...
        EnhancementVariant=boundedInteger(0, 0, 3), ...
        SynchronizationErrorSeconds=nonnegativeDouble(0), ...
        LegacyItsG5NodesEnabled=logicalLeaf(false), ...
        ItsG5PerceivedSidelinkEndSeconds=optionalNonnegativeDouble())), ...
    MethodB=tableNode(struct( ...
        EnergySignalLeadTimeSeconds=optionalNonnegativeDouble(), ...
        AllNodesTransmitInEmptySubframes=logicalLeaf(true))), ...
    MethodC=tableNode(struct( ...
        TimeGapVariant=enumIntegerLeaf(1, [1, 2]), ...
        DetectAndCancelItsG5Enabled=logicalLeaf(false), ...
        ModifiedContentionWindowEnabled=logicalLeaf(false), ...
        MultipleSubframeIndicationEnabled=logicalLeaf(false))), ...
    MethodF=tableNode(struct( ...
        GuardIntervalEnabled=logicalLeaf(true))), ...
    ChannelLoad=tableNode(struct( ...
        SidelinkVariant=boundedInteger(3, 1, 5), ...
        TotalVariant=enumIntegerLeaf(1, [1, 2, 9])))), ...
    "Method", coexistenceMethodValues, ...
    ["", "MethodA", "MethodB", "MethodC", "MethodF"]);

positionError = tableNode(struct( ...
    Type=requiredEnumLeaf( ...
        ["Gaussian", "PacketLoss", "Delay", "FalseExit", "FalseMerge"]), ...
    MeanMagnitudeMeters=nonnegativeDouble(0), ...
    StandardDeviationMeters=nonnegativeDouble(0), ...
    DisplacementRandomSeed=seedLeaf(1), ...
    AffectedVehicleProbability=boundedDouble(1, 0, 1), ...
    SelectionRandomSeed=seedLeaf(1), ...
    ResetAfterSeconds=nonnegativeDoubleOrInfinity(inf), ...
    ActiveRoutes=stringArray("All"), ...
    LossProbability=boundedDouble(0, 0, 1), ...
    RandomSeed=seedLeaf(1), ...
    DelaySeconds=nonnegativeDouble(0), ...
    DisplacementScale=boundedDouble(1, 0, 1)));

roadsideUnit = tableNode(struct( ...
    Id=requiredString(), ...
    Technology=requiredEnumLeaf(["Ieee80211p", "LteV2X"]), ...
    PacketType=requiredEnumLeaf(["Cam", "Denm", "HighPriorityDenm"]), ...
    PositionMeters=fixedNumericArray(2)));

outputs = tableNode(struct( ...
    ResourceUsage=outputSwitch(), ...
    AverageNeighborCount=outputSwitch(), ...
    VehicleKinematics=outputSwitch(), ...
    PositionErrorTrace=outputSwitchWithFlush(10000), ...
    ControllerDiagnostics=tableNode(struct( ...
        Enabled=logicalLeaf(false), ...
        TopK=positiveInteger(10), ...
        RankDisplacementEnabled=logicalLeaf(false), ...
        FlushRowCount=positiveInteger(5000))), ...
    PacketFateTrace=tableNode(struct( ...
        Enabled=logicalLeaf(false), ...
        FlushRowCount=positiveInteger(10000), ...
        FileFormat=enumLeaf("parquet", ["parquet", "csv"]))), ...
    InterferenceClassification=outputSwitch(), ...
    UpdateDelay=outputSwitch(), ...
    WirelessBlindSpot=tableNode(struct( ...
        Enabled=logicalLeaf(false), ...
        MaximumDelaySeconds=positiveDouble(10), ...
        BinWidthSeconds=positiveDouble(0.1))), ...
    PacketDelay=outputSwitch(), ...
    DataAge=outputSwitch(), ...
    DelayMetrics=tableNode(struct( ...
        BinWidthSeconds=positiveDouble(0.001))), ...
    PacketReceptionRatio=tableNode(struct( ...
        Enabled=logicalLeaf(false), ...
        DistanceBinWidthMeters=positiveDouble(10))), ...
    ChannelBusyRatio=outputSwitch(), ...
    CoexistenceTechnologyShare=outputSwitch()));

rootChildren = struct( ...
    SchemaVersion=enumIntegerLeaf(1, 1), ...
    Simulation=tableNode(struct( ...
        RandomSeed=seedLeaf(1), ...
        DurationSeconds=positiveDouble(10))), ...
    Scenario=scenario, ...
    Application=application, ...
    Radio=radio, ...
    Channel=channel, ...
    Awareness=tableNode(struct( ...
        RangesMeters=positiveNumericArray(150))), ...
    ResourceAllocation=resourceAllocation, ...
    Coexistence=coexistence, ...
    Positioning=tableNode(struct( ...
        Errors=arrayOfTables(positionError))), ...
    Infrastructure=tableNode(struct( ...
        RoadsideUnits=arrayOfTables(roadsideUnit))), ...
    Outputs=outputs);

cachedSchema = tableNode(rootChildren);
cachedSchema.SchemaVersion = 1;
result = cachedSchema;
end

function result = highwayNode(laneCount, meanSpeed, speedStandardDeviation)
result = tableNode(struct( ...
    RandomSeed=seedLeaf(1), ...
    VehicleCount=positiveInteger(100), ...
    NLanes=positiveInteger(laneCount), ...
    LaneWidth=positiveDouble(2.5), ...
    RoadLength=positiveDouble(2000), ...
    CentralDividerWidth=nonnegativeDouble(0), ...
    MeanVehicleSpeed=nonnegativeDouble(meanSpeed), ...
    VehicleSpeedStandardDeviation=nonnegativeDouble(speedStandardDeviation), ...
    RerollSpeedOnWrapAround=logicalLeaf(true)));
end

function result = exitRampNode()
children = highwayNode(2, 80, 10).Children;
children.NLanes = boundedInteger(2, 2, inf);
children.ExitProbability = boundedDouble(0.5, 0, 1);
children.MergeDistance = nonnegativeDouble(100);
result = tableNode(children);
end

function result = roundaboutNode()
result = tableNode(struct( ...
    RandomSeed=seedLeaf(1), ...
    VehicleCount=positiveInteger(100), ...
    ExitLengths=positiveNumericArray(500), ...
    RoadWidth=positiveDouble(4), ...
    InnerCircleDiameter=positiveDouble(60), ...
    MeanVehicleSpeed=nonnegativeDouble(20), ...
    VehicleSpeedStandardDeviation=nonnegativeDouble(2), ...
    RerollSpeedOnWrapAround=logicalLeaf(true)));
end

function result = outputSwitch()
result = tableNode(struct(Enabled=logicalLeaf(false)));
end

function result = outputSwitchWithFlush(defaultRows)
result = tableNode(struct( ...
    Enabled=logicalLeaf(false), ...
    FlushRowCount=positiveInteger(defaultRows)));
end

function result = tableNode(children, selector, values, branches)
arguments
    children (1, 1) struct
    selector (1, 1) string = ""
    values string = strings(0, 1)
    branches string = strings(0, 1)
end
result = baseNode("table");
result.Children = children;
result.Selector = selector;
result.BranchValues = values(:);
result.BranchChildren = branches(:);
end

function result = arrayOfTables(element)
result = baseNode("arrayOfTables");
result.Element = element;
result.HasDefault = true;
result.Default = {};
end

function result = requiredString()
result = baseNode("string");
result.Required = true;
result.MustBeNonemptyText = true;
end

function result = optionalString()
result = baseNode("string");
result.MustBeNonemptyText = true;
end

function result = enumLeaf(defaultValue, values)
result = leafWithDefault("string", string(defaultValue));
result.AllowedStrings = string(values(:));
end

function result = requiredEnumLeaf(values)
result = baseNode("string");
result.Required = true;
result.AllowedStrings = string(values(:));
end

function result = stringArray(defaultValue)
result = leafWithDefault("stringArray", string(defaultValue));
result.MinimumCount = 1;
end

function result = finiteDouble(defaultValue)
result = leafWithDefault("double", defaultValue);
result.MustBeFinite = true;
end

function result = optionalFiniteDouble()
result = baseNode("double");
result.MustBeFinite = true;
end

function result = positiveDouble(defaultValue)
result = boundedDouble(defaultValue, 0, inf);
result.MinimumExclusive = true;
end

function result = positiveDoubleOrInfinity(defaultValue)
result = positiveDouble(defaultValue);
result.AllowPositiveInfinity = true;
result.MustBeFinite = false;
end

function result = nonnegativeDouble(defaultValue)
result = boundedDouble(defaultValue, 0, inf);
end

function result = optionalNonnegativeDouble()
result = baseNode("double");
result.Minimum = 0;
result.MustBeFinite = true;
end

function result = nonnegativeDoubleOrInfinity(defaultValue)
result = nonnegativeDouble(defaultValue);
result.AllowPositiveInfinity = true;
result.MustBeFinite = false;
end

function result = boundedDouble(defaultValue, minimum, maximum)
result = leafWithDefault("double", double(defaultValue));
result.Minimum = minimum;
result.Maximum = maximum;
result.MustBeFinite = isfinite(maximum);
end

function result = positiveInteger(defaultValue)
result = boundedInteger(defaultValue, 1, inf);
end

function result = optionalPositiveInteger()
result = baseNode("integer");
result.Minimum = 1;
end

function result = nonnegativeInteger(defaultValue)
result = boundedInteger(defaultValue, 0, inf);
end

function result = boundedInteger(defaultValue, minimum, maximum)
result = leafWithDefault("integer", double(defaultValue));
result.Minimum = minimum;
result.Maximum = maximum;
end

function result = enumIntegerLeaf(defaultValue, allowedValues)
result = boundedInteger(defaultValue, -inf, inf);
result.AllowedNumbers = double(allowedValues(:));
end

function result = enumDoubleLeaf(defaultValue, allowedValues)
result = finiteDouble(defaultValue);
result.AllowedNumbers = double(allowedValues(:));
end

function result = positiveIntegerOrInfinity(defaultValue)
result = positiveInteger(defaultValue);
result.AllowPositiveInfinity = true;
end

function result = seedLeaf(defaultValue)
result = boundedInteger(defaultValue, 1, double(intmax("uint32")));
end

function result = logicalLeaf(defaultValue)
result = leafWithDefault("logical", logical(defaultValue));
end

function result = positiveNumericArray(defaultValue)
result = leafWithDefault("numericArray", double(defaultValue));
result.Minimum = 0;
result.MinimumExclusive = true;
result.MustBeFinite = true;
result.MinimumCount = 1;
end

function result = boundedNumericArray(defaultValue, minimum, maximum)
result = leafWithDefault("numericArray", double(defaultValue));
result.Minimum = minimum;
result.Maximum = maximum;
result.MustBeFinite = true;
result.MinimumCount = 1;
end

function result = fixedNumericArray(count)
result = baseNode("numericArray");
result.MustBeFinite = true;
result.MinimumCount = count;
result.MaximumCount = count;
end

function result = leafWithDefault(kind, defaultValue)
result = baseNode(kind);
result.HasDefault = true;
result.Default = defaultValue;
end

function result = baseNode(kind)
result = struct( ...
    Kind=string(kind), ...
    HasDefault=false, ...
    Default=[], ...
    Required=false, ...
    Children=struct(), ...
    Element=struct(), ...
    Selector="", ...
    BranchValues=strings(0, 1), ...
    BranchChildren=strings(0, 1), ...
    AllowedStrings=strings(0, 1), ...
    AllowedNumbers=zeros(0, 1), ...
    Minimum=-inf, ...
    Maximum=inf, ...
    MinimumExclusive=false, ...
    MustBeFinite=false, ...
    AllowPositiveInfinity=false, ...
    MustBeNonemptyText=false, ...
    MinimumCount=0, ...
    MaximumCount=inf);
end
