%% 16 - Run a fixed IEEE DENM roadside unit

exampleScriptDirectory = fileparts(mfilename("fullpath"));
[exampleResults,exampleOutputDirectory] = runExample(exampleScriptDirectory);
clear exampleScriptDirectory

disp(exampleResults.RoadsideUnitFates)
fprintf("Completed output: %s\n",exampleOutputDirectory);

function [results,outputDirectory] = runExample(exampleDirectory)
timer = tic;
configurationFile = fullfile( ...
    exampleDirectory,"16_roadside_unit.toml");
outputDirectory = string(tempname);
template = v2xsim.config.load(configurationFile);
configuration = template.resolve();
simulationTimer = tic;
simulationResult = v2xsim.runSimulation( ...
    configuration, ...
    OutputDirectory=outputDirectory, ...
    RunLabel="roadside-unit");
simulationElapsedSeconds = toc(simulationTimer);
outputDirectory = simulationResult.RunDirectory;
summary = jsondecode(fileread(fullfile( ...
    simulationResult.RunDirectory,"simulation_summary.json")));

chunks = dir(fullfile(outputDirectory,"packet_fates_*.csv"));
parts = arrayfun(@(file) readtable( ...
    fullfile(file.folder,file.name),TextType="string"), ...
    chunks,UniformOutput=false);
fates = vertcat(parts{:});
rsuMask = fates.TransmitterUeId == "rsu-west" | ...
    fates.ReceiverUeId == "rsu-west";
roadsideUnitFates = fates(rsuMask,:);
assert(~isempty(roadsideUnitFates), ...
    "The RSU example produced no directed RSU packet fates.");

elapsedSeconds = toc(timer);
if elapsedSeconds > 30
    warning( ...
        "v2xsimexample:SlowExample", ...
        "This example took %.1f seconds on this computer.", ...
        elapsedSeconds);
end
results = struct( ...
    SimulationResult=simulationResult, ...
    Summary=summary, ...
    RoadsideUnitFates=roadsideUnitFates, ...
    SimulationElapsedSeconds=simulationElapsedSeconds, ...
    ElapsedSeconds=elapsedSeconds);
end
