classdef CompiledSimulationPlanTest < matlab.unittest.TestCase
    %COMPILEDSIMULATIONPLANTEST Tests immutable plan compilation.

    methods (Test)
        function testCopiesEveryResolvedConfigurationDomain(testCase)
            configuration = v2xsim.config.defaults();

            plan = v2xsim.runtime.compile(configuration);

            domainNames = [ ...
                "Simulation", ...
                "Scenario", ...
                "Application", ...
                "Radio", ...
                "Channel", ...
                "Awareness", ...
                "ResourceAllocation", ...
                "Coexistence", ...
                "Positioning", ...
                "Infrastructure", ...
                "Outputs"];
            testCase.verifyEqual(plan.Configuration, configuration);
            testCase.verifyEqual( ...
                plan.SchemaVersion, configuration.Data.SchemaVersion);
            for domainName = domainNames
                testCase.verifyEqual( ...
                    plan.(domainName), ...
                    configuration.Data.(domainName));
            end
        end

        function testResolvedBoundaryRejectsAdditionalDomains(testCase)
            configuration = v2xsim.config.defaults();
            additionalData = configuration.Data;
            additionalData.Legacy = struct();

            testCase.verifyError( ...
                @() v2xsim.config.ResolvedConfiguration( ...
                    additionalData, configuration.Provenance), ...
                "v2xsim:config:UnknownKey");
        end

        function testResolvedBoundaryRejectsNonscalarDomain(testCase)
            configuration = v2xsim.config.defaults();
            data = configuration.Data;
            data.Radio = repmat(struct(), 1, 2);

            testCase.verifyError( ...
                @() v2xsim.config.ResolvedConfiguration( ...
                    data, configuration.Provenance), ...
                "v2xsim:config:InvalidResolvedConfiguration");
        end

        function testResolvedBoundaryRejectsUnsupportedSchema(testCase)
            configuration = v2xsim.config.defaults();
            data = configuration.Data;
            data.SchemaVersion = 2;

            testCase.verifyError( ...
                @() v2xsim.config.ResolvedConfiguration( ...
                    data, configuration.Provenance), ...
                "v2xsim:config:InvalidEnumValue");
        end
    end
end
