classdef MetricsAccumulatorTest < matlab.unittest.TestCase
    %METRICSACCUMULATORTEST Tests named metric and event accumulation.

    methods (Test)
        function testAccumulatesNamedMetricsAndOrderedEvents(testCase)
            accumulator = v2xsim.runtime.MetricsAccumulator();
            accumulator.increment("Transmissions");
            accumulator.addMetric("Transmissions", 2);
            accumulator.setMetric("MeanNeighbors", 4.5);
            accumulator.recordEvent( ...
                "VehicleEntered", 0.25, ...
                struct("NodeId", uint64(7)));

            snapshot = accumulator.snapshot();

            testCase.verifyEqual( ...
                snapshot.Metrics.Name, ...
                ["Transmissions"; "MeanNeighbors"]);
            testCase.verifyEqual(snapshot.Metrics.Value, [3; 4.5]);
            testCase.verifyEqual( ...
                accumulator.getMetric("Transmissions"), 3);
            testCase.verifyEqual( ...
                snapshot.Events.Name, "VehicleEntered");
            testCase.verifyEqual( ...
                snapshot.Events.SimulationTimeSeconds, 0.25);
            testCase.verifyEqual( ...
                snapshot.Events.Details{1}, ...
                struct("NodeId", uint64(7)));
        end

        function testSnapshotHasValueSemantics(testCase)
            accumulator = v2xsim.runtime.MetricsAccumulator();
            accumulator.setMetric("Packets", 2);
            snapshotBeforeUpdate = accumulator.snapshot();

            accumulator.increment("Packets");

            testCase.verifyEqual( ...
                snapshotBeforeUpdate.Metrics.Value, 2);
            testCase.verifyEqual( ...
                accumulator.snapshot().Metrics.Value, 3);
        end

        function testFinalizeIsIdempotentAndFreezesMutations(testCase)
            accumulator = v2xsim.runtime.MetricsAccumulator();
            accumulator.setMetric("Packets", 5);

            first = accumulator.finalize();
            second = accumulator.finalize();

            testCase.verifyTrue(accumulator.IsFinalized);
            testCase.verifyEqual(second, first);
            testCase.verifyError( ...
                @() accumulator.increment("Packets"), ...
                "v2xsim:runtime:MetricsFinalized");
            testCase.verifyError( ...
                @() accumulator.recordEvent( ...
                    "LateEvent", 1, struct()), ...
                "v2xsim:runtime:MetricsFinalized");
        end

        function testRejectsInvalidMetricAndEventValues(testCase)
            accumulator = v2xsim.runtime.MetricsAccumulator();

            testCase.verifyError( ...
                @() accumulator.setMetric(" ", 1), ...
                "v2xsim:runtime:InvalidMetricName");
            testCase.verifyError( ...
                @() accumulator.setMetric("Packets", NaN), ...
                "v2xsim:runtime:InvalidMetricValue");
            testCase.verifyError( ...
                @() accumulator.recordEvent( ...
                    "VehicleEntered", -1, struct()), ...
                "v2xsim:runtime:InvalidEventTime");
            testCase.verifyError( ...
                @() accumulator.recordEvent( ...
                    "VehicleEntered", 0, ...
                    repmat(struct(), 1, 2)), ...
                "v2xsim:runtime:InvalidEventDetails");
        end

        function testUnknownMetricHasStableDiagnostic(testCase)
            accumulator = v2xsim.runtime.MetricsAccumulator();

            testCase.verifyError( ...
                @() accumulator.getMetric("missing"), ...
                "v2xsim:runtime:UnknownMetric");
        end
    end
end
