classdef RunOptionsTest < matlab.unittest.TestCase
    %RUNOPTIONSTEST Tests process-boundary run options.

    methods (Test)
        function testRunLabelHasStableDefault(testCase)
            options = v2xsim.runtime.RunOptions( ...
                OutputDirectory="results/run-1");

            testCase.verifyEqual( ...
                options.OutputDirectory, "results/run-1");
            testCase.verifyEqual(options.RunLabel, "");
        end

        function testNormalizesTextOptions(testCase)
            options = v2xsim.runtime.RunOptions( ...
                OutputDirectory="  results/run-1  ", ...
                RunLabel="  paired-seed  ");

            testCase.verifyEqual( ...
                options.OutputDirectory, "results/run-1");
            testCase.verifyEqual(options.RunLabel, "paired-seed");
        end

        function testRejectsBlankOutputDirectory(testCase)
            testCase.verifyError( ...
                @() v2xsim.runtime.RunOptions( ...
                    OutputDirectory="   "), ...
                "v2xsim:runtime:InvalidOutputDirectory");
        end

        function testRejectsMissingRunLabel(testCase)
            testCase.verifyError( ...
                @() v2xsim.runtime.RunOptions( ...
                    OutputDirectory="results/run-1", ...
                    RunLabel=string(missing)), ...
                "v2xsim:runtime:InvalidRunLabel");
        end

        function testRequiresOutputDirectory(testCase)
            testCase.verifyError( ...
                @() v2xsim.runtime.RunOptions(), ...
                "v2xsim:runtime:MissingOutputDirectory");
        end
    end
end
