classdef RuntimeStateTest < matlab.unittest.TestCase
    %RUNTIMESTATETEST Tests isolated mutable runtime state owners.

    methods (Test)
        function testChannelStateOwnsSquareLogicalMatrix(testCase)
            state = v2xsim.runtime.ChannelState();
            testCase.verifySize(state.LosMatrix, [0, 0]);

            expected = logical([1, 0; 0, 1]);
            state.replaceLosMatrix(expected);

            testCase.verifyEqual(state.LosMatrix, expected);
            testCase.verifyError( ...
                @() state.replaceLosMatrix(true(2, 3)), ...
                "v2xsim:runtime:InvalidLosMatrix");
            testCase.verifyError( ...
                @() state.replaceLosMatrix(eye(2)), ...
                "v2xsim:runtime:InvalidLosMatrix");
        end

        function testRadioStateAlignsAndUpdatesNodes(testCase)
            state = v2xsim.runtime.RadioNodeState( ...
                [3, 8], [20, 23], [0, Inf], [1, 4]);

            testCase.verifyEqual(state.NodeIds, uint64([3; 8]));
            testCase.verifyEqual( ...
                state.TransmitPowersDbm, [20; 23]);
            state.updateNode(8, 17, 2.5, 9);

            snapshot = state.snapshot();
            testCase.verifyEqual( ...
                string(snapshot.Properties.VariableNames), ...
                [ ...
                    "NodeId", "TransmitPowerDbm", ...
                    "TimerSeconds", "Counter"]);
            testCase.verifyEqual(snapshot.TransmitPowerDbm, [20; 17]);
            testCase.verifyEqual(snapshot.TimerSeconds, [0; 2.5]);
            testCase.verifyEqual(snapshot.Counter, uint64([1; 9]));
        end

        function testRadioStateRejectsIdentityAndShapeErrors(testCase)
            testCase.verifyError( ...
                @() v2xsim.runtime.RadioNodeState( ...
                    [1, 1], [1, 2], [0, 0], [0, 0]), ...
                "v2xsim:runtime:DuplicateNodeId");
            testCase.verifyError( ...
                @() v2xsim.runtime.RadioNodeState( ...
                    [0, 1], [1, 2], [0, 0], [0, 0]), ...
                "v2xsim:runtime:InvalidNodeIds");
            testCase.verifyError( ...
                @() v2xsim.runtime.RadioNodeState( ...
                    [1, 2], 1, [0, 0], [0, 0]), ...
                "v2xsim:runtime:NodeStateSizeMismatch");
            testCase.verifyError( ...
                @() v2xsim.runtime.RadioNodeState( ...
                    1, 20, -1, 0), ...
                "v2xsim:runtime:InvalidTimers");
            testCase.verifyError( ...
                @() v2xsim.runtime.RadioNodeState( ...
                    1, 20, 0, 0.5), ...
                "v2xsim:runtime:InvalidCounters");
        end

        function testRadioStateRejectsUnknownNodeUpdate(testCase)
            state = v2xsim.runtime.RadioNodeState( ...
                1, 20, 0, 0);

            testCase.verifyError( ...
                @() state.updateNode(2, 20, 0, 0), ...
                "v2xsim:runtime:UnknownNodeId");
        end

        function testCoexistenceStateAlignsAndUpdatesNodes(testCase)
            state = v2xsim.runtime.CoexistenceState( ...
                [2, 7], [0.04, 0.05]);

            state.updateNode(7, 0.08);

            snapshot = state.snapshot();
            testCase.verifyEqual(snapshot.NodeId, uint64([2; 7]));
            testCase.verifyEqual( ...
                snapshot.KnownLteEndSeconds, [0.04; 0.08]);
        end

        function testCoexistenceStateRejectsInvalidInputs(testCase)
            testCase.verifyError( ...
                @() v2xsim.runtime.CoexistenceState( ...
                    [1, 1], [0.1, 0.2]), ...
                "v2xsim:runtime:DuplicateNodeId");
            testCase.verifyError( ...
                @() v2xsim.runtime.CoexistenceState( ...
                    [1, 2], 0.1), ...
                "v2xsim:runtime:NodeStateSizeMismatch");
            testCase.verifyError( ...
                @() v2xsim.runtime.CoexistenceState(1, -0.1), ...
                "v2xsim:runtime:InvalidKnownLteEnds");
        end

        function testPositioningStateSeparatesProcessAndChainData( ...
                testCase)
            processData = struct("DrawCount", 3);
            chainData = struct("ActiveModuleCount", 2);
            state = v2xsim.runtime.PositioningState( ...
                processData, chainData);

            snapshot = state.snapshot();
            snapshot.ErrorProcessData.DrawCount = 99;

            testCase.verifyEqual( ...
                state.ErrorProcessData.DrawCount, 3);
            testCase.verifyEqual( ...
                state.ChainData.ActiveModuleCount, 2);
            state.replaceChainData(struct("ActiveModuleCount", 4));
            testCase.verifyEqual( ...
                state.ChainData.ActiveModuleCount, 4);
        end

        function testPositioningStateRejectsNonscalarStruct(testCase)
            testCase.verifyError( ...
                @() v2xsim.runtime.PositioningState( ...
                    repmat(struct(), 1, 2), struct()), ...
                "v2xsim:runtime:InvalidPositioningState");
        end
    end
end
