classdef SimulationResultTest < matlab.unittest.TestCase
    %SIMULATIONRESULTTEST Tests completed-run result invariants.

    methods (Test)
        function testRetainsPlanMetricsArtifactsAndDirectory(testCase)
            configuration = v2xsim.config.defaults();
            plan = ...
                v2xsim.runtime.CompiledSimulationPlan(configuration);
            accumulator = v2xsim.runtime.MetricsAccumulator();
            accumulator.setMetric("Packets", 3);
            metrics = accumulator.finalize();
            appliedChain = struct( ...
                Enabled=true, ...
                Modules={{struct( ...
                    Index=1, Origin="Custom", ...
                    Type="research.CustomModule", ...
                    Descriptor=struct(Version="1"))}});

            result = v2xsim.runtime.SimulationResult( ...
                configuration, plan, metrics, ...
                ["summary.json", "packets.csv"], "  run-output  ", ...
                appliedChain);

            testCase.verifyEqual( ...
                result.Configuration, configuration);
            testCase.verifyEqual(result.Plan, plan);
            testCase.verifyEqual(result.Metrics, metrics);
            testCase.verifyEqual( ...
                result.Artifacts, ["summary.json"; "packets.csv"]);
            testCase.verifyEqual(result.RunDirectory, "run-output");
            testCase.verifyEqual( ...
                result.AppliedPositionErrorChain, appliedChain);
        end

        function testRejectsConfigurationPlanMismatch(testCase)
            configuration = v2xsim.config.defaults();
            otherData = configuration.Data;
            otherData.Simulation.RandomSeed = ...
                otherData.Simulation.RandomSeed + 1;
            otherConfiguration = ...
                v2xsim.config.ResolvedConfiguration( ...
                    otherData, configuration.Provenance);
            otherPlan = ...
                v2xsim.runtime.CompiledSimulationPlan( ...
                    otherConfiguration);
            metrics = ...
                v2xsim.runtime.MetricsAccumulator().finalize();

            testCase.verifyError( ...
                @() v2xsim.runtime.SimulationResult( ...
                    configuration, otherPlan, metrics, ...
                    strings(0, 1), "run"), ...
                "v2xsim:runtime:ConfigurationPlanMismatch");
        end

        function testRejectsInvalidMetricsSnapshot(testCase)
            configuration = v2xsim.config.defaults();
            plan = ...
                v2xsim.runtime.CompiledSimulationPlan(configuration);

            testCase.verifyError( ...
                @() v2xsim.runtime.SimulationResult( ...
                    configuration, plan, struct(), ...
                    strings(0, 1), "run"), ...
                "v2xsim:runtime:InvalidMetricsSnapshot");
        end

        function testRejectsInvalidArtifactsAndDirectory(testCase)
            configuration = v2xsim.config.defaults();
            plan = ...
                v2xsim.runtime.CompiledSimulationPlan(configuration);
            metrics = ...
                v2xsim.runtime.MetricsAccumulator().finalize();

            testCase.verifyError( ...
                @() v2xsim.runtime.SimulationResult( ...
                    configuration, plan, metrics, ...
                    ["same.csv", "same.csv"], "run"), ...
                "v2xsim:runtime:DuplicateArtifact");
            testCase.verifyError( ...
                @() v2xsim.runtime.SimulationResult( ...
                    configuration, plan, metrics, ...
                    strings(0, 1), " "), ...
                "v2xsim:runtime:InvalidRunDirectory");
        end

        function testRejectsInvalidAppliedPositionErrorChain(testCase)
            configuration = v2xsim.config.defaults();
            plan = ...
                v2xsim.runtime.CompiledSimulationPlan(configuration);
            metrics = ...
                v2xsim.runtime.MetricsAccumulator().finalize();

            testCase.verifyError( ...
                @() v2xsim.runtime.SimulationResult( ...
                    configuration, plan, metrics, ...
                    strings(0, 1), "run", ...
                    struct(Enabled=false, ...
                        Modules={{struct(Index=1)}})), ...
                "v2xsim:runtime:InvalidAppliedPositionErrorChain");
        end
    end
end
