classdef SimulationProgressTest < matlab.unittest.TestCase
    %SIMULATIONPROGRESSTEST Run-owned progress callback contracts.

    methods (Test)
        function emitsMonotonicProgressWithoutDisturbingRuntimeTimer( ...
                testCase)
            configuration = testCase.createSmallConfiguration(); %#ok<NASGU>
            temporaryFolder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            outputDirectory = fullfile( ...
                string(temporaryFolder.Folder), "progress-run");
            events = repmat(emptyProgressEvent(), 0, 1);
            progressFcn = @captureProgress; %#ok<NASGU>
            originalPath = path;
            originalWorkingDirectory = string(pwd);
            warningIdentifier = ...
                "v2xsimtest:runtime:ObserverMutation";
            originalWarningState = warning( ...
                "query", warningIdentifier);

            evalc("v2xsim.runSimulation(configuration," + ...
                "OutputDirectory=outputDirectory," + ...
                "ProgressFcn=progressFcn);");

            stages = string({events.Stage}).';
            simulatedTimes = [events.SimulatedTimeSeconds].';
            durations = [events.SimulationDurationSeconds].';
            fractions = [events.FractionComplete].';
            elapsedWallTimes = [events.ElapsedWallSeconds].';
            simulating = stages == "simulating";

            testCase.verifyEqual(stages(1), "initializing");
            testCase.verifyEqual(stages(end), "finalizing");
            testCase.verifyGreaterThanOrEqual(nnz(simulating), 10);
            testCase.verifyGreaterThanOrEqual(diff(simulatedTimes), 0);
            testCase.verifyGreaterThanOrEqual(diff(fractions), 0);
            testCase.verifyGreaterThanOrEqual(diff(elapsedWallTimes), 0);
            testCase.verifyEqual( ...
                unique(durations), 0.2, AbsTol=eps(0.2));
            testCase.verifyEqual(simulatedTimes(1), 0);
            testCase.verifyEqual( ...
                simulatedTimes(end), 0.2, AbsTol=eps(0.2));
            testCase.verifyGreaterThanOrEqual(fractions, 0);
            testCase.verifyLessThanOrEqual(fractions, 1);

            summary = jsondecode(fileread(fullfile( ...
                outputDirectory, "simulation_summary.json")));
            % Each simulated-time callback resets MATLAB's implicit tic/toc
            % stopwatch and then pauses. The engine's explicit stopwatch
            % must still include those observer costs.
            testCase.verifyGreaterThan( ...
                summary.Run.ComputationDurationSeconds, ...
                0.002 .* nnz(simulating));
            testCase.verifyEqual(path, originalPath);
            testCase.verifyEqual( ...
                string(pwd), originalWorkingDirectory);
            testCase.verifyEqual( ...
                warning("query", warningIdentifier), ...
                originalWarningState);

            function captureProgress(event)
                tic
                if event.Stage == "simulating"
                    pause(0.003);
                end
                addpath(tempdir);
                cd(tempdir);
                warning("off", warningIdentifier);
                RandStream.setGlobalStream( ...
                    RandStream("mt19937ar", Seed=17));
                events(end + 1, 1) = event;
            end
        end

        function callbackFailureHasStableDiagnosticAndReleasesLock( ...
                testCase)
            configuration = testCase.createSmallConfiguration();
            temporaryFolder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            outputDirectory = fullfile( ...
                string(temporaryFolder.Folder), "failed-progress-run");

            testCase.verifyError( ...
                @() v2xsim.runSimulation( ...
                    configuration, ...
                    OutputDirectory=outputDirectory, ...
                    ProgressFcn=@failProgress), ...
                "v2xsim:runtime:ProgressCallbackFailed");
            testCase.verifyTrue(isfolder(outputDirectory));
            testCase.verifyFalse(isfolder(fullfile( ...
                outputDirectory, ".v2xsim-output-lock")));
        end

        function restoresPropertiesMutatedOnExistingRandomStream( ...
                testCase)
            callerStream = RandStream.getGlobalStream();
            streamCleanup = onCleanup( ...
                @() RandStream.setGlobalStream(callerStream));
            testStream = RandStream("mrg32k3a", Seed=20260730);
            referenceStream = RandStream("mrg32k3a", Seed=20260730);
            RandStream.setGlobalStream(testStream);

            expectedState = testStream.State;
            expectedAntithetic = testStream.Antithetic;
            expectedFullPrecision = testStream.FullPrecision;
            expectedNormalTransform = testStream.NormalTransform;
            expectedSubstream = testStream.Substream;
            expectedUniformValues = rand(referenceStream, 1, 8);
            expectedNormalValues = randn(referenceStream, 1, 8);

            v2xsim.runtime.internal.reportProgress( ...
                @mutateExistingStream, "simulating", 1, 2, 3);

            testCase.verifyTrue( ...
                RandStream.getGlobalStream() == testStream);
            testCase.verifyEqual(testStream.State, expectedState);
            testCase.verifyEqual( ...
                testStream.Antithetic, expectedAntithetic);
            testCase.verifyEqual( ...
                testStream.FullPrecision, expectedFullPrecision);
            testCase.verifyEqual( ...
                testStream.NormalTransform, expectedNormalTransform);
            testCase.verifyEqual( ...
                testStream.Substream, expectedSubstream);
            testCase.verifyEqual( ...
                rand(testStream, 1, 8), expectedUniformValues);
            testCase.verifyEqual( ...
                randn(testStream, 1, 8), expectedNormalValues);
            streamCleanup; %#ok<VUNUS>

            function mutateExistingStream(~)
                testStream.Antithetic = ~expectedAntithetic;
                testStream.FullPrecision = ~expectedFullPrecision;
                if string(expectedNormalTransform) == "Inversion"
                    testStream.NormalTransform = "Ziggurat";
                else
                    testStream.NormalTransform = "Inversion";
                end
                testStream.Substream = expectedSubstream + 4;
            end
        end

        function restorationFailureHasStableDiagnosticAndRestoresOthers( ...
                testCase)
            temporaryFolder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            deletedDirectory = fullfile( ...
                string(temporaryFolder.Folder), "deleted-original");
            fallbackDirectory = fullfile( ...
                string(temporaryFolder.Folder), "fallback");
            mkdir(deletedDirectory);
            mkdir(fallbackDirectory);

            callerWorkingDirectory = string(pwd);
            originalPath = path;
            originalStream = RandStream.getGlobalStream();
            originalWarningState = warning;
            processCleanup = onCleanup(@() restoreTestProcessState( ...
                callerWorkingDirectory, originalPath, ...
                originalStream, originalWarningState));
            warningIdentifier = ...
                "v2xsimtest:runtime:RestorationFailureMutation";
            originalWarningSetting = warning( ...
                "query", warningIdentifier);
            cd(deletedDirectory);

            testCase.verifyError( ...
                @() v2xsim.runtime.internal.reportProgress( ...
                    @deleteOriginalWorkingDirectory, ...
                    "simulating", 1, 2, 3), ...
                "v2xsim:runtime:ProgressStateRestoreFailed");
            testCase.verifyEqual(string(pwd), fallbackDirectory);
            testCase.verifyFalse(isfolder(deletedDirectory));
            testCase.verifyEqual(path, originalPath);
            testCase.verifyTrue( ...
                RandStream.getGlobalStream() == originalStream);
            testCase.verifyEqual( ...
                warning("query", warningIdentifier), ...
                originalWarningSetting);
            processCleanup; %#ok<VUNUS>

            function deleteOriginalWorkingDirectory(~)
                cd(fallbackDirectory);
                rmdir(deletedDirectory);
                addpath(fallbackDirectory);
                warning("off", warningIdentifier);
                RandStream.setGlobalStream( ...
                    RandStream("mt19937ar", Seed=73));
            end
        end

        function rejectsInvalidNonemptyProgressFunction(testCase)
            configuration = testCase.createSmallConfiguration();
            temporaryFolder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            outputDirectory = fullfile( ...
                string(temporaryFolder.Folder), ...
                "invalid-progress-function");

            testCase.verifyError( ...
                @() v2xsim.runSimulation( ...
                    configuration, ...
                    OutputDirectory=outputDirectory, ...
                    ProgressFcn=42), ...
                "v2xsim:runtime:InvalidProgressFunction");
        end

        function omittedAndEmptyProgressFunctionsRun(testCase)
            configuration = testCase.createSmallConfiguration(); %#ok<NASGU>
            temporaryFolder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            omittedOutputDirectory = fullfile( ...
                string(temporaryFolder.Folder), "omitted-progress");
            emptyOutputDirectory = fullfile( ...
                string(temporaryFolder.Folder), "empty-progress");

            evalc("omittedResult = v2xsim.runSimulation(" + ...
                "configuration," + ...
                "OutputDirectory=omittedOutputDirectory);");
            evalc("emptyResult = v2xsim.runSimulation(" + ...
                "configuration,OutputDirectory=emptyOutputDirectory," + ...
                "ProgressFcn=[]);");

            testCase.verifyClass( ...
                omittedResult, "v2xsim.runtime.SimulationResult");
            testCase.verifyClass( ...
                emptyResult, "v2xsim.runtime.SimulationResult");
            testCase.verifyTrue(isfile(fullfile( ...
                omittedOutputDirectory, "simulation_summary.json")));
            testCase.verifyTrue(isfile(fullfile( ...
                emptyOutputDirectory, "simulation_summary.json")));
        end
    end

    methods (Static, Access = private)
        function configuration = createSmallConfiguration()
            projectRoot = string(fileparts(fileparts(fileparts( ...
                fileparts(mfilename("fullpath"))))));
            configurationFile = fullfile( ...
                projectRoot, "tests", "+v2xsimtest", ...
                "+fixtures", "config", ...
                "EtsiHighwayMediumMode1.toml");
            patchData = struct( ...
                Simulation=struct( ...
                    RandomSeed=991, DurationSeconds=0.2), ...
                Scenario=struct( ...
                    Type="BrownianMotion", ...
                    UpdateIntervalSeconds=0.01, ...
                    BrownianMotion=struct( ...
                        RandomSeed=992, ...
                        VehicleCount=2, ...
                        SimulationAreaSize=100, ...
                        MeanVehicleSpeed=5, ...
                        VehicleSpeedStandardDeviation=0)), ...
                Outputs=struct( ...
                    PacketReceptionRatio=struct(Enabled=false), ...
                    VehicleKinematics=struct(Enabled=false), ...
                    UpdateDelay=struct(Enabled=false), ...
                    PacketDelay=struct(Enabled=false), ...
                    DataAge=struct(Enabled=false), ...
                    WirelessBlindSpot=struct(Enabled=false), ...
                    AverageNeighborCount=struct(Enabled=false), ...
                    ChannelBusyRatio=struct(Enabled=false)));
            configuration = v2xsim.config.load( ...
                configurationFile).resolve( ...
                    Patch=v2xsim.config.patch(patchData));
        end
    end
end

function event = emptyProgressEvent()
event = struct( ...
    Stage="", ...
    SimulatedTimeSeconds=0, ...
    SimulationDurationSeconds=1, ...
    FractionComplete=0, ...
    ElapsedWallSeconds=0, ...
    Message="");
end

function failProgress(~)
error( ...
    "v2xsimtest:runtime:DeliberateProgressFailure", ...
    "Deliberate progress callback failure.");
end

function restoreTestProcessState( ...
        workingDirectory, originalPath, originalStream, ...
        originalWarningState)
cd(workingDirectory);
path(originalPath);
RandStream.setGlobalStream(originalStream);
warning(originalWarningState);
end
