function summary = buildSimulationSummary( ...
        stationManagement, simParams, appParams, phyParams, ...
        sinrManagement, outParams, outputValues)
%BUILDSIMULATIONSUMMARY Build the versioned semantic simulation summary.
%   This function is pure apart from recording the current UTC completion
%   time. It preserves the simulator's existing KPI calculations while
%   representing configuration and results as typed, nested data.

arguments (Input)
    stationManagement (1, 1) struct
    simParams (1, 1) struct
    appParams (1, 1) struct
    phyParams (1, 1) struct
    sinrManagement (1, 1) struct
    outParams (1, 1) struct
    outputValues (1, 1) struct
end

summary = struct;
summary.SchemaVersion = 2;
summary.Run = buildRun(simParams, outParams, outputValues);
summary.Configuration = buildConfiguration( ...
    simParams, appParams, phyParams, sinrManagement);
summary.Results = buildResults( ...
    stationManagement, simParams, phyParams, outputValues);
end

function run = buildRun(simParams, outParams, outputValues)
completedAt = datetime( ...
    "now", TimeZone="UTC", ...
    Format="uuuu-MM-dd'T'HH:mm:ss.SSS'Z'");

run = struct( ...
    "SimulatorVersion", simulatorVersion(simParams), ...
    "CompletedAtUtc", string(completedAt), ...
    "RunLabel", textField(outParams, "message", ""), ...
    "RandomSeed", requiredField(simParams, "seed"), ...
    "SimulatedDurationSeconds", ...
        requiredField(simParams, "simulationTime"), ...
    "ComputationDurationSeconds", ...
        requiredField(outputValues, "computationTime"), ...
    "ConfigurationFile", textField(simParams, "fileCfg", ""));
end

function configuration = buildConfiguration( ...
        simParams, appParams, phyParams, sinrManagement)
technology = requiredField(simParams, "technology");
cellularConfigured = technology ~= 2;
ieee80211pConfigured = technology ~= 1;

configuration = struct;
configuration.RadioAccessMode = radioAccessMode(simParams);
configuration.Scenario = buildScenario(simParams);
configuration.Infrastructure = struct( ...
    "RoadSideUnitCount", fieldOr(appParams, "nRSUs", 0));
configuration.Positioning = buildPositioning( ...
    simParams, cellularConfigured);
configuration.Application = struct( ...
    "PacketGeneration", buildPacketGeneration( ...
        appParams, cellularConfigured));
configuration.ResourcePool = buildResourcePool( ...
    simParams, appParams, phyParams, cellularConfigured);
configuration.Radio = buildRadio(phyParams);
configuration.CellularSidelink = buildCellularConfiguration( ...
    simParams, phyParams, cellularConfigured);
configuration.Ieee80211p = buildIeee80211pConfiguration( ...
    phyParams, ieee80211pConfigured);
configuration.Channel = buildChannel( ...
    simParams, phyParams, cellularConfigured, ieee80211pConfigured);
configuration.Coexistence = buildCoexistence( ...
    simParams, phyParams, sinrManagement);
configuration.ResourceAllocation = buildResourceAllocation( ...
    simParams, cellularConfigured);
configuration.Awareness = struct;
configuration.Awareness.RangesMeters = num2cell( ...
    rowVector(requiredField(phyParams, "Raw")));
end

function scenario = buildScenario(simParams)
obstacleMapEnabled = logical(fieldOr( ...
    simParams, "fileObstaclesMap", false));

limits = struct( ...
    "MinimumXMeters", fieldOr(simParams, "XminTrace", NaN), ...
    "MaximumXMeters", fieldOr(simParams, "XmaxTrace", NaN), ...
    "MinimumYMeters", fieldOr(simParams, "YminTrace", NaN), ...
    "MaximumYMeters", fieldOr(simParams, "YmaxTrace", NaN));
obstacleMap = struct( ...
    "Enabled", obstacleMapEnabled, ...
    "File", textField(simParams, "filenameObstaclesMap", ""));

scenario = struct;
scenario.Type = textField(simParams, "typeOfScenario", "");
scenario.PositionLimitsMeters = limits;
scenario.ObstacleMap = obstacleMap;
scenario.Options = buildScenarioOptions(simParams);
end

function positioning = buildPositioning(simParams, cellularConfigured)
allocatorType = string(fieldOr( ...
    simParams, "resourceAllocationType", ""));
positionUpdateAvailable = cellularConfigured && ...
    allocatorType == "ReuseDistance";
positioning = struct( ...
    "SnapshotIntervalSeconds", ...
        requiredField(simParams, "positionTimeResolution"), ...
    "ControlledPositioningEnabled", positionUpdateAvailable, ...
    "PositionError95PercentileMeters", conditionalField( ...
        simParams, "posError95", positionUpdateAvailable), ...
    "UpdateIntervalSeconds", conditionalField( ...
        simParams, "Tupdate", positionUpdateAvailable), ...
    "UpdateIntervalExceedsSimulationDuration", ...
        positionUpdateAvailable && ...
        simParams.Tupdate > simParams.simulationTime);
positioning.ErrorChain = buildPositionErrorChain(simParams);
end

function options = buildScenarioOptions(simParams)
options = struct;
if ~isfield(simParams, "scenarioOptions") || ...
        ~isstruct(simParams.scenarioOptions)
    return
end

configuredOptions = simParams.scenarioOptions;
optionNames = [ ...
    "RandomSeed", "VehicleCount", "SimulationAreaSize", ...
    "MeanVehicleSpeed", "VehicleSpeedStandardDeviation", ...
    "NLanes", "LaneWidth", "RoadLength", ...
    "CentralDividerWidth", "RerollSpeedOnWrapAround", ...
    "TrafficModel", "Placement", "MinimumRoadLength", ...
    "ExitProbability", "MergeDistance"];
for optionName = optionNames
    if ~isfield(configuredOptions, optionName)
        continue
    end
    value = configuredOptions.(optionName);
    if isenum(value)
        value = string(value);
    end
    options.(optionName) = value;
end
end

function errorChain = buildPositionErrorChain(simParams)
moduleNames = string(fieldOr( ...
    simParams, "positionErrorModuleNames", strings(1, 0)));
moduleNames = reshape(moduleNames, 1, []);
configuredOptions = fieldOr( ...
    simParams, "positionErrorOptions", struct);
modules = cell(1, numel(moduleNames));
for moduleIndex = 1:numel(moduleNames)
    moduleName = moduleNames(moduleIndex);
    moduleOptions = struct;
    if isfield(configuredOptions, moduleName)
        moduleOptions = configuredOptions.(moduleName);
    end
    if moduleName == "Delay"
        modules{moduleIndex} = struct( ...
            "Index", moduleIndex, ...
            "Type", "PositionDelayError", ...
            "Options", moduleOptions);
        continue
    end

    statusEffectTypes = struct( ...
        "Gaussian", ...
            "IsotropicGaussianPositionErrorStatusEffect", ...
        "FalseExit", ...
            "FalseExitPositionErrorStatusEffect", ...
        "FalseMerge", ...
            "FalseMergePositionErrorStatusEffect");
    if ~isfield(statusEffectTypes, moduleName)
        error( ...
            "v2xsim:output:UnknownPositionErrorModule", ...
            "Cannot summarize position error module type ""%s"".", ...
            moduleName);
    end
    statusEffect = struct( ...
        "Type", statusEffectTypes.(moduleName), ...
        "Options", moduleOptions);
    modules{moduleIndex} = struct( ...
        "Index", moduleIndex, ...
        "Type", "PositionErrorStatusEffectInflictor", ...
        "StatusEffect", statusEffect);
end
errorChain = struct( ...
    "Enabled", ~isempty(moduleNames), ...
    "Modules", {modules});
end

function packetGeneration = buildPacketGeneration( ...
        appParams, cellularConfigured)
variability = requiredField( ...
    appParams, "variabilityGenerationInterval");
if variability == -1
    mode = "EtsiCam";
elseif variability == 0
    mode = "Periodic";
else
    mode = "PerVehicleUniformJitter";
end

camDiscretizationActive = variability == -1 && ...
    isfield(appParams, "camDiscretizationType") && ...
    ~strcmpi(string(appParams.camDiscretizationType), "null");
camDiscretization = struct( ...
    "Enabled", camDiscretizationActive, ...
    "Type", conditionalTextField( ...
        appParams, "camDiscretizationType", ...
        camDiscretizationActive), ...
    "MaximumIntervalIncreasePercent", conditionalField( ...
        appParams, "camDiscretizationIncrease", ...
        camDiscretizationActive));

packetGeneration = struct;
packetGeneration.Mode = mode;
packetGeneration.AllocationPeriodSeconds = ...
    requiredField(appParams, "allocationPeriod");
packetGeneration.PacketSizeBytes = ...
    requiredField(appParams, "beaconSizeBytes");
packetGeneration.CellularSidelinkResourcePercentage = ...
    conditionalField(appParams, "resourcesV2V", cellularConfigured);
packetGeneration.DeterministicIntervalSeconds = ...
    requiredField(appParams, "generationInterval");
packetGeneration.MeanRandomAdditionalIntervalSeconds = ...
    requiredField(appParams, "generationIntervalAverageRandomPart");
packetGeneration.UniformJitterSpanSeconds = conditionalValue( ...
    variability, variability > 0);
packetGeneration.UniformJitterHalfWidthSeconds = conditionalValue( ...
    variability / 2, variability > 0);
packetGeneration.CamDiscretization = camDiscretization;
end

function resourcePool = buildResourcePool( ...
        simParams, appParams, phyParams, cellularConfigured)
isLte = cellularConfigured && fieldOr(simParams, "mode5G", 0) == 0;
resourceBlockUnits = conditionalField( ...
    appParams, "RBsBeacon", cellularConfigured);
if isLte
    physicalResourceBlockCount = resourceBlockUnits / 2;
else
    physicalResourceBlockCount = resourceBlockUnits;
end

resourcePool = struct( ...
    "Active", cellularConfigured, ...
    "BeaconResourceCount", conditionalField( ...
        appParams, "Nbeacons", cellularConfigured), ...
    "BeaconResourceBlockUnits", resourceBlockUnits, ...
    "PhysicalResourceBlockCount", physicalResourceBlockCount, ...
    "SubchannelCount", conditionalField( ...
        phyParams, "NsubchannelsBeacon", cellularConfigured), ...
    "PhysicalResourceBlocksPerSubchannel", conditionalField( ...
        phyParams, "sizeSubchannel", cellularConfigured), ...
    "AdjacentPscchAndPsschEnabled", conditionalField( ...
        phyParams, "ifAdjacent", isLte));
end

function radio = buildRadio(phyParams)
channelCount = fieldOr(phyParams, "nChannels", 1);
proportions = fieldOr( ...
    phyParams, "propVehiclesChannels", defaultChannelProportions( ...
        channelCount));
powerDeltas = fieldOr( ...
    phyParams, "mcoPowerDeltaChannels", zeros(1, channelCount));
channels = cell(1, channelCount);
for channelIndex = 1:channelCount
    channels{channelIndex} = struct( ...
        "ChannelIndex", channelIndex, ...
        "ConfiguredVehicleFraction", ...
            indexedValue(proportions, channelIndex), ...
        "TransmitPowerDeltaDb", ...
            indexedValue(powerDeltas, channelIndex));
end

radio = struct;
radio.BandwidthMegahertz = requiredField(phyParams, "BwMHz");
radio.TransmitPowerDbm = requiredField(phyParams, "Ptx_dBm");
radio.FixedPowerDensity = logical(fieldOr( ...
    phyParams, "FixedPdensity", false));
radio.NoisePowerDensityDbmPerMegahertz = ...
    requiredField(phyParams, "Pnoise_MHz_dBm");
radio.ReceiverNoiseFigureDb = requiredField(phyParams, "F_dB");
radio.TransmitterAntennaGainDb = requiredField(phyParams, "Gt_dB");
radio.ReceiverAntennaGainDb = requiredField(phyParams, "Gr_dB");
radio.Channels = channels;
end

function configuration = buildCellularConfiguration( ...
        simParams, phyParams, active)
mode = fieldOr(simParams, "mode5G", NaN);
isLte = active && mode == 0;
isNr = active && mode == 1;
if isLte
    technology = "LTE-V2X";
    subcarrierSpacing = 15;
    mcs = fieldOr(phyParams, "MCS_LTE", NaN);
elseif isNr
    technology = "NR-V2X";
    subcarrierSpacing = fieldOr(phyParams, "SCS_NR", NaN);
    mcs = fieldOr(phyParams, "MCS_NR", NaN);
else
    technology = "";
    subcarrierSpacing = NaN;
    mcs = NaN;
end

duplex = conditionalTextField(phyParams, "duplexCV2X", active);
isFullDuplex = active && duplex == "FD";
residualSelfInterferenceDb = fieldOr( ...
    phyParams, "Ksi_dB", NaN);
selfInterferenceThresholdMultiplier = fieldOr( ...
    phyParams, "PDelta", NaN);
configuration = struct( ...
    "Active", active, ...
    "Technology", technology, ...
    "SubcarrierSpacingKilohertz", subcarrierSpacing, ...
    "ModulationAndCodingScheme", mcs, ...
    "PowerDensityDbmPerMegahertz", conditionalField( ...
        phyParams, "P_ERP_MHz_CV2X_dBm", active), ...
    "DuplexMode", duplex, ...
    "FullDuplexEnabled", isFullDuplex, ...
    "ResidualSelfInterferenceDb", conditionalValue( ...
        residualSelfInterferenceDb, isFullDuplex), ...
    "ResidualSelfInterferenceMode", ...
        residualSelfInterferenceMode( ...
            residualSelfInterferenceDb, isFullDuplex), ...
    "SelfInterferenceThresholdMultiplier", conditionalValue( ...
        selfInterferenceThresholdMultiplier, isFullDuplex), ...
    "SelfInterferenceThresholdMultiplierMode", ...
        selfInterferenceThresholdMultiplierMode( ...
            selfInterferenceThresholdMultiplier, isFullDuplex), ...
    "SelfInterferenceThresholdAdjustmentEnabled", ...
        isFullDuplex && ...
        residualSelfInterferenceDb < Inf && ...
        selfInterferenceThresholdMultiplier < Inf);
end

function configuration = buildIeee80211pConfiguration(phyParams, active)
usesLtePhy = active && logical(fieldOr( ...
    phyParams, "pWithLTEPHY", false));
if active && usesLtePhy
    mcs = fieldOr(phyParams, "MCS_pWithLTEphy", NaN);
elseif active
    mcs = fieldOr(phyParams, "MCS_11p", NaN);
else
    mcs = NaN;
end

backoff = struct( ...
    "ContentionWindow", conditionalField( ...
        phyParams, "CW", active), ...
    "ArbitrationInterframeSpaceNumber", conditionalField( ...
        phyParams, "AifsN", active), ...
    "NondecodedPreambleCcaThresholdDbm", conditionalField( ...
        phyParams, "CCAthr11p_notsync", active), ...
    "DecodedPreambleCcaThresholdDbm", conditionalField( ...
        phyParams, "CCAthr11p_sync", active), ...
    "RelativeInterferenceLevelModelEnabled", ...
        active && logical(fieldOr(phyParams, "rilModel11p", false)));

configuration = struct( ...
    "Active", active, ...
    "UsesCellularPhy", usesLtePhy, ...
    "ModulationAndCodingScheme", mcs, ...
    "PowerDensityDbmPerMegahertz", conditionalField( ...
        phyParams, "P_ERP_MHz_11p_dBm", active), ...
    "Backoff", backoff);
end

function channel = buildChannel( ...
        simParams, phyParams, cellularConfigured, ieee80211pConfigured)
modelCode = requiredField(phyParams, "channelModel");
pathLoss = struct( ...
    "ModelCode", modelCode, ...
    "Model", channelModelName(modelCode), ...
    "ReferenceLossAtOneMeterDb", fieldOr( ...
        phyParams, "L0_dB", NaN), ...
    "Exponent", fieldOr(phyParams, "beta", NaN), ...
    "FirstBreakpointMeters", fieldOr( ...
        phyParams, "d_threshold1", NaN), ...
    "SecondBreakpointMeters", fieldOr( ...
        phyParams, "d_threshold2", NaN), ...
    "SecondExponent", fieldOr(phyParams, "beta2", NaN), ...
    "ThirdExponent", fieldOr(phyParams, "beta3", NaN));

obstacles = struct( ...
    "Enabled", logical(fieldOr( ...
        simParams, "fileObstaclesMap", false)), ...
    "BuildingAttenuationDbPerMeter", fieldOr( ...
        phyParams, "Abuild_dB", NaN), ...
    "WallAttenuationDb", fieldOr(phyParams, "Awall_dB", NaN));

usesCurves = logical(requiredField(phyParams, "PERcurves"));
if usesCurves
    packetErrorModel = "PacketErrorRateCurves";
else
    packetErrorModel = "SinrThresholds";
end
packetError = struct( ...
    "Model", packetErrorModel, ...
    "CurveFolder", conditionalTextField( ...
        phyParams, "folderPERcurves", usesCurves), ...
    "CellularSidelinkLosSinrThresholdDb", conditionalField( ...
        phyParams, "sinrThresholdCV2X_LOS_dB", ...
        cellularConfigured && ~usesCurves), ...
    "Ieee80211pLosSinrThresholdDb", conditionalField( ...
        phyParams, "sinrThreshold11p_LOS_dB", ...
        ieee80211pConfigured && ~usesCurves));

shadowing = struct( ...
    "LosStandardDeviationDb", ...
        requiredField(phyParams, "stdDevShadowLOS_dB"), ...
    "NlosStandardDeviationDb", ...
        requiredField(phyParams, "stdDevShadowNLOS_dB"));

rangeEstimates = struct( ...
    "CellularSidelinkTwoSigmaMaximumMeters", conditionalField( ...
        phyParams, "RawMaxCV2X", cellularConfigured), ...
    "CellularSidelinkLosMaximumMeters", conditionalField( ...
        phyParams, "RawMaxLOSCV2X", cellularConfigured), ...
    "CellularSidelinkNlosMaximumMeters", conditionalField( ...
        phyParams, "RawMaxNLOSCV2X", ...
        cellularConfigured && modelCode == 0), ...
    "Ieee80211pTwoSigmaMaximumMeters", conditionalField( ...
        phyParams, "RawMax11p", ieee80211pConfigured), ...
    "Ieee80211pLosMaximumMeters", conditionalField( ...
        phyParams, "RawMaxLOS11p", ieee80211pConfigured), ...
    "Ieee80211pNlosMaximumMeters", conditionalField( ...
        phyParams, "RawMaxNLOS11p", ...
        ieee80211pConfigured && modelCode == 0));

channel = struct( ...
    "PathLoss", pathLoss, ...
    "Obstacles", obstacles, ...
    "PacketErrorModel", packetError, ...
    "Shadowing", shadowing, ...
    "RangeEstimates", rangeEstimates);
end

function coexistence = buildCoexistence( ...
        simParams, phyParams, sinrManagement)
technology = requiredField(simParams, "technology");
active = ismember(technology, [3, 4]);
sharedChannel = technology == 4;
methodCode = conditionalField( ...
    simParams, "coexMethod", sharedChannel);
slotCode = conditionalField( ...
    simParams, "coex_slotManagement", ...
    sharedChannel && methodCode ~= 0);
staticSlotManagement = sharedChannel && slotCode == 1;

effectiveStaticCellularDuration = fieldOr( ...
    simParams, "coex_endOfLTE", NaN);
if staticSlotManagement && methodCode == 3 && ...
        isfield(sinrManagement, "coex_NtotSubframeLTE")
    subframeCounts = sinrManagement.coex_NtotSubframeLTE;
    if ~isempty(subframeCounts)
        effectiveStaticCellularDuration = ...
            subframeCounts(1) * fieldOr(phyParams, "Tsf", NaN);
    end
end

perceivedEnd = NaN;
perceivedEndMode = "NotApplicable";
if sharedChannel && methodCode == 1
    configuredPerceivedEnd = fieldOr( ...
        simParams, "coexA_endOfLteKnownBy11p", -1);
    if configuredPerceivedEnd == -1
        perceivedEnd = effectiveStaticCellularDuration;
        perceivedEndMode = "EffectiveCellularSidelinkBoundary";
    else
        perceivedEnd = configuredPerceivedEnd;
        perceivedEndMode = "Explicit";
    end
end

methodA = struct( ...
    "Enabled", sharedChannel && methodCode == 1, ...
    "GuardTimeSeconds", conditionalField( ...
        simParams, "coexA_guardTime", methodCode == 1), ...
    "EnhancementVariant", conditionalField( ...
        simParams, "coexA_improvements", methodCode == 1), ...
    "DesynchronizationErrorSeconds", conditionalField( ...
        simParams, "coexA_desynchError", methodCode == 1), ...
    "Ieee80211pPerceivedCellularSidelinkEndSeconds", perceivedEnd, ...
    "Ieee80211pPerceivedCellularSidelinkEndMode", ...
        perceivedEndMode, ...
    "LegacyIeee80211pNodesEnabled", conditionalField( ...
        simParams, "coexA_withLegacyITSG5", methodCode == 1));
methodB = struct( ...
    "Enabled", sharedChannel && methodCode == 2, ...
    "EnergySignalLeadTimeSeconds", conditionalField( ...
        simParams, "coexB_timeBeforeLTEstarts", methodCode == 2), ...
    "AllVehiclesTransmitInEmptySubframes", conditionalField( ...
        simParams, "coexB_allToTransmitInEmptySF", methodCode == 2));
methodC = struct( ...
    "Enabled", sharedChannel && methodCode == 3, ...
    "TimeGapVariant", conditionalField( ...
        simParams, "coexC_timegapVariant", methodCode == 3), ...
    "Ieee80211pDetectionEnabled", conditionalField( ...
        simParams, "coexC_11pDetection", methodCode == 3), ...
    "ModifiedContentionWindowEnabled", conditionalField( ...
        simParams, "coexCmodifiedCW", methodCode == 3), ...
    "MultipleSubframeIndicationEnabled", conditionalField( ...
        simParams, "coexC_moreThanOneSubframe", methodCode == 3));
methodF = struct( ...
    "Enabled", sharedChannel && methodCode == 6, ...
    "GuardTimeEnabled", conditionalField( ...
        simParams, "coexF_guardTime", methodCode == 6));

coexistence = struct( ...
    "Active", active, ...
    "InterferenceMode", coexistenceInterferenceMode(technology), ...
    "CellularSidelinkVehicleGroupSize", conditionalField( ...
        simParams, "numVehiclesLTE", active), ...
    "Ieee80211pVehicleGroupSize", conditionalField( ...
        simParams, "numVehicles11p", active), ...
    "MethodCode", methodCode, ...
    "Method", coexistenceMethodName(methodCode, sharedChannel), ...
    "SlotManagementCode", slotCode, ...
    "SlotManagement", slotManagementName(slotCode), ...
    "SuperframeDurationSeconds", conditionalField( ...
        simParams, "coex_superFlength", sharedChannel), ...
    "EffectiveStaticCellularSidelinkDurationSeconds", ...
        conditionalValue( ...
            effectiveStaticCellularDuration, ...
            staticSlotManagement), ...
    "CellularSidelinkCbrVariant", conditionalField( ...
        simParams, "coex_cbrLteVariant", sharedChannel), ...
    "CombinedCbrVariant", conditionalField( ...
        simParams, "coex_cbrTotVariant", sharedChannel), ...
    "MethodA", methodA, ...
    "MethodB", methodB, ...
    "MethodC", methodC, ...
    "MethodF", methodF);
end

function allocation = buildResourceAllocation(simParams, active)
if active && isfield(simParams, "resourceAllocationMetadata")
    metadata = simParams.resourceAllocationMetadata;
else
    metadata = struct;
end
allocation = struct( ...
    "Active", active, ...
    "Metadata", metadata);
end

function results = buildResults( ...
        stationManagement, simParams, phyParams, outputValues)
ranges = rowVector(requiredField(phyParams, "Raw"));
cellularActive = requiredField(outputValues, "AvgNUEsCV2X") > 0;
ieee80211pActive = requiredField(outputValues, "AvgNUEs11p") > 0;
combinedActive = requiredField(outputValues, "AvgNUEsTOT") > 0;

cellular = struct;
cellular.Active = cellularActive;
cellular.AverageUeCount = requiredField( ...
    outputValues, "AvgNUEsCV2X");
if cellularActive
    cellular.AwarenessRangeMetrics = buildAwarenessMetrics( ...
        ranges, ...
        requiredField(outputValues, "NneighborsCV2X"), ...
        requiredField(outputValues, "StDevNeighboursCV2X"), ...
        requiredField(outputValues, "NtxBeaconsCV2X"), ...
        requiredField(outputValues, "blockingRateCV2X"), ...
        requiredField(outputValues, "errorRateCV2X"), ...
        requiredField(outputValues, "packetReceptionRatioCV2X"), ...
        "MeanSnapshotNeighborCountStandardDeviation");
else
    cellular.AwarenessRangeMetrics = cell(1, 0);
end
cellular.AverageSuccessfulReassignmentsPerUePerSecond = ...
    conditionalValue( ...
        requiredField(outputValues, "NreassignCV2X"), cellularActive);
cellular.AverageInitialTransmissionsPerUePerSecond = ...
    conditionalValue( ...
        requiredField(outputValues, "cv2xTransmissionsFirst") / ...
        (requiredField(outputValues, "AvgNUEsCV2X") * ...
        requiredField(simParams, "simulationTime")), ...
        cellularActive);
cellular.AverageTransmissionsPerPacketIncludingHarq = ...
    conditionalValue( ...
        requiredField(outputValues, "cv2xTransmissionsIncHarq") / ...
        requiredField(outputValues, "cv2xTransmissionsFirst"), ...
        cellularActive);
cellular.ChannelBusyRatio = buildChannelBusyRatio( ...
    stationManagement, simParams, phyParams, ...
    "CellularSidelink", cellularActive);

ieee80211p = struct;
ieee80211p.Active = ieee80211pActive;
ieee80211p.AverageUeCount = requiredField( ...
    outputValues, "AvgNUEs11p");
if ieee80211pActive
    ieee80211p.AwarenessRangeMetrics = buildAwarenessMetrics( ...
        ranges, ...
        requiredField(outputValues, "Nneighbors11p"), ...
        requiredField(outputValues, "StDevNeighbours11p"), ...
        requiredField(outputValues, "NtxBeacons11p"), ...
        requiredField(outputValues, "blockingRate11p"), ...
        requiredField(outputValues, "errorRate11p"), ...
        requiredField(outputValues, "packetReceptionRatio11p"), ...
        "MeanSnapshotNeighborCountStandardDeviation");
else
    ieee80211p.AwarenessRangeMetrics = cell(1, 0);
end
firstRange = ranges(1);
ieee80211pOpportunities = requiredField( ...
    outputValues, "NtxBeacons11p");
averageOpportunityRate = conditionalValue( ...
    sum(ieee80211pOpportunities(:, :, 1), "all") / ...
    (requiredField(outputValues, "AvgNUEs11p") * ...
    indexedValue(requiredField(outputValues, "Nneighbors11p"), 1) * ...
    requiredField(simParams, "simulationTime")), ...
    ieee80211pActive);
ieee80211p.AverageTransmissionOpportunityRate = struct( ...
    "AwarenessRangeLowerBoundMeters", 0, ...
    "AwarenessRangeUpperBoundMeters", firstRange, ...
    "PerUePerNeighborPerSecond", averageOpportunityRate);
ieee80211p.ChannelBusyRatio = buildChannelBusyRatio( ...
    stationManagement, simParams, phyParams, ...
    "Ieee80211p", ieee80211pActive);

combined = struct;
combined.Active = combinedActive;
combined.AverageUeCount = requiredField( ...
    outputValues, "AvgNUEsTOT");
if combinedActive
    combined.AwarenessRangeMetrics = buildAwarenessMetrics( ...
        ranges, ...
        requiredField(outputValues, "NneighborsTOT"), ...
        requiredField(outputValues, "StDevNeighboursTOT"), ...
        requiredField(outputValues, "NtxBeaconsTOT"), ...
        requiredField(outputValues, "blockingRateTOT"), ...
        requiredField(outputValues, "errorRateTOT"), ...
        requiredField(outputValues, "packetReceptionRatioTOT"), ...
        "MeanSnapshotSumOfTechnologyNeighborCountStandardDeviations");
else
    combined.AwarenessRangeMetrics = cell(1, 0);
end
combined.ChannelBusyRatio = emptyChannelBusyRatio("NotApplicable");

results = struct( ...
    "CellularSidelink", cellular, ...
    "Ieee80211p", ieee80211p, ...
    "Combined", combined);
end

function metrics = buildAwarenessMetrics( ...
        ranges, neighborCounts, dispersions, opportunities, ...
        blockingRates, errorRates, receptionRatios, dispersionField)
metrics = cell(1, numel(ranges));
lowerBound = 0;
for index = 1:numel(ranges)
    metric = struct( ...
        "AwarenessRangeLowerBoundMeters", lowerBound, ...
        "AwarenessRangeUpperBoundMeters", ranges(index), ...
        "AverageNeighborCount", indexedValue( ...
            neighborCounts, index), ...
        "NonblockedTransmitterReceiverOpportunityCount", ...
            sum(opportunities(:, :, index), "all"), ...
        "BlockingRate", indexedValue(blockingRates, index), ...
        "ErrorRate", indexedValue(errorRates, index), ...
        "PacketReceptionRatio", indexedValue( ...
            receptionRatios, index));
    metric.(dispersionField) = indexedValue(dispersions, index);
    metrics{index} = metric;
    lowerBound = ranges(index);
end
end

function result = buildChannelBusyRatio( ...
        stationManagement, simParams, phyParams, technology, active)
discardedSampleCount = 10;
if ~active
    result = emptyChannelBusyRatio("NotApplicable");
    return
end
if ~logical(fieldOr(simParams, "cbrActive", false))
    result = emptyChannelBusyRatio("Disabled");
    return
end

channelCount = fieldOr(phyParams, "nChannels", 1);
vehicleStates = fieldOr(stationManagement, "vehicleState", []);
vehicleChannels = fieldOr(stationManagement, "vehicleChannel", []);
if technology == "CellularSidelink"
    eligibleVehicles = vehicleStates == 100;
    values = fieldOr(stationManagement, "cbrCV2Xvalues", []);
    dccFlags = fieldOr( ...
        stationManagement, "dccLteTriggered", ...
        false(1, channelCount));
    harqFlags = fieldOr( ...
        stationManagement, "dccLteTriggeredHarq", ...
        false(1, channelCount));
else
    eligibleVehicles = vehicleStates ~= 100;
    values = fieldOr(stationManagement, "cbr11pValues", []);
    dccFlags = fieldOr( ...
        stationManagement, "dcc11pTriggered", ...
        false(1, channelCount));
    harqFlags = nan(1, channelCount);
end

if ~any(eligibleVehicles)
    channels = emptyCbrChannels( ...
        channelCount, dccFlags, harqFlags, "NoEligibleUes");
    result = channelBusyRatio( ...
        "NoEligibleUes", discardedSampleCount, channels);
    return
end
if size(values, 2) <= discardedSampleCount
    channels = emptyCbrChannels( ...
        channelCount, dccFlags, harqFlags, ...
        "InsufficientSamples");
    result = channelBusyRatio( ...
        "InsufficientSamples", discardedSampleCount, channels);
    return
end

channels = emptyCbrChannels( ...
    channelCount, dccFlags, harqFlags, "NoValidSamples");
hasAnyValidSample = false;
for channelIndex = 1:channelCount
    rows = eligibleVehicles & vehicleChannels == channelIndex;
    channelValues = values(rows, discardedSampleCount + 1:end);
    channelValues = channelValues(:);
    channelValues = channelValues(channelValues >= 0);
    if isempty(channelValues)
        medianRatio = NaN;
    else
        medianRatio = median(channelValues);
        channels{channelIndex}.Status = "Available";
        hasAnyValidSample = true;
    end
    channels{channelIndex}.MedianRatio = medianRatio;
end
if hasAnyValidSample
    status = "Available";
else
    status = "NoValidSamples";
end
result = channelBusyRatio( ...
    status, discardedSampleCount, channels);
end

function result = emptyChannelBusyRatio(status)
result = channelBusyRatio(status, 0, cell(1, 0));
end

function result = channelBusyRatio(status, warmupSampleCount, channels)
result = struct;
result.Status = status;
result.WarmupSampleCountRequired = warmupSampleCount;
result.Channels = channels;
end

function channels = emptyCbrChannels( ...
        channelCount, dccFlags, harqFlags, status)
channels = cell(1, channelCount);
for channelIndex = 1:channelCount
    channels{channelIndex} = struct( ...
        "ChannelIndex", channelIndex, ...
        "Status", status, ...
        "MedianRatio", NaN, ...
        "CongestionControlTriggered", ...
            logical(indexedValue(dccFlags, channelIndex)), ...
        "HarqCongestionControlTriggered", ...
            indexedValue(harqFlags, channelIndex));
end
end

function value = requiredField(source, name)
if ~isfield(source, name)
    error( ...
        "v2xsim:output:MissingSummaryInput", ...
        "Summary input is missing required field ""%s"".",name);
end
value = source.(name);
end

function value = fieldOr(source, name, defaultValue)
if isfield(source, name)
    value = source.(name);
else
    value = defaultValue;
end
end

function value = conditionalField(source, name, applicable)
if applicable && isfield(source, name)
    value = source.(name);
else
    value = NaN;
end
end

function value = conditionalTextField(source, name, applicable)
if applicable && isfield(source, name)
    value = string(source.(name));
else
    value = "";
end
end

function value = conditionalValue(candidate, applicable)
if applicable
    value = candidate;
else
    value = NaN;
end
end

function value = textField(source, name, defaultValue)
value = string(fieldOr(source, name, defaultValue));
end

function value = indexedValue(values, index)
if numel(values) >= index
    value = values(index);
else
    value = NaN;
end
end

function values = rowVector(values)
values = reshape(values, 1, []);
end

function values = defaultChannelProportions(channelCount)
if channelCount == 1
    values = 1;
else
    values = nan(1, channelCount);
end
end

function value = radioAccessMode(simParams)
technology = requiredField(simParams, "technology");
mode5G = fieldOr(simParams, "mode5G", 0);
switch technology
    case 1
        if mode5G == 1
            value = "NR-V2X";
        else
            value = "LTE-V2X";
        end
    case 2
        value = "80211p";
    case 3
        value = "COEX-NO-INTERF";
    case 4
        if mode5G == 1
            value = "COEX-STD-INTERF-5G";
        else
            value = "COEX-STD-INTERF";
        end
    otherwise
        value = "Unknown";
end
end

function value = simulatorVersion(simParams)
if isfield(simParams, "SimulatorVersion")
    value = string(simParams.SimulatorVersion);
elseif isfield(simParams, "CheckVersion")
    value = string(simParams.CheckVersion);
elseif exist("constants", "class") == 8
    value = string(constants.SIM_VERSION);
else
    % Keep the pure builder usable with only src on the path. Simulator
    % integration takes the constants branch above.
    value = "V7";
end
end

function value = channelModelName(modelCode)
names = [ ...
    "WinnerPlusB1", ...
    "SingleSlope", ...
    "TwoSlope", ...
    "ThreeSlope", ...
    "NrNlosVehicle"];
if isfinite(modelCode) && modelCode >= 0 && ...
        modelCode < numel(names) && modelCode == fix(modelCode)
    value = names(modelCode + 1);
else
    value = "Unknown";
end
end

function value = coexistenceInterferenceMode(technology)
switch technology
    case 3
        value = "Orthogonal";
    case 4
        value = "SharedChannel";
    otherwise
        value = "NotApplicable";
end
end

function value = coexistenceMethodName(methodCode, applicable)
if ~applicable
    value = "NotApplicable";
    return
end
switch methodCode
    case 0
        value = "StandardProtocols";
    case 1
        value = "A";
    case 2
        value = "B";
    case 3
        value = "C";
    case 6
        value = "F";
    otherwise
        value = "Unknown";
end
end

function value = slotManagementName(slotCode)
switch slotCode
    case 1
        value = "Static";
    case 2
        value = "Dynamic";
    otherwise
        value = "NotApplicable";
end
end

function mode = residualSelfInterferenceMode(value, applicable)
if ~applicable
    mode = "NotApplicable";
elseif isnan(value)
    mode = "Invalid";
elseif value == -Inf
    mode = "PerfectCancellation";
elseif value == Inf
    mode = "UnboundedResidualInterference";
else
    mode = "Finite";
end
end

function mode = selfInterferenceThresholdMultiplierMode( ...
        value, applicable)
if ~applicable
    mode = "NotApplicable";
elseif isnan(value)
    mode = "Invalid";
elseif value == Inf
    mode = "ThresholdDisabled";
elseif value == -Inf
    mode = "NegativeInfinity";
else
    mode = "Finite";
end
end
