function context = buildResourceAllocationContext( ...
        allocator,sensingHistory,simValues,stationManagement, ...
        timeManagement,positionManagement,sinrManagement, ...
        simParams,absoluteSlot)
%BUILDRESOURCEALLOCATIONCONTEXT Adapt legacy arrays at one sealed boundary.

activeIds = stationManagement.activeIDsCV2X(:);
ueIds = simValues.world.UeIds(activeIds);
grid = allocator.Grid;
selectionOriginSlot = selectionOriginSlots( ...
    activeIds,timeManagement,grid,absoluteSlot);
eligibility = buildEligibility( ...
    allocator,activeIds,sinrManagement,simParams,grid, ...
    selectionOriginSlot,absoluteSlot);
newPacketMask = false(numel(activeIds),1);
if isfield(timeManagement,"timeLastPacket")
    newPacketMask = ...
        timeManagement.timeLastPacket(activeIds) > ...
        timeManagement.timeNow - grid.SlotDurationSeconds - 1e-8;
end

switch allocator.ContextContract
    case "ThreeGpp"
        firstTransmissionMask = false(numel(activeIds),1);
        if isfield(stationManagement,"transmittingIDsCV2X") && ...
                isfield(stationManagement,"pckTxOccurring")
            firstTransmissionIds = ...
                stationManagement.transmittingIDsCV2X( ...
                stationManagement.pckTxOccurring( ...
                stationManagement.transmittingIDsCV2X) == 1);
            firstTransmissionMask = ...
                ismember(activeIds,firstTransmissionIds);
        end

        assignments = allocator.Assignments.ResourceIds;
        hasPrimaryThisSlot = false(numel(activeIds),1);
        assigned = ~isnan(assignments(:,1));
        primaryTime = zeros(numel(activeIds),1);
        primaryTime(assigned) = ceil( ...
            assignments(assigned,1) / ...
            grid.NumberFrequencyResources);
        hasPrimaryThisSlot(assigned) = ...
            primaryTime(assigned) == ...
            grid.periodicSlot(absoluteSlot);
        skippedReservedMask = ...
            hasPrimaryThisSlot & ~firstTransmissionMask;

        context = v2xsim.resource.ThreeGppAllocationContext( ...
            grid.NetworkSliceId,ueIds,absoluteSlot,newPacketMask, ...
            eligibility,sensingHistory.snapshot( ...
            simParams.averageSensingActive), ...
            firstTransmissionMask,skippedReservedMask, ...
            stationManagement.pckBuffer(activeIds) > 0, ...
            stationManagement.cv2xNumberOfReplicas(activeIds), ...
            selectionOriginSlot);
    case "Autonomous"
        averageSensing = false;
        if isfield(simParams,"averageSensingActive")
            averageSensing = simParams.averageSensingActive;
        end
        context = v2xsim.resource.AutonomousAllocationContext( ...
            grid.NetworkSliceId,ueIds,absoluteSlot,newPacketMask, ...
            eligibility,sensingHistory.snapshot(averageSensing), ...
            selectionOriginSlot);
    case "Centralized"
        activeIndexes = ...
            stationManagement.indexInActiveIDs_ofLTEnodes(:);
        context = v2xsim.resource.CentralizedAllocationContext( ...
            grid.NetworkSliceId,ueIds,absoluteSlot,newPacketMask, ...
            eligibility,simValues.XvehicleEstimated(activeIds), ...
            positionManagement.distanceEstimated(activeIds,activeIds), ...
            positionManagement.distanceReal(activeIds,activeIds), ...
            sinrManagement.P_RX_MHz(activeIndexes,activeIndexes), ...
            sinrManagement.Shadowing_dB(activeIndexes,activeIndexes), ...
            selectionOriginSlot);
    case "Basic"
        context = v2xsim.resource.ResourceAllocationContext( ...
            grid.NetworkSliceId,ueIds,absoluteSlot,newPacketMask, ...
            eligibility,selectionOriginSlot);
    otherwise
        error( ...
            "v2xsim:resource:UnknownContextContract", ...
            "Unknown resource-allocation context contract ""%s"".", ...
            allocator.ContextContract);
end
end

function eligibility = buildEligibility( ...
        allocator,activeIds,sinrManagement,simParams,grid, ...
        selectionOriginSlot,currentSlot)
ueCount = numel(activeIds);
eligibility = true(ueCount,grid.ResourceCount);

if ~isfield(simParams,"resourcePressure") || ...
        simParams.resourcePressure.NetworkSliceId ~= grid.NetworkSliceId
    error( ...
        "v2xsim:resource:MissingResourcePressure", ...
        "The allocation context requires resource pressure for its network slice.");
end
eligibility = eligibility & simParams.resourcePressure.eligibilityMask(ueCount);

if allocator.UsesSelectionWindow
    eligibility = eligibility & ...
        v2xsim.resource.algorithm.buildSelectionWindowEligibility( ...
            grid,selectionOriginSlot,currentSlot, ...
            simParams.T1autonomousModeTTIs, ...
            simParams.T2autonomousModeTTIs);
end

hasMitigation = ...
    simParams.technology == constants.TECH_COEX_STD_INTERF && ...
    simParams.coexMethod ~= constants.COEX_METHOD_NON;
if hasMitigation
    resourceTime = ceil( ...
        (1:grid.ResourceCount) / grid.NumberFrequencyResources);
    for row = 1:ueCount
        availableSlots = ...
            sinrManagement.coex_NtotTTILTE(activeIds(row));
        superframeSlot = mod( ...
            resourceTime - 1,simParams.coex_superframeTTI) + 1;
        eligibility(row,superframeSlot > availableSlots) = false;
    end
end
end

function originSlot = selectionOriginSlots( ...
        activeIds,timeManagement,grid,currentSlot)
originSlot = repmat(currentSlot,numel(activeIds),1);
packetTimes = -inf(numel(activeIds),1);
if isfield(timeManagement,"timeLastPacket")
    packetTimes = timeManagement.timeLastPacket(activeIds);
end
needsInitialOrigin = packetTimes < 0;
if isfield(timeManagement,"timeNextPacket")
    packetTimes(needsInitialOrigin) = ...
        timeManagement.timeNextPacket(activeIds(needsInitialOrigin));
end
hasPacketOrigin = isfinite(packetTimes) & packetTimes >= 0;
originSlot(hasPacketOrigin) = max( ...
    ceil(packetTimes(hasPacketOrigin) / grid.SlotDurationSeconds) - 1, ...
    0);
end
