function dispatchAfterResourceAllocationDecision( ...
        simValues,timeManagement,context,result)
%DISPATCHAFTERRESOURCEALLOCATIONDECISION Publish one allocator snapshot.

if ~isfield(simValues,"hookDispatcher") || ...
        isempty(result.DecisionUeIds)
    return
end
invocation = v2xsim.hook.invocations. ...
    AfterResourceAllocationDecisionInvocation( ...
        timeManagement.timeNow, ...
        simValues.resourceAllocationEpoch,context,result);
simValues.hookDispatcher.dispatch( ...
    v2xsim.hook.points.AfterResourceAllocationDecision,invocation);
end
