function stationManagement = projectResourceAllocation( ...
        stationManagement,simValues,result,grid)
%PROJECTRESOURCEALLOCATION Project the sole global slice to legacy BRid.

globalSliceId = v2xsim.network.NetworkSliceId("global");
if grid.NetworkSliceId ~= globalSliceId || ...
        result.NetworkSliceId ~= globalSliceId
    error( ...
        "v2xsim:resource:UnsupportedSliceComposition", ...
        "The legacy scheduler can project only the global network slice.");
end

activeIds = stationManagement.activeIDsCV2X(:);
activeUeIds = simValues.world.UeIds(activeIds);
[found,assignmentRows] = ismember( ...
    activeUeIds,result.Assignments.UeId);
if ~all(found)
    error( ...
        "v2xsim:resource:LegacyProjectionIdentityMismatch", ...
        "Every active C-V2X UE must have one allocator assignment.");
end

stationManagement.BRid( ...
    stationManagement.vehicleState == constants.V_STATE_LTE_TXRX,:) = -1;
resourceIds = result.Assignments.ResourceIds(assignmentRows,:);
resourceIds(isnan(resourceIds)) = constants.BRID_ACTV_LTE_NO_RSRC;
stationManagement.BRid(activeIds,:) = resourceIds;
stationManagement.BRid( ...
    stationManagement.vehicleState ~= constants.V_STATE_LTE_TXRX,:) = ...
    constants.BRID_NOT_LTE;

stationManagement.resourceReservations = false( ...
    grid.ResourceCount,size(stationManagement.BRid,1));
if ~isempty(result.Reservations)
    [knownUe,reservingIds] = ismember( ...
        result.Reservations.UeId,simValues.world.UeIds);
    if ~all(knownUe) || ...
            ~all(ismember(reservingIds,activeIds))
        error( ...
            "v2xsim:resource:LegacyProjectionIdentityMismatch", ...
            "Reservations must belong to active C-V2X UEs.");
    end
    reservationIndexes = sub2ind( ...
        size(stationManagement.resourceReservations), ...
        result.Reservations.ResourceId,reservingIds);
    stationManagement.resourceReservations(reservationIndexes) = true;
end
end
