function [simValues,stationManagement,timeManagement,sinrManagement, ...
        reassignedCount] = stepResourceAllocation( ...
            simValues,stationManagement,timeManagement, ...
            positionManagement,sinrManagement,simParams,phyParams, ...
            appParams,outParams)
%STEPRESOURCEALLOCATION Shared sensing followed by one polymorphic step.

allocator = simValues.resourceAllocator;
activeIds = stationManagement.activeIDsCV2X(:);
ueIds = simValues.world.UeIds(activeIds);
allocator = allocator.synchronizeUes(ueIds);
sensingHistory = simValues.sensingHistory.synchronizeUes(ueIds);

[timeManagement,stationManagement,sinrManagement] = ...
    CV2XsensingProcedure( ...
        timeManagement,stationManagement,sinrManagement, ...
        simParams,phyParams,appParams,outParams);

absoluteSlot = timeManagement.elapsedTime_TTIs - 1;
periodicSlot = allocator.Grid.periodicSlot(absoluteSlot);
resourceColumns = allocator.Grid.resourceId( ...
    periodicSlot,1:allocator.Grid.NumberFrequencyResources);
currentEnergy = permute( ...
    stationManagement.sensingMatrixCV2X( ...
        1,resourceColumns,activeIds),[3 2 1]);
reservedMask = logical( ...
    stationManagement.knownUsedMatrixCV2X(:,activeIds).');
sensingHistory = sensingHistory.update( ...
    allocator.Grid.NetworkSliceId,ueIds,absoluteSlot, ...
    currentEnergy,reservedMask);

% Keep the old CBR implementation as a projection of the shared component.
stationManagement.sensingMatrixCV2X(:) = 0;
stationManagement.sensingMatrixCV2X(:,:,activeIds) = ...
    sensingHistory.EnergyHistory;

context = buildResourceAllocationContext( ...
    allocator,sensingHistory,simValues,stationManagement, ...
    timeManagement,positionManagement,sinrManagement, ...
    simParams,absoluteSlot);
[allocator,result] = allocator.step(context);
stationManagement = projectResourceAllocation( ...
    stationManagement,simValues,result,allocator.Grid);

simValues.resourceAllocator = allocator;
simValues.sensingHistory = sensingHistory;
simValues.resourceAllocationResult = result;
reassignedCount = numel(result.ReassignedUeIds);
end
