classdef RadioNodeState < handle
    %RADIONODESTATE Owns aligned per-node radio runtime state.
    %   Handle semantics provide one explicit owner for mutable power,
    %   timer, and counter values. Node identifiers are positive integers
    %   and do not depend on positions in a legacy dense state struct.

    properties (SetAccess = private)
        NodeIds (:, 1) uint64 = zeros(0, 1, "uint64")
        TransmitPowersDbm (:, 1) double = zeros(0, 1)
        TimersSeconds (:, 1) double = zeros(0, 1)
        Counters (:, 1) uint64 = zeros(0, 1, "uint64")
    end

    methods
        function obj = RadioNodeState( ...
                nodeIds, transmitPowersDbm, timersSeconds, counters)
            arguments (Input)
                nodeIds = zeros(0, 1)
                transmitPowersDbm = zeros(0, 1)
                timersSeconds = zeros(0, 1)
                counters = zeros(0, 1)
            end

            obj.replace( ...
                nodeIds, transmitPowersDbm, timersSeconds, counters);
        end

        function replace( ...
                obj, nodeIds, transmitPowersDbm, timersSeconds, counters)
            %REPLACE Atomically replace all aligned node state.
            arguments (Input)
                obj (1, 1)
                nodeIds
                transmitPowersDbm
                timersSeconds
                counters
            end

            [nodeIds, transmitPowersDbm, timersSeconds, counters] = ...
                v2xsim.runtime.RadioNodeState.validateState( ...
                    nodeIds, transmitPowersDbm, ...
                    timersSeconds, counters);
            obj.NodeIds = nodeIds;
            obj.TransmitPowersDbm = transmitPowersDbm;
            obj.TimersSeconds = timersSeconds;
            obj.Counters = counters;
        end

        function updateNode( ...
                obj, nodeId, transmitPowerDbm, timerSeconds, counter)
            %UPDATENODE Replace all runtime values for one existing node.
            arguments (Input)
                obj (1, 1)
                nodeId
                transmitPowerDbm
                timerSeconds
                counter
            end

            [validatedId, validatedPower, validatedTimer, ...
                validatedCounter] = ...
                v2xsim.runtime.RadioNodeState.validateState( ...
                    nodeId, transmitPowerDbm, timerSeconds, counter);
            nodeIndex = find(obj.NodeIds == validatedId, 1);
            if isempty(nodeIndex)
                error( ...
                    "v2xsim:runtime:UnknownNodeId", ...
                    "Radio state has no node with identifier %s.", ...
                    string(validatedId));
            end

            obj.TransmitPowersDbm(nodeIndex) = validatedPower;
            obj.TimersSeconds(nodeIndex) = validatedTimer;
            obj.Counters(nodeIndex) = validatedCounter;
        end

        function nodes = snapshot(obj)
            %SNAPSHOT Return a value-semantic table of current node state.
            arguments (Input)
                obj (1, 1)
            end
            arguments (Output)
                nodes table
            end

            nodes = table( ...
                obj.NodeIds, obj.TransmitPowersDbm, ...
                obj.TimersSeconds, obj.Counters, ...
                VariableNames=[ ...
                    "NodeId", "TransmitPowerDbm", ...
                    "TimerSeconds", "Counter"]);
        end
    end

    methods (Static, Access = private)
        function [nodeIds, powers, timers, counters] = ...
                validateState(nodeIds, powers, timers, counters)
            nodeIds = ...
                v2xsim.runtime.RadioNodeState.validateNodeIds(nodeIds);
            nodeCount = numel(nodeIds);

            if ~isnumeric(powers) || ~isreal(powers) || ...
                    (~isempty(powers) && ~isvector(powers)) || ...
                    any(~isfinite(powers))
                error( ...
                    "v2xsim:runtime:InvalidTransmitPowers", ...
                    "Transmit powers must be a finite real vector.");
            end
            powers = double(powers(:));

            if ~isnumeric(timers) || ~isreal(timers) || ...
                    (~isempty(timers) && ~isvector(timers)) || ...
                    any(isnan(timers)) || any(timers < 0)
                error( ...
                    "v2xsim:runtime:InvalidTimers", ...
                    "Timers must be a nonnegative real vector without NaN.");
            end
            timers = double(timers(:));

            if ~isnumeric(counters) || ~isreal(counters) || ...
                    (~isempty(counters) && ~isvector(counters)) || ...
                    any(~isfinite(counters)) || ...
                    any(counters < 0) || any(mod(counters, 1) ~= 0) || ...
                    any(counters > flintmax)
                error( ...
                    "v2xsim:runtime:InvalidCounters", ...
                    "Counters must be exactly representable " + ...
                    "nonnegative integers.");
            end
            counters = uint64(counters(:));

            if numel(powers) ~= nodeCount || ...
                    numel(timers) ~= nodeCount || ...
                    numel(counters) ~= nodeCount
                error( ...
                    "v2xsim:runtime:NodeStateSizeMismatch", ...
                    "Node identifiers, powers, timers, and counters " + ...
                    "must have equal lengths.");
            end
        end

        function nodeIds = validateNodeIds(nodeIds)
            if ~isnumeric(nodeIds) || ~isreal(nodeIds) || ...
                    (~isempty(nodeIds) && ~isvector(nodeIds)) || ...
                    any(~isfinite(nodeIds)) || ...
                    any(nodeIds <= 0) || any(mod(nodeIds, 1) ~= 0) || ...
                    any(nodeIds > flintmax)
                error( ...
                    "v2xsim:runtime:InvalidNodeIds", ...
                    "Node identifiers must be exactly representable " + ...
                    "positive integers.");
            end
            nodeIds = uint64(nodeIds(:));
            if numel(unique(nodeIds)) ~= numel(nodeIds)
                error( ...
                    "v2xsim:runtime:DuplicateNodeId", ...
                    "Node identifiers must be unique.");
            end
        end
    end
end
