classdef SimulationResult
    %SIMULATIONRESULT Immutable record of one completed simulation.
    %   The result retains the resolved configuration and compiled plan,
    %   finalized metrics, artifact paths, and the run directory without
    %   depending on legacy runtime structures.

    properties (SetAccess = immutable)
        % These value classes have no zero-input constructors. Constructor
        % validation provides the type boundary without invalid defaults.
        Configuration
        Plan
        Metrics (1, 1) struct
        Artifacts (:, 1) string
        RunDirectory (1, 1) string
        AppliedPositionErrorChain (1, 1) struct
    end

    methods
        function obj = SimulationResult( ...
                configuration, plan, metrics, artifacts, runDirectory, ...
                appliedPositionErrorChain)
            arguments (Input)
                configuration (1, 1) ...
                    v2xsim.config.ResolvedConfiguration
                plan (1, 1) v2xsim.runtime.CompiledSimulationPlan
                metrics (1, 1) struct
                artifacts string
                runDirectory (1, 1) string
                appliedPositionErrorChain (1, 1) struct = struct( ...
                    "Enabled", false, "Modules", {{}})
            end

            if ~isequal(configuration, plan.Configuration)
                error( ...
                    "v2xsim:runtime:ConfigurationPlanMismatch", ...
                    "SimulationResult configuration must be the " + ...
                    "configuration compiled into its plan.");
            end
            v2xsim.runtime.SimulationResult.validateMetrics(metrics);

            if ~isvector(artifacts) && ~isempty(artifacts)
                error( ...
                    "v2xsim:runtime:InvalidArtifacts", ...
                    "Artifacts must be a string vector.");
            end
            artifacts = artifacts(:);
            if any(ismissing(artifacts)) || ...
                    any(strlength(strip(artifacts)) == 0)
                error( ...
                    "v2xsim:runtime:InvalidArtifacts", ...
                    "Artifact paths must be nonblank.");
            end
            if numel(unique(artifacts)) ~= numel(artifacts)
                error( ...
                    "v2xsim:runtime:DuplicateArtifact", ...
                    "Artifact paths must be unique.");
            end

            runDirectory = strip(runDirectory);
            if ismissing(runDirectory) || strlength(runDirectory) == 0
                error( ...
                    "v2xsim:runtime:InvalidRunDirectory", ...
                    "RunDirectory must be nonblank.");
            end
            v2xsim.runtime.SimulationResult. ...
                validateAppliedPositionErrorChain( ...
                    appliedPositionErrorChain);

            obj.Configuration = configuration;
            obj.Plan = plan;
            obj.Metrics = metrics;
            obj.Artifacts = artifacts;
            obj.RunDirectory = runDirectory;
            obj.AppliedPositionErrorChain = appliedPositionErrorChain;
        end
    end

    methods (Static, Access = private)
        function validateMetrics(metrics)
            expectedFields = ["Metrics", "Events"];
            actualFields = string(fieldnames(metrics)).';
            if numel(actualFields) ~= numel(expectedFields) || ...
                    ~all(ismember(expectedFields, actualFields)) || ...
                    ~istable(metrics.Metrics) || ...
                    ~istable(metrics.Events)
                error( ...
                    "v2xsim:runtime:InvalidMetricsSnapshot", ...
                    "Metrics must be a MetricsAccumulator snapshot.");
            end

            metricNames = string( ...
                metrics.Metrics.Properties.VariableNames);
            eventNames = string( ...
                metrics.Events.Properties.VariableNames);
            if ~isequal(metricNames, ["Name", "Value"]) || ...
                    ~isequal(eventNames, [ ...
                        "Name", "SimulationTimeSeconds", "Details"]) || ...
                    ~isstring(metrics.Metrics.Name) || ...
                    ~isnumeric(metrics.Metrics.Value) || ...
                    ~isstring(metrics.Events.Name) || ...
                    ~isnumeric(metrics.Events.SimulationTimeSeconds) || ...
                    ~iscell(metrics.Events.Details)
                error( ...
                    "v2xsim:runtime:InvalidMetricsSnapshot", ...
                    "Metrics snapshot tables have an invalid schema.");
            end
            if any(ismissing(metrics.Metrics.Name)) || ...
                    any(strlength(strip(metrics.Metrics.Name)) == 0) || ...
                    any(~isfinite(metrics.Metrics.Value)) || ...
                    any(ismissing(metrics.Events.Name)) || ...
                    any(strlength(strip(metrics.Events.Name)) == 0) || ...
                    any(~isfinite( ...
                        metrics.Events.SimulationTimeSeconds)) || ...
                    any(metrics.Events.SimulationTimeSeconds < 0) || ...
                    any(~cellfun(@(value) ...
                        isstruct(value) && isscalar(value), ...
                        metrics.Events.Details))
                error( ...
                    "v2xsim:runtime:InvalidMetricsSnapshot", ...
                    "Metrics snapshot values are invalid.");
            end
        end

        function validateAppliedPositionErrorChain(value)
            expectedFields = ["Enabled", "Modules"];
            actualFields = string(fieldnames(value)).';
            hasExpectedFields = ...
                numel(actualFields) == numel(expectedFields) && ...
                all(ismember(expectedFields, actualFields));
            if ~hasExpectedFields || ...
                    ~islogical(value.Enabled) || ...
                    ~isscalar(value.Enabled) || ...
                    ~iscell(value.Modules) || ...
                    (~isrow(value.Modules) && ~isempty(value.Modules)) || ...
                    any(~cellfun( ...
                        @(module) isstruct(module) && isscalar(module), ...
                        value.Modules))
                error( ...
                    "v2xsim:runtime:InvalidAppliedPositionErrorChain", ...
                    "AppliedPositionErrorChain must contain logical " + ...
                    "Enabled and a row cell array of scalar module " + ...
                    "descriptors.");
            end
            if value.Enabled ~= ~isempty(value.Modules)
                error( ...
                    "v2xsim:runtime:InvalidAppliedPositionErrorChain", ...
                    "AppliedPositionErrorChain.Enabled must agree " + ...
                    "with whether Modules is empty.");
            end
        end
    end
end
