classdef ExitRampPositionErrorContextTest < matlab.unittest.TestCase
    %EXITRAMPPOSITIONERRORCONTEXTTEST Tests ramp-specific context contracts.

    methods (Test)
        function testCapturesExitRampScenarioSnapshot(testCase)
            scenario = testCase.createScenario();

            context = ...
                v2xsim.positioning.ExitRampPositionErrorContext( ...
                    scenario, 2.5, 0.1, 10);

            testCase.verifyTrue(isa( ...
                context, "v2xsim.positioning.PositionErrorContext"));
            testCase.verifyEqual( ...
                context.ActualPositions, ...
                scenario.VehicleKinematics(:, ["X", "Y"]));
            testCase.verifyEqual(context.Geometry, scenario.Geometry);
            testCase.verifyEqual( ...
                context.LaneNetwork, scenario.LaneNetwork);
            testCase.verifyEqual( ...
                context.VehicleLaneStates, ...
                scenario.VehicleLaneStates);
            testCase.verifyEqual( ...
                context.VehicleRouteStates, ...
                scenario.VehicleRouteStates);
        end

        function testFalseRouteInflictorAcceptsExitRampContext(testCase)
            scenario = testCase.createScenario();
            context = ...
                v2xsim.positioning.ExitRampPositionErrorContext( ...
                    scenario, 0, 0.1, 10);
            module = testCase.createFalseExitInflictor();

            [~, apparentPositions] = module.apply( ...
                context.ActualPositions, context);

            testCase.verifyEqual( ...
                apparentPositions, context.ActualPositions);
        end

        function testFalseRouteInflictorRejectsGenericContext(testCase)
            scenario = testCase.createScenario();
            actualPositions = ...
                scenario.VehicleKinematics(:, ["X", "Y"]);
            context = v2xsim.positioning.PositionErrorContext( ...
                actualPositions, 0, 0.1, 10);
            module = testCase.createFalseExitInflictor();

            testCase.verifyError( ...
                @() module.apply(actualPositions, context), ...
                "v2xsim:positioning:UnsupportedErrorContext");
        end

        function testBuildsRowOrderedFalseRouteProjections(testCase)
            scenario = testCase.createScenario();
            context = ...
                v2xsim.positioning.ExitRampPositionErrorContext( ...
                    scenario, 0, 0.1, 10);
            allIds = string( ...
                context.ActualPositions.Properties.RowNames);
            requestedIds = flip(allIds(1:min(8, numel(allIds))));

            falseExit = context.getRouteProjection( ...
                "FalseExit", requestedIds);
            falseMerge = context.getRouteProjection( ...
                "FalseMerge", requestedIds);
            routes = context.VehicleRouteStates( ...
                cellstr(requestedIds), :).Route;

            testCase.verifyEqual( ...
                string(falseExit.Properties.RowNames), requestedIds);
            testCase.verifyEqual(falseExit.TrueRoute, routes);
            testCase.verifyEqual( ...
                falseExit.IsEligible, routes ~= "Regular");
            testCase.verifyEqual( ...
                falseExit.IsApplicable, ...
                routes == "Merge" | routes == "Adjacent");
            testCase.verifyEqual( ...
                falseMerge.IsApplicable, routes == "Ramp");
            testCase.verifyTrue(all(isfinite( ...
                [falseExit.TargetX; falseExit.TargetY; ...
                falseMerge.TargetX; falseMerge.TargetY])));
        end
    end

    methods (Access = private)
        function module = createFalseExitInflictor(~)
            effect = v2xsim.positioning. ...
                FalseExitPositionErrorStatusEffect(1);
            module = v2xsim.positioning. ...
                PositionErrorStatusEffectInflictor(effect);
        end

        function scenario = createScenario(~)
            scenario = ...
                v2xsim.vehicle.scenarios.ExitRampHighwayScenario( ...
                    20, ...
                    RandomSeed=100, ...
                    RoadLength=200, ...
                    MergeDistance=40);
        end
    end
end
