classdef FalseExitPositionErrorStatusEffectTest < ...
        matlab.unittest.TestCase
    %FALSEEXITPOSITIONERRORSTATUSEFFECTTEST False exit observations.

    methods (Test)
        function testProjectsMergingVehiclesOntoRamp(testCase)
            scenario = testCase.createScenario(0, 40);
            context = testCase.createContext(scenario, 0, 20);
            apparentPositions = context.ActualPositions;
            apparentPositions.X = apparentPositions.X + 2;
            apparentPositions.Y = apparentPositions.Y - 3;
            module = testCase.createFalseExitInflictor(1);
            affected = testCase.getAffectedVehicles(context);
            testCase.assertTrue(any(affected));

            [~, outputPositions] = module.apply( ...
                apparentPositions, context);

            falsePositions = testCase.getRampPositions( ...
                context, affected);
            testCase.verifyEqual( ...
                outputPositions.X(affected), ...
                falsePositions(:, 1) + 2, ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                outputPositions.Y(affected), ...
                falsePositions(:, 2) - 3, ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                outputPositions(~affected, :), ...
                apparentPositions(~affected, :));
        end

        function testZeroProbabilityLeavesPositionsUnchanged(testCase)
            scenario = testCase.createScenario(0, 40);
            context = testCase.createContext(scenario, 0, 10);
            module = testCase.createFalseExitInflictor(0);

            [~, outputPositions] = module.apply( ...
                context.ActualPositions, context);

            testCase.verifyEqual( ...
                outputPositions, context.ActualPositions);
        end

        function testFiniteResetTeleportsVehiclesBackToTruth(testCase)
            scenario = testCase.createScenario(0, 40);
            module = testCase.createFalseExitInflictor( ...
                1, ResetAfterSeconds=2);
            initialContext = testCase.createContext(scenario, 0, 10);
            affected = testCase.getAffectedVehicles(initialContext);
            testCase.assertTrue(any(affected));

            [module, falsePositions] = module.apply( ...
                initialContext.ActualPositions, initialContext);
            oneSecondContext = testCase.createContext(scenario, 1, 10);
            [module, beforeReset] = module.apply( ...
                oneSecondContext.ActualPositions, oneSecondContext);
            resetContext = testCase.createContext(scenario, 2, 10);
            [module, afterReset] = module.apply( ...
                resetContext.ActualPositions, resetContext);
            afterRepairContext = testCase.createContext(scenario, 3, 10);
            [~, afterRepair] = module.apply( ...
                afterRepairContext.ActualPositions, afterRepairContext);

            testCase.verifyNotEqual( ...
                falsePositions(affected, :), ...
                initialContext.ActualPositions(affected, :));
            testCase.verifyEqual( ...
                beforeReset(affected, :), ...
                falsePositions(affected, :), ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                afterReset, resetContext.ActualPositions);
            testCase.verifyEqual( ...
                afterRepair, afterRepairContext.ActualPositions);
        end

        function testDefaultStatusEffectDoesNotExpire(testCase)
            scenario = testCase.createScenario(0, 40);
            module = testCase.createFalseExitInflictor(1);
            initialContext = testCase.createContext(scenario, 0, 20);
            affected = testCase.getAffectedVehicles(initialContext);
            testCase.assertTrue(any(affected));
            [module, initialOutput] = module.apply( ...
                initialContext.ActualPositions, initialContext);

            laterContext = testCase.createContext(scenario, 20, 20);
            [~, laterOutput] = module.apply( ...
                laterContext.ActualPositions, laterContext);

            testCase.verifyEqual( ...
                laterOutput(affected, :), ...
                initialOutput(affected, :), ...
                AbsTol=1e-12);
            testCase.verifyNotEqual( ...
                laterOutput(affected, :), ...
                laterContext.ActualPositions(affected, :));
        end

        function testResetTimerStartsAtRouteDivergence(testCase)
            scenario = testCase.createScenario(0, 40);
            initialRoutes = scenario.VehicleRouteStates;
            vehicleIndex = find(initialRoutes.Route == "Outer", 1);
            testCase.assertNotEmpty(vehicleIndex);
            rowName = initialRoutes.Properties.RowNames{vehicleIndex};
            speed = abs(scenario.VehicleKinematics.vX(vehicleIndex));
            direction = initialRoutes.TravelDirection(vehicleIndex);
            distanceToFork = direction .* ...
                (scenario.Geometry.ForkX - ...
                scenario.VehicleKinematics.X(vehicleIndex));
            timeToDivergence = distanceToFork ./ speed + 0.1;
            module = testCase.createFalseExitInflictor( ...
                1, ResetAfterSeconds=1);

            initialContext = ...
                v2xsim.positioning.ExitRampPositionErrorContext( ...
                    scenario, 0, 0.1, timeToDivergence + 1);
            [module, ~, initialDiagnostics] = module.apply( ...
                initialContext.ActualPositions, initialContext);
            scenario = scenario.step(timeToDivergence);
            divergedContext = ...
                v2xsim.positioning.ExitRampPositionErrorContext( ...
                    scenario, timeToDivergence, 0.1, ...
                    timeToDivergence + 1);
            [~, outputPositions, divergedDiagnostics] = module.apply( ...
                divergedContext.ActualPositions, divergedContext);

            testCase.verifyTrue(ismember( ...
                divergedContext.VehicleRouteStates.Route(rowName), ...
                ["Merge", "Adjacent"]));
            testCase.verifyNotEqual( ...
                outputPositions(rowName, :), ...
                divergedContext.ActualPositions(rowName, :));
            diagnosticRow = ...
                divergedDiagnostics.VehicleId == string(rowName);
            testCase.verifyFalse( ...
                initialDiagnostics.LeftCensoredAtStart( ...
                    diagnosticRow));
            testCase.verifyTrue( ...
                divergedDiagnostics.ActiveSegmentEntered( ...
                    diagnosticRow));
            testCase.verifyFalse( ...
                divergedDiagnostics.LeftCensoredAtStart( ...
                    diagnosticRow));
        end

        function testFractionalProbabilityIsDrawnOncePerVehicle(testCase)
            seed = 700;
            probability = 0.5;
            scenario = testCase.createScenario(0, 40);
            initialContext = testCase.createContext(scenario, 0, 10);
            routes = initialContext.VehicleRouteStates.Route;
            eligible = routes ~= "Regular";
            expectedSelected = false(height(routes), 1);
            expectedStream = RandStream("mt19937ar", Seed=seed);
            eligibleIndices = find(eligible);
            vehicleIds = string( ...
                initialContext.VehicleRouteStates.Properties.RowNames);
            [~, stableOrder] = sort(vehicleIds(eligibleIndices));
            expectedSelected( ...
                eligibleIndices(stableOrder)) = ...
                rand(expectedStream, nnz(eligible), 1) < probability;
            expectedAffected = expectedSelected & ...
                testCase.getAffectedVehicles(initialContext);
            module = testCase.createFalseExitInflictor( ...
                probability, ...
                SelectionRandomStream=RandStream( ...
                    "mt19937ar", Seed=seed));

            [module, initialOutput] = module.apply( ...
                initialContext.ActualPositions, initialContext);
            laterContext = testCase.createContext(scenario, 0.1, 10);
            [~, laterOutput] = module.apply( ...
                laterContext.ActualPositions, laterContext);

            initiallyChanged = ...
                initialOutput.X ~= initialContext.ActualPositions.X | ...
                initialOutput.Y ~= initialContext.ActualPositions.Y;
            laterChanged = ...
                laterOutput.X ~= laterContext.ActualPositions.X | ...
                laterOutput.Y ~= laterContext.ActualPositions.Y;
            testCase.verifyEqual(initiallyChanged, expectedAffected);
            testCase.verifyEqual(laterChanged, expectedAffected);
        end

        function testRejectsProbabilityAboveOne(testCase)
            testCase.verifyError( ...
                @() v2xsim.positioning. ...
                    FalseExitPositionErrorStatusEffect(1.1), ...
                "v2xsim:positioning:" + ...
                "InvalidAffectedVehicleProbability");
        end

        function testDisplacementScaleScalesRouteError(testCase)
            scenario = testCase.createScenario(0, 40);
            context = testCase.createContext(scenario, 0, 10);
            fullModule = testCase.createFalseExitInflictor(1);
            scaledModule = testCase.createFalseExitInflictor( ...
                    1, DisplacementScale=0.25);

            [~, fullPositions] = fullModule.apply( ...
                context.ActualPositions, context);
            [~, scaledPositions] = scaledModule.apply( ...
                context.ActualPositions, context);

            testCase.verifyEqual( ...
                [scaledPositions.X, scaledPositions.Y] - ...
                    context.ActualPositions{:, ["X", "Y"]}, ...
                0.25 .* ( ...
                    [fullPositions.X, fullPositions.Y] - ...
                    context.ActualPositions{:, ["X", "Y"]}), ...
                AbsTol=1e-12);
        end

        function testLifecycleReportsSelectionActivationAndReset( ...
                testCase)
            scenario = testCase.createScenario(0, 40);
            module = testCase.createFalseExitInflictor( ...
                1, ResetAfterSeconds=1);
            initialContext = testCase.createContext(scenario, 0, 10);
            affected = testCase.getAffectedVehicles(initialContext);

            [module, ~, initialDiagnostics] = module.apply( ...
                initialContext.ActualPositions, initialContext);
            resetContext = testCase.createContext(scenario, 1, 10);
            [~, ~, resetDiagnostics] = module.apply( ...
                resetContext.ActualPositions, resetContext);

            testCase.verifyTrue(all( ...
                initialDiagnostics.IsEvaluated( ...
                    initialContext.VehicleRouteStates.Route ~= ...
                    "Regular")));
            testCase.verifyTrue(all( ...
                initialDiagnostics.SelectionOccurred( ...
                    initialContext.VehicleRouteStates.Route ~= ...
                    "Regular")));
            testCase.verifyTrue(all( ...
                initialDiagnostics.ActiveSegmentEntered(affected)));
            testCase.verifyTrue(all( ...
                initialDiagnostics.LeftCensoredAtStart(affected)));
            testCase.verifyEqual( ...
                initialDiagnostics.TrueRoute, ...
                initialContext.VehicleRouteStates.Route);
            testCase.verifyEqual( ...
                unique(initialDiagnostics.StatusEffectType), ...
                "v2xsim.positioning." + ...
                "FalseExitPositionErrorStatusEffect");
            testCase.verifyTrue(all( ...
                resetDiagnostics.ResetOccurred(affected)));
            testCase.verifyTrue(all( ...
                resetDiagnostics.ActiveSegmentExited(affected)));
            testCase.verifyFalse(any( ...
                resetDiagnostics.IsSelected(affected)));
            testCase.verifyFalse(any( ...
                resetDiagnostics.IsActive(affected)));
        end

        function testGaussianCanShareFalseExitSelectionCohort(testCase)
            seed = 812;
            probability = 0.35;
            scenario = testCase.createScenario(0, 40);
            context = testCase.createContext(scenario, 0, 10);
            falseExit = testCase.createFalseExitInflictor( ...
                probability, SelectionRandomSeed=seed);
            gaussianEffect = v2xsim.positioning. ...
                IsotropicGaussianPositionErrorStatusEffect( ...
                    1, ...
                    AffectedVehicleProbability=probability, ...
                    SelectionRandomSeed=seed, ...
                    ActiveRoutes=["Merge", "Adjacent"]);
            gaussian = v2xsim.positioning. ...
                PositionErrorStatusEffectInflictor(gaussianEffect);

            [~, ~, falseExitDiagnostics] = falseExit.apply( ...
                context.ActualPositions, context);
            [~, ~, gaussianDiagnostics] = gaussian.apply( ...
                context.ActualPositions, context);

            testCase.verifyEqual( ...
                gaussianDiagnostics.IsSelected, ...
                falseExitDiagnostics.IsSelected);
            testCase.verifyEqual( ...
                gaussianDiagnostics.IsActive, ...
                falseExitDiagnostics.IsActive);
        end

        function testSelectionRandomnessDoesNotAdvanceGlobalStream( ...
                testCase)
            originalState = rng;
            testCase.addTeardown(@() rng(originalState));
            rng(44);
            expectedState = rng;
            scenario = testCase.createScenario(0, 40);
            context = testCase.createContext(scenario, 0, 10);
            module = testCase.createFalseExitInflictor( ...
                0.5, SelectionRandomSeed=99);

            module.apply(context.ActualPositions, context);

            testCase.verifyEqual(rng, expectedState);
        end
    end

    methods (Access = private)
        function module = createFalseExitInflictor( ...
                ~, affectedVehicleProbability, varargin)
            effect = v2xsim.positioning. ...
                FalseExitPositionErrorStatusEffect( ...
                    affectedVehicleProbability, varargin{:});
            module = v2xsim.positioning. ...
                PositionErrorStatusEffectInflictor(effect);
        end

        function scenario = createScenario(~, exitProbability, mergeDistance)
            scenario = ...
                v2xsim.vehicle.scenarios.ExitRampHighwayScenario( ...
                    500, ...
                    RandomSeed=500, ...
                    RoadLength=200, ...
                    MeanVehicleSpeed=20, ...
                    VehicleSpeedStandardDeviation=0, ...
                    RerollSpeedOnWrapAround=false, ...
                    ExitProbability=exitProbability, ...
                    MergeDistance=mergeDistance);
        end

        function context = createContext( ...
                ~, scenario, simulationTimeSeconds, durationSeconds)
            context = ...
                v2xsim.positioning.ExitRampPositionErrorContext( ...
                    scenario, simulationTimeSeconds, 0.1, ...
                    durationSeconds);
        end

        function affected = getAffectedVehicles(~, context)
            route = context.VehicleRouteStates.Route;
            affected = route == "Merge" | route == "Adjacent";
        end

        function positions = getRampPositions( ...
                ~, context, affected)
            geometry = context.Geometry;
            actualPositions = context.ActualPositions(affected, :);
            direction = ...
                context.VehicleRouteStates.TravelDirection(affected);
            distancePastFork = direction .* ...
                (actualPositions.X - geometry.ForkX);
            progress = distancePastFork ./ ...
                (geometry.RoadLength ./ 2);
            positions = context.LaneNetwork.evaluate( ...
                geometry.getRampLaneId(direction), progress);
        end
    end
end
