classdef IsotropicGaussianPositionErrorStatusEffectTest < ...
        matlab.unittest.TestCase
    %ISOTROPICGAUSSIANPOSITIONERRORSTATUSEFFECTTEST Gaussian displacement.

    methods (Test)
        function testMatchesRadialGaussianFormula(testCase)
            seed = 42;
            meanMagnitudeMeters = 4;
            standardDeviationMeters = 3;
            positions = testCase.createPositions();
            module = testCase.createInflictor( ...
                    standardDeviationMeters, ...
                    MeanMagnitudeMeters=meanMagnitudeMeters, ...
                    DisplacementRandomStream=RandStream( ...
                        "mt19937ar", Seed=seed));
            expectedStream = RandStream("mt19937ar", Seed=seed);
            radialDisplacement = meanMagnitudeMeters + ...
                standardDeviationMeters .* randn( ...
                    expectedStream, height(positions), 1);
            directionRadians = 2 .* pi .* rand( ...
                expectedStream, height(positions), 1);
            displacement = radialDisplacement .* ...
                [cos(directionRadians), sin(directionRadians)];

            [~, actualPositions] = module.apply( ...
                positions, testCase.createContext(positions, 0));

            expectedPositions = positions;
            expectedPositions.X = expectedPositions.X + ...
                displacement(:, 1);
            expectedPositions.Y = expectedPositions.Y + ...
                displacement(:, 2);
            testCase.verifyEqual( ...
                actualPositions, expectedPositions, AbsTol=1e-12);
        end

        function testMeanMagnitudeWithZeroDeviationHasRandomDirection( ...
                testCase)
            meanMagnitudeMeters = 5;
            positions = testCase.createPositions();
            module = testCase.createInflictor( ...
                0, MeanMagnitudeMeters=meanMagnitudeMeters, ...
                DisplacementRandomSeed=73);

            [~, actualPositions] = module.apply( ...
                positions, testCase.createContext(positions, 0));

            displacementMagnitude = hypot( ...
                actualPositions.X - positions.X, ...
                actualPositions.Y - positions.Y);
            testCase.verifyEqual( ...
                displacementMagnitude, ...
                repmat(meanMagnitudeMeters, height(positions), 1), ...
                AbsTol=1e-12);
            testCase.verifyNotEqual( ...
                actualPositions.X - positions.X, ...
                actualPositions.Y - positions.Y);
        end

        function testSuccessiveApplicationsDrawNewErrors(testCase)
            positions = testCase.createPositions();
            module = testCase.createInflictor( ...
                    1, ...
                    DisplacementRandomStream=RandStream( ...
                        "mt19937ar", Seed=100));

            [module, firstPositions] = module.apply( ...
                positions, testCase.createContext(positions, 0));
            [~, secondPositions] = module.apply( ...
                positions, testCase.createContext(positions, 0.1));

            testCase.verifyNotEqual(firstPositions, secondPositions);
        end

        function testCopiedChainsOwnIndependentDisplacementStreams( ...
                testCase)
            positions = testCase.createPositions();
            module = testCase.createInflictor( ...
                1, DisplacementRandomSeed=42);
            original = v2xsim.positioning.PositionErrorChain({module});
            firstCopy = original;
            secondCopy = original;

            [firstCopy, firstPositions] = firstCopy.apply( ...
                positions, testCase.createContext(positions, 0));
            [secondCopy, secondPositions] = secondCopy.apply( ...
                positions, testCase.createContext(positions, 0));
            [~, firstNextPositions] = firstCopy.apply( ...
                positions, testCase.createContext(positions, 0.1));
            [~, secondNextPositions] = secondCopy.apply( ...
                positions, testCase.createContext(positions, 0.1));

            testCase.verifyEqual(firstPositions, secondPositions);
            testCase.verifyEqual( ...
                firstNextPositions, secondNextPositions);
        end

        function testDisplacementIsInvariantToInputRowOrder(testCase)
            positions = testCase.createPositions();
            reorderedPositions = flipud(positions);
            firstModule = testCase.createInflictor( ...
                1, DisplacementRandomSeed=87);
            secondModule = testCase.createInflictor( ...
                1, DisplacementRandomSeed=87);

            [~, firstOutput] = firstModule.apply( ...
                positions, testCase.createContext(positions, 0));
            [~, secondOutput] = secondModule.apply( ...
                reorderedPositions, ...
                testCase.createContext(positions, 0));

            testCase.verifyEqual( ...
                firstOutput, ...
                secondOutput(firstOutput.Properties.RowNames, :));
        end

        function testUpstreamRowReorderingDoesNotChangeGaussianById( ...
                testCase)
            positions = testCase.createPositions();
            identity = ...
                v2xsimtest.positioning.fixture.PositionErrorModuleStub( ...
                    @(value, ~) value);
            reorder = ...
                v2xsimtest.positioning.fixture.PositionErrorModuleStub( ...
                    @(value, ~) flipud(value));
            firstGaussian = testCase.createInflictor( ...
                1, DisplacementRandomSeed=109);
            secondGaussian = testCase.createInflictor( ...
                1, DisplacementRandomSeed=109);
            firstChain = v2xsim.positioning.PositionErrorChain( ...
                {identity, firstGaussian});
            secondChain = v2xsim.positioning.PositionErrorChain( ...
                {reorder, secondGaussian});
            context = testCase.createContext(positions, 0);

            [~, firstOutput] = firstChain.apply(positions, context);
            [~, secondOutput] = secondChain.apply(positions, context);

            testCase.verifyEqual( ...
                firstOutput, ...
                secondOutput(firstOutput.Properties.RowNames, :));
        end

        function testZeroDeviationIsIdentity(testCase)
            positions = testCase.createPositions();
            module = testCase.createInflictor(0);

            [~, actualPositions] = module.apply( ...
                positions, testCase.createContext(positions, 0));

            testCase.verifyEqual(actualPositions, positions);
        end

        function testDoesNotAdvanceGlobalOrSuppliedStream(testCase)
            originalGlobalState = rng;
            testCase.addTeardown(@() rng(originalGlobalState));
            rng(91);
            expectedGlobalState = rng;
            suppliedStream = RandStream("mt19937ar", Seed=55);
            expectedSuppliedState = suppliedStream.State;
            positions = testCase.createPositions();
            module = testCase.createInflictor( ...
                1, DisplacementRandomStream=suppliedStream);

            module.apply( ...
                positions, testCase.createContext(positions, 0));

            testCase.verifyEqual(rng, expectedGlobalState);
            testCase.verifyEqual( ...
                suppliedStream.State, expectedSuppliedState);
        end

        function testReturnsPerVehicleDiagnostics(testCase)
            positions = testCase.createPositions();
            module = testCase.createInflictor( ...
                1, DisplacementRandomSeed=5);

            [~, outputPositions, diagnostics] = module.apply( ...
                positions, testCase.createContext(positions, 0));

            testCase.verifyEqual( ...
                diagnostics.VehicleId, ["vehicle-1"; "vehicle-2"]);
            testCase.verifyEqual(diagnostics.IsSelected, true(2, 1));
            testCase.verifyEqual(diagnostics.IsActive, true(2, 1));
            testCase.verifyEqual( ...
                diagnostics.LeftCensoredAtStart, true(2, 1));
            testCase.verifyEqual( ...
                diagnostics.DisplacementXMeters, ...
                outputPositions.X - positions.X, AbsTol=1e-12);
            testCase.verifyEqual( ...
                diagnostics.DisplacementMagnitudeMeters, ...
                hypot( ...
                    outputPositions.X - positions.X, ...
                    outputPositions.Y - positions.Y), ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                diagnostics.LifecycleEvent, ...
                repmat( ...
                    "Selected|ActiveSegmentEntered", 2, 1));
            testCase.verifyEqual( ...
                unique(diagnostics.StatusEffectType), ...
                "v2xsim.positioning." + ...
                "IsotropicGaussianPositionErrorStatusEffect");
        end

        function testFiniteResetExpiresSelection(testCase)
            positions = testCase.createPositions();
            module = testCase.createInflictor( ...
                1, ResetAfterSeconds=1);

            [module, initial] = module.apply( ...
                positions, testCase.createContext(positions, 0));
            [~, afterReset, diagnostics] = module.apply( ...
                positions, testCase.createContext(positions, 1));

            testCase.verifyNotEqual(initial, positions);
            testCase.verifyEqual(afterReset, positions);
            testCase.verifyTrue(all(diagnostics.ResetOccurred));
            testCase.verifyFalse(any(diagnostics.IsSelected));
        end

        function testDrawsFullMatrixWhenNoTargetsAreActive(testCase)
            seed = 905;
            positions = testCase.createPositions();
            context = testCase.createContext(positions, 0);
            effect = v2xsim.positioning. ...
                IsotropicGaussianPositionErrorStatusEffect( ...
                    1, DisplacementRandomSeed=seed);
            expectedStream = RandStream("mt19937ar", Seed=seed);
            randn(expectedStream, height(positions), 1);
            rand(expectedStream, height(positions), 1);
            expectedRadialDisplacement = randn( ...
                expectedStream, height(positions), 1);
            expectedDirectionRadians = 2 .* pi .* rand( ...
                expectedStream, height(positions), 1);
            expectedDisplacement = expectedRadialDisplacement .* ...
                [cos(expectedDirectionRadians), ...
                sin(expectedDirectionRadians)];

            [effect, inactiveOutput] = effect.applyToPositions( ...
                positions, context, false(2, 1));
            [~, activeOutput] = effect.applyToPositions( ...
                positions, context, true(2, 1));

            testCase.verifyEqual(inactiveOutput, positions);
            testCase.verifyEqual( ...
                activeOutput{:, ["X", "Y"]}, ...
                positions{:, ["X", "Y"]} + expectedDisplacement, ...
                AbsTol=1e-12);
        end
    end

    methods (Access = private)
        function module = createInflictor( ...
                ~, standardDeviationMeters, varargin)
            effect = v2xsim.positioning. ...
                IsotropicGaussianPositionErrorStatusEffect( ...
                    standardDeviationMeters, varargin{:});
            module = v2xsim.positioning. ...
                PositionErrorStatusEffectInflictor(effect);
        end

        function positions = createPositions(~)
            positions = table( ...
                [10; 20], [30; 40], ...
                VariableNames=["X", "Y"], ...
                RowNames=["vehicle-1", "vehicle-2"]);
        end

        function context = createContext( ...
                ~, actualPositions, simulationTimeSeconds)
            context = v2xsim.positioning.PositionErrorContext( ...
                actualPositions, simulationTimeSeconds, 0.1, 10);
        end
    end
end
