classdef PositionErrorStatusEffectInflictorTest < ...
        matlab.unittest.TestCase
    %POSITIONERRORSTATUSEFFECTINFLICTORTEST Tests effect composition.

    methods (Test)
        function testSeparatesEffectModuleAndChainTypes(testCase)
            effect = v2xsim.positioning. ...
                IsotropicGaussianPositionErrorStatusEffect(0);
            module = v2xsim.positioning. ...
                PositionErrorStatusEffectInflictor(effect);
            chain = v2xsim.positioning.PositionErrorChain({module});

            testCase.verifyTrue( ...
                isa(effect, "v2xsim.status.StatusEffect"));
            testCase.verifyTrue(isa( ...
                effect, ...
                "v2xsim.positioning.PositionErrorStatusEffect"));
            testCase.verifyFalse( ...
                isa(effect, "v2xsim.positioning.PositionErrorModule"));
            testCase.verifyTrue( ...
                isa(module, "v2xsim.positioning.PositionErrorModule"));
            testCase.verifyEqual(module.Effect, effect);
            testCase.verifyFalse( ...
                isa(chain, "v2xsim.positioning.PositionErrorModule"));
        end

        function testAppliesEffectAndIdentifiesItInDiagnostics(testCase)
            positions = testCase.createPositions();
            effect = v2xsim.positioning. ...
                IsotropicGaussianPositionErrorStatusEffect( ...
                    1, DisplacementRandomSeed=5);
            module = v2xsim.positioning. ...
                PositionErrorStatusEffectInflictor(effect);

            [module, outputPositions, diagnostics] = module.apply( ...
                positions, testCase.createContext(positions));

            testCase.verifyNotEqual(outputPositions, positions);
            testCase.verifyTrue(all(diagnostics.IsActive));
            testCase.verifyEqual( ...
                unique(diagnostics.ModuleType), ...
                "v2xsim.positioning." + ...
                "PositionErrorStatusEffectInflictor");
            testCase.verifyEqual( ...
                unique(diagnostics.StatusEffectType), ...
                "v2xsim.positioning." + ...
                "IsotropicGaussianPositionErrorStatusEffect");
            testCase.verifyTrue(isa( ...
                module.Effect, ...
                "v2xsim.positioning." + ...
                "IsotropicGaussianPositionErrorStatusEffect"));
        end

        function testNonEffectModuleHasEmptyStatusEffectType(testCase)
            positions = testCase.createPositions();
            module = v2xsim.positioning.PositionDelayError(0);

            [~, ~, diagnostics] = module.apply( ...
                positions, testCase.createContext(positions));

            testCase.verifyEqual( ...
                diagnostics.StatusEffectType, strings(2, 1));
        end

        function testRejectsInvalidEffectClassificationMasks(testCase)
            positions = testCase.createPositions();
            effect = v2xsimtest.positioning.fixture. ...
                InvalidMaskPositionErrorStatusEffect();
            module = v2xsim.positioning. ...
                PositionErrorStatusEffectInflictor(effect);

            testCase.verifyError( ...
                @() module.apply( ...
                    positions, testCase.createContext(positions)), ...
                "v2xsim:status:TargetMaskSizeMismatch");
        end
    end

    methods (Access = private)
        function positions = createPositions(~)
            positions = table( ...
                [10; 20], [30; 40], ...
                VariableNames=["X", "Y"], ...
                RowNames=["vehicle-1", "vehicle-2"]);
        end

        function context = createContext(~, positions)
            context = v2xsim.positioning.PositionErrorContext( ...
                positions, 0, 0.1, 10);
        end
    end
end
