classdef PositionDelayErrorTest < matlab.unittest.TestCase
    %POSITIONDELAYERRORTEST Tests timestamped apparent-position history.

    methods (Test)
        function testReturnsPositionsFromConfiguredDelay(testCase)
            module = v2xsim.positioning.PositionDelayError(1);
            sampleTimes = [0, 0.5, 1, 1.5];
            apparentX = [0, 5, 10, 15];
            expectedX = [0, 0, 0, 5];
            expectedSourceTimes = [0, 0, 0, 0.5];
            expectedAges = [0, 0.5, 1, 1];
            expectedOutcomes = [ ...
                "WarmupHeld", "WarmupHeld", "Delayed", "Delayed"];

            for sampleIndex = 1:numel(sampleTimes)
                positions = testCase.createPositions( ...
                    apparentX(sampleIndex));
                context = testCase.createContext( ...
                    positions, sampleTimes(sampleIndex));

                [module, delayedPositions, diagnostics] = module.apply( ...
                    positions, context);

                testCase.verifyEqual( ...
                    delayedPositions.X, expectedX(sampleIndex));
                testCase.verifyEqual( ...
                    diagnostics.OutputSourceTimeSeconds, ...
                    expectedSourceTimes(sampleIndex));
                testCase.verifyEqual( ...
                    diagnostics.OutputAgeSeconds, ...
                    expectedAges(sampleIndex));
                testCase.verifyEqual( ...
                    diagnostics.NetworkUpdateOutcome, ...
                    expectedOutcomes(sampleIndex));
            end
        end

        function testUsesSampleAndHoldForUnalignedDelay(testCase)
            module = v2xsim.positioning.PositionDelayError(0.75);
            sampleTimes = [0, 0.5, 1];
            apparentX = [0, 5, 10];

            for sampleIndex = 1:numel(sampleTimes)
                positions = testCase.createPositions( ...
                    apparentX(sampleIndex));
                context = testCase.createContext( ...
                    positions, sampleTimes(sampleIndex));
                [module, delayedPositions] = module.apply( ...
                    positions, context);
            end

            testCase.verifyEqual(delayedPositions.X, 0);
        end

        function testZeroDelayIsIdentity(testCase)
            positions = testCase.createPositions(10);
            module = v2xsim.positioning.PositionDelayError(0);

            [~, delayedPositions, diagnostics] = module.apply( ...
                positions, testCase.createContext(positions, 1));

            testCase.verifyEqual(delayedPositions, positions);
            testCase.verifyEqual( ...
                diagnostics.NetworkUpdateOutcome, "Delayed");
            testCase.verifyEqual( ...
                diagnostics.OutputSourceTimeSeconds, 1);
            testCase.verifyEqual(diagnostics.OutputAgeSeconds, 0);
        end

        function testDelaysOutputOfPrecedingModule(testCase)
            addHundred = ...
                v2xsimtest.positioning.fixture.PositionErrorModuleStub( ...
                    @(positions, ~) ...
                    testCase.addToX(positions, 100));
            delay = v2xsim.positioning.PositionDelayError(0.5);
            chain = v2xsim.positioning.PositionErrorChain( ...
                {addHundred, delay});
            initialPositions = testCase.createPositions(0);
            laterPositions = testCase.createPositions(5);

            chain = chain.apply( ...
                initialPositions, ...
                testCase.createContext(initialPositions, 0));
            [~, delayedPositions, diagnostics] = chain.apply( ...
                laterPositions, ...
                testCase.createContext(laterPositions, 0.5));

            testCase.verifyEqual(delayedPositions.X, 100);
            firstModule = diagnostics.ModuleIndex == 1;
            delayModule = diagnostics.ModuleIndex == 2;
            testCase.verifyEqual( ...
                diagnostics.NetworkUpdateOutcome(firstModule), "");
            testCase.verifyTrue(all(isnan( ...
                diagnostics.OutputSourceTimeSeconds(firstModule))));
            testCase.verifyEqual( ...
                diagnostics.NetworkUpdateOutcome(delayModule), ...
                "Delayed");
            testCase.verifyEqual( ...
                diagnostics.OutputSourceTimeSeconds(delayModule), 0);
            testCase.verifyEqual( ...
                diagnostics.OutputAgeSeconds(delayModule), 0.5);
        end

        function testNewVehicleUsesCurrentPositionUntilHistoryExists( ...
                testCase)
            module = v2xsim.positioning.PositionDelayError(1);
            initialPositions = testCase.createPositions(0);
            module = module.apply( ...
                initialPositions, ...
                testCase.createContext(initialPositions, 0));
            currentPositions = table( ...
                [5; 25], [0; 0], ...
                VariableNames=["X", "Y"], ...
                RowNames=["vehicle-1", "vehicle-2"]);

            [~, delayedPositions, diagnostics] = module.apply( ...
                currentPositions, ...
                testCase.createContext(currentPositions, 0.5));

            testCase.verifyEqual(delayedPositions.X, [0; 25]);
            testCase.verifyEqual( ...
                diagnostics.NetworkUpdateOutcome, ...
                ["WarmupHeld"; "CurrentFallback"]);
            testCase.verifyEqual( ...
                diagnostics.OutputSourceTimeSeconds, [0; 0.5]);
            testCase.verifyEqual( ...
                diagnostics.OutputAgeSeconds, [0.5; 0]);
        end

        function testRejectsDecreasingSimulationTime(testCase)
            module = v2xsim.positioning.PositionDelayError(1);
            positions = testCase.createPositions(0);
            module = module.apply( ...
                positions, testCase.createContext(positions, 1));

            testCase.verifyError( ...
                @() module.apply( ...
                    positions, testCase.createContext(positions, 0.5)), ...
                "v2xsim:positioning:PositionDelayTimeReversed");
        end
    end

    methods (Access = private)
        function positions = createPositions(~, x)
            positions = table( ...
                x, 0, ...
                VariableNames=["X", "Y"], ...
                RowNames="vehicle-1");
        end

        function context = createContext( ...
                ~, actualPositions, simulationTimeSeconds)
            context = v2xsim.positioning.PositionErrorContext( ...
                actualPositions, simulationTimeSeconds, 0.5, 10);
        end

        function positions = addToX(~, positions, offset)
            positions.X = positions.X + offset;
        end
    end
end
