classdef PositionErrorDiagnosticsTest < matlab.unittest.TestCase
    %POSITIONERRORDIAGNOSTICSTEST Tests normalized network metadata.

    methods (Test)
        function testAcceptsCompleteNetworkUpdateMetadata(testCase)
            diagnostics = testCase.createNetworkDiagnostics();

            testCase.verifyWarningFree(@() ...
                v2xsim.positioning.diagnostics. ...
                mustBePositionErrorDiagnosticsTable(diagnostics));
            testCase.verifyEqual( ...
                string(diagnostics.Properties.VariableNames(end - 2:end)), ...
                ["NetworkUpdateOutcome", ...
                    "OutputSourceTimeSeconds", "OutputAgeSeconds"]);
        end

        function testRejectsIncompleteNetworkUpdateMetadata(testCase)
            diagnostics = testCase.createNetworkDiagnostics();
            diagnostics.OutputAgeSeconds(1) = NaN;

            testCase.verifyError(@() ...
                v2xsim.positioning.diagnostics. ...
                mustBePositionErrorDiagnosticsTable(diagnostics), ...
                "v2xsim:positioning:diagnostics:" + ...
                "IncompleteNetworkUpdateDiagnostics");
        end

        function testRejectsFutureOutputSourceTime(testCase)
            diagnostics = testCase.createNetworkDiagnostics();
            diagnostics.OutputSourceTimeSeconds(1) = 1.1;
            diagnostics.OutputAgeSeconds(1) = 0;

            testCase.verifyError(@() ...
                v2xsim.positioning.diagnostics. ...
                mustBePositionErrorDiagnosticsTable(diagnostics), ...
                "v2xsim:positioning:diagnostics:" + ...
                "InvalidOutputSourceTime");
        end

        function testRejectsInconsistentOutputAge(testCase)
            diagnostics = testCase.createNetworkDiagnostics();
            diagnostics.OutputAgeSeconds(1) = 0.5;

            testCase.verifyError(@() ...
                v2xsim.positioning.diagnostics. ...
                mustBePositionErrorDiagnosticsTable(diagnostics), ...
                "v2xsim:positioning:diagnostics:InconsistentOutputAge");
        end

        function testRejectsBlankNetworkUpdateOutcome(testCase)
            diagnostics = testCase.createNetworkDiagnostics();
            diagnostics.NetworkUpdateOutcome(1) = " ";

            testCase.verifyError(@() ...
                v2xsim.positioning.diagnostics. ...
                mustBePositionErrorDiagnosticsTable(diagnostics), ...
                "v2xsim:positioning:diagnostics:" + ...
                "InvalidNetworkUpdateOutcome");
        end
    end

    methods (Access = private)
        function diagnostics = createNetworkDiagnostics(~)
            positions = table( ...
                [1; 2], [3; 4], ...
                VariableNames=["X", "Y"], ...
                RowNames=["vehicle-1", "vehicle-2"]);
            diagnostics = ...
                v2xsim.positioning.diagnostics.createRows( ...
                    positions, positions, 1, ...
                    "v2xsim.positioning.TestNetworkModule");
            diagnostics.NetworkUpdateOutcome = ...
                ["Delayed"; "CurrentFallback"];
            diagnostics.OutputSourceTimeSeconds = [0.25; 1];
            diagnostics.OutputAgeSeconds = [0.75; 0];
        end
    end
end
