classdef PositionErrorChainExtensionTest < matlab.unittest.TestCase
    %POSITIONERRORCHAINEXTENSIONTEST Public extension and composition API.

    methods (Test)
        function composesConfiguredAndCustomModulesInExplicitOrder( ...
                testCase)
            gaussian = testCase.stub(@(positions, ~) ...
                testCase.addToX(positions, 1));
            delay = testCase.stub(@(positions, ~) ...
                testCase.multiplyX(positions, 2));
            custom = v2xsimtest.positioning.fixture. ...
                FixedOffsetPositionErrorModule(10);
            descriptor = struct( ...
                Name="Fixed offset", Version="1.0", ...
                Parameters=struct(OffsetMeters=10));
            specification = ...
                v2xsim.positioning.PositionErrorChainSpecification([ ...
                    v2xsim.positioning. ...
                        PositionErrorChainEntry.configured("Gaussian"), ...
                    v2xsim.positioning. ...
                        PositionErrorChainEntry.custom( ...
                            custom, descriptor), ...
                    v2xsim.positioning. ...
                        PositionErrorChainEntry.configured("Delay")]);
            simParams = testCase.compose( ...
                ["Gaussian", "Delay"], {gaussian, delay}, ...
                specification);
            positions = testCase.positions();
            context = testCase.context(positions, 0);

            [chain, output, diagnostics] = ...
                simParams.positionErrorChain.apply(positions, context);
            chain = chain.apply(positions, testCase.context(positions, 1));

            testCase.verifyEqual(output.X, ([1; 2] + 1 + 10) .* 2);
            testCase.verifyEqual( ...
                diagnostics.ModuleIndex, [1; 1; 2; 2; 3; 3]);
            testCase.verifyEqual( ...
                chain.Modules{2}.ApplicationCount, 2);
            testCase.verifyEqual( ...
                simParams.positionErrorChainComposition{2}.Descriptor, ...
                descriptor);
            testCase.verifyEqual( ...
                simParams.positionErrorChainComposition{2}.Class, ...
                "v2xsimtest.positioning.fixture." + ...
                "FixedOffsetPositionErrorModule");
        end

        function rejectsUnknownConfiguredReference(testCase)
            specification = testCase.specification( ...
                v2xsim.positioning. ...
                    PositionErrorChainEntry.configured("Unknown"));

            testCase.verifyError( ...
                @() testCase.compose( ...
                    "Gaussian", {testCase.stub(@(value, ~) value)}, ...
                    specification), ...
                "v2xsim:positioning:" + ...
                "UnknownConfiguredPositionErrorType");
        end

        function rejectsDuplicateConfiguredReference(testCase)
            configured = v2xsim.positioning. ...
                PositionErrorChainEntry.configured("Gaussian");
            specification = testCase.specification( ...
                [configured, configured]);

            testCase.verifyError( ...
                @() testCase.compose( ...
                    "Gaussian", {testCase.stub(@(value, ~) value)}, ...
                    specification), ...
                "v2xsim:positioning:" + ...
                "DuplicateConfiguredPositionErrorReference");
        end

        function rejectsOmittedConfiguredReference(testCase)
            custom = v2xsimtest.positioning.fixture. ...
                FixedOffsetPositionErrorModule(1);
            specification = testCase.specification( ...
                v2xsim.positioning. ...
                    PositionErrorChainEntry.custom(custom, struct()));

            testCase.verifyError( ...
                @() testCase.compose( ...
                    "Gaussian", {testCase.stub(@(value, ~) value)}, ...
                    specification), ...
                "v2xsim:positioning:" + ...
                "MissingConfiguredPositionErrorReference");
        end

        function rejectsInvalidCustomModuleAndDescriptor(testCase)
            testCase.verifyError( ...
                @() v2xsim.positioning. ...
                    PositionErrorChainEntry.custom(42, struct()), ...
                "v2xsim:positioning:InvalidCustomPositionErrorModule");
            custom = v2xsimtest.positioning.fixture. ...
                FixedOffsetPositionErrorModule(1);
            testCase.verifyError( ...
                @() v2xsim.positioning. ...
                    PositionErrorChainEntry.custom( ...
                        custom, struct(Value=@sin)), ...
                "v2xsim:positioning:InvalidPositionErrorDescriptor");
            testCase.verifyError( ...
                @() v2xsim.positioning. ...
                    PositionErrorChainEntry.custom( ...
                        custom, struct(Value=NaN)), ...
                "v2xsim:positioning:InvalidPositionErrorDescriptor");
        end

        function supportsExplicitEmptyChainWhenNothingIsConfigured( ...
                testCase)
            specification = ...
                v2xsim.positioning.PositionErrorChainSpecification();

            simParams = testCase.compose( ...
                strings(1, 0), cell(1, 0), specification);

            testCase.verifyEmpty(simParams.positionErrorChain.Modules);
            testCase.verifyEmpty( ...
                simParams.positionErrorChainComposition);
        end
    end

    methods (Access = private)
        function simParams = compose( ...
                ~, configuredTypes, configuredModules, specification)
            configuredTypes = reshape(string(configuredTypes), 1, []);
            errors = cell(1, numel(configuredTypes));
            for errorIndex = 1:numel(configuredTypes)
                errors{errorIndex} = struct( ...
                    Type=configuredTypes(errorIndex));
            end
            positioning = struct(Errors={errors});
            simParams = struct( ...
                positionErrorModuleNames=configuredTypes, ...
                positionErrorChain= ...
                    v2xsim.positioning. ...
                    PositionErrorChain(configuredModules));
            simParams = v2xsim.runtime.internal. ...
                composePositionErrorChain( ...
                    simParams, positioning, specification);
        end

        function specification = specification(~, entries)
            specification = v2xsim.positioning. ...
                PositionErrorChainSpecification(entries);
        end

        function module = stub(~, transform)
            module = v2xsimtest.positioning.fixture. ...
                PositionErrorModuleStub(transform);
        end

        function positions = positions(~)
            positions = table( ...
                [1; 2], [3; 4], ...
                VariableNames=["X", "Y"], ...
                RowNames=["vehicle-1", "vehicle-2"]);
        end

        function context = context(~, positions, simulationTimeSeconds)
            context = v2xsim.positioning.PositionErrorContext( ...
                positions, simulationTimeSeconds, 0.1, 10);
        end

        function positions = addToX(~, positions, offset)
            positions.X = positions.X + offset;
        end

        function positions = multiplyX(~, positions, multiplier)
            positions.X = positions.X .* multiplier;
        end
    end
end
