classdef PositionErrorCalibrationTest < matlab.unittest.TestCase
    %POSITIONERRORCALIBRATIONTEST Tests equal-magnitude calibration.

    methods (Test)
        function testCartesianGaussianAxisSigmaMatchesMean(testCase)
            meanMagnitude = [0, 2, 10];

            sigma = v2xsim.positioning.calibration. ...
                cartesianGaussianAxisStandardDeviation(meanMagnitude);

            testCase.verifyEqual( ...
                sigma, meanMagnitude .* sqrt(2 ./ pi), ...
                AbsTol=1e-14);
        end

        function testFalseRouteFullScaleMean(testCase)
            actual = v2xsim.positioning.calibration. ...
                falseRouteMeanMagnitudeAtFullScale(200, 4, 40);

            testCase.verifyEqual(actual, 53.2, AbsTol=1e-12);
        end

        function testFalseRouteScaleMatchesTarget(testCase)
            target = 13.3;

            scale = v2xsim.positioning.calibration. ...
                falseRouteDisplacementScale( ...
                    target, 200, 4, 40);

            testCase.verifyEqual(scale, 0.25, AbsTol=1e-12);
        end

        function testRejectsMergeLongerThanHalfRoad(testCase)
            testCase.verifyError( ...
                @() v2xsim.positioning.calibration. ...
                    falseRouteMeanMagnitudeAtFullScale( ...
                        200, 4, 101), ...
                "v2xsim:positioning:calibration:" + ...
                "InvalidMergeDistance");
        end

        function testRejectsTargetAboveFullScale(testCase)
            testCase.verifyError( ...
                @() v2xsim.positioning.calibration. ...
                    falseRouteDisplacementScale( ...
                        60, 200, 4, 40), ...
                "v2xsim:positioning:calibration:" + ...
                "TargetExceedsFullScale");
        end

        function testCyclicUpdateGroupsAreOneBased(testCase)
            actual = arrayfun( ...
                @(index) v2xsim.positioning. ...
                    cyclicUpdateGroup(index, 3), ...
                1:8);

            testCase.verifyEqual(actual, [1, 2, 3, 1, 2, 3, 1, 2]);
        end
    end
end
