classdef RoundaboutPositionErrorContextTest < matlab.unittest.TestCase
    %ROUNDABOUTPOSITIONERRORCONTEXTTEST Roundabout false-exit projection.

    methods (Test)
        function testCapturesRoundaboutScenarioSnapshot(testCase)
            scenario = testCase.createScenario();

            context = ...
                v2xsim.positioning.RoundaboutPositionErrorContext( ...
                    scenario, 2.5, 0.1, 10);

            testCase.verifyTrue(isa( ...
                context, ...
                "v2xsim.positioning.RoutePositionErrorContext"));
            testCase.verifyEqual( ...
                context.ActualPositions, ...
                scenario.VehicleKinematics(:, ["X", "Y"]));
            testCase.verifyEqual(context.Geometry, scenario.Geometry);
            testCase.verifyEqual( ...
                context.LaneNetwork, scenario.LaneNetwork);
            testCase.verifyEqual( ...
                context.VehicleLaneStates, scenario.VehicleLaneStates);
            testCase.verifyEqual( ...
                context.VehicleRouteStates, scenario.VehicleRouteStates);
        end

        function testBuildsFalseExitProjectionInRequestedOrder(testCase)
            scenario = testCase.createScenario();
            context = testCase.createContext(scenario, 0);
            allIds = string( ...
                context.ActualPositions.Properties.RowNames);
            requestedIds = flip(allIds(1:min(12, numel(allIds))));
            laneStates = context.VehicleLaneStates( ...
                cellstr(requestedIds), :);
            routeStates = context.VehicleRouteStates( ...
                cellstr(requestedIds), :);
            [expectedApplicable, targetLaneIds, targetProgress] = ...
                context.Geometry.getFalseExitLaneCoordinates( ...
                    laneStates, routeStates);
            expectedTargets = context.ActualPositions( ...
                cellstr(requestedIds), ["X", "Y"]);
            if any(expectedApplicable)
                expectedTargets{expectedApplicable, :} = ...
                    context.LaneNetwork.evaluate( ...
                        targetLaneIds(expectedApplicable), ...
                        targetProgress(expectedApplicable));
            end

            projection = context.getRouteProjection( ...
                "FalseExit", requestedIds);

            testCase.verifyEqual( ...
                string(projection.Properties.RowNames), requestedIds);
            testCase.verifyTrue(all(projection.IsEligible));
            testCase.verifyEqual( ...
                projection.IsApplicable, expectedApplicable);
            testCase.verifyEqual( ...
                projection.TrueRoute, ...
                routeStates.EntryArm + "->" + routeStates.ExitArm);
            testCase.verifyEqual( ...
                [projection.TargetX, projection.TargetY], ...
                expectedTargets{:, ["X", "Y"]}, ...
                AbsTol=1e-12);
        end

        function testFalseMergeIsUnsupported(testCase)
            scenario = testCase.createScenario();
            context = testCase.createContext(scenario, 0);
            effect = v2xsim.positioning. ...
                FalseMergePositionErrorStatusEffect(1);
            module = v2xsim.positioning. ...
                PositionErrorStatusEffectInflictor(effect);

            testCase.verifyError( ...
                @() module.apply( ...
                    context.ActualPositions, context), ...
                "v2xsim:positioning:UnsupportedErrorContext");
        end

        function testFalseExitUsesApplicableRoundaboutProjection(testCase)
            scenario = testCase.createScenario();
            simulationTime = 0;
            context = testCase.createContext(scenario, simulationTime);
            projection = context.getRouteProjection( ...
                "FalseExit", string( ...
                    context.ActualPositions.Properties.RowNames));
            while ~any(projection.IsApplicable) && simulationTime < 20
                scenario = scenario.step(0.1);
                simulationTime = simulationTime + 0.1;
                context = testCase.createContext( ...
                    scenario, simulationTime);
                projection = context.getRouteProjection( ...
                    "FalseExit", string( ...
                        context.ActualPositions.Properties.RowNames));
            end
            testCase.assertTrue(any(projection.IsApplicable));
            apparentInput = context.ActualPositions;
            apparentInput.X = apparentInput.X + 2;
            apparentInput.Y = apparentInput.Y - 3;
            effect = v2xsim.positioning. ...
                FalseExitPositionErrorStatusEffect(1);
            module = v2xsim.positioning. ...
                PositionErrorStatusEffectInflictor(effect);

            [~, apparentOutput, diagnostics] = module.apply( ...
                apparentInput, context);

            applicable = projection.IsApplicable;
            testCase.verifyEqual( ...
                apparentOutput.X(applicable), ...
                projection.TargetX(applicable) + 2, ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                apparentOutput.Y(applicable), ...
                projection.TargetY(applicable) - 3, ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                apparentOutput(~applicable, :), ...
                apparentInput(~applicable, :));
            testCase.verifyEqual( ...
                diagnostics.TrueRoute, projection.TrueRoute);
        end

        function testSkippedExitWindowAndEqualDistanceContract(testCase)
            geometry = ...
                v2xsim.vehicle.scenario.roundabout.Geometry(100, 4, 60);
            rowNames = ["AfterExit"; "AfterEntry"; "NextJunction"];
            laneIds = [ ...
                geometry.getCirculatingLaneIdAfterExit("East"); ...
                geometry.getCirculatingLaneIdAfterEntry("East"); ...
                geometry.getCirculatingLaneIdAfterEntry("East")];
            progress = [0.25; 0.5; 1];
            laneStates = table( ...
                laneIds, progress, zeros(3, 1), ...
                VariableNames=[ ...
                    "LaneId", "Progress", "LateralOffsetMeters"], ...
                RowNames=cellstr(rowNames));
            routeStates = table( ...
                repmat("North", 3, 1), ...
                repmat("South", 3, 1), ...
                repmat("Circulating", 3, 1), ...
                VariableNames=["EntryArm", "ExitArm", "Stage"], ...
                RowNames=cellstr(rowNames));

            [applicable, targetLaneIds, targetProgress] = ...
                geometry.getFalseExitLaneCoordinates( ...
                    laneStates, routeStates);

            distances = [ ...
                0.25 .* geometry.ExitToEntryArcLength; ...
                geometry.ExitToEntryArcLength + ...
                    0.5 .* geometry.EntryToExitArcLength];
            eastExitLength = geometry.ExitLaneLengths(2);
            testCase.verifyEqual(applicable, [true; true; false]);
            testCase.verifyEqual( ...
                targetLaneIds(1:2), ...
                repmat(geometry.getExitLaneId("East"), 2, 1));
            testCase.verifyEqual( ...
                targetProgress(1:2), ...
                distances ./ eastExitLength, ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                targetLaneIds(3), laneIds(3));
            testCase.verifyEqual(targetProgress(3), progress(3));

            referenceGeometry = geometry;
            shortLength = referenceGeometry.MinimumExitLength;
            shortGeometry = ...
                v2xsim.vehicle.scenario.roundabout.Geometry( ...
                    [100, shortLength, 100, 100], 4, 60);
            shortExitLength = shortGeometry.ExitLaneLengths(2);
            testCase.assertLessThan( ...
                shortExitLength, shortGeometry.ExitToEntryArcLength);
            earlyDistance = 0.25 .* shortExitLength;
            lateDistance = 0.5 .* ( ...
                shortExitLength + shortGeometry.ExitToEntryArcLength);
            shortProgress = [earlyDistance; lateDistance] ./ ...
                shortGeometry.ExitToEntryArcLength;
            shortLaneIds = repmat( ...
                shortGeometry.getCirculatingLaneIdAfterExit("East"), ...
                2, 1);
            shortLaneStates = table( ...
                shortLaneIds, shortProgress, zeros(2, 1), ...
                VariableNames=[ ...
                    "LaneId", "Progress", "LateralOffsetMeters"], ...
                RowNames=["BeforeFalsePathEnd", "AfterFalsePathEnd"]);
            shortRouteStates = table( ...
                repmat("North", 2, 1), ...
                repmat("South", 2, 1), ...
                repmat("Circulating", 2, 1), ...
                VariableNames=["EntryArm", "ExitArm", "Stage"], ...
                RowNames=shortLaneStates.Properties.RowNames);

            [shortApplicable, shortTargetLaneIds, ...
                shortTargetProgress] = ...
                shortGeometry.getFalseExitLaneCoordinates( ...
                    shortLaneStates, shortRouteStates);

            testCase.verifyEqual( ...
                shortApplicable, [true; false]);
            testCase.verifyEqual( ...
                shortTargetLaneIds(1), ...
                shortGeometry.getExitLaneId("East"));
            testCase.verifyEqual( ...
                shortTargetProgress(1), 0.25, AbsTol=1e-12);
            testCase.verifyEqual( ...
                shortTargetLaneIds(2), shortLaneIds(2));
            testCase.verifyEqual( ...
                shortTargetProgress(2), shortProgress(2));
        end
    end

    methods (Static, Access = private)
        function scenario = createScenario()
            scenario = v2xsim.vehicle.scenarios.RoundaboutScenario( ...
                120, ...
                RandomSeed=510, ...
                ExitLengths=[100, 110, 120, 130], ...
                RoadWidth=4, ...
                InnerCircleDiameter=60, ...
                MeanVehicleSpeed=20, ...
                VehicleSpeedStandardDeviation=0, ...
                RerollSpeedOnWrapAround=false);
        end

        function context = createContext(scenario, simulationTime)
            context = ...
                v2xsim.positioning.RoundaboutPositionErrorContext( ...
                    scenario, simulationTime, 0.1, 30);
        end
    end
end
