classdef RoutePositionErrorContextTest < matlab.unittest.TestCase
    %ROUTEPOSITIONERRORCONTEXTTEST Projection-contract validation.

    methods (Test)
        function testAcceptsProjectionInRequestedIdentityOrder(testCase)
            actualPositions = testCase.createActualPositions();
            requestedIds = ["V2"; "V1"];
            projection = testCase.createProjection(requestedIds);
            context = v2xsimtest.positioning.fixture. ...
                RoutePositionErrorContextStub( ...
                    actualPositions, projection);

            actual = context.getRouteProjection( ...
                "FalseExit", requestedIds);

            testCase.verifyEqual(actual, projection);
        end

        function testRejectsProjectionWithWrongIdentityOrder(testCase)
            actualPositions = testCase.createActualPositions();
            projection = testCase.createProjection(["V1"; "V2"]);
            context = v2xsimtest.positioning.fixture. ...
                RoutePositionErrorContextStub( ...
                    actualPositions, projection);

            testCase.verifyError( ...
                @() context.getRouteProjection( ...
                    "FalseExit", ["V2"; "V1"]), ...
                "v2xsim:positioning:InvalidRouteProjection");
        end

        function testRejectsInvalidProjectionValues(testCase)
            actualPositions = testCase.createActualPositions();
            projection = testCase.createProjection(["V1"; "V2"]);
            projection.IsEligible(1) = false;
            projection.IsApplicable(1) = true;
            context = v2xsimtest.positioning.fixture. ...
                RoutePositionErrorContextStub( ...
                    actualPositions, projection);

            testCase.verifyError( ...
                @() context.getRouteProjection( ...
                    "FalseExit", ["V1"; "V2"]), ...
                "v2xsim:positioning:InvalidRouteProjection");
        end

        function testRejectsUnknownAndDuplicateVehicleIds(testCase)
            actualPositions = testCase.createActualPositions();
            projection = testCase.createProjection(["V1"; "V2"]);
            context = v2xsimtest.positioning.fixture. ...
                RoutePositionErrorContextStub( ...
                    actualPositions, projection);

            testCase.verifyError( ...
                @() context.getRouteProjection( ...
                    "FalseExit", ["V1"; "Unknown"]), ...
                "v2xsim:positioning:UnknownRouteProjectionVehicle");
            testCase.verifyError( ...
                @() context.getRouteProjection( ...
                    "FalseExit", ["V1"; "V1"]), ...
                "v2xsim:positioning:InvalidRouteProjectionVehicleIds");
        end

        function testRejectsUnknownRouteErrorType(testCase)
            actualPositions = testCase.createActualPositions();
            projection = testCase.createProjection(["V1"; "V2"]);
            context = v2xsimtest.positioning.fixture. ...
                RoutePositionErrorContextStub( ...
                    actualPositions, projection);

            testCase.verifyError( ...
                @() context.getRouteProjection( ...
                    "FalseTurn", ["V1"; "V2"]), ...
                "v2xsim:positioning:UnknownRouteErrorType");
        end

        function testFalseExitUsesScenarioNeutralProjection(testCase)
            actualPositions = testCase.createActualPositions();
            vehicleIds = ["V1"; "V2"];
            projection = testCase.createProjection(vehicleIds);
            context = v2xsimtest.positioning.fixture. ...
                RoutePositionErrorContextStub( ...
                    actualPositions, projection);
            apparentInput = actualPositions;
            apparentInput.X = apparentInput.X + 2;
            apparentInput.Y = apparentInput.Y - 3;
            effect = v2xsim.positioning. ...
                FalseExitPositionErrorStatusEffect(1);
            module = v2xsim.positioning. ...
                PositionErrorStatusEffectInflictor(effect);

            [~, apparentOutput, diagnostics] = module.apply( ...
                apparentInput, context);

            testCase.verifyEqual( ...
                apparentOutput.X, projection.TargetX + 2);
            testCase.verifyEqual( ...
                apparentOutput.Y, projection.TargetY - 3);
            testCase.verifyEqual( ...
                diagnostics.TrueRoute, projection.TrueRoute);
        end

        function testFalseExitReactivatesAtLaterRouteOpportunity(testCase)
            actualPositions = table( ...
                1, 2, VariableNames=["X", "Y"], RowNames="V1");
            activeProjection = testCase.createProjection("V1");
            inactiveProjection = activeProjection;
            inactiveProjection.IsApplicable(:) = false;
            inactiveProjection.TargetX = actualPositions.X;
            inactiveProjection.TargetY = actualPositions.Y;
            initialContext = v2xsimtest.positioning.fixture. ...
                RoutePositionErrorContextStub( ...
                    actualPositions, activeProjection);
            gapContext = v2xsimtest.positioning.fixture. ...
                RoutePositionErrorContextStub( ...
                    actualPositions, inactiveProjection, ...
                    SimulationTimeSeconds=0.1);
            laterContext = v2xsimtest.positioning.fixture. ...
                RoutePositionErrorContextStub( ...
                    actualPositions, activeProjection, ...
                    SimulationTimeSeconds=0.2);
            effect = v2xsim.positioning. ...
                FalseExitPositionErrorStatusEffect(1);
            module = v2xsim.positioning. ...
                PositionErrorStatusEffectInflictor(effect);

            [module, initialOutput, initialDiagnostics] = ...
                module.apply(actualPositions, initialContext);
            [module, gapOutput, gapDiagnostics] = ...
                module.apply(actualPositions, gapContext);
            [~, laterOutput, laterDiagnostics] = ...
                module.apply(actualPositions, laterContext);

            testCase.verifyNotEqual(initialOutput, actualPositions);
            testCase.verifyEqual(gapOutput, actualPositions);
            testCase.verifyNotEqual(laterOutput, actualPositions);
            testCase.verifyTrue(initialDiagnostics.ActiveSegmentEntered);
            testCase.verifyTrue(gapDiagnostics.ActiveSegmentExited);
            testCase.verifyTrue(laterDiagnostics.ActiveSegmentEntered);
            testCase.verifyEqual(initialDiagnostics.EpisodeId, 1);
            testCase.verifyEqual(laterDiagnostics.EpisodeId, 2);
            testCase.verifyTrue(laterDiagnostics.IsSelected);
        end
    end

    methods (Static, Access = private)
        function actualPositions = createActualPositions()
            actualPositions = table( ...
                [1; 2], [3; 4], ...
                VariableNames=["X", "Y"], ...
                RowNames=["V1", "V2"]);
        end

        function projection = createProjection(vehicleIds)
            vehicleCount = numel(vehicleIds);
            projection = table( ...
                repmat("North->South", vehicleCount, 1), ...
                true(vehicleCount, 1), ...
                true(vehicleCount, 1), ...
                (1:vehicleCount).', ...
                (11:(10 + vehicleCount)).', ...
                VariableNames=[ ...
                    "TrueRoute", "IsEligible", "IsApplicable", ...
                    "TargetX", "TargetY"], ...
                RowNames=cellstr(vehicleIds));
        end
    end
end
