classdef ControllerMetricsTest < matlab.unittest.TestCase
    %CONTROLLERMETRICSTEST Tests topology and allocation comparisons.

    methods (Test)
        function kendallRankAndRangeMetricsAreIdentityStable(testCase)
            ueIds = ["a";"b";"c";"d"];
            truth = [ ...
                0 1 2 3; ...
                1 0 4 5; ...
                2 4 0 6; ...
                3 5 6 0];
            apparent = truth;
            apparent(1,:) = [0 3 1 2];
            apparent(:,1) = apparent(1,:).';

            result = ...
                v2xsim.resource.metrics.compareNeighborTopology( ...
                    ueIds,apparent,truth,TopK=2, ...
                    NeighborRangesMeters=2.5);
            ego = result.Topology(result.Topology.EgoUeId == "a",:);
            range = result.RangeTopology( ...
                result.RangeTopology.EgoUeId == "a",:);
            ranks = result.RankDisplacement( ...
                result.RankDisplacement.EgoUeId == "a",:);

            testCase.verifyEqual( ...
                ego.NormalizedKendallTauDistance,2/3, ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                ego.MeanAbsoluteRankDisplacement,4/3, ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                ego.TopKNeighborJaccard,1/3,AbsTol=1e-12);
            testCase.verifyEqual(range.MissedNeighborCount,1);
            testCase.verifyEqual(range.PhantomNeighborCount,1);
            testCase.verifyEqual( ...
                ranks.SignedRankDisplacement, ...
                [2;-1;-1]);
        end

        function kendallIsMissingWithFewerThanTwoNeighbors(testCase)
            result = ...
                v2xsim.resource.metrics.compareNeighborTopology( ...
                    ["b";"a"],[0 1;1 0],[0 1;1 0]);

            testCase.verifyTrue(all(ismissing( ...
                result.Topology.NormalizedKendallTauDistance)));
        end

        function distanceTiesUseUeIdentity(testCase)
            ueIds = ["ego";"z";"a"];
            tied = [0 1 1;1 0 2;1 2 0];

            result = ...
                v2xsim.resource.metrics.compareNeighborTopology( ...
                    ueIds,tied,tied);

            testCase.verifyEqual( ...
                result.Topology.NormalizedKendallTauDistance, ...
                zeros(3,1));
            egoRanks = result.RankDisplacement( ...
                result.RankDisplacement.EgoUeId == "ego",:);
            testCase.verifyEqual(egoRanks.NeighborUeId,["z";"a"]);
            testCase.verifyEqual(egoRanks.TrueRank,[2;1]);
        end

        function pairGraphComparisonIsResourceLabelInvariant(testCase)
            ueIds = ["a";"b";"c";"d"];
            distance = [ ...
                0 1 4 5;1 0 6 7;4 6 0 2;5 7 2 0];

            result = v2xsim.resource.metrics.compareAllocations( ...
                ueIds,[1;1;2;2],[3;3;4;4],distance,[2 2]);

            testCase.verifyEqual( ...
                result.Summary.ExactDecisionDisagreementRate,1);
            testCase.verifyEqual( ...
                result.Summary.ResourcePairGraphXorCount,0);
            testCase.verifyEqual( ...
                result.Summary.ResourcePairGraphJaccard,1);
            testCase.verifyEqual(result.CoUser.CoUserJaccard,ones(4,1));
            testCase.verifyEqual( ...
                result.Summary. ...
                    LiveMinimumTrueCoResourceDistanceMeters,1);
            testCase.verifyEqual( ...
                result.Summary.TotalUnorderedUePairCount,6);
            testCase.verifyEqual( ...
                result.Summary.HarmfulReuseCandidateCount,0);
            testCase.verifyEqual( ...
                result.Summary.MissedReuseCandidateCount,0);
            testCase.verifyEqual( ...
                result.Summary.HarmfulReuseCandidateRate,0);
            testCase.verifyEqual( ...
                result.Summary.MissedReuseCandidateRate,0);
        end

        function pairGraphComparisonDetectsMeaningfulChange(testCase)
            distance = [0 2 8;2 0 4;8 4 0];

            result = v2xsim.resource.metrics.compareAllocations( ...
                ["a";"b";"c"],[1;1;2],[1;2;2], ...
                distance,[2 1], ...
                PreviousResourceIds=[1;2;2]);

            testCase.verifyEqual( ...
                result.Summary.ResourcePairGraphXorCount,2);
            testCase.verifyEqual( ...
                result.Summary.ResourcePairGraphXorRate,2/3, ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                result.Summary.ResourcePairGraphJaccard,0);
            testCase.verifyEqual( ...
                result.Summary.HarmfulReuseCandidateCount,1);
            testCase.verifyEqual( ...
                result.Summary.MissedReuseCandidateCount,1);
            testCase.verifyEqual( ...
                result.Summary.HarmfulReuseCandidateRate,1/3, ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                result.Summary.MissedReuseCandidateRate,1/3, ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                result.Summary.LiveAssignmentChurnRate,1/3, ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                result.Summary.OracleAssignmentChurnRate,0);
        end

        function reuseCandidateRowsRetainPairResourceEvidence(testCase)
            live = table( ...
                ["c";"a";"b"],[1;1;2], ...
                VariableNames=["UeId","ResourceIds"]);
            oracle = table( ...
                ["b";"c";"a"],[2;1;2], ...
                VariableNames=["UeId","ResourceIds"]);

            rows = ...
                v2xsim.resource.metrics.buildReuseCandidateRows( ...
                    live,oracle,[2 1]);

            testCase.verifyEqual(height(rows),2);
            testCase.verifyTrue(all(ismember( ...
                rows.CandidateType, ...
                ["harmful_reuse","missed_reuse"])));
            harmful = rows(rows.CandidateType == "harmful_reuse",:);
            missed = rows(rows.CandidateType == "missed_reuse",:);
            testCase.verifyEqual( ...
                harmful{:,["FirstUeId","SecondUeId"]}, ...
                ["a","c"]);
            testCase.verifyTrue(harmful.LiveSameResource);
            testCase.verifyFalse(harmful.OracleSameResource);
            testCase.verifyEqual( ...
                harmful.LiveResourceRelation,"cochannel");
            testCase.verifyEqual( ...
                harmful.OracleResourceRelation,"separate_time");
            testCase.verifyTrue( ...
                harmful.IsHarmfulInterferenceOverlap);
            testCase.verifyEqual( ...
                [ ...
                    harmful.LiveFirstResourceId, ...
                    harmful.LiveSecondResourceId], ...
                [1 1]);
            testCase.verifyEqual( ...
                missed{:,["FirstUeId","SecondUeId"]}, ...
                ["a","b"]);
            testCase.verifyFalse(missed.LiveSameResource);
            testCase.verifyTrue(missed.OracleSameResource);
            testCase.verifyTrue( ...
                missed.IsMissedInterferenceOverlap);
            testCase.verifyEqual( ...
                [ ...
                    missed.OracleFirstResourceId, ...
                    missed.OracleSecondResourceId], ...
                [2 2]);
        end

        function separatesExactReuseFromInterferenceOverlap(testCase)
            ueIds = ["a";"b"];
            distance = [0 10;10 0];

            adjacentResolved = ...
                v2xsim.resource.metrics.compareAllocations( ...
                    ueIds,[1;2],[1;4],distance,[2 3]);
            testCase.verifyEqual( ...
                adjacentResolved.Summary. ...
                    HarmfulReuseCandidateCount,0);
            testCase.verifyEqual( ...
                adjacentResolved.Summary. ...
                    HarmfulInterferenceOverlapCandidateCount,1);
            testCase.verifyEqual( ...
                adjacentResolved.Summary. ...
                    HarmfulInterferenceOverlapCandidateRate,1);
            testCase.verifyEqual( ...
                adjacentResolved.Summary. ...
                    InterferenceOverlapPairGraphXorCount,1);
            testCase.verifyEqual( ...
                adjacentResolved.Summary. ...
                    InterferenceOverlapPairGraphJaccard,0);

            live = table( ...
                ueIds,[1;2], ...
                VariableNames=["UeId","ResourceIds"]);
            oracle = table( ...
                ueIds,[1;4], ...
                VariableNames=["UeId","ResourceIds"]);
            rows = ...
                v2xsim.resource.metrics.buildReuseCandidateRows( ...
                    live,oracle,[2 3]);
            testCase.verifyEqual(height(rows),1);
            testCase.verifyEqual( ...
                rows.CandidateType,"unchanged_separation");
            testCase.verifyEqual( ...
                rows.LiveResourceRelation,"adjacent_channel");
            testCase.verifyEqual( ...
                rows.OracleResourceRelation,"separate_time");
            testCase.verifyTrue( ...
                rows.IsHarmfulInterferenceOverlap);
            testCase.verifyFalse( ...
                rows.IsMissedInterferenceOverlap);
        end

        function cochannelToAdjacentIsNotResolvedInterference( ...
                testCase)
            ueIds = ["a";"b"];
            distance = [0 10;10 0];
            comparison = ...
                v2xsim.resource.metrics.compareAllocations( ...
                    ueIds,[1;1],[1;2],distance,[1 3]);

            testCase.verifyEqual( ...
                comparison.Summary.HarmfulReuseCandidateCount,1);
            testCase.verifyEqual( ...
                comparison.Summary. ...
                    HarmfulInterferenceOverlapCandidateCount,0);
            testCase.verifyEqual( ...
                comparison.Summary. ...
                    InterferenceOverlapPairGraphXorCount,0);
            testCase.verifyEqual( ...
                comparison.Summary. ...
                    InterferenceOverlapPairGraphJaccard,1);

            live = table( ...
                ueIds,[1;1], ...
                VariableNames=["UeId","ResourceIds"]);
            oracle = table( ...
                ueIds,[1;2], ...
                VariableNames=["UeId","ResourceIds"]);
            rows = ...
                v2xsim.resource.metrics.buildReuseCandidateRows( ...
                    live,oracle,[1 3]);
            testCase.verifyEqual(height(rows),1);
            testCase.verifyEqual( ...
                rows.CandidateType,"harmful_reuse");
            testCase.verifyEqual( ...
                rows.LiveResourceRelation,"cochannel");
            testCase.verifyEqual( ...
                rows.OracleResourceRelation,"adjacent_channel");
            testCase.verifyFalse( ...
                rows.IsHarmfulInterferenceOverlap);
        end

        function physicalOverlapUsesFrequencyCouplingMatrix( ...
                testCase)
            ueIds = ["a";"b"];
            distance = [0 10;10 0];
            coupling = eye(3);
            coupling(1,3) = 0.01;
            coupling(3,1) = 0.02;

            comparison = ...
                v2xsim.resource.metrics.compareAllocations( ...
                    ueIds,[1;3],[1;4],distance,[2 3], ...
                    FrequencyInterferenceCoupling=coupling);

            testCase.verifyEqual( ...
                comparison.Summary. ...
                    HarmfulInterferenceOverlapCandidateCount,1);
            live = table( ...
                ueIds,[1;3], ...
                VariableNames=["UeId","ResourceIds"]);
            oracle = table( ...
                ueIds,[1;4], ...
                VariableNames=["UeId","ResourceIds"]);
            rows = ...
                v2xsim.resource.metrics.buildReuseCandidateRows( ...
                    live,oracle,[2 3], ...
                    FrequencyInterferenceCoupling=coupling);
            testCase.verifyEqual(height(rows),1);
            testCase.verifyEqual( ...
                rows.LiveResourceRelation,"other_same_time");
            testCase.verifyEqual( ...
                rows.OracleResourceRelation,"separate_time");
            testCase.verifyTrue( ...
                rows.IsHarmfulInterferenceOverlap);
        end

        function zeroAdjacentCouplingOverridesLegacyDefault( ...
                testCase)
            comparison = ...
                v2xsim.resource.metrics.compareAllocations( ...
                    ["a";"b"],[1;2],[1;4], ...
                    [0 10;10 0],[2 3], ...
                    FrequencyInterferenceCoupling=eye(3));

            testCase.verifyEqual( ...
                comparison.Summary. ...
                    HarmfulInterferenceOverlapCandidateCount,0);
            testCase.verifyEqual( ...
                comparison.Summary. ...
                    InterferenceOverlapPairGraphXorCount,0);
        end

        function unchangedAdjacentPairIsOmittedFromSparseRows( ...
                testCase)
            assignments = table( ...
                ["a";"b"],[1;2], ...
                VariableNames=["UeId","ResourceIds"]);

            rows = ...
                v2xsim.resource.metrics.buildReuseCandidateRows( ...
                    assignments,assignments,[1 3]);

            testCase.verifyEmpty(rows);
            testCase.verifyTrue(all(ismember( ...
                [ ...
                    "LiveResourceRelation", ...
                    "OracleResourceRelation", ...
                    "IsHarmfulInterferenceOverlap", ...
                    "IsMissedInterferenceOverlap"], ...
                string(rows.Properties.VariableNames))));
        end

        function rankDetailCanBeOmittedWithoutLosingEgoMetrics( ...
                testCase)
            ueIds = ["a";"b";"c";"d"];
            truth = [ ...
                0 1 2 3;1 0 4 5;2 4 0 6;3 5 6 0];
            apparent = truth;
            apparent(1,:) = [0 3 1 2];
            apparent(:,1) = apparent(1,:).';

            detailed = ...
                v2xsim.resource.metrics.compareNeighborTopology( ...
                    ueIds,apparent,truth,TopK=2);
            compact = ...
                v2xsim.resource.metrics.compareNeighborTopology( ...
                    ueIds,apparent,truth,TopK=2, ...
                    IncludeRankDisplacement=false);

            testCase.verifyEqual(compact.Topology,detailed.Topology);
            testCase.verifyEmpty(compact.RankDisplacement);
            testCase.verifyEqual( ...
                compact.RankDisplacement.Properties.VariableNames, ...
                detailed.RankDisplacement.Properties.VariableNames);
        end
    end
end
