classdef (Abstract, HandleCompatible) StatusEffect
    %STATUSEFFECT Stateful selection and activation lifecycle for targets.
    %   Status effects track target state independently of the subsystem
    %   that gives an active effect its consequence. Targets are evaluated
    %   for selection once when they first become eligible. A selected
    %   target is active whenever the caller reports that the effect is
    %   applicable, until an optional reset permanently clears selection.

    properties (SetAccess = immutable)
        SelectionProbability (1, 1) double ...
            {mustBeReal, mustBeFinite, mustBeNonnegative} = 0
        SelectionRandomSeed (1, 1) double ...
            {mustBeReal, mustBeFinite, mustBeInteger, ...
            mustBeNonnegative} = 0
        ResetAfterSeconds (1, 1) double ...
            {mustBeReal, mustBeNonnegative} = Inf
    end

    properties (Access = private)
        TargetStates table = table( ...
            false(0, 1), false(0, 1), NaN(0, 1), ...
            false(0, 1), zeros(0, 1), ...
            VariableNames=[ ...
                "Evaluated", "Selected", "ActivatedAtSeconds", ...
                "IsActive", "EpisodeId"])
        SelectionRandomStream (1, 1) RandStream = ...
            RandStream("mt19937ar", Seed=0)
        LastSimulationTimeSeconds (1, 1) double = NaN
    end

    methods (Access = protected)
        function obj = StatusEffect( ...
                selectionProbability, selectionRandomSeed, ...
                resetAfterSeconds, selectionRandomStream)
            arguments (Input)
                selectionProbability (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative}
                selectionRandomSeed (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeInteger, ...
                    mustBeNonnegative}
                resetAfterSeconds (1, 1) double ...
                    {mustBeReal, mustBeNonnegative}
                selectionRandomStream = []
            end

            if selectionProbability > 1
                error( ...
                    "v2xsim:status:InvalidSelectionProbability", ...
                    "SelectionProbability must lie between zero and " + ...
                    "one, inclusive.");
            end
            if isnan(resetAfterSeconds)
                error( ...
                    "v2xsim:status:InvalidResetDuration", ...
                    "ResetAfterSeconds must be nonnegative or Inf.");
            end

            obj.SelectionProbability = selectionProbability;
            obj.ResetAfterSeconds = resetAfterSeconds;
            [obj.SelectionRandomStream, obj.SelectionRandomSeed] = ...
                v2xsim.status.internal.createOwnedRandomStream( ...
                    selectionRandomSeed, selectionRandomStream);
        end
    end

    methods (Sealed)
        function [obj, lifecycle] = advance( ...
                obj, targetIds, eligible, applicable, ...
                simulationTimeSeconds)
            %ADVANCE Update selection, activation, reset, and episode state.
            arguments (Input)
                obj (1, 1)
                targetIds (:, 1) string
                eligible
                applicable
                simulationTimeSeconds (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative}
            end

            if ~islogical(eligible) || ~islogical(applicable)
                error( ...
                    "v2xsim:status:InvalidTargetMask", ...
                    "Eligible and applicable masks must be logical.");
            end
            targetCount = numel(targetIds);
            expectedMaskSize = [targetCount, 1];
            if ~isequal(size(eligible), expectedMaskSize) || ...
                    ~isequal(size(applicable), expectedMaskSize)
                error( ...
                    "v2xsim:status:TargetMaskSizeMismatch", ...
                    "Eligible and applicable masks must contain one " + ...
                    "value per target.");
            end
            if any(ismissing(targetIds) | strlength(targetIds) == 0) || ...
                    numel(unique(targetIds)) ~= targetCount
                error( ...
                    "v2xsim:status:InvalidTargetIds", ...
                    "Target IDs must be unique, nonmissing, and nonempty.");
            end
            if ~isnan(obj.LastSimulationTimeSeconds) && ...
                    simulationTimeSeconds < ...
                    obj.LastSimulationTimeSeconds
                error( ...
                    "v2xsim:status:TimeReversed", ...
                    "Status effects require nondecreasing simulation " + ...
                    "times.");
            end
            obj.LastSimulationTimeSeconds = simulationTimeSeconds;

            previouslyKnownIds = string( ...
                obj.TargetStates.Properties.RowNames);
            firstObservation = ~ismember(targetIds, previouslyKnownIds);
            obj = obj.ensureTargetStates(targetIds);
            knownIds = string(obj.TargetStates.Properties.RowNames);
            [~, stateIndices] = ismember(targetIds, knownIds);

            shouldEvaluate = eligible & ...
                ~obj.TargetStates.Evaluated(stateIndices);
            [obj, selectedNow] = obj.drawSelections( ...
                targetIds, shouldEvaluate);
            if any(shouldEvaluate)
                evaluatedIndices = stateIndices(shouldEvaluate);
                obj.TargetStates.Evaluated(evaluatedIndices) = true;
                obj.TargetStates.Selected(evaluatedIndices) = ...
                    selectedNow(shouldEvaluate);
            end

            selected = obj.TargetStates.Selected(stateIndices);
            activatedAt = ...
                obj.TargetStates.ActivatedAtSeconds(stateIndices);
            firstActivation = selected & applicable & isnan(activatedAt);
            if any(firstActivation)
                activatedIndices = stateIndices(firstActivation);
                obj.TargetStates.ActivatedAtSeconds( ...
                    activatedIndices) = simulationTimeSeconds;
                activatedAt(firstActivation) = simulationTimeSeconds;
            end

            shouldReset = selected & ~isnan(activatedAt) & ...
                simulationTimeSeconds - activatedAt >= ...
                obj.ResetAfterSeconds;
            if any(shouldReset)
                resetIndices = stateIndices(shouldReset);
                obj.TargetStates.Selected(resetIndices) = false;
                selected(shouldReset) = false;
            end

            previouslyActive = ...
                obj.TargetStates.IsActive(stateIndices);
            isActive = selected & applicable;
            entered = ~previouslyActive & isActive;
            exited = previouslyActive & ~isActive;
            if any(entered)
                enteredIndices = stateIndices(entered);
                obj.TargetStates.EpisodeId(enteredIndices) = ...
                    obj.TargetStates.EpisodeId(enteredIndices) + 1;
            end
            obj.TargetStates.IsActive(stateIndices) = isActive;

            episodeId = obj.TargetStates.EpisodeId(stateIndices);
            episodeId(episodeId == 0) = NaN;
            lifecycle = struct( ...
                IsEvaluated= ...
                    obj.TargetStates.Evaluated(stateIndices), ...
                EvaluationOccurred=shouldEvaluate, ...
                SelectionOccurred=shouldEvaluate & selectedNow, ...
                IsSelected=selected, ...
                ActiveSegmentEntered=entered, ...
                IsActive=isActive, ...
                ActiveSegmentExited=exited, ...
                ResetOccurred=shouldReset, ...
                EpisodeId=episodeId, ...
                LeftCensoredAtStart=entered & firstObservation);
        end
    end

    methods (Access = private)
        function obj = ensureTargetStates(obj, targetIds)
            knownIds = string(obj.TargetStates.Properties.RowNames);
            missingIds = targetIds(~ismember(targetIds, knownIds));
            if isempty(missingIds)
                return
            end

            newStates = table( ...
                false(numel(missingIds), 1), ...
                false(numel(missingIds), 1), ...
                NaN(numel(missingIds), 1), ...
                false(numel(missingIds), 1), ...
                zeros(numel(missingIds), 1), ...
                VariableNames=obj.TargetStates.Properties.VariableNames, ...
                RowNames=cellstr(missingIds));
            obj.TargetStates = [obj.TargetStates; newStates];
        end

        function [obj, selected] = drawSelections( ...
                obj, targetIds, shouldEvaluate)
            selected = false(size(targetIds));
            evaluationIndices = find(shouldEvaluate);
            if isempty(evaluationIndices) || ...
                    obj.SelectionProbability == 0
                return
            end
            if obj.SelectionProbability == 1
                selected(evaluationIndices) = true;
                return
            end

            [~, stableOrder] = sort(targetIds(evaluationIndices));
            orderedIndices = evaluationIndices(stableOrder);
            [obj.SelectionRandomStream, ~] = ...
                v2xsim.status.internal.createOwnedRandomStream( ...
                    obj.SelectionRandomSeed, ...
                    obj.SelectionRandomStream);
            selected(orderedIndices) = rand( ...
                obj.SelectionRandomStream, ...
                numel(orderedIndices), 1) < ...
                obj.SelectionProbability;
        end
    end
end
