%% 07 - Run NR-V2X with centralized Mode 1-style allocation
% MaximumReuseDistance is one of V7's centralized cellular-sidelink
% allocators. The summary records the exact allocator and its category.

exampleScriptDirectory = fileparts(mfilename("fullpath"));
[exampleResults,exampleOutputDirectory] = runExample( ...
    exampleScriptDirectory);
clear exampleScriptDirectory

disp(exampleResults.Overview)
fprintf("Completed output: %s\n",exampleOutputDirectory);

function [results,outputDirectory] = runExample(exampleDirectory)
timer = tic;
configurationFile = fullfile( ...
    exampleDirectory,"07_nr_mode1_quickstart.toml");
outputDirectory = string(tempname);
template = v2xsim.config.load(configurationFile);
configuration = template.resolve();
simulationTimer = tic;
simulationResult = v2xsim.runSimulation( ...
    configuration, ...
    OutputDirectory=outputDirectory, ...
    RunLabel="nr-mode1-quickstart");
simulationElapsedSeconds = toc(simulationTimer);
outputDirectory = simulationResult.RunDirectory;
summary = jsondecode(fileread(fullfile( ...
    simulationResult.RunDirectory,"simulation_summary.json")));

metadata = summary.Configuration.ResourceAllocation.Metadata;
assert(string(summary.Configuration.RadioAccessMode) == "NR-V2X", ...
    "The quickstart did not run NR-V2X.");
assert(string(metadata.Category) == "Centralized", ...
    "The quickstart did not use centralized allocation.");

prrFiles = dir(fullfile( ...
    outputDirectory,"packet_reception_ratio_*.csv"));
assert(isscalar(prrFiles), ...
    "The NR Mode 1 quickstart did not produce its PRR artifact.");
prr = readPrr(fullfile(prrFiles(1).folder,prrFiles(1).name));

overview = table( ...
    string(summary.Configuration.RadioAccessMode), ...
    string(metadata.Type), ...
    string(metadata.Category), ...
    summary.Results.CellularSidelink.AverageUeCount, ...
    cellularPacketReceptionRatio(summary), ...
    VariableNames=[ ...
        "RadioAccessMode","Allocator","Category", ...
        "AverageUeCount","PacketReceptionRatio"]);

figure(Name="V7 NR Mode 1 quickstart");
plot( ...
    prr.DistanceUpperBoundMeters,prr.PacketReceptionRatio, ...
    "o-",LineWidth=1.2);
grid on
xlabel("Distance upper bound (m)")
ylabel("Packet reception ratio")
ylim([0,1])
title("NR-V2X centralized allocation")

elapsedSeconds = toc(timer);
if elapsedSeconds > 30
    warning( ...
        "v2xsimexample:SlowExample", ...
        "This example took %.1f seconds on this computer.", ...
        elapsedSeconds);
end

results = struct( ...
    SimulationResult=simulationResult, ...
    Summary=summary, ...
    Overview=overview, ...
    PacketReceptionRatio=prr, ...
    SimulationElapsedSeconds=simulationElapsedSeconds, ...
    ElapsedSeconds=elapsedSeconds);
end

function result = readPrr(filename)
values = readmatrix(filename);
result = array2table( ...
    values, ...
    VariableNames=[ ...
        "DistanceUpperBoundMeters","CorrectCount","ErrorCount", ...
        "BlockedCount","OpportunityCount","PacketReceptionRatio"]);
end

function ratio = cellularPacketReceptionRatio(summary)
metrics = summary.Results.CellularSidelink.AwarenessRangeMetrics;
if iscell(metrics)
    metric = metrics{end};
else
    metric = metrics(end);
end
ratio = metric.PacketReceptionRatio;
if isempty(ratio)
    ratio = NaN;
end
end
