%% 07 - Run NR-V2X with centralized Mode 1-style allocation
% MaximumReuseDistance is one of V7's centralized cellular-sidelink
% allocators. The summary records the exact allocator and its category.

exampleScriptDirectory = fileparts(mfilename("fullpath"));
[exampleResults,exampleOutputDirectory] = runExample( ...
    exampleScriptDirectory);
clear exampleScriptDirectory

disp(exampleResults.Overview)
fprintf("Completed output: %s\n",exampleOutputDirectory);

function [results,outputDirectory] = runExample(exampleDirectory)
timer = tic;
configurationFile = fullfile( ...
    exampleDirectory,"07_nr_mode1_quickstart.toml");
outputDirectory = string(tempname);
template = v2xsim.config.load(configurationFile);
repetitionCount = 5;
baseSeed = template.Data.Simulation.RandomSeed;
prrRows = table();
simulationTimer = tic;
for repetition = 1:repetitionCount
    configuration = template.resolve(Patch=v2xsim.config.patch(struct( ...
        "Simulation",struct("RandomSeed",baseSeed + repetition - 1))));
    repetitionOutputDirectory = string(tempname);
    simulationResult = v2xsim.runSimulation( ...
        configuration, ...
        OutputDirectory=repetitionOutputDirectory, ...
        RunLabel="nr-mode1-quickstart-repetition-" + repetition);
    outputDirectory = simulationResult.RunDirectory;
    prrRows = [prrRows; ...
        v2xsim.analysis.readDeliveryPrrArtifact(outputDirectory)]; %#ok<AGROW>
end
simulationElapsedSeconds = toc(simulationTimer);
summary = jsondecode(fileread(fullfile( ...
    simulationResult.RunDirectory,"simulation_summary.json")));

metadata = summary.Configuration.ResourceAllocation.Metadata;
assert(string(summary.Configuration.RadioAccessMode) == "NR-V2X", ...
    "The quickstart did not run NR-V2X.");
assert(string(metadata.Category) == "Centralized", ...
    "The quickstart did not use centralized allocation.");

prr = v2xsim.analysis.poolPacketReceptionCounts(prrRows, ...
    GroupVariables=strings(1,0));
[deliveryPrrRangeMeters,deliveryPrrRangeStatus,plotCurve] = ...
    v2xsim.analysis.prrThresholdRange(prr);

overview = table( ...
    string(summary.Configuration.RadioAccessMode), ...
    string(metadata.Type), ...
    string(metadata.Category), ...
    summary.Results.CellularSidelink.AverageUeCount, ...
    cellularPacketReceptionRatio(summary), ...
    VariableNames=[ ...
        "RadioAccessMode","Allocator","Category", ...
        "AverageUeCount","PacketReceptionRatio"]);

figure(Name="V7 NR Mode 1 quickstart");
plot( ...
    plotCurve.DistanceMeters,plotCurve.DeliveryPrr, ...
    "o-",LineWidth=1.2,DisplayName="Delivery PRR");
hold on
yline(0.9,"--",DisplayName="90% threshold");
if isfinite(deliveryPrrRangeMeters)
    xline( ...
        deliveryPrrRangeMeters,":", ...
        "90% range: " + string(sprintf( ...
            "%.1f m (%s)",deliveryPrrRangeMeters, ...
            char(deliveryPrrRangeStatus))), ...
        DisplayName="90% range");
    if deliveryPrrRangeStatus == "Crossed"
        plot( ...
            deliveryPrrRangeMeters,0.9,"o", ...
            DisplayName="Threshold crossing");
    end
else
    text(0.02,0.08,"90% range unavailable: incomplete distance grid", ...
        Units="normalized");
end
hold off
grid on
xlabel("Distance (m)")
ylabel("Delivery PRR")
ylim([0,1])
title("NR-V2X centralized allocation: delivery PRR")
legend(Location="best")

elapsedSeconds = toc(timer);
if elapsedSeconds > 30
    warning( ...
        "v2xsimexample:SlowExample", ...
        "This example took %.1f seconds on this computer.", ...
        elapsedSeconds);
end

results = struct( ...
    SimulationResult=simulationResult, ...
    Summary=summary, ...
    Overview=overview, ...
    PacketReceptionRatio=prr, ...
    DeliveryPrrByDistance=prr, ...
    DeliveryPrrRangeMeters=deliveryPrrRangeMeters, ...
    DeliveryPrrRangeStatus=deliveryPrrRangeStatus, ...
    RepetitionCount=repetitionCount, ...
    SimulationElapsedSeconds=simulationElapsedSeconds, ...
    ElapsedSeconds=elapsedSeconds);
end

function ratio = cellularPacketReceptionRatio(summary)
metrics = summary.Results.CellularSidelink.AwarenessRangeMetrics;
if iscell(metrics)
    metric = metrics{end};
else
    metric = metrics(end);
end
ratio = metric.PacketReceptionRatio;
if isempty(ratio)
    ratio = NaN;
end
end
