function results = runPublishedCampaigns( ...
        simulatorRoot, outputDirectory, options)
%RUNPUBLISHEDCAMPAIGNS Run the Wu et al. 2023 coexistence campaigns.
%   RESULTS contains one aggregated row per technology and configuration.
%   Raw PRR and delay histograms are pooled across deterministic seeds
%   before the metrics are calculated. Per-seed metrics are written to
%   campaign-seed-summary.csv for diagnostics.

arguments (Input)
    simulatorRoot (1, 1) string {mustBeNonzeroLengthText}
    outputDirectory (1, 1) string {mustBeNonzeroLengthText}
    options.Methods (1, :) string = [ ...
        "no_method", "enhanced_A", "method_B", "dynamic_C", ...
        "dynamic_C_preamble", "method_F"]
    options.DensitiesVehiclesPerKilometer (1, :) double ...
        {mustBeReal, mustBeFinite, mustBePositive} = 6
    options.SidelinkFractions (1, :) double ...
        {mustBeReal, mustBeFinite, mustBeNonnegative} = 0.5
    options.PacketIntervalVariationsSeconds (1, :) double ...
        {mustBeReal, mustBeFinite} = 0
    options.RandomSeeds (1, :) double ...
        {mustBeInteger, mustBePositive} = 10:15
    options.SimulationTimeSeconds (1, 1) double ...
        {mustBeReal, mustBeFinite, mustBePositive} = ...
        defaultSimulationTimeSeconds()
    options.ExecutionMode (1, 1) string {mustBeMember( ...
        options.ExecutionMode, ["auto", "serial", "parallel"])} = "auto"
    options.MaxWorkers (1, 1) double { ...
        v2xsimregression.execution.mustBeWorkerLimit} = Inf
end

arguments (Output)
    results table
end

validateCampaignOptions(options);
[sourceDirectory, fixtureDirectory, tomlDirectory] = ...
    resolveSimulatorDirectories(simulatorRoot);
validateSimulatorRoot( ...
    simulatorRoot, fixtureDirectory);
prepareOutputDirectory(outputDirectory);

originalPath = path;
randomStream = RandStream.getGlobalStream();
originalRandomState = randomStream.State;
environmentCleanup = onCleanup( ...
    @() restoreEnvironment( ...
        originalPath, randomStream, originalRandomState));

addpath(sourceDirectory);
addpath(tomlDirectory);

results = createEmptyResults(0);
seedResults = createEmptySeedResults(0);
roadLengthKilometers = 8;
workItems = cell(1, 0);
workLabels = strings(1, 0);
for density = options.DensitiesVehiclesPerKilometer
    vehicleCount = round(density .* roadLengthKilometers);
    for sidelinkFraction = options.SidelinkFractions
        sidelinkVehicleCount = ceil( ...
            vehicleCount .* sidelinkFraction);
        itsG5VehicleCount = vehicleCount - sidelinkVehicleCount;
        for intervalVariation = ...
                options.PacketIntervalVariationsSeconds
            for method = options.Methods
                methodOutputDirectory = campaignOutputDirectory( ...
                    outputDirectory, density, sidelinkFraction, ...
                    intervalVariation, method);
                for randomSeed = options.RandomSeeds
                    seedDirectory = fullfile( ...
                        methodOutputDirectory, ...
                        compose("seed-%d", randomSeed));
                    workItem = struct( ...
                        SourceDirectory=sourceDirectory, ...
                        ConfigurationFile=fullfile( ...
                            fixtureDirectory, "cochannel.toml"), ...
                        OutputDirectory=seedDirectory, ...
                        Method=method, ...
                        Density=density, ...
                        VehicleCount=vehicleCount, ...
                        SidelinkFraction=sidelinkFraction, ...
                        SidelinkVehicleCount=sidelinkVehicleCount, ...
                        ItsG5VehicleCount=itsG5VehicleCount, ...
                        IntervalVariation=intervalVariation, ...
                        RandomSeed=randomSeed, ...
                        SimulationTimeSeconds= ...
                            options.SimulationTimeSeconds);
                    workItems{end + 1} = workItem; %#ok<AGROW>
                    workLabels(end + 1) = compose( ...
                        "method=%s,density=%g,nr-fraction=%g," + ...
                        "traffic=%g,seed=%d", ...
                        method, density, sidelinkFraction, ...
                        intervalVariation, randomSeed); %#ok<AGROW>
                end
            end
        end
    end
end
assertUniqueWorkItemDirectories(workItems);

additionalPaths = [ ...
    fullfile(simulatorRoot, "regression-tests"), ...
    sourceDirectory, ...
    tomlDirectory];
seedDirectoryOutputs = ...
    v2xsimregression.execution.runWorkItems( ...
        workItems, @runSeedWorkItem, ...
        Labels=workLabels, ...
        ExecutionMode=options.ExecutionMode, ...
        MaxWorkers=options.MaxWorkers, ...
        AdditionalPaths=additionalPaths);

workIndex = 0;
for density = options.DensitiesVehiclesPerKilometer
    for sidelinkFraction = options.SidelinkFractions
        for intervalVariation = ...
                options.PacketIntervalVariationsSeconds
            for method = options.Methods
                methodOutputDirectory = campaignOutputDirectory( ...
                    outputDirectory, density, sidelinkFraction, ...
                    intervalVariation, method);
                seedRange = workIndex + (1:numel(options.RandomSeeds));
                seedDirectories = string(seedDirectoryOutputs(seedRange)).';
                workIndex = workIndex + numel(options.RandomSeeds);

                technologies = technologiesForMethod(method);
                for technology = technologies
                    summary = summarizeTechnology( ...
                        method, technology, density, ...
                        sidelinkFraction, intervalVariation, ...
                        options.RandomSeeds, ...
                        options.SimulationTimeSeconds, ...
                        methodOutputDirectory, seedDirectories);
                    results = [results; summary]; %#ok<AGROW>
                    seedSummary = summarizeTechnologySeeds( ...
                        method, technology, density, ...
                        sidelinkFraction, intervalVariation, ...
                        options.RandomSeeds, ...
                        options.SimulationTimeSeconds, ...
                        seedDirectories);
                    seedResults = [ ...
                        seedResults; seedSummary]; %#ok<AGROW>
                end
            end
        end
    end
end

writetable(results, fullfile(outputDirectory, "campaign-summary.csv"));
writetable( ...
    seedResults, ...
    fullfile(outputDirectory, "campaign-seed-summary.csv"));
end

function validateCampaignOptions(options)
supportedMethods = [ ...
    "only_NR", "only_ITS", "no_method", "enhanced_A", ...
    "method_B", "dynamic_C", "dynamic_C_preamble", "method_F"];
if any(~ismember(options.Methods, supportedMethods))
    unsupportedMethods = options.Methods( ...
        ~ismember(options.Methods, supportedMethods));
    error( ...
        "v2xsimregression:zhuofei2023cochannel:UnsupportedMethod", ...
        "Unsupported method(s): %s.", ...
        join(unsupportedMethods, ", "));
end
if numel(unique(options.Methods)) ~= numel(options.Methods)
    error( ...
        "v2xsimregression:zhuofei2023cochannel:DuplicateMethod", ...
        "Methods must not contain duplicates.");
end
uniqueOptions = { ...
    options.DensitiesVehiclesPerKilometer, ...
    options.SidelinkFractions, ...
    options.PacketIntervalVariationsSeconds, ...
    options.RandomSeeds};
optionNames = [ ...
    "DensitiesVehiclesPerKilometer", ...
    "SidelinkFractions", ...
    "PacketIntervalVariationsSeconds", ...
    "RandomSeeds"];
for optionIndex = 1:numel(uniqueOptions)
    values = uniqueOptions{optionIndex};
    if numel(unique(values)) ~= numel(values)
        error( ...
            "v2xsimregression:zhuofei2023cochannel:DuplicateOption", ...
            "%s must not contain duplicates.", ...
            optionNames(optionIndex));
    end
end
if any(options.SidelinkFractions > 1)
    error( ...
        "v2xsimregression:zhuofei2023cochannel:InvalidFraction", ...
        "SidelinkFractions must be between zero and one.");
end
if isempty(options.Methods) || isempty(options.RandomSeeds)
    error( ...
        "v2xsimregression:zhuofei2023cochannel:EmptyCampaign", ...
        "Methods and RandomSeeds must both be nonempty.");
end
if any(~ismember( ...
        options.PacketIntervalVariationsSeconds, [0, -1]))
    error( ...
        "v2xsimregression:zhuofei2023cochannel:InvalidTraffic", ...
        ["PacketIntervalVariationsSeconds must be 0 for periodic ", ...
        "traffic or -1 for the ETSI CAM rules."]);
end
end

function seedDirectory = runSeedWorkItem(workItem)
seedDirectory = workItem.OutputDirectory;
    runSimulation( ...
        workItem.SourceDirectory, workItem.ConfigurationFile, ...
        seedDirectory, workItem.Method, workItem.Density, ...
        workItem.VehicleCount, workItem.SidelinkFraction, ...
        workItem.SidelinkVehicleCount, workItem.ItsG5VehicleCount, ...
        workItem.IntervalVariation, workItem.RandomSeed, ...
        workItem.SimulationTimeSeconds);
end

function runSimulation( ...
        sourceDirectory, configurationFile, outputDirectory, ...
        method, density, vehicleCount, sidelinkFraction, ...
        sidelinkVehicleCount, itsG5VehicleCount, ...
        intervalVariation, randomSeed, simulationTimeSeconds)
if intervalVariation == 0
    packetGeneration = struct( ...
        Mode="Periodic", ...
        IntervalVariationSeconds=0);
else
    packetGeneration = struct(Mode="EtsiCam");
end

patchData = struct( ...
    Simulation=struct( ...
        RandomSeed=randomSeed, ...
        DurationSeconds=simulationTimeSeconds), ...
    Scenario=struct( ...
        BidirectionalHighway=struct( ...
            RandomSeed=randomSeed, ...
            VehicleCount=vehicleCount)), ...
    Application=struct( ...
        PacketSizeBytes=350, ...
        PacketGeneration=packetGeneration), ...
    Radio=radioPatch(method), ...
    Awareness=struct(RangesMeters=[50, 150, 300, 500]), ...
    Outputs=struct( ...
        AverageNeighborCount=struct(Enabled=false), ...
        UpdateDelay=struct(Enabled=false), ...
        PacketDelay=struct(Enabled=true), ...
        DataAge=struct(Enabled=true), ...
        PacketReceptionRatio=struct(Enabled=true), ...
        ChannelBusyRatio=struct(Enabled=false), ...
        CoexistenceTechnologyShare=struct( ...
            Enabled=method == "dynamic_C")));
if ~ismember(method, ["only_NR", "only_ITS"])
    patchData.Coexistence = coexistencePatch( ...
        method, sidelinkVehicleCount, itsG5VehicleCount);
end

template = v2xsim.config.load(configurationFile);
configuration = template.resolve( ...
    Patch=v2xsim.config.patch(patchData)); %#ok<NASGU>
runLabel = compose( ...
    "density=%g, nr-fraction=%g, traffic=%g, method=%s, seed=%d", ...
    density, sidelinkFraction, intervalVariation, method, ...
    randomSeed); %#ok<NASGU>
evalc("v2xsim.runSimulation(configuration," + ...
    "OutputDirectory=outputDirectory,RunLabel=runLabel);");
validateSimulationOutputs( ...
    outputDirectory,technologiesForMethod(method),method);

resolvedEntrypoint = string(which("v2xsim.runSimulation"));
if ~startsWith(resolvedEntrypoint, sourceDirectory)
    error( ...
        "v2xsimregression:zhuofei2023cochannel:WrongSimulator", ...
        "v2xsim.runSimulation resolved outside the requested simulator: %s", ...
        resolvedEntrypoint);
end
end

function radio = radioPatch(method)
if method == "only_NR"
    radio = struct(Type="NrV2X", NrV2X=struct());
elseif method == "only_ITS"
    radio = struct( ...
        Type="Ieee80211p", ...
        Ieee80211p=struct());
else
    radio = struct( ...
        Type="Coexistence", ...
        Coexistence=struct( ...
            SidelinkType="NrV2X", ...
            InterferenceModel="Cochannel"));
end
end

function patchData = coexistencePatch( ...
        method, sidelinkVehicleCount, itsG5VehicleCount)
patchData = struct( ...
    VehiclePattern=struct( ...
        SidelinkVehicleCount=sidelinkVehicleCount, ...
        ItsG5VehicleCount=itsG5VehicleCount));
if method == "no_method"
    patchData.Method = "Standard";
elseif method == "enhanced_A"
    patchData.Method = "MethodA";
    patchData.MethodA = struct(EnhancementVariant=2);
    patchData.Superframe = struct( ...
        DurationSeconds=0.025, ...
        SidelinkPortionEndSeconds=0.013);
elseif method == "method_B"
    patchData.Method = "MethodB";
    patchData.MethodB = struct();
    patchData.Superframe = struct( ...
        DurationSeconds=0.025, ...
        SidelinkPortionEndSeconds=0.013);
elseif method == "dynamic_C"
    patchData.Method = "MethodC";
    patchData.MethodC = struct();
    patchData.Superframe = struct( ...
        DurationSeconds=0.025, ...
        SlotManagement="Dynamic");
elseif method == "dynamic_C_preamble"
    patchData.Method = "MethodC";
    patchData.MethodC = struct();
    patchData.Superframe = struct( ...
        DurationSeconds=0.05, ...
        SidelinkPortionEndSeconds=0.05);
elseif method == "method_F"
    patchData.Method = "MethodF";
    patchData.MethodF = struct();
    patchData.Superframe = struct( ...
        DurationSeconds=0.025, ...
        SidelinkPortionEndSeconds=0.013);
else
    error( ...
        "v2xsimregression:zhuofei2023cochannel:UnsupportedMethod", ...
        "Unsupported coexistence method: %s.", method);
end
end

function validateSimulationOutputs( ...
        outputDirectory,technologies,method)
summaryFile = fullfile(outputDirectory,"simulation_summary.json");
if ~isfile(summaryFile)
    error( ...
        "v2xsimregression:zhuofei2023cochannel:MissingOutput", ...
        "The simulator did not create the expected file: %s", ...
        summaryFile);
end
if method == "dynamic_C"
    technologyShareFile = fullfile( ...
        outputDirectory,"coexistence_technology_share.csv");
    if ~isfile(technologyShareFile)
        error( ...
            "v2xsimregression:zhuofei2023cochannel:MissingOutput", ...
            "The simulator did not create the expected file: %s", ...
            technologyShareFile);
    end
    technologyShare = readtable( ...
        technologyShareFile, TextType="string");
    expectedNames = [ ...
        "SimulationTimeSeconds", ...
        "VehicleId", ...
        "CellularSidelinkOnlyChannelBusyRatio", ...
        "CombinedChannelBusyRatio", ...
        "CellularSidelinkVehicleFraction", ...
        "AllocatedCellularSidelinkSubframeCount"];
    if ~isequal( ...
            string(technologyShare.Properties.VariableNames), ...
            expectedNames)
        error( ...
            "v2xsimregression:zhuofei2023cochannel:" + ...
            "InvalidTechnologyShareSchema", ...
            "Unexpected coexistence technology-share schema in: %s", ...
            technologyShareFile);
    end
end
for technology = technologies
    suffix = outputSuffix(technology);
    expectedFiles = [ ...
        "packet_reception_ratio_" + suffix + ".csv", ...
        "packet_delay_" + suffix + ".csv", ...
        "data_age_" + suffix + ".csv"];
    for expectedFile = expectedFiles
        expectedPath = fullfile(outputDirectory, expectedFile);
        if ~isfile(expectedPath)
            error( ...
                "v2xsimregression:zhuofei2023cochannel:MissingOutput", ...
                "The simulator did not create the expected file: %s", ...
                expectedPath);
        end
    end
end
end

function summary = summarizeTechnology( ...
        method, technology, density, sidelinkFraction, ...
        intervalVariation, randomSeeds, simulationTimeSeconds, ...
        methodOutputDirectory, seedDirectories)
suffix = outputSuffix(technology);
prrFiles = fullfile( ...
    seedDirectories, "packet_reception_ratio_" + suffix + ".csv");
delayFiles = fullfile( ...
    seedDirectories, "packet_delay_" + suffix + ".csv");
dataAgeFiles = fullfile( ...
    seedDirectories, "data_age_" + suffix + ".csv");

[normalizedPrrScore, rangeAt90Meters] = summarizePrr(prrFiles);
meanEndToEndDelaySeconds = summarizeHistogram(delayFiles, 6);
meanDataAgeSeconds = summarizeHistogram(dataAgeFiles, 8);
trafficPattern = trafficPatternName(intervalVariation);
seedCount = numel(randomSeeds);
itsG5Fraction = 1 - sidelinkFraction;

summary = table( ...
    method, technology, density, sidelinkFraction, itsG5Fraction, ...
    intervalVariation, trafficPattern, seedCount, ...
    simulationTimeSeconds, normalizedPrrScore, rangeAt90Meters, ...
    meanEndToEndDelaySeconds, meanDataAgeSeconds, ...
    methodOutputDirectory, ...
    VariableNames=[ ...
        "Method", "Technology", "DensityVehiclesPerKilometer", ...
        "SidelinkFraction", "ItsG5Fraction", ...
        "PacketIntervalVariationSeconds", "TrafficPattern", ...
        "SeedCount", "SimulationTimeSeconds", ...
        "NormalizedPrrScore", "RangeAt90Meters", ...
        "MeanEndToEndDelaySeconds", "MeanDataAgeSeconds", ...
        "OutputDirectory"]);
end

function summaries = summarizeTechnologySeeds( ...
        method, technology, density, sidelinkFraction, ...
        intervalVariation, randomSeeds, simulationTimeSeconds, ...
        seedDirectories)
seedCount = numel(randomSeeds);
normalizedPrrScores = zeros(seedCount, 1);
rangesAt90Meters = zeros(seedCount, 1);
meanEndToEndDelaySeconds = zeros(seedCount, 1);
meanDataAgeSeconds = zeros(seedCount, 1);
suffix = outputSuffix(technology);

for seedIndex = 1:seedCount
    seedDirectory = seedDirectories(seedIndex);
    prrFile = fullfile( ...
        seedDirectory, ...
        "packet_reception_ratio_" + suffix + ".csv");
    delayFile = fullfile( ...
        seedDirectory, "packet_delay_" + suffix + ".csv");
    dataAgeFile = fullfile( ...
        seedDirectory, "data_age_" + suffix + ".csv");

    [normalizedPrrScores(seedIndex), ...
        rangesAt90Meters(seedIndex)] = summarizePrr(prrFile);
    meanEndToEndDelaySeconds(seedIndex) = ...
        summarizeHistogram(delayFile, 6);
    meanDataAgeSeconds(seedIndex) = ...
        summarizeHistogram(dataAgeFile, 8);
end

simulationSeeds = randomSeeds(:);
scenarioSeeds = simulationSeeds;
itsG5Fraction = 1 - sidelinkFraction;
summaries = table( ...
    repmat(method, seedCount, 1), ...
    repmat(technology, seedCount, 1), ...
    repmat(density, seedCount, 1), ...
    repmat(sidelinkFraction, seedCount, 1), ...
    repmat(itsG5Fraction, seedCount, 1), ...
    repmat(intervalVariation, seedCount, 1), ...
    repmat(trafficPatternName(intervalVariation), seedCount, 1), ...
    simulationSeeds, scenarioSeeds, ...
    repmat(simulationTimeSeconds, seedCount, 1), ...
    normalizedPrrScores, rangesAt90Meters, ...
    meanEndToEndDelaySeconds, meanDataAgeSeconds, ...
    seedDirectories, ...
    VariableNames=[ ...
        "Method", "Technology", "DensityVehiclesPerKilometer", ...
        "SidelinkFraction", "ItsG5Fraction", ...
        "PacketIntervalVariationSeconds", "TrafficPattern", ...
        "SimulationSeed", "ScenarioSeed", ...
        "SimulationTimeSeconds", "NormalizedPrrScore", ...
        "RangeAt90Meters", "MeanEndToEndDelaySeconds", ...
        "MeanDataAgeSeconds", "OutputDirectory"]);
end

function [normalizedPrrScore, rangeAt90Meters] = ...
        summarizePrr(prrFiles)
maximumScoreDistanceMeters = 1500;
distanceBinsMeters = (50:50:maximumScoreDistanceMeters).';
correctPackets = zeros(size(distanceBinsMeters));
totalPackets = zeros(size(distanceBinsMeters));

for prrFile = prrFiles.'
    prrData = readmatrix( ...
        prrFile, FileType="text", Delimiter=",");
    [hasBin, fileRow] = ismember( ...
        distanceBinsMeters, prrData(:, 1));
    correctPackets(hasBin) = correctPackets(hasBin) + ...
        prrData(fileRow(hasBin), 2);
    totalPackets(hasBin) = totalPackets(hasBin) + ...
        prrData(fileRow(hasBin), 5);
end

hasSamples = totalPackets > 0;
sampledDistancesMeters = distanceBinsMeters(hasSamples);
packetReceptionRatios = ...
    correctPackets(hasSamples) ./ totalPackets(hasSamples);
scoredDistancesMeters = [0; sampledDistancesMeters];
scoredPrr = [1; packetReceptionRatios];
normalizedPrrScore = ...
    trapz(scoredDistancesMeters, scoredPrr) ./ ...
    maximumScoreDistanceMeters;
rangeAt90Meters = firstThresholdCrossing( ...
    sampledDistancesMeters, packetReceptionRatios, 0.9);
end

function crossingDistance = firstThresholdCrossing( ...
        distances, values, threshold)
firstBelowThreshold = find(values < threshold, 1);
if isempty(firstBelowThreshold)
    crossingDistance = distances(end);
elseif firstBelowThreshold == 1
    crossingDistance = 0;
else
    leftIndex = firstBelowThreshold - 1;
    rightIndex = firstBelowThreshold;
    crossingDistance = interp1( ...
        values([leftIndex, rightIndex]), ...
        distances([leftIndex, rightIndex]), threshold);
end
end

function meanValue = summarizeHistogram(histogramFiles, lastCountColumn)
weightedSum = 0;
sampleCount = 0;
for histogramFile = histogramFiles.'
    histogramData = readmatrix( ...
        histogramFile, FileType="text", Delimiter=",");
    countColumns = 2:2:min( ...
        lastCountColumn, size(histogramData, 2));
    binCounts = sum(histogramData(:, countColumns), 2);
    isFiniteSample = ...
        isfinite(histogramData(:, 1)) & isfinite(binCounts);
    weightedSum = weightedSum + sum( ...
        histogramData(isFiniteSample, 1) .* ...
        binCounts(isFiniteSample));
    sampleCount = sampleCount + sum(binCounts(isFiniteSample));
end

if sampleCount == 0
    meanValue = NaN;
else
    meanValue = weightedSum ./ sampleCount;
end
end

function results = createEmptyResults(rowCount)
results = table( ...
    Size=[rowCount, 14], ...
    VariableTypes=[ ...
        "string", "string", "double", "double", "double", ...
        "double", "string", "double", "double", "double", ...
        "double", "double", "double", "string"], ...
    VariableNames=[ ...
        "Method", "Technology", "DensityVehiclesPerKilometer", ...
        "SidelinkFraction", "ItsG5Fraction", ...
        "PacketIntervalVariationSeconds", "TrafficPattern", ...
        "SeedCount", "SimulationTimeSeconds", ...
        "NormalizedPrrScore", "RangeAt90Meters", ...
        "MeanEndToEndDelaySeconds", "MeanDataAgeSeconds", ...
        "OutputDirectory"]);
end

function results = createEmptySeedResults(rowCount)
results = table( ...
    Size=[rowCount, 15], ...
    VariableTypes=[ ...
        "string", "string", "double", "double", "double", ...
        "double", "string", "double", "double", "double", ...
        "double", "double", "double", "double", "string"], ...
    VariableNames=[ ...
        "Method", "Technology", "DensityVehiclesPerKilometer", ...
        "SidelinkFraction", "ItsG5Fraction", ...
        "PacketIntervalVariationSeconds", "TrafficPattern", ...
        "SimulationSeed", "ScenarioSeed", ...
        "SimulationTimeSeconds", "NormalizedPrrScore", ...
        "RangeAt90Meters", "MeanEndToEndDelaySeconds", ...
        "MeanDataAgeSeconds", "OutputDirectory"]);
end

function technologies = technologiesForMethod(method)
if method == "only_NR"
    technologies = "NR-V2X";
elseif method == "only_ITS"
    technologies = "IEEE 802.11p";
else
    technologies = ["IEEE 802.11p", "NR-V2X"];
end
end

function suffix = outputSuffix(technology)
if technology == "IEEE 802.11p"
    suffix = "11p";
else
    suffix = "5G";
end
end

function name = trafficPatternName(intervalVariation)
if intervalVariation == 0
    name = "periodic";
else
    name = "ETSI-CAM";
end
end

function outputDirectory = campaignOutputDirectory( ...
        campaignRoot, density, sidelinkFraction, ...
        intervalVariation, method)
outputDirectory = fullfile( ...
    campaignRoot, ...
    "density-" + numericPathToken(density), ...
    "nr-fraction-" + numericPathToken(sidelinkFraction), ...
    trafficPatternName(intervalVariation), method);
end

function token = numericPathToken(value)
token = compose("%.17g",value);
token = replace(token,["-", "+", "."],["m", "p", "d"]);
end

function assertUniqueWorkItemDirectories(workItems)
outputDirectories = strings(1, numel(workItems));
for workIndex = 1:numel(workItems)
    outputDirectories(workIndex) = ...
        string(workItems{workIndex}.OutputDirectory);
end
if numel(unique(outputDirectories)) ~= numel(outputDirectories)
    error( ...
        "v2xsimregression:zhuofei2023cochannel:" + ...
        "OutputDirectoryCollision", ...
        "Campaign options generated duplicate run output directories.");
end
end

function [sourceDirectory, fixtureDirectory, tomlDirectory] = ...
        resolveSimulatorDirectories(simulatorRoot)
sourceDirectory = fullfile(simulatorRoot, "src");
fixtureDirectory = fullfile(fileparts(mfilename("fullpath")), "config");
tomlDirectory = fullfile(simulatorRoot, "lib", "matlab-toml");
end

function validateSimulatorRoot(simulatorRoot, fixtureDirectory)
if ~isfolder(simulatorRoot)
    error( ...
        "v2xsimregression:zhuofei2023cochannel:MissingSimulatorRoot", ...
        "SimulatorRoot is not a directory: %s", simulatorRoot);
end
if ~isfile(fullfile( ...
        simulatorRoot, "src", "+v2xsim", "runSimulation.m"))
    error( ...
        "v2xsimregression:zhuofei2023cochannel:MissingSimulator", ...
        "v2xsim.runSimulation was not found under: %s", ...
        simulatorRoot);
end
if ~isfile(fullfile(fixtureDirectory, "cochannel.toml"))
    error( ...
        "v2xsimregression:zhuofei2023cochannel:MissingConfiguration", ...
        "The co-channel regression configuration was not found under: %s", ...
        fixtureDirectory);
end
if ~isfolder(fullfile(simulatorRoot, "src", "+v2xsim"))
    error( ...
        "v2xsimregression:zhuofei2023cochannel:MissingRefactoredSource", ...
        "The simulator root requires src/+v2xsim under: %s", ...
        simulatorRoot);
end
end

function prepareOutputDirectory(outputDirectory)
if isfolder(outputDirectory)
    directoryEntries = dir(outputDirectory);
    entryNames = string({directoryEntries.name});
    isContent = ~ismember(entryNames, [".", ".."]);
    if any(isContent)
        error( ...
            "v2xsimregression:zhuofei2023cochannel:OutputNotEmpty", ...
            "Refusing to append results in nonempty folder: %s", ...
            outputDirectory);
    end
else
    [wasCreated, message] = mkdir(outputDirectory);
    if ~wasCreated
        error( ...
            "v2xsimregression:zhuofei2023cochannel:OutputCreationFailed", ...
            "Could not create output folder %s: %s", ...
            outputDirectory, message);
    end
end
end

function simulationTimeSeconds = defaultSimulationTimeSeconds()
configuredValue = string(getenv( ...
    "V2XSIM_PAPER_SIMULATION_TIME_SECONDS"));
if configuredValue == ""
    simulationTimeSeconds = 5;
    return
end

simulationTimeSeconds = str2double(configuredValue);
if ~isscalar(simulationTimeSeconds) || ...
        ~isfinite(simulationTimeSeconds) || simulationTimeSeconds <= 0
    error( ...
        "v2xsimregression:zhuofei2023cochannel:InvalidDuration", ...
        ["V2XSIM_PAPER_SIMULATION_TIME_SECONDS must contain a ", ...
        "positive finite number."]);
end
end

function restoreEnvironment( ...
        originalPath, originalRandomStream, originalRandomState)
path(originalPath);
RandStream.setGlobalStream(originalRandomStream);
originalRandomStream.State = originalRandomState;
end
