classdef RunPublishedCampaignsTest < matlab.unittest.TestCase
    %RUNPUBLISHEDCAMPAIGNSTEST Campaign orchestration contracts.

    properties (SetAccess = private)
        SimulatorRoot (1, 1) string
        OutputDirectory (1, 1) string
    end

    methods (TestMethodSetup)
        function configureCampaign(testCase)
            testCase.SimulatorRoot = getSimulatorRoot();
            temporaryFolder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            testCase.OutputDirectory = string(temporaryFolder.Folder);
        end
    end

    methods (Test)
        function testSeedDiagnosticsAndEnvironmentRestoration(testCase)
            testPath = path;
            testStream = RandStream.getGlobalStream();
            testStreamState = testStream.State;
            testCleanup = onCleanup( ...
                @() restoreTestEnvironment( ...
                    testPath, testStream, testStreamState));

            campaignStream = RandStream("mrg32k3a", Seed=987);
            RandStream.setGlobalStream(campaignStream);
            campaignStreamState = campaignStream.State;
            campaignPath = path;

            results = ...
                v2xsimregression.paper.zhuofei2023cochannel. ...
                runPublishedCampaigns( ...
                    testCase.SimulatorRoot, ...
                    fullfile(testCase.OutputDirectory, "campaign"), ...
                    Methods="only_ITS", ...
                    RandomSeeds=17, ...
                    SimulationTimeSeconds=0.2);

            testCase.verifyTrue( ...
                isequal(RandStream.getGlobalStream(), campaignStream), ...
                "The campaign must reinstall the original global stream.");
            testCase.verifyEqual( ...
                campaignStream.State, campaignStreamState, ...
                "The campaign must restore the original stream state.");
            testCase.verifyEqual( ...
                path, campaignPath, ...
                "The campaign must restore the MATLAB path.");

            campaignDirectory = fullfile( ...
                testCase.OutputDirectory, "campaign");
            testCase.verifyTrue(isfile(fullfile( ...
                campaignDirectory, "campaign-summary.csv")));
            seedSummaryFile = fullfile( ...
                campaignDirectory, "campaign-seed-summary.csv");
            testCase.verifyTrue(isfile(seedSummaryFile));

            seedSummary = readtable( ...
                seedSummaryFile, TextType="string");
            expectedNames = [ ...
                "Method", "Technology", ...
                "DensityVehiclesPerKilometer", ...
                "SidelinkFraction", "ItsG5Fraction", ...
                "PacketIntervalVariationSeconds", "TrafficPattern", ...
                "SimulationSeed", "ScenarioSeed", ...
                "SimulationTimeSeconds", "NormalizedPrrScore", ...
                "RangeAt90Meters", "MeanEndToEndDelaySeconds", ...
                "MeanDataAgeSeconds", "OutputDirectory"];
            testCase.verifyEqual( ...
                string(seedSummary.Properties.VariableNames), ...
                expectedNames);
            testCase.verifyEqual(height(results), 1);
            testCase.verifyEqual(height(seedSummary), 1);
            testCase.verifyEqual(seedSummary.Method, "only_ITS");
            testCase.verifyEqual( ...
                seedSummary.Technology, "IEEE 802.11p");
            testCase.verifyEqual(seedSummary.SimulationSeed, 17);
            testCase.verifyEqual(seedSummary.ScenarioSeed, 17);

            metricNames = [ ...
                "NormalizedPrrScore", "RangeAt90Meters", ...
                "MeanEndToEndDelaySeconds", "MeanDataAgeSeconds"];
            testCase.verifyEqual( ...
                seedSummary{1, metricNames}, ...
                results{1, metricNames}, ...
                AbsTol=1e-14, RelTol=1e-12);
        end

        function testMetricsAreIndependentOfMethodOrder(testCase)
            firstResults = ...
                v2xsimregression.paper.zhuofei2023cochannel. ...
                runPublishedCampaigns( ...
                    testCase.SimulatorRoot, ...
                    fullfile(testCase.OutputDirectory, "first-order"), ...
                    Methods=["only_ITS", "only_NR"], ...
                    RandomSeeds=29, ...
                    SimulationTimeSeconds=0.2);
            secondResults = ...
                v2xsimregression.paper.zhuofei2023cochannel. ...
                runPublishedCampaigns( ...
                    testCase.SimulatorRoot, ...
                    fullfile(testCase.OutputDirectory, "second-order"), ...
                    Methods=["only_NR", "only_ITS"], ...
                    RandomSeeds=29, ...
                    SimulationTimeSeconds=0.2);

            firstResults = sortrows( ...
                firstResults, ["Method", "Technology"]);
            secondResults = sortrows( ...
                secondResults, ["Method", "Technology"]);
            metadataNames = [ ...
                "Method", "Technology", ...
                "DensityVehiclesPerKilometer", ...
                "SidelinkFraction", "ItsG5Fraction", ...
                "PacketIntervalVariationSeconds", "TrafficPattern", ...
                "SeedCount", "SimulationTimeSeconds"];
            testCase.verifyEqual( ...
                firstResults(:, metadataNames), ...
                secondResults(:, metadataNames));

            metricNames = [ ...
                "NormalizedPrrScore", "RangeAt90Meters", ...
                "MeanEndToEndDelaySeconds", "MeanDataAgeSeconds"];
            testCase.verifyEqual( ...
                firstResults{:, metricNames}, ...
                secondResults{:, metricNames}, ...
                AbsTol=1e-14, RelTol=1e-12);
        end
    end
end

function simulatorRoot = getSimulatorRoot()
simulatorRoot = string(getenv("V2XSIM_PAPER_SIMULATOR_ROOT"));
if simulatorRoot == ""
    simulatorRoot = string(fileparts(fileparts(fileparts(fileparts( ...
        fileparts(mfilename("fullpath")))))));
end
end

function restoreTestEnvironment( ...
        originalPath, originalStream, originalStreamState)
path(originalPath);
RandStream.setGlobalStream(originalStream);
originalStream.State = originalStreamState;
end
