function results = runPublishedCampaigns( ...
        simulatorRoot, outputDirectory, options)
%RUNPUBLISHEDCAMPAIGNS Run the Wu et al. 2023 coexistence campaigns.
%   RESULTS contains one aggregated row per technology and configuration.
%   Raw PRR and delay histograms are pooled across deterministic seeds
%   before the metrics are calculated.

arguments (Input)
    simulatorRoot (1, 1) string {mustBeNonzeroLengthText}
    outputDirectory (1, 1) string {mustBeNonzeroLengthText}
    options.Methods (1, :) string = [ ...
        "no_method", "enhanced_A", "method_B", "dynamic_C", ...
        "dynamic_C_preamble", "method_F"]
    options.DensitiesVehiclesPerKilometer (1, :) double ...
        {mustBeReal, mustBeFinite, mustBePositive} = 6
    options.SidelinkFractions (1, :) double ...
        {mustBeReal, mustBeFinite, mustBeNonnegative} = 0.5
    options.PacketIntervalVariationsSeconds (1, :) double ...
        {mustBeReal, mustBeFinite} = 0
    options.RandomSeeds (1, :) double ...
        {mustBeInteger, mustBeNonnegative} = 10:15
    options.SimulationTimeSeconds (1, 1) double ...
        {mustBeReal, mustBeFinite, mustBePositive} = ...
        defaultSimulationTimeSeconds()
end

arguments (Output)
    results table
end

validateCampaignOptions(options);
[simulatorDirectory, fixtureDirectory] = ...
    resolveSimulatorDirectories(simulatorRoot);
validateSimulatorRoot( ...
    simulatorRoot, simulatorDirectory, fixtureDirectory);
prepareOutputDirectory(outputDirectory);

originalPath = path;
randomStream = RandStream.getGlobalStream();
originalRandomState = randomStream.State;
environmentCleanup = onCleanup( ...
    @() restoreEnvironment( ...
        originalPath, randomStream, originalRandomState));

addpath(fullfile(simulatorRoot, "src"));
addpath(simulatorDirectory);

results = createEmptyResults(0);
roadLengthKilometers = 8;
for density = options.DensitiesVehiclesPerKilometer
    vehicleCount = round(density .* roadLengthKilometers);
    for sidelinkFraction = options.SidelinkFractions
        sidelinkVehicleCount = ceil( ...
            vehicleCount .* sidelinkFraction);
        itsG5VehicleCount = vehicleCount - sidelinkVehicleCount;
        for intervalVariation = ...
                options.PacketIntervalVariationsSeconds
            for method = options.Methods
                methodOutputDirectory = campaignOutputDirectory( ...
                    outputDirectory, density, sidelinkFraction, ...
                    intervalVariation, method);
                seedDirectories = runMethodSeeds( ...
                    simulatorDirectory, fixtureDirectory, ...
                    methodOutputDirectory, method, density, ...
                    vehicleCount, sidelinkFraction, ...
                    sidelinkVehicleCount, itsG5VehicleCount, ...
                    intervalVariation, options.RandomSeeds, ...
                    options.SimulationTimeSeconds);

                technologies = technologiesForMethod(method);
                for technology = technologies
                    summary = summarizeTechnology( ...
                        method, technology, density, ...
                        sidelinkFraction, intervalVariation, ...
                        options.RandomSeeds, ...
                        options.SimulationTimeSeconds, ...
                        methodOutputDirectory, seedDirectories);
                    results = [results; summary]; %#ok<AGROW>
                end
            end
        end
    end
end

writetable(results, fullfile(outputDirectory, "campaign-summary.csv"));
end

function validateCampaignOptions(options)
supportedMethods = [ ...
    "only_NR", "only_ITS", "no_method", "enhanced_A", ...
    "method_B", "dynamic_C", "dynamic_C_preamble", "method_F"];
if any(~ismember(options.Methods, supportedMethods))
    unsupportedMethods = options.Methods( ...
        ~ismember(options.Methods, supportedMethods));
    error( ...
        "v2xsimregression:zhuofei2023cochannel:UnsupportedMethod", ...
        "Unsupported method(s): %s.", ...
        join(unsupportedMethods, ", "));
end
if numel(unique(options.Methods)) ~= numel(options.Methods)
    error( ...
        "v2xsimregression:zhuofei2023cochannel:DuplicateMethod", ...
        "Methods must not contain duplicates.");
end
if any(options.SidelinkFractions > 1)
    error( ...
        "v2xsimregression:zhuofei2023cochannel:InvalidFraction", ...
        "SidelinkFractions must be between zero and one.");
end
if isempty(options.Methods) || isempty(options.RandomSeeds)
    error( ...
        "v2xsimregression:zhuofei2023cochannel:EmptyCampaign", ...
        "Methods and RandomSeeds must both be nonempty.");
end
if any(~ismember( ...
        options.PacketIntervalVariationsSeconds, [0, -1]))
    error( ...
        "v2xsimregression:zhuofei2023cochannel:InvalidTraffic", ...
        ["PacketIntervalVariationsSeconds must be 0 for periodic ", ...
        "traffic or -1 for the ETSI CAM rules."]);
end
end

function seedDirectories = runMethodSeeds( ...
        simulatorDirectory, fixtureDirectory, methodOutputDirectory, ...
        method, density, vehicleCount, sidelinkFraction, ...
        sidelinkVehicleCount, itsG5VehicleCount, intervalVariation, ...
        randomSeeds, simulationTimeSeconds)
seedDirectories = strings(numel(randomSeeds), 1);
for seedIndex = 1:numel(randomSeeds)
    randomSeed = randomSeeds(seedIndex);
    seedDirectory = fullfile( ...
        methodOutputDirectory, compose("seed-%d", randomSeed));
    runSimulation( ...
        simulatorDirectory, fixtureDirectory, seedDirectory, ...
        method, density, vehicleCount, sidelinkFraction, ...
        sidelinkVehicleCount, itsG5VehicleCount, ...
        intervalVariation, randomSeed, simulationTimeSeconds);
    seedDirectories(seedIndex) = seedDirectory;
end
end

function runSimulation( ...
        simulatorDirectory, fixtureDirectory, outputDirectory, ...
        method, density, vehicleCount, sidelinkFraction, ...
        sidelinkVehicleCount, itsG5VehicleCount, ...
        intervalVariation, randomSeed, simulationTimeSeconds)
prepareOutputDirectory(outputDirectory);
configurationFile = fullfile( ...
    fixtureDirectory, "cochannel.cfg");

simulationArguments = { ...
    configurationFile, ...
    "simulation.RequiredVersion", "V7", ...
    "simulation.RadioAccessMode", radioAccessMode(method), ...
    "simulation.RandomSeed", randomSeed, ...
    "simulation.DurationSeconds", simulationTimeSeconds, ...
    "scenarioOptions.VehicleCount", vehicleCount, ...
    "application.PacketGeneration.IntervalVariationSeconds", ...
        intervalVariation, ...
    "application.PacketSizeBytes", 350, ...
    "awareness.RangesMeters", [50, 150, 300, 500], ...
    "output.NeighborCount.Enabled", false, ...
    "output.UpdateDelay.Enabled", false, ...
    "output.PacketDelay.Enabled", true, ...
    "output.DataAge.Enabled", true, ...
    "output.PacketReceptionRatio.Enabled", true, ...
    "output.ChannelBusyRatio.Enabled", false, ...
    "simulation.RunLabel", compose( ...
        "density=%g, nr-fraction=%g, traffic=%g, method=%s, seed=%d", ...
        density, sidelinkFraction, intervalVariation, method, ...
        randomSeed), ...
    "output.Directory", outputDirectory};

if ~ismember(method, ["only_NR", "only_ITS"])
    coexistenceArguments = methodConfigurationArguments( ...
        method, sidelinkVehicleCount, itsG5VehicleCount);
    simulationArguments = [ ...
        simulationArguments, coexistenceArguments]; %#ok<NASGU>
end

evalc("WiLabV2Xsim(simulationArguments{:});");
validateSimulationOutputs( ...
    outputDirectory, technologiesForMethod(method));

if ~contains(which("WiLabV2Xsim"), simulatorDirectory)
    error( ...
        "v2xsimregression:zhuofei2023cochannel:WrongSimulator", ...
        "WiLabV2Xsim resolved outside the requested simulator: %s", ...
        which("WiLabV2Xsim"));
end
end

function mode = radioAccessMode(method)
if method == "only_NR"
    mode = "NR-V2X";
elseif method == "only_ITS"
    mode = "80211p";
else
    mode = "COEX-STD-INTERF-5G";
end
end

function methodArguments = methodConfigurationArguments( ...
        method, sidelinkVehicleCount, itsG5VehicleCount)
methodArguments = { ...
    "coexistence.VehiclePattern.SidelinkVehicleCount", ...
        sidelinkVehicleCount, ...
    "coexistence.VehiclePattern.ItsG5VehicleCount", ...
        itsG5VehicleCount};

if method == "no_method"
    settings = {};
elseif method == "enhanced_A"
    settings = { ...
        "coexistence.Method", 'A', ...
        "coexistence.MethodA.EnhancementVariant", 2, ...
        "coexistence.Superframe.DurationSeconds", 0.025, ...
        "coexistence.Superframe.SidelinkPortionEndSeconds", 0.013};
elseif method == "method_B"
    settings = { ...
        "coexistence.Method", 'B', ...
        "coexistence.Superframe.DurationSeconds", 0.025, ...
        "coexistence.Superframe.SidelinkPortionEndSeconds", 0.013};
elseif method == "dynamic_C"
    settings = { ...
        "coexistence.Method", 'C', ...
        "coexistence.Superframe.DurationSeconds", 0.025, ...
        "coexistence.Superframe.SlotAllocationMode", 'dynamic'};
elseif method == "dynamic_C_preamble"
    settings = { ...
        "coexistence.Method", 'C', ...
        "coexistence.Superframe.DurationSeconds", 0.05, ...
        "coexistence.Superframe.SidelinkPortionEndSeconds", 0.05};
elseif method == "method_F"
    settings = { ...
        "coexistence.Method", 'F', ...
        "coexistence.Superframe.DurationSeconds", 0.025, ...
        "coexistence.Superframe.SidelinkPortionEndSeconds", 0.013};
else
    error( ...
        "v2xsimregression:zhuofei2023cochannel:UnsupportedMethod", ...
        "Unsupported coexistence method: %s.", method);
end
methodArguments = [methodArguments, settings];
end

function validateSimulationOutputs(outputDirectory, technologies)
for technology = technologies
    suffix = outputSuffix(technology);
    expectedFiles = [ ...
        "packet_reception_ratio_1_" + suffix + ".csv", ...
        "packet_delay_1_" + suffix + ".csv", ...
        "data_age_1_" + suffix + ".csv"];
    for expectedFile = expectedFiles
        expectedPath = fullfile(outputDirectory, expectedFile);
        if ~isfile(expectedPath)
            error( ...
                "v2xsimregression:zhuofei2023cochannel:MissingOutput", ...
                "The simulator did not create the expected file: %s", ...
                expectedPath);
        end
    end
end
end

function summary = summarizeTechnology( ...
        method, technology, density, sidelinkFraction, ...
        intervalVariation, randomSeeds, simulationTimeSeconds, ...
        methodOutputDirectory, seedDirectories)
suffix = outputSuffix(technology);
prrFiles = fullfile( ...
    seedDirectories, "packet_reception_ratio_1_" + suffix + ".csv");
delayFiles = fullfile( ...
    seedDirectories, "packet_delay_1_" + suffix + ".csv");
dataAgeFiles = fullfile( ...
    seedDirectories, "data_age_1_" + suffix + ".csv");

[normalizedPrrScore, rangeAt90Meters] = summarizePrr(prrFiles);
meanEndToEndDelaySeconds = summarizeHistogram(delayFiles, 6);
meanDataAgeSeconds = summarizeHistogram(dataAgeFiles, 8);
trafficPattern = trafficPatternName(intervalVariation);
seedCount = numel(randomSeeds);
itsG5Fraction = 1 - sidelinkFraction;

summary = table( ...
    method, technology, density, sidelinkFraction, itsG5Fraction, ...
    intervalVariation, trafficPattern, seedCount, ...
    simulationTimeSeconds, normalizedPrrScore, rangeAt90Meters, ...
    meanEndToEndDelaySeconds, meanDataAgeSeconds, ...
    methodOutputDirectory, ...
    VariableNames=[ ...
        "Method", "Technology", "DensityVehiclesPerKilometer", ...
        "SidelinkFraction", "ItsG5Fraction", ...
        "PacketIntervalVariationSeconds", "TrafficPattern", ...
        "SeedCount", "SimulationTimeSeconds", ...
        "NormalizedPrrScore", "RangeAt90Meters", ...
        "MeanEndToEndDelaySeconds", "MeanDataAgeSeconds", ...
        "OutputDirectory"]);
end

function [normalizedPrrScore, rangeAt90Meters] = ...
        summarizePrr(prrFiles)
maximumScoreDistanceMeters = 1500;
distanceBinsMeters = (50:50:maximumScoreDistanceMeters).';
correctPackets = zeros(size(distanceBinsMeters));
totalPackets = zeros(size(distanceBinsMeters));

for prrFile = prrFiles.'
    prrData = readmatrix( ...
        prrFile, FileType="text", Delimiter=",");
    [hasBin, fileRow] = ismember( ...
        distanceBinsMeters, prrData(:, 1));
    correctPackets(hasBin) = correctPackets(hasBin) + ...
        prrData(fileRow(hasBin), 2);
    totalPackets(hasBin) = totalPackets(hasBin) + ...
        prrData(fileRow(hasBin), 5);
end

hasSamples = totalPackets > 0;
sampledDistancesMeters = distanceBinsMeters(hasSamples);
packetReceptionRatios = ...
    correctPackets(hasSamples) ./ totalPackets(hasSamples);
scoredDistancesMeters = [0; sampledDistancesMeters];
scoredPrr = [1; packetReceptionRatios];
normalizedPrrScore = ...
    trapz(scoredDistancesMeters, scoredPrr) ./ ...
    maximumScoreDistanceMeters;
rangeAt90Meters = firstThresholdCrossing( ...
    sampledDistancesMeters, packetReceptionRatios, 0.9);
end

function crossingDistance = firstThresholdCrossing( ...
        distances, values, threshold)
firstBelowThreshold = find(values < threshold, 1);
if isempty(firstBelowThreshold)
    crossingDistance = distances(end);
elseif firstBelowThreshold == 1
    crossingDistance = 0;
else
    leftIndex = firstBelowThreshold - 1;
    rightIndex = firstBelowThreshold;
    crossingDistance = interp1( ...
        values([leftIndex, rightIndex]), ...
        distances([leftIndex, rightIndex]), threshold);
end
end

function meanValue = summarizeHistogram(histogramFiles, lastCountColumn)
weightedSum = 0;
sampleCount = 0;
for histogramFile = histogramFiles.'
    histogramData = readmatrix( ...
        histogramFile, FileType="text", Delimiter=",");
    countColumns = 2:2:min( ...
        lastCountColumn, size(histogramData, 2));
    binCounts = sum(histogramData(:, countColumns), 2);
    isFiniteSample = ...
        isfinite(histogramData(:, 1)) & isfinite(binCounts);
    weightedSum = weightedSum + sum( ...
        histogramData(isFiniteSample, 1) .* ...
        binCounts(isFiniteSample));
    sampleCount = sampleCount + sum(binCounts(isFiniteSample));
end

if sampleCount == 0
    meanValue = NaN;
else
    meanValue = weightedSum ./ sampleCount;
end
end

function results = createEmptyResults(rowCount)
results = table( ...
    Size=[rowCount, 14], ...
    VariableTypes=[ ...
        "string", "string", "double", "double", "double", ...
        "double", "string", "double", "double", "double", ...
        "double", "double", "double", "string"], ...
    VariableNames=[ ...
        "Method", "Technology", "DensityVehiclesPerKilometer", ...
        "SidelinkFraction", "ItsG5Fraction", ...
        "PacketIntervalVariationSeconds", "TrafficPattern", ...
        "SeedCount", "SimulationTimeSeconds", ...
        "NormalizedPrrScore", "RangeAt90Meters", ...
        "MeanEndToEndDelaySeconds", "MeanDataAgeSeconds", ...
        "OutputDirectory"]);
end

function technologies = technologiesForMethod(method)
if method == "only_NR"
    technologies = "NR-V2X";
elseif method == "only_ITS"
    technologies = "IEEE 802.11p";
else
    technologies = ["IEEE 802.11p", "NR-V2X"];
end
end

function suffix = outputSuffix(technology)
if technology == "IEEE 802.11p"
    suffix = "11p";
else
    suffix = "5G";
end
end

function name = trafficPatternName(intervalVariation)
if intervalVariation == 0
    name = "periodic";
else
    name = "ETSI-CAM";
end
end

function outputDirectory = campaignOutputDirectory( ...
        campaignRoot, density, sidelinkFraction, ...
        intervalVariation, method)
outputDirectory = fullfile( ...
    campaignRoot, ...
    compose("density-%g", density), ...
    compose("nr-percent-%d", round(100 .* sidelinkFraction)), ...
    trafficPatternName(intervalVariation), method);
end

function [simulatorDirectory, fixtureDirectory] = ...
        resolveSimulatorDirectories(simulatorRoot)
simulatorDirectory = fullfile(simulatorRoot, "old_src");
fixtureDirectory = fullfile(fileparts(mfilename("fullpath")), "config");
end

function validateSimulatorRoot( ...
        simulatorRoot, simulatorDirectory, fixtureDirectory)
if ~isfolder(simulatorRoot)
    error( ...
        "v2xsimregression:zhuofei2023cochannel:MissingSimulatorRoot", ...
        "SimulatorRoot is not a directory: %s", simulatorRoot);
end
if ~isfile(fullfile(simulatorDirectory, "WiLabV2Xsim.m"))
    error( ...
        "v2xsimregression:zhuofei2023cochannel:MissingSimulator", ...
        "WiLabV2Xsim.m was not found under: %s", ...
        simulatorDirectory);
end
if ~isfile(fullfile(fixtureDirectory, "cochannel.cfg"))
    error( ...
        "v2xsimregression:zhuofei2023cochannel:MissingConfiguration", ...
        "The co-channel regression configuration was not found under: %s", ...
        fixtureDirectory);
end
if ~isfolder(fullfile(simulatorRoot, "src", "+v2xsim"))
    error( ...
        "v2xsimregression:zhuofei2023cochannel:MissingRefactoredSource", ...
        "The simulator root requires src/+v2xsim under: %s", ...
        simulatorRoot);
end
end

function prepareOutputDirectory(outputDirectory)
if isfolder(outputDirectory)
    directoryEntries = dir(outputDirectory);
    isContent = ~ismember({directoryEntries.name}, {".", ".."});
    if any(isContent)
        error( ...
            "v2xsimregression:zhuofei2023cochannel:OutputNotEmpty", ...
            "Refusing to append results in nonempty folder: %s", ...
            outputDirectory);
    end
else
    [wasCreated, message] = mkdir(outputDirectory);
    if ~wasCreated
        error( ...
            "v2xsimregression:zhuofei2023cochannel:OutputCreationFailed", ...
            "Could not create output folder %s: %s", ...
            outputDirectory, message);
    end
end
end

function simulationTimeSeconds = defaultSimulationTimeSeconds()
configuredValue = string(getenv( ...
    "V2XSIM_PAPER_SIMULATION_TIME_SECONDS"));
if configuredValue == ""
    simulationTimeSeconds = 5;
    return
end

simulationTimeSeconds = str2double(configuredValue);
if ~isscalar(simulationTimeSeconds) || ...
        ~isfinite(simulationTimeSeconds) || simulationTimeSeconds <= 0
    error( ...
        "v2xsimregression:zhuofei2023cochannel:InvalidDuration", ...
        ["V2XSIM_PAPER_SIMULATION_TIME_SECONDS must contain a ", ...
        "positive finite number."]);
end
end

function restoreEnvironment( ...
        originalPath, randomStream, originalRandomState)
path(originalPath);
randomStream.State = originalRandomState;
end
