classdef Zhuofei2023CoChannelTest < matlab.unittest.TestCase
    %ZHUOFEI2023COCHANNELTEST Conclusion-level paper regressions.
    %   Reasserts the conclusions behind Figures 10-12 and 15 from
    %   Wu et al. (2023), rather than matching individual plot samples.

    properties (Constant, Access = private)
        MinimumAucImprovement = 0.005
        PrrPreservationTolerance = 0.01
        MinimumRangeImprovementMeters = 100
        MinimumDelayIncreaseSeconds = 0.002
        ComparableDelayToleranceSeconds = 0.002
        TrafficPatternScoreTolerance = 0.025
    end

    properties (SetAccess = private)
        SimulatorRoot (1, 1) string
        OutputDirectory (1, 1) string
    end

    methods (TestClassSetup)
        function configureCampaign(testCase)
            testCase.SimulatorRoot = getSimulatorRoot();
            temporaryFolder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            testCase.OutputDirectory = string(temporaryFolder.Folder);
        end
    end

    methods (Test)
        function testFigures10To12SupportMitigationTradeoffs(testCase)
            methods = [ ...
                "no_method", "enhanced_A", "method_B", ...
                "dynamic_C", "dynamic_C_preamble", "method_F"];
            results = ...
                v2xsimregression.paper.zhuofei2023cochannel. ...
                runPublishedCampaigns( ...
                    testCase.SimulatorRoot, ...
                    fullfile( ...
                        testCase.OutputDirectory, "figures-10-to-12"), ...
                    Methods=methods, ...
                    PacketIntervalVariationsSeconds=0, ...
                    RandomSeeds=10:15);

            noMethod11p = selectRow( ...
                results, "no_method", "IEEE 802.11p", 0);
            noMethodNr = selectRow( ...
                results, "no_method", "NR-V2X", 0);
            enhancedA11p = selectRow( ...
                results, "enhanced_A", "IEEE 802.11p", 0);
            methodB11p = selectRow( ...
                results, "method_B", "IEEE 802.11p", 0);
            dynamicC11p = selectRow( ...
                results, "dynamic_C", "IEEE 802.11p", 0);
            preambleOnlyC11p = selectRow( ...
                results, "dynamic_C_preamble", "IEEE 802.11p", 0);
            methodF11p = selectRow( ...
                results, "method_F", "IEEE 802.11p", 0);

            testCase.verifyGreaterThan( ...
                enhancedA11p.NormalizedPrrScore - ...
                    noMethod11p.NormalizedPrrScore, ...
                testCase.MinimumAucImprovement, ...
                "Enhanced Method A must improve IEEE 802.11p PRR.");
            testCase.verifyGreaterThanOrEqual( ...
                dynamicC11p.NormalizedPrrScore - ...
                    noMethod11p.NormalizedPrrScore, ...
                -testCase.PrrPreservationTolerance, ...
                "Dynamic Method C must preserve IEEE 802.11p PRR.");
            testCase.verifyGreaterThan( ...
                preambleOnlyC11p.NormalizedPrrScore - ...
                    noMethod11p.NormalizedPrrScore, ...
                testCase.MinimumAucImprovement, ...
                "Preamble-only Method C must improve IEEE 802.11p PRR.");

            positiveMethods = [ ...
                "enhanced_A", "dynamic_C", "dynamic_C_preamble"];
            for method = positiveMethods
                methodNr = selectRow(results, method, "NR-V2X", 0);
                testCase.verifyGreaterThanOrEqual( ...
                    methodNr.NormalizedPrrScore - ...
                        noMethodNr.NormalizedPrrScore, ...
                    -testCase.PrrPreservationTolerance, ...
                    compose( ...
                        "%s must not materially reduce NR-V2X PRR.", ...
                        method));
            end

            for method = positiveMethods
                method11p = selectRow( ...
                    results, method, "IEEE 802.11p", 0);
                testCase.verifyGreaterThan( ...
                    method11p.RangeAt90Meters - ...
                        noMethod11p.RangeAt90Meters, ...
                    testCase.MinimumRangeImprovementMeters, ...
                    compose( ...
                        "%s must extend the reliable IEEE 802.11p range.", ...
                        method));
            end

            testCase.verifyLessThan( ...
                methodB11p.NormalizedPrrScore, ...
                noMethod11p.NormalizedPrrScore, ...
                "Method B must retain its IEEE 802.11p range tradeoff.");
            testCase.verifyLessThan( ...
                methodF11p.NormalizedPrrScore, ...
                noMethod11p.NormalizedPrrScore, ...
                "Method F must retain its IEEE 802.11p range tradeoff.");

            testCase.verifyGreaterThan( ...
                enhancedA11p.MeanEndToEndDelaySeconds - ...
                    noMethod11p.MeanEndToEndDelaySeconds, ...
                0.005, ...
                "Method A must expose its IEEE 802.11p delay cost.");
            testCase.verifyGreaterThan( ...
                methodB11p.MeanEndToEndDelaySeconds - ...
                    noMethod11p.MeanEndToEndDelaySeconds, ...
                testCase.MinimumDelayIncreaseSeconds, ...
                "Method B must expose its IEEE 802.11p delay cost.");
            testCase.verifyGreaterThan( ...
                methodF11p.MeanEndToEndDelaySeconds - ...
                    noMethod11p.MeanEndToEndDelaySeconds, ...
                testCase.MinimumDelayIncreaseSeconds, ...
                "Method F must expose its IEEE 802.11p delay cost.");
            testCase.verifyLessThanOrEqual( ...
                abs(dynamicC11p.MeanEndToEndDelaySeconds - ...
                    noMethod11p.MeanEndToEndDelaySeconds), ...
                testCase.ComparableDelayToleranceSeconds, ...
                "Dynamic Method C must preserve IEEE 802.11p delay.");
            testCase.verifyLessThanOrEqual( ...
                abs(preambleOnlyC11p.MeanEndToEndDelaySeconds - ...
                    noMethod11p.MeanEndToEndDelaySeconds), ...
                testCase.ComparableDelayToleranceSeconds, ...
                "Preamble-only Method C must preserve 802.11p delay.");

            nrDelays = results.MeanEndToEndDelaySeconds( ...
                results.Technology == "NR-V2X");
            testCase.verifyLessThanOrEqual( ...
                max(nrDelays) - min(nrDelays), 0.005, ...
                "Mitigation must leave average NR-V2X delay comparable.");
            testCase.verifyLessThanOrEqual( ...
                abs(dynamicC11p.MeanDataAgeSeconds - ...
                    noMethod11p.MeanDataAgeSeconds), ...
                testCase.ComparableDelayToleranceSeconds, ...
                "Dynamic Method C must preserve IEEE 802.11p data age.");
            testCase.verifyLessThanOrEqual( ...
                abs(preambleOnlyC11p.MeanDataAgeSeconds - ...
                    noMethod11p.MeanDataAgeSeconds), ...
                testCase.ComparableDelayToleranceSeconds, ...
                "Preamble-only Method C must preserve 802.11p data age.");
        end

        function testFigure15SupportsTrafficPatternConclusion(testCase)
            methods = [ ...
                "no_method", "enhanced_A", "dynamic_C_preamble"];
            results = ...
                v2xsimregression.paper.zhuofei2023cochannel. ...
                runPublishedCampaigns( ...
                    testCase.SimulatorRoot, ...
                    fullfile(testCase.OutputDirectory, "figure-15"), ...
                    Methods=methods, ...
                    PacketIntervalVariationsSeconds=[0, -1], ...
                    RandomSeeds=10:12);

            for method = methods
                for technology = ["IEEE 802.11p", "NR-V2X"]
                    periodic = selectRow( ...
                        results, method, technology, 0);
                    etsiCam = selectRow( ...
                        results, method, technology, -1);
                    testCase.verifyLessThanOrEqual( ...
                        abs(periodic.NormalizedPrrScore - ...
                            etsiCam.NormalizedPrrScore), ...
                        testCase.TrafficPatternScoreTolerance, ...
                        compose( ...
                            "%s %s PRR must remain comparable for " + ...
                            "periodic and ETSI-CAM traffic.", ...
                            method, technology));
                end
            end

            for intervalVariation = [0, -1]
                noMethod11p = selectRow( ...
                    results, "no_method", ...
                    "IEEE 802.11p", intervalVariation);
                enhancedA11p = selectRow( ...
                    results, "enhanced_A", ...
                    "IEEE 802.11p", intervalVariation);
                preambleOnlyC11p = selectRow( ...
                    results, "dynamic_C_preamble", ...
                    "IEEE 802.11p", intervalVariation);
                testCase.verifyGreaterThan( ...
                    enhancedA11p.NormalizedPrrScore, ...
                    noMethod11p.NormalizedPrrScore, ...
                    "Method A must improve both traffic patterns.");
                testCase.verifyGreaterThanOrEqual( ...
                    preambleOnlyC11p.NormalizedPrrScore - ...
                        noMethod11p.NormalizedPrrScore, ...
                    -testCase.PrrPreservationTolerance, ...
                    "Method C must preserve both traffic patterns.");
            end
        end
    end
end

function simulatorRoot = getSimulatorRoot()
simulatorRoot = string(getenv("V2XSIM_PAPER_SIMULATOR_ROOT"));
if simulatorRoot == ""
    simulatorRoot = string(fileparts(fileparts(fileparts(fileparts( ...
        fileparts(mfilename("fullpath")))))));
end
end

function selectedRow = selectRow( ...
        results, method, technology, intervalVariation)
isSelected = ...
    results.Method == method & ...
    results.Technology == technology & ...
    results.PacketIntervalVariationSeconds == intervalVariation;
selectedRow = results(isSelected, :);
if height(selectedRow) ~= 1
    error( ...
        "v2xsimregression:zhuofei2023cochannel:NonuniqueSelection", ...
        "Expected one campaign row but selected %d.", ...
        height(selectedRow));
end
end
