classdef ChannelBusyRatioRecorder < v2xsim.hook.Hook
    %CHANNELBUSYRATIORECORDER Collect and serialize optional CBR output.
    %   In coexistence modes, cleanup also writes
    %   coex_cv2xOnly_CBRstatistic_<simulation-id>_<technology>.csv when
    %   CV2X-only CBR samples are available. This is a separate two-column
    %   ECDF file, not an additional column in the standard CBR files.

    properties (Constant, Access = protected)
        DependencyTypes = [ ...
            ?v2xsim.hook.dependencies.OutputDirectory, ...
            ?v2xsim.hook.dependencies.SimulationIdentifier]
    end

    properties (SetAccess = immutable)
        MeasurementWindowSeconds (1, 1) double ...
            {mustBeReal, mustBeFinite, mustBePositive} = 0.1
        SimulationDurationSeconds (1, 1) double ...
            {mustBeReal, mustBeFinite, mustBePositive} = 1
        WriteTechnologyOnlyStatistic (1, 1) logical = false
    end

    properties (Access = private)
        OutputDirectory (1, 1) string = ""
        SimulationIdentifier (1, 1) double = NaN
        Samples table = table( ...
            zeros(0, 1), strings(0, 1), zeros(0, 1), ...
            zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
            VariableNames=[ ...
                "WindowIndex", "Technology", "UeId", "Channel", ...
                "Value", "TechnologyOnlyValue"])
    end

    methods
        function obj = ChannelBusyRatioRecorder( ...
                measurementWindowSeconds, simulationDurationSeconds, ...
                options)
            arguments (Input)
                measurementWindowSeconds (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBePositive}
                simulationDurationSeconds (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBePositive}
                options.WriteTechnologyOnlyStatistic (1, 1) logical = false
            end

            obj.MeasurementWindowSeconds = measurementWindowSeconds;
            obj.SimulationDurationSeconds = simulationDurationSeconds;
            obj.WriteTechnologyOnlyStatistic = ...
                options.WriteTechnologyOnlyStatistic;
        end

        function obj = build( ...
                obj, outputDirectory, simulationIdentifier)
            arguments (Input)
                obj (1, 1)
                outputDirectory (1, 1) ...
                    v2xsim.hook.dependencies.OutputDirectory
                simulationIdentifier (1, 1) ...
                    v2xsim.hook.dependencies.SimulationIdentifier
            end

            obj.OutputDirectory = outputDirectory.Path;
            obj.SimulationIdentifier = simulationIdentifier.Value;
        end

        function [obj, invocation] = invoke(obj, invocation)
            arguments (Input)
                obj (1, 1)
                invocation (1, 1) ...
                    v2xsim.hook.invocations. ...
                    AfterChannelBusyRatioSampledInvocation
            end

            sampleCount = numel(invocation.UeIds);
            if sampleCount == 0
                return
            end
            windowIndex = ceil( ...
                invocation.SimulationTimeSeconds ./ ...
                obj.MeasurementWindowSeconds - 1e-9);
            technologyOnlyValues = ...
                invocation.TechnologyOnlyValues;
            if isempty(technologyOnlyValues)
                technologyOnlyValues = -ones(sampleCount, 1);
            end
            newSamples = table( ...
                repmat(windowIndex, sampleCount, 1), ...
                repmat(invocation.Technology, sampleCount, 1), ...
                invocation.UeIds, invocation.Channels, ...
                invocation.Values, technologyOnlyValues, ...
                VariableNames=obj.Samples.Properties.VariableNames);
            obj.Samples = [obj.Samples; newSamples];
        end

        function obj = cleanup(obj)
            if isempty(obj.Samples)
                return
            end

            technologies = unique(obj.Samples.Technology, "stable");
            for technology = technologies.'
                technologySamples = obj.Samples( ...
                    obj.Samples.Technology == technology, :);
                if ceil( ...
                        obj.SimulationDurationSeconds ./ ...
                        obj.MeasurementWindowSeconds) > 10
                    technologySamples = technologySamples( ...
                        technologySamples.WindowIndex > 10, :);
                end
                if isempty(technologySamples)
                    continue
                end
                obj.writeTechnologyStatistics( ...
                    technology, technologySamples);
            end
        end
    end

    methods (Access = private)
        function writeTechnologyStatistics( ...
                obj, technology, samples)
            channels = unique(samples.Channel, "stable");
            multipleChannels = numel(channels) > 1;
            for channel = channels.'
                channelSamples = samples( ...
                    samples.Channel == channel & ...
                    samples.Value >= 0, :);
                if isempty(channelSamples)
                    continue
                end
                suffix = obj.technologySuffix(technology);
                if multipleChannels
                    filename = sprintf( ...
                        "CBRstatistic_%d_%s_C%d.csv", ...
                        obj.SimulationIdentifier, suffix, channel);
                else
                    filename = sprintf( ...
                        "CBRstatistic_%d_%s.csv", ...
                        obj.SimulationIdentifier, suffix);
                end
                obj.writeEcdf( ...
                    fullfile(obj.OutputDirectory, filename), ...
                    channelSamples.Value);
            end

            firstUe = min(samples.UeId);
            genericSamples = sortrows( ...
                samples( ...
                    samples.UeId == firstUe & ...
                    samples.Value >= 0, :), ...
                "WindowIndex");
            if ~isempty(genericSamples)
                filename = sprintf( ...
                    "CBRofGenericVehicle_%d_%s.csv", ...
                    obj.SimulationIdentifier, ...
                    obj.technologySuffix(technology));
                obj.writeGenericVehicle( ...
                    fullfile(obj.OutputDirectory, filename), ...
                    genericSamples);
            end

            technologyOnlyValues = ...
                samples.TechnologyOnlyValue( ...
                    samples.TechnologyOnlyValue >= 0);
            if obj.WriteTechnologyOnlyStatistic && ...
                    technology ~= "11p" && ...
                    ~isempty(technologyOnlyValues)
                filename = sprintf( ...
                    "coex_cv2xOnly_CBRstatistic_%d_%s.csv", ...
                    obj.SimulationIdentifier, ...
                    obj.technologySuffix(technology));
                obj.writeEcdf( ...
                    fullfile(obj.OutputDirectory, filename), ...
                    technologyOnlyValues);
            end
        end

        function writeEcdf(~, filename, values)
            [probabilities, samples] = ecdf(values);
            fileIdentifier = fopen(filename, "w");
            if fileIdentifier == -1
                error( ...
                    "v2xsim:hook:OutputOpenFailed", ...
                    "Could not open CBR output file %s.", filename);
            end
            closeFile = onCleanup(@() fclose(fileIdentifier));
            fprintf( ...
                fileIdentifier, "%f,%f\n", ...
                [samples, probabilities].');
        end

        function writeGenericVehicle( ...
                obj, filename, samples)
            fileIdentifier = fopen(filename, "w");
            if fileIdentifier == -1
                error( ...
                    "v2xsim:hook:OutputOpenFailed", ...
                    "Could not open CBR output file %s.", filename);
            end
            closeFile = onCleanup(@() fclose(fileIdentifier));
            timeSeconds = ...
                samples.WindowIndex .* obj.MeasurementWindowSeconds;
            if ceil( ...
                    obj.SimulationDurationSeconds ./ ...
                    obj.MeasurementWindowSeconds) <= 10
                timeSeconds = timeSeconds + ...
                    10 .* obj.MeasurementWindowSeconds;
            end
            fprintf( ...
                fileIdentifier, "%f,%f\n", ...
                [timeSeconds, samples.Value].');
        end

        function suffix = technologySuffix(~, technology)
            if technology == "11p"
                suffix = "11p";
            else
                suffix = technology;
            end
        end
    end
end
