classdef DataAgeRecorder < v2xsim.hook.Hook
    %DATAAGERECORDER Collect age-of-information histograms.

    properties (Constant, Access = protected)
        DependencyTypes = ...
            ?v2xsim.hook.dependencies.OutputDirectory
    end

    properties (SetAccess = immutable)
        BinWidthSeconds (1, 1) double ...
            {mustBeReal, mustBeFinite, mustBePositive} = 1
        MaximumAgeSeconds (1, 1) double ...
            {mustBeReal, mustBeFinite, mustBePositive} = 10
        ChannelCount (1, 1) double ...
            {mustBeReal, mustBeFinite, mustBeInteger, ...
            mustBePositive} = 1
    end

    properties (Access = private)
        OutputDirectory (1, 1) string = ""
        BinCount (1, 1) double = 1
        Entries (1, :) cell = cell(1, 0)
    end

    methods
        function obj = DataAgeRecorder(binWidthSeconds, options)
            arguments (Input)
                binWidthSeconds (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBePositive}
                options.MaximumAgeSeconds (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBePositive} = 10
                options.ChannelCount (1, 1) double ...
                    {mustBeReal, mustBeFinite, ...
                    mustBeInteger, mustBePositive} = 1
            end

            obj.BinWidthSeconds = binWidthSeconds;
            obj.MaximumAgeSeconds = options.MaximumAgeSeconds;
            obj.ChannelCount = options.ChannelCount;
            obj.BinCount = max( ...
                1, round( ...
                    options.MaximumAgeSeconds ./ binWidthSeconds) + 1);
        end

        function obj = build(obj, outputDirectory)
            arguments (Input)
                obj (1, 1)
                outputDirectory (1, 1) ...
                    v2xsim.hook.dependencies.OutputDirectory
            end

            obj.OutputDirectory = outputDirectory.Path;
        end

        function [obj, invocation] = invoke(obj, invocation)
            arguments (Input)
                obj (1, 1)
                invocation (1, 1) ...
                    v2xsim.hook.invocations. ...
                    AfterPacketFatesDeterminedInvocation
            end

            if isempty(invocation.Transmitters)
                return
            end
            obj.mustAcceptChannels(invocation.Transmitters.Channel);
            [obj, entryIndex] = obj.ensureEntry(invocation);
            entry = obj.Entries{entryIndex};
            entry.Counts = obj.expandCounts( ...
                entry.Counts, ...
                max(invocation.Transmitters.Channel), ...
                max(invocation.Transmitters.PacketType), ...
                numel(invocation.AwarenessRangesMeters));
            entry.PreviousGenerationTimes = obj.expandTimes( ...
                entry.PreviousGenerationTimes, ...
                invocation.MaximumUeId, ...
                numel(invocation.AwarenessRangesMeters));

            outcomes = string(invocation.Links.Outcome);
            for transmitterIndex = 1:height(invocation.Transmitters)
                transmitter = invocation.Transmitters( ...
                    transmitterIndex, :);
                isTransmitterLink = ...
                    invocation.Links.TransmitterId == ...
                    transmitter.TransmitterId;
                transmitterLinks = invocation.Links( ...
                    isTransmitterLink, :);
                transmitterOutcomes = outcomes(isTransmitterLink);
                for rangeIndex = 1:numel( ...
                        invocation.AwarenessRangesMeters)
                    isInRange = ...
                        transmitterLinks.DistanceMeters < ...
                        invocation.AwarenessRangesMeters(rangeIndex);
                    previousTimes = entry.PreviousGenerationTimes( ...
                        transmitter.TransmitterId, :, rangeIndex);
                    nextTimes = -ones(size(previousTimes));
                    inRangeReceiverIds = ...
                        transmitterLinks.ReceiverId(isInRange);
                    nextTimes(inRangeReceiverIds) = ...
                        previousTimes(inRangeReceiverIds);
                    correctReceiverIds = transmitterLinks.ReceiverId( ...
                        isInRange & transmitterOutcomes == "correct");
                    for receiverId = correctReceiverIds.'
                        previousTime = previousTimes(receiverId);
                        if previousTime >= 0
                            ageSeconds = ...
                                invocation.SimulationTimeSeconds - ...
                                previousTime;
                            if ageSeconds < 0
                                error( ...
                                    "v2xsim:hook:outputs:NegativeDataAge", ...
                                    "A stored generation time cannot " + ...
                                    "follow the packet fate time.");
                            end
                            binIndex = obj.ageBin(ageSeconds);
                            entry.Counts( ...
                                transmitter.Channel, ...
                                transmitter.PacketType, ...
                                binIndex, rangeIndex) = ...
                                entry.Counts( ...
                                    transmitter.Channel, ...
                                    transmitter.PacketType, ...
                                    binIndex, rangeIndex) + 1;
                        end
                        nextTimes(receiverId) = ...
                            transmitter.GenerationTimeSeconds;
                    end
                    entry.PreviousGenerationTimes( ...
                        transmitter.TransmitterId, :, rangeIndex) = ...
                        nextTimes;
                end
            end
            obj.Entries{entryIndex} = entry;
        end

        function obj = cleanup(obj)
            for entryIndex = 1:numel(obj.Entries)
                entry = obj.Entries{entryIndex};
                for channel = 1:size(entry.Counts, 1)
                    for packetType = 1:size(entry.Counts, 2)
                        histogram = reshape( ...
                            entry.Counts(channel, packetType, :, :), ...
                            obj.BinCount, ...
                            numel(entry.AwarenessRangesMeters));
                        if sum(histogram, "all") == 0
                            continue
                        end
                        histogram = ...
                            obj.convertCumulativeRangesToBins( ...
                                histogram);
                        filename = obj.outputFilename( ...
                            entry.Technology, channel, packetType);
                        obj.writeHistogram(filename, histogram);
                    end
                end
            end
        end
    end

    methods (Access = private)
        function [obj, entryIndex] = ensureEntry(obj, invocation)
            isTechnology = cellfun( ...
                @(entry) entry.Technology == invocation.Technology, ...
                obj.Entries);
            entryIndex = find(isTechnology, 1);
            if isempty(entryIndex)
                rangeCount = numel(invocation.AwarenessRangesMeters);
                entry = struct( ...
                    Technology=invocation.Technology, ...
                    AwarenessRangesMeters= ...
                        invocation.AwarenessRangesMeters, ...
                    Counts=zeros(0, 0, obj.BinCount, rangeCount), ...
                    PreviousGenerationTimes=-ones( ...
                        invocation.MaximumUeId, ...
                        invocation.MaximumUeId, rangeCount));
                obj.Entries{end + 1} = entry;
                entryIndex = numel(obj.Entries);
                return
            end
            if ~isequal( ...
                    obj.Entries{entryIndex}.AwarenessRangesMeters, ...
                    invocation.AwarenessRangesMeters)
                error( ...
                    "v2xsim:hook:outputs:AwarenessRangesChanged", ...
                    "Awareness ranges cannot change during a simulation.");
            end
        end

        function counts = expandCounts( ...
                obj, counts, channelCount, packetTypeCount, rangeCount)
            if size(counts, 1) >= channelCount && ...
                    size(counts, 2) >= packetTypeCount
                return
            end
            expanded = zeros( ...
                max(size(counts, 1), channelCount), ...
                max(size(counts, 2), packetTypeCount), ...
                obj.BinCount, rangeCount);
            if ~isempty(counts)
                expanded( ...
                    1:size(counts, 1), ...
                    1:size(counts, 2), :, :) = counts;
            end
            counts = expanded;
        end

        function times = expandTimes(~, times, maximumUeId, rangeCount)
            if size(times, 1) >= maximumUeId
                return
            end
            expanded = -ones(maximumUeId, maximumUeId, rangeCount);
            expanded(1:size(times, 1), 1:size(times, 2), :) = times;
            times = expanded;
        end

        function binIndex = ageBin(obj, ageSeconds)
            arguments (Input)
                obj (1, 1)
                ageSeconds (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative}
            end

            maximumRecordedAge = ...
                obj.BinCount .* obj.BinWidthSeconds;
            if all(ageSeconds >= maximumRecordedAge, "all")
                binIndex = obj.BinCount;
            else
                binIndex = max( ...
                    1, ceil(ageSeconds ./ obj.BinWidthSeconds));
            end
        end

        function histogram = convertCumulativeRangesToBins( ...
                ~, histogram)
            for rangeIndex = size(histogram, 2):-1:2
                histogram(:, rangeIndex) = ...
                    histogram(:, rangeIndex) - ...
                    histogram(:, rangeIndex - 1);
            end
        end

        function filename = outputFilename( ...
                obj, technology, channel, packetType)
            packetSuffix = obj.packetTypeSuffix(packetType);
            if obj.ChannelCount == 1
                channelSuffix = "";
            else
                channelSuffix = sprintf("_C%d", channel);
            end
            filename = fullfile( ...
                obj.OutputDirectory, ...
                sprintf( ...
                    "data_age_%s%s%s.csv", ...
                    technology, ...
                    packetSuffix, channelSuffix));
        end

        function suffix = packetTypeSuffix(~, packetType)
            if packetType == 1
                suffix = "";
            elseif packetType == 2
                suffix = "_DENM";
            else
                error( ...
                    "v2xsim:hook:outputs:UnsupportedPacketType", ...
                    "Packet type %d is not supported.", packetType);
            end
        end

        function writeHistogram(obj, filename, histogram)
            fileIdentifier = fopen(filename, "a");
            if fileIdentifier == -1
                error( ...
                    "v2xsim:hook:OutputOpenFailed", ...
                    "Could not open data-age output file %s.", filename);
            end
            closeFile = onCleanup(@() fclose(fileIdentifier));
            totals = sum(histogram, 1);
            rangeCount = size(histogram, 2);
            for binIndex = 1:obj.BinCount
                fprintf( ...
                    fileIdentifier, "%.3f,", ...
                    binIndex .* obj.BinWidthSeconds);
                for rangeIndex = 1:rangeCount
                    cumulativeProbability = ...
                        sum(histogram(1:binIndex, rangeIndex)) ./ ...
                        totals(rangeIndex);
                    fprintf( ...
                        fileIdentifier, "%d,%.6f", ...
                        histogram(binIndex, rangeIndex), ...
                        cumulativeProbability);
                    if rangeCount == 1
                        fprintf(fileIdentifier, "\n");
                    else
                        fprintf(fileIdentifier, ",");
                    end
                end
                if rangeCount > 1
                    fprintf( ...
                        fileIdentifier, "%d,%.6f\n", ...
                        sum(histogram(binIndex, :)), ...
                        sum(histogram(1:binIndex, :), "all") ./ ...
                        sum(totals));
                end
            end
        end

        function mustAcceptChannels(obj, channels)
            if any(channels > obj.ChannelCount)
                error( ...
                    "v2xsim:hook:outputs:ChannelOutOfRange", ...
                    "Invocation channel exceeds configured channel count.");
            end
        end
    end
end
