classdef InterferenceEvidenceRecorder < v2xsim.hook.Hook
    %INTERFERENCEEVIDENCERECORDER Stream causal terminal-error evidence.
    %   Register this hook at both AfterPacketFatesDetermined and
    %   AfterInterferenceEvidenceDetermined. Observing the packet-fate
    %   stream first makes PacketSequence identical to the packet trace,
    %   including blocked-packet transitions. GenerationTimeSeconds and
    %   AttemptNumber remain in both artifacts as the authoritative
    %   fallback identity.

    properties (Constant, Access = protected)
        DependencyTypes = ...
            ?v2xsim.hook.dependencies.OutputDirectory
    end

    properties (SetAccess = immutable)
        FlushRowCount (1,1) double ...
            {mustBeReal,mustBeFinite,mustBeInteger,mustBePositive} = 10000
    end

    properties (Access = private)
        OutputDirectory (1,1) string = ""
        AttemptBuffer table = table()
        CounterfactualBuffer table = table()
        SequenceState table = table()
        AttemptChunkFiles (:,1) string = strings(0,1)
        CounterfactualChunkFiles (:,1) string = strings(0,1)
        NextAttemptChunkIndex (1,1) double = 1
        NextCounterfactualChunkIndex (1,1) double = 1
    end

    methods
        function obj = InterferenceEvidenceRecorder(options)
            arguments (Input)
                options.FlushRowCount (1,1) double ...
                    {mustBeReal,mustBeFinite, ...
                    mustBeInteger,mustBePositive} = 10000
            end

            obj.FlushRowCount = options.FlushRowCount;
            obj.AttemptBuffer = ...
                v2xsim.analysis.emptyInterferenceAttemptTrace();
            obj.CounterfactualBuffer = ...
                v2xsim.analysis. ...
                emptyInterferenceCounterfactualTrace();
            obj.SequenceState = table( ...
                strings(0,1),zeros(0,1),zeros(0,1), ...
                VariableNames=[ ...
                    "TransmitterKey","GenerationTimeSeconds", ...
                    "PacketSequence"]);
        end

        function obj = build(obj,outputDirectory)
            arguments (Input)
                obj (1,1)
                outputDirectory (1,1) ...
                    v2xsim.hook.dependencies.OutputDirectory
            end

            obj.OutputDirectory = outputDirectory.Path;
        end

        function [obj,invocation] = invoke(obj,invocation)
            arguments (Input)
                obj (1,1)
                invocation (1,1) ...
                    v2xsim.hook.invocation.Invocation
            end

            if isa( ...
                    invocation, ...
                    "v2xsim.hook.invocations." + ...
                    "AfterPacketFatesDeterminedInvocation")
                obj = obj.observePacketFates(invocation);
            elseif isa( ...
                    invocation, ...
                    "v2xsim.hook.invocations." + ...
                    "AfterInterferenceEvidenceDeterminedInvocation")
                obj = obj.recordEvidence(invocation);
            else
                error( ...
                    "v2xsim:hook:outputs:" + ...
                    "InvalidInterferenceEvidenceInvocation", ...
                    "InterferenceEvidenceRecorder received %s.", ...
                    class(invocation));
            end
        end

        function obj = cleanup(obj)
            obj = obj.flushCompleteChunks();
            if ~isempty(obj.AttemptBuffer)
                [obj,~] = obj.writeChunk( ...
                    "attempt",obj.AttemptBuffer);
                obj.AttemptBuffer(:,:) = [];
            end
            if ~isempty(obj.CounterfactualBuffer)
                [obj,~] = obj.writeChunk( ...
                    "counterfactual", ...
                    obj.CounterfactualBuffer);
                obj.CounterfactualBuffer(:,:) = [];
            end
        end

        function rows = terminalAttempts(obj)
            arguments (Input)
                obj (1,1)
            end
            arguments (Output)
                rows table
            end

            rows = v2xsim.analysis.emptyInterferenceAttemptTrace();
            for filename = obj.AttemptChunkFiles.'
                chunk = readtable(filename,TextType="string");
                chunk = obj.coerceAttemptTypes(chunk);
                rows = [rows;chunk]; %#ok<AGROW>
            end
            rows = [rows;obj.AttemptBuffer];
        end

        function rows = counterfactuals(obj)
            arguments (Input)
                obj (1,1)
            end
            arguments (Output)
                rows table
            end

            rows = ...
                v2xsim.analysis.emptyInterferenceCounterfactualTrace();
            for filename = obj.CounterfactualChunkFiles.'
                chunk = readtable(filename,TextType="string");
                chunk = obj.coerceCounterfactualTypes(chunk);
                rows = [rows;chunk]; %#ok<AGROW>
            end
            rows = [rows;obj.CounterfactualBuffer];
        end
    end

    methods (Access = private)
        function obj = observePacketFates(obj,invocation)
            if isempty(invocation.Links)
                return
            end
            transmitters = invocation.Transmitters;
            ueIds = obj.packetTransmitterUeIds(transmitters);
            for transmitterIndex = 1:height(transmitters)
                providedSequence = obj.optionalValue( ...
                    transmitters,"PacketSequence", ...
                    transmitterIndex,nan);
                [obj,~] = obj.sequenceForPacket( ...
                    invocation.Technology, ...
                    ueIds(transmitterIndex), ...
                    transmitters.GenerationTimeSeconds( ...
                        transmitterIndex), ...
                    providedSequence);
            end
        end

        function obj = recordEvidence(obj,invocation)
            if isempty(invocation.TerminalAttempts)
                return
            end

            transmitters = invocation.Transmitters;
            transmitterCount = height(transmitters);
            packetSequences = zeros(transmitterCount,1);
            sequenceAligned = false(transmitterCount,1);
            for transmitterIndex = 1:transmitterCount
                [obj,packetSequences(transmitterIndex), ...
                    sequenceAligned(transmitterIndex)] = ...
                    obj.sequenceForEvidence( ...
                        invocation.Technology, ...
                        transmitters.TransmitterUeId( ...
                            transmitterIndex), ...
                        transmitters.GenerationTimeSeconds( ...
                            transmitterIndex));
            end

            rawAttempts = invocation.TerminalAttempts;
            [knownTransmitters,transmitterRows] = ismember( ...
                rawAttempts.TransmitterId, ...
                transmitters.TransmitterId);
            if ~all(knownTransmitters)
                error( ...
                    "v2xsim:hook:outputs:" + ...
                    "UnknownInterferenceTransmitter", ...
                    "Every terminal attempt must identify a " + ...
                    "transmitter row.");
            end
            attemptCount = height(rawAttempts);
            attempts = table( ...
                repmat( ...
                    invocation.SimulationTimeSeconds, ...
                    attemptCount,1), ...
                repmat(invocation.Technology,attemptCount,1), ...
                rawAttempts.TransmitterId, ...
                transmitters.TransmitterUeId(transmitterRows), ...
                rawAttempts.ReceiverId, ...
                invocation.UeIds(rawAttempts.ReceiverId), ...
                packetSequences(transmitterRows), ...
                sequenceAligned(transmitterRows), ...
                transmitters.GenerationTimeSeconds( ...
                    transmitterRows), ...
                transmitters.AttemptNumber(transmitterRows), ...
                transmitters.ResourceId(transmitterRows), ...
                transmitters.FrequencyResourceId(transmitterRows), ...
                transmitters.AllocationEpoch(transmitterRows), ...
                rawAttempts.Outcome, ...
                rawAttempts.ObservedSinrDb, ...
                rawAttempts.DecodeThresholdDb, ...
                rawAttempts.SinrWithoutAllInterferersDb, ...
                rawAttempts.InterfererCount, ...
                rawAttempts.EvidenceIsExhaustive, ...
                VariableNames=string( ...
                    v2xsim.analysis. ...
                    emptyInterferenceAttemptTrace(). ...
                    Properties.VariableNames));

            rawCounterfactuals = invocation.Counterfactuals;
            counterfactuals = ...
                v2xsim.analysis. ...
                emptyInterferenceCounterfactualTrace();
            if ~isempty(rawCounterfactuals)
                [knownTerminal,terminalRows] = ismember( ...
                    rawCounterfactuals{:, ...
                        ["TransmitterId","ReceiverId"]}, ...
                    rawAttempts{:, ...
                        ["TransmitterId","ReceiverId"]},"rows");
                if ~all(knownTerminal)
                    error( ...
                        "v2xsim:hook:outputs:" + ...
                        "OrphanInterferenceCounterfactual", ...
                        "Every counterfactual must identify a " + ...
                        "terminal attempt.");
                end
                counterTransmitterRows = ...
                    transmitterRows(terminalRows);
                counterCount = height(rawCounterfactuals);
                transmitterUeIds = ...
                    transmitters.TransmitterUeId( ...
                        counterTransmitterRows);
                interfererUeIds = invocation.UeIds( ...
                    rawCounterfactuals.InterfererId);
                canonicalPairs = sort( ...
                    [transmitterUeIds,interfererUeIds],2);
                counterfactuals = table( ...
                    repmat( ...
                        invocation.SimulationTimeSeconds, ...
                        counterCount,1), ...
                    repmat( ...
                        invocation.Technology,counterCount,1), ...
                    rawCounterfactuals.TransmitterId, ...
                    transmitterUeIds, ...
                    rawCounterfactuals.ReceiverId, ...
                    invocation.UeIds( ...
                        rawCounterfactuals.ReceiverId), ...
                    packetSequences(counterTransmitterRows), ...
                    sequenceAligned(counterTransmitterRows), ...
                    transmitters.GenerationTimeSeconds( ...
                        counterTransmitterRows), ...
                    transmitters.AttemptNumber( ...
                        counterTransmitterRows), ...
                    transmitters.ResourceId( ...
                        counterTransmitterRows), ...
                    transmitters.FrequencyResourceId( ...
                        counterTransmitterRows), ...
                    transmitters.AllocationEpoch( ...
                        counterTransmitterRows), ...
                    rawCounterfactuals.InterfererId, ...
                    interfererUeIds, ...
                    canonicalPairs(:,1),canonicalPairs(:,2), ...
                    rawCounterfactuals.InterfererResourceId, ...
                    rawCounterfactuals. ...
                        InterfererFrequencyResourceId, ...
                    rawCounterfactuals.ResourceRelation, ...
                    rawCounterfactuals.RemovedInterferencePower, ...
                    rawAttempts.ObservedSinrDb(terminalRows), ...
                    rawAttempts.DecodeThresholdDb(terminalRows), ...
                    rawCounterfactuals. ...
                        SinrWithoutInterfererDb, ...
                    rawAttempts. ...
                        SinrWithoutAllInterferersDb(terminalRows), ...
                    rawAttempts.EvidenceIsExhaustive(terminalRows), ...
                    VariableNames=string( ...
                        v2xsim.analysis. ...
                        emptyInterferenceCounterfactualTrace(). ...
                        Properties.VariableNames));
            end

            obj.AttemptBuffer = [obj.AttemptBuffer;attempts];
            obj.CounterfactualBuffer = [ ...
                obj.CounterfactualBuffer;counterfactuals];
            obj = obj.flushCompleteChunks();
        end

        function [obj,sequence,isAligned] = ...
                sequenceForEvidence( ...
                    obj,technology,transmitterUeId,generationTime)
            key = technology + "|" + transmitterUeId;
            stateRow = find( ...
                obj.SequenceState.TransmitterKey == key,1);
            if ~isempty(stateRow) && ...
                    obj.SequenceState.GenerationTimeSeconds( ...
                        stateRow) == generationTime
                sequence = ...
                    obj.SequenceState.PacketSequence(stateRow);
                isAligned = true;
                return
            end
            if ~isempty(stateRow)
                error( ...
                    "v2xsim:hook:outputs:" + ...
                    "UnalignedInterferencePacketSequence", ...
                    "No packet-fate observation matches generation " + ...
                    "%.9g for %s/%s.", ...
                    generationTime,technology,transmitterUeId);
            end
            [obj,sequence] = obj.sequenceForPacket( ...
                technology,transmitterUeId,generationTime,nan);
            isAligned = false;
        end

        function [obj,sequence] = sequenceForPacket( ...
                obj,technology,transmitterUeId,generationTime, ...
                providedSequence)
            key = technology + "|" + transmitterUeId;
            stateRow = find( ...
                obj.SequenceState.TransmitterKey == key,1);
            if ~isnan(providedSequence)
                sequence = providedSequence;
                if isempty(stateRow)
                    obj.SequenceState(end + 1,:) = { ...
                        key,generationTime,sequence};
                else
                    previousSequence = ...
                        obj.SequenceState.PacketSequence(stateRow);
                    previousGenerationTime = ...
                        obj.SequenceState.GenerationTimeSeconds( ...
                            stateRow);
                    if sequence < previousSequence || ...
                            (sequence == previousSequence && ...
                            generationTime ~= previousGenerationTime)
                        error( ...
                            "v2xsim:hook:outputs:" + ...
                            "InvalidPacketSequence", ...
                            "Explicit packet sequences must increase " + ...
                            "when generation time changes.");
                    end
                    obj.SequenceState.GenerationTimeSeconds( ...
                        stateRow) = generationTime;
                    obj.SequenceState.PacketSequence(stateRow) = ...
                        sequence;
                end
                return
            end

            if isempty(stateRow)
                sequence = 1;
                obj.SequenceState(end + 1,:) = { ...
                    key,generationTime,sequence};
            elseif obj.SequenceState.GenerationTimeSeconds( ...
                    stateRow) == generationTime
                sequence = ...
                    obj.SequenceState.PacketSequence(stateRow);
            else
                sequence = ...
                    obj.SequenceState.PacketSequence(stateRow) + 1;
                obj.SequenceState.GenerationTimeSeconds( ...
                    stateRow) = generationTime;
                obj.SequenceState.PacketSequence(stateRow) = ...
                    sequence;
            end
        end

        function values = packetTransmitterUeIds( ...
                ~,transmitters)
            if ismember( ...
                    "TransmitterUeId", ...
                    string(transmitters.Properties.VariableNames))
                values = string(transmitters.TransmitterUeId);
            else
                values = "UE" + ...
                    string(transmitters.TransmitterId);
            end
            values = values(:);
        end

        function values = optionalColumn( ...
                ~,source,variableName,defaultValue)
            if ismember( ...
                    variableName, ...
                    string(source.Properties.VariableNames))
                values = double(source.(variableName));
            else
                values = repmat(defaultValue,height(source),1);
            end
            values = values(:);
        end

        function value = optionalValue( ...
                obj,source,variableName,row,defaultValue)
            values = obj.optionalColumn( ...
                source,variableName,defaultValue);
            value = values(row);
        end

        function obj = flushCompleteChunks(obj)
            while height(obj.AttemptBuffer) >= obj.FlushRowCount
                chunk = obj.AttemptBuffer( ...
                    1:obj.FlushRowCount,:);
                [obj,~] = obj.writeChunk("attempt",chunk);
                obj.AttemptBuffer(1:obj.FlushRowCount,:) = [];
            end
            while height(obj.CounterfactualBuffer) >= ...
                    obj.FlushRowCount
                chunk = obj.CounterfactualBuffer( ...
                    1:obj.FlushRowCount,:);
                [obj,~] = obj.writeChunk( ...
                    "counterfactual",chunk);
                obj.CounterfactualBuffer( ...
                    1:obj.FlushRowCount,:) = [];
            end
        end

        function [obj,filename] = writeChunk(obj,kind,rows)
            if strlength(obj.OutputDirectory) == 0
                error( ...
                    "v2xsim:hook:outputs:" + ...
                    "InterferenceEvidenceRecorderNotBuilt", ...
                    "InterferenceEvidenceRecorder must be built " + ...
                    "before it flushes rows.");
            end
            if kind == "attempt"
                filename = fullfile( ...
                    obj.OutputDirectory,sprintf( ...
                        "interference_attempts_%06d.csv", ...
                        obj.NextAttemptChunkIndex));
                obj.AttemptChunkFiles(end + 1,1) = filename;
                obj.NextAttemptChunkIndex = ...
                    obj.NextAttemptChunkIndex + 1;
            else
                filename = fullfile( ...
                    obj.OutputDirectory,sprintf( ...
                        "interference_counterfactuals_%06d.csv", ...
                        obj.NextCounterfactualChunkIndex));
                obj.CounterfactualChunkFiles(end + 1,1) = filename;
                obj.NextCounterfactualChunkIndex = ...
                    obj.NextCounterfactualChunkIndex + 1;
            end
            try
                writetable(rows,filename);
            catch cause
                error( ...
                    "v2xsim:hook:OutputOpenFailed", ...
                    "Could not write interference evidence %s: %s", ...
                    filename,cause.message);
            end
        end

        function rows = coerceAttemptTypes(~,rows)
            rows = coerceTypes( ...
                rows, ...
                v2xsim.analysis.emptyInterferenceAttemptTrace(), ...
                ["Technology","TransmitterUeId", ...
                "ReceiverUeId","Outcome"], ...
                ["PacketSequenceAligned","EvidenceIsExhaustive"]);
        end

        function rows = coerceCounterfactualTypes(~,rows)
            rows = coerceTypes( ...
                rows, ...
                v2xsim.analysis. ...
                    emptyInterferenceCounterfactualTrace(), ...
                ["Technology","TransmitterUeId","ReceiverUeId", ...
                "InterfererUeId","ReusePairFirstUeId", ...
                "ReusePairSecondUeId","ResourceRelation"], ...
                ["PacketSequenceAligned","EvidenceIsExhaustive"]);
        end
    end
end

function rows = coerceTypes( ...
        rows,expected,stringNames,logicalNames)
expectedNames = string(expected.Properties.VariableNames);
if ~isequal( ...
        string(rows.Properties.VariableNames),expectedNames)
    error( ...
        "v2xsim:hook:outputs:InvalidInterferenceEvidenceTrace", ...
        "An interference-evidence chunk has an invalid schema.");
end
for variableName = stringNames
    rows.(variableName) = string(rows.(variableName));
end
for variableName = logicalNames
    rows.(variableName) = logical(rows.(variableName));
end
end
