classdef NeighborCountRecorder < v2xsim.hook.Hook
    %NEIGHBORCOUNTRECORDER Stream per-range neighbor summaries.

    properties (Constant, Access = protected)
        DependencyTypes = [ ...
            ?v2xsim.hook.dependencies.OutputDirectory, ...
            ?v2xsim.hook.dependencies.SimulationIdentifier]
    end

    properties (Access = private)
        OutputDirectory (1, 1) string = ""
        SimulationIdentifier (1, 1) double = NaN
    end

    methods
        function obj = build( ...
                obj, outputDirectory, simulationIdentifier)
            arguments (Input)
                obj (1, 1)
                outputDirectory (1, 1) ...
                    v2xsim.hook.dependencies.OutputDirectory
                simulationIdentifier (1, 1) ...
                    v2xsim.hook.dependencies.SimulationIdentifier
            end

            obj.OutputDirectory = outputDirectory.Path;
            obj.SimulationIdentifier = simulationIdentifier.Value;
        end

        function [obj, invocation] = invoke(obj, invocation)
            arguments (Input)
                obj (1, 1)
                invocation (1, 1) ...
                    v2xsim.hook.invocations. ...
                    AfterNeighborGraphUpdatedInvocation
            end

            filename = fullfile( ...
                obj.OutputDirectory, ...
                sprintf( ...
                    "neighbors_%d.csv", ...
                    obj.SimulationIdentifier));
            fileIdentifier = fopen(filename, "a");
            if fileIdentifier == -1
                error( ...
                    "v2xsim:hook:OutputOpenFailed", ...
                    "Could not open neighbor-count output file %s.", ...
                    filename);
            end
            closeFile = onCleanup(@() fclose(fileIdentifier));

            fprintf( ...
                fileIdentifier, "%f,", ...
                invocation.SimulationTimeSeconds);
            ueCount = numel(invocation.UeIds);
            for rangeIndex = 1:numel( ...
                    invocation.AwarenessRangesMeters)
                upperBound = ...
                    invocation.AwarenessRangesMeters(rangeIndex);
                if rangeIndex == 1
                    isInBin = ...
                        invocation.DistanceMatrixMeters < upperBound;
                else
                    lowerBound = ...
                        invocation.AwarenessRangesMeters(rangeIndex - 1);
                    isInBin = ...
                        invocation.DistanceMatrixMeters >= lowerBound & ...
                        invocation.DistanceMatrixMeters < upperBound;
                end
                isInBin(1:ueCount + 1:end) = false;
                averageTotalNeighbors = nnz(isInBin) ./ ueCount;
                fprintf( ...
                    fileIdentifier, "%d,%d,%d", ...
                    invocation.AverageCv2xNeighbors(rangeIndex), ...
                    invocation.AverageItsG5Neighbors(rangeIndex), ...
                    averageTotalNeighbors);
                if rangeIndex < numel( ...
                        invocation.AwarenessRangesMeters)
                    fprintf(fileIdentifier, ",");
                else
                    fprintf(fileIdentifier, "\n");
                end
            end
        end
    end
end
