classdef PacketDelayRecorder < v2xsim.hook.Hook
    %PACKETDELAYRECORDER Collect and serialize packet-delay histograms.

    properties (Constant, Access = protected)
        DependencyTypes = ...
            ?v2xsim.hook.dependencies.OutputDirectory
    end

    properties (SetAccess = immutable)
        BinWidthSeconds (1, 1) double ...
            {mustBeReal, mustBeFinite, mustBePositive} = 1
        AllocationPeriodSeconds (1, 1) double ...
            {mustBeReal, mustBeFinite, mustBePositive} = 1
        ChannelCount (1, 1) double ...
            {mustBeReal, mustBeFinite, mustBeInteger, ...
            mustBePositive} = 1
    end

    properties (Access = private)
        OutputDirectory (1, 1) string = ""
        BinCount (1, 1) double = 1
        Entries (1, :) cell = cell(1, 0)
    end

    methods
        function obj = PacketDelayRecorder( ...
                binWidthSeconds, allocationPeriodSeconds, options)
            arguments (Input)
                binWidthSeconds (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBePositive}
                allocationPeriodSeconds (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBePositive}
                options.ChannelCount (1, 1) double ...
                    {mustBeReal, mustBeFinite, ...
                    mustBeInteger, mustBePositive} = 1
            end

            obj.BinWidthSeconds = binWidthSeconds;
            obj.AllocationPeriodSeconds = allocationPeriodSeconds;
            obj.ChannelCount = options.ChannelCount;
            obj.BinCount = max( ...
                1, round( ...
                    2 .* allocationPeriodSeconds ./ binWidthSeconds));
        end

        function obj = build(obj, outputDirectory)
            arguments (Input)
                obj (1, 1)
                outputDirectory (1, 1) ...
                    v2xsim.hook.dependencies.OutputDirectory
            end

            obj.OutputDirectory = outputDirectory.Path;
        end

        function [obj, invocation] = invoke(obj, invocation)
            arguments (Input)
                obj (1, 1)
                invocation (1, 1) ...
                    v2xsim.hook.invocations. ...
                    AfterPacketFatesDeterminedInvocation
            end

            if isempty(invocation.Transmitters)
                return
            end
            obj.mustAcceptChannels(invocation.Transmitters.Channel);
            [obj, entryIndex] = obj.ensureEntry( ...
                invocation.Technology, ...
                invocation.AwarenessRangesMeters);
            entry = obj.Entries{entryIndex};
            entry.Counts = obj.expandCounts( ...
                entry.Counts, ...
                max(invocation.Transmitters.Channel), ...
                max(invocation.Transmitters.PacketType), ...
                numel(invocation.AwarenessRangesMeters));

            outcomes = string(invocation.Links.Outcome);
            for transmitterIndex = 1:height(invocation.Transmitters)
                transmitter = invocation.Transmitters( ...
                    transmitterIndex, :);
                delaySeconds = ...
                    invocation.SimulationTimeSeconds - ...
                    transmitter.GenerationTimeSeconds;
                if delaySeconds < 0
                    error( ...
                        "v2xsim:hook:outputs:NegativePacketDelay", ...
                        "Packet generation time cannot follow fate time.");
                end
                binIndex = obj.delayBin(delaySeconds);
                isTransmitterLink = ...
                    invocation.Links.TransmitterId == ...
                    transmitter.TransmitterId;
                for rangeIndex = 1:numel( ...
                        invocation.AwarenessRangesMeters)
                    correctCount = nnz( ...
                        isTransmitterLink & ...
                        outcomes == "correct" & ...
                        invocation.Links.DistanceMeters < ...
                        invocation.AwarenessRangesMeters(rangeIndex));
                    entry.Counts( ...
                        transmitter.Channel, ...
                        transmitter.PacketType, ...
                        binIndex, rangeIndex) = ...
                        entry.Counts( ...
                            transmitter.Channel, ...
                            transmitter.PacketType, ...
                            binIndex, rangeIndex) + ...
                        correctCount;
                end
            end
            obj.Entries{entryIndex} = entry;
        end

        function obj = cleanup(obj)
            for entryIndex = 1:numel(obj.Entries)
                entry = obj.Entries{entryIndex};
                for channel = 1:size(entry.Counts, 1)
                    for packetType = 1:size(entry.Counts, 2)
                        histogram = reshape( ...
                            entry.Counts(channel, packetType, :, :), ...
                            obj.BinCount, ...
                            numel(entry.AwarenessRangesMeters));
                        if sum(histogram, "all") == 0
                            continue
                        end
                        histogram = ...
                            obj.convertCumulativeRangesToBins( ...
                                histogram);
                        filename = obj.outputFilename( ...
                            "packet_delay", entry.Technology, ...
                            channel, packetType);
                        obj.writeHistogram(filename, histogram);
                    end
                end
            end
        end
    end

    methods (Access = private)
        function [obj, entryIndex] = ensureEntry( ...
                obj, technology, awarenessRangesMeters)
            isTechnology = cellfun( ...
                @(entry) entry.Technology == technology, ...
                obj.Entries);
            entryIndex = find(isTechnology, 1);
            if isempty(entryIndex)
                entry = struct( ...
                    Technology=technology, ...
                    AwarenessRangesMeters=awarenessRangesMeters, ...
                    Counts=zeros( ...
                        0, 0, obj.BinCount, ...
                        numel(awarenessRangesMeters)));
                obj.Entries{end + 1} = entry;
                entryIndex = numel(obj.Entries);
                return
            end

            if ~isequal( ...
                    obj.Entries{entryIndex}.AwarenessRangesMeters, ...
                    awarenessRangesMeters)
                error( ...
                    "v2xsim:hook:outputs:AwarenessRangesChanged", ...
                    "Awareness ranges cannot change during a simulation.");
            end
        end

        function counts = expandCounts( ...
                obj, counts, channelCount, packetTypeCount, rangeCount)
            if size(counts, 1) >= channelCount && ...
                    size(counts, 2) >= packetTypeCount
                return
            end
            expanded = zeros( ...
                max(size(counts, 1), channelCount), ...
                max(size(counts, 2), packetTypeCount), ...
                obj.BinCount, rangeCount);
            if ~isempty(counts)
                expanded( ...
                    1:size(counts, 1), ...
                    1:size(counts, 2), :, :) = counts;
            end
            counts = expanded;
        end

        function binIndex = delayBin(obj, delaySeconds)
            arguments (Input)
                obj (1, 1)
                delaySeconds (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative}
            end

            maximumRecordedDelay = ...
                obj.BinCount .* obj.BinWidthSeconds;
            if all(delaySeconds >= maximumRecordedDelay, "all")
                binIndex = obj.BinCount;
            else
                binIndex = max( ...
                    1, ceil(delaySeconds ./ obj.BinWidthSeconds));
            end
        end

        function histogram = convertCumulativeRangesToBins( ...
                ~, histogram)
            for rangeIndex = size(histogram, 2):-1:2
                histogram(:, rangeIndex) = ...
                    histogram(:, rangeIndex) - ...
                    histogram(:, rangeIndex - 1);
            end
        end

        function filename = outputFilename( ...
                obj, prefix, technology, channel, packetType)
            packetSuffix = obj.packetTypeSuffix(packetType);
            if obj.ChannelCount == 1
                channelSuffix = "";
            else
                channelSuffix = sprintf("_C%d", channel);
            end
            filename = fullfile( ...
                obj.OutputDirectory, ...
                sprintf( ...
                    "%s_%s%s%s.csv", ...
                    prefix,technology, ...
                    packetSuffix, channelSuffix));
        end

        function suffix = packetTypeSuffix(~, packetType)
            if packetType == 1
                suffix = "";
            elseif packetType == 2
                suffix = "_DENM";
            else
                error( ...
                    "v2xsim:hook:outputs:UnsupportedPacketType", ...
                    "Packet type %d is not supported.", packetType);
            end
        end

        function writeHistogram(obj, filename, histogram)
            fileIdentifier = fopen(filename, "a");
            if fileIdentifier == -1
                error( ...
                    "v2xsim:hook:OutputOpenFailed", ...
                    "Could not open packet-delay output file %s.", ...
                    filename);
            end
            closeFile = onCleanup(@() fclose(fileIdentifier));
            totals = sum(histogram, 1);
            rangeCount = size(histogram, 2);
            for binIndex = 1:obj.BinCount
                fprintf( ...
                    fileIdentifier, "%.3f,", ...
                    binIndex .* obj.BinWidthSeconds);
                for rangeIndex = 1:rangeCount
                    cumulativeProbability = ...
                        sum(histogram(1:binIndex, rangeIndex)) ./ ...
                        totals(rangeIndex);
                    fprintf( ...
                        fileIdentifier, "%d,%.6f", ...
                        histogram(binIndex, rangeIndex), ...
                        cumulativeProbability);
                    if rangeCount == 1
                        fprintf(fileIdentifier, "\n");
                    else
                        fprintf(fileIdentifier, ",");
                    end
                end
                if rangeCount > 1
                    fprintf( ...
                        fileIdentifier, "%d,%.6f\n", ...
                        sum(histogram(binIndex, :)), ...
                        sum(histogram(1:binIndex, :), "all") ./ ...
                        sum(totals));
                end
            end
        end

        function mustAcceptChannels(obj, channels)
            if any(channels > obj.ChannelCount)
                error( ...
                    "v2xsim:hook:outputs:ChannelOutOfRange", ...
                    "Invocation channel exceeds configured channel count.");
            end
        end
    end
end
