classdef PacketFateTraceRecorder < v2xsim.hook.Hook
    %PACKETFATETRACERECORDER Stream terminal directed packet outcomes.
    %   The recorder assigns a monotonic packet sequence independently for
    %   every technology/transmitter UE identity. Allocator-blocked
    %   observations are immutable terminal PRR events and are written with
    %   their block-time true-distance snapshot. Correct/error observations
    %   retain directed-packet reconciliation across repeated radio reports.
    %   Terminal fates are written in bounded chunks.

    properties (Constant, Access = protected)
        DependencyTypes = ...
            ?v2xsim.hook.dependencies.OutputDirectory
    end

    properties (SetAccess = immutable)
        FlushRowCount (1,1) double ...
            {mustBeReal,mustBeFinite,mustBeInteger,mustBePositive} = 10000
        FileFormat (1,1) string = "csv"
        FilenamePrefix (1,1) string = "packet_fates"
    end

    properties (Access = private)
        OutputDirectory (1,1) string = ""
        BufferedFates table = table()
        SequenceState table = table()
        ActiveTerminalFates table = table()
        ChunkFiles (:,1) string = strings(0,1)
        NextChunkIndex (1,1) double = 1
    end

    methods
        function obj = PacketFateTraceRecorder(options)
            arguments (Input)
                options.FlushRowCount (1,1) double ...
                    {mustBeReal,mustBeFinite, ...
                    mustBeInteger,mustBePositive} = 10000
                options.FileFormat (1,1) string = "csv"
                options.FilenamePrefix (1,1) string = ...
                    "packet_fates"
            end

            obj.FlushRowCount = options.FlushRowCount;
            obj.FileFormat = validatestring( ...
                options.FileFormat,["csv","parquet"]);
            obj.validateFilenamePrefix(options.FilenamePrefix);
            obj.FilenamePrefix = options.FilenamePrefix;
            obj.BufferedFates = ...
                v2xsim.analysis.emptyTerminalPacketFateTable();
            obj.SequenceState = table( ...
                strings(0,1),zeros(0,1),zeros(0,1), ...
                VariableNames=[ ...
                    "TransmitterKey","GenerationTimeSeconds", ...
                    "PacketSequence"]);
            obj.ActiveTerminalFates = ...
                v2xsim.analysis.emptyTerminalPacketFateTable();
        end

        function obj = build(obj,outputDirectory)
            arguments (Input)
                obj (1,1)
                outputDirectory (1,1) ...
                    v2xsim.hook.dependencies.OutputDirectory
            end

            obj.OutputDirectory = outputDirectory.Path;
        end

        function [obj,invocation] = invoke(obj,invocation)
            arguments (Input)
                obj (1,1)
                invocation (1,1) ...
                    v2xsim.hook.invocations. ...
                    AfterPacketFatesDeterminedInvocation
            end

            [obj,observations] = ...
                obj.observationsFromInvocation(invocation);
            terminalFates = ...
                v2xsim.analysis.aggregateTerminalPacketFates( ...
                    observations);
            [obj,terminalFates] = ...
                obj.reconcileActiveTerminalState( ...
                    terminalFates);
            if isempty(terminalFates)
                obj = obj.flushCompleteChunks();
                return
            end
            obj.BufferedFates = [ ...
                obj.BufferedFates;terminalFates];
            obj = obj.flushCompleteChunks();
        end

        function obj = cleanup(obj)
            obj.ActiveTerminalFates( ...
                1:height(obj.ActiveTerminalFates),:) = [];
            obj = obj.flushCompleteChunks();
            if isempty(obj.BufferedFates)
                return
            end
            [obj,~] = obj.writeChunk(obj.BufferedFates);
            obj.BufferedFates(:,:) = [];
        end

        function fates = terminalFates(obj)
            %TERMINALFATES Return written and currently buffered rows.
            arguments (Input)
                obj (1,1)
            end
            arguments (Output)
                fates table
            end

            fates = ...
                v2xsim.analysis.emptyTerminalPacketFateTable();
            for filename = obj.ChunkFiles.'
                if obj.FileFormat == "csv"
                    rows = readtable( ...
                        filename,TextType="string");
                else
                    rows = parquetread(filename);
                end
                rows = obj.coerceTraceTypes(rows);
                fates = [fates;rows]; %#ok<AGROW>
            end
            fates = [fates;obj.BufferedFates];
            if ~isempty(fates)
                fates = sortrows( ...
                    fates,["FateTimeSeconds","Technology", ...
                    "TransmitterUeId","PacketSequence", ...
                    "ReceiverUeId"]);
            end
        end
    end

    methods (Access = private)
        function [obj,observations] = ...
                observationsFromInvocation(obj,invocation)
            links = invocation.Links;
            linkCount = height(links);
            transmitters = invocation.Transmitters;
            transmitterUeIds = obj.transmitterUeIds( ...
                transmitters);
            packetSequences = nan(height(transmitters),1);
            for transmitterIndex = 1:height(transmitters)
                providedSequence = obj.optionalValue( ...
                    transmitters,"PacketSequence", ...
                    transmitterIndex,nan);
                [obj,packetSequences(transmitterIndex)] = ...
                    obj.sequenceForPacket( ...
                        invocation.Technology, ...
                        transmitterUeIds(transmitterIndex), ...
                        transmitters.GenerationTimeSeconds( ...
                            transmitterIndex), ...
                        providedSequence);
            end
            if linkCount == 0
                observations = ...
                    v2xsim.analysis.emptyTerminalPacketFateTable();
                return
            end

            [knownTransmitters,transmitterRows] = ismember( ...
                links.TransmitterId,transmitters.TransmitterId);
            if ~all(knownTransmitters)
                error( ...
                    "v2xsim:hook:outputs:" + ...
                    "UnknownPacketTransmitter", ...
                    "Every packet link must identify a transmitter row.");
            end

            receiverUeIds = obj.receiverUeIds(links);
            attemptNumbers = obj.optionalColumn( ...
                transmitters,"AttemptNumber",nan);
            resourceIds = obj.optionalColumn( ...
                transmitters,"ResourceId",nan);
            timeResourceIds = obj.optionalColumn( ...
                transmitters,"TimeResourceId",nan);
            frequencyResourceIds = obj.optionalColumn( ...
                transmitters,"FrequencyResourceId",nan);
            allocationEpochs = obj.optionalColumn( ...
                transmitters,"AllocationEpoch",nan);
            outcomes = string(links.Outcome);
            observations = table( ...
                repmat(invocation.SimulationTimeSeconds,linkCount,1), ...
                repmat(invocation.Technology,linkCount,1), ...
                double(links.TransmitterId), ...
                transmitterUeIds(transmitterRows), ...
                double(links.ReceiverId),receiverUeIds, ...
                packetSequences(transmitterRows), ...
                double(transmitters.GenerationTimeSeconds( ...
                    transmitterRows)), ...
                attemptNumbers(transmitterRows),outcomes, ...
                double(transmitters.Channel(transmitterRows)), ...
                double(transmitters.PacketType(transmitterRows)), ...
                double(links.DistanceMeters), ...
                resourceIds(transmitterRows), ...
                timeResourceIds(transmitterRows), ...
                frequencyResourceIds(transmitterRows), ...
                allocationEpochs(transmitterRows), ...
                VariableNames=string( ...
                    v2xsim.analysis. ...
                    emptyTerminalPacketFateTable(). ...
                    Properties.VariableNames));
        end

        function values = transmitterUeIds(~,transmitters)
            if ismember( ...
                    "TransmitterUeId", ...
                    string(transmitters.Properties.VariableNames))
                values = string(transmitters.TransmitterUeId);
            else
                values = "UE" + ...
                    string(transmitters.TransmitterId);
            end
            values = values(:);
        end

        function values = receiverUeIds(~,links)
            if ismember( ...
                    "ReceiverUeId", ...
                    string(links.Properties.VariableNames))
                values = string(links.ReceiverUeId);
            else
                values = "UE" + string(links.ReceiverId);
            end
            values = values(:);
        end

        function [obj,sequence] = sequenceForPacket( ...
                obj,technology,transmitterUeId,generationTime, ...
                providedSequence)
            key = technology + "|" + transmitterUeId;
            stateRow = find( ...
                obj.SequenceState.TransmitterKey == key,1);
            if ~isnan(providedSequence)
                sequence = providedSequence;
                if isempty(stateRow)
                    obj.SequenceState(end + 1,:) = { ...
                        key,generationTime,sequence};
                else
                    previousSequence = ...
                        obj.SequenceState.PacketSequence(stateRow);
                    previousGenerationTime = ...
                        obj.SequenceState.GenerationTimeSeconds( ...
                            stateRow);
                    if sequence < previousSequence || ...
                            (sequence == previousSequence && ...
                            generationTime ~= previousGenerationTime)
                        error( ...
                            "v2xsim:hook:outputs:" + ...
                            "InvalidPacketSequence", ...
                            "Explicit packet sequences must increase " + ...
                            "when generation time changes.");
                    end
                    if sequence > previousSequence
                        obj = obj.clearActiveTerminalState( ...
                            technology,transmitterUeId);
                    end
                    obj.SequenceState.GenerationTimeSeconds( ...
                        stateRow) = generationTime;
                    obj.SequenceState.PacketSequence(stateRow) = sequence;
                end
                return
            end

            if isempty(stateRow)
                sequence = 1;
                obj.SequenceState(end + 1,:) = { ...
                    key,generationTime,sequence};
            elseif obj.SequenceState.GenerationTimeSeconds( ...
                    stateRow) == generationTime
                sequence = ...
                    obj.SequenceState.PacketSequence(stateRow);
            else
                sequence = ...
                    obj.SequenceState.PacketSequence(stateRow) + 1;
                obj = obj.clearActiveTerminalState( ...
                    technology,transmitterUeId);
                obj.SequenceState.GenerationTimeSeconds( ...
                    stateRow) = generationTime;
                obj.SequenceState.PacketSequence(stateRow) = ...
                    sequence;
            end
        end

        function [obj,newFates] = ...
                reconcileActiveTerminalState(obj,terminalFates)
            retain = true(height(terminalFates),1);
            for fateIndex = 1:height(terminalFates)
                % A block has already been counted by the global PRR
                % recorder. Preserve that exact event row immediately;
                % only radio terminal outcomes participate in active-state
                % reconciliation.
                if terminalFates.Outcome(fateIndex) == "blocked"
                    continue
                end
                isExisting = ...
                    obj.ActiveTerminalFates.Technology == ...
                        terminalFates.Technology(fateIndex) & ...
                    obj.ActiveTerminalFates.TransmitterUeId == ...
                        terminalFates.TransmitterUeId(fateIndex) & ...
                    obj.ActiveTerminalFates.PacketSequence == ...
                        terminalFates.PacketSequence(fateIndex) & ...
                    obj.ActiveTerminalFates.ReceiverUeId == ...
                        terminalFates.ReceiverUeId(fateIndex);
                existingRow = find(isExisting,1);
                if isempty(existingRow)
                    obj.ActiveTerminalFates(end + 1,:) = ...
                        terminalFates(fateIndex,:);
                    continue
                end
                existingOutcome = ...
                    obj.ActiveTerminalFates.Outcome(existingRow);
                newOutcome = terminalFates.Outcome(fateIndex);
                if existingOutcome ~= newOutcome
                    error( ...
                        "v2xsim:analysis:" + ...
                        "ConflictingTerminalPacketFates", ...
                        "Directed packet %s/%s/%u/%s changed terminal " + ...
                        "outcome from %s to %s at %.9g s " + ...
                        "(generation %.9g s, attempt %.9g).", ...
                        terminalFates.Technology(fateIndex), ...
                        terminalFates.TransmitterUeId(fateIndex), ...
                        terminalFates.PacketSequence(fateIndex), ...
                        terminalFates.ReceiverUeId(fateIndex), ...
                        existingOutcome,newOutcome, ...
                        terminalFates.FateTimeSeconds(fateIndex), ...
                        terminalFates.GenerationTimeSeconds(fateIndex), ...
                        terminalFates.AttemptNumber(fateIndex));
                end
                retain(fateIndex) = false;
            end
            newFates = terminalFates(retain,:);
        end

        function obj = clearActiveTerminalState( ...
                obj,technology,transmitterUeId)
            isTransmitter = ...
                obj.ActiveTerminalFates.Technology == technology & ...
                obj.ActiveTerminalFates.TransmitterUeId == ...
                    transmitterUeId;
            obj.ActiveTerminalFates(isTransmitter,:) = [];
        end

        function values = optionalColumn( ...
                ~,source,variableName,defaultValue)
            if ismember( ...
                    variableName, ...
                    string(source.Properties.VariableNames))
                values = double(source.(variableName));
            else
                values = repmat(defaultValue,height(source),1);
            end
            values = values(:);
        end

        function value = optionalValue( ...
                obj,source,variableName,row,defaultValue)
            values = obj.optionalColumn( ...
                source,variableName,defaultValue);
            value = values(row);
        end

        function obj = flushCompleteChunks(obj)
            while height(obj.BufferedFates) >= obj.FlushRowCount
                chunk = obj.BufferedFates( ...
                    1:obj.FlushRowCount,:);
                [obj,~] = obj.writeChunk(chunk);
                obj.BufferedFates(1:obj.FlushRowCount,:) = [];
            end
        end

        function [obj,filename] = writeChunk(obj,rows)
            if strlength(obj.OutputDirectory) == 0
                error( ...
                    "v2xsim:hook:outputs:" + ...
                    "PacketFateTraceNotBuilt", ...
                    "PacketFateTraceRecorder must be built before " + ...
                    "it flushes rows.");
            end
            filename = fullfile( ...
                obj.OutputDirectory,sprintf( ...
                    "%s_%06d.%s", ...
                    obj.FilenamePrefix,obj.NextChunkIndex, ...
                    obj.FileFormat));
            try
                if obj.FileFormat == "csv"
                    writetable(rows,filename);
                else
                    parquetwrite(filename,rows);
                end
            catch cause
                error( ...
                    "v2xsim:hook:OutputOpenFailed", ...
                    "Could not write packet-fate trace %s: %s", ...
                    filename,cause.message);
            end
            obj.ChunkFiles(end + 1,1) = filename;
            obj.NextChunkIndex = obj.NextChunkIndex + 1;
        end

        function rows = coerceTraceTypes(~,rows)
            expected = ...
                v2xsim.analysis.emptyTerminalPacketFateTable();
            expectedNames = string( ...
                expected.Properties.VariableNames);
            if ~isequal( ...
                    string(rows.Properties.VariableNames), ...
                    expectedNames)
                error( ...
                    "v2xsim:hook:outputs:" + ...
                    "InvalidPacketFateTrace", ...
                    "A packet-fate trace chunk has an invalid schema.");
            end
            stringNames = [ ...
                "Technology","TransmitterUeId", ...
                "ReceiverUeId","Outcome"];
            for variableName = stringNames
                rows.(variableName) = ...
                    string(rows.(variableName));
            end
        end
    end

    methods (Static,Access = private)
        function validateFilenamePrefix(value)
            if ismissing(value) || ...
                    strlength(strip(value)) == 0 || ...
                    value ~= strip(value) || ...
                    contains(value,["/","\\"])
                error( ...
                    "v2xsim:hook:outputs:" + ...
                    "InvalidPacketFateFilenamePrefix", ...
                    "FilenamePrefix must be a nonblank file-name " + ...
                    "component.");
            end
        end
    end
end
