classdef VehicleKinematicsRecorder < v2xsim.hook.Hook
    %VEHICLEKINEMATICSRECORDER Stream long-form vehicle kinematics.

    properties (Constant, Access = protected)
        DependencyTypes = [ ...
            ?v2xsim.hook.dependencies.OutputDirectory, ...
            ?v2xsim.hook.dependencies.SimulationIdentifier]
    end

    properties (Access = private)
        OutputDirectory (1, 1) string = ""
        SimulationIdentifier (1, 1) double = NaN
        HasWrittenRows (1, 1) logical = false
    end

    methods
        function obj = build( ...
                obj, outputDirectory, simulationIdentifier)
            arguments (Input)
                obj (1, 1)
                outputDirectory (1, 1) ...
                    v2xsim.hook.dependencies.OutputDirectory
                simulationIdentifier (1, 1) ...
                    v2xsim.hook.dependencies.SimulationIdentifier
            end

            obj.OutputDirectory = outputDirectory.Path;
            obj.SimulationIdentifier = simulationIdentifier.Value;
            filename = obj.outputFilename();
            if isfile(filename)
                fileInformation = dir(filename);
                obj.HasWrittenRows = fileInformation.bytes > 0;
            end
        end

        function [obj, invocation] = invoke(obj, invocation)
            arguments (Input)
                obj (1, 1)
                invocation (1, 1) ...
                    v2xsim.hook.invocations. ...
                    AfterVehicleKinematicsUpdatedInvocation
            end

            vehicleKinematics = invocation.VehicleKinematics;
            vehicleCount = height(vehicleKinematics);
            if vehicleCount == 0
                return
            end

            outputRows = table( ...
                repmat( ...
                    invocation.SimulationTimeSeconds, ...
                    vehicleCount, 1), ...
                string(vehicleKinematics.Properties.RowNames), ...
                vehicleKinematics.X, ...
                vehicleKinematics.Y, ...
                vehicleKinematics.vX, ...
                vehicleKinematics.vY, ...
                vehicleKinematics.aX, ...
                vehicleKinematics.aY, ...
                VariableNames=[ ...
                    "SimulationTimeSeconds", ...
                    "VehicleId", ...
                    "X", ...
                    "Y", ...
                    "vX", ...
                    "vY", ...
                    "aX", ...
                    "aY"]);

            filename = obj.outputFilename();
            try
                if obj.HasWrittenRows
                    writetable( ...
                        outputRows, filename, ...
                        WriteMode="append", ...
                        WriteVariableNames=false);
                else
                    writetable(outputRows, filename);
                    obj.HasWrittenRows = true;
                end
            catch cause
                error( ...
                    "v2xsim:hook:OutputOpenFailed", ...
                    "Could not write vehicle-kinematics output " + ...
                    "file %s: %s", ...
                    filename, cause.message);
            end
        end
    end

    methods (Access = private)
        function filename = outputFilename(obj)
            filename = fullfile( ...
                obj.OutputDirectory, ...
                sprintf( ...
                    "vehicle_kinematics_%d.csv", ...
                    obj.SimulationIdentifier));
        end
    end
end
