classdef WirelessBlindSpotRecorder < v2xsim.hook.Hook
    %WIRELESSBLINDSPOTRECORDER Collect wireless-blind-spot statistics.
    %   Entry and last-reception timestamps are owned by the hook. A
    %   neighbor snapshot updates range membership, while packet-fate
    %   invocations update successful-reception timestamps.

    properties (Constant, Access = protected)
        DependencyTypes = [ ...
            ?v2xsim.hook.dependencies.OutputDirectory, ...
            ?v2xsim.hook.dependencies.SimulationIdentifier]
    end

    properties (SetAccess = immutable)
        MaximumDelaySeconds (1, 1) double ...
            {mustBeReal, mustBeFinite, mustBePositive} = 1
        ResolutionSeconds (1, 1) double ...
            {mustBeReal, mustBeFinite, mustBePositive} = 1
        Cv2xTechnology (1, 1) string = ""
    end

    properties (Access = private)
        OutputDirectory (1, 1) string = ""
        SimulationIdentifier (1, 1) double = NaN
        ItsG5State = struct( ...
            Technology="11p", ...
            Ranges=zeros(1, 0), ...
            LastReceptionTimes=zeros(0, 0, 0), ...
            LastSuccessfulGenerationTimes=zeros(0, 0), ...
            EnteredRangeTimes=zeros(0, 0, 0), ...
            GreaterOrEqualCounts=zeros(0, 0), ...
            ShorterCounts=zeros(0, 0))
        Cv2xState = struct( ...
            Technology="", ...
            Ranges=zeros(1, 0), ...
            LastReceptionTimes=zeros(0, 0, 0), ...
            LastSuccessfulGenerationTimes=zeros(0, 0), ...
            EnteredRangeTimes=zeros(0, 0, 0), ...
            GreaterOrEqualCounts=zeros(0, 0), ...
            ShorterCounts=zeros(0, 0))
    end

    methods
        function obj = WirelessBlindSpotRecorder( ...
                maximumDelaySeconds, resolutionSeconds, options)
            arguments (Input)
                maximumDelaySeconds (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBePositive}
                resolutionSeconds (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBePositive}
                options.Cv2xTechnology (1, 1) string = ""
            end

            if resolutionSeconds > maximumDelaySeconds
                error( ...
                    "v2xsim:hook:builtins:InvalidBlindSpotResolution", ...
                    "ResolutionSeconds cannot exceed MaximumDelaySeconds.");
            end
            if options.Cv2xTechnology ~= ""
                options.Cv2xTechnology = string(validatestring( ...
                    options.Cv2xTechnology, ["LTE", "5G"]));
            end

            obj.MaximumDelaySeconds = maximumDelaySeconds;
            obj.ResolutionSeconds = resolutionSeconds;
            obj.Cv2xTechnology = options.Cv2xTechnology;
            obj.Cv2xState.Technology = options.Cv2xTechnology;
        end

        function obj = build( ...
                obj, outputDirectory, simulationIdentifier)
            arguments (Input)
                obj (1, 1)
                outputDirectory (1, 1) ...
                    v2xsim.hook.dependencies.OutputDirectory
                simulationIdentifier (1, 1) ...
                    v2xsim.hook.dependencies.SimulationIdentifier
            end

            obj.OutputDirectory = outputDirectory.Path;
            obj.SimulationIdentifier = simulationIdentifier.Value;
        end

        function [obj, invocation] = invoke(obj, invocation)
            arguments (Input)
                obj (1, 1)
                invocation (1, 1) ...
                    v2xsim.hook.invocation.Invocation
            end

            if isa( ...
                    invocation, ...
                    "v2xsim.hook.invocations." + ...
                    "AfterNeighborGraphUpdatedInvocation")
                obj = obj.observeNeighborGraph(invocation);
            elseif isa( ...
                    invocation, ...
                    "v2xsim.hook.invocations." + ...
                    "AfterPacketFatesDeterminedInvocation")
                obj = obj.observePacketFates(invocation);
            else
                error( ...
                    "v2xsim:hook:builtins:UnsupportedInvocation", ...
                    "WirelessBlindSpotRecorder cannot consume %s.", ...
                    class(invocation));
            end
        end

        function obj = cleanup(obj)
            obj.writeState(obj.Cv2xState);
            obj.writeState(obj.ItsG5State);
        end
    end

    methods (Access = private)
        function obj = observeNeighborGraph(obj, invocation)
            ranges = invocation.AwarenessRangesMeters;
            if isempty(invocation.UeIds)
                return
            end

            maximumUeId = max(invocation.UeIds);
            obj.ItsG5State = obj.updateTechnologySnapshot( ...
                obj.ItsG5State, invocation.ItsG5UeIds, ...
                invocation.UeIds, invocation.DistanceMatrixMeters, ...
                ranges, invocation.SimulationTimeSeconds, maximumUeId);
            obj.Cv2xState = obj.updateTechnologySnapshot( ...
                obj.Cv2xState, invocation.Cv2xUeIds, ...
                invocation.UeIds, invocation.DistanceMatrixMeters, ...
                ranges, invocation.SimulationTimeSeconds, maximumUeId);
        end

        function obj = observePacketFates(obj, invocation)
            if invocation.Technology == "11p"
                state = obj.ItsG5State;
                isItsG5 = true;
            else
                state = obj.Cv2xState;
                isItsG5 = false;
                if state.Technology == ""
                    state.Technology = invocation.Technology;
                elseif state.Technology ~= invocation.Technology
                    error( ...
                        "v2xsim:hook:builtins:" + ...
                        "TechnologyChangedDuringSimulation", ...
                        "C-V2X technology changed from %s to %s.", ...
                        state.Technology, invocation.Technology);
                end
            end

            state = obj.ensureState( ...
                state, invocation.MaximumUeId, ...
                invocation.AwarenessRangesMeters);
            correctLinks = invocation.Links( ...
                string(invocation.Links.Outcome) == "correct", :);
            for linkIndex = 1:height(correctLinks)
                transmitterId = ...
                    correctLinks.TransmitterId(linkIndex);
                receiverId = correctLinks.ReceiverId(linkIndex);
                transmitterIndex = find( ...
                    invocation.Transmitters.TransmitterId == ...
                        transmitterId, ...
                    1);
                generationTime = ...
                    invocation.Transmitters. ...
                        GenerationTimeSeconds(transmitterIndex);

                if state.LastSuccessfulGenerationTimes( ...
                        transmitterId, receiverId) == generationTime
                    continue
                end
                state.LastSuccessfulGenerationTimes( ...
                    transmitterId, receiverId) = generationTime;

                isInRange = ...
                    correctLinks.DistanceMeters(linkIndex) < state.Ranges;
                for rangeIndex = find(isInRange)
                    state.LastReceptionTimes( ...
                        transmitterId, receiverId, rangeIndex) = ...
                        invocation.SimulationTimeSeconds;
                end
            end

            if isItsG5
                obj.ItsG5State = state;
            else
                obj.Cv2xState = state;
            end
        end

        function state = updateTechnologySnapshot( ...
                obj, state, technologyUeIds, ueIds, distances, ...
                ranges, simulationTimeSeconds, maximumUeId)
            state = obj.ensureState(state, maximumUeId, ranges);
            [isPresent, rowIndices] = ismember(technologyUeIds, ueIds);
            if ~all(isPresent)
                error( ...
                    "v2xsim:hook:builtins:MissingTechnologyUe", ...
                    "Every technology-specific UE must have a distance row.");
            end

            technologyUeIds = technologyUeIds(:);
            rowIndices = rowIndices(:);
            technologyDistances = distances(rowIndices, rowIndices);
            technologyCount = numel(technologyUeIds);
            stateMaximumUeId = ...
                size(state.LastSuccessfulGenerationTimes, 1);

            for rangeIndex = 1:numel(ranges)
                isInRange = ...
                    technologyDistances < ranges(rangeIndex);
                isInRange(1:technologyCount + 1:end) = false;

                enteredTimes = -ones(stateMaximumUeId);
                lastReceptionTimes = -ones(stateMaximumUeId);
                if technologyCount > 0
                    previousEnteredTimes = state.EnteredRangeTimes( ...
                        technologyUeIds, technologyUeIds, rangeIndex);
                    newlyInRange = ...
                        isInRange & previousEnteredTimes < 0;
                    previousEnteredTimes(newlyInRange) = ...
                        simulationTimeSeconds;
                    previousEnteredTimes(~isInRange) = -1;
                    enteredTimes( ...
                        technologyUeIds, technologyUeIds) = ...
                        previousEnteredTimes;

                    previousReceptionTimes = ...
                        state.LastReceptionTimes( ...
                            technologyUeIds, technologyUeIds, ...
                            rangeIndex);
                    previousReceptionTimes(~isInRange) = -1;
                    lastReceptionTimes( ...
                        technologyUeIds, technologyUeIds) = ...
                        previousReceptionTimes;
                end

                state.EnteredRangeTimes(:, :, rangeIndex) = ...
                    enteredTimes;
                state.LastReceptionTimes(:, :, rangeIndex) = ...
                    lastReceptionTimes;
                state = obj.countSnapshot( ...
                    state, rangeIndex, simulationTimeSeconds);
            end

            generationTimes = -ones(stateMaximumUeId);
            if technologyCount > 0
                previousGenerationTimes = ...
                    state.LastSuccessfulGenerationTimes( ...
                        technologyUeIds, technologyUeIds);
                isInMaximumRange = ...
                    technologyDistances < ranges(end);
                isInMaximumRange( ...
                    1:technologyCount + 1:end) = false;
                previousGenerationTimes(~isInMaximumRange) = -1;
                generationTimes( ...
                    technologyUeIds, technologyUeIds) = ...
                    previousGenerationTimes;
            end
            state.LastSuccessfulGenerationTimes = generationTimes;
        end

        function state = countSnapshot( ...
                obj, state, rangeIndex, simulationTimeSeconds)
            lastReceptionTimes = ...
                state.LastReceptionTimes(:, :, rangeIndex);
            enteredRangeTimes = ...
                state.EnteredRangeTimes(:, :, rangeIndex);
            hasReception = lastReceptionTimes >= 0;
            hasEnteredRange = enteredRangeTimes >= 0;
            timeSinceReception = ...
                simulationTimeSeconds - lastReceptionTimes;
            timeSinceEntry = ...
                simulationTimeSeconds - enteredRangeTimes;
            thresholds = obj.thresholds();

            for thresholdIndex = 1:numel(thresholds)
                threshold = thresholds(thresholdIndex);
                isGreaterOrEqual = ...
                    (hasReception & ...
                        timeSinceReception >= threshold) | ...
                    (~hasReception & hasEnteredRange & ...
                        timeSinceEntry > threshold);
                isShorter = ...
                    hasReception & timeSinceReception > 0 & ...
                    timeSinceReception < threshold;
                state.GreaterOrEqualCounts( ...
                    thresholdIndex, rangeIndex) = ...
                    state.GreaterOrEqualCounts( ...
                        thresholdIndex, rangeIndex) + ...
                    nnz(isGreaterOrEqual);
                state.ShorterCounts( ...
                    thresholdIndex, rangeIndex) = ...
                    state.ShorterCounts( ...
                        thresholdIndex, rangeIndex) + ...
                    nnz(isShorter);
            end
        end

        function state = ensureState(obj, state, maximumUeId, ranges)
            thresholds = obj.thresholds();
            if isempty(state.Ranges)
                state.Ranges = ranges;
                state.GreaterOrEqualCounts = ...
                    zeros(numel(thresholds), numel(ranges));
                state.ShorterCounts = ...
                    zeros(numel(thresholds), numel(ranges));
            elseif ~isequal(state.Ranges, ranges)
                error( ...
                    "v2xsim:hook:builtins:AwarenessRangesChanged", ...
                    "Awareness ranges cannot change during a simulation.");
            end

            currentMaximumId = ...
                size(state.LastSuccessfulGenerationTimes, 1);
            if maximumUeId <= currentMaximumId
                return
            end

            lastReceptionTimes = ...
                -ones(maximumUeId, maximumUeId, numel(ranges));
            enteredRangeTimes = ...
                -ones(maximumUeId, maximumUeId, numel(ranges));
            generationTimes = -ones(maximumUeId);
            if currentMaximumId > 0
                lastReceptionTimes( ...
                    1:currentMaximumId, 1:currentMaximumId, :) = ...
                    state.LastReceptionTimes;
                enteredRangeTimes( ...
                    1:currentMaximumId, 1:currentMaximumId, :) = ...
                    state.EnteredRangeTimes;
                generationTimes( ...
                    1:currentMaximumId, 1:currentMaximumId) = ...
                    state.LastSuccessfulGenerationTimes;
            end
            state.LastReceptionTimes = lastReceptionTimes;
            state.EnteredRangeTimes = enteredRangeTimes;
            state.LastSuccessfulGenerationTimes = generationTimes;
        end

        function writeState(obj, state)
            totalCounts = ...
                state.GreaterOrEqualCounts + state.ShorterCounts;
            if isempty(totalCounts) || ~any(totalCounts, "all")
                return
            end
            if state.Technology == ""
                error( ...
                    "v2xsim:hook:builtins:MissingCv2xTechnology", ...
                    "Cv2xTechnology is required to name blind-spot output.");
            end

            filename = fullfile( ...
                obj.OutputDirectory, ...
                sprintf( ...
                    "wireless_blind_spot_%d_%s.csv", ...
                    obj.SimulationIdentifier, state.Technology));
            fileIdentifier = fopen(filename, "a");
            if fileIdentifier == -1
                error( ...
                    "v2xsim:hook:OutputOpenFailed", ...
                    "Could not open wireless-blind-spot file %s.", ...
                    filename);
            end
            closeFile = onCleanup(@() fclose(fileIdentifier));

            thresholds = obj.thresholds();
            for thresholdIndex = 1:numel(thresholds)
                fprintf( ...
                    fileIdentifier, "%.3f", ...
                    thresholds(thresholdIndex));
                for rangeIndex = 1:numel(state.Ranges)
                    greaterOrEqual = state.GreaterOrEqualCounts( ...
                        thresholdIndex, rangeIndex);
                    shorter = state.ShorterCounts( ...
                        thresholdIndex, rangeIndex);
                    probability = ...
                        greaterOrEqual ./ (greaterOrEqual + shorter);
                    fprintf( ...
                        fileIdentifier, ",%d,%d,%.6f", ...
                        greaterOrEqual, shorter, probability);
                end
                fprintf(fileIdentifier, "\n");
            end
        end

        function values = thresholds(obj)
            thresholdCount = ceil( ...
                obj.MaximumDelaySeconds ./ obj.ResolutionSeconds);
            values = obj.ResolutionSeconds .* (1:thresholdCount);
        end
    end
end
