function diagnostics = attachContext(diagnostics, context)
%ATTACHCONTEXT Add scenario-specific values to diagnostic rows.

if isempty(diagnostics) || ...
        ~isa( ...
            context, ...
            "v2xsim.positioning.ExitRampPositionErrorContext")
    return
end

routeStates = context.VehicleRouteStates;
[knownVehicles, routeRows] = ismember( ...
    diagnostics.VehicleId, ...
    string(routeStates.Properties.RowNames));
if ~all(knownVehicles)
    error( ...
        "v2xsim:positioning:diagnostics:UnknownRouteVehicle", ...
        "Every diagnostic vehicle must have a route state.");
end
diagnostics.TrueRoute = string(routeStates.Route(routeRows));
end
