function diagnostics = createRows( ...
        inputPositions, outputPositions, simulationTimeSeconds, ...
        moduleType, lifecycle, statusEffectType)
%CREATEROWS Build normalized per-vehicle position-error diagnostics.
%   LIFECYCLE is an optional scalar struct whose fields may override the
%   default lifecycle columns. Every supplied field must contain one value
%   per input vehicle.

arguments (Input)
    inputPositions table ...
        {v2xsim.positioning.validation.mustBe2DPositionTable}
    outputPositions table ...
        {v2xsim.positioning.validation.mustBe2DPositionTable}
    simulationTimeSeconds (1, 1) double ...
        {mustBeReal, mustBeFinite, mustBeNonnegative}
    moduleType (1, 1) string
    lifecycle (1, 1) struct = struct()
    statusEffectType (1, 1) string = ""
end

vehicleIds = reshape( ...
    string(inputPositions.Properties.RowNames), [], 1);
outputVehicleIds = reshape( ...
    string(outputPositions.Properties.RowNames), [], 1);
if ~isequal(sort(vehicleIds), sort(outputVehicleIds))
    error( ...
        "v2xsim:positioning:diagnostics:VehicleSetChanged", ...
        "Diagnostic input and output positions must identify the " + ...
        "same vehicles.");
end
outputPositions = outputPositions(cellstr(vehicleIds), :);
vehicleCount = height(inputPositions);

isEvaluated = logicalColumn( ...
    lifecycle, "IsEvaluated", false(vehicleCount, 1), vehicleCount);
evaluationOccurred = logicalColumn( ...
    lifecycle, "EvaluationOccurred", ...
    false(vehicleCount, 1), vehicleCount);
selectionOccurred = logicalColumn( ...
    lifecycle, "SelectionOccurred", ...
    false(vehicleCount, 1), vehicleCount);
isSelected = logicalColumn( ...
    lifecycle, "IsSelected", false(vehicleCount, 1), vehicleCount);
activeSegmentEntered = logicalColumn( ...
    lifecycle, "ActiveSegmentEntered", ...
    false(vehicleCount, 1), vehicleCount);
isActive = logicalColumn( ...
    lifecycle, "IsActive", false(vehicleCount, 1), vehicleCount);
activeSegmentExited = logicalColumn( ...
    lifecycle, "ActiveSegmentExited", ...
    false(vehicleCount, 1), vehicleCount);
resetOccurred = logicalColumn( ...
    lifecycle, "ResetOccurred", false(vehicleCount, 1), vehicleCount);
episodeId = doubleColumn( ...
    lifecycle, "EpisodeId", NaN(vehicleCount, 1), vehicleCount);
leftCensoredAtStart = logicalColumn( ...
    lifecycle, "LeftCensoredAtStart", ...
    false(vehicleCount, 1), vehicleCount);

if any(selectionOccurred & ~evaluationOccurred)
    error( ...
        "v2xsim:positioning:diagnostics:InvalidLifecycleState", ...
        "SelectionOccurred requires EvaluationOccurred.");
end
if any(activeSegmentEntered & activeSegmentExited)
    error( ...
        "v2xsim:positioning:diagnostics:InvalidLifecycleState", ...
        "A vehicle cannot enter and exit an active segment in the " + ...
        "same diagnostic row.");
end
if any(~isnan(episodeId) & ...
        (episodeId < 1 | fix(episodeId) ~= episodeId))
    error( ...
        "v2xsim:positioning:diagnostics:InvalidEpisodeId", ...
        "EpisodeId values must be positive integers or NaN.");
end

inputX = double(inputPositions.X);
inputY = double(inputPositions.Y);
outputX = double(outputPositions.X);
outputY = double(outputPositions.Y);
displacementX = outputX - inputX;
displacementY = outputY - inputY;
lifecycleEvent = composeLifecycleEvents( ...
    evaluationOccurred, selectionOccurred, ...
    activeSegmentEntered, activeSegmentExited, resetOccurred);

diagnostics = table( ...
    repmat(simulationTimeSeconds, vehicleCount, 1), ...
    vehicleIds, ...
    strings(vehicleCount, 1), ...
    ones(vehicleCount, 1), ...
    repmat(moduleType, vehicleCount, 1), ...
    repmat(statusEffectType, vehicleCount, 1), ...
    inputX, ...
    inputY, ...
    outputX, ...
    outputY, ...
    displacementX, ...
    displacementY, ...
    hypot(displacementX, displacementY), ...
    isEvaluated, ...
    evaluationOccurred, ...
    selectionOccurred, ...
    isSelected, ...
    activeSegmentEntered, ...
    isActive, ...
    activeSegmentExited, ...
    resetOccurred, ...
    episodeId, ...
    leftCensoredAtStart, ...
    lifecycleEvent, ...
    strings(vehicleCount, 1), ...
    NaN(vehicleCount, 1), ...
    NaN(vehicleCount, 1), ...
    VariableNames=v2xsim.positioning.diagnostics. ...
        emptyTable().Properties.VariableNames);
end

function value = logicalColumn( ...
        lifecycle, fieldName, defaultValue, expectedHeight)
value = fieldOrDefault(lifecycle, fieldName, defaultValue);
if ~islogical(value) || ...
        ~isequal(size(value), [expectedHeight, 1])
    error( ...
        "v2xsim:positioning:diagnostics:InvalidLifecycleColumn", ...
        "%s must be a %d-by-1 logical column.", ...
        fieldName, expectedHeight);
end
end

function value = doubleColumn( ...
        lifecycle, fieldName, defaultValue, expectedHeight)
value = fieldOrDefault(lifecycle, fieldName, defaultValue);
if ~isa(value, "double") || ~isreal(value) || ...
        ~isequal(size(value), [expectedHeight, 1])
    error( ...
        "v2xsim:positioning:diagnostics:InvalidLifecycleColumn", ...
        "%s must be a %d-by-1 real double column.", ...
        fieldName, expectedHeight);
end
end

function value = fieldOrDefault(structure, fieldName, defaultValue)
if isfield(structure, fieldName)
    value = structure.(fieldName);
else
    value = defaultValue;
end
end

function events = composeLifecycleEvents( ...
        evaluationOccurred, selectionOccurred, ...
        activeSegmentEntered, activeSegmentExited, resetOccurred)
events = strings(size(evaluationOccurred));
events(evaluationOccurred & selectionOccurred) = "Selected";
events(evaluationOccurred & ~selectionOccurred) = ...
    "EvaluatedNotSelected";
events = appendEvent( ...
    events, activeSegmentEntered, "ActiveSegmentEntered");
events = appendEvent( ...
    events, activeSegmentExited, "ActiveSegmentExited");
events = appendEvent(events, resetOccurred, "Reset");
end

function events = appendEvent(events, mask, eventName)
separator = strings(size(events));
separator(mask & events ~= "") = "|";
events(mask) = ...
    events(mask) + separator(mask) + eventName;
end
