function diagnostics = emptyTable()
%EMPTYTABLE Create an empty position-error diagnostic table.

diagnostics = table( ...
    zeros(0, 1), strings(0, 1), strings(0, 1), ...
    zeros(0, 1), strings(0, 1), strings(0, 1), ...
    zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    false(0, 1), false(0, 1), false(0, 1), false(0, 1), ...
    false(0, 1), false(0, 1), false(0, 1), false(0, 1), ...
    NaN(0, 1), false(0, 1), strings(0, 1), ...
    strings(0, 1), NaN(0, 1), NaN(0, 1), ...
    VariableNames=[ ...
        "SimulationTimeSeconds", ...
        "VehicleId", ...
        "TrueRoute", ...
        "ModuleIndex", ...
        "ModuleType", ...
        "StatusEffectType", ...
        "InputXMeters", ...
        "InputYMeters", ...
        "OutputXMeters", ...
        "OutputYMeters", ...
        "DisplacementXMeters", ...
        "DisplacementYMeters", ...
        "DisplacementMagnitudeMeters", ...
        "IsEvaluated", ...
        "EvaluationOccurred", ...
        "SelectionOccurred", ...
        "IsSelected", ...
        "ActiveSegmentEntered", ...
        "IsActive", ...
        "ActiveSegmentExited", ...
        "ResetOccurred", ...
        "EpisodeId", ...
        "LeftCensoredAtStart", ...
        "LifecycleEvent", ...
        "NetworkUpdateOutcome", ...
        "OutputSourceTimeSeconds", ...
        "OutputAgeSeconds"]);
end
