function mustBePositionErrorDiagnosticsTable(value)
%MUSTBEPOSITIONERRORDIAGNOSTICSTABLE Validate normalized trace rows.

if ~istable(value)
    error( ...
        "v2xsim:positioning:diagnostics:MustBeTable", ...
        "Position-error diagnostics must be a table.");
end

expected = v2xsim.positioning.diagnostics.emptyTable();
if ~isequal( ...
        string(value.Properties.VariableNames), ...
        string(expected.Properties.VariableNames))
    error( ...
        "v2xsim:positioning:diagnostics:InvalidSchema", ...
        "Position-error diagnostics have an invalid table schema.");
end

numericVariables = [ ...
    "SimulationTimeSeconds", ...
    "ModuleIndex", ...
    "InputXMeters", ...
    "InputYMeters", ...
    "OutputXMeters", ...
    "OutputYMeters", ...
    "DisplacementXMeters", ...
    "DisplacementYMeters", ...
    "DisplacementMagnitudeMeters", ...
    "EpisodeId"];
for variableName = numericVariables
    column = value.(variableName);
    if ~isa(column, "double") || ~isreal(column) || ...
            size(column, 2) ~= 1
        error( ...
            "v2xsim:positioning:diagnostics:InvalidColumnType", ...
            "%s must be a real double column.", variableName);
    end
end

logicalVariables = [ ...
    "IsEvaluated", ...
    "EvaluationOccurred", ...
    "SelectionOccurred", ...
    "IsSelected", ...
    "ActiveSegmentEntered", ...
    "IsActive", ...
    "ActiveSegmentExited", ...
    "ResetOccurred", ...
    "LeftCensoredAtStart"];
for variableName = logicalVariables
    if ~islogical(value.(variableName)) || ...
            size(value.(variableName), 2) ~= 1
        error( ...
            "v2xsim:positioning:diagnostics:InvalidColumnType", ...
            "%s must be a logical column.", variableName);
    end
end

stringVariables = [ ...
    "VehicleId", "TrueRoute", "ModuleType", "StatusEffectType", ...
    "LifecycleEvent"];
for variableName = stringVariables
    if ~isstring(value.(variableName)) || ...
            size(value.(variableName), 2) ~= 1
        error( ...
            "v2xsim:positioning:diagnostics:InvalidColumnType", ...
            "%s must be a string column.", variableName);
    end
end

if any(~isfinite(value.SimulationTimeSeconds)) || ...
        any(value.SimulationTimeSeconds < 0)
    error( ...
        "v2xsim:positioning:diagnostics:InvalidSimulationTime", ...
        "SimulationTimeSeconds must be finite and nonnegative.");
end
if any(~isfinite(value.ModuleIndex)) || ...
        any(value.ModuleIndex < 0) || ...
        any(fix(value.ModuleIndex) ~= value.ModuleIndex)
    error( ...
        "v2xsim:positioning:diagnostics:InvalidModuleIndex", ...
        "ModuleIndex must contain nonnegative integers.");
end
finiteVariables = setdiff(numericVariables, ...
    ["SimulationTimeSeconds", "EpisodeId"]);
for variableName = finiteVariables
    if any(~isfinite(value.(variableName)))
        error( ...
            "v2xsim:positioning:diagnostics:NonfiniteValue", ...
            "%s must contain finite values.", variableName);
    end
end
if any(~isnan(value.EpisodeId) & ...
        (~isfinite(value.EpisodeId) | value.EpisodeId < 1 | ...
        fix(value.EpisodeId) ~= value.EpisodeId))
    error( ...
        "v2xsim:positioning:diagnostics:InvalidEpisodeId", ...
        "EpisodeId must contain positive integers or NaN.");
end
if any(ismissing(value.VehicleId) | strlength(value.VehicleId) == 0)
    error( ...
        "v2xsim:positioning:diagnostics:InvalidVehicleId", ...
        "VehicleId values must be nonmissing and nonempty.");
end
if any(ismissing(value.ModuleType) | strlength(value.ModuleType) == 0)
    error( ...
        "v2xsim:positioning:diagnostics:InvalidModuleType", ...
        "ModuleType values must be nonmissing and nonempty.");
end
if any(ismissing(value.StatusEffectType))
    error( ...
        "v2xsim:positioning:diagnostics:InvalidStatusEffectType", ...
        "StatusEffectType values must not be missing.");
end
end
