function validateRetentionParameters(keepProbability, maximumIntervals)
%VALIDATERETENTIONPARAMETERS Validate the Bazzi retention-process inputs.
%   This validation does not materialize a probability distribution, so
%   closed-form or sampled consumers can handle their own supported sizes.
%
%   Reference: A. Bazzi et al., IEEE TVT 69(8), 2020,
%   DOI 10.1109/TVT.2020.3001074.

arguments (Input)
    keepProbability (1, 1) double
    maximumIntervals (1, 1) double
end

if ~isreal(keepProbability) || ~isfinite(keepProbability) || ...
        keepProbability < 0 || keepProbability > 1
    error( ...
        "v2xsimregression:bazzi2020blindspots:" + ...
        "InvalidKeepProbability", ...
        "Keep probability must be a finite scalar in [0, 1].");
end

isValidMaximum = ...
    isreal(maximumIntervals) && ( ...
    (isfinite(maximumIntervals) && maximumIntervals >= 1 && ...
    fix(maximumIntervals) == maximumIntervals) || ...
    isinf(maximumIntervals) && maximumIntervals > 0);
if ~isValidMaximum
    error( ...
        "v2xsimregression:bazzi2020blindspots:" + ...
        "InvalidMaximumIntervals", ...
        "Maximum intervals must be a positive integer or positive Inf.");
end

if keepProbability == 1 && isinf(maximumIntervals)
    error( ...
        "v2xsimregression:bazzi2020blindspots:" + ...
        "NonconvergentRetention", ...
        "An infinite interval cap with keep probability one never " + ...
        "changes resource and has no proper TBC distribution.");
end
end
