function [probability, unchangedProbability, model] = ...
        wirelessBlindSpotProbability( ...
        elapsedSeconds, keepProbability, options)
%WIRELESSBLINDSPOTPROBABILITY Two-vehicle WBS model, Bazzi Eqs. (1)-(12).
%   Two vehicles form a wireless blind spot when both retain their resource
%   through the requested delay and initially select the same resource.
%   Equation (12) is therefore P_WBS=P_unchanged^2/R, where R is the number
%   of equiprobable resources.
%
%   Reference: A. Bazzi et al., "On Wireless Blind Spots in the C-V2X
%   Sidelink," IEEE Trans. Veh. Technol., vol. 69, no. 8, 2020,
%   DOI 10.1109/TVT.2020.3001074.

arguments (Input)
    elapsedSeconds double
    keepProbability (1, 1) double
    options.MaximumConsecutiveReservationIntervals (1, 1) double = Inf
    options.MinimumReselectionCounter (1, 1) double = 5
    options.MaximumReselectionCounter (1, 1) double = 15
    options.BeaconRateHz (1, 1) double = 10
    options.ResourceCount (1, 1) double = 100
    options.TailTolerance (1, 1) double = 1e-12
end

arguments (Output)
    probability double
    unchangedProbability double
    model (1, 1) struct
end

validateElapsedSeconds(elapsedSeconds);
validateBeaconRate(options.BeaconRateHz);
validateResourceCount(options.ResourceCount);

[tbcPeriods, tbcProbability, omittedProbability] = ...
    v2xsimregression.paper.bazzi2020blindspots.analysis.tbcPmf( ...
    keepProbability, ...
    MaximumConsecutiveReservationIntervals= ...
    options.MaximumConsecutiveReservationIntervals, ...
    MinimumReselectionCounter=options.MinimumReselectionCounter, ...
    MaximumReselectionCounter=options.MaximumReselectionCounter, ...
    TailTolerance=options.TailTolerance);

elapsedPeriods = elapsedSeconds .* options.BeaconRateHz;
unchangedProbability = ...
    v2xsimregression.paper.bazzi2020blindspots.analysis. ...
    resourceUnchangedProbability( ...
    elapsedPeriods, tbcPeriods, tbcProbability);
probability = unchangedProbability .^ 2 ./ options.ResourceCount;

if nargout >= 3
    [expectedSeconds, expectedPeriods] = ...
        v2xsimregression.paper.bazzi2020blindspots.analysis. ...
        expectedTbcDuration( ...
        keepProbability, ...
        MaximumConsecutiveReservationIntervals= ...
        options.MaximumConsecutiveReservationIntervals, ...
        MinimumReselectionCounter=options.MinimumReselectionCounter, ...
        MaximumReselectionCounter=options.MaximumReselectionCounter, ...
        BeaconRateHz=options.BeaconRateHz);
    model = struct( ...
        "TbcPeriods", tbcPeriods, ...
        "TbcProbability", tbcProbability, ...
        "OmittedProbability", omittedProbability, ...
        "ExpectedTbcPeriods", expectedPeriods, ...
        "ExpectedTbcSeconds", expectedSeconds, ...
        "BeaconRateHz", options.BeaconRateHz, ...
        "ResourceCount", options.ResourceCount);
else
    model = struct();
end
end

function validateElapsedSeconds(value)
if ~isreal(value) || any(~isfinite(value), "all") || ...
        any(value < 0, "all")
    error( ...
        "v2xsimregression:bazzi2020blindspots:" + ...
        "InvalidElapsedSeconds", ...
        "Elapsed seconds must be finite, real, and nonnegative.");
end
end

function validateBeaconRate(value)
if ~isreal(value) || ~isfinite(value) || value <= 0
    error( ...
        "v2xsimregression:bazzi2020blindspots:InvalidBeaconRate", ...
        "Beacon rate must be a finite positive scalar.");
end
end

function validateResourceCount(value)
if ~isreal(value) || ~isfinite(value) || value < 1 || ...
        fix(value) ~= value
    error( ...
        "v2xsimregression:bazzi2020blindspots:" + ...
        "InvalidResourceCount", ...
        "Resource count must be a finite positive integer.");
end
end
