classdef ResourceAllocatorSmokeTest < matlab.unittest.TestCase
    %RESOURCEALLOCATORSMOKETEST Full-simulator coverage of named allocators.

    properties (TestParameter)
        AllocatorType = { ...
            "ReuseDistance", ...
            "MaximumReuseDistance", ...
            "MinimumReusePower", ...
            "ThreeGppAutonomous", ...
            "RandomBenchmark", ...
            "OrderedBenchmark"}
    end

    properties (SetAccess = private)
        TemporaryDirectory (1,1) string
    end

    methods (TestClassSetup)
        function createTemporaryDirectory(testCase)
            temporaryFolder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            testCase.TemporaryDirectory = ...
                string(temporaryFolder.Folder);
        end
    end

    methods (Test)
        function testNamedAllocatorRunsThroughSimulator( ...
                testCase,AllocatorType)
            allocatorType = string(AllocatorType);
            projectRoot = fileparts(fileparts(fileparts(fileparts( ...
                mfilename("fullpath")))));
            sourceDirectory = fullfile(projectRoot,"src");
            simulatorDirectory = fullfile(projectRoot,"old_src");
            originalPath = path;
            testCase.addTeardown(@() path(originalPath));
            addpath(sourceDirectory);
            addpath(simulatorDirectory);

            outputDirectory = fullfile( ...
                testCase.TemporaryDirectory,allocatorType);
            configurationFile = fullfile( ...
                simulatorDirectory,"ConfigFiles", ...
                "EtsiHighwayMediumMode1.cfg");
            simulationArguments = { ...
                configurationFile, ...
                "simulation.RandomSeed",2, ...
                "simulation.RadioAccessMode","LTE-V2X", ...
                "simulation.DurationSeconds",0.2, ...
                "scenario.Type","BidirectionalHighwayScenario", ...
                "scenarioOptions.VehicleCount",4, ...
                "scenarioOptions.RoadLength",200, ...
                "scenarioOptions.MeanVehicleSpeed",10, ...
                "scenarioOptions.VehicleSpeedStandardDeviation",0, ...
                "scenarioOptions.RerollSpeedOnWrapAround",false, ...
                "resourceAllocation.Type",allocatorType, ...
                "output.Directory",outputDirectory, ...
                "output.PacketReceptionRatio.Enabled",false, ...
                "output.UpdateDelay.Enabled",false, ...
                "output.PacketDelay.Enabled",false, ...
                "output.DataAge.Enabled",false, ...
                "output.AverageNeighborCount.Enabled",false, ...
                "output.ChannelBusyRatio.Enabled",false}; %#ok<NASGU>

            evalc("v2xsim.runSimulation(simulationArguments{:});");

            output = jsondecode(fileread(fullfile( ...
                outputDirectory,"simulation_summary.json")));
            decodedMetadata = ...
                output.Configuration.ResourceAllocation.Metadata;
            testCase.verifyEqual( ...
                string(decodedMetadata.Type),allocatorType);
            testCase.verifyEqual( ...
                string(decodedMetadata.NetworkSliceId),"global");
            testCase.verifyEqual(decodedMetadata.RandomSeed,2);
        end
    end
end
