classdef ResourceAllocatorSmokeTest < matlab.unittest.TestCase
    %RESOURCEALLOCATORSMOKETEST Full-simulator coverage of named allocators.

    properties (TestParameter)
        AllocatorType = { ...
            "ReuseDistance", ...
            "MaximumReuseDistance", ...
            "MinimumReusePower", ...
            "SensingBased", ...
            "Random", ...
            "Ordered"}
    end

    properties (SetAccess = private)
        TemporaryDirectory (1,1) string
    end

    methods (TestClassSetup)
        function createTemporaryDirectory(testCase)
            temporaryFolder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            testCase.TemporaryDirectory = ...
                string(temporaryFolder.Folder);
        end
    end

    methods (Test)
        function testNamedAllocatorRunsThroughSimulator( ...
                testCase,AllocatorType)
            allocatorType = string(AllocatorType);
            projectRoot = fileparts(fileparts(fileparts(fileparts( ...
                mfilename("fullpath")))));
            sourceDirectory = fullfile(projectRoot,"src");
            tomlDirectory = fullfile(projectRoot,"lib","matlab-toml");
            originalPath = path;
            testCase.addTeardown(@() path(originalPath));
            addpath(sourceDirectory);
            addpath(tomlDirectory);

            outputDirectory = fullfile( ...
                testCase.TemporaryDirectory,allocatorType);
            configurationFile = fullfile( ...
                projectRoot, "tests", "+v2xsimtest", "+fixtures", ...
                "config", "EtsiHighwayMediumMode1.toml");
            allocationPatch = struct( ...
                Type=allocatorType, RandomSeed=2);
            allocationPatch.(allocatorType) = struct();
            patchData = struct( ...
                Simulation=struct( ...
                    RandomSeed=2, DurationSeconds=0.2), ...
                Scenario=struct( ...
                    Type="BidirectionalHighway", ...
                    BidirectionalHighway=struct( ...
                        RandomSeed=2, ...
                        VehicleCount=4, ...
                        RoadLength=200, ...
                        MeanVehicleSpeed=10, ...
                        VehicleSpeedStandardDeviation=0, ...
                        RerollSpeedOnWrapAround=false)), ...
                Radio=struct( ...
                    Type="LteV2X", LteV2X=struct()), ...
                ResourceAllocation=allocationPatch, ...
                Outputs=disabledOutputs());
            configuration = v2xsim.config.load( ...
                configurationFile).resolve( ...
                    Patch=v2xsim.config.patch(patchData)); %#ok<NASGU>

            evalc("v2xsim.runSimulation(configuration," + ...
                "OutputDirectory=outputDirectory," + ...
                "RunLabel=allocatorType);");

            output = jsondecode(fileread(fullfile( ...
                outputDirectory,"simulation_summary.json")));
            decodedMetadata = ...
                output.Configuration.ResourceAllocation.Metadata;
            testCase.verifyEqual( ...
                string(decodedMetadata.Type),allocatorType);
            testCase.verifyEqual( ...
                string(decodedMetadata.NetworkSliceId),"global");
            testCase.verifyEqual(decodedMetadata.RandomSeed,2);
        end
    end
end

function result = disabledOutputs()
result = struct( ...
    PacketReceptionRatio=struct(Enabled=false), ...
    UpdateDelay=struct(Enabled=false), ...
    PacketDelay=struct(Enabled=false), ...
    DataAge=struct(Enabled=false), ...
    WirelessBlindSpot=struct(Enabled=false), ...
    AverageNeighborCount=struct(Enabled=false), ...
    ChannelBusyRatio=struct(Enabled=false));
end
