function packetReceptionRatios = runEtsiHighwayDensitySweep( ...
        outputDirectory, technology)
%RUNETSIHIGHWAYDENSITYSWEEP Run the three ETSI freeway traffic models.

arguments (Input)
    outputDirectory (1, 1) string
    technology (1, 1) string {mustBeMember(technology, ...
        ["LTE-V2X", "5G-V2X", "80211p"])}
end

arguments (Output)
    packetReceptionRatios (3, 1) double
end

projectRoot = fileparts(fileparts(fileparts(fileparts( ...
    mfilename("fullpath")))));
sourceDirectory = fullfile(projectRoot, "src");
tomlDirectory = fullfile(projectRoot, "lib", "matlab-toml");
addpath(sourceDirectory);
addpath(tomlDirectory);

configurationFile = fullfile( ...
    projectRoot, "tests", "+v2xsimtest", "+fixtures", ...
    "config", "EtsiHighwayMediumMode1.toml");
trafficModels = [ ...
    "HighSpeedLowDensity", ...
    "MediumSpeedMediumDensity", ...
    "LowSpeedHighDensity"];

packetReceptionRatios = zeros(numel(trafficModels),1);
for trafficModelIndex = 1:numel(trafficModels)
    trafficModel = trafficModels(trafficModelIndex);
    runDirectory = fullfile(outputDirectory,trafficModel);
    radioType = radioTypeForLegacyLabel(technology);
    radioPatch = struct(Type=radioType);
    radioPatch.(radioType) = struct();
    patchData = struct( ...
        Simulation=struct(DurationSeconds=2), ...
        Scenario=struct(EtsiHighway=struct( ...
            TrafficModel=trafficModel)), ...
        Radio=radioPatch, ...
        Outputs=struct( ...
            PacketReceptionRatio=struct(Enabled=false), ...
            UpdateDelay=struct(Enabled=false), ...
            PacketDelay=struct(Enabled=false), ...
            DataAge=struct(Enabled=false), ...
            WirelessBlindSpot=struct(Enabled=false), ...
            AverageNeighborCount=struct(Enabled=false), ...
            ChannelBusyRatio=struct(Enabled=false)));
    configuration = v2xsim.config.load(configurationFile).resolve( ...
        Patch=v2xsim.config.patch(patchData)); %#ok<NASGU>
    evalc("v2xsim.runSimulation(configuration," + ...
        "OutputDirectory=runDirectory," + ...
        "RunLabel=trafficModel + ""/"" + radioType);");

    summary = jsondecode(fileread(fullfile( ...
        runDirectory,"simulation_summary.json")));
    if technology == "80211p"
        metrics = summary.Results.Ieee80211p.AwarenessRangeMetrics;
    else
        metrics = summary.Results.CellularSidelink.AwarenessRangeMetrics;
    end
    packetReceptionRatios(trafficModelIndex) = ...
        metrics.PacketReceptionRatio;
end
end

function result = radioTypeForLegacyLabel(technology)
switch technology
    case "LTE-V2X"
        result = "LteV2X";
    case "5G-V2X"
        result = "NrV2X";
    case "80211p"
        result = "Ieee80211p";
end
end
