function packetReceptionRatios = runEtsiHighwayDensitySweep( ...
        outputDirectory, technology)
%RUNETSIHIGHWAYDENSITYSWEEP Run the three ETSI freeway traffic models.

arguments (Input)
    outputDirectory (1, 1) string
    technology (1, 1) string {mustBeMember(technology, ...
        ["LTE-V2X", "5G-V2X", "80211p"])}
end

arguments (Output)
    packetReceptionRatios (3, 1) double
end

projectRoot = fileparts(fileparts(fileparts(fileparts( ...
    mfilename("fullpath")))));
sourceDirectory = fullfile(projectRoot, "src");
simulatorDirectory = fullfile(projectRoot, "old_src");
addpath(sourceDirectory);
addpath(simulatorDirectory);

configurationFile = fullfile( ...
    simulatorDirectory, ...
    "ConfigFiles", ...
    "EtsiHighwayMediumMode1.cfg");
trafficModels = [ ...
    "HighSpeedLowDensity", ...
    "MediumSpeedMediumDensity", ...
    "LowSpeedHighDensity"];

packetReceptionRatios = zeros(numel(trafficModels),1);
for trafficModelIndex = 1:numel(trafficModels)
    trafficModel = trafficModels(trafficModelIndex);
    runDirectory = fullfile(outputDirectory,trafficModel);
    % The arguments are consumed by the command evaluated below.
    simulationArguments = { ...
        configurationFile, ...
        "simulation.RadioAccessMode", technology, ...
        "simulation.DurationSeconds", 2, ...
        "scenarioOptions.TrafficModel", trafficModel, ...
        "output.Directory", runDirectory, ...
        "output.PacketReceptionRatio.Enabled", false, ...
        "output.UpdateDelay.Enabled", false, ...
        "output.PacketDelay.Enabled", false, ...
        "output.DataAge.Enabled", false, ...
        "output.AverageNeighborCount.Enabled", false, ...
        "output.ChannelBusyRatio.Enabled", false}; %#ok<NASGU>
    evalc("WiLabV2Xsim(simulationArguments{:});");

    summary = jsondecode(fileread(fullfile( ...
        runDirectory,"simulation_summary.json")));
    if technology == "80211p"
        metrics = summary.Results.Ieee80211p.AwarenessRangeMetrics;
    else
        metrics = summary.Results.CellularSidelink.AwarenessRangeMetrics;
    end
    packetReceptionRatios(trafficModelIndex) = ...
        metrics.PacketReceptionRatio;
end
end
