classdef WorldRsuSmokeTest < matlab.unittest.TestCase
    %WORLDRSUSMOKETEST End-to-end smoke test with a fixed World RSU.

    properties (SetAccess = private)
        TemporaryDirectory (1,1) string
    end

    methods (TestClassSetup)
        function createTemporaryDirectory(testCase)
            temporaryFolder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            testCase.TemporaryDirectory = ...
                string(temporaryFolder.Folder);
        end
    end

    methods (Test)
        function testVehiclesAndRsuParticipateAsDistinct11pUes(testCase)
            output = testCase.runSimulation( ...
                "Ieee80211p", "Ieee80211p", ...
                "HighPriorityDenm", false, "11p");

            testCase.verifyUeCounts(output,0,5);
        end

        function testCv2xRsuRunsWithVehiclePositionError(testCase)
            output = testCase.runSimulation( ...
                "LteV2X", "LteV2X", "Cam", true, "cv2x");

            testCase.verifyUeCounts(output,5,0);
        end
    end

    methods (Access = private)
        function output = runSimulation( ...
                testCase,technology,rsuTechnology,packetType, ...
                usePositionError,testName)
            projectRoot = fileparts(fileparts(fileparts(fileparts( ...
                mfilename("fullpath")))));
            sourceDirectory = fullfile(projectRoot,"src");
            tomlDirectory = fullfile(projectRoot,"lib","matlab-toml");
            addpath(sourceDirectory);
            addpath(tomlDirectory);

            outputDirectory = fullfile( ...
                testCase.TemporaryDirectory,testName + "-output");
            configurationFile = fullfile( ...
                projectRoot, "tests", "+v2xsimtest", "+fixtures", ...
                "config", "EtsiHighwayMediumMode1.toml");
            scenarioPatch = struct( ...
                Type="BidirectionalHighway", ...
                BidirectionalHighway=struct( ...
                    RandomSeed=1, ...
                    VehicleCount=4, ...
                    RoadLength=200, ...
                    MeanVehicleSpeed=10, ...
                    VehicleSpeedStandardDeviation=0, ...
                    RerollSpeedOnWrapAround=false));
            radioPatch = struct(Type=technology);
            radioPatch.(technology) = struct();
            resourceAllocationPatch = struct();
            if usePositionError
                resourceAllocationPatch = struct( ...
                    Type="ReuseDistance", ...
                    ReuseDistance=struct( ...
                        PositionError95PercentileMeters=20));
            end
            roadsideUnits = {struct( ...
                Id="RSU1", ...
                Technology=rsuTechnology, ...
                PacketType=packetType, ...
                PositionMeters=[100, 5])};
            patchData = struct( ...
                Simulation=struct( ...
                    RandomSeed=1, DurationSeconds=0.2), ...
                Scenario=scenarioPatch, ...
                Radio=radioPatch, ...
                Infrastructure=struct( ...
                    RoadsideUnits={roadsideUnits}), ...
                Outputs=disabledOutputs());
            if ~isempty(fieldnames(resourceAllocationPatch))
                patchData.ResourceAllocation = ...
                    resourceAllocationPatch;
            end
            configuration = v2xsim.config.load( ...
                configurationFile).resolve( ...
                    Patch=v2xsim.config.patch(patchData)); %#ok<NASGU>

            pathBeforeSimulation = path;
            evalc("v2xsim.runSimulation(configuration," + ...
                "OutputDirectory=outputDirectory," + ...
                "RunLabel=testName);");
            testCase.verifyEqual(path, pathBeforeSimulation);

            output = jsondecode(fileread(fullfile( ...
                outputDirectory,"simulation_summary.json")));
        end

        function verifyUeCounts( ...
                testCase,output,expectedCv2xCount,expected11pCount)
            testCase.verifyEqual( ...
                output.Results.CellularSidelink.AverageUeCount, ...
                expectedCv2xCount);
            testCase.verifyEqual( ...
                output.Results.Ieee80211p.AverageUeCount, ...
                expected11pCount);
            testCase.verifyEqual( ...
                output.Results.Combined.AverageUeCount,5);
            testCase.verifyEqual( ...
                output.Configuration.Infrastructure. ...
                RoadSideUnitCount,1);
        end
    end
end

function result = disabledOutputs()
result = struct( ...
    PacketReceptionRatio=struct(Enabled=false), ...
    UpdateDelay=struct(Enabled=false), ...
    PacketDelay=struct(Enabled=false), ...
    DataAge=struct(Enabled=false), ...
    WirelessBlindSpot=struct(Enabled=false), ...
    AverageNeighborCount=struct(Enabled=false), ...
    ChannelBusyRatio=struct(Enabled=false));
end
