classdef Bazzi2020BlindSpotTest < matlab.unittest.TestCase
    %BAZZI2020BLINDSPOTTEST Bounded and publication-scale paper regressions.
    %   The short method exercises real evidence collection at both density
    %   extremes. Publication-strength conclusions remain an explicit run.

    properties (SetAccess = private)
        SimulatorRoot (1, 1) string
        OutputDirectory (1, 1) string
    end

    methods (TestClassSetup)
        function configureCampaign(testCase)
            testCase.SimulatorRoot = getSimulatorRoot();
            temporaryFolder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            testCase.OutputDirectory = string(temporaryFolder.Folder);
        end
    end

    methods (Test, TestTags = {'ShortCampaign'})
        function testShortenedProfileProducesBoundedRealEvidence(testCase)
            originalPath = path;
            originalStream = RandStream.getGlobalStream();
            originalStreamState = originalStream.State;
            originalWarningState = warning;
            environmentCleanup = onCleanup(@() restoreEnvironment( ...
                originalPath, originalStream, originalStreamState, ...
                originalWarningState));

            campaignDirectory = fullfile( ...
                testCase.OutputDirectory, "shortened");
            [aggregate, comparisons] = ...
                v2xsimregression.paper.bazzi2020blindspots. ...
                runPublishedCampaigns( ...
                    testCase.SimulatorRoot, ...
                    campaignDirectory, ...
                    Profile="shortened");

            testCase.verifyTrue(isfile(fullfile( ...
                campaignDirectory, "campaign-manifest.csv")));
            testCase.verifyTrue(isfile(fullfile( ...
                campaignDirectory, "campaign-progress.jsonl")));
            testCase.verifyTrue(isfile(fullfile( ...
                campaignDirectory, "campaign-seed-summary.csv")));
            testCase.verifyTrue(isfile(fullfile( ...
                campaignDirectory, "campaign-summary.csv")));
            testCase.verifyTrue(isfile(fullfile( ...
                campaignDirectory, "campaign-comparisons.csv")));
            testCase.verifyEqual(path, originalPath);
            testCase.verifyTrue(isequal( ...
                RandStream.getGlobalStream(), originalStream));
            testCase.verifyEqual( ...
                originalStream.State, originalStreamState);
            testCase.verifyEqual(warning, originalWarningState);

            testCase.verifyEqual(height(aggregate), 8);
            testCase.verifyEqual(height(comparisons), 8);
            testCase.verifyEqual(unique(aggregate.SeedCount), 3);
            testCase.verifyEqual(unique(aggregate.RoadLengthMeters), 300);
            testCase.verifyEqual( ...
                unique(aggregate.SimulationTimeSeconds), 12);
            testCase.verifyGreaterThan( ...
                aggregate.PrrTotalCount0To300, 0);
            testCase.verifyGreaterThanOrEqual( ...
                aggregate.PrrAuc0To300, 0);
            testCase.verifyLessThanOrEqual( ...
                aggregate.PrrAuc0To300, 1);
            testCase.verifyGreaterThanOrEqual( ...
                aggregate.WbsTailProbabilityAuc2To10Seconds, 0);

            for scheme = unique(aggregate.Scheme, "stable").'
                light = selectAggregate(aggregate, "light", scheme);
                congested = selectAggregate( ...
                    aggregate, "congested", scheme);
                testCase.verifyGreaterThan( ...
                    light.PrrAuc0To300, congested.PrrAuc0To300, ...
                    "The bounded high-density case must reduce PRR AUC.");
            end

            congestedLegacy = selectAggregate( ...
                aggregate, "congested", "legacy-p08");
            congestedCappedTwo = selectAggregate( ...
                aggregate, "congested", "capped-m2");
            congestedCappedFive = selectAggregate( ...
                aggregate, "congested", "capped-m5");
            testCase.verifyLessThan( ...
                congestedCappedTwo. ...
                WbsTailProbabilityAuc2To10Seconds, ...
                congestedCappedFive. ...
                WbsTailProbabilityAuc2To10Seconds, ...
                "A two-interval cap must expose less WBS tail than five.");
            testCase.verifyLessThan( ...
                congestedCappedFive. ...
                WbsTailProbabilityAuc2To10Seconds, ...
                congestedLegacy.WbsTailProbabilityAuc2To10Seconds, ...
                "The bounded cap must reduce congested WBS-tail exposure.");
            testCase.verifyLessThanOrEqual( ...
                abs(congestedCappedFive.PrrAuc0To300 - ...
                congestedLegacy.PrrAuc0To300), ...
                0.05, ...
                "The bounded five-interval cap must remain near legacy PRR.");

            progressLines = readlines(fullfile( ...
                campaignDirectory, "campaign-progress.jsonl"));
            testCase.verifyEqual( ...
                nnz(contains(progressLines, ...
                    '"Event":"completed"')), ...
                24);
            testCase.verifyFalse(any(contains( ...
                progressLines, '"Event":"failed"')));

            environmentCleanup; %#ok<VUNUS>
        end
    end

    methods (Test, TestTags = {'PublicationCampaign'})
        function testPublicationProfileReassertsFigures3And4(testCase)
            aggregate = ...
                v2xsimregression.paper.bazzi2020blindspots. ...
                runPublishedCampaigns( ...
                    testCase.SimulatorRoot, ...
                    fullfile( ...
                        testCase.OutputDirectory, "publication"), ...
                    Profile="publication");

            for scenario = ["light", "medium", "congested"]
                legacy = selectAggregate( ...
                    aggregate, scenario, "legacy-p08");
                for cappedScheme = [ ...
                        "capped-m2", "capped-m3", ...
                        "capped-m4", "capped-m5"]
                    capped = selectAggregate( ...
                        aggregate, scenario, cappedScheme);
                    testCase.verifyGreaterThanOrEqual( ...
                        capped.PrrRangeAt90Meters, ...
                        0.75 .* legacy.PrrRangeAt90Meters, ...
                        compose( ...
                            "%s must retain 75%% of reliable range.", ...
                            cappedScheme));
                    testCase.verifyLessThan( ...
                        capped.WbsThresholdCrossingSeconds, ...
                        legacy.WbsThresholdCrossingSeconds, ...
                        compose( ...
                            "%s must shorten the 1e-4 WBS duration.", ...
                            cappedScheme));
                end

                cappedTwo = selectAggregate( ...
                    aggregate, scenario, "capped-m2");
                cappedFive = selectAggregate( ...
                    aggregate, scenario, "capped-m5");
                testCase.verifyGreaterThanOrEqual( ...
                    cappedFive.PrrAuc0To300, ...
                    cappedTwo.PrrAuc0To300, ...
                    "A larger cap must preserve or improve PRR AUC.");
                testCase.verifyGreaterThan( ...
                    cappedFive.WbsTailProbabilityAuc2To10Seconds, ...
                    cappedTwo.WbsTailProbabilityAuc2To10Seconds, ...
                    "A larger cap must expose more WBS-tail risk.");
            end

            congestedLegacy = selectAggregate( ...
                aggregate, "congested", "legacy-p08");
            congestedCappedFive = selectAggregate( ...
                aggregate, "congested", "capped-m5");
            % A right-censored numeric value is the end of the generated
            % WBS window and therefore a lower bound, not an observed
            % crossing. A value above 10 s still supports this contract.
            testCase.verifyGreaterThan( ...
                congestedLegacy.WbsThresholdCrossingSeconds, 10, ...
                ["The congested legacy case must cross after 10 s or ", ...
                "be right-censored beyond 10 s."]);
            testCase.verifyLessThan( ...
                congestedCappedFive.WbsThresholdCrossingSeconds, 8, ...
                "The congested five-interval cap must cross before 8 s.");
        end
    end
end

function restoreEnvironment( ...
        originalPath, originalStream, originalStreamState, ...
        originalWarningState)
path(originalPath);
RandStream.setGlobalStream(originalStream);
originalStream.State = originalStreamState;
warning(originalWarningState);
end

function simulatorRoot = getSimulatorRoot()
simulatorRoot = string(getenv("V2XSIM_PAPER_SIMULATOR_ROOT"));
if simulatorRoot == ""
    simulatorRoot = string(fileparts(fileparts(fileparts(fileparts( ...
        fileparts(mfilename("fullpath")))))));
end
end

function row = selectAggregate(results, scenario, scheme)
row = results( ...
    results.Scenario == scenario & results.Scheme == scheme, :);
if height(row) ~= 1
    error( ...
        "v2xsimregression:bazzi2020blindspots:" + ...
        "NonuniqueAggregateSelection", ...
        "Expected one %s/%s aggregate row; selected %d.", ...
        scenario, scheme, height(row));
end
end
