classdef Bazzi2020ReducerTest < matlab.unittest.TestCase
    %BAZZI2020REDUCERTEST Fast orchestration and reducer contracts.

    methods (Test)
        function testConfigurationKeepsAllocationLoadSchedulerEnabled( ...
                testCase)
            data = loadPublishedConfiguration();

            testCase.verifyTrue( ...
                data.Application.ChannelLoad.Enabled);
            testCase.verifyEqual( ...
                data.Application.ChannelLoad. ...
                    MeasurementWindowSeconds, ...
                0.1);
            testCase.verifyEqual( ...
                data.Application.ChannelLoad.UpdateStepsPerWindow, ...
                100);
            testCase.verifyFalse( ...
                data.Application.CongestionControl.Enabled);
            testCase.verifyFalse( ...
                data.Outputs.ChannelBusyRatio.Enabled);
        end

        function testConfigurationLocksPublishedRadioSetup(testCase)
            data = loadPublishedConfiguration();

            testCase.verifyEqual(data.SchemaVersion, 1);
            testCase.verifyEqual( ...
                data.Scenario.Type, "BidirectionalHighway");
            testCase.verifyEqual(data.Radio.Type, "LteV2X");
            testCase.verifyEqual( ...
                data.Application.PacketSizeBytes, 300);
            testCase.verifyEqual( ...
                data.Application. ...
                    ResourceReservationIntervalSeconds, ...
                0.1);
            testCase.verifyEqual( ...
                data.Application.PacketGeneration.IntervalSeconds, ...
                0.1);
            testCase.verifyEqual(data.Radio.BandwidthMHz, 10);
            testCase.verifyEqual(data.Radio.TransmitPowerDbm, 23);
            testCase.verifyEqual( ...
                data.Radio.TransmitAntennaGainDb, 3);
            testCase.verifyEqual( ...
                data.Radio.ReceiveAntennaGainDb, 3);
            testCase.verifyEqual( ...
                data.Radio.ReceiverNoiseFigureDb, 9);
            testCase.verifyEqual( ...
                data.Channel.PathLoss.Model, "WinnerPlusB1");
            testCase.verifyFalse( ...
                data.Channel.RayleighFadingEnabled);
            testCase.verifyEqual( ...
                data.Channel.Shadowing.LosStandardDeviationDb, 3);
            testCase.verifyEqual( ...
                data.Channel.Shadowing.NlosStandardDeviationDb, 4);
            testCase.verifyEqual(data.Radio.LteV2X.Mcs, 6);
            testCase.verifyEqual( ...
                data.Channel.PacketError.SidelinkLosThresholdDb, ...
                5.79);
            testCase.verifyEqual( ...
                data.ResourceAllocation.SensingBased. ...
                    ReselectionCounterMinimum, ...
                5);
            testCase.verifyEqual( ...
                data.ResourceAllocation.SensingBased. ...
                    ReselectionCounterMaximum, ...
                15);
            testCase.verifyEqual( ...
                data.Awareness.RangesMeters, [100, 300]);
        end

        function testShortenedManifestIsStableAndSeedPaired(testCase)
            manifest = ...
                v2xsimregression.paper.bazzi2020blindspots. ...
                createCampaignManifest( ...
                    "shortened", "campaign-output", 10:12);

            testCase.verifyEqual(height(manifest), 24);
            testCase.verifyEqual( ...
                manifest.Scenario(1:3), repmat("light", 3, 1));
            testCase.verifyEqual( ...
                manifest.Scheme(1:3), repmat("legacy-p0", 3, 1));
            testCase.verifyEqual(manifest.SimulationSeed(1:3), (10:12).');
            testCase.verifyEqual( ...
                manifest.SimulationSeed, manifest.ScenarioSeed);
            testCase.verifyEqual( ...
                manifest.SimulationSeed, manifest.AllocatorSeed);
            testCase.verifyEqual( ...
                numel(unique(manifest.OutputDirectory)), ...
                height(manifest), ...
                "Every work item must own an isolated output directory.");
            testCase.verifyEqual( ...
                unique(manifest.VehicleCount( ...
                    manifest.Scenario == "light")), 30);
            testCase.verifyEqual( ...
                unique(manifest.VehicleCount( ...
                    manifest.Scenario == "congested")), 120);
            testCase.verifyEqual( ...
                unique(manifest.SpeedKilometersPerHour( ...
                    manifest.Scenario == "light")), 140);
            testCase.verifyEqual( ...
                unique(manifest.SpeedKilometersPerHour( ...
                    manifest.Scenario == "congested")), 50);
            testCase.verifyEqual( ...
                unique(manifest.RoadLengthMeters), 300);
            testCase.verifyEqual( ...
                unique(manifest.SimulationTimeSeconds), 12);
            testCase.verifyEqual( ...
                unique( ...
                    manifest.WirelessBlindSpotMaximumDelaySeconds), ...
                10);
            testCase.verifyEqual( ...
                unique(manifest.Scheme, "stable").', [ ...
                    "legacy-p0", "legacy-p08", ...
                    "capped-m2", "capped-m5"]);
            verifySchemeParameters( ...
                testCase, manifest, "legacy-p0", 0, Inf);
            verifySchemeParameters( ...
                testCase, manifest, "legacy-p08", 0.8, Inf);
            verifySchemeParameters( ...
                testCase, manifest, "capped-m2", 0.8, 2);
            verifySchemeParameters( ...
                testCase, manifest, "capped-m5", 0.8, 5);

            repeated = ...
                v2xsimregression.paper.bazzi2020blindspots. ...
                createCampaignManifest( ...
                    "shortened", "campaign-output", 10:12);
            testCase.verifyEqual(repeated, manifest);
        end

        function testPublicationManifestCoversFigures3And4(testCase)
            manifest = ...
                v2xsimregression.paper.bazzi2020blindspots. ...
                createCampaignManifest( ...
                    "publication", "campaign-output", 10:19);

            testCase.verifyEqual(height(manifest), 180);
            testCase.verifyEqual( ...
                unique(manifest.RoadLengthMeters), 4000);
            testCase.verifyEqual( ...
                unique(manifest.SimulationTimeSeconds), 120);
            testCase.verifyEqual( ...
                unique(manifest.VehicleCount).', [400, 800, 1600]);
            testCase.verifyEqual( ...
                unique(manifest.SimulationSeed, "stable").', 10:19);
            testCase.verifyEqual( ...
                unique(manifest.SpeedKilometersPerHour( ...
                    manifest.Scenario == "light")), 140);
            testCase.verifyEqual( ...
                unique(manifest.SpeedKilometersPerHour( ...
                    manifest.Scenario == "medium")), 100);
            testCase.verifyEqual( ...
                unique(manifest.SpeedKilometersPerHour( ...
                    manifest.Scenario == "congested")), 50);
            testCase.verifyEqual( ...
                unique(manifest.Scheme, "stable").', [ ...
                    "legacy-p0", "legacy-p08", ...
                    "capped-m2", "capped-m3", ...
                    "capped-m4", "capped-m5"]);
            verifySchemeParameters( ...
                testCase, manifest, "legacy-p0", 0, Inf);
            verifySchemeParameters( ...
                testCase, manifest, "legacy-p08", 0.8, Inf);
            for cap = 2:5
                verifySchemeParameters( ...
                    testCase, manifest, "capped-m" + cap, 0.8, cap);
            end
        end

        function testManifestRejectsSeedAboveUint32Range(testCase)
            testCase.verifyError( ...
                @() v2xsimregression.paper.bazzi2020blindspots. ...
                    createCampaignManifest( ...
                        "shortened", "campaign-output", 2^32), ...
                "v2xsimregression:bazzi2020blindspots:InvalidRandomSeed");
        end

        function testRunnerRefusesNonemptyOutputDirectory(testCase)
            temporaryFolder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            outputDirectory = string(temporaryFolder.Folder);
            writelines("existing research artifact", ...
                fullfile(outputDirectory, "do-not-overwrite.txt"));

            testCase.verifyError( ...
                @() v2xsimregression.paper.bazzi2020blindspots. ...
                    runPublishedCampaigns( ...
                        getSimulatorRoot(), outputDirectory, ...
                        Profile="shortened", ...
                        RandomSeeds=10, ...
                        ExecutionMode="serial", ...
                        BootstrapSampleCount=40), ...
                "v2xsimregression:bazzi2020blindspots:OutputNotEmpty");
        end

        function testRunnerWritesCsvAndRestoresEnvironment(testCase)
            temporaryFolder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            temporaryRoot = string(temporaryFolder.Folder);
            simulatorRoot = createMockSimulator( ...
                fullfile(temporaryRoot, "simulator"), false);
            outputDirectory = fullfile(temporaryRoot, "campaign");
            environment = captureEnvironment();
            cleanup = onCleanup(@() restoreEnvironment(environment));

            [aggregate, comparisons] = ...
                v2xsimregression.paper.bazzi2020blindspots. ...
                runPublishedCampaigns( ...
                    simulatorRoot, outputDirectory, ...
                    Profile="shortened", ...
                    RandomSeeds=10, ...
                    ExecutionMode="serial", ...
                    BootstrapSampleCount=40);

            testCase.verifyEqual(height(aggregate), 8);
            testCase.verifyEqual(height(comparisons), 8);
            testCase.verifyEqual( ...
                aggregate.Scenario.', ...
                repelem(["light", "congested"], 4));
            testCase.verifyEqual( ...
                aggregate.Scheme.', repmat([ ...
                    "legacy-p0", "legacy-p08", ...
                    "capped-m2", "capped-m5"], 1, 2));
            for fileName = [ ...
                    "campaign-manifest.csv", ...
                    "campaign-progress.jsonl", ...
                    "campaign-seed-summary.csv", ...
                    "campaign-summary.csv", ...
                    "campaign-comparisons.csv"]
                testCase.verifyTrue(isfile(fullfile( ...
                    outputDirectory, fileName)));
            end
            persistedManifest = readtable(fullfile( ...
                outputDirectory, "campaign-manifest.csv"), ...
                TextType="string");
            testCase.verifyEqual(height(persistedManifest), 8);
            testCase.verifyEqual( ...
                persistedManifest.WorkItemIndex, (1:8).');
            progressEvents = readProgressEvents(fullfile( ...
                outputDirectory, "campaign-progress.jsonl"));
            eventTypes = string({progressEvents.Event});
            testCase.verifyEqual(nnz(eventTypes == "queued"), 8);
            testCase.verifyEqual(nnz(eventTypes == "heartbeat"), 24);
            testCase.verifyEqual(nnz(eventTypes == "completed"), 8);
            testCase.verifyEqual(nnz(eventTypes == "failed"), 0);
            verifyEnvironment(testCase, environment);

            cleanup; %#ok<VUNUS>
        end

        function testRunnerRestoresEnvironmentAfterWorkItemFailure( ...
                testCase)
            temporaryFolder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            temporaryRoot = string(temporaryFolder.Folder);
            simulatorRoot = createMockSimulator( ...
                fullfile(temporaryRoot, "simulator"), true);
            outputDirectory = fullfile(temporaryRoot, "campaign");
            environment = captureEnvironment();
            cleanup = onCleanup(@() restoreEnvironment(environment));

            testCase.verifyError( ...
                @() v2xsimregression.paper.bazzi2020blindspots. ...
                    runPublishedCampaigns( ...
                        simulatorRoot, outputDirectory, ...
                        Profile="shortened", ...
                        RandomSeeds=10, ...
                        ExecutionMode="serial", ...
                        BootstrapSampleCount=40), ...
                "v2xsimregression:execution:MultipleWorkItemsFailed");
            testCase.verifyTrue(isfile(fullfile( ...
                outputDirectory, "campaign-manifest.csv")));
            progressEvents = readProgressEvents(fullfile( ...
                outputDirectory, "campaign-progress.jsonl"));
            eventTypes = string({progressEvents.Event});
            testCase.verifyEqual(nnz(eventTypes == "queued"), 8);
            testCase.verifyEqual(nnz(eventTypes == "heartbeat"), 8);
            testCase.verifyEqual(nnz(eventTypes == "failed"), 8);
            testCase.verifyEqual(nnz(eventTypes == "completed"), 0);
            verifyEnvironment(testCase, environment);

            cleanup; %#ok<VUNUS>
        end

        function testSerialAndParallelRunnerResultsHaveStableOrder( ...
                testCase)
            testCase.assumeTrue( ...
                ~isempty(ver("parallel")) && ...
                license("test", "Distrib_Computing_Toolbox"), ...
                "Parallel Computing Toolbox is unavailable.");
            temporaryFolder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            temporaryRoot = string(temporaryFolder.Folder);
            simulatorRoot = createMockSimulator( ...
                fullfile(temporaryRoot, "simulator"), false);

            [serialAggregate, serialComparisons] = ...
                v2xsimregression.paper.bazzi2020blindspots. ...
                runPublishedCampaigns( ...
                    simulatorRoot, ...
                    fullfile(temporaryRoot, "serial"), ...
                    Profile="shortened", ...
                    RandomSeeds=10, ...
                    ExecutionMode="serial", ...
                    BootstrapSampleCount=40);
            [parallelAggregate, parallelComparisons] = ...
                v2xsimregression.paper.bazzi2020blindspots. ...
                runPublishedCampaigns( ...
                    simulatorRoot, ...
                    fullfile(temporaryRoot, "parallel"), ...
                    Profile="shortened", ...
                    RandomSeeds=10, ...
                    ExecutionMode="parallel", ...
                    BootstrapSampleCount=40);

            testCase.verifyEqual( ...
                removevars(serialAggregate, "OutputDirectory"), ...
                removevars(parallelAggregate, "OutputDirectory"));
            testCase.verifyEqual( ...
                serialComparisons, parallelComparisons);
        end

        function testCrossingInterpolationAndCensoring(testCase)
            crossingFunction = @(x, y) ...
                v2xsimregression.paper.bazzi2020blindspots. ...
                firstDownwardCrossing(x, y, 1e-4);

            [crossedValue, crossedStatus] = crossingFunction( ...
                [1; 2; 3], [2e-4; 1.5e-4; 0.5e-4]);
            testCase.verifyEqual(crossedValue, 2.5, AbsTol=1e-14);
            testCase.verifyEqual(crossedStatus, "crossed");

            [leftValue, leftStatus] = crossingFunction( ...
                [0.1; 0.2], [0.5e-4; 0.25e-4]);
            testCase.verifyEqual(leftValue, 0.1);
            testCase.verifyEqual(leftStatus, "left_censored");

            [rightValue, rightStatus] = crossingFunction( ...
                [10; 20], [3e-4; 2e-4]);
            testCase.verifyEqual(rightValue, 20);
            testCase.verifyEqual(rightStatus, "right_censored");
        end

        function testPoolsRawCountsBeforeCalculatingMetrics(testCase)
            [firstPrr, secondPrr] = syntheticPrrOutputs();
            [firstWbs, secondWbs] = syntheticWbsOutputs();

            [metrics, pooledPrr, pooledWbs] = ...
                v2xsimregression.paper.bazzi2020blindspots. ...
                reduceCountOutputs( ...
                    {firstPrr, secondPrr}, ...
                    {firstWbs, secondWbs}, ...
                    WirelessBlindSpotMaximumDelaySeconds=15);

            expectedCorrect = ...
                firstPrr(:, 2) + secondPrr(:, 2);
            expectedTotal = ...
                firstPrr(:, 5) + secondPrr(:, 5);
            expectedPrr = expectedCorrect ./ expectedTotal;
            expectedAuc = trapz( ...
                [0; (10:10:300).'], ...
                [expectedPrr(1); expectedPrr]) ./ 300;
            testCase.verifyEqual( ...
                pooledPrr.CorrectCount, expectedCorrect);
            testCase.verifyEqual( ...
                pooledPrr.TotalCount, expectedTotal);
            testCase.verifyEqual( ...
                pooledPrr.PacketReceptionRatio, expectedPrr, ...
                AbsTol=1e-14);
            testCase.verifyEqual( ...
                metrics.PrrAuc0To300, expectedAuc, ...
                AbsTol=1e-14);
            testCase.verifyEqual( ...
                metrics.PrrCorrectCount0To300, ...
                sum(expectedCorrect));
            testCase.verifyEqual( ...
                metrics.PrrTotalCount0To300, sum(expectedTotal));

            expectedWbsGreaterOrEqual = ...
                firstWbs(:, 2) + secondWbs(:, 2);
            expectedWbsTotal = ...
                sum(firstWbs(:, 2:3), 2) + ...
                sum(secondWbs(:, 2:3), 2);
            expectedWbsProbability = ...
                expectedWbsGreaterOrEqual ./ expectedWbsTotal;
            tailRows = ...
                pooledWbs.DurationSeconds >= 2 & ...
                pooledWbs.DurationSeconds <= 10;
            expectedWbsAuc = trapz( ...
                pooledWbs.DurationSeconds(tailRows), ...
                expectedWbsProbability(tailRows));
            testCase.verifyEqual( ...
                pooledWbs.GreaterOrEqualCount, ...
                expectedWbsGreaterOrEqual);
            testCase.verifyEqual( ...
                pooledWbs.Probability, expectedWbsProbability, ...
                AbsTol=1e-14);
            testCase.verifyEqual( ...
                metrics.WbsTailProbabilityAuc2To10Seconds, ...
                expectedWbsAuc, AbsTol=1e-14);
            testCase.verifyEqual( ...
                metrics.WbsThresholdCrossingStatus, "crossed");
        end

        function testPrrReductionIgnoresValidBinsBeyond300Meters( ...
                testCase)
            [prrOutput, ~] = syntheticPrrOutputs();
            [wbsOutput, ~] = syntheticWbsOutputs();
            extraDistanceRow = [310, 1, 2, 0, 3, 1 / 3];

            baseline = ...
                v2xsimregression.paper.bazzi2020blindspots. ...
                reduceCountOutputs( ...
                    {prrOutput}, {wbsOutput}, ...
                    WirelessBlindSpotMaximumDelaySeconds=15);
            extended = ...
                v2xsimregression.paper.bazzi2020blindspots. ...
                reduceCountOutputs( ...
                    {[prrOutput; extraDistanceRow]}, {wbsOutput}, ...
                    WirelessBlindSpotMaximumDelaySeconds=15);

            testCase.verifyEqual(extended, baseline);
        end

        function testRejectsInconsistentPrrCounts(testCase)
            [prrOutput, ~] = syntheticPrrOutputs();
            [wbsOutput, ~] = syntheticWbsOutputs();
            prrOutput(1, 5) = prrOutput(1, 5) + 1;

            testCase.verifyError( ...
                @() v2xsimregression.paper.bazzi2020blindspots. ...
                    reduceCountOutputs( ...
                        {prrOutput}, {wbsOutput}, ...
                        WirelessBlindSpotMaximumDelaySeconds=15), ...
                "v2xsimregression:bazzi2020blindspots:" + ...
                "InconsistentPrrCounts");

            [prrOutput, ~] = syntheticPrrOutputs();
            prrOutput(1, 6) = NaN;
            testCase.verifyError( ...
                @() v2xsimregression.paper.bazzi2020blindspots. ...
                    reduceCountOutputs( ...
                        {prrOutput}, {wbsOutput}, ...
                        WirelessBlindSpotMaximumDelaySeconds=15), ...
                "v2xsimregression:bazzi2020blindspots:" + ...
                "InvalidPrrRatio");
        end

        function testPairedBootstrapIsDeterministicAndStreamLocal( ...
                testCase)
            manifest = ...
                v2xsimregression.paper.bazzi2020blindspots. ...
                createCampaignManifest( ...
                    "shortened", "campaign-output", 10:14);
            seedResults = syntheticSeedSummary(manifest);

            originalStream = RandStream.getGlobalStream();
            originalState = originalStream.State;
            cleanup = onCleanup(@() restoreGlobalStream( ...
                originalStream, originalState));

            first = ...
                v2xsimregression.paper.bazzi2020blindspots. ...
                buildPairedComparisons( ...
                    seedResults, "shortened", 10:14, 200);
            second = ...
                v2xsimregression.paper.bazzi2020blindspots. ...
                buildPairedComparisons( ...
                    seedResults, "shortened", 10:14, 200);

            testCase.verifyEqual(first, second);
            testCase.verifyEqual(height(first), 8);
            testCase.verifyEqual( ...
                originalStream.State, originalState, ...
                "Bootstrap resampling must not consume the global stream.");
            legacyTradeoff = first( ...
                first.Scenario == "light" & ...
                first.ReferenceScheme == "legacy-p0" & ...
                first.CandidateScheme == "legacy-p08", :);
            testCase.verifyGreaterThan( ...
                legacyTradeoff.PrrAucDifferenceLower95Percentile, 0);
            testCase.verifyGreaterThan( ...
                legacyTradeoff. ...
                WbsTailAucDifferenceLower95Percentile, 0);
        end

        function testPairedComparisonRejectsMissingSeed(testCase)
            manifest = ...
                v2xsimregression.paper.bazzi2020blindspots. ...
                createCampaignManifest( ...
                    "shortened", "campaign-output", 10:14);
            seedResults = syntheticSeedSummary(manifest);
            missingRow = ...
                seedResults.Scenario == "light" & ...
                seedResults.Scheme == "legacy-p08" & ...
                seedResults.RandomSeed == 12;
            seedResults(missingRow, :) = [];

            testCase.verifyError( ...
                @() v2xsimregression.paper.bazzi2020blindspots. ...
                    buildPairedComparisons( ...
                        seedResults, "shortened", 10:14, 100), ...
                "v2xsimregression:bazzi2020blindspots:UnpairedSeeds");
        end
    end
end

function data = loadPublishedConfiguration()
simulatorRoot = getSimulatorRoot();
originalPath = path;
cleanup = onCleanup(@() path(originalPath));
addpath(fullfile(simulatorRoot, "src"));
addpath(fullfile(simulatorRoot, "lib", "matlab-toml"));
configurationFile = fullfile( ...
    fileparts(mfilename("fullpath")), ...
    "config", "bazzi2020.toml");
template = v2xsim.config.load(configurationFile);
configuration = template.resolve();
data = configuration.Data;
cleanup; %#ok<VUNUS>
end

function verifySchemeParameters( ...
        testCase, manifest, scheme, keepProbability, maximumIntervals)
rows = manifest(manifest.Scheme == scheme, :);
testCase.assertNotEmpty(rows);
testCase.verifyEqual(unique(rows.KeepResourceProbability), keepProbability);
testCase.verifyEqual( ...
    unique(rows.MaximumConsecutiveReservationIntervals), maximumIntervals);
end

function simulatorRoot = getSimulatorRoot()
simulatorRoot = string(fileparts(fileparts(fileparts(fileparts( ...
    fileparts(mfilename("fullpath")))))));
end

function simulatorRoot = createMockSimulator( ...
        simulatorRoot, shouldFail)
sourcePackage = fullfile(simulatorRoot, "src", "+v2xsim");
configurationPackage = fullfile(sourcePackage, "+config");
mkdir(configurationPackage);
mkdir(fullfile(simulatorRoot, "regression-tests"));
mkdir(fullfile(simulatorRoot, "lib", "matlab-toml"));

writelines([ ...
    "function result = load(~)", ...
    "%LOAD Return an unresolved mock template.", ...
    "result = v2xsim.config.MockTemplate();", ...
    "end"], ...
    fullfile(configurationPackage, "load.m"));
writelines([ ...
    "function result = patch(data)", ...
    "%PATCH Preserve the runner's nested patch data.", ...
    "arguments (Input)", ...
    "    data (1, 1) struct", ...
    "end", ...
    "result = data;", ...
    "end"], ...
    fullfile(configurationPackage, "patch.m"));
writelines([ ...
    "classdef MockTemplate", ...
    "    %MOCKTEMPLATE Minimal configuration-template test double.", ...
    "    methods", ...
    "        function result = resolve(obj, options)", ...
    "            arguments (Input)", ...
    "                obj (1, 1) v2xsim.config.MockTemplate", ...
    "                options.Patch (1, 1) struct = struct()", ...
    "            end", ...
    "            result = options.Patch;", ...
    "        end", ...
    "    end", ...
    "end"], ...
    fullfile(configurationPackage, "MockTemplate.m"));

mockFile = fullfile(sourcePackage, "runSimulation.m");
if shouldFail
    writelines([ ...
        "function runSimulation(configuration, options)", ...
        "%RUNSIMULATION Deliberate runner-cleanup failure fixture.", ...
        "arguments (Input)", ...
        "    configuration (1, 1) struct", ...
        "    options.OutputDirectory (1, 1) string", ...
        "    options.RunLabel (1, 1) string", ...
        "    options.ProgressFcn (1, 1) function_handle = @(~) []", ...
        "end", ...
        "assert(isfield(configuration, ""Simulation""));", ...
        "options.ProgressFcn(mockProgressEvent(" + ...
            """initializing"",0,configuration.Simulation.DurationSeconds));", ...
        "error(""v2xsimtest:MockSimulationFailure"", " + ...
            """Deliberate mock simulation failure."");", ...
        "end", ...
        mockProgressEventFunctionLines()], mockFile);
    return
end

writelines([ ...
    "function runSimulation(configuration, options)", ...
    "%RUNSIMULATION Count-preserving runner orchestration fixture.", ...
    "arguments (Input)", ...
    "    configuration (1, 1) struct", ...
    "    options.OutputDirectory (1, 1) string", ...
    "    options.RunLabel (1, 1) string", ...
    "    options.ProgressFcn (1, 1) function_handle = @(~) []", ...
    "end", ...
    "assert(configuration.Radio.Type == ""LteV2X"");", ...
    "assert(strlength(options.RunLabel) > 0);", ...
    "duration = configuration.Simulation.DurationSeconds;", ...
    "options.ProgressFcn(mockProgressEvent(""initializing"",0,duration));", ...
    "options.ProgressFcn(mockProgressEvent(" + ...
        """simulating"",duration ./ 2,duration));", ...
    "outputDirectory = options.OutputDirectory;", ...
    "mkdir(outputDirectory);", ...
    "distances = (10:10:300).';", ...
    "total = repmat(100, numel(distances), 1);", ...
    "correct = 100 - distances ./ 10;", ...
    "packetReceptionRatio = [distances, correct, " + ...
        "total - correct, zeros(size(total)), total, correct ./ total];", ...
    "writematrix(packetReceptionRatio, fullfile(outputDirectory, " + ...
        """packet_reception_ratio_LTE.csv""));", ...
    "maximumDelay = configuration.Outputs." + ...
        "WirelessBlindSpot.MaximumDelaySeconds;", ...
    "durations = (0.1:0.1:maximumDelay).';", ...
    "wbsTotal = repmat(100000, numel(durations), 1);", ...
    "greaterOrEqual = round(wbsTotal .* 10 .^ (-durations ./ 3));", ...
    "shorter = wbsTotal - greaterOrEqual;", ...
    "probability = greaterOrEqual ./ wbsTotal;", ...
    "wirelessBlindSpot = [durations, greaterOrEqual, shorter, " + ...
        "probability, greaterOrEqual, shorter, probability];", ...
    "writematrix(wirelessBlindSpot, fullfile(outputDirectory, " + ...
        """wireless_blind_spot_LTE.csv""));", ...
    "writelines(""{}"", fullfile(outputDirectory, " + ...
        """simulation_summary.json""));", ...
    "options.ProgressFcn(mockProgressEvent(" + ...
        """finalizing"",duration,duration));", ...
    "end", ...
    mockProgressEventFunctionLines()], mockFile);
end

function lines = mockProgressEventFunctionLines()
lines = [ ...
    "function event = mockProgressEvent(stage,time,duration)", ...
    "event = struct( ...", ...
    "    Stage=stage, ...", ...
    "    SimulatedTimeSeconds=time, ...", ...
    "    SimulationDurationSeconds=duration, ...", ...
    "    FractionComplete=time ./ duration, ...", ...
    "    ElapsedWallSeconds=time, ...", ...
    "    Message="""");", ...
    "end"];
end

function events = readProgressEvents(progressLogFile)
lines = readlines(progressLogFile);
lines(strlength(lines) == 0) = [];
eventCells = cell(1, numel(lines));
for lineIndex = 1:numel(lines)
    eventCells{lineIndex} = jsondecode(lines(lineIndex));
end
events = [eventCells{:}];
end

function environment = captureEnvironment()
stream = RandStream.getGlobalStream();
environment = struct( ...
    Path=path, ...
    Stream=stream, ...
    StreamState=stream.State, ...
    WarningState=warning);
end

function verifyEnvironment(testCase, environment)
testCase.verifyEqual(path, environment.Path);
testCase.verifyTrue(isequal( ...
    RandStream.getGlobalStream(), environment.Stream));
testCase.verifyEqual( ...
    environment.Stream.State, environment.StreamState);
testCase.verifyEqual(warning, environment.WarningState);
end

function restoreEnvironment(environment)
path(environment.Path);
RandStream.setGlobalStream(environment.Stream);
environment.Stream.State = environment.StreamState;
warning(environment.WarningState);
end

function [first, second] = syntheticPrrOutputs()
distances = (10:10:300).';
firstTotal = repmat(100, numel(distances), 1);
secondTotal = repmat(300, numel(distances), 1);
firstCorrect = round(firstTotal .* linspace(0.99, 0.55, ...
    numel(distances)).');
secondCorrect = round(secondTotal .* linspace(0.98, 0.65, ...
    numel(distances)).');
firstError = firstTotal - firstCorrect;
secondError = secondTotal - secondCorrect;
first = [ ...
    distances, firstCorrect, firstError, ...
    zeros(size(distances)), firstTotal, ...
    firstCorrect ./ firstTotal];
second = [ ...
    distances, secondCorrect, secondError, ...
    zeros(size(distances)), secondTotal, ...
    secondCorrect ./ secondTotal];
end

function [first, second] = syntheticWbsOutputs()
durations = (0.1:0.1:15).';
firstTotal = 100000;
secondTotal = 300000;
probabilities = 10 .^ (-durations);
firstGreaterOrEqual = round(firstTotal .* probabilities);
secondGreaterOrEqual = round(secondTotal .* probabilities);
firstShorter = firstTotal - firstGreaterOrEqual;
secondShorter = secondTotal - secondGreaterOrEqual;
firstProbability = firstGreaterOrEqual ./ firstTotal;
secondProbability = secondGreaterOrEqual ./ secondTotal;
first = [ ...
    durations, firstGreaterOrEqual, firstShorter, firstProbability, ...
    firstGreaterOrEqual, firstShorter, firstProbability];
second = [ ...
    durations, secondGreaterOrEqual, secondShorter, secondProbability, ...
    secondGreaterOrEqual, secondShorter, secondProbability];
end

function seedResults = syntheticSeedSummary(manifest)
seedResults = manifest(:, [ ...
    "Profile", "Scenario", "DensityVehiclesPerKilometer", ...
    "SpeedKilometersPerHour", "Scheme", "SimulationSeed"]);
seedResults.Properties.VariableNames(end) = "RandomSeed";
seedOffset = 0.0001 .* seedResults.RandomSeed;
scenarioOffset = 0.01 .* ...
    double(seedResults.Scenario == "congested");

prrSchemeEffect = zeros(height(seedResults), 1);
wbsSchemeEffect = zeros(height(seedResults), 1);
rangeSchemeEffect = zeros(height(seedResults), 1);
for scheme = unique(seedResults.Scheme, "stable").'
    selected = seedResults.Scheme == scheme;
    if scheme == "legacy-p0"
        prrSchemeEffect(selected) = 0;
        rangeSchemeEffect(selected) = 0;
        wbsSchemeEffect(selected) = 0.01;
    elseif scheme == "legacy-p08"
        prrSchemeEffect(selected) = 0.08;
        rangeSchemeEffect(selected) = 20;
        wbsSchemeEffect(selected) = 0.02;
    elseif scheme == "capped-m2"
        prrSchemeEffect(selected) = 0.04;
        rangeSchemeEffect(selected) = 10;
        wbsSchemeEffect(selected) = 0.004;
    else
        prrSchemeEffect(selected) = 0.07;
        rangeSchemeEffect(selected) = 18;
        wbsSchemeEffect(selected) = 0.008;
    end
end

seedResults.PrrAuc0To300 = ...
    0.7 + scenarioOffset + seedOffset + prrSchemeEffect;
seedResults.PrrRangeAt90Meters = ...
    100 + 100 .* scenarioOffset + rangeSchemeEffect;
seedResults.WbsTailProbabilityAuc2To10Seconds = ...
    wbsSchemeEffect + seedOffset;
end

function restoreGlobalStream(stream, state)
RandStream.setGlobalStream(stream);
stream.State = state;
end
