classdef Bazzi2020AnalyticalTest < matlab.unittest.TestCase
    %BAZZI2020ANALYTICALTEST Equations (1)-(12) scientific regression.
    %   Reference DOI: 10.1109/TVT.2020.3001074.

    methods (Test)
        function tbeAndIntervalCountDistributions(testCase)
            analysis = ...
                "v2xsimregression.paper.bazzi2020blindspots.analysis.";

            [periods, probability] = feval( ...
                analysis + "tbePmf", 5, 15);
            testCase.verifyEqual(periods, 5:15);
            testCase.verifyEqual( ...
                probability, ones(1, 11) ./ 11, AbsTol=eps);

            [counts, cappedProbability, omittedProbability] = feval( ...
                analysis + "intervalCountPmf", 0.8, 5);
            testCase.verifyEqual(counts, 1:5);
            testCase.verifyEqual( ...
                cappedProbability, ...
                [0.2, 0.16, 0.128, 0.1024, 0.4096], ...
                AbsTol=10 * eps);
            testCase.verifyEqual(omittedProbability, 0);
            testCase.verifyEqual(sum(cappedProbability), 1, ...
                AbsTol=10 * eps);
        end

        function discreteConvolutionHasExpectedFiniteSupport(testCase)
            [periods, probability, omittedProbability] = ...
                v2xsimregression.paper.bazzi2020blindspots.analysis. ...
                tbcPmf( ...
                0.8, ...
                MaximumConsecutiveReservationIntervals=5);

            testCase.verifyEqual(periods([1, end]), [5, 75]);
            testCase.verifyGreaterThan(probability([1, end]), [0, 0]);
            testCase.verifyEqual(sum(probability), 1, ...
                AbsTol=2e-14);
            testCase.verifyEqual(omittedProbability, 0);

            [forcedPeriods, forcedProbability] = ...
                v2xsimregression.paper.bazzi2020blindspots.analysis. ...
                tbcPmf( ...
                1, ...
                MaximumConsecutiveReservationIntervals=5);
            testCase.verifyEqual(forcedPeriods([1, end]), [25, 75]);
            testCase.verifyEqual(sum(forcedProbability), 1, ...
                AbsTol=2e-14);
        end

        function expectedTbcDurationMatchesClosedForm(testCase)
            [legacySeconds, legacyPeriods] = ...
                v2xsimregression.paper.bazzi2020blindspots.analysis. ...
                expectedTbcDuration(0.8);
            testCase.verifyEqual(legacyPeriods, 50, AbsTol=5e-14);
            testCase.verifyEqual(legacySeconds, 5, AbsTol=5e-15);

            [cappedSeconds, cappedPeriods] = ...
                v2xsimregression.paper.bazzi2020blindspots.analysis. ...
                expectedTbcDuration( ...
                0.8, ...
                MaximumConsecutiveReservationIntervals=5);
            testCase.verifyEqual(cappedPeriods, 33.616, ...
                AbsTol=5e-13);
            testCase.verifyEqual(cappedSeconds, 3.3616, ...
                AbsTol=5e-14);

            [oneIntervalSeconds, oneIntervalPeriods] = ...
                v2xsimregression.paper.bazzi2020blindspots.analysis. ...
                expectedTbcDuration( ...
                1, ...
                MaximumConsecutiveReservationIntervals=1);
            testCase.verifyEqual(oneIntervalPeriods, 10);
            testCase.verifyEqual(oneIntervalSeconds, 1);
        end

        function analyticalPmfAgreesWithIndependentMonteCarlo(testCase)
            [analyticalPeriods, analyticalProbability] = ...
                v2xsimregression.paper.bazzi2020blindspots.analysis. ...
                tbcPmf( ...
                0.8, ...
                MaximumConsecutiveReservationIntervals=5);
            [sampledPeriods, sampledProbability, sampledDurations] = ...
                v2xsimregression.paper.bazzi2020blindspots.analysis. ...
                monteCarloTbcPmf( ...
                0.8, ...
                NumberOfSamples=150000, ...
                MaximumConsecutiveReservationIntervals=5, ...
                Seed=3001074);

            commonSupport = ...
                min([analyticalPeriods, sampledPeriods]): ...
                max([analyticalPeriods, sampledPeriods]);
            analyticalAligned = zeros(size(commonSupport));
            sampledAligned = zeros(size(commonSupport));
            analyticalAligned( ...
                analyticalPeriods - commonSupport(1) + 1) = ...
                analyticalProbability;
            sampledAligned( ...
                sampledPeriods - commonSupport(1) + 1) = ...
                sampledProbability;

            testCase.verifyLessThan( ...
                max(abs(cumsum(analyticalAligned) - ...
                cumsum(sampledAligned))), ...
                0.004);
            testCase.verifyEqual(mean(sampledDurations), 33.616, ...
                AbsTol=0.25);
        end

        function paperLegacyAndCappedTailClaims(testCase)
            legacyAtTenSeconds = ...
                v2xsimregression.paper.bazzi2020blindspots.analysis. ...
                wirelessBlindSpotProbability(10, 0.8);
            testCase.verifyEqual( ...
                legacyAtTenSeconds, ...
                1.2263e-4, ...
                AbsTol=8e-9);

            capFiveAtFivePointTwoSeconds = ...
                v2xsimregression.paper.bazzi2020blindspots.analysis. ...
                wirelessBlindSpotProbability( ...
                5.2, ...
                0.8, ...
                MaximumConsecutiveReservationIntervals=5);
            testCase.verifyLessThan( ...
                capFiveAtFivePointTwoSeconds, 1e-5);

            afterFiniteSupport = ...
                v2xsimregression.paper.bazzi2020blindspots.analysis. ...
                wirelessBlindSpotProbability( ...
                7.6, ...
                0.8, ...
                MaximumConsecutiveReservationIntervals=5);
            testCase.verifyEqual(afterFiniteSupport, 0);
        end

        function equationElevenUsesConstantDenominator(testCase)
            periods = [1, 2];
            probability = [0.5, 0.5];

            unchanged = ...
                v2xsimregression.paper.bazzi2020blindspots.analysis. ...
                resourceUnchangedProbability( ...
                [0, 1, 2], periods, probability);

            % S(1)=1.5, so the fixed denominator is 2.5.
            testCase.verifyEqual( ...
                unchanged, [1, 0.6, 0.2], AbsTol=eps);
        end

        function MonteCarloStreamIsOwnedAndRepeatable(testCase)
            originalGlobalState = rng;
            cleanup = onCleanup(@() rng(originalGlobalState));
            rng(982451653, "twister");
            stateBefore = rng;

            [periodsA, probabilityA, durationsA] = ...
                v2xsimregression.paper.bazzi2020blindspots.analysis. ...
                monteCarloTbcPmf( ...
                0.8, ...
                NumberOfSamples=2000, ...
                MaximumConsecutiveReservationIntervals=5, ...
                Seed=73);
            stateAfter = rng;
            [periodsB, probabilityB, durationsB] = ...
                v2xsimregression.paper.bazzi2020blindspots.analysis. ...
                monteCarloTbcPmf( ...
                0.8, ...
                NumberOfSamples=2000, ...
                MaximumConsecutiveReservationIntervals=5, ...
                Seed=73);

            testCase.verifyEqual(stateAfter, stateBefore);
            currentState = rng;
            testCase.verifyEqual(currentState, stateBefore);
            testCase.verifyEqual(periodsB, periodsA);
            testCase.verifyEqual(probabilityB, probabilityA);
            testCase.verifyEqual(durationsB, durationsA);
        end

        function inputBoundariesHaveStableDiagnostics(testCase)
            prefix = "v2xsimregression:bazzi2020blindspots:";

            testCase.verifyError( ...
                @() v2xsimregression.paper.bazzi2020blindspots. ...
                analysis.tbePmf(0, 15), ...
                prefix + "InvalidTbeIntervalBounds");
            testCase.verifyError( ...
                @() v2xsimregression.paper.bazzi2020blindspots. ...
                analysis.intervalCountPmf(-eps, Inf), ...
                prefix + "InvalidKeepProbability");
            testCase.verifyError( ...
                @() v2xsimregression.paper.bazzi2020blindspots. ...
                analysis.intervalCountPmf(0.8, 1.5), ...
                prefix + "InvalidMaximumIntervals");
            testCase.verifyError( ...
                @() v2xsimregression.paper.bazzi2020blindspots. ...
                analysis.intervalCountPmf(1, Inf), ...
                prefix + "NonconvergentRetention");
            testCase.verifyError( ...
                @() v2xsimregression.paper.bazzi2020blindspots. ...
                analysis.wirelessBlindSpotProbability(-0.1, 0.8), ...
                prefix + "InvalidElapsedSeconds");
            testCase.verifyError( ...
                @() v2xsimregression.paper.bazzi2020blindspots. ...
                analysis.wirelessBlindSpotProbability( ...
                1, 0.8, ResourceCount=0), ...
                prefix + "InvalidResourceCount");
            testCase.verifyError( ...
                @() v2xsimregression.paper.bazzi2020blindspots. ...
                analysis.monteCarloTbcPmf( ...
                0.8, NumberOfSamples=0), ...
                prefix + "InvalidMonteCarloSampleCount");
            testCase.verifyError( ...
                @() v2xsimregression.paper.bazzi2020blindspots. ...
                analysis.monteCarloTbcPmf( ...
                0.8, Seed=-1), ...
                prefix + "InvalidMonteCarloSeed");
        end

        function oversizedAnalyticalSupportFailsBeforeMaterialization( ...
                testCase)
            prefix = "v2xsimregression:bazzi2020blindspots:";
            expectedDiagnostic = prefix + "AnalyticalSupportTooLarge";

            testCase.verifyError( ...
                @() v2xsimregression.paper.bazzi2020blindspots. ...
                analysis.intervalCountPmf(0.999, Inf), ...
                expectedDiagnostic);
            testCase.verifyError( ...
                @() v2xsimregression.paper.bazzi2020blindspots. ...
                analysis.intervalCountPmf(0.8, 1025), ...
                expectedDiagnostic);
            testCase.verifyError( ...
                @() v2xsimregression.paper.bazzi2020blindspots. ...
                analysis.tbcPmf( ...
                0.8, ...
                MaximumConsecutiveReservationIntervals=1025), ...
                expectedDiagnostic);
        end
    end
end
