function comparisons = buildPairedComparisons( ...
        seedResults, profile, randomSeeds, bootstrapSampleCount)
%BUILDPAIREDCOMPARISONS Build deterministic paired-seed intervals.
%   Every difference is candidate minus reference. Resampling is over the
%   paired seed rows, never over independently sampled campaign arms.

arguments (Input)
    seedResults table
    profile (1, 1) string {mustBeMember( ...
        profile, ["shortened", "publication"])}
    randomSeeds (1, :) double ...
        {mustBeInteger, mustBeNonnegative, ...
        v2xsimregression.paper.bazzi2020blindspots. ...
        mustBeRandomSeeds}
    bootstrapSampleCount (1, 1) double ...
        {mustBeInteger, mustBePositive}
end

if isempty(randomSeeds) || ...
        numel(unique(randomSeeds)) ~= numel(randomSeeds)
    error( ...
        "v2xsimregression:bazzi2020blindspots:" + ...
        "InvalidComparisonSeeds", ...
        "Comparison seeds must be nonempty and unique.");
end
if bootstrapSampleCount < 40
    error( ...
        "v2xsimregression:bazzi2020blindspots:" + ...
        "InsufficientBootstrapSamples", ...
        "BootstrapSampleCount must be at least 40.");
end

requiredVariables = [ ...
    "Profile", "Scenario", "DensityVehiclesPerKilometer", ...
    "SpeedKilometersPerHour", "Scheme", "RandomSeed", ...
    "PrrAuc0To300", "PrrRangeAt90Meters", ...
    "WbsTailProbabilityAuc2To10Seconds"];
if ~all(ismember( ...
        requiredVariables, ...
        string(seedResults.Properties.VariableNames)))
    error( ...
        "v2xsimregression:bazzi2020blindspots:" + ...
        "InvalidSeedSummarySchema", ...
        "Seed summaries do not contain the required comparison fields.");
end
if any(seedResults.Profile ~= profile)
    error( ...
        "v2xsimregression:bazzi2020blindspots:" + ...
        "MixedComparisonProfiles", ...
        "Every seed-summary row must belong to the requested profile.");
end

definition = ...
    v2xsimregression.paper.bazzi2020blindspots. ...
    campaignDefinition(profile);
cappedSchemes = definition.Schemes( ...
    startsWith(definition.Schemes, "capped-"));
referenceSchemes = [ ...
    "legacy-p0", ...
    repmat("legacy-p08", 1, numel(cappedSchemes)), ...
    "capped-m2"];
candidateSchemes = [ ...
    "legacy-p08", cappedSchemes, "capped-m5"];
comparisonCount = ...
    numel(definition.ScenarioNames) .* numel(referenceSchemes);
comparisonCells = cell(comparisonCount, 1);

comparisonIndex = 0;
for scenarioIndex = 1:numel(definition.ScenarioNames)
    scenario = definition.ScenarioNames(scenarioIndex);
    for pairIndex = 1:numel(referenceSchemes)
        comparisonIndex = comparisonIndex + 1;
        referenceScheme = referenceSchemes(pairIndex);
        candidateScheme = candidateSchemes(pairIndex);
        reference = pairedRows( ...
            seedResults, scenario, referenceScheme, randomSeeds);
        candidate = pairedRows( ...
            seedResults, scenario, candidateScheme, randomSeeds);

        metricVariables = [ ...
            "PrrAuc0To300", "PrrRangeAt90Meters", ...
            "WbsTailProbabilityAuc2To10Seconds"];
        referenceMetrics = reference{:, metricVariables};
        candidateMetrics = candidate{:, metricVariables};
        differences = candidateMetrics - referenceMetrics;
        if any(~isfinite( ...
                [referenceMetrics, candidateMetrics]), "all")
            error( ...
                "v2xsimregression:bazzi2020blindspots:" + ...
                "NonfiniteComparisonMetric", ...
                "Paired comparison metrics must be finite.");
        end

        streamSeed = ...
            730000 + 100 .* scenarioIndex + pairIndex;
        confidenceIntervals = pairedBootstrapMeanIntervals( ...
            differences, bootstrapSampleCount, streamSeed);
        density = unique(reference.DensityVehiclesPerKilometer);
        speed = unique(reference.SpeedKilometersPerHour);
        if ~isscalar(density) || ~isscalar(speed)
            error( ...
                "v2xsimregression:bazzi2020blindspots:" + ...
                "InconsistentScenarioMetadata", ...
                "A named scenario must have one density and speed.");
        end

        comparisonCells{comparisonIndex} = table( ...
            profile, scenario, density, speed, ...
            referenceScheme, candidateScheme, numel(randomSeeds), ...
            mean(referenceMetrics(:, 1)), ...
            mean(candidateMetrics(:, 1)), ...
            mean(differences(:, 1)), ...
            confidenceIntervals(1, 1), ...
            confidenceIntervals(1, 2), ...
            mean(referenceMetrics(:, 2)), ...
            mean(candidateMetrics(:, 2)), ...
            mean(differences(:, 2)), ...
            confidenceIntervals(2, 1), ...
            confidenceIntervals(2, 2), ...
            mean(referenceMetrics(:, 3)), ...
            mean(candidateMetrics(:, 3)), ...
            mean(differences(:, 3)), ...
            confidenceIntervals(3, 1), ...
            confidenceIntervals(3, 2), ...
            VariableNames=[ ...
                "Profile", "Scenario", ...
                "DensityVehiclesPerKilometer", ...
                "SpeedKilometersPerHour", ...
                "ReferenceScheme", "CandidateScheme", "SeedCount", ...
                "ReferenceMeanPrrAuc0To300", ...
                "CandidateMeanPrrAuc0To300", ...
                "MeanPrrAucDifference", ...
                "PrrAucDifferenceLower95Percentile", ...
                "PrrAucDifferenceUpper95Percentile", ...
                "ReferenceMeanPrrRangeAt90Meters", ...
                "CandidateMeanPrrRangeAt90Meters", ...
                "MeanPrrRangeAt90MetersDifference", ...
                "PrrRangeDifferenceLower95Percentile", ...
                "PrrRangeDifferenceUpper95Percentile", ...
                "ReferenceMeanWbsTailAuc2To10Seconds", ...
                "CandidateMeanWbsTailAuc2To10Seconds", ...
                "MeanWbsTailAucDifference", ...
                "WbsTailAucDifferenceLower95Percentile", ...
                "WbsTailAucDifferenceUpper95Percentile"]);
    end
end

comparisons = vertcat(comparisonCells{:});
end

function rows = pairedRows( ...
        seedResults, scenario, scheme, randomSeeds)
rows = seedResults( ...
    seedResults.Scenario == scenario & ...
    seedResults.Scheme == scheme, :);
if height(rows) ~= numel(randomSeeds) || ...
        numel(unique(rows.RandomSeed)) ~= height(rows)
    error( ...
        "v2xsimregression:bazzi2020blindspots:UnpairedSeeds", ...
        "Scenario %s scheme %s must contain each seed exactly once.", ...
        scenario, scheme);
end
[isPresent, rowOrder] = ismember(randomSeeds(:), rows.RandomSeed);
if ~all(isPresent)
    error( ...
        "v2xsimregression:bazzi2020blindspots:UnpairedSeeds", ...
        "Scenario %s scheme %s is missing a requested seed.", ...
        scenario, scheme);
end
rows = rows(rowOrder, :);
end

function confidenceIntervals = pairedBootstrapMeanIntervals( ...
        differences, bootstrapSampleCount, randomSeed)
stream = RandStream("mt19937ar", Seed=randomSeed);
seedCount = size(differences, 1);
sampleRows = randi( ...
    stream, seedCount, seedCount, bootstrapSampleCount);
metricCount = size(differences, 2);
confidenceIntervals = zeros(metricCount, 2);
lowerIndex = max(1, ceil(0.025 .* bootstrapSampleCount));
upperIndex = min( ...
    bootstrapSampleCount, ...
    floor(0.975 .* bootstrapSampleCount));
for metricIndex = 1:metricCount
    metricDifferences = differences(:, metricIndex);
    bootstrapMeans = sort(mean( ...
        metricDifferences(sampleRows), 1));
    confidenceIntervals(metricIndex, :) = [ ...
        bootstrapMeans(lowerIndex), ...
        bootstrapMeans(upperIndex)];
end
end
