function manifest = createCampaignManifest( ...
        profile, outputDirectory, randomSeeds)
%CREATECAMPAIGNMANIFEST Create stable scenario/scheme/seed work items.
%   Simulation, scenario, and allocator seeds are deliberately paired by
%   numeric value while remaining owned by independent random streams.

arguments (Input)
    profile (1, 1) string {mustBeMember( ...
        profile, ["shortened", "publication"])}
    outputDirectory (1, 1) string {mustBeNonzeroLengthText}
    randomSeeds (1, :) double ...
        {mustBeInteger, mustBeNonnegative, ...
        v2xsimregression.paper.bazzi2020blindspots. ...
        mustBeRandomSeeds}
end

if isempty(randomSeeds)
    error( ...
        "v2xsimregression:bazzi2020blindspots:EmptyRandomSeeds", ...
        "RandomSeeds must be nonempty.");
end
if numel(unique(randomSeeds)) ~= numel(randomSeeds)
    error( ...
        "v2xsimregression:bazzi2020blindspots:" + ...
        "DuplicateRandomSeed", ...
        "RandomSeeds must not contain duplicates.");
end

definition = ...
    v2xsimregression.paper.bazzi2020blindspots. ...
    campaignDefinition(profile);
scenarioCount = numel(definition.ScenarioNames);
schemeCount = numel(definition.Schemes);
seedCount = numel(randomSeeds);
workItemCount = scenarioCount * schemeCount * seedCount;

workItemIndex = (1:workItemCount).';
profiles = repmat(profile, workItemCount, 1);
scenarioNames = strings(workItemCount, 1);
densities = zeros(workItemCount, 1);
speeds = zeros(workItemCount, 1);
roadLengths = repmat( ...
    definition.RoadLengthMeters, workItemCount, 1);
vehicleCounts = zeros(workItemCount, 1);
simulationTimes = repmat( ...
    definition.SimulationTimeSeconds, workItemCount, 1);
wbsMaximumDelays = repmat( ...
    definition.WirelessBlindSpotMaximumDelaySeconds, ...
    workItemCount, 1);
schemes = strings(workItemCount, 1);
keepProbabilities = zeros(workItemCount, 1);
maximumIntervals = zeros(workItemCount, 1);
simulationSeeds = zeros(workItemCount, 1);
scenarioSeeds = zeros(workItemCount, 1);
allocatorSeeds = zeros(workItemCount, 1);
outputDirectories = strings(workItemCount, 1);
labels = strings(workItemCount, 1);

workIndex = 0;
for scenarioIndex = 1:scenarioCount
    scenarioName = definition.ScenarioNames(scenarioIndex);
    density = ...
        definition.DensitiesVehiclesPerKilometer(scenarioIndex);
    speed = definition.SpeedsKilometersPerHour(scenarioIndex);
    vehicleCount = round( ...
        density .* definition.RoadLengthMeters ./ 1000);
    for schemeIndex = 1:schemeCount
        scheme = definition.Schemes(schemeIndex);
        for randomSeed = randomSeeds
            workIndex = workIndex + 1;
            scenarioNames(workIndex) = scenarioName;
            densities(workIndex) = density;
            speeds(workIndex) = speed;
            vehicleCounts(workIndex) = vehicleCount;
            schemes(workIndex) = scheme;
            keepProbabilities(workIndex) = ...
                definition.KeepProbabilities(schemeIndex);
            maximumIntervals(workIndex) = ...
                definition. ...
                MaximumConsecutiveReservationIntervals(schemeIndex);
            simulationSeeds(workIndex) = randomSeed;
            scenarioSeeds(workIndex) = randomSeed;
            allocatorSeeds(workIndex) = randomSeed;
            outputDirectories(workIndex) = fullfile( ...
                outputDirectory, ...
                "scenario-" + scenarioName, ...
                "scheme-" + scheme, ...
                compose("seed-%d", randomSeed));
            labels(workIndex) = compose( ...
                "profile=%s,scenario=%s,scheme=%s,seed=%d", ...
                profile, scenarioName, scheme, randomSeed);
        end
    end
end

manifest = table( ...
    workItemIndex, profiles, scenarioNames, densities, speeds, ...
    roadLengths, vehicleCounts, simulationTimes, wbsMaximumDelays, ...
    schemes, keepProbabilities, maximumIntervals, simulationSeeds, ...
    scenarioSeeds, allocatorSeeds, outputDirectories, labels, ...
    VariableNames=[ ...
        "WorkItemIndex", "Profile", "Scenario", ...
        "DensityVehiclesPerKilometer", ...
        "SpeedKilometersPerHour", "RoadLengthMeters", ...
        "VehicleCount", "SimulationTimeSeconds", ...
        "WirelessBlindSpotMaximumDelaySeconds", "Scheme", ...
        "KeepResourceProbability", ...
        "MaximumConsecutiveReservationIntervals", ...
        "SimulationSeed", "ScenarioSeed", "AllocatorSeed", ...
        "OutputDirectory", "Label"]);
end
