function [metrics, pooledPrr, pooledWbs] = ...
        reduceCountOutputs(prrOutputs, wbsOutputs, options)
%REDUCECOUNTOUTPUTS Pool raw PRR/WBS counts and derive paper metrics.
%   PRR ratios and wireless-blind-spot probabilities are always recomputed
%   after pooling numerator and denominator counts. Averaging per-seed
%   ratios would give runs with few observations disproportionate weight.

arguments (Input)
    prrOutputs (1, :) cell
    wbsOutputs (1, :) cell
    options.MaximumPrrDistanceMeters (1, 1) double ...
        {mustBeReal, mustBeFinite, mustBePositive} = 300
    options.PrrBinWidthMeters (1, 1) double ...
        {mustBeReal, mustBeFinite, mustBePositive} = 10
    options.WirelessBlindSpotMaximumDelaySeconds (1, 1) double ...
        {mustBeReal, mustBeFinite, mustBePositive}
    options.WirelessBlindSpotBinWidthSeconds (1, 1) double ...
        {mustBeReal, mustBeFinite, mustBePositive} = 0.1
    options.AwarenessRangeCount (1, 1) double ...
        {mustBeInteger, mustBePositive} = 2
    options.WirelessBlindSpotAwarenessRangeIndex (1, 1) double ...
        {mustBeInteger, mustBePositive} = 1
    options.WirelessBlindSpotTailStartSeconds (1, 1) double ...
        {mustBeReal, mustBeFinite, mustBeNonnegative} = 2
    options.WirelessBlindSpotTailEndSeconds (1, 1) double ...
        {mustBeReal, mustBeFinite, mustBePositive} = 10
    options.WirelessBlindSpotProbabilityThreshold (1, 1) double ...
        {mustBeReal, mustBeFinite, mustBePositive} = 1e-4
end

arguments (Output)
    metrics (1, 1) struct
    pooledPrr table
    pooledWbs table
end

if isempty(prrOutputs) || numel(prrOutputs) ~= numel(wbsOutputs)
    error( ...
        "v2xsimregression:bazzi2020blindspots:" + ...
        "MismatchedCountOutputs", ...
        "PRR and WBS outputs must contain the same nonzero run count.");
end
if options.WirelessBlindSpotAwarenessRangeIndex > ...
        options.AwarenessRangeCount
    error( ...
        "v2xsimregression:bazzi2020blindspots:" + ...
        "InvalidAwarenessRangeIndex", ...
        "The selected WBS awareness-range index exceeds the range count.");
end
if options.WirelessBlindSpotTailStartSeconds >= ...
        options.WirelessBlindSpotTailEndSeconds || ...
        options.WirelessBlindSpotTailEndSeconds > ...
        options.WirelessBlindSpotMaximumDelaySeconds
    error( ...
        "v2xsimregression:bazzi2020blindspots:InvalidTailInterval", ...
        "The WBS tail interval must be increasing and within the output.");
end
if options.WirelessBlindSpotProbabilityThreshold > 1
    error( ...
        "v2xsimregression:bazzi2020blindspots:" + ...
        "InvalidProbabilityThreshold", ...
        "The WBS probability threshold cannot exceed one.");
end

expectedDistances = ( ...
    options.PrrBinWidthMeters: ...
    options.PrrBinWidthMeters: ...
    options.MaximumPrrDistanceMeters).';
prrCounts = zeros(numel(expectedDistances), 3);
for outputIndex = 1:numel(prrOutputs)
    data = validatePrrOutput( ...
        prrOutputs{outputIndex}, expectedDistances);
    prrCounts = prrCounts + data(:, 2:4);
end

prrTotalCounts = sum(prrCounts, 2);
if any(prrTotalCounts == 0)
    error( ...
        "v2xsimregression:bazzi2020blindspots:" + ...
        "IncompletePrrCurve", ...
        "Every 10 m PRR bin through 300 m must contain samples.");
end
packetReceptionRatios = prrCounts(:, 1) ./ prrTotalCounts;
prrAuc = trapz( ...
    [0; expectedDistances], ...
    [packetReceptionRatios(1); packetReceptionRatios]) ./ ...
    options.MaximumPrrDistanceMeters;
[rangeAt90Meters, ~] = ...
    v2xsimregression.paper.bazzi2020blindspots. ...
    firstDownwardCrossing( ...
        [0; expectedDistances], ...
        [packetReceptionRatios(1); packetReceptionRatios], 0.9);

expectedDurations = ( ...
    options.WirelessBlindSpotBinWidthSeconds: ...
    options.WirelessBlindSpotBinWidthSeconds: ...
    options.WirelessBlindSpotMaximumDelaySeconds).';
wbsCounts = zeros(numel(expectedDurations), 2);
for outputIndex = 1:numel(wbsOutputs)
    data = wbsOutputs{outputIndex};
    validateWbsOutput( ...
        data, expectedDurations, options.AwarenessRangeCount);
    firstCountColumn = 2 + 3 .* ( ...
        options.WirelessBlindSpotAwarenessRangeIndex - 1);
    wbsCounts = wbsCounts + ...
        data(:, firstCountColumn:firstCountColumn + 1);
end

wbsTotalCounts = sum(wbsCounts, 2);
if any(wbsTotalCounts == 0)
    error( ...
        "v2xsimregression:bazzi2020blindspots:" + ...
        "IncompleteWirelessBlindSpotCurve", ...
        "Every WBS duration threshold must contain observations.");
end
wbsProbabilities = wbsCounts(:, 1) ./ wbsTotalCounts;
isTail = expectedDurations >= ...
    options.WirelessBlindSpotTailStartSeconds & ...
    expectedDurations <= ...
    options.WirelessBlindSpotTailEndSeconds;
expectedTailDurations = ( ...
    options.WirelessBlindSpotTailStartSeconds: ...
    options.WirelessBlindSpotBinWidthSeconds: ...
    options.WirelessBlindSpotTailEndSeconds).';
if ~isequalWithinTolerance( ...
        expectedDurations(isTail), expectedTailDurations)
    error( ...
        "v2xsimregression:bazzi2020blindspots:IncompleteTailCurve", ...
        "The WBS output does not cover every requested tail threshold.");
end
wbsTailAuc = trapz( ...
    expectedDurations(isTail), wbsProbabilities(isTail));
[wbsCrossingSeconds, wbsCrossingStatus] = ...
    v2xsimregression.paper.bazzi2020blindspots. ...
    firstDownwardCrossing( ...
        expectedDurations, wbsProbabilities, ...
        options.WirelessBlindSpotProbabilityThreshold);

atTenSeconds = find( ...
    abs(expectedDurations - 10) <= gridTolerance(10), 1);
if isempty(atTenSeconds)
    error( ...
        "v2xsimregression:bazzi2020blindspots:MissingTenSecondWbs", ...
        "The WBS output must contain the 10-second threshold.");
end

metrics = struct( ...
    PrrAuc0To300=prrAuc, ...
    PrrRangeAt90Meters=rangeAt90Meters, ...
    PrrCorrectCount0To300=sum(prrCounts(:, 1)), ...
    PrrErrorCount0To300=sum(prrCounts(:, 2)), ...
    PrrBlockedCount0To300=sum(prrCounts(:, 3)), ...
    PrrTotalCount0To300=sum(prrTotalCounts), ...
    WbsTailProbabilityAuc2To10Seconds=wbsTailAuc, ...
    WbsProbabilityThreshold= ...
        options.WirelessBlindSpotProbabilityThreshold, ...
    WbsThresholdCrossingSeconds=wbsCrossingSeconds, ...
    WbsThresholdCrossingStatus=wbsCrossingStatus, ...
    WbsAt10GreaterOrEqualCount=wbsCounts(atTenSeconds, 1), ...
    WbsAt10ShorterCount=wbsCounts(atTenSeconds, 2), ...
    WbsAt10Probability=wbsProbabilities(atTenSeconds));

pooledPrr = table( ...
    expectedDistances, prrCounts(:, 1), prrCounts(:, 2), ...
    prrCounts(:, 3), prrTotalCounts, packetReceptionRatios, ...
    VariableNames=[ ...
        "DistanceMeters", "CorrectCount", "ErrorCount", ...
        "BlockedCount", "TotalCount", "PacketReceptionRatio"]);
pooledWbs = table( ...
    expectedDurations, wbsCounts(:, 1), wbsCounts(:, 2), ...
    wbsTotalCounts, wbsProbabilities, ...
    VariableNames=[ ...
        "DurationSeconds", "GreaterOrEqualCount", "ShorterCount", ...
        "TotalCount", "Probability"]);
end

function selectedData = validatePrrOutput(data, expectedDistances)
if ~isnumeric(data) || ~ismatrix(data) || ...
        size(data, 2) ~= 6 || ...
        size(data, 1) < numel(expectedDistances)
    error( ...
        "v2xsimregression:bazzi2020blindspots:InvalidPrrOutput", ...
        "Each PRR output must have six columns and cover every " + ...
        "requested distance bin.");
end
if any(~isfinite(data(:, 1:5)), "all") || ...
        any(data(:, 1:5) < 0, "all") || ...
        any(data(:, 2:5) ~= fix(data(:, 2:5)), "all")
    error( ...
        "v2xsimregression:bazzi2020blindspots:InvalidPrrOutput", ...
        "PRR distances and count columns must be finite nonnegative " + ...
        "values, and counts must be integers.");
end
selectedData = data(1:numel(expectedDistances), :);
if ~isequalWithinTolerance(selectedData(:, 1), expectedDistances)
    error( ...
        "v2xsimregression:bazzi2020blindspots:InvalidPrrGrid", ...
        "The PRR distance grid must begin with every requested bin once.");
end
if any(data(:, 5) ~= sum(data(:, 2:4), 2))
    error( ...
        "v2xsimregression:bazzi2020blindspots:" + ...
        "InconsistentPrrCounts", ...
        "Each PRR total must equal correct + error + blocked.");
end

expectedRatios = data(:, 2) ./ data(:, 5);
hasTotal = data(:, 5) > 0;
if any(~isfinite(data(hasTotal, 6))) || ...
        any(abs( ...
        data(hasTotal, 6) - expectedRatios(hasTotal)) > 5e-6) || ...
        any(~isnan(data(~hasTotal, 6)))
    error( ...
        "v2xsimregression:bazzi2020blindspots:InvalidPrrRatio", ...
        "PRR ratio columns must agree with their raw counts.");
end
end

function validateWbsOutput(data, expectedDurations, awarenessRangeCount)
expectedColumnCount = 1 + 3 .* awarenessRangeCount;
if ~isnumeric(data) || ~ismatrix(data) || ...
        size(data, 2) ~= expectedColumnCount || ...
        size(data, 1) ~= numel(expectedDurations)
    error( ...
        "v2xsimregression:bazzi2020blindspots:InvalidWbsOutput", ...
        "Each WBS output must have one duration/count/probability row " + ...
        "for every configured threshold and awareness range.");
end
if any(~isfinite(data(:, 1))) || ...
        ~isequalWithinTolerance(data(:, 1), expectedDurations)
    error( ...
        "v2xsimregression:bazzi2020blindspots:InvalidWbsGrid", ...
        "The WBS duration grid must contain every configured bin once.");
end

for rangeIndex = 1:awarenessRangeCount
    greaterOrEqualColumn = 2 + 3 .* (rangeIndex - 1);
    shorterColumn = greaterOrEqualColumn + 1;
    probabilityColumn = shorterColumn + 1;
    counts = data(:, [greaterOrEqualColumn, shorterColumn]);
    if any(~isfinite(counts), "all") || ...
            any(counts < 0, "all") || ...
            any(counts ~= fix(counts), "all")
        error( ...
            "v2xsimregression:bazzi2020blindspots:" + ...
            "InvalidWbsCounts", ...
            "WBS count columns must contain nonnegative integers.");
    end
    totals = sum(counts, 2);
    expectedProbabilities = counts(:, 1) ./ totals;
    hasTotal = totals > 0;
    probabilities = data(:, probabilityColumn);
    if any(~isfinite(probabilities(hasTotal))) || ...
            any(abs( ...
            probabilities(hasTotal) - ...
            expectedProbabilities(hasTotal)) > 5e-6) || ...
            any(~isnan(probabilities(~hasTotal)))
        error( ...
            "v2xsimregression:bazzi2020blindspots:" + ...
            "InvalidWbsProbability", ...
            "WBS probabilities must agree with their raw counts.");
    end
end
end

function result = isequalWithinTolerance(actual, expected)
tolerance = gridTolerance(max(abs(expected), [], "all"));
result = isequal(size(actual), size(expected)) && ...
    all(abs(actual - expected) <= tolerance, "all");
end

function tolerance = gridTolerance(scale)
tolerance = 64 .* eps(max(1, scale));
end
