function [aggregateResults, comparisons] = runPublishedCampaigns( ...
        simulatorRoot, outputDirectory, options)
%RUNPUBLISHEDCAMPAIGNS Run the Bazzi et al. 2020 blind-spot campaign.
%   AGGREGATERESULTS contains one row per scenario and allocation scheme.
%   Raw PRR and WBS counts are pooled across seeds before metrics are
%   derived. COMPARISONS contains deterministic paired-seed percentile
%   bootstrap intervals, expressed as candidate minus reference.

arguments (Input)
    simulatorRoot (1, 1) string {mustBeNonzeroLengthText}
    outputDirectory (1, 1) string {mustBeNonzeroLengthText}
    options.Profile (1, 1) string {mustBeMember( ...
        options.Profile, ["shortened", "publication"])} = "shortened"
    options.RandomSeeds (1, :) double ...
        {mustBeInteger, mustBeNonnegative, ...
        v2xsimregression.paper.bazzi2020blindspots. ...
        mustBeRandomSeeds} = zeros(1, 0)
    options.ExecutionMode (1, 1) string {mustBeMember( ...
        options.ExecutionMode, ["auto", "serial", "parallel"])} = "auto"
    options.MaxWorkers (1, 1) double { ...
        v2xsimregression.execution.mustBeWorkerLimit} = Inf
    options.BootstrapSampleCount (1, 1) double ...
        {mustBeInteger, mustBePositive} = 10000
end

arguments (Output)
    aggregateResults table
    comparisons table
end

definition = ...
    v2xsimregression.paper.bazzi2020blindspots. ...
    campaignDefinition(options.Profile);
randomSeeds = options.RandomSeeds;
if isempty(randomSeeds)
    randomSeeds = definition.DefaultRandomSeeds;
end
if numel(unique(randomSeeds)) ~= numel(randomSeeds)
    error( ...
        "v2xsimregression:bazzi2020blindspots:" + ...
        "DuplicateRandomSeed", ...
        "RandomSeeds must not contain duplicates.");
end
if options.BootstrapSampleCount < 40
    error( ...
        "v2xsimregression:bazzi2020blindspots:" + ...
        "InsufficientBootstrapSamples", ...
        "BootstrapSampleCount must be at least 40.");
end

callerWorkingDirectory = string(pwd);
simulatorRoot = absolutePath( ...
    simulatorRoot, callerWorkingDirectory);
outputDirectory = absolutePath( ...
    outputDirectory, callerWorkingDirectory);
sourceDirectory = fullfile(simulatorRoot, "src");
tomlDirectory = fullfile(simulatorRoot, "lib", "matlab-toml");
configurationFile = fullfile( ...
    fileparts(mfilename("fullpath")), ...
    "config", "bazzi2020.toml");
validateSimulator( ...
    simulatorRoot, sourceDirectory, configurationFile);
prepareOutputDirectory(outputDirectory);

originalPath = path;
originalStream = RandStream.getGlobalStream();
originalStreamState = originalStream.State;
originalWarningState = warning;
environmentCleanup = onCleanup(@() restoreEnvironment( ...
    originalPath, originalStream, originalStreamState, ...
    originalWarningState));

addpath(sourceDirectory);
addpath(tomlDirectory);

manifest = ...
    v2xsimregression.paper.bazzi2020blindspots. ...
    createCampaignManifest( ...
        options.Profile, outputDirectory, randomSeeds);
manifestFile = fullfile(outputDirectory, "campaign-manifest.csv");
writetable(manifest, manifestFile);
progressLogFile = fullfile( ...
    outputDirectory, "campaign-progress.jsonl");
fprintf("Bazzi campaign manifest: %s\n", manifestFile);
fprintf("Bazzi campaign progress journal: %s\n", progressLogFile);
manifestStructures = table2struct(manifest);
workItems = cell(1, numel(manifestStructures));
for workIndex = 1:numel(manifestStructures)
    workItem = manifestStructures(workIndex);
    workItem.ConfigurationFile = configurationFile;
    workItem.SourceDirectory = sourceDirectory;
    workItems{workIndex} = workItem;
end

additionalPaths = [ ...
    fullfile(simulatorRoot, "regression-tests"), ...
    sourceDirectory, ...
    tomlDirectory];
seedDirectoryOutputs = ...
    v2xsimregression.execution.runWorkItems( ...
        workItems, @runSeedWorkItem, ...
        Labels=manifest.Label.', ...
        ExecutionMode=options.ExecutionMode, ...
        MaxWorkers=options.MaxWorkers, ...
        AdditionalPaths=additionalPaths, ...
        ProgressLogFile=progressLogFile, ...
        CollectAllFailures=true);
seedDirectories = string(seedDirectoryOutputs).';
if ~isequal(seedDirectories, manifest.OutputDirectory)
    error( ...
        "v2xsimregression:bazzi2020blindspots:" + ...
        "WorkItemOrderChanged", ...
        "The work scheduler did not preserve manifest result order.");
end

seedResults = summarizeSeeds(manifest, definition);
aggregateResults = summarizeConfigurations( ...
    manifest, definition, outputDirectory);
comparisons = ...
    v2xsimregression.paper.bazzi2020blindspots. ...
    buildPairedComparisons( ...
        seedResults, options.Profile, randomSeeds, ...
        options.BootstrapSampleCount);

writetable( ...
    seedResults, ...
    fullfile(outputDirectory, "campaign-seed-summary.csv"));
writetable( ...
    aggregateResults, ...
    fullfile(outputDirectory, "campaign-summary.csv"));
writetable( ...
    comparisons, ...
    fullfile(outputDirectory, "campaign-comparisons.csv"));

environmentCleanup; %#ok<VUNUS>
end

function seedDirectory = runSeedWorkItem( ...
        workItem, reportProgress) %#ok<INUSD>
seedDirectory = workItem.OutputDirectory;
patchData = struct( ...
    Simulation=struct( ...
        RandomSeed=workItem.SimulationSeed, ...
        DurationSeconds=workItem.SimulationTimeSeconds), ...
    Scenario=struct( ...
        Type="BidirectionalHighway", ...
        UpdateIntervalSeconds=0.1, ...
        BidirectionalHighway=struct( ...
            RandomSeed=workItem.ScenarioSeed, ...
            VehicleCount=workItem.VehicleCount, ...
            NLanes=3, ...
            LaneWidth=4, ...
            RoadLength=workItem.RoadLengthMeters, ...
            CentralDividerWidth=0, ...
            MeanVehicleSpeed= ...
                workItem.SpeedKilometersPerHour ./ 3.6, ...
            VehicleSpeedStandardDeviation=0, ...
            RerollSpeedOnWrapAround=false)), ...
    Application=struct( ...
        PacketSizeBytes=300, ...
        ResourceReservationIntervalSeconds=0.1, ...
        PacketGeneration=struct( ...
            IntervalSeconds=0.1, ...
            IntervalVariationSeconds=0, ...
            RandomComponentMeanSeconds=0), ...
        CongestionControl=struct(Enabled=false), ...
        ChannelLoad=struct( ...
            Enabled=true, ...
            MeasurementWindowSeconds=0.1, ...
            UpdateStepsPerWindow=100)), ...
    Radio=struct( ...
        Type="LteV2X", ...
        BandwidthMHz=10, ...
        TransmitPowerDbm=23, ...
        FixedPowerDensityEnabled=false, ...
        TransmitAntennaGainDb=3, ...
        ReceiveAntennaGainDb=3, ...
        ReceiverNoiseFigureDb=9, ...
        LteV2X=struct( ...
            Mcs=6, ...
            AdjacentPscchAndPsschEnabled=true), ...
        Sidelink=struct( ...
            MaximumTransmissionCount=1, ...
            ResourcePool=struct( ...
                SubchannelSizeResourceBlocks=10, ...
                PartialFrequencyOverlapEnabled=false))), ...
    Channel=struct( ...
        RayleighFadingEnabled=false, ...
        PacketError=struct( ...
            Model="Threshold", ...
            SidelinkLosThresholdDb=5.79), ...
        PathLoss=struct(Model="WinnerPlusB1"), ...
        Shadowing=struct( ...
            LosStandardDeviationDb=3, ...
            NlosStandardDeviationDb=4)), ...
    Awareness=struct(RangesMeters=[100, 300]), ...
    ResourceAllocation=struct( ...
        Type="SensingBased", ...
        RandomSeed=workItem.AllocatorSeed, ...
        SensingBased=struct( ...
            ReselectionCounterMinimum=5, ...
            ReselectionCounterMaximum=15, ...
            KeepResourceProbability= ...
                workItem.KeepResourceProbability, ...
            MaximumConsecutiveReservationIntervals= ...
                workItem.MaximumConsecutiveReservationIntervals)), ...
    Outputs=struct( ...
        PacketReceptionRatio=struct( ...
            Enabled=true, ...
            DistanceBinWidthMeters=10), ...
        WirelessBlindSpot=struct( ...
            Enabled=true, ...
            MaximumDelaySeconds= ...
                workItem.WirelessBlindSpotMaximumDelaySeconds, ...
            BinWidthSeconds=0.1), ...
        AverageNeighborCount=struct(Enabled=false), ...
        UpdateDelay=struct(Enabled=false), ...
        PacketDelay=struct(Enabled=false), ...
        DataAge=struct(Enabled=false), ...
        ChannelBusyRatio=struct(Enabled=false)));
template = v2xsim.config.load(workItem.ConfigurationFile);
configuration = template.resolve( ...
    Patch=v2xsim.config.patch(patchData)); %#ok<NASGU>
evalc("v2xsim.runSimulation(configuration," + ...
    "OutputDirectory=seedDirectory,RunLabel=workItem.Label," + ...
    "ProgressFcn=reportProgress);");

validateSeedOutputs(seedDirectory);
resolvedEntrypoint = string(which("v2xsim.runSimulation"));
if ~startsWith(resolvedEntrypoint, workItem.SourceDirectory)
    error( ...
        "v2xsimregression:bazzi2020blindspots:WrongSimulator", ...
        "v2xsim.runSimulation resolved outside the requested root: %s", ...
        resolvedEntrypoint);
end
end

function seedResults = summarizeSeeds(manifest, definition)
rowCells = cell(height(manifest), 1);
for rowIndex = 1:height(manifest)
    directory = manifest.OutputDirectory(rowIndex);
    [prrData, wbsData] = readCountOutputs(directory);
    metrics = ...
        v2xsimregression.paper.bazzi2020blindspots. ...
        reduceCountOutputs( ...
            {prrData}, {wbsData}, ...
            WirelessBlindSpotMaximumDelaySeconds= ...
                definition.WirelessBlindSpotMaximumDelaySeconds);
    rowCells{rowIndex} = seedSummaryRow( ...
        manifest(rowIndex, :), metrics);
end
seedResults = vertcat(rowCells{:});
end

function aggregateResults = summarizeConfigurations( ...
        manifest, definition, outputDirectory)
configurationCount = ...
    numel(definition.ScenarioNames) .* numel(definition.Schemes);
rowCells = cell(configurationCount, 1);
configurationIndex = 0;
for scenario = definition.ScenarioNames
    for scheme = definition.Schemes
        configurationIndex = configurationIndex + 1;
        selected = manifest( ...
            manifest.Scenario == scenario & ...
            manifest.Scheme == scheme, :);
        prrOutputs = cell(1, height(selected));
        wbsOutputs = cell(1, height(selected));
        for seedIndex = 1:height(selected)
            [prrOutputs{seedIndex}, wbsOutputs{seedIndex}] = ...
                readCountOutputs( ...
                    selected.OutputDirectory(seedIndex));
        end
        metrics = ...
            v2xsimregression.paper.bazzi2020blindspots. ...
            reduceCountOutputs( ...
                prrOutputs, wbsOutputs, ...
                WirelessBlindSpotMaximumDelaySeconds= ...
                    definition. ...
                    WirelessBlindSpotMaximumDelaySeconds);
        configurationDirectory = fullfile( ...
            outputDirectory, "scenario-" + scenario, ...
            "scheme-" + scheme);
        rowCells{configurationIndex} = aggregateSummaryRow( ...
            selected, metrics, configurationDirectory);
    end
end
aggregateResults = vertcat(rowCells{:});
end

function row = seedSummaryRow(manifestRow, metrics)
row = table( ...
    manifestRow.Profile, manifestRow.Scenario, ...
    manifestRow.DensityVehiclesPerKilometer, ...
    manifestRow.SpeedKilometersPerHour, ...
    manifestRow.RoadLengthMeters, manifestRow.VehicleCount, ...
    manifestRow.Scheme, manifestRow.KeepResourceProbability, ...
    manifestRow.MaximumConsecutiveReservationIntervals, ...
    manifestRow.SimulationSeed, manifestRow.ScenarioSeed, ...
    manifestRow.AllocatorSeed, manifestRow.SimulationTimeSeconds, ...
    manifestRow.WirelessBlindSpotMaximumDelaySeconds, ...
    metrics.PrrAuc0To300, metrics.PrrRangeAt90Meters, ...
    metrics.PrrCorrectCount0To300, ...
    metrics.PrrErrorCount0To300, ...
    metrics.PrrBlockedCount0To300, ...
    metrics.PrrTotalCount0To300, ...
    metrics.WbsTailProbabilityAuc2To10Seconds, ...
    metrics.WbsProbabilityThreshold, ...
    metrics.WbsThresholdCrossingSeconds, ...
    metrics.WbsThresholdCrossingStatus, ...
    metrics.WbsAt10GreaterOrEqualCount, ...
    metrics.WbsAt10ShorterCount, ...
    metrics.WbsAt10Probability, ...
    manifestRow.OutputDirectory, ...
    VariableNames=summaryVariableNames("seed"));
row.RandomSeed = row.SimulationSeed;
row = movevars(row, "RandomSeed", Before="SimulationSeed");
end

function row = aggregateSummaryRow( ...
        selectedManifest, metrics, outputDirectory)
metadata = selectedManifest(1, :);
row = table( ...
    metadata.Profile, metadata.Scenario, ...
    metadata.DensityVehiclesPerKilometer, ...
    metadata.SpeedKilometersPerHour, ...
    metadata.RoadLengthMeters, metadata.VehicleCount, ...
    metadata.Scheme, metadata.KeepResourceProbability, ...
    metadata.MaximumConsecutiveReservationIntervals, ...
    height(selectedManifest), metadata.SimulationTimeSeconds, ...
    metadata.WirelessBlindSpotMaximumDelaySeconds, ...
    metrics.PrrAuc0To300, metrics.PrrRangeAt90Meters, ...
    metrics.PrrCorrectCount0To300, ...
    metrics.PrrErrorCount0To300, ...
    metrics.PrrBlockedCount0To300, ...
    metrics.PrrTotalCount0To300, ...
    metrics.WbsTailProbabilityAuc2To10Seconds, ...
    metrics.WbsProbabilityThreshold, ...
    metrics.WbsThresholdCrossingSeconds, ...
    metrics.WbsThresholdCrossingStatus, ...
    metrics.WbsAt10GreaterOrEqualCount, ...
    metrics.WbsAt10ShorterCount, ...
    metrics.WbsAt10Probability, outputDirectory, ...
    VariableNames=summaryVariableNames("aggregate"));
end

function variableNames = summaryVariableNames(kind)
metadataNames = [ ...
    "Profile", "Scenario", "DensityVehiclesPerKilometer", ...
    "SpeedKilometersPerHour", "RoadLengthMeters", "VehicleCount", ...
    "Scheme", "KeepResourceProbability", ...
    "MaximumConsecutiveReservationIntervals"];
if kind == "seed"
    runNames = [ ...
        "SimulationSeed", "ScenarioSeed", "AllocatorSeed", ...
        "SimulationTimeSeconds", ...
        "WirelessBlindSpotMaximumDelaySeconds"];
else
    runNames = [ ...
        "SeedCount", "SimulationTimeSeconds", ...
        "WirelessBlindSpotMaximumDelaySeconds"];
end
metricNames = [ ...
    "PrrAuc0To300", "PrrRangeAt90Meters", ...
    "PrrCorrectCount0To300", "PrrErrorCount0To300", ...
    "PrrBlockedCount0To300", "PrrTotalCount0To300", ...
    "WbsTailProbabilityAuc2To10Seconds", ...
    "WbsProbabilityThreshold", ...
    "WbsThresholdCrossingSeconds", ...
    "WbsThresholdCrossingStatus", ...
    "WbsAt10GreaterOrEqualCount", ...
    "WbsAt10ShorterCount", "WbsAt10Probability", ...
    "OutputDirectory"];
variableNames = [metadataNames, runNames, metricNames];
end

function [prrData, wbsData] = readCountOutputs(directory)
validateSeedOutputs(directory);
prrData = readmatrix( ...
    fullfile(directory, "packet_reception_ratio_LTE.csv"), ...
    FileType="text", Delimiter=",");
wbsData = readmatrix( ...
    fullfile(directory, "wireless_blind_spot_LTE.csv"), ...
    FileType="text", Delimiter=",");
end

function validateSeedOutputs(directory)
expectedFiles = [ ...
    "simulation_summary.json", ...
    "packet_reception_ratio_LTE.csv", ...
    "wireless_blind_spot_LTE.csv"];
for expectedFile = expectedFiles
    expectedPath = fullfile(directory, expectedFile);
    if ~isfile(expectedPath)
        error( ...
            "v2xsimregression:bazzi2020blindspots:MissingOutput", ...
            "The simulator did not create the expected file: %s", ...
            expectedPath);
    end
end
end

function validateSimulator( ...
        simulatorRoot, sourceDirectory, configurationFile)
if ~isfolder(simulatorRoot)
    error( ...
        "v2xsimregression:bazzi2020blindspots:" + ...
        "MissingSimulatorRoot", ...
        "SimulatorRoot is not a directory: %s", simulatorRoot);
end
if ~isfile(fullfile( ...
        sourceDirectory, "+v2xsim", "runSimulation.m"))
    error( ...
        "v2xsimregression:bazzi2020blindspots:MissingSimulator", ...
        "v2xsim.runSimulation was not found under: %s", ...
        simulatorRoot);
end
if ~isfile(configurationFile)
    error( ...
        "v2xsimregression:bazzi2020blindspots:" + ...
        "MissingConfiguration", ...
        "The Bazzi 2020 configuration was not found: %s", ...
        configurationFile);
end
end

function prepareOutputDirectory(outputDirectory)
if isfolder(outputDirectory)
    directoryEntries = dir(outputDirectory);
    entryNames = string({directoryEntries.name});
    isContent = ~ismember(entryNames, [".", ".."]);
    if any(isContent)
        error( ...
            "v2xsimregression:bazzi2020blindspots:OutputNotEmpty", ...
            "Refusing to append results in nonempty folder: %s", ...
            outputDirectory);
    end
else
    [wasCreated, message] = mkdir(outputDirectory);
    if ~wasCreated
        error( ...
            "v2xsimregression:bazzi2020blindspots:" + ...
            "OutputCreationFailed", ...
            "Could not create output folder %s: %s", ...
            outputDirectory, message);
    end
end
end

function restoreEnvironment( ...
        originalPath, originalStream, originalStreamState, ...
        originalWarningState)
path(originalPath);
RandStream.setGlobalStream(originalStream);
originalStream.State = originalStreamState;
warning(originalWarningState);
end

function pathValue = absolutePath(pathValue, baseDirectory)
if ~isAbsolutePath(pathValue)
    pathValue = fullfile(baseDirectory, pathValue);
end
end

function result = isAbsolutePath(pathValue)
if ispc
    result = ~isempty(regexp( ...
        pathValue, "^[A-Za-z]:[\\/]|^\\\\", "once"));
else
    result = startsWith(pathValue, "/");
end
end
