classdef ServiceContainerTest < matlab.unittest.TestCase
    %SERVICECONTAINERTEST Tests hook dependency provider lifetimes.

    methods (Test)
        function testProvidesValueConstant(testCase)
            import v2xsim.hook.dependencies.OutputDirectory

            container = ...
                v2xsim.hook.dependency.ServiceContainer();
            expected = OutputDirectory(tempdir);
            dependencyType = ...
                ?v2xsim.hook.dependencies.OutputDirectory;
            container.provideConstant(dependencyType, expected);

            actual = container.resolve(dependencyType);

            testCase.verifyEqual(actual, expected);
        end

        function testClassProviderConstructsEveryResolution(testCase)
            import v2xsimtest.hook.dependency.fixture.TransientDependency

            container = ...
                v2xsim.hook.dependency.ServiceContainer();
            dependencyType = ...
                ?v2xsimtest.hook.dependency.fixture. ...
                TransientDependency;
            container.provideClass( ...
                dependencyType, ...
                "v2xsimtest.hook.dependency.fixture." + ...
                "TransientDependency");

            first = container.resolve(dependencyType);
            second = container.resolve(dependencyType);

            testCase.verifyFalse(first == second);
        end

        function testInstanceProviderReturnsSharedHandle(testCase)
            import v2xsimtest.hook.dependency.fixture.TransientDependency

            container = ...
                v2xsim.hook.dependency.ServiceContainer();
            expected = TransientDependency();
            dependencyType = ...
                ?v2xsimtest.hook.dependency.fixture. ...
                TransientDependency;
            container.provideInstance( ...
                dependencyType, expected);

            first = container.resolve(dependencyType);
            second = container.resolve(dependencyType);

            testCase.verifyTrue(first == expected);
            testCase.verifyTrue(second == expected);
        end

        function testResolveAllPreservesRequestedOrder(testCase)
            import v2xsim.hook.dependencies.OutputDirectory
            import v2xsimtest.hook.dependency.fixture.TransientDependency

            container = ...
                v2xsim.hook.dependency.ServiceContainer();
            outputDirectory = OutputDirectory(tempdir);
            transient = TransientDependency();
            container.provideConstant( ...
                ?v2xsim.hook.dependencies.OutputDirectory, ...
                outputDirectory);
            container.provideInstance( ...
                ?v2xsimtest.hook.dependency.fixture. ...
                TransientDependency, ...
                transient);

            resolved = container.resolveAll( ...
                [ ...
                ?v2xsimtest.hook.dependency.fixture. ...
                TransientDependency, ...
                ?v2xsim.hook.dependencies.OutputDirectory]);

            testCase.verifyTrue(resolved{1} == transient);
            testCase.verifyEqual( ...
                resolved{2}, outputDirectory);
        end

        function testResolveAllRejectsUntypedEmptyArray(testCase)
            container = ...
                v2xsim.hook.dependency.ServiceContainer();

            testCase.verifyError( ...
                @() container.resolveAll([]), ...
                "v2xsim:hook:dependency:InvalidDependencyType");
        end

        function testReprovidingDependencyReplacesProvider(testCase)
            import v2xsim.hook.dependencies.OutputDirectory

            container = ...
                v2xsim.hook.dependency.ServiceContainer();
            container.provideConstant( ...
                ?v2xsim.hook.dependencies.OutputDirectory, ...
                OutputDirectory(tempdir));
            expected = OutputDirectory(pwd);
            container.provideConstant( ...
                ?v2xsim.hook.dependencies.OutputDirectory, ...
                expected);

            testCase.verifyEqual( ...
                container.resolve( ...
                ?v2xsim.hook.dependencies.OutputDirectory), ...
                expected);
        end

        function testContainerBindingsAreIsolated(testCase)
            import v2xsim.hook.dependencies.OutputDirectory

            first = v2xsim.hook.dependency.ServiceContainer();
            second = v2xsim.hook.dependency.ServiceContainer();
            first.provideConstant( ...
                ?v2xsim.hook.dependencies.OutputDirectory, ...
                OutputDirectory(tempdir));

            testCase.verifyError( ...
                @() second.resolve( ...
                    ?v2xsim.hook.dependencies.OutputDirectory), ...
                "v2xsim:hook:dependency:NotProvided");
        end

        function testRejectsNonDependencyKey(testCase)
            container = ...
                v2xsim.hook.dependency.ServiceContainer();

            testCase.verifyError( ...
                @() container.resolve(?string), ...
                "v2xsim:hook:dependency:InvalidDependencyType");
        end

        function testRejectsHandleAsConstant(testCase)
            import v2xsimtest.hook.dependency.fixture.TransientDependency

            container = ...
                v2xsim.hook.dependency.ServiceContainer();

            testCase.verifyError( ...
                @() container.provideConstant( ...
                    ?v2xsimtest.hook.dependency.fixture. ...
                    TransientDependency, ...
                    TransientDependency()), ...
                "v2xsim:hook:dependency:HandleConstant");
        end

        function testRejectsValueAsSingleton(testCase)
            import v2xsim.hook.dependencies.OutputDirectory

            container = ...
                v2xsim.hook.dependency.ServiceContainer();

            testCase.verifyError( ...
                @() container.provideInstance( ...
                    ?v2xsim.hook.dependencies.OutputDirectory, ...
                    OutputDirectory(tempdir)), ...
                "v2xsim:hook:dependency:ValueInstance");
        end

        function testRejectsIncompatibleClassProvider(testCase)
            import v2xsim.hook.dependencies.OutputDirectory

            container = ...
                v2xsim.hook.dependency.ServiceContainer();

            testCase.verifyError( ...
                @() container.provideClass( ...
                    ?v2xsim.hook.dependencies.OutputDirectory, ...
                    "v2xsimtest.hook.dependency.fixture." + ...
                    "TransientDependency"), ...
                "v2xsim:hook:dependency:IncompatibleClass");
        end

        function testReportsConstructorDependenciesAtResolution( ...
                testCase)
            import v2xsimtest.hook.dependency.fixture.ConfiguredDependency

            container = ...
                v2xsim.hook.dependency.ServiceContainer();
            dependencyType = ...
                ?v2xsimtest.hook.dependency.fixture. ...
                ConfiguredDependency;
            container.provideClass( ...
                dependencyType, ...
                "v2xsimtest.hook.dependency.fixture." + ...
                "ConfiguredDependency");

            testCase.verifyError( ...
                @() container.resolve(dependencyType), ...
                "v2xsim:hook:dependency:ConstructionFailed");
        end

        function testRejectsDeletedSingletonAtResolution(testCase)
            import v2xsimtest.hook.dependency.fixture.TransientDependency

            container = ...
                v2xsim.hook.dependency.ServiceContainer();
            instance = TransientDependency();
            dependencyType = ...
                ?v2xsimtest.hook.dependency.fixture. ...
                TransientDependency;
            container.provideInstance( ...
                dependencyType, instance);
            delete(instance);

            testCase.verifyError( ...
                @() container.resolve(dependencyType), ...
                "v2xsim:hook:dependency:DeletedInstance");
        end
    end
end
