%% 05 - Inspect hook-backed output artifacts
% Optional recorders publish stable CSV names alongside the JSON completion
% summary. Packet fates use CSV here so the example needs no extra toolbox.

exampleScriptDirectory = fileparts(mfilename("fullpath"));
[exampleResults,exampleOutputDirectory] = runExample( ...
    exampleScriptDirectory);
clear exampleScriptDirectory

disp(exampleResults.Artifacts)
fprintf("Completed output: %s\n",exampleOutputDirectory);

function [results,outputDirectory] = runExample(exampleDirectory)
timer = tic;
configurationFile = fullfile( ...
    exampleDirectory,"05_output_artifacts.toml");
outputDirectory = string(tempname);
template = v2xsim.config.load(configurationFile);
configuration = template.resolve();
simulationTimer = tic;
simulationResult = v2xsim.runSimulation( ...
    configuration, ...
    OutputDirectory=outputDirectory, ...
    RunLabel="output-artifacts");
simulationElapsedSeconds = toc(simulationTimer);
outputDirectory = simulationResult.RunDirectory;
summary = jsondecode(fileread(fullfile( ...
    simulationResult.RunDirectory,"simulation_summary.json")));

artifactFiles = dir(simulationResult.RunDirectory);
artifactFiles = artifactFiles(~[artifactFiles.isdir]);
artifactTable = table( ...
    string({artifactFiles.name}).', ...
    [artifactFiles.bytes].', ...
    VariableNames=["Artifact","Bytes"]);
artifactTable = sortrows(artifactTable,"Artifact");

prrFiles = dir(fullfile( ...
    outputDirectory,"packet_reception_ratio_*.csv"));
assert(~isempty(prrFiles), ...
    "The output example did not produce a PRR artifact.");
prrValues = readmatrix(fullfile(prrFiles(1).folder,prrFiles(1).name));
prr = array2table( ...
    prrValues, ...
    VariableNames=[ ...
        "DistanceUpperBoundMeters","CorrectCount","ErrorCount", ...
        "BlockedCount","OpportunityCount","PacketReceptionRatio"]);

figure(Name="V7 packet reception ratio");
plot( ...
    prr.DistanceUpperBoundMeters,prr.PacketReceptionRatio, ...
    "o-",LineWidth=1.2);
grid on
xlabel("Distance upper bound (m)")
ylabel("Packet reception ratio")
ylim([0,1])
title("Distance-binned cellular packet reception ratio")

elapsedSeconds = toc(timer);
if elapsedSeconds > 30
    warning( ...
        "v2xsimexample:SlowExample", ...
        "This example took %.1f seconds on this computer.", ...
        elapsedSeconds);
end
results = struct( ...
    SimulationResult=simulationResult, ...
    Summary=summary, ...
    Artifacts=artifactTable, ...
    PacketReceptionRatio=prr, ...
    SimulationElapsedSeconds=simulationElapsedSeconds, ...
    ElapsedSeconds=elapsedSeconds);
end
