%% 05 - Inspect hook-backed output artifacts
% Optional recorders publish stable CSV names alongside the JSON completion
% summary. Packet fates use CSV here so the example needs no extra toolbox.

exampleScriptDirectory = fileparts(mfilename("fullpath"));
[exampleResults,exampleOutputDirectory] = runExample( ...
    exampleScriptDirectory);
clear exampleScriptDirectory

disp(exampleResults.Artifacts)
fprintf("Completed output: %s\n",exampleOutputDirectory);

function [results,outputDirectory] = runExample(exampleDirectory)
timer = tic;
configurationFile = fullfile( ...
    exampleDirectory,"05_output_artifacts.toml");
outputDirectory = string(tempname);
template = v2xsim.config.load(configurationFile);
repetitionCount = 5;
baseSeed = template.Data.Simulation.RandomSeed;
prrRows = table();
simulationTimer = tic;
for repetition = 1:repetitionCount
    configuration = template.resolve(Patch=v2xsim.config.patch(struct( ...
        "Simulation",struct("RandomSeed",baseSeed + repetition - 1))));
    repetitionOutputDirectory = string(tempname);
    simulationResult = v2xsim.runSimulation( ...
        configuration, ...
        OutputDirectory=repetitionOutputDirectory, ...
        RunLabel="output-artifacts-repetition-" + repetition);
    outputDirectory = simulationResult.RunDirectory;
    prrRows = [prrRows; ...
        v2xsim.analysis.readDeliveryPrrArtifact(outputDirectory)]; %#ok<AGROW>
end
simulationElapsedSeconds = toc(simulationTimer);
summary = jsondecode(fileread(fullfile( ...
    simulationResult.RunDirectory,"simulation_summary.json")));

artifactFiles = dir(simulationResult.RunDirectory);
artifactFiles = artifactFiles(~[artifactFiles.isdir]);
artifactTable = table( ...
    string({artifactFiles.name}).', ...
    [artifactFiles.bytes].', ...
    VariableNames=["Artifact","Bytes"]);
artifactTable = sortrows(artifactTable,"Artifact");

prrFiles = dir(fullfile( ...
    outputDirectory,"packet_reception_ratio_*.csv"));
assert(~isempty(prrFiles), ...
    "The output example did not produce a PRR artifact.");
prr = v2xsim.analysis.poolPacketReceptionCounts(prrRows, ...
    GroupVariables=strings(1,0));
[deliveryPrrRangeMeters,deliveryPrrRangeStatus,plotCurve] = ...
    v2xsim.analysis.prrThresholdRange(prr);

figure(Name="V7 delivery PRR");
plot( ...
    plotCurve.DistanceMeters,plotCurve.DeliveryPrr, ...
    "o-",LineWidth=1.2,DisplayName="Delivery PRR");
hold on
yline(0.9,"--",DisplayName="90% threshold");
if isfinite(deliveryPrrRangeMeters)
    xline( ...
        deliveryPrrRangeMeters,":", ...
        "90% range: " + string(sprintf( ...
            "%.1f m (%s)",deliveryPrrRangeMeters, ...
            char(deliveryPrrRangeStatus))), ...
        DisplayName="90% range");
    if deliveryPrrRangeStatus == "Crossed"
        plot( ...
            deliveryPrrRangeMeters,0.9,"o", ...
            DisplayName="Threshold crossing");
    end
else
    text(0.02,0.08,"90% range unavailable: incomplete distance grid", ...
        Units="normalized");
end
hold off
grid on
xlabel("Distance (m)")
ylabel("Delivery PRR")
ylim([0,1])
title("Distance-binned cellular delivery PRR")
legend(Location="best")

elapsedSeconds = toc(timer);
if elapsedSeconds > 30
    warning( ...
        "v2xsimexample:SlowExample", ...
        "This example took %.1f seconds on this computer.", ...
        elapsedSeconds);
end
results = struct( ...
    SimulationResult=simulationResult, ...
    Summary=summary, ...
    Artifacts=artifactTable, ...
    PacketReceptionRatio=prr, ...
    DeliveryPrrByDistance=prr, ...
    DeliveryPrrRangeMeters=deliveryPrrRangeMeters, ...
    DeliveryPrrRangeStatus=deliveryPrrRangeStatus, ...
    RepetitionCount=repetitionCount, ...
    SimulationElapsedSeconds=simulationElapsedSeconds, ...
    ElapsedSeconds=elapsedSeconds);
end
