function results = runPublishedCampaigns( ...
        simulatorRoot, outputDirectory, options)
%RUNPUBLISHEDCAMPAIGNS Run the Todisco et al. 2021 paper campaigns.
%   RESULTS is one row per simulated configuration, with a normalized
%   area-under-PRR score and the furthest sampled distance at which PRR is
%   at least 0.9.
%
%   SIMULATORROOT is the current repository root. The paper's legacy
%   highway inputs and Mode 2 controls are expressed through the modern
%   scenario and resource-selection parameters.
%
%   The regression duration is fixed at the 10 seconds used by the
%   published scripts. Figures can contain any combination of 7, 9, and 11.

arguments (Input)
    simulatorRoot (1, 1) string {mustBeNonzeroLengthText}
    outputDirectory (1, 1) string {mustBeNonzeroLengthText}
    options.Figures (1, :) double ...
        {mustBeInteger, mustBeMember(options.Figures, [7, 9, 11])} = ...
        [7, 9, 11]
    options.ExecutionMode (1, 1) string {mustBeMember( ...
        options.ExecutionMode, ["auto", "serial", "parallel"])} = "auto"
    options.MaxWorkers (1, 1) double { ...
        v2xsimregression.execution.mustBeWorkerLimit} = Inf
end

arguments (Output)
    results table
end

simulationTimeSeconds = 10;
[simulatorDirectory, paperDirectory] = ...
    resolveSimulatorDirectories(simulatorRoot);
validateSimulatorRoot( ...
    simulatorRoot, simulatorDirectory, paperDirectory);
prepareOutputDirectory(outputDirectory);

originalPath = path;
randomStream = RandStream.getGlobalStream();
originalRandomState = randomStream.State;
environmentCleanup = onCleanup( ...
    @() restoreEnvironment( ...
        originalPath, randomStream, originalRandomState));

addpath(fullfile(simulatorRoot, "src"));
addpath(simulatorDirectory);

workItems = cell(1, 0);
if ismember(7, options.Figures)
    workItems = [workItems, createFigure7WorkItems( ...
        simulatorDirectory, paperDirectory, outputDirectory, ...
        simulationTimeSeconds)];
end
if ismember(9, options.Figures)
    workItems = [workItems, createFigure9WorkItems( ...
        simulatorDirectory, paperDirectory, outputDirectory, ...
        simulationTimeSeconds)];
end
if ismember(11, options.Figures)
    workItems = [workItems, createFigure11WorkItems( ...
        simulatorDirectory, paperDirectory, outputDirectory, ...
        simulationTimeSeconds)];
end

workLabels = cellfun( ...
    @(workItem) workItem.Label, workItems, UniformOutput=false);
additionalPaths = [ ...
    fullfile(simulatorRoot, "regression-tests"), ...
    fullfile(simulatorRoot, "src"), ...
    simulatorDirectory];
resultCells = v2xsimregression.execution.runWorkItems( ...
    workItems, @runCaseWorkItem, ...
    Labels=string(workLabels), ...
    ExecutionMode=options.ExecutionMode, ...
    MaxWorkers=options.MaxWorkers, ...
    AdditionalPaths=additionalPaths);
if isempty(resultCells)
    results = createEmptyResults(0);
else
    results = vertcat(resultCells{:});
end
end

function workItems = createFigure7WorkItems( ...
        simulatorDirectory, paperDirectory, outputDirectory, ...
        simulationTimeSeconds)
workItems = cell(1, 5);
workIndex = 0;
subcarrierSpacingsKilohertz = [15, 30, 60];
dmrsCounts = [24, 18, 12];

for spacingIndex = 1:numel(subcarrierSpacingsKilohertz)
    for hasIbe = [true, false]
        if subcarrierSpacingsKilohertz(spacingIndex) == 60 && hasIbe
            continue
        end

        caseName = compose( ...
            "scs-%d-ibe-%d", ...
            subcarrierSpacingsKilohertz(spacingIndex), hasIbe);
        caseOutputDirectory = fullfile( ...
            outputDirectory, "figure-7", caseName);
        figureArguments = { ...
            "application.PacketSizeBytes", 350, ...
            "application.ResourceReservationIntervalSeconds", 0.1, ...
            "nrV2x.Mcs", 21, ...
            "nrV2x.SubcarrierSpacingKilohertz", subcarrierSpacingsKilohertz(spacingIndex), ...
            "nrV2x.DmrsResourceElementCountPerSlot", dmrsCounts(spacingIndex), ...
            "sidelink.InBandEmissionEnabled", hasIbe};

        summaryArguments = { ...
            7, caseName, 350, ...
            subcarrierSpacingsKilohertz(spacingIndex), hasIbe, ...
            NaN, NaN, NaN, NaN, NaN, NaN, 150, ...
            caseOutputDirectory};
        workIndex = workIndex + 1;
        workItems{workIndex} = createWorkItem( ...
            simulatorDirectory, paperDirectory, caseOutputDirectory, ...
            simulationTimeSeconds, 7, figureArguments, ...
            summaryArguments, "figure-7/" + caseName);
    end
end
end

function workItems = createFigure9WorkItems( ...
        simulatorDirectory, paperDirectory, outputDirectory, ...
        simulationTimeSeconds)
workItems = cell(1, 12);
workIndex = 0;
candidateFractions = [1, 0.5, 0.2];
sensingThresholdsDbm = [-126, -110];
packetSizesBytes = [350, 1000];

for candidateFraction = candidateFractions
    for sensingThresholdDbm = sensingThresholdsDbm
        for packetSizeBytes = packetSizesBytes
            if packetSizeBytes == 350
                mcsIndex = 4;
            else
                mcsIndex = 11;
            end

            caseName = compose( ...
                "packet-%d-m-%d-threshold-%d", ...
                packetSizeBytes, round(100 .* candidateFraction), ...
                sensingThresholdDbm);
            caseOutputDirectory = fullfile( ...
                outputDirectory, "figure-9", caseName);
            [l2Arguments, thresholdFloorFraction, l2Active] = ...
                createL2Arguments(candidateFraction, false);
            figureArguments = [{ ...
                "application.PacketSizeBytes", packetSizeBytes, ...
                "application.ResourceReservationIntervalSeconds", 0.1, ...
                "nrV2x.Mcs", mcsIndex, ...
                "nrV2x.SubcarrierSpacingKilohertz", 15, ...
                "nrV2x.DmrsResourceElementCountPerSlot", 24, ...
                "resourceAllocation.Autonomous.SensingThresholdDbm", sensingThresholdDbm}, ...
                l2Arguments];

            summaryArguments = { ...
                9, caseName, packetSizeBytes, 15, NaN, ...
                thresholdFloorFraction, candidateFraction, l2Active, ...
                sensingThresholdDbm, NaN, NaN, 350, ...
                caseOutputDirectory};
            workIndex = workIndex + 1;
            workItems{workIndex} = createWorkItem( ...
                simulatorDirectory, paperDirectory, ...
                caseOutputDirectory, simulationTimeSeconds, 9, ...
                figureArguments, summaryArguments, ...
                "figure-9/" + caseName);
        end
    end
end
end

function workItems = createFigure11WorkItems( ...
        simulatorDirectory, paperDirectory, outputDirectory, ...
        simulationTimeSeconds)
workItems = cell(1, 5);
workIndex = 0;
candidateFractions = [1, 0.2];

for candidateFraction = candidateFractions
    for averagesRsrp = [true, false]
        for hasCoherentArrivals = [true, false]
            if hasCoherentArrivals && ...
                    (candidateFraction == 0.2 || averagesRsrp)
                continue
            end

            if hasCoherentArrivals
                allocationPeriodSeconds = 0.2;
            else
                allocationPeriodSeconds = 0.1;
            end

            caseName = compose( ...
                "m-%d-average-%d-coherent-%d", ...
                round(100 .* candidateFraction), averagesRsrp, ...
                hasCoherentArrivals);
            caseOutputDirectory = fullfile( ...
                outputDirectory, "figure-11", caseName);
            [l2Arguments, thresholdFloorFraction, l2Active] = ...
                createL2Arguments(candidateFraction, averagesRsrp);
            figureArguments = [{ ...
                "application.PacketSizeBytes", 350, ...
                "application.ResourceReservationIntervalSeconds", allocationPeriodSeconds, ...
                "application.PacketGeneration.IntervalSeconds", 0.2, ...
                "nrV2x.Mcs", 4, ...
                "nrV2x.SubcarrierSpacingKilohertz", 15, ...
                "nrV2x.DmrsResourceElementCountPerSlot", 24, ...
                "resourceAllocation.Autonomous.SensingThresholdDbm", -126}, ...
                l2Arguments];

            summaryArguments = { ...
                11, caseName, 350, 15, NaN, ...
                thresholdFloorFraction, candidateFraction, l2Active, ...
                -126, averagesRsrp, hasCoherentArrivals, 500, ...
                caseOutputDirectory};
            workIndex = workIndex + 1;
            workItems{workIndex} = createWorkItem( ...
                simulatorDirectory, paperDirectory, ...
                caseOutputDirectory, simulationTimeSeconds, 11, ...
                figureArguments, summaryArguments, ...
                "figure-11/" + caseName);
        end
    end
end
end

function workItem = createWorkItem( ...
        simulatorDirectory, paperDirectory, outputDirectory, ...
        simulationTimeSeconds, figureNumber, figureArguments, ...
        summaryArguments, label)
workItem = struct( ...
    SimulatorDirectory=simulatorDirectory, ...
    PaperDirectory=paperDirectory, ...
    OutputDirectory=outputDirectory, ...
    SimulationTimeSeconds=simulationTimeSeconds, ...
    FigureNumber=figureNumber, ...
    FigureArguments={figureArguments}, ...
    SummaryArguments={summaryArguments}, ...
    Label=label);
end

function result = runCaseWorkItem(workItem)
runSimulation( ...
    workItem.SimulatorDirectory, workItem.PaperDirectory, ...
    workItem.OutputDirectory, workItem.SimulationTimeSeconds, ...
    workItem.FigureNumber, workItem.FigureArguments);
result = summarizePrr(workItem.SummaryArguments{:});
end

function [l2Arguments, thresholdFloorFraction, l2Active] = ...
        createL2Arguments(candidateFraction, averagesRsrp)
arguments (Input)
    candidateFraction (1, 1) double ...
        {mustBeReal, mustBeFinite, mustBeBetween( ...
            candidateFraction, 0.2, 1)}
    averagesRsrp (1, 1) logical
end

thresholdFloorFraction = 0.2;
l2Active = candidateFraction < 1;
l2Arguments = { ...
    "resourceAllocation.Autonomous.MinimumCandidateFraction", thresholdFloorFraction, ...
    "resourceAllocation.Autonomous.L2CandidateFraction", candidateFraction, ...
    "resourceAllocation.Autonomous.L2RankingEnabled", l2Active, ...
    "resourceAllocation.Autonomous.AverageSensingEnabled", averagesRsrp};
end

function runSimulation( ...
        simulatorDirectory, paperDirectory, outputDirectory, ...
        simulationTimeSeconds, figureNumber, figureArguments)
configurationFile = fullfile( ...
    paperDirectory, compose("fig%d_config.cfg", figureNumber));

commonArguments = { ...
    configurationFile, ...
    "simulation.RequiredVersion", "V7", ...
    "simulation.RandomSeed", 10, ...
    "scenarioOptions.RandomSeed", 10, ...
    "simulation.DurationSeconds", simulationTimeSeconds, ...
    "awareness.RangesMeters", 150, ...
    "simulation.RadioAccessMode", "5G-V2X", ...
    "radio.ReceiverNoiseFigureDb", 6, ...
    "resourceAllocation.Autonomous.KeepResourceProbability", 0.4, ...
    "radio.BandwidthMHz", 10, ...
    "resourcePool.SubchannelSizeResourceBlocks", 10, ...
    "sidelink.Harq.MaximumTransmissionCount", 1, ...
    "radio.FixedPowerDensityEnabled", true, ...
    "congestionControl.Enabled", false, ...
    "channelLoad.Enabled", true, ...
    "output.PacketReceptionRatio.Enabled", true, ...
    "output.AverageNeighborCount.Enabled", false, ...
    "output.UpdateDelay.Enabled", false, ...
    "output.PacketDelay.Enabled", false, ...
    "output.DataAge.Enabled", false, ...
    "output.ChannelBusyRatio.Enabled", false, ...
    "output.Directory", outputDirectory};

scenarioArguments = { ...
    "scenario.Type", "BidirectionalHighwayScenario", ...
    "scenarioOptions.VehicleCount", 200, ...
    "scenarioOptions.NLanes", 3, ...
    "scenarioOptions.LaneWidth", 4, ...
    "scenarioOptions.RoadLength", 2000, ...
    "scenarioOptions.CentralDividerWidth", 0, ...
    "scenarioOptions.MeanVehicleSpeed", 70 ./ 3.6, ...
    "scenarioOptions.VehicleSpeedStandardDeviation", 7 ./ 3.6, ...
    "scenarioOptions.RerollSpeedOnWrapAround", false};

configuredArguments = [ ...
    commonArguments, scenarioArguments, figureArguments];
simulationArguments = configuredArguments; %#ok<NASGU>
evalc("v2xsim.runSimulation(simulationArguments{:});");

expectedOutputFiles = [ ...
    "simulation_summary.json", ...
    "packet_reception_ratio_5G.csv"];
for expectedOutputFile = expectedOutputFiles
    expectedPath = fullfile(outputDirectory,expectedOutputFile);
    if ~isfile(expectedPath)
        error( ...
            "v2xsimregression:vittorio2021:MissingOutput", ...
            "The simulator did not create the expected file: %s", ...
            expectedPath);
    end
end

resolvedEntrypoint = string(which("v2xsim.runSimulation"));
expectedSourceDirectory = fullfile(fileparts(simulatorDirectory), "src");
if ~startsWith(resolvedEntrypoint, expectedSourceDirectory)
    error( ...
        "v2xsimregression:vittorio2021:WrongSimulator", ...
        "v2xsim.runSimulation resolved outside the requested simulator: %s", ...
        resolvedEntrypoint);
end
end

function summary = summarizePrr( ...
        figureNumber, caseName, packetSizeBytes, ...
        subcarrierSpacingKilohertz, hasIbe, ...
        thresholdFloorFraction, l2SelectionFraction, l2Active, ...
        sensingThresholdDbm, averagesRsrp, hasCoherentArrivals, ...
        maximumScoreDistanceMeters, outputDirectory)
hasIbe = double(hasIbe);
l2Active = double(l2Active);
averagesRsrp = double(averagesRsrp);
hasCoherentArrivals = double(hasCoherentArrivals);

prrFile = fullfile( ...
    outputDirectory, "packet_reception_ratio_5G.csv");
prrData = readmatrix( ...
    prrFile, FileType="text", Delimiter=",");
distancesMeters = prrData(:, 1);
packetReceptionRatios = prrData(:, 6);
isFiniteSample = ...
    isfinite(distancesMeters) & isfinite(packetReceptionRatios);
distancesMeters = distancesMeters(isFiniteSample);
packetReceptionRatios = packetReceptionRatios(isFiniteSample);

isScoredSample = distancesMeters <= maximumScoreDistanceMeters;
scoredDistancesMeters = [0; distancesMeters(isScoredSample)];
scoredPrr = [1; packetReceptionRatios(isScoredSample)];
normalizedPrrScore = ...
    trapz(scoredDistancesMeters, scoredPrr) ./ ...
    maximumScoreDistanceMeters;

reliableDistancesMeters = ...
    distancesMeters(packetReceptionRatios >= 0.9);
if isempty(reliableDistancesMeters)
    rangeAt90Meters = 0;
else
    rangeAt90Meters = max(reliableDistancesMeters);
end

summary = table( ...
    figureNumber, caseName, packetSizeBytes, ...
    subcarrierSpacingKilohertz, hasIbe, thresholdFloorFraction, ...
    l2SelectionFraction, l2Active, sensingThresholdDbm, ...
    averagesRsrp, hasCoherentArrivals, maximumScoreDistanceMeters, ...
    normalizedPrrScore, rangeAt90Meters, outputDirectory, ...
    VariableNames=[ ...
        "Figure", "CaseName", "PacketSizeBytes", ...
        "SubcarrierSpacingKilohertz", "HasIbe", ...
        "ThresholdFloorFraction", "L2SelectionFraction", ...
        "resourceAllocation.Autonomous.L2RankingEnabled", "SensingThresholdDbm", "AveragesRsrp", ...
        "HasCoherentArrivals", ...
        "MaximumScoreDistanceMeters", "NormalizedPrrScore", ...
        "RangeAt90Meters", "OutputDirectory"]);
end

function results = createEmptyResults(rowCount)
arguments (Input)
    rowCount (1, 1) double ...
        {mustBeInteger, mustBeNonnegative}
end

results = table( ...
    Size=[rowCount, 15], ...
    VariableTypes=[ ...
        "double", "string", "double", "double", "double", ...
        "double", "double", "double", "double", "double", ...
        "double", "double", "double", "double", "string"], ...
    VariableNames=[ ...
        "Figure", "CaseName", "PacketSizeBytes", ...
        "SubcarrierSpacingKilohertz", "HasIbe", ...
        "ThresholdFloorFraction", "L2SelectionFraction", ...
        "resourceAllocation.Autonomous.L2RankingEnabled", "SensingThresholdDbm", "AveragesRsrp", ...
        "HasCoherentArrivals", ...
        "MaximumScoreDistanceMeters", "NormalizedPrrScore", ...
        "RangeAt90Meters", "OutputDirectory"]);
end

function [simulatorDirectory, paperDirectory] = ...
        resolveSimulatorDirectories(simulatorRoot)
simulatorDirectory = fullfile(simulatorRoot, "old_src");
paperDirectory = fullfile( ...
    simulatorDirectory, "codeForPaper", "Vittorio2021Performance");
end

function validateSimulatorRoot( ...
        simulatorRoot, simulatorDirectory, paperDirectory)
if ~isfolder(simulatorRoot)
    error( ...
        "v2xsimregression:vittorio2021:MissingSimulatorRoot", ...
        "SimulatorRoot is not a directory: %s", simulatorRoot);
end
if ~isfile(fullfile( ...
        simulatorRoot, "src", "+v2xsim", "runSimulation.m"))
    error( ...
        "v2xsimregression:vittorio2021:MissingSimulator", ...
        "v2xsim.runSimulation was not found under: %s", ...
        simulatorRoot);
end
if ~isfolder(paperDirectory)
    error( ...
        "v2xsimregression:vittorio2021:MissingPaperCode", ...
        "The Vittorio2021Performance folder was not found under: %s", ...
        simulatorDirectory);
end
if ~isfolder(fullfile(simulatorRoot, "src", "+v2xsim"))
    error( ...
        "v2xsimregression:vittorio2021:MissingRefactoredSource", ...
        "The simulator root requires src/+v2xsim under: %s", ...
        simulatorRoot);
end
end

function prepareOutputDirectory(outputDirectory)
if isfolder(outputDirectory)
    directoryEntries = dir(outputDirectory);
    entryNames = string({directoryEntries.name});
    isContent = ~ismember(entryNames, [".", ".."]);
    if any(isContent)
        error( ...
            "v2xsimregression:vittorio2021:OutputNotEmpty", ...
            "Refusing to append simulator results in nonempty folder: %s", ...
            outputDirectory);
    end
else
    [wasCreated, message] = mkdir(outputDirectory);
    if ~wasCreated
        error( ...
            "v2xsimregression:vittorio2021:OutputCreationFailed", ...
            "Could not create output folder %s: %s", ...
            outputDirectory, message);
    end
end
end

function restoreEnvironment( ...
        originalPath, randomStream, originalRandomState)
path(originalPath);
RandStream.setGlobalStream(randomStream);
randomStream.State = originalRandomState;
end
