function results = runPublishedCampaigns( ...
        simulatorRoot, outputDirectory, options)
%RUNPUBLISHEDCAMPAIGNS Run the Todisco et al. 2021 paper campaigns.
%   RESULTS is one row per simulated configuration, with a normalized
%   area-under-PRR score and the furthest sampled distance at which PRR is
%   at least 0.9.
%
%   SIMULATORROOT is the current repository root. The paper's legacy
%   highway inputs and Mode 2 controls are expressed through the modern
%   scenario and resource-selection parameters.
%
%   The regression duration is fixed at the 10 seconds used by the
%   published scripts. Figures can contain any combination of 7, 9, and 11.

arguments (Input)
    simulatorRoot (1, 1) string {mustBeNonzeroLengthText}
    outputDirectory (1, 1) string {mustBeNonzeroLengthText}
    options.Figures (1, :) double ...
        {mustBeInteger, mustBeMember(options.Figures, [7, 9, 11])} = ...
        [7, 9, 11]
    options.ExecutionMode (1, 1) string {mustBeMember( ...
        options.ExecutionMode, ["auto", "serial", "parallel"])} = "auto"
    options.MaxWorkers (1, 1) double { ...
        v2xsimregression.execution.mustBeWorkerLimit} = Inf
end

arguments (Output)
    results table
end

simulationTimeSeconds = 10;
[sourceDirectory, configurationDirectory, tomlDirectory] = ...
    resolveSimulatorDirectories(simulatorRoot);
validateSimulatorRoot( ...
    simulatorRoot, sourceDirectory, configurationDirectory);
prepareOutputDirectory(outputDirectory);

originalPath = path;
randomStream = RandStream.getGlobalStream();
originalRandomState = randomStream.State;
environmentCleanup = onCleanup( ...
    @() restoreEnvironment( ...
        originalPath, randomStream, originalRandomState));

addpath(sourceDirectory);
addpath(tomlDirectory);

workItems = cell(1, 0);
if ismember(7, options.Figures)
    workItems = [workItems, createFigure7WorkItems( ...
        sourceDirectory, configurationDirectory, outputDirectory, ...
        simulationTimeSeconds)];
end
if ismember(9, options.Figures)
    workItems = [workItems, createFigure9WorkItems( ...
        sourceDirectory, configurationDirectory, outputDirectory, ...
        simulationTimeSeconds)];
end
if ismember(11, options.Figures)
    workItems = [workItems, createFigure11WorkItems( ...
        sourceDirectory, configurationDirectory, outputDirectory, ...
        simulationTimeSeconds)];
end

workLabels = cellfun( ...
    @(workItem) workItem.Label, workItems, UniformOutput=false);
additionalPaths = [ ...
    fullfile(simulatorRoot, "regression-tests"), ...
    sourceDirectory, ...
    tomlDirectory];
resultCells = v2xsimregression.execution.runWorkItems( ...
    workItems, @runCaseWorkItem, ...
    Labels=string(workLabels), ...
    ExecutionMode=options.ExecutionMode, ...
    MaxWorkers=options.MaxWorkers, ...
    AdditionalPaths=additionalPaths);
if isempty(resultCells)
    results = createEmptyResults(0);
else
    results = vertcat(resultCells{:});
end
end

function workItems = createFigure7WorkItems( ...
        sourceDirectory, configurationDirectory, outputDirectory, ...
        simulationTimeSeconds)
workItems = cell(1, 5);
workIndex = 0;
subcarrierSpacingsKilohertz = [15, 30, 60];
dmrsCounts = [24, 18, 12];

for spacingIndex = 1:numel(subcarrierSpacingsKilohertz)
    for hasIbe = [true, false]
        if subcarrierSpacingsKilohertz(spacingIndex) == 60 && hasIbe
            continue
        end

        caseName = compose( ...
            "scs-%d-ibe-%d", ...
            subcarrierSpacingsKilohertz(spacingIndex), hasIbe);
        caseOutputDirectory = fullfile( ...
            outputDirectory, "figure-7", caseName);
        figurePatch = struct( ...
            Application=struct( ...
                PacketSizeBytes=350, ...
                ResourceReservationIntervalSeconds=0.1), ...
            Radio=struct( ...
                NrV2X=struct( ...
                    Mcs=21, ...
                    SubcarrierSpacingKilohertz= ...
                        subcarrierSpacingsKilohertz(spacingIndex), ...
                    DmrsResourceElementCountPerSlot= ...
                        dmrsCounts(spacingIndex)), ...
                Sidelink=struct( ...
                    InBandEmissionEnabled=hasIbe)));

        summaryArguments = { ...
            7, caseName, 350, ...
            subcarrierSpacingsKilohertz(spacingIndex), hasIbe, ...
            NaN, NaN, NaN, -126, NaN, NaN, 150, ...
            caseOutputDirectory};
        workIndex = workIndex + 1;
        workItems{workIndex} = createWorkItem( ...
            sourceDirectory, configurationDirectory, ...
            caseOutputDirectory, simulationTimeSeconds, 7, ...
            figurePatch, ...
            summaryArguments, "figure-7/" + caseName);
    end
end
end

function workItems = createFigure9WorkItems( ...
        sourceDirectory, configurationDirectory, outputDirectory, ...
        simulationTimeSeconds)
workItems = cell(1, 12);
workIndex = 0;
candidateFractions = [1, 0.5, 0.2];
sensingThresholdsDbm = [-126, -110];
packetSizesBytes = [350, 1000];

for candidateFraction = candidateFractions
    for sensingThresholdDbm = sensingThresholdsDbm
        for packetSizeBytes = packetSizesBytes
            if packetSizeBytes == 350
                mcsIndex = 4;
            else
                mcsIndex = 11;
            end

            caseName = compose( ...
                "packet-%d-m-%d-threshold-%d", ...
                packetSizeBytes, round(100 .* candidateFraction), ...
                sensingThresholdDbm);
            caseOutputDirectory = fullfile( ...
                outputDirectory, "figure-9", caseName);
            [sensingBasedPatch, thresholdFloorFraction, l2Active] = ...
                createL2Patch(candidateFraction, false);
            sensingBasedPatch.SensingThresholdDbm = ...
                sensingThresholdDbm;
            figurePatch = struct( ...
                Application=struct( ...
                    PacketSizeBytes=packetSizeBytes, ...
                    ResourceReservationIntervalSeconds=0.1), ...
                Radio=struct( ...
                    NrV2X=struct( ...
                        Mcs=mcsIndex, ...
                        SubcarrierSpacingKilohertz=15, ...
                        DmrsResourceElementCountPerSlot=24)), ...
                ResourceAllocation=struct( ...
                    SensingBased=sensingBasedPatch));

            summaryArguments = { ...
                9, caseName, packetSizeBytes, 15, NaN, ...
                thresholdFloorFraction, candidateFraction, l2Active, ...
                sensingThresholdDbm, NaN, NaN, 350, ...
                caseOutputDirectory};
            workIndex = workIndex + 1;
            workItems{workIndex} = createWorkItem( ...
                sourceDirectory, configurationDirectory, ...
                caseOutputDirectory, simulationTimeSeconds, 9, ...
                figurePatch, summaryArguments, ...
                "figure-9/" + caseName);
        end
    end
end
end

function workItems = createFigure11WorkItems( ...
        sourceDirectory, configurationDirectory, outputDirectory, ...
        simulationTimeSeconds)
workItems = cell(1, 5);
workIndex = 0;
candidateFractions = [1, 0.2];

for candidateFraction = candidateFractions
    for averagesRsrp = [true, false]
        for hasCoherentArrivals = [true, false]
            if hasCoherentArrivals && ...
                    (candidateFraction == 0.2 || averagesRsrp)
                continue
            end

            if hasCoherentArrivals
                allocationPeriodSeconds = 0.2;
            else
                allocationPeriodSeconds = 0.1;
            end

            caseName = compose( ...
                "m-%d-average-%d-coherent-%d", ...
                round(100 .* candidateFraction), averagesRsrp, ...
                hasCoherentArrivals);
            caseOutputDirectory = fullfile( ...
                outputDirectory, "figure-11", caseName);
            [sensingBasedPatch, thresholdFloorFraction, l2Active] = ...
                createL2Patch(candidateFraction, averagesRsrp);
            sensingBasedPatch.SensingThresholdDbm = -126;
            figurePatch = struct( ...
                Application=struct( ...
                    PacketSizeBytes=350, ...
                    ResourceReservationIntervalSeconds= ...
                        allocationPeriodSeconds, ...
                    PacketGeneration=struct( ...
                        IntervalSeconds=0.2)), ...
                Radio=struct( ...
                    NrV2X=struct( ...
                        Mcs=4, ...
                        SubcarrierSpacingKilohertz=15, ...
                        DmrsResourceElementCountPerSlot=24)), ...
                ResourceAllocation=struct( ...
                    SensingBased=sensingBasedPatch));

            summaryArguments = { ...
                11, caseName, 350, 15, NaN, ...
                thresholdFloorFraction, candidateFraction, l2Active, ...
                -126, averagesRsrp, hasCoherentArrivals, 500, ...
                caseOutputDirectory};
            workIndex = workIndex + 1;
            workItems{workIndex} = createWorkItem( ...
                sourceDirectory, configurationDirectory, ...
                caseOutputDirectory, simulationTimeSeconds, 11, ...
                figurePatch, summaryArguments, ...
                "figure-11/" + caseName);
        end
    end
end
end

function workItem = createWorkItem( ...
        sourceDirectory, configurationDirectory, outputDirectory, ...
        simulationTimeSeconds, figureNumber, figurePatch, ...
        summaryArguments, label)
workItem = struct( ...
    SourceDirectory=sourceDirectory, ...
    ConfigurationFile=fullfile( ...
        configurationDirectory, ...
        compose("figure%d.toml", figureNumber)), ...
    OutputDirectory=outputDirectory, ...
    SimulationTimeSeconds=simulationTimeSeconds, ...
    FigureNumber=figureNumber, ...
    FigurePatch=figurePatch, ...
    SummaryArguments={summaryArguments}, ...
    Label=label);
end

function result = runCaseWorkItem(workItem)
runSimulation( ...
    workItem.SourceDirectory, workItem.ConfigurationFile, ...
    workItem.OutputDirectory, workItem.SimulationTimeSeconds, ...
    workItem.FigurePatch, workItem.Label);
result = summarizePrr(workItem.SummaryArguments{:});
end

function [sensingBasedPatch, thresholdFloorFraction, l2Active] = ...
        createL2Patch(candidateFraction, averagesRsrp)
arguments (Input)
    candidateFraction (1, 1) double ...
        {mustBeReal, mustBeFinite, mustBeBetween( ...
            candidateFraction, 0.2, 1)}
    averagesRsrp (1, 1) logical
end

thresholdFloorFraction = 0.2;
l2Active = candidateFraction < 1;
sensingBasedPatch = struct( ...
    MinimumCandidateFraction=thresholdFloorFraction, ...
    L2CandidateFraction=candidateFraction, ...
    L2RankingEnabled=l2Active, ...
    AverageSensingEnabled=averagesRsrp);
end

function runSimulation( ...
        sourceDirectory, configurationFile, outputDirectory, ...
        simulationTimeSeconds, figurePatch, runLabel) %#ok<INUSD>
commonPatch = struct( ...
    Simulation=struct( ...
        RandomSeed=10, ...
        DurationSeconds=simulationTimeSeconds), ...
    Scenario=struct( ...
        Type="BidirectionalHighway", ...
        BidirectionalHighway=struct( ...
            RandomSeed=10, ...
            VehicleCount=200, ...
            NLanes=3, ...
            LaneWidth=4, ...
            RoadLength=2000, ...
            CentralDividerWidth=0, ...
            MeanVehicleSpeed=70 ./ 3.6, ...
            VehicleSpeedStandardDeviation=7 ./ 3.6, ...
            RerollSpeedOnWrapAround=false)), ...
    Application=struct( ...
        CongestionControl=struct(Enabled=false), ...
        ChannelLoad=struct(Enabled=true)), ...
    Radio=struct( ...
        Type="NrV2X", ...
        BandwidthMHz=10, ...
        ReceiverNoiseFigureDb=6, ...
        FixedPowerDensityEnabled=true, ...
        Sidelink=struct( ...
            MaximumTransmissionCount=1, ...
            ResourcePool=struct( ...
                SubchannelSizeResourceBlocks=10))), ...
    Awareness=struct(RangesMeters=150), ...
    ResourceAllocation=struct( ...
        Type="SensingBased", ...
        SensingBased=struct( ...
            KeepResourceProbability=0.4)), ...
    Outputs=struct( ...
        PacketReceptionRatio=struct(Enabled=true), ...
        AverageNeighborCount=struct(Enabled=false), ...
        UpdateDelay=struct(Enabled=false), ...
        PacketDelay=struct(Enabled=false), ...
        DataAge=struct(Enabled=false), ...
        ChannelBusyRatio=struct(Enabled=false)));

template = v2xsim.config.load(configurationFile);
template = template.withPatch(v2xsim.config.patch(commonPatch));
configuration = template.resolve( ...
    Patch=v2xsim.config.patch(figurePatch)); %#ok<NASGU>
evalc("v2xsim.runSimulation(configuration," + ...
    "OutputDirectory=outputDirectory,RunLabel=runLabel);");

expectedOutputFiles = [ ...
    "simulation_summary.json", ...
    "packet_reception_ratio_5G.csv"];
for expectedOutputFile = expectedOutputFiles
    expectedPath = fullfile(outputDirectory,expectedOutputFile);
    if ~isfile(expectedPath)
        error( ...
            "v2xsimregression:vittorio2021:MissingOutput", ...
            "The simulator did not create the expected file: %s", ...
            expectedPath);
    end
end

resolvedEntrypoint = string(which("v2xsim.runSimulation"));
if ~startsWith(resolvedEntrypoint, sourceDirectory)
    error( ...
        "v2xsimregression:vittorio2021:WrongSimulator", ...
        "v2xsim.runSimulation resolved outside the requested simulator: %s", ...
        resolvedEntrypoint);
end
end

function summary = summarizePrr( ...
        figureNumber, caseName, packetSizeBytes, ...
        subcarrierSpacingKilohertz, hasIbe, ...
        thresholdFloorFraction, l2SelectionFraction, l2Active, ...
        sensingThresholdDbm, averagesRsrp, hasCoherentArrivals, ...
        maximumScoreDistanceMeters, outputDirectory)
hasIbe = double(hasIbe);
l2Active = double(l2Active);
averagesRsrp = double(averagesRsrp);
hasCoherentArrivals = double(hasCoherentArrivals);

prrFile = fullfile( ...
    outputDirectory, "packet_reception_ratio_5G.csv");
prrData = readmatrix( ...
    prrFile, FileType="text", Delimiter=",");
distancesMeters = prrData(:, 1);
packetReceptionRatios = prrData(:, 6);
isFiniteSample = ...
    isfinite(distancesMeters) & isfinite(packetReceptionRatios);
distancesMeters = distancesMeters(isFiniteSample);
packetReceptionRatios = packetReceptionRatios(isFiniteSample);

isScoredSample = distancesMeters <= maximumScoreDistanceMeters;
scoredDistancesMeters = [0; distancesMeters(isScoredSample)];
scoredPrr = [1; packetReceptionRatios(isScoredSample)];
normalizedPrrScore = ...
    trapz(scoredDistancesMeters, scoredPrr) ./ ...
    maximumScoreDistanceMeters;

reliableDistancesMeters = ...
    distancesMeters(packetReceptionRatios >= 0.9);
if isempty(reliableDistancesMeters)
    rangeAt90Meters = 0;
else
    rangeAt90Meters = max(reliableDistancesMeters);
end

summary = table( ...
    figureNumber, caseName, packetSizeBytes, ...
    subcarrierSpacingKilohertz, hasIbe, thresholdFloorFraction, ...
    l2SelectionFraction, l2Active, sensingThresholdDbm, ...
    averagesRsrp, hasCoherentArrivals, maximumScoreDistanceMeters, ...
    normalizedPrrScore, rangeAt90Meters, outputDirectory, ...
    VariableNames=[ ...
        "Figure", "CaseName", "PacketSizeBytes", ...
        "SubcarrierSpacingKilohertz", "HasIbe", ...
        "ThresholdFloorFraction", "L2SelectionFraction", ...
        "resourceAllocation.Autonomous.L2RankingEnabled", "SensingThresholdDbm", "AveragesRsrp", ...
        "HasCoherentArrivals", ...
        "MaximumScoreDistanceMeters", "NormalizedPrrScore", ...
        "RangeAt90Meters", "OutputDirectory"]);
end

function results = createEmptyResults(rowCount)
arguments (Input)
    rowCount (1, 1) double ...
        {mustBeInteger, mustBeNonnegative}
end

results = table( ...
    Size=[rowCount, 15], ...
    VariableTypes=[ ...
        "double", "string", "double", "double", "double", ...
        "double", "double", "double", "double", "double", ...
        "double", "double", "double", "double", "string"], ...
    VariableNames=[ ...
        "Figure", "CaseName", "PacketSizeBytes", ...
        "SubcarrierSpacingKilohertz", "HasIbe", ...
        "ThresholdFloorFraction", "L2SelectionFraction", ...
        "resourceAllocation.Autonomous.L2RankingEnabled", "SensingThresholdDbm", "AveragesRsrp", ...
        "HasCoherentArrivals", ...
        "MaximumScoreDistanceMeters", "NormalizedPrrScore", ...
        "RangeAt90Meters", "OutputDirectory"]);
end

function [sourceDirectory, configurationDirectory, tomlDirectory] = ...
        resolveSimulatorDirectories(simulatorRoot)
sourceDirectory = fullfile(simulatorRoot, "src");
configurationDirectory = fullfile( ...
    fileparts(mfilename("fullpath")), "config");
tomlDirectory = fullfile(simulatorRoot, "lib", "matlab-toml");
end

function validateSimulatorRoot( ...
        simulatorRoot, sourceDirectory, configurationDirectory)
if ~isfolder(simulatorRoot)
    error( ...
        "v2xsimregression:vittorio2021:MissingSimulatorRoot", ...
        "SimulatorRoot is not a directory: %s", simulatorRoot);
end
if ~isfile(fullfile( ...
        sourceDirectory, "+v2xsim", "runSimulation.m"))
    error( ...
        "v2xsimregression:vittorio2021:MissingSimulator", ...
        "v2xsim.runSimulation was not found under: %s", ...
        simulatorRoot);
end
expectedConfigurations = fullfile( ...
    configurationDirectory, ...
    ["figure7.toml", "figure9.toml", "figure11.toml"]);
if any(~isfile(expectedConfigurations))
    error( ...
        "v2xsimregression:vittorio2021:MissingConfiguration", ...
        "One or more Vittorio 2021 TOML baselines are missing under: %s", ...
        configurationDirectory);
end
if ~isfolder(fullfile(sourceDirectory, "+v2xsim"))
    error( ...
        "v2xsimregression:vittorio2021:MissingRefactoredSource", ...
        "The simulator root requires src/+v2xsim under: %s", ...
        simulatorRoot);
end
end

function prepareOutputDirectory(outputDirectory)
if isfolder(outputDirectory)
    directoryEntries = dir(outputDirectory);
    entryNames = string({directoryEntries.name});
    isContent = ~ismember(entryNames, [".", ".."]);
    if any(isContent)
        error( ...
            "v2xsimregression:vittorio2021:OutputNotEmpty", ...
            "Refusing to append simulator results in nonempty folder: %s", ...
            outputDirectory);
    end
else
    [wasCreated, message] = mkdir(outputDirectory);
    if ~wasCreated
        error( ...
            "v2xsimregression:vittorio2021:OutputCreationFailed", ...
            "Could not create output folder %s: %s", ...
            outputDirectory, message);
    end
end
end

function restoreEnvironment( ...
        originalPath, randomStream, originalRandomState)
path(originalPath);
RandStream.setGlobalStream(randomStream);
randomStream.State = originalRandomState;
end
