classdef Vittorio2021PerformanceTest < matlab.unittest.TestCase
    %VITTORIO2021PERFORMANCETEST Conclusion-level paper regressions.
    %   Reproduces Figures 7, 9, and 11 from Todisco et al. (2021).
    %   Assertions encode the conclusions supported by the curves rather
    %   than requiring the refactored simulator to reproduce every point.

    properties (Constant, Access = private)
        ComparableScoreTolerance = 0.05
        MinimumConclusionMargin = 0.01
    end

    properties (SetAccess = private)
        SimulatorRoot (1, 1) string
        OutputDirectory (1, 1) string
    end

    methods (TestClassSetup)
        function configureCampaign(testCase)
            testCase.SimulatorRoot = getSimulatorRoot();
            temporaryFolder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            testCase.OutputDirectory = string(temporaryFolder.Folder);
        end
    end

    methods (Test)
        function testFigure7ConfigurationPreservesPublishedThreshold( ...
                testCase)
            configurationFile = fullfile( ...
                fileparts(mfilename("fullpath")), ...
                "config","figure7.toml");
            configuration = v2xsim.config.load( ...
                configurationFile).resolve();

            testCase.verifyEqual( ...
                configuration.Data.ResourceAllocation. ...
                    SensingBased.SensingThresholdDbm, ...
                -126);
        end

        function testFigure7SupportsNumerologyAndIbeConclusion(testCase)
            results = ...
                v2xsimregression.paper.vittorio2021.runPublishedCampaigns( ...
                    testCase.SimulatorRoot, ...
                    fullfile(testCase.OutputDirectory, "figure-7"), ...
                    Figures=7);

            scs15WithIbe = selectScore( ...
                results, "SubcarrierSpacingKilohertz", 15, ...
                "HasIbe", true);
            scs30WithIbe = selectScore( ...
                results, "SubcarrierSpacingKilohertz", 30, ...
                "HasIbe", true);
            scs15WithoutIbe = selectScore( ...
                results, "SubcarrierSpacingKilohertz", 15, ...
                "HasIbe", false);
            scs30WithoutIbe = selectScore( ...
                results, "SubcarrierSpacingKilohertz", 30, ...
                "HasIbe", false);
            withoutIbeScores = results.NormalizedPrrScore( ...
                results.HasIbe == false);

            testCase.verifyGreaterThan( ...
                scs30WithIbe - scs15WithIbe, ...
                testCase.MinimumConclusionMargin, ...
                "With IBE, 30 kHz must outperform 15 kHz.");
            testCase.verifyGreaterThan( ...
                scs15WithoutIbe - scs15WithIbe, ...
                testCase.MinimumConclusionMargin, ...
                "Removing IBE must improve the 15 kHz result.");
            testCase.verifyGreaterThan( ...
                scs30WithoutIbe - scs30WithIbe, ...
                testCase.MinimumConclusionMargin, ...
                "Removing IBE must improve the 30 kHz result.");
            testCase.verifyLessThanOrEqual( ...
                max(withoutIbeScores) - min(withoutIbeScores), ...
                testCase.ComparableScoreTolerance, ...
                "Without IBE, the SCS curves must remain comparable.");
        end

        function testFigure9SupportsL2AndThresholdConclusion(testCase)
            results = ...
                v2xsimregression.paper.vittorio2021.runPublishedCampaigns( ...
                    testCase.SimulatorRoot, ...
                    fullfile(testCase.OutputDirectory, "figure-9"), ...
                    Figures=9);

            for packetSizeBytes = [350, 1000]
                mode2AtMinus110 = selectScore( ...
                    results, "PacketSizeBytes", packetSizeBytes, ...
                    "resourceAllocation.Autonomous.L2RankingEnabled", false, ...
                    "SensingThresholdDbm", -110);
                mode2AtMinus126 = selectScore( ...
                    results, "PacketSizeBytes", packetSizeBytes, ...
                    "resourceAllocation.Autonomous.L2RankingEnabled", false, ...
                    "SensingThresholdDbm", -126);
                m50AtMinus110 = selectScore( ...
                    results, "PacketSizeBytes", packetSizeBytes, ...
                    "resourceAllocation.Autonomous.L2RankingEnabled", true, ...
                    "L2SelectionFraction", 0.5, ...
                    "SensingThresholdDbm", -110);
                m20AtMinus110 = selectScore( ...
                    results, "PacketSizeBytes", packetSizeBytes, ...
                    "resourceAllocation.Autonomous.L2RankingEnabled", true, ...
                    "L2SelectionFraction", 0.2, ...
                    "SensingThresholdDbm", -110);
                lowThresholdScores = results.NormalizedPrrScore( ...
                    results.PacketSizeBytes == packetSizeBytes & ...
                    results.SensingThresholdDbm == -126);

                testCase.verifyGreaterThan( ...
                    m20AtMinus110 - mode2AtMinus110, ...
                    testCase.MinimumConclusionMargin, ...
                    "At -110 dBm, M=20% must outperform Mode 2.");
                testCase.verifyGreaterThan( ...
                    m20AtMinus110 - m50AtMinus110, ...
                    testCase.MinimumConclusionMargin, ...
                    "At -110 dBm, M=20% must outperform M=50%.");
                testCase.verifyGreaterThan( ...
                    mode2AtMinus126 - mode2AtMinus110, ...
                    testCase.MinimumConclusionMargin, ...
                    "Mode 2 must benefit from the lower RSRP threshold.");
                testCase.verifyLessThanOrEqual( ...
                    max(lowThresholdScores) - min(lowThresholdScores), ...
                    testCase.ComparableScoreTolerance, ...
                    "At -126 dBm, the L2 settings must remain comparable.");
            end
        end

        function testFigure11SupportsJointMechanismConclusion(testCase)
            results = ...
                v2xsimregression.paper.vittorio2021.runPublishedCampaigns( ...
                    testCase.SimulatorRoot, ...
                    fullfile(testCase.OutputDirectory, "figure-11"), ...
                    Figures=11);

            legacyMode2 = selectScore( ...
                results, "resourceAllocation.Autonomous.L2RankingEnabled", false, ...
                "AveragesRsrp", false, ...
                "HasCoherentArrivals", false);
            l2Only = selectScore( ...
                results, "resourceAllocation.Autonomous.L2RankingEnabled", true, ...
                "L2SelectionFraction", 0.2, ...
                "AveragesRsrp", false, ...
                "HasCoherentArrivals", false);
            averagingOnly = selectScore( ...
                results, "resourceAllocation.Autonomous.L2RankingEnabled", false, ...
                "AveragesRsrp", true, ...
                "HasCoherentArrivals", false);
            bothMechanisms = selectScore( ...
                results, "resourceAllocation.Autonomous.L2RankingEnabled", true, ...
                "L2SelectionFraction", 0.2, ...
                "AveragesRsrp", true, ...
                "HasCoherentArrivals", false);
            coherentMode2 = selectScore( ...
                results, "resourceAllocation.Autonomous.L2RankingEnabled", false, ...
                "AveragesRsrp", false, ...
                "HasCoherentArrivals", true);

            bestSingleMechanism = max( ...
                [legacyMode2, l2Only, averagingOnly]);
            testCase.verifyGreaterThan( ...
                bothMechanisms - bestSingleMechanism, ...
                testCase.MinimumConclusionMargin, ...
                ["Only restoring both L2 selection and RSRP averaging ", ...
                "must provide the relevant improvement."]);
            testCase.verifyGreaterThan( ...
                coherentMode2 - legacyMode2, ...
                testCase.MinimumConclusionMargin, ...
                "Coherent arrivals must outperform incoherent Mode 2.");
            testCase.verifyLessThanOrEqual( ...
                abs(bothMechanisms - coherentMode2), ...
                testCase.ComparableScoreTolerance, ...
                ["Restoring both mechanisms under incoherent arrivals ", ...
                "must approximate coherent Mode 2."]);
        end
    end
end

function simulatorRoot = getSimulatorRoot()
simulatorRoot = string(getenv("V2XSIM_PAPER_SIMULATOR_ROOT"));

if simulatorRoot == ""
    simulatorRoot = string(fileparts(fileparts(fileparts(fileparts( ...
    fileparts(mfilename("fullpath")))))));
end
end

function score = selectScore(results, selectors)
arguments (Input)
    results table
end
arguments (Repeating)
    selectors
end

isSelected = true(height(results), 1);
for selectorIndex = 1:2:numel(selectors)
    variableName = string(selectors{selectorIndex});
    expectedValue = selectors{selectorIndex + 1};
    isSelected = isSelected & ...
        results.(variableName) == expectedValue;
end

selectedScores = results.NormalizedPrrScore(isSelected);
if numel(selectedScores) ~= 1
    error( ...
        "v2xsimregression:vittorio2021:NonuniqueSelection", ...
        "Expected one campaign row but selected %d.", ...
        numel(selectedScores));
end
score = selectedScores;
end
