function results = addExposureMatchingDiagnostics(results)
%ADDEXPOSUREMATCHINGDIAGNOSTICS Check route-matched active cohorts.

arguments (Input)
    results table
end
arguments (Output)
    results table
end

requiredNames = [ ...
    "RandomSeed", "NormalizedMagnitude", "Treatment", ...
    "SelectedVehicleCohortKey", "ActivePositionSampleCount", ...
    "StatusEffectEpisodeCount"];
actualNames = string(results.Properties.VariableNames);
if any(~ismember(requiredNames, actualNames))
    error( ...
        "v2xsimregression:positionerror:" + ...
        "InvalidExposureMatchingResults", ...
        "Exposure matching requires %s.", ...
        strjoin(requiredNames, ", "));
end

rowCount = height(results);
cohortMatch = false(rowCount, 1);
activeSampleCountDifference = nan(rowCount, 1);
episodeCountDifference = nan(rowCount, 1);
referenceTreatment = strings(rowCount, 1);
status = repmat("Unmatched", rowCount, 1);
for row = 1:rowCount
    treatment = string(results.Treatment(row));
    if treatment == "None"
        cohortMatch(row) = true;
        activeSampleCountDifference(row) = 0;
        episodeCountDifference(row) = 0;
        referenceTreatment(row) = "None";
        status(row) = "NoErrorBaseline";
        continue
    end
    referenceTreatment(row) = pairedTreatment(treatment);
    reference = ...
        double(results.RandomSeed) == ...
            double(results.RandomSeed(row)) & ...
        double(results.NormalizedMagnitude) == ...
            double(results.NormalizedMagnitude(row)) & ...
        string(results.Treatment) == referenceTreatment(row);
    if nnz(reference) ~= 1
        error( ...
            "v2xsimregression:positionerror:" + ...
            "UnbalancedExposureMatchingResults", ...
            "Treatment %s at seed %g and magnitude %g requires " + ...
            "exactly one %s partner.", ...
            treatment, double(results.RandomSeed(row)), ...
            double(results.NormalizedMagnitude(row)), ...
            referenceTreatment(row));
    end
    cohortMatch(row) = ...
        string(results.SelectedVehicleCohortKey(row)) == ...
        string(results.SelectedVehicleCohortKey(reference));
    activeSampleCountDifference(row) = ...
        double(results.ActivePositionSampleCount(row)) - ...
        double(results.ActivePositionSampleCount(reference));
    episodeCountDifference(row) = ...
        double(results.StatusEffectEpisodeCount(row)) - ...
        double(results.StatusEffectEpisodeCount(reference));
    if cohortMatch(row) && ...
            activeSampleCountDifference(row) == 0 && ...
            episodeCountDifference(row) == 0
        status(row) = "Matched";
    else
        status(row) = "Mismatch";
    end
end

results.ExposureReferenceTreatment = referenceTreatment;
results.ExposureCohortMatch = cohortMatch;
results.ExposureActiveSampleCountDifference = ...
    activeSampleCountDifference;
results.ExposureEpisodeCountDifference = episodeCountDifference;
results.ExposureMatchingStatus = status;
end

function reference = pairedTreatment(treatment)
switch treatment
    case "GaussianMainline"
        reference = "FalseExit";
    case "FalseExit"
        reference = "GaussianMainline";
    case "GaussianRamp"
        reference = "FalseMerge";
    case "FalseMerge"
        reference = "GaussianRamp";
    otherwise
        error( ...
            "v2xsimregression:positionerror:" + ...
            "UnknownExposureMatchingTreatment", ...
            "Unknown exposure-matching treatment %s.", treatment);
end
end
