function analysis = analyzeMechanismEffectResults(effectRows, options)
%ANALYZEMECHANISMEFFECTRESULTS Analyze each outcome and estimand safely.
%   Finite, complete outcome/estimand factorials are passed to
%   analyzeEffectDominance. Incomplete responses and scientifically
%   degenerate models receive an explicit NotAnalyzable status so a
%   secondary mechanism outcome cannot abort the primary campaign.

arguments (Input)
    effectRows table
    options.RunEffectAnalysis (1, 1) logical = true
    options.BootstrapSampleCount (1, 1) double ...
        {mustBeInteger, mustBePositive} = 10000
    options.RandomSeed (1, 1) double ...
        {mustBeInteger, mustBeNonnegative} = 94721
    options.MagnitudeModel (1, 1) string {mustBeMember( ...
        options.MagnitudeModel, ...
        ["categorical", "continuous"])} = "categorical"
    options.MagnitudeVariable (1, 1) string ...
        {mustBeNonzeroLengthText} = "NormalizedMagnitude"
end

arguments (Output)
    analysis (1, 1) struct
end

requiredVariables = [ ...
    "OutcomeName", "ResponseDomain", "Estimand", ...
    "RandomSeed", "ErrorModel", "NormalizedMagnitude", ...
    options.MagnitudeVariable, ...
    "ResponseValue", "DeltaResponseValue"];
missingVariables = setdiff( ...
    requiredVariables, ...
    string(effectRows.Properties.VariableNames), "stable");
if ~isempty(missingVariables)
    error( ...
        "v2xsimregression:positionerror:" + ...
        "InvalidMechanismEffectRows", ...
        "Mechanism effect rows are missing variables: %s.", ...
        join(missingVariables, ", "));
end

outcomeNames = unique(string(effectRows.OutcomeName), "stable");
outcomeTemplate = struct( ...
    "OutcomeName", "", ...
    "ResponseDomain", "", ...
    "Status", "", ...
    "Estimands", struct.empty(0, 1));
outcomes = repmat(outcomeTemplate, numel(outcomeNames), 1);

for outcomeIndex = 1:numel(outcomeNames)
    outcomeName = outcomeNames(outcomeIndex);
    outcomeRows = effectRows.OutcomeName == outcomeName;
    domains = unique( ...
        string(effectRows.ResponseDomain(outcomeRows)), "stable");
    if numel(domains) ~= 1 || ...
            ~ismember(domains, ["auc", "finite"])
        error( ...
            "v2xsimregression:positionerror:" + ...
            "InvalidMechanismResponseDomain", ...
            "Outcome %s must have one response domain.", ...
            outcomeName);
    end

    estimandNames = unique( ...
        string(effectRows.Estimand(outcomeRows)), "stable");
    estimandTemplate = struct( ...
        "Estimand", "", ...
        "Status", "", ...
        "Reason", "", ...
        "NonfiniteRowCount", 0, ...
        "Analysis", struct);
    estimands = repmat( ...
        estimandTemplate, numel(estimandNames), 1);
    for estimandIndex = 1:numel(estimandNames)
        estimandName = estimandNames(estimandIndex);
        selected = outcomeRows & ...
            effectRows.Estimand == estimandName;
        selectedRows = effectRows(selected, :);
        nonfinite = ...
            ~isfinite(selectedRows.ResponseValue) | ...
            ~isfinite(selectedRows.DeltaResponseValue);

        estimands(estimandIndex).Estimand = estimandName;
        estimands(estimandIndex).NonfiniteRowCount = nnz(nonfinite);
        if ~options.RunEffectAnalysis
            estimands(estimandIndex).Status = "NotRequested";
            estimands(estimandIndex).Reason = ...
                "EffectAnalysisDisabled";
        elseif any(nonfinite)
            estimands(estimandIndex).Status = "NotAnalyzable";
            estimands(estimandIndex).Reason = ...
                "NonfiniteResponse";
        elseif domains == "auc" && ...
                (any(selectedRows.ResponseValue < 0 | ...
                    selectedRows.ResponseValue > 1) || ...
                any(selectedRows.DeltaResponseValue < -1 | ...
                    selectedRows.DeltaResponseValue > 1))
            estimands(estimandIndex).Status = "NotAnalyzable";
            estimands(estimandIndex).Reason = ...
                "ResponseOutsideAucRange";
        else
            try
                fitted = v2xsimregression.positionerror. ...
                    analyzeEffectDominance( ...
                        selectedRows, ...
                        BootstrapSampleCount= ...
                            options.BootstrapSampleCount, ...
                        RandomSeed=options.RandomSeed, ...
                        ResponseVariable="ResponseValue", ...
                        DeltaResponseVariable= ...
                            "DeltaResponseValue", ...
                        ResponseDomain=domains, ...
                        MagnitudeModel=options.MagnitudeModel, ...
                        MagnitudeVariable= ...
                            options.MagnitudeVariable);
                estimands(estimandIndex).Status = "Analyzed";
                estimands(estimandIndex).Analysis = fitted;
            catch exception
                if isNotAnalyzableError(exception.identifier)
                    estimands(estimandIndex).Status = ...
                        "NotAnalyzable";
                    estimands(estimandIndex).Reason = ...
                        string(exception.identifier);
                else
                    rethrow(exception);
                end
            end
        end
    end

    statuses = string({estimands.Status});
    if all(statuses == "Analyzed")
        outcomeStatus = "Analyzed";
    elseif all(statuses == "NotRequested")
        outcomeStatus = "NotRequested";
    elseif any(statuses == "Analyzed")
        outcomeStatus = "PartiallyAnalyzed";
    else
        outcomeStatus = "NotAnalyzable";
    end
    outcomes(outcomeIndex).OutcomeName = outcomeName;
    outcomes(outcomeIndex).ResponseDomain = domains;
    outcomes(outcomeIndex).Status = outcomeStatus;
    outcomes(outcomeIndex).Estimands = estimands;
end

analysis = struct( ...
    "MagnitudeModel", options.MagnitudeModel, ...
    "MagnitudeVariable", options.MagnitudeVariable, ...
    "OutcomeCount", numel(outcomes), ...
    "Outcomes", outcomes);
end

function tf = isNotAnalyzableError(identifier)
tf = ismember(string(identifier), [ ...
    "v2xsimregression:positionerror:DegenerateEffectModel", ...
    "v2xsimregression:positionerror:RankDeficientEffectModel", ...
    "v2xsimregression:positionerror:" + ...
        "DegeneratePredictiveReferenceLoss", ...
    "v2xsimregression:positionerror:" + ...
        "RankDeficientPredictiveEffectModel", ...
    "v2xsimregression:positionerror:InsufficientFactorLevels"]);
end
