function analysis = analyzeEffectDominance(seedResults, options)
%ANALYZEEFFECTDOMINANCE Compare error-structure and magnitude effects.
%   ANALYSIS = ANALYZEEFFECTDOMINANCE(SEEDRESULTS) uses an explicit paired
%   delta response when present. Otherwise, it subtracts the paired
%   no-error response from every treatment response. By default the
%   response is DeliveryPrrAuc and is validated as an AUC. Other finite
%   scalar responses can be selected with ResponseVariable and
%   ResponseDomain="finite".
%
%       delta response ~ seed + error model * magnitude factor
%
%   and reports drop-term partial R-squared values for error structure
%   (model plus interaction terms) and magnitude (categorical magnitude
%   plus interaction terms). MagnitudeModel="continuous" provides a
%   predeclared linear sensitivity analysis. MagnitudeVariable can select
%   a realized-magnitude column for that continuous sensitivity while the
%   assigned NormalizedMagnitude remains the balancing key. Confidence
%   limits for the difference resample complete seed blocks, preserving
%   every treatment within a seed.
%
%   A separate predictive sensitivity centers the treatment deltas within
%   each seed and evaluates four models by leave-one-seed-out mean squared
%   error: intercept-only (N), error structure (S), magnitude (M), and
%   structure-by-magnitude (SM). Two-factor Shapley loss reductions allocate
%   the interaction once. This complements, but does not replace, the
%   overlapping nonadditive drop-block partial R-squared statistics.

arguments (Input)
    seedResults table
    options.BootstrapSampleCount (1, 1) double ...
        {mustBeInteger, mustBePositive} = 10000
    options.RandomSeed (1, 1) double ...
        {mustBeInteger, mustBeNonnegative} = 94721
    options.ResponseVariable (1, 1) string ...
        {mustBeNonzeroLengthText} = "DeliveryPrrAuc"
    options.DeltaResponseVariable (1, 1) string = ""
    options.ResponseDomain (1, 1) string {mustBeMember( ...
        options.ResponseDomain, ["auto", "auc", "finite"])} = "auto"
    options.MagnitudeModel (1, 1) string {mustBeMember( ...
        options.MagnitudeModel, ...
        ["categorical", "continuous"])} = "categorical"
    options.MagnitudeVariable (1, 1) string ...
        {mustBeNonzeroLengthText} = "NormalizedMagnitude"
end

arguments (Output)
    analysis (1, 1) struct
end

if options.BootstrapSampleCount < 40
    error( ...
        "v2xsimregression:positionerror:InsufficientBootstrapSamples", ...
        "BootstrapSampleCount must be at least 40.");
end

responseVariable = options.ResponseVariable;
deltaResponseVariable = options.DeltaResponseVariable;
if strlength(deltaResponseVariable) == 0
    deltaResponseVariable = "Delta" + responseVariable;
end
responseDomain = resolveResponseDomain( ...
    options.ResponseDomain, responseVariable);
magnitudeVariable = options.MagnitudeVariable;
if magnitudeVariable ~= "NormalizedMagnitude" && ...
        options.MagnitudeModel ~= "continuous"
    error( ...
        "v2xsimregression:positionerror:" + ...
        "RealizedMagnitudeRequiresContinuousModel", ...
        "A non-assigned MagnitudeVariable requires " + ...
        "MagnitudeModel=""continuous"".");
end

requiredVariables = [ ...
    "RandomSeed", "ErrorModel", ...
    "NormalizedMagnitude", magnitudeVariable, responseVariable];
missingVariables = setdiff( ...
    requiredVariables, string(seedResults.Properties.VariableNames), ...
    "stable");
if ~isempty(missingVariables)
    error( ...
        "v2xsimregression:positionerror:InvalidSeedResults", ...
        "Seed results are missing required variables: %s.", ...
        join(missingVariables, ", "));
end

randomSeeds = double(seedResults.RandomSeed);
errorModels = string(seedResults.ErrorModel);
assignedMagnitude = double(seedResults.NormalizedMagnitude);
magnitudeData = seedResults.(magnitudeVariable);
if ~isnumeric(magnitudeData) || ~isreal(magnitudeData) || ...
        ~iscolumn(magnitudeData)
    error( ...
        "v2xsimregression:positionerror:InvalidSeedResults", ...
        "The selected magnitude variable must be a real numeric column.");
end
modelMagnitude = double(magnitudeData);
responseData = seedResults.(responseVariable);
if ~isnumeric(responseData) || ~isreal(responseData) || ...
        ~iscolumn(responseData)
    error( ...
        "v2xsimregression:positionerror:InvalidSeedResults", ...
        "The selected response must be a real numeric column.");
end
responseValues = double(responseData);
hasExplicitDelta = ismember( ...
    deltaResponseVariable, ...
    string(seedResults.Properties.VariableNames));
if hasExplicitDelta
    explicitDelta = seedResults.(deltaResponseVariable);
    if ~isnumeric(explicitDelta) || ~isreal(explicitDelta) || ...
            ~iscolumn(explicitDelta) || ...
            any(~isfinite(explicitDelta))
        error( ...
            invalidDeltaIdentifier(responseDomain), ...
            "Explicit paired deltas must be a finite numeric column.");
    end
    if responseDomain == "auc" && ...
            any(explicitDelta < -1 | explicitDelta > 1)
        error( ...
            invalidDeltaIdentifier(responseDomain), ...
            "Explicit paired AUC deltas must be in [-1, 1].");
    end
    explicitDelta = double(explicitDelta);
else
    explicitDelta = zeros(0, 1);
end
if any(~isfinite(randomSeeds)) || ...
        any(randomSeeds ~= fix(randomSeeds)) || ...
        any(~isfinite(assignedMagnitude)) || ...
        any(assignedMagnitude < 0) || ...
        any(~isfinite(modelMagnitude)) || ...
        any(modelMagnitude < 0) || ...
        any(~isfinite(responseValues)) || ...
        any(ismissing(errorModels) | strlength(errorModels) == 0)
    error( ...
        "v2xsimregression:positionerror:InvalidSeedResults", ...
        "Seed, model, magnitude, and response values must be valid.");
end
if responseDomain == "auc" && ...
        any(responseValues < 0 | responseValues > 1)
    error( ...
        "v2xsimregression:positionerror:InvalidSeedResults", ...
        "AUC response values must be in [0, 1].");
end

baselineMask = strcmpi(errorModels, "None");
treatmentMask = ~baselineMask;
if ~any(baselineMask) || ~any(treatmentMask)
    error( ...
        "v2xsimregression:positionerror:MissingTreatmentArm", ...
        "Results must include no-error and nonzero-error treatment rows.");
end
if any(assignedMagnitude(baselineMask) ~= 0) || ...
        any(modelMagnitude(baselineMask) ~= 0)
    error( ...
        "v2xsimregression:positionerror:InvalidBaselineMagnitude", ...
        "Every no-error baseline must have zero normalized magnitude.");
end
if hasExplicitDelta && any(explicitDelta(baselineMask) ~= 0)
    error( ...
        invalidDeltaIdentifier(responseDomain), ...
        "Every no-error baseline must have zero paired delta.");
end
if any(assignedMagnitude(treatmentMask) <= 0) || ...
        any(modelMagnitude(treatmentMask) <= 0)
    error( ...
        "v2xsimregression:positionerror:InvalidTreatmentMagnitude", ...
        "Every error treatment must have positive normalized magnitude.");
end

seedIds = unique(randomSeeds, "stable");
modelNames = unique(errorModels(treatmentMask), "stable");
% The assigned factor identifies the balanced treatment cells even when
% the continuous sensitivity uses a slightly different realized value in
% every seed/model arm.
magnitudes = unique(assignedMagnitude(treatmentMask), "stable");
if numel(seedIds) < 2 || numel(modelNames) < 2 || numel(magnitudes) < 2
    error( ...
        "v2xsimregression:positionerror:InsufficientFactorLevels", ...
        "At least two seeds, error models, and magnitudes are required.");
end

treatments = pairedTreatmentRows( ...
    randomSeeds, errorModels, assignedMagnitude, modelMagnitude, ...
    responseValues, explicitDelta, ...
    seedIds, modelNames, magnitudes);
predictiveSensitivity = predictiveLossSensitivity( ...
    treatments, modelNames, options.MagnitudeModel);
pointEstimate = fitDominanceModel( ...
    treatments.SeedBlock, treatments.ErrorModel, ...
    treatments.ModelMagnitude, treatments.DeltaResponseValue, ...
    modelNames, options.MagnitudeModel);

stream = RandStream("mt19937ar", Seed=options.RandomSeed);
bootstrapDifferences = zeros(options.BootstrapSampleCount, 1);
bootstrapPredictiveDifferences = zeros( ...
    options.BootstrapSampleCount, 1);
seedCount = numel(seedIds);
for sampleIndex = 1:options.BootstrapSampleCount
    sampledSeedRows = randi(stream, seedCount, seedCount, 1);
    sampled = resampleSeedBlocks(treatments, sampledSeedRows);
    bootstrapFit = fitDominanceModel( ...
        sampled.SeedBlock, sampled.ErrorModel, ...
        sampled.ModelMagnitude, ...
        sampled.DeltaResponseValue, modelNames, ...
        options.MagnitudeModel);
    bootstrapDifferences(sampleIndex) = ...
        bootstrapFit.PartialR2Difference;
    bootstrapPredictive = summarizePredictiveLosses( ...
        predictiveSensitivity.PerSeedLosses( ...
            sampledSeedRows, :));
    bootstrapPredictiveDifferences(sampleIndex) = ...
        bootstrapPredictive.NormalizedContributionDifference;
end

confidenceInterval = percentile95(bootstrapDifferences);
predictiveConfidenceInterval = percentile95( ...
    bootstrapPredictiveDifferences);

analysis = pointEstimate;
analysis.SeedCount = seedCount;
analysis.ObservationCount = height(treatments);
analysis.ErrorModels = modelNames.';
analysis.NormalizedMagnitudes = magnitudes.';
analysis.BootstrapSampleCount = options.BootstrapSampleCount;
analysis.ResponseVariable = responseVariable;
analysis.ResponseDomain = responseDomain;
analysis.MagnitudeModel = options.MagnitudeModel;
analysis.MagnitudeVariable = magnitudeVariable;
analysis.FittedMagnitudeMinimum = min(treatments.ModelMagnitude);
analysis.FittedMagnitudeMaximum = max(treatments.ModelMagnitude);
if hasExplicitDelta
    if responseVariable == "DeliveryPrrAuc" && ...
            deltaResponseVariable == "DeltaDeliveryPrrAuc"
        analysis.DeltaResponseSource = ...
            "ExplicitDeltaDeliveryPrrAuc";
    else
        analysis.DeltaResponseSource = ...
            "Explicit:" + deltaResponseVariable;
    end
else
    if responseVariable == "DeliveryPrrAuc"
        analysis.DeltaResponseSource = ...
            "PairedRawDeliveryPrrAuc";
    else
        analysis.DeltaResponseSource = ...
            "PairedRaw:" + responseVariable;
    end
end
analysis.PartialR2DifferenceLower95 = confidenceInterval(1);
analysis.PartialR2DifferenceUpper95 = confidenceInterval(2);
analysis.PartialR2StatisticType = ...
    "OverlappingNonadditiveDropBlock";
analysis.PartialR2InteractionTreatment = ...
    "CreditedToBothDroppedFactorBlocks";
analysis.PartialR2ContributionsAreAdditive = false;
analysis.ErrorStructureDominates = confidenceInterval(1) > 0;
analysis.MagnitudeDominates = confidenceInterval(2) < 0;
analysis.Conclusion = dominanceConclusion(analysis);
analysis.PredictiveLossN = predictiveSensitivity.LossN;
analysis.PredictiveLossS = predictiveSensitivity.LossS;
analysis.PredictiveLossM = predictiveSensitivity.LossM;
analysis.PredictiveLossSM = predictiveSensitivity.LossSM;
analysis.PredictiveContributionErrorStructure = ...
    predictiveSensitivity.ContributionErrorStructure;
analysis.PredictiveContributionMagnitude = ...
    predictiveSensitivity.ContributionMagnitude;
analysis.PredictiveContributionDifference = ...
    predictiveSensitivity.ContributionDifference;
analysis.PredictiveNormalizedContributionErrorStructure = ...
    predictiveSensitivity.NormalizedContributionErrorStructure;
analysis.PredictiveNormalizedContributionMagnitude = ...
    predictiveSensitivity.NormalizedContributionMagnitude;
analysis.PredictiveNormalizedContributionDifference = ...
    predictiveSensitivity.NormalizedContributionDifference;
analysis.PredictiveNormalizedContributionDifferenceLower95 = ...
    predictiveConfidenceInterval(1);
analysis.PredictiveNormalizedContributionDifferenceUpper95 = ...
    predictiveConfidenceInterval(2);
analysis.PredictiveErrorStructureDominates = ...
    predictiveConfidenceInterval(1) > 0;
analysis.PredictiveMagnitudeDominates = ...
    predictiveConfidenceInterval(2) < 0;
analysis.PredictiveSensitivityConclusion = ...
    predictiveDominanceConclusion(analysis);
analysis.PredictiveLossMethod = ...
    "LeaveOneSeedOutCenteredTreatmentDeltaMse";
analysis.PredictiveContributionMethod = ...
    "TwoFactorShapleyLossReduction";
analysis.PredictiveInteractionTreatment = ...
    "AllocatedOnceByAveragingFactorOrder";
analysis.PredictiveLossColumns = ["N", "S", "M", "SM"];
analysis.PredictiveHeldOutSeedIds = seedIds.';
analysis.PredictivePerSeedLosses = ...
    predictiveSensitivity.PerSeedLosses;
end

function treatments = pairedTreatmentRows( ...
        randomSeeds, errorModels, assignedMagnitude, modelMagnitude, ...
        responseValues, explicitDelta, ...
        seedIds, modelNames, magnitudes)
hasExplicitDelta = ~isempty(explicitDelta);
baselineResponse = zeros(numel(seedIds), 1);
for seedIndex = 1:numel(seedIds)
    selectedBaseline = ...
        randomSeeds == seedIds(seedIndex) & strcmpi(errorModels, "None");
    if nnz(selectedBaseline) ~= 1
        error( ...
            "v2xsimregression:positionerror:UnpairedBaseline", ...
            "Seed %g must contain exactly one no-error baseline.", ...
            seedIds(seedIndex));
    end
    baselineResponse(seedIndex) = responseValues(selectedBaseline);
end

expectedTreatmentCount = ...
    numel(seedIds) .* numel(modelNames) .* numel(magnitudes);
treatmentSeed = zeros(expectedTreatmentCount, 1);
treatmentModel = strings(expectedTreatmentCount, 1);
treatmentMagnitude = zeros(expectedTreatmentCount, 1);
fittedMagnitude = zeros(expectedTreatmentCount, 1);
treatmentResponse = zeros(expectedTreatmentCount, 1);
treatmentBaselineResponse = zeros(expectedTreatmentCount, 1);
deltaResponseValue = zeros(expectedTreatmentCount, 1);
nextRow = 0;
for seedIndex = 1:numel(seedIds)
    for modelIndex = 1:numel(modelNames)
        for magnitudeIndex = 1:numel(magnitudes)
            selected = ...
                randomSeeds == seedIds(seedIndex) & ...
                errorModels == modelNames(modelIndex) & ...
                assignedMagnitude == magnitudes(magnitudeIndex);
            if nnz(selected) ~= 1
                error( ...
                    "v2xsimregression:positionerror:UnbalancedManifest", ...
                    "Every seed/model/magnitude tuple must occur once.");
            end
            nextRow = nextRow + 1;
            treatmentSeed(nextRow) = seedIndex;
            treatmentModel(nextRow) = modelNames(modelIndex);
            treatmentMagnitude(nextRow) = magnitudes(magnitudeIndex);
            fittedMagnitude(nextRow) = modelMagnitude(selected);
            treatmentResponse(nextRow) = responseValues(selected);
            treatmentBaselineResponse(nextRow) = ...
                baselineResponse(seedIndex);
            if hasExplicitDelta
                deltaResponseValue(nextRow) = ...
                    explicitDelta(selected);
            else
                deltaResponseValue(nextRow) = ...
                    treatmentResponse(nextRow) - ...
                    treatmentBaselineResponse(nextRow);
            end
        end
    end
end

treatments = table( ...
    treatmentSeed, treatmentModel, treatmentMagnitude, ...
    fittedMagnitude, ...
    treatmentResponse, treatmentBaselineResponse, ...
    deltaResponseValue, ...
    VariableNames=[ ...
        "SeedBlock", "ErrorModel", "NormalizedMagnitude", ...
        "ModelMagnitude", ...
        "ResponseValue", "BaselineResponseValue", ...
        "DeltaResponseValue"]);
end

function sensitivity = predictiveLossSensitivity( ...
        treatments, modelNames, magnitudeModel)
seedBlocks = unique(treatments.SeedBlock, "stable");
seedCount = numel(seedBlocks);
centeredResponse = treatments.DeltaResponseValue;
for seedIndex = 1:seedCount
    seedRows = treatments.SeedBlock == seedBlocks(seedIndex);
    centeredResponse(seedRows) = ...
        centeredResponse(seedRows) - ...
        mean(centeredResponse(seedRows));
end

designs = predictiveDesigns( ...
    treatments.ErrorModel, treatments.ModelMagnitude, ...
    modelNames, magnitudeModel);
modelLabels = ["N", "S", "M", "SM"];
perSeedLosses = zeros(seedCount, numel(modelLabels));
for seedIndex = 1:seedCount
    heldRows = treatments.SeedBlock == seedBlocks(seedIndex);
    trainingRows = ~heldRows;
    for modelIndex = 1:numel(modelLabels)
        design = designs{modelIndex};
        trainingDesign = design(trainingRows, :);
        if rank(trainingDesign) ~= size(trainingDesign, 2)
            error( ...
                "v2xsimregression:positionerror:" + ...
                "RankDeficientPredictiveEffectModel", ...
                "Predictive model %s is rank deficient while " + ...
                "holding out seed block %g.", ...
                modelLabels(modelIndex), seedBlocks(seedIndex));
        end
        coefficients = ...
            trainingDesign \ centeredResponse(trainingRows);
        prediction = design(heldRows, :) * coefficients;
        residual = centeredResponse(heldRows) - prediction;
        perSeedLosses(seedIndex, modelIndex) = ...
            mean(residual .^ 2);
    end
end

responseScale = max(1, max(abs(centeredResponse)));
referenceTolerance = ...
    100 .* eps(responseScale) .^ 2;
if any(perSeedLosses(:, 1) <= referenceTolerance)
    error( ...
        "v2xsimregression:positionerror:" + ...
        "DegeneratePredictiveReferenceLoss", ...
        "Every held-out seed requires positive centered " + ...
        "intercept-only predictive loss.");
end
sensitivity = summarizePredictiveLosses(perSeedLosses);
sensitivity.PerSeedLosses = perSeedLosses;
end

function designs = predictiveDesigns( ...
        errorModel, modelMagnitude, modelNames, magnitudeModel)
observationCount = numel(errorModel);
intercept = ones(observationCount, 1);
modelTerms = indicatorTerms(errorModel, modelNames);
if magnitudeModel == "categorical"
    magnitudeTerms = indicatorTerms( ...
        modelMagnitude, unique(modelMagnitude, "stable"));
    interactionTerms = factorialInteractions( ...
        modelTerms, magnitudeTerms);
else
    magnitudeTerms = modelMagnitude;
    interactionTerms = modelTerms .* modelMagnitude;
end
designs = { ...
    intercept, ...
    [intercept, modelTerms], ...
    [intercept, magnitudeTerms], ...
    [ ...
        intercept, modelTerms, ...
        magnitudeTerms, interactionTerms]};
end

function summary = summarizePredictiveLosses(perSeedLosses)
if ~isnumeric(perSeedLosses) || ...
        size(perSeedLosses, 2) ~= 4 || ...
        any(~isfinite(perSeedLosses), "all") || ...
        any(perSeedLosses < 0, "all")
    error( ...
        "v2xsimregression:positionerror:InvalidPredictiveLoss", ...
        "Predictive losses must be a finite nonnegative N/S/M/SM " + ...
        "matrix.");
end
meanLoss = mean(perSeedLosses, 1);
lossN = meanLoss(1);
if lossN <= 0
    error( ...
        "v2xsimregression:positionerror:" + ...
        "DegeneratePredictiveReferenceLoss", ...
        "Normalized predictive contributions require positive " + ...
        "intercept-only loss.");
end
lossS = meanLoss(2);
lossM = meanLoss(3);
lossSM = meanLoss(4);
structureContribution = 0.5 .* ( ...
    (lossN - lossS) + (lossM - lossSM));
magnitudeContribution = 0.5 .* ( ...
    (lossN - lossM) + (lossS - lossSM));
contributionDifference = ...
    structureContribution - magnitudeContribution;
summary = struct( ...
    "LossN", lossN, ...
    "LossS", lossS, ...
    "LossM", lossM, ...
    "LossSM", lossSM, ...
    "ContributionErrorStructure", structureContribution, ...
    "ContributionMagnitude", magnitudeContribution, ...
    "ContributionDifference", contributionDifference, ...
    "NormalizedContributionErrorStructure", ...
        structureContribution ./ lossN, ...
    "NormalizedContributionMagnitude", ...
        magnitudeContribution ./ lossN, ...
    "NormalizedContributionDifference", ...
        contributionDifference ./ lossN);
end

function fit = fitDominanceModel( ...
        seedBlock, errorModel, normalizedMagnitude, response, ...
        modelNames, magnitudeModel)
observationCount = numel(response);
intercept = ones(observationCount, 1);
seedTerms = indicatorTerms(seedBlock, unique(seedBlock, "stable"));
modelTerms = indicatorTerms(errorModel, modelNames);
if magnitudeModel == "categorical"
    magnitudeTerms = indicatorTerms( ...
        normalizedMagnitude, ...
        unique(normalizedMagnitude, "stable"));
    interactionTerms = factorialInteractions( ...
        modelTerms, magnitudeTerms);
else
    magnitudeTerms = normalizedMagnitude;
    interactionTerms = modelTerms .* normalizedMagnitude;
end

fullDesign = [ ...
    intercept, seedTerms, modelTerms, ...
    magnitudeTerms, interactionTerms];
withoutStructure = [ ...
    intercept, seedTerms, magnitudeTerms];
withoutMagnitude = [ ...
    intercept, seedTerms, modelTerms];

fullSse = residualSumOfSquares(fullDesign, response, "full");
withoutStructureSse = residualSumOfSquares( ...
    withoutStructure, response, "without-structure");
withoutMagnitudeSse = residualSumOfSquares( ...
    withoutMagnitude, response, "without-magnitude");
if withoutStructureSse <= eps || withoutMagnitudeSse <= eps
    error( ...
        "v2xsimregression:positionerror:DegenerateEffectModel", ...
        "Partial R-squared is undefined for a zero-residual reduced model.");
end

partialStructure = max( ...
    0, withoutStructureSse - fullSse) ./ withoutStructureSse;
partialMagnitude = max( ...
    0, withoutMagnitudeSse - fullSse) ./ withoutMagnitudeSse;
fit = struct( ...
    "PartialR2ErrorStructure", partialStructure, ...
    "PartialR2Magnitude", partialMagnitude, ...
    "PartialR2Difference", partialStructure - partialMagnitude, ...
    "FullModelResidualSumOfSquares", fullSse);
end

function terms = factorialInteractions(leftTerms, rightTerms)
rowCount = size(leftTerms, 1);
leftCount = size(leftTerms, 2);
rightCount = size(rightTerms, 2);
terms = zeros(rowCount, leftCount .* rightCount);
for rightIndex = 1:rightCount
    columns = (rightIndex - 1) .* leftCount + (1:leftCount);
    terms(:, columns) = ...
        leftTerms .* rightTerms(:, rightIndex);
end
end

function responseDomain = resolveResponseDomain( ...
        configuredDomain, responseVariable)
if configuredDomain ~= "auto"
    responseDomain = configuredDomain;
elseif endsWith(responseVariable, "Auc", IgnoreCase=true)
    responseDomain = "auc";
else
    responseDomain = "finite";
end
end

function identifier = invalidDeltaIdentifier(responseDomain)
if responseDomain == "auc"
    identifier = ...
        "v2xsimregression:positionerror:" + ...
        "InvalidDeltaDeliveryPrrAuc";
else
    identifier = ...
        "v2xsimregression:positionerror:InvalidDeltaResponse";
end
end

function terms = indicatorTerms(values, levels)
levels = reshape(levels, 1, []);
if numel(levels) <= 1
    terms = zeros(numel(values), 0);
    return
end

terms = false(numel(values), numel(levels) - 1);
for levelIndex = 2:numel(levels)
    terms(:, levelIndex - 1) = values == levels(levelIndex);
end
terms = double(terms);
end

function sse = residualSumOfSquares(design, response, modelName)
if rank(design) ~= size(design, 2)
    error( ...
        "v2xsimregression:positionerror:RankDeficientEffectModel", ...
        "The %s effect-model design is rank deficient.", modelName);
end
residual = response - design * (design \ response);
sse = sum(residual .^ 2);
end

function sampled = resampleSeedBlocks(treatments, sampledSeedRows)
rowsPerSeed = height(treatments) ./ numel(unique( ...
    treatments.SeedBlock, "stable"));
sampled = treatments([], :);
for bootstrapSeedIndex = 1:numel(sampledSeedRows)
    sourceRows = treatments.SeedBlock == ...
        sampledSeedRows(bootstrapSeedIndex);
    block = treatments(sourceRows, :);
    if height(block) ~= rowsPerSeed %#ok<BDSCI>
        error( ...
            "v2xsimregression:positionerror:UnbalancedSeedBlock", ...
            "Every seed block must contain the same treatments.");
    end
    block.SeedBlock(:) = bootstrapSeedIndex;
    sampled = [sampled; block]; %#ok<AGROW>
end
end

function interval = percentile95(values)
values = sort(values);
sampleCount = numel(values);
lowerIndex = max(1, ceil(0.025 .* sampleCount));
upperIndex = min(sampleCount, floor(0.975 .* sampleCount));
interval = [values(lowerIndex), values(upperIndex)];
end

function conclusion = dominanceConclusion(analysis)
if analysis.ErrorStructureDominates
    conclusion = "ErrorStructureDominates";
elseif analysis.MagnitudeDominates
    conclusion = "MagnitudeDominates";
else
    conclusion = "Inconclusive";
end
end

function conclusion = predictiveDominanceConclusion(analysis)
if analysis.PredictiveErrorStructureDominates
    conclusion = "ErrorStructureDominates";
elseif analysis.PredictiveMagnitudeDominates
    conclusion = "MagnitudeDominates";
else
    conclusion = "Inconclusive";
end
end
