function effectRows = buildMechanismEffectResults( ...
        seedResults, outcomeVariables, options)
%BUILDMECHANISMEFFECTRESULTS Build long paired scalar-outcome factorials.
%   Each selected outcome produces three estimands:
%
%   * RouteBalanced: equal-route Gaussian, false exit, and false merge.
%   * Mainline: GaussianMainline and false exit.
%   * Ramp: GaussianRamp and false merge.
%
%   The route-balanced Gaussian response and delta are equal-weight means
%   of the GaussianMainline and GaussianRamp values and paired deltas.
%   BaselineVariables can select a different no-error reference column for
%   an outcome whose treatment-only population is undefined at baseline.
%   Numeric NaN values are retained so downstream campaign analysis can
%   mark an outcome NotAnalyzable without aborting primary reduction.

arguments (Input)
    seedResults table
    outcomeVariables (1, :) string {mustBeNonzeroLengthText}
    options.BaselineVariables (1, :) string = strings(1, 0)
    options.AucOutcomeVariables (1, :) string = strings(1, 0)
end

arguments (Output)
    effectRows table
end

if isempty(outcomeVariables) || ...
        numel(unique(outcomeVariables)) ~= numel(outcomeVariables)
    error( ...
        "v2xsimregression:positionerror:" + ...
        "InvalidMechanismOutcomeVariables", ...
        "Outcome variables must be a nonempty unique string vector.");
end
baselineVariables = options.BaselineVariables;
if isempty(baselineVariables)
    baselineVariables = outcomeVariables;
elseif numel(baselineVariables) ~= numel(outcomeVariables)
    error( ...
        "v2xsimregression:positionerror:" + ...
        "InvalidMechanismBaselineVariables", ...
        "BaselineVariables must match the number of outcomes.");
end
if any(~ismember(options.AucOutcomeVariables, outcomeVariables))
    error( ...
        "v2xsimregression:positionerror:" + ...
        "InvalidMechanismAucOutcomes", ...
        "Every AUC outcome must also be a selected outcome.");
end

requiredVariables = unique([ ...
    "RandomSeed", "Treatment", "NormalizedMagnitude", ...
    "RealizedNormalizedMagnitude", ...
    outcomeVariables, baselineVariables], "stable");
missingVariables = setdiff( ...
    requiredVariables, ...
    string(seedResults.Properties.VariableNames), "stable");
if ~isempty(missingVariables)
    error( ...
        "v2xsimregression:positionerror:" + ...
        "InvalidMechanismSeedResults", ...
        "Seed results are missing variables: %s.", ...
        join(missingVariables, ", "));
end

randomSeeds = seedResults.RandomSeed;
normalizedMagnitudes = seedResults.NormalizedMagnitude;
realizedNormalizedMagnitudes = ...
    seedResults.RealizedNormalizedMagnitude;
treatments = string(seedResults.Treatment);
if ~isnumeric(randomSeeds) || ~isreal(randomSeeds) || ...
        ~iscolumn(randomSeeds) || ...
        any(~isfinite(randomSeeds)) || ...
        any(randomSeeds ~= fix(randomSeeds)) || ...
        ~isnumeric(normalizedMagnitudes) || ...
        ~isreal(normalizedMagnitudes) || ...
        ~iscolumn(normalizedMagnitudes) || ...
        any(~isfinite(normalizedMagnitudes)) || ...
        any(normalizedMagnitudes < 0) || ...
        ~isnumeric(realizedNormalizedMagnitudes) || ...
        ~isreal(realizedNormalizedMagnitudes) || ...
        ~iscolumn(realizedNormalizedMagnitudes) || ...
        any(~isfinite(realizedNormalizedMagnitudes)) || ...
        any(realizedNormalizedMagnitudes < 0) || ...
        any(ismissing(treatments) | strlength(treatments) == 0)
    error( ...
        "v2xsimregression:positionerror:" + ...
        "InvalidMechanismSeedResults", ...
        "Seed, treatment, and magnitude factors must be valid.");
end
baselineRows = treatments == "None";
if any(normalizedMagnitudes(baselineRows) ~= 0) || ...
        any(realizedNormalizedMagnitudes(baselineRows) ~= 0) || ...
        any(normalizedMagnitudes(~baselineRows) <= 0) || ...
        any(realizedNormalizedMagnitudes(~baselineRows) <= 0)
    error( ...
        "v2xsimregression:positionerror:" + ...
        "InvalidMechanismSeedResults", ...
        "Baseline magnitudes must be zero and treatment " + ...
        "magnitudes must be positive.");
end

for variableName = unique( ...
        [outcomeVariables, baselineVariables], "stable")
    values = seedResults.(variableName);
    if ~isnumeric(values) || ~isreal(values) || ~iscolumn(values)
        error( ...
            "v2xsimregression:positionerror:" + ...
            "InvalidMechanismResponse", ...
            "Mechanism outcome %s must be a real numeric column.", ...
            variableName);
    end
end

seedIds = unique(double(randomSeeds), "stable");
magnitudes = unique(double(normalizedMagnitudes( ...
    treatments ~= "None")), "stable");
estimands = ["RouteBalanced", "Mainline", "Ramp"];
rowsPerOutcomeSeed = 3 + 7 .* numel(magnitudes);
rowCount = numel(outcomeVariables) .* ...
    numel(seedIds) .* rowsPerOutcomeSeed;

outcomeName = strings(rowCount, 1);
responseDomain = strings(rowCount, 1);
estimand = strings(rowCount, 1);
randomSeed = zeros(rowCount, 1);
errorModel = strings(rowCount, 1);
normalizedMagnitude = zeros(rowCount, 1);
realizedNormalizedMagnitude = zeros(rowCount, 1);
sourceVariable = strings(rowCount, 1);
baselineVariable = strings(rowCount, 1);
responseValue = nan(rowCount, 1);
baselineResponseValue = nan(rowCount, 1);
deltaResponseValue = nan(rowCount, 1);
nextRow = 0;

for outcomeIndex = 1:numel(outcomeVariables)
    selectedOutcome = outcomeVariables(outcomeIndex);
    selectedBaseline = baselineVariables(outcomeIndex);
    if ismember(selectedOutcome, options.AucOutcomeVariables)
        selectedDomain = "auc";
    else
        selectedDomain = "finite";
    end

    for seedIndex = 1:numel(seedIds)
        seed = seedIds(seedIndex);
        baseline = uniqueTreatmentRow( ...
            seedResults, treatments, normalizedMagnitudes, ...
            seed, "None", 0);
        baselineValue = double(baseline.(selectedBaseline));

        for selectedEstimand = estimands
            nextRow = nextRow + 1;
            outcomeName(nextRow) = selectedOutcome;
            responseDomain(nextRow) = selectedDomain;
            estimand(nextRow) = selectedEstimand;
            randomSeed(nextRow) = seed;
            errorModel(nextRow) = "None";
            sourceVariable(nextRow) = selectedOutcome;
            baselineVariable(nextRow) = selectedBaseline;
            responseValue(nextRow) = baselineValue;
            baselineResponseValue(nextRow) = baselineValue;
            if isfinite(baselineValue)
                deltaResponseValue(nextRow) = 0;
            end

            for magnitude = reshape(magnitudes, 1, [])
                [models, values, realizedMagnitudes] = ...
                    estimandResponses( ...
                        seedResults, treatments, ...
                        normalizedMagnitudes, seed, magnitude, ...
                        selectedEstimand, selectedOutcome);
                for modelIndex = 1:numel(models)
                    nextRow = nextRow + 1;
                    outcomeName(nextRow) = selectedOutcome;
                    responseDomain(nextRow) = selectedDomain;
                    estimand(nextRow) = selectedEstimand;
                    randomSeed(nextRow) = seed;
                    errorModel(nextRow) = models(modelIndex);
                    normalizedMagnitude(nextRow) = magnitude;
                    realizedNormalizedMagnitude(nextRow) = ...
                        realizedMagnitudes(modelIndex);
                    sourceVariable(nextRow) = selectedOutcome;
                    baselineVariable(nextRow) = selectedBaseline;
                    responseValue(nextRow) = values(modelIndex);
                    baselineResponseValue(nextRow) = baselineValue;
                    deltaResponseValue(nextRow) = ...
                        values(modelIndex) - baselineValue;
                end
            end
        end
    end
end

effectRows = table( ...
    outcomeName, responseDomain, estimand, randomSeed, ...
    errorModel, normalizedMagnitude, ...
    realizedNormalizedMagnitude, sourceVariable, ...
    baselineVariable, responseValue, baselineResponseValue, ...
    deltaResponseValue, ...
    VariableNames=[ ...
        "OutcomeName", "ResponseDomain", "Estimand", ...
        "RandomSeed", "ErrorModel", "NormalizedMagnitude", ...
        "RealizedNormalizedMagnitude", ...
        "SourceVariable", "BaselineVariable", ...
        "ResponseValue", "BaselineResponseValue", ...
        "DeltaResponseValue"]);
end

function [models, values, realizedMagnitudes] = estimandResponses( ...
        seedResults, treatments, normalizedMagnitudes, ...
        seed, magnitude, estimand, outcomeVariable)
if estimand == "RouteBalanced"
    gaussianMainline = uniqueTreatmentRow( ...
        seedResults, treatments, normalizedMagnitudes, ...
        seed, "GaussianMainline", magnitude);
    gaussianRamp = uniqueTreatmentRow( ...
        seedResults, treatments, normalizedMagnitudes, ...
        seed, "GaussianRamp", magnitude);
    falseExit = uniqueTreatmentRow( ...
        seedResults, treatments, normalizedMagnitudes, ...
        seed, "FalseExit", magnitude);
    falseMerge = uniqueTreatmentRow( ...
        seedResults, treatments, normalizedMagnitudes, ...
        seed, "FalseMerge", magnitude);
    models = ["Gaussian", "FalseExit", "FalseMerge"];
    values = [ ...
        mean([ ...
            double(gaussianMainline.(outcomeVariable)), ...
            double(gaussianRamp.(outcomeVariable))]), ...
        double(falseExit.(outcomeVariable)), ...
        double(falseMerge.(outcomeVariable))];
    realizedMagnitudes = [ ...
        mean([ ...
            double(gaussianMainline.RealizedNormalizedMagnitude), ...
            double(gaussianRamp.RealizedNormalizedMagnitude)]), ...
        double(falseExit.RealizedNormalizedMagnitude), ...
        double(falseMerge.RealizedNormalizedMagnitude)];
elseif estimand == "Mainline"
    gaussianMainline = uniqueTreatmentRow( ...
        seedResults, treatments, normalizedMagnitudes, ...
        seed, "GaussianMainline", magnitude);
    falseExit = uniqueTreatmentRow( ...
        seedResults, treatments, normalizedMagnitudes, ...
        seed, "FalseExit", magnitude);
    models = ["Gaussian", "FalseExit"];
    values = [ ...
        double(gaussianMainline.(outcomeVariable)), ...
        double(falseExit.(outcomeVariable))];
    realizedMagnitudes = [ ...
        double(gaussianMainline.RealizedNormalizedMagnitude), ...
        double(falseExit.RealizedNormalizedMagnitude)];
else
    gaussianRamp = uniqueTreatmentRow( ...
        seedResults, treatments, normalizedMagnitudes, ...
        seed, "GaussianRamp", magnitude);
    falseMerge = uniqueTreatmentRow( ...
        seedResults, treatments, normalizedMagnitudes, ...
        seed, "FalseMerge", magnitude);
    models = ["Gaussian", "FalseMerge"];
    values = [ ...
        double(gaussianRamp.(outcomeVariable)), ...
        double(falseMerge.(outcomeVariable))];
    realizedMagnitudes = [ ...
        double(gaussianRamp.RealizedNormalizedMagnitude), ...
        double(falseMerge.RealizedNormalizedMagnitude)];
end
end

function row = uniqueTreatmentRow( ...
        seedResults, treatments, normalizedMagnitudes, ...
        seed, treatment, magnitude)
selected = ...
    double(seedResults.RandomSeed) == seed & ...
    treatments == treatment & ...
    double(normalizedMagnitudes) == magnitude;
if nnz(selected) ~= 1
    error( ...
        "v2xsimregression:positionerror:UnbalancedManifest", ...
        "Every seed/treatment/magnitude tuple must occur once.");
end
row = seedResults(selected, :);
end
