function effectResults = buildRouteStratifiedEffectResults(seedResults)
%BUILDROUTESTRATIFIEDEFFECTRESULTS Build within-route paired contrasts.
%   Mainline compares GaussianMainline with FalseExit against the
%   mainline baseline. Ramp compares GaussianRamp with FalseMerge against
%   the ramp baseline. Keeping these two factorials separate prevents route
%   population from being attributed to error structure.

arguments (Input)
    seedResults table
end
arguments (Output)
    effectResults table
end

requiredNames = [ ...
    "RandomSeed", "Treatment", "NormalizedMagnitude", ...
    "RealizedNormalizedMagnitude", ...
    "MainlineTransmitterDeliveryPrrAuc", ...
    "RampTransmitterDeliveryPrrAuc"];
if any(~ismember( ...
        requiredNames, ...
        string(seedResults.Properties.VariableNames)))
    error( ...
        "v2xsimregression:positionerror:" + ...
        "InvalidRouteStratifiedResults", ...
        "Seed results are missing route-stratified AUC columns.");
end

seedIds = unique(seedResults.RandomSeed, "stable");
magnitudes = unique( ...
    seedResults.NormalizedMagnitude( ...
        seedResults.Treatment ~= "None"), "stable");
routeNames = ["Mainline", "Ramp"];
rowCount = numel(seedIds) .* numel(routeNames) .* ...
    (1 + 2 .* numel(magnitudes));
randomSeed = zeros(rowCount, 1);
routePopulation = strings(rowCount, 1);
errorModel = strings(rowCount, 1);
normalizedMagnitude = zeros(rowCount, 1);
realizedNormalizedMagnitude = zeros(rowCount, 1);
deliveryPrrAuc = zeros(rowCount, 1);
nextRow = 0;

for seedIndex = 1:numel(seedIds)
    seed = seedIds(seedIndex);
    baseline = uniqueTreatmentRow( ...
        seedResults, seed, "None", 0);
    if baseline.RealizedNormalizedMagnitude ~= 0
        error( ...
            "v2xsimregression:positionerror:" + ...
            "InvalidRealizedMagnitude", ...
            "The no-error baseline must have zero realized magnitude.");
    end
    for routeName = routeNames
        if routeName == "Mainline"
            baselineAuc = ...
                baseline.MainlineTransmitterDeliveryPrrAuc;
            gaussianTreatment = "GaussianMainline";
            falseRouteTreatment = "FalseExit";
            falseRouteModel = "FalseExit";
            responseVariable = ...
                "MainlineTransmitterDeliveryPrrAuc";
        else
            baselineAuc = ...
                baseline.RampTransmitterDeliveryPrrAuc;
            gaussianTreatment = "GaussianRamp";
            falseRouteTreatment = "FalseMerge";
            falseRouteModel = "FalseMerge";
            responseVariable = ...
                "RampTransmitterDeliveryPrrAuc";
        end
        if ~isfinite(baselineAuc)
            error( ...
                "v2xsimregression:positionerror:" + ...
                "IncompleteRouteMatchedPrrCurve", ...
                "Seed %g has an incomplete %s baseline.", ...
                seed, lower(routeName));
        end

        nextRow = nextRow + 1;
        randomSeed(nextRow) = seed;
        routePopulation(nextRow) = routeName;
        errorModel(nextRow) = "None";
        deliveryPrrAuc(nextRow) = baselineAuc;

        for magnitude = reshape(magnitudes, 1, [])
            gaussian = uniqueTreatmentRow( ...
                seedResults, seed, gaussianTreatment, magnitude);
            falseRoute = uniqueTreatmentRow( ...
                seedResults, seed, ...
                falseRouteTreatment, magnitude);
            responses = [ ...
                gaussian.(responseVariable), ...
                falseRoute.(responseVariable)];
            realizedMagnitudes = [ ...
                gaussian.RealizedNormalizedMagnitude, ...
                falseRoute.RealizedNormalizedMagnitude];
            if any(~isfinite( ...
                    [responses, realizedMagnitudes])) || ...
                    any(realizedMagnitudes <= 0)
                error( ...
                    "v2xsimregression:positionerror:" + ...
                    "IncompleteRouteMatchedPrrCurve", ...
                    "Seed %g magnitude %g has incomplete %s curves.", ...
                    seed, magnitude, lower(routeName));
            end

            models = ["Gaussian", falseRouteModel];
            for modelIndex = 1:numel(models)
                nextRow = nextRow + 1;
                randomSeed(nextRow) = seed;
                routePopulation(nextRow) = routeName;
                errorModel(nextRow) = models(modelIndex);
                normalizedMagnitude(nextRow) = magnitude;
                realizedNormalizedMagnitude(nextRow) = ...
                    realizedMagnitudes(modelIndex);
                deliveryPrrAuc(nextRow) = ...
                    responses(modelIndex);
            end
        end
    end
end

effectResults = table( ...
    randomSeed, routePopulation, errorModel, ...
    normalizedMagnitude, realizedNormalizedMagnitude, ...
    deliveryPrrAuc, ...
    VariableNames=[ ...
        "RandomSeed", "RoutePopulation", "ErrorModel", ...
        "NormalizedMagnitude", "RealizedNormalizedMagnitude", ...
        "DeliveryPrrAuc"]);
end

function row = uniqueTreatmentRow( ...
        seedResults, seed, treatment, magnitude)
selected = ...
    seedResults.RandomSeed == seed & ...
    seedResults.Treatment == treatment & ...
    seedResults.NormalizedMagnitude == magnitude;
if nnz(selected) ~= 1
    error( ...
        "v2xsimregression:positionerror:UnbalancedManifest", ...
        "Every seed/treatment/magnitude tuple must occur once.");
end
row = seedResults(selected, :);
end
