function effectResults = buildRouteMatchedEffectResults(seedResults)
%BUILDROUTEMATCHEDEFFECTRESULTS Form route-specific AUCs and paired deltas.
%   Gaussian uses the equal-weight mean of its mainline-only and ramp-only
%   treatment deltas. False exit uses the mainline-transmitter delta and
%   false merge uses the ramp-transmitter delta. DELIVERYPRRAUC always
%   remains an observed route-specific or equal-route-weight AUC in [0, 1].
%   DELTADELIVERYPRRAUC carries the route-matched paired response used by
%   the effect model.

arguments (Input)
    seedResults table
end
arguments (Output)
    effectResults table
end

requiredNames = [ ...
    "RandomSeed", "Treatment", "NormalizedMagnitude", ...
    "RealizedNormalizedMagnitude", ...
    "MainlineTransmitterDeliveryPrrAuc", ...
    "RampTransmitterDeliveryPrrAuc"];
if any(~ismember( ...
        requiredNames, ...
        string(seedResults.Properties.VariableNames)))
    error( ...
        "v2xsimregression:positionerror:InvalidRouteMatchedResults", ...
        "Seed results are missing route-matched AUC columns.");
end

seedIds = unique(seedResults.RandomSeed, "stable");
magnitudes = unique( ...
    seedResults.NormalizedMagnitude( ...
        seedResults.Treatment ~= "None"), "stable");
rowCount = numel(seedIds) .* (1 + 3 .* numel(magnitudes));
randomSeed = zeros(rowCount, 1);
errorModel = strings(rowCount, 1);
normalizedMagnitude = zeros(rowCount, 1);
realizedNormalizedMagnitude = zeros(rowCount, 1);
deliveryPrrAuc = zeros(rowCount, 1);
deltaDeliveryPrrAuc = zeros(rowCount, 1);
nextRow = 0;

for seedIndex = 1:numel(seedIds)
    seed = seedIds(seedIndex);
    baseline = seedResults( ...
        seedResults.RandomSeed == seed & ...
        seedResults.Treatment == "None", :);
    if height(baseline) ~= 1
        error( ...
            "v2xsimregression:positionerror:UnpairedBaseline", ...
            "Every seed must contain exactly one baseline.");
    end
    baselineMainline = ...
        baseline.MainlineTransmitterDeliveryPrrAuc;
    baselineRamp = baseline.RampTransmitterDeliveryPrrAuc;
    commonBaseline = mean([baselineMainline, baselineRamp]);
    if baseline.RealizedNormalizedMagnitude ~= 0
        error( ...
            "v2xsimregression:positionerror:" + ...
            "InvalidRealizedMagnitude", ...
            "The no-error baseline must have zero realized magnitude.");
    end
    if ~all(isfinite( ...
            [baselineMainline, baselineRamp, commonBaseline])) || ...
            any([baselineMainline, baselineRamp] < 0 | ...
                [baselineMainline, baselineRamp] > 1)
        error( ...
            "v2xsimregression:positionerror:" + ...
            "IncompleteRouteMatchedPrrCurve", ...
            "Seed %g has an invalid route-specific baseline.", ...
            seed);
    end

    nextRow = nextRow + 1;
    randomSeed(nextRow) = seed;
    errorModel(nextRow) = "None";
    deliveryPrrAuc(nextRow) = commonBaseline;

    for magnitude = reshape(magnitudes, 1, [])
        gaussianMainline = uniqueTreatmentRow( ...
            seedResults, seed, "GaussianMainline", magnitude);
        gaussianRamp = uniqueTreatmentRow( ...
            seedResults, seed, "GaussianRamp", magnitude);
        falseExit = uniqueTreatmentRow( ...
            seedResults, seed, "FalseExit", magnitude);
        falseMerge = uniqueTreatmentRow( ...
            seedResults, seed, "FalseMerge", magnitude);

        rawAucs = [ ...
            mean([ ...
                gaussianMainline. ...
                    MainlineTransmitterDeliveryPrrAuc, ...
                gaussianRamp.RampTransmitterDeliveryPrrAuc]), ...
            falseExit.MainlineTransmitterDeliveryPrrAuc, ...
            falseMerge.RampTransmitterDeliveryPrrAuc];
        deltas = [ ...
            mean([ ...
                gaussianMainline. ...
                    MainlineTransmitterDeliveryPrrAuc - ...
                    baselineMainline, ...
                gaussianRamp.RampTransmitterDeliveryPrrAuc - ...
                    baselineRamp]), ...
            falseExit.MainlineTransmitterDeliveryPrrAuc - ...
                baselineMainline, ...
            falseMerge.RampTransmitterDeliveryPrrAuc - ...
                baselineRamp];
        realizedMagnitudes = [ ...
            mean([ ...
                gaussianMainline.RealizedNormalizedMagnitude, ...
                gaussianRamp.RealizedNormalizedMagnitude]), ...
            falseExit.RealizedNormalizedMagnitude, ...
            falseMerge.RealizedNormalizedMagnitude];
        if any(~isfinite( ...
                [rawAucs, deltas, realizedMagnitudes])) || ...
                any(rawAucs < 0 | rawAucs > 1) || ...
                any(realizedMagnitudes <= 0)
            error( ...
                "v2xsimregression:positionerror:" + ...
                "IncompleteRouteMatchedPrrCurve", ...
                "Seed %g magnitude %g has invalid route curves.", ...
                seed, magnitude);
        end

        models = ["Gaussian", "FalseExit", "FalseMerge"];
        for modelIndex = 1:numel(models)
            nextRow = nextRow + 1;
            randomSeed(nextRow) = seed;
            errorModel(nextRow) = models(modelIndex);
            normalizedMagnitude(nextRow) = magnitude;
            realizedNormalizedMagnitude(nextRow) = ...
                realizedMagnitudes(modelIndex);
            deliveryPrrAuc(nextRow) = rawAucs(modelIndex);
            deltaDeliveryPrrAuc(nextRow) = deltas(modelIndex);
        end
    end
end

effectResults = table( ...
    randomSeed, errorModel, normalizedMagnitude, ...
    realizedNormalizedMagnitude, ...
    deliveryPrrAuc, deltaDeliveryPrrAuc, ...
    VariableNames=[ ...
        "RandomSeed", "ErrorModel", ...
        "NormalizedMagnitude", "RealizedNormalizedMagnitude", ...
        "DeliveryPrrAuc", ...
        "DeltaDeliveryPrrAuc"]);
end

function row = uniqueTreatmentRow( ...
        seedResults, seed, treatment, magnitude)
selected = ...
    seedResults.RandomSeed == seed & ...
    seedResults.Treatment == treatment & ...
    seedResults.NormalizedMagnitude == magnitude;
if nnz(selected) ~= 1
    error( ...
        "v2xsimregression:positionerror:UnbalancedManifest", ...
        "Every seed/treatment/magnitude tuple must occur once.");
end
row = seedResults(selected, :);
end
