function manifest = createRampCampaignManifest( ...
        outputDirectory, randomSeeds, normalizedMagnitudes, options)
%CREATERAMPCAMPAIGNMANIFEST Build paired ramp-error work items.
%   Every seed receives one no-error baseline and the complete
%   ErrorModel-by-NormalizedMagnitude factorial. Position-error selection
%   seeds are shared across Gaussian, false-exit, and false-merge arms so
%   the selected outer-lane cohort is paired across error structures.

arguments (Input)
    outputDirectory (1, 1) string {mustBeNonzeroLengthText}
    randomSeeds (1, :) double ...
        {mustBeInteger, mustBeNonnegative}
    normalizedMagnitudes (1, :) double ...
        {mustBeReal, mustBeFinite, mustBePositive}
    options.SimulationTimeSeconds (1, 1) double ...
        {mustBeReal, mustBeFinite, mustBePositive} = 60
    options.RoadLengthMeters (1, 1) double ...
        {mustBeReal, mustBeFinite, mustBePositive} = 2000
    options.LaneWidthMeters (1, 1) double ...
        {mustBeReal, mustBeFinite, mustBePositive} = 4
    options.MergeDistanceMeters (1, 1) double ...
        {mustBeReal, mustBeFinite, mustBeNonnegative} = 100
    options.AffectedVehicleProbability (1, 1) double ...
        {mustBeReal, mustBeFinite, mustBeNonnegative} = 1
end

arguments (Output)
    manifest table
end

if isempty(randomSeeds) || isempty(normalizedMagnitudes)
    error( ...
        "v2xsimregression:positionerror:EmptyManifestFactor", ...
        "Random seeds and normalized magnitudes must be nonempty.");
end
if numel(unique(randomSeeds)) ~= numel(randomSeeds)
    error( ...
        "v2xsimregression:positionerror:DuplicateRandomSeed", ...
        "RandomSeeds must not contain duplicates.");
end
if numel(unique(normalizedMagnitudes)) ~= ...
        numel(normalizedMagnitudes)
    error( ...
        "v2xsimregression:positionerror:DuplicateMagnitude", ...
        "NormalizedMagnitudes must not contain duplicates.");
end
if any(normalizedMagnitudes > 1)
    error( ...
        "v2xsimregression:positionerror:MagnitudeScaleOutOfRange", ...
        "Normalized magnitudes cannot exceed full false-route scale.");
end
if options.MergeDistanceMeters > options.RoadLengthMeters ./ 2
    error( ...
        "v2xsimregression:positionerror:InvalidMergeDistance", ...
        "MergeDistanceMeters cannot exceed half RoadLengthMeters.");
end
if options.AffectedVehicleProbability > 1
    error( ...
        "v2xsimregression:positionerror:InvalidAffectedProbability", ...
        "AffectedVehicleProbability cannot exceed one.");
end
if any(randomSeeds > double(intmax("uint32")))
    error( ...
        "v2xsimregression:positionerror:RandomSeedOutOfRange", ...
        "Random seeds must fit in an unsigned 32-bit integer.");
end

treatments = [ ...
    "GaussianMainline", "GaussianRamp", ...
    "FalseExit", "FalseMerge"];
fullScaleMeanMagnitude = ...
    v2xsim.positioning.calibration. ...
        falseRouteMeanMagnitudeAtFullScale( ...
            options.RoadLengthMeters, ...
            options.LaneWidthMeters, ...
            options.MergeDistanceMeters);
runCountPerSeed = ...
    1 + numel(treatments) .* numel(normalizedMagnitudes);
rowCount = numel(randomSeeds) .* runCountPerSeed;

runLabel = strings(rowCount, 1);
runOutputDirectory = strings(rowCount, 1);
randomSeed = zeros(rowCount, 1);
treatment = strings(rowCount, 1);
errorModel = strings(rowCount, 1);
normalizedMagnitude = zeros(rowCount, 1);
targetMeanMagnitudeMeters = zeros(rowCount, 1);
gaussianMagnitudeStandardDeviationMeters = zeros(rowCount, 1);
falseRouteDisplacementScale = zeros(rowCount, 1);
selectionRandomSeed = zeros(rowCount, 1);
displacementRandomSeed = zeros(rowCount, 1);
simulationTimeSeconds = repmat( ...
    options.SimulationTimeSeconds, rowCount, 1);

nextRow = 0;
for seed = randomSeeds
    sharedSelectionSeed = saltedSeed(seed, 310019);
    gaussianDisplacementSeed = saltedSeed(seed, 410041);

    nextRow = nextRow + 1;
    [runLabel(nextRow), runOutputDirectory(nextRow)] = ...
        runIdentity(outputDirectory, seed, "None", 0);
    randomSeed(nextRow) = seed;
    treatment(nextRow) = "None";
    errorModel(nextRow) = "None";
    selectionRandomSeed(nextRow) = sharedSelectionSeed;
    displacementRandomSeed(nextRow) = gaussianDisplacementSeed;

    for configuredTreatment = treatments
        for magnitude = normalizedMagnitudes
            nextRow = nextRow + 1;
            targetMagnitude = magnitude .* fullScaleMeanMagnitude;
            [runLabel(nextRow), runOutputDirectory(nextRow)] = ...
                runIdentity( ...
                    outputDirectory, seed, ...
                    configuredTreatment, magnitude);
            randomSeed(nextRow) = seed;
            treatment(nextRow) = configuredTreatment;
            if startsWith(configuredTreatment, "Gaussian")
                errorModel(nextRow) = "Gaussian";
            else
                errorModel(nextRow) = configuredTreatment;
            end
            normalizedMagnitude(nextRow) = magnitude;
            targetMeanMagnitudeMeters(nextRow) = targetMagnitude;
            % Preserve the radial coefficient of variation of the former
            % Cartesian-Gaussian comparator while making the radial mean
            % an explicit treatment parameter.
            gaussianMagnitudeStandardDeviationMeters(nextRow) = ...
                targetMagnitude .* sqrt((4 - pi) ./ pi);
            falseRouteDisplacementScale(nextRow) = ...
                v2xsim.positioning.calibration. ...
                    falseRouteDisplacementScale( ...
                        targetMagnitude, ...
                        options.RoadLengthMeters, ...
                        options.LaneWidthMeters, ...
                        options.MergeDistanceMeters);
            selectionRandomSeed(nextRow) = sharedSelectionSeed;
            displacementRandomSeed(nextRow) = ...
                gaussianDisplacementSeed;
        end
    end
end

manifest = table( ...
    runLabel, runOutputDirectory, randomSeed, treatment, errorModel, ...
    normalizedMagnitude, targetMeanMagnitudeMeters, ...
    gaussianMagnitudeStandardDeviationMeters, ...
    falseRouteDisplacementScale, selectionRandomSeed, ...
    displacementRandomSeed, simulationTimeSeconds, ...
    repmat(options.AffectedVehicleProbability, rowCount, 1), ...
    repmat(options.RoadLengthMeters, rowCount, 1), ...
    repmat(options.LaneWidthMeters, rowCount, 1), ...
    repmat(options.MergeDistanceMeters, rowCount, 1), ...
    VariableNames=[ ...
        "RunLabel", "OutputDirectory", "RandomSeed", ...
        "Treatment", "ErrorModel", "NormalizedMagnitude", ...
        "TargetMeanMagnitudeMeters", ...
        "GaussianMagnitudeStandardDeviationMeters", ...
        "FalseRouteDisplacementScale", ...
        "SelectionRandomSeed", "DisplacementRandomSeed", ...
        "SimulationTimeSeconds", "AffectedVehicleProbability", ...
        "RoadLengthMeters", "LaneWidthMeters", ...
        "MergeDistanceMeters"]);
end

function seed = saltedSeed(baseSeed, salt)
modulus = double(intmax("uint32")) + 1;
seed = mod(double(baseSeed) + salt, modulus);
end

function [label, directory] = ...
        runIdentity(outputRoot, seed, model, magnitude)
seedToken = compose("seed-%u", uint32(seed));
modelToken = lower(regexprep(model, "[^A-Za-z0-9]", ""));
if model == "None"
    treatmentToken = "no-error";
else
    magnitudeToken = replace(compose("%.6g", magnitude), ".", "p");
    treatmentToken = modelToken + "-magnitude-" + magnitudeToken;
end
label = seedToken + "/" + treatmentToken;
directory = fullfile(outputRoot, seedToken, treatmentToken);
end
