function [outcomes, baselines, aucOutcomes] = ...
        rampMechanismOutcomeConfiguration()
%RAMPMECHANISMOUTCOMECONFIGURATION Predeclare comparable mechanisms.
%   Failure mechanisms use denominator-explicit rates rather than raw
%   counts. Conditional status-effect-active-link AUC remains descriptive
%   because the no-error arm has no matched active-link population.

outcomes = [ ...
    "MeanNormalizedKendallTauDistance", ...
    "MeanTopKNeighborJaccard", ...
    "MeanResourcePairGraphXorRate", ...
    "MeanInterferenceOverlapPairGraphXorRate", ...
    "MeanExactDecisionDisagreementRate", ...
    "MeanTrueDistanceRegretMeters", ...
    "MeanHarmfulReuseCandidateRate", ...
    "MeanMissedReuseCandidateRate", ...
    "MeanHarmfulInterferenceOverlapCandidateRate", ...
    "MeanMissedInterferenceOverlapCandidateRate", ...
    failureRateOutcomes(), ...
    "RadioPrrAuc"];
baselines = outcomes;
aucOutcomes = "RadioPrrAuc";
end

function outcomes = failureRateOutcomes()
prefixes = [ ...
    "HiddenTerminal", ...
    "HalfDuplexFailure", ...
    "CochannelInterferenceFailure", ...
    "AdjacentChannelInterferenceFailure", ...
    "CrossTechnologyInterferenceFailure", ...
    "MultipleSufficientInterferersFailure", ...
    "JointInterferenceFailure", ...
    "OtherInterferenceFailure", ...
    "NoiseOrPropagationFailure"];
outcomes = strings(1, numel(prefixes) .* 2);
outcomes(1:2:end) = prefixes + "CompositionRate";
outcomes(2:2:end) = prefixes + "IncidenceRate";
end
