function [seedResults, effectAnalysis, effectSeedResults, ...
        routeStratifiedAnalysis, routeStratifiedSeedResults] = ...
        runRampErrorStructureCampaign( ...
            simulatorRoot, outputDirectory, options)
%RUNRAMPERRORSTRUCTURECAMPAIGN Run the paired ramp-error factorial.
%   The default campaign contains one no-error baseline and all
%   Gaussian-mainline/Gaussian-ramp/false-exit/false-merge execution arms
%   by magnitude for every seed. The two Gaussian arms support a single
%   route-balanced Gaussian estimand. Traffic, packet, propagation, and
%   allocator seeds are paired; positioning uses isolated component-owned
%   displacement and selection streams recorded in each simulation summary.

arguments (Input)
    simulatorRoot (1, 1) string {mustBeNonzeroLengthText}
    outputDirectory (1, 1) string {mustBeNonzeroLengthText}
    options.RandomSeeds (1, :) double ...
        {mustBeInteger, mustBePositive} = 10:29
    options.NormalizedMagnitudes (1, :) double ...
        {mustBeReal, mustBeFinite, mustBePositive} = [0.25, 0.5, 1]
    options.SimulationTimeSeconds (1, 1) double ...
        {mustBeReal, mustBeFinite, mustBePositive} = 60
    options.VehicleCount (1, 1) double ...
        {mustBeInteger, mustBePositive} = 120
    options.RoadLengthMeters (1, 1) double ...
        {mustBeReal, mustBeFinite, mustBePositive} = 2000
    options.LaneWidthMeters (1, 1) double ...
        {mustBeReal, mustBeFinite, mustBePositive} = 4
    options.MergeDistanceMeters (1, 1) double ...
        {mustBeReal, mustBeFinite, mustBeNonnegative} = 100
    options.ExitProbability (1, 1) double ...
        {mustBeReal, mustBeFinite, mustBeNonnegative} = 0.5
    options.AffectedVehicleProbability (1, 1) double ...
        {mustBeReal, mustBeFinite, mustBeNonnegative} = 1
    options.MaximumPrrDistanceMeters (1, 1) double ...
        {mustBeReal, mustBeFinite, mustBePositive} = 300
    options.PrrDistanceBinWidthMeters (1, 1) double ...
        {mustBeReal, mustBeFinite, mustBePositive} = 25
    options.MaximumExposedShadowCases (1, 1) double ...
        {mustBeReal, mustBePositive} = 1000
    options.ExposedShadowEvaluationHorizonSeconds (1, 1) double ...
        {mustBeReal, mustBeFinite, mustBePositive} = 0.1
    options.MinimumShadowReceiverObservationCount (1, 1) double ...
        {mustBeInteger, mustBePositive} = 10
    options.PositionErrorTraceFlushRowCount (1, 1) double ...
        {mustBeInteger, mustBePositive} = 50000
    options.ControllerDiagnosticsFlushRowCount (1, 1) double ...
        {mustBeInteger, mustBePositive} = 25000
    options.PacketFateTraceFlushRowCount (1, 1) double ...
        {mustBeInteger, mustBePositive} = 100000
    options.ExecutionMode (1, 1) string {mustBeMember( ...
        options.ExecutionMode, ["auto", "serial", "parallel"])} = "auto"
    options.MaxWorkers (1, 1) double { ...
        v2xsimregression.execution.mustBeWorkerLimit} = Inf
    options.BootstrapSampleCount (1, 1) double ...
        {mustBeInteger, mustBePositive} = 10000
    options.MagnitudeModel (1, 1) string {mustBeMember( ...
        options.MagnitudeModel, ...
        ["categorical", "continuous"])} = "categorical"
    options.MaximumMagnitudeRelativeError (1, 1) double ...
        {mustBeReal, mustBeFinite, mustBeNonnegative} = 0.05
    options.EnforceMagnitudeCalibration (1, 1) logical = true
    options.EnforceExposureMatching (1, 1) logical = true
    options.RunEffectAnalysis (1, 1) logical = true
end

arguments (Output)
    seedResults table
    effectAnalysis (1, 1) struct
    effectSeedResults table
    routeStratifiedAnalysis (1, 1) struct
    routeStratifiedSeedResults table
end

if numel(unique(options.RandomSeeds)) ~= ...
        numel(options.RandomSeeds)
    error( ...
        "v2xsimregression:positionerror:DuplicateRandomSeed", ...
        "RandomSeeds must not contain duplicates.");
end
if any(options.RandomSeeds > double(intmax("uint32")))
    error( ...
        "v2xsimregression:positionerror:RandomSeedOutOfRange", ...
        "Random seeds must fit in an unsigned 32-bit integer.");
end
if numel(unique(options.NormalizedMagnitudes)) ~= ...
        numel(options.NormalizedMagnitudes)
    error( ...
        "v2xsimregression:positionerror:DuplicateMagnitude", ...
        "NormalizedMagnitudes must not contain duplicates.");
end
if any(options.NormalizedMagnitudes > 1)
    error( ...
        "v2xsimregression:positionerror:MagnitudeScaleOutOfRange", ...
        "Normalized magnitudes cannot exceed full false-route scale.");
end
if options.ExitProbability > 1 || ...
        options.AffectedVehicleProbability > 1
    error( ...
        "v2xsimregression:positionerror:InvalidProbability", ...
        "Exit and affected-vehicle probabilities cannot exceed one.");
end
if options.MergeDistanceMeters > ...
        options.RoadLengthMeters ./ 2
    error( ...
        "v2xsimregression:positionerror:InvalidMergeDistance", ...
        "MergeDistanceMeters cannot exceed half RoadLengthMeters.");
end
if options.RunEffectAnalysis && numel(options.RandomSeeds) < 2
    error( ...
        "v2xsimregression:positionerror:InsufficientAnalysisSeeds", ...
        "Effect analysis requires at least two paired seeds.");
end
if options.RunEffectAnalysis && ...
        numel(options.NormalizedMagnitudes) < 2
    error( ...
        "v2xsimregression:positionerror:" + ...
        "InsufficientAnalysisMagnitudes", ...
        "Effect analysis requires at least two magnitudes.");
end
if options.RunEffectAnalysis && options.BootstrapSampleCount < 40
    error( ...
        "v2xsimregression:positionerror:" + ...
        "InsufficientBootstrapSamples", ...
        "BootstrapSampleCount must be at least 40.");
end
if ~isinf(options.MaximumExposedShadowCases) && ...
        (~isfinite(options.MaximumExposedShadowCases) || ...
        fix(options.MaximumExposedShadowCases) ~= ...
            options.MaximumExposedShadowCases)
    error( ...
        "v2xsimregression:positionerror:" + ...
        "InvalidMaximumShadowCases", ...
        "MaximumExposedShadowCases must be a positive integer or Inf.");
end
if options.ExposedShadowEvaluationHorizonSeconds ~= 0.1
    error( ...
        "v2xsimregression:positionerror:" + ...
        "InvalidExposedShadowHorizon", ...
        "The Ramp campaign shadow horizon must equal the 0.1-second " + ...
        "allocation interval. Independent replications, not a longer " + ...
        "resource lock, provide repeated receiver observations.");
end
if mod( ...
        options.MaximumPrrDistanceMeters, ...
        options.PrrDistanceBinWidthMeters) ~= 0
    error( ...
        "v2xsimregression:positionerror:MisalignedPrrGrid", ...
        "Maximum PRR distance must be a multiple of bin width.");
end

callerDirectory = string(pwd);
simulatorRoot = absolutePath(simulatorRoot, callerDirectory);
outputDirectory = absolutePath(outputDirectory, callerDirectory);
configurationFile = fullfile( ...
    simulatorRoot, "tests", "+v2xsimtest", "+fixtures", ...
    "config", "ExitRampHighwaySmoke.toml");
validateSimulator(simulatorRoot, configurationFile);
prepareCampaignDirectory(outputDirectory);

originalPath = path;
originalStream = RandStream.getGlobalStream();
originalStreamState = originalStream.State;
originalWarningState = warning;
environmentCleanup = onCleanup(@() restoreEnvironment( ...
    originalPath, originalStream, originalStreamState, ...
    originalWarningState));

addpath(fullfile(simulatorRoot, "src"));
addpath(fullfile(simulatorRoot, "regression-tests"));
addpath(fullfile(simulatorRoot, "lib", "matlab-toml"));

manifest = ...
    v2xsimregression.positionerror.createRampCampaignManifest( ...
        outputDirectory, options.RandomSeeds, ...
        options.NormalizedMagnitudes, ...
        SimulationTimeSeconds=options.SimulationTimeSeconds, ...
        RoadLengthMeters=options.RoadLengthMeters, ...
        LaneWidthMeters=options.LaneWidthMeters, ...
        MergeDistanceMeters=options.MergeDistanceMeters, ...
        AffectedVehicleProbability= ...
            options.AffectedVehicleProbability);
manifest.VehicleCount = repmat( ...
    options.VehicleCount, height(manifest), 1);
manifest.ExitProbability = repmat( ...
    options.ExitProbability, height(manifest), 1);
manifest.MaximumPrrDistanceMeters = repmat( ...
    options.MaximumPrrDistanceMeters, height(manifest), 1);
manifest.PrrDistanceBinWidthMeters = repmat( ...
    options.PrrDistanceBinWidthMeters, height(manifest), 1);
manifest.AllocationIntervalSeconds = repmat( ...
    0.1, height(manifest), 1);
manifest.MaximumTransmissionCount = ones(height(manifest), 1);
manifest.MaximumMagnitudeRelativeError = repmat( ...
    options.MaximumMagnitudeRelativeError, ...
    height(manifest), 1);
manifest.EnforceMagnitudeCalibration = repmat( ...
    options.EnforceMagnitudeCalibration, height(manifest), 1);
manifest.EnforceExposureMatching = repmat( ...
    options.EnforceExposureMatching, height(manifest), 1);
manifest.MagnitudeModel = repmat( ...
    options.MagnitudeModel, height(manifest), 1);
manifest.MaximumExposedShadowCases = repmat( ...
    options.MaximumExposedShadowCases, height(manifest), 1);
manifest.ExposedShadowEvaluationHorizonSeconds = repmat( ...
    options.ExposedShadowEvaluationHorizonSeconds, ...
    height(manifest), 1);
manifest.MinimumShadowReceiverObservationCount = repmat( ...
    options.MinimumShadowReceiverObservationCount, ...
    height(manifest), 1);
manifest.PositionErrorTraceFlushRowCount = repmat( ...
    options.PositionErrorTraceFlushRowCount, height(manifest), 1);
manifest.ControllerDiagnosticsFlushRowCount = repmat( ...
    options.ControllerDiagnosticsFlushRowCount, ...
    height(manifest), 1);
manifest.PacketFateTraceFlushRowCount = repmat( ...
    options.PacketFateTraceFlushRowCount, height(manifest), 1);
writetable( ...
    manifest, ...
    fullfile(outputDirectory, "campaign_manifest.csv"));
workItems = table2struct(manifest);
workItemCells = arrayfun( ...
    @(workItem) {workItem}, workItems);
additionalPaths = [ ...
    fullfile(simulatorRoot, "regression-tests"), ...
    fullfile(simulatorRoot, "src"), ...
    fullfile(simulatorRoot, "lib", "matlab-toml")];
resultCells = v2xsimregression.execution.runWorkItems( ...
    workItemCells, ...
    @(workItem) runWorkItem( ...
        workItem, configurationFile, options), ...
    Labels=manifest.RunLabel.', ...
    ExecutionMode=options.ExecutionMode, ...
    MaxWorkers=options.MaxWorkers, ...
    AdditionalPaths=additionalPaths, ...
    CollectAllFailures=true);
seedResults = vertcat(resultCells{:});
seedResults = sortrows( ...
    seedResults, ...
    ["RandomSeed", "Treatment", "NormalizedMagnitude"]);
seedResults = addMagnitudeCalibration( ...
    seedResults, options.MaximumMagnitudeRelativeError);
seedResults = ...
    v2xsimregression.positionerror. ...
        addExposureMatchingDiagnostics(seedResults);
writetable( ...
    seedResults, ...
    fullfile(outputDirectory, "seed_results.csv"));
if options.EnforceMagnitudeCalibration
    failedCalibration = ...
        seedResults.Treatment ~= "None" & ...
        seedResults.MagnitudeCalibrationStatus ~= ...
            "WithinTolerance";
    if any(failedCalibration)
        error( ...
            "v2xsimregression:positionerror:" + ...
            "RealizedMagnitudeMismatch", ...
            "Realized active mean error is outside the configured " + ...
            "relative tolerance for: %s.", ...
            join(seedResults.RunLabel(failedCalibration), ", "));
    end
end
if options.EnforceExposureMatching
    failedExposureMatching = ...
        seedResults.Treatment ~= "None" & ...
        seedResults.ExposureMatchingStatus ~= "Matched";
    if any(failedExposureMatching)
        error( ...
            "v2xsimregression:positionerror:" + ...
            "ExposureManipulationMismatch", ...
            "Route-matched Gaussian and false-route arms do not " + ...
            "share the same selected cohort, active sample count, " + ...
            "and episode count for: %s.", ...
            join(seedResults.RunLabel(failedExposureMatching), ", "));
    end
end

if any(~isfinite(seedResults.DeliveryPrrAuc))
    incompleteRuns = seedResults.RunLabel( ...
        ~isfinite(seedResults.DeliveryPrrAuc));
    error( ...
        "v2xsimregression:positionerror:IncompletePrimaryPrrCurve", ...
        "Primary delivery PRR curves are incomplete for: %s.", ...
        join(incompleteRuns, ", "));
end

effectSeedResults = ...
    v2xsimregression.positionerror. ...
        buildRouteMatchedEffectResults(seedResults);
routeStratifiedSeedResults = ...
    v2xsimregression.positionerror. ...
        buildRouteStratifiedEffectResults(seedResults);
[mechanismOutcomes, mechanismBaselines, aucOutcomes] = ...
    v2xsimregression.positionerror. ...
        rampMechanismOutcomeConfiguration();
mechanismEffectRows = ...
    v2xsimregression.positionerror. ...
        buildMechanismEffectResults( ...
            seedResults, mechanismOutcomes, ...
            BaselineVariables=mechanismBaselines, ...
            AucOutcomeVariables=aucOutcomes);
mechanismAnalysis = ...
    v2xsimregression.positionerror. ...
        analyzeMechanismEffectResults( ...
            mechanismEffectRows, ...
            RunEffectAnalysis=options.RunEffectAnalysis, ...
            BootstrapSampleCount=options.BootstrapSampleCount, ...
            MagnitudeModel=options.MagnitudeModel);
mechanismAnalysis.RealizedMagnitudeSensitivity = ...
    v2xsimregression.positionerror. ...
        analyzeMechanismEffectResults( ...
            mechanismEffectRows, ...
            RunEffectAnalysis=options.RunEffectAnalysis, ...
            BootstrapSampleCount=options.BootstrapSampleCount, ...
            MagnitudeModel="continuous", ...
            MagnitudeVariable="RealizedNormalizedMagnitude");
mechanismAnalysis.EstimandInterpretation = struct( ...
    "RouteBalanced", ...
        "DescriptiveAcrossNonMirroredRoutePopulations", ...
    "Mainline", "IdentifiableGaussianVersusFalseExit", ...
    "Ramp", "IdentifiableGaussianVersusFalseMerge");
if options.RunEffectAnalysis
    effectAnalysis = ...
        v2xsimregression.positionerror.analyzeEffectDominance( ...
            effectSeedResults, ...
            BootstrapSampleCount=options.BootstrapSampleCount, ...
            MagnitudeModel=options.MagnitudeModel);
    effectAnalysis.RealizedMagnitudeSensitivity = ...
        v2xsimregression.positionerror.analyzeEffectDominance( ...
            effectSeedResults, ...
            BootstrapSampleCount=options.BootstrapSampleCount, ...
            MagnitudeModel="continuous", ...
            MagnitudeVariable= ...
                "RealizedNormalizedMagnitude");
    effectAnalysis.EstimandInterpretation = ...
        "DescriptiveAcrossNonMirroredRoutePopulations";
    routeStratifiedAnalysis = struct;
    for routeName = ["Mainline", "Ramp"]
        routeRows = ...
            routeStratifiedSeedResults.RoutePopulation == ...
            routeName;
        routeAnalysis = ...
            v2xsimregression.positionerror. ...
                analyzeEffectDominance( ...
                    routeStratifiedSeedResults(routeRows, :), ...
                    BootstrapSampleCount= ...
                        options.BootstrapSampleCount, ...
                    MagnitudeModel=options.MagnitudeModel);
        routeAnalysis.RealizedMagnitudeSensitivity = ...
            v2xsimregression.positionerror. ...
                analyzeEffectDominance( ...
                    routeStratifiedSeedResults(routeRows, :), ...
                    BootstrapSampleCount= ...
                        options.BootstrapSampleCount, ...
                    MagnitudeModel="continuous", ...
                    MagnitudeVariable= ...
                        "RealizedNormalizedMagnitude");
        if routeName == "Mainline"
            routeAnalysis.EstimandInterpretation = ...
                "IdentifiableGaussianVersusFalseExit";
        else
            routeAnalysis.EstimandInterpretation = ...
                "IdentifiableGaussianVersusFalseMerge";
        end
        routeStratifiedAnalysis.(routeName) = routeAnalysis;
    end
else
    effectAnalysis = struct( ...
        "Conclusion", "NotRequested", ...
        "EstimandInterpretation", ...
            "DescriptiveAcrossNonMirroredRoutePopulations");
    routeStratifiedAnalysis = struct( ...
        "Conclusion", "NotRequested");
end

writetable( ...
    effectSeedResults, ...
    fullfile(outputDirectory, "effect_seed_results.csv"));
writetable( ...
    routeStratifiedSeedResults, ...
    fullfile( ...
        outputDirectory, ...
        "route_stratified_effect_seed_results.csv"));
writetable( ...
    mechanismEffectRows, ...
    fullfile( ...
        outputDirectory, ...
        "mechanism_effect_seed_results.csv"));
writelines( ...
    string(jsonencode(effectAnalysis, PrettyPrint=true)), ...
    fullfile(outputDirectory, "effect_analysis.json"));
writelines( ...
    string(jsonencode( ...
        routeStratifiedAnalysis, PrettyPrint=true)), ...
    fullfile( ...
        outputDirectory, ...
        "route_stratified_effect_analysis.json"));
writelines( ...
    string(jsonencode( ...
        mechanismAnalysis, PrettyPrint=true)), ...
    fullfile( ...
        outputDirectory, ...
        "mechanism_effect_analysis.json"));
environmentCleanup; %#ok<VUNUS>
end

function results = addMagnitudeCalibration(results, tolerance)
target = double(results.TargetMeanMagnitudeMeters);
realized = double(results.RealizedMeanErrorMagnitudeMeters);
isBaseline = results.Treatment == "None";
relativeError = nan(height(results), 1);
relativeError(~isBaseline) = ...
    abs(realized(~isBaseline) - target(~isBaseline)) ./ ...
    target(~isBaseline);
realizedNormalizedMagnitude = zeros(height(results), 1);
realizedNormalizedMagnitude(~isBaseline) = ...
    results.NormalizedMagnitude(~isBaseline) .* ...
    realized(~isBaseline) ./ target(~isBaseline);
status = repmat("WithinTolerance", height(results), 1);
status(isBaseline) = "NoErrorBaseline";
status(~isBaseline & ~isfinite(relativeError)) = ...
    "Unavailable";
status(~isBaseline & isfinite(relativeError) & ...
    relativeError > tolerance) = "OutsideTolerance";
results.MagnitudeAbsoluteErrorMeters = ...
    abs(realized - target);
results.MagnitudeRelativeError = relativeError;
results.RealizedNormalizedMagnitude = ...
    realizedNormalizedMagnitude;
results.MagnitudeRelativeTolerance = ...
    repmat(tolerance, height(results), 1);
results.MagnitudeCalibrationStatus = status;
end

function result = runWorkItem( ...
        workItem, configurationFile, options)
positionErrors = treatmentErrors(workItem);
patchData = struct( ...
    Simulation=struct( ...
        RandomSeed=workItem.RandomSeed, ...
        DurationSeconds=workItem.SimulationTimeSeconds), ...
    Scenario=struct( ...
        Type="ExitRampHighway", ...
        UpdateIntervalSeconds=0.1, ...
        ExitRampHighway=struct( ...
            RandomSeed=workItem.RandomSeed, ...
            VehicleCount=options.VehicleCount, ...
            NLanes=2, ...
            LaneWidth=workItem.LaneWidthMeters, ...
            RoadLength=workItem.RoadLengthMeters, ...
            CentralDividerWidth=0, ...
            MeanVehicleSpeed=30, ...
            VehicleSpeedStandardDeviation=0, ...
            RerollSpeedOnWrapAround=false, ...
            ExitProbability=options.ExitProbability, ...
            MergeDistance=workItem.MergeDistanceMeters)), ...
    Application=struct( ...
        ResourceReservationIntervalSeconds=0.1, ...
        PacketGeneration=struct( ...
            IntervalVariationSeconds=0, ...
            IntervalSeconds=0.1, ...
            RandomComponentMeanSeconds=0)), ...
    Radio=struct( ...
        Type="LteV2X", ...
        LteV2X=struct( ...
            Mcs=7, ...
            AdjacentPscchAndPsschEnabled=true), ...
        Sidelink=struct(MaximumTransmissionCount=1)), ...
    Awareness=struct( ...
        RangesMeters=options.MaximumPrrDistanceMeters), ...
    ResourceAllocation=struct( ...
        Type="MaximumReuseDistance", ...
        RandomSeed=workItem.RandomSeed, ...
        MaximumReuseDistance=struct( ...
            ReassignmentIntervalSeconds=0.1)), ...
    Positioning=struct(Errors={positionErrors}), ...
    Outputs=struct( ...
        PacketReceptionRatio=struct( ...
            Enabled=true, ...
            DistanceBinWidthMeters= ...
                options.PrrDistanceBinWidthMeters), ...
        PositionErrorTrace=struct( ...
            Enabled=true, ...
            FlushRowCount= ...
                options.PositionErrorTraceFlushRowCount), ...
        ControllerDiagnostics=struct( ...
            Enabled=true, ...
            RankDisplacementEnabled=false, ...
            FlushRowCount= ...
                options.ControllerDiagnosticsFlushRowCount), ...
        PacketFateTrace=struct( ...
            Enabled=true, ...
            FlushRowCount= ...
                options.PacketFateTraceFlushRowCount, ...
            FileFormat="parquet"), ...
        InterferenceClassification=struct(Enabled=true), ...
        UpdateDelay=struct(Enabled=false), ...
        PacketDelay=struct(Enabled=false), ...
        DataAge=struct(Enabled=false), ...
        WirelessBlindSpot=struct(Enabled=false), ...
        AverageNeighborCount=struct(Enabled=false), ...
        ChannelBusyRatio=struct(Enabled=false)));
template = v2xsim.config.load(configurationFile);
configuration = template.resolve( ...
    Patch=v2xsim.config.patch(patchData)); %#ok<NASGU>
evalc("v2xsim.runSimulation(configuration," + ...
    "OutputDirectory=workItem.OutputDirectory," + ...
    "RunLabel=workItem.RunLabel);");

mechanisms = ...
    v2xsimregression.positionerror.summarizeRampRun( ...
        workItem.OutputDirectory, ...
        options.MaximumPrrDistanceMeters, ...
        options.PrrDistanceBinWidthMeters, ...
        MaximumExposedShadowCases= ...
            options.MaximumExposedShadowCases, ...
        ExposedShadowEvaluationHorizonSeconds= ...
            options.ExposedShadowEvaluationHorizonSeconds, ...
        MinimumShadowReceiverObservationCount= ...
            options.MinimumShadowReceiverObservationCount, ...
        ExposedShadowSelectionSeed=workItem.RandomSeed);
manifestRow = struct2table(workItem, AsArray=true);
mechanismRow = struct2table(mechanisms, AsArray=true);
result = [manifestRow, mechanismRow];
end

function errors = treatmentErrors(workItem)
switch workItem.Treatment
    case "None"
        errors = cell(0, 1);
    case "GaussianMainline"
        errors = {struct( ...
            Type="Gaussian", ...
            StandardDeviationMeters= ...
                workItem.GaussianAxisStandardDeviationMeters, ...
            DisplacementRandomSeed= ...
                workItem.DisplacementRandomSeed, ...
            AffectedVehicleProbability= ...
                workItem.AffectedVehicleProbability, ...
            SelectionRandomSeed=workItem.SelectionRandomSeed, ...
            ActiveRoutes=["Merge", "Adjacent"])};
    case "GaussianRamp"
        errors = {struct( ...
            Type="Gaussian", ...
            StandardDeviationMeters= ...
                workItem.GaussianAxisStandardDeviationMeters, ...
            DisplacementRandomSeed= ...
                workItem.DisplacementRandomSeed, ...
            AffectedVehicleProbability= ...
                workItem.AffectedVehicleProbability, ...
            SelectionRandomSeed=workItem.SelectionRandomSeed, ...
            ActiveRoutes="Ramp")};
    case "FalseExit"
        errors = {struct( ...
            Type="FalseExit", ...
            AffectedVehicleProbability= ...
                workItem.AffectedVehicleProbability, ...
            ResetAfterSeconds=Inf, ...
            DisplacementScale= ...
                workItem.FalseRouteDisplacementScale, ...
            SelectionRandomSeed=workItem.SelectionRandomSeed)};
    case "FalseMerge"
        errors = {struct( ...
            Type="FalseMerge", ...
            AffectedVehicleProbability= ...
                workItem.AffectedVehicleProbability, ...
            ResetAfterSeconds=Inf, ...
            DisplacementScale= ...
                workItem.FalseRouteDisplacementScale, ...
            SelectionRandomSeed=workItem.SelectionRandomSeed)};
    otherwise
        error( ...
            "v2xsimregression:positionerror:UnknownErrorModel", ...
            "Unknown treatment %s.", workItem.Treatment);
end
end

function validateSimulator(root, configurationFile)
if ~isfolder(root) || ~isfile(configurationFile) || ...
        ~isfile(fullfile( ...
            root, "src", "+v2xsim", "runSimulation.m"))
    error( ...
        "v2xsimregression:positionerror:InvalidSimulatorRoot", ...
        "Simulator root is incomplete: %s", root);
end
end

function prepareCampaignDirectory(outputDirectory)
if isfolder(outputDirectory)
    entries = dir(outputDirectory);
    names = string({entries.name});
    hasContent = any(~ismember(names, [".", ".."]));
    if hasContent
        error( ...
            "v2xsimregression:positionerror:NonemptyCampaignDirectory", ...
            "Campaign output directory must be new or empty: %s", ...
            outputDirectory);
    end
    return
end
[created, message] = mkdir(outputDirectory);
if ~created
    error( ...
        "v2xsimregression:positionerror:" + ...
        "CampaignDirectoryCreationFailed", ...
        "Could not create campaign directory %s: %s", ...
        outputDirectory, message);
end
end

function value = absolutePath(value, baseDirectory)
value = string(value);
if ~isAbsolutePath(value)
    value = fullfile(baseDirectory, value);
end
end

function tf = isAbsolutePath(value)
if ispc
    tf = ~isempty(regexp(value, "^[A-Za-z]:[\\/]", "once")) || ...
        startsWith(value, "\\");
else
    tf = startsWith(value, "/");
end
end

function restoreEnvironment( ...
        originalPath, originalStream, originalStreamState, ...
        originalWarningState)
path(originalPath);
RandStream.setGlobalStream(originalStream);
originalStream.State = originalStreamState;
warning(originalWarningState);
end
