function summary = summarizeRampRun( ...
        runDirectory, maximumDistanceMeters, ...
        distanceBinWidthMeters, options)
%SUMMARIZERAMPRUN Reduce one completed ramp-error run to study metrics.
%   Raw trace files remain the source of truth. This reducer pools packet
%   counts before ratios, scores a fixed distance grid, stratifies packet
%   delivery by whether either endpoint is actively affected, and
%   summarizes controller-visible topology and allocation differences.

arguments (Input)
    runDirectory (1, 1) string {mustBeNonzeroLengthText}
    maximumDistanceMeters (1, 1) double ...
        {mustBeReal, mustBeFinite, mustBePositive}
    distanceBinWidthMeters (1, 1) double ...
        {mustBeReal, mustBeFinite, mustBePositive}
    options.MaximumExposedShadowCases (1, 1) double ...
        {mustBeReal, mustBePositive} = 1000
    options.ExposedShadowEvaluationHorizonSeconds (1, 1) double ...
        {mustBeReal, mustBeFinite, mustBePositive} = 0.1
    options.MinimumShadowReceiverObservationCount (1, 1) double ...
        {mustBeInteger, mustBePositive} = 10
    options.ExposedShadowSelectionSeed (1, 1) double ...
        {mustBeInteger, mustBeNonnegative} = 0
end

arguments (Output)
    summary (1, 1) struct
end

if ~isfolder(runDirectory)
    error( ...
        "v2xsimregression:positionerror:MissingRunDirectory", ...
        "Run directory does not exist: %s", runDirectory);
end
if mod(maximumDistanceMeters, distanceBinWidthMeters) ~= 0
    error( ...
        "v2xsimregression:positionerror:MisalignedPrrGrid", ...
        "Maximum distance must be an integer multiple of bin width.");
end
completionFile = fullfile(runDirectory, "simulation_summary.json");
if ~isfile(completionFile)
    error( ...
        "v2xsimregression:positionerror:IncompleteRun", ...
        "Run has no completion summary: %s", runDirectory);
end
readCompletionSummary(completionFile);

positionTrace = readCsvChunks( ...
    runDirectory, "position_error_trace_*.csv");
lifecycleEvents = compactLifecycleEvents(positionTrace);
[leftCensoredEpisodeCount, rightCensoredEpisodeCount] = ...
    countCensoredLifecycleEpisodes(lifecycleEvents);
writetable( ...
    lifecycleEvents, ...
    fullfile(runDirectory, ...
        "position_error_lifecycle_events.csv"));
distanceGrid = ...
    (distanceBinWidthMeters:distanceBinWidthMeters: ...
        maximumDistanceMeters).';
positionState = buildPositionStateLookup(positionTrace);
[packetReduction, errorFates] = reducePacketFateChunks( ...
    runDirectory, distanceGrid, positionState);
interferenceAttempts = readInterferenceAttemptChunks(runDirectory);
interferenceCounterfactuals = ...
    readInterferenceCounterfactualChunks(runDirectory);
topology = readOptionalTable( ...
    fullfile(runDirectory, "controller_topology.csv"));
allocationSummary = readOptionalTable( ...
    fullfile(runDirectory, "controller_allocation_summary.csv"));
allocationDecision = readOptionalTable( ...
    fullfile(runDirectory, "controller_allocation_decision.csv"));
reuseCandidates = readOptionalTable( ...
    fullfile(runDirectory, "controller_reuse_candidate.csv"));
[shadowManifest, exposedClassificationStatus] = ...
    createShadowManifest( ...
        reuseCandidates, runDirectory, maximumDistanceMeters, ...
        options);
writetable( ...
    shadowManifest, ...
    fullfile( ...
        runDirectory, ...
        "exposed_reuse_shadow_manifest.csv"));

[realizedMean, realizedRms, realizedQ95, activeSampleCount, ...
        moduleSampleCount, activeSampleFraction, ...
        overallMeanMagnitude, selectedVehicleCount, episodeCount, ...
        selectedVehicleCohortKey] = ...
    summarizePositionTrace(positionTrace);
[transmitterActive, receiverActive] = ...
    activeEndpointMasks(errorFates, positionState);
transmitterRoutes = endpointRoutes( ...
    errorFates.TransmitterUeId, ...
    errorFates.FateTimeSeconds, positionState);
receiverRoutes = endpointRoutes( ...
    errorFates.ReceiverUeId, ...
    errorFates.FateTimeSeconds, positionState);
[classifierCandidates, allocatorEvidenceAvailable] = ...
    validClassifierReuseCandidates(reuseCandidates);
[classifiedFates, failureEvidence, failureCoverage] = ...
    v2xsim.analysis.classifyRecordedFailureModes( ...
        errorFates, interferenceAttempts, ...
        interferenceCounterfactuals, ...
        classifierCandidates);
failureEvidence = sparseFailureEvidence(failureEvidence);
failureEvents = buildFailureEvents( ...
    classifiedFates, failureCoverage, ...
    transmitterActive, receiverActive, ...
    transmitterRoutes, receiverRoutes, ...
    allocatorEvidenceAvailable);
terminalRadioFateCount = overallTerminalRadioFateCount( ...
    packetReduction);
failureModeSummary = summarizeFailureModes( ...
    failureEvents, allocatorEvidenceAvailable, ...
    terminalRadioFateCount);
writetable( ...
    failureEvents, ...
    fullfile(runDirectory, "failure_mode_events.csv"));
writetable( ...
    failureEvidence, ...
    fullfile(runDirectory, "failure_mode_evidence.csv"));
writetable( ...
    failureModeSummary, ...
    fullfile(runDirectory, "failure_mode_summary.csv"));
failureMetrics = failureSummaryMetrics( ...
    failureEvents, failureModeSummary, ...
    allocatorEvidenceAvailable, terminalRadioFateCount);

perVehicleMetrics = finalizePerVehicleMetrics( ...
    packetReduction.PerVehicle, positionTrace, distanceGrid);
writetable( ...
    perVehicleMetrics, ...
    fullfile(runDirectory, "per_vehicle_prr.csv"));
allPacketMetrics = packetMetricsFromReduction( ...
    packetReduction, "all", distanceGrid);
statusEffectActiveTransmitterMetrics = packetMetricsFromReduction( ...
    packetReduction, "status_effect_active_transmitter", distanceGrid);
statusEffectActiveReceiverMetrics = packetMetricsFromReduction( ...
    packetReduction, "status_effect_active_receiver", distanceGrid);
eitherEndpointStatusEffectActiveMetrics = packetMetricsFromReduction( ...
    packetReduction, ...
    "either_endpoint_status_effect_active", distanceGrid);
mainlineMetrics = packetMetricsFromReduction( ...
    packetReduction, "mainline_transmitter", distanceGrid);
rampMetrics = packetMetricsFromReduction( ...
    packetReduction, "ramp_transmitter", distanceGrid);
[harmfulCandidateCount, missedCandidateCount, ...
        meanHarmfulCandidateRate, meanMissedCandidateRate, ...
        harmfulInterferenceOverlapCandidateCount, ...
        missedInterferenceOverlapCandidateCount, ...
        meanHarmfulInterferenceOverlapCandidateRate, ...
        meanMissedInterferenceOverlapCandidateRate] = ...
    summarizeReuseCandidates( ...
        reuseCandidates, allocationSummary);

summary = struct( ...
    "RealizedMeanErrorMagnitudeMeters", realizedMean, ...
    "RealizedRmsErrorMagnitudeMeters", realizedRms, ...
    "Realized95PercentileErrorMagnitudeMeters", realizedQ95, ...
    "ActivePositionSampleCount", activeSampleCount, ...
    "PositionModuleSampleCount", moduleSampleCount, ...
    "ActivePositionSampleFraction", activeSampleFraction, ...
    "OverallMeanErrorMagnitudeMeters", overallMeanMagnitude, ...
    "SelectedVehicleCount", selectedVehicleCount, ...
    "SelectedVehicleCohortKey", selectedVehicleCohortKey, ...
    "StatusEffectEpisodeCount", episodeCount, ...
    "LeftCensoredEpisodeCount", leftCensoredEpisodeCount, ...
    "RightCensoredEpisodeCount", rightCensoredEpisodeCount, ...
    "TerminalPacketFateCount", ...
        packetReduction.TerminalPacketFateCount, ...
    "CorrectCount", allPacketMetrics.CorrectCount, ...
    "ErrorCount", allPacketMetrics.ErrorCount, ...
    "BlockedCount", allPacketMetrics.BlockedCount, ...
    "DeliveryPrrAuc", allPacketMetrics.DeliveryPrrAuc, ...
    "RadioPrrAuc", allPacketMetrics.RadioPrrAuc, ...
    "PrrCurveStatus", allPacketMetrics.Status, ...
    "StatusEffectActiveTransmitterDeliveryPrrAuc", ...
        statusEffectActiveTransmitterMetrics.DeliveryPrrAuc, ...
    "StatusEffectActiveTransmitterPrrCurveStatus", ...
        statusEffectActiveTransmitterMetrics.Status, ...
    "StatusEffectActiveReceiverDeliveryPrrAuc", ...
        statusEffectActiveReceiverMetrics.DeliveryPrrAuc, ...
    "StatusEffectActiveReceiverPrrCurveStatus", ...
        statusEffectActiveReceiverMetrics.Status, ...
    "EitherEndpointStatusEffectActiveDeliveryPrrAuc", ...
        eitherEndpointStatusEffectActiveMetrics.DeliveryPrrAuc, ...
    "EitherEndpointStatusEffectActivePrrCurveStatus", ...
        eitherEndpointStatusEffectActiveMetrics.Status, ...
    "MainlineTransmitterDeliveryPrrAuc", ...
        mainlineMetrics.DeliveryPrrAuc, ...
    "MainlineTransmitterPrrCurveStatus", ...
        mainlineMetrics.Status, ...
    "RampTransmitterDeliveryPrrAuc", ...
        rampMetrics.DeliveryPrrAuc, ...
    "RampTransmitterPrrCurveStatus", ...
        rampMetrics.Status, ...
    "MeanNormalizedKendallTauDistance", ...
        meanVariable(topology, ...
            "NormalizedKendallTauDistance"), ...
    "MeanTopKNeighborJaccard", ...
        meanVariable(topology, "TopKNeighborJaccard"), ...
    "MeanResourcePairGraphXorRate", ...
        meanVariable(allocationSummary, ...
            "ResourcePairGraphXorRate"), ...
    "MeanResourcePairGraphJaccard", ...
        meanVariable(allocationSummary, ...
            "ResourcePairGraphJaccard"), ...
    "MeanInterferenceOverlapPairGraphXorRate", ...
        meanVariable(allocationSummary, ...
            "InterferenceOverlapPairGraphXorRate"), ...
    "MeanInterferenceOverlapPairGraphJaccard", ...
        meanVariable(allocationSummary, ...
            "InterferenceOverlapPairGraphJaccard"), ...
    "MeanExactDecisionDisagreementRate", ...
        meanVariable(allocationSummary, ...
            "ExactDecisionDisagreementRate"), ...
    "MeanTrueDistanceRegretMeters", ...
        meanVariable(allocationDecision, ...
            "TrueTimeRegretMeters"), ...
    "HarmfulReuseCandidateCount", harmfulCandidateCount, ...
    "MissedReuseCandidateCount", missedCandidateCount, ...
    "MeanHarmfulReuseCandidateRate", ...
        meanHarmfulCandidateRate, ...
    "MeanMissedReuseCandidateRate", ...
        meanMissedCandidateRate, ...
    "HarmfulInterferenceOverlapCandidateCount", ...
        harmfulInterferenceOverlapCandidateCount, ...
    "MissedInterferenceOverlapCandidateCount", ...
        missedInterferenceOverlapCandidateCount, ...
    "MeanHarmfulInterferenceOverlapCandidateRate", ...
        meanHarmfulInterferenceOverlapCandidateRate, ...
    "MeanMissedInterferenceOverlapCandidateRate", ...
        meanMissedInterferenceOverlapCandidateRate, ...
    "ExposedReuseShadowCaseCount", ...
        height(shadowManifest), ...
    "ExposedTerminalCount", NaN, ...
    "ExposedTerminalClassificationStatus", ...
        exposedClassificationStatus, ...
    "FailureClassificationStatus", ...
        failureMetrics.Status, ...
    "FailureAllocatorEvidenceAvailable", ...
        failureMetrics.AllocatorEvidenceAvailable, ...
    "FailureClassifiedErrorCount", ...
        failureMetrics.ClassifiedErrorCount, ...
    "FailureUnclassifiedErrorCount", ...
        failureMetrics.UnclassifiedErrorCount, ...
    "FailureEvidenceCoveredErrorCount", ...
        failureMetrics.EvidenceCoveredErrorCount, ...
    "FailureEvidenceExhaustiveErrorCount", ...
        failureMetrics.EvidenceExhaustiveErrorCount, ...
    "FailureEvidenceCoverageRate", ...
        failureMetrics.EvidenceCoverageRate, ...
    "FailureEvidenceExhaustiveRate", ...
        failureMetrics.EvidenceExhaustiveRate, ...
    "HiddenTerminalCount", ...
        failureMetrics.HiddenTerminalCount, ...
    "HiddenTerminalRateAmongErrors", ...
        failureMetrics.HiddenTerminalRateAmongErrors, ...
    "StatusEffectActiveTransmitterHiddenTerminalCount", ...
        failureMetrics. ...
            StatusEffectActiveTransmitterHiddenTerminalCount, ...
    "StatusEffectActiveReceiverHiddenTerminalCount", ...
        failureMetrics.StatusEffectActiveReceiverHiddenTerminalCount, ...
    "EitherEndpointStatusEffectActiveErrorCount", ...
        failureMetrics.EitherEndpointStatusEffectActiveErrorCount, ...
    "EitherEndpointStatusEffectActiveHiddenTerminalCount", ...
        failureMetrics. ...
            EitherEndpointStatusEffectActiveHiddenTerminalCount, ...
    "EitherEndpointStatusEffectActiveHiddenTerminalRateAmongErrors", ...
        failureMetrics. ...
            EitherEndpointStatusEffectActiveHiddenTerminalRateAmongErrors, ...
    "HalfDuplexFailureCount", ...
        failureMetrics.HalfDuplexFailureCount, ...
    "CochannelInterferenceFailureCount", ...
        failureMetrics.CochannelInterferenceFailureCount, ...
    "AdjacentChannelInterferenceFailureCount", ...
        failureMetrics.AdjacentChannelInterferenceFailureCount, ...
    "JointInterferenceFailureCount", ...
        failureMetrics.JointInterferenceFailureCount, ...
    "NoiseOrPropagationFailureCount", ...
        failureMetrics.NoiseOrPropagationFailureCount);
summary = addComparableFailureMetrics(summary, failureMetrics);
end

function summary = addComparableFailureMetrics(summary, metrics)
summary.FailureModeRatesAreMutuallyExclusive = false;
summary.HiddenTerminalDefinition = ...
    "IndividuallySufficientAllocatorInducedInterferer";
summary.JointHiddenTerminalAttributionAvailable = false;
summary.FailureInterferenceEvidenceComplete = ...
    metrics.InterferenceEvidenceComplete;
summary.FailureCompositionDenominatorErrorCount = ...
    metrics.CompositionDenominatorErrorCount;
summary.FailureIncidenceDenominatorRadioFateCount = ...
    metrics.IncidenceDenominatorRadioFateCount;
summary.TerminalRadioFateCount = ...
    metrics.IncidenceDenominatorRadioFateCount;
summary.FailureModeCompositionRateStatus = ...
    metrics.ModeCompositionRateStatus;
summary.FailureModeIncidenceRateStatus = ...
    metrics.ModeIncidenceRateStatus;
summary.HiddenTerminalCountStatus = ...
    metrics.HiddenTerminalCountStatus;
summary.HiddenTerminalCompositionRateStatus = ...
    metrics.HiddenTerminalCompositionRateStatus;
summary.HiddenTerminalIncidenceRateStatus = ...
    metrics.HiddenTerminalIncidenceRateStatus;
summary.DetectedHiddenTerminalCount = ...
    metrics.DetectedHiddenTerminalCount;
summary.DetectedHiddenTerminalCompositionRate = ...
    metrics.DetectedHiddenTerminalCompositionRate;
summary.HiddenTerminalCompositionRate = ...
    metrics.HiddenTerminalCompositionRate;
summary.HiddenTerminalIncidenceRate = ...
    metrics.HiddenTerminalIncidenceRate;

prefixes = [ ...
    "HalfDuplexFailure", ...
    "CochannelInterferenceFailure", ...
    "AdjacentChannelInterferenceFailure", ...
    "CrossTechnologyInterferenceFailure", ...
    "MultipleSufficientInterferersFailure", ...
    "JointInterferenceFailure", ...
    "OtherInterferenceFailure", ...
    "NoiseOrPropagationFailure"];
for prefix = prefixes
    for suffix = [ ...
            "Count", "CompositionRate", "IncidenceRate"]
        summary.(prefix + suffix) = ...
            metrics.(prefix + suffix);
    end
    detectedName = "Detected" + prefix + "Count";
    summary.(detectedName) = metrics.(detectedName);
end
end

function [candidates, evidenceAvailable] = ...
        validClassifierReuseCandidates(candidates)
requiredNames = [ ...
    "AllocationEpoch", "NetworkSliceId", ...
    "FirstUeId", "SecondUeId", "CandidateType", ...
    "LiveResourceRelation", "OracleResourceRelation", ...
    "IsHarmfulInterferenceOverlap", ...
    "IsMissedInterferenceOverlap"];
evidenceAvailable = all(ismember( ...
        requiredNames, ...
        string(candidates.Properties.VariableNames)));
if ~evidenceAvailable
    candidates = table();
    return
end
candidates = candidates(:, requiredNames);
for variableName = [ ...
        "NetworkSliceId", "FirstUeId", "SecondUeId", ...
        "CandidateType", "LiveResourceRelation", ...
        "OracleResourceRelation"]
    candidates.(variableName) = ...
        string(candidates.(variableName));
end
for variableName = [ ...
        "IsHarmfulInterferenceOverlap", ...
        "IsMissedInterferenceOverlap"]
    candidates.(variableName) = logicalColumn( ...
        candidates.(variableName), variableName);
end
end

function events = buildFailureEvents( ...
        classified, coverage, transmitterActive, receiverActive, ...
        transmitterRoutes, receiverRoutes, ...
        allocatorEvidenceAvailable)
if height(classified) ~= height(coverage) || ...
        height(classified) ~= numel(transmitterActive) || ...
        height(classified) ~= numel(receiverActive) || ...
        height(classified) ~= numel(transmitterRoutes) || ...
        height(classified) ~= numel(receiverRoutes)
    error( ...
        "v2xsimregression:positionerror:" + ...
        "FailureEvidenceAlignmentMismatch", ...
        "Failure classification, coverage, route, and status-effect " + ...
        "activity " + ...
        "rows must remain aligned.");
end

errorRows = classified.Outcome == "error";
events = classified(errorRows, :);
events.HasAttemptEvidence = ...
    coverage.HasAttemptEvidence(errorRows);
events.EvidenceIsExhaustive = ...
    coverage.EvidenceIsExhaustive(errorRows);
events.CounterfactualCount = ...
    coverage.CounterfactualCount(errorRows);
events.AllocatorEvidenceAvailable = repmat( ...
    allocatorEvidenceAvailable, height(events), 1);
events.TransmitterPositionErrorActive = ...
    transmitterActive(errorRows);
events.ReceiverPositionErrorActive = ...
    receiverActive(errorRows);
events.EitherEndpointPositionErrorActive = ...
    transmitterActive(errorRows) | receiverActive(errorRows);
events.TransmitterTrueRoute = transmitterRoutes(errorRows);
events.ReceiverTrueRoute = receiverRoutes(errorRows);
end

function evidence = sparseFailureEvidence(evidence)
% Raw interference chunks remain authoritative for joint mechanisms.
% This joined convenience artifact retains only rows that are individually
% sufficient to change decoding or are linked to harmful interference
% overlap.
if isempty(evidence)
    return
end
retain = ...
    evidence.SinrWithoutInterfererDb >= ...
        evidence.DecodeThresholdDb | ...
    evidence.IsHarmfulReuseCandidate;
evidence = evidence(retain, :);
end

function count = overallTerminalRadioFateCount(reduction)
allRow = reduction.CategoryNames == "all";
if nnz(allRow) ~= 1
    error( ...
        "v2xsimregression:positionerror:" + ...
        "InvalidPacketReduction", ...
        "Packet reduction must contain one all-fates category.");
end
count = sum( ...
    reduction.CategoryOutcomeCounts(allRow, 1:2));
end

function summary = summarizeFailureModes( ...
        events, allocatorEvidenceAvailable, ...
        terminalRadioFateCount)
modeOrder = [ ...
    "hidden_terminal", "half_duplex", ...
    "cochannel_interference", ...
    "adjacent_channel_interference", ...
    "cross_technology_interference", ...
    "multiple_sufficient_interferers", ...
    "joint_interference", "other_interference", ...
    "noise_or_propagation", ...
    "unclassified_missing_counterfactual", ...
    "unclassified_incomplete_counterfactual"];
primaryModeCount = 9;
errorCount = height(events);
interferenceEvidenceComplete = errorCount == 0 || ...
    all(events.HasAttemptEvidence & ...
        events.EvidenceIsExhaustive);
detectedCount = zeros(numel(modeOrder), 1);
statusEffectActiveTransmitterCount = zeros(numel(modeOrder), 1);
statusEffectActiveReceiverCount = zeros(numel(modeOrder), 1);
eitherEndpointStatusEffectActiveCount = ...
    zeros(numel(modeOrder), 1);
for modeIndex = 1:numel(modeOrder)
    if modeOrder(modeIndex) == "hidden_terminal"
        modeRows = events.IsHiddenTerminal;
    else
        modeRows = events.FailureMode == modeOrder(modeIndex);
    end
    detectedCount(modeIndex) = nnz(modeRows);
    statusEffectActiveTransmitterCount(modeIndex) = nnz( ...
        modeRows & events.TransmitterPositionErrorActive);
    statusEffectActiveReceiverCount(modeIndex) = nnz( ...
        modeRows & events.ReceiverPositionErrorActive);
    eitherEndpointStatusEffectActiveCount(modeIndex) = nnz( ...
        modeRows & events.EitherEndpointPositionErrorActive);
end

observedCompositionRate = divideOrNaN( ...
    detectedCount, repmat(errorCount, numel(modeOrder), 1));
observedIncidenceRate = divideOrNaN( ...
    detectedCount, ...
    repmat(terminalRadioFateCount, numel(modeOrder), 1));
count = detectedCount;
compositionRate = observedCompositionRate;
incidenceRate = observedIncidenceRate;
countStatus = repmat("Descriptive", numel(modeOrder), 1);
compositionRateStatus = countStatus;
incidenceRateStatus = countStatus;
for modeIndex = 1:primaryModeCount
    modeIsHidden = modeOrder(modeIndex) == "hidden_terminal";
    [modeComplete, incompleteStatus] = ...
        modeEvidenceStatus( ...
            modeIsHidden, interferenceEvidenceComplete, ...
            allocatorEvidenceAvailable);
    if ~modeComplete
        count(modeIndex) = NaN;
        compositionRate(modeIndex) = NaN;
        incidenceRate(modeIndex) = NaN;
        countStatus(modeIndex) = incompleteStatus;
        compositionRateStatus(modeIndex) = incompleteStatus;
        incidenceRateStatus(modeIndex) = incompleteStatus;
        continue
    end
    countStatus(modeIndex) = "Analyzable";
    if errorCount == 0
        compositionRate(modeIndex) = NaN;
        compositionRateStatus(modeIndex) = ...
            "NotAnalyzableNoTerminalErrors";
    else
        compositionRateStatus(modeIndex) = "Analyzable";
    end
    if terminalRadioFateCount == 0
        incidenceRate(modeIndex) = NaN;
        incidenceRateStatus(modeIndex) = ...
            "NotAnalyzableNoTerminalRadioFates";
    else
        incidenceRateStatus(modeIndex) = "Analyzable";
    end
end

compositionDenominator = repmat( ...
    errorCount, numel(modeOrder), 1);
incidenceDenominator = repmat( ...
    terminalRadioFateCount, numel(modeOrder), 1);
summary = table( ...
    modeOrder.', detectedCount, count, ...
    observedCompositionRate, compositionRate, ...
    compositionRate, observedIncidenceRate, incidenceRate, ...
    incidenceRate, compositionDenominator, ...
    incidenceDenominator, countStatus, ...
    compositionRateStatus, incidenceRateStatus, ...
    statusEffectActiveTransmitterCount, ...
    statusEffectActiveReceiverCount, ...
    eitherEndpointStatusEffectActiveCount, ...
    repmat(allocatorEvidenceAvailable, numel(modeOrder), 1), ...
    repmat( ...
        interferenceEvidenceComplete, numel(modeOrder), 1), ...
    VariableNames=[ ...
        "FailureMode", "DetectedCount", "Count", ...
        "ObservedCompositionRate", "CompositionRate", ...
        "RateAmongErrors", "ObservedIncidenceRate", ...
        "IncidenceRate", "RateAmongTerminalRadioFates", ...
        "CompositionDenominator", "IncidenceDenominator", ...
        "CountStatus", "CompositionRateStatus", ...
        "IncidenceRateStatus", ...
        "StatusEffectActiveTransmitterCount", ...
        "StatusEffectActiveReceiverCount", ...
        "EitherEndpointStatusEffectActiveCount", ...
        "AllocatorEvidenceAvailable", ...
        "InterferenceEvidenceComplete"]);
end

function [complete, status] = modeEvidenceStatus( ...
        isHidden, interferenceEvidenceComplete, ...
        allocatorEvidenceAvailable)
if isHidden && ~allocatorEvidenceAvailable
    complete = false;
    status = "NotAnalyzableMissingAllocatorEvidence";
elseif ~interferenceEvidenceComplete
    complete = false;
    status = ...
        "NotAnalyzableIncompleteInterferenceEvidence";
else
    complete = true;
    status = "Analyzable";
end
end

function metrics = failureSummaryMetrics( ...
        events, modeSummary, allocatorEvidenceAvailable, ...
        terminalRadioFateCount)
errorCount = height(events);
unclassified = startsWith( ...
    events.FailureMode, "unclassified_");
coveredCount = nnz(events.HasAttemptEvidence);
exhaustiveCount = nnz(events.EvidenceIsExhaustive);
hidden = events.IsHiddenTerminal;
eitherEndpointStatusEffectActive = ...
    events.EitherEndpointPositionErrorActive;
interferenceEvidenceComplete = errorCount == 0 || ...
    all(events.HasAttemptEvidence & ...
        events.EvidenceIsExhaustive);

if errorCount == 0
    status = "NoErrors";
elseif ~allocatorEvidenceAvailable
    status = "IncompleteAllocatorEvidence";
elseif coveredCount == 0
    status = "NoInterferenceEvidence";
elseif exhaustiveCount == errorCount
    status = "Complete";
else
    status = "IncompleteInterferenceEvidence";
end

hiddenCount = modeValue( ...
    modeSummary, "hidden_terminal", "Count");
hiddenDetectedCount = modeValue( ...
    modeSummary, "hidden_terminal", "DetectedCount");
hiddenCompositionRate = modeValue( ...
    modeSummary, "hidden_terminal", "CompositionRate");
hiddenIncidenceRate = modeValue( ...
    modeSummary, "hidden_terminal", "IncidenceRate");
hiddenIsAnalyzable = isfinite(hiddenCount);
generalMode = "half_duplex";
metrics = struct( ...
    "Status", status, ...
    "AllocatorEvidenceAvailable", ...
        allocatorEvidenceAvailable, ...
    "InterferenceEvidenceComplete", ...
        interferenceEvidenceComplete, ...
    "CompositionDenominatorErrorCount", errorCount, ...
    "IncidenceDenominatorRadioFateCount", ...
        terminalRadioFateCount, ...
    "ModeCompositionRateStatus", ...
        modeValue( ...
            modeSummary, generalMode, ...
            "CompositionRateStatus"), ...
    "ModeIncidenceRateStatus", ...
        modeValue( ...
            modeSummary, generalMode, ...
            "IncidenceRateStatus"), ...
    "HiddenTerminalCountStatus", ...
        modeValue( ...
            modeSummary, "hidden_terminal", "CountStatus"), ...
    "HiddenTerminalCompositionRateStatus", ...
        modeValue( ...
            modeSummary, "hidden_terminal", ...
            "CompositionRateStatus"), ...
    "HiddenTerminalIncidenceRateStatus", ...
        modeValue( ...
            modeSummary, "hidden_terminal", ...
            "IncidenceRateStatus"), ...
    "ClassifiedErrorCount", nnz(~unclassified), ...
    "UnclassifiedErrorCount", nnz(unclassified), ...
    "EvidenceCoveredErrorCount", coveredCount, ...
    "EvidenceExhaustiveErrorCount", exhaustiveCount, ...
    "EvidenceCoverageRate", ratioOrNaN(coveredCount, errorCount), ...
    "EvidenceExhaustiveRate", ...
        ratioOrNaN(exhaustiveCount, errorCount), ...
    "DetectedHiddenTerminalCount", hiddenDetectedCount, ...
    "HiddenTerminalCount", hiddenCount, ...
    "DetectedHiddenTerminalCompositionRate", ...
        ratioOrNaN(nnz(hidden), errorCount), ...
    "HiddenTerminalCompositionRate", ...
        hiddenCompositionRate, ...
    "HiddenTerminalRateAmongErrors", ...
        hiddenCompositionRate, ...
    "HiddenTerminalIncidenceRate", ...
        hiddenIncidenceRate, ...
    "StatusEffectActiveTransmitterHiddenTerminalCount", ...
        gateValue( ...
            nnz(hidden & ...
                events.TransmitterPositionErrorActive), ...
            hiddenIsAnalyzable), ...
    "StatusEffectActiveReceiverHiddenTerminalCount", ...
        gateValue( ...
            nnz(hidden & events.ReceiverPositionErrorActive), ...
            hiddenIsAnalyzable), ...
    "EitherEndpointStatusEffectActiveErrorCount", ...
        nnz(eitherEndpointStatusEffectActive), ...
    "EitherEndpointStatusEffectActiveHiddenTerminalCount", ...
        gateValue( ...
            nnz(hidden & eitherEndpointStatusEffectActive), ...
            hiddenIsAnalyzable), ...
    "EitherEndpointStatusEffectActiveHiddenTerminalRateAmongErrors", ...
        gateValue( ...
            ratioOrNaN( ...
                nnz(hidden & eitherEndpointStatusEffectActive), ...
                nnz(eitherEndpointStatusEffectActive)), ...
            hiddenIsAnalyzable));
metrics = addPrimaryModeMetrics( ...
    metrics, modeSummary, "HalfDuplexFailure", ...
    "half_duplex");
metrics = addPrimaryModeMetrics( ...
    metrics, modeSummary, "CochannelInterferenceFailure", ...
    "cochannel_interference");
metrics = addPrimaryModeMetrics( ...
    metrics, modeSummary, "AdjacentChannelInterferenceFailure", ...
    "adjacent_channel_interference");
metrics = addPrimaryModeMetrics( ...
    metrics, modeSummary, "CrossTechnologyInterferenceFailure", ...
    "cross_technology_interference");
metrics = addPrimaryModeMetrics( ...
    metrics, modeSummary, "MultipleSufficientInterferersFailure", ...
    "multiple_sufficient_interferers");
metrics = addPrimaryModeMetrics( ...
    metrics, modeSummary, "JointInterferenceFailure", ...
    "joint_interference");
metrics = addPrimaryModeMetrics( ...
    metrics, modeSummary, "OtherInterferenceFailure", ...
    "other_interference");
metrics = addPrimaryModeMetrics( ...
    metrics, modeSummary, "NoiseOrPropagationFailure", ...
    "noise_or_propagation");
end

function metrics = addPrimaryModeMetrics( ...
        metrics, summary, fieldPrefix, mode)
metrics.("Detected" + fieldPrefix + "Count") = ...
    modeValue(summary, mode, "DetectedCount");
metrics.(fieldPrefix + "Count") = ...
    modeValue(summary, mode, "Count");
metrics.(fieldPrefix + "CompositionRate") = ...
    modeValue(summary, mode, "CompositionRate");
metrics.(fieldPrefix + "IncidenceRate") = ...
    modeValue(summary, mode, "IncidenceRate");
end

function value = modeValue(summary, mode, variableName)
row = summary.FailureMode == mode;
if nnz(row) ~= 1
    error( ...
        "v2xsimregression:positionerror:" + ...
        "InvalidFailureModeSummary", ...
        "Failure-mode summary must contain one %s row.", mode);
end
value = summary.(variableName)(row);
end

function value = gateValue(value, condition)
if ~condition
    value = NaN;
end
end

function value = ratioOrNaN(numerator, denominator)
if denominator == 0
    value = NaN;
else
    value = numerator ./ denominator;
end
end

function [manifest, status] = createShadowManifest( ...
        candidates, runDirectory, maximumDistanceMeters, options)
requiredNames = [ ...
    "SimulationTimeSeconds", "AllocationEpoch", ...
    "NetworkSliceId", "FirstUeId", "SecondUeId", ...
    "CandidateType", "LiveResourceRelation", ...
    "OracleResourceRelation", "LiveFirstResourceId", ...
    "LiveSecondResourceId", "OracleFirstResourceId", ...
    "OracleSecondResourceId"];
actualNames = string(candidates.Properties.VariableNames);
if isempty(candidates) && ...
        all(ismember(requiredNames, actualNames))
    manifest = ...
        v2xsim.analysis.createExposedReuseShadowManifest( ...
            candidates, ...
            SourceRunId=sourceRunId(runDirectory), ...
            MaximumCases= ...
                options.MaximumExposedShadowCases, ...
            SelectionSeed= ...
                options.ExposedShadowSelectionSeed, ...
            EvaluationHorizonSeconds= ...
                options. ...
                    ExposedShadowEvaluationHorizonSeconds, ...
            AnalysisRangeMeters=maximumDistanceMeters, ...
            MinimumReceiverObservationCount= ...
                options. ...
                    MinimumShadowReceiverObservationCount);
    status = "NoMissedReuseCandidates";
    return
end
if any(~ismember(requiredNames, actualNames))
    emptyCandidates = table( ...
        zeros(0, 1), zeros(0, 1), strings(0, 1), ...
        strings(0, 1), strings(0, 1), strings(0, 1), ...
        strings(0, 1), strings(0, 1), ...
        zeros(0, 1), zeros(0, 1), ...
        zeros(0, 1), zeros(0, 1), ...
        VariableNames=requiredNames);
    manifest = ...
        v2xsim.analysis.createExposedReuseShadowManifest( ...
            emptyCandidates, ...
            SourceRunId=sourceRunId(runDirectory), ...
            MaximumCases= ...
                options.MaximumExposedShadowCases, ...
            SelectionSeed= ...
                options.ExposedShadowSelectionSeed, ...
            EvaluationHorizonSeconds= ...
                options. ...
                    ExposedShadowEvaluationHorizonSeconds, ...
            AnalysisRangeMeters=maximumDistanceMeters, ...
            MinimumReceiverObservationCount= ...
                options. ...
                    MinimumShadowReceiverObservationCount);
    status = "CandidateSchemaInsufficient";
    return
end

manifest = ...
    v2xsim.analysis.createExposedReuseShadowManifest( ...
        candidates, ...
        SourceRunId=sourceRunId(runDirectory), ...
        MaximumCases=options.MaximumExposedShadowCases, ...
        SelectionSeed=options.ExposedShadowSelectionSeed, ...
        EvaluationHorizonSeconds= ...
            options.ExposedShadowEvaluationHorizonSeconds, ...
        AnalysisRangeMeters=maximumDistanceMeters, ...
        MinimumReceiverObservationCount= ...
            options.MinimumShadowReceiverObservationCount);
if isempty(manifest)
    status = "NoMissedReuseCandidates";
else
    status = "ShadowRunRequired";
end
end

function identifier = sourceRunId(runDirectory)
summaryFile = fullfile(runDirectory, "simulation_summary.json");
simulationSummary = readCompletionSummary(summaryFile);
if isfield(simulationSummary, "Run") && ...
        isstruct(simulationSummary.Run) && ...
        isfield(simulationSummary.Run, "RunLabel")
    runLabel = strip(string( ...
        simulationSummary.Run.RunLabel));
    if isscalar(runLabel) && ~ismissing(runLabel) && ...
            strlength(runLabel) > 0
        identifier = runLabel;
        return
    end
end

% A schema-v2 summary without a usable label falls back to the stable
% seed/treatment path.
[seedDirectory, treatmentName] = fileparts(runDirectory);
[~, seedName] = fileparts(seedDirectory);
identifier = string(fullfile(seedName, treatmentName));
if strlength(strip(identifier)) == 0
    identifier = string(runDirectory);
end
if strlength(strip(identifier)) == 0
    identifier = "source";
end
end

function summary = readCompletionSummary(filename)
try
    summary = jsondecode(fileread(filename));
catch cause
    error( ...
        "v2xsimregression:positionerror:InvalidCompletionSummary", ...
        "Could not decode completion summary %s: %s", ...
        filename, cause.message);
end

isSupported = isstruct(summary) && isscalar(summary) && ...
    isfield(summary, "SchemaVersion") && ...
    isnumeric(summary.SchemaVersion) && ...
    isscalar(summary.SchemaVersion) && ...
    isfinite(summary.SchemaVersion) && ...
    summary.SchemaVersion == 2;
if ~isSupported
    error( ...
        "v2xsimregression:positionerror:UnsupportedSummarySchema", ...
        "Ramp study runs require simulation-summary schema version 2.");
end
end

function [harmfulCount, missedCount, ...
        meanHarmfulRate, meanMissedRate, ...
        harmfulOverlapCount, missedOverlapCount, ...
        meanHarmfulOverlapRate, meanMissedOverlapRate] = ...
        summarizeReuseCandidates(candidates,allocationSummary)
harmfulCount = 0;
missedCount = 0;
meanHarmfulRate = NaN;
meanMissedRate = NaN;
harmfulOverlapCount = NaN;
missedOverlapCount = NaN;
meanHarmfulOverlapRate = NaN;
meanMissedOverlapRate = NaN;
summaryNames = string( ...
    allocationSummary.Properties.VariableNames);
requiredExactSummaryNames = [ ...
    "HarmfulReuseCandidateCount", ...
    "MissedReuseCandidateCount", ...
    "HarmfulReuseCandidateRate", ...
    "MissedReuseCandidateRate"];
if all(ismember(requiredExactSummaryNames,summaryNames))
    harmfulCount = sum( ...
        allocationSummary.HarmfulReuseCandidateCount);
    missedCount = sum( ...
        allocationSummary.MissedReuseCandidateCount);
    meanHarmfulRate = mean( ...
        allocationSummary.HarmfulReuseCandidateRate, ...
        "omitmissing");
    meanMissedRate = mean( ...
        allocationSummary.MissedReuseCandidateRate, ...
        "omitmissing");
end

requiredOverlapSummaryNames = [ ...
    "HarmfulInterferenceOverlapCandidateCount", ...
    "MissedInterferenceOverlapCandidateCount", ...
    "HarmfulInterferenceOverlapCandidateRate", ...
    "MissedInterferenceOverlapCandidateRate"];
if all(ismember(requiredOverlapSummaryNames,summaryNames))
    harmfulOverlapCount = sum( ...
        allocationSummary. ...
            HarmfulInterferenceOverlapCandidateCount);
    missedOverlapCount = sum( ...
        allocationSummary. ...
            MissedInterferenceOverlapCandidateCount);
    meanHarmfulOverlapRate = mean( ...
        allocationSummary. ...
            HarmfulInterferenceOverlapCandidateRate, ...
        "omitmissing");
    meanMissedOverlapRate = mean( ...
        allocationSummary. ...
            MissedInterferenceOverlapCandidateRate, ...
        "omitmissing");
end

% Compatibility fallback for runs without all-pair summary metrics. Sparse
% candidate rows still support event counts, but not rates because unchanged
% unordered UE pairs are absent from the artifact.
candidateNames = string(candidates.Properties.VariableNames);
if ~all(ismember(requiredExactSummaryNames,summaryNames)) && ...
        ismember("CandidateType",candidateNames)
    candidateType = string(candidates.CandidateType);
    harmfulCount = nnz(candidateType == "harmful_reuse");
    missedCount = nnz(candidateType == "missed_reuse");
end
if ~all(ismember(requiredOverlapSummaryNames,summaryNames)) && ...
        all(ismember( ...
            ["IsHarmfulInterferenceOverlap", ...
                "IsMissedInterferenceOverlap"], ...
            candidateNames))
    harmfulOverlapCount = nnz(logicalColumn( ...
        candidates.IsHarmfulInterferenceOverlap, ...
        "IsHarmfulInterferenceOverlap"));
    missedOverlapCount = nnz(logicalColumn( ...
        candidates.IsMissedInterferenceOverlap, ...
        "IsMissedInterferenceOverlap"));
end
end

function events = compactLifecycleEvents(positionTrace)
canonical = v2xsim.positioning.diagnostics.emptyTable();
traceOutputNames = [ ...
    "SimulationTimeSeconds", "VehicleId", "ModuleIndex", ...
    "ModuleType", "StatusEffectType", "TrueRoute", "EpisodeId", ...
    "IsSelected", "IsActive", "IsEvaluated", ...
    "EvaluationOccurred", "SelectionOccurred", ...
    "ActiveSegmentEntered", "ActiveSegmentExited", ...
    "ResetOccurred", "LeftCensoredAtStart", ...
    "LifecycleEvent"];
outputNames = [ ...
    traceOutputNames(1:end - 1), ...
    "RightCensoredAtEnd", "LifecycleEvent"];
if isempty(positionTrace) && width(positionTrace) == 0
    events = canonical(:, traceOutputNames);
    events.RightCensoredAtEnd = false(0, 1);
    events = events(:, outputNames);
    return
end
actualNames = string(positionTrace.Properties.VariableNames);
if any(~ismember(traceOutputNames, actualNames))
    error( ...
        "v2xsimregression:positionerror:InvalidPositionTrace", ...
        "Position-error trace is missing lifecycle-event columns.");
end
eventRows = ...
    logical(positionTrace.EvaluationOccurred) | ...
    logical(positionTrace.SelectionOccurred) | ...
    logical(positionTrace.ActiveSegmentEntered) | ...
    logical(positionTrace.ActiveSegmentExited) | ...
    logical(positionTrace.ResetOccurred) | ...
    logical(positionTrace.LeftCensoredAtStart);
events = positionTrace(eventRows, traceOutputNames);
events.RightCensoredAtEnd = false(height(events), 1);
events = events(:, outputNames);

rightCensoredEvents = rightCensoredLifecycleEvents( ...
    positionTrace, traceOutputNames, outputNames);
events = [events; rightCensoredEvents];
events.VehicleId = string(events.VehicleId);
events.ModuleType = string(events.ModuleType);
events.StatusEffectType = string(events.StatusEffectType);
events.TrueRoute = string(events.TrueRoute);
events.LifecycleEvent = string(events.LifecycleEvent);
events = sortrows( ...
    events, ["SimulationTimeSeconds", "VehicleId", ...
        "ModuleIndex", "RightCensoredAtEnd"]);
end

function events = rightCensoredLifecycleEvents( ...
        positionTrace, traceOutputNames, outputNames)
events = positionTrace([], traceOutputNames);
events.RightCensoredAtEnd = false(0, 1);
events = events(:, outputNames);

moduleRows = double(positionTrace.ModuleIndex) > 0 & ...
    strlength(string(positionTrace.StatusEffectType)) > 0;
moduleTrace = positionTrace(moduleRows, :);
if isempty(moduleTrace)
    return
end
vehicleIds = string(moduleTrace.VehicleId);
moduleTypes = string(moduleTrace.ModuleType);
statusEffectTypes = string(moduleTrace.StatusEffectType);
[groups, ~, ~, ~, ~] = findgroups( ...
    vehicleIds, double(moduleTrace.ModuleIndex), ...
    moduleTypes, statusEffectTypes);
traceRows = (1:height(moduleTrace)).';
finalRows = splitapply( ...
    @lastObservedRow, traceRows, ...
    double(moduleTrace.SimulationTimeSeconds), groups);
activeAtEnd = logical(moduleTrace.IsActive(finalRows));
hasEpisode = isfinite(double( ...
    moduleTrace.EpisodeId(finalRows)));
finalRows = finalRows(activeAtEnd & hasEpisode);
if isempty(finalRows)
    return
end

events = moduleTrace(finalRows, traceOutputNames);
events.EvaluationOccurred(:) = false;
events.SelectionOccurred(:) = false;
events.ActiveSegmentEntered(:) = false;
events.ActiveSegmentExited(:) = false;
events.ResetOccurred(:) = false;
events.LeftCensoredAtStart(:) = false;
events.LifecycleEvent(:) = "RightCensoredAtEnd";
events.RightCensoredAtEnd = true(height(events), 1);
events = events(:, outputNames);
end

function row = lastObservedRow(rows, times)
maximumTime = max(times);
row = rows(find(times == maximumTime, 1, "last"));
end

function [leftCount, rightCount] = ...
        countCensoredLifecycleEpisodes(events)
leftCount = countLifecycleEpisodes( ...
    events, "LeftCensoredAtStart");
rightCount = countLifecycleEpisodes( ...
    events, "RightCensoredAtEnd");
end

function count = countLifecycleEpisodes(events, flagName)
mask = logical(events.(flagName)) & ...
    double(events.ModuleIndex) > 0 & ...
    strlength(string(events.StatusEffectType)) > 0 & ...
    isfinite(double(events.EpisodeId));
if ~any(mask)
    count = 0;
    return
end
keys = table( ...
    string(events.VehicleId(mask)), ...
    double(events.ModuleIndex(mask)), ...
    string(events.ModuleType(mask)), ...
    string(events.StatusEffectType(mask)), ...
    double(events.EpisodeId(mask)), ...
    VariableNames=[ ...
        "VehicleId", "ModuleIndex", "ModuleType", ...
        "StatusEffectType", "EpisodeId"]);
count = height(unique(keys));
end

function lookup = buildPositionStateLookup(positionTrace)
lookup = struct( ...
    "Active", emptyTemporalState(false), ...
    "Route", emptyTemporalState(""));
names = string(positionTrace.Properties.VariableNames);
if isempty(positionTrace) || ...
        ~all(ismember( ...
            ["SimulationTimeSeconds", "VehicleId"], names))
    return
end
if all(ismember( ...
        ["ModuleIndex", "StatusEffectType", "IsActive"], names))
    moduleRows = positionTrace.ModuleIndex > 0 & ...
        strlength(string(positionTrace.StatusEffectType)) > 0;
    activeRows = aggregateActivePositionRows( ...
        positionTrace(moduleRows, :));
    lookup.Active = buildTemporalState( ...
        activeRows, "IsActive", false);
end
if ismember("TrueRoute", names)
    lookup.Route = buildTemporalState( ...
        positionTrace, "TrueRoute", "");
end
end

function rows = aggregateActivePositionRows(rows)
if isempty(rows)
    return
end
[groups, vehicleIds, simulationTimes] = findgroups( ...
    string(rows.VehicleId), ...
    double(rows.SimulationTimeSeconds));
isActive = splitapply(@any, logical(rows.IsActive), groups);
rows = table( ...
    simulationTimes, vehicleIds, isActive, ...
    VariableNames=[ ...
        "SimulationTimeSeconds", "VehicleId", "IsActive"]);
end

function state = emptyTemporalState(defaultValue)
state = struct( ...
    "VehicleIds", strings(0, 1), ...
    "Times", {cell(0, 1)}, ...
    "Values", {cell(0, 1)}, ...
    "DefaultValue", defaultValue);
end

function state = buildTemporalState(rows, valueName, defaultValue)
state = emptyTemporalState(defaultValue);
if isempty(rows)
    return
end
vehicleIds = string(rows.VehicleId);
[sortedVehicleIds, order] = sort(vehicleIds);
sortedTimes = double(rows.SimulationTimeSeconds(order));
sortedValues = rows.(valueName)(order);
if isstring(defaultValue)
    sortedValues = string(sortedValues);
else
    sortedValues = logical(sortedValues);
end
groupStart = [ ...
    1; find(sortedVehicleIds(2:end) ~= ...
        sortedVehicleIds(1:end - 1)) + 1];
groupEnd = [groupStart(2:end) - 1; numel(order)];
state.VehicleIds = sortedVehicleIds(groupStart);
state.Times = cell(numel(groupStart), 1);
state.Values = cell(numel(groupStart), 1);
for groupIndex = 1:numel(groupStart)
    groupRows = groupStart(groupIndex):groupEnd(groupIndex);
    times = sortedTimes(groupRows);
    values = sortedValues(groupRows);
    [times, retainedRows] = unique(times, "last");
    values = values(retainedRows);
    [times, timeOrder] = sort(times);
    state.Times{groupIndex} = times;
    state.Values{groupIndex} = values(timeOrder);
end
end

function [reduction, errorFates] = reducePacketFateChunks( ...
        runDirectory, distanceGrid, positionState)
parquetFiles = dir(fullfile( ...
    runDirectory, "packet_fates_*.parquet"));
csvFiles = dir(fullfile(runDirectory, "packet_fates_*.csv"));
if ~isempty(parquetFiles) && ~isempty(csvFiles)
    error( ...
        "v2xsimregression:positionerror:MixedPacketTraceFormats", ...
        "A run cannot mix packet-fate CSV and Parquet chunks.");
end

files = parquetFiles;
isParquet = true;
if isempty(files)
    files = csvFiles;
    isParquet = false;
end
files = sortTraceFiles(files);
reduction = initializePacketReduction(numel(distanceGrid));
errorParts = cell(numel(files), 1);
errorPartCount = 0;
for fileIndex = 1:numel(files)
    filename = fullfile( ...
        files(fileIndex).folder, files(fileIndex).name);
    if isParquet
        chunk = parquetread(filename);
    else
        chunk = readtable(filename, TextType="string");
    end
    chunk = coercePacketFateTypes(chunk);
    chunk = ...
        v2xsim.analysis.aggregateTerminalPacketFates(chunk);
    if isempty(chunk)
        continue
    end
    transmitterActive = previousStateAtTimes( ...
        chunk.TransmitterUeId, chunk.FateTimeSeconds, ...
        positionState.Active);
    receiverActive = previousStateAtTimes( ...
        chunk.ReceiverUeId, chunk.FateTimeSeconds, ...
        positionState.Active);
    transmitterRoutes = previousStateAtTimes( ...
        chunk.TransmitterUeId, chunk.FateTimeSeconds, ...
        positionState.Route);
    reduction = accumulatePacketChunk( ...
        reduction, chunk, transmitterActive, receiverActive, ...
        transmitterRoutes, distanceGrid);
    errorRows = chunk.Outcome == "error";
    if any(errorRows)
        errorPartCount = errorPartCount + 1;
        errorParts{errorPartCount} = chunk(errorRows, :);
    end
end

if errorPartCount == 0
    errorFates = ...
        v2xsim.analysis.emptyTerminalPacketFateTable();
else
    errorFates = vertcat(errorParts{1:errorPartCount});
    errorFates = ...
        v2xsim.analysis.aggregateTerminalPacketFates(errorFates);
end
end

function files = sortTraceFiles(files)
if isempty(files)
    return
end
[~, order] = sort(string({files.name}));
files = files(order);
end

function reduction = initializePacketReduction(binCount)
categoryNames = [ ...
    "all"; "status_effect_active_transmitter"; ...
    "status_effect_active_receiver"; ...
    "either_endpoint_status_effect_active"; ...
    "mainline_transmitter"; ...
    "ramp_transmitter"];
categoryCount = numel(categoryNames);
reduction = struct( ...
    "CategoryNames", categoryNames, ...
    "CategoryFateCounts", zeros(categoryCount, 1), ...
    "CategoryOutcomeCounts", zeros(categoryCount, 3), ...
    "CategoryBinOutcomeCounts", ...
        zeros(categoryCount, binCount .* 3), ...
    "TerminalPacketFateCount", 0, ...
    "PerVehicle", initializePerVehicleReduction(binCount));
end

function accumulator = initializePerVehicleReduction(binCount)
accumulator = struct( ...
    "Keys", strings(0, 1), ...
    "Technology", strings(0, 1), ...
    "VehicleUeId", strings(0, 1), ...
    "Perspective", strings(0, 1), ...
    "ExposureState", strings(0, 1), ...
    "FateCount", zeros(0, 1), ...
    "BinOutcomeCounts", zeros(0, binCount .* 3));
end

function reduction = accumulatePacketChunk( ...
        reduction, chunk, transmitterActive, receiverActive, ...
        transmitterRoutes, distanceGrid)
outcomeIndex = packetOutcomeIndex(chunk.Outcome);
binCount = numel(distanceGrid);
binIndex = discretize( ...
    double(chunk.TrueDistanceMeters), ...
    [-Inf; distanceGrid; Inf]);
withinGrid = binIndex <= binCount;
categoryMasks = [ ...
    true(height(chunk), 1), ...
    transmitterActive, receiverActive, ...
    transmitterActive | receiverActive, ...
    ismember(transmitterRoutes, ["Merge", "Adjacent"]), ...
    transmitterRoutes == "Ramp"];
for categoryIndex = 1:width(categoryMasks)
    categoryRows = categoryMasks(:, categoryIndex);
    reduction.CategoryFateCounts(categoryIndex) = ...
        reduction.CategoryFateCounts(categoryIndex) + ...
        nnz(categoryRows);
    if any(categoryRows)
        reduction.CategoryOutcomeCounts(categoryIndex, :) = ...
            reduction.CategoryOutcomeCounts(categoryIndex, :) + ...
            accumarray( ...
                outcomeIndex(categoryRows), 1, [3, 1]).';
    end
    gridRows = categoryRows & withinGrid;
    if any(gridRows)
        binOutcomeColumn = ...
            (outcomeIndex(gridRows) - 1) .* binCount + ...
            binIndex(gridRows);
        reduction.CategoryBinOutcomeCounts( ...
            categoryIndex, :) = ...
            reduction.CategoryBinOutcomeCounts( ...
                categoryIndex, :) + ...
            accumarray( ...
                binOutcomeColumn, 1, ...
                [binCount .* 3, 1]).';
    end
end
reduction.TerminalPacketFateCount = ...
    reduction.TerminalPacketFateCount + height(chunk);
reduction.PerVehicle = accumulatePerVehicleChunk( ...
    reduction.PerVehicle, chunk, transmitterActive, ...
    receiverActive, binIndex, withinGrid, outcomeIndex);
end

function indices = packetOutcomeIndex(outcomes)
outcomes = string(outcomes);
indices = zeros(numel(outcomes), 1);
indices(outcomes == "correct") = 1;
indices(outcomes == "error") = 2;
indices(outcomes == "blocked") = 3;
if any(indices == 0)
    error( ...
        "v2xsimregression:positionerror:InvalidPacketTrace", ...
        "Reduced packet-fate chunks must contain terminal outcomes.");
end
end

function accumulator = accumulatePerVehicleChunk( ...
        accumulator, chunk, transmitterActive, receiverActive, ...
        binIndex, withinGrid, outcomeIndex)
technologies = string(chunk.Technology);
transmitters = string(chunk.TransmitterUeId);
receivers = string(chunk.ReceiverUeId);
seenVehicles = unique( ...
    table( ...
        [technologies; technologies], ...
        [transmitters; receivers], ...
        VariableNames=["Technology", "VehicleUeId"]), ...
    "rows", "stable");
for perspective = ["transmitter", "receiver"]
    [accumulator, ~] = ensurePerVehicleRows( ...
        accumulator, seenVehicles.Technology, ...
        seenVehicles.VehicleUeId, ...
        repmat(perspective, height(seenVehicles), 1), ...
        repmat("all", height(seenVehicles), 1));
end

[accumulator, transmitterRows] = ensurePerVehicleRows( ...
    accumulator, technologies, transmitters, ...
    repmat("transmitter", height(chunk), 1), ...
    repmat("all", height(chunk), 1));
[accumulator, receiverRows] = ensurePerVehicleRows( ...
    accumulator, technologies, receivers, ...
    repmat("receiver", height(chunk), 1), ...
    repmat("all", height(chunk), 1));
accumulator.FateCount = accumulator.FateCount + ...
    accumarray( ...
        [transmitterRows; receiverRows], 1, ...
        [numel(accumulator.Keys), 1]);

if ~any(withinGrid)
    return
end
within = find(withinGrid);
transmitterState = repmat("inactive", numel(within), 1);
transmitterState(transmitterActive(within)) = "active";
receiverState = repmat("inactive", numel(within), 1);
receiverState(receiverActive(within)) = "active";
contributions = table( ...
    [technologies(within); technologies(within); ...
        technologies(within); technologies(within)], ...
    [transmitters(within); receivers(within); ...
        transmitters(within); receivers(within)], ...
    [repmat("transmitter", numel(within), 1); ...
        repmat("receiver", numel(within), 1); ...
        repmat("transmitter", numel(within), 1); ...
        repmat("receiver", numel(within), 1)], ...
    [repmat("all", numel(within), 1); ...
        repmat("all", numel(within), 1); ...
        transmitterState; receiverState], ...
    repmat(binIndex(within), 4, 1), ...
    repmat(outcomeIndex(within), 4, 1), ...
    VariableNames=[ ...
        "Technology", "VehicleUeId", "Perspective", ...
        "ExposureState", "BinIndex", "OutcomeIndex"]);
[groups, groupRows] = findgroups(contributions);
groupCounts = accumarray(groups, 1);
[accumulator, metricRows] = ensurePerVehicleRows( ...
    accumulator, groupRows.Technology, ...
    groupRows.VehicleUeId, groupRows.Perspective, ...
    groupRows.ExposureState);
columnCount = size(accumulator.BinOutcomeCounts, 2);
binCount = columnCount ./ 3;
countColumns = ...
    (groupRows.OutcomeIndex - 1) .* binCount + ...
    groupRows.BinIndex;
linearIndices = sub2ind( ...
    size(accumulator.BinOutcomeCounts), ...
    metricRows, countColumns);
accumulator.BinOutcomeCounts(linearIndices) = ...
    accumulator.BinOutcomeCounts(linearIndices) + ...
    groupCounts;
stateRows = groupRows.ExposureState ~= "all";
if any(stateRows)
    accumulator.FateCount = accumulator.FateCount + ...
        accumarray( ...
            metricRows(stateRows), groupCounts(stateRows), ...
            [numel(accumulator.Keys), 1]);
end
end

function [accumulator, rowIndices] = ensurePerVehicleRows( ...
        accumulator, technology, vehicleUeId, perspective, ...
        exposureState)
technology = string(technology);
vehicleUeId = string(vehicleUeId);
perspective = string(perspective);
exposureState = string(exposureState);
keys = vehicleMetricKeys( ...
    technology, vehicleUeId, perspective, exposureState);
[known, rowIndices] = ismember(keys, accumulator.Keys);
if any(~known)
    newRows = unique( ...
        table( ...
            keys(~known), technology(~known), ...
            vehicleUeId(~known), perspective(~known), ...
            exposureState(~known), ...
            VariableNames=[ ...
                "Key", "Technology", "VehicleUeId", ...
                "Perspective", "ExposureState"]), ...
        "rows", "stable");
    oldCount = numel(accumulator.Keys);
    newCount = height(newRows);
    accumulator.Keys = [accumulator.Keys; newRows.Key];
    accumulator.Technology = [ ...
        accumulator.Technology; newRows.Technology];
    accumulator.VehicleUeId = [ ...
        accumulator.VehicleUeId; newRows.VehicleUeId];
    accumulator.Perspective = [ ...
        accumulator.Perspective; newRows.Perspective];
    accumulator.ExposureState = [ ...
        accumulator.ExposureState; newRows.ExposureState];
    accumulator.FateCount = [ ...
        accumulator.FateCount; zeros(newCount, 1)];
    accumulator.BinOutcomeCounts( ...
        oldCount + (1:newCount), :) = 0;
    [~, rowIndices] = ismember(keys, accumulator.Keys);
end
end

function keys = vehicleMetricKeys( ...
        technology, vehicleUeId, perspective, exposureState)
separator = string(char(31));
keys = technology + separator + vehicleUeId + separator + ...
    perspective + separator + exposureState;
end

function metrics = finalizePerVehicleMetrics( ...
        accumulator, positionTrace, distanceGrid)
rowCount = numel(accumulator.Keys);
binCount = numel(distanceGrid);
correctByBin = accumulator.BinOutcomeCounts(:, 1:binCount);
errorByBin = accumulator.BinOutcomeCounts( ...
    :, binCount + (1:binCount));
blockedByBin = accumulator.BinOutcomeCounts( ...
    :, 2 .* binCount + (1:binCount));
correctCount = sum(correctByBin, 2);
errorCount = sum(errorByBin, 2);
blockedCount = sum(blockedByBin, 2);
totalCount = correctCount + errorCount + blockedCount;
radioAttemptCount = correctCount + errorCount;
deliveryPrr = divideOrNaN(correctCount, totalCount);
radioPrr = divideOrNaN(correctCount, radioAttemptCount);
blockingRate = divideOrNaN(blockedCount, totalCount);
deliveryPrrAuc = nan(rowCount, 1);
radioPrrAuc = nan(rowCount, 1);
deliveryStatus = repmat("NoTerminalFates", rowCount, 1);
radioStatus = deliveryStatus;
nonemptyDeliveryBinCount = nnzByRow( ...
    correctByBin + errorByBin + blockedByBin > 0);
nonemptyRadioBinCount = nnzByRow( ...
    correctByBin + errorByBin > 0);
for rowIndex = 1:rowCount
    if accumulator.FateCount(rowIndex) == 0
        continue
    elseif totalCount(rowIndex) == 0
        deliveryStatus(rowIndex) = ...
            "NoFatesWithinDistanceGrid";
        radioStatus(rowIndex) = ...
            "NoFatesWithinDistanceGrid";
        continue
    end
    [deliveryPrrAuc(rowIndex), deliveryStatus(rowIndex)] = ...
        scoreBinnedCounts( ...
            correctByBin(rowIndex, :), ...
            correctByBin(rowIndex, :) + ...
                errorByBin(rowIndex, :) + ...
                blockedByBin(rowIndex, :), ...
            distanceGrid);
    if radioAttemptCount(rowIndex) == 0
        radioStatus(rowIndex) = "NoRadioAttempts";
    else
        [radioPrrAuc(rowIndex), radioStatus(rowIndex)] = ...
            scoreBinnedCounts( ...
                correctByBin(rowIndex, :), ...
                correctByBin(rowIndex, :) + ...
                    errorByBin(rowIndex, :), ...
                distanceGrid);
    end
end

metrics = table( ...
    accumulator.Technology, accumulator.VehicleUeId, ...
    accumulator.Perspective, accumulator.ExposureState, ...
    repmat(distanceGrid(end), rowCount, 1), ...
    repmat(binCount, rowCount, 1), ...
    nonemptyDeliveryBinCount, nonemptyRadioBinCount, ...
    correctCount, errorCount, blockedCount, totalCount, ...
    radioAttemptCount, deliveryPrr, radioPrr, blockingRate, ...
    deliveryPrrAuc, radioPrrAuc, deliveryStatus, radioStatus, ...
    VariableNames=[ ...
        "Technology", "VehicleUeId", "Perspective", ...
        "ExposureState", "MaximumDistanceMeters", ...
        "DistanceBinCount", "NonemptyDeliveryBinCount", ...
        "NonemptyRadioBinCount", "CorrectCount", ...
        "ErrorCount", "BlockedCount", "TotalCount", ...
        "RadioAttemptCount", "DeliveryPrr", "RadioPrr", ...
        "BlockingRate", "DeliveryPrrAuc", "RadioPrrAuc", ...
        "DeliveryPrrAucStatus", "RadioPrrAucStatus"]);

vehicleLifecycle = summarizeVehicleLifecycle(positionTrace);
[hasLifecycle, lifecycleRows] = ismember( ...
    metrics.VehicleUeId, vehicleLifecycle.VehicleUeId);
metrics.EverSelectedForPositionError = false(height(metrics), 1);
metrics.ActivePositionSampleCount = zeros(height(metrics), 1);
metrics.StatusEffectEpisodeCount = zeros(height(metrics), 1);
metrics.FirstActiveTimeSeconds = nan(height(metrics), 1);
metrics.LastActiveTimeSeconds = nan(height(metrics), 1);
metrics.EverSelectedForPositionError(hasLifecycle) = ...
    vehicleLifecycle.EverSelectedForPositionError( ...
        lifecycleRows(hasLifecycle));
metrics.ActivePositionSampleCount(hasLifecycle) = ...
    vehicleLifecycle.ActivePositionSampleCount( ...
        lifecycleRows(hasLifecycle));
metrics.StatusEffectEpisodeCount(hasLifecycle) = ...
    vehicleLifecycle.StatusEffectEpisodeCount( ...
        lifecycleRows(hasLifecycle));
metrics.FirstActiveTimeSeconds(hasLifecycle) = ...
    vehicleLifecycle.FirstActiveTimeSeconds( ...
        lifecycleRows(hasLifecycle));
metrics.LastActiveTimeSeconds(hasLifecycle) = ...
    vehicleLifecycle.LastActiveTimeSeconds( ...
        lifecycleRows(hasLifecycle));
metrics = sortrows( ...
    metrics, ["Technology", "VehicleUeId", ...
        "Perspective", "ExposureState"]);
end

function counts = nnzByRow(values)
counts = sum(values, 2);
end

function values = divideOrNaN(numerator, denominator)
values = nan(size(numerator));
hasDenominator = denominator > 0;
values(hasDenominator) = ...
    numerator(hasDenominator) ./ denominator(hasDenominator);
end

function [auc, status] = scoreBinnedCounts( ...
        correctCounts, denominatorCounts, distanceGrid)
auc = NaN;
if any(denominatorCounts <= 0)
    status = "IncompleteDistanceGrid";
    return
end
ratios = correctCounts ./ denominatorCounts;
auc = trapz( ...
    [0; distanceGrid], [1; ratios(:)]) ./ distanceGrid(end);
status = "Complete";
end

function lifecycle = summarizeVehicleLifecycle(positionTrace)
lifecycle = table( ...
    strings(0, 1), false(0, 1), zeros(0, 1), ...
    zeros(0, 1), nan(0, 1), nan(0, 1), ...
    VariableNames=[ ...
        "VehicleUeId", "EverSelectedForPositionError", ...
        "ActivePositionSampleCount", "StatusEffectEpisodeCount", ...
        "FirstActiveTimeSeconds", "LastActiveTimeSeconds"]);
requiredNames = [ ...
    "VehicleId", "ModuleIndex", "SimulationTimeSeconds", ...
    "StatusEffectType", "IsSelected", "IsActive", "EpisodeId"];
if isempty(positionTrace) || ...
        any(~ismember( ...
            requiredNames, ...
            string(positionTrace.Properties.VariableNames)))
    return
end

moduleRows = positionTrace.ModuleIndex > 0 & ...
    strlength(string(positionTrace.StatusEffectType)) > 0;
moduleTrace = positionTrace(moduleRows, :);
if isempty(moduleTrace)
    return
end
[vehicleGroups, vehicleIds] = findgroups( ...
    string(moduleTrace.VehicleId));
lifecycle = table( ...
    vehicleIds, ...
    splitapply( ...
        @any, logical(moduleTrace.IsSelected), vehicleGroups), ...
    splitapply( ...
        @sum, logical(moduleTrace.IsActive), vehicleGroups), ...
    splitapply( ...
        @countFiniteModuleEpisodes, ...
        double(moduleTrace.ModuleIndex), ...
        double(moduleTrace.EpisodeId), vehicleGroups), ...
    splitapply( ...
        @minimumActiveTime, ...
        double(moduleTrace.SimulationTimeSeconds), ...
        logical(moduleTrace.IsActive), vehicleGroups), ...
    splitapply( ...
        @maximumActiveTime, ...
        double(moduleTrace.SimulationTimeSeconds), ...
        logical(moduleTrace.IsActive), vehicleGroups), ...
    VariableNames=lifecycle.Properties.VariableNames);
end

function count = countFiniteModuleEpisodes(moduleIndices, episodeIds)
finiteEpisode = isfinite(episodeIds);
if ~any(finiteEpisode)
    count = 0;
    return
end
keys = table( ...
    moduleIndices(finiteEpisode), episodeIds(finiteEpisode), ...
    VariableNames=["ModuleIndex", "EpisodeId"]);
count = height(unique(keys));
end

function value = minimumActiveTime(times, active)
if any(active)
    value = min(times(active));
else
    value = NaN;
end
end

function value = maximumActiveTime(times, active)
if any(active)
    value = max(times(active));
else
    value = NaN;
end
end

function routes = endpointRoutes(vehicleIds, queryTimes, positionState)
routes = previousStateAtTimes( ...
    vehicleIds, queryTimes, positionState.Route);
end

function values = previousStateAtTimes( ...
        vehicleIds, queryTimes, temporalState)
rowCount = numel(vehicleIds);
if isstring(temporalState.DefaultValue)
    values = repmat(temporalState.DefaultValue, rowCount, 1);
else
    values = repmat( ...
        logical(temporalState.DefaultValue), rowCount, 1);
end
if rowCount == 0 || isempty(temporalState.VehicleIds)
    return
end
[knownVehicles, stateRows] = ismember( ...
    string(vehicleIds), temporalState.VehicleIds);
for stateRow = unique(stateRows(knownVehicles)).'
    queryRows = stateRows == stateRow;
    times = temporalState.Times{stateRow};
    stateValues = temporalState.Values{stateRow};
    bins = discretize( ...
        double(queryTimes(queryRows)), ...
        [-Inf; times; Inf]);
    previousRows = bins - 1;
    matched = previousRows >= 1 & ...
        previousRows <= numel(times);
    queryValues = repmat( ...
        temporalState.DefaultValue, nnz(queryRows), 1);
    queryValues(matched) = stateValues(previousRows(matched));
    values(queryRows) = queryValues;
end
end

function rows = readCsvChunks(runDirectory, pattern)
files = sortTraceFiles(dir(fullfile(runDirectory, pattern)));
rows = table();
if isempty(files)
    return
end
parts = cell(numel(files), 1);
for fileIndex = 1:numel(files)
    parts{fileIndex} = readtable( ...
        fullfile(files(fileIndex).folder, files(fileIndex).name), ...
        TextType="string");
end
rows = vertcat(parts{:});
end

function rows = readInterferenceAttemptChunks(runDirectory)
rows = v2xsim.analysis.emptyInterferenceAttemptTrace();
rawRows = readCsvChunks( ...
    runDirectory, "interference_attempts_*.csv");
if isempty(rawRows) && width(rawRows) == 0
    return
end
rows = coerceInterferenceTraceTypes( ...
    rawRows, rows, ...
    ["Technology", "TransmitterUeId", ...
        "ReceiverUeId", "Outcome"], ...
    ["PacketSequenceAligned", "EvidenceIsExhaustive"]);
end

function rows = readInterferenceCounterfactualChunks(runDirectory)
rows = ...
    v2xsim.analysis.emptyInterferenceCounterfactualTrace();
rawRows = readCsvChunks( ...
    runDirectory, "interference_counterfactuals_*.csv");
if isempty(rawRows) && width(rawRows) == 0
    return
end
rows = coerceInterferenceTraceTypes( ...
    rawRows, rows, ...
    ["Technology", "TransmitterUeId", ...
        "ReceiverUeId", "InterfererUeId", ...
        "ReusePairFirstUeId", "ReusePairSecondUeId", ...
        "ResourceRelation"], ...
    ["PacketSequenceAligned", "EvidenceIsExhaustive"]);
end

function rows = coerceInterferenceTraceTypes( ...
        rows, expected, stringNames, logicalNames)
expectedNames = string(expected.Properties.VariableNames);
if ~isequal( ...
        string(rows.Properties.VariableNames), expectedNames)
    error( ...
        "v2xsimregression:positionerror:" + ...
        "InvalidInterferenceEvidenceTrace", ...
        "An interference-evidence trace has an unexpected schema.");
end
for variableName = stringNames
    rows.(variableName) = string(rows.(variableName));
end
for variableName = logicalNames
    rows.(variableName) = logicalColumn( ...
        rows.(variableName), variableName);
end
end

function values = logicalColumn(values, variableName)
if islogical(values)
    return
end
if isnumeric(values)
    if any(~ismember(values, [0, 1]))
        error( ...
            "v2xsimregression:positionerror:" + ...
            "InvalidInterferenceEvidenceTrace", ...
            "%s must contain logical values.", variableName);
    end
    values = logical(values);
    return
end
values = lower(string(values));
if any(~ismember(values, ["true", "false", "1", "0"]))
    error( ...
        "v2xsimregression:positionerror:" + ...
        "InvalidInterferenceEvidenceTrace", ...
        "%s must contain logical values.", variableName);
end
values = values == "true" | values == "1";
end

function rows = coercePacketFateTypes(rows)
expectedNames = string( ...
    v2xsim.analysis.emptyTerminalPacketFateTable(). ...
        Properties.VariableNames);
if ~isequal(string(rows.Properties.VariableNames), expectedNames)
    error( ...
        "v2xsimregression:positionerror:InvalidPacketTrace", ...
        "Packet-fate trace has an unexpected schema.");
end
for variableName = [ ...
        "Technology", "TransmitterUeId", ...
        "ReceiverUeId", "Outcome"]
    rows.(variableName) = string(rows.(variableName));
end
end

function rows = readOptionalTable(filename)
if isfile(filename)
    rows = readtable(filename, TextType="string");
else
    rows = table();
end
end

function [meanMagnitude, rmsMagnitude, q95Magnitude, sampleCount, ...
        moduleSampleCount, activeSampleFraction, ...
        overallMeanMagnitude, selectedVehicleCount, episodeCount, ...
        selectedVehicleCohortKey] = ...
        summarizePositionTrace(positionTrace)
if isempty(positionTrace)
    [meanMagnitude, rmsMagnitude, q95Magnitude] = deal(NaN);
    [sampleCount, moduleSampleCount, selectedVehicleCount, ...
        episodeCount] = deal(0);
    activeSampleFraction = 0;
    overallMeanMagnitude = 0;
    selectedVehicleCohortKey = "";
    return
end
requiredNames = [ ...
    "VehicleId", "ModuleIndex", "DisplacementMagnitudeMeters", ...
    "StatusEffectType", "IsSelected", "IsActive", "EpisodeId"];
if any(~ismember( ...
        requiredNames, ...
        string(positionTrace.Properties.VariableNames)))
    error( ...
        "v2xsimregression:positionerror:InvalidPositionTrace", ...
        "Position-error trace is missing required columns.");
end

moduleRows = positionTrace.ModuleIndex > 0 & ...
    strlength(string(positionTrace.StatusEffectType)) > 0;
active = logical(positionTrace.IsActive) & moduleRows;
magnitudes = double( ...
    positionTrace.DisplacementMagnitudeMeters(active));
sampleCount = numel(magnitudes);
moduleSampleCount = nnz(moduleRows);
if moduleSampleCount == 0
    activeSampleFraction = 0;
    overallMeanMagnitude = 0;
else
    activeSampleFraction = sampleCount ./ moduleSampleCount;
    overallMeanMagnitude = mean(double( ...
        positionTrace. ...
            DisplacementMagnitudeMeters(moduleRows)));
end
if isempty(magnitudes)
    meanMagnitude = 0;
    rmsMagnitude = 0;
    q95Magnitude = 0;
else
    meanMagnitude = mean(magnitudes);
    rmsMagnitude = sqrt(mean(magnitudes .^ 2));
    q95Magnitude = linearQuantile(magnitudes, 0.95);
end
selectedVehicleIds = sort(unique(string( ...
    positionTrace.VehicleId( ...
        logical(positionTrace.IsSelected) & ...
        moduleRows))));
selectedVehicleCount = numel(selectedVehicleIds);
selectedVehicleCohortKey = strjoin(selectedVehicleIds, "|");
episodeRows = isfinite(double(positionTrace.EpisodeId)) & ...
    moduleRows;
if ~any(episodeRows)
    episodeCount = 0;
else
    episodeKeys = table( ...
        string(positionTrace.VehicleId(episodeRows)), ...
        double(positionTrace.ModuleIndex(episodeRows)), ...
        string(positionTrace.StatusEffectType(episodeRows)), ...
        double(positionTrace.EpisodeId(episodeRows)), ...
        VariableNames=[ ...
            "VehicleId", "ModuleIndex", ...
            "StatusEffectType", "EpisodeId"]);
    episodeCount = height(unique(episodeKeys));
end
end

function [transmitterActive, receiverActive] = ...
        activeEndpointMasks(fates, positionState)
transmitterActive = previousStateAtTimes( ...
    fates.TransmitterUeId, fates.FateTimeSeconds, ...
    positionState.Active);
receiverActive = previousStateAtTimes( ...
    fates.ReceiverUeId, fates.FateTimeSeconds, ...
    positionState.Active);
end

function metrics = packetMetricsFromReduction( ...
        reduction, categoryName, distanceGrid)
categoryRow = find( ...
    reduction.CategoryNames == categoryName, 1);
if isempty(categoryRow)
    error( ...
        "v2xsimregression:positionerror:" + ...
        "UnknownPacketMetricCategory", ...
        "Unknown packet reduction category: %s.", categoryName);
end
outcomeCounts = ...
    reduction.CategoryOutcomeCounts(categoryRow, :);
metrics = struct( ...
    "CorrectCount", outcomeCounts(1), ...
    "ErrorCount", outcomeCounts(2), ...
    "BlockedCount", outcomeCounts(3), ...
    "DeliveryPrrAuc", NaN, ...
    "RadioPrrAuc", NaN, ...
    "Status", "Incomplete");
if reduction.CategoryFateCounts(categoryRow) == 0
    metrics.Status = "NoTerminalFates";
    return
end

binCount = numel(distanceGrid);
counts = reduction.CategoryBinOutcomeCounts(categoryRow, :);
correctCounts = counts(1:binCount);
errorCounts = counts(binCount + (1:binCount));
blockedCounts = counts(2 .* binCount + (1:binCount));
[metrics.DeliveryPrrAuc, deliveryStatus] = ...
    scoreBinnedCounts( ...
        correctCounts, ...
        correctCounts + errorCounts + blockedCounts, ...
        distanceGrid);
if deliveryStatus == "Complete"
    metrics.Status = "Complete";
end
[metrics.RadioPrrAuc, ~] = scoreBinnedCounts( ...
    correctCounts, correctCounts + errorCounts, distanceGrid);
end

function value = meanVariable(rows, variableName)
if isempty(rows) || ...
        ~ismember(variableName, ...
            string(rows.Properties.VariableNames))
    value = NaN;
    return
end
values = double(rows.(variableName));
values = values(isfinite(values));
if isempty(values)
    value = NaN;
else
    value = mean(values);
end
end

function value = linearQuantile(values, probability)
values = sort(values(:));
if isscalar(values)
    value = values;
    return
end
position = 1 + (numel(values) - 1) .* probability;
lowerIndex = floor(position);
upperIndex = ceil(position);
weight = position - lowerIndex;
value = values(lowerIndex) .* (1 - weight) + ...
    values(upperIndex) .* weight;
end
