classdef Operations
    %OPERATIONS Pure implementation helpers for the configuration package.

    methods (Static)
        function result = emptyProvenance()
            result = table( ...
                strings(0, 1), strings(0, 1), ...
                VariableNames=["Path", "Source"]);
        end

        function validateProvenance(value)
            expectedNames = ["Path", "Source"];
            if ~isequal( ...
                    string(value.Properties.VariableNames), expectedNames) || ...
                    ~isstring(value.Path) || ~isstring(value.Source) || ...
                    size(value.Path, 2) ~= 1 || size(value.Source, 2) ~= 1 || ...
                    height(value) ~= numel(unique(value.Path)) || ...
                    any(ismissing(value.Path) | ...
                        strlength(strip(value.Path)) == 0) || ...
                    any(ismissing(value.Source) | ...
                        strlength(strip(value.Source)) == 0)
                error( ...
                    "v2xsim:config:InvalidProvenance", ...
                    "Provenance must contain unique, nonblank string " + ...
                    "Path and Source columns.");
            end
        end

        function validateProvenanceForData(value, data)
            arguments (Input)
                value table
                data (1, 1) struct
            end

            v2xsim.config.internal.Operations.validateProvenance(value);
            expectedPaths = sort( ...
                v2xsim.config.internal.Operations.leafPaths(data, ""));
            actualPaths = sort(value.Path);
            if ~isequal(actualPaths, expectedPaths)
                error( ...
                    "v2xsim:config:InvalidProvenance", ...
                    "Provenance paths must match the configuration " + ...
                    "data leaves exactly.");
            end
        end

        function result = provenanceForData(data, source)
            arguments (Input)
                data (1, 1) struct
                source (1, 1) string {mustBeNonzeroLengthText}
            end

            paths = ...
                v2xsim.config.internal.Operations.leafPaths(data, "");
            result = table( ...
                paths, repmat(source, numel(paths), 1), ...
                VariableNames=["Path", "Source"]);
        end

        function result = fromToml(value)
            %FROMTOML Preserve exact keys while normalizing parser types.
            if isa(value, "containers.Map")
                result = struct();
                keys = string(value.keys);
                for index = 1:numel(keys)
                    key = keys(index);
                    if ~isvarname(key)
                        error( ...
                            "v2xsim:config:UnknownKey", ...
                            "TOML key ""%s"" is not a valid V7 schema name.", ...
                            key);
                    end
                    result.(key) = ...
                        v2xsim.config.internal.Operations.fromToml( ...
                            value(char(key)));
                end
            elseif iscell(value)
                if all(cellfun(@(item) ischar(item) || ...
                        (isstring(item) && isscalar(item)), value), "all")
                    result = reshape(string(value), size(value));
                elseif all(cellfun(@(item) ...
                        isnumeric(item) && isscalar(item) && ...
                        isreal(item), value), "all")
                    numericValues = cellfun(@double, value);
                    result = reshape(numericValues, size(value));
                else
                    result = cell(size(value));
                    for index = 1:numel(value)
                        result{index} = ...
                            v2xsim.config.internal.Operations.fromToml( ...
                                value{index});
                    end
                end
            elseif ischar(value)
                result = string(value);
            elseif isinteger(value)
                if any(abs(double(value)) > flintmax, "all")
                    error( ...
                        "v2xsim:config:IntegerOutOfRange", ...
                        "A TOML integer exceeds MATLAB's exact double range.");
                end
                if isscalar(value)
                    % Preserve scalar TOML integer identity until schema
                    % validation; resolution normalizes accepted numerics.
                    result = value;
                else
                    result = double(value);
                end
            else
                result = value;
            end
        end

        function validateKnownStructure(data, schema, sourceName)
            arguments (Input)
                data (1, 1) struct
                schema (1, 1) struct
                sourceName (1, 1) string
            end
            v2xsim.config.internal.Operations.validateNode( ...
                data, schema, "", false, sourceName);
        end

        function validateAuthoredActivity(data, schema)
            arguments (Input)
                data (1, 1) struct
                schema (1, 1) struct
            end

            % Coexistence is a top-level domain for runtime compatibility,
            % but is semantically selected by Radio.Type.
            if isfield(data, "Coexistence")
                radioType = "LteV2X";
                if isfield(data, "Radio") && ...
                        isfield(data.Radio, "Type")
                    radioType = string(data.Radio.Type);
                end
                if radioType ~= "Coexistence"
                    error( ...
                        "v2xsim:config:InactiveKey", ...
                        "Key ""Coexistence"" is inactive unless " + ...
                        "Radio.Type is ""Coexistence"".");
                end
                interferenceModel = "Independent";
                if isfield(data, "Radio") && ...
                        isfield(data.Radio, "Coexistence") && ...
                        isfield( ...
                            data.Radio.Coexistence, "InterferenceModel")
                    interferenceModel = string( ...
                        data.Radio.Coexistence.InterferenceModel);
                end
                if interferenceModel == "Independent"
                    inactiveNames = setdiff( ...
                        string(fieldnames(data.Coexistence)), ...
                        "VehiclePattern", "stable");
                    if ~isempty(inactiveNames)
                        error( ...
                            "v2xsim:config:InactiveKey", ...
                            "Coexistence.%s is inactive for independent " + ...
                            "interference.", inactiveNames(1));
                    end
                end
            end
            v2xsim.config.internal.Operations.validateNode( ...
                data, schema, "", true, "Configuration");
        end

        function result = deepMerge(base, overlay)
            arguments (Input)
                base (1, 1) struct
                overlay (1, 1) struct
            end
            result = v2xsim.config.internal.Operations.mergeNode( ...
                base, overlay, v2xsim.config.schema(), "");
        end

        function result = mergeProvenance(base, overlay)
            arguments (Input)
                base table
                overlay table
            end
            v2xsim.config.internal.Operations.validateProvenance(base);
            v2xsim.config.internal.Operations.validateProvenance(overlay);
            if isempty(overlay)
                result = base;
                return
            end
            result = base(~ismember(base.Path, overlay.Path), :);
            result = [result; overlay];
        end

        function result = retainProvenanceForData(provenance, data)
            paths = v2xsim.config.internal.Operations.leafPaths(data, "");
            result = provenance(ismember(provenance.Path, paths), :);
        end

        function result = overlayProvenance(base, overlay)
            result = ...
                v2xsim.config.internal.Operations.mergeProvenance( ...
                    base, overlay);
        end

        function result = markSources(provenance, paths, source)
            arguments (Input)
                provenance table
                paths string
                source (1, 1) string
            end
            result = provenance;
            result.Source(ismember(result.Path, paths)) = source;
        end

        function result = applyDefaults(data, schema)
            arguments (Input)
                data (1, 1) struct
                schema (1, 1) struct
            end
            result = v2xsim.config.internal.Operations.applyNode( ...
                data, schema, "");
        end

        function result = applyDerivedDefaults(data, authored)
            result = data;
            masterSeed = result.Simulation.RandomSeed;

            scenarioBranch = result.Scenario.Type;
            scenarioSeedPath = ...
                "Scenario." + scenarioBranch + ".RandomSeed";
            if ~v2xsim.config.internal.Operations.hasPath( ...
                    authored, scenarioSeedPath)
                result.Scenario.(scenarioBranch).RandomSeed = masterSeed;
            end
            if ~v2xsim.config.internal.Operations.hasPath( ...
                    authored, "ResourceAllocation.RandomSeed")
                result.ResourceAllocation.RandomSeed = masterSeed;
            end
            if ~v2xsim.config.internal.Operations.hasPath( ...
                    authored, ...
                    "Application.PacketGeneration.IntervalSeconds")
                result.Application.PacketGeneration.IntervalSeconds = ...
                    result.Application.ResourceReservationIntervalSeconds;
            end

            interval = result.Application.ResourceReservationIntervalSeconds;
            allocationType = result.ResourceAllocation.Type;
            allocation = result.ResourceAllocation.(allocationType);
            intervalFields = [ ...
                "PositionUpdateIntervalSeconds", ...
                "ReassignmentIntervalSeconds"];
            for field = intervalFields
                path = "ResourceAllocation." + allocationType + "." + field;
                if isfield(allocation, field) && ...
                        ~v2xsim.config.internal.Operations.hasPath( ...
                            authored, path)
                    allocation.(field) = interval;
                end
            end
            result.ResourceAllocation.(allocationType) = allocation;

            if allocationType == "SensingBased"
                sensing = result.ResourceAllocation.SensingBased;
                if ~v2xsim.config.internal.Operations.hasPath( ...
                        authored, ...
                        "ResourceAllocation.SensingBased.L2CandidateFraction")
                    sensing.L2CandidateFraction = ...
                        sensing.MinimumCandidateFraction;
                end
                isNr = result.Radio.Type == "NrV2X" || ...
                    (result.Radio.Type == "Coexistence" && ...
                     result.Radio.Coexistence.SidelinkType == "NrV2X");
                if ~v2xsim.config.internal.Operations.hasPath( ...
                        authored, ...
                        "ResourceAllocation.SensingBased.L2RankingEnabled")
                    sensing.L2RankingEnabled = ~isNr;
                end
                if ~v2xsim.config.internal.Operations.hasPath( ...
                        authored, ...
                        "ResourceAllocation.SensingBased.AverageSensingEnabled")
                    sensing.AverageSensingEnabled = ~isNr;
                end
                if ~v2xsim.config.internal.Operations.hasPath( ...
                        authored, ...
                        "ResourceAllocation.SensingBased." + ...
                        "SelectionWindowStartMilliseconds")
                    if isNr && ...
                            result.Radio.NrV2X. ...
                                SubcarrierSpacingKilohertz > 15
                        sensing.SelectionWindowStartMilliseconds = 0.5;
                    else
                        sensing.SelectionWindowStartMilliseconds = 1;
                    end
                end
                result.ResourceAllocation.SensingBased = sensing;
            elseif allocationType == "Random" && ...
                    ~v2xsim.config.internal.Operations.hasPath( ...
                        authored, ...
                        "ResourceAllocation.Random." + ...
                        "SelectionWindowStartMilliseconds")
                result.ResourceAllocation.Random. ...
                    SelectionWindowStartMilliseconds = 1;
            end

            if result.Radio.Type ~= "Coexistence"
                result.Coexistence = struct();
            end

            if isfield(result.Positioning, "Errors")
                errors = result.Positioning.Errors;
                authoredErrors = {};
                if v2xsim.config.internal.Operations.hasPath( ...
                        authored, "Positioning.Errors")
                    authoredErrors = authored.Positioning.Errors;
                end
                for index = 1:numel(errors)
                    errorData = errors{index};
                    authoredError = struct();
                    if index <= numel(authoredErrors)
                        authoredError = authoredErrors{index};
                    end
                    if errorData.Type == "Gaussian"
                        if ~isfield(authoredError, "DisplacementRandomSeed")
                            errorData.DisplacementRandomSeed = ...
                                v2xsim.config.internal.Operations ...
                                .saltedSeed(masterSeed, 104729);
                        end
                        if ~isfield(authoredError, "SelectionRandomSeed")
                            errorData.SelectionRandomSeed = ...
                                v2xsim.config.internal.Operations ...
                                .saltedSeed(masterSeed, 130363);
                        end
                    elseif ismember( ...
                            errorData.Type, ["FalseExit", "FalseMerge"]) && ...
                            ~isfield(authoredError, "SelectionRandomSeed")
                        salt = 155921;
                        if errorData.Type == "FalseMerge"
                            salt = 180503;
                        end
                        errorData.SelectionRandomSeed = ...
                            v2xsim.config.internal.Operations ...
                            .saltedSeed(masterSeed, salt);
                    end
                    errors{index} = errorData;
                end
                result.Positioning.Errors = errors;
            end
        end

        function result = derivedDefaultPaths(data, authored)
            allPaths = ...
                v2xsim.config.internal.Operations.leafPaths(data, "");
            authoredPaths = ...
                v2xsim.config.internal.Operations.leafPaths(authored, "");
            result = strings(0, 1);
            candidates = [ ...
                "ResourceAllocation.RandomSeed"; ...
                "Application.PacketGeneration.IntervalSeconds"];
            scenarioType = data.Scenario.Type;
            candidates(end + 1) = ...
                "Scenario." + scenarioType + ".RandomSeed";
            allocationType = data.ResourceAllocation.Type;
            allocationPath = "ResourceAllocation." + allocationType + ".";
            allocation = data.ResourceAllocation.(allocationType);
            for field = [ ...
                    "PositionUpdateIntervalSeconds", ...
                    "ReassignmentIntervalSeconds"]
                if isfield(allocation, field)
                    candidates(end + 1) = allocationPath + field; %#ok<AGROW>
                end
            end
            if data.ResourceAllocation.Type == "SensingBased"
                candidates = [candidates; ...
                    "ResourceAllocation.SensingBased.L2CandidateFraction"; ...
                    "ResourceAllocation.SensingBased.L2RankingEnabled"; ...
                    "ResourceAllocation.SensingBased.AverageSensingEnabled"; ...
                    "ResourceAllocation.SensingBased." + ...
                        "SelectionWindowStartMilliseconds"];
            elseif data.ResourceAllocation.Type == "Random"
                candidates(end + 1) = ...
                    "ResourceAllocation.Random." + ...
                    "SelectionWindowStartMilliseconds";
            end
            if isfield(data.Positioning, "Errors")
                errors = data.Positioning.Errors;
                for index = 1:numel(errors)
                    errorPath = "Positioning.Errors(" + index + ").";
                    if errors{index}.Type == "Gaussian"
                        candidates(end + 1) = ...
                            errorPath + "DisplacementRandomSeed"; %#ok<AGROW>
                        candidates(end + 1) = ...
                            errorPath + "SelectionRandomSeed"; %#ok<AGROW>
                    elseif ismember( ...
                            errors{index}.Type, ["FalseExit", "FalseMerge"])
                        candidates(end + 1) = ...
                            errorPath + "SelectionRandomSeed"; %#ok<AGROW>
                    end
                end
            end
            for path = candidates.'
                if ismember(path, allPaths) && ...
                        ~ismember(path, authoredPaths)
                    result(end + 1, 1) = path; %#ok<AGROW>
                end
            end
        end

        function validateResolved(data, schema)
            v2xsim.config.internal.Operations.validateCompleteness( ...
                data, schema, "");
            v2xsim.config.internal.Operations.validateNode( ...
                data, schema, "", true, "Resolved configuration");
            v2xsim.config.internal.Operations.validateCrossFields(data);
        end
    end

    methods (Static, Access = private)
        function result = mergeNode(base, overlay, node, path)
            if ~isstruct(base) || ~isstruct(overlay) || ...
                    ~isscalar(base) || ~isscalar(overlay) || ...
                    node.Kind ~= "table"
                result = overlay;
                return
            end

            result = base;

            % Coexistence is selected by a discriminator in the Radio
            % domain even though its settings occupy a root-level table.
            if path == "" && isfield(overlay, "Radio") && ...
                    isfield(overlay.Radio, "Type")
                oldRadioType = "LteV2X";
                if isfield(base, "Radio") && ...
                        isfield(base.Radio, "Type")
                    oldRadioType = string(base.Radio.Type);
                end
                newRadioType = string(overlay.Radio.Type);
                if oldRadioType == "Coexistence" && ...
                        newRadioType ~= "Coexistence" && ...
                        isfield(result, "Coexistence")
                    result = rmfield(result, "Coexistence");
                end
            end
            if path == "" && isfield(overlay, "Radio") && ...
                    isfield(overlay.Radio, "Coexistence") && ...
                    isfield( ...
                        overlay.Radio.Coexistence, "InterferenceModel") && ...
                    string(overlay.Radio.Coexistence.InterferenceModel) == ...
                        "Independent" && ...
                    isfield(result, "Coexistence")
                inactiveNames = setdiff( ...
                    string(fieldnames(result.Coexistence)), ...
                    "VehiclePattern", "stable");
                if ~isempty(inactiveNames)
                    result.Coexistence = rmfield( ...
                        result.Coexistence, cellstr(inactiveNames));
                end
            end

            selector = node.Selector;
            if strlength(selector) > 0 && isfield(overlay, selector)
                oldValue = "";
                if isfield(base, selector)
                    oldValue = string(base.(selector));
                end
                newValue = string(overlay.(selector));
                if oldValue ~= newValue
                    branchNames = node.BranchChildren;
                    if path == "Radio"
                        cellularTypes = ...
                            ["LteV2X", "NrV2X", "Coexistence"];
                        sharedSidelinkRemainsActive = ...
                            ismember(oldValue, cellularTypes) && ...
                            ismember(newValue, cellularTypes);
                        if ~sharedSidelinkRemainsActive
                            branchNames(end + 1) = "Sidelink";
                        end
                    end
                    for branch = branchNames.'
                        if strlength(branch) > 0 && isfield(result, branch)
                            result = rmfield(result, branch);
                        end
                    end
                end
            end

            if path == "Radio" && isfield(overlay, "Coexistence") && ...
                    isfield(overlay.Coexistence, "SidelinkType")
                oldSidelinkType = "";
                if isfield(base, "Coexistence") && ...
                        isfield(base.Coexistence, "SidelinkType")
                    oldSidelinkType = string( ...
                        base.Coexistence.SidelinkType);
                end
                newSidelinkType = string( ...
                    overlay.Coexistence.SidelinkType);
                if oldSidelinkType ~= newSidelinkType
                    for branch = ["LteV2X", "NrV2X"]
                        if isfield(result, branch)
                            result = rmfield(result, branch);
                        end
                    end
                end
            end

            if ismember(path, ["Channel.PathLoss", "Channel.PacketError"]) && ...
                    isfield(overlay, "Model") && ...
                    (~isfield(base, "Model") || ...
                     string(base.Model) ~= string(overlay.Model))
                retained = struct();
                if isfield(result, "Model")
                    retained.Model = result.Model;
                end
                result = retained;
            end

            names = string(fieldnames(overlay));
            for index = 1:numel(names)
                name = names(index);
                childPath = ...
                    v2xsim.config.internal.Operations.joinPath(path, name);
                if isfield(result, name) && isfield(node.Children, name)
                    result.(name) = ...
                        v2xsim.config.internal.Operations.mergeNode( ...
                            result.(name), overlay.(name), ...
                            node.Children.(name), childPath);
                else
                    result.(name) = overlay.(name);
                end
            end
        end

        function validateNode(value, node, path, enforceActivity, sourceName)
            if node.Kind == "table"
                if ~isstruct(value) || ~isscalar(value)
                    v2xsim.config.internal.Operations.typeError( ...
                        path, "a table", sourceName);
                end
                names = string(fieldnames(value));
                knownNames = string(fieldnames(node.Children));
                for index = 1:numel(names)
                    name = names(index);
                    if ~ismember(name, knownNames)
                        insensitive = ...
                            knownNames(strcmpi(name, knownNames));
                        suggestion = "";
                        if ~isempty(insensitive)
                            suggestion = " Did you mean """ + ...
                                insensitive(1) + """?";
                        end
                        error( ...
                            "v2xsim:config:UnknownKey", ...
                            "%s contains unknown key ""%s"".%s", ...
                            sourceName, ...
                            v2xsim.config.internal.Operations.joinPath( ...
                                path, name), ...
                            suggestion);
                    end
                end

                if enforceActivity
                    activeNames = ...
                        v2xsim.config.internal.Operations.activeChildNames( ...
                            value, node, path);
                    inactiveAuthored = setdiff(names, activeNames, "stable");
                    if ~isempty(inactiveAuthored)
                        error( ...
                            "v2xsim:config:InactiveKey", ...
                            "Key ""%s"" is inactive for the selected variant.", ...
                            v2xsim.config.internal.Operations.joinPath( ...
                                path, inactiveAuthored(1)));
                    end
                end

                for index = 1:numel(names)
                    name = names(index);
                    childPath = ...
                        v2xsim.config.internal.Operations.joinPath(path, name);
                    v2xsim.config.internal.Operations.validateNode( ...
                        value.(name), node.Children.(name), childPath, ...
                        enforceActivity, sourceName);
                end
                return
            end

            if node.Kind == "arrayOfTables"
                if ~iscell(value) || (~isvector(value) && ~isempty(value))
                    v2xsim.config.internal.Operations.typeError( ...
                        path, "an array of tables", sourceName);
                end
                for index = 1:numel(value)
                    if ~isstruct(value{index}) || ~isscalar(value{index})
                        v2xsim.config.internal.Operations.typeError( ...
                            path, "an array of scalar tables", sourceName);
                    end
                    elementPath = path + "(" + index + ")";
                    v2xsim.config.internal.Operations.validateNode( ...
                        value{index}, node.Element, elementPath, ...
                        enforceActivity, sourceName);
                end
                return
            end

            v2xsim.config.internal.Operations.validateLeaf( ...
                value, node, path, sourceName);
        end

        function validateLeaf(value, node, path, sourceName)
            kind = node.Kind;
            valid = true;
            switch kind
                case "string"
                    valid = isstring(value) && isscalar(value) && ...
                        ~ismissing(value);
                case "logical"
                    valid = islogical(value) && isscalar(value);
                case "double"
                    valid = isnumeric(value) && ~islogical(value) && ...
                        isreal(value) && isscalar(value) && ~isnan(value);
                case "integer"
                    valid = isnumeric(value) && ~islogical(value) && ...
                        isreal(value) && isscalar(value) && ...
                        ~isnan(value) && ...
                        (isinf(value) || mod(value, 1) == 0);
                    if sourceName == "TOML configuration"
                        valid = valid && isinteger(value);
                    end
                case "numericArray"
                    valid = isnumeric(value) && ~islogical(value) && ...
                        isreal(value) && isvector(value) && ...
                        all(~isnan(value), "all");
                case "stringArray"
                    valid = isstring(value) && isvector(value) && ...
                        all(~ismissing(value), "all");
            end
            if ~valid
                v2xsim.config.internal.Operations.typeError( ...
                    path, kind, sourceName);
            end

            if kind == "string" && ~isempty(node.AllowedStrings) && ...
                    ~ismember(value, node.AllowedStrings)
                error( ...
                    "v2xsim:config:InvalidEnumValue", ...
                    """%s"" must be one of: %s.", ...
                    path, strjoin(node.AllowedStrings, ", "));
            end
            if kind == "string" && node.MustBeNonemptyText && ...
                    strlength(strip(value)) == 0
                error( ...
                    "v2xsim:config:BlankString", ...
                    """%s"" must contain non-whitespace text.", path);
            end
            if kind == "string" && strcmpi(value, "null")
                error( ...
                    "v2xsim:config:NullSentinelUnsupported", ...
                    """%s"" cannot use a ""null"" sentinel; omit the key.", ...
                    path);
            end
            if ismember(kind, ["double", "integer", "numericArray"])
                if node.MustBeFinite && any(~isfinite(value), "all")
                    error( ...
                        "v2xsim:config:NonfiniteValue", ...
                        """%s"" must be finite.", path);
                end
                if any(isinf(value) & value > 0, "all") && ...
                        ~node.AllowPositiveInfinity
                    error( ...
                        "v2xsim:config:NonfiniteValue", ...
                        """%s"" does not allow infinity.", path);
                end
                if any(value < node.Minimum, "all") || ...
                        (node.MinimumExclusive && ...
                         any(value <= node.Minimum, "all")) || ...
                        any(value > node.Maximum, "all")
                    error( ...
                        "v2xsim:config:ValueOutOfRange", ...
                        """%s"" is outside its permitted range.", path);
                end
                if ~isempty(node.AllowedNumbers) && ...
                        any(~ismember(double(value), node.AllowedNumbers), "all")
                    error( ...
                        "v2xsim:config:InvalidEnumValue", ...
                        """%s"" has an unsupported numeric value.", path);
                end
            end
            if ismember(kind, ["numericArray", "stringArray"]) && ...
                    (numel(value) < node.MinimumCount || ...
                     numel(value) > node.MaximumCount)
                error( ...
                    "v2xsim:config:InvalidArraySize", ...
                    """%s"" has an invalid number of elements.", path);
            end
        end

        function result = applyNode(authored, node, path)
            if node.Kind == "table"
                if isempty(authored)
                    authored = struct();
                end
                result = authored;
                activeNames = ...
                    v2xsim.config.internal.Operations.activeChildNames( ...
                        authored, node, path);
                for index = 1:numel(activeNames)
                    name = activeNames(index);
                    childNode = node.Children.(name);
                    childPath = ...
                        v2xsim.config.internal.Operations.joinPath(path, name);
                    if isfield(authored, name)
                        result.(name) = ...
                            v2xsim.config.internal.Operations.applyNode( ...
                                authored.(name), childNode, childPath);
                    elseif childNode.Kind == "table"
                        result.(name) = ...
                            v2xsim.config.internal.Operations.applyNode( ...
                                struct(), childNode, childPath);
                    elseif childNode.HasDefault
                        result.(name) = childNode.Default;
                    elseif childNode.Required
                        error( ...
                            "v2xsim:config:MissingRequiredKey", ...
                            "Required key ""%s"" is missing.", childPath);
                    end
                end
                inactive = setdiff( ...
                    string(fieldnames(result)), activeNames, "stable");
                if ~isempty(inactive)
                    result = rmfield(result, cellstr(inactive));
                end
                return
            end
            if node.Kind == "arrayOfTables"
                if isempty(authored)
                    result = node.Default;
                    return
                end
                result = cell(size(authored));
                for index = 1:numel(authored)
                    result{index} = ...
                        v2xsim.config.internal.Operations.applyNode( ...
                            authored{index}, node.Element, ...
                            path + "(" + index + ")");
                end
                return
            end
            if isempty(authored) && node.HasDefault
                result = node.Default;
            else
                result = authored;
                if ismember(node.Kind, ["double", "integer", "numericArray"])
                    result = double(result);
                elseif node.Kind == "string"
                    result = string(result);
                elseif node.Kind == "stringArray"
                    result = string(result);
                end
            end
        end

        function names = activeChildNames(value, node, path)
            names = string(fieldnames(node.Children));
            branchChildren = node.BranchChildren;
            regularNames = setdiff(names, branchChildren, "stable");

            if strlength(node.Selector) > 0
                selectorValue = "";
                if isfield(value, node.Selector)
                    selectorValue = string(value.(node.Selector));
                else
                    selectorNode = node.Children.(node.Selector);
                    if selectorNode.HasDefault
                        selectorValue = string(selectorNode.Default);
                    end
                end
                match = find(node.BranchValues == selectorValue, 1);
                if ~isempty(match)
                    branch = node.BranchChildren(match);
                    if strlength(branch) > 0
                        regularNames(end + 1) = branch;
                    end
                end
            end

            if path == "Radio"
                % Cellular modes share sidelink settings. Coexistence also
                % activates IEEE 802.11p and one selected sidelink PHY.
                radioType = "LteV2X";
                if isfield(value, "Type")
                    radioType = string(value.Type);
                end
                if radioType == "Coexistence"
                    regularNames = union( ...
                        regularNames, ...
                        ["Coexistence", "Ieee80211p", "Sidelink"], "stable");
                    sidelinkType = "LteV2X";
                    if isfield(value, "Coexistence") && ...
                            isfield(value.Coexistence, "SidelinkType")
                        sidelinkType = string( ...
                            value.Coexistence.SidelinkType);
                    end
                    regularNames = union( ...
                        regularNames, sidelinkType, "stable");
                elseif ismember(radioType, ["LteV2X", "NrV2X"])
                    regularNames = union( ...
                        regularNames, "Sidelink", "stable");
                else
                    regularNames = setdiff( ...
                        regularNames, "Sidelink", "stable");
                end
            elseif startsWith(path, "Positioning.Errors(")
                errorType = "";
                if isfield(value, "Type")
                    errorType = string(value.Type);
                end
                switch errorType
                    case "Gaussian"
                        regularNames = [ ...
                            "Type", "MeanMagnitudeMeters", ...
                            "StandardDeviationMeters", ...
                            "DisplacementRandomSeed", ...
                            "AffectedVehicleProbability", ...
                            "SelectionRandomSeed", "ResetAfterSeconds", ...
                            "ActiveRoutes"];
                    case "Delay"
                        regularNames = ["Type", "DelaySeconds"];
                    case {"FalseExit", "FalseMerge"}
                        regularNames = [ ...
                            "Type", "AffectedVehicleProbability", ...
                            "SelectionRandomSeed", "ResetAfterSeconds", ...
                            "DisplacementScale"];
                    otherwise
                        regularNames = "Type";
                end
            elseif path == "Channel.PathLoss"
                model = "WinnerPlusB1";
                if isfield(value, "Model")
                    model = string(value.Model);
                end
                switch model
                    case "WinnerPlusB1"
                        regularNames = "Model";
                    case "SingleSlope"
                        regularNames = [ ...
                            "Model", "ReferenceLossAtOneMeterDb", ...
                            "Exponent1"];
                    case "TwoSlope"
                        regularNames = [ ...
                            "Model", "ReferenceLossAtOneMeterDb", ...
                            "Exponent1", "BreakpointDistance1Meters", ...
                            "Exponent2"];
                    case "ThreeSlope"
                        regularNames = names;
                    case "NrV2VNlos"
                        regularNames = [ ...
                            "Model", "ReferenceLossAtOneMeterDb", ...
                            "Exponent1"];
                end
            elseif path == "Channel.PacketError"
                model = "Threshold";
                if isfield(value, "Model")
                    model = string(value.Model);
                end
                if model == "Curves"
                    regularNames = [ ...
                        "Model", "CurveDirectory", "NlosCurveDirectory"];
                else
                    regularNames = [ ...
                        "Model", "Ieee80211pLosThresholdDb", ...
                        "SidelinkLosThresholdDb"];
                end
            end
            names = unique(regularNames, "stable");
        end

        function validateCrossFields(data)
            if data.SchemaVersion ~= 1
                error( ...
                    "v2xsim:config:UnsupportedSchemaVersion", ...
                    "Only SchemaVersion 1 is supported.");
            end

            if data.Scenario.Type == "ExitRampHighway"
                exitRamp = data.Scenario.ExitRampHighway;
                if exitRamp.MergeDistance > exitRamp.RoadLength / 2
                    error( ...
                        "v2xsim:config:InvalidExitRampGeometry", ...
                        "ExitRampHighway.MergeDistance cannot exceed " + ...
                        "half of RoadLength.");
                end
            end

            if data.Scenario.Type == "Roundabout"
                roundabout = data.Scenario.Roundabout;
                exitLengths = roundabout.ExitLengths;
                if ~isvector(exitLengths) || ...
                        ~ismember(numel(exitLengths), [1, 4])
                    error( ...
                        "v2xsim:config:InvalidRoundaboutExitLengths", ...
                        "Roundabout.ExitLengths must contain one shared " + ...
                        "length or four lengths ordered North, East, " + ...
                        "South, West.");
                end

                roadWidth = roundabout.RoadWidth;
                innerDiameter = roundabout.InnerCircleDiameter;
                if innerDiameter < 2 * roadWidth
                    error( ...
                        "v2xsim:config:InvalidRoundaboutGeometry", ...
                        "Roundabout.InnerCircleDiameter must be at " + ...
                        "least twice Roundabout.RoadWidth.");
                end

                tangentDistance = sqrt( ...
                    0.75 * innerDiameter ^ 2 + ...
                    innerDiameter * roadWidth);
                outerPavementRadius = innerDiameter / 2 + roadWidth;
                minimumExitLength = ...
                    tangentDistance - outerPavementRadius;
                if any(exitLengths < minimumExitLength)
                    error( ...
                        "v2xsim:config:InvalidRoundaboutGeometry", ...
                        "Every Roundabout.ExitLengths value must be at " + ...
                        "least %.15g meters for the configured smooth " + ...
                        "connector geometry.", minimumExitLength);
                end
            end

            interval = ...
                data.Application.ResourceReservationIntervalSeconds;
            supportedIntervals = 0.1 .* (1:10);
            intervalTolerance = ...
                16 * eps(max(1, abs(interval)));
            if all(abs(interval - supportedIntervals) > intervalTolerance)
                error( ...
                    "v2xsim:config:InvalidResourceReservationInterval", ...
                    "ResourceReservationIntervalSeconds must be one " + ...
                    "of 0.1:0.1:1 seconds.");
            end
            packetGeneration = data.Application.PacketGeneration;
            if packetGeneration.Mode == "Periodic" && ...
                    packetGeneration.IntervalVariationSeconds >= interval
                error( ...
                    "v2xsim:config:InvalidPacketGeneration", ...
                    "Periodic IntervalVariationSeconds must be less " + ...
                    "than ResourceReservationIntervalSeconds.");
            elseif packetGeneration.Mode == "EtsiCam"
                generationTolerance = 16 * eps(max( ...
                    1, max(abs([ ...
                        packetGeneration.IntervalSeconds, interval]))));
                if abs(packetGeneration.IntervalSeconds - interval) > ...
                        generationTolerance || ...
                        packetGeneration.IntervalVariationSeconds ~= 0 || ...
                        packetGeneration.RandomComponentMeanSeconds ~= 0
                    error( ...
                        "v2xsim:config:InvalidPacketGeneration", ...
                        "EtsiCam requires IntervalSeconds equal to the " + ...
                        "resource-reservation interval and both variation " + ...
                        "and random-component settings equal to zero.");
                end
            end

            if ismember(data.Radio.Type, ["Ieee80211p", "Coexistence"]) && ...
                    data.Radio.BandwidthMHz ~= 10
                error( ...
                    "v2xsim:config:InvalidBandwidth", ...
                    "IEEE 802.11p and coexistence require 10 MHz bandwidth.");
            end
            if isfield(data.Radio, "Ieee80211p")
                cbrThresholds = ...
                    data.Radio.Ieee80211p.Repetition.CbrThresholds;
                if any(diff(cbrThresholds) < 0)
                    error( ...
                        "v2xsim:config:InvalidRepetitionThresholds", ...
                        "IEEE 802.11p repetition CBR thresholds must " + ...
                        "be nondecreasing.");
                end
            end

            isNrSidelink = data.Radio.Type == "NrV2X" || ...
                (data.Radio.Type == "Coexistence" && ...
                 data.Radio.Coexistence.SidelinkType == "NrV2X");
            if isNrSidelink
                pool = data.Radio.Sidelink.ResourcePool;
                subchannelSize = 10;
                if isfield(pool, "SubchannelSizeResourceBlocks")
                    subchannelSize = ...
                        pool.SubchannelSizeResourceBlocks;
                end
                if ~ismember( ...
                        subchannelSize, [10, 12, 15, 20, 25, 50, 75, 100])
                    error( ...
                        "v2xsim:config:InvalidNrResourcePool", ...
                        "NR-V2X subchannel size must be one of " + ...
                        "10, 12, 15, 20, 25, 50, 75, or 100 RBs.");
                end
                if data.Radio.NrV2X.SciResourceBlockCount > subchannelSize
                    error( ...
                        "v2xsim:config:InvalidNrResourcePool", ...
                        "NrV2X.SciResourceBlockCount cannot exceed the " + ...
                        "effective subchannel size.");
                end
            end

            awarenessRanges = data.Awareness.RangesMeters;
            if any(mod(awarenessRanges, 1) ~= 0) || ...
                    any(diff(awarenessRanges) < 0)
                error( ...
                    "v2xsim:config:InvalidAwarenessRanges", ...
                    "Awareness ranges must be integer-valued and " + ...
                    "nondecreasing.");
            end

            obstacles = data.Channel.Obstacles;
            if obstacles.BuildingAttenuationDbPerMeter ~= 0.4 || ...
                    obstacles.WallAttenuationDb ~= 6
                error( ...
                    "v2xsim:config:UnsupportedObstacleConfiguration", ...
                    "Custom obstacle attenuation is unavailable because " + ...
                    "V7 no longer supports map-backed trace scenarios.");
            end

            if data.Application.CongestionControl.Enabled && ...
                    ~data.Application.ChannelLoad.Enabled
                error( ...
                    "v2xsim:config:CongestionControlRequiresChannelLoad", ...
                    "Congestion control requires channel-load measurement.");
            end
            if data.Outputs.ChannelBusyRatio.Enabled && ...
                    ~data.Application.ChannelLoad.Enabled
                error( ...
                    "v2xsim:config:OutputRequiresChannelLoad", ...
                    "Channel-busy-ratio output requires channel-load measurement.");
            end

            allocationType = data.ResourceAllocation.Type;
            allocation = data.ResourceAllocation.(allocationType);
            for field = [ ...
                    "PositionUpdateIntervalSeconds", ...
                    "ReassignmentIntervalSeconds"]
                if isfield(allocation, field)
                    ratio = allocation.(field) / interval;
                    if abs(ratio - round(ratio)) > ...
                            16 * eps(max(1, abs(ratio)))
                        error( ...
                            "v2xsim:config:NonIntegralInterval", ...
                            "%s must be an exact positive multiple of " + ...
                            "ResourceReservationIntervalSeconds.", field);
                    end
                end
            end

            if ismember(allocationType, ["SensingBased", "Random"])
                numerology = 0;
                if isNrSidelink
                    numerology = log2( ...
                        data.Radio.NrV2X. ...
                            SubcarrierSpacingKilohertz / 15);
                end
                minimumStarts = [1, 0.5, 0.5];
                maximumStarts = [4, 3, 2.75];
                windowStart = minimumStarts(numerology + 1);
                if isfield( ...
                        allocation, "SelectionWindowStartMilliseconds")
                    windowStart = ...
                        allocation.SelectionWindowStartMilliseconds;
                end
                slotsPerMillisecond = 2^numerology;
                windowStartSlots = ...
                    windowStart * slotsPerMillisecond;
                alignmentTolerance = 16 * eps(max( ...
                    1, abs(windowStartSlots)));
                if windowStart < minimumStarts(numerology + 1) || ...
                        windowStart > maximumStarts(numerology + 1) || ...
                        abs(windowStartSlots - round(windowStartSlots)) > ...
                            alignmentTolerance
                    error( ...
                        "v2xsim:config:InvalidSelectionWindow", ...
                        "SelectionWindowStartMilliseconds is outside " + ...
                        "the range or slot alignment for the configured " + ...
                        "sidelink numerology.");
                end
            end
            if allocationType == "SensingBased"
                sensing = data.ResourceAllocation.SensingBased;
                if sensing.ReselectEveryPacketEnabled && ...
                        sensing.KeepResourceProbability ~= 0
                    error( ...
                        "v2xsim:config:InvalidKeepResourceProbability", ...
                        "KeepResourceProbability must be zero when every " + ...
                        "packet reselects.");
                end
                if sensing.ReevaluateAfterSkippedTransmissionEnabled && ...
                        ~sensing.ReevaluationEnabled
                    error( ...
                        "v2xsim:config:InvalidReevaluationOptions", ...
                        "Skipped-transmission reevaluation requires reevaluation.");
                end
                threshold = sensing.SensingThresholdDbm;
                if threshold < -128 || threshold > -2 || ...
                        mod(threshold, 2) ~= 0
                    error( ...
                        "v2xsim:config:InvalidSensingThreshold", ...
                        "SensingThresholdDbm must be -128:-2 in 2 dB steps.");
                end
                if isfield(sensing, "ReselectionCounterMinimum") && ...
                        isfield(sensing, "ReselectionCounterMaximum") && ...
                        sensing.ReselectionCounterMaximum <= ...
                            sensing.ReselectionCounterMinimum
                    error( ...
                        "v2xsim:config:InvalidReselectionCounter", ...
                        "Maximum reselection counter must exceed minimum.");
                end
            end

            pathLoss = data.Channel.PathLoss;
            if isfield(pathLoss, "BreakpointDistance2Meters") && ...
                    pathLoss.BreakpointDistance2Meters < ...
                        pathLoss.BreakpointDistance1Meters
                error( ...
                    "v2xsim:config:InvalidPathLossBreakpoints", ...
                    "Path-loss breakpoints must be nondecreasing.");
            end
            if data.Channel.PacketError.Model == "Curves" && ...
                    ~isfield(data.Channel.PacketError, "CurveDirectory")
                error( ...
                    "v2xsim:config:MissingPacketErrorCurveDirectory", ...
                    "CurveDirectory is required for curve-based packet errors.");
            end
            if data.Channel.PacketError.Model == "Curves"
                for field = ["CurveDirectory", "NlosCurveDirectory"]
                    if isfield(data.Channel.PacketError, field) && ...
                            ~v2xsim.config.internal.Operations ...
                                .isAbsolutePath( ...
                                    data.Channel.PacketError.(field))
                        error( ...
                            "v2xsim:config:RelativeResourcePath", ...
                            "%s must resolve to an absolute path. " + ...
                            "TOML paths are resolved relative to their " + ...
                            "configuration file.", field);
                    end
                end
            end
            thresholdFields = [ ...
                "Ieee80211pLosThresholdDb", "SidelinkLosThresholdDb"];
            for field = thresholdFields
                if isfield(data.Channel.PacketError, field) && ...
                        data.Channel.PacketError.(field) == -1000
                    error( ...
                        "v2xsim:config:AutomaticSentinelUnsupported", ...
                        "%s cannot use -1000 for automatic selection; " + ...
                        "omit the key.", field);
                end
            end

            errorTypes = strings(0, 1);
            for index = 1:numel(data.Positioning.Errors)
                positionError = data.Positioning.Errors{index};
                errorTypes(end + 1, 1) = positionError.Type; %#ok<AGROW>
                if positionError.Type == "FalseExit" && ...
                        ~ismember( ...
                            data.Scenario.Type, ...
                            ["ExitRampHighway", "Roundabout"])
                    error( ...
                        "v2xsim:config:IncompatiblePositionError", ...
                        "FalseExit requires ExitRampHighway or Roundabout.");
                end
                if positionError.Type == "FalseMerge" && ...
                        data.Scenario.Type ~= "ExitRampHighway"
                    error( ...
                        "v2xsim:config:IncompatiblePositionError", ...
                        "FalseMerge requires ExitRampHighway.");
                end
                if positionError.Type == "Gaussian" && ...
                        isfield(positionError, "ActiveRoutes") && ...
                        ~isequal(positionError.ActiveRoutes, "All") && ...
                        data.Scenario.Type ~= "ExitRampHighway"
                    error( ...
                        "v2xsim:config:IncompatiblePositionError", ...
                        "Route-filtered Gaussian error requires ExitRampHighway.");
                end
                if positionError.Type == "Gaussian" && ...
                        isfield(positionError, "ActiveRoutes")
                    routes = positionError.ActiveRoutes;
                    allowedRoutes = ["Ramp", "Merge", "Adjacent"];
                    isAll = isequal(routes, "All");
                    if ~isAll && ( ...
                            any(~ismember(routes, allowedRoutes)) || ...
                            numel(unique(routes)) ~= numel(routes))
                        error( ...
                            "v2xsim:config:InvalidPositionErrorRoutes", ...
                            "Gaussian ActiveRoutes must be ""All"" or a " + ...
                            "unique array drawn from Ramp, Merge, and Adjacent.");
                    end
                end
            end
            if numel(unique(errorTypes)) ~= numel(errorTypes)
                error( ...
                    "v2xsim:config:DuplicatePositionErrorType", ...
                    "Each positioning error type may occur at most once.");
            end

            units = data.Infrastructure.RoadsideUnits;
            ids = strings(numel(units), 1);
            for index = 1:numel(units)
                unit = units{index};
                ids(index) = unit.Id;
                if ismember(unit.PacketType, ["Denm", "HighPriorityDenm"]) && ...
                        unit.Technology ~= "Ieee80211p"
                    error( ...
                        "v2xsim:config:UnsupportedRoadsideUnitPacket", ...
                        "DENM roadside units require Ieee80211p.");
                end
            end
            if numel(unique(ids)) ~= numel(ids)
                error( ...
                    "v2xsim:config:DuplicateRoadsideUnitId", ...
                    "Roadside-unit identifiers must be unique.");
            end
            if any(matches( ...
                    ids, regexpPattern("^V[1-9][0-9]*$")))
                error( ...
                    "v2xsim:config:ReservedRoadsideUnitId", ...
                    "Roadside-unit identifiers cannot use the generated " + ...
                    "vehicle namespace V1, V2, and so on.");
            end
            if ~isempty(units)
                technologies = cellfun( ...
                    @(unit) unit.Technology, units, ...
                    UniformOutput=false);
                packetTypes = cellfun( ...
                    @(unit) unit.PacketType, units, ...
                    UniformOutput=false);
                if numel(unique(string(technologies))) > 1 || ...
                        numel(unique(string(packetTypes))) > 1
                    error( ...
                        "v2xsim:config:HeterogeneousRoadsideUnitsUnsupported", ...
                        "V7 currently requires homogeneous roadside units.");
                end
                technology = string(technologies{1});
                if (data.Radio.Type == "Ieee80211p" && ...
                        technology ~= "Ieee80211p") || ...
                        (ismember(data.Radio.Type, ...
                            ["LteV2X", "NrV2X"]) && ...
                         technology ~= "LteV2X")
                    error( ...
                        "v2xsim:config:IncompatibleRoadsideUnitTechnology", ...
                        "Roadside-unit technology must be active in the " + ...
                        "selected radio configuration.");
                end
            end

            wirelessBlindSpot = data.Outputs.WirelessBlindSpot;
            if wirelessBlindSpot.BinWidthSeconds > ...
                    wirelessBlindSpot.MaximumDelaySeconds
                error( ...
                    "v2xsim:config:InvalidWirelessBlindSpotBins", ...
                    "WirelessBlindSpot.BinWidthSeconds cannot exceed " + ...
                    "MaximumDelaySeconds.");
            end
        end

        function validateCompleteness(value, node, path)
            if node.Kind == "table"
                if ~isstruct(value) || ~isscalar(value)
                    error( ...
                        "v2xsim:config:InvalidResolvedConfiguration", ...
                        "Resolved key ""%s"" must be a scalar table.", path);
                end
                activeNames = ...
                    v2xsim.config.internal.Operations.activeChildNames( ...
                        value, node, path);
                for index = 1:numel(activeNames)
                    name = activeNames(index);
                    child = node.Children.(name);
                    mustExist = child.Required || child.HasDefault || ...
                        ismember(child.Kind, ["table", "arrayOfTables"]);
                    childPath = ...
                        v2xsim.config.internal.Operations.joinPath(path, name);
                    if mustExist && ~isfield(value, name)
                        error( ...
                            "v2xsim:config:MissingResolvedKey", ...
                            "Resolved configuration is missing ""%s"".", ...
                            childPath);
                    end
                    if isfield(value, name)
                        if childPath == "Coexistence" && ...
                                isempty(fieldnames(value.(name)))
                            continue
                        end
                        v2xsim.config.internal.Operations ...
                            .validateCompleteness( ...
                                value.(name), child, childPath);
                    end
                end
            elseif node.Kind == "arrayOfTables" && iscell(value)
                for index = 1:numel(value)
                    v2xsim.config.internal.Operations.validateCompleteness( ...
                        value{index}, node.Element, ...
                        path + "(" + index + ")");
                end
            end
        end

        function result = leafPaths(value, prefix)
            if isstruct(value) && isscalar(value)
                names = string(fieldnames(value));
                result = strings(0, 1);
                for index = 1:numel(names)
                    childPath = ...
                        v2xsim.config.internal.Operations.joinPath( ...
                            prefix, names(index));
                    childPaths = ...
                        v2xsim.config.internal.Operations.leafPaths( ...
                            value.(names(index)), childPath);
                    result = [result; childPaths]; %#ok<AGROW>
                end
            elseif iscell(value)
                result = strings(0, 1);
                for index = 1:numel(value)
                    childPaths = ...
                        v2xsim.config.internal.Operations.leafPaths( ...
                            value{index}, prefix + "(" + index + ")");
                    result = [result; childPaths]; %#ok<AGROW>
                end
            else
                result = prefix;
            end
        end

        function result = hasPath(data, path)
            parts = split(path, ".");
            value = data;
            result = true;
            for index = 1:numel(parts)
                if ~isstruct(value) || ~isscalar(value) || ...
                        ~isfield(value, parts(index))
                    result = false;
                    return
                end
                value = value.(parts(index));
            end
        end

        function result = joinPath(parent, child)
            if strlength(parent) == 0
                result = child;
            else
                result = parent + "." + child;
            end
        end

        function result = isAbsolutePath(path)
            path = string(path);
            if ispc
                result = ~isempty( ...
                    regexp(path, "^[A-Za-z]:[\\/]|^\\\\", "once"));
            else
                result = startsWith(path, "/");
            end
        end

        function typeError(path, expected, sourceName)
            if strlength(path) == 0
                path = "<root>";
            end
            error( ...
                "v2xsim:config:InvalidType", ...
                "%s key ""%s"" must be %s.", ...
                sourceName, path, expected);
        end

        function result = saltedSeed(masterSeed, salt)
            maximum = double(intmax("uint32"));
            result = mod(double(masterSeed) - 1 + double(salt), maximum) + 1;
        end
    end
end
