function terminalFates = aggregateTerminalPacketFates(observations)
%AGGREGATETERMINALPACKETFATES Reconcile directed HARQ observations.
%   TERMINALFATES = AGGREGATETERMINALPACKETFATES(OBSERVATIONS) returns at
%   most one radio terminal row for each
%   technology/transmitter/packet/receiver identity. Provisional "none"
%   observations are discarded, repeated radio terminal reports are
%   idempotent, and conflicting correct and error outcomes are rejected.
%   Every allocator-blocked observation is already a terminal PRR event and
%   is therefore retained independently of later radio observations.

arguments (Input)
    observations table
end
arguments (Output)
    terminalFates table
end

expectedNames = string( ...
    v2xsim.analysis.emptyTerminalPacketFateTable(). ...
    Properties.VariableNames);
actualNames = string(observations.Properties.VariableNames);
if ~isequal(actualNames,expectedNames)
    error( ...
        "v2xsim:analysis:InvalidPacketFateSchema", ...
        "Packet observations must contain exactly %s.", ...
        strjoin(expectedNames,", "));
end

validateObservations(observations);
terminalFates = observations( ...
    string(observations.Outcome) ~= "none",:);
if isempty(terminalFates)
    terminalFates = ...
        v2xsim.analysis.emptyTerminalPacketFateTable();
    return
end

terminalFates = sortrows( ...
    terminalFates, ...
    ["FateTimeSeconds","Technology","TransmitterUeId", ...
    "PacketSequence","ReceiverUeId","AttemptNumber"]);
isBlocked = terminalFates.Outcome == "blocked";
radioRows = find(~isBlocked);
if isempty(radioRows)
    return
end

identityNames = [ ...
    "Technology","TransmitterUeId", ...
    "PacketSequence","ReceiverUeId"];
groupIndices = findgroups( ...
    terminalFates(radioRows,identityNames));
groupCount = max(groupIndices);
radioOutcomes = terminalFates.Outcome(radioRows);
isCorrect = radioOutcomes == "correct";
isError = radioOutcomes == "error";
hasCorrect = accumarray( ...
    groupIndices,isCorrect,[groupCount,1],@any);
hasError = accumarray( ...
    groupIndices,isError,[groupCount,1],@any);
conflictingGroups = find(hasCorrect & hasError);
if ~isempty(conflictingGroups)
    firstGroup = conflictingGroups(1);
    firstRadioRow = find(groupIndices == firstGroup,1);
    firstRow = radioRows(firstRadioRow);
    error( ...
        "v2xsim:analysis:ConflictingTerminalPacketFates", ...
        "Directed packet %s/%s/%u/%s has conflicting terminal " + ...
        "outcomes.", ...
        terminalFates.Technology(firstRow), ...
        terminalFates.TransmitterUeId(firstRow), ...
        terminalFates.PacketSequence(firstRow), ...
        terminalFates.ReceiverUeId(firstRow));
end

radioRowIndices = (1:numel(radioRows)).';
selectionOrder = sortrows( ...
    table(groupIndices,radioRowIndices), ...
    ["groupIndices","radioRowIndices"]);
isFirstGroupRow = [ ...
    true;diff(selectionOrder.groupIndices) ~= 0];
retainedRadioRows = radioRows( ...
    selectionOrder.radioRowIndices(isFirstGroupRow));
retain = isBlocked;
retain(retainedRadioRows) = true;
terminalFates = terminalFates(retain,:);
end

function validateObservations(observations)
numericColumns = [ ...
    "FateTimeSeconds","TransmitterId","ReceiverId", ...
    "PacketSequence","GenerationTimeSeconds","AttemptNumber", ...
    "Channel","PacketType","TrueDistanceMeters", ...
    "ResourceId","TimeResourceId","FrequencyResourceId", ...
    "AllocationEpoch"];
for variableName = numericColumns
    values = observations.(variableName);
    if ~isnumeric(values) || ~iscolumn(values)
        error( ...
            "v2xsim:analysis:InvalidPacketFateValues", ...
            "%s must be a numeric column.",variableName);
    end
end

nonnegativeColumns = [ ...
    "FateTimeSeconds","GenerationTimeSeconds", ...
    "TrueDistanceMeters"];
for variableName = nonnegativeColumns
    values = observations.(variableName);
    if any(~isfinite(values)) || any(values < 0)
        error( ...
            "v2xsim:analysis:InvalidPacketFateValues", ...
            "%s must contain finite nonnegative values.", ...
            variableName);
    end
end

positiveIntegerColumns = [ ...
    "TransmitterId","ReceiverId","PacketSequence", ...
    "Channel","PacketType"];
for variableName = positiveIntegerColumns
    values = observations.(variableName);
    if any(~isfinite(values)) || any(values < 1) || ...
            any(fix(values) ~= values)
        error( ...
            "v2xsim:analysis:InvalidPacketFateValues", ...
            "%s must contain positive integer values.", ...
            variableName);
    end
end
if any(observations.TransmitterId == observations.ReceiverId)
    error( ...
        "v2xsim:analysis:InvalidPacketFateValues", ...
        "Packet-fate transmitters and receivers must differ.");
end

optionalIntegerColumns = [ ...
    "AttemptNumber","ResourceId","TimeResourceId", ...
    "FrequencyResourceId","AllocationEpoch"];
for variableName = optionalIntegerColumns
    values = observations.(variableName);
    known = ~isnan(values);
    minimumValue = double(variableName ~= "AttemptNumber" && ...
        variableName ~= "AllocationEpoch");
    if any(~isfinite(values(known))) || ...
            any(values(known) < minimumValue) || ...
            any(fix(values(known)) ~= values(known))
        error( ...
            "v2xsim:analysis:InvalidPacketFateValues", ...
            "%s must contain integer identifiers or NaN.", ...
            variableName);
    end
end

stringColumns = [ ...
    "Technology","TransmitterUeId","ReceiverUeId","Outcome"];
for variableName = stringColumns
    values = observations.(variableName);
    if ~isstring(values) || ~iscolumn(values) || ...
            any(ismissing(values)) || ...
            any(strlength(strip(values)) == 0) || ...
            any(values ~= strip(values))
        error( ...
            "v2xsim:analysis:InvalidPacketFateValues", ...
            "%s must contain nonblank string values.",variableName);
    end
end
if any(observations.TransmitterUeId == ...
        observations.ReceiverUeId)
    error( ...
        "v2xsim:analysis:InvalidPacketFateValues", ...
        "Stable transmitter and receiver identities must differ.");
end
if any(~ismember( ...
        string(observations.Outcome), ...
        ["none","correct","error","blocked"]))
    error( ...
        "v2xsim:analysis:InvalidPacketFateValues", ...
        "Outcome must be none, correct, error, or blocked.");
end
end
