function classified = classifyExposedReuseOpportunities( ...
        reuseCandidates,shadowPredictions,options)
%CLASSIFYEXPOSEDREUSEOPPORTUNITIES Apply the shadow-PRR safety rule.
%   A missed-reuse pair is exposed only when the caller asserts that the
%   shadow prediction set is complete and every relevant same-technology
%   receiver within range meets MinimumPrr. EventKeyVariables separates
%   repeated observations of the same pair, such as AllocationEpoch.

arguments (Input)
    reuseCandidates table
    shadowPredictions table
    options.MinimumPrr (1,1) double ...
        {mustBeReal,mustBeFinite,mustBeNonnegative} = 0.9
    options.PredictionsAreComplete (1,1) logical = false
    options.EmptyNeighborSetIsSafe (1,1) logical = true
    options.EventKeyVariables (1,:) string = strings(1,0)
end
arguments (Output)
    classified table
end

if options.MinimumPrr > 1
    error( ...
        "v2xsim:analysis:InvalidPrrThreshold", ...
        "MinimumPrr cannot exceed one.");
end
eventKeyVariables = validateEventKeyVariables( ...
    options.EventKeyVariables,reuseCandidates,shadowPredictions);
validateReuseCandidates(reuseCandidates,eventKeyVariables);
validateShadowPredictions(shadowPredictions,eventKeyVariables);

candidateCount = height(reuseCandidates);
eligibleReceiverCount = zeros(candidateCount,1);
minimumPredictedPrr = nan(candidateCount,1);
isExposedOpportunity = false(candidateCount,1);
opportunityStatus = repmat( ...
    "not_missed_reuse",candidateCount,1);
for candidateIndex = 1:candidateCount
    if reuseCandidates.CandidateType(candidateIndex) ~= ...
            "missed_reuse"
        continue
    end
    firstUeId = reuseCandidates.FirstUeId(candidateIndex);
    secondUeId = reuseCandidates.SecondUeId(candidateIndex);
    isPair = eventKeyMask( ...
        shadowPredictions,reuseCandidates,candidateIndex, ...
        eventKeyVariables) & ...
        shadowPredictions.FirstUeId == firstUeId & ...
        shadowPredictions.SecondUeId == secondUeId;
    isEligible = isPair & ...
        shadowPredictions.IsSameTechnology & ...
        shadowPredictions.IsWithinAnalysisRange;
    predictedPrr = ...
        shadowPredictions.PredictedPrr(isEligible);
    eligibleReceiverCount(candidateIndex) = numel(predictedPrr);

    if ~options.PredictionsAreComplete
        opportunityStatus(candidateIndex) = ...
            "incomplete_prediction_set";
        continue
    end
    if isempty(predictedPrr)
        if options.EmptyNeighborSetIsSafe
            isExposedOpportunity(candidateIndex) = true;
            opportunityStatus(candidateIndex) = ...
                "exposed_no_relevant_neighbors";
        else
            opportunityStatus(candidateIndex) = ...
                "no_relevant_neighbor_prediction";
        end
        continue
    end
    minimumPredictedPrr(candidateIndex) = min(predictedPrr);
    if all(predictedPrr >= options.MinimumPrr)
        isExposedOpportunity(candidateIndex) = true;
        opportunityStatus(candidateIndex) = "exposed";
    else
        opportunityStatus(candidateIndex) = "unsafe";
    end
end

classified = reuseCandidates;
classified.EligibleReceiverCount = eligibleReceiverCount;
classified.MinimumPredictedPrr = minimumPredictedPrr;
classified.IsExposedOpportunity = isExposedOpportunity;
classified.OpportunityStatus = opportunityStatus;
end

function eventKeyVariables = validateEventKeyVariables( ...
        eventKeyVariables,candidates,predictions)
eventKeyVariables = eventKeyVariables(:).';
baseNames = [ ...
    "FirstUeId","SecondUeId","CandidateType", ...
    "ReceiverUeId","IsSameTechnology", ...
    "IsWithinAnalysisRange","PredictedPrr"];
if any(ismissing(eventKeyVariables)) || ...
        any(strlength(strip(eventKeyVariables)) == 0) || ...
        any(eventKeyVariables ~= strip(eventKeyVariables)) || ...
        numel(unique(eventKeyVariables)) ~= ...
        numel(eventKeyVariables) || ...
        any(ismember(eventKeyVariables,baseNames)) || ...
        any(~ismember( ...
            eventKeyVariables, ...
            string(candidates.Properties.VariableNames))) || ...
        any(~ismember( ...
            eventKeyVariables, ...
            string(predictions.Properties.VariableNames)))
    error( ...
        "v2xsim:analysis:InvalidExposedReuseEventKeys", ...
        "EventKeyVariables must be unique nonblank metadata " + ...
        "variables present in candidates and predictions.");
end
for variableName = eventKeyVariables
    candidateValues = candidates.(variableName);
    predictionValues = predictions.(variableName);
    if ~strcmp(class(candidateValues),class(predictionValues)) || ...
            size(candidateValues,2) ~= ...
            size(predictionValues,2) || ...
            anyMissing(candidateValues) || ...
            anyMissing(predictionValues)
        error( ...
            "v2xsim:analysis:InvalidExposedReuseEventKeys", ...
            "Event key %s must have matching nonmissing types and " + ...
            "widths in candidates and predictions.",variableName);
    end
end
end

function validateReuseCandidates(candidates,eventKeyVariables)
requiredNames = [ ...
    eventKeyVariables,"FirstUeId","SecondUeId","CandidateType"];
if any(~ismember( ...
        requiredNames, ...
        string(candidates.Properties.VariableNames))) || ...
        ~isstring(candidates.FirstUeId) || ...
        ~isstring(candidates.SecondUeId) || ...
        ~isstring(candidates.CandidateType) || ...
        any(ismissing(candidates.FirstUeId)) || ...
        any(ismissing(candidates.SecondUeId)) || ...
        any(strlength(strip(candidates.FirstUeId)) == 0) || ...
        any(strlength(strip(candidates.SecondUeId)) == 0) || ...
        any(~ismember( ...
            candidates.CandidateType, ...
            ["harmful_reuse","missed_reuse", ...
            "unchanged_overlap","unchanged_separation"]))
    error( ...
        "v2xsim:analysis:InvalidReuseCandidates", ...
        "Reuse candidates have an invalid schema or classification.");
end
if any(candidates.FirstUeId >= candidates.SecondUeId)
    error( ...
        "v2xsim:analysis:InvalidReuseCandidates", ...
        "Reuse-candidate endpoint identities must be canonicalized.");
end
identityNames = [ ...
    eventKeyVariables,"FirstUeId","SecondUeId"];
if height(unique(candidates(:,identityNames),"rows")) ~= ...
        height(candidates)
    error( ...
        "v2xsim:analysis:InvalidReuseCandidates", ...
        "Every reuse-candidate UE pair must occur once.");
end
end

function validateShadowPredictions(predictions,eventKeyVariables)
expectedNames = [ ...
    eventKeyVariables, ...
    "FirstUeId","SecondUeId","ReceiverUeId", ...
    "IsSameTechnology","IsWithinAnalysisRange","PredictedPrr"];
if ~isequal( ...
        string(predictions.Properties.VariableNames), ...
        expectedNames) || ...
        ~isstring(predictions.FirstUeId) || ...
        ~isstring(predictions.SecondUeId) || ...
        ~isstring(predictions.ReceiverUeId) || ...
        any(ismissing(predictions.FirstUeId)) || ...
        any(ismissing(predictions.SecondUeId)) || ...
        any(ismissing(predictions.ReceiverUeId)) || ...
        any(strlength(strip(predictions.FirstUeId)) == 0) || ...
        any(strlength(strip(predictions.SecondUeId)) == 0) || ...
        any(strlength(strip(predictions.ReceiverUeId)) == 0) || ...
        ~islogical(predictions.IsSameTechnology) || ...
        ~iscolumn(predictions.IsSameTechnology) || ...
        ~islogical(predictions.IsWithinAnalysisRange) || ...
        ~iscolumn(predictions.IsWithinAnalysisRange) || ...
        ~isnumeric(predictions.PredictedPrr) || ...
        ~iscolumn(predictions.PredictedPrr) || ...
        any(~isfinite(predictions.PredictedPrr)) || ...
        any(predictions.PredictedPrr < 0) || ...
        any(predictions.PredictedPrr > 1)
    error( ...
        "v2xsim:analysis:InvalidShadowPredictions", ...
        "Shadow predictions must contain canonical pair identities, " + ...
        "receiver scope, and finite PRR probabilities.");
end
if any(predictions.FirstUeId >= predictions.SecondUeId)
    error( ...
        "v2xsim:analysis:InvalidShadowPredictions", ...
        "Shadow-prediction endpoint identities must be canonicalized.");
end
identityNames = [ ...
    eventKeyVariables, ...
    "FirstUeId","SecondUeId","ReceiverUeId"];
if height(unique(predictions(:,identityNames),"rows")) ~= ...
        height(predictions)
    error( ...
        "v2xsim:analysis:InvalidShadowPredictions", ...
        "Every pair/receiver shadow prediction must occur once.");
end
end

function mask = eventKeyMask( ...
        predictions,candidates,candidateIndex,eventKeyVariables)
if isempty(eventKeyVariables)
    mask = true(height(predictions),1);
    return
end
[mask,~] = ismember( ...
    predictions(:,eventKeyVariables), ...
    candidates(candidateIndex,eventKeyVariables),"rows");
end

function tf = anyMissing(values)
try
    tf = any(ismissing(values),"all");
catch
    tf = false;
end
end
