function candidates = classifyReuseCandidates( ...
        liveAssignments,oracleAssignments)
%CLASSIFYREUSECANDIDATES Compare pairwise live and oracle reuse graphs.
%   Assignment resource labels may differ between the live and oracle
%   results. Classification depends only on whether each UE pair shares at
%   least one resource, making the comparison invariant to global resource
%   relabeling.

arguments (Input)
    liveAssignments table
    oracleAssignments table
end
arguments (Output)
    candidates table
end

validateAssignments(liveAssignments,"live");
validateAssignments(oracleAssignments,"oracle");
liveUeIds = liveAssignments.UeId;
oracleUeIds = oracleAssignments.UeId;
if ~isequal(sort(liveUeIds),sort(oracleUeIds)) || ...
        size(liveAssignments.ResourceIds,2) ~= ...
        size(oracleAssignments.ResourceIds,2)
    error( ...
        "v2xsim:analysis:IncompatibleReuseAssignments", ...
        "Live and oracle assignments must cover the same UEs and " + ...
        "number of transmission resources.");
end

ueIds = sort(liveUeIds);
[~,liveRows] = ismember(ueIds,liveUeIds);
[~,oracleRows] = ismember(ueIds,oracleUeIds);
ueCount = numel(ueIds);
if ueCount < 2
    candidates = table( ...
        strings(0,1),strings(0,1), ...
        false(0,1),false(0,1),strings(0,1), ...
        VariableNames=[ ...
            "FirstUeId","SecondUeId", ...
            "LiveOverlap","OracleOverlap","CandidateType"]);
    return
end

pairs = nchoosek((1:ueCount).',2);
pairCount = size(pairs,1);
liveOverlap = false(pairCount,1);
oracleOverlap = false(pairCount,1);
for pairIndex = 1:pairCount
    firstIndex = pairs(pairIndex,1);
    secondIndex = pairs(pairIndex,2);
    liveOverlap(pairIndex) = shareResource( ...
        liveAssignments.ResourceIds(liveRows(firstIndex),:), ...
        liveAssignments.ResourceIds(liveRows(secondIndex),:));
    oracleOverlap(pairIndex) = shareResource( ...
        oracleAssignments.ResourceIds(oracleRows(firstIndex),:), ...
        oracleAssignments.ResourceIds(oracleRows(secondIndex),:));
end

candidateType = repmat("unchanged_separation",pairCount,1);
candidateType(liveOverlap & oracleOverlap) = "unchanged_overlap";
candidateType(liveOverlap & ~oracleOverlap) = "harmful_reuse";
candidateType(~liveOverlap & oracleOverlap) = "missed_reuse";
candidates = table( ...
    ueIds(pairs(:,1)),ueIds(pairs(:,2)), ...
    liveOverlap,oracleOverlap,candidateType, ...
    VariableNames=[ ...
        "FirstUeId","SecondUeId", ...
        "LiveOverlap","OracleOverlap","CandidateType"]);
end

function validateAssignments(assignments,label)
expectedNames = ["UeId","ResourceIds"];
if ~isequal( ...
        string(assignments.Properties.VariableNames), ...
        expectedNames) || ...
        ~isstring(assignments.UeId) || ...
        ~iscolumn(assignments.UeId) || ...
        any(ismissing(assignments.UeId)) || ...
        any(strlength(strip(assignments.UeId)) == 0) || ...
        any(assignments.UeId ~= strip(assignments.UeId)) || ...
        numel(unique(assignments.UeId)) ~= height(assignments) || ...
        ~isnumeric(assignments.ResourceIds) || ...
        size(assignments.ResourceIds,1) ~= height(assignments) || ...
        size(assignments.ResourceIds,2) == 0
    error( ...
        "v2xsim:analysis:InvalidReuseAssignments", ...
        "%s assignments must contain unique string UeId and numeric " + ...
        "ResourceIds.",label);
end
resources = assignments.ResourceIds;
assigned = ~isnan(resources);
if any(~isfinite(resources(assigned))) || ...
        any(resources(assigned) <= 0) || ...
        any(fix(resources(assigned)) ~= resources(assigned))
    error( ...
        "v2xsim:analysis:InvalidReuseAssignments", ...
        "%s resources must be positive integers or NaN.",label);
end
end

function tf = shareResource(firstResources,secondResources)
firstResources = unique(firstResources(~isnan(firstResources)));
secondResources = unique(secondResources(~isnan(secondResources)));
tf = any(ismember(firstResources,secondResources));
end
