function classified = classifyFailureModes( ...
        terminalFates,counterfactualEvidence,options)
%CLASSIFYFAILUREMODES Classify terminal packet outcomes from PHY evidence.
%   Counterfactual evidence is one row per candidate interferer at the
%   terminal attempt. An interferer is individually sufficient when the
%   observed SINR is below the sampled decode threshold and removing that
%   interferer raises SINR to the threshold. Hidden-terminal classification
%   additionally requires a harmful interference-overlap flag from the
%   live/oracle allocation comparison. The overlap producer uses the PHY
%   frequency-coupling matrix, so a farther same-time interferer may be
%   causal when in-band emission is nonzero.
%
%   This function does not infer causality from allocation overlap alone.
%   EvidenceIsExhaustive must be true before absence of a sufficient
%   interferer is labelled noise_or_propagation.

arguments (Input)
    terminalFates table
    counterfactualEvidence table
    options.EvidenceIsExhaustive (1,1) logical = false
end
arguments (Output)
    classified table
end

terminalFates = ...
    v2xsim.analysis.aggregateTerminalPacketFates( ...
        terminalFates);
validateEvidence(counterfactualEvidence);
[~,evidenceRowGroups] = validateEvidenceJoins( ...
    terminalFates,counterfactualEvidence);

fateCount = height(terminalFates);
failureMode = strings(fateCount,1);
culpritUeIds = strings(fateCount,1);
causalInterfererCount = zeros(fateCount,1);
isHiddenTerminal = false(fateCount,1);
isAmbiguous = false(fateCount,1);
for fateIndex = 1:fateCount
    outcome = terminalFates.Outcome(fateIndex);
    if outcome == "correct"
        failureMode(fateIndex) = "delivered";
        continue
    elseif outcome == "blocked"
        failureMode(fateIndex) = "blocked";
        continue
    end

    evidenceRows = counterfactualEvidence( ...
        evidenceRowGroups{fateIndex},:);
    if isempty(evidenceRows)
        if options.EvidenceIsExhaustive
            failureMode(fateIndex) = "noise_or_propagation";
        else
            failureMode(fateIndex) = ...
                "unclassified_missing_counterfactual";
            isAmbiguous(fateIndex) = true;
        end
        continue
    end
    if any( ...
            evidenceRows.ObservedSinrDb >= ...
            evidenceRows.DecodeThresholdDb)
        error( ...
            "v2xsim:analysis:InconsistentCounterfactualEvidence", ...
            "Terminal error evidence must have observed SINR below " + ...
            "the sampled decode threshold.");
    end

    isHalfDuplex = ...
        evidenceRows.ResourceRelation == "half_duplex";
    isSufficient = ...
        evidenceRows.SinrWithoutInterfererDb >= ...
        evidenceRows.DecodeThresholdDb;
    sufficientRows = evidenceRows(isSufficient,:);
    causalInterfererCount(fateIndex) = ...
        height(sufficientRows);
    if ~isempty(sufficientRows)
        culpritUeIds(fateIndex) = strjoin( ...
            unique( ...
                sufficientRows.InterfererUeId,"stable"),";");
    end
    isHiddenTerminal(fateIndex) = any( ...
        isSufficient & ...
        evidenceRows.IsHarmfulReuseCandidate & ...
        ismember( ...
            evidenceRows.ResourceRelation, ...
            ["cochannel","adjacent_channel","other"]));

    if any(isHalfDuplex)
        failureMode(fateIndex) = "half_duplex";
        isAmbiguous(fateIndex) = ...
            nnz(isHalfDuplex) > 1 || ...
            any(isSufficient & ~isHalfDuplex);
    elseif height(sufficientRows) > 1
        failureMode(fateIndex) = ...
            "multiple_sufficient_interferers";
        isAmbiguous(fateIndex) = true;
    elseif height(sufficientRows) == 1
        relation = sufficientRows.ResourceRelation(1);
        if isHiddenTerminal(fateIndex)
            failureMode(fateIndex) = "hidden_terminal";
        elseif relation == "cochannel"
            failureMode(fateIndex) = ...
                "cochannel_interference";
        elseif relation == "adjacent_channel"
            failureMode(fateIndex) = ...
                "adjacent_channel_interference";
        elseif relation == "cross_technology"
            failureMode(fateIndex) = ...
                "cross_technology_interference";
        else
            failureMode(fateIndex) = "other_interference";
        end
    elseif jointRemovalSucceeds(evidenceRows)
        failureMode(fateIndex) = "joint_interference";
        culpritUeIds(fateIndex) = strjoin( ...
            unique(evidenceRows.InterfererUeId,"stable"),";");
        isAmbiguous(fateIndex) = true;
    elseif options.EvidenceIsExhaustive
        failureMode(fateIndex) = "noise_or_propagation";
    else
        failureMode(fateIndex) = ...
            "unclassified_incomplete_counterfactual";
        isAmbiguous(fateIndex) = true;
    end
end

classified = terminalFates;
classified.FailureMode = failureMode;
classified.CulpritUeIds = culpritUeIds;
classified.CausalInterfererCount = causalInterfererCount;
classified.IsHiddenTerminal = isHiddenTerminal;
classified.IsAmbiguous = isAmbiguous;
end

function validateEvidence(evidence)
requiredNames = [ ...
    "Technology","TransmitterUeId","ReceiverUeId", ...
    "PacketSequence","AttemptNumber","InterfererUeId", ...
    "ResourceRelation","ObservedSinrDb","DecodeThresholdDb", ...
    "SinrWithoutInterfererDb","IsHarmfulReuseCandidate"];
optionalNames = "SinrWithoutAllInterferersDb";
actualNames = string(evidence.Properties.VariableNames);
if ~all(ismember(requiredNames,actualNames)) || ...
        any(~ismember(actualNames,[requiredNames,optionalNames]))
    error( ...
        "v2xsim:analysis:InvalidCounterfactualEvidence", ...
        "Counterfactual evidence must contain %s.", ...
        strjoin(requiredNames,", "));
end

stringNames = [ ...
    "Technology","TransmitterUeId","ReceiverUeId", ...
    "InterfererUeId","ResourceRelation"];
for variableName = stringNames
    values = evidence.(variableName);
    if ~isstring(values) || ~iscolumn(values) || ...
            any(ismissing(values)) || ...
            any(strlength(strip(values)) == 0) || ...
            any(values ~= strip(values))
        error( ...
            "v2xsim:analysis:InvalidCounterfactualEvidence", ...
            "%s must contain nonblank string values.",variableName);
    end
end
if any(~ismember( ...
        evidence.ResourceRelation, ...
        ["cochannel","adjacent_channel","cross_technology", ...
        "half_duplex","other"]))
    error( ...
        "v2xsim:analysis:InvalidCounterfactualEvidence", ...
        "ResourceRelation contains an unsupported mechanism.");
end

integerNames = ["PacketSequence","AttemptNumber"];
for variableName = integerNames
    values = evidence.(variableName);
    if ~isnumeric(values) || ~iscolumn(values) || ...
            any(~isfinite(values)) || any(values < 1) || ...
            any(fix(values) ~= values)
        error( ...
            "v2xsim:analysis:InvalidCounterfactualEvidence", ...
            "%s must contain positive integer values.",variableName);
    end
end
numericNames = [ ...
    "ObservedSinrDb","DecodeThresholdDb", ...
    "SinrWithoutInterfererDb"];
if ismember(optionalNames,actualNames)
    numericNames(end + 1) = optionalNames;
end
for variableName = numericNames
    values = evidence.(variableName);
    if ~isnumeric(values) || ~iscolumn(values) || ...
            ~isreal(values) || any(isnan(values))
        error( ...
            "v2xsim:analysis:InvalidCounterfactualEvidence", ...
            "%s must contain real non-NaN values.",variableName);
    end
end
if ~islogical(evidence.IsHarmfulReuseCandidate) || ...
        ~iscolumn(evidence.IsHarmfulReuseCandidate)
    error( ...
        "v2xsim:analysis:InvalidCounterfactualEvidence", ...
        "IsHarmfulReuseCandidate must be a logical column.");
end

identityNames = [ ...
    "Technology","TransmitterUeId","ReceiverUeId", ...
    "PacketSequence","AttemptNumber","InterfererUeId"];
if height(unique(evidence(:,identityNames),"rows")) ~= ...
        height(evidence)
    error( ...
        "v2xsim:analysis:DuplicateCounterfactualEvidence", ...
        "Counterfactual evidence must contain one row per packet " + ...
        "attempt and interferer.");
end

packetIdentityNames = identityNames(1:end - 1);
if ~isempty(evidence)
    packetGroups = findgroups( ...
        evidence(:,packetIdentityNames));
    observedIsConsistent = splitapply( ...
        @(values) all(values == values(1)), ...
        evidence.ObservedSinrDb,packetGroups);
    thresholdIsConsistent = splitapply( ...
        @(values) all(values == values(1)), ...
        evidence.DecodeThresholdDb,packetGroups);
    if any(~observedIsConsistent) || ...
            any(~thresholdIsConsistent)
        error( ...
            "v2xsim:analysis:" + ...
            "InconsistentCounterfactualEvidence", ...
            "Observed SINR and sampled threshold must be " + ...
            "constant across interferers for one packet attempt.");
    end
    if ismember(optionalNames,actualNames)
        allRemovalIsConsistent = splitapply( ...
            @(values) all(values == values(1)), ...
            evidence.SinrWithoutAllInterferersDb, ...
            packetGroups);
        if any(~allRemovalIsConsistent)
            error( ...
                "v2xsim:analysis:" + ...
                "InconsistentCounterfactualEvidence", ...
                "The all-interferer counterfactual must be constant " + ...
                "within one packet attempt.");
        end
    end
end
end

function [evidenceFateRows,evidenceRowGroups] = ...
        validateEvidenceJoins(fates,evidence)
identityNames = [ ...
    "Technology","TransmitterUeId","ReceiverUeId", ...
    "PacketSequence"];
[isKnown,evidenceFateRows] = ismember( ...
    evidence(:,identityNames), ...
    fates(:,identityNames),"rows");
if any(~isKnown)
    error( ...
        "v2xsim:analysis:OrphanCounterfactualEvidence", ...
        "Every counterfactual row must identify a terminal " + ...
        "directed packet attempt.");
end
if ~isempty(evidence)
    fateAttempts = fates.AttemptNumber(evidenceFateRows);
    if any( ...
            ~isnan(fateAttempts) & ...
            fateAttempts ~= evidence.AttemptNumber)
        error( ...
            "v2xsim:analysis:OrphanCounterfactualEvidence", ...
            "Every counterfactual row must identify a terminal " + ...
            "directed packet attempt.");
    end
end
evidenceRowGroups = cell(height(fates),1);
if isempty(evidence)
    return
end
[sortedFateRows,rowOrder] = sort(evidenceFateRows);
groupStarts = [1;find(diff(sortedFateRows) ~= 0) + 1];
groupEnds = [groupStarts(2:end) - 1;height(evidence)];
for groupIndex = 1:numel(groupStarts)
    fateRow = sortedFateRows(groupStarts(groupIndex));
    evidenceRowGroups{fateRow} = ...
        rowOrder( ...
            groupStarts(groupIndex):groupEnds(groupIndex));
end
end

function tf = jointRemovalSucceeds(evidence)
variableNames = string(evidence.Properties.VariableNames);
if ~ismember("SinrWithoutAllInterferersDb",variableNames)
    tf = false;
    return
end
tf = any( ...
    evidence.SinrWithoutAllInterferersDb >= ...
    evidence.DecodeThresholdDb);
end
