function manifest = createExposedReuseShadowManifest( ...
        reuseCandidates,options)
%CREATEEXPOSEDREUSESHADOWMANIFEST Plan same-state PHY branch evaluations.
%   Each missed-reuse event becomes one candidate-specific shadow case.
%   A future executor must fork the complete simulator state at the
%   recorded allocation decision, replay the control branch, and evaluate
%   an intervention branch in which both endpoints use the common
%   true-geometry-oracle resource until the next allocation decision.
%   Independent replications restart from the same fork to obtain the
%   required receiver observations without turning one event into a
%   persistent resource-locking policy. This function plans those
%   evaluations; it does not predict radio performance from geometry.

arguments (Input)
    reuseCandidates table
    options.SourceRunId (1,1) string = "source"
    options.EvaluationHorizonSeconds (1,1) double ...
        {mustBeReal,mustBeFinite,mustBePositive} = 0.1
    options.AllocationIntervalSeconds (1,1) double ...
        {mustBeReal,mustBeFinite,mustBePositive} = 0.1
    options.AnalysisRangeMeters (1,1) double ...
        {mustBeReal,mustBeFinite,mustBePositive} = 300
    options.MinimumReceiverObservationCount (1,1) double ...
        {mustBeInteger,mustBePositive} = 10
    options.MaximumCases (1,1) double ...
        {mustBeReal,mustBePositive} = Inf
    options.SelectionSeed (1,1) double ...
        {mustBeInteger,mustBeNonnegative} = 0
end
arguments (Output)
    manifest table
end

sourceRunId = strip(options.SourceRunId);
if ismissing(sourceRunId) || strlength(sourceRunId) == 0
    error( ...
        "v2xsim:analysis:InvalidShadowSourceRunId", ...
        "SourceRunId must be nonblank.");
end
if ~isinf(options.MaximumCases) && ...
        (~isfinite(options.MaximumCases) || ...
        fix(options.MaximumCases) ~= options.MaximumCases)
    error( ...
        "v2xsim:analysis:InvalidMaximumShadowCases", ...
        "MaximumCases must be a positive integer or Inf.");
end
if options.SelectionSeed > double(intmax("uint32"))
    error( ...
        "v2xsim:analysis:ShadowSelectionSeedOutOfRange", ...
        "SelectionSeed must fit in an unsigned 32-bit integer.");
end
if options.EvaluationHorizonSeconds > ...
        options.AllocationIntervalSeconds
    error( ...
        "v2xsim:analysis:ShadowHorizonCrossesAllocationDecision", ...
        "EvaluationHorizonSeconds cannot extend beyond the next " + ...
        "allocation decision for the single-epoch intervention.");
end

validateCandidates(reuseCandidates);
missed = reuseCandidates( ...
    string(reuseCandidates.CandidateType) == "missed_reuse" & ...
    string(reuseCandidates.LiveResourceRelation) == ...
        "separate_time" & ...
    string(reuseCandidates.OracleResourceRelation) == ...
        "cochannel",:);
missed = canonicalOrder(missed);
candidateCount = height(missed);
selectionProbability = 1;
if candidateCount > options.MaximumCases
    selectionProbability = options.MaximumCases ./ candidateCount;
    selectionStream = RandStream( ...
        "mt19937ar",Seed=options.SelectionSeed);
    priorities = rand(selectionStream,candidateCount,1);
    selection = table( ...
        priorities,(1:candidateCount).', ...
        VariableNames=["Priority","CandidateRow"]);
    selection = sortrows( ...
        selection,["Priority","CandidateRow"]);
    selectedRows = sort( ...
        selection.CandidateRow(1:options.MaximumCases));
    missed = missed(selectedRows,:);
end

caseCount = height(missed);
caseNumber = (1:caseCount).';
shadowCaseId = sourceRunId + compose( ...
    "|shadow-case-%08u",uint32(caseNumber));
interventionResourceId = ...
    double(missed.OracleFirstResourceId);
manifest = table( ...
    shadowCaseId,repmat(sourceRunId,caseCount,1), ...
    double(missed.SimulationTimeSeconds), ...
    uint64(missed.AllocationEpoch), ...
    string(missed.NetworkSliceId), ...
    string(missed.FirstUeId),string(missed.SecondUeId), ...
    repmat("missed_reuse",caseCount,1), ...
    double(missed.LiveFirstResourceId), ...
    double(missed.LiveSecondResourceId), ...
    interventionResourceId,interventionResourceId, ...
    repmat(options.EvaluationHorizonSeconds,caseCount,1), ...
    repmat(options.AllocationIntervalSeconds,caseCount,1), ...
    repmat( ...
        "single_epoch_replicated_from_fork",caseCount,1), ...
    true(caseCount,1), ...
    repmat( ...
        options.MinimumReceiverObservationCount,caseCount,1), ...
    repmat(options.AnalysisRangeMeters,caseCount,1), ...
    repmat( ...
        options.MinimumReceiverObservationCount,caseCount,1), ...
    true(caseCount,1),true(caseCount,1),true(caseCount,1), ...
    repmat( ...
        "same_technology_endpoint_links_in_" + ...
        "true_range_at_fork",caseCount,1), ...
    repmat(selectionProbability,caseCount,1), ...
    repmat(1 ./ selectionProbability,caseCount,1), ...
    repmat("shadow_run_required",caseCount,1), ...
    VariableNames=[ ...
        "ShadowCaseId","SourceRunId", ...
        "SimulationTimeSeconds","AllocationEpoch", ...
        "NetworkSliceId","FirstUeId","SecondUeId", ...
        "CandidateType","ControlFirstResourceId", ...
        "ControlSecondResourceId", ...
        "InterventionFirstResourceId", ...
        "InterventionSecondResourceId", ...
        "EvaluationHorizonSeconds","AllocationIntervalSeconds", ...
        "InterventionPolicy", ...
        "StopBeforeNextAllocationDecision", ...
        "RequiredIndependentReplicateCount", ...
        "AnalysisRangeMeters", ...
        "MinimumReceiverObservationCount", ...
        "StateSnapshotRequired","ControlReplayRequired", ...
        "CommonRandomNumbersRequired", ...
        "ReceiverRosterDefinition", ...
        "SelectionProbability","AnalysisWeight", ...
        "OpportunityStatus"]);
end

function validateCandidates(candidates)
requiredNames = [ ...
    "SimulationTimeSeconds","AllocationEpoch","NetworkSliceId", ...
    "FirstUeId","SecondUeId","CandidateType", ...
    "LiveResourceRelation","OracleResourceRelation", ...
    "LiveFirstResourceId","LiveSecondResourceId", ...
    "OracleFirstResourceId","OracleSecondResourceId"];
actualNames = string(candidates.Properties.VariableNames);
if any(~ismember(requiredNames,actualNames))
    error( ...
        "v2xsim:analysis:InvalidShadowReuseCandidates", ...
        "Reuse candidates must contain %s.", ...
        strjoin(requiredNames,", "));
end

stringNames = [ ...
    "NetworkSliceId","FirstUeId","SecondUeId","CandidateType", ...
    "LiveResourceRelation","OracleResourceRelation"];
for variableName = stringNames
    values = string(candidates.(variableName));
    if any(ismissing(values)) || ...
            any(strlength(strip(values)) == 0)
        error( ...
            "v2xsim:analysis:InvalidShadowReuseCandidates", ...
            "%s must contain nonblank values.",variableName);
    end
end
candidateTypes = string(candidates.CandidateType);
if any(~ismember( ...
        candidateTypes, ...
        ["harmful_reuse","missed_reuse", ...
        "unchanged_overlap","unchanged_separation"]))
    error( ...
        "v2xsim:analysis:InvalidShadowReuseCandidates", ...
        "CandidateType contains an unsupported classification.");
end
validRelations = [ ...
    "unassigned","separate_time","cochannel", ...
    "adjacent_channel","other_same_time"];
if any(~ismember( ...
        string(candidates.LiveResourceRelation),validRelations)) || ...
        any(~ismember( ...
            string(candidates.OracleResourceRelation),validRelations))
    error( ...
        "v2xsim:analysis:InvalidShadowReuseCandidates", ...
        "LiveResourceRelation and OracleResourceRelation contain " + ...
        "an unsupported value.");
end
firstUeIds = string(candidates.FirstUeId);
secondUeIds = string(candidates.SecondUeId);
if any(firstUeIds >= secondUeIds)
    error( ...
        "v2xsim:analysis:InvalidShadowReuseCandidates", ...
        "Candidate pair identities must be canonicalized.");
end

time = candidates.SimulationTimeSeconds;
epoch = candidates.AllocationEpoch;
if ~isnumeric(time) || ~iscolumn(time) || ...
        any(~isfinite(time)) || any(time < 0) || ...
        ~isnumeric(epoch) || ~iscolumn(epoch) || ...
        any(~isfinite(epoch)) || any(epoch < 0) || ...
        any(fix(epoch) ~= epoch)
    error( ...
        "v2xsim:analysis:InvalidShadowReuseCandidates", ...
        "Candidate times and allocation epochs are invalid.");
end

resourceNames = [ ...
    "LiveFirstResourceId","LiveSecondResourceId", ...
    "OracleFirstResourceId","OracleSecondResourceId"];
for variableName = resourceNames
    values = candidates.(variableName);
    if ~isnumeric(values) || ~iscolumn(values) || ...
            any(~isfinite(values)) || any(values < 1) || ...
            any(fix(values) ~= values)
        error( ...
            "v2xsim:analysis:InvalidShadowReuseCandidates", ...
            "%s must contain positive integer resources.", ...
            variableName);
    end
end

isMissed = candidateTypes == "missed_reuse";
if any( ...
        candidates.LiveFirstResourceId(isMissed) == ...
        candidates.LiveSecondResourceId(isMissed)) || ...
        any( ...
            candidates.OracleFirstResourceId(isMissed) ~= ...
            candidates.OracleSecondResourceId(isMissed)) || ...
        any( ...
            string(candidates.OracleResourceRelation(isMissed)) ~= ...
                "cochannel")
    error( ...
        "v2xsim:analysis:InconsistentMissedReuseCandidate", ...
        "A missed-reuse pair must use unequal live resources and " + ...
        "share a cochannel true-geometry-oracle resource.");
end

identity = table( ...
    double(time),uint64(epoch),string(candidates.NetworkSliceId), ...
    firstUeIds,secondUeIds, ...
    VariableNames=[ ...
        "SimulationTimeSeconds","AllocationEpoch", ...
        "NetworkSliceId","FirstUeId","SecondUeId"]);
if height(unique(identity,"rows")) ~= height(identity)
    error( ...
        "v2xsim:analysis:DuplicateShadowReuseCandidate", ...
        "Each allocation-epoch candidate pair must occur once.");
end
end

function ordered = canonicalOrder(candidates)
if isempty(candidates)
    ordered = candidates;
    return
end
sortNames = [ ...
    "SimulationTimeSeconds","AllocationEpoch", ...
    "NetworkSliceId","FirstUeId","SecondUeId"];
ordered = sortrows(candidates,sortNames);
end
