function rows = emptyInterferenceCounterfactualTrace()
%EMPTYINTERFERENCECOUNTERFACTUALTRACE Canonical per-interferer schema.

rows = table( ...
    zeros(0,1),strings(0,1), ...
    zeros(0,1),strings(0,1), ...
    zeros(0,1),strings(0,1), ...
    zeros(0,1),false(0,1), ...
    zeros(0,1),zeros(0,1), ...
    zeros(0,1),zeros(0,1),zeros(0,1), ...
    zeros(0,1),strings(0,1), ...
    strings(0,1),strings(0,1), ...
    zeros(0,1),zeros(0,1), ...
    strings(0,1),zeros(0,1), ...
    zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1), ...
    false(0,1), ...
    VariableNames=[ ...
        "EvidenceTimeSeconds","Technology", ...
        "TransmitterId","TransmitterUeId", ...
        "ReceiverId","ReceiverUeId", ...
        "PacketSequence","PacketSequenceAligned", ...
        "GenerationTimeSeconds","AttemptNumber", ...
        "ResourceId","FrequencyResourceId","AllocationEpoch", ...
        "InterfererId","InterfererUeId", ...
        "ReusePairFirstUeId","ReusePairSecondUeId", ...
        "InterfererResourceId","InterfererFrequencyResourceId", ...
        "ResourceRelation","RemovedInterferencePower", ...
        "ObservedSinrDb","DecodeThresholdDb", ...
        "SinrWithoutInterfererDb", ...
        "SinrWithoutAllInterferersDb", ...
        "EvidenceIsExhaustive"]);
end
