function fates = emptyTerminalPacketFateTable()
%EMPTYTERMINALPACKETFATETABLE Canonical directed packet-fate schema.

fates = table( ...
    zeros(0,1),strings(0,1), ...
    zeros(0,1),strings(0,1), ...
    zeros(0,1),strings(0,1), ...
    zeros(0,1),zeros(0,1),zeros(0,1), ...
    strings(0,1),zeros(0,1),zeros(0,1), ...
    zeros(0,1),zeros(0,1),zeros(0,1), ...
    zeros(0,1),zeros(0,1), ...
    VariableNames=[ ...
        "FateTimeSeconds","Technology", ...
        "TransmitterId","TransmitterUeId", ...
        "ReceiverId","ReceiverUeId", ...
        "PacketSequence","GenerationTimeSeconds", ...
        "AttemptNumber","Outcome","Channel","PacketType", ...
        "TrueDistanceMeters","ResourceId", ...
        "TimeResourceId","FrequencyResourceId", ...
        "AllocationEpoch"]);
end
