function rows = emptyInterferenceAttemptTrace()
%EMPTYINTERFERENCEATTEMPTTRACE Canonical terminal PHY-attempt schema.

rows = table( ...
    zeros(0,1),strings(0,1), ...
    zeros(0,1),strings(0,1), ...
    zeros(0,1),strings(0,1), ...
    zeros(0,1),false(0,1), ...
    zeros(0,1),zeros(0,1), ...
    zeros(0,1),zeros(0,1),zeros(0,1), ...
    strings(0,1), ...
    zeros(0,1),zeros(0,1),zeros(0,1), ...
    zeros(0,1),false(0,1), ...
    VariableNames=[ ...
        "EvidenceTimeSeconds","Technology", ...
        "TransmitterId","TransmitterUeId", ...
        "ReceiverId","ReceiverUeId", ...
        "PacketSequence","PacketSequenceAligned", ...
        "GenerationTimeSeconds","AttemptNumber", ...
        "ResourceId","FrequencyResourceId","AllocationEpoch", ...
        "Outcome","ObservedSinrDb","DecodeThresholdDb", ...
        "SinrWithoutAllInterferersDb","InterfererCount", ...
        "EvidenceIsExhaustive"]);
end
