function score = normalizedPrrAuc( ...
        curve,maximumDistanceMeters,options)
%NORMALIZEDPRRAUC Score a complete fixed-grid PRR curve.
%   The curve is anchored at distance zero with PRR one, integrated through
%   MAXIMUMDISTANCEMETERS, and normalized by that distance.

arguments (Input)
    curve table
    maximumDistanceMeters (1,1) double ...
        {mustBeReal,mustBeFinite,mustBePositive}
    options.Metric (1,1) string = "DeliveryPrr"
    options.RequireNonemptyBins (1,1) logical = true
end
arguments (Output)
    score (1,1) double
end

metric = validatestring( ...
    options.Metric,["DeliveryPrr","RadioPrr"]);
requiredNames = [ ...
    "DistanceUpperBoundMeters",metric,"TotalCount", ...
    "RadioAttemptCount"];
if any(~ismember( ...
        requiredNames,string(curve.Properties.VariableNames)))
    error( ...
        "v2xsim:analysis:InvalidPrrCurveSchema", ...
        "PRR curve must contain %s.",strjoin(requiredNames,", "));
end

curve = curve( ...
    curve.DistanceUpperBoundMeters <= ...
    maximumDistanceMeters,:);
curve = sortrows(curve,"DistanceUpperBoundMeters");
distances = curve.DistanceUpperBoundMeters;
if isempty(curve) || ...
        distances(end) ~= maximumDistanceMeters || ...
        numel(unique(distances)) ~= numel(distances) || ...
        any(~isfinite(distances)) || any(distances <= 0) || ...
        any(diff(distances) <= 0)
    error( ...
        "v2xsim:analysis:IncompletePrrCurve", ...
        "One unique increasing fixed-grid curve must reach the " + ...
        "requested maximum distance.");
end

if metric == "DeliveryPrr"
    denominators = curve.TotalCount;
else
    denominators = curve.RadioAttemptCount;
end
ratios = curve.(metric);
if options.RequireNonemptyBins && ...
        (any(denominators <= 0) || any(~isfinite(ratios)))
    error( ...
        "v2xsim:analysis:IncompletePrrCurve", ...
        "Every scored distance bin must contain observations.");
end
if any(~isfinite(ratios)) || any(ratios < 0) || any(ratios > 1)
    error( ...
        "v2xsim:analysis:InvalidPrrCurveValues", ...
        "Scored PRR values must be finite probabilities.");
end

score = trapz( ...
    [0;distances],[1;ratios]) ./ ...
    maximumDistanceMeters;
end
