function metrics = perVehiclePacketReceptionMetrics( ...
        terminalFates,distanceGridMeters)
%PERVEHICLEPACKETRECEPTIONMETRICS Summarize both endpoint perspectives.
%   One row is returned for every technology/vehicle and for each of the
%   "transmitter" and "receiver" perspectives. Counts and pooled ratios
%   cover the fixed distance grid. Delivery and radio AUCs are reported
%   only when every corresponding grid bin has a denominator; Status
%   columns make sparse per-vehicle curves explicit.

arguments (Input)
    terminalFates table
    distanceGridMeters (:,1) double ...
        {mustBeReal,mustBeFinite,mustBePositive}
end
arguments (Output)
    metrics table
end

if isempty(distanceGridMeters) || ...
        any(diff(distanceGridMeters) <= 0)
    error( ...
        "v2xsim:analysis:InvalidPrrDistanceGrid", ...
        "Distance grid values must be strictly increasing.");
end
terminalFates = ...
    v2xsim.analysis.aggregateTerminalPacketFates( ...
        terminalFates);
if isempty(terminalFates)
    metrics = emptyMetrics();
    return
end

technologies = unique(terminalFates.Technology,"stable");
technologyMetrics = cell(numel(technologies),1);
for technologyIndex = 1:numel(technologies)
    technology = technologies(technologyIndex);
    technologyFates = terminalFates( ...
        terminalFates.Technology == technology,:);
    technologyMetrics{technologyIndex} = summarizeTechnology( ...
        technologyFates,technology,distanceGridMeters);
end

metrics = vertcat(technologyMetrics{:});
metrics = sortrows( ...
    metrics,["Technology","VehicleUeId","Perspective"]);
end

function metrics = summarizeTechnology( ...
        fates,technology,distanceGridMeters)
vehicleIds = unique( ...
    [fates.TransmitterUeId;fates.ReceiverUeId],"stable");
vehicleCount = numel(vehicleIds);
binCount = numel(distanceGridMeters);
[~,transmitterGroups] = ismember( ...
    fates.TransmitterUeId,vehicleIds);
[~,receiverGroups] = ismember( ...
    fates.ReceiverUeId,vehicleIds);

% The overflow edge preserves the original half-open grid bins:
% [0,g(1)), [g(1),g(2)), ..., with g(end) excluded.
binIndices = discretize( ...
    fates.TrueDistanceMeters, ...
    [-Inf;distanceGridMeters;Inf]);
outcomeIndices = ones(height(fates),1);
outcomeIndices(fates.Outcome == "error") = 2;
outcomeIndices(fates.Outcome == "blocked") = 3;

transmitterBins = accumulateBins( ...
    transmitterGroups,binIndices,outcomeIndices, ...
    vehicleCount,binCount);
receiverBins = accumulateBins( ...
    receiverGroups,binIndices,outcomeIndices, ...
    vehicleCount,binCount);
correctBins = [ ...
    transmitterBins(:,:,1);receiverBins(:,:,1)];
errorBins = [ ...
    transmitterBins(:,:,2);receiverBins(:,:,2)];
blockedBins = [ ...
    transmitterBins(:,:,3);receiverBins(:,:,3)];
totalBins = correctBins + errorBins + blockedBins;
radioBins = correctBins + errorBins;

correctCount = sum(correctBins,2);
errorCount = sum(errorBins,2);
blockedCount = sum(blockedBins,2);
totalCount = sum(totalBins,2);
radioAttemptCount = sum(radioBins,2);
deliveryPrr = divideOrNan(correctCount,totalCount);
radioPrr = divideOrNan(correctCount,radioAttemptCount);
blockingRate = divideOrNan(blockedCount,totalCount);
nonemptyDeliveryBinCount = sum(totalBins > 0,2);
nonemptyRadioBinCount = sum(radioBins > 0,2);

transmitterFateCounts = accumarray( ...
    transmitterGroups,1,[vehicleCount,1]);
receiverFateCounts = accumarray( ...
    receiverGroups,1,[vehicleCount,1]);
hasTerminalFates = ...
    [transmitterFateCounts;receiverFateCounts] > 0;
hasFatesWithinGrid = totalCount > 0;

deliveryPrrAucStatus = repmat( ...
    "NoTerminalFates",2 .* vehicleCount,1);
radioPrrAucStatus = deliveryPrrAucStatus;
outsideGridOnly = hasTerminalFates & ~hasFatesWithinGrid;
deliveryPrrAucStatus(outsideGridOnly) = ...
    "NoFatesWithinDistanceGrid";
radioPrrAucStatus(outsideGridOnly) = ...
    "NoFatesWithinDistanceGrid";

completeDeliveryCurve = ...
    hasFatesWithinGrid & all(totalBins > 0,2);
incompleteDeliveryCurve = ...
    hasFatesWithinGrid & ~completeDeliveryCurve;
deliveryPrrAucStatus(completeDeliveryCurve) = "Complete";
deliveryPrrAucStatus(incompleteDeliveryCurve) = ...
    "IncompleteDistanceGrid";

hasRadioAttempts = radioAttemptCount > 0;
noRadioAttempts = hasFatesWithinGrid & ~hasRadioAttempts;
radioPrrAucStatus(noRadioAttempts) = "NoRadioAttempts";
completeRadioCurve = ...
    hasRadioAttempts & all(radioBins > 0,2);
incompleteRadioCurve = ...
    hasRadioAttempts & ~completeRadioCurve;
radioPrrAucStatus(completeRadioCurve) = "Complete";
radioPrrAucStatus(incompleteRadioCurve) = ...
    "IncompleteDistanceGrid";

deliveryBinPrr = divideOrNan(correctBins,totalBins);
radioBinPrr = divideOrNan(correctBins,radioBins);
deliveryPrrAuc = calculateAuc( ...
    deliveryBinPrr,completeDeliveryCurve,distanceGridMeters);
radioPrrAuc = calculateAuc( ...
    radioBinPrr,completeRadioCurve,distanceGridMeters);

rowCount = 2 .* vehicleCount;
metrics = table( ...
    repmat(technology,rowCount,1), ...
    [vehicleIds;vehicleIds], ...
    [repmat("transmitter",vehicleCount,1); ...
    repmat("receiver",vehicleCount,1)], ...
    repmat(distanceGridMeters(end),rowCount,1), ...
    repmat(binCount,rowCount,1), ...
    nonemptyDeliveryBinCount,nonemptyRadioBinCount, ...
    correctCount,errorCount,blockedCount,totalCount, ...
    radioAttemptCount,deliveryPrr,radioPrr,blockingRate, ...
    deliveryPrrAuc,radioPrrAuc, ...
    deliveryPrrAucStatus,radioPrrAucStatus, ...
    VariableNames=string( ...
        emptyMetrics().Properties.VariableNames));
end

function counts = accumulateBins( ...
        groupIndices,binIndices,outcomeIndices, ...
        groupCount,binCount)
withinGrid = binIndices <= binCount;
if any(withinGrid)
    counts = accumarray( ...
        [groupIndices(withinGrid), ...
        binIndices(withinGrid), ...
        outcomeIndices(withinGrid)], ...
        1,[groupCount,binCount,3]);
else
    counts = zeros(groupCount,binCount,3);
end
end

function scores = calculateAuc( ...
        ratios,completeRows,distanceGridMeters)
scores = nan(size(ratios,1),1);
if ~any(completeRows)
    return
end
anchoredRatios = [ ...
    ones(1,nnz(completeRows)); ...
    ratios(completeRows,:).'];
scores(completeRows) = trapz( ...
    [0;distanceGridMeters],anchoredRatios,1).' ./ ...
    distanceGridMeters(end);
end

function values = divideOrNan(numerator,denominator)
values = nan(size(numerator));
hasDenominator = denominator > 0;
values(hasDenominator) = ...
    numerator(hasDenominator) ./ denominator(hasDenominator);
end

function metrics = emptyMetrics()
metrics = table( ...
    strings(0,1),strings(0,1),strings(0,1), ...
    zeros(0,1),zeros(0,1),zeros(0,1),zeros(0,1), ...
    zeros(0,1),zeros(0,1),zeros(0,1), ...
    zeros(0,1),zeros(0,1), ...
    zeros(0,1),zeros(0,1),zeros(0,1), ...
    zeros(0,1),zeros(0,1),strings(0,1),strings(0,1), ...
    VariableNames=[ ...
        "Technology","VehicleUeId","Perspective", ...
        "MaximumDistanceMeters","DistanceBinCount", ...
        "NonemptyDeliveryBinCount","NonemptyRadioBinCount", ...
        "CorrectCount","ErrorCount","BlockedCount", ...
        "TotalCount","RadioAttemptCount", ...
        "DeliveryPrr","RadioPrr","BlockingRate", ...
        "DeliveryPrrAuc","RadioPrrAuc", ...
        "DeliveryPrrAucStatus","RadioPrrAucStatus"]);
end
