function pooled = poolPacketReceptionCounts(curves,options)
%POOLPACKETRECEPTIONCOUNTS Pool PRR numerators before computing ratios.
%   CURVES may contain rows from multiple seeds. Counts are summed for each
%   requested group and fixed-grid distance before any ratio is computed.

arguments (Input)
    curves table
    options.GroupVariables (1,:) string = ...
        ["Technology","Channel","PacketType"]
end
arguments (Output)
    pooled table
end

requiredNames = [ ...
    options.GroupVariables,"DistanceUpperBoundMeters", ...
    "CorrectCount","ErrorCount","BlockedCount"];
actualNames = string(curves.Properties.VariableNames);
if numel(unique(options.GroupVariables)) ~= ...
        numel(options.GroupVariables) || ...
        any(~ismember(requiredNames,actualNames))
    error( ...
        "v2xsim:analysis:InvalidPrrCountSchema", ...
        "PRR count rows must contain grouping, distance, and fate counts.");
end

countNames = ["CorrectCount","ErrorCount","BlockedCount"];
for variableName = countNames
    values = curves.(variableName);
    if ~isnumeric(values) || ~iscolumn(values) || ...
            any(~isfinite(values)) || any(values < 0) || ...
            any(fix(values) ~= values)
        error( ...
            "v2xsim:analysis:InvalidPrrCounts", ...
            "%s must contain nonnegative integer counts.", ...
            variableName);
    end
end
distances = curves.DistanceUpperBoundMeters;
if ~isnumeric(distances) || ~iscolumn(distances) || ...
        any(~isfinite(distances)) || any(distances <= 0)
    error( ...
        "v2xsim:analysis:InvalidPrrDistanceGrid", ...
        "DistanceUpperBoundMeters must be finite and positive.");
end

keyNames = [ ...
    options.GroupVariables,"DistanceUpperBoundMeters"];
if isempty(curves)
    pooled = curves(:,requiredNames);
    pooled = addMetrics(pooled);
    return
end
[groupIndices,keyRows] = findgroups(curves(:,keyNames));
pooled = [ ...
    keyRows,table( ...
        splitapply(@sum,curves.CorrectCount,groupIndices), ...
        splitapply(@sum,curves.ErrorCount,groupIndices), ...
        splitapply(@sum,curves.BlockedCount,groupIndices), ...
        VariableNames=countNames)];
pooled = sortrows(pooled,keyNames);
pooled = addMetrics(pooled);
end

function pooled = addMetrics(pooled)
pooled.TotalCount = ...
    pooled.CorrectCount + pooled.ErrorCount + pooled.BlockedCount;
pooled.RadioAttemptCount = ...
    pooled.CorrectCount + pooled.ErrorCount;
pooled.DeliveryPrr = divideOrNan( ...
    pooled.CorrectCount,pooled.TotalCount);
pooled.RadioPrr = divideOrNan( ...
    pooled.CorrectCount,pooled.RadioAttemptCount);
pooled.BlockingRate = divideOrNan( ...
    pooled.BlockedCount,pooled.TotalCount);
end

function values = divideOrNan(numerator,denominator)
values = nan(size(numerator));
hasDenominator = denominator > 0;
values(hasDenominator) = ...
    numerator(hasDenominator) ./ denominator(hasDenominator);
end
