function [classified,predictions,linkPredictions,summary] = ...
        reduceExposedReuseShadowResults( ...
            manifest,caseExecutions,receiverRoster, ...
            shadowReceiverCounts,options)
%REDUCEEXPOSEDREUSESHADOWRESULTS Classify completed paired shadow cases.
%   The reducer never treats an oracle allocation as radio evidence.
%   CASEEXECUTIONS must attest that a full-state control replay matched the
%   source and that common random numbers were preserved. RECEIVERROSTER
%   must enumerate the complete receiver scope declared by the manifest.
%   SHADOWRECEIVERCOUNTS contains intervention-branch terminal outcomes.

arguments (Input)
    manifest table
    caseExecutions table
    receiverRoster table
    shadowReceiverCounts table
    options.MinimumPrr (1,1) double ...
        {mustBeReal,mustBeFinite,mustBeNonnegative} = 0.9
    options.PrrDefinition (1,1) string = "delivery"
    options.EmptyNeighborSetIsSafe (1,1) logical = true
end
arguments (Output)
    classified table
    predictions table
    linkPredictions table
    summary (1,1) struct
end

if options.MinimumPrr > 1
    error( ...
        "v2xsim:analysis:InvalidPrrThreshold", ...
        "MinimumPrr cannot exceed one.");
end
prrDefinition = string(validatestring( ...
    options.PrrDefinition,["delivery","radio"]));
validateManifest(manifest);
validateExecutions(caseExecutions,manifest);
validateReceiverRoster(receiverRoster,manifest);
validateReceiverCounts( ...
    shadowReceiverCounts,manifest,receiverRoster);

linkPredictions = buildLinkPredictions( ...
    manifest,receiverRoster,shadowReceiverCounts,prrDefinition);
predictions = collapseLinkPredictions(linkPredictions);
caseCount = height(manifest);
eligibleReceiverCount = zeros(caseCount,1);
coveredReceiverCount = zeros(caseCount,1);
requiredDirectedLinkCount = zeros(caseCount,1);
coveredDirectedLinkCount = zeros(caseCount,1);
minimumPredictedPrr = nan(caseCount,1);
isExposedOpportunity = false(caseCount,1);
opportunityStatus = repmat("shadow_run_required",caseCount,1);

for caseIndex = 1:caseCount
    caseId = manifest.ShadowCaseId(caseIndex);
    rosterRows = receiverRoster.ShadowCaseId == caseId & ...
        receiverRoster.IsSameTechnology & ...
        receiverRoster.IsWithinAnalysisRange;
    eligibleReceiverCount(caseIndex) = numel(unique( ...
        receiverRoster.ReceiverUeId(rosterRows)));
    requiredDirectedLinkCount(caseIndex) = nnz(rosterRows);
    predictionRows = predictions.ShadowCaseId == caseId;
    coveredReceiverCount(caseIndex) = nnz(predictionRows);
    coveredDirectedLinkCount(caseIndex) = nnz( ...
        linkPredictions.ShadowCaseId == caseId);

    executionRow = find( ...
        caseExecutions.ShadowCaseId == caseId,1);
    if isempty(executionRow) || ...
            caseExecutions.ExecutionStatus(executionRow) == "pending"
        continue
    end
    if caseExecutions.ExecutionStatus(executionRow) == "failed" || ...
            ~caseExecutions.StateSnapshotRestored(executionRow) || ...
            ~caseExecutions.ControlReplayMatchedSource(executionRow) || ...
            ~caseExecutions.CommonRandomNumbersVerified(executionRow)
        opportunityStatus(caseIndex) = "invalid_shadow_run";
        continue
    end
    if ~caseExecutions.ReceiverRosterComplete(executionRow) || ...
            ~receiverCoverageIsComplete( ...
                manifest(caseIndex,:),receiverRoster, ...
                shadowReceiverCounts,prrDefinition)
        opportunityStatus(caseIndex) = ...
            "incomplete_receiver_coverage";
        continue
    end

    candidate = manifest( ...
        caseIndex, ...
        ["ShadowCaseId","FirstUeId", ...
        "SecondUeId","CandidateType"]);
    eventPredictions = predictions( ...
        predictionRows, ...
        ["ShadowCaseId","FirstUeId","SecondUeId", ...
        "ReceiverUeId","IsSameTechnology", ...
        "IsWithinAnalysisRange","PredictedPrr"]);
    eventClassification = ...
        v2xsim.analysis.classifyExposedReuseOpportunities( ...
            candidate,eventPredictions, ...
            MinimumPrr=options.MinimumPrr, ...
            PredictionsAreComplete=true, ...
            EmptyNeighborSetIsSafe= ...
                options.EmptyNeighborSetIsSafe, ...
            EventKeyVariables="ShadowCaseId");
    minimumPredictedPrr(caseIndex) = ...
        eventClassification.MinimumPredictedPrr;
    isExposedOpportunity(caseIndex) = ...
        eventClassification.IsExposedOpportunity;
    opportunityStatus(caseIndex) = ...
        eventClassification.OpportunityStatus;
end

classified = manifest;
classified.EligibleReceiverCount = eligibleReceiverCount;
classified.CoveredReceiverCount = coveredReceiverCount;
classified.RequiredDirectedLinkCount = requiredDirectedLinkCount;
classified.CoveredDirectedLinkCount = coveredDirectedLinkCount;
classified.MinimumPredictedPrr = minimumPredictedPrr;
classified.IsExposedOpportunity = isExposedOpportunity;
classified.OpportunityStatus = opportunityStatus;
summary = summarizeClassifiedCases(classified);
end

function summary = summarizeClassifiedCases(classified)
sampledCaseCount = height(classified);
estimatedEligibleCaseCount = sum(classified.AnalysisWeight);
complete = ismember( ...
    classified.OpportunityStatus,["exposed","unsafe"]);
completeCaseCount = nnz(complete);
weightedExposedCount = NaN;
exposedRate = NaN;
if sampledCaseCount == 0
    status = "NoEligibleTemporalCandidates";
elseif all(complete)
    status = "Complete";
    weightedExposedCount = sum( ...
        classified.AnalysisWeight( ...
            classified.IsExposedOpportunity));
    exposedRate = ...
        weightedExposedCount ./ estimatedEligibleCaseCount;
else
    status = "IncompleteShadowEvaluation";
end
summary = struct( ...
    "Status",status, ...
    "SampledCaseCount",sampledCaseCount, ...
    "CompleteCaseCount",completeCaseCount, ...
    "EstimatedEligibleTemporalCandidateCount", ...
        estimatedEligibleCaseCount, ...
    "EstimatedExposedOpportunityCount", ...
        weightedExposedCount, ...
    "ExposedOpportunityRate",exposedRate, ...
    "Estimator","HorvitzThompsonWithKnownCandidateDenominator");
end

function predictions = buildLinkPredictions( ...
        manifest,roster,counts,prrDefinition)
eligibleRoster = roster( ...
    roster.IsSameTechnology & roster.IsWithinAnalysisRange,:);
if isempty(eligibleRoster)
    predictions = emptyLinkPredictions();
    return
end
[hasCounts,countRows] = ismember( ...
    eligibleRoster(:,[ ...
        "ShadowCaseId","TransmitterUeId","ReceiverUeId"]), ...
    counts(:,[ ...
        "ShadowCaseId","TransmitterUeId","ReceiverUeId"]),"rows");
eligibleRoster = eligibleRoster(hasCounts,:);
countRows = countRows(hasCounts);
if isempty(eligibleRoster)
    predictions = emptyLinkPredictions();
    return
end

correctCount = counts.CorrectCount(countRows);
if prrDefinition == "delivery"
    denominator = correctCount + ...
        counts.ErrorCount(countRows) + ...
        counts.BlockedCount(countRows);
else
    denominator = correctCount + counts.ErrorCount(countRows);
end
hasDenominator = denominator > 0;
eligibleRoster = eligibleRoster(hasDenominator,:);
correctCount = correctCount(hasDenominator);
denominator = denominator(hasDenominator);
if isempty(eligibleRoster)
    predictions = emptyLinkPredictions();
    return
end

[hasCase,caseRows] = ismember( ...
    eligibleRoster.ShadowCaseId,manifest.ShadowCaseId);
if ~all(hasCase)
    error( ...
        "v2xsim:analysis:OrphanShadowReceiverRoster", ...
        "Every receiver-roster row must identify a shadow case.");
end
predictions = table( ...
    eligibleRoster.ShadowCaseId, ...
    manifest.FirstUeId(caseRows), ...
    manifest.SecondUeId(caseRows), ...
    eligibleRoster.TransmitterUeId, ...
    eligibleRoster.ReceiverUeId, ...
    eligibleRoster.IsSameTechnology, ...
    eligibleRoster.IsWithinAnalysisRange, ...
    correctCount ./ denominator, ...
    VariableNames=[ ...
        "ShadowCaseId","FirstUeId","SecondUeId", ...
        "TransmitterUeId","ReceiverUeId","IsSameTechnology", ...
        "IsWithinAnalysisRange","PredictedPrr"]);
end

function predictions = collapseLinkPredictions(linkPredictions)
if isempty(linkPredictions)
    predictions = emptyPredictions();
    return
end
identity = unique( ...
    linkPredictions(:,[ ...
        "ShadowCaseId","FirstUeId", ...
        "SecondUeId","ReceiverUeId"]), ...
    "rows","stable");
rowCount = height(identity);
isSameTechnology = true(rowCount,1);
isWithinAnalysisRange = true(rowCount,1);
predictedPrr = zeros(rowCount,1);
for row = 1:rowCount
    isReceiver = ...
        linkPredictions.ShadowCaseId == ...
            identity.ShadowCaseId(row) & ...
        linkPredictions.ReceiverUeId == ...
            identity.ReceiverUeId(row);
    predictedPrr(row) = min( ...
        linkPredictions.PredictedPrr(isReceiver));
end
predictions = table( ...
    identity.ShadowCaseId,identity.FirstUeId, ...
    identity.SecondUeId,identity.ReceiverUeId, ...
    isSameTechnology,isWithinAnalysisRange,predictedPrr, ...
    VariableNames=[ ...
        "ShadowCaseId","FirstUeId","SecondUeId", ...
        "ReceiverUeId","IsSameTechnology", ...
        "IsWithinAnalysisRange","PredictedPrr"]);
end

function complete = receiverCoverageIsComplete( ...
        manifestRow,roster,counts,prrDefinition)
caseId = manifestRow.ShadowCaseId;
eligible = roster( ...
    roster.ShadowCaseId == caseId & ...
    roster.IsSameTechnology & ...
    roster.IsWithinAnalysisRange,:);
if isempty(eligible)
    complete = true;
    return
end
[hasCounts,countRows] = ismember( ...
    eligible(:,[ ...
        "ShadowCaseId","TransmitterUeId","ReceiverUeId"]), ...
    counts(:,[ ...
        "ShadowCaseId","TransmitterUeId","ReceiverUeId"]),"rows");
if ~all(hasCounts)
    complete = false;
    return
end
if prrDefinition == "delivery"
    denominator = ...
        counts.CorrectCount(countRows) + ...
        counts.ErrorCount(countRows) + ...
        counts.BlockedCount(countRows);
else
    denominator = ...
        counts.CorrectCount(countRows) + ...
        counts.ErrorCount(countRows);
end
complete = all( ...
    denominator >= ...
    manifestRow.MinimumReceiverObservationCount);
end

function validateManifest(manifest)
requiredNames = [ ...
    "ShadowCaseId","FirstUeId","SecondUeId", ...
    "CandidateType","MinimumReceiverObservationCount", ...
    "EvaluationHorizonSeconds", ...
    "AllocationIntervalSeconds", ...
    "InterventionPolicy", ...
    "StopBeforeNextAllocationDecision", ...
    "RequiredIndependentReplicateCount", ...
    "StateSnapshotRequired","ControlReplayRequired", ...
    "CommonRandomNumbersRequired"];
requiredNames = [ ...
    requiredNames,"SelectionProbability","AnalysisWeight"];
if any(~ismember( ...
        requiredNames,string(manifest.Properties.VariableNames))) || ...
        ~isstring(manifest.ShadowCaseId) || ...
        ~isstring(manifest.FirstUeId) || ...
        ~isstring(manifest.SecondUeId) || ...
        ~isstring(manifest.CandidateType) || ...
        any(ismissing(manifest.ShadowCaseId)) || ...
        any(strlength(strip(manifest.ShadowCaseId)) == 0) || ...
        numel(unique(manifest.ShadowCaseId)) ~= height(manifest) || ...
        any(manifest.FirstUeId >= manifest.SecondUeId) || ...
        any(manifest.CandidateType ~= "missed_reuse") || ...
        ~isnumeric(manifest.EvaluationHorizonSeconds) || ...
        any(~isfinite(manifest.EvaluationHorizonSeconds)) || ...
        any(manifest.EvaluationHorizonSeconds <= 0) || ...
        ~isnumeric(manifest.AllocationIntervalSeconds) || ...
        any(~isfinite(manifest.AllocationIntervalSeconds)) || ...
        any(manifest.AllocationIntervalSeconds <= 0) || ...
        any(manifest.EvaluationHorizonSeconds > ...
            manifest.AllocationIntervalSeconds) || ...
        ~isstring(manifest.InterventionPolicy) || ...
        any(manifest.InterventionPolicy ~= ...
            "single_epoch_replicated_from_fork") || ...
        ~islogical( ...
            manifest.StopBeforeNextAllocationDecision) || ...
        any(~manifest.StopBeforeNextAllocationDecision) || ...
        ~isnumeric( ...
            manifest.RequiredIndependentReplicateCount) || ...
        any(~isfinite( ...
            manifest.RequiredIndependentReplicateCount)) || ...
        any(manifest.RequiredIndependentReplicateCount < 1) || ...
        any(fix(manifest.RequiredIndependentReplicateCount) ~= ...
            manifest.RequiredIndependentReplicateCount) || ...
        ~isnumeric(manifest.MinimumReceiverObservationCount) || ...
        any(~isfinite(manifest.MinimumReceiverObservationCount)) || ...
        any(manifest.MinimumReceiverObservationCount < 1) || ...
        any(fix(manifest.MinimumReceiverObservationCount) ~= ...
            manifest.MinimumReceiverObservationCount) || ...
        any(manifest.RequiredIndependentReplicateCount < ...
            manifest.MinimumReceiverObservationCount) || ...
        ~isnumeric(manifest.SelectionProbability) || ...
        ~iscolumn(manifest.SelectionProbability) || ...
        any(~isfinite(manifest.SelectionProbability)) || ...
        any(manifest.SelectionProbability <= 0) || ...
        any(manifest.SelectionProbability > 1) || ...
        ~isnumeric(manifest.AnalysisWeight) || ...
        ~iscolumn(manifest.AnalysisWeight) || ...
        any(~isfinite(manifest.AnalysisWeight)) || ...
        any(manifest.AnalysisWeight < 1) || ...
        any(abs( ...
            manifest.SelectionProbability .* ...
            manifest.AnalysisWeight - 1) > 1e-12) || ...
        ~islogical(manifest.StateSnapshotRequired) || ...
        ~islogical(manifest.ControlReplayRequired) || ...
        ~islogical(manifest.CommonRandomNumbersRequired) || ...
        any(~manifest.StateSnapshotRequired) || ...
        any(~manifest.ControlReplayRequired) || ...
        any(~manifest.CommonRandomNumbersRequired)
    error( ...
        "v2xsim:analysis:InvalidExposedShadowManifest", ...
        "The exposed-reuse shadow manifest is invalid.");
end
end

function validateExecutions(executions,manifest)
expectedNames = [ ...
    "ShadowCaseId","ExecutionStatus", ...
    "StateSnapshotRestored","ControlReplayMatchedSource", ...
    "CommonRandomNumbersVerified","ReceiverRosterComplete"];
if ~isequal( ...
        string(executions.Properties.VariableNames),expectedNames) || ...
        ~isstring(executions.ShadowCaseId) || ...
        ~isstring(executions.ExecutionStatus) || ...
        any(~ismember( ...
            executions.ExecutionStatus, ...
            ["pending","complete","failed"])) || ...
        numel(unique(executions.ShadowCaseId)) ~= ...
        height(executions)
    error( ...
        "v2xsim:analysis:InvalidExposedShadowExecutions", ...
        "Shadow executions must contain one valid status row per case.");
end
logicalNames = expectedNames(3:end);
for variableName = logicalNames
    if ~islogical(executions.(variableName)) || ...
            ~iscolumn(executions.(variableName))
        error( ...
            "v2xsim:analysis:InvalidExposedShadowExecutions", ...
            "%s must be a logical column.",variableName);
    end
end
if any(~ismember(executions.ShadowCaseId,manifest.ShadowCaseId))
    error( ...
        "v2xsim:analysis:OrphanExposedShadowExecution", ...
        "Every execution row must identify a manifest case.");
end
end

function validateReceiverRoster(roster,manifest)
expectedNames = [ ...
    "ShadowCaseId","TransmitterUeId","ReceiverUeId", ...
    "IsSameTechnology","IsWithinAnalysisRange"];
if ~isequal( ...
        string(roster.Properties.VariableNames),expectedNames) || ...
        ~isstring(roster.ShadowCaseId) || ...
        ~isstring(roster.TransmitterUeId) || ...
        ~isstring(roster.ReceiverUeId) || ...
        any(ismissing(roster.ShadowCaseId)) || ...
        any(ismissing(roster.TransmitterUeId)) || ...
        any(ismissing(roster.ReceiverUeId)) || ...
        any(strlength(strip(roster.ShadowCaseId)) == 0) || ...
        any(strlength(strip(roster.TransmitterUeId)) == 0) || ...
        any(strlength(strip(roster.ReceiverUeId)) == 0) || ...
        ~islogical(roster.IsSameTechnology) || ...
        ~iscolumn(roster.IsSameTechnology) || ...
        ~islogical(roster.IsWithinAnalysisRange) || ...
        ~iscolumn(roster.IsWithinAnalysisRange) || ...
        height(unique( ...
            roster(:,[ ...
                "ShadowCaseId","TransmitterUeId","ReceiverUeId"]), ...
            "rows")) ~= ...
            height(roster)
    error( ...
        "v2xsim:analysis:InvalidExposedShadowReceiverRoster", ...
        "Receiver roster rows must uniquely identify case receivers.");
end
if any(~ismember(roster.ShadowCaseId,manifest.ShadowCaseId))
    error( ...
        "v2xsim:analysis:OrphanShadowReceiverRoster", ...
        "Every receiver-roster row must identify a manifest case.");
end
if ~isempty(roster)
    [~,caseRows] = ismember( ...
        roster.ShadowCaseId,manifest.ShadowCaseId);
    isPairTransmitter = ...
        roster.TransmitterUeId == manifest.FirstUeId(caseRows) | ...
        roster.TransmitterUeId == manifest.SecondUeId(caseRows);
    if any(~isPairTransmitter)
        error( ...
            "v2xsim:analysis:InvalidShadowTransmitterEndpoint", ...
            "Every shadow link must originate at a candidate endpoint.");
    end
    if any( ...
            roster.ReceiverUeId == manifest.FirstUeId(caseRows) | ...
            roster.ReceiverUeId == manifest.SecondUeId(caseRows))
        error( ...
            "v2xsim:analysis:InvalidShadowReceiverEndpoint", ...
            "Candidate transmitters cannot also be shadow receivers.");
    end
end
end

function validateReceiverCounts(counts,manifest,roster)
expectedNames = [ ...
    "ShadowCaseId","TransmitterUeId","ReceiverUeId", ...
    "CorrectCount","ErrorCount","BlockedCount"];
if ~isequal( ...
        string(counts.Properties.VariableNames),expectedNames) || ...
        ~isstring(counts.ShadowCaseId) || ...
        ~isstring(counts.TransmitterUeId) || ...
        ~isstring(counts.ReceiverUeId) || ...
        height(unique( ...
            counts(:,[ ...
                "ShadowCaseId","TransmitterUeId","ReceiverUeId"]), ...
            "rows")) ~= ...
            height(counts)
    error( ...
        "v2xsim:analysis:InvalidExposedShadowReceiverCounts", ...
        "Shadow counts must uniquely identify case receivers.");
end
for variableName = expectedNames(4:end)
    values = counts.(variableName);
    if ~isnumeric(values) || ~iscolumn(values) || ...
            any(~isfinite(values)) || any(values < 0) || ...
            any(fix(values) ~= values)
        error( ...
            "v2xsim:analysis:InvalidExposedShadowReceiverCounts", ...
            "%s must contain nonnegative integer counts.", ...
            variableName);
    end
end
if any(~ismember(counts.ShadowCaseId,manifest.ShadowCaseId))
    error( ...
        "v2xsim:analysis:OrphanExposedShadowReceiverCount", ...
        "Every receiver count must identify a manifest case.");
end
if ~isempty(counts)
    [knownReceiver,~] = ismember( ...
        counts(:,[ ...
            "ShadowCaseId","TransmitterUeId","ReceiverUeId"]), ...
        roster(:,[ ...
            "ShadowCaseId","TransmitterUeId","ReceiverUeId"]),"rows");
    if ~all(knownReceiver)
        error( ...
            "v2xsim:analysis:OrphanExposedShadowReceiverCount", ...
            "Every receiver count must identify a declared receiver.");
    end
end
end

function predictions = emptyLinkPredictions()
predictions = table( ...
    strings(0,1),strings(0,1),strings(0,1), ...
    strings(0,1), ...
    strings(0,1),false(0,1),false(0,1),zeros(0,1), ...
    VariableNames=[ ...
        "ShadowCaseId","FirstUeId","SecondUeId", ...
        "TransmitterUeId","ReceiverUeId","IsSameTechnology", ...
        "IsWithinAnalysisRange","PredictedPrr"]);
end

function predictions = emptyPredictions()
predictions = table( ...
    strings(0,1),strings(0,1),strings(0,1), ...
    strings(0,1),false(0,1),false(0,1),zeros(0,1), ...
    VariableNames=[ ...
        "ShadowCaseId","FirstUeId","SecondUeId", ...
        "ReceiverUeId","IsSameTechnology", ...
        "IsWithinAnalysisRange","PredictedPrr"]);
end
