classdef BRAssignmentParametersTest < matlab.unittest.TestCase
    %BRASSIGNMENTPARAMETERSTEST Tests the named allocator configuration.

    methods (TestClassSetup)
        function addLegacyInitializationPath(testCase)
            projectRoot = fileparts(fileparts(fileparts(fileparts( ...
                mfilename("fullpath")))));
            legacyInitializationPath = fullfile( ...
                projectRoot, "old_src", "MatFilesInit");
            originalPath = path;
            testCase.addTeardown(@() path(originalPath));
            addpath(legacyInitializationPath);
        end
    end

    methods (Test)
        function testDefaultRatiosRemainCoupledAtTwentyPercent(testCase)
            simParams = testCase.initializeWithArguments({});

            testCase.verifyEqual( ...
                simParams.ratioSelectedAutonomousMode, 0.2);
            testCase.verifyEqual(simParams.ratioSelectedL2, 0.2);
        end

        function testExistingRatioStillConfiguresBothStages(testCase)
            simParams = testCase.initializeWithArguments( ...
                {"resourceAllocation.Autonomous.MinimumCandidateFraction", 0.5});

            testCase.verifyEqual( ...
                simParams.ratioSelectedAutonomousMode, 0.5);
            testCase.verifyEqual(simParams.ratioSelectedL2, 0.5);
        end

        function testThresholdAndL2RatiosCanBeSetIndependently(testCase)
            simParams = testCase.initializeWithArguments({ ...
                "resourceAllocation.Autonomous.MinimumCandidateFraction", 0.2, ...
                "resourceAllocation.Autonomous.L2CandidateFraction", 0.5});

            testCase.verifyEqual( ...
                simParams.ratioSelectedAutonomousMode, 0.2);
            testCase.verifyEqual(simParams.ratioSelectedL2, 0.5);
        end

        function testEveryNamedAllocatorCanBeSelected(testCase)
            types = [ ...
                "ReuseDistance", ...
                "MaximumReuseDistance", ...
                "MinimumReusePower", ...
                "ThreeGppAutonomous", ...
                "RandomBenchmark", ...
                "OrderedBenchmark"];

            for type = types
                simParams = testCase.initializeWithArguments( ...
                    {"resourceAllocation.Type",type});
                testCase.verifyEqual( ...
                    simParams.resourceAllocationType,type);
            end
        end

        function testNumericAlgorithmNameIsRejected(testCase)
            testCase.verifyError( ...
                @() testCase.initializeWithArguments( ...
                    {"resourceAllocation.Algorithm",18}), ...
                "v2xsim:resource:RemovedNumericAlgorithm");
            testCase.verifyError( ...
                @() testCase.initializeWithArguments( ...
                    {"resourceAllocation.Type",18}), ...
                "v2xsim:resource:RemovedNumericAlgorithm");
        end

        function testUnknownNamedAllocatorIsRejected(testCase)
            testCase.verifyError( ...
                @() testCase.initializeWithArguments( ...
                    {"resourceAllocation.Type","NearestColor"}), ...
                "v2xsim:resource:UnknownAllocatorType");
        end

        function testRandomBenchmarkNumerologyConfigurationWorks(testCase)
            simParams = testCase.initializeWithArguments({ ...
                "resourceAllocation.Type","RandomBenchmark", ...
                "resourceAllocation.Autonomous." + ...
                    "SelectionWindowStartMilliseconds",1, ...
                "resourceAllocation.Autonomous." + ...
                    "SelectionWindowEndMilliseconds",50});

            testCase.verifyEqual(simParams.T1autonomousModeTTIs,1);
            testCase.verifyEqual(simParams.T2autonomousModeTTIs,50);
        end

        function testScheduledIntervalMustBeExactMultiple(testCase)
            testCase.verifyError( ...
                @() testCase.initializeWithArguments({ ...
                    "resourceAllocation.Type","ReuseDistance", ...
                    "resourceAllocation.Controlled." + ...
                        "ReassignmentIntervalSeconds",0.15}), ...
                "v2xsim:resource:NonIntegralInterval");
        end

        function testAllocatorSeedDefaultsToSimulationSeed(testCase)
            initialSimParams = struct("mode5G",1,"seed",73);
            initialPhyParams = testCase.defaultPhyParameters();

            [simParams,~,remainingArguments] = ...
                initiateBRAssignmentAlgorithm( ...
                    initialSimParams,initialPhyParams,0.1,"",{});

            testCase.verifyEqual( ...
                simParams.resourceAllocationRandomSeed,73);
            testCase.verifyEmpty(remainingArguments{1});
        end

        function testMinimumReselectionCounterCanBeOverriddenAlone( ...
                testCase)
            simParams = testCase.initializeWithArguments({ ...
                "resourceAllocation.Autonomous." + ...
                    "ReselectionCounterMinimum",6});

            testCase.verifyEqual(simParams.minRandValueMode4,6);
            testCase.verifyEqual(simParams.maxRandValueMode4,-1);
        end

        function testSelectionWindowMustAlignWithNumerologySlots( ...
                testCase)
            initialSimParams = struct("mode5G",1);
            initialPhyParams = testCase.defaultPhyParameters();
            initialPhyParams.muNumerology = 1;

            testCase.verifyError( ...
                @() initiateBRAssignmentAlgorithm( ...
                    initialSimParams,initialPhyParams,0.1,"",{ ...
                        "resourceAllocation.Autonomous." + ...
                            "SelectionWindowStartMilliseconds",0.75}), ...
                "v2xsim:resource:InvalidSelectionWindow");
        end
    end

    methods (Access = private)
        function simParams = initializeWithArguments( ...
                testCase, inputArguments)
            initialSimParams = struct("mode5G", 1);
            initialPhyParams = testCase.defaultPhyParameters();

            [simParams, ~, remainingArguments] = ...
                initiateBRAssignmentAlgorithm( ...
                    initialSimParams, initialPhyParams, 0.1, "", ...
                    inputArguments);
            testCase.verifyEmpty(remainingArguments{1});
        end
    end

    methods (Static, Access = private)
        function phyParams = defaultPhyParameters()
            phyParams = struct( ...
                "PDelta",Inf, ...
                "duplexCV2X","HD", ...
                "cv2xNumberOfReplicasMax",1, ...
                "muNumerology",0, ...
                "BRoverlapAllowed",false);
        end
    end
end
