classdef Cv2xSinrAveragingTest < matlab.unittest.TestCase
    %CV2XSINRAVERAGINGTEST Coexistence interference averaging boundaries.

    methods (TestClassSetup)
        function addLegacySinrPaths(testCase)
            projectRoot = string(fileparts(fileparts(fileparts( ...
                fileparts(mfilename("fullpath"))))));
            originalPath = path;
            testCase.addTeardown(@() path(originalPath));
            addpath(fullfile(projectRoot,"old_src","MatFilesInit"));
            addpath(fullfile(projectRoot,"old_src","MainFilesCV2X"));
        end
    end

    methods (Test)
        function testZeroDurationUpdatePreservesFiniteAverage(testCase)
            sinrManagement = testCase.sinrState(1,[2;3],[2;3]);

            sinrManagement = updateSINRCV2X( ...
                1,testCase.stationState(),sinrManagement, ...
                1,1,testCase.simulationParameters(),struct());

            testCase.verifyEqual( ...
                sinrManagement.coex_averageTTIinterfFrom11pToLTE, ...
                [2;3]);
            testCase.verifyTrue(all(isfinite( ...
                sinrManagement.coex_averageTTIinterfFrom11pToLTE)));
            testCase.verifyEqual( ...
                sinrManagement.instantThisPstartedCV2X,1);
        end

        function testPositiveDurationUpdateUsesTimeWeightedAverage( ...
                testCase)
            sinrManagement = testCase.sinrState(1.5,[2;4],[4;8]);

            sinrManagement = updateSINRCV2X( ...
                2,testCase.stationState(),sinrManagement, ...
                1,1,testCase.simulationParameters(),struct());

            testCase.verifyEqual( ...
                sinrManagement.coex_averageTTIinterfFrom11pToLTE, ...
                [3;6],AbsTol=1e-12);
            testCase.verifyEqual( ...
                sinrManagement.instantThisPstartedCV2X,2);
        end
    end

    methods (Access = private)
        function value = stationState(~)
            value = struct( ...
                "activeIDsCV2X",[1;2], ...
                "transmittingIDsCV2X",zeros(0,1));
        end

        function value = sinrState( ...
                ~,instantThisPowerStarted,averageInterference, ...
                currentInterference)
            value = struct( ...
                "coex_averageTTIinterfFrom11pToLTE", ...
                    averageInterference, ...
                "coex_currentInterfFrom11pToLTE", ...
                    currentInterference, ...
                "instantThisPstartedCV2X",instantThisPowerStarted, ...
                "instantTheSINRaverageStartedCV2X",1);
        end

        function value = simulationParameters(~)
            value = struct( ...
                "technology",constants.TECH_COEX_STD_INTERF);
        end
    end
end
