classdef Cv2xInterferenceEvidenceBridgeTest < matlab.unittest.TestCase
    methods (TestClassSetup)
        function addLegacyPaths(testCase)
            projectRoot = string(fileparts(fileparts(fileparts( ...
                fileparts(mfilename("fullpath"))))));
            originalPath = path;
            testCase.addTeardown(@() path(originalPath));
            addpath(fullfile( ...
                projectRoot,"old_src","MatFilesInit"));
            addpath(fullfile( ...
                projectRoot,"old_src","MainFilesCV2X"));
            addpath(fullfile( ...
                projectRoot,"old_src", ...
                "MatFilesResourceAllocationCV2X"));
        end
    end

    methods (Test)
        function capturesExactConcurrentTransmitterRemoval(testCase)
            [station,sinr,sim,app,phy,position] = ...
                testCase.fixtureState(true);
            time = struct("timeNow",0);

            sinr = initLastPowerCV2X( ...
                time,station,sinr,sim,app,phy);
            sinr = updateSINRCV2X( ...
                1,station,sinr, ...
                phy.PnoiseData,phy.PnoiseSCI,sim,app);
            [~,~,~,diagnostics] = elaborateFateRxCV2X( ...
                time,station.transmittingIDsCV2X, ...
                station.indexInActiveIDsOnlyLTE_OfTxLTE, ...
                station.neighborsIDLTE,sinr,station, ...
                position,phy);

            attempt = diagnostics.TerminalAttempts( ...
                diagnostics.TerminalAttempts.TransmitterId == 1 & ...
                diagnostics.TerminalAttempts.ReceiverId == 2,:);
            counterfactual = diagnostics.Counterfactuals( ...
                diagnostics.Counterfactuals.TransmitterId == 1 & ...
                diagnostics.Counterfactuals.ReceiverId == 2,:);

            testCase.verifyEqual(height(attempt),1);
            testCase.verifyEqual(attempt.Outcome,"error");
            testCase.verifyTrue(attempt.EvidenceIsExhaustive);
            testCase.verifyEqual(attempt.InterfererCount,1);
            testCase.verifyEqual(height(counterfactual),1);
            testCase.verifyEqual(counterfactual.InterfererId,3);
            testCase.verifyEqual( ...
                counterfactual.ResourceRelation,"cochannel");
            testCase.verifyEqual( ...
                counterfactual.RemovedInterferencePower,5, ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                counterfactual.SinrWithoutInterfererDb, ...
                10 * log10(5),AbsTol=1e-12);
        end

        function disabledDiagnosticsDoNotAllocateContributorTensor( ...
                testCase)
            [station,sinr,sim,app,phy] = ...
                testCase.fixtureState(false);
            time = struct("timeNow",0);

            sinr = initLastPowerCV2X( ...
                time,station,sinr,sim,app,phy);

            testCase.verifyFalse( ...
                sinr.cv2xInterferenceEvidenceEnabled);
            testCase.verifyFalse(isfield( ...
                sinr,"cv2xIndividualInterferencePowerData"));
        end
    end

    methods (Access = private)
        function [station,sinr,sim,app,phy,position] = ...
                fixtureState(~,enabled)
            station = struct( ...
                "activeIDs",(1:3).', ...
                "activeIDsCV2X",(1:3).', ...
                "indexInActiveIDs_ofLTEnodes",(1:3).', ...
                "transmittingIDsCV2X",[1,3], ...
                "transmittingFusedLTE",[1;1], ...
                "indexInActiveIDsOnlyLTE_OfTxLTE",[1;3], ...
                "neighborsIDLTE",[2,3;1,3;1,2], ...
                "vehicleState",100 * ones(3,1), ...
                "pckReceived",zeros(3,3), ...
                "pckTxOccurring",[1;0;1], ...
                "BRid",ones(3,1), ...
                "cv2xNumberOfReplicas",ones(3,1));
            sinr = struct( ...
                "P_RX_MHz",[0,1,2;10,0,5;2,1,0], ...
                "coex_currentInterfFrom11pToLTE",zeros(3,1), ...
                "cumulativeSINR",zeros(3,3));
            sim = struct( ...
                "technology",constants.TECH_ONLY_CV2X, ...
                "interferenceClassificationEnabled",enabled);
            app = struct("NbeaconsF",1,"RBsBeacon",4);
            phy = struct( ...
                "fadingRayleigh",false, ...
                "IBEmatrixData",1, ...
                "IBEmatrixControl",1, ...
                "BwMHz_cv2xBR",1, ...
                "Ksi",0, ...
                "P_ERP_MHz_CV2X",ones(3,1), ...
                "PnoiseData",2, ...
                "PnoiseSCI",2, ...
                "LOS",zeros(2,2), ...
                "sinrVectorCV2X_LOS",100, ...
                "sinrVectorCV2X_NLOS",100, ...
                "cv2xNumberOfReplicasMax",1);
            position = struct( ...
                "distanceReal",[0,10,20;10,0,10;20,10,0]);
        end
    end
end
