classdef GeometryBridgeTest < matlab.unittest.TestCase
    %GEOMETRYBRIDGETEST Physical/apparent distance and neighbor contracts.

    methods (TestClassSetup)
        function addGeometryPaths(testCase)
            projectRoot = string(fileparts(fileparts(fileparts( ...
                fileparts(mfilename("fullpath"))))));
            originalPath = path;
            testCase.addTeardown(@() path(originalPath));
            addpath(fullfile(projectRoot,"old_src","MatFilesInit"));
            addpath(fullfile(projectRoot,"old_src","MatFilesUtility"));
        end
    end

    methods (Test)
        function testMixedTechnologyGeometryUsesIdentitySafePartitions( ...
                testCase)
            stationManagement = testCase.stationState( ...
                [ ...
                    constants.V_STATE_LTE_TXRX; ...
                    constants.V_STATE_11P_IDLE; ...
                    constants.V_STATE_LTE_TXRX; ...
                    constants.V_STATE_11P_IDLE]);
            positionManagement = struct( ...
                "XvehicleReal",[0;30;100;130], ...
                "YvehicleReal",zeros(4,1), ...
                "NgroupPosUpdate",1);
            simValues = struct( ...
                "XvehicleEstimated",[0;30;80;130], ...
                "YvehicleEstimated",zeros(4,1));
            simParams = struct("posError95",1);

            [positionManagement,stationManagement] = computeDistance( ...
                simParams,simValues,stationManagement, ...
                positionManagement);

            testCase.verifyEqual( ...
                positionManagement.distanceReal(1,3),100);
            testCase.verifyEqual( ...
                positionManagement.distanceEstimated(1,3),80);
            testCase.verifyEqual( ...
                positionManagement.distanceReal, ...
                positionManagement.distanceReal.');
            testCase.verifyEqual( ...
                diag(positionManagement.distanceReal),zeros(4,1));

            phyParams = struct( ...
                "Raw",[99 100 101], ...
                "RawMaxCV2X",101, ...
                "RawMax11p",101);
            [~,stationManagement] = computeNeighbors( ...
                stationManagement,positionManagement,phyParams);

            testCase.verifyEqual( ...
                stationManagement.neighborsIDLTE,[3;1]);
            testCase.verifyEqual( ...
                stationManagement.neighborsID11p,[4;2]);
            testCase.verifySize( ...
                stationManagement.awarenessIDLTE,[2 1 3]);
            testCase.verifySize( ...
                stationManagement.awarenessID11p,[2 1 3]);
            testCase.verifyEqual( ...
                stationManagement.awarenessIDLTE(:,:,1:2), ...
                zeros(2,1,2));
            testCase.verifyEqual( ...
                stationManagement.awarenessID11p(:,:,1:2), ...
                zeros(2,1,2));
            testCase.verifyEqual( ...
                stationManagement.awarenessIDLTE(:,:,3),[3;1]);
            testCase.verifyEqual( ...
                stationManagement.awarenessID11p(:,:,3),[4;2]);
        end

        function testSingletonTechnologyPartitionsHaveNoNeighbors( ...
                testCase)
            stationManagement = testCase.stationState( ...
                [ ...
                    constants.V_STATE_LTE_TXRX; ...
                    constants.V_STATE_11P_IDLE]);
            positionManagement = struct( ...
                "XvehicleReal",[0;50], ...
                "YvehicleReal",[0;0], ...
                "NgroupPosUpdate",1);
            [positionManagement,stationManagement] = computeDistance( ...
                struct("posError95",0), ...
                struct( ...
                    "XvehicleEstimated",[0;50], ...
                    "YvehicleEstimated",[0;0]), ...
                stationManagement,positionManagement);

            [~,stationManagement] = computeNeighbors( ...
                stationManagement,positionManagement, ...
                struct( ...
                    "Raw",[50 100], ...
                    "RawMaxCV2X",100, ...
                    "RawMax11p",100));

            testCase.verifySize( ...
                stationManagement.neighborsIDLTE,[1 0]);
            testCase.verifySize( ...
                stationManagement.neighborsID11p,[1 0]);
            testCase.verifyEmpty( ...
                stationManagement.awarenessIDLTE);
            testCase.verifyEmpty( ...
                stationManagement.awarenessID11p);
        end

        function testEstimatedDistanceAlwaysUsesApparentPositions( ...
                testCase)
            stationManagement = testCase.stationState( ...
                [ ...
                    constants.V_STATE_11P_IDLE; ...
                    constants.V_STATE_11P_IDLE]);
            positionManagement = struct( ...
                "XvehicleReal",[0;100], ...
                "YvehicleReal",[0;0], ...
                "NgroupPosUpdate",1);
            simValues = struct( ...
                "XvehicleEstimated",[0;25], ...
                "YvehicleEstimated",[0;0]);

            [positionManagement,~] = computeDistance( ...
                struct("posError95",0),simValues, ...
                stationManagement,positionManagement);

            testCase.verifyEqual( ...
                positionManagement.distanceReal(1,2),100);
            testCase.verifyEqual( ...
                positionManagement.distanceEstimated(1,2),25);
        end
    end

    methods (Access = private)
        function value = stationState(~,vehicleState)
            activeIds = (1:numel(vehicleState)).';
            value = struct( ...
                "activeIDs",activeIds, ...
                "vehicleState",vehicleState, ...
                "activeIDsCV2X",activeIds( ...
                    vehicleState == constants.V_STATE_LTE_TXRX), ...
                "activeIDs11p",activeIds( ...
                    vehicleState ~= constants.V_STATE_LTE_TXRX));
        end
    end
end
