classdef Ieee80211pStateMachineTest < matlab.unittest.TestCase
    %IEEE80211PSTATEMACHINETEST Exact receive/backoff transition contracts.

    methods (TestClassSetup)
        function addLegacyMacPaths(testCase)
            projectRoot = string(fileparts(fileparts(fileparts( ...
                fileparts(mfilename("fullpath"))))));
            originalPath = path;
            testCase.addTeardown(@() path(originalPath));
            addpath(fullfile(projectRoot,"old_src","MatFilesInit"));
            addpath(fullfile( ...
                projectRoot,"old_src","MainFilesIEEE802.11p"));
        end
    end

    methods (Test)
        function testReceptionFreezesEligibleBackoff(testCase)
            [timeManagement,stationManagement,sinrManagement, ...
                simParams,phyParams] = testCase.startState();

            [timeManagement,stationManagement,sinrManagement, ...
                outputValues] = checkVehiclesStartReceiving11p( ...
                    2,2,timeManagement,stationManagement, ...
                    sinrManagement,simParams,phyParams,struct(), ...
                    struct("Sentinel",17));

            testCase.verifyEqual( ...
                stationManagement.vehicleState, ...
                [constants.V_STATE_11P_RX; ...
                 constants.V_STATE_11P_TX; ...
                 constants.V_STATE_11P_BACKOFF]);
            testCase.verifyEqual( ...
                stationManagement.nSlotBackoff11p,[5;0;6]);
            testCase.verifyEqual( ...
                timeManagement.timeNextTxRx11p,[Inf;Inf;1.8]);
            testCase.verifyEqual( ...
                sinrManagement.idFromWhichRx11p,[2;2;3]);
            testCase.verifyEqual( ...
                sinrManagement.instantThisSINRstarted11p(1),1);
            testCase.verifyEqual(outputValues.Sentinel,17);
        end

        function testReceptionEndResumesAndIdlesQueues(testCase)
            [timeManagement,stationManagement,sinrManagement, ...
                simParams,phyParams] = testCase.stopState();

            [timeManagement,stationManagement,sinrManagement, ...
                outputValues] = checkVehiclesStopReceiving11p( ...
                    timeManagement,stationManagement,sinrManagement, ...
                    simParams,phyParams,struct(),struct("Sentinel",23));

            testCase.verifyEqual( ...
                stationManagement.vehicleState, ...
                [constants.V_STATE_11P_BACKOFF; ...
                 constants.V_STATE_11P_IDLE; ...
                 constants.V_STATE_11P_IDLE]);
            testCase.verifyEqual( ...
                timeManagement.timeNextTxRx11p,[1.04;Inf;Inf], ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                sinrManagement.idFromWhichRx11p,[1;2;3]);
            testCase.verifyEqual( ...
                stationManagement.channelSensedBusyMatrix11p, ...
                [0.2 0 0.1], AbsTol=1e-12);
            testCase.verifyEqual( ...
                timeManagement.cbr11p_timeStartBusy,[-1;0.8;-1]);
            testCase.verifyEqual(outputValues.Sentinel,23);
        end

        function testInterferenceKeepsReceiverBusy(testCase)
            [timeManagement,stationManagement,sinrManagement, ...
                simParams,phyParams] = testCase.stopState();
            simParams.cbrActive = false;
            sinrManagement.coex_virtualInterference(1) = 2;

            [timeManagement,stationManagement,sinrManagement] = ...
                checkVehiclesStopReceiving11p( ...
                    timeManagement,stationManagement,sinrManagement, ...
                    simParams,phyParams,struct(),struct());

            testCase.verifyEqual( ...
                stationManagement.vehicleState(1), ...
                constants.V_STATE_11P_RX);
            testCase.verifyEqual( ...
                timeManagement.timeNextTxRx11p(1),Inf);
            testCase.verifyEqual( ...
                sinrManagement.idFromWhichRx11p(1),1);
        end
    end

    methods (Access = private)
        function [timeManagement,stationManagement,sinrManagement, ...
                simParams,phyParams] = startState(~)
            timeManagement = struct( ...
                "timeNow",1, ...
                "timeNextTxRx11p",[1.45;Inf;1.8], ...
                "cbr11p_timeStartBusy",-ones(3,1));
            stationManagement = struct( ...
                "activeIDs",(1:3).', ...
                "activeIDsCV2X",zeros(0,1), ...
                "vehicleState",[ ...
                    constants.V_STATE_11P_BACKOFF; ...
                    constants.V_STATE_11P_TX; ...
                    constants.V_STATE_11P_BACKOFF], ...
                "vehicleChannel",[1;1;2], ...
                "nSlotBackoff11p",[8;0;6], ...
                "preambleAlreadyDetected",false(3), ...
                "channelSensedBusyMatrix11p",zeros(1,3));
            sinrManagement = struct( ...
                "P_RX_MHz",[0 10 0;0 0 0;0 0 0], ...
                "coex_InterfFromLTEto11p",zeros(3,1), ...
                "coex_virtualInterference",zeros(3,1), ...
                "idFromWhichRx11p",(1:3).', ...
                "sinrAverage11p",zeros(3,1), ...
                "interfAverage11p",zeros(3,1), ...
                "instantThisSINRavStarted11p",zeros(3,1), ...
                "instantThisSINRstarted11p",zeros(3,1));
            simParams = struct( ...
                "technology",constants.TECH_ONLY_11P, ...
                "cbrActive",false);
            phyParams = struct( ...
                "tSlot",0.1, ...
                "Pnoise_MHz",1, ...
                "BwMHz",1, ...
                "sinrThreshold11p_preamble",1, ...
                "PrxSensNotSynch",1);
        end

        function [timeManagement,stationManagement,sinrManagement, ...
                simParams,phyParams] = stopState(~)
            timeManagement = struct( ...
                "timeNow",1, ...
                "timeNextTxRx11p",Inf(3,1), ...
                "cbr11p_timeStartBusy",[0.8;0.8;0.9]);
            stationManagement = struct( ...
                "activeIDs",(1:3).', ...
                "activeIDsCV2X",zeros(0,1), ...
                "vehicleState",[ ...
                    constants.V_STATE_11P_RX; ...
                    constants.V_STATE_11P_IDLE; ...
                    constants.V_STATE_11P_RX], ...
                "pckBuffer",[1;0;0], ...
                "nSlotBackoff11p",[2;-1;-1], ...
                "CW_11p",4 * ones(3,1), ...
                "tAifs_11p",0.02 * ones(3,1), ...
                "channelSensedBusyMatrix11p",zeros(1,3));
            sinrManagement = struct( ...
                "idFromWhichRx11p",[2;2;2], ...
                "P_RX_MHz",zeros(3), ...
                "coex_InterfFromLTEto11p",zeros(3,1), ...
                "coex_virtualInterference",zeros(3,1));
            simParams = struct( ...
                "technology",constants.TECH_ONLY_11P, ...
                "cbrActive",true);
            phyParams = struct( ...
                "BwMHz",1, ...
                "PrxSensNotSynch",1, ...
                "PrxSensWhenSynch",1, ...
                "tSlot",0.01);
        end
    end
end
