classdef InitiateMainSimulationParametersTest < matlab.unittest.TestCase
    %INITIATEMAINSIMULATIONPARAMETERSTEST Tests scenario config bridging.

    methods (TestClassSetup)
        function addLegacyInitializationPath(testCase)
            projectRoot = fileparts(fileparts(fileparts(fileparts( ...
                mfilename("fullpath")))));
            legacyInitializationPath = fullfile( ...
                projectRoot, "old_src", "MatFilesInit");
            addpath(legacyInitializationPath);
            testCase.addTeardown(@() rmpath(legacyInitializationPath));
        end
    end

    methods (Test)
        function testDefaultSelectsBidirectionalHighway(testCase)
            [simParams, remainingArguments] = ...
                testCase.initializeWithArguments({"simulation.RandomSeed", 1});

            testCase.verifyEqual( ...
                simParams.typeOfScenario, ...
                'BidirectionalHighwayScenario');
            testCase.verifyEqual( ...
                string(fieldnames(simParams.scenarioOptions)), ...
                ["VehicleCount"; "NLanes"; "LaneWidth"; ...
                "RoadLength"; "CentralDividerWidth"; ...
                "MeanVehicleSpeed"; ...
                "VehicleSpeedStandardDeviation"; ...
                "RerollSpeedOnWrapAround"]);
            testCase.verifyEqual(simParams.scenarioOptions.VehicleCount, 100);
            testCase.verifyClass( ...
                simParams.positionErrorChain, ...
                "v2xsim.positioning.PositionErrorChain");
            testCase.verifyEmpty(simParams.positionErrorChain.Modules);
            testCase.verifyEmpty(simParams.positionErrorModuleNames);
            testCase.verifyEmpty(remainingArguments{1});
        end

        function testV6NameEmitsCompatibilityWarning(testCase)
            testCase.verifyWarning( ...
                @() testCase.initializeWithArguments({"seed", 7}), ...
                "v2xsim:parameters:DeprecatedV6Name");
        end

        function testCanonicalAndV6NamesCannotConflict(testCase)
            testCase.verifyError( ...
                @() testCase.initializeWithArguments({ ...
                    "simulation.RandomSeed", 1, "seed", 2}), ...
                "v2xsim:parameters:ConflictingNames");
        end

        function testBrownianOptionsUseConstructorNames(testCase)
            inputArguments = { ...
                "simulation.RandomSeed", 1, ...
                "scenario.Type", "BrownianMotionScenario", ...
                "scenarioOptions.VehicleCount", 25, ...
                "scenarioOptions.SimulationAreaSize", 500, ...
                "scenarioOptions.MeanVehicleSpeed", 40, ...
                "scenarioOptions.VehicleSpeedStandardDeviation", 5};

            [simParams, remainingArguments] = ...
                testCase.initializeWithArguments(inputArguments);

            testCase.verifyEqual( ...
                string(fieldnames(simParams.scenarioOptions)), ...
                ["VehicleCount"; "SimulationAreaSize"; ...
                "MeanVehicleSpeed"; ...
                "VehicleSpeedStandardDeviation"]);
            testCase.verifyEqual(simParams.scenarioOptions.VehicleCount, 25);
            testCase.verifyEqual( ...
                simParams.scenarioOptions.SimulationAreaSize, 500);
            testCase.verifyEmpty(remainingArguments{1});
        end

        function testEtsiStringsBecomeScenarioEnums(testCase)
            inputArguments = { ...
                "simulation.RandomSeed", 1, ...
                "scenario.Type", "EtsiHighwayScenario", ...
                "scenarioOptions.TrafficModel", ...
                    "MediumSpeedMediumDensity", ...
                "scenarioOptions.Placement", "Gaussian", ...
                "scenarioOptions.MinimumRoadLength", 2500};

            [simParams, remainingArguments] = ...
                testCase.initializeWithArguments(inputArguments);

            import v2xsim.vehicle.scenarios.etsihighway.Placement
            import v2xsim.vehicle.scenarios.etsihighway.TrafficModel

            testCase.verifyEqual( ...
                simParams.scenarioOptions.TrafficModel, ...
                TrafficModel.MediumSpeedMediumDensity);
            testCase.verifyEqual( ...
                simParams.scenarioOptions.Placement, Placement.Gaussian);
            testCase.verifyEqual( ...
                simParams.scenarioOptions.MinimumRoadLength, 2500);
            testCase.verifyEmpty(remainingArguments{1});
        end

        function testExitRampOptionsUseConstructorNames(testCase)
            inputArguments = { ...
                "simulation.RandomSeed", 1, ...
                "scenario.Type", "ExitRampHighwayScenario", ...
                "scenarioOptions.VehicleCount", 80, ...
                "scenarioOptions.NLanes", 3, ...
                "scenarioOptions.ExitProbability", 0.2, ...
                "scenarioOptions.MergeDistance", 60};

            [simParams, remainingArguments] = ...
                testCase.initializeWithArguments(inputArguments);

            testCase.verifyEqual( ...
                string(fieldnames(simParams.scenarioOptions)), ...
                ["VehicleCount"; "NLanes"; "LaneWidth"; ...
                "RoadLength"; "CentralDividerWidth"; ...
                "MeanVehicleSpeed"; ...
                "VehicleSpeedStandardDeviation"; ...
                "RerollSpeedOnWrapAround"; "ExitProbability"; ...
                "MergeDistance"]);
            testCase.verifyEqual(simParams.scenarioOptions.NLanes, 3);
            testCase.verifyEqual( ...
                simParams.scenarioOptions.ExitProbability, 0.2);
            testCase.verifyEqual( ...
                simParams.scenarioOptions.MergeDistance, 60);
            testCase.verifyEmpty(remainingArguments{1});
        end

        function testConfigFileAndCommandLinePrecedence(testCase)
            configPath = string(tempname) + ".cfg";
            writelines([ ...
                "[simulation.RandomSeed] 1", ...
                "[scenario.Type] BrownianMotionScenario", ...
                "[scenarioOptions.VehicleCount] 20", ...
                "[scenarioOptions.SimulationAreaSize] 750", ...
                "[scenarioOptions.MeanVehicleSpeed] 30"], configPath);
            testCase.addTeardown(@() delete(configPath));

            inputArguments = { ...
                "scenarioOptions.VehicleCount", 35, ...
                "scenarioOptions.VehicleSpeedStandardDeviation", 2};
            [simParams, remainingArguments] = ...
                testCase.initializeWithArguments( ...
                    inputArguments, configPath);

            testCase.verifyEqual(simParams.scenarioOptions.VehicleCount, 35);
            testCase.verifyEqual( ...
                simParams.scenarioOptions.SimulationAreaSize, 750);
            testCase.verifyEqual( ...
                simParams.scenarioOptions.MeanVehicleSpeed, 30);
            testCase.verifyEqual( ...
                simParams.scenarioOptions.VehicleSpeedStandardDeviation, 2);
            testCase.verifyEmpty(remainingArguments{1});
        end

        function testRemovedLegacyScenarioNameIsRejected(testCase)
            testCase.verifyError( ...
                @() testCase.initializeWithArguments( ...
                    {"simulation.RandomSeed", 1, "scenario.Type", "PPP"}), ...
                "v2xsim:legacy:UnknownScenario");
        end

        function testParsesOrderedPositionErrorChain(testCase)
            inputArguments = { ...
                "simulation.RandomSeed", 1, ...
                "scenario.Type", "ExitRampHighwayScenario", ...
                "positioning.ErrorModules", ...
                    "Gaussian,FalseExit,Delay,FalseMerge", ...
                "positioning.Gaussian.StandardDeviationMeters", ...
                    3, ...
                "positioning.FalseExit.AffectedVehicleProbability", ...
                    0.1, ...
                "positioning.FalseExit.ResetAfterSeconds", ...
                    5, ...
                "positioning.Delay.DelaySeconds", 0.5, ...
                "positioning.FalseMerge.AffectedVehicleProbability", ...
                    0.2};

            [simParams, remainingArguments] = ...
                testCase.initializeWithArguments(inputArguments);

            modules = simParams.positionErrorChain.Modules;
            testCase.verifyEqual( ...
                simParams.positionErrorModuleNames, ...
                ["Gaussian", "FalseExit", "Delay", "FalseMerge"]);
            testCase.verifyClass( ...
                modules{1}, ...
                "v2xsim.positioning.IsotropicGaussianPositionError");
            testCase.verifyEqual( ...
                modules{1}.StandardDeviationMeters, 3);
            testCase.verifyClass( ...
                modules{2}, ...
                "v2xsim.positioning.FalseExitPositionError");
            testCase.verifyEqual(modules{2}.CurseProbability, 0.1);
            testCase.verifyEqual(modules{2}.ResetAfterSeconds, 5);
            testCase.verifyClass( ...
                modules{3}, ...
                "v2xsim.positioning.PositionDelayError");
            testCase.verifyEqual(modules{3}.DelaySeconds, 0.5);
            testCase.verifyClass( ...
                modules{4}, ...
                "v2xsim.positioning.FalseMergePositionError");
            testCase.verifyEqual(modules{4}.CurseProbability, 0.2);
            testCase.verifyEqual(modules{4}.ResetAfterSeconds, Inf);
            testCase.verifyEmpty(remainingArguments{1});
        end

        function testPositionErrorConfigAllowsCommandLineOverride( ...
                testCase)
            configPath = string(tempname) + ".cfg";
            writelines([ ...
                "[simulation.RandomSeed] 1", ...
                "[positioning.ErrorModules] Gaussian,Delay", ...
                "[positioning.Gaussian." + ...
                    "StandardDeviationMeters] 2", ...
                "[positioning.Delay.DelaySeconds] 0.5"], ...
                configPath);
            testCase.addTeardown(@() delete(configPath));

            [simParams, remainingArguments] = ...
                testCase.initializeWithArguments( ...
                    { ...
                    "positioning.Gaussian." + ...
                        "StandardDeviationMeters", 4}, ...
                    configPath);

            modules = simParams.positionErrorChain.Modules;
            testCase.verifyEqual( ...
                modules{1}.StandardDeviationMeters, 4);
            testCase.verifyEqual(modules{2}.DelaySeconds, 0.5);
            testCase.verifyEmpty(remainingArguments{1});
        end

        function testRejectsRampErrorForOtherScenario(testCase)
            testCase.verifyError( ...
                @() testCase.initializeWithArguments({ ...
                    "simulation.RandomSeed", 1, ...
                    "scenario.Type", "BidirectionalHighwayScenario", ...
                    "positioning.ErrorModules", "FalseExit"}), ...
                "v2xsim:legacy:IncompatiblePositionErrorModule");
        end

        function testRejectsUnknownPositionErrorModule(testCase)
            testCase.verifyError( ...
                @() testCase.initializeWithArguments({ ...
                    "simulation.RandomSeed", 1, ...
                    "positioning.ErrorModules", "Teleport"}), ...
                "v2xsim:legacy:UnknownPositionErrorModule");
        end

        function testRejectsDuplicatePositionErrorModule(testCase)
            testCase.verifyError( ...
                @() testCase.initializeWithArguments({ ...
                    "simulation.RandomSeed", 1, ...
                    "positioning.ErrorModules", "Gaussian,Gaussian"}), ...
                "v2xsim:legacy:DuplicatePositionErrorModule");
        end
    end

    methods (Access = private)
        function [simParams, remainingArguments] = ...
                initializeWithArguments(~, inputArguments, configPath)
            if nargin < 3
                configPath = "";
            end

            [simParams, remainingArguments] = ...
                initiateMainSimulationParameters( ...
                    configPath, inputArguments);
        end
    end
end
