classdef LegacySemanticDispatchTest < matlab.unittest.TestCase
    %LEGACYSEMANTICDISPATCHTEST Semantic contracts at god-object seams.

    methods (TestClassSetup)
        function addDispatchPaths(testCase)
            projectRoot = string(fileparts(fileparts(fileparts( ...
                fileparts(mfilename("fullpath"))))));
            originalPath = path;
            testCase.addTeardown(@() path(originalPath));
            pathsToAdd = [ ...
                fullfile(projectRoot,"src"), ...
                fullfile(projectRoot,"tests"), ...
                fullfile(projectRoot,"old_src","MainFiles"), ...
                fullfile(projectRoot,"old_src","MatFilesUtility")];
            for pathToAdd = pathsToAdd
                addpath(pathToAdd);
            end
        end
    end

    methods (Test)
        function testNeighborSnapshotPreservesWorldIdentity(testCase)
            [world,registry,dispatcher] = ...
                testCase.createCaptureRegistry( ...
                    v2xsim.hook.points.AfterNeighborGraphUpdated);
            stationManagement = struct( ...
                "activeIDs",[3;1;4;2], ...
                "activeIDsCV2X",[1;2], ...
                "activeIDs11p",[3;4]);
            positionManagement = struct( ...
                "distanceReal",testCase.distanceMatrix());
            simValues = struct( ...
                "world",world, ...
                "hookDispatcher",dispatcher);

            dispatchAfterNeighborGraphUpdated( ...
                simValues,struct("timeNow",0.25), ...
                stationManagement,positionManagement, ...
                struct("Raw",[100 200]),[6 10],[4 8]);

            hook = testCase.capturedHook( ...
                registry, ...
                v2xsim.hook.points.AfterNeighborGraphUpdated);
            testCase.verifyNumElements(hook.Invocations,1);
            invocation = hook.Invocations{1};
            testCase.verifyEqual(invocation.UeIds,[3;1;4;2]);
            testCase.verifyEqual( ...
                world.UeIds(invocation.UeIds), ...
                ["wifi";"alpha";"roadside";"beta"]);
            testCase.verifyEqual( ...
                invocation.DistanceMatrixMeters, ...
                positionManagement.distanceReal( ...
                    stationManagement.activeIDs, ...
                    stationManagement.activeIDs));
            testCase.verifyEqual( ...
                invocation.AverageCv2xNeighbors,[3 5]);
            testCase.verifyEqual( ...
                invocation.AverageItsG5Neighbors,[2 4]);
        end

        function testPacketFatesPreserveEndpointIdentityAndCounts( ...
                testCase)
            [world,registry,dispatcher] = ...
                testCase.createCaptureRegistry( ...
                    v2xsim.hook.points.AfterPacketFatesDetermined);
            stationManagement = struct( ...
                "activeIDs",(1:4).', ...
                "vehicleChannel",[1;2;1;2], ...
                "pckType",[1;1;2;2], ...
                "pckTxOccurring",[0;2;0;1], ...
                "BRid",[ ...
                    11,12; ...
                    21,22; ...
                    31,32; ...
                    41,42]);
            simValues = struct( ...
                "world",world, ...
                "maxID",4, ...
                "resourceAllocationEpoch",uint64(6), ...
                "hookDispatcher",dispatcher);
            positionManagement = struct( ...
                "distanceReal",testCase.distanceMatrix());

            dispatchAfterPacketFatesDetermined( ...
                simValues,0.5,"LTE",[100 200], ...
                stationManagement,positionManagement, ...
                [2;1],[0.4;0.45], ...
                [4 3 0;3 4 0], ...
                [2 4;1 3],[2 3],"blocked");

            hook = testCase.capturedHook( ...
                registry, ...
                v2xsim.hook.points.AfterPacketFatesDetermined);
            invocation = hook.Invocations{1};
            testCase.verifyEqual( ...
                world.UeIds(invocation.Transmitters.TransmitterId), ...
                ["beta";"alpha"]);
            testCase.verifyEqual(height(invocation.Links),4);
            endpointNames = table( ...
                world.UeIds(invocation.Links.TransmitterId), ...
                world.UeIds(invocation.Links.ReceiverId), ...
                invocation.Links.Outcome, ...
                VariableNames=["Transmitter","Receiver","Outcome"]);
            expected = table( ...
                ["beta";"beta";"alpha";"alpha"], ...
                ["roadside";"wifi";"wifi";"roadside"], ...
                ["correct";"error";"correct";"blocked"], ...
                VariableNames=["Transmitter","Receiver","Outcome"]);
            testCase.verifyEqual(endpointNames,expected);
            expectedDistances = arrayfun( ...
                @(row) positionManagement.distanceReal( ...
                    invocation.Links.TransmitterId(row), ...
                    invocation.Links.ReceiverId(row)), ...
                (1:height(invocation.Links)).');
            testCase.verifyEqual( ...
                invocation.Links.DistanceMeters,expectedDistances);
            testCase.verifyEqual( ...
                invocation.Transmitters.TransmitterUeId, ...
                ["beta";"alpha"]);
            testCase.verifyEqual( ...
                invocation.Transmitters.AttemptNumber,[2;0]);
            testCase.verifyEqual( ...
                invocation.Transmitters.ResourceId,[22;nan]);
            testCase.verifyEqual( ...
                invocation.Transmitters.AllocationEpoch,[6;6]);
            testCase.verifyEqual( ...
                invocation.Links.TransmitterUeId, ...
                ["beta";"beta";"alpha";"alpha"]);
            testCase.verifyEqual( ...
                invocation.Links.ReceiverUeId, ...
                ["roadside";"wifi";"wifi";"roadside"]);
            testCase.verifyEqual( ...
                invocation.Links.IsTerminal, ...
                [true;true;true;true]);
            outcomes = string(invocation.Links.Outcome);
            testCase.verifyEqual( ...
                [ ...
                    nnz(outcomes == "correct"); ...
                    nnz(outcomes == "error"); ...
                    nnz(outcomes == "blocked")], ...
                [2;1;1]);
        end
    end

    methods (Access = private)
        function [world,registry,dispatcher] = ...
                createCaptureRegistry(testCase,point)
            world = testCase.createWorld();
            container = ...
                v2xsim.hook.dependency.ServiceContainer();
            registry = v2xsim.hook.HookRegistry(container);
            registry.register( ...
                v2xsimtest.legacy.fixture.InvocationCaptureHook(), ...
                point);
            dispatcher = registry.createDispatcher();
        end

        function hook = capturedHook(~,registry,point)
            hooks = registry.getHooks(point);
            hook = hooks{1};
        end

        function world = createWorld(testCase)
            vehicleIds = ["alpha";"beta";"wifi"];
            kinematics = testCase.createKinematics(vehicleIds);
            transitions = testCase.createTransitions(vehicleIds);
            scenario = ...
                v2xsimtest.vehicle.scenario.fixture.ScenarioStub( ...
                    kinematics,kinematics,transitions);
            rsuPositions = table( ...
                30,40, ...
                VariableNames=["X","Y"], ...
                RowNames="roadside");
            world = v2xsim.World(scenario,rsuPositions);
        end

        function value = createKinematics(~,ids)
            count = numel(ids);
            value = table( ...
                (0:count - 1).' .* 10, ...
                zeros(count,1), ...
                nan(count,1), ...
                nan(count,1), ...
                nan(count,1), ...
                nan(count,1), ...
                VariableNames=["X","Y","vX","vY","aX","aY"], ...
                RowNames=cellstr(ids));
        end

        function value = createTransitions(~,ids)
            import v2xsim.vehicle.scenario.VehicleLifecycleTransition

            transition = repmat( ...
                VehicleLifecycleTransition.Unchanged,numel(ids),1);
            value = table( ...
                transition, ...
                VariableNames="Transition", ...
                RowNames=cellstr(ids));
        end

        function value = distanceMatrix(~)
            positions = [0 0;10 0;20 0;30 40];
            deltaX = positions(:,1) - positions(:,1).';
            deltaY = positions(:,2) - positions(:,2).';
            value = hypot(deltaX,deltaY);
        end
    end
end
