classdef OutputHookCompositionTest < matlab.unittest.TestCase
    %OUTPUTHOOKCOMPOSITIONTEST Tests output configuration composition.

    methods (TestClassSetup)
        function addCompatibilityPaths(testCase)
            projectRoot = fileparts(fileparts(fileparts(fileparts( ...
                mfilename("fullpath")))));
            pathToAdd = fullfile(projectRoot,"old_src","MatFilesInit");
            addpath(pathToAdd);
            testCase.addTeardown(@() rmpath(pathToAdd));
        end
    end

    methods (Test)
        function composesVehicleKinematicsRecorderFromRenamedOption( ...
                testCase)
            outputDirectory = testCase.makeOutputDirectory();
            inputArguments = { ...
                "output.Directory",outputDirectory, ...
                "output.VehicleKinematics.Enabled",true};

            [outParams,remainingArguments,outputHookOptions] = ...
                initiateOutParameters( ...
                    struct("cbrActive",false),struct(),"",inputArguments);

            testCase.assertEmpty(remainingArguments{1});
            testCase.verifyTrue( ...
                outputHookOptions.VehicleKinematicsEnabled);
            testCase.verifyFalse(isfield( ...
                outputHookOptions,"VehicleSpeedEnabled"));

            simParams = struct( ...
                "technology",constants.TECH_ONLY_11P);
            [registry,~] = composeOutputHooks( ...
                outputHookOptions,outParams,simParams, ...
                struct(),struct());
            testCase.addTeardown(@() registry.cleanup());
            hooks = registry.getHooks( ...
                v2xsim.hook.points. ...
                    AfterVehicleKinematicsUpdated);

            testCase.verifyNumElements(hooks,1);
            testCase.verifyInstanceOf( ...
                hooks{1}, ...
                "v2xsim.hooks.common.VehicleKinematicsRecorder");
        end

        function removedSpeedOptionIsNotAccepted(testCase)
            outputDirectory = testCase.makeOutputDirectory();
            inputArguments = { ...
                "output.Directory",outputDirectory, ...
                "output.VehicleSpeed.Enabled",true};

            [~,remainingArguments,outputHookOptions] = ...
                initiateOutParameters( ...
                    struct("cbrActive",false),struct(),"",inputArguments);

            testCase.verifyEqual( ...
                remainingArguments{1}, ...
                {"output.VehicleSpeed.Enabled",true});
            testCase.verifyFalse( ...
                outputHookOptions.VehicleKinematicsEnabled);
            testCase.verifyError( ...
                @() canonicalParameterName("printSpeed"), ...
                "v2xsim:parameters:UnregisteredParameter");
            testCase.verifyError( ...
                @() canonicalParameterName( ...
                    "output.VehicleSpeed.Enabled"), ...
                "v2xsim:parameters:UnregisteredParameter");
        end
    end

    methods (Access = private)
        function outputDirectory = makeOutputDirectory(testCase)
            fixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            outputDirectory = string(fixture.Folder);
        end
    end
end
