classdef OutputHookCompositionTest < matlab.unittest.TestCase
    %OUTPUTHOOKCOMPOSITIONTEST Tests output configuration composition.

    methods (TestClassSetup)
        function addCompatibilityPaths(testCase)
            projectRoot = fileparts(fileparts(fileparts(fileparts( ...
                mfilename("fullpath")))));
            pathToAdd = fullfile(projectRoot,"old_src","MatFilesInit");
            addpath(pathToAdd);
            testCase.addTeardown(@() rmpath(pathToAdd));
        end
    end

    methods (Test)
        function composesVehicleKinematicsRecorderFromRenamedOption( ...
                testCase)
            outputDirectory = testCase.makeOutputDirectory();
            inputArguments = { ...
                "output.Directory",outputDirectory, ...
                "output.VehicleKinematics.Enabled",true};

            [outParams,remainingArguments,outputHookOptions] = ...
                initiateOutParameters( ...
                    struct("cbrActive",false),struct(),"",inputArguments);

            testCase.assertEmpty(remainingArguments{1});
            testCase.verifyTrue( ...
                outputHookOptions.VehicleKinematicsEnabled);
            testCase.verifyFalse( ...
                outputHookOptions. ...
                    ControllerDiagnosticsRankDisplacementEnabled);
            testCase.verifyFalse(isfield( ...
                outputHookOptions,"VehicleSpeedEnabled"));

            simParams = struct( ...
                "technology",constants.TECH_ONLY_11P);
            [registry,~] = composeOutputHooks( ...
                outputHookOptions,outParams,simParams, ...
                struct(),struct());
            testCase.addTeardown(@() registry.cleanup());
            hooks = registry.getHooks( ...
                v2xsim.hook.points. ...
                    AfterVehicleKinematicsUpdated);

            testCase.verifyNumElements(hooks,1);
            testCase.verifyInstanceOf( ...
                hooks{1}, ...
                "v2xsim.hooks.common.VehicleKinematicsRecorder");
        end

        function composesTechnologySpecificNeighborCountRecorders( ...
                testCase)
            outputDirectory = testCase.makeOutputDirectory();
            inputArguments = { ...
                "output.Directory",outputDirectory, ...
                "output.AverageNeighborCount.Enabled",true};

            [outParams,remainingArguments,outputHookOptions] = ...
                initiateOutParameters( ...
                    struct("cbrActive",false),struct(),"",inputArguments);

            testCase.assertEmpty(remainingArguments{1});
            testCase.verifyTrue( ...
                outputHookOptions.AverageNeighborCountEnabled);

            simulationTechnologies = [ ...
                constants.TECH_ONLY_CV2X, ...
                constants.TECH_ONLY_11P, ...
                constants.TECH_COEX_NO_INTERF, ...
                constants.TECH_COEX_STD_INTERF];
            expectedRecorderTechnologies = { ...
                "cv2x", ...
                "itsg5", ...
                ["all", "cv2x", "itsg5"], ...
                ["all", "cv2x", "itsg5"]};

            for scenarioIndex = 1:numel(simulationTechnologies)
                simParams = struct( ...
                    "technology", ...
                    simulationTechnologies(scenarioIndex));
                [registry,~] = composeOutputHooks( ...
                    outputHookOptions,outParams,simParams, ...
                    struct(),struct());
                testCase.addTeardown(@() registry.cleanup());
                hooks = registry.getHooks( ...
                    v2xsim.hook.points. ...
                        AfterNeighborGraphUpdated);

                expectedTechnologies = ...
                    expectedRecorderTechnologies{scenarioIndex};
                testCase.verifyNumElements( ...
                    hooks,numel(expectedTechnologies));
                actualTechnologies = strings( ...
                    1,numel(hooks));
                for hookIndex = 1:numel(hooks)
                    testCase.verifyInstanceOf( ...
                        hooks{hookIndex}, ...
                        "v2xsim.hooks.common." + ...
                            "AverageNeighborCountRecorder");
                    actualTechnologies(hookIndex) = ...
                        hooks{hookIndex}.Technology;
                end
                testCase.verifyEqual( ...
                    actualTechnologies,expectedTechnologies);
            end
        end

        function removedNeighborCountSettingsAreNotAccepted(testCase)
            outputDirectory = testCase.makeOutputDirectory();
            oldSettings = [ ...
                "printNeighbors", ...
                "output.NeighborCount.Enabled"];

            for oldSetting = oldSettings
                inputArguments = { ...
                    "output.Directory",outputDirectory, ...
                    oldSetting,true};
                [~,remainingArguments,outputHookOptions] = ...
                    initiateOutParameters( ...
                        struct("cbrActive",false),struct(), ...
                        "",inputArguments);

                testCase.verifyEqual( ...
                    remainingArguments{1}, ...
                    {oldSetting,true});
                testCase.verifyFalse( ...
                    outputHookOptions.AverageNeighborCountEnabled);
                testCase.verifyError( ...
                    @() canonicalParameterName(oldSetting), ...
                    "v2xsim:parameters:UnregisteredParameter");
            end
        end

        function composesResearchDiagnosticRecorders(testCase)
            outputDirectory = testCase.makeOutputDirectory();
            inputArguments = { ...
                "output.Directory",outputDirectory, ...
                "output.PositionErrorTrace.Enabled",true, ...
                "output.PositionErrorTrace.FlushRowCount",37, ...
                "output.ControllerDiagnostics.Enabled",true, ...
                "output.ControllerDiagnostics.TopK",4, ...
                "output.ControllerDiagnostics." + ...
                    "RankDisplacementEnabled",true, ...
                "output.ControllerDiagnostics.FlushRowCount",53, ...
                "output.PacketFateTrace.Enabled",true, ...
                "output.PacketFateTrace.FlushRowCount",71, ...
                "output.PacketFateTrace.FileFormat","csv"};

            [outParams,remainingArguments,outputHookOptions] = ...
                initiateOutParameters( ...
                    struct("cbrActive",false),struct(),"",inputArguments);
            testCase.assertEmpty(remainingArguments{1});
            testCase.verifyTrue( ...
                outputHookOptions. ...
                    ControllerDiagnosticsRankDisplacementEnabled);

            simParams = struct( ...
                "technology",constants.TECH_ONLY_CV2X);
            frequencyCoupling = [1,0.1;0.2,1];
            [registry,~] = composeOutputHooks( ...
                outputHookOptions,outParams,simParams, ...
                struct(),struct( ...
                    "Raw",300, ...
                    "IBEmatrixData",frequencyCoupling));
            testCase.addTeardown(@() registry.cleanup());

            positioningHooks = registry.getHooks( ...
                v2xsim.hook.points. ...
                    AfterPositionErrorChainApplied);
            controllerHooks = registry.getHooks( ...
                v2xsim.hook.points. ...
                    AfterResourceAllocationDecision);
            packetHooks = registry.getHooks( ...
                v2xsim.hook.points.AfterPacketFatesDetermined);
            testCase.verifyNumElements(positioningHooks,1);
            testCase.verifyNumElements(controllerHooks,1);
            testCase.verifyClass( ...
                positioningHooks{1}, ...
                "v2xsim.hooks.common.PositionErrorTraceRecorder");
            testCase.verifyEqual( ...
                positioningHooks{1}.FlushEveryRows,37);
            testCase.verifyClass( ...
                controllerHooks{1}, ...
                "v2xsim.hooks.common.ControllerDiagnosticsRecorder");
            testCase.verifyEqual(controllerHooks{1}.TopK,4);
            testCase.verifyTrue( ...
                controllerHooks{1}.RankDisplacementEnabled);
            testCase.verifyEqual( ...
                controllerHooks{1}.FlushRowCount,53);
            testCase.verifyEqual( ...
                controllerHooks{1}. ...
                    FrequencyInterferenceCoupling, ...
                frequencyCoupling);
            testCase.verifyNumElements(packetHooks,1);
            testCase.verifyClass( ...
                packetHooks{1}, ...
                "v2xsim.hooks.common.PacketFateTraceRecorder");
            testCase.verifyEqual(packetHooks{1}.FlushRowCount,71);
            testCase.verifyEqual(packetHooks{1}.FileFormat,"csv");
        end

        function removedSpeedOptionIsNotAccepted(testCase)
            outputDirectory = testCase.makeOutputDirectory();
            inputArguments = { ...
                "output.Directory",outputDirectory, ...
                "output.VehicleSpeed.Enabled",true};

            [~,remainingArguments,outputHookOptions] = ...
                initiateOutParameters( ...
                    struct("cbrActive",false),struct(),"",inputArguments);

            testCase.verifyEqual( ...
                remainingArguments{1}, ...
                {"output.VehicleSpeed.Enabled",true});
            testCase.verifyFalse( ...
                outputHookOptions.VehicleKinematicsEnabled);
            testCase.verifyError( ...
                @() canonicalParameterName("printSpeed"), ...
                "v2xsim:parameters:UnregisteredParameter");
            testCase.verifyError( ...
                @() canonicalParameterName( ...
                    "output.VehicleSpeed.Enabled"), ...
                "v2xsim:parameters:UnregisteredParameter");
        end

        function composesCausalInterferenceRecorderAtBothPoints( ...
                testCase)
            outputDirectory = testCase.makeOutputDirectory();
            inputArguments = { ...
                "output.Directory",outputDirectory, ...
                "output.InterferenceClassification.Enabled",true, ...
                "output.PacketFateTrace.FlushRowCount",17};
            [outParams,remainingArguments,outputHookOptions] = ...
                initiateOutParameters( ...
                    struct("cbrActive",false),struct(), ...
                    "",inputArguments);
            testCase.assertEmpty(remainingArguments{1});
            testCase.verifyTrue( ...
                outputHookOptions.PositionErrorTraceEnabled);
            testCase.verifyTrue( ...
                outputHookOptions.ControllerDiagnosticsEnabled);
            testCase.verifyTrue( ...
                outputHookOptions.PacketFateTraceEnabled);

            simParams = struct( ...
                "technology",constants.TECH_ONLY_CV2X);
            [registry,~] = composeOutputHooks( ...
                outputHookOptions,outParams,simParams, ...
                struct(),struct("Raw",300));
            testCase.addTeardown(@() registry.cleanup());
            packetHooks = registry.getHooks( ...
                v2xsim.hook.points.AfterPacketFatesDetermined);
            evidenceHooks = registry.getHooks( ...
                v2xsim.hook.points. ...
                    AfterInterferenceEvidenceDetermined);

            testCase.verifyNumElements(packetHooks,2);
            testCase.verifyClass( ...
                packetHooks{2}, ...
                "v2xsim.hooks.common.InterferenceEvidenceRecorder");
            testCase.verifyEqual(packetHooks{2}.FlushRowCount,17);
            testCase.verifyNumElements(evidenceHooks,1);
            testCase.verifyEqual(packetHooks{2},evidenceHooks{1});
        end
    end

    methods (Access = private)
        function outputDirectory = makeOutputDirectory(testCase)
            fixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            outputDirectory = string(fixture.Folder);
        end
    end
end
