classdef OutputHookCompositionTest < matlab.unittest.TestCase
    %OUTPUTHOOKCOMPOSITIONTEST Tests output configuration composition.

    methods (TestClassSetup)
        function addCompatibilityPaths(testCase)
            projectRoot = fileparts(fileparts(fileparts(fileparts( ...
                mfilename("fullpath")))));
            pathToAdd = fullfile(projectRoot,"old_src","MatFilesInit");
            addpath(pathToAdd);
            testCase.addTeardown(@() rmpath(pathToAdd));
        end
    end

    methods (Test)
        function composesVehicleKinematicsRecorderFromRenamedOption( ...
                testCase)
            outputDirectory = testCase.makeOutputDirectory();
            inputArguments = { ...
                "output.Directory",outputDirectory, ...
                "output.VehicleKinematics.Enabled",true};

            [outParams,remainingArguments,outputHookOptions] = ...
                initiateOutParameters( ...
                    struct("cbrActive",false),struct(),"",inputArguments);

            testCase.assertEmpty(remainingArguments{1});
            testCase.verifyTrue( ...
                outputHookOptions.VehicleKinematicsEnabled);
            testCase.verifyFalse(isfield( ...
                outputHookOptions,"VehicleSpeedEnabled"));

            simParams = struct( ...
                "technology",constants.TECH_ONLY_11P);
            [registry,~] = composeOutputHooks( ...
                outputHookOptions,outParams,simParams, ...
                struct(),struct());
            testCase.addTeardown(@() registry.cleanup());
            hooks = registry.getHooks( ...
                v2xsim.hook.points. ...
                    AfterVehicleKinematicsUpdated);

            testCase.verifyNumElements(hooks,1);
            testCase.verifyInstanceOf( ...
                hooks{1}, ...
                "v2xsim.hooks.common.VehicleKinematicsRecorder");
        end

        function composesTechnologySpecificNeighborCountRecorders( ...
                testCase)
            outputDirectory = testCase.makeOutputDirectory();
            inputArguments = { ...
                "output.Directory",outputDirectory, ...
                "output.AverageNeighborCount.Enabled",true};

            [outParams,remainingArguments,outputHookOptions] = ...
                initiateOutParameters( ...
                    struct("cbrActive",false),struct(),"",inputArguments);

            testCase.assertEmpty(remainingArguments{1});
            testCase.verifyTrue( ...
                outputHookOptions.AverageNeighborCountEnabled);

            simulationTechnologies = [ ...
                constants.TECH_ONLY_CV2X, ...
                constants.TECH_ONLY_11P, ...
                constants.TECH_COEX_NO_INTERF, ...
                constants.TECH_COEX_STD_INTERF];
            expectedRecorderTechnologies = { ...
                "cv2x", ...
                "itsg5", ...
                ["all", "cv2x", "itsg5"], ...
                ["all", "cv2x", "itsg5"]};

            for scenarioIndex = 1:numel(simulationTechnologies)
                simParams = struct( ...
                    "technology", ...
                    simulationTechnologies(scenarioIndex));
                [registry,~] = composeOutputHooks( ...
                    outputHookOptions,outParams,simParams, ...
                    struct(),struct());
                testCase.addTeardown(@() registry.cleanup());
                hooks = registry.getHooks( ...
                    v2xsim.hook.points. ...
                        AfterNeighborGraphUpdated);

                expectedTechnologies = ...
                    expectedRecorderTechnologies{scenarioIndex};
                testCase.verifyNumElements( ...
                    hooks,numel(expectedTechnologies));
                actualTechnologies = strings( ...
                    1,numel(hooks));
                for hookIndex = 1:numel(hooks)
                    testCase.verifyInstanceOf( ...
                        hooks{hookIndex}, ...
                        "v2xsim.hooks.common." + ...
                            "AverageNeighborCountRecorder");
                    actualTechnologies(hookIndex) = ...
                        hooks{hookIndex}.Technology;
                end
                testCase.verifyEqual( ...
                    actualTechnologies,expectedTechnologies);
            end
        end

        function removedNeighborCountSettingsAreNotAccepted(testCase)
            outputDirectory = testCase.makeOutputDirectory();
            oldSettings = [ ...
                "printNeighbors", ...
                "output.NeighborCount.Enabled"];

            for oldSetting = oldSettings
                inputArguments = { ...
                    "output.Directory",outputDirectory, ...
                    oldSetting,true};
                [~,remainingArguments,outputHookOptions] = ...
                    initiateOutParameters( ...
                        struct("cbrActive",false),struct(), ...
                        "",inputArguments);

                testCase.verifyEqual( ...
                    remainingArguments{1}, ...
                    {oldSetting,true});
                testCase.verifyFalse( ...
                    outputHookOptions.AverageNeighborCountEnabled);
                testCase.verifyError( ...
                    @() canonicalParameterName(oldSetting), ...
                    "v2xsim:parameters:UnregisteredParameter");
            end
        end

        function removedSpeedOptionIsNotAccepted(testCase)
            outputDirectory = testCase.makeOutputDirectory();
            inputArguments = { ...
                "output.Directory",outputDirectory, ...
                "output.VehicleSpeed.Enabled",true};

            [~,remainingArguments,outputHookOptions] = ...
                initiateOutParameters( ...
                    struct("cbrActive",false),struct(),"",inputArguments);

            testCase.verifyEqual( ...
                remainingArguments{1}, ...
                {"output.VehicleSpeed.Enabled",true});
            testCase.verifyFalse( ...
                outputHookOptions.VehicleKinematicsEnabled);
            testCase.verifyError( ...
                @() canonicalParameterName("printSpeed"), ...
                "v2xsim:parameters:UnregisteredParameter");
            testCase.verifyError( ...
                @() canonicalParameterName( ...
                    "output.VehicleSpeed.Enabled"), ...
                "v2xsim:parameters:UnregisteredParameter");
        end
    end

    methods (Access = private)
        function outputDirectory = makeOutputDirectory(testCase)
            fixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            outputDirectory = string(fixture.Folder);
        end
    end
end
