classdef ResourceAllocationBridgeTest < matlab.unittest.TestCase
    %RESOURCEALLOCATIONBRIDGETEST Identity-safe legacy allocator bridges.

    properties (SetAccess = private)
        ProjectRoot (1,1) string
    end

    methods (TestClassSetup)
        function addBridgePaths(testCase)
            testCase.ProjectRoot = string(fileparts(fileparts(fileparts( ...
                fileparts(mfilename("fullpath"))))));
            originalPath = path;
            testCase.addTeardown(@() path(originalPath));
            pathsToAdd = [ ...
                fullfile(testCase.ProjectRoot,"src"), ...
                fullfile(testCase.ProjectRoot,"tests"), ...
                fullfile(testCase.ProjectRoot,"old_src","MatFilesInit"), ...
                fullfile( ...
                    testCase.ProjectRoot,"old_src", ...
                    "MatFilesResourceAllocationCV2X")];
            for pathToAdd = pathsToAdd
                addpath(pathToAdd);
            end
        end
    end

    methods (Test)
        function testProjectsNamedAssignmentsIntoDenseLegacyRows(testCase)
            world = testCase.createWorld();
            grid = testCase.createGrid();
            assignments = table( ...
                ["alpha";"beta"],[1 2;3 NaN], ...
                VariableNames=["UeId","ResourceIds"]);
            reservations = table( ...
                ["alpha";"beta"],[5;4], ...
                VariableNames=["UeId","ResourceId"]);
            result = v2xsim.resource.ResourceAllocationResult( ...
                grid.NetworkSliceId,assignments, ...
                strings(0,1),strings(0,1),strings(0,1), ...
                reservations);
            stationManagement = struct( ...
                "activeIDsCV2X",[2;1], ...
                "vehicleState",[ ...
                    constants.V_STATE_LTE_TXRX; ...
                    constants.V_STATE_LTE_TXRX; ...
                    constants.V_STATE_11P_IDLE; ...
                    constants.V_STATE_11P_IDLE], ...
                "BRid",-2 .* ones(4,2));
            simValues = struct("world",world);

            stationManagement = projectResourceAllocation( ...
                stationManagement,simValues,result,grid);

            testCase.verifyEqual( ...
                stationManagement.BRid(1,:),[1 2]);
            testCase.verifyEqual( ...
                stationManagement.BRid(2,:), ...
                [3 constants.BRID_ACTV_LTE_NO_RSRC]);
            testCase.verifyEqual( ...
                stationManagement.BRid(3:4,:), ...
                repmat(constants.BRID_NOT_LTE,2,2));
            testCase.verifyTrue( ...
                stationManagement.resourceReservations(5,1));
            testCase.verifyTrue( ...
                stationManagement.resourceReservations(4,2));
            testCase.verifyEqual( ...
                nnz(stationManagement.resourceReservations),2);
        end

        function testBuildsCentralizedContextInActiveUeOrder(testCase)
            world = testCase.createWorld();
            grid = testCase.createGrid();
            allocator = v2xsim.resource.OrderedBenchmarkAllocator( ...
                grid,7);
            allocator = allocator.synchronizeUes(["beta";"alpha"]);
            sensingHistory = ...
                v2xsim.resource.sensing.SensingHistory(grid,2);
            sensingHistory = sensingHistory.synchronizeUes( ...
                ["beta";"alpha"]);

            stationManagement = struct( ...
                "activeIDsCV2X",[2;1], ...
                "indexInActiveIDs_ofLTEnodes",[2;1]);
            simValues = struct("world",world);
            timeManagement = struct( ...
                "timeNow",0.5, ...
                "timeLastPacket",[0.45;0.1;-1;-1], ...
                "timeNextPacket",inf(4,1));
            positionManagement = struct( ...
                "XvehicleReal",[10;20;30;40], ...
                "distanceEstimated",testCase.labeledMatrix(100), ...
                "distanceReal",testCase.labeledMatrix(200));
            sinrManagement = struct( ...
                "P_RX_MHz",[11 12;21 22], ...
                "Shadowing_dB",[31 32;41 42]);
            simParams = struct( ...
                "technology",constants.TECH_ONLY_CV2X);

            context = buildResourceAllocationContext( ...
                allocator,sensingHistory,simValues, ...
                stationManagement,timeManagement,positionManagement, ...
                sinrManagement,simParams,5);

            testCase.verifyClass( ...
                context,"v2xsim.resource.CentralizedAllocationContext");
            testCase.verifyEqual(context.UeIds,["beta";"alpha"]);
            testCase.verifyEqual(context.X,[20;10]);
            testCase.verifyEqual( ...
                context.EstimatedDistanceMeters, ...
                positionManagement.distanceEstimated([2 1],[2 1]));
            testCase.verifyEqual( ...
                context.TrueDistanceMeters, ...
                positionManagement.distanceReal([2 1],[2 1]));
            testCase.verifyEqual( ...
                context.ReceivedPowerWattsPerMHz,[22 21;12 11]);
            testCase.verifyEqual( ...
                context.ShadowingDecibels,[42 41;32 31]);
            testCase.verifyEqual(context.NewPacketMask,[false;true]);
        end

        function testSynchronizationRemovesExitedUeState(testCase)
            world = testCase.createWorld();
            grid = testCase.createGrid();
            allocator = v2xsim.resource.OrderedBenchmarkAllocator( ...
                grid,3);
            allocator = allocator.synchronizeUes(["alpha";"beta"]);
            sensingHistory = ...
                v2xsim.resource.sensing.SensingHistory(grid,2);
            sensingHistory = sensingHistory.synchronizeUes( ...
                ["alpha";"beta"]);
            sensingHistory = sensingHistory.update( ...
                grid.NetworkSliceId,["alpha";"beta"],0, ...
                [11 12 13;21 22 23], ...
                [true false false false false false; ...
                false false false true false false]);
            previousResult = v2xsim.resource.ResourceAllocationResult( ...
                grid.NetworkSliceId,allocator.Assignments, ...
                strings(0,1),strings(0,1),strings(0,1), ...
                table( ...
                    ["alpha";"beta"],[3;4], ...
                    VariableNames=["UeId","ResourceId"]));
            simValues = struct( ...
                "world",world, ...
                "resourceAllocator",allocator, ...
                "sensingHistory",sensingHistory, ...
                "resourceAllocationResult",previousResult);
            stationManagement = struct( ...
                "activeIDsCV2X",2, ...
                "vehicleState",[ ...
                    constants.V_STATE_11P_IDLE; ...
                    constants.V_STATE_LTE_TXRX; ...
                    constants.V_STATE_11P_IDLE; ...
                    constants.V_STATE_11P_IDLE], ...
                "BRid",-2 .* ones(4,1), ...
                "sensingMatrixCV2X",99 .* ones(2,6,4), ...
                "knownUsedMatrixCV2X",ones(6,4));

            [simValues,stationManagement] = ...
                synchronizeResourceAllocation( ...
                    simValues,stationManagement);

            testCase.verifyEqual( ...
                simValues.resourceAllocator.UeIds,"beta");
            testCase.verifyEqual( ...
                simValues.sensingHistory.UeIds,"beta");
            testCase.verifyEqual( ...
                simValues.resourceAllocationResult.Reservations, ...
                table( ...
                    "beta",4, ...
                    VariableNames=["UeId","ResourceId"]));
            testCase.verifyEqual( ...
                squeeze(stationManagement.sensingMatrixCV2X( ...
                    1,1:3,2)),[21 22 23]);
            testCase.verifyEqual( ...
                stationManagement.sensingMatrixCV2X(:,:,[1 3 4]), ...
                zeros(2,6,3), ...
                "Exited and noncellular identities must not retain " + ...
                "legacy sensing history.");
            testCase.verifyEqual( ...
                stationManagement.knownUsedMatrixCV2X(:,[1 3 4]), ...
                zeros(6,3), ...
                "Exited and noncellular identities must not retain " + ...
                "legacy reservations.");
            testCase.verifyEqual( ...
                stationManagement.knownUsedMatrixCV2X(:,2), ...
                [0;0;0;1;0;0]);
            testCase.verifyTrue( ...
                stationManagement.resourceReservations(4,2));
            testCase.verifyEqual( ...
                nnz(stationManagement.resourceReservations),1);
            testCase.verifyEqual( ...
                stationManagement.BRid(1),constants.BRID_NOT_LTE);
            testCase.verifyEqual( ...
                stationManagement.BRid(2), ...
                constants.BRID_ACTV_LTE_NO_RSRC);
        end
    end

    methods (Access = private)
        function world = createWorld(testCase)
            vehicleIds = ["alpha";"beta";"wifi"];
            vehicleKinematics = testCase.createKinematics(vehicleIds);
            transitions = testCase.createTransitions(vehicleIds);
            scenario = ...
                v2xsimtest.vehicle.scenario.fixture.ScenarioStub( ...
                    vehicleKinematics,vehicleKinematics,transitions);
            rsuPositions = table( ...
                40,0, ...
                VariableNames=["X","Y"], ...
                RowNames="roadside");
            world = v2xsim.World(scenario,rsuPositions);
        end

        function value = createKinematics(~,ids)
            count = numel(ids);
            value = table( ...
                (1:count).' .* 10, ...
                zeros(count,1), ...
                nan(count,1), ...
                nan(count,1), ...
                nan(count,1), ...
                nan(count,1), ...
                VariableNames=["X","Y","vX","vY","aX","aY"], ...
                RowNames=cellstr(ids));
        end

        function value = createTransitions(~,ids)
            import v2xsim.vehicle.scenario.VehicleLifecycleTransition

            transition = repmat( ...
                VehicleLifecycleTransition.Unchanged,numel(ids),1);
            value = table( ...
                transition, ...
                VariableNames="Transition", ...
                RowNames=cellstr(ids));
        end

        function grid = createGrid(~)
            grid = v2xsim.resource.BRResourceGrid( ...
                v2xsim.network.NetworkSliceId("global"), ...
                2,3,0.1);
        end

        function value = labeledMatrix(~,offset)
            value = offset + reshape(1:16,4,4);
            value(1:5:end) = 0;
        end
    end
end
