classdef ExposedReuseShadowStudyTest < matlab.unittest.TestCase
    methods (Test)
        function plansRepeatedMissedReuseEventsWithoutRadioClaims( ...
                testCase)
            candidates = testCase.makeCandidates(3);

            manifest = v2xsim.analysis. ...
                createExposedReuseShadowManifest( ...
                    candidates,SourceRunId="seed-7/run", ...
                    EvaluationHorizonSeconds=2, ...
                    AllocationIntervalSeconds=2, ...
                    AnalysisRangeMeters=250, ...
                    MinimumReceiverObservationCount=4);

            testCase.verifyEqual(height(manifest),3);
            testCase.verifyEqual( ...
                manifest.AllocationEpoch,uint64((1:3).'));
            testCase.verifyEqual( ...
                manifest.InterventionFirstResourceId,[9;9;9]);
            testCase.verifyEqual( ...
                manifest.InterventionSecondResourceId,[9;9;9]);
            testCase.verifyTrue(all(manifest.StateSnapshotRequired));
            testCase.verifyTrue(all(manifest.ControlReplayRequired));
            testCase.verifyTrue( ...
                all(manifest.CommonRandomNumbersRequired));
            testCase.verifyEqual( ...
                manifest.InterventionPolicy, ...
                repmat( ...
                    "single_epoch_replicated_from_fork",3,1));
            testCase.verifyTrue(all( ...
                manifest.StopBeforeNextAllocationDecision));
            testCase.verifyEqual( ...
                manifest.RequiredIndependentReplicateCount, ...
                repmat(4,3,1));
            testCase.verifyEqual( ...
                manifest.OpportunityStatus, ...
                repmat("shadow_run_required",3,1));
            testCase.verifyFalse( ...
                ismember( ...
                    "IsExposedOpportunity", ...
                    string(manifest.Properties.VariableNames)));
        end

        function emptyCandidateTraceKeepsManifestSchema(testCase)
            manifest = v2xsim.analysis. ...
                createExposedReuseShadowManifest( ...
                    testCase.makeCandidates(0));

            testCase.verifyEmpty(manifest);
            testCase.verifyTrue(ismember( ...
                "ShadowCaseId", ...
                string(manifest.Properties.VariableNames)));
            testCase.verifyTrue(ismember( ...
                "OpportunityStatus", ...
                string(manifest.Properties.VariableNames)));
        end

        function excludesAlreadyConcurrentMissedReusePairs( ...
                testCase)
            candidates = testCase.makeCandidates(3);
            candidates.LiveResourceRelation = [ ...
                "adjacent_channel"; ...
                "other_same_time"; ...
                "separate_time"];

            manifest = v2xsim.analysis. ...
                createExposedReuseShadowManifest(candidates);

            testCase.verifyEqual(height(manifest),1);
            testCase.verifyEqual( ...
                manifest.AllocationEpoch,uint64(3));
        end

        function subsamplesDeterministicallyWithAnalysisWeights( ...
                testCase)
            candidates = testCase.makeCandidates(5);

            first = v2xsim.analysis. ...
                createExposedReuseShadowManifest( ...
                    candidates,MaximumCases=2,SelectionSeed=17);
            second = v2xsim.analysis. ...
                createExposedReuseShadowManifest( ...
                    candidates,MaximumCases=2,SelectionSeed=17);

            testCase.verifyEqual(first.ShadowCaseId, ...
                second.ShadowCaseId);
            testCase.verifyEqual(height(first),2);
            testCase.verifyEqual( ...
                first.SelectionProbability,repmat(0.4,2,1));
            testCase.verifyEqual( ...
                first.AnalysisWeight,repmat(2.5,2,1));
        end

        function rejectsHorizonPastNextAllocation(testCase)
            testCase.verifyError( ...
                @() v2xsim.analysis. ...
                    createExposedReuseShadowManifest( ...
                        testCase.makeCandidates(1), ...
                        EvaluationHorizonSeconds=0.2, ...
                        AllocationIntervalSeconds=0.1), ...
                "v2xsim:analysis:" + ...
                "ShadowHorizonCrossesAllocationDecision");
        end

        function eventKeysKeepRepeatedPairsSeparate(testCase)
            candidates = table( ...
                uint64([1;2]),["A";"A"],["B";"B"], ...
                ["missed_reuse";"missed_reuse"], ...
                VariableNames=[ ...
                    "AllocationEpoch","FirstUeId", ...
                    "SecondUeId","CandidateType"]);
            predictions = table( ...
                uint64([1;2]),["A";"A"],["B";"B"],["R";"R"], ...
                true(2,1),true(2,1),[0.95;0.4], ...
                VariableNames=[ ...
                    "AllocationEpoch","FirstUeId","SecondUeId", ...
                    "ReceiverUeId","IsSameTechnology", ...
                    "IsWithinAnalysisRange","PredictedPrr"]);

            classified = v2xsim.analysis. ...
                classifyExposedReuseOpportunities( ...
                    candidates,predictions, ...
                    PredictionsAreComplete=true, ...
                    EventKeyVariables="AllocationEpoch");

            testCase.verifyEqual( ...
                classified.OpportunityStatus,["exposed";"unsafe"]);
            testCase.verifyEqual( ...
                classified.IsExposedOpportunity,[true;false]);
        end

        function requiresExecutionAndCompleteReceiverCoverage(testCase)
            manifest = v2xsim.analysis. ...
                createExposedReuseShadowManifest( ...
                    testCase.makeCandidates(4), ...
                    MinimumReceiverObservationCount=10);
            caseIds = manifest.ShadowCaseId;
            executions = table( ...
                caseIds(2:4),repmat("complete",3,1), ...
                true(3,1),true(3,1),true(3,1),true(3,1), ...
                VariableNames=[ ...
                    "ShadowCaseId","ExecutionStatus", ...
                    "StateSnapshotRestored", ...
                    "ControlReplayMatchedSource", ...
                    "CommonRandomNumbersVerified", ...
                    "ReceiverRosterComplete"]);
            roster = table( ...
                caseIds,repmat("A",4,1),repmat("R",4,1), ...
                true(4,1),true(4,1), ...
                VariableNames=[ ...
                    "ShadowCaseId","TransmitterUeId","ReceiverUeId", ...
                    "IsSameTechnology","IsWithinAnalysisRange"]);
            counts = table( ...
                caseIds(2:4),repmat("A",3,1),repmat("R",3,1), ...
                [5;9;8],[0;1;2],zeros(3,1), ...
                VariableNames=[ ...
                    "ShadowCaseId","TransmitterUeId","ReceiverUeId", ...
                    "CorrectCount","ErrorCount","BlockedCount"]);

            [classified,predictions,~,summary] = v2xsim.analysis. ...
                reduceExposedReuseShadowResults( ...
                    manifest,executions,roster,counts);

            testCase.verifyEqual( ...
                classified.OpportunityStatus, ...
                ["shadow_run_required"; ...
                "incomplete_receiver_coverage"; ...
                "exposed";"unsafe"]);
            testCase.verifyEqual( ...
                classified.IsExposedOpportunity, ...
                [false;false;true;false]);
            testCase.verifyEqual( ...
                classified.EligibleReceiverCount,ones(4,1));
            testCase.verifyEqual(height(predictions),3);
            testCase.verifyEqual( ...
                predictions.PredictedPrr,[1;0.9;0.8], ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                summary.Status,"IncompleteShadowEvaluation");
            testCase.verifyEqual(summary.CompleteCaseCount,2);
            testCase.verifyTrue(isnan( ...
                summary.ExposedOpportunityRate));
        end

        function rejectsACompletedButUnpairedShadowRun(testCase)
            manifest = v2xsim.analysis. ...
                createExposedReuseShadowManifest( ...
                    testCase.makeCandidates(1), ...
                    MinimumReceiverObservationCount=1);
            executions = table( ...
                manifest.ShadowCaseId,"complete",true,false,true,true, ...
                VariableNames=[ ...
                    "ShadowCaseId","ExecutionStatus", ...
                    "StateSnapshotRestored", ...
                    "ControlReplayMatchedSource", ...
                    "CommonRandomNumbersVerified", ...
                    "ReceiverRosterComplete"]);
            roster = table( ...
                manifest.ShadowCaseId,"A","R",true,true, ...
                VariableNames=[ ...
                    "ShadowCaseId","TransmitterUeId","ReceiverUeId", ...
                    "IsSameTechnology","IsWithinAnalysisRange"]);
            counts = table( ...
                manifest.ShadowCaseId,"A","R",1,0,0, ...
                VariableNames=[ ...
                    "ShadowCaseId","TransmitterUeId","ReceiverUeId", ...
                    "CorrectCount","ErrorCount","BlockedCount"]);

            classified = v2xsim.analysis. ...
                reduceExposedReuseShadowResults( ...
                    manifest,executions,roster,counts);

            testCase.verifyEqual( ...
                classified.OpportunityStatus,"invalid_shadow_run");
            testCase.verifyFalse( ...
                classified.IsExposedOpportunity);
        end

        function usesWorstEndpointLinkAtEachReceiver(testCase)
            manifest = v2xsim.analysis. ...
                createExposedReuseShadowManifest( ...
                    testCase.makeCandidates(1), ...
                    MinimumReceiverObservationCount=10);
            executions = table( ...
                manifest.ShadowCaseId,"complete", ...
                true,true,true,true, ...
                VariableNames=[ ...
                    "ShadowCaseId","ExecutionStatus", ...
                    "StateSnapshotRestored", ...
                    "ControlReplayMatchedSource", ...
                    "CommonRandomNumbersVerified", ...
                    "ReceiverRosterComplete"]);
            roster = table( ...
                repmat(manifest.ShadowCaseId,2,1),["A";"B"], ...
                ["R";"R"],true(2,1),true(2,1), ...
                VariableNames=[ ...
                    "ShadowCaseId","TransmitterUeId","ReceiverUeId", ...
                    "IsSameTechnology","IsWithinAnalysisRange"]);
            counts = table( ...
                repmat(manifest.ShadowCaseId,2,1),["A";"B"], ...
                ["R";"R"],[10;8],[0;2],[0;0], ...
                VariableNames=[ ...
                    "ShadowCaseId","TransmitterUeId","ReceiverUeId", ...
                    "CorrectCount","ErrorCount","BlockedCount"]);

            [classified,predictions,linkPredictions,summary] = ...
                v2xsim.analysis.reduceExposedReuseShadowResults( ...
                    manifest,executions,roster,counts);

            testCase.verifyEqual(height(linkPredictions),2);
            testCase.verifyEqual(predictions.PredictedPrr,0.8);
            testCase.verifyEqual( ...
                classified.OpportunityStatus,"unsafe");
            testCase.verifyEqual( ...
                classified.RequiredDirectedLinkCount,2);
            testCase.verifyEqual(summary.Status,"Complete");
            testCase.verifyEqual( ...
                summary.EstimatedEligibleTemporalCandidateCount,1);
            testCase.verifyEqual( ...
                summary.EstimatedExposedOpportunityCount,0);
            testCase.verifyEqual(summary.ExposedOpportunityRate,0);
        end
    end

    methods (Static, Access = private)
        function candidates = makeCandidates(count)
            epoch = uint64((1:count).');
            simulationTime = double(epoch) .* 0.1;
            candidates = table( ...
                simulationTime,epoch,repmat("global",count,1), ...
                repmat("A",count,1),repmat("B",count,1), ...
                repmat("missed_reuse",count,1), ...
                repmat("separate_time",count,1), ...
                repmat("cochannel",count,1), ...
                ones(count,1),repmat(2,count,1), ...
                repmat(9,count,1),repmat(9,count,1), ...
                VariableNames=[ ...
                    "SimulationTimeSeconds","AllocationEpoch", ...
                    "NetworkSliceId","FirstUeId","SecondUeId", ...
                    "CandidateType","LiveResourceRelation", ...
                    "OracleResourceRelation", ...
                    "LiveFirstResourceId", ...
                    "LiveSecondResourceId","OracleFirstResourceId", ...
                    "OracleSecondResourceId"]);
        end
    end
end
