classdef InterferenceEvidenceAnalysisTest < matlab.unittest.TestCase
    methods (Test)
        function computesMrcCounterfactualsPerTerminalAttempt(testCase)
            result = v2xsim.analysis. ...
                calculateCumulativeSinrCounterfactuals( ...
                    2,10,2,[3;5]);

            testCase.verifyEqual(result.ObservedSinr,3,AbsTol=1e-12);
            testCase.verifyEqual( ...
                result.SinrWithoutEachInterferer, ...
                [2 + 10/7;4],AbsTol=1e-12);
            testCase.verifyEqual( ...
                result.SinrWithoutAllInterferers,7,AbsTol=1e-12);
        end

        function removesInfiniteHalfDuplexPowerWithoutNan(testCase)
            result = v2xsim.analysis. ...
                calculateCumulativeSinrCounterfactuals( ...
                    0,10,2,[Inf;3]);

            testCase.verifyEqual(result.ObservedSinr,0);
            testCase.verifyEqual( ...
                result.SinrWithoutEachInterferer,[2;0]);
            testCase.verifyEqual( ...
                result.SinrWithoutAllInterferers,5);
            testCase.verifyFalse(any(isnan( ...
                result.SinrWithoutEachInterferer)));
        end

        function joinsPacketAndAllocatorEvidenceBeforeHiddenLabel( ...
                testCase)
            [fates,attempts,counterfactuals] = ...
                testCase.makeRecordedError("cochannel");
            reuseCandidates = testCase.makeReuseCandidate( ...
                "harmful_reuse","cochannel", ...
                "separate_time",true,false);

            [classified,evidence,coverage,exposedStatus] = ...
                v2xsim.analysis.classifyRecordedFailureModes( ...
                    fates,attempts,counterfactuals, ...
                    reuseCandidates);

            testCase.verifyEqual( ...
                evidence.PacketSequence,42);
            testCase.verifyTrue( ...
                evidence.IsHarmfulReuseCandidate);
            testCase.verifyEqual( ...
                classified.FailureMode,"hidden_terminal");
            testCase.verifyTrue(classified.IsHiddenTerminal);
            testCase.verifyTrue(coverage.EvidenceIsExhaustive);
            testCase.verifyEqual( ...
                exposedStatus,"shadow_predictions_required");
            testCase.verifyEqual( ...
                coverage.ExposedTerminalStatus, ...
                "shadow_predictions_required");
        end

        function adjacentAllocatorPlacementCanBeHiddenTerminal( ...
                testCase)
            [fates,attempts,counterfactuals] = ...
                testCase.makeRecordedError("adjacent_channel");
            reuseCandidates = testCase.makeReuseCandidate( ...
                "unchanged_separation","adjacent_channel", ...
                "separate_time",true,false);

            [classified,evidence] = ...
                v2xsim.analysis.classifyRecordedFailureModes( ...
                    fates,attempts,counterfactuals, ...
                    reuseCandidates);

            testCase.verifyTrue( ...
                evidence.IsHarmfulReuseCandidate);
            testCase.verifyEqual( ...
                classified.FailureMode,"hidden_terminal");
            testCase.verifyTrue(classified.IsHiddenTerminal);
        end

        function fartherSameTimeLeakageCanBeHiddenTerminal( ...
                testCase)
            [fates,attempts,counterfactuals] = ...
                testCase.makeRecordedError("other");
            reuseCandidates = testCase.makeReuseCandidate( ...
                "unchanged_separation","other_same_time", ...
                "separate_time",true,false);

            [classified,evidence] = ...
                v2xsim.analysis.classifyRecordedFailureModes( ...
                    fates,attempts,counterfactuals, ...
                    reuseCandidates);

            testCase.verifyTrue( ...
                evidence.IsHarmfulReuseCandidate);
            testCase.verifyEqual( ...
                classified.FailureMode,"hidden_terminal");
            testCase.verifyTrue(classified.IsHiddenTerminal);
        end

        function cochannelToAdjacentIsNotResolvedHiddenTerminal( ...
                testCase)
            [fates,attempts,counterfactuals] = ...
                testCase.makeRecordedError("cochannel");
            reuseCandidates = testCase.makeReuseCandidate( ...
                "harmful_reuse","cochannel", ...
                "adjacent_channel",false,false);

            [classified,evidence] = ...
                v2xsim.analysis.classifyRecordedFailureModes( ...
                    fates,attempts,counterfactuals, ...
                    reuseCandidates);

            testCase.verifyFalse( ...
                evidence.IsHarmfulReuseCandidate);
            testCase.verifyEqual( ...
                classified.FailureMode, ...
                "cochannel_interference");
            testCase.verifyFalse(classified.IsHiddenTerminal);
        end

        function allocatorAndPhyRelationsMustMatchForHiddenLabel( ...
                testCase)
            [fates,attempts,counterfactuals] = ...
                testCase.makeRecordedError("adjacent_channel");
            reuseCandidates = testCase.makeReuseCandidate( ...
                "harmful_reuse","cochannel", ...
                "separate_time",true,false);

            [classified,evidence] = ...
                v2xsim.analysis.classifyRecordedFailureModes( ...
                    fates,attempts,counterfactuals, ...
                    reuseCandidates);

            testCase.verifyFalse( ...
                evidence.IsHarmfulReuseCandidate);
            testCase.verifyEqual( ...
                classified.FailureMode, ...
                "adjacent_channel_interference");
            testCase.verifyFalse(classified.IsHiddenTerminal);
        end

        function rejectsCandidateSchemaWithoutRelationEvidence( ...
                testCase)
            [fates,attempts,counterfactuals] = ...
                testCase.makeRecordedError("cochannel");
            legacyCandidates = table( ...
                9,"ue4","ue5","harmful_reuse", ...
                VariableNames=[ ...
                    "AllocationEpoch","FirstUeId", ...
                    "SecondUeId","CandidateType"]);

            testCase.verifyError( ...
                @() v2xsim.analysis. ...
                    classifyRecordedFailureModes( ...
                        fates,attempts,counterfactuals, ...
                        legacyCandidates), ...
                "v2xsim:analysis:" + ...
                "InvalidReuseCandidateEvidence");
        end

        function acceptsCsvBinaryOverlapFlags(testCase)
            [fates,attempts,counterfactuals] = ...
                testCase.makeRecordedError("adjacent_channel");
            reuseCandidates = testCase.makeReuseCandidate( ...
                "unchanged_separation","adjacent_channel", ...
                "separate_time",true,false);
            reuseCandidates.IsHarmfulInterferenceOverlap = ...
                double( ...
                    reuseCandidates. ...
                        IsHarmfulInterferenceOverlap);
            reuseCandidates.IsMissedInterferenceOverlap = ...
                double( ...
                    reuseCandidates. ...
                        IsMissedInterferenceOverlap);

            classified = ...
                v2xsim.analysis.classifyRecordedFailureModes( ...
                    fates,attempts,counterfactuals, ...
                    reuseCandidates);

            testCase.verifyTrue(classified.IsHiddenTerminal);
        end

        function rejectsUnqualifiedNonGlobalSliceEvidence(testCase)
            [fates,attempts,counterfactuals] = ...
                testCase.makeRecordedError("cochannel");
            reuseCandidates = testCase.makeReuseCandidate( ...
                "harmful_reuse","cochannel", ...
                "separate_time",true,false);
            reuseCandidates.NetworkSliceId = "slice-a";

            testCase.verifyError( ...
                @() v2xsim.analysis. ...
                    classifyRecordedFailureModes( ...
                        fates,attempts,counterfactuals, ...
                        reuseCandidates), ...
                "v2xsim:analysis:" + ...
                "UnsupportedReuseCandidateNetworkSlice");
        end

        function exhaustiveAttemptWithoutContributorIsNoiseFailure( ...
                testCase)
            fates = ...
                v2xsim.analysis.emptyTerminalPacketFateTable();
            fates(1,:) = { ...
                0.2,"LTE",5,"ue5",2,"ue2",1,0.1,1, ...
                "error",1,1,30,7,nan,2,9};
            attempts = ...
                v2xsim.analysis.emptyInterferenceAttemptTrace();
            attempts(1,:) = { ...
                0.2,"LTE",5,"ue5",2,"ue2",1,true, ...
                0.1,1,7,2,9,"error",-5,0,-5,0,true};

            classified = ...
                v2xsim.analysis.classifyRecordedFailureModes( ...
                    fates,attempts, ...
                    v2xsim.analysis. ...
                        emptyInterferenceCounterfactualTrace(), ...
                    table());

            testCase.verifyEqual( ...
                classified.FailureMode, ...
                "noise_or_propagation");
            testCase.verifyFalse(classified.IsHiddenTerminal);
        end

        function classifiesModeratelyLargeEvidenceSet(testCase)
            fateCount = 2000;
            fates = table( ...
                (1:fateCount).' / 1000, ...
                repmat("LTE",fateCount,1), ...
                ones(fateCount,1),repmat("tx",fateCount,1), ...
                2 * ones(fateCount,1), ...
                repmat("rx",fateCount,1), ...
                (1:fateCount).',(1:fateCount).' / 1000, ...
                ones(fateCount,1),repmat("error",fateCount,1), ...
                ones(fateCount,1),ones(fateCount,1), ...
                10 * ones(fateCount,1), ...
                ones(fateCount,1),nan(fateCount,1), ...
                ones(fateCount,1),ones(fateCount,1), ...
                VariableNames=string( ...
                    v2xsim.analysis. ...
                    emptyTerminalPacketFateTable(). ...
                    Properties.VariableNames));
            evidenceCount = 2 * fateCount;
            packetSequence = repelem((1:fateCount).',2);
            evidence = table( ...
                repmat("LTE",evidenceCount,1), ...
                repmat("tx",evidenceCount,1), ...
                repmat("rx",evidenceCount,1), ...
                packetSequence,ones(evidenceCount,1), ...
                repmat(["i1";"i2"],fateCount,1), ...
                repmat("cochannel",evidenceCount,1), ...
                -5 * ones(evidenceCount,1), ...
                zeros(evidenceCount,1), ...
                -1 * ones(evidenceCount,1), ...
                false(evidenceCount,1), ...
                ones(evidenceCount,1), ...
                VariableNames=[ ...
                    "Technology","TransmitterUeId","ReceiverUeId", ...
                    "PacketSequence","AttemptNumber", ...
                    "InterfererUeId","ResourceRelation", ...
                    "ObservedSinrDb","DecodeThresholdDb", ...
                    "SinrWithoutInterfererDb", ...
                    "IsHarmfulReuseCandidate", ...
                    "SinrWithoutAllInterferersDb"]);

            classified = v2xsim.analysis.classifyFailureModes( ...
                fates,evidence,EvidenceIsExhaustive=true);

            testCase.verifyEqual(height(classified),fateCount);
            testCase.verifyTrue(all( ...
                classified.FailureMode == "joint_interference"));
        end
    end

    methods (Access = private)
        function [fates,attempts,counterfactuals] = ...
                makeRecordedError(~,resourceRelation)
            fates = ...
                v2xsim.analysis.emptyTerminalPacketFateTable();
            fates(1,:) = { ...
                0.2,"LTE",5,"ue5",2,"ue2",42,0.1,1, ...
                "error",1,1,30,7,nan,2,9};

            attempts = ...
                v2xsim.analysis.emptyInterferenceAttemptTrace();
            attempts(1,:) = { ...
                0.2,"LTE",5,"ue5",2,"ue2",99,false, ...
                0.1,1,7,2,9,"error",-5,0,3,1,true};
            counterfactuals = ...
                v2xsim.analysis. ...
                emptyInterferenceCounterfactualTrace();
            counterfactuals(1,:) = { ...
                0.2,"LTE",5,"ue5",2,"ue2",99,false, ...
                0.1,1,7,2,9,4,"ue4","ue4","ue5", ...
                7,2,resourceRelation,3,-5,0,2,3,true};
        end

        function candidate = makeReuseCandidate( ...
                ~,candidateType,liveRelation,oracleRelation, ...
                isHarmful,isMissed)
            candidate = table( ...
                9,"global","ue4","ue5",candidateType, ...
                liveRelation,oracleRelation,isHarmful,isMissed, ...
                VariableNames=[ ...
                    "AllocationEpoch","NetworkSliceId", ...
                    "FirstUeId","SecondUeId","CandidateType", ...
                    "LiveResourceRelation", ...
                    "OracleResourceRelation", ...
                    "IsHarmfulInterferenceOverlap", ...
                    "IsMissedInterferenceOverlap"]);
        end
    end
end
