classdef PacketFateAnalysisTest < matlab.unittest.TestCase
    methods (Test)
        function reconcilesHarqToOneTerminalDirectedFate(testCase)
            observations = testCase.makeFates( ...
                [0.1;0.15;0.2;0.2;0.2], ...
                ["beta";"beta";"beta";"beta";"gamma"], ...
                [1;1;1;1;1],[1;0;2;2;2], ...
                ["none";"blocked";"correct";"correct";"error"], ...
                [5;5;5;5;15]);

            terminal = ...
                v2xsim.analysis.aggregateTerminalPacketFates( ...
                    observations);

            testCase.verifyEqual(height(terminal),2);
            testCase.verifyEqual( ...
                terminal.ReceiverUeId,["beta";"gamma"]);
            testCase.verifyEqual( ...
                terminal.Outcome,["correct";"error"]);
        end

        function rejectsConflictingTerminalOutcomes(testCase)
            observations = testCase.makeFates( ...
                [0.1;0.2],["beta";"beta"], ...
                [1;1],[1;2],["correct";"error"],[5;5]);

            testCase.verifyError( ...
                @() v2xsim.analysis. ...
                    aggregateTerminalPacketFates(observations), ...
                "v2xsim:analysis:" + ...
                "ConflictingTerminalPacketFates");
        end

        function computesExplicitDeliveryRadioAndBlockingMetrics( ...
                testCase)
            fates = testCase.makeFates( ...
                [0.1;0.1;0.1;0.1], ...
                ["beta";"gamma";"delta";"epsilon"], ...
                ones(4,1),ones(4,1), ...
                ["correct";"blocked";"error";"blocked"], ...
                [5;5;15;25]);

            curve = v2xsim.analysis.packetReceptionCurve( ...
                fates,[10;20;30]);

            testCase.verifyEqual( ...
                curve.CorrectCount,[1;0;0]);
            testCase.verifyEqual( ...
                curve.ErrorCount,[0;1;0]);
            testCase.verifyEqual( ...
                curve.BlockedCount,[1;0;1]);
            testCase.verifyEqual( ...
                curve.DeliveryPrr,[0.5;0;0]);
            testCase.verifyEqual( ...
                curve.RadioPrr,[1;0;nan]);
            testCase.verifyEqual( ...
                curve.BlockingRate,[0.5;0;1]);
            score = v2xsim.analysis.normalizedPrrAuc( ...
                curve,30);
            testCase.verifyEqual(score,1/3,AbsTol=1e-12);
        end

        function poolsCountsBeforeRatios(testCase)
            first = table( ...
                "LTE",1,1,10,1,0,1, ...
                VariableNames=[ ...
                    "Technology","Channel","PacketType", ...
                    "DistanceUpperBoundMeters", ...
                    "CorrectCount","ErrorCount","BlockedCount"]);
            second = table( ...
                "LTE",1,1,10,0,1,0, ...
                VariableNames=first.Properties.VariableNames);

            pooled = ...
                v2xsim.analysis.poolPacketReceptionCounts( ...
                    [first;second]);

            testCase.verifyEqual(pooled.TotalCount,3);
            testCase.verifyEqual(pooled.DeliveryPrr,1/3);
            testCase.verifyEqual(pooled.RadioPrr,0.5);
            testCase.verifyEqual(pooled.BlockingRate,1/3);
        end

        function identifiesLabelInvariantReuseCandidates(testCase)
            live = table( ...
                ["A";"B";"C"],[1;1;2], ...
                VariableNames=["UeId","ResourceIds"]);
            oracle = table( ...
                ["C";"A";"B"],[9;9;8], ...
                VariableNames=["UeId","ResourceIds"]);

            candidates = ...
                v2xsim.analysis.classifyReuseCandidates( ...
                    live,oracle);

            testCase.verifyEqual( ...
                candidates.CandidateType, ...
                ["harmful_reuse";"missed_reuse"; ...
                "unchanged_separation"]);
            testCase.verifyEqual( ...
                candidates(:,["FirstUeId","SecondUeId"]), ...
                table( ...
                    ["A";"A";"B"],["B";"C";"C"], ...
                    VariableNames=[ ...
                        "FirstUeId","SecondUeId"]));
        end

        function requiresCompleteSafePredictionsForExposedReuse( ...
                testCase)
            live = table( ...
                ["A";"B";"C"],[1;1;2], ...
                VariableNames=["UeId","ResourceIds"]);
            oracle = table( ...
                ["A";"B";"C"],[9;8;9], ...
                VariableNames=["UeId","ResourceIds"]);
            candidates = ...
                v2xsim.analysis.classifyReuseCandidates( ...
                    live,oracle);
            predictions = table( ...
                ["A";"A"],["C";"C"],["R1";"R2"], ...
                [true;true],[true;true],[0.95;0.91], ...
                VariableNames=[ ...
                    "FirstUeId","SecondUeId","ReceiverUeId", ...
                    "IsSameTechnology","IsWithinAnalysisRange", ...
                    "PredictedPrr"]);

            incomplete = v2xsim.analysis. ...
                classifyExposedReuseOpportunities( ...
                    candidates,predictions);
            complete = v2xsim.analysis. ...
                classifyExposedReuseOpportunities( ...
                    candidates,predictions, ...
                    PredictionsAreComplete=true);

            missedRow = ...
                complete.CandidateType == "missed_reuse";
            testCase.verifyFalse( ...
                incomplete.IsExposedOpportunity(missedRow));
            testCase.verifyTrue( ...
                complete.IsExposedOpportunity(missedRow));
            testCase.verifyEqual( ...
                complete.MinimumPredictedPrr(missedRow),0.91);
        end

        function classifiesHiddenMultipleJointAndNoiseFailures( ...
                testCase)
            fates = testCase.makeFates( ...
                (0.1:0.1:0.5).', ...
                repmat("receiver",5,1), ...
                (1:5).',ones(5,1), ...
                ["error";"error";"error";"error";"correct"], ...
                repmat(10,5,1));
            evidence = testCase.makeCounterfactualEvidence();

            classified = v2xsim.analysis.classifyFailureModes( ...
                fates,evidence,EvidenceIsExhaustive=true);

            testCase.verifyEqual( ...
                classified.FailureMode, ...
                ["hidden_terminal"; ...
                "multiple_sufficient_interferers"; ...
                "joint_interference"; ...
                "noise_or_propagation"; ...
                "delivered"]);
            testCase.verifyEqual( ...
                classified.IsHiddenTerminal, ...
                [true;true;false;false;false]);
            testCase.verifyEqual( ...
                classified.CausalInterfererCount,[1;2;0;0;0]);
            testCase.verifyEqual( ...
                classified.IsAmbiguous, ...
                [false;true;true;false;false]);
        end

        function summarizesPerVehicleEndpointPerspectives(testCase)
            fates = testCase.makeFates( ...
                [0.1;0.2;0.3], ...
                ["beta";"beta";"beta"], ...
                [1;2;3],[1;1;1], ...
                ["correct";"error";"blocked"], ...
                [5;15;25]);

            metrics = v2xsim.analysis. ...
                perVehiclePacketReceptionMetrics( ...
                    fates,[10;20;30]);

            alphaTx = ...
                metrics.VehicleUeId == "alpha" & ...
                metrics.Perspective == "transmitter";
            betaRx = ...
                metrics.VehicleUeId == "beta" & ...
                metrics.Perspective == "receiver";
            testCase.verifyTrue(any(alphaTx));
            testCase.verifyTrue(any(betaRx));
            testCase.verifyEqual( ...
                metrics{alphaTx, ...
                ["CorrectCount","ErrorCount","BlockedCount"]}, ...
                [1,1,1]);
            testCase.verifyEqual( ...
                metrics.DeliveryPrr(alphaTx),1/3);
            testCase.verifyEqual( ...
                metrics.DeliveryPrrAucStatus(alphaTx),"Complete");
            testCase.verifyEqual( ...
                metrics.DeliveryPrrAuc(alphaTx),0.5, ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                metrics.RadioPrrAucStatus(alphaTx), ...
                "IncompleteDistanceGrid");
            testCase.verifyEqual( ...
                metrics.TotalCount(betaRx),3);
        end

        function groupedPerVehicleMetricsMatchScalarReference(testCase)
            fates = testCase.makeLargeFates(480,12);
            boundaryDistances = [ ...
                0;9.999;10;19.999;20;29.999;30;45];
            fates.TrueDistanceMeters = repmat( ...
                boundaryDistances,60,1);
            outsideOnly = testCase.makeLargeFates(1,2);
            outsideOnly.Technology = "NR";
            outsideOnly.TrueDistanceMeters = 45;
            fates = [fates;outsideOnly];
            distanceGridMeters = [10;20;30];

            actual = v2xsim.analysis. ...
                perVehiclePacketReceptionMetrics( ...
                    fates,distanceGridMeters);
            expected = testCase.referencePerVehicleMetrics( ...
                fates,distanceGridMeters);

            testCase.verifyEqual(actual,expected,AbsTol=1e-12);
            nrRows = actual.Technology == "NR";
            testCase.verifyTrue(any( ...
                actual.DeliveryPrrAucStatus(nrRows) == ...
                "NoTerminalFates"));
            testCase.verifyTrue(any( ...
                actual.DeliveryPrrAucStatus(nrRows) == ...
                "NoFatesWithinDistanceGrid"));
        end

        function handlesModeratelyLargePerVehicleTrace(testCase)
            fateCount = 120000;
            vehicleCount = 300;
            fates = testCase.makeLargeFates( ...
                fateCount,vehicleCount);
            distanceGridMeters = (10:10:200).';

            metrics = v2xsim.analysis. ...
                perVehiclePacketReceptionMetrics( ...
                    fates,distanceGridMeters);

            testCase.verifyEqual( ...
                height(metrics),4 .* vehicleCount);
            testCase.verifyEqual( ...
                sum(metrics.TotalCount),2 .* fateCount);
            testCase.verifyEqual( ...
                sum(metrics.CorrectCount + ...
                metrics.ErrorCount + metrics.BlockedCount), ...
                2 .* fateCount);
            testCase.verifyEqual( ...
                string(metrics.Properties.VariableNames), ...
                [ ...
                "Technology","VehicleUeId","Perspective", ...
                "MaximumDistanceMeters","DistanceBinCount", ...
                "NonemptyDeliveryBinCount", ...
                "NonemptyRadioBinCount","CorrectCount", ...
                "ErrorCount","BlockedCount","TotalCount", ...
                "RadioAttemptCount","DeliveryPrr","RadioPrr", ...
                "BlockingRate","DeliveryPrrAuc","RadioPrrAuc", ...
                "DeliveryPrrAucStatus","RadioPrrAucStatus"]);
        end
    end

    methods (Access = private)
        function fates = makeFates( ...
                ~,times,receiverUeIds,packetSequences, ...
                attempts,outcomes,distances)
            rowCount = numel(times);
            fates = table( ...
                times,repmat("LTE",rowCount,1), ...
                ones(rowCount,1),repmat("alpha",rowCount,1), ...
                (2:rowCount + 1).',receiverUeIds, ...
                packetSequences,zeros(rowCount,1),attempts,outcomes, ...
                ones(rowCount,1),ones(rowCount,1),distances, ...
                nan(rowCount,1),nan(rowCount,1), ...
                nan(rowCount,1),ones(rowCount,1), ...
                VariableNames=string( ...
                    v2xsim.analysis. ...
                    emptyTerminalPacketFateTable(). ...
                    Properties.VariableNames));
        end

        function evidence = makeCounterfactualEvidence(~)
            technology = repmat("LTE",5,1);
            transmitterUeId = repmat("alpha",5,1);
            receiverUeId = repmat("receiver",5,1);
            packetSequence = [1;2;2;3;3];
            attemptNumber = ones(5,1);
            interfererUeId = ["B";"B";"C";"B";"C"];
            resourceRelation = [ ...
                "cochannel";"cochannel";"adjacent_channel"; ...
                "cochannel";"adjacent_channel"];
            observedSinrDb = -5 .* ones(5,1);
            decodeThresholdDb = zeros(5,1);
            sinrWithoutInterfererDb = [2;2;1;-1;-2];
            isHarmfulReuseCandidate = ...
                [true;true;false;false;false];
            sinrWithoutAllInterferersDb = [-1;2;2;1;1];
            evidence = table( ...
                technology,transmitterUeId,receiverUeId, ...
                packetSequence,attemptNumber,interfererUeId, ...
                resourceRelation,observedSinrDb,decodeThresholdDb, ...
                sinrWithoutInterfererDb,isHarmfulReuseCandidate, ...
                sinrWithoutAllInterferersDb, ...
                VariableNames=[ ...
                    "Technology","TransmitterUeId","ReceiverUeId", ...
                    "PacketSequence","AttemptNumber","InterfererUeId", ...
                    "ResourceRelation","ObservedSinrDb", ...
                    "DecodeThresholdDb","SinrWithoutInterfererDb", ...
                    "IsHarmfulReuseCandidate", ...
                    "SinrWithoutAllInterferersDb"]);
        end

        function fates = makeLargeFates( ...
                ~,rowCount,vehicleCount)
            rowIndices = (1:rowCount).';
            technologyCycle = ["LTE";"11p"];
            technology = technologyCycle( ...
                mod(rowIndices - 1,numel(technologyCycle)) + 1);
            transmitterIndices = ...
                mod(rowIndices - 1,vehicleCount) + 1;
            receiverIndices = ...
                mod(transmitterIndices,vehicleCount) + 1;
            outcomeCycle = ["correct";"error";"blocked"];
            outcome = outcomeCycle( ...
                mod(rowIndices - 1,numel(outcomeCycle)) + 1);
            distances = ...
                5 + 10 .* mod(rowIndices - 1,20);
            fates = table( ...
                rowIndices ./ 1000,technology, ...
                transmitterIndices, ...
                compose("ue-%04d",transmitterIndices), ...
                receiverIndices, ...
                compose("ue-%04d",receiverIndices), ...
                rowIndices,zeros(rowCount,1), ...
                ones(rowCount,1),outcome, ...
                ones(rowCount,1),ones(rowCount,1),distances, ...
                nan(rowCount,1),nan(rowCount,1), ...
                nan(rowCount,1),ones(rowCount,1), ...
                VariableNames=string( ...
                    v2xsim.analysis. ...
                    emptyTerminalPacketFateTable(). ...
                    Properties.VariableNames));
        end

        function metrics = referencePerVehicleMetrics( ...
                testCase,fates,distanceGridMeters)
            fates = v2xsim.analysis. ...
                aggregateTerminalPacketFates(fates);
            technologies = unique(fates.Technology,"stable");
            technologyColumn = strings(0,1);
            vehicleUeId = strings(0,1);
            perspective = strings(0,1);
            summaries = repmat( ...
                testCase.emptyReferenceSummary(),0,1);
            for technology = technologies.'
                technologyFates = fates( ...
                    fates.Technology == technology,:);
                vehicleIds = unique( ...
                    [technologyFates.TransmitterUeId; ...
                    technologyFates.ReceiverUeId],"stable");
                for vehicleId = vehicleIds.'
                    for endpoint = ["transmitter","receiver"]
                        if endpoint == "transmitter"
                            selected = ...
                                technologyFates.TransmitterUeId == ...
                                vehicleId;
                        else
                            selected = ...
                                technologyFates.ReceiverUeId == ...
                                vehicleId;
                        end
                        technologyColumn(end + 1,1) = technology; %#ok<AGROW>
                        vehicleUeId(end + 1,1) = vehicleId; %#ok<AGROW>
                        perspective(end + 1,1) = endpoint; %#ok<AGROW>
                        summaries(end + 1,1) = ...
                            testCase.referenceCurveSummary( ...
                            technologyFates(selected,:), ...
                            distanceGridMeters); %#ok<AGROW>
                    end
                end
            end
            metrics = testCase.referenceSummaryTable( ...
                technologyColumn,vehicleUeId,perspective, ...
                summaries,distanceGridMeters);
            metrics = sortrows( ...
                metrics, ...
                ["Technology","VehicleUeId","Perspective"]);
        end

        function summary = referenceCurveSummary( ...
                testCase,fates,distanceGridMeters)
            summary = testCase.emptyReferenceSummary();
            if isempty(fates)
                return
            end
            curve = v2xsim.analysis.packetReceptionCurve( ...
                fates,distanceGridMeters, ...
                GroupVariables=strings(1,0));
            summary.CorrectCount = sum(curve.CorrectCount);
            summary.ErrorCount = sum(curve.ErrorCount);
            summary.BlockedCount = sum(curve.BlockedCount);
            summary.TotalCount = sum(curve.TotalCount);
            summary.RadioAttemptCount = ...
                sum(curve.RadioAttemptCount);
            summary.NonemptyDeliveryBinCount = ...
                nnz(curve.TotalCount > 0);
            summary.NonemptyRadioBinCount = ...
                nnz(curve.RadioAttemptCount > 0);
            if summary.TotalCount == 0
                summary.DeliveryPrrAucStatus = ...
                    "NoFatesWithinDistanceGrid";
                summary.RadioPrrAucStatus = ...
                    "NoFatesWithinDistanceGrid";
                return
            end
            summary.DeliveryPrr = ...
                summary.CorrectCount ./ summary.TotalCount;
            summary.BlockingRate = ...
                summary.BlockedCount ./ summary.TotalCount;
            [summary.DeliveryPrrAuc, ...
                summary.DeliveryPrrAucStatus] = ...
                testCase.referenceAuc( ...
                curve,distanceGridMeters(end),"DeliveryPrr");
            if summary.RadioAttemptCount > 0
                summary.RadioPrr = ...
                    summary.CorrectCount ./ ...
                    summary.RadioAttemptCount;
                [summary.RadioPrrAuc, ...
                    summary.RadioPrrAucStatus] = ...
                    testCase.referenceAuc( ...
                    curve,distanceGridMeters(end),"RadioPrr");
            else
                summary.RadioPrrAucStatus = "NoRadioAttempts";
            end
        end

        function summary = emptyReferenceSummary(~)
            summary = struct( ...
                CorrectCount=0,ErrorCount=0,BlockedCount=0, ...
                TotalCount=0,RadioAttemptCount=0, ...
                DeliveryPrr=NaN,RadioPrr=NaN, ...
                BlockingRate=NaN,DeliveryPrrAuc=NaN, ...
                RadioPrrAuc=NaN, ...
                DeliveryPrrAucStatus="NoTerminalFates", ...
                RadioPrrAucStatus="NoTerminalFates", ...
                NonemptyDeliveryBinCount=0, ...
                NonemptyRadioBinCount=0);
        end

        function [score,status] = referenceAuc( ...
                ~,curve,maximumDistanceMeters,metric)
            try
                score = v2xsim.analysis.normalizedPrrAuc( ...
                    curve,maximumDistanceMeters,Metric=metric);
                status = "Complete";
            catch cause
                if string(cause.identifier) ~= ...
                        "v2xsim:analysis:IncompletePrrCurve"
                    rethrow(cause)
                end
                score = NaN;
                status = "IncompleteDistanceGrid";
            end
        end

        function metrics = referenceSummaryTable( ...
                ~,technology,vehicleUeId,perspective, ...
                summaries,distanceGridMeters)
            rowCount = numel(summaries);
            metrics = table( ...
                technology,vehicleUeId,perspective, ...
                repmat(distanceGridMeters(end),rowCount,1), ...
                repmat(numel(distanceGridMeters),rowCount,1), ...
                [summaries.NonemptyDeliveryBinCount].', ...
                [summaries.NonemptyRadioBinCount].', ...
                [summaries.CorrectCount].', ...
                [summaries.ErrorCount].', ...
                [summaries.BlockedCount].', ...
                [summaries.TotalCount].', ...
                [summaries.RadioAttemptCount].', ...
                [summaries.DeliveryPrr].', ...
                [summaries.RadioPrr].', ...
                [summaries.BlockingRate].', ...
                [summaries.DeliveryPrrAuc].', ...
                [summaries.RadioPrrAuc].', ...
                [summaries.DeliveryPrrAucStatus].', ...
                [summaries.RadioPrrAucStatus].', ...
                VariableNames=[ ...
                    "Technology","VehicleUeId","Perspective", ...
                    "MaximumDistanceMeters","DistanceBinCount", ...
                    "NonemptyDeliveryBinCount", ...
                    "NonemptyRadioBinCount","CorrectCount", ...
                    "ErrorCount","BlockedCount","TotalCount", ...
                    "RadioAttemptCount","DeliveryPrr","RadioPrr", ...
                    "BlockingRate","DeliveryPrrAuc","RadioPrrAuc", ...
                    "DeliveryPrrAucStatus", ...
                    "RadioPrrAucStatus"]);
        end
    end
end
