classdef CoexistenceModeBehaviorTest < matlab.unittest.TestCase
    %COEXISTENCEMODEBEHAVIORTEST Outcome-level coexistence regression.

    properties (Constant, Access = private)
        MinimumPrrGain = 0.015
        RandomSeeds = 10:12
        SimulationTimeSeconds = 3
    end

    properties (SetAccess = private)
        SimulatorRoot (1, 1) string
        OutputDirectory (1, 1) string
    end

    methods (TestClassSetup)
        function configureCampaign(testCase)
            testCase.SimulatorRoot = repositoryRoot();
            temporaryFolder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            testCase.OutputDirectory = fullfile( ...
                string(temporaryFolder.Folder), ...
                "coexistence-mode-comparison");
        end
    end

    methods (Test, TestTags = {'CoexistenceSemantics'})
        function testOrthogonalChannelsOutperformSharedChannel( ...
                testCase)
            originalPath = path;
            originalStream = RandStream.getGlobalStream();
            originalStreamState = originalStream.State;
            originalWarningState = warning;
            processCleanup = onCleanup(@() restoreProcessState( ...
                originalPath, originalStream, ...
                originalStreamState, originalWarningState));

            [seedResults, comparisons] = ...
                v2xsimregression.coexistence.runModeComparison( ...
                    testCase.SimulatorRoot, ...
                    testCase.OutputDirectory, ...
                    RandomSeeds=testCase.RandomSeeds, ...
                    SimulationTimeSeconds= ...
                        testCase.SimulationTimeSeconds);

            testCase.verifyEqual( ...
                sort(unique(seedResults.Mode)).', ...
                ["COEX-NO-INTERF", "COEX-STD-INTERF"]);
            testCase.verifyEqual( ...
                sort(unique(seedResults.RandomSeed)).', ...
                testCase.RandomSeeds);
            testCase.verifyEqual( ...
                comparisons.Technology.', ...
                ["IEEE 802.11p", "LTE-V2X"]);
            testCase.verifyEqual( ...
                comparisons.SeedCount, ...
                repmat(numel(testCase.RandomSeeds), 2, 1));
            testCase.verifyGreaterThan( ...
                comparisons.OrthogonalMinusSharedPrr, ...
                testCase.MinimumPrrGain, ...
                "Disabling cross-technology interference must improve " + ...
                "pooled PRR through 500 m for both technologies.");
            testCase.verifyGreaterThan( ...
                comparisons.OrthogonalTotalCount, 0);
            testCase.verifyGreaterThan( ...
                comparisons.SharedTotalCount, 0);
            testCase.verifyTrue(isfile(fullfile( ...
                testCase.OutputDirectory, "seed-summary.csv")));
            testCase.verifyTrue(isfile(fullfile( ...
                testCase.OutputDirectory, ...
                "mode-comparison.csv")));

            testCase.verifyEqual(path, originalPath);
            testCase.verifyTrue( ...
                isequal(RandStream.getGlobalStream(), originalStream));
            testCase.verifyEqual( ...
                originalStream.State, originalStreamState);
            testCase.verifyEqual(warning, originalWarningState);

            processCleanup; %#ok<VUNUS>
        end
    end
end

function root = repositoryRoot()
root = string(fileparts(fileparts(fileparts(fileparts( ...
    mfilename("fullpath"))))));
end

function restoreProcessState( ...
        originalPath, originalStream, originalStreamState, ...
        originalWarningState)
path(originalPath);
RandStream.setGlobalStream(originalStream);
originalStream.State = originalStreamState;
warning(originalWarningState);
end
