function [seedResults, comparisons] = runModeComparison( ...
        simulatorRoot, outputDirectory, options)
%RUNMODECOMPARISON Compare orthogonal and shared-channel coexistence.
%   Raw PRR fate counts are pooled across paired deterministic seeds before
%   the two radio-access modes are compared.

arguments (Input)
    simulatorRoot (1, 1) string {mustBeNonzeroLengthText}
    outputDirectory (1, 1) string {mustBeNonzeroLengthText}
    options.RandomSeeds (1, :) double { ...
        mustBeInteger, mustBeNonnegative} = 10:12
    options.SimulationTimeSeconds (1, 1) double { ...
        mustBeReal, mustBeFinite, mustBePositive} = 3
    options.ExecutionMode (1, 1) string {mustBeMember( ...
        options.ExecutionMode, ["auto", "serial", "parallel"])} = "auto"
    options.MaxWorkers (1, 1) double { ...
        v2xsimregression.execution.mustBeWorkerLimit} = Inf
end

arguments (Output)
    seedResults table
    comparisons table
end

validateOptions(options);
callerWorkingDirectory = string(pwd);
simulatorRoot = absolutePath( ...
    simulatorRoot, callerWorkingDirectory);
outputDirectory = absolutePath( ...
    outputDirectory, callerWorkingDirectory);
simulatorDirectory = fullfile(simulatorRoot, "old_src");
configurationFile = fullfile( ...
    fileparts(mfilename("fullpath")), "config", ...
    "lteCoexistence.cfg");
validateSimulator( ...
    simulatorRoot, configurationFile);
createExclusiveOutputDirectory(outputDirectory);

originalPath = path;
originalStream = RandStream.getGlobalStream();
originalStreamState = originalStream.State;
originalWarningState = warning;
environmentCleanup = onCleanup(@() restoreEnvironment( ...
    originalPath, originalStream, originalStreamState, ...
    originalWarningState));

addpath(fullfile(simulatorRoot, "src"));
addpath(simulatorDirectory);

manifest = createManifest( ...
    configurationFile, outputDirectory, options.RandomSeeds, ...
    options.SimulationTimeSeconds);
workItems = arrayfun(@(workItem) {workItem}, manifest);
labels = string({manifest.Label});
additionalPaths = [ ...
    fullfile(simulatorRoot, "regression-tests"), ...
    fullfile(simulatorRoot, "src"), ...
    simulatorDirectory];
resultCells = v2xsimregression.execution.runWorkItems( ...
    workItems, @runWorkItem, ...
    Labels=labels, ...
    ExecutionMode=options.ExecutionMode, ...
    MaxWorkers=options.MaxWorkers, ...
    AdditionalPaths=additionalPaths, ...
    CollectAllFailures=true);

seedResults = vertcat(resultCells{:});
comparisons = poolModeCounts( ...
    seedResults, options.RandomSeeds);
writetable( ...
    seedResults, fullfile(outputDirectory, "seed-summary.csv"));
writetable( ...
    comparisons, ...
    fullfile(outputDirectory, "mode-comparison.csv"));

environmentCleanup; %#ok<VUNUS>
end

function validateOptions(options)
if isempty(options.RandomSeeds)
    error( ...
        "v2xsimregression:coexistence:EmptySeedManifest", ...
        "RandomSeeds must be nonempty.");
end
if numel(unique(options.RandomSeeds)) ~= ...
        numel(options.RandomSeeds)
    error( ...
        "v2xsimregression:coexistence:DuplicateRandomSeed", ...
        "RandomSeeds must not contain duplicates.");
end
end

function manifest = createManifest( ...
        configurationFile, outputDirectory, randomSeeds, ...
        simulationTimeSeconds)
modes = ["COEX-NO-INTERF", "COEX-STD-INTERF"];
manifest = repmat(struct( ...
    "ConfigurationFile", configurationFile, ...
    "OutputDirectory", "", ...
    "Mode", "", ...
    "RandomSeed", 0, ...
    "SimulationTimeSeconds", simulationTimeSeconds, ...
    "Label", ""), ...
    1, numel(modes) .* numel(randomSeeds));

workIndex = 0;
for mode = modes
    modeDirectory = lower(replace(mode, "-", "_"));
    for randomSeed = randomSeeds
        workIndex = workIndex + 1;
        label = compose("%s/seed-%d", mode, randomSeed);
        manifest(workIndex).OutputDirectory = fullfile( ...
            outputDirectory, modeDirectory, ...
            compose("seed-%d", randomSeed));
        manifest(workIndex).Mode = mode;
        manifest(workIndex).RandomSeed = randomSeed;
        manifest(workIndex).Label = label;
    end
end
end

function result = runWorkItem(workItem)
simulationArguments = { ...
    workItem.ConfigurationFile, ...
    "simulation.RequiredVersion", "V7", ...
    "simulation.RadioAccessMode", workItem.Mode, ...
    "simulation.RandomSeed", workItem.RandomSeed, ...
    "scenarioOptions.RandomSeed", workItem.RandomSeed, ...
    "resourceAllocation.RandomSeed", workItem.RandomSeed, ...
    "simulation.DurationSeconds", workItem.SimulationTimeSeconds, ...
    "simulation.RunLabel", workItem.Label, ...
    "output.Directory", workItem.OutputDirectory}; %#ok<NASGU>
evalc("v2xsim.runSimulation(simulationArguments{:});");

summaryFile = fullfile( ...
    workItem.OutputDirectory, "simulation_summary.json");
if ~isfile(summaryFile)
    error( ...
        "v2xsimregression:coexistence:MissingSimulationSummary", ...
        "Simulation did not publish a summary for %s.", ...
        workItem.Label);
end
verifySummary(summaryFile, workItem);

technologies = ["IEEE 802.11p", "LTE-V2X"];
resultCells = cell(1, numel(technologies));
for technologyIndex = 1:numel(technologies)
    technology = technologies(technologyIndex);
    prrFile = fullfile( ...
        workItem.OutputDirectory, prrFilename(technology));
    counts = readPrrCounts(prrFile, 500);
    resultCells{technologyIndex} = table( ...
        workItem.Mode, technology, workItem.RandomSeed, ...
        workItem.SimulationTimeSeconds, ...
        counts(1), counts(2), counts(3), sum(counts), ...
        counts(1) ./ sum(counts), ...
        workItem.OutputDirectory, ...
        VariableNames=[ ...
            "Mode", "Technology", "RandomSeed", ...
            "SimulationTimeSeconds", "CorrectCount", ...
            "ErrorCount", "BlockedCount", "TotalCount", ...
            "PooledPrrThrough500Meters", "OutputDirectory"]);
end
result = vertcat(resultCells{:});
end

function verifySummary(summaryFile, workItem)
summary = jsondecode(fileread(summaryFile));
if string(summary.Configuration.RadioAccessMode) ~= workItem.Mode
    error( ...
        "v2xsimregression:coexistence:WrongRadioAccessMode", ...
        "Summary mode does not match work item %s.", ...
        workItem.Label);
end
coexistence = summary.Configuration.Coexistence;
if ~logical(coexistence.Active)
    error( ...
        "v2xsimregression:coexistence:InactiveCoexistence", ...
        "Coexistence must be active for %s.", workItem.Label);
end
if workItem.Mode == "COEX-NO-INTERF"
    expectedInterferenceMode = "Orthogonal";
else
    expectedInterferenceMode = "SharedChannel";
end
if string(coexistence.InterferenceMode) ~= expectedInterferenceMode
    error( ...
        "v2xsimregression:coexistence:WrongInterferenceMode", ...
        "Unexpected interference mode for %s.", workItem.Label);
end
if coexistence.CellularSidelinkVehicleGroupSize ~= 24 || ...
        coexistence.Ieee80211pVehicleGroupSize ~= 24
    error( ...
        "v2xsimregression:coexistence:WrongPopulationPattern", ...
        "Expected a balanced 24/24 technology pattern for %s.", ...
        workItem.Label);
end
end

function counts = readPrrCounts( ...
        prrFile, maximumDistanceMeters)
if ~isfile(prrFile)
    error( ...
        "v2xsimregression:coexistence:MissingPrrOutput", ...
        "Expected packet-reception output was not created: %s", ...
        prrFile);
end
prrData = readmatrix(prrFile);
if size(prrData, 2) ~= 6 || isempty(prrData)
    error( ...
        "v2xsimregression:coexistence:InvalidPrrOutput", ...
        "Packet-reception output must contain six numeric columns: %s", ...
        prrFile);
end
if any(~isfinite(prrData(:, 1:5)), "all") || ...
        any(prrData(:, 1:5) < 0, "all")
    error( ...
        "v2xsimregression:coexistence:InvalidPrrOutput", ...
        "Packet-reception distances and counts must be finite and nonnegative.");
end
if any(prrData(:, 2:5) ~= fix(prrData(:, 2:5)), "all")
    error( ...
        "v2xsimregression:coexistence:InvalidPrrOutput", ...
        "Packet-reception counts must be integers.");
end
if any(prrData(:, 5) ~= sum(prrData(:, 2:4), 2))
    error( ...
        "v2xsimregression:coexistence:InconsistentPrrCounts", ...
        "Every PRR row must satisfy total = correct + error + blocked.");
end

isScored = prrData(:, 1) > 0 & ...
    prrData(:, 1) <= maximumDistanceMeters;
scored = prrData(isScored, :);
expectedDistances = (50:50:maximumDistanceMeters).';
if isempty(scored) || ...
        ~isequal(scored(:, 1), expectedDistances) || ...
        any(scored(:, 5) == 0)
    error( ...
        "v2xsimregression:coexistence:IncompletePrrCurve", ...
        "Every 50 m distance bin through %g m must contain samples.", ...
        maximumDistanceMeters);
end
counts = sum(scored(:, 2:4), 1);
end

function comparisons = poolModeCounts(seedResults, randomSeeds)
modes = ["COEX-NO-INTERF", "COEX-STD-INTERF"];
technologies = ["IEEE 802.11p", "LTE-V2X"];
comparisonCells = cell(1, numel(technologies));
for technologyIndex = 1:numel(technologies)
    technology = technologies(technologyIndex);
    modeCounts = zeros(numel(modes), 4);
    for modeIndex = 1:numel(modes)
        mode = modes(modeIndex);
        selected = seedResults( ...
            seedResults.Mode == mode & ...
            seedResults.Technology == technology, :);
        if height(selected) ~= numel(randomSeeds) || ...
                ~isequal( ...
                    sort(selected.RandomSeed).', ...
                    sort(randomSeeds))
            error( ...
                "v2xsimregression:coexistence:UnpairedSeeds", ...
                "%s/%s does not contain every manifest seed.", ...
                mode, technology);
        end
        modeCounts(modeIndex, :) = sum( ...
            selected{:, [ ...
                "CorrectCount", "ErrorCount", ...
                "BlockedCount", "TotalCount"]}, 1);
    end

    orthogonalPrr = modeCounts(1, 1) ./ modeCounts(1, 4);
    sharedChannelPrr = modeCounts(2, 1) ./ modeCounts(2, 4);
    comparisonCells{technologyIndex} = table( ...
        technology, numel(randomSeeds), ...
        modeCounts(1, 1), modeCounts(1, 2), ...
        modeCounts(1, 3), modeCounts(1, 4), ...
        modeCounts(2, 1), modeCounts(2, 2), ...
        modeCounts(2, 3), modeCounts(2, 4), ...
        orthogonalPrr, sharedChannelPrr, ...
        orthogonalPrr - sharedChannelPrr, ...
        VariableNames=[ ...
            "Technology", "SeedCount", ...
            "OrthogonalCorrectCount", "OrthogonalErrorCount", ...
            "OrthogonalBlockedCount", "OrthogonalTotalCount", ...
            "SharedCorrectCount", "SharedErrorCount", ...
            "SharedBlockedCount", "SharedTotalCount", ...
            "OrthogonalPrr", "SharedChannelPrr", ...
            "OrthogonalMinusSharedPrr"]);
end
comparisons = vertcat(comparisonCells{:});
end

function filename = prrFilename(technology)
if technology == "IEEE 802.11p"
    filename = "packet_reception_ratio_11p.csv";
else
    filename = "packet_reception_ratio_LTE.csv";
end
end

function createExclusiveOutputDirectory(outputDirectory)
if isfile(outputDirectory) || isfolder(outputDirectory)
    error( ...
        "v2xsimregression:coexistence:OutputAlreadyExists", ...
        "The coexistence regression output path already exists: %s", ...
        outputDirectory);
end
[created, message] = mkdir(outputDirectory);
if ~created
    error( ...
        "v2xsimregression:coexistence:OutputDirectoryCreationFailed", ...
        "Could not create output directory ""%s"": %s", ...
        outputDirectory, message);
end
end

function validateSimulator(simulatorRoot, configurationFile)
if ~isfolder(simulatorRoot)
    error( ...
        "v2xsimregression:coexistence:MissingSimulatorRoot", ...
        "Simulator root is not a directory: %s", simulatorRoot);
end
if ~isfile(fullfile( ...
        simulatorRoot, "src", "+v2xsim", "runSimulation.m"))
    error( ...
        "v2xsimregression:coexistence:MissingSimulator", ...
        "v2xsim.runSimulation was not found below %s.", ...
        simulatorRoot);
end
if ~isfile(configurationFile)
    error( ...
        "v2xsimregression:coexistence:MissingConfiguration", ...
        "Baseline configuration was not found: %s", ...
        configurationFile);
end
end

function restoreEnvironment( ...
        originalPath, originalStream, originalStreamState, ...
        originalWarningState)
path(originalPath);
RandStream.setGlobalStream(originalStream);
originalStream.State = originalStreamState;
warning(originalWarningState);
end

function pathValue = absolutePath(pathValue, baseDirectory)
if ~isAbsolutePath(pathValue)
    pathValue = fullfile(baseDirectory, pathValue);
end
end

function tf = isAbsolutePath(pathValue)
if ispc
    tf = ~isempty(regexp( ...
        pathValue, "^[A-Za-z]:[\\/]|^\\\\", "once"));
else
    tf = startsWith(pathValue, "/");
end
end
