function [seedResults, comparisons] = runPressureCampaign( ...
        simulatorRoot, outputDirectory, options)
%RUNPRESSURECAMPAIGN Estimate the per-allocator capacity-pressure effect.
%   The campaign holds scenario, traffic, PHY, and allocator parameters
%   fixed.  It changes only the static time and frequency availability of the
%   ResourcePressure policy, pairing each pressure level by random seed.

arguments (Input)
    simulatorRoot (1, 1) string {mustBeNonzeroLengthText}
    outputDirectory (1, 1) string {mustBeNonzeroLengthText}
    options.Allocators (1, :) string {mustBeMember( ...
        options.Allocators, ["ReuseDistance", "MaximumReuseDistance", ...
        "MinimumReusePower", "SensingBased", "Random", "Ordered"])} = ...
        ["ReuseDistance", "MaximumReuseDistance", ...
        "MinimumReusePower", "SensingBased", "Random", "Ordered"]
    options.RandomSeeds (1, :) double {mustBeInteger,mustBePositive} = 10:19
    options.SimulationTimeSeconds (1, 1) double { ...
        mustBeReal,mustBeFinite,mustBePositive} = 2
    options.ExecutionMode (1, 1) string {mustBeMember( ...
        options.ExecutionMode, ["auto", "serial", "parallel"])} = "auto"
    options.MaxWorkers (1, 1) double { ...
        v2xsimregression.execution.mustBeWorkerLimit} = Inf
    options.BootstrapSampleCount (1, 1) double { ...
        mustBeInteger,mustBePositive} = 10000
end

arguments (Output)
    seedResults table
    comparisons table
end

availabilityPercents = [100, 25];
validateOptions(options);

callerWorkingDirectory = string(pwd);
simulatorRoot = absolutePath(simulatorRoot, callerWorkingDirectory);
outputDirectory = absolutePath(outputDirectory, callerWorkingDirectory);
configurationFile = fullfile( ...
    simulatorRoot, "tests", "+v2xsimtest", "+fixtures", ...
    "config", "EtsiHighwayMediumMode1.toml");
validateSimulator(simulatorRoot,configurationFile);

originalPath = path;
originalStream = RandStream.getGlobalStream();
originalStreamState = originalStream.State;
originalWarningState = warning;
environmentCleanup = onCleanup(@() restoreEnvironment( ...
    originalPath,originalStream,originalStreamState,originalWarningState));

addpath(fullfile(simulatorRoot,"src"));
addpath(fullfile(simulatorRoot,"lib","matlab-toml"));
if ~isfolder(outputDirectory)
    [created,message] = mkdir(outputDirectory);
    if ~created
        error( ...
            "v2xsimregression:resourcepressure:OutputDirectoryCreationFailed", ...
            "Could not create output directory ""%s"": %s", ...
            outputDirectory,message);
    end
end

manifest = createManifest( ...
    configurationFile,outputDirectory,options.Allocators,options.RandomSeeds, ...
    availabilityPercents,options.SimulationTimeSeconds);
workItems = arrayfun(@(workItem) {workItem},manifest);
labels = string({manifest.Label});
additionalPaths = [ ...
    fullfile(simulatorRoot,"regression-tests"), ...
    fullfile(simulatorRoot,"src"), ...
    fullfile(simulatorRoot,"lib","matlab-toml")];
resultCells = v2xsimregression.execution.runWorkItems( ...
    workItems,@runWorkItem,Labels=labels, ...
    ExecutionMode=options.ExecutionMode,MaxWorkers=options.MaxWorkers, ...
    AdditionalPaths=additionalPaths,CollectAllFailures=true);
seedResults = vertcat(resultCells{:});
comparisons = comparePressureLevels( ...
    seedResults,options.Allocators,options.RandomSeeds, ...
    availabilityPercents,options.BootstrapSampleCount);

environmentCleanup; %#ok<VUNUS>
end

function validateOptions(options)
if isempty(options.Allocators) || isempty(options.RandomSeeds)
    error( ...
        "v2xsimregression:resourcepressure:EmptyManifest", ...
        "Allocators and RandomSeeds must both be nonempty.");
end
if numel(unique(options.Allocators)) ~= numel(options.Allocators)
    error( ...
        "v2xsimregression:resourcepressure:DuplicateAllocator", ...
        "Allocators must not contain duplicates.");
end
if numel(unique(options.RandomSeeds)) ~= numel(options.RandomSeeds)
    error( ...
        "v2xsimregression:resourcepressure:DuplicateRandomSeed", ...
        "RandomSeeds must not contain duplicates.");
end
if options.BootstrapSampleCount < 40
    error( ...
        "v2xsimregression:resourcepressure:InsufficientBootstrapSamples", ...
        "BootstrapSampleCount must be at least 40.");
end
end

function manifest = createManifest( ...
        configurationFile,outputDirectory,allocators,randomSeeds, ...
        availabilityPercents,simulationTimeSeconds)
manifest = repmat(struct( ...
    "ConfigurationFile",configurationFile, ...
    "OutputDirectory","", ...
    "Allocator","", ...
    "RandomSeed",0, ...
    "AvailabilityPercent",0, ...
    "SimulationTimeSeconds",simulationTimeSeconds, ...
    "Label",""), ...
    1,numel(allocators) .* numel(randomSeeds) .* ...
    numel(availabilityPercents));

workIndex = 0;
for allocator = allocators
    for availabilityPercent = availabilityPercents
        for randomSeed = randomSeeds
            workIndex = workIndex + 1;
            label = compose( ...
                "%s/availability-%d/seed-%d", ...
                allocator,availabilityPercent,randomSeed);
            manifest(workIndex).OutputDirectory = fullfile( ...
                outputDirectory,lower(allocator), ...
                compose("availability-%d",availabilityPercent), ...
                compose("seed-%d",randomSeed));
            manifest(workIndex).Allocator = allocator;
            manifest(workIndex).RandomSeed = randomSeed;
            manifest(workIndex).AvailabilityPercent = availabilityPercent;
            manifest(workIndex).Label = label;
        end
    end
end
end

function result = runWorkItem(workItem)
template = v2xsim.config.load(workItem.ConfigurationFile);
configuration = template.resolve(Patch=v2xsim.config.patch( ...
    configurationPatch(workItem))); %#ok<NASGU>
evalc("v2xsim.runSimulation(configuration," + ...
    "OutputDirectory=workItem.OutputDirectory," + ...
    "RunLabel=workItem.Label);");

summaryFile = fullfile(workItem.OutputDirectory,"simulation_summary.json");
if ~isfile(summaryFile)
    error( ...
        "v2xsimregression:resourcepressure:MissingSimulationSummary", ...
        "Simulation did not publish a summary for %s.",workItem.Label);
end

prrFile = fullfile(workItem.OutputDirectory,"packet_reception_ratio_5G.csv");
[normalizedPrrAuc,counts] = scorePrrFile(prrFile,300);
result = table( ...
    workItem.Allocator,workItem.RandomSeed,workItem.AvailabilityPercent, ...
    workItem.SimulationTimeSeconds,normalizedPrrAuc, ...
    counts(1),counts(2),counts(3),sum(counts),workItem.OutputDirectory, ...
    VariableNames=[ ...
        "Allocator", "RandomSeed", "AvailabilityPercent", ...
        "SimulationTimeSeconds", "NormalizedPrrAuc", ...
        "CorrectCount", "ErrorCount", "BlockedCount", "TotalCount", ...
        "OutputDirectory"]);
end

function patchData = configurationPatch(workItem)
pressure = struct( ...
    TimeAvailabilityPercent=workItem.AvailabilityPercent, ...
    FrequencyAvailabilityPercent=workItem.AvailabilityPercent);
patchData = struct( ...
    Simulation=struct( ...
        RandomSeed=workItem.RandomSeed, ...
        DurationSeconds=workItem.SimulationTimeSeconds), ...
    Scenario=struct( ...
        Type="BidirectionalHighway", ...
        BidirectionalHighway=struct( ...
            RandomSeed=workItem.RandomSeed, ...
            VehicleCount=126, ...
            NLanes=3, ...
            LaneWidth=4, ...
            RoadLength=2100, ...
            CentralDividerWidth=0, ...
            MeanVehicleSpeed=140 ./ 3.6, ...
            VehicleSpeedStandardDeviation=0, ...
            RerollSpeedOnWrapAround=false)), ...
    Application=struct( ...
        ResourceReservationIntervalSeconds=0.1, ...
        PacketGeneration=struct( ...
            IntervalVariationSeconds=0, ...
            IntervalSeconds=0.1, ...
            RandomComponentMeanSeconds=0)), ...
    Radio=struct( ...
        Type="NrV2X", ...
        NrV2X=struct( ...
            Mcs=7, ...
            SubcarrierSpacingKilohertz=15, ...
            DmrsResourceElementCountPerSlot=24), ...
        Sidelink=struct(ResourcePool=struct( ...
            SubchannelSizeResourceBlocks=10, ...
            PartialFrequencyOverlapEnabled=false, ...
            ResourcePressure=pressure))), ...
    Awareness=struct(RangesMeters=300), ...
    ResourceAllocation=struct( ...
        Type=workItem.Allocator, ...
        RandomSeed=workItem.RandomSeed), ...
    Outputs=struct( ...
        PacketReceptionRatio=struct( ...
            Enabled=true,DistanceBinWidthMeters=25), ...
        UpdateDelay=struct(Enabled=false), ...
        PacketDelay=struct(Enabled=false), ...
        DataAge=struct(Enabled=false), ...
        WirelessBlindSpot=struct(Enabled=false), ...
        AverageNeighborCount=struct(Enabled=false), ...
        ChannelBusyRatio=struct(Enabled=false)));
end

function [normalizedPrrAuc,counts] = scorePrrFile( ...
        prrFile,maximumScoreDistanceMeters)
if ~isfile(prrFile)
    error( ...
        "v2xsimregression:resourcepressure:MissingPrrOutput", ...
        "Expected packet-reception output was not created: %s",prrFile);
end
prrData = readmatrix(prrFile);
if size(prrData,2) ~= 6 || isempty(prrData)
    error( ...
        "v2xsimregression:resourcepressure:InvalidPrrOutput", ...
        "Packet-reception output must contain six numeric columns: %s", ...
        prrFile);
end
if any(~isfinite(prrData(:,1:5)),"all") || ...
        any(prrData(:,1:5) < 0,"all") || ...
        any(prrData(:,2:5) ~= fix(prrData(:,2:5)),"all")
    error( ...
        "v2xsimregression:resourcepressure:InvalidPrrOutput", ...
        "Packet-reception distances and counts must be finite, " + ...
        "nonnegative integers.");
end
if any(prrData(:,5) ~= sum(prrData(:,2:4),2))
    error( ...
        "v2xsimregression:resourcepressure:InconsistentPrrCounts", ...
        "Every PRR row must satisfy total = correct + error + blocked.");
end

isScored = prrData(:,1) > 0 & ...
    prrData(:,1) <= maximumScoreDistanceMeters;
scored = prrData(isScored,:);
expectedDistances = (25:25:maximumScoreDistanceMeters).';
if isempty(scored) || ~isequal(scored(:,1),expectedDistances) || ...
        any(scored(:,5) == 0)
    error( ...
        "v2xsimregression:resourcepressure:IncompletePrrCurve", ...
        "Every 25 m distance bin through %g m must contain samples.", ...
        maximumScoreDistanceMeters);
end

packetReceptionRatios = scored(:,2) ./ scored(:,5);
normalizedPrrAuc = trapz( ...
    [0;scored(:,1)],[1;packetReceptionRatios]) ./ ...
    maximumScoreDistanceMeters;
counts = sum(scored(:,2:4),1);
end

function comparisons = comparePressureLevels( ...
        seedResults,allocators,randomSeeds, ...
        availabilityPercents,bootstrapSampleCount)
comparisonCells = cell(1,numel(allocators));
for allocatorIndex = 1:numel(allocators)
    allocator = allocators(allocatorIndex);
    scores = pairedScores( ...
        seedResults,allocator,randomSeeds,availabilityPercents);
    pairedDifferences = scores(:,1) - scores(:,2);
    confidenceInterval = pairedBootstrapMeanInterval( ...
        pairedDifferences,bootstrapSampleCount,92000 + allocatorIndex);
    comparisonCells{allocatorIndex} = table( ...
        allocator,numel(randomSeeds),mean(scores(:,1)),mean(scores(:,2)), ...
        mean(pairedDifferences),confidenceInterval(1),confidenceInterval(2), ...
        VariableNames=[ ...
            "Allocator", "SeedCount", "UnpressuredMeanAuc", ...
            "PressuredMeanAuc", "MeanUnpressuredMinusPressuredAuc", ...
            "Lower95ConfidenceBound", "Upper95ConfidenceBound"]);
end
comparisons = vertcat(comparisonCells{:});
end

function scores = pairedScores( ...
        seedResults,allocator,randomSeeds,availabilityPercents)
scores = zeros(numel(randomSeeds),numel(availabilityPercents));
for availabilityIndex = 1:numel(availabilityPercents)
    selected = seedResults( ...
        seedResults.Allocator == allocator & ...
        seedResults.AvailabilityPercent == ...
            availabilityPercents(availabilityIndex),:);
    [isPresent,rowOrder] = ismember(randomSeeds(:),selected.RandomSeed);
    if ~all(isPresent) || height(selected) ~= numel(randomSeeds)
        error( ...
            "v2xsimregression:resourcepressure:UnpairedSeeds", ...
            "Allocator %s does not contain every manifest seed at " + ...
            "%d%% availability.",allocator, ...
            availabilityPercents(availabilityIndex));
    end
    scores(:,availabilityIndex) = selected.NormalizedPrrAuc(rowOrder);
end
end

function confidenceInterval = pairedBootstrapMeanInterval( ...
        pairedDifferences,bootstrapSampleCount,randomSeed)
stream = RandStream("mt19937ar",Seed=randomSeed);
seedCount = numel(pairedDifferences);
sampleRows = randi( ...
    stream,seedCount,seedCount,bootstrapSampleCount);
bootstrapMeans = sort(mean(pairedDifferences(sampleRows),1));
lowerIndex = max(1,ceil(0.025 .* bootstrapSampleCount));
upperIndex = min( ...
    bootstrapSampleCount,floor(0.975 .* bootstrapSampleCount));
confidenceInterval = [ ...
    bootstrapMeans(lowerIndex),bootstrapMeans(upperIndex)];
end

function validateSimulator(simulatorRoot,configurationFile)
if ~isfolder(simulatorRoot) || ...
        ~isfile(fullfile(simulatorRoot,"src","+v2xsim","runSimulation.m"))
    error( ...
        "v2xsimregression:resourcepressure:MissingSimulator", ...
        "v2xsim.runSimulation was not found below %s.",simulatorRoot);
end
if ~isfile(configurationFile)
    error( ...
        "v2xsimregression:resourcepressure:MissingConfiguration", ...
        "Baseline configuration was not found: %s.",configurationFile);
end
end

function restoreEnvironment( ...
        originalPath,originalStream,originalStreamState,originalWarningState)
path(originalPath);
RandStream.setGlobalStream(originalStream);
originalStream.State = originalStreamState;
warning(originalWarningState);
end

function pathValue = absolutePath(pathValue,baseDirectory)
if ~isAbsolutePath(pathValue)
    pathValue = fullfile(baseDirectory,pathValue);
end
end

function tf = isAbsolutePath(pathValue)
if ispc
    tf = ~isempty(regexp(pathValue,"^[A-Za-z]:[\\/]|^\\\\","once"));
else
    tf = startsWith(pathValue,"/");
end
end
