classdef ErrorStructureAnalysisTest < matlab.unittest.TestCase
    %ERRORSTRUCTUREANALYSISTEST Tests paired error-effect inference.

    methods (TestClassSetup)
        function addRegressionPath(testCase)
            projectRoot = fileparts(fileparts(fileparts(fileparts( ...
                mfilename("fullpath")))));
            regressionPath = fullfile(projectRoot, "regression-tests");
            originalPath = path;
            testCase.addTeardown(@() path(originalPath));
            addpath(regressionPath);
        end
    end

    methods (Test)
        function identifiesDominantErrorStructure(testCase)
            results = createSyntheticResults( ...
                StructureScale=0.09, MagnitudeScale=0.005);

            analysis = ...
                v2xsimregression.positionerror.analyzeEffectDominance( ...
                    results, BootstrapSampleCount=200, RandomSeed=11);

            testCase.verifyTrue(analysis.ErrorStructureDominates);
            testCase.verifyFalse(analysis.MagnitudeDominates);
            testCase.verifyGreaterThan( ...
                analysis.PartialR2ErrorStructure, ...
                analysis.PartialR2Magnitude);
            testCase.verifyEqual( ...
                analysis.Conclusion, "ErrorStructureDominates");
            testCase.verifyTrue( ...
                analysis.PredictiveErrorStructureDominates);
            testCase.verifyFalse( ...
                analysis.PredictiveMagnitudeDominates);
            testCase.verifyGreaterThan( ...
                analysis. ...
                    PredictiveContributionErrorStructure, ...
                analysis.PredictiveContributionMagnitude);
            testCase.verifyEqual( ...
                analysis.PredictiveSensitivityConclusion, ...
                "ErrorStructureDominates");
            testCase.verifyEqual( ...
                analysis.PredictiveContributionErrorStructure + ...
                analysis.PredictiveContributionMagnitude, ...
                analysis.PredictiveLossN - ...
                analysis.PredictiveLossSM, ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                analysis.PartialR2StatisticType, ...
                "OverlappingNonadditiveDropBlock");
            testCase.verifyFalse( ...
                analysis.PartialR2ContributionsAreAdditive);
            testCase.verifyEqual( ...
                analysis.PredictiveContributionMethod, ...
                "TwoFactorShapleyLossReduction");
        end

        function identifiesDominantMagnitude(testCase)
            results = createSyntheticResults( ...
                StructureScale=0.002, MagnitudeScale=0.12);

            analysis = ...
                v2xsimregression.positionerror.analyzeEffectDominance( ...
                    results, BootstrapSampleCount=200, RandomSeed=17);

            testCase.verifyFalse(analysis.ErrorStructureDominates);
            testCase.verifyTrue(analysis.MagnitudeDominates);
            testCase.verifyLessThan( ...
                analysis.PartialR2ErrorStructure, ...
                analysis.PartialR2Magnitude);
            testCase.verifyEqual( ...
                analysis.Conclusion, "MagnitudeDominates");
            testCase.verifyFalse( ...
                analysis.PredictiveErrorStructureDominates);
            testCase.verifyTrue( ...
                analysis.PredictiveMagnitudeDominates);
            testCase.verifyLessThan( ...
                analysis. ...
                    PredictiveContributionErrorStructure, ...
                analysis.PredictiveContributionMagnitude);
            testCase.verifyEqual( ...
                analysis.PredictiveSensitivityConclusion, ...
                "MagnitudeDominates");
        end

        function supportsWithinRouteTwoModelFactorial(testCase)
            results = createSyntheticResults( ...
                StructureScale=0.08, MagnitudeScale=0.004);
            results = results( ...
                ismember( ...
                    results.ErrorModel, ...
                    ["None", "Gaussian", "FalseExit"]), :);

            analysis = ...
                v2xsimregression.positionerror.analyzeEffectDominance( ...
                    results, BootstrapSampleCount=200, RandomSeed=23);

            testCase.verifyTrue(analysis.ErrorStructureDominates);
            testCase.verifyEqual( ...
                analysis.ErrorModels, ...
                ["Gaussian", "FalseExit"]);
        end

        function consumesExplicitPairedDeltasWhenPresent(testCase)
            results = createSyntheticResults( ...
                StructureScale=0.09, MagnitudeScale=0.005);
            results.DeltaDeliveryPrrAuc = pairedDeltas(results);
            results.DeliveryPrrAuc(:) = 0.5;

            analysis = ...
                v2xsimregression.positionerror.analyzeEffectDominance( ...
                    results, BootstrapSampleCount=200, RandomSeed=29);

            testCase.verifyTrue(analysis.ErrorStructureDominates);
            testCase.verifyEqual( ...
                analysis.DeltaResponseSource, ...
                "ExplicitDeltaDeliveryPrrAuc");
        end

        function rejectsMalformedExplicitPairedDeltas(testCase)
            results = createSyntheticResults();
            results.DeltaDeliveryPrrAuc = pairedDeltas(results);

            nonfinite = results;
            nonfinite.DeltaDeliveryPrrAuc(2) = NaN;
            testCase.verifyError( ...
                @() analyze(nonfinite), ...
                "v2xsimregression:positionerror:" + ...
                "InvalidDeltaDeliveryPrrAuc");

            outsideAucDifferenceRange = results;
            outsideAucDifferenceRange. ...
                DeltaDeliveryPrrAuc(2) = -1.01;
            testCase.verifyError( ...
                @() analyze(outsideAucDifferenceRange), ...
                "v2xsimregression:positionerror:" + ...
                "InvalidDeltaDeliveryPrrAuc");

            nonzeroBaseline = results;
            nonzeroBaseline.DeltaDeliveryPrrAuc(1) = 0.01;
            testCase.verifyError( ...
                @() analyze(nonzeroBaseline), ...
                "v2xsimregression:positionerror:" + ...
                "InvalidDeltaDeliveryPrrAuc");
        end

        function categoricalMagnitudeCapturesNonlinearResponse(testCase)
            results = createNonlinearGenericResults();

            categorical = ...
                v2xsimregression.positionerror. ...
                    analyzeEffectDominance( ...
                        results, BootstrapSampleCount=40, ...
                        RandomSeed=31, ...
                        ResponseVariable="ResponseValue", ...
                        ResponseDomain="finite");
            continuous = ...
                v2xsimregression.positionerror. ...
                    analyzeEffectDominance( ...
                        results, BootstrapSampleCount=40, ...
                        RandomSeed=31, ...
                        ResponseVariable="ResponseValue", ...
                        ResponseDomain="finite", ...
                        MagnitudeModel="continuous");

            testCase.verifyEqual( ...
                categorical.MagnitudeModel, "categorical");
            testCase.verifyEqual( ...
                continuous.MagnitudeModel, "continuous");
            testCase.verifyGreaterThan( ...
                categorical.PartialR2Magnitude, ...
                continuous.PartialR2Magnitude);
            testCase.verifyGreaterThan( ...
                max(abs(results.DeltaResponseValue)), 1);
        end

        function fitsContinuousRealizedMagnitudeSensitivity(testCase)
            results = createSyntheticResults( ...
                StructureScale=0.03, MagnitudeScale=0.08);
            treatmentRows = results.ErrorModel ~= "None";
            modelOffset = zeros(height(results), 1);
            modelOffset(results.ErrorModel == "FalseExit") = 0.02;
            modelOffset(results.ErrorModel == "FalseMerge") = -0.015;
            results.RealizedNormalizedMagnitude = ...
                results.NormalizedMagnitude .* ...
                (1 + modelOffset + ...
                0.002 .* sin(results.RandomSeed));

            analysis = ...
                v2xsimregression.positionerror. ...
                    analyzeEffectDominance( ...
                        results, BootstrapSampleCount=40, ...
                        RandomSeed=37, ...
                        MagnitudeModel="continuous", ...
                        MagnitudeVariable= ...
                            "RealizedNormalizedMagnitude");

            testCase.verifyEqual( ...
                analysis.MagnitudeVariable, ...
                "RealizedNormalizedMagnitude");
            testCase.verifyEqual( ...
                analysis.MagnitudeModel, "continuous");
            testCase.verifyGreaterThan( ...
                analysis.FittedMagnitudeMinimum, 0);
            testCase.verifyTrue(all( ...
                results.RealizedNormalizedMagnitude( ...
                    treatmentRows) > 0));
        end

        function realizedMagnitudeRequiresContinuousModel(testCase)
            results = createSyntheticResults();
            results.RealizedNormalizedMagnitude = ...
                results.NormalizedMagnitude;

            testCase.verifyError( ...
                @() v2xsimregression.positionerror. ...
                    analyzeEffectDominance( ...
                        results, BootstrapSampleCount=40, ...
                        MagnitudeVariable= ...
                            "RealizedNormalizedMagnitude"), ...
                "v2xsimregression:positionerror:" + ...
                "RealizedMagnitudeRequiresContinuousModel");
        end

        function rejectsUnbalancedTreatments(testCase)
            results = createSyntheticResults();
            results(end, :) = [];

            testCase.verifyError( ...
                @() v2xsimregression.positionerror. ...
                    analyzeEffectDominance( ...
                        results, BootstrapSampleCount=40), ...
                "v2xsimregression:positionerror:UnbalancedManifest");
        end

        function rejectsDegeneratePredictiveReferenceLoss(testCase)
            results = createSyntheticResults();
            results.DeltaDeliveryPrrAuc = zeros(height(results), 1);
            results.DeltaDeliveryPrrAuc( ...
                results.ErrorModel ~= "None") = -0.1;

            testCase.verifyError( ...
                @() v2xsimregression.positionerror. ...
                    analyzeEffectDominance( ...
                        results, BootstrapSampleCount=40), ...
                "v2xsimregression:positionerror:" + ...
                "DegeneratePredictiveReferenceLoss");
        end

        function rejectsRankDeficientPredictiveSensitivity( ...
                testCase)
            results = createSyntheticResults();
            results.RealizedNormalizedMagnitude = ...
                double(results.ErrorModel ~= "None");

            testCase.verifyError( ...
                @() v2xsimregression.positionerror. ...
                    analyzeEffectDominance( ...
                        results, BootstrapSampleCount=40, ...
                        MagnitudeModel="continuous", ...
                        MagnitudeVariable= ...
                            "RealizedNormalizedMagnitude"), ...
                "v2xsimregression:positionerror:" + ...
                "RankDeficientPredictiveEffectModel");
        end
    end
end

function analysis = analyze(results)
analysis = v2xsimregression.positionerror.analyzeEffectDominance( ...
    results, BootstrapSampleCount=40);
end

function deltas = pairedDeltas(results)
deltas = zeros(height(results), 1);
seedIds = unique(results.RandomSeed, "stable");
for seed = reshape(seedIds, 1, [])
    seedRows = results.RandomSeed == seed;
    baseline = seedRows & results.ErrorModel == "None";
    deltas(seedRows) = ...
        results.DeliveryPrrAuc(seedRows) - ...
        results.DeliveryPrrAuc(baseline);
end
end

function results = createNonlinearGenericResults()
randomSeeds = (1:8).';
models = ["Gaussian", "FalseExit", "FalseMerge"];
magnitudes = [0.25, 0.5, 1];
nonlinearMagnitudeLevels = [0, 2, 0];
rowCount = numel(randomSeeds) .* ...
    (1 + numel(models) .* numel(magnitudes));
seedColumn = zeros(rowCount, 1);
modelColumn = strings(rowCount, 1);
magnitudeColumn = zeros(rowCount, 1);
responseColumn = zeros(rowCount, 1);
deltaColumn = zeros(rowCount, 1);
nextRow = 0;
for seed = reshape(randomSeeds, 1, [])
    baseline = 10 + 0.01 .* seed;
    nextRow = nextRow + 1;
    seedColumn(nextRow) = seed;
    modelColumn(nextRow) = "None";
    responseColumn(nextRow) = baseline;
    for modelIndex = 1:numel(models)
        for magnitudeIndex = 1:numel(magnitudes)
            magnitude = magnitudes(magnitudeIndex);
            nonlinearMagnitude = ...
                nonlinearMagnitudeLevels(magnitudeIndex);
            delta = nonlinearMagnitude + ...
                0.05 .* (modelIndex - 1) + ...
                0.002 .* sin( ...
                    11 .* seed + 3 .* modelIndex + ...
                    magnitudeIndex);
            nextRow = nextRow + 1;
            seedColumn(nextRow) = seed;
            modelColumn(nextRow) = models(modelIndex);
            magnitudeColumn(nextRow) = magnitude;
            responseColumn(nextRow) = baseline + delta;
            deltaColumn(nextRow) = delta;
        end
    end
end
results = table( ...
    seedColumn, modelColumn, magnitudeColumn, ...
    responseColumn, deltaColumn, ...
    VariableNames=[ ...
        "RandomSeed", "ErrorModel", "NormalizedMagnitude", ...
        "ResponseValue", "DeltaResponseValue"]);
end

function results = createSyntheticResults(options)
arguments
    options.StructureScale (1, 1) double = 0.05
    options.MagnitudeScale (1, 1) double = 0.02
end

randomSeeds = (1:12).';
models = ["Gaussian", "FalseExit", "FalseMerge"];
magnitudes = [0.25, 0.5, 1];
rowCount = numel(randomSeeds) .* ...
    (1 + numel(models) .* numel(magnitudes));
seedColumn = zeros(rowCount, 1);
modelColumn = strings(rowCount, 1);
magnitudeColumn = zeros(rowCount, 1);
aucColumn = zeros(rowCount, 1);
nextRow = 0;

for seedIndex = 1:numel(randomSeeds)
    seedEffect = 0.002 .* sin(randomSeeds(seedIndex));
    baseline = 0.92 + seedEffect;
    nextRow = nextRow + 1;
    seedColumn(nextRow) = randomSeeds(seedIndex);
    modelColumn(nextRow) = "None";
    aucColumn(nextRow) = baseline;

    for modelIndex = 1:numel(models)
        modelLevel = modelIndex - 1;
        for magnitude = magnitudes
            nextRow = nextRow + 1;
            seedColumn(nextRow) = randomSeeds(seedIndex);
            modelColumn(nextRow) = models(modelIndex);
            magnitudeColumn(nextRow) = magnitude;
            smallDeterministicResidual = 0.0002 .* ...
                sin(13 .* seedIndex + 7 .* modelIndex + magnitude);
            aucColumn(nextRow) = baseline - ...
                options.StructureScale .* modelLevel - ...
                options.MagnitudeScale .* magnitude + ...
                smallDeterministicResidual;
        end
    end
end

results = table( ...
    seedColumn, modelColumn, magnitudeColumn, aucColumn, ...
    VariableNames=[ ...
        "RandomSeed", "ErrorModel", ...
        "NormalizedMagnitude", "DeliveryPrrAuc"]);
end
