classdef MechanismEffectAnalysisTest < matlab.unittest.TestCase
    %MECHANISMEFFECTANALYSISTEST Tests long mechanism factorials.

    methods (TestClassSetup)
        function addRegressionPath(testCase)
            projectRoot = fileparts(fileparts(fileparts(fileparts( ...
                mfilename("fullpath")))));
            regressionPath = fullfile(projectRoot, "regression-tests");
            originalPath = path;
            testCase.addTeardown(@() path(originalPath));
            addpath(regressionPath);
        end
    end

    methods (Test)
        function campaignUsesComparableFailureRates(testCase)
            [outcomes, baselines, aucOutcomes] = ...
                v2xsimregression.positionerror. ...
                    rampMechanismOutcomeConfiguration();

            prefixes = [ ...
                "HiddenTerminal", ...
                "HalfDuplexFailure", ...
                "CochannelInterferenceFailure", ...
                "AdjacentChannelInterferenceFailure", ...
                "CrossTechnologyInterferenceFailure", ...
                "MultipleSufficientInterferersFailure", ...
                "JointInterferenceFailure", ...
                "OtherInterferenceFailure", ...
                "NoiseOrPropagationFailure"];
            for prefix = prefixes
                testCase.verifyTrue(ismember( ...
                    prefix + "CompositionRate", outcomes));
                testCase.verifyTrue(ismember( ...
                    prefix + "IncidenceRate", outcomes));
            end
            testCase.verifyFalse(any(endsWith(outcomes, "Count")));
            testCase.verifyFalse(ismember( ...
                "EitherEndpointStatusEffectActiveDeliveryPrrAuc", ...
                outcomes));
            testCase.verifyTrue(ismember( ...
                "MeanInterferenceOverlapPairGraphXorRate", ...
                outcomes));
            testCase.verifyTrue(ismember( ...
                "MeanHarmfulInterferenceOverlapCandidateRate", ...
                outcomes));
            testCase.verifyTrue(ismember( ...
                "MeanMissedInterferenceOverlapCandidateRate", ...
                outcomes));
            testCase.verifyEqual(baselines, outcomes);
            testCase.verifyEqual(aucOutcomes, "RadioPrrAuc");
        end

        function buildsCombinedAndWithinRoutePairedRows(testCase)
            seedResults = oneSeedResults();
            effectRows = v2xsimregression.positionerror. ...
                buildMechanismEffectResults( ...
                    seedResults, ...
                    ["Metric", "StatusEffectActiveAuc"], ...
                    BaselineVariables= ...
                        ["Metric", "OverallAuc"], ...
                    AucOutcomeVariables="StatusEffectActiveAuc");

            testCase.verifyEqual(height(effectRows), 20);
            combined = effectRows( ...
                effectRows.OutcomeName == "Metric" & ...
                effectRows.Estimand == "RouteBalanced", :);
            testCase.verifyEqual( ...
                combined.ErrorModel, ...
                ["None"; "Gaussian"; "FalseExit"; "FalseMerge"]);
            testCase.verifyEqual( ...
                combined.ResponseValue, [10; 13; 16; 18]);
            testCase.verifyEqual( ...
                combined.DeltaResponseValue, [0; 3; 6; 8]);
            testCase.verifyEqual( ...
                combined.RealizedNormalizedMagnitude, ...
                [0; 0.5; 0.48; 0.52], AbsTol=1e-12);

            mainline = effectRows( ...
                effectRows.OutcomeName == "Metric" & ...
                effectRows.Estimand == "Mainline", :);
            testCase.verifyEqual( ...
                mainline.ResponseValue, [10; 12; 16]);
            testCase.verifyEqual( ...
                mainline.DeltaResponseValue, [0; 2; 6]);

            ramp = effectRows( ...
                effectRows.OutcomeName == "Metric" & ...
                effectRows.Estimand == "Ramp", :);
            testCase.verifyEqual( ...
                ramp.ResponseValue, [10; 14; 18]);
            testCase.verifyEqual( ...
                ramp.DeltaResponseValue, [0; 4; 8]);

            activeEffect = effectRows( ...
                effectRows.OutcomeName == "StatusEffectActiveAuc" & ...
                effectRows.Estimand == "RouteBalanced", :);
            testCase.verifyEqual( ...
                activeEffect.BaselineVariable, ...
                repmat("OverallAuc", 4, 1));
            testCase.verifyEqual( ...
                activeEffect.ResponseValue, ...
                [0.8; 0.65; 0.5; 0.4], ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                activeEffect.DeltaResponseValue, ...
                [0; -0.15; -0.3; -0.4], AbsTol=1e-12);
        end

        function incompleteOutcomeIsNotAnalyzable(testCase)
            seedResults = factorialSeedResults();
            effectRows = v2xsimregression.positionerror. ...
                buildMechanismEffectResults( ...
                    seedResults, ["Metric", "HiddenRate"]);

            analysis = v2xsimregression.positionerror. ...
                analyzeMechanismEffectResults( ...
                    effectRows, BootstrapSampleCount=40, ...
                    RandomSeed=13);

            metric = analysis.Outcomes( ...
                string({analysis.Outcomes.OutcomeName}) == "Metric");
            hidden = analysis.Outcomes( ...
                string({analysis.Outcomes.OutcomeName}) == ...
                    "HiddenRate");
            testCase.verifyEqual(metric.Status, "Analyzed");
            testCase.verifyEqual(hidden.Status, "NotAnalyzable");
            testCase.verifyEqual( ...
                string({hidden.Estimands.Status}), ...
                repmat("NotAnalyzable", 1, 3));
            testCase.verifyEqual( ...
                string({hidden.Estimands.Reason}), ...
                repmat("NonfiniteResponse", 1, 3));
            encoded = jsonencode(analysis);
            decoded = jsondecode(encoded);
            testCase.verifyEqual(decoded.OutcomeCount, 2);
        end

        function analysisCanBeDisabledWithoutValidResponses(testCase)
            seedResults = factorialSeedResults();
            effectRows = v2xsimregression.positionerror. ...
                buildMechanismEffectResults( ...
                    seedResults, "HiddenRate");

            analysis = v2xsimregression.positionerror. ...
                analyzeMechanismEffectResults( ...
                    effectRows, RunEffectAnalysis=false);

            testCase.verifyEqual( ...
                analysis.Outcomes.Status, "NotRequested");
            testCase.verifyEqual( ...
                string({analysis.Outcomes.Estimands.Status}), ...
                repmat("NotRequested", 1, 3));
        end

        function invalidAucIsNotAnalyzable(testCase)
            seedResults = factorialSeedResults();
            effectRows = v2xsimregression.positionerror. ...
                buildMechanismEffectResults( ...
                    seedResults, "Metric", ...
                    AucOutcomeVariables="Metric");

            analysis = v2xsimregression.positionerror. ...
                analyzeMechanismEffectResults( ...
                    effectRows, BootstrapSampleCount=40);

            testCase.verifyEqual( ...
                analysis.Outcomes.Status, "NotAnalyzable");
            testCase.verifyEqual( ...
                string({analysis.Outcomes.Estimands.Reason}), ...
                repmat("ResponseOutsideAucRange", 1, 3));
        end

        function supportsRealizedMagnitudeSensitivity(testCase)
            seedResults = factorialSeedResults();
            effectRows = v2xsimregression.positionerror. ...
                buildMechanismEffectResults(seedResults, "Metric");

            analysis = v2xsimregression.positionerror. ...
                analyzeMechanismEffectResults( ...
                    effectRows, BootstrapSampleCount=40, ...
                    MagnitudeModel="continuous", ...
                    MagnitudeVariable= ...
                        "RealizedNormalizedMagnitude");

            testCase.verifyEqual( ...
                analysis.MagnitudeVariable, ...
                "RealizedNormalizedMagnitude");
            testCase.verifyEqual( ...
                analysis.Outcomes.Status, "Analyzed");
            estimands = analysis.Outcomes.Estimands;
            for estimandIndex = 1:numel(estimands)
                testCase.verifyEqual( ...
                    estimands(estimandIndex). ...
                        Analysis.MagnitudeVariable, ...
                    "RealizedNormalizedMagnitude");
            end
        end
    end
end

function results = oneSeedResults()
randomSeed = ones(5, 1);
treatment = [ ...
    "None"; "GaussianMainline"; "GaussianRamp"; ...
    "FalseExit"; "FalseMerge"];
    normalizedMagnitude = [0; 0.5; 0.5; 0.5; 0.5];
    realizedNormalizedMagnitude = [0; 0.45; 0.55; 0.48; 0.52];
metric = [10; 12; 14; 16; 18];
overallAuc = repmat(0.8, 5, 1);
statusEffectActiveAuc = [NaN; 0.7; 0.6; 0.5; 0.4];
results = table( ...
    randomSeed, treatment, normalizedMagnitude, ...
    realizedNormalizedMagnitude, ...
    metric, overallAuc, statusEffectActiveAuc, ...
    VariableNames=[ ...
        "RandomSeed", "Treatment", "NormalizedMagnitude", ...
        "RealizedNormalizedMagnitude", ...
        "Metric", "OverallAuc", "StatusEffectActiveAuc"]);
end

function results = factorialSeedResults()
seedIds = (1:4).';
magnitudes = [0.25, 1];
rowCount = numel(seedIds) .* ...
    (1 + 4 .* numel(magnitudes));
randomSeed = zeros(rowCount, 1);
treatment = strings(rowCount, 1);
normalizedMagnitude = zeros(rowCount, 1);
realizedNormalizedMagnitude = zeros(rowCount, 1);
metric = zeros(rowCount, 1);
hiddenRate = nan(rowCount, 1);
nextRow = 0;
for seed = reshape(seedIds, 1, [])
    baseline = 10 + 0.1 .* seed;
    nextRow = nextRow + 1;
    randomSeed(nextRow) = seed;
    treatment(nextRow) = "None";
    metric(nextRow) = baseline;
    for magnitude = magnitudes
        for selectedTreatment = [ ...
                "GaussianMainline", "GaussianRamp", ...
                "FalseExit", "FalseMerge"]
            nextRow = nextRow + 1;
            randomSeed(nextRow) = seed;
            treatment(nextRow) = selectedTreatment;
            normalizedMagnitude(nextRow) = magnitude;
            realizedNormalizedMagnitude(nextRow) = ...
                magnitude .* (1 + 0.01 .* sin( ...
                    seed + strlength(selectedTreatment)));
            if selectedTreatment == "GaussianMainline"
                effect = 0.2 + 0.3 .* magnitude;
            elseif selectedTreatment == "GaussianRamp"
                effect = 0.3 + 0.2 .* magnitude;
            elseif selectedTreatment == "FalseExit"
                effect = 0.8 + 0.1 .* magnitude;
            else
                effect = -0.4 + 0.5 .* magnitude;
            end
            metric(nextRow) = baseline + effect;
        end
    end
end
results = table( ...
    randomSeed, treatment, normalizedMagnitude, ...
    realizedNormalizedMagnitude, ...
    metric, hiddenRate, ...
    VariableNames=[ ...
        "RandomSeed", "Treatment", "NormalizedMagnitude", ...
        "RealizedNormalizedMagnitude", ...
        "Metric", "HiddenRate"]);
end
