classdef RampCampaignManifestTest < matlab.unittest.TestCase
    %RAMPCAMPAIGNMANIFESTTEST Tests paired treatment construction.

    methods (TestClassSetup)
        function addRegressionPath(testCase)
            projectRoot = fileparts(fileparts(fileparts(fileparts( ...
                mfilename("fullpath")))));
            regressionPath = fullfile(projectRoot, "regression-tests");
            originalPath = path;
            testCase.addTeardown(@() path(originalPath));
            addpath(regressionPath);
        end
    end

    methods (Test)
        function createsCompletePairedFactorial(testCase)
            manifest = v2xsimregression.positionerror. ...
                createRampCampaignManifest( ...
                    "/tmp/ramp-study", [7, 11], [0.25, 0.5, 1], ...
                    RoadLengthMeters=2000, ...
                    LaneWidthMeters=4, ...
                    MergeDistanceMeters=100);

            testCase.verifyEqual(height(manifest), 26);
            for seed = [7, 11]
                seedRows = manifest(manifest.RandomSeed == seed, :);
                testCase.verifyEqual( ...
                    nnz(seedRows.ErrorModel == "None"), 1);
                for treatment = [ ...
                        "GaussianMainline", "GaussianRamp", ...
                        "FalseExit", "FalseMerge"]
                    modelRows = seedRows( ...
                        seedRows.Treatment == treatment, :);
                    testCase.verifyEqual( ...
                        modelRows.NormalizedMagnitude, ...
                        [0.25; 0.5; 1]);
                end
                treatmentRows = seedRows(seedRows.ErrorModel ~= "None", :);
                testCase.verifyEqual( ...
                    unique(treatmentRows.SelectionRandomSeed), ...
                    seedRows.SelectionRandomSeed(1));
            end

            expectedFullScaleMean = 500 + 4 .* 0.95;
            fullScaleRows = ...
                manifest.NormalizedMagnitude == 1;
            testCase.verifyEqual( ...
                manifest.TargetMeanMagnitudeMeters(fullScaleRows), ...
                repmat(expectedFullScaleMean, 8, 1), ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                manifest.FalseRouteDisplacementScale(fullScaleRows), ...
                ones(8, 1), AbsTol=1e-12);
            gaussianRows = ...
                manifest.Treatment == "GaussianMainline" & ...
                fullScaleRows;
            testCase.verifyEqual( ...
                manifest. ...
                    GaussianAxisStandardDeviationMeters(gaussianRows), ...
                repmat( ...
                    expectedFullScaleMean .* sqrt(2 ./ pi), ...
                    2, 1), ...
                AbsTol=1e-12);
        end

        function rejectsDuplicateFactors(testCase)
            testCase.verifyError( ...
                @() v2xsimregression.positionerror. ...
                    createRampCampaignManifest( ...
                        "/tmp/ramp-study", [1, 1], 0.5), ...
                "v2xsimregression:positionerror:DuplicateRandomSeed");
            testCase.verifyError( ...
                @() v2xsimregression.positionerror. ...
                    createRampCampaignManifest( ...
                        "/tmp/ramp-study", 1, [0.5, 0.5]), ...
                "v2xsimregression:positionerror:DuplicateMagnitude");
        end

        function rejectsInvalidAnalysisDesignBeforeExecution(testCase)
            missingRoot = "/definitely-missing-v2xsim-root";
            unusedOutput = "/tmp/unused-ramp-study-output";
            testCase.verifyError( ...
                @() v2xsimregression.positionerror. ...
                    runRampErrorStructureCampaign( ...
                        missingRoot, unusedOutput, ...
                        RandomSeeds=[1, 2], ...
                        NormalizedMagnitudes=0.5), ...
                "v2xsimregression:positionerror:" + ...
                "InsufficientAnalysisMagnitudes");
            testCase.verifyError( ...
                @() v2xsimregression.positionerror. ...
                    runRampErrorStructureCampaign( ...
                        missingRoot, unusedOutput, ...
                        RandomSeeds=[1, 2], ...
                        BootstrapSampleCount=39), ...
                "v2xsimregression:positionerror:" + ...
                "InsufficientBootstrapSamples");
            testCase.verifyError( ...
                @() v2xsimregression.positionerror. ...
                    runRampErrorStructureCampaign( ...
                        missingRoot, unusedOutput, ...
                        RandomSeeds=[1, 2], ...
                        ExposedShadowEvaluationHorizonSeconds=1), ...
                "v2xsimregression:positionerror:" + ...
                "InvalidExposedShadowHorizon");
        end

        function buildsRouteMatchedBaselineDeltas(testCase)
            seed = ones(5, 1);
            treatment = [ ...
                "None"; "GaussianMainline"; "GaussianRamp"; ...
                "FalseExit"; "FalseMerge"];
            magnitude = [0; 0.5; 0.5; 0.5; 0.5];
            realizedMagnitude = [0; 0.45; 0.55; 0.48; 0.52];
            mainlineAuc = [0.8; 0.7; 0.1; 0.75; 0.1];
            rampAuc = [0.6; 0.1; 0.4; 0.1; 0.3];
            raw = table( ...
                seed, treatment, magnitude, realizedMagnitude, ...
                mainlineAuc, rampAuc, ...
                VariableNames=[ ...
                    "RandomSeed", "Treatment", ...
                    "NormalizedMagnitude", ...
                    "RealizedNormalizedMagnitude", ...
                    "MainlineTransmitterDeliveryPrrAuc", ...
                    "RampTransmitterDeliveryPrrAuc"]);

            matched = v2xsimregression.positionerror. ...
                buildRouteMatchedEffectResults(raw);

            testCase.verifyEqual( ...
                matched.ErrorModel, ...
                ["None"; "Gaussian"; "FalseExit"; "FalseMerge"]);
            testCase.verifyEqual( ...
                matched.DeliveryPrrAuc, ...
                [0.7; 0.55; 0.75; 0.3], ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                matched.DeltaDeliveryPrrAuc, ...
                [0; -0.15; -0.05; -0.3], ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                matched.RealizedNormalizedMagnitude, ...
                [0; 0.5; 0.48; 0.52], AbsTol=1e-12);

            stratified = v2xsimregression.positionerror. ...
                buildRouteStratifiedEffectResults(raw);
            testCase.verifyEqual( ...
                stratified.RoutePopulation, ...
                ["Mainline"; "Mainline"; "Mainline"; ...
                    "Ramp"; "Ramp"; "Ramp"]);
            testCase.verifyEqual( ...
                stratified.ErrorModel, ...
                ["None"; "Gaussian"; "FalseExit"; ...
                    "None"; "Gaussian"; "FalseMerge"]);
            testCase.verifyEqual( ...
                stratified.DeliveryPrrAuc, ...
                [0.8; 0.7; 0.75; 0.6; 0.4; 0.3], ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                stratified.RealizedNormalizedMagnitude, ...
                [0; 0.45; 0.48; 0; 0.55; 0.52], ...
                AbsTol=1e-12);
        end

        function checksExactRouteMatchedExposureCohorts(testCase)
            results = table( ...
                ones(5, 1), ...
                [0; 0.5; 0.5; 0.5; 0.5], ...
                ["None"; "GaussianMainline"; "GaussianRamp"; ...
                    "FalseExit"; "FalseMerge"], ...
                [""; "A|B"; "C|D"; "A|B"; "C|D"], ...
                [0; 10; 8; 10; 8], ...
                [0; 2; 1; 2; 1], ...
                VariableNames=[ ...
                    "RandomSeed", "NormalizedMagnitude", ...
                    "Treatment", "SelectedVehicleCohortKey", ...
                    "ActivePositionSampleCount", ...
                    "StatusEffectEpisodeCount"]);

            matched = v2xsimregression.positionerror. ...
                addExposureMatchingDiagnostics(results);

            testCase.verifyEqual( ...
                matched.ExposureMatchingStatus, ...
                ["NoErrorBaseline"; repmat("Matched", 4, 1)]);
            testCase.verifyTrue(all( ...
                matched.ExposureCohortMatch));
            testCase.verifyEqual( ...
                matched.ExposureActiveSampleCountDifference, ...
                zeros(5, 1));

            results.ActivePositionSampleCount(4) = 9;
            mismatched = v2xsimregression.positionerror. ...
                addExposureMatchingDiagnostics(results);
            testCase.verifyEqual( ...
                mismatched.ExposureMatchingStatus(2), ...
                "Mismatch");
            testCase.verifyEqual( ...
                mismatched.ExposureMatchingStatus(4), ...
                "Mismatch");
        end

        function rejectsIncompleteStatusEffectMatchingSchema(testCase)
            incomplete = table( ...
                1, 0.5, "GaussianMainline", "A|B", 10, ...
                VariableNames=[ ...
                    "RandomSeed", "NormalizedMagnitude", ...
                    "Treatment", "SelectedVehicleCohortKey", ...
                    "ActivePositionSampleCount"]);

            testCase.verifyError( ...
                @() v2xsimregression.positionerror. ...
                    addExposureMatchingDiagnostics(incomplete), ...
                "v2xsimregression:positionerror:" + ...
                "InvalidExposureMatchingResults");
        end

        function neverManufacturesOutOfRangeRouteMatchedAuc(testCase)
            seed = ones(5, 1);
            treatment = [ ...
                "None"; "GaussianMainline"; "GaussianRamp"; ...
                "FalseExit"; "FalseMerge"];
            magnitude = [0; 0.5; 0.5; 0.5; 0.5];
            realizedMagnitude = magnitude;
            mainlineAuc = [0.9; 0.2; 0.5; 0.1; 0.5];
            rampAuc = [0.1; 0.5; 0.8; 0.5; 0.9];
            raw = table( ...
                seed, treatment, magnitude, realizedMagnitude, ...
                mainlineAuc, rampAuc, ...
                VariableNames=[ ...
                    "RandomSeed", "Treatment", ...
                    "NormalizedMagnitude", ...
                    "RealizedNormalizedMagnitude", ...
                    "MainlineTransmitterDeliveryPrrAuc", ...
                    "RampTransmitterDeliveryPrrAuc"]);

            matched = v2xsimregression.positionerror. ...
                buildRouteMatchedEffectResults(raw);

            testCase.verifyEqual( ...
                matched.DeliveryPrrAuc, ...
                [0.5; 0.5; 0.1; 0.9], ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                matched.DeltaDeliveryPrrAuc, ...
                [0; 0; -0.8; 0.8], ...
                AbsTol=1e-12);
            testCase.verifyGreaterThanOrEqual( ...
                matched.DeliveryPrrAuc, zeros(4, 1));
            testCase.verifyLessThanOrEqual( ...
                matched.DeliveryPrrAuc, ones(4, 1));
        end
    end
end
