classdef RampRunSummaryTest < matlab.unittest.TestCase
    %RAMPRUNSUMMARYTEST Tests reduction of raw research traces.

    methods (TestClassSetup)
        function addRegressionPath(testCase)
            projectRoot = fileparts(fileparts(fileparts(fileparts( ...
                mfilename("fullpath")))));
            regressionPath = fullfile(projectRoot, "regression-tests");
            originalPath = path;
            testCase.addTeardown(@() path(originalPath));
            addpath(regressionPath);
        end
    end

    methods (Test)
        function summarizesMechanismChainAndActiveStatusEffect(testCase)
            fixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            runDirectory = string(fixture.Folder);
            writelines( ...
                "{""SchemaVersion"":2,""Run"":{" + ...
                    """RunLabel"":""seed-7/false-exit""}}", ...
                fullfile(runDirectory, ...
                    "simulation_summary.json"));

            positionRows = createPositionRows();
            writetable( ...
                positionRows, fullfile(runDirectory, ...
                    "position_error_trace_000001.csv"));
            fates = createPacketFates();
            writetable( ...
                fates, fullfile(runDirectory, ...
                    "packet_fates_000001.csv"));
            [attempts, counterfactuals] = ...
                createInterferenceEvidence();
            writetable( ...
                attempts, fullfile(runDirectory, ...
                    "interference_attempts_000001.csv"));
            writetable( ...
                counterfactuals, fullfile(runDirectory, ...
                    "interference_counterfactuals_000001.csv"));
            topology = table( ...
                [0.2; 0.4], [0.8; 0.6], ...
                VariableNames=[ ...
                    "NormalizedKendallTauDistance", ...
                    "TopKNeighborJaccard"]);
            writetable( ...
                topology, fullfile(runDirectory, ...
                    "controller_topology.csv"));
            allocation = table( ...
                0.25, 0.75, 0.4, 0.5, 0.5, ...
                1, 1, 0.25, 0.25, ...
                1, 1, 0.125, 0.125, ...
                VariableNames=[ ...
                    "ResourcePairGraphXorRate", ...
                    "ResourcePairGraphJaccard", ...
                    "InterferenceOverlapPairGraphXorRate", ...
                    "InterferenceOverlapPairGraphJaccard", ...
                    "ExactDecisionDisagreementRate", ...
                    "HarmfulReuseCandidateCount", ...
                    "MissedReuseCandidateCount", ...
                    "HarmfulReuseCandidateRate", ...
                    "MissedReuseCandidateRate", ...
                    "HarmfulInterferenceOverlapCandidateCount", ...
                    "MissedInterferenceOverlapCandidateCount", ...
                    "HarmfulInterferenceOverlapCandidateRate", ...
                    "MissedInterferenceOverlapCandidateRate"]);
            writetable( ...
                allocation, fullfile(runDirectory, ...
                    "controller_allocation_summary.csv"));
            decisions = table( ...
                [2; 4], ...
                VariableNames="TrueTimeRegretMeters");
            writetable( ...
                decisions, fullfile(runDirectory, ...
                    "controller_allocation_decision.csv"));
            reuseCandidates = table( ...
                [0; 0], [0; 0], [1; 1], ...
                ["global"; "global"], ...
                ["V1"; "V1"], ["V2"; "V3"], ...
                ["harmful_reuse"; "missed_reuse"], ...
                [true; false], [false; true], ...
                ["cochannel"; "separate_time"], ...
                ["separate_time"; "cochannel"], ...
                [true; false], [false; true], ...
                [1; 1], [1; 2], [1; 3], [2; 3], ...
                VariableNames=[ ...
                    "SimulationTimeSeconds", ...
                    "AllocationEpoch", "AbsoluteSlot", ...
                    "NetworkSliceId", "FirstUeId", ...
                    "SecondUeId", "CandidateType", ...
                    "LiveSameResource", "OracleSameResource", ...
                    "LiveResourceRelation", ...
                    "OracleResourceRelation", ...
                    "IsHarmfulInterferenceOverlap", ...
                    "IsMissedInterferenceOverlap", ...
                    "LiveFirstResourceId", ...
                    "LiveSecondResourceId", ...
                    "OracleFirstResourceId", ...
                    "OracleSecondResourceId"]);
            writetable( ...
                reuseCandidates, fullfile(runDirectory, ...
                    "controller_reuse_candidate.csv"));

            summary = ...
                v2xsimregression.positionerror.summarizeRampRun( ...
                    runDirectory, 50, 25);

            testCase.verifyEqual( ...
                summary.RealizedMeanErrorMagnitudeMeters, 5, ...
                AbsTol=1e-12);
            testCase.verifyEqual(summary.ActivePositionSampleCount, 1);
            testCase.verifyEqual(summary.PositionModuleSampleCount, 2);
            testCase.verifyEqual( ...
                summary.ActivePositionSampleFraction, 0.5);
            testCase.verifyEqual( ...
                summary.OverallMeanErrorMagnitudeMeters, 2.5, ...
                AbsTol=1e-12);
            testCase.verifyEqual(summary.SelectedVehicleCount, 1);
            testCase.verifyEqual( ...
                summary.SelectedVehicleCohortKey, "V1");
            testCase.verifyEqual( ...
                summary.StatusEffectEpisodeCount, 1);
            testCase.verifyEqual( ...
                summary.LeftCensoredEpisodeCount, 1);
            testCase.verifyEqual( ...
                summary.RightCensoredEpisodeCount, 1);
            testCase.verifyEqual( ...
                summary.DeliveryPrrAuc, 0.75, AbsTol=1e-12);
            testCase.verifyEqual( ...
                summary.StatusEffectActiveTransmitterDeliveryPrrAuc, ...
                0.75, AbsTol=1e-12);
            testCase.verifyEqual( ...
                summary.MeanNormalizedKendallTauDistance, ...
                0.3, AbsTol=1e-12);
            testCase.verifyEqual( ...
                summary.MeanResourcePairGraphXorRate, 0.25);
            testCase.verifyEqual( ...
                summary.MeanInterferenceOverlapPairGraphXorRate, ...
                0.4);
            testCase.verifyEqual( ...
                summary.MeanInterferenceOverlapPairGraphJaccard, ...
                0.5);
            testCase.verifyEqual( ...
                summary.MeanTrueDistanceRegretMeters, 3);
            testCase.verifyEqual( ...
                summary.HarmfulReuseCandidateCount, 1);
            testCase.verifyEqual( ...
                summary.MissedReuseCandidateCount, 1);
            testCase.verifyEqual( ...
                summary.MeanHarmfulReuseCandidateRate, 0.25);
            testCase.verifyEqual( ...
                summary.MeanMissedReuseCandidateRate, 0.25);
            testCase.verifyEqual( ...
                summary.HarmfulInterferenceOverlapCandidateCount, ...
                1);
            testCase.verifyEqual( ...
                summary.MissedInterferenceOverlapCandidateCount, ...
                1);
            testCase.verifyEqual( ...
                summary. ...
                    MeanHarmfulInterferenceOverlapCandidateRate, ...
                0.125);
            testCase.verifyEqual( ...
                summary. ...
                    MeanMissedInterferenceOverlapCandidateRate, ...
                0.125);
            testCase.verifyEqual( ...
                summary.ExposedReuseShadowCaseCount, 1);
            testCase.verifyEqual( ...
                summary.ExposedTerminalClassificationStatus, ...
                "ShadowRunRequired");
            testCase.verifyEqual( ...
                summary.FailureClassificationStatus, "Complete");
            testCase.verifyFalse( ...
                summary.FailureModeRatesAreMutuallyExclusive);
            testCase.verifyEqual( ...
                summary.HiddenTerminalDefinition, ...
                "IndividuallySufficientAllocatorInducedInterferer");
            testCase.verifyFalse( ...
                summary.JointHiddenTerminalAttributionAvailable);
            testCase.verifyTrue( ...
                summary.FailureAllocatorEvidenceAvailable);
            testCase.verifyEqual(summary.HiddenTerminalCount, 1);
            testCase.verifyEqual( ...
                summary.HiddenTerminalRateAmongErrors, 1);
            testCase.verifyEqual( ...
                summary.HiddenTerminalCompositionRate, 1);
            testCase.verifyEqual( ...
                summary.HiddenTerminalIncidenceRate, 0.5, ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                summary.FailureCompositionDenominatorErrorCount, 1);
            testCase.verifyEqual( ...
                summary.FailureIncidenceDenominatorRadioFateCount, 2);
            testCase.verifyEqual(summary.BlockedCount, 1);
            testCase.verifyEqual( ...
                summary.HiddenTerminalCompositionRateStatus, ...
                "Analyzable");
            testCase.verifyEqual( ...
                summary.HiddenTerminalIncidenceRateStatus, ...
                "Analyzable");
            testCase.verifyEqual( ...
                summary. ...
                    StatusEffectActiveTransmitterHiddenTerminalCount, ...
                1);
            testCase.verifyEqual( ...
                summary. ...
                    EitherEndpointStatusEffectActiveHiddenTerminalCount, ...
                1);
            testCase.verifyEqual( ...
                summary.FailureEvidenceCoverageRate, 1);
            failureEvents = readtable( ...
                fullfile(runDirectory, "failure_mode_events.csv"), ...
                TextType="string");
            testCase.verifyEqual(height(failureEvents), 1);
            testCase.verifyEqual( ...
                failureEvents.FailureMode, "hidden_terminal");
            testCase.verifyTrue(logical( ...
                failureEvents. ...
                    TransmitterPositionErrorActive));
            testCase.verifyTrue(logical( ...
                failureEvents.AllocatorEvidenceAvailable));
            failureSummary = readtable( ...
                fullfile(runDirectory, "failure_mode_summary.csv"), ...
                TextType="string");
            hiddenRow = ...
                failureSummary.FailureMode == "hidden_terminal";
            testCase.verifyEqual( ...
                failureSummary.Count(hiddenRow), 1);
            testCase.verifyEqual( ...
                failureSummary.CompositionRate(hiddenRow), 1);
            testCase.verifyEqual( ...
                failureSummary.IncidenceRate(hiddenRow), 0.5, ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                failureSummary. ...
                    StatusEffectActiveTransmitterCount(hiddenRow), ...
                1);
            testCase.verifyEqual( ...
                failureSummary. ...
                    StatusEffectActiveReceiverCount(hiddenRow), ...
                0);
            testCase.verifyEqual( ...
                failureSummary. ...
                    EitherEndpointStatusEffectActiveCount(hiddenRow), ...
                1);
            shadowManifest = readtable( ...
                fullfile( ...
                    runDirectory, ...
                    "exposed_reuse_shadow_manifest.csv"), ...
                TextType="string");
            testCase.verifyEqual(height(shadowManifest), 1);
            testCase.verifyEqual( ...
                shadowManifest.FirstUeId, "V1");
            testCase.verifyEqual( ...
                shadowManifest.SecondUeId, "V3");
            testCase.verifyEqual( ...
                shadowManifest.SourceRunId, ...
                "seed-7/false-exit");
            testCase.verifyEqual( ...
                shadowManifest.EvaluationHorizonSeconds, 0.1);

            lifecycleEvents = readtable( ...
                fullfile( ...
                    runDirectory, ...
                    "position_error_lifecycle_events.csv"), ...
                TextType="string");
            testCase.verifyEqual(height(lifecycleEvents), 3);
            v1Event = lifecycleEvents.VehicleId == "V1";
            testCase.verifyEqual(nnz(v1Event), 2);
            entryEvent = v1Event & ...
                logical(lifecycleEvents.ActiveSegmentEntered);
            rightCensorEvent = v1Event & ...
                logical(lifecycleEvents.RightCensoredAtEnd);
            testCase.verifyTrue(logical( ...
                lifecycleEvents.SelectionOccurred(entryEvent)));
            testCase.verifyTrue(logical( ...
                lifecycleEvents.LeftCensoredAtStart(entryEvent)));
            testCase.verifyEqual( ...
                lifecycleEvents.StatusEffectType(entryEvent), ...
                "v2xsim.positioning." + ...
                "IsotropicGaussianPositionErrorStatusEffect");
            testCase.verifyEqual(nnz(rightCensorEvent), 1);
            testCase.verifyEqual( ...
                lifecycleEvents.LifecycleEvent(rightCensorEvent), ...
                "RightCensoredAtEnd");
            testCase.verifyFalse(logical( ...
                lifecycleEvents.ActiveSegmentExited( ...
                    rightCensorEvent)));

            perVehicle = readtable( ...
                fullfile(runDirectory, "per_vehicle_prr.csv"), ...
                TextType="string");
            statusEffectActiveTransmitter = ...
                perVehicle.VehicleUeId == "V1" & ...
                perVehicle.Perspective == "transmitter" & ...
                perVehicle.ExposureState == "active";
            testCase.verifyEqual( ...
                nnz(statusEffectActiveTransmitter), 1);
            testCase.verifyEqual( ...
                perVehicle.DeliveryPrrAuc( ...
                    statusEffectActiveTransmitter), ...
                0.75, AbsTol=1e-12);
            testCase.verifyEqual( ...
                perVehicle. ...
                    EverSelectedForPositionError( ...
                        statusEffectActiveTransmitter), 1);
            testCase.verifyEqual( ...
                perVehicle.StatusEffectEpisodeCount( ...
                    statusEffectActiveTransmitter), 1);
        end

        function sparseCompatibilityRowsDoNotImplyRates(testCase)
            fixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            runDirectory = string(fixture.Folder);
            writelines( ...
                "{""SchemaVersion"":2}", fullfile(runDirectory, ...
                    "simulation_summary.json"));
            writetable( ...
                createPositionRows(), fullfile(runDirectory, ...
                    "position_error_trace_000001.csv"));
            writetable( ...
                createPacketFates(), fullfile(runDirectory, ...
                    "packet_fates_000001.csv"));
            allocation = table( ...
                0.25, 0.75, 0.5, ...
                VariableNames=[ ...
                    "ResourcePairGraphXorRate", ...
                    "ResourcePairGraphJaccard", ...
                    "ExactDecisionDisagreementRate"]);
            writetable( ...
                allocation, fullfile(runDirectory, ...
                    "controller_allocation_summary.csv"));
            reuseCandidates = table( ...
                [1; 1; 2], ...
                ["harmful_reuse"; "missed_reuse"; ...
                    "harmful_reuse"], ...
                VariableNames=[ ...
                    "AllocationEpoch", "CandidateType"]);
            writetable( ...
                reuseCandidates, fullfile(runDirectory, ...
                    "controller_reuse_candidate.csv"));

            summary = ...
                v2xsimregression.positionerror.summarizeRampRun( ...
                    runDirectory, 50, 25);

            testCase.verifyEqual( ...
                summary.HarmfulReuseCandidateCount, 2);
            testCase.verifyEqual( ...
                summary.MissedReuseCandidateCount, 1);
            testCase.verifyTrue(isnan( ...
                summary.MeanHarmfulReuseCandidateRate));
            testCase.verifyTrue(isnan( ...
                summary.MeanMissedReuseCandidateRate));
            testCase.verifyEqual( ...
                summary.FailureClassificationStatus, ...
                "IncompleteAllocatorEvidence");
            testCase.verifyFalse( ...
                summary.FailureAllocatorEvidenceAvailable);
            testCase.verifyTrue(isnan( ...
                summary.HiddenTerminalCount));
            testCase.verifyTrue(isnan( ...
                summary.HiddenTerminalCompositionRate));
            testCase.verifyEqual( ...
                summary.HiddenTerminalCompositionRateStatus, ...
                "NotAnalyzableMissingAllocatorEvidence");
            testCase.verifyEqual( ...
                summary.FailureUnclassifiedErrorCount, 1);
        end

        function streamsChunksWithEagerEquivalentVehicleMetrics( ...
                testCase)
            singleFixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            splitFixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            singleDirectory = string(singleFixture.Folder);
            splitDirectory = string(splitFixture.Folder);
            positionRows = createTemporalPositionRows();
            fates = createBoundaryPacketFates();
            for directory = [singleDirectory, splitDirectory]
                writelines( ...
                    "{""SchemaVersion"":2}", fullfile(directory, ...
                        "simulation_summary.json"));
                writetable( ...
                    positionRows, fullfile(directory, ...
                        "position_error_trace_000001.csv"));
            end
            writetable( ...
                fates, fullfile(singleDirectory, ...
                    "packet_fates_000001.csv"));
            writetable( ...
                fates(1, :), fullfile(splitDirectory, ...
                    "packet_fates_000001.csv"));
            writetable( ...
                fates(2:end, :), fullfile(splitDirectory, ...
                    "packet_fates_000002.csv"));

            singleSummary = ...
                v2xsimregression.positionerror.summarizeRampRun( ...
                    singleDirectory, 50, 25);
            splitSummary = ...
                v2xsimregression.positionerror.summarizeRampRun( ...
                    splitDirectory, 50, 25);

            comparedFields = [ ...
                "TerminalPacketFateCount", "CorrectCount", ...
                "ErrorCount", "BlockedCount", "DeliveryPrrAuc", ...
                "RadioPrrAuc", ...
                "StatusEffectActiveTransmitterDeliveryPrrAuc", ...
                "MainlineTransmitterDeliveryPrrAuc", ...
                "RampTransmitterDeliveryPrrAuc"];
            for fieldName = comparedFields
                testCase.verifyEqual( ...
                    singleSummary.(fieldName), ...
                    splitSummary.(fieldName), ...
                    AbsTol=1e-12);
            end
            testCase.verifyEqual( ...
                singleSummary.TerminalPacketFateCount, 3);
            testCase.verifyEqual(singleSummary.CorrectCount, 1);
            testCase.verifyEqual(singleSummary.ErrorCount, 1);
            testCase.verifyEqual(singleSummary.BlockedCount, 1);
            testCase.verifyEqual( ...
                singleSummary.DeliveryPrrAuc, 0.75, ...
                AbsTol=1e-12);

            singleVehicle = readtable( ...
                fullfile(singleDirectory, "per_vehicle_prr.csv"), ...
                TextType="string");
            splitVehicle = readtable( ...
                fullfile(splitDirectory, "per_vehicle_prr.csv"), ...
                TextType="string");
            testCase.verifyEqual(singleVehicle, splitVehicle);

            expectedAll = ...
                v2xsim.analysis.perVehiclePacketReceptionMetrics( ...
                    fates, [25; 50]);
            actualAll = singleVehicle( ...
                singleVehicle.ExposureState == "all", ...
                expectedAll.Properties.VariableNames);
            testCase.verifyEqual(actualAll, expectedAll);
            activeTransmitter = ...
                singleVehicle.VehicleUeId == "V1" & ...
                singleVehicle.Perspective == "transmitter" & ...
                singleVehicle.ExposureState == "active";
            inactiveTransmitter = ...
                singleVehicle.VehicleUeId == "V1" & ...
                singleVehicle.Perspective == "transmitter" & ...
                singleVehicle.ExposureState == "inactive";
            testCase.verifyEqual( ...
                singleVehicle.ErrorCount(activeTransmitter), 1);
            testCase.verifyEqual( ...
                singleVehicle.CorrectCount(inactiveTransmitter), 1);
        end

        function multiModuleActivityUsesAnyActiveModuleAtTime( ...
                testCase)
            fixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            runDirectory = string(fixture.Folder);
            writelines( ...
                "{""SchemaVersion"":2}", fullfile(runDirectory, ...
                    "simulation_summary.json"));
            firstModule = createPositionRows();
            secondModule = firstModule;
            secondModule.ModuleIndex(:) = 2;
            secondModule.ModuleType(:) = ...
                "v2xsim.positioning.PositionDelayError";
            secondModule.StatusEffectType(:) = "";
            secondModule.IsEvaluated(:) = false;
            secondModule.EvaluationOccurred(:) = false;
            secondModule.SelectionOccurred(:) = false;
            secondModule.IsSelected(:) = false;
            secondModule.ActiveSegmentEntered(:) = false;
            secondModule.IsActive(:) = false;
            secondModule.EpisodeId(:) = NaN;
            secondModule.LeftCensoredAtStart(:) = false;
            secondModule.LifecycleEvent(:) = "";
            writetable( ...
                [firstModule; secondModule], ...
                fullfile(runDirectory, ...
                    "position_error_trace_000001.csv"));
            writetable( ...
                createPacketFates(), fullfile(runDirectory, ...
                    "packet_fates_000001.csv"));

            summary = ...
                v2xsimregression.positionerror.summarizeRampRun( ...
                    runDirectory, 50, 25);

            testCase.verifyEqual( ...
                summary.StatusEffectActiveTransmitterDeliveryPrrAuc, ...
                0.75, AbsTol=1e-12);
            perVehicle = readtable( ...
                fullfile(runDirectory, "per_vehicle_prr.csv"), ...
                TextType="string");
            statusEffectActiveTransmitter = ...
                perVehicle.VehicleUeId == "V1" & ...
                perVehicle.Perspective == "transmitter" & ...
                perVehicle.ExposureState == "active";
            testCase.verifyEqual( ...
                nnz(statusEffectActiveTransmitter), 1);
            testCase.verifyEqual( ...
                perVehicle.TotalCount( ...
                    statusEffectActiveTransmitter), 2);
        end

        function headerOnlyCandidatesPreserveAllocatorAvailability( ...
                testCase)
            fixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            runDirectory = string(fixture.Folder);
            writelines( ...
                "{""SchemaVersion"":2}", fullfile(runDirectory, ...
                    "simulation_summary.json"));
            writetable( ...
                createPositionRows(), fullfile(runDirectory, ...
                    "position_error_trace_000001.csv"));
            fates = createPacketFates();
            writetable( ...
                fates(2, :), fullfile(runDirectory, ...
                    "packet_fates_000001.csv"));
            writetable( ...
                createReuseCandidates(false), ...
                fullfile(runDirectory, ...
                    "controller_reuse_candidate.csv"));

            summary = ...
                v2xsimregression.positionerror.summarizeRampRun( ...
                    runDirectory, 50, 25);

            testCase.verifyTrue( ...
                summary.FailureAllocatorEvidenceAvailable);
            testCase.verifyEqual( ...
                summary.FailureClassificationStatus, ...
                "NoInterferenceEvidence");
            testCase.verifyTrue(isnan( ...
                summary.HiddenTerminalCompositionRate));
            testCase.verifyTrue(isnan( ...
                summary.CochannelInterferenceFailureIncidenceRate));
            testCase.verifyEqual( ...
                summary.FailureModeCompositionRateStatus, ...
                "NotAnalyzableIncompleteInterferenceEvidence");
            testCase.verifyEqual( ...
                summary.HiddenTerminalCompositionRateStatus, ...
                "NotAnalyzableIncompleteInterferenceEvidence");
            events = readtable( ...
                fullfile(runDirectory, "failure_mode_events.csv"), ...
                TextType="string");
            testCase.verifyTrue(logical( ...
                events.AllocatorEvidenceAvailable));
            modeSummary = readtable( ...
                fullfile(runDirectory, "failure_mode_summary.csv"), ...
                TextType="string");
            testCase.verifyTrue(all(logical( ...
                modeSummary.AllocatorEvidenceAvailable)));
        end

        function hiddenTotalsUseCausalFlagAcrossAmbiguousMode( ...
                testCase)
            fixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            runDirectory = string(fixture.Folder);
            prepareErrorOnlyRun(runDirectory);
            [attempts, counterfactuals] = ...
                createMultipleSufficientEvidence();
            writetable( ...
                attempts, fullfile(runDirectory, ...
                    "interference_attempts_000001.csv"));
            writetable( ...
                counterfactuals, fullfile(runDirectory, ...
                    "interference_counterfactuals_000001.csv"));
            candidates = createReuseCandidates(false);
            candidates(1, :) = createReuseCandidates(true);
            writetable( ...
                candidates, fullfile(runDirectory, ...
                    "controller_reuse_candidate.csv"));

            summary = ...
                v2xsimregression.positionerror.summarizeRampRun( ...
                    runDirectory, 50, 25);

            testCase.verifyEqual(summary.HiddenTerminalCount, 1);
            events = readtable( ...
                fullfile(runDirectory, "failure_mode_events.csv"), ...
                TextType="string");
            testCase.verifyEqual( ...
                events.FailureMode, ...
                "multiple_sufficient_interferers");
            testCase.verifyTrue(logical(events.IsHiddenTerminal));
            modes = readtable( ...
                fullfile(runDirectory, "failure_mode_summary.csv"), ...
                TextType="string");
            hiddenMode = modes.FailureMode == "hidden_terminal";
            multipleMode = modes.FailureMode == ...
                "multiple_sufficient_interferers";
            testCase.verifyEqual(modes.Count(hiddenMode), 1);
            testCase.verifyEqual(modes.Count(multipleMode), 1);
            testCase.verifyEqual( ...
                modes.CompositionRate(hiddenMode), 1);
            testCase.verifyEqual( ...
                modes.CompositionRate(multipleMode), 1);
        end

        function joinedEvidenceIsSparseButJointEventIsRetained( ...
                testCase)
            fixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            runDirectory = string(fixture.Folder);
            prepareErrorOnlyRun(runDirectory);
            [attempts, counterfactuals] = createJointEvidence();
            writetable( ...
                attempts, fullfile(runDirectory, ...
                    "interference_attempts_000001.csv"));
            writetable( ...
                counterfactuals, fullfile(runDirectory, ...
                    "interference_counterfactuals_000001.csv"));
            writetable( ...
                createReuseCandidates(false), ...
                fullfile(runDirectory, ...
                    "controller_reuse_candidate.csv"));

            summary = ...
                v2xsimregression.positionerror.summarizeRampRun( ...
                    runDirectory, 50, 25);

            testCase.verifyEqual( ...
                summary.JointInterferenceFailureCount, 1);
            events = readtable( ...
                fullfile(runDirectory, "failure_mode_events.csv"), ...
                TextType="string");
            testCase.verifyEqual( ...
                events.FailureMode, "joint_interference");
            joinedEvidence = readtable( ...
                fullfile(runDirectory, "failure_mode_evidence.csv"), ...
                TextType="string");
            testCase.verifyEqual(height(joinedEvidence), 0);
            testCase.verifyGreaterThan(width(joinedEvidence), 0);
        end

        function shadowSourceFallbackKeepsSeedTreatmentPath( ...
                testCase)
            fixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            runDirectory = fullfile( ...
                string(fixture.Folder), ...
                "seed-11", "false-merge");
            mkdir(runDirectory);
            writelines( ...
                "{""SchemaVersion"":2}", fullfile(runDirectory, ...
                    "simulation_summary.json"));
            writetable( ...
                createPositionRows(), fullfile(runDirectory, ...
                    "position_error_trace_000001.csv"));
            candidate = createReuseCandidates(true);
            candidate.SecondUeId(:) = "V3";
            candidate.CandidateType(:) = "missed_reuse";
            candidate.LiveSameResource(:) = false;
            candidate.OracleSameResource(:) = true;
            candidate.LiveResourceRelation(:) = "separate_time";
            candidate.OracleResourceRelation(:) = "cochannel";
            candidate.IsHarmfulInterferenceOverlap(:) = false;
            candidate.IsMissedInterferenceOverlap(:) = true;
            candidate.LiveSecondResourceId(:) = 2;
            candidate.OracleFirstResourceId(:) = 3;
            candidate.OracleSecondResourceId(:) = 3;
            writetable( ...
                candidate, fullfile(runDirectory, ...
                    "controller_reuse_candidate.csv"));

            v2xsimregression.positionerror.summarizeRampRun( ...
                runDirectory, 50, 25);

            manifest = readtable( ...
                fullfile( ...
                    runDirectory, ...
                    "exposed_reuse_shadow_manifest.csv"), ...
                TextType="string");
            testCase.verifyEqual( ...
                manifest.SourceRunId, ...
                string(fullfile("seed-11", "false-merge")));
        end

        function noErrorsHaveZeroIncidenceButNoComposition( ...
                testCase)
            fixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            runDirectory = string(fixture.Folder);
            writelines( ...
                "{""SchemaVersion"":2}", fullfile(runDirectory, ...
                    "simulation_summary.json"));
            writetable( ...
                createPositionRows(), fullfile(runDirectory, ...
                    "position_error_trace_000001.csv"));
            fates = createPacketFates();
            writetable( ...
                fates(1, :), fullfile(runDirectory, ...
                    "packet_fates_000001.csv"));
            writetable( ...
                createReuseCandidates(false), ...
                fullfile(runDirectory, ...
                    "controller_reuse_candidate.csv"));

            summary = ...
                v2xsimregression.positionerror.summarizeRampRun( ...
                    runDirectory, 50, 25);

            testCase.verifyEqual( ...
                summary.FailureClassificationStatus, "NoErrors");
            testCase.verifyEqual(summary.HiddenTerminalCount, 0);
            testCase.verifyTrue(isnan( ...
                summary.HiddenTerminalCompositionRate));
            testCase.verifyEqual( ...
                summary.HiddenTerminalCompositionRateStatus, ...
                "NotAnalyzableNoTerminalErrors");
            testCase.verifyEqual( ...
                summary.HiddenTerminalIncidenceRate, 0);
            testCase.verifyEqual( ...
                summary.HiddenTerminalIncidenceRateStatus, ...
                "Analyzable");
            testCase.verifyEqual( ...
                summary.CochannelInterferenceFailureIncidenceRate, 0);
            testCase.verifyEqual(summary.TerminalRadioFateCount, 1);
        end

        function missingAllocatorOnlyGatesHiddenRates(testCase)
            fixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            runDirectory = string(fixture.Folder);
            prepareErrorOnlyRun(runDirectory);
            [attempts, counterfactuals] = ...
                createInterferenceEvidence();
            writetable( ...
                attempts, fullfile(runDirectory, ...
                    "interference_attempts_000001.csv"));
            writetable( ...
                counterfactuals, fullfile(runDirectory, ...
                    "interference_counterfactuals_000001.csv"));

            summary = ...
                v2xsimregression.positionerror.summarizeRampRun( ...
                    runDirectory, 50, 25);

            testCase.verifyEqual( ...
                summary.FailureClassificationStatus, ...
                "IncompleteAllocatorEvidence");
            testCase.verifyEqual( ...
                summary.DetectedHiddenTerminalCount, 0);
            testCase.verifyTrue(isnan(summary.HiddenTerminalCount));
            testCase.verifyTrue(isnan( ...
                summary.HiddenTerminalIncidenceRate));
            testCase.verifyEqual( ...
                summary.HiddenTerminalIncidenceRateStatus, ...
                "NotAnalyzableMissingAllocatorEvidence");
            testCase.verifyEqual( ...
                summary.CochannelInterferenceFailureCount, 1);
            testCase.verifyEqual( ...
                summary.CochannelInterferenceFailureCompositionRate, 1);
            testCase.verifyEqual( ...
                summary.CochannelInterferenceFailureIncidenceRate, 1);
            testCase.verifyEqual( ...
                summary.FailureModeIncidenceRateStatus, ...
                "Analyzable");
        end

        function rejectsPreV2CompletionSummary(testCase)
            fixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            runDirectory = string(fixture.Folder);
            writelines( ...
                "{""SchemaVersion"":1}", ...
                fullfile(runDirectory, "simulation_summary.json"));

            testCase.verifyError( ...
                @() v2xsimregression.positionerror. ...
                    summarizeRampRun(runDirectory, 50, 25), ...
                "v2xsimregression:positionerror:" + ...
                    "UnsupportedSummarySchema");
        end

        function normallyExitedEpisodeIsNotRightCensored(testCase)
            fixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            runDirectory = string(fixture.Folder);
            rows = createNormallyExitedPositionRows();
            prepareLifecycleOnlyRun(runDirectory, rows);

            summary = ...
                v2xsimregression.positionerror.summarizeRampRun( ...
                    runDirectory, 50, 25);

            testCase.verifyEqual( ...
                summary.StatusEffectEpisodeCount, 1);
            testCase.verifyEqual( ...
                summary.LeftCensoredEpisodeCount, 1);
            testCase.verifyEqual( ...
                summary.RightCensoredEpisodeCount, 0);
            events = readtable( ...
                fullfile( ...
                    runDirectory, ...
                    "position_error_lifecycle_events.csv"), ...
                TextType="string");
            testCase.verifyFalse(any(logical( ...
                events.RightCensoredAtEnd)));
            exited = logical(events.ActiveSegmentExited);
            testCase.verifyEqual(nnz(exited), 1);
            testCase.verifyEqual( ...
                events.LifecycleEvent(exited), ...
                "ActiveSegmentExited");
        end

        function censorCountsDistinguishModulesWithSameEpisodeId( ...
                testCase)
            fixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            runDirectory = string(fixture.Folder);
            firstModule = createPositionRows();
            secondModule = firstModule;
            secondModule.ModuleIndex(:) = 2;
            secondModule.ModuleType(:) = ...
                "v2xsim.positioning." + ...
                "PositionErrorStatusEffectInflictor";
            secondModule.StatusEffectType(:) = ...
                "v2xsim.positioning.SecondTestStatusEffect";
            prepareLifecycleOnlyRun( ...
                runDirectory, [firstModule; secondModule]);

            summary = ...
                v2xsimregression.positionerror.summarizeRampRun( ...
                    runDirectory, 50, 25);

            testCase.verifyEqual( ...
                summary.StatusEffectEpisodeCount, 2);
            testCase.verifyEqual( ...
                summary.LeftCensoredEpisodeCount, 2);
            testCase.verifyEqual( ...
                summary.RightCensoredEpisodeCount, 2);
            events = readtable( ...
                fullfile( ...
                    runDirectory, ...
                    "position_error_lifecycle_events.csv"), ...
                TextType="string");
            testCase.verifyEqual(nnz(logical( ...
                events.RightCensoredAtEnd)), 2);
        end

        function rejectsTraceWithoutConcreteStatusEffectType(testCase)
            fixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            runDirectory = string(fixture.Folder);
            positionRows = createPositionRows();
            positionRows.StatusEffectType = [];
            prepareLifecycleOnlyRun(runDirectory, positionRows);

            testCase.verifyError( ...
                @() v2xsimregression.positionerror. ...
                    summarizeRampRun(runDirectory, 50, 25), ...
                "v2xsimregression:positionerror:" + ...
                "InvalidPositionTrace");
        end
    end
end

function [attempts, counterfactuals] = createInterferenceEvidence()
attempts = v2xsim.analysis.emptyInterferenceAttemptTrace();
attempts(1, :) = { ...
    0.05, "LTE", 1, "V1", 3, "V3", ...
    99, false, 0, 1, 1, 1, 0, ...
    "error", -5, 0, 2, 1, true};
counterfactuals = ...
    v2xsim.analysis.emptyInterferenceCounterfactualTrace();
counterfactuals(1, :) = { ...
    0.05, "LTE", 1, "V1", 3, "V3", ...
    99, false, 0, 1, 1, 1, 0, ...
    2, "V2", "V1", "V2", 1, 1, ...
    "cochannel", 3, -5, 0, 2, 2, true};
end

function rows = createPositionRows()
inputPositions = table( ...
    [0; 10], [0; 0], ...
    VariableNames=["X", "Y"], ...
    RowNames=["V1", "V2"]);
outputPositions = table( ...
    [3; 10], [4; 0], ...
    VariableNames=["X", "Y"], ...
    RowNames=["V1", "V2"]);
lifecycle = struct( ...
    "IsEvaluated", [true; true], ...
    "EvaluationOccurred", [true; true], ...
    "SelectionOccurred", [true; false], ...
    "IsSelected", [true; false], ...
    "ActiveSegmentEntered", [true; false], ...
    "IsActive", [true; false], ...
    "ActiveSegmentExited", [false; false], ...
    "ResetOccurred", [false; false], ...
    "EpisodeId", [1; NaN], ...
    "LeftCensoredAtStart", [true; false]);
rows = v2xsim.positioning.diagnostics.createRows( ...
    inputPositions, outputPositions, 0, ...
    "v2xsim.positioning.PositionErrorStatusEffectInflictor", ...
    lifecycle, ...
    "v2xsim.positioning." + ...
        "IsotropicGaussianPositionErrorStatusEffect");
rows.TrueRoute = ["Merge"; "Adjacent"];
end

function fates = createPacketFates()
fates = v2xsim.analysis.emptyTerminalPacketFateTable();
fates(1, :) = { ...
    0.05, "LTE", 1, "V1", 2, "V2", ...
    1, 0, 1, "correct", 1, 1, 10, 1, 1, 1, 0};
fates(2, :) = { ...
    0.05, "LTE", 1, "V1", 3, "V3", ...
    1, 0, 1, "error", 1, 1, 30, 1, 1, 1, 0};
fates(3, :) = { ...
    0.05, "LTE", 1, "V1", 4, "V4", ...
    1, 0, 1, "blocked", 1, 1, 50, 1, 1, 1, 0};
end

function rows = createTemporalPositionRows()
rowsAtZero = createPositionRows();
rowsAtZero.IsEvaluated(:) = false;
rowsAtZero.EvaluationOccurred(:) = false;
rowsAtZero.SelectionOccurred(:) = false;
rowsAtZero.IsSelected(:) = false;
rowsAtZero.ActiveSegmentEntered(:) = false;
rowsAtZero.IsActive(:) = false;
rowsAtZero.EpisodeId(:) = NaN;
rowsAtZero.LifecycleEvent(:) = "";

rowsAtBoundary = rowsAtZero;
rowsAtBoundary.SimulationTimeSeconds(:) = 0.1;
rowsAtBoundary.TrueRoute(1) = "Ramp";
rowsAtBoundary.IsEvaluated(1) = true;
rowsAtBoundary.EvaluationOccurred(1) = true;
rowsAtBoundary.SelectionOccurred(1) = true;
rowsAtBoundary.IsSelected(1) = true;
rowsAtBoundary.ActiveSegmentEntered(1) = true;
rowsAtBoundary.IsActive(1) = true;
rowsAtBoundary.EpisodeId(1) = 1;
rowsAtBoundary.LifecycleEvent(1) = ...
    "Selected|ActiveSegmentEntered";
rows = [rowsAtZero; rowsAtBoundary];
end

function rows = createNormallyExitedPositionRows()
rowsAtStart = createPositionRows();
rowsAtExit = rowsAtStart;
rowsAtExit.SimulationTimeSeconds(:) = 0.1;
rowsAtExit.OutputXMeters = rowsAtExit.InputXMeters;
rowsAtExit.OutputYMeters = rowsAtExit.InputYMeters;
rowsAtExit.DisplacementXMeters(:) = 0;
rowsAtExit.DisplacementYMeters(:) = 0;
rowsAtExit.DisplacementMagnitudeMeters(:) = 0;
rowsAtExit.EvaluationOccurred(:) = false;
rowsAtExit.SelectionOccurred(:) = false;
rowsAtExit.ActiveSegmentEntered(:) = false;
rowsAtExit.LeftCensoredAtStart(:) = false;
rowsAtExit.LifecycleEvent(:) = "";
vehicleOne = rowsAtExit.VehicleId == "V1";
rowsAtExit.IsActive(vehicleOne) = false;
rowsAtExit.ActiveSegmentExited(vehicleOne) = true;
rowsAtExit.LifecycleEvent(vehicleOne) = ...
    "ActiveSegmentExited";
rows = [rowsAtStart; rowsAtExit];
end

function prepareLifecycleOnlyRun(runDirectory, positionRows)
writelines( ...
    "{""SchemaVersion"":2}", fullfile(runDirectory, ...
        "simulation_summary.json"));
writetable( ...
    positionRows, fullfile(runDirectory, ...
        "position_error_trace_000001.csv"));
end

function fates = createBoundaryPacketFates()
fates = v2xsim.analysis.emptyTerminalPacketFateTable();
fates(1, :) = { ...
    0.099, "LTE", 1, "V1", 2, "V2", ...
    1, 0, 1, "correct", 1, 1, 10, 1, 1, 1, 0};
fates(2, :) = { ...
    0.1, "LTE", 1, "V1", 3, "V3", ...
    1, 0, 1, "error", 1, 1, 30, 1, 1, 1, 0};
fates(3, :) = { ...
    0.11, "LTE", 1, "V1", 4, "V4", ...
    1, 0, 1, "blocked", 1, 1, 50, 1, 1, 1, 0};
end

function candidates = createReuseCandidates(includeHarmfulRow)
candidates = table( ...
    0.05, 0, 1, "global", "V1", "V2", ...
    "harmful_reuse", true, false, ...
    "cochannel", "separate_time", true, false, ...
    1, 1, 1, 2, ...
    VariableNames=[ ...
        "SimulationTimeSeconds", ...
        "AllocationEpoch", "AbsoluteSlot", ...
        "NetworkSliceId", "FirstUeId", ...
        "SecondUeId", "CandidateType", ...
        "LiveSameResource", "OracleSameResource", ...
        "LiveResourceRelation", ...
        "OracleResourceRelation", ...
        "IsHarmfulInterferenceOverlap", ...
        "IsMissedInterferenceOverlap", ...
        "LiveFirstResourceId", ...
        "LiveSecondResourceId", ...
        "OracleFirstResourceId", ...
        "OracleSecondResourceId"]);
if ~includeHarmfulRow
    candidates(1, :) = [];
end
end

function prepareErrorOnlyRun(runDirectory)
writelines( ...
    "{""SchemaVersion"":2}", fullfile(runDirectory, ...
        "simulation_summary.json"));
writetable( ...
    createPositionRows(), fullfile(runDirectory, ...
        "position_error_trace_000001.csv"));
fates = createPacketFates();
writetable( ...
    fates(2, :), fullfile(runDirectory, ...
        "packet_fates_000001.csv"));
end

function [attempts, counterfactuals] = ...
        createMultipleSufficientEvidence()
[attempts, counterfactuals] = createInterferenceEvidence();
attempts.InterfererCount(:) = 2;
counterfactuals(2, :) = { ...
    0.05, "LTE", 1, "V1", 3, "V3", ...
    99, false, 0, 1, 1, 1, 0, ...
    4, "V4", "V1", "V4", 2, 2, ...
    "adjacent_channel", 2, -5, 0, 2, 2, true};
end

function [attempts, counterfactuals] = createJointEvidence()
[attempts, counterfactuals] = createMultipleSufficientEvidence();
counterfactuals.SinrWithoutInterfererDb(:) = -1;
end
