function printDebugCumulativeSINR(outParams,time,idTx,pckTxOccurring,IDRxs,cumulativePreable, cumulativeSINR, state, distance,rxOk)
% after each time transmission, print the cumulative SINR of all of the
% receiver

filename = fullfile(outParams.outputFolder,"_DebugCumulative11p.csv");
fid = fopen(filename,'r');
if fid==-1
    fid = fopen(filename,'w');
    fprintf(fid, ...
        ['TimeSeconds,TransmitterVehicleId,TransmittedPacketId,' ...
        'ReceiverVehicleId,CumulativePreambleSinr,' ...
        'CumulativeSinr,ReceiverState,DistanceMeters,' ...
        'ReceptionSuccessful\n']);
end
fclose(fid);

fid = fopen(filename,'a');

for i = 1:length(IDRxs)
    fprintf(fid,'%3.6f,%d,%d,%d,%.2f,%.2f,%d,%.2f,%d\n', ...
        time,idTx,pckTxOccurring,IDRxs(i), ...
        cumulativePreable(IDRxs(i),idTx), ...
        cumulativeSINR(IDRxs(i),idTx),state(IDRxs(i)), ...
        distance(IDRxs(i),idTx),rxOk(i));
end
fclose(fid);
