classdef AfterPositionErrorChainAppliedInvocationTest < ...
        matlab.unittest.TestCase
    %AFTERPOSITIONERRORCHAINAPPLIEDINVOCATIONTEST Tests hook snapshots.

    methods (Test)
        function testRetainsPositionsBeforeAndAfterChain(testCase)
            before = testCase.createPositions(["V1", "V2"]);
            after = before;
            after.X = after.X + 5;

            invocation = v2xsim.hook.invocations. ...
                AfterPositionErrorChainAppliedInvocation( ...
                    before, after);

            testCase.verifyEqual( ...
                invocation.PositionsBeforeErrorChain, before);
            testCase.verifyEqual( ...
                invocation.PositionsAfterErrorChain, after);
        end

        function testRejectsDifferentVehicleSets(testCase)
            before = testCase.createPositions(["V1", "V2"]);
            after = testCase.createPositions(["V1", "V3"]);

            testCase.verifyError( ...
                @() v2xsim.hook.invocations. ...
                AfterPositionErrorChainAppliedInvocation( ...
                    before, after), ...
                "v2xsim:hook:invocations:VehicleSetChanged");
        end

        function testAlignsAfterPositionsByVehicleIdentity(testCase)
            before = testCase.createPositions(["V1", "V2"]);
            after = before;
            after.X = after.X + [10; 20];
            after = after(["V2", "V1"], :);

            invocation = v2xsim.hook.invocations. ...
                AfterPositionErrorChainAppliedInvocation( ...
                    before, after);

            testCase.verifyEqual( ...
                invocation.PositionsAfterErrorChain, ...
                after(["V1", "V2"], :));
            testCase.verifyEqual( ...
                invocation.PositionsAfterErrorChain.X - ...
                invocation.PositionsBeforeErrorChain.X, ...
                [10; 20]);
        end

        function testPointUsesPointContract(testCase)
            point = v2xsim.hook.points. ...
                AfterPositionErrorChainApplied;
            positions = testCase.createPositions(["V1", "V2"]);
            invocation = v2xsim.hook.invocations. ...
                AfterPositionErrorChainAppliedInvocation( ...
                    positions, positions);

            testCase.verifyInstanceOf( ...
                point, "v2xsim.hook.point.Point");
            testCase.verifyEqual( ...
                point.invocationType(), ...
                ?v2xsim.hook.invocations. ...
                AfterPositionErrorChainAppliedInvocation);
            testCase.verifyTrue( ...
                point.acceptsInvocation(invocation));
        end

        function testRetainsValidatedModuleDiagnostics(testCase)
            before = testCase.createPositions(["V1", "V2"]);
            after = before;
            after.X = after.X + 1;
            diagnostics = ...
                v2xsim.positioning.diagnostics.createRows( ...
                    before, after, 0.5, ...
                    "v2xsim.positioning.TestModule");

            invocation = v2xsim.hook.invocations. ...
                AfterPositionErrorChainAppliedInvocation( ...
                    before, after, 0.5, diagnostics);

            testCase.verifyEqual( ...
                invocation.ModuleDiagnostics, diagnostics);
        end

        function testRejectsDiagnosticTimeMismatch(testCase)
            positions = testCase.createPositions(["V1", "V2"]);
            diagnostics = ...
                v2xsim.positioning.diagnostics.createRows( ...
                    positions, positions, 0.4, ...
                    "v2xsim.positioning.TestModule");

            testCase.verifyError( ...
                @() v2xsim.hook.invocations. ...
                    AfterPositionErrorChainAppliedInvocation( ...
                        positions, positions, 0.5, diagnostics), ...
                "v2xsim:hook:invocations:DiagnosticTimeMismatch");
        end
    end

    methods (Access = private)
        function positions = createPositions(~, vehicleIds)
            positions = table( ...
                [1; 2], [3; 4], ...
                VariableNames=["X", "Y"], ...
                RowNames=vehicleIds);
        end
    end
end
