classdef AfterPacketFatesDeterminedInvocationTest < ...
        matlab.unittest.TestCase
    methods (Test)
        function onAirProvenanceIsLogicalAndIndependentOfLinks(testCase)
            import v2xsimtest.fixtures.ResourceUsageEvents
            event = ResourceUsageEvents.transmission(0.1);
            testCase.verifyTrue(event.Transmitters.IsOnAirObservation);
            testCase.verifyEmpty(event.Links);
            event = ResourceUsageEvents.transmission(0.2,"alpha",1,1,4,false,"blocked");
            testCase.verifyFalse(event.Transmitters.IsOnAirObservation);
            testCase.verifyEqual(event.Transmitters.AttemptNumber,1);
        end

        function rejectsMalformedOnAirProvenance(testCase)
            import v2xsimtest.fixtures.ResourceUsageEvents
            invalid = {1,0,nan,"true",{true},[true false]};
            for index = 1:numel(invalid)
                testCase.verifyError(@() ResourceUsageEvents.transmission( ...
                    0.1,"alpha",1,1,4,invalid{index}), ...
                    "v2xsim:hook:invocations:InvalidTransmitters");
            end
        end

        function completionRequiresLogicalFlagAndExplicitIdentity(testCase)
            tx = table(1,1,1,0,VariableNames=["TransmitterId","Channel","PacketType","GenerationTimeSeconds"]);
            links = table(1,2,10,"correct",VariableNames=["TransmitterId","ReceiverId","DistanceMeters","Outcome"]);
            tx.IsPacketComplete = true;
            testCase.verifyError(@() v2xsim.hook.invocations.AfterPacketFatesDeterminedInvocation( ...
                1,"LTE",2,100,tx,links),"v2xsim:hook:invocations:InvalidTransmitters");
            tx.PacketSequence = 1;
            result = v2xsim.hook.invocations.AfterPacketFatesDeterminedInvocation(1,"LTE",2,100,tx,links);
            testCase.verifyTrue(result.Transmitters.IsPacketComplete);
            tx.IsPacketComplete = 1;
            testCase.verifyError(@() v2xsim.hook.invocations.AfterPacketFatesDeterminedInvocation( ...
                1,"LTE",2,100,tx,links),"v2xsim:hook:invocations:InvalidTransmitters");
        end

        function acceptsStableIdentityAndPacketMetadata(testCase)
            transmitters = table( ...
                2,"beta",1,1,0.1,nan,2,7,4,3,9, ...
                VariableNames=[ ...
                    "TransmitterId","TransmitterUeId", ...
                    "Channel","PacketType","GenerationTimeSeconds", ...
                    "PacketSequence","AttemptNumber","ResourceId", ...
                    "TimeResourceId","FrequencyResourceId", ...
                    "AllocationEpoch"]);
            links = table( ...
                2,"beta",3,"gamma",25,"error",true, ...
                VariableNames=[ ...
                    "TransmitterId","TransmitterUeId", ...
                    "ReceiverId","ReceiverUeId", ...
                    "DistanceMeters","Outcome","IsTerminal"]);

            invocation = v2xsim.hook.invocations. ...
                AfterPacketFatesDeterminedInvocation( ...
                    0.2,"LTE",3,100,transmitters,links);

            testCase.verifyEqual( ...
                invocation.Transmitters.TransmitterUeId,"beta");
            testCase.verifyEqual( ...
                invocation.Transmitters.AllocationEpoch,9);
            testCase.verifyEqual( ...
                invocation.Links.ReceiverUeId,"gamma");
            testCase.verifyTrue(invocation.Links.IsTerminal);
        end

        function rejectsTerminalFlagThatConflictsWithOutcome(testCase)
            transmitters = table( ...
                1,1,1,0.1, ...
                VariableNames=[ ...
                    "TransmitterId","Channel","PacketType", ...
                    "GenerationTimeSeconds"]);
            links = table( ...
                1,2,10,"none",true, ...
                VariableNames=[ ...
                    "TransmitterId","ReceiverId", ...
                    "DistanceMeters","Outcome","IsTerminal"]);

            testCase.verifyError( ...
                @() v2xsim.hook.invocations. ...
                    AfterPacketFatesDeterminedInvocation( ...
                        0.2,"11p",2,100,transmitters,links), ...
                "v2xsim:hook:invocations:InvalidLinks");
        end
    end
end
