classdef AfterVehicleKinematicsUpdatedInvocationTest < ...
        matlab.unittest.TestCase
    %AFTERVEHICLEKINEMATICSUPDATEDINVOCATIONTEST Tests snapshots.

    methods (Test)
        function retainsCanonicalKinematicsAndUnavailableValues(testCase)
            vehicleKinematics = testCase.kinematicsTable( ...
                [ ...
                    1, 2, 3, 4, 5, 6; ...
                    7, 8, NaN, NaN, NaN, NaN], ...
                ["V2";"V1"]);

            invocation = v2xsim.hook.invocations. ...
                AfterVehicleKinematicsUpdatedInvocation( ...
                    0.25,vehicleKinematics);

            testCase.verifyEqual( ...
                invocation.SimulationTimeSeconds,0.25);
            testCase.verifyTrue(isequaln( ...
                invocation.VehicleKinematics,vehicleKinematics));
        end

        function acceptsEmptyCanonicalSnapshot(testCase)
            vehicleKinematics = testCase.kinematicsTable( ...
                zeros(0,6),strings(0,1));

            invocation = v2xsim.hook.invocations. ...
                AfterVehicleKinematicsUpdatedInvocation( ...
                    0.5,vehicleKinematics);

            testCase.verifyEqual( ...
                invocation.VehicleKinematics,vehicleKinematics);
        end

        function rejectsMissingCanonicalVariable(testCase)
            vehicleKinematics = testCase.kinematicsTable( ...
                ones(1,6),"V1");
            vehicleKinematics.aY = [];

            testCase.verifyError( ...
                @() v2xsim.hook.invocations. ...
                    AfterVehicleKinematicsUpdatedInvocation( ...
                        0.5,vehicleKinematics), ...
                "v2xsim:hook:invocations:" + ...
                    "InvalidVehicleKinematicsVariables");
        end

        function rejectsAdditionalSpeedVariable(testCase)
            vehicleKinematics = testCase.kinematicsTable( ...
                ones(1,6),"V1");
            vehicleKinematics.SpeedMetersPerSecond = 10;

            testCase.verifyError( ...
                @() v2xsim.hook.invocations. ...
                    AfterVehicleKinematicsUpdatedInvocation( ...
                        0.5,vehicleKinematics), ...
                "v2xsim:hook:invocations:" + ...
                    "InvalidVehicleKinematicsVariables");
        end

        function rejectsNonemptySnapshotWithoutVehicleIds(testCase)
            vehicleKinematics = array2table( ...
                ones(1,6), ...
                VariableNames=["X","Y","vX","vY","aX","aY"]);

            testCase.verifyError( ...
                @() v2xsim.hook.invocations. ...
                    AfterVehicleKinematicsUpdatedInvocation( ...
                        0.5,vehicleKinematics), ...
                "v2xsim:hook:invocations:MissingVehicleIds");
        end

        function pointDeclaresKinematicsInvocation(testCase)
            point = v2xsim.hook.points. ...
                AfterVehicleKinematicsUpdated;
            vehicleKinematics = testCase.kinematicsTable( ...
                ones(1,6),"V1");
            invocation = v2xsim.hook.invocations. ...
                AfterVehicleKinematicsUpdatedInvocation( ...
                    0.5,vehicleKinematics);

            testCase.verifyEqual( ...
                point.invocationType(), ...
                ?v2xsim.hook.invocations. ...
                AfterVehicleKinematicsUpdatedInvocation);
            testCase.verifyTrue(point.acceptsInvocation(invocation));
        end
    end

    methods (Access = private)
        function vehicleKinematics = kinematicsTable( ...
                ~,values,vehicleIds)
            vehicleKinematics = array2table( ...
                values, ...
                VariableNames=["X","Y","vX","vY","aX","aY"]);
            if ~isempty(vehicleIds)
                vehicleKinematics.Properties.RowNames = ...
                    cellstr(vehicleIds);
            end
        end
    end
end
