classdef points < v2xsim.hook.point.Point
    %POINTS Logical locations where simulator hooks may be invoked.

    enumeration
        AfterVehicleKinematicsUpdated
        AfterPositionErrorChainApplied
        AfterNeighborGraphUpdated
        AfterResourceAllocationDecision
        AfterPacketFatesDetermined
        AfterInterferenceEvidenceDetermined
        AfterChannelBusyRatioSampled
    end

    methods (Access = protected)
        function invocationType = declaredInvocationType(obj)
            arguments (Input)
                obj (1, 1)
            end
            arguments (Output)
                invocationType (1, 1) matlab.metadata.Class
            end

            switch obj
                case v2xsim.hook.points. ...
                        AfterVehicleKinematicsUpdated
                    invocationType = ...
                        ?v2xsim.hook.invocations. ...
                        AfterVehicleKinematicsUpdatedInvocation;
                case v2xsim.hook.points. ...
                        AfterPositionErrorChainApplied
                    invocationType = ...
                        ?v2xsim.hook.invocations. ...
                        AfterPositionErrorChainAppliedInvocation;
                case v2xsim.hook.points. ...
                        AfterNeighborGraphUpdated
                    invocationType = ...
                        ?v2xsim.hook.invocations. ...
                        AfterNeighborGraphUpdatedInvocation;
                case v2xsim.hook.points. ...
                        AfterResourceAllocationDecision
                    invocationType = ...
                        ?v2xsim.hook.invocations. ...
                        AfterResourceAllocationDecisionInvocation;
                case v2xsim.hook.points. ...
                        AfterPacketFatesDetermined
                    invocationType = ...
                        ?v2xsim.hook.invocations. ...
                        AfterPacketFatesDeterminedInvocation;
                case v2xsim.hook.points. ...
                        AfterInterferenceEvidenceDetermined
                    invocationType = ...
                        ?v2xsim.hook.invocations. ...
                        AfterInterferenceEvidenceDeterminedInvocation;
                case v2xsim.hook.points. ...
                        AfterChannelBusyRatioSampled
                    invocationType = ...
                        ?v2xsim.hook.invocations. ...
                        AfterChannelBusyRatioSampledInvocation;
                otherwise
                    error( ...
                        "v2xsim:hook:UnknownPoint", ...
                        "The Hook Point does not declare an invocation.");
            end
        end
    end
end
