function report = validateV7Wiki(wikiDirectory, options)
%VALIDATEV7WIKI Check the V7 GitHub Wiki's local documentation contracts.
%   REPORT = VALIDATEV7WIKI(WIKIDIRECTORY) verifies that the complete
%   first-release page set exists, local Markdown links resolve, critical
%   public configuration/output tokens remain documented, and canonical
%   example files referenced by the wiki exist in this repository.

arguments (Input)
    wikiDirectory (1,1) string = defaultWikiDirectory()
    options.ThrowOnFailure (1,1) logical = true
end

arguments (Output)
    report (1,1) struct
end

if ~isfolder(wikiDirectory)
    error( ...
        "v2xsimdocs:wiki:DirectoryNotFound", ...
        "The wiki directory does not exist: %s",wikiDirectory);
end

projectRoot = fileparts(fileparts(mfilename("fullpath")));
requiredPages = wikiPageNames();
failureKind = strings(0,1);
source = strings(0,1);
detail = strings(0,1);

for page = requiredPages
    pageFile = fullfile(wikiDirectory,page + ".md");
    if ~isfile(pageFile)
        [failureKind,source,detail] = appendFailure( ...
            failureKind,source,detail, ...
            "MissingPage",page,pageFile);
    end
end

markdownFiles = dir(fullfile(wikiDirectory,"*.md"));
checkedLinkCount = 0;
wikiCorpus = "";
for fileIndex = 1:numel(markdownFiles)
    pageFile = fullfile( ...
        markdownFiles(fileIndex).folder,markdownFiles(fileIndex).name);
    pageText = string(fileread(pageFile));
    wikiCorpus = wikiCorpus + newline + pageText;
    linkTargets = markdownLinkTargets(pageText);
    for linkTarget = linkTargets
        if isExternalOrAnchor(linkTarget)
            continue
        end
        checkedLinkCount = checkedLinkCount + 1;
        localTarget = erase(extractBefore(linkTarget + "#","#"),".md");
        localTarget = replace(localTarget,"%20"," ");
        targetFile = fullfile(wikiDirectory,localTarget + ".md");
        if ~isfile(targetFile)
            [failureKind,source,detail] = appendFailure( ...
                failureKind,source,detail, ...
                "BrokenLink",string(markdownFiles(fileIndex).name), ...
                linkTarget);
        end
    end
end

criticalTokens = wikiCriticalTokens();
for tokenIndex = 1:height(criticalTokens)
    pageFile = fullfile( ...
        wikiDirectory,criticalTokens.Page(tokenIndex) + ".md");
    if ~isfile(pageFile)
        continue
    end
    pageText = string(fileread(pageFile));
    if ~contains(pageText,criticalTokens.Token(tokenIndex))
        [failureKind,source,detail] = appendFailure( ...
            failureKind,source,detail, ...
            "MissingToken",criticalTokens.Page(tokenIndex), ...
            criticalTokens.Token(tokenIndex));
    end
end

schemaPaths = schemaLeafPaths(v2xsim.config.schema(),"");
configurationIndex = string(fileread(fullfile( ...
    wikiDirectory,"Complete-Configuration-Key-Index.md")));
for schemaPath = schemaPaths.'
    if ~contains(configurationIndex,schemaPath)
        [failureKind,source,detail] = appendFailure( ...
            failureKind,source,detail, ...
            "MissingSchemaPath","Complete-Configuration-Key-Index", ...
            schemaPath);
    end
end

enumValues = schemaEnumValues(v2xsim.config.schema());
for enumValue = enumValues.'
    if ~contains(wikiCorpus,enumValue)
        [failureKind,source,detail] = appendFailure( ...
            failureKind,source,detail, ...
            "MissingEnumValue","wiki",enumValue);
    end
end

outputContracts = publicOutputContracts();
for contractIndex = 1:height(outputContracts)
    pageFile = fullfile( ...
        wikiDirectory,outputContracts.Page(contractIndex) + ".md");
    if ~isfile(pageFile)
        continue
    end
    pageText = string(fileread(pageFile));
    columns = outputContracts.Columns{contractIndex};
    for column = columns
        if ~contains(pageText,column)
            [failureKind,source,detail] = appendFailure( ...
                failureKind,source,detail, ...
                "MissingOutputColumn", ...
                outputContracts.Page(contractIndex),column);
        end
    end
end

canonicalExamples = [ ...
    "examples/v7/v7_04_apply_position_errors.m"; ...
    "examples/v7/v7_07_run_nr_mode1.m"; ...
    "examples/v7/v7_08_run_nr_mode1_etsi_campaign.m"; ...
    "examples/v7/v7_09_explore_traffic_scenarios.m"; ...
    "examples/v7/v7_10_run_nr_mode2.m"; ...
    "examples/v7/config/07_nr_mode1_quickstart.toml"; ...
    "examples/v7/config/08_nr_mode1_etsi_campaign.toml"; ...
    "examples/v7/config/09_traffic_scenario_gallery.toml"; ...
    "examples/v7/config/10_nr_mode2_all_options.toml"; ...
    "examples/v7/v7_11_compare_lte_modes.m"; ...
    "examples/v7/v7_12_compare_ieee80211p.m"; ...
    "examples/v7/v7_13_compare_coexistence_methods.m"; ...
    "examples/v7/v7_14_compare_channel_models.m"; ...
    "examples/v7/v7_15_compare_application_traffic.m"; ...
    "examples/v7/v7_16_run_roadside_unit.m"; ...
    "examples/v7/v7_17_reduce_packet_fates.m"; ...
    "examples/v7/config/11_lte_modes.toml"; ...
    "examples/v7/config/12_ieee80211p.toml"; ...
    "examples/v7/config/13_coexistence_methods.toml"; ...
    "examples/v7/config/14_channel_models.toml"; ...
    "examples/v7/config/15_application_traffic.toml"; ...
    "examples/v7/config/16_roadside_unit.toml"];
for relativePath = canonicalExamples.'
    exampleFile = fullfile( ...
        projectRoot,replace(relativePath,"/",filesep));
    if ~isfile(exampleFile)
        [failureKind,source,detail] = appendFailure( ...
            failureKind,source,detail, ...
            "MissingExample","v7-dev",relativePath);
    end
end

failures = table( ...
    failureKind,source,detail, ...
    VariableNames=["Kind","Source","Detail"]);
report = struct( ...
    WikiDirectory=wikiDirectory, ...
    RequiredPageCount=numel(requiredPages), ...
    MarkdownFileCount=numel(markdownFiles), ...
    CheckedLinkCount=checkedLinkCount, ...
    CriticalTokenCount=height(criticalTokens), ...
    SchemaPathCount=numel(schemaPaths), ...
    EnumValueCount=numel(enumValues), ...
    OutputColumnCount=sum(cellfun(@numel,outputContracts.Columns)), ...
    CanonicalExampleCount=numel(canonicalExamples), ...
    IsValid=isempty(failures), ...
    Failures=failures);

if options.ThrowOnFailure && ~report.IsValid
    firstFailure = failures(1,:);
    error( ...
        "v2xsimdocs:wiki:ValidationFailed", ...
        "Wiki validation found %d failure(s). First: %s in %s (%s).", ...
        height(failures),firstFailure.Kind, ...
        firstFailure.Source,firstFailure.Detail);
end
end

function directory = defaultWikiDirectory()
projectRoot = fileparts(fileparts(mfilename("fullpath")));
directory = string(fullfile(projectRoot,"..","v7-wiki"));
end

function pages = wikiPageNames()
pages = [ ...
    "Home"; ...
    "_Sidebar"; ...
    "Getting-Started"; ...
    "Simulator-Scope-and-Fidelity"; ...
    "Standards-and-Terminology"; ...
    "C-V2X-and-NR-Mode-1"; ...
    "Mode-1-Quickstart"; ...
    "Mode-1-Research-Campaign"; ...
    "NR-V2X-Mode-2"; ...
    "Mode-2-Quickstart"; ...
    "PHY-Parameters-and-Beacon-Resources"; ...
    "Configuration-Reference"; ...
    "Traffic-Scenarios-Overview"; ...
    "Brownian-Motion-Scenario"; ...
    "Bidirectional-Highway-Scenario"; ...
    "ETSI-Highway-Scenario"; ...
    "Exit-Ramp-Highway-Scenario"; ...
    "Visualising-Traffic-Trajectories"; ...
    "True-and-Apparent-Position-Data-Flow"; ...
    "Position-Error-Configuration"; ...
    "Gaussian-Position-Error"; ...
    "Delayed-Position-Error"; ...
    "False-Route-Position-Errors"; ...
    "Position-Error-Lifecycle"; ...
    "Position-Error-Calibration"; ...
    "Analysing-Position-Error-Traces"; ...
    "Designing-Research-Campaigns"; ...
    "Outputs-and-Data-Dictionary"; ...
    "Plotting-and-Visualisation"; ...
    "Reproducibility-and-Statistics"; ...
    "Troubleshooting-and-Limitations"; ...
    "Citing-the-Simulator"; ...
    "Maintaining-the-Wiki"; ...
    "Autonomous-Allocation"; ...
    "LTE-V2X-Mode-3"; ...
    "LTE-V2X-Mode-4"; ...
    "Centralized-and-Benchmark-Allocators"; ...
    "IEEE-80211p-and-ITS-G5"; ...
    "Coexistence"; ...
    "Coexistence-Methods"; ...
    "Infrastructure-and-RSUs"; ...
    "Packet-Generation-and-Application-Traffic"; ...
    "Channel-Load-Congestion-Control-and-Awareness"; ...
    "Channel-and-Reception-Pipeline"; ...
    "Path-Loss-Models"; ...
    "Shadowing-Fading-and-Obstacles"; ...
    "Packet-Error-and-PER-Curves"; ...
    "Installation-and-Environment"; ...
    "Running-Simulations-and-Results"; ...
    "Migrating-from-V6"; ...
    "Simulation-Result-and-Summary"; ...
    "Aggregate-Metric-Outputs"; ...
    "Packet-and-Interference-Traces"; ...
    "Controller-and-Coexistence-Diagnostics"; ...
    "MATLAB-Analysis-API"; ...
    "Ramp-Position-Error-Study"; ...
    "Exposed-Reuse-Shadow-Evaluation"; ...
    "Architecture-and-Extension-Points"; ...
    "Testing-and-Verification"; ...
    "Complete-Configuration-Key-Index"; ...
    "Publication-Reproductions"; ...
    "Bazzi-2020-Wireless-Blind-Spots"; ...
    "Todisco-2021-NR-V2X-Mode-2"; ...
    "Wu-2023-Cochannel"; ...
    "Zhuofei-2023-Repetition"];
end

function paths = schemaLeafPaths(node, prefix)
kind = string(node.Kind);
if kind == "table"
    paths = strings(0,1);
    names = string(fieldnames(node.Children));
    for name = names.'
        if prefix == ""
            childPrefix = name;
        else
            childPrefix = prefix + "." + name;
        end
        paths = [paths; schemaLeafPaths( ...
            node.Children.(name),childPrefix)]; %#ok<AGROW>
    end
elseif kind == "arrayOfTables"
    paths = schemaLeafPaths(node.Element,prefix + "[]");
else
    paths = prefix;
end
end

function values = schemaEnumValues(node)
kind = string(node.Kind);
values = strings(0,1);
if ~isempty(node.AllowedStrings)
    values = string(node.AllowedStrings(:));
end
if kind == "table"
    names = string(fieldnames(node.Children));
    for name = names.'
        values = [values; schemaEnumValues( ...
            node.Children.(name))]; %#ok<AGROW>
    end
elseif kind == "arrayOfTables"
    values = [values; schemaEnumValues(node.Element)];
end
values = unique(values(values ~= ""),"stable");
end

function contracts = publicOutputContracts()
packetColumns = string( ...
    v2xsim.analysis.emptyTerminalPacketFateTable().Properties.VariableNames);
attemptColumns = string( ...
    v2xsim.analysis.emptyInterferenceAttemptTrace().Properties.VariableNames);
counterfactualColumns = string( ...
    v2xsim.analysis.emptyInterferenceCounterfactualTrace(). ...
    Properties.VariableNames);
aggregateColumns = [ ...
    "SimulationTimeSeconds","VehicleId","X","Y","vX","vY","aX","aY", ...
    "AwarenessRangeLowerBoundMeters","AwarenessRangeUpperBoundMeters", ...
    "AverageNeighborCount","DistanceUpperBoundMeters","CorrectCount", ...
    "ErrorCount","BlockedCount","OpportunityCount", ...
    "PacketReceptionRatio"];
page = [ ...
    "Packet-and-Interference-Traces"; ...
    "Packet-and-Interference-Traces"; ...
    "Packet-and-Interference-Traces"; ...
    "Aggregate-Metric-Outputs"];
columns = { ...
    packetColumns;attemptColumns;counterfactualColumns;aggregateColumns};
contracts = table(page,columns,VariableNames=["Page","Columns"]);
end

function targets = markdownLinkTargets(pageText)
matches = regexp( ...
    char(pageText),"\[[^\]]*\]\(([^)]+)\)","tokens");
if isempty(matches)
    targets = strings(0,1);
    return
end
targets = string(cellfun(@(match) match{1},matches, ...
    UniformOutput=false)).';
end

function result = isExternalOrAnchor(target)
result = startsWith(target,[ ...
    "http://","https://","mailto:","#"]);
end

function tokens = wikiCriticalTokens()
page = [ ...
    "Configuration-Reference"; ...
    "Configuration-Reference"; ...
    "Configuration-Reference"; ...
    "Configuration-Reference"; ...
    "Traffic-Scenarios-Overview"; ...
    "Traffic-Scenarios-Overview"; ...
    "Traffic-Scenarios-Overview"; ...
    "Traffic-Scenarios-Overview"; ...
    "Position-Error-Configuration"; ...
    "Position-Error-Configuration"; ...
    "Position-Error-Configuration"; ...
    "Position-Error-Configuration"; ...
    "Outputs-and-Data-Dictionary"; ...
    "Outputs-and-Data-Dictionary"; ...
    "Outputs-and-Data-Dictionary"; ...
    "Outputs-and-Data-Dictionary"; ...
    "C-V2X-and-NR-Mode-1"; ...
    "C-V2X-and-NR-Mode-1"; ...
    "NR-V2X-Mode-2"; ...
    "NR-V2X-Mode-2"; ...
    "NR-V2X-Mode-2"; ...
    "NR-V2X-Mode-2"; ...
    "NR-V2X-Mode-2"; ...
    "NR-V2X-Mode-2"; ...
    "NR-V2X-Mode-2"; ...
    "NR-V2X-Mode-2"; ...
    "NR-V2X-Mode-2"; ...
    "NR-V2X-Mode-2"; ...
    "NR-V2X-Mode-2"; ...
    "NR-V2X-Mode-2"; ...
    "NR-V2X-Mode-2"; ...
    "NR-V2X-Mode-2"; ...
    "NR-V2X-Mode-2"; ...
    "PHY-Parameters-and-Beacon-Resources"; ...
    "PHY-Parameters-and-Beacon-Resources"; ...
    "PHY-Parameters-and-Beacon-Resources"; ...
    "PHY-Parameters-and-Beacon-Resources"; ...
    "PHY-Parameters-and-Beacon-Resources"];
token = [ ...
    "Simulation.RandomSeed"; ...
    "Radio.NrV2X.SubcarrierSpacingKilohertz"; ...
    "ResourceAllocation.MaximumReuseDistance"; ...
    "Outputs.PacketReceptionRatio"; ...
    "BrownianMotion"; ...
    "BidirectionalHighway"; ...
    "EtsiHighway"; ...
    "ExitRampHighway"; ...
    "Gaussian"; ...
    "Delay"; ...
    "FalseExit"; ...
    "FalseMerge"; ...
    "SimulationTimeSeconds"; ...
    "DisplacementMagnitudeMeters"; ...
    "OpportunityCount"; ...
    "packet_fates_<chunk>"; ...
    "MaximumReuseDistance"; ...
    "MinimumReusePower"; ...
    "ReevaluationEnabled"; ...
    "ReevaluateAfterSkippedTransmissionEnabled"; ...
    "ReselectEveryPacketEnabled"; ...
    "KeepResourceProbability"; ...
    "MaximumConsecutiveReservationIntervals"; ...
    "MinimumCandidateFraction"; ...
    "L2CandidateFraction"; ...
    "L2RankingEnabled"; ...
    "AverageSensingEnabled"; ...
    "SensingWindowSeconds"; ...
    "ReselectionCounterMinimum"; ...
    "ReselectionCounterMaximum"; ...
    "SensingThresholdDbm"; ...
    "SelectionWindowStartMilliseconds"; ...
    "SelectionWindowEndMilliseconds"; ...
    "N_BR = N_time * N_frequency"; ...
    "DmrsResourceElementCountPerSlot"; ...
    "SciSymbolCount"; ...
    "PartialFrequencyOverlapEnabled"; ...
    "FixedPowerDensityEnabled"];
tokens = table(page,token,VariableNames=["Page","Token"]);
end

function [kinds,sources,details] = appendFailure( ...
        kinds,sources,details,kind,source,detail)
kinds(end + 1,1) = kind;
sources(end + 1,1) = source;
details(end + 1,1) = detail;
end
