classdef SelectionWindowEligibilityTest < matlab.unittest.TestCase
    %SELECTIONWINDOWELIGIBILITYTEST Tests future T1--T2 eligibility.

    methods (Test)
        function testUsesEachUesAbsoluteSelectionOrigin(testCase)
            grid = testCase.createGrid();
            actual = ...
                v2xsim.resource.algorithm. ...
                    buildSelectionWindowEligibility( ...
                        grid,[0;2],1,1,3);

            testCase.verifyEqual( ...
                actual(1,:),testCase.maskForTimeSlots(grid,[3,4]));
            testCase.verifyEqual( ...
                actual(2,:),testCase.maskForTimeSlots(grid,[1,4,5]));
        end

        function testWrapsSelectionWindowAcrossGridPeriod(testCase)
            grid = testCase.createGrid();
            actual = ...
                v2xsim.resource.algorithm. ...
                    buildSelectionWindowEligibility( ...
                        grid,4,4,1,3);

            testCase.verifyEqual( ...
                actual,testCase.maskForTimeSlots(grid,[1,2,3]));
        end

        function testCurrentSlotEqualToOriginKeepsFutureOffsets(testCase)
            grid = testCase.createGrid();
            actual = ...
                v2xsim.resource.algorithm. ...
                    buildSelectionWindowEligibility( ...
                        grid,2,2,1,2);

            testCase.verifyEqual( ...
                actual,testCase.maskForTimeSlots(grid,[4,5]));
        end

        function testReevaluationExcludesElapsedOccurrences(testCase)
            grid = testCase.createGrid();
            actual = ...
                v2xsim.resource.algorithm. ...
                    buildSelectionWindowEligibility( ...
                        grid,0,2,1,4);

            testCase.verifyEqual( ...
                actual,testCase.maskForTimeSlots(grid,[4,5]));
        end

        function testCurrentSlotAfterDeadlineHasNoEligibleResources( ...
                testCase)
            grid = testCase.createGrid();
            actual = ...
                v2xsim.resource.algorithm. ...
                    buildSelectionWindowEligibility( ...
                        grid,4,7,1,3);

            testCase.verifyFalse(any(actual,"all"));
        end

        function testAcceptsEmptyUeSet(testCase)
            grid = testCase.createGrid();
            actual = ...
                v2xsim.resource.algorithm. ...
                    buildSelectionWindowEligibility( ...
                        grid,zeros(0,1),0,1,3);

            testCase.verifyClass(actual,"logical");
            testCase.verifySize(actual,[0,grid.ResourceCount]);
        end

        function testRejectsReversedWindow(testCase)
            grid = testCase.createGrid();

            testCase.verifyError( ...
                @() v2xsim.resource.algorithm. ...
                    buildSelectionWindowEligibility( ...
                        grid,0,0,4,3), ...
                "v2xsim:resource:InvalidSelectionWindow");
        end

        function testRejectsWindowLongerThanGridPeriod(testCase)
            grid = testCase.createGrid();

            testCase.verifyError( ...
                @() v2xsim.resource.algorithm. ...
                    buildSelectionWindowEligibility( ...
                        grid,0,0,1,6), ...
                "v2xsim:resource:InvalidSelectionWindow");
        end
    end

    methods (Static,Access=private)
        function grid = createGrid()
            grid = v2xsim.resource.BRResourceGrid( ...
                v2xsim.network.NetworkSliceId("selection-window"), ...
                5,2,0.001);
        end

        function mask = maskForTimeSlots(grid,timeSlots)
            resourceTimeSlots = ceil( ...
                (1:grid.ResourceCount) / ...
                grid.NumberFrequencyResources);
            mask = ismember(resourceTimeSlots,timeSlots);
        end
    end
end
