classdef CoexistenceChannelLoadDisabledTest < matlab.unittest.TestCase
    %COEXISTENCECHANNELLOADDISABLEDTEST Disabled CBR remains a valid mode.

    properties (TestParameter)
        RadioMode = {"Ieee80211p","Independent","Cochannel"}
    end

    properties (SetAccess = private)
        TemporaryDirectory (1,1) string
    end

    methods (TestClassSetup)
        function createTemporaryDirectory(testCase)
            temporaryFolder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            testCase.TemporaryDirectory = string(temporaryFolder.Folder);
        end
    end

    methods (TestMethodSetup)
        function isolateProcessWideState(testCase)
            originalPath = path;
            originalStream = RandStream.getGlobalStream();
            originalStreamState = originalStream.State;
            originalWarnings = warning;
            testCase.addTeardown(@() path(originalPath));
            testCase.addTeardown(@() restoreGlobalRandomStream( ...
                originalStream,originalStreamState));
            testCase.addTeardown(@() warning(originalWarnings));

            root = testCase.projectRoot();
            addpath(fullfile(root,"src"));
            addpath(fullfile(root,"lib","matlab-toml"));
        end
    end

    methods (Test)
        function testRunCompletesWithoutCbrState( ...
                testCase,RadioMode)
            radioMode = string(RadioMode);
            originalPath = path;
            originalRandomState = rng;
            originalWarnings = warning;

            configurationFile = fullfile( ...
                testCase.projectRoot(),"regression-tests", ...
                "+v2xsimregression","+coexistence","config", ...
                "lteCoexistence.toml");
            patchData = struct( ...
                Simulation=struct( ...
                    RandomSeed=73,DurationSeconds=0.5), ...
                Scenario=struct( ...
                    BidirectionalHighway=struct(RandomSeed=73)), ...
                Application=struct( ...
                    ChannelLoad=struct(Enabled=false)), ...
                Radio=testCase.radioPatch(radioMode), ...
                ResourceAllocation=struct(RandomSeed=73), ...
                Outputs=struct( ...
                    PacketReceptionRatio=struct(Enabled=false), ...
                    ChannelBusyRatio=struct(Enabled=false)));
            configuration = v2xsim.config.load( ...
                configurationFile).resolve( ...
                    Patch=v2xsim.config.patch(patchData)); %#ok<NASGU>
            outputDirectory = fullfile( ...
                testCase.TemporaryDirectory,lower(radioMode));

            evalc("result = v2xsim.runSimulation(configuration," + ...
                "OutputDirectory=outputDirectory," + ...
                "RunLabel='channel-load-disabled');");

            testCase.verifyClass( ...
                result,"v2xsim.runtime.SimulationResult");
            testCase.verifyFalse( ...
                result.Configuration.Data.Application.ChannelLoad.Enabled);
            testCase.verifyEqual( ...
                result.RunDirectory,outputDirectory);
            testCase.verifyTrue(all(isfile(result.Artifacts)));

            summaryFile = fullfile( ...
                outputDirectory,"simulation_summary.json");
            testCase.assertTrue(isfile(summaryFile));
            summary = jsondecode(fileread(summaryFile));
            testCase.verifyEqual( ...
                string(summary.Results.Ieee80211p. ...
                    ChannelBusyRatio.Status), ...
                "Disabled");
            testCase.verifyEmpty( ...
                summary.Results.Ieee80211p.ChannelBusyRatio.Channels);
            if radioMode == "Ieee80211p"
                testCase.verifyEqual( ...
                    string(summary.Results.CellularSidelink. ...
                        ChannelBusyRatio.Status), ...
                    "NotApplicable");
            else
                testCase.verifyEqual( ...
                    string(summary.Results.CellularSidelink. ...
                        ChannelBusyRatio.Status), ...
                    "Disabled");
                testCase.verifyEmpty( ...
                    summary.Results.CellularSidelink. ...
                        ChannelBusyRatio.Channels);
            end
            testCase.verifyEqual( ...
                string(summary.Results.Combined.ChannelBusyRatio.Status), ...
                "NotApplicable");

            cbrFiles = [ ...
                dir(fullfile(outputDirectory,"CBR*.csv")); ...
                dir(fullfile(outputDirectory,"coex_*CBR*.csv"))];
            testCase.verifyEmpty(cbrFiles);
            testCase.verifyFalse(isfile(fullfile( ...
                outputDirectory,"error_log.txt")));
            testCase.verifyFalse(isfolder(fullfile( ...
                outputDirectory,".v2xsim-output-lock")));
            testCase.verifyEqual(path,originalPath);
            testCase.verifyEqual(rng,originalRandomState);
            testCase.verifyEqual(warning,originalWarnings);
        end
    end

    methods (Access = private)
        function patch = radioPatch(~,radioMode)
            if radioMode == "Ieee80211p"
                patch = struct(Type="Ieee80211p");
                return
            end
            patch = struct( ...
                Type="Coexistence", ...
                Coexistence=struct( ...
                    SidelinkType="LteV2X", ...
                    InterferenceModel=radioMode));
        end

        function root = projectRoot(~)
            root = string(fileparts(fileparts(fileparts(fileparts( ...
                mfilename("fullpath"))))));
        end
    end
end

function restoreGlobalRandomStream(stream,state)
RandStream.setGlobalStream(stream);
stream.State = state;
end
