classdef CustomPositionErrorModuleRunTest < matlab.unittest.TestCase
    %CUSTOMPOSITIONERRORMODULERUNTEST End-to-end custom-chain contract.

    methods (TestMethodSetup)
        function isolateProcessWideState(testCase)
            originalPath = path;
            originalRandomState = rng;
            originalWarnings = warning;
            testCase.addTeardown(@() path(originalPath));
            testCase.addTeardown(@() rng(originalRandomState));
            testCase.addTeardown(@() warning(originalWarnings));
        end
    end

    methods (Test)
        function customModuleChangesControllerVisiblePositions(testCase)
            outputFixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            outputDirectory = string(outputFixture.Folder);
            delayError = struct(Type="Delay", DelaySeconds=0);
            patch = v2xsim.config.patch(struct( ...
                Simulation=struct( ...
                    RandomSeed=811, DurationSeconds=0.1), ...
                Scenario=struct( ...
                    BidirectionalHighway=struct( ...
                        RandomSeed=812, VehicleCount=4, ...
                        RoadLength=200, NLanes=1, ...
                        MeanVehicleSpeed=10, ...
                        VehicleSpeedStandardDeviation=0)), ...
                Positioning=struct(Errors={{delayError}}), ...
                Outputs=struct(PositionErrorTrace=struct( ...
                    Enabled=true, FlushRowCount=1000))));
            configuration = v2xsim.config.ConfigurationTemplate( ...
                struct(SchemaVersion=1)).resolve(Patch=patch); %#ok<NASGU>
            customModule = v2xsimtest.positioning.fixture. ...
                FixedOffsetPositionErrorModule(5);
            descriptor = struct( ...
                Name="Integration fixed offset", ...
                Version="1.0", ...
                SourceRevision="test-fixture", ...
                Parameters=struct(OffsetMeters=5));
            specification = ...
                v2xsim.positioning.PositionErrorChainSpecification([ ...
                    v2xsim.positioning. ...
                        PositionErrorChainEntry.custom( ...
                            customModule, descriptor), ...
                    v2xsim.positioning. ...
                        PositionErrorChainEntry.configured("Delay")]); %#ok<NASGU>

            evalc("result = v2xsim.runSimulation(" + ...
                "configuration, OutputDirectory=outputDirectory, " + ...
                "PositionErrorChainSpecification=specification);");

            traceFiles = dir(fullfile( ...
                outputDirectory, "position_error_trace_*.csv"));
            testCase.assertNotEmpty(traceFiles);
            traces = cell(numel(traceFiles), 1);
            for fileIndex = 1:numel(traceFiles)
                traces{fileIndex} = readtable( ...
                    fullfile(traceFiles(fileIndex).folder, ...
                        traceFiles(fileIndex).name), ...
                    TextType="string");
            end
            trace = vertcat(traces{:});
            customClass = "v2xsimtest.positioning.fixture." + ...
                "FixedOffsetPositionErrorModule";
            customRows = trace.ModuleType == customClass;
            testCase.verifyTrue(any(customRows));
            testCase.verifyEqual( ...
                unique(trace.ModuleIndex(customRows)), 1);
            testCase.verifyEqual( ...
                trace.DisplacementXMeters(customRows), ...
                5 * ones(nnz(customRows), 1), AbsTol=1e-12);
            testCase.verifyEqual( ...
                trace.DisplacementYMeters(customRows), ...
                zeros(nnz(customRows), 1), AbsTol=1e-12);

            appliedChain = result.AppliedPositionErrorChain;
            testCase.verifyEqual( ...
                appliedChain.Modules{1}.Type, customClass);
            testCase.verifyEqual( ...
                appliedChain.Modules{1}.Descriptor, descriptor);
            testCase.verifyEqual( ...
                appliedChain.Modules{2}.Type, "PositionDelayError");

            summary = jsondecode(fileread(fullfile( ...
                outputDirectory, "simulation_summary.json")));
            summaryModules = ...
                summary.Configuration.Positioning.ErrorChain.Modules;
            testCase.verifyEqual( ...
                string(summaryModules{1}.Type), customClass);
            testCase.verifyEqual( ...
                string(summaryModules{1}.Descriptor.Version), "1.0");
        end
    end
end
