classdef NetworkPositionErrorRunTest < matlab.unittest.TestCase
    %NETWORKPOSITIONERRORRUNTEST Configured network-error chain integration.

    methods (TestMethodSetup)
        function isolateProcessWideState(testCase)
            originalPath = path;
            originalRandomState = rng;
            originalWarnings = warning;
            testCase.addTeardown(@() path(originalPath));
            testCase.addTeardown(@() rng(originalRandomState));
            testCase.addTeardown(@() warning(originalWarnings));
        end
    end

    methods (Test)
        function configuredPacketLossThenDelayProducesAgedTrace(testCase)
            outputFixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            outputDirectory = string(outputFixture.Folder);
            packetLoss = struct( ...
                Type="PacketLoss", ...
                LossProbability=1, ...
                RandomSeed=1709);
            delay = struct(Type="Delay", DelaySeconds=0.1);
            patch = v2xsim.config.patch(struct( ...
                Simulation=struct( ...
                    RandomSeed=1701, DurationSeconds=0.2), ...
                Scenario=struct( ...
                    UpdateIntervalSeconds=0.1, ...
                    BidirectionalHighway=struct( ...
                        RandomSeed=1703, VehicleCount=2, ...
                        RoadLength=200, NLanes=1, ...
                        MeanVehicleSpeed=10, ...
                        VehicleSpeedStandardDeviation=0)), ...
                Positioning=struct( ...
                    Errors={{packetLoss, delay}}), ...
                Outputs=struct(PositionErrorTrace=struct( ...
                    Enabled=true, FlushRowCount=1000))));
            configuration = v2xsim.config.ConfigurationTemplate( ...
                struct(SchemaVersion=1)).resolve(Patch=patch); %#ok<NASGU>

            evalc("result = v2xsim.runSimulation(" + ...
                "configuration, OutputDirectory=outputDirectory);");

            appliedModules = result.AppliedPositionErrorChain.Modules;
            testCase.verifyNumElements(appliedModules, 2);
            testCase.verifyEqual( ...
                appliedModules{1}.Type, "PositionPacketLossError");
            testCase.verifyEqual( ...
                appliedModules{1}.Options.LossProbability, 1);
            testCase.verifyEqual( ...
                appliedModules{1}.Options.RandomSeed, 1709);
            testCase.verifyEqual( ...
                appliedModules{2}.Type, "PositionDelayError");
            testCase.verifyEqual( ...
                appliedModules{2}.Options.DelaySeconds, 0.1);

            trace = testCase.readPositionErrorTrace(outputDirectory);
            packetLossRows = trace.ModuleIndex == 1;
            delayRows = trace.ModuleIndex == 2;
            testCase.assertTrue(any(packetLossRows));
            testCase.assertTrue(any(delayRows));
            testCase.verifyTrue(all( ...
                trace.ModuleType(packetLossRows) == ...
                "v2xsim.positioning.PositionPacketLossError"));
            testCase.verifyTrue(all( ...
                trace.ModuleType(delayRows) == ...
                "v2xsim.positioning.PositionDelayError"));

            packetTrace = trace(packetLossRows, :);
            bootstrapRows = packetTrace.SimulationTimeSeconds == 0;
            droppedRows = packetTrace.SimulationTimeSeconds > 0;
            testCase.assertTrue(any(bootstrapRows));
            testCase.assertTrue(any(droppedRows));
            testCase.verifyTrue(all( ...
                packetTrace.NetworkUpdateOutcome(bootstrapRows) == ...
                "BootstrapReceived"));
            testCase.verifyEqual( ...
                packetTrace.OutputSourceTimeSeconds(bootstrapRows), ...
                zeros(nnz(bootstrapRows), 1));
            testCase.verifyEqual( ...
                packetTrace.OutputAgeSeconds(bootstrapRows), ...
                zeros(nnz(bootstrapRows), 1));
            testCase.verifyTrue(all( ...
                packetTrace.NetworkUpdateOutcome(droppedRows) == ...
                "Dropped"));
            testCase.verifyEqual( ...
                packetTrace.OutputSourceTimeSeconds(droppedRows), ...
                zeros(nnz(droppedRows), 1));
            testCase.verifyEqual( ...
                packetTrace.OutputAgeSeconds(droppedRows), ...
                packetTrace.SimulationTimeSeconds(droppedRows), ...
                AbsTol=1e-12);

            delayTrace = trace(delayRows, :);
            warmupRows = delayTrace.SimulationTimeSeconds == 0;
            delayedRows = delayTrace.SimulationTimeSeconds > 0;
            testCase.assertTrue(any(warmupRows));
            testCase.assertTrue(any(delayedRows));
            testCase.verifyTrue(all( ...
                delayTrace.NetworkUpdateOutcome(warmupRows) == ...
                "WarmupHeld"));
            testCase.verifyEqual( ...
                delayTrace.OutputSourceTimeSeconds(warmupRows), ...
                zeros(nnz(warmupRows), 1));
            testCase.verifyEqual( ...
                delayTrace.OutputAgeSeconds(warmupRows), ...
                zeros(nnz(warmupRows), 1));
            testCase.verifyTrue(all( ...
                delayTrace.NetworkUpdateOutcome(delayedRows) == ...
                "Delayed"));
            testCase.verifyEqual( ...
                delayTrace.OutputSourceTimeSeconds(delayedRows), ...
                delayTrace.SimulationTimeSeconds(delayedRows) - 0.1, ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                delayTrace.OutputAgeSeconds(delayedRows), ...
                0.1 .* ones(nnz(delayedRows), 1), ...
                AbsTol=1e-12);
        end
    end

    methods (Access = private)
        function trace = readPositionErrorTrace(~, outputDirectory)
            traceFiles = dir(fullfile( ...
                outputDirectory, "position_error_trace_*.csv"));
            assert(~isempty(traceFiles), ...
                "NetworkPositionErrorRunTest:MissingTrace", ...
                "The simulation did not produce a position-error trace.");
            chunks = cell(numel(traceFiles), 1);
            for fileIndex = 1:numel(traceFiles)
                chunks{fileIndex} = readtable( ...
                    fullfile(traceFiles(fileIndex).folder, ...
                        traceFiles(fileIndex).name), ...
                    TextType="string");
            end
            trace = vertcat(chunks{:});
        end
    end
end
