classdef OutputCountOracleTest < matlab.unittest.TestCase
    %OUTPUTCOUNTORACLETEST Reconcile full-run artifacts with the summary.

    properties (TestParameter)
        RadioAccessMode = { ...
            "80211p", ...
            "LTE-V2X", ...
            "NR-V2X", ...
            "COEX-NO-INTERF"}
    end

    properties (Constant, Access = private)
        AwarenessRangesMeters = [50, 100, 300]
        DistanceBinWidthMeters = 10
        SimulationDurationSeconds = 0.6
        VehicleCount = 6
    end

    properties (SetAccess = private)
        TemporaryDirectory (1, 1) string
    end

    methods (TestClassSetup)
        function createTemporaryDirectory(testCase)
            temporaryFolder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            testCase.TemporaryDirectory = string(temporaryFolder.Folder);
        end
    end

    methods (TestMethodSetup)
        function preserveProcessStateAndConfigurePaths(testCase)
            originalPath = path;
            originalStream = RandStream.getGlobalStream();
            originalStreamState = originalStream.State;
            originalWarnings = warning;
            testCase.addTeardown(@() path(originalPath));
            testCase.addTeardown(@() restoreGlobalRandomStream( ...
                originalStream,originalStreamState));
            testCase.addTeardown(@() warning(originalWarnings));

            projectRoot = testCase.projectRoot();
            addpath(fullfile(projectRoot, "src"));
            addpath(fullfile(projectRoot, "old_src"));
        end
    end

    methods (Test)
        function testArtifactsReconcileAndObserversArePassive( ...
                testCase, RadioAccessMode)
            radioAccessMode = string(RadioAccessMode);
            [enabledSummary, enabledDirectory] = ...
                testCase.runSimulation(radioAccessMode, true);
            [disabledSummary, disabledDirectory] = ...
                testCase.runSimulation(radioAccessMode, false);

            specification = testCase.specification(radioAccessMode);
            testCase.verifySummaryContract( ...
                enabledSummary, enabledDirectory, specification);
            testCase.verifyPopulationPartitions( ...
                enabledSummary, specification);
            testCase.verifyExpectedArtifacts( ...
                enabledDirectory, specification);
            testCase.verifyArtifactSchemas( ...
                enabledDirectory, enabledSummary, specification);
            testCase.verifyCountsReconcile( ...
                enabledDirectory, enabledSummary, specification);

            testCase.verifyOnlySummaryExists(disabledDirectory);
            testCase.verifyEqual( ...
                testCase.semanticSummary(enabledSummary), ...
                testCase.semanticSummary(disabledSummary), ...
                "Enabling output observers must not change " + ...
                "simulation results or configuration.");
        end
    end

    methods (Access = private)
        function [summary, outputDirectory] = runSimulation( ...
                testCase, radioAccessMode, outputsEnabled)
            specification = testCase.specification(radioAccessMode);
            if outputsEnabled
                outputState = "enabled";
            else
                outputState = "disabled";
            end
            outputDirectory = fullfile( ...
                testCase.TemporaryDirectory, ...
                specification.DirectoryToken + "-" + outputState);
            configurationFile = fullfile( ...
                testCase.projectRoot(), "old_src", "ConfigFiles", ...
                "EtsiHighwayMediumMode1.cfg");
            outputArguments = { ...
                "output.VehicleKinematics.Enabled", outputsEnabled, ...
                "output.PacketReceptionRatio.Enabled", outputsEnabled, ...
                "output.UpdateDelay.Enabled", outputsEnabled, ...
                "output.PacketDelay.Enabled", outputsEnabled, ...
                "output.DataAge.Enabled", outputsEnabled, ...
                "output.WirelessBlindSpot.Enabled", outputsEnabled, ...
                "output.AverageNeighborCount.Enabled", outputsEnabled, ...
                "output.ChannelBusyRatio.Enabled", outputsEnabled};
            if outputsEnabled
                outputArguments = [ ...
                    outputArguments, { ...
                        "output.PacketReceptionRatio." + ...
                            "DistanceBinWidthMeters", ...
                        testCase.DistanceBinWidthMeters}];
            end
            simulationArguments = { ...
                configurationFile, ...
                "simulation.RandomSeed", 71, ...
                "simulation.RunLabel", ...
                    "output-count-oracle-" + ...
                    specification.DirectoryToken, ...
                "simulation.RadioAccessMode", radioAccessMode, ...
                "simulation.DurationSeconds", ...
                    testCase.SimulationDurationSeconds, ...
                "scenario.UpdateIntervalSeconds", 0.1, ...
                "scenario.Type", "BidirectionalHighwayScenario", ...
                "scenarioOptions.RandomSeed", 19, ...
                "scenarioOptions.VehicleCount", ...
                    testCase.VehicleCount, ...
                "scenarioOptions.RoadLength", 200, ...
                "scenarioOptions.MeanVehicleSpeed", 10, ...
                "scenarioOptions.VehicleSpeedStandardDeviation", 0, ...
                "scenarioOptions.RerollSpeedOnWrapAround", false, ...
                "awareness.RangesMeters", ...
                    testCase.AwarenessRangesMeters, ...
                "output.Directory", outputDirectory};
            if radioAccessMode == "COEX-NO-INTERF"
                simulationArguments = [ ...
                    simulationArguments, { ...
                        "coexistence.VehiclePattern." + ...
                            "SidelinkVehicleCount", 3, ...
                        "coexistence.VehiclePattern." + ...
                            "ItsG5VehicleCount", 3}];
            end
            simulationArguments = [ ...
                simulationArguments, outputArguments]; %#ok<NASGU>

            evalc("WiLabV2Xsim(simulationArguments{:});");
            summaryFilename = fullfile( ...
                outputDirectory, "simulation_summary.json");
            testCase.assertTrue(isfile(summaryFilename));
            summary = jsondecode(fileread(summaryFilename));
        end

        function verifySummaryContract( ...
                testCase, summary, outputDirectory, specification)
            summaryFilename = fullfile( ...
                outputDirectory, "simulation_summary.json");
            summaryText = string(fileread(summaryFilename));

            testCase.verifyEqual(summary.SchemaVersion, 1);
            testCase.verifyEqual( ...
                string(fieldnames(summary)).', ...
                ["SchemaVersion", "Run", "Configuration", "Results"]);
            testCase.verifyFalse(contains(summaryText, "NaN"));
            testCase.verifyFalse(contains(summaryText, "Infinity"));
            testCase.verifyEqual( ...
                string(summary.Run.SimulatorVersion), "V7");
            testCase.verifyEqual(summary.Run.RandomSeed, 71);
            testCase.verifyEqual( ...
                summary.Run.SimulatedDurationSeconds, ...
                testCase.SimulationDurationSeconds, AbsTol=1e-12);
            testCase.verifyGreaterThanOrEqual( ...
                summary.Run.ComputationDurationSeconds, 0);
            testCase.verifyEqual( ...
                string(summary.Run.RunLabel), ...
                "output-count-oracle-" + ...
                    specification.DirectoryToken);
            timestampMatch = regexp( ...
                string(summary.Run.CompletedAtUtc), ...
                "^\d{4}-\d{2}-\d{2}T" + ...
                    "\d{2}:\d{2}:\d{2}\.\d{3}Z$", ...
                "once");
            testCase.verifyNotEmpty(timestampMatch);

            testCase.verifyEqual( ...
                string(summary.Configuration.RadioAccessMode), ...
                specification.RadioAccessMode);
            testCase.verifyEqual( ...
                summary.Configuration.Awareness.RangesMeters(:).', ...
                testCase.AwarenessRangesMeters);
            testCase.verifyEqual( ...
                summary.Configuration.Infrastructure. ...
                    RoadSideUnitCount, ...
                0);
            testCase.verifyEqual( ...
                numel(summary.Configuration.Radio.Channels), 1);
            testCase.verifyFalse(isfile(fullfile( ...
                outputDirectory, ".v2xsim-output-lock")));
            testCase.verifyFalse(isfolder(fullfile( ...
                outputDirectory, ".v2xsim-output-lock")));
            testCase.verifyFalse(isfile(fullfile( ...
                outputDirectory, "error_log.txt")));
        end

        function verifyPopulationPartitions( ...
                testCase, summary, specification)
            cellular = summary.Results.CellularSidelink;
            ieee80211p = summary.Results.Ieee80211p;
            combined = summary.Results.Combined;

            testCase.verifyEqual( ...
                cellular.Active, ...
                specification.CellularUeCount > 0);
            testCase.verifyEqual( ...
                ieee80211p.Active, ...
                specification.Ieee80211pUeCount > 0);
            testCase.verifyTrue(combined.Active);
            testCase.verifyEqual( ...
                cellular.AverageUeCount, ...
                specification.CellularUeCount);
            testCase.verifyEqual( ...
                ieee80211p.AverageUeCount, ...
                specification.Ieee80211pUeCount);
            testCase.verifyEqual( ...
                combined.AverageUeCount, testCase.VehicleCount);
            testCase.verifyEqual( ...
                cellular.AverageUeCount + ...
                    ieee80211p.AverageUeCount, ...
                combined.AverageUeCount);

            if specification.CellularUeCount == 0
                testCase.verifyEmpty( ...
                    cellular.AwarenessRangeMetrics);
                testCase.verifyEqual( ...
                    string(cellular.ChannelBusyRatio.Status), ...
                    "NotApplicable");
            end
            if specification.Ieee80211pUeCount == 0
                testCase.verifyEmpty( ...
                    ieee80211p.AwarenessRangeMetrics);
                testCase.verifyEqual( ...
                    string(ieee80211p.ChannelBusyRatio.Status), ...
                    "NotApplicable");
            end

            coexistence = summary.Configuration.Coexistence;
            testCase.verifyEqual( ...
                coexistence.Active, specification.IsCoexistence);
            if specification.IsCoexistence
                testCase.verifyEqual( ...
                    string(coexistence.InterferenceMode), ...
                    "Orthogonal");
                testCase.verifyEqual( ...
                    coexistence.CellularSidelinkVehicleGroupSize, ...
                    3);
                testCase.verifyEqual( ...
                    coexistence.Ieee80211pVehicleGroupSize, 3);
            end
        end

        function verifyExpectedArtifacts( ...
                testCase, outputDirectory, specification)
            technologyArtifactPrefixes = [ ...
                "packet_reception_ratio", ...
                "packet_delay", ...
                "update_delay", ...
                "data_age", ...
                "wireless_blind_spot", ...
                "CBRstatistic", ...
                "CBRofGenericVehicle"];
            allTechnologyTokens = ["11p", "LTE", "5G"];

            expectedFiles = [ ...
                "simulation_summary.json", ...
                "vehicle_kinematics.csv"];
            for technology = specification.TechnologyTokens
                expectedFiles = [ ...
                    expectedFiles, ...
                    technologyArtifactPrefixes + ...
                        "_" + technology + ".csv"]; %#ok<AGROW>
            end
            for technology = specification.NeighborTokens
                expectedFiles = [ ...
                    expectedFiles, ...
                    "average_neighbor_count_over_time_" + ...
                        technology + ".csv", ...
                    "average_neighbor_count_simulation_wide_" + ...
                        technology + ".csv"]; %#ok<AGROW>
            end
            if specification.IsCoexistence
                expectedFiles(end + 1) = ...
                    "coex_cv2xOnly_CBRstatistic_LTE.csv";
            end

            listing = dir(outputDirectory);
            actualFiles = string({listing(~[listing.isdir]).name});
            testCase.verifyTrue(all(ismember( ...
                expectedFiles, actualFiles)), ...
                "Every applicable optional artifact must be present.");

            inactiveTokens = setdiff( ...
                allTechnologyTokens, ...
                specification.TechnologyTokens, "stable");
            for technology = inactiveTokens
                inactiveFiles = ...
                    technologyArtifactPrefixes + ...
                    "_" + technology + ".csv";
                testCase.verifyFalse(any(ismember( ...
                    inactiveFiles, actualFiles)), ...
                    "Inactive technologies must not emit artifacts.");
            end

            neighborListing = dir(fullfile( ...
                outputDirectory, ...
                "average_neighbor_count_*.csv"));
            actualNeighborFiles = ...
                sort(string({neighborListing.name}));
            expectedNeighborFiles = strings( ...
                1, 2 * numel(specification.NeighborTokens));
            outputIndex = 0;
            for technology = specification.NeighborTokens
                outputIndex = outputIndex + 1;
                expectedNeighborFiles(outputIndex) = ...
                    "average_neighbor_count_over_time_" + ...
                        technology + ".csv";
                outputIndex = outputIndex + 1;
                expectedNeighborFiles(outputIndex) = ...
                    "average_neighbor_count_simulation_wide_" + ...
                        technology + ".csv";
            end
            testCase.verifyEqual( ...
                actualNeighborFiles, sort(expectedNeighborFiles));
        end

        function verifyArtifactSchemas( ...
                testCase, outputDirectory, summary, specification)
            testCase.verifyKinematicsArtifact(outputDirectory);
            for technology = specification.NeighborTokens
                testCase.verifyNeighborArtifacts( ...
                    outputDirectory, technology);
            end
            for technology = specification.TechnologyTokens
                testCase.verifyTechnologyArtifacts( ...
                    outputDirectory, technology);
            end
            if specification.IsCoexistence
                testCase.verifyCbrStatistic(fullfile( ...
                    outputDirectory, ...
                    "coex_cv2xOnly_CBRstatistic_LTE.csv"));
            end

            testCase.verifyEqual( ...
                string(summary.Configuration.Scenario.Type), ...
                "BidirectionalHighwayScenario");
        end

        function verifyKinematicsArtifact(testCase, outputDirectory)
            output = readtable( ...
                fullfile(outputDirectory, "vehicle_kinematics.csv"), ...
                TextType="string");
            testCase.verifyEqual( ...
                string(output.Properties.VariableNames), ...
                ["SimulationTimeSeconds", "VehicleId", ...
                    "X", "Y", "vX", "vY", "aX", "aY"]);
            testCase.verifyGreaterThan(height(output), 0);
            testCase.verifyTrue(all( ...
                output.SimulationTimeSeconds >= 0 & ...
                output.SimulationTimeSeconds <= ...
                    testCase.SimulationDurationSeconds));
            testCase.verifyTrue(all( ...
                diff(output.SimulationTimeSeconds) >= 0));
            testCase.verifyEqual( ...
                sort(unique(output.VehicleId)), ...
                "V" + string((1:testCase.VehicleCount).'));
            testCase.verifyTrue(all(isfinite( ...
                output{:, ["X", "Y", "vX", "vY"]}), "all"));
            testCase.verifyFalse(any(isinf( ...
                output{:, ["aX", "aY"]}), "all"));

            uniqueRows = unique( ...
                output(:, ["SimulationTimeSeconds", "VehicleId"]), ...
                "rows");
            testCase.verifyEqual(height(uniqueRows), height(output), ...
                "A vehicle may appear only once at each snapshot.");
        end

        function verifyNeighborArtifacts( ...
                testCase, outputDirectory, technology)
            expectedBounds = [ ...
                [0, testCase.AwarenessRangesMeters(1:end - 1)].', ...
                testCase.AwarenessRangesMeters.'];
            simulationWide = readtable(fullfile( ...
                outputDirectory, ...
                "average_neighbor_count_simulation_wide_" + ...
                    technology + ".csv"));
            testCase.verifyEqual( ...
                string(simulationWide.Properties.VariableNames), ...
                ["AwarenessRangeLowerBoundMeters", ...
                    "AwarenessRangeUpperBoundMeters", ...
                    "AverageNeighborCount"]);
            testCase.verifyEqual( ...
                simulationWide{:, 1:2}, expectedBounds);
            testCase.verifyTrue(all(isfinite( ...
                simulationWide.AverageNeighborCount)));
            testCase.verifyGreaterThanOrEqual( ...
                simulationWide.AverageNeighborCount, 0);
            testCase.verifyLessThanOrEqual( ...
                simulationWide.AverageNeighborCount, ...
                testCase.VehicleCount - 1);

            overTime = readtable(fullfile( ...
                outputDirectory, ...
                "average_neighbor_count_over_time_" + ...
                    technology + ".csv"));
            testCase.verifyEqual( ...
                string(overTime.Properties.VariableNames), ...
                ["SimulationTimeSeconds", ...
                    "AwarenessRangeLowerBoundMeters", ...
                    "AwarenessRangeUpperBoundMeters", ...
                    "AverageNeighborCount"]);
            testCase.verifyGreaterThan(height(overTime), 0);
            testCase.verifyTrue(all( ...
                overTime.SimulationTimeSeconds >= 0 & ...
                overTime.SimulationTimeSeconds <= ...
                    testCase.SimulationDurationSeconds));
            testCase.verifyTrue(all( ...
                diff(overTime.SimulationTimeSeconds) >= 0));
            actualBounds = unique(overTime{:, 2:3}, "rows");
            testCase.verifyEqual(actualBounds, expectedBounds);
            testCase.verifyTrue(all(isfinite( ...
                overTime.AverageNeighborCount)));
            testCase.verifyGreaterThanOrEqual( ...
                overTime.AverageNeighborCount, 0);
            testCase.verifyLessThanOrEqual( ...
                overTime.AverageNeighborCount, ...
                testCase.VehicleCount - 1);
        end

        function verifyTechnologyArtifacts( ...
                testCase, outputDirectory, technology)
            delayPrefixes = [ ...
                "packet_delay", "update_delay", "data_age"];
            for prefix = delayPrefixes
                testCase.verifyThreeColumnDistribution(fullfile( ...
                    outputDirectory, ...
                    prefix + "_" + technology + ".csv"));
            end

            wirelessBlindSpot = readmatrix(fullfile( ...
                outputDirectory, ...
                "wireless_blind_spot_" + technology + ".csv"));
            rangeCount = ...
                numel(testCase.AwarenessRangesMeters);
            testCase.verifySize( ...
                wirelessBlindSpot, ...
                [size(wirelessBlindSpot, 1), ...
                    1 + 3 * rangeCount]);
            testCase.verifyGreaterThan( ...
                size(wirelessBlindSpot, 1), 0);
            testCase.verifyTrue(all(isfinite( ...
                wirelessBlindSpot(:, 1)), "all"));
            testCase.verifyGreaterThan( ...
                wirelessBlindSpot(:, 1), 0);
            testCase.verifyTrue(all(diff( ...
                wirelessBlindSpot(:, 1)) > 0));
            for rangeIndex = 1:rangeCount
                greaterOrEqualColumn = 2 + ...
                    3 * (rangeIndex - 1);
                shorterColumn = greaterOrEqualColumn + 1;
                probabilityColumn = greaterOrEqualColumn + 2;
                greaterOrEqual = wirelessBlindSpot( ...
                    :, greaterOrEqualColumn);
                shorter = wirelessBlindSpot(:, shorterColumn);
                probability = wirelessBlindSpot( ...
                    :, probabilityColumn);
                denominator = greaterOrEqual + shorter;

                testCase.verifyTrue(all(isfinite( ...
                    [greaterOrEqual, shorter]), "all"));
                testCase.verifyGreaterThanOrEqual( ...
                    [greaterOrEqual, shorter], 0);
                testCase.verifyEqual( ...
                    [greaterOrEqual, shorter], ...
                    round([greaterOrEqual, shorter]));
                hasDenominator = denominator > 0;
                testCase.verifyEqual( ...
                    probability(hasDenominator), ...
                    greaterOrEqual(hasDenominator) ./ ...
                        denominator(hasDenominator), ...
                    AbsTol=5e-7);
                testCase.verifyTrue(all(isnan( ...
                    probability(~hasDenominator))));
            end

            testCase.verifyCbrStatistic(fullfile( ...
                outputDirectory, ...
                "CBRstatistic_" + technology + ".csv"));
            genericCbr = readmatrix(fullfile( ...
                outputDirectory, ...
                "CBRofGenericVehicle_" + technology + ".csv"));
            testCase.verifySize( ...
                genericCbr, [size(genericCbr, 1), 2]);
            testCase.verifyGreaterThan(size(genericCbr, 1), 0);
            testCase.verifyTrue(all(isfinite(genericCbr), "all"));
            testCase.verifyGreaterThanOrEqual(genericCbr, 0);
            testCase.verifyLessThanOrEqual(genericCbr(:, 2), 1);
        end

        function verifyThreeColumnDistribution(testCase, filename)
            output = readmatrix(filename);
            rangeCount = numel(testCase.AwarenessRangesMeters);
            if rangeCount == 1
                expectedColumnCount = 3;
            else
                expectedColumnCount = 1 + ...
                    2 * rangeCount + 2;
            end
            testCase.verifySize( ...
                output, ...
                [size(output, 1), expectedColumnCount]);
            testCase.verifyGreaterThan(size(output, 1), 0);
            testCase.verifyTrue(all(isfinite(output(:, 1))));
            testCase.verifyGreaterThan(output(:, 1), 0);
            testCase.verifyTrue(all(diff(output(:, 1)) > 0));

            countColumns = 2:2:(1 + 2 * rangeCount);
            probabilityColumns = countColumns + 1;
            testCase.verifyTrue(all(isfinite( ...
                output(:, countColumns)), "all"));
            testCase.verifyGreaterThanOrEqual( ...
                output(:, countColumns), 0);
            testCase.verifyEqual( ...
                output(:, countColumns), ...
                round(output(:, countColumns)));
            for rangeIndex = 1:rangeCount
                probabilityColumn = ...
                    probabilityColumns(rangeIndex);
                probability = output(:, probabilityColumn);
                totalCount = sum(output( ...
                    :, countColumns(rangeIndex)));
                if totalCount == 0
                    testCase.verifyTrue(all(isnan(probability)));
                else
                    testCase.verifyTrue(all(isfinite(probability)));
                    testCase.verifyGreaterThanOrEqual( ...
                        probability, 0);
                    testCase.verifyLessThanOrEqual( ...
                        probability, 1);
                    testCase.verifyTrue(all(diff( ...
                        probability) >= 0));
                    testCase.verifyEqual( ...
                        probability(end), 1, AbsTol=5e-7);
                end
            end

            if rangeCount > 1
                aggregateCountColumn = expectedColumnCount - 1;
                aggregateProbabilityColumn = expectedColumnCount;
                testCase.verifyEqual( ...
                    output(:, aggregateCountColumn), ...
                    sum(output(:, countColumns), 2));
                aggregateProbability = ...
                    output(:, aggregateProbabilityColumn);
                testCase.verifyTrue(all(isfinite( ...
                    aggregateProbability)));
                testCase.verifyGreaterThanOrEqual( ...
                    aggregateProbability, 0);
                testCase.verifyLessThanOrEqual( ...
                    aggregateProbability, 1);
                testCase.verifyTrue(all(diff( ...
                    aggregateProbability) >= 0));
            end
        end

        function verifyCbrStatistic(testCase, filename)
            output = readmatrix(filename);
            testCase.verifySize(output, [size(output, 1), 2]);
            testCase.verifyGreaterThan(size(output, 1), 0);
            testCase.verifyTrue(all(isfinite(output), "all"));
            testCase.verifyGreaterThanOrEqual(output, 0);
            testCase.verifyLessThanOrEqual(output, 1);
            testCase.verifyTrue(all(diff(output(:, 1)) >= 0));
        end

        function verifyCountsReconcile( ...
                testCase, outputDirectory, summary, specification)
            rangeCount = numel(testCase.AwarenessRangesMeters);
            cellularCounts = zeros(rangeCount, 3);
            ieee80211pCounts = zeros(rangeCount, 3);

            if specification.CellularUeCount > 0
                cellularCounts = testCase.verifyPrrArtifact( ...
                    outputDirectory, ...
                    specification.CellularTechnologyToken);
                testCase.verifyResultCounts( ...
                    summary.Results.CellularSidelink, ...
                    cellularCounts);
            end
            if specification.Ieee80211pUeCount > 0
                ieee80211pCounts = testCase.verifyPrrArtifact( ...
                    outputDirectory, "11p");
                testCase.verifyResultCounts( ...
                    summary.Results.Ieee80211p, ...
                    ieee80211pCounts);
            end

            combinedCounts = cellularCounts + ieee80211pCounts;
            testCase.verifyResultCounts( ...
                summary.Results.Combined, combinedCounts);
            testCase.verifyGreaterThan(sum(combinedCounts, "all"), 0, ...
                "The test run must exercise real packet fates.");
        end

        function countsByRange = verifyPrrArtifact( ...
                testCase, outputDirectory, technology)
            output = readmatrix(fullfile( ...
                outputDirectory, ...
                "packet_reception_ratio_" + technology + ".csv"));
            testCase.verifySize(output, [size(output, 1), 6]);
            testCase.verifyGreaterThan(size(output, 1), 0);
            testCase.verifyTrue(all(isfinite(output(:, 1:5)), "all"));
            testCase.verifyEqual( ...
                output(:, 1), ...
                (1:size(output, 1)).' .* ...
                    testCase.DistanceBinWidthMeters);
            testCase.verifyGreaterThanOrEqual(output(:, 2:5), 0);
            testCase.verifyEqual( ...
                output(:, 2:5), round(output(:, 2:5)));
            testCase.verifyEqual( ...
                output(:, 5), sum(output(:, 2:4), 2), ...
                "Correct + error + blocked must equal total.");

            nonemptyBins = output(:, 5) > 0;
            testCase.verifyEqual( ...
                output(nonemptyBins, 6), ...
                output(nonemptyBins, 2) ./ ...
                    output(nonemptyBins, 5), ...
                AbsTol=5e-7);
            testCase.verifyTrue(all(isnan( ...
                output(~nonemptyBins, 6))));

            rangeCount = numel(testCase.AwarenessRangesMeters);
            countsByRange = zeros(rangeCount, 3);
            lowerBound = 0;
            for rangeIndex = 1:rangeCount
                upperBound = ...
                    testCase.AwarenessRangesMeters(rangeIndex);
                isInRange = ...
                    output(:, 1) > lowerBound & ...
                    output(:, 1) <= upperBound;
                countsByRange(rangeIndex, :) = ...
                    sum(output(isInRange, 2:4), 1);
                lowerBound = upperBound;
            end
            testCase.verifyGreaterThan(sum(countsByRange, "all"), 0);
        end

        function verifyResultCounts(testCase, result, countsByRange)
            metrics = result.AwarenessRangeMetrics;
            testCase.verifyNumElements( ...
                metrics, numel(testCase.AwarenessRangesMeters));
            lowerBound = 0;
            for rangeIndex = 1:numel( ...
                    testCase.AwarenessRangesMeters)
                metric = testCase.metricAt(metrics, rangeIndex);
                upperBound = ...
                    testCase.AwarenessRangesMeters(rangeIndex);
                correctCount = countsByRange(rangeIndex, 1);
                errorCount = countsByRange(rangeIndex, 2);
                blockedCount = countsByRange(rangeIndex, 3);
                nonblockedCount = correctCount + errorCount;
                totalCount = nonblockedCount + blockedCount;

                testCase.verifyEqual( ...
                    metric.AwarenessRangeLowerBoundMeters, ...
                    lowerBound);
                testCase.verifyEqual( ...
                    metric.AwarenessRangeUpperBoundMeters, ...
                    upperBound);
                testCase.verifyEqual( ...
                    metric. ...
                        NonblockedTransmitterReceiverOpportunityCount, ...
                    nonblockedCount);
                testCase.verifyNullableRatio( ...
                    metric.BlockingRate, blockedCount, totalCount);
                testCase.verifyNullableRatio( ...
                    metric.ErrorRate, errorCount, nonblockedCount);
                testCase.verifyNullableRatio( ...
                    metric.PacketReceptionRatio, ...
                    correctCount, nonblockedCount);
                lowerBound = upperBound;
            end
        end

        function verifyNullableRatio( ...
                testCase, actualValue, numerator, denominator)
            if denominator == 0
                testCase.verifyEmpty(actualValue);
            else
                testCase.verifyEqual( ...
                    actualValue, numerator / denominator, ...
                    AbsTol=1e-12);
            end
        end

        function verifyOnlySummaryExists(testCase, outputDirectory)
            listing = dir(outputDirectory);
            actualFiles = string({listing(~[listing.isdir]).name});
            testCase.verifyEqual( ...
                actualFiles, "simulation_summary.json");
            testCase.verifyFalse(isfile(fullfile( ...
                outputDirectory, ".v2xsim-output-lock")));
            testCase.verifyFalse(isfolder(fullfile( ...
                outputDirectory, ".v2xsim-output-lock")));
        end
    end

    methods (Static, Access = private)
        function projectRoot = projectRoot()
            projectRoot = string(fileparts(fileparts(fileparts( ...
                fileparts(mfilename("fullpath"))))));
        end

        function specification = specification(radioAccessMode)
            specification = struct( ...
                RadioAccessMode=radioAccessMode, ...
                DirectoryToken="", ...
                TechnologyTokens=strings(1, 0), ...
                NeighborTokens=strings(1, 0), ...
                CellularTechnologyToken="", ...
                CellularUeCount=0, ...
                Ieee80211pUeCount=0, ...
                IsCoexistence=false);
            switch radioAccessMode
                case "80211p"
                    specification.DirectoryToken = "ieee80211p";
                    specification.TechnologyTokens = "11p";
                    specification.NeighborTokens = "itsg5";
                    specification.Ieee80211pUeCount = 6;
                case "LTE-V2X"
                    specification.DirectoryToken = "lte-v2x";
                    specification.TechnologyTokens = "LTE";
                    specification.NeighborTokens = "cv2x";
                    specification.CellularTechnologyToken = "LTE";
                    specification.CellularUeCount = 6;
                case "NR-V2X"
                    specification.DirectoryToken = "nr-v2x";
                    specification.TechnologyTokens = "5G";
                    specification.NeighborTokens = "cv2x";
                    specification.CellularTechnologyToken = "5G";
                    specification.CellularUeCount = 6;
                case "COEX-NO-INTERF"
                    specification.DirectoryToken = ...
                        "coexistence-orthogonal";
                    specification.TechnologyTokens = ...
                        ["LTE", "11p"];
                    specification.NeighborTokens = ...
                        ["all", "cv2x", "itsg5"];
                    specification.CellularTechnologyToken = "LTE";
                    specification.CellularUeCount = 3;
                    specification.Ieee80211pUeCount = 3;
                    specification.IsCoexistence = true;
                otherwise
                    error( ...
                        "v2xsimtest:integration:" + ...
                            "UnsupportedRadioAccessMode", ...
                        "Unsupported radio-access mode %s.", ...
                        radioAccessMode);
            end
        end

        function summary = semanticSummary(summary)
            summary.Run = rmfield( ...
                summary.Run, ...
                ["CompletedAtUtc", "ComputationDurationSeconds"]);
        end

        function metric = metricAt(metrics, index)
            if iscell(metrics)
                metric = metrics{index};
            else
                metric = metrics(index);
            end
        end
    end
end

function restoreGlobalRandomStream(stream,state)
RandStream.setGlobalStream(stream);
stream.State = state;
end
