classdef ScenarioRadioCompatibilityTest < matlab.unittest.TestCase
    %SCENARIORADIOCOMPATIBILITYTEST Full scenario/radio integration matrix.

    properties (TestParameter)
        ScenarioType = { ...
            "BrownianMotionScenario", ...
            "BidirectionalHighwayScenario", ...
            "EtsiHighwayScenario", ...
            "ExitRampHighwayScenario"}
        RadioAccessMode = { ...
            "LTE-V2X", ...
            "NR-V2X", ...
            "80211p", ...
            "COEX-NO-INTERF", ...
            "COEX-STD-INTERF", ...
            "COEX-STD-INTERF-5G"}
    end

    properties (SetAccess = private)
        TemporaryDirectory (1, 1) string
    end

    methods (TestClassSetup)
        function createTemporaryDirectory(testCase)
            temporaryFolder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            testCase.TemporaryDirectory = string(temporaryFolder.Folder);
        end
    end

    methods (TestMethodSetup)
        function isolateProcessWideState(testCase)
            originalPath = path;
            originalStream = RandStream.getGlobalStream();
            originalStreamState = originalStream.State;
            originalWarnings = warning;
            testCase.addTeardown(@() path(originalPath));
            testCase.addTeardown(@() restoreGlobalRandomStream( ...
                originalStream,originalStreamState));
            testCase.addTeardown(@() warning(originalWarnings));

            projectRoot = testCase.projectRoot();
            addpath(fullfile(projectRoot, "src"));
            addpath(fullfile(projectRoot, "old_src"));
        end
    end

    methods (Test)
        function testScenarioSupportsRadioMode( ...
                testCase, ScenarioType, RadioAccessMode)
            scenarioType = string(ScenarioType);
            radioAccessMode = string(RadioAccessMode);
            [scenarioArguments, expectedUeCount] = ...
                testCase.configurationForScenario(scenarioType);
            expectation = testCase.expectationForRadioMode( ...
                radioAccessMode, expectedUeCount);

            runLabel = scenarioType + "::" + radioAccessMode;
            outputDirectory = fullfile( ...
                testCase.TemporaryDirectory, ...
                lower(scenarioType) + "__" + lower(radioAccessMode));
            configurationFile = fullfile( ...
                testCase.projectRoot(), "old_src", "ConfigFiles", ...
                "EtsiHighwayMediumMode1.cfg");
            simulationArguments = { ...
                configurationFile, ...
                "simulation.RandomSeed", 711, ...
                "simulation.DurationSeconds", 0.3, ...
                "simulation.RadioAccessMode", radioAccessMode, ...
                "simulation.RunLabel", runLabel, ...
                "scenario.Type", scenarioType, ...
                "scenario.UpdateIntervalSeconds", 0.1, ...
                "scenarioOptions.RandomSeed", 733, ...
                "output.Directory", outputDirectory, ...
                "output.PacketReceptionRatio.Enabled", false, ...
                "output.VehicleKinematics.Enabled", false, ...
                "output.UpdateDelay.Enabled", false, ...
                "output.PacketDelay.Enabled", false, ...
                "output.DataAge.Enabled", false, ...
                "output.WirelessBlindSpot.Enabled", false, ...
                "output.AverageNeighborCount.Enabled", false, ...
                "output.ChannelBusyRatio.Enabled", false};
            if expectation.CoexistenceActive
                coexistenceArguments = { ...
                    "coexistence.VehiclePattern.SidelinkVehicleCount", ...
                        expectation.CellularUeCount, ...
                    "coexistence.VehiclePattern.ItsG5VehicleCount", ...
                        expectation.Ieee80211pUeCount};
            else
                coexistenceArguments = cell(1, 0);
            end
            simulationArguments = [ ...
                simulationArguments, scenarioArguments, ...
                coexistenceArguments]; %#ok<NASGU>

            evalc("v2xsim.runSimulation(simulationArguments{:});");

            summaryFile = fullfile( ...
                outputDirectory, "simulation_summary.json");
            testCase.assertTrue( ...
                isfile(summaryFile), ...
                "A completed run must publish its summary.");
            testCase.verifyFalse(isfile(fullfile( ...
                outputDirectory, "error_log.txt")));
            testCase.verifyFalse(isfolder(fullfile( ...
                outputDirectory, ".v2xsim-output-lock")));

            jsonText = string(fileread(summaryFile));
            testCase.verifyFalse(contains(jsonText, "NaN"));
            testCase.verifyFalse(contains(jsonText, "Infinity"));
            summary = jsondecode(jsonText);

            testCase.verifySummaryProvenance( ...
                summary, scenarioType, radioAccessMode, runLabel, ...
                configurationFile);
            testCase.verifyTechnologyConfiguration(summary, expectation);
            testCase.verifyTechnologyResults( ...
                summary.Results, expectation, expectedUeCount);
        end
    end

    methods (Access = private)
        function verifySummaryProvenance( ...
                testCase, summary, scenarioType, radioAccessMode, ...
                runLabel, configurationFile)
            requiredFields = [ ...
                "SchemaVersion", "Run", "Configuration", "Results"];
            testCase.verifyTrue(all(isfield( ...
                summary, cellstr(requiredFields))));
            testCase.verifyEqual(summary.SchemaVersion, 2);
            testCase.verifyEqual( ...
                string(summary.Run.SimulatorVersion), "V7");
            testCase.verifyEqual(summary.Run.RandomSeed, 711);
            testCase.verifyEqual( ...
                summary.Run.SimulatedDurationSeconds, 0.3, ...
                AbsTol=eps(0.3));
            testCase.verifyGreaterThanOrEqual( ...
                summary.Run.ComputationDurationSeconds, 0);
            testCase.verifyTrue( ...
                isfinite(summary.Run.ComputationDurationSeconds));
            testCase.verifyNotEmpty( ...
                regexp( ...
                    string(summary.Run.CompletedAtUtc), ...
                    "^\d{4}-\d{2}-\d{2}T", ...
                    "once"));
            testCase.verifyEqual(string(summary.Run.RunLabel), runLabel);
            testCase.verifyEqual( ...
                string(summary.Run.ConfigurationFile), ...
                string(configurationFile));
            testCase.verifyEqual( ...
                string(summary.Configuration.RadioAccessMode), ...
                radioAccessMode);
            testCase.verifyEqual( ...
                string(summary.Configuration.Scenario.Type), ...
                scenarioType);
        end

        function verifyTechnologyConfiguration( ...
                testCase, summary, expectation)
            configuration = summary.Configuration;
            testCase.verifyEqual( ...
                logical(configuration.CellularSidelink.Active), ...
                expectation.CellularActive);
            testCase.verifyEqual( ...
                logical(configuration.ResourcePool.Active), ...
                expectation.CellularActive);
            testCase.verifyEqual( ...
                logical(configuration.Ieee80211p.Active), ...
                expectation.Ieee80211pActive);
            testCase.verifyEqual( ...
                logical(configuration.Coexistence.Active), ...
                expectation.CoexistenceActive);
            testCase.verifyEqual( ...
                string(configuration.CellularSidelink.Technology), ...
                expectation.CellularTechnology);
            testCase.verifyEqual( ...
                string(configuration.Coexistence.InterferenceMode), ...
                expectation.InterferenceMode);

            if expectation.CoexistenceActive
                testCase.verifyEqual( ...
                    configuration.Coexistence. ...
                    CellularSidelinkVehicleGroupSize, ...
                    expectation.CellularUeCount);
                testCase.verifyEqual( ...
                    configuration.Coexistence. ...
                    Ieee80211pVehicleGroupSize, ...
                    expectation.Ieee80211pUeCount);
            else
                testCase.verifyEmpty( ...
                    configuration.Coexistence. ...
                    CellularSidelinkVehicleGroupSize);
                testCase.verifyEmpty( ...
                    configuration.Coexistence. ...
                    Ieee80211pVehicleGroupSize);
            end
        end

        function verifyTechnologyResults( ...
                testCase, results, expectation, expectedUeCount)
            requiredFields = [ ...
                "CellularSidelink", "Ieee80211p", "Combined"];
            testCase.verifyTrue(all(isfield( ...
                results, cellstr(requiredFields))));
            testCase.verifyResultPartition( ...
                results.CellularSidelink, ...
                expectation.CellularActive, ...
                expectation.CellularUeCount, ...
                "MeanSnapshotNeighborCountStandardDeviation", ...
                expectation.CellularActive);
            testCase.verifyResultPartition( ...
                results.Ieee80211p, ...
                expectation.Ieee80211pActive, ...
                expectation.Ieee80211pUeCount, ...
                "MeanSnapshotNeighborCountStandardDeviation", ...
                expectation.Ieee80211pActive);
            testCase.verifyResultPartition( ...
                results.Combined, true, expectedUeCount, ...
                "MeanSnapshotSumOfTechnologyNeighborCount" + ...
                "StandardDeviations", false);

            testCase.verifyEqual( ...
                results.Combined.AverageUeCount, ...
                results.CellularSidelink.AverageUeCount + ...
                results.Ieee80211p.AverageUeCount, ...
                AbsTol=1e-12);
            testCase.verifyEqual( ...
                string(results.Combined.ChannelBusyRatio.Status), ...
                "NotApplicable");

            testCase.verifyFiniteOrUnavailable( ...
                results.CellularSidelink. ...
                AverageSuccessfulReassignmentsPerUePerSecond, ...
                "Cellular reassignment rate");
            testCase.verifyFiniteOrUnavailable( ...
                results.CellularSidelink. ...
                AverageInitialTransmissionsPerUePerSecond, ...
                "Cellular initial-transmission rate");
            testCase.verifyFiniteOrUnavailable( ...
                results.CellularSidelink. ...
                AverageTransmissionsPerPacketIncludingHarq, ...
                "Cellular HARQ transmission ratio");
            testCase.verifyFiniteOrUnavailable( ...
                results.Ieee80211p.AverageTransmissionOpportunityRate. ...
                PerUePerNeighborPerSecond, ...
                "IEEE 802.11p transmission-opportunity rate");
        end

        function verifyResultPartition( ...
                testCase, partition, expectedActive, ...
                expectedUeCount, dispersionField, ...
                expectTechnologyChannelBusyRatio)
            testCase.verifyEqual( ...
                logical(partition.Active), expectedActive);
            testCase.verifyEqual( ...
                partition.AverageUeCount, expectedUeCount, ...
                AbsTol=1e-12);
            testCase.verifyTrue( ...
                isfinite(partition.AverageUeCount) && ...
                partition.AverageUeCount >= 0);

            if ~expectedActive
                testCase.verifyEmpty(partition.AwarenessRangeMetrics);
                testCase.verifyEqual( ...
                    string(partition.ChannelBusyRatio.Status), ...
                    "NotApplicable");
                return
            end

            metrics = partition.AwarenessRangeMetrics;
            testCase.verifyNotEmpty(metrics);
            for metricIndex = 1:numel(metrics)
                metric = metrics(metricIndex);
                requiredFields = [ ...
                    "AwarenessRangeLowerBoundMeters", ...
                    "AwarenessRangeUpperBoundMeters", ...
                    "AverageNeighborCount", ...
                    "NonblockedTransmitterReceiverOpportunityCount", ...
                    "BlockingRate", ...
                    "ErrorRate", ...
                    "PacketReceptionRatio", ...
                    dispersionField];
                testCase.verifyTrue(all(isfield( ...
                    metric, cellstr(requiredFields))));

                testCase.verifyFiniteNonnegative( ...
                    metric.AwarenessRangeLowerBoundMeters, ...
                    "Awareness-range lower bound");
                testCase.verifyFiniteNonnegative( ...
                    metric.AwarenessRangeUpperBoundMeters, ...
                    "Awareness-range upper bound");
                testCase.verifyGreaterThan( ...
                    metric.AwarenessRangeUpperBoundMeters, ...
                    metric.AwarenessRangeLowerBoundMeters);
                testCase.verifyFiniteNonnegative( ...
                    metric.AverageNeighborCount, ...
                    "Average neighbor count");
                testCase.verifyFiniteNonnegative( ...
                    metric.NonblockedTransmitterReceiverOpportunityCount, ...
                    "Nonblocked opportunity count");
                testCase.verifyEqual( ...
                    metric.NonblockedTransmitterReceiverOpportunityCount, ...
                    round(metric. ...
                    NonblockedTransmitterReceiverOpportunityCount));
                testCase.verifyFiniteNonnegative( ...
                    metric.(dispersionField), ...
                    "Neighbor-count dispersion");
                testCase.verifyProbabilityOrUnavailable( ...
                    metric.BlockingRate, "Blocking rate");
                testCase.verifyProbabilityOrUnavailable( ...
                    metric.ErrorRate, "Error rate");
                testCase.verifyProbabilityOrUnavailable( ...
                    metric.PacketReceptionRatio, ...
                    "Packet reception ratio");

                if ~isempty(metric.ErrorRate) && ...
                        ~isempty(metric.PacketReceptionRatio)
                    testCase.verifyEqual( ...
                        metric.ErrorRate + ...
                        metric.PacketReceptionRatio, ...
                        1, AbsTol=1e-12);
                end
            end

            if expectTechnologyChannelBusyRatio
                testCase.verifyChannelBusyRatio( ...
                    partition.ChannelBusyRatio);
            else
                testCase.verifyEqual( ...
                    string(partition.ChannelBusyRatio.Status), ...
                    "NotApplicable");
                testCase.verifyEmpty( ...
                    partition.ChannelBusyRatio.Channels);
            end
        end

        function verifyChannelBusyRatio(testCase, channelBusyRatio)
            allowedStatuses = [ ...
                "Available", ...
                "Disabled", ...
                "NoEligibleUes", ...
                "InsufficientSamples", ...
                "NoValidSamples"];
            testCase.verifyTrue(ismember( ...
                string(channelBusyRatio.Status), allowedStatuses));
            testCase.verifyFiniteNonnegative( ...
                channelBusyRatio.WarmupSampleCountRequired, ...
                "Channel-load warmup sample count");
            testCase.verifyNotEmpty(channelBusyRatio.Channels);

            channels = channelBusyRatio.Channels;
            for channelIndex = 1:numel(channels)
                channel = channels(channelIndex);
                testCase.verifyFiniteNonnegative( ...
                    channel.ChannelIndex, "Channel index");
                testCase.verifyTrue(ismember( ...
                    string(channel.Status), allowedStatuses));
                testCase.verifyProbabilityOrUnavailable( ...
                    channel.MedianRatio, ...
                    "Median channel-busy ratio");
                if string(channel.Status) == "Available"
                    testCase.verifyNotEmpty(channel.MedianRatio);
                end
            end
        end

        function verifyProbabilityOrUnavailable( ...
                testCase, value, description)
            if isempty(value)
                return
            end
            testCase.verifyTrue( ...
                isnumeric(value) && isscalar(value) && ...
                isfinite(value) && value >= 0 && value <= 1, ...
                description + ...
                " must be finite in [0, 1] or JSON null.");
        end

        function verifyFiniteOrUnavailable( ...
                testCase, value, description)
            if isempty(value)
                return
            end
            testCase.verifyTrue( ...
                isnumeric(value) && isscalar(value) && ...
                isfinite(value), ...
                description + " must be finite or JSON null.");
        end

        function verifyFiniteNonnegative( ...
                testCase, value, description)
            testCase.verifyTrue( ...
                isnumeric(value) && isscalar(value) && ...
                isfinite(value) && value >= 0, ...
                description + ...
                " must be a finite nonnegative scalar.");
        end
    end

    methods (Static, Access = private)
        function projectRoot = projectRoot()
            projectRoot = string(fileparts(fileparts(fileparts( ...
                fileparts(mfilename("fullpath"))))));
        end

        function [scenarioArguments, expectedUeCount] = ...
                configurationForScenario(scenarioType)
            switch scenarioType
                case "BrownianMotionScenario"
                    expectedUeCount = 6;
                    scenarioArguments = { ...
                        "scenarioOptions.VehicleCount", ...
                            expectedUeCount, ...
                        "scenarioOptions.SimulationAreaSize", 200, ...
                        "scenarioOptions.MeanVehicleSpeed", 10, ...
                        "scenarioOptions.VehicleSpeedStandardDeviation", ...
                            0};

                case "BidirectionalHighwayScenario"
                    expectedUeCount = 6;
                    scenarioArguments = ...
                        v2xsimtest.integration. ...
                        ScenarioRadioCompatibilityTest. ...
                        highwayScenarioArguments(expectedUeCount);

                case "EtsiHighwayScenario"
                    expectedUeCount = 72;
                    scenarioArguments = { ...
                        "scenarioOptions.TrafficModel", ...
                            "HighSpeedLowDensity", ...
                        "scenarioOptions.Placement", "Uniform", ...
                        "scenarioOptions.MinimumRoadLength", 2000};

                case "ExitRampHighwayScenario"
                    expectedUeCount = 6;
                    scenarioArguments = [ ...
                        v2xsimtest.integration. ...
                        ScenarioRadioCompatibilityTest. ...
                        highwayScenarioArguments(expectedUeCount), { ...
                        "scenarioOptions.ExitProbability", 0.5, ...
                        "scenarioOptions.MergeDistance", 25}];

                otherwise
                    error( ...
                        "v2xsimtest:integration:UnknownScenario", ...
                        "Unknown scenario type: %s.", scenarioType);
            end
        end

        function scenarioArguments = ...
                highwayScenarioArguments(expectedUeCount)
            scenarioArguments = { ...
                "scenarioOptions.VehicleCount", expectedUeCount, ...
                "scenarioOptions.NLanes", 2, ...
                "scenarioOptions.LaneWidth", 4, ...
                "scenarioOptions.RoadLength", 200, ...
                "scenarioOptions.CentralDividerWidth", 0, ...
                "scenarioOptions.MeanVehicleSpeed", 10, ...
                "scenarioOptions.VehicleSpeedStandardDeviation", 0, ...
                "scenarioOptions.RerollSpeedOnWrapAround", false};
        end

        function expectation = expectationForRadioMode( ...
                radioAccessMode, expectedUeCount)
            coexistenceActive = startsWith( ...
                radioAccessMode, "COEX-");
            cellularActive = radioAccessMode ~= "80211p";
            ieee80211pActive = ...
                radioAccessMode == "80211p" || coexistenceActive;

            if coexistenceActive
                cellularUeCount = expectedUeCount / 2;
                ieee80211pUeCount = expectedUeCount / 2;
            elseif cellularActive
                cellularUeCount = expectedUeCount;
                ieee80211pUeCount = 0;
            else
                cellularUeCount = 0;
                ieee80211pUeCount = expectedUeCount;
            end

            if ismember(radioAccessMode, [ ...
                    "NR-V2X", "COEX-STD-INTERF-5G"])
                cellularTechnology = "NR-V2X";
            elseif cellularActive
                cellularTechnology = "LTE-V2X";
            else
                cellularTechnology = "";
            end

            if radioAccessMode == "COEX-NO-INTERF"
                interferenceMode = "Orthogonal";
            elseif coexistenceActive
                interferenceMode = "SharedChannel";
            else
                interferenceMode = "NotApplicable";
            end

            expectation = struct( ...
                CellularActive=cellularActive, ...
                Ieee80211pActive=ieee80211pActive, ...
                CoexistenceActive=coexistenceActive, ...
                CellularTechnology=cellularTechnology, ...
                InterferenceMode=interferenceMode, ...
                CellularUeCount=cellularUeCount, ...
                Ieee80211pUeCount=ieee80211pUeCount);
        end
    end
end

function restoreGlobalRandomStream(stream,state)
RandStream.setGlobalStream(stream);
stream.State = state;
end
