classdef ServiceContainer < handle
    %SERVICECONTAINER Provides dependencies used to build hooks.
    %   Constants are value dependencies. Class providers construct a new
    %   zero-argument instance for every resolution. Instance providers
    %   retain one shared handle dependency.

    properties (Access = private)
        Providers
    end

    methods
        function obj = ServiceContainer()
            obj.Providers = containers.Map( ...
                "KeyType", "char", ...
                "ValueType", "any");
        end

        function provideConstant(obj, dependencyType, value)
            %PROVIDECONSTANT Bind a value dependency.
            arguments (Input)
                obj (1, 1)
                dependencyType
                value (1, 1)
            end

            obj.validateDependencyType(dependencyType);
            obj.validateAssignable( ...
                dependencyType, value, "constant");
            if isa(value, "handle")
                error( ...
                    "v2xsim:hook:dependency:HandleConstant", ...
                    "A constant dependency must be a value object. " + ...
                    "Use provideInstance for a shared handle.");
            end

            obj.setProvider( ...
                dependencyType, ...
                struct(Kind="constant", Payload=value));
        end

        function provideClass( ...
                obj, dependencyType, implementationClassName)
            %PROVIDECLASS Bind a transient zero-argument implementation.
            arguments (Input)
                obj (1, 1)
                dependencyType
                implementationClassName {mustBeTextScalar}
            end

            obj.validateDependencyType(dependencyType);
            implementationClassName = string( ...
                implementationClassName);
            implementationType = meta.class.fromName( ...
                implementationClassName);
            if isempty(implementationType)
                error( ...
                    "v2xsim:hook:dependency:UnknownClass", ...
                    "Dependency implementation class %s was not found.", ...
                    implementationClassName);
            end
            if ~(implementationType <= dependencyType)
                error( ...
                    "v2xsim:hook:dependency:IncompatibleClass", ...
                    "%s is not an implementation of dependency %s.", ...
                    implementationClassName, dependencyType.Name);
            end
            if implementationType.Abstract
                error( ...
                    "v2xsim:hook:dependency:AbstractClass", ...
                    "Dependency implementation class %s is abstract.", ...
                    implementationClassName);
            end

            obj.setProvider( ...
                dependencyType, ...
                struct( ...
                    Kind="class", ...
                    Payload=implementationClassName));
        end

        function provideInstance(obj, dependencyType, instance)
            %PROVIDEINSTANCE Bind one shared handle dependency.
            arguments (Input)
                obj (1, 1)
                dependencyType
                instance (1, 1)
            end

            obj.validateDependencyType(dependencyType);
            obj.validateAssignable( ...
                dependencyType, instance, "instance");
            if ~isa(instance, "handle")
                error( ...
                    "v2xsim:hook:dependency:ValueInstance", ...
                    "A singleton dependency must be a handle object. " + ...
                    "Use provideConstant for a value object.");
            end
            if ~isvalid(instance)
                error( ...
                    "v2xsim:hook:dependency:DeletedInstance", ...
                    "A deleted handle cannot be provided as a dependency.");
            end

            obj.setProvider( ...
                dependencyType, ...
                struct(Kind="instance", Payload=instance));
        end

        function dependency = resolve(obj, dependencyType)
            %RESOLVE Resolve one dependency.
            arguments (Input)
                obj (1, 1)
                dependencyType
            end

            obj.validateDependencyType(dependencyType);
            key = char(dependencyType.Name);
            if ~isKey(obj.Providers, key)
                error( ...
                    "v2xsim:hook:dependency:NotProvided", ...
                    "No provider is configured for dependency %s.", ...
                    dependencyType.Name);
            end

            provider = obj.Providers(key);
            switch provider.Kind
                case "constant"
                    dependency = provider.Payload;
                case "class"
                    dependency = obj.construct( ...
                        dependencyType, provider.Payload);
                case "instance"
                    dependency = provider.Payload;
                otherwise
                    error( ...
                        "v2xsim:hook:dependency:InvalidProvider", ...
                        "Dependency %s has an invalid provider.", ...
                        dependencyType.Name);
            end

            obj.validateAssignable( ...
                dependencyType, dependency, "resolved value");
            if isa(dependency, "handle") && ~isvalid(dependency)
                error( ...
                    "v2xsim:hook:dependency:DeletedInstance", ...
                    "The resolved instance for dependency %s " + ...
                    "has been deleted.", ...
                    dependencyType.Name);
            end
        end

        function dependencies = resolveAll(obj, dependencyTypes)
            %RESOLVEALL Resolve dependencies in the requested order.
            arguments (Input)
                obj (1, 1)
                dependencyTypes
            end
            arguments (Output)
                dependencies (1, :) cell
            end

            if ~isa( ...
                    dependencyTypes, ...
                    "matlab.metadata.Class") || ...
                    (~isempty(dependencyTypes) && ...
                    ~isrow(dependencyTypes))
                error( ...
                    "v2xsim:hook:dependency:InvalidDependencyType", ...
                    "Requested dependencies must be a row array of " + ...
                    "class metadata objects.");
            end

            dependencies = cell(1, numel(dependencyTypes));
            for dependencyIndex = 1:numel(dependencyTypes)
                dependencyType = dependencyTypes(dependencyIndex);
                dependencies{dependencyIndex} = ...
                    obj.resolve(dependencyType);
            end
        end
    end

    methods (Access = private)
        function dependency = construct( ...
                ~, dependencyType, implementationClassName)
            try
                dependency = feval(implementationClassName);
            catch cause
                exception = MException( ...
                    "v2xsim:hook:dependency:ConstructionFailed", ...
                    "Could not construct %s for dependency %s. " + ...
                    "Transient dependency classes must have a " + ...
                    "zero-argument constructor.", ...
                    implementationClassName, dependencyType.Name);
                exception = addCause(exception, cause);
                throwAsCaller(exception);
            end
        end

        function setProvider(obj, dependencyType, provider)
            obj.Providers(char(dependencyType.Name)) = provider;
        end

        function validateDependencyType(~, dependencyType)
            if ~isa( ...
                    dependencyType, ...
                    "matlab.metadata.Class") || ...
                    ~isscalar(dependencyType)
                error( ...
                    "v2xsim:hook:dependency:InvalidDependencyType", ...
                    "A dependency type must be one scalar class " + ...
                    "metadata object.");
            end

            baseType = ?v2xsim.hook.dependency.Dependency;
            if ~(dependencyType <= baseType)
                error( ...
                    "v2xsim:hook:dependency:InvalidDependencyType", ...
                    "%s is not a Hook Dependency type.", ...
                    dependencyType.Name);
            end
        end

        function validateAssignable( ...
                ~, dependencyType, value, valueDescription)
            if ~isscalar(value) || ...
                    ~isa(value, dependencyType.Name)
                error( ...
                    "v2xsim:hook:dependency:IncompatibleValue", ...
                    "The dependency %s %s must be one scalar %s.", ...
                    valueDescription, class(value), dependencyType.Name);
            end
        end
    end
end
