function mustBeUeIds(value)
%MUSTBEUEIDS Validate a vector of stable, unique UE identifiers.

if ~isstring(value) || (~isvector(value) && ~isempty(value))
    error( ...
        "v2xsim:resource:InvalidUeIds", ...
        "UE identifiers must be supplied as a string vector.");
end

if any(ismissing(value)) || any(strlength(value) == 0) || ...
        any(strlength(strip(value)) == 0) || any(value ~= strip(value))
    error( ...
        "v2xsim:resource:InvalidUeIds", ...
        "UE identifiers must be nonblank strings without leading or " + ...
        "trailing whitespace.");
end

if numel(unique(value)) ~= numel(value)
    error( ...
        "v2xsim:resource:DuplicateUeId", ...
        "UE identifiers must be unique.");
end
end
