classdef GeometryTest < matlab.unittest.TestCase
    %GEOMETRYTEST Exact geometry, topology, and projection contracts.

    methods (Test)
        function testScalarAndColumnExitLengthsNormalizeNorthEastSouthWest( ...
                testCase)
            scalarGeometry = ...
                v2xsim.vehicle.scenario.roundabout.Geometry(500, 4, 60);
            vectorGeometry = ...
                v2xsim.vehicle.scenario.roundabout.Geometry( ...
                    [100; 200; 300; 400], 4, 60);

            testCase.verifyEqual( ...
                scalarGeometry.ExitLengths, [500, 500, 500, 500]);
            testCase.verifyEqual( ...
                vectorGeometry.ExitLengths, [100, 200, 300, 400]);
            testCase.verifySize(vectorGeometry.ExitLengths, [1, 4]);
            testCase.verifyEqual( ...
                scalarGeometry.CirculatoryLaneCenterRadius, 32);
            testCase.verifyEqual( ...
                scalarGeometry.OuterPavementRadius, 34);
            testCase.verifyEqual( ...
                scalarGeometry.FilletTangentAxialDistance, ...
                sqrt(2940), AbsTol=1e-12);
        end

        function testRejectsInfeasibleGeometryWithStableIdentifiers( ...
                testCase)
            testCase.verifyError( ...
                @() v2xsim.vehicle.scenario.roundabout.Geometry( ...
                    [100, 200], 4, 60), ...
                "v2xsim:scenario:roundabout:InvalidExitLengths");
            testCase.verifyError( ...
                @() v2xsim.vehicle.scenario.roundabout.Geometry( ...
                    [100, NaN, 100, 100], 4, 60), ...
                "v2xsim:scenario:roundabout:InvalidExitLengths");
            testCase.verifyError( ...
                @() v2xsim.vehicle.scenario.roundabout.Geometry( ...
                    100, 4, 7.999), ...
                "v2xsim:scenario:roundabout:InnerCircleTooSmall");

            reference = ...
                v2xsim.vehicle.scenario.roundabout.Geometry(500, 4, 60);
            tooShort = reference.MinimumExitLength - 1e-6;
            testCase.verifyError( ...
                @() v2xsim.vehicle.scenario.roundabout.Geometry( ...
                    tooShort, 4, 60), ...
                "v2xsim:scenario:roundabout:ExitLengthTooShort");
        end

        function testMinimumLengthCreatesValidZeroStraightFillets( ...
                testCase)
            reference = ...
                v2xsim.vehicle.scenario.roundabout.Geometry(500, 4, 60);
            geometry = ...
                v2xsim.vehicle.scenario.roundabout.Geometry( ...
                    reference.MinimumExitLength, 4, 60);
            network = geometry.createLaneNetwork();

            testCase.verifyEqual( ...
                geometry.StraightLaneLengths, zeros(1, 4), ...
                AbsTol=1e-12);
            approachIds = geometry.getApproachLaneId( ...
                geometry.ArmNames(:));
            testCase.verifyEqual( ...
                geometry.getRouteStage(approachIds, zeros(4, 1)), ...
                repmat("EntryConnector", 4, 1));
            positions = network.evaluate(approachIds, zeros(4, 1));
            testCase.verifyTrue(all(isfinite(positions), "all"));
        end

        function testNetworkHasAllSixteenNamedLanesAndConnections(testCase)
            geometry = ...
                v2xsim.vehicle.scenario.roundabout.Geometry( ...
                    [100, 200, 300, 400], 4, 60);
            network = geometry.createLaneNetwork();
            expectedLaneIds = strings(1, 16);
            next = 1;
            for arm = geometry.ArmNames
                expectedLaneIds(next:next + 3) = [ ...
                    geometry.getApproachLaneId(arm), ...
                    geometry.getExitLaneId(arm), ...
                    geometry.getCirculatingLaneIdAfterEntry(arm), ...
                    geometry.getCirculatingLaneIdAfterExit(arm)];
                next = next + 4;
            end

            testCase.verifyEqual(network.LaneCount, 16);
            testCase.verifyEqual(network.LaneIds, expectedLaneIds);
            testCase.verifyEqual(height(network.Connections), 16);
            testCase.verifyTrue(all(network.Connections.FromProgress == 1));
            testCase.verifyTrue(all(network.Connections.ToProgress == 0));

            for arm = geometry.ArmNames
                outgoingApproach = network.getOutgoingConnections( ...
                    geometry.getApproachLaneId(arm));
                outgoingAfterEntry = network.getOutgoingConnections( ...
                    geometry.getCirculatingLaneIdAfterEntry(arm));
                outgoingAfterExit = network.getOutgoingConnections( ...
                    geometry.getCirculatingLaneIdAfterExit(arm));
                testCase.verifyEqual(height(outgoingApproach), 1);
                testCase.verifyEqual(height(outgoingAfterEntry), 2);
                testCase.verifyEqual(height(outgoingAfterExit), 1);
            end
        end

        function testAllJoinsArePositionAndTangentContinuous(testCase)
            geometry = ...
                v2xsim.vehicle.scenario.roundabout.Geometry( ...
                    [100, 200, 300, 400], 4, 60);
            network = geometry.createLaneNetwork();
            positionTolerance = 1e-10;
            tangentTolerance = 1e-10;

            for armIndex = 1:4
                arm = geometry.ArmNames(armIndex);
                nextArm = geometry.getClockwiseArm(arm);
                approach = geometry.getApproachLaneId(arm);
                onCircle = ...
                    geometry.getCirculatingLaneIdAfterEntry(arm);
                nextExit = geometry.getExitLaneId(nextArm);
                afterNextExit = ...
                    geometry.getCirculatingLaneIdAfterExit(nextArm);
                afterExit = ...
                    geometry.getCirculatingLaneIdAfterExit(arm);

                testCase.verifyEqual( ...
                    network.evaluate(approach, 1), ...
                    network.evaluate(onCircle, 0), ...
                    AbsTol=positionTolerance);
                testCase.verifyEqual( ...
                    geometry.getLaneTangent(approach, 1), ...
                    geometry.getLaneTangent(onCircle, 0), ...
                    AbsTol=tangentTolerance);

                circleEnd = network.evaluate(onCircle, 1);
                circleTangent = geometry.getLaneTangent(onCircle, 1);
                testCase.verifyEqual( ...
                    circleEnd, network.evaluate(nextExit, 0), ...
                    AbsTol=positionTolerance);
                testCase.verifyEqual( ...
                    circleEnd, network.evaluate(afterNextExit, 0), ...
                    AbsTol=positionTolerance);
                testCase.verifyEqual( ...
                    circleTangent, ...
                    geometry.getLaneTangent(nextExit, 0), ...
                    AbsTol=tangentTolerance);
                testCase.verifyEqual( ...
                    circleTangent, ...
                    geometry.getLaneTangent(afterNextExit, 0), ...
                    AbsTol=tangentTolerance);

                testCase.verifyEqual( ...
                    network.evaluate(afterExit, 1), ...
                    network.evaluate(onCircle, 0), ...
                    AbsTol=positionTolerance);
                testCase.verifyEqual( ...
                    geometry.getLaneTangent(afterExit, 1), ...
                    geometry.getLaneTangent(onCircle, 0), ...
                    AbsTol=tangentTolerance);

                approachJoin = geometry.StraightLaneLengths(armIndex) ./ ...
                    geometry.ApproachLaneLengths(armIndex);
                exitJoin = geometry.ConnectorArcLength ./ ...
                    geometry.ExitLaneLengths(armIndex);
                distanceOffset = 1e-7;
                approachDelta = distanceOffset ./ ...
                    geometry.ApproachLaneLengths(armIndex);
                exitDelta = distanceOffset ./ ...
                    geometry.ExitLaneLengths(armIndex);
                testCase.verifyEqual( ...
                    geometry.getLaneTangent( ...
                        approach, approachJoin - approachDelta), ...
                    geometry.getLaneTangent( ...
                        approach, approachJoin + approachDelta), ...
                    AbsTol=1e-7);
                testCase.verifyEqual( ...
                    geometry.getLaneTangent( ...
                        geometry.getExitLaneId(arm), ...
                        exitJoin - exitDelta), ...
                    geometry.getLaneTangent( ...
                        geometry.getExitLaneId(arm), ...
                        exitJoin + exitDelta), ...
                    AbsTol=1e-7);
            end
        end

        function testLaneEvaluatorsAcceptMultipleProgressValues(testCase)
            geometry = ...
                v2xsim.vehicle.scenario.roundabout.Geometry(500, 4, 60);
            network = geometry.createLaneNetwork();
            progress = [0; 0.1; 0.5; 0.9; 1];

            for laneId = network.LaneIds
                laneIds = repmat(laneId, numel(progress), 1);
                positions = network.evaluate(laneIds, progress);
                tangents = geometry.getLaneTangent(laneIds, progress);
                testCase.verifySize(positions, [numel(progress), 2]);
                testCase.verifySize(tangents, [numel(progress), 2]);
                testCase.verifyTrue(all(isfinite(positions), "all"));
                testCase.verifyEqual( ...
                    vecnorm(tangents, 2, 2), ones(numel(progress), 1), ...
                    AbsTol=1e-12);
            end
        end

        function testFilletsHaveExactRadiusAndLeftDrivingOrientation( ...
                testCase)
            exitLengths = [100, 200, 300, 400];
            geometry = ...
                v2xsim.vehicle.scenario.roundabout.Geometry( ...
                    exitLengths, 4, 60);
            network = geometry.createLaneNetwork();
            outward = [0, 1; 1, 0; 0, -1; -1, 0];
            clockwise = [1, 0; 0, -1; -1, 0; 0, 1];
            filletFraction = (0:0.25:1).';

            for armIndex = 1:4
                arm = geometry.ArmNames(armIndex);
                approach = geometry.getApproachLaneId(arm);
                onExit = geometry.getExitLaneId(arm);
                expectedApproachBoundary = ...
                    (geometry.OuterPavementRadius + ...
                    exitLengths(armIndex)) .* outward(armIndex, :) + ...
                    (geometry.RoadWidth ./ 2) .* clockwise(armIndex, :);
                expectedExitBoundary = ...
                    (geometry.OuterPavementRadius + ...
                    exitLengths(armIndex)) .* outward(armIndex, :) - ...
                    (geometry.RoadWidth ./ 2) .* clockwise(armIndex, :);
                testCase.verifyEqual( ...
                    network.evaluate(approach, 0), ...
                    expectedApproachBoundary, AbsTol=1e-12);
                testCase.verifyEqual( ...
                    network.evaluate(onExit, 1), ...
                    expectedExitBoundary, AbsTol=1e-12);

                approachProgress = ( ...
                    geometry.StraightLaneLengths(armIndex) + ...
                    filletFraction .* geometry.ConnectorArcLength) ./ ...
                    geometry.ApproachLaneLengths(armIndex);
                exitProgress = ...
                    filletFraction .* geometry.ConnectorArcLength ./ ...
                    geometry.ExitLaneLengths(armIndex);
                approachCenter = ...
                    geometry.OuterPavementRadius .* ...
                    clockwise(armIndex, :) + ...
                    geometry.FilletTangentAxialDistance .* ...
                    outward(armIndex, :);
                exitCenter = ...
                    -geometry.OuterPavementRadius .* ...
                    clockwise(armIndex, :) + ...
                    geometry.FilletTangentAxialDistance .* ...
                    outward(armIndex, :);
                approachPosition = network.evaluate( ...
                    repmat(approach, 5, 1), approachProgress);
                exitPosition = network.evaluate( ...
                    repmat(onExit, 5, 1), exitProgress);
                testCase.verifyEqual( ...
                    vecnorm(approachPosition - approachCenter, 2, 2), ...
                    repmat( ...
                    geometry.CirculatoryLaneCenterRadius, 5, 1), ...
                    AbsTol=1e-11);
                testCase.verifyEqual( ...
                    vecnorm(exitPosition - exitCenter, 2, 2), ...
                    repmat( ...
                    geometry.CirculatoryLaneCenterRadius, 5, 1), ...
                    AbsTol=1e-11);

                circleLane = ...
                    geometry.getCirculatingLaneIdAfterEntry(arm);
                circlePosition = network.evaluate(circleLane, 0.5);
                circleTangent = geometry.getLaneTangent(circleLane, 0.5);
                signedTurn = ...
                    circlePosition(1) .* circleTangent(2) - ...
                    circlePosition(2) .* circleTangent(1);
                testCase.verifyLessThan(signedTurn, 0);
            end
        end

        function testFalseExitProjectionTracksEachSkippedExitWindow( ...
                testCase)
            geometry = ...
                v2xsim.vehicle.scenario.roundabout.Geometry(500, 4, 60);
            rowNames = compose("V%d", (1:8).');
            laneId = [ ...
                geometry.getCirculatingLaneIdAfterExit("East"); ...
                geometry.getCirculatingLaneIdAfterEntry("East"); ...
                geometry.getCirculatingLaneIdAfterExit("South"); ...
                geometry.getCirculatingLaneIdAfterExit("East"); ...
                geometry.getCirculatingLaneIdAfterExit("East"); ...
                geometry.getCirculatingLaneIdAfterEntry("West"); ...
                geometry.getCirculatingLaneIdAfterExit("West"); ...
                geometry.getCirculatingLaneIdAfterExit("East")];
            progress = 0.25 .* ones(8, 1);
            laneStates = table( ...
                laneId, progress, zeros(8, 1), ...
                VariableNames=[ ...
                    "LaneId", "Progress", "LateralOffsetMeters"], ...
                RowNames=rowNames);
            entryArm = repmat("North", 8, 1);
            exitArm = ["West"; "West"; "West"; "East"; ...
                "North"; "North"; "South"; "West"];
            stage = repmat("Circulating", 8, 1);
            stage(8) = "Outbound";
            routeStates = table( ...
                entryArm, exitArm, stage, ...
                VariableNames=["EntryArm", "ExitArm", "Stage"], ...
                RowNames=rowNames);

            [applicable, targetLaneId, targetProgress] = ...
                geometry.getFalseExitLaneCoordinates( ...
                    laneStates, routeStates);

            testCase.verifyEqual(applicable, ...
                logical([1; 1; 1; 0; 1; 1; 0; 0]));
            expectedLaneId = laneId;
            expectedLaneId([1, 2, 5]) = geometry.getExitLaneId("East");
            expectedLaneId(3) = geometry.getExitLaneId("South");
            expectedLaneId(6) = geometry.getExitLaneId("West");
            testCase.verifyEqual(targetLaneId, expectedLaneId);

            expectedProgress = progress;
            eastLength = geometry.ExitLaneLengths(2);
            expectedProgress([1, 5]) = ...
                0.25 .* geometry.ExitToEntryArcLength ./ eastLength;
            expectedProgress(2) = ...
                (geometry.ExitToEntryArcLength + ...
                0.25 .* geometry.EntryToExitArcLength) ./ eastLength;
            expectedProgress(3) = ...
                0.25 .* geometry.ExitToEntryArcLength ./ ...
                geometry.ExitLaneLengths(3);
            expectedProgress(6) = ...
                (geometry.ExitToEntryArcLength + ...
                0.25 .* geometry.EntryToExitArcLength) ./ ...
                geometry.ExitLaneLengths(4);
            testCase.verifyEqual( ...
                targetProgress, expectedProgress, AbsTol=1e-12);
        end

        function testFalseExitProjectionEndsAtFalsePathEndpoint(testCase)
            reference = ...
                v2xsim.vehicle.scenario.roundabout.Geometry(500, 4, 60);
            geometry = ...
                v2xsim.vehicle.scenario.roundabout.Geometry( ...
                    [500, reference.MinimumExitLength, 500, 500], 4, 60);
            falseLength = geometry.ExitLaneLengths(2);
            testCase.assertLessThan( ...
                falseLength, geometry.ExitToEntryArcLength);
            distances = [falseLength - 1e-4; falseLength];
            progress = distances ./ geometry.ExitToEntryArcLength;
            laneId = repmat( ...
                geometry.getCirculatingLaneIdAfterExit("East"), 2, 1);
            rowNames = ["BeforeEnd"; "AtEnd"];
            laneStates = table( ...
                laneId, progress, zeros(2, 1), ...
                VariableNames=[ ...
                    "LaneId", "Progress", "LateralOffsetMeters"], ...
                RowNames=rowNames);
            routeStates = table( ...
                repmat("North", 2, 1), repmat("South", 2, 1), ...
                repmat("Circulating", 2, 1), ...
                VariableNames=["EntryArm", "ExitArm", "Stage"], ...
                RowNames=rowNames);

            [applicable, targetLaneId, targetProgress] = ...
                geometry.getFalseExitLaneCoordinates( ...
                    laneStates, routeStates);

            testCase.verifyEqual(applicable, logical([1; 0]));
            testCase.verifyEqual( ...
                targetLaneId(1), geometry.getExitLaneId("East"));
            testCase.verifyEqual( ...
                targetProgress(1), distances(1) ./ falseLength, ...
                AbsTol=1e-12);
            testCase.verifyEqual(targetLaneId(2), laneId(2));
            testCase.verifyEqual(targetProgress(2), progress(2));
        end
    end
end
