classdef ConfigurationSystemTest < matlab.unittest.TestCase
    %CONFIGURATIONSYSTEMTEST Focused tests for the TOML-only config core.

    methods (Test)
        function loadsAndResolvesAllMigratedFixtures(testCase)
            repositoryRoot = testCase.repositoryRoot();
            searchRoots = [ ...
                fullfile(repositoryRoot, "examples"), ...
                fullfile(repositoryRoot, "regression-tests"), ...
                fullfile(repositoryRoot, "tests", ...
                    "+v2xsimtest", "+fixtures")];
            entriesByRoot = cell(size(searchRoots));
            fileCount = 0;
            for rootIndex = 1:numel(searchRoots)
                entriesByRoot{rootIndex} = dir(fullfile( ...
                    searchRoots(rootIndex), "**", "*.toml"));
                fileCount = fileCount + numel(entriesByRoot{rootIndex});
            end
            files = strings(fileCount, 1);
            fileIndex = 0;
            for rootIndex = 1:numel(searchRoots)
                entries = entriesByRoot{rootIndex};
                for index = 1:numel(entries)
                    fileIndex = fileIndex + 1;
                    files(fileIndex) = string(fullfile( ...
                        entries(index).folder, entries(index).name));
                end
            end

            % Lesson 17 owns a copy of the output-artifact input so every
            % tutorial directory remains self-contained.
            testCase.verifyNumElements(files, 28);
            for file = reshape(files, 1, [])
                configuration = v2xsim.config.load(file).resolve();
                testCase.verifyEqual(configuration.Data.SchemaVersion, 1);
                testCase.verifyGreaterThan( ...
                    configuration.Data.Simulation.RandomSeed, 0);
                scenarioType = configuration.Data.Scenario.Type;
                testCase.verifyGreaterThan( ...
                    configuration.Data.Scenario.(scenarioType).RandomSeed, 0);
                testCase.verifyGreaterThan( ...
                    configuration.Data.ResourceAllocation.RandomSeed, 0);
            end
        end

        function normalizesNativeArraysAndOrderedArraysOfTables(testCase)
            file = testCase.writeToml( ...
                "SchemaVersion = 1" + newline + ...
                "[Awareness]" + newline + ...
                "RangesMeters = [100, 300]" + newline + ...
                "[[Positioning.Errors]]" + newline + ...
                "Type = ""Gaussian""" + newline + ...
                "MeanMagnitudeMeters = 2" + newline + ...
                "StandardDeviationMeters = 3" + newline + ...
                "[[Positioning.Errors]]" + newline + ...
                "Type = ""PacketLoss""" + newline + ...
                "LossProbability = 0.2" + newline + ...
                "RandomSeed = 77" + newline + ...
                "[[Positioning.Errors]]" + newline + ...
                "Type = ""Delay""" + newline + ...
                "DelaySeconds = 0.1");

            template = v2xsim.config.load(file);

            testCase.verifyClass(template.Data.Awareness.RangesMeters, "double");
            testCase.verifyEqual( ...
                template.Data.Awareness.RangesMeters, [100, 300]);
            testCase.verifyClass(template.Data.Positioning.Errors, "cell");
            testCase.verifyEqual( ...
                string(cellfun( ...
                    @(entry) entry.Type, ...
                    template.Data.Positioning.Errors, ...
                    UniformOutput=false)), ...
                ["Gaussian", "PacketLoss", "Delay"]);

            configuration = template.resolve();
            testCase.verifyEqual( ...
                configuration.sourceFor( ...
                    "Positioning.Errors(1).MeanMagnitudeMeters"), ...
                "File:" + file);
            testCase.verifyEqual( ...
                configuration.sourceFor( ...
                    "Positioning.Errors(1).StandardDeviationMeters"), ...
                "File:" + file);
            testCase.verifyEqual( ...
                configuration.sourceFor( ...
                    "Positioning.Errors(1).DisplacementRandomSeed"), ...
                "Derived");
            testCase.verifyEqual( ...
                configuration.sourceFor( ...
                    "Positioning.Errors(1).AffectedVehicleProbability"), ...
                "Default");
            testCase.verifyEqual( ...
                configuration.Data.Positioning.Errors{2}.LossProbability, ...
                0.2);
            testCase.verifyEqual( ...
                configuration.Data.Positioning.Errors{2}.RandomSeed, 77);
            testCase.verifyEqual(configuration.sourceFor( ...
                "Positioning.Errors(2).RandomSeed"), "File:" + file);
        end

        function resolvesPacketLossDefaultsSeedsAndValidation(testCase)
            derived = v2xsim.config.ConfigurationTemplate(struct( ...
                SchemaVersion=1, ...
                Simulation=struct(RandomSeed=17), ...
                Positioning=struct(Errors={{struct( ...
                    Type="PacketLoss")}}))).resolve();
            packetLoss = derived.Data.Positioning.Errors{1};

            testCase.verifyEqual(packetLoss.LossProbability, 0);
            testCase.verifyEqual(packetLoss.RandomSeed, 205036);
            testCase.verifyEqual(derived.sourceFor( ...
                "Positioning.Errors(1).LossProbability"), "Default");
            testCase.verifyEqual(derived.sourceFor( ...
                "Positioning.Errors(1).RandomSeed"), "Derived");

            explicit = v2xsim.config.ConfigurationTemplate(struct( ...
                SchemaVersion=1, ...
                Positioning=struct(Errors={{struct( ...
                    Type="PacketLoss", LossProbability=0.25, ...
                    RandomSeed=91)}}))).resolve();
            testCase.verifyEqual( ...
                explicit.Data.Positioning.Errors{1}.LossProbability, 0.25);
            testCase.verifyEqual( ...
                explicit.Data.Positioning.Errors{1}.RandomSeed, 91);
            testCase.verifyEqual(explicit.sourceFor( ...
                "Positioning.Errors(1).RandomSeed"), "Template");

            inactiveField = v2xsim.config.ConfigurationTemplate(struct( ...
                SchemaVersion=1, ...
                Positioning=struct(Errors={{struct( ...
                    Type="Delay", LossProbability=0.1)}})));
            duplicateType = v2xsim.config.ConfigurationTemplate(struct( ...
                SchemaVersion=1, ...
                Positioning=struct(Errors={{ ...
                    struct(Type="PacketLoss"), ...
                    struct(Type="PacketLoss")}})));

            testCase.verifyError( ...
                @() v2xsim.config.ConfigurationTemplate(struct( ...
                    SchemaVersion=1, ...
                    Positioning=struct(Errors={{struct( ...
                        Type="PacketLoss", ...
                        LossProbability=-0.01)}}))), ...
                "v2xsim:config:ValueOutOfRange");
            testCase.verifyError( ...
                @() v2xsim.config.ConfigurationTemplate(struct( ...
                    SchemaVersion=1, ...
                    Positioning=struct(Errors={{struct( ...
                        Type="PacketLoss", ...
                        LossProbability=1.01)}}))), ...
                "v2xsim:config:ValueOutOfRange");
            testCase.verifyError( ...
                @() inactiveField.resolve(), ...
                "v2xsim:config:InactiveKey");
            testCase.verifyError( ...
                @() duplicateType.resolve(), ...
                "v2xsim:config:DuplicatePositionErrorType");
        end

        function resolvesRoundaboutDefaultsAndExitLengthForms(testCase)
            defaults = v2xsim.config.ConfigurationTemplate(struct( ...
                SchemaVersion=1, ...
                Scenario=struct(Type="Roundabout"))).resolve();
            roundabout = defaults.Data.Scenario.Roundabout;

            testCase.verifyEqual(roundabout.RandomSeed, 1);
            testCase.verifyEqual(roundabout.VehicleCount, 100);
            testCase.verifyEqual(roundabout.ExitLengths, 500);
            testCase.verifyEqual(roundabout.RoadWidth, 4);
            testCase.verifyEqual(roundabout.InnerCircleDiameter, 60);
            testCase.verifyEqual(roundabout.MeanVehicleSpeed, 20);
            testCase.verifyEqual( ...
                roundabout.VehicleSpeedStandardDeviation, 2);
            testCase.verifyTrue(roundabout.RerollSpeedOnWrapAround);

            configuredExitLengths = [120, 140, 160, 180];
            configured = v2xsim.config.ConfigurationTemplate(struct( ...
                SchemaVersion=1, ...
                Scenario=struct( ...
                    Type="Roundabout", ...
                    Roundabout=struct( ...
                        ExitLengths=configuredExitLengths, ...
                        RoadWidth=6, ...
                        InnerCircleDiameter=40)))).resolve();

            testCase.verifyEqual( ...
                configured.Data.Scenario.Roundabout.ExitLengths, ...
                configuredExitLengths);
        end

        function rejectsWrongExtensionAndSchemaVersion(testCase)
            folder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture).Folder;
            cfgFile = fullfile(folder, "configuration.cfg");
            testCase.writeUtf8(cfgFile, "SchemaVersion = 1");
            missingVersion = testCase.writeToml( ...
                "[Simulation]" + newline + "DurationSeconds = 1");
            futureVersion = testCase.writeToml("SchemaVersion = 2");
            floatingVersion = testCase.writeToml("SchemaVersion = 1.0");
            floatingSeed = testCase.writeToml( ...
                "SchemaVersion = 1" + newline + ...
                "[Simulation]" + newline + "RandomSeed = 1.0");

            testCase.verifyError( ...
                @() v2xsim.config.load(cfgFile), ...
                "v2xsim:config:UnsupportedFileExtension");
            testCase.verifyError( ...
                @() v2xsim.config.load(missingVersion), ...
                "v2xsim:config:MissingSchemaVersion");
            testCase.verifyError( ...
                @() v2xsim.config.load(futureVersion), ...
                "v2xsim:config:UnsupportedSchemaVersion");
            testCase.verifyError( ...
                @() v2xsim.config.load(floatingVersion), ...
                "v2xsim:config:InvalidType");
            testCase.verifyError( ...
                @() v2xsim.config.load(floatingSeed), ...
                "v2xsim:config:InvalidType");
        end

        function rejectsUnknownAndCaseMismatchedKeys(testCase)
            unknown = testCase.writeToml( ...
                "SchemaVersion = 1" + newline + ...
                "[Simulation]" + newline + "Mystery = 3");
            wrongCase = testCase.writeToml( ...
                "SchemaVersion = 1" + newline + ...
                "[simulation]" + newline + "DurationSeconds = 1");

            testCase.verifyError( ...
                @() v2xsim.config.load(unknown), ...
                "v2xsim:config:UnknownKey");
            testCase.verifyError( ...
                @() v2xsim.config.load(wrongCase), ...
                "v2xsim:config:UnknownKey");
        end

        function deepPatchReplacesArraysAndArraysOfTablesAtomically(testCase)
            originalError = {struct( ...
                Type="Gaussian", StandardDeviationMeters=3), ...
                struct(Type="Delay", DelaySeconds=0.1)};
            template = v2xsim.config.ConfigurationTemplate(struct( ...
                SchemaVersion=1, ...
                Awareness=struct(RangesMeters=[100, 200]), ...
                Positioning=struct(Errors={originalError})));
            replacementError = {struct(Type="Delay", DelaySeconds=0.25)};
            overlay = v2xsim.config.patch(struct( ...
                Awareness=struct(RangesMeters=300), ...
                Positioning=struct(Errors={replacementError})));

            merged = template.withPatch(overlay);

            testCase.verifyEqual(merged.Data.Awareness.RangesMeters, 300);
            testCase.verifyNumElements(merged.Data.Positioning.Errors, 1);
            testCase.verifyEqual( ...
                merged.Data.Positioning.Errors{1}.DelaySeconds, 0.25);
        end

        function patchSwitchesSelectedVariantsAtomically(testCase)
            template = v2xsim.config.ConfigurationTemplate(struct( ...
                SchemaVersion=1, ...
                Scenario=struct( ...
                    Type="BidirectionalHighway", ...
                    BidirectionalHighway=struct(VehicleCount=5)), ...
                Radio=struct( ...
                    Type="LteV2X", LteV2X=struct(Mcs=3), ...
                    Sidelink=struct( ...
                        MaximumTransmissionCount=1)), ...
                ResourceAllocation=struct( ...
                    Type="SensingBased", ...
                    SensingBased=struct(KeepResourceProbability=0.4))));
            overlay = v2xsim.config.patch(struct( ...
                Scenario=struct( ...
                    Type="EtsiHighway", ...
                    EtsiHighway=struct( ...
                        TrafficModel="MediumSpeedMediumDensity")), ...
                Radio=struct( ...
                    Type="NrV2X", NrV2X=struct(Mcs=8)), ...
                ResourceAllocation=struct( ...
                    Type="Random", Random=struct( ...
                        SelectionWindowEndMilliseconds=50))));

            merged = template.withPatch(overlay);
            resolved = template.resolve(Patch=overlay);

            testCase.verifyFalse( ...
                isfield(merged.Data.Scenario, "BidirectionalHighway"));
            testCase.verifyFalse(isfield(merged.Data.Radio, "LteV2X"));
            testCase.verifyFalse(isfield( ...
                merged.Data.ResourceAllocation, "SensingBased"));
            testCase.verifyEqual(resolved.Data.Scenario.Type, "EtsiHighway");
            testCase.verifyEqual(resolved.Data.Radio.Type, "NrV2X");
            testCase.verifyEqual( ...
                resolved.Data.ResourceAllocation.Type, "Random");
        end

        function coexistenceSidelinkPatchReplacesOnlyOldPhyBranch(testCase)
            template = v2xsim.config.ConfigurationTemplate(struct( ...
                SchemaVersion=1, ...
                Radio=struct( ...
                    Type="Coexistence", ...
                    Coexistence=struct( ...
                        SidelinkType="LteV2X", ...
                        InterferenceModel="Cochannel"), ...
                    Ieee80211p=struct(Mcs=2), ...
                    LteV2X=struct(Mcs=7), ...
                    Sidelink=struct( ...
                        MaximumTransmissionCount=1))));
            overlay = v2xsim.config.patch(struct( ...
                Radio=struct( ...
                    Coexistence=struct(SidelinkType="NrV2X"), ...
                    NrV2X=struct(Mcs=8))));

            merged = template.withPatch(overlay);
            resolved = merged.resolve();

            testCase.verifyFalse(isfield(merged.Data.Radio, "LteV2X"));
            testCase.verifyTrue(isfield(merged.Data.Radio, "NrV2X"));
            testCase.verifyTrue(isfield(merged.Data.Radio, "Ieee80211p"));
            testCase.verifyTrue(isfield(merged.Data.Radio, "Sidelink"));
            testCase.verifyEqual( ...
                resolved.Data.Radio.Coexistence.SidelinkType, "NrV2X");
        end

        function rejectsInactiveAuthoredBranches(testCase)
            inactiveScenario = v2xsim.config.ConfigurationTemplate(struct( ...
                SchemaVersion=1, ...
                Scenario=struct( ...
                    Type="BidirectionalHighway", ...
                    ExitRampHighway=struct(VehicleCount=3))));
            inactiveRadio = v2xsim.config.ConfigurationTemplate(struct( ...
                SchemaVersion=1, ...
                Radio=struct( ...
                    Type="Ieee80211p", ...
                    Sidelink=struct(MaximumTransmissionCount=1))));
            inactiveCoexistence = ...
                v2xsim.config.ConfigurationTemplate(struct( ...
                    SchemaVersion=1, ...
                    Radio=struct(Type="Coexistence"), ...
                    Coexistence=struct( ...
                        Method="Standard", MethodA=struct( ...
                            EnhancementVariant=1))));
            inactiveIndependentMethod = ...
                v2xsim.config.ConfigurationTemplate(struct( ...
                    SchemaVersion=1, ...
                    Radio=struct( ...
                        Type="Coexistence", ...
                        Coexistence=struct( ...
                            InterferenceModel="Independent")), ...
                    Coexistence=struct(Method="MethodA")));

            testCase.verifyError( ...
                @() inactiveScenario.resolve(), ...
                "v2xsim:config:InactiveKey");
            testCase.verifyError( ...
                @() inactiveRadio.resolve(), ...
                "v2xsim:config:InactiveKey");
            testCase.verifyError( ...
                @() inactiveCoexistence.resolve(), ...
                "v2xsim:config:InactiveKey");
            testCase.verifyError( ...
                @() inactiveIndependentMethod.resolve(), ...
                "v2xsim:config:InactiveKey");
        end

        function defaultsAndProvenanceAreImmutableResolutionInputs(testCase)
            template = v2xsim.config.ConfigurationTemplate(struct( ...
                SchemaVersion=1, ...
                Simulation=struct(RandomSeed=17)));
            overlay = v2xsim.config.patch(struct( ...
                Simulation=struct(DurationSeconds=2)));

            configuration = template.resolve(Patch=overlay);

            testCase.verifyEqual(configuration.Data.Simulation.RandomSeed, 17);
            testCase.verifyEqual(configuration.Data.Simulation.DurationSeconds, 2);
            testCase.verifyEqual( ...
                configuration.Data.Scenario. ...
                    BidirectionalHighway.RandomSeed, 17);
            testCase.verifyEqual( ...
                configuration.Data.ResourceAllocation.RandomSeed, 17);
            testCase.verifyEqual( ...
                configuration.sourceFor("Simulation.RandomSeed"), ...
                "Template");
            testCase.verifyEqual( ...
                configuration.sourceFor("Simulation.DurationSeconds"), ...
                "Patch");
            testCase.verifyEqual( ...
                configuration.sourceFor( ...
                    "Scenario.BidirectionalHighway.RandomSeed"), ...
                "Derived");
        end

        function resolvedConstructorRejectsIncompleteDataWithStableId(testCase)
            defaults = v2xsim.config.defaults();
            incompleteData = rmfield(defaults.Data, "Outputs");

            testCase.verifyError( ...
                @() v2xsim.config.ResolvedConfiguration( ...
                    incompleteData, defaults.Provenance), ...
                "v2xsim:config:MissingResolvedKey");
        end

        function rejectsNullAndAutomaticSentinelsAndUnlistedInfinity(testCase)
            nullDirectory = testCase.writeToml( ...
                "SchemaVersion = 1" + newline + ...
                "[Channel.PacketError]" + newline + ...
                "Model = ""Curves""" + newline + ...
                "CurveDirectory = ""null""");
            zeroSeed = testCase.writeToml( ...
                "SchemaVersion = 1" + newline + ...
                "[Simulation]" + newline + "RandomSeed = 0");
            infiniteDuration = testCase.writeToml( ...
                "SchemaVersion = 1" + newline + ...
                "[Simulation]" + newline + "DurationSeconds = inf");
            automaticThreshold = testCase.writeToml( ...
                "SchemaVersion = 1" + newline + ...
                "[Channel.PacketError]" + newline + ...
                "SidelinkLosThresholdDb = -1000");
            negativeMeanMagnitude = testCase.writeToml( ...
                "SchemaVersion = 1" + newline + ...
                "[[Positioning.Errors]]" + newline + ...
                "Type = ""Gaussian""" + newline + ...
                "MeanMagnitudeMeters = -1");

            testCase.verifyError( ...
                @() v2xsim.config.load(nullDirectory), ...
                "v2xsim:config:NullSentinelUnsupported");
            testCase.verifyError( ...
                @() v2xsim.config.load(zeroSeed).resolve(), ...
                "v2xsim:config:ValueOutOfRange");
            testCase.verifyError( ...
                @() v2xsim.config.load(infiniteDuration).resolve(), ...
                "v2xsim:config:NonfiniteValue");
            testCase.verifyError( ...
                @() v2xsim.config.load(automaticThreshold).resolve(), ...
                "v2xsim:config:AutomaticSentinelUnsupported");
            testCase.verifyError( ...
                @() v2xsim.config.load(negativeMeanMagnitude).resolve(), ...
                "v2xsim:config:ValueOutOfRange");

            allowedInfinity = testCase.writeToml( ...
                "SchemaVersion = 1" + newline + ...
                "[[Positioning.Errors]]" + newline + ...
                "Type = ""Gaussian""" + newline + ...
                "ResetAfterSeconds = inf");
            configuration = v2xsim.config.load(allowedInfinity).resolve();
            testCase.verifyEqual( ...
                configuration.Data.Positioning.Errors{1}. ...
                    ResetAfterSeconds, inf);
        end

        function validatesFixedArraysAndPositioningRouteNames(testCase)
            invalidRoutes = ...
                v2xsim.config.ConfigurationTemplate(struct( ...
                    SchemaVersion=1, ...
                    Scenario=struct(Type="ExitRampHighway"), ...
                    Positioning=struct(Errors={{struct( ...
                        Type="Gaussian", ...
                        ActiveRoutes=["Ramp", "Ramp"])}})));

            testCase.verifyError( ...
                @() v2xsim.config.ConfigurationTemplate(struct( ...
                    SchemaVersion=1, ...
                    Radio=struct( ...
                        Type="Ieee80211p", ...
                        Ieee80211p=struct( ...
                            Repetition=struct( ...
                                CbrThresholds=[0.03, 0.05]))))), ...
                "v2xsim:config:InvalidArraySize");
            testCase.verifyError( ...
                @() invalidRoutes.resolve(), ...
                "v2xsim:config:InvalidPositionErrorRoutes");
        end

        function validatesRoundaboutGeometry(testCase)
            invalidCount = v2xsim.config.ConfigurationTemplate(struct( ...
                SchemaVersion=1, ...
                Scenario=struct( ...
                    Type="Roundabout", ...
                    Roundabout=struct(ExitLengths=[100, 100]))));
            invalidDiameter = v2xsim.config.ConfigurationTemplate(struct( ...
                SchemaVersion=1, ...
                Scenario=struct( ...
                    Type="Roundabout", ...
                    Roundabout=struct( ...
                        RoadWidth=10, InnerCircleDiameter=19))));

            innerDiameter = 60;
            roadWidth = 4;
            tangentDistance = sqrt( ...
                0.75 * innerDiameter ^ 2 + innerDiameter * roadWidth);
            minimumExitLength = tangentDistance - ...
                (innerDiameter / 2 + roadWidth);
            tooShort = v2xsim.config.ConfigurationTemplate(struct( ...
                SchemaVersion=1, ...
                Scenario=struct( ...
                    Type="Roundabout", ...
                    Roundabout=struct( ...
                        ExitLengths=minimumExitLength - 1e-6, ...
                        RoadWidth=roadWidth, ...
                        InnerCircleDiameter=innerDiameter))));

            testCase.verifyError( ...
                @() invalidCount.resolve(), ...
                "v2xsim:config:InvalidRoundaboutExitLengths");
            testCase.verifyError( ...
                @() v2xsim.config.ConfigurationTemplate(struct( ...
                    SchemaVersion=1, ...
                    Scenario=struct( ...
                        Type="Roundabout", ...
                        Roundabout=struct( ...
                            ExitLengths=[100, 100; 100, 100])))), ...
                "v2xsim:config:InvalidType");
            testCase.verifyError( ...
                @() invalidDiameter.resolve(), ...
                "v2xsim:config:InvalidRoundaboutGeometry");
            testCase.verifyError( ...
                @() tooShort.resolve(), ...
                "v2xsim:config:InvalidRoundaboutGeometry");

            boundary = v2xsim.config.ConfigurationTemplate(struct( ...
                SchemaVersion=1, ...
                Scenario=struct( ...
                    Type="Roundabout", ...
                    Roundabout=struct( ...
                        ExitLengths=minimumExitLength, ...
                        RoadWidth=roadWidth, ...
                        InnerCircleDiameter=innerDiameter)))).resolve();
            testCase.verifyEqual( ...
                boundary.Data.Scenario.Roundabout.ExitLengths, ...
                minimumExitLength);
        end

        function validatesScenarioSpecificPositionErrors(testCase)
            roundaboutFalseExit = ...
                v2xsim.config.ConfigurationTemplate(struct( ...
                    SchemaVersion=1, ...
                    Scenario=struct(Type="Roundabout"), ...
                    Positioning=struct(Errors={{struct( ...
                        Type="FalseExit")}}))).resolve();

            testCase.verifyEqual( ...
                roundaboutFalseExit.Data.Positioning.Errors{1}.Type, ...
                "FalseExit");

            invalidFalseExit = ...
                v2xsim.config.ConfigurationTemplate(struct( ...
                    SchemaVersion=1, ...
                    Scenario=struct(Type="BidirectionalHighway"), ...
                    Positioning=struct(Errors={{struct( ...
                        Type="FalseExit")}})));
            invalidFalseMerge = ...
                v2xsim.config.ConfigurationTemplate(struct( ...
                    SchemaVersion=1, ...
                    Scenario=struct(Type="Roundabout"), ...
                    Positioning=struct(Errors={{struct( ...
                        Type="FalseMerge")}})));
            invalidRouteFilteredGaussian = ...
                v2xsim.config.ConfigurationTemplate(struct( ...
                    SchemaVersion=1, ...
                    Scenario=struct(Type="Roundabout"), ...
                    Positioning=struct(Errors={{struct( ...
                        Type="Gaussian", ActiveRoutes="Ramp")}})));

            testCase.verifyError( ...
                @() invalidFalseExit.resolve(), ...
                "v2xsim:config:IncompatiblePositionError");
            testCase.verifyError( ...
                @() invalidFalseMerge.resolve(), ...
                "v2xsim:config:IncompatiblePositionError");
            testCase.verifyError( ...
                @() invalidRouteFilteredGaussian.resolve(), ...
                "v2xsim:config:IncompatiblePositionError");
        end

        function rejectsScenarioAndApplicationEngineIncompatibilities(testCase)
            testCase.verifyError( ...
                @() v2xsim.config.ConfigurationTemplate(struct( ...
                    SchemaVersion=1, ...
                    Scenario=struct( ...
                        Type="ExitRampHighway", ...
                        ExitRampHighway=struct(NLanes=1)))), ...
                "v2xsim:config:ValueOutOfRange");
            testCase.verifyError( ...
                @() v2xsim.config.ConfigurationTemplate(struct( ...
                    SchemaVersion=1, ...
                    Scenario=struct( ...
                        Type="EtsiHighway", ...
                        EtsiHighway=struct( ...
                            MinimumRoadLength=1999)))), ...
                "v2xsim:config:ValueOutOfRange");

            invalidRamp = v2xsim.config.ConfigurationTemplate(struct( ...
                SchemaVersion=1, ...
                Scenario=struct( ...
                    Type="ExitRampHighway", ...
                    ExitRampHighway=struct( ...
                        RoadLength=100, MergeDistance=51))));
            invalidReservationInterval = ...
                v2xsim.config.ConfigurationTemplate(struct( ...
                    SchemaVersion=1, ...
                    Application=struct( ...
                        ResourceReservationIntervalSeconds=0.15)));
            invalidVariation = ...
                v2xsim.config.ConfigurationTemplate(struct( ...
                    SchemaVersion=1, ...
                    Application=struct( ...
                        ResourceReservationIntervalSeconds=0.1, ...
                        PacketGeneration=struct( ...
                            IntervalVariationSeconds=0.1))));
            invalidCam = v2xsim.config.ConfigurationTemplate(struct( ...
                SchemaVersion=1, ...
                Application=struct( ...
                    ResourceReservationIntervalSeconds=0.1, ...
                    PacketGeneration=struct( ...
                        Mode="EtsiCam", ...
                        IntervalSeconds=0.2, ...
                        RandomComponentMeanSeconds=0.1))));

            testCase.verifyError( ...
                @() invalidRamp.resolve(), ...
                "v2xsim:config:InvalidExitRampGeometry");
            testCase.verifyError( ...
                @() invalidReservationInterval.resolve(), ...
                "v2xsim:config:InvalidResourceReservationInterval");
            testCase.verifyError( ...
                @() invalidVariation.resolve(), ...
                "v2xsim:config:InvalidPacketGeneration");
            testCase.verifyError( ...
                @() invalidCam.resolve(), ...
                "v2xsim:config:InvalidPacketGeneration");

            inactiveCam = v2xsim.config.ConfigurationTemplate(struct( ...
                SchemaVersion=1, ...
                Application=struct(PacketGeneration=struct( ...
                    Mode="Periodic", ...
                    Cam=struct(IntervalDiscretization="AllSteps")))));
            testCase.verifyError( ...
                @() inactiveCam.resolve(), ...
                "v2xsim:config:InactiveKey");
        end

        function rejectsRadioChannelAndSelectionEngineIncompatibilities(testCase)
            testCase.verifyError( ...
                @() v2xsim.config.ConfigurationTemplate(struct( ...
                    SchemaVersion=1, ...
                    Channel=struct(PathLoss=struct( ...
                        Model="TwoSlope", ...
                        BreakpointDistance1Meters=0.5)))), ...
                "v2xsim:config:ValueOutOfRange");

            decreasingThresholds = ...
                v2xsim.config.ConfigurationTemplate(struct( ...
                    SchemaVersion=1, ...
                    Radio=struct( ...
                        Type="Ieee80211p", ...
                        Ieee80211p=struct(Repetition=struct( ...
                            CbrThresholds=[0.2, 0.1, 0.3])))));
            invalidBandwidth = ...
                v2xsim.config.ConfigurationTemplate(struct( ...
                    SchemaVersion=1, ...
                    Radio=struct( ...
                        Type="Coexistence", BandwidthMHz=5)));
            invalidSubchannel = ...
                v2xsim.config.ConfigurationTemplate(struct( ...
                    SchemaVersion=1, ...
                    Radio=struct( ...
                        Type="NrV2X", ...
                        Sidelink=struct(ResourcePool=struct( ...
                            SubchannelSizeResourceBlocks=11)))));
            invalidSciReservation = ...
                v2xsim.config.ConfigurationTemplate(struct( ...
                    SchemaVersion=1, ...
                    Radio=struct( ...
                        Type="NrV2X", ...
                        NrV2X=struct(SciResourceBlockCount=12))));
            invalidSelectionWindow = ...
                v2xsim.config.ConfigurationTemplate(struct( ...
                    SchemaVersion=1, ...
                    Radio=struct( ...
                        Type="NrV2X", ...
                        NrV2X=struct( ...
                            SubcarrierSpacingKilohertz=60)), ...
                    ResourceAllocation=struct( ...
                        Type="Random", ...
                        Random=struct( ...
                            SelectionWindowStartMilliseconds=0.6))));

            testCase.verifyError( ...
                @() decreasingThresholds.resolve(), ...
                "v2xsim:config:InvalidRepetitionThresholds");
            testCase.verifyError( ...
                @() invalidBandwidth.resolve(), ...
                "v2xsim:config:InvalidBandwidth");
            testCase.verifyError( ...
                @() invalidSubchannel.resolve(), ...
                "v2xsim:config:InvalidNrResourcePool");
            testCase.verifyError( ...
                @() invalidSciReservation.resolve(), ...
                "v2xsim:config:InvalidNrResourcePool");
            testCase.verifyError( ...
                @() invalidSelectionWindow.resolve(), ...
                "v2xsim:config:InvalidSelectionWindow");
        end

        function rejectsIgnoredAndSilentlyNormalizedValues(testCase)
            descendingRanges = ...
                v2xsim.config.ConfigurationTemplate(struct( ...
                    SchemaVersion=1, ...
                    Awareness=struct(RangesMeters=[300, 100])));
            fractionalRange = ...
                v2xsim.config.ConfigurationTemplate(struct( ...
                    SchemaVersion=1, ...
                    Awareness=struct(RangesMeters=100.5)));
            unsupportedObstacles = ...
                v2xsim.config.ConfigurationTemplate(struct( ...
                    SchemaVersion=1, ...
                    Channel=struct(Obstacles=struct( ...
                        WallAttenuationDb=7))));
            invalidBins = ...
                v2xsim.config.ConfigurationTemplate(struct( ...
                    SchemaVersion=1, ...
                    Outputs=struct(WirelessBlindSpot=struct( ...
                        MaximumDelaySeconds=1, ...
                        BinWidthSeconds=2))));

            testCase.verifyError( ...
                @() descendingRanges.resolve(), ...
                "v2xsim:config:InvalidAwarenessRanges");
            testCase.verifyError( ...
                @() fractionalRange.resolve(), ...
                "v2xsim:config:InvalidAwarenessRanges");
            testCase.verifyError( ...
                @() unsupportedObstacles.resolve(), ...
                "v2xsim:config:UnsupportedObstacleConfiguration");
            testCase.verifyError( ...
                @() invalidBins.resolve(), ...
                "v2xsim:config:InvalidWirelessBlindSpotBins");
        end

        function enforcesRequiredTextAndReservedIdentifiers(testCase)
            testCase.verifyError( ...
                @() v2xsim.config.ConfigurationTemplate(struct( ...
                    SchemaVersion=1, ...
                    Channel=struct(PacketError=struct( ...
                        Model="Curves", CurveDirectory=" ")))), ...
                "v2xsim:config:BlankString");
            testCase.verifyError( ...
                @() v2xsim.config.ConfigurationTemplate(struct( ...
                    SchemaVersion=1, ...
                    Infrastructure=struct(RoadsideUnits={{struct( ...
                        Id="", ...
                        Technology="Ieee80211p", ...
                        PacketType="Cam", ...
                        PositionMeters=[0, 0])}}))), ...
                "v2xsim:config:BlankString");

            missingErrorType = ...
                v2xsim.config.ConfigurationTemplate(struct( ...
                    SchemaVersion=1, ...
                    Positioning=struct(Errors={{struct()}})));
            missingRsuTechnology = ...
                v2xsim.config.ConfigurationTemplate(struct( ...
                    SchemaVersion=1, ...
                    Infrastructure=struct(RoadsideUnits={{struct( ...
                        Id="RSU-1", ...
                        PacketType="Cam", ...
                        PositionMeters=[0, 0])}})));
            reservedRsuId = ...
                v2xsim.config.ConfigurationTemplate(struct( ...
                    SchemaVersion=1, ...
                    Infrastructure=struct(RoadsideUnits={{struct( ...
                        Id="V1", ...
                        Technology="Ieee80211p", ...
                        PacketType="Cam", ...
                        PositionMeters=[0, 0])}})));

            testCase.verifyError( ...
                @() missingErrorType.resolve(), ...
                "v2xsim:config:MissingRequiredKey");
            testCase.verifyError( ...
                @() missingRsuTechnology.resolve(), ...
                "v2xsim:config:MissingRequiredKey");
            testCase.verifyError( ...
                @() reservedRsuId.resolve(), ...
                "v2xsim:config:ReservedRoadsideUnitId");

            incompatibleRsu = ...
                v2xsim.config.ConfigurationTemplate(struct( ...
                    SchemaVersion=1, ...
                    Radio=struct(Type="Ieee80211p"), ...
                    Infrastructure=struct(RoadsideUnits={{struct( ...
                        Id="RSU-1", ...
                        Technology="LteV2X", ...
                        PacketType="Cam", ...
                        PositionMeters=[0, 0])}})));
            testCase.verifyError( ...
                @() incompatibleRsu.resolve(), ...
                "v2xsim:config:IncompatibleRoadsideUnitTechnology");
        end

        function resolvesTomlResourcePathsAtTheFileBoundary(testCase)
            folder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture).Folder;
            configurationFolder = fullfile(folder, "configuration");
            curveFolder = fullfile(configurationFolder, "curves");
            workerFolder = fullfile(folder, "worker");
            mkdir(configurationFolder);
            mkdir(curveFolder);
            mkdir(workerFolder);
            file = fullfile(configurationFolder, "resource-paths.toml");
            testCase.writeUtf8(file, ...
                "SchemaVersion = 1" + newline + ...
                "[Channel.PacketError]" + newline + ...
                "Model = ""Curves""" + newline + ...
                "CurveDirectory = ""curves""");

            originalFolder = string(pwd);
            folderCleanup = onCleanup(@() cd(originalFolder));
            cd(workerFolder);
            configuration = v2xsim.config.load(file).resolve();

            testCase.verifyEqual( ...
                configuration.Data.Channel.PacketError.CurveDirectory, ...
                string(curveFolder));
            testCase.verifyEqual( ...
                configuration.sourceFor( ...
                    "Channel.PacketError.CurveDirectory"), ...
                "File:" + string(file));
            folderCleanup; %#ok<VUNUS>

            relativePath = v2xsim.config.ConfigurationTemplate(struct( ...
                SchemaVersion=1, ...
                Channel=struct(PacketError=struct( ...
                    Model="Curves", CurveDirectory="curves"))));
            testCase.verifyError( ...
                @() relativePath.resolve(), ...
                "v2xsim:config:RelativeResourcePath");
        end

        function enforcesExactProvenanceCoverage(testCase)
            configuration = v2xsim.config.defaults();
            emptyProvenance = ...
                v2xsim.config.internal.Operations.emptyProvenance();
            additionalProvenance = [ ...
                configuration.Provenance; ...
                table( ...
                    "Legacy.Value", "Patch", ...
                    VariableNames=["Path", "Source"])];

            testCase.verifyError( ...
                @() v2xsim.config.ConfigurationTemplate( ...
                    struct(SchemaVersion=1), emptyProvenance), ...
                "v2xsim:config:InvalidProvenance");
            testCase.verifyError( ...
                @() v2xsim.config.ResolvedConfiguration( ...
                    configuration.Data, emptyProvenance), ...
                "v2xsim:config:InvalidProvenance");
            testCase.verifyError( ...
                @() v2xsim.config.ResolvedConfiguration( ...
                    configuration.Data, additionalProvenance), ...
                "v2xsim:config:InvalidProvenance");
        end

        function preservesSharedSidelinkAndRemovesInactiveCoexistence(testCase)
            inactiveCoexistence = ...
                v2xsim.config.ConfigurationTemplate(struct( ...
                    SchemaVersion=1, ...
                    Coexistence=struct(Method="MethodA")));
            testCase.verifyError( ...
                @() inactiveCoexistence.resolve(), ...
                "v2xsim:config:InactiveKey");

            template = v2xsim.config.ConfigurationTemplate(struct( ...
                SchemaVersion=1, ...
                Radio=struct( ...
                    Type="Coexistence", ...
                    Sidelink=struct(ResourcePool=struct( ...
                        SubchannelSizeResourceBlocks=20))), ...
                Coexistence=struct(Method="MethodA")));
            overlay = v2xsim.config.patch(struct( ...
                Radio=struct(Type="NrV2X")));

            merged = template.withPatch(overlay);
            configuration = merged.resolve();

            testCase.verifyFalse(isfield(merged.Data, "Coexistence"));
            testCase.verifyEqual( ...
                configuration.Data.Radio.Sidelink.ResourcePool. ...
                    SubchannelSizeResourceBlocks, ...
                20);
            testCase.verifyEqual( ...
                configuration.sourceFor( ...
                    "Radio.Sidelink.ResourcePool." + ...
                    "SubchannelSizeResourceBlocks"), ...
                "Template");

            cochannel = v2xsim.config.ConfigurationTemplate(struct( ...
                SchemaVersion=1, ...
                Radio=struct( ...
                    Type="Coexistence", ...
                    Coexistence=struct( ...
                        InterferenceModel="Cochannel")), ...
                Coexistence=struct( ...
                    Method="MethodA", ...
                    VehiclePattern=struct(SidelinkVehicleCount=3), ...
                    MethodA=struct(EnhancementVariant=1))));
            independentPatch = v2xsim.config.patch(struct( ...
                Radio=struct(Coexistence=struct( ...
                    InterferenceModel="Independent"))));

            independent = cochannel.withPatch(independentPatch);
            independentConfiguration = independent.resolve();

            testCase.verifyEqual( ...
                string(fieldnames(independent.Data.Coexistence)), ...
                "VehiclePattern");
            testCase.verifyEqual( ...
                independentConfiguration.Data.Coexistence. ...
                    VehiclePattern.SidelinkVehicleCount, ...
                3);
        end
    end

    methods (Access = private)
        function file = writeToml(testCase, text)
            folder = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture).Folder;
            file = fullfile(folder, "configuration.toml");
            testCase.writeUtf8(file, text);
        end
    end

    methods (Static, Access = private)
        function writeUtf8(file, text)
            fileIdentifier = fopen(file, "wt", "n", "UTF-8");
            if fileIdentifier < 0
                error( ...
                    "v2xsimtest:config:FixtureWriteFailed", ...
                    "Could not create TOML fixture ""%s"".", file);
            end
            cleanup = onCleanup(@() fclose(fileIdentifier));
            fwrite(fileIdentifier, char(text), "char");
        end

        function result = repositoryRoot()
            result = string(mfilename("fullpath"));
            for index = 1:4
                result = string(fileparts(result));
            end
        end
    end
end
