classdef StatusEffectStub < v2xsim.status.StatusEffect
    %STATUSEFFECTSTUB Concrete domain-neutral lifecycle test double.

    methods
        function obj = StatusEffectStub( ...
                selectionProbability, options)
            arguments (Input)
                selectionProbability (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeNonnegative}
                options.SelectionRandomSeed (1, 1) double ...
                    {mustBeReal, mustBeFinite, mustBeInteger, ...
                    mustBeNonnegative} = 0
                options.SelectionRandomStream = []
                options.ResetAfterSeconds (1, 1) double ...
                    {mustBeReal, mustBeNonnegative} = Inf
            end

            obj = obj@v2xsim.status.StatusEffect( ...
                selectionProbability, ...
                options.SelectionRandomSeed, ...
                options.ResetAfterSeconds, ...
                options.SelectionRandomStream);
        end
    end
end
