function [resultingList,stationManagement,sinrManagement, ...
        interferenceDiagnostics] = elaborateFateRxCV2X( ...
        ~,IDvehicleTXLTE,indexVehicleTX,neighborsID, ...
        sinrManagement,stationManagement,positionManagement,phyParams)
% Detect correctly decoded beacons and create the list of correct
% transmissions
% [ID TX, ID RX, BRid, distance]

interferenceDiagnostics = struct();
interferenceEvidenceEnabled = ...
    isfield(sinrManagement,"cv2xInterferenceEvidenceEnabled") && ...
    sinrManagement.cv2xInterferenceEvidenceEnabled;
if interferenceEvidenceEnabled
    interferenceDiagnostics.TerminalAttempts = ...
        v2xsim.hook.invocations. ...
        AfterInterferenceEvidenceDeterminedInvocation. ...
        emptyTerminalAttempts();
    interferenceDiagnostics.Counterfactuals = ...
        v2xsim.hook.invocations. ...
        AfterInterferenceEvidenceDeterminedInvocation. ...
        emptyCounterfactuals();
end

distance = positionManagement.distanceReal(stationManagement.vehicleState(stationManagement.activeIDs)==100,stationManagement.vehicleState(stationManagement.activeIDs)==100);

Ntx = length(IDvehicleTXLTE);              % Number of tx vehicles
%resultingList = zeros(Ntx*length(neighborsID(1,:)),5);        % Initialize error matrix
resultingList = zeros(0,5);        % Initialize error matrix
indexRaw = 0;                              % Initialize number of errors

for i = 1:Ntx

    %if IDvehicleTXLTE(i)==39
    %    fp = fopen('Temp.txt','a');
    %    fprintf(fp,'T=%f: new tx, attemmpt %d\n',timeManagement.timeNow,stationManagement.pckTxOccurring(IDvehicleTXLTE(i)));
    %    fclose(fp);
    %end
    
    % Find indexes of receiving vehicles in neighborsID
    indexNeighborsRX = find(neighborsID(indexVehicleTX(i),:));
    
    resultingList(indexRaw+1:indexRaw+length(indexNeighborsRX),5)=0;
    
    for j = 1:length(indexNeighborsRX)
        
        IDvehicleRX = neighborsID(indexVehicleTX(i),indexNeighborsRX(j));
        
        % If this packet was already received it can be skipped
        if stationManagement.pckReceived(IDvehicleRX,IDvehicleTXLTE(i))>0
            continue;
        end

        priorCombinedSinr = ...
            sinrManagement.cumulativeSINR( ...
                IDvehicleRX,IDvehicleTXLTE(i));

        % Update of cumulativeSINR, to account for possible Maximal Ratio
        % Combining
        sinrManagement.cumulativeSINR(IDvehicleRX,IDvehicleTXLTE(i)) = sinrManagement.cumulativeSINR(IDvehicleRX,IDvehicleTXLTE(i)) + ...
            sinrManagement.neighborsSINRaverageCV2X(i,indexNeighborsRX(j));

        % If received beacon SINR is lower than the threshold
        %if sinrManagement.neighborsSINR(i,indexNeighborsRX(j)) < phyParams.gammaMinLTE
        % randomSINRthreshold = sinrV(randi(length(sinrV)))
        sinrThreshold=(phyParams.LOS(i,indexNeighborsRX(j))*phyParams.sinrVectorCV2X_LOS(randi(length(phyParams.sinrVectorCV2X_LOS)))+... %if LOS
            (1-phyParams.LOS(i,indexNeighborsRX(j)))*phyParams.sinrVectorCV2X_NLOS(randi(length(phyParams.sinrVectorCV2X_NLOS))));  %if NLOS

        terminalOutcome = "";
        if sinrManagement.cumulativeSINR(IDvehicleRX,IDvehicleTXLTE(i)) >= sinrThreshold
            % CORRECT            
            indexRaw = indexRaw + 1;
            resultingList(indexRaw,1) = IDvehicleTXLTE(i);
            resultingList(indexRaw,2) = IDvehicleRX;
            resultingList(indexRaw,3) = stationManagement.BRid(IDvehicleTXLTE(i),stationManagement.pckTxOccurring(IDvehicleTXLTE(i)));
            resultingList(indexRaw,4) = distance(indexVehicleTX(i),stationManagement.activeIDsCV2X==IDvehicleRX);
            resultingList(indexRaw,5) = 1; % COLUMN 5=1 IS "CORRECT"
            % Mark that this packet has been received
            stationManagement.pckReceived(IDvehicleRX,IDvehicleTXLTE(i))=1;
            terminalOutcome = "correct";
        elseif stationManagement.pckTxOccurring( ...
                IDvehicleTXLTE(i)) >= ...
                effectiveCv2xTransmissionCount( ...
                stationManagement,IDvehicleTXLTE(i))
            % ERROR IN LAST ATTEMPT
            indexRaw = indexRaw + 1;
            resultingList(indexRaw,1) = IDvehicleTXLTE(i);
            resultingList(indexRaw,2) = IDvehicleRX;
            resultingList(indexRaw,3) = stationManagement.BRid(IDvehicleTXLTE(i),stationManagement.pckTxOccurring(IDvehicleTXLTE(i)));
            resultingList(indexRaw,4) = distance(indexVehicleTX(i),stationManagement.activeIDsCV2X==IDvehicleRX);
            resultingList(indexRaw,5) = 0; % COLUMN 5=0 IS "ERROR"
            terminalOutcome = "error";
        elseif ~isinf(phyParams.Ksi) || isempty(find(IDvehicleTXLTE == IDvehicleRX, 1))
            % ERROR IN ATTEMPT (NOT THE LAST ONE) AND THE RECEIVER IS NOT
            % TRANSMITTING
            %if IDvehicleRX==11 && IDvehicleTXLTE(i)==39
            %    fp = fopen('Temp.txt','a');
            %    fprintf(fp,'T=%f: pckReceived incr. (now %d)\n',timeManagement.timeNow,-stationManagement.pckReceived(IDvehicleRX,IDvehicleTXLTE(i))+1);
            %    fclose(fp);
            %end
            % An additional attempt is recorded by decrementing 'stationManagement.pckReceived'
            stationManagement.pckReceived(IDvehicleRX,IDvehicleTXLTE(i)) = stationManagement.pckReceived(IDvehicleRX,IDvehicleTXLTE(i))-1;
            if stationManagement.pckReceived(IDvehicleRX,IDvehicleTXLTE(i))<-(phyParams.cv2xNumberOfReplicasMax-1)
                error('Too many errors in the packet transmission');
            end
        else
            % ERROR IN ATTEMPT (NOT THE LAST ONE) AND THE RECEIVER IS TRANSMITTING
            % No correct reception recorded
            % No wrong reception recorded
            % No attempt recorded
        end

        if interferenceEvidenceEnabled && ...
                terminalOutcome == "error"
            [terminalAttempt,counterfactuals] = ...
                terminalInterferenceEvidence( ...
                    IDvehicleTXLTE(i),IDvehicleRX,i, ...
                    indexNeighborsRX(j),priorCombinedSinr, ...
                    sinrThreshold,terminalOutcome, ...
                    sinrManagement,stationManagement);
            interferenceDiagnostics.TerminalAttempts = [ ...
                interferenceDiagnostics.TerminalAttempts; ...
                terminalAttempt];
            interferenceDiagnostics.Counterfactuals = [ ...
                interferenceDiagnostics.Counterfactuals; ...
                counterfactuals];
        end
    end
end

delIndex = resultingList(:,1)==0;
%if sum(delIndex)>0
%    error('Error strange here...');
%end
resultingList(delIndex,:) = [];

end

function [terminalAttempt,counterfactuals] = ...
        terminalInterferenceEvidence( ...
            transmitterId,receiverId,transmitterIndex,neighborIndex, ...
            priorCombinedSinr,decodeThreshold,outcome, ...
            sinrManagement,stationManagement)
allPowers = reshape( ...
    sinrManagement.cv2xIndividualInterferencePowerData( ...
        transmitterIndex,neighborIndex,:),[],1);
positiveContributor = allPowers > 0;
interfererPowers = allPowers(positiveContributor);
interfererIds = ...
    sinrManagement.cv2xInterferenceTransmitterIds( ...
        positiveContributor);
interfererFrequencyIds = ...
    sinrManagement.cv2xInterferenceFrequencyResourceIds( ...
        positiveContributor);

counterfactualSinr = ...
    v2xsim.analysis.calculateCumulativeSinrCounterfactuals( ...
        priorCombinedSinr, ...
        sinrManagement.neighPowerUsefulCV2X( ...
            transmitterIndex,neighborIndex), ...
        sinrManagement. ...
            cv2xCounterfactualUnattributedDenominatorPower( ...
                transmitterIndex,neighborIndex), ...
        interfererPowers);
observedSinr = ...
    sinrManagement.cumulativeSINR(receiverId,transmitterId);
evidenceIsExhaustive = ...
    sinrManagement.cv2xInterferenceEvidenceIsExhaustive;

terminalAttempt = table( ...
    transmitterId,receiverId,string(outcome), ...
    linearToDb(observedSinr),linearToDb(decodeThreshold), ...
    linearToDb( ...
        counterfactualSinr.SinrWithoutAllInterferers), ...
    numel(interfererIds),logical(evidenceIsExhaustive), ...
    VariableNames=string( ...
        v2xsim.hook.invocations. ...
        AfterInterferenceEvidenceDeterminedInvocation. ...
        emptyTerminalAttempts().Properties.VariableNames));

if isempty(interfererIds)
    counterfactuals = v2xsim.hook.invocations. ...
        AfterInterferenceEvidenceDeterminedInvocation. ...
        emptyCounterfactuals();
    return
end

interfererCount = numel(interfererIds);
interfererResourceIds = zeros(interfererCount,1);
relations = repmat("other",interfererCount,1);
desiredFrequencyId = ...
    sinrManagement.cv2xInterferenceFrequencyResourceIds( ...
        transmitterIndex);
for interfererIndex = 1:interfererCount
    interfererId = interfererIds(interfererIndex);
    attemptNumber = ...
        stationManagement.pckTxOccurring(interfererId);
    interfererResourceIds(interfererIndex) = ...
        stationManagement.BRid(interfererId,attemptNumber);
    if interfererId == receiverId
        relations(interfererIndex) = "half_duplex";
    elseif interfererFrequencyIds(interfererIndex) == ...
            desiredFrequencyId
        relations(interfererIndex) = "cochannel";
    elseif abs( ...
            interfererFrequencyIds(interfererIndex) - ...
            desiredFrequencyId) == 1
        relations(interfererIndex) = "adjacent_channel";
    end
end

counterfactuals = table( ...
    repmat(transmitterId,interfererCount,1), ...
    repmat(receiverId,interfererCount,1), ...
    interfererIds,interfererResourceIds, ...
    interfererFrequencyIds,relations,interfererPowers, ...
    arrayfun( ...
        @linearToDb, ...
        counterfactualSinr.SinrWithoutEachInterferer), ...
    VariableNames=string( ...
        v2xsim.hook.invocations. ...
        AfterInterferenceEvidenceDeterminedInvocation. ...
        emptyCounterfactuals().Properties.VariableNames));
end

function valueDb = linearToDb(value)
valueDb = 10 * log10(value);
end
