function [phyParams,simValues,outputValues,sinrManagement,stationManagement,timeManagement] = ...
            mainCV2XttiEnds(appParams,simParams,phyParams,outParams,simValues,outputValues,timeManagement,positionManagement,sinrManagement,stationManagement)
% a C-V2X TTI (time transmission interval) ends

[simValues,stationManagement,timeManagement,sinrManagement,Nreassign] = ...
    stepResourceAllocation( ...
        simValues,stationManagement,timeManagement, ...
        positionManagement,sinrManagement,simParams,phyParams, ...
        appParams,outParams);

% Incremental sum of successfully reassigned and unlocked vehicles
outputValues.NreassignCV2X = outputValues.NreassignCV2X + Nreassign;

% A blocked outcome belongs to the allocator decision just completed. Only
% UEs with a pending packet have a packet fate to record.
blockedUeIds = ...
    simValues.resourceAllocationResult.BlockedUeIds;
[knownBlockedUes,blockedIds] = ismember( ...
    blockedUeIds,simValues.world.UeIds);
if ~all(knownBlockedUes)
    error( ...
        "v2xsim:resource:LegacyProjectionIdentityMismatch", ...
        "Blocked allocator outcomes must identify known UEs.");
end
blockedIds = blockedIds( ...
    stationManagement.pckBuffer(blockedIds) > 0);
for blockedId = reshape(blockedIds,1,[])
    [stationManagement,outputValues] = bufferOverflowLTE( ...
        blockedId,timeManagement,positionManagement, ...
        stationManagement,phyParams,appParams,outputValues, ...
        simValues,simParams.stringCV2X);
    stationManagement.pckNextAttempt(blockedId) = 1;
end
