function dispatchAfterPacketFatesDetermined( ...
        simValues,simulationTimeSeconds,technology, ...
        awarenessRangesMeters,stationManagement,positionManagement, ...
        transmitterIds,generationTimes,candidateReceiverIds, ...
        correctPairs,errorPairs,defaultOutcome)
%DISPATCHAFTERPACKETFATESDETERMINED Project legacy packet outcomes to hooks.
%   CANDIDATERECEIVERIDS has one row per transmitter and may use zero as
%   padding. CORRECTPAIRS and ERRORPAIRS contain [transmitter, receiver]
%   identifiers. All remaining candidate links receive DEFAULTOUTCOME.

if ~isfield(simValues,"hookDispatcher") || isempty(transmitterIds)
    return
end

transmitterIds = double(transmitterIds(:));
generationTimes = double(generationTimes(:));
candidateReceiverIds = double(candidateReceiverIds);
if isvector(candidateReceiverIds) && isscalar(transmitterIds)
    candidateReceiverIds = reshape(candidateReceiverIds,1,[]);
end
if size(candidateReceiverIds,1)~=numel(transmitterIds)
    error( ...
        "v2xsim:legacy:InvalidPacketFateCandidates", ...
        "Candidate receiver rows must correspond to transmitters.");
end

linkTransmitterIds = zeros(0,1);
linkReceiverIds = zeros(0,1);
linkDistances = zeros(0,1);
linkOutcomes = strings(0,1);
activeIds = stationManagement.activeIDs(:);

for transmitterIndex = 1:numel(transmitterIds)
    transmitterId = transmitterIds(transmitterIndex);
    receiverIds = candidateReceiverIds(transmitterIndex,:);
    receiverIds = receiverIds( ...
        receiverIds>0 & receiverIds~=transmitterId);
    receiverIds = unique(receiverIds(:),"stable");
    if isempty(receiverIds)
        continue
    end

    isTransmitterActive = ismember(transmitterId,activeIds);
    areReceiversActive = ismember(receiverIds,activeIds);
    if ~isTransmitterActive || ~all(areReceiversActive)
        error( ...
            "v2xsim:legacy:InactivePacketFateEndpoint", ...
            "Packet-fate endpoints must be active UEs.");
    end

    outcomes = repmat( ...
        string(defaultOutcome),numel(receiverIds),1);
    if ~isempty(correctPairs)
        isCorrect = ismember( ...
            [repmat(transmitterId,numel(receiverIds),1),receiverIds], ...
            double(correctPairs),"rows");
        outcomes(isCorrect) = "correct";
    end
    if ~isempty(errorPairs)
        isError = ismember( ...
            [repmat(transmitterId,numel(receiverIds),1),receiverIds], ...
            double(errorPairs),"rows");
        outcomes(isError) = "error";
    end

    linkTransmitterIds = [ ...
        linkTransmitterIds; ...
        repmat(transmitterId,numel(receiverIds),1)]; %#ok<AGROW>
    linkReceiverIds = [linkReceiverIds;receiverIds]; %#ok<AGROW>
    linkDistances = [ ...
        linkDistances; ...
        positionManagement.distanceReal( ...
            transmitterId,receiverIds).']; %#ok<AGROW>
    linkOutcomes = [linkOutcomes;outcomes]; %#ok<AGROW>
end

transmitters = table( ...
    transmitterIds, ...
    double(stationManagement.vehicleChannel(transmitterIds)), ...
    double(stationManagement.pckType(transmitterIds)), ...
    generationTimes, ...
    VariableNames=[ ...
        "TransmitterId","Channel","PacketType", ...
        "GenerationTimeSeconds"]);
links = table( ...
    linkTransmitterIds,linkReceiverIds,linkDistances,linkOutcomes, ...
    VariableNames=[ ...
        "TransmitterId","ReceiverId","DistanceMeters","Outcome"]);
invocation = v2xsim.hook.invocations. ...
    AfterPacketFatesDeterminedInvocation( ...
        simulationTimeSeconds,string(technology),simValues.maxID, ...
        double(awarenessRangesMeters(:).'),transmitters,links);
simValues.hookDispatcher.dispatch( ...
    v2xsim.hook.points.AfterPacketFatesDetermined,invocation);
end
