function dispatchAfterInterferenceEvidenceDetermined( ...
        simValues,simulationTimeSeconds,technology, ...
        stationManagement,transmitterIds,generationTimes,diagnostics)
%DISPATCHAFTERINTERFERENCEEVIDENCEDETERMINED Project terminal PHY evidence.

if ~isfield(simValues,"hookDispatcher") || ...
        ~simValues.hookDispatcher.hasHooks( ...
            v2xsim.hook.points. ...
            AfterInterferenceEvidenceDetermined) || ...
        isempty(diagnostics.TerminalAttempts)
    return
end

transmitterIds = double(transmitterIds(:));
generationTimes = double(generationTimes(:));
if numel(generationTimes) ~= numel(transmitterIds)
    error( ...
        "v2xsim:legacy:InvalidInterferenceGenerationTimes", ...
        "Every interference-evidence transmitter requires one " + ...
        "packet generation time.");
end

ueIds = stableUeIds(simValues);
attemptNumbers = double( ...
    stationManagement.pckTxOccurring(transmitterIds));
resourceIds = zeros(numel(transmitterIds),1);
for transmitterIndex = 1:numel(transmitterIds)
    resourceIds(transmitterIndex) = stationManagement.BRid( ...
        transmitterIds(transmitterIndex), ...
        attemptNumbers(transmitterIndex));
end
if numel(stationManagement.transmittingFusedLTE) < ...
        numel(transmitterIds)
    error( ...
        "v2xsim:legacy:InvalidInterferenceFrequencyResources", ...
        "Every interference-evidence transmitter requires one " + ...
        "frequency-resource identifier.");
end
frequencyResourceIds = double( ...
    stationManagement.transmittingFusedLTE( ...
        1:numel(transmitterIds)));
frequencyResourceIds = frequencyResourceIds(:);
allocationEpochs = zeros(numel(transmitterIds),1);
if isfield(simValues,"resourceAllocationEpoch")
    allocationEpochs(:) = double( ...
        simValues.resourceAllocationEpoch);
end

transmitters = table( ...
    transmitterIds,ueIds(transmitterIds),generationTimes, ...
    attemptNumbers,resourceIds,frequencyResourceIds, ...
    allocationEpochs, ...
    VariableNames=[ ...
        "TransmitterId","TransmitterUeId", ...
        "GenerationTimeSeconds","AttemptNumber", ...
        "ResourceId","FrequencyResourceId", ...
        "AllocationEpoch"]);
invocation = v2xsim.hook.invocations. ...
    AfterInterferenceEvidenceDeterminedInvocation( ...
        simulationTimeSeconds,string(technology),simValues.maxID, ...
        ueIds,transmitters,diagnostics.TerminalAttempts, ...
        diagnostics.Counterfactuals);
simValues.hookDispatcher.dispatch( ...
    v2xsim.hook.points. ...
        AfterInterferenceEvidenceDetermined, ...
    invocation);
end

function ueIds = stableUeIds(simValues)
if isfield(simValues,"world") && ...
        isa(simValues.world,"v2xsim.World")
    ueIds = simValues.world.UeIds;
else
    ueIds = "UE" + string((1:simValues.maxID).');
end
ueIds = string(ueIds(:));
if numel(ueIds) ~= simValues.maxID || ...
        any(ismissing(ueIds)) || ...
        any(strlength(strip(ueIds)) == 0) || ...
        numel(unique(ueIds)) ~= numel(ueIds)
    error( ...
        "v2xsim:legacy:InvalidInterferenceEvidenceIdentity", ...
        "World UE identities must uniquely map every dense legacy UE ID.");
end
end
