function dispatchAfterPacketFatesDetermined( ...
        simValues,simulationTimeSeconds,technology, ...
        awarenessRangesMeters,stationManagement,positionManagement, ...
        transmitterIds,generationTimes,candidateReceiverIds, ...
        correctPairs,errorPairs,defaultOutcome)
%DISPATCHAFTERPACKETFATESDETERMINED Project legacy packet outcomes to hooks.
%   CANDIDATERECEIVERIDS has one row per transmitter and may use zero as
%   padding. CORRECTPAIRS and ERRORPAIRS contain [transmitter, receiver]
%   identifiers. All remaining candidate links receive DEFAULTOUTCOME.

if ~isfield(simValues,"hookDispatcher") || isempty(transmitterIds)
    return
end

transmitterIds = double(transmitterIds(:));
generationTimes = double(generationTimes(:));
candidateReceiverIds = double(candidateReceiverIds);
if isvector(candidateReceiverIds) && isscalar(transmitterIds)
    candidateReceiverIds = reshape(candidateReceiverIds,1,[]);
end
if size(candidateReceiverIds,1)~=numel(transmitterIds)
    error( ...
        "v2xsim:legacy:InvalidPacketFateCandidates", ...
        "Candidate receiver rows must correspond to transmitters.");
end

linkTransmitterIds = zeros(0,1);
linkReceiverIds = zeros(0,1);
linkDistances = zeros(0,1);
linkOutcomes = strings(0,1);
activeIds = stationManagement.activeIDs(:);
ueIds = stableUeIds(simValues);

for transmitterIndex = 1:numel(transmitterIds)
    transmitterId = transmitterIds(transmitterIndex);
    receiverIds = candidateReceiverIds(transmitterIndex,:);
    receiverIds = receiverIds( ...
        receiverIds>0 & receiverIds~=transmitterId);
    receiverIds = unique(receiverIds(:),"stable");
    if isempty(receiverIds)
        continue
    end

    isTransmitterActive = ismember(transmitterId,activeIds);
    areReceiversActive = ismember(receiverIds,activeIds);
    if ~isTransmitterActive || ~all(areReceiversActive)
        error( ...
            "v2xsim:legacy:InactivePacketFateEndpoint", ...
            "Packet-fate endpoints must be active UEs.");
    end

    outcomes = repmat( ...
        string(defaultOutcome),numel(receiverIds),1);
    if ~isempty(correctPairs)
        isCorrect = ismember( ...
            [repmat(transmitterId,numel(receiverIds),1),receiverIds], ...
            double(correctPairs),"rows");
        outcomes(isCorrect) = "correct";
    end
    if ~isempty(errorPairs)
        isError = ismember( ...
            [repmat(transmitterId,numel(receiverIds),1),receiverIds], ...
            double(errorPairs),"rows");
        outcomes(isError) = "error";
    end

    linkTransmitterIds = [ ...
        linkTransmitterIds; ...
        repmat(transmitterId,numel(receiverIds),1)]; %#ok<AGROW>
    linkReceiverIds = [linkReceiverIds;receiverIds]; %#ok<AGROW>
    linkDistances = [ ...
        linkDistances; ...
        positionManagement.distanceReal( ...
            transmitterId,receiverIds).']; %#ok<AGROW>
    linkOutcomes = [linkOutcomes;outcomes]; %#ok<AGROW>
end

attemptNumbers = packetAttemptNumbers( ...
    stationManagement,transmitterIds);
allocationEpochs = packetAllocationEpochs( ...
    simValues,numel(transmitterIds));
packetSequences = nan(numel(transmitterIds),1);
packetComplete = false(numel(transmitterIds),1);
packetTypes = double(stationManagement.pckType(transmitterIds));
for packetIndex = 1:numel(transmitterIds)
    id = transmitterIds(packetIndex);
    if isfield(stationManagement,"packetFateMetadata")
        packet = stationManagement.packetFateMetadata;
        packetComplete(packetIndex) = packet.IsPacketComplete;
        attemptNumbers(packetIndex) = packet.AttemptNumber;
    elseif isfield(stationManagement,"packetBuffers")
        packet = stationManagement.packetBuffers{id}.head();
        if string(technology) == "11p"
            limit = stationManagement.ITSNumberOfReplicas(id);
        else
            limit = effectiveCv2xTransmissionCount(stationManagement,id);
        end
        packetComplete(packetIndex) = stationManagement.pckTxOccurring(id) >= limit;
    else
        continue
    end
    packetSequences(packetIndex) = packet.Sequence;
    generationTimes(packetIndex) = packet.GenerationTimeSeconds;
    packetTypes(packetIndex) = packet.PacketType;
end
resourceIds = packetResourceIds(stationManagement,transmitterIds,attemptNumbers,technology);
transmitters = table( ...
    transmitterIds, ...
    ueIds(transmitterIds), ...
    double(stationManagement.vehicleChannel(transmitterIds)), ...
    packetTypes, ...
    generationTimes, ...
    packetSequences, ...
    attemptNumbers,resourceIds, ...
    nan(numel(transmitterIds),1), ...
    nan(numel(transmitterIds),1), ...
    allocationEpochs, ...
    VariableNames=[ ...
        "TransmitterId","TransmitterUeId", ...
        "Channel","PacketType","GenerationTimeSeconds", ...
        "PacketSequence","AttemptNumber","ResourceId", ...
        "TimeResourceId","FrequencyResourceId", ...
        "AllocationEpoch"]);
transmitters.IsPacketComplete = packetComplete;
% Explicit event provenance distinguishes an actual TTI from a discard of
% a packet that has previously transmitted. It also covers zero-RX TTIs.
transmitters.IsOnAirObservation = repmat( ...
    string(defaultOutcome)~="blocked",numel(transmitterIds),1);
links = table( ...
    linkTransmitterIds,ueIds(linkTransmitterIds), ...
    linkReceiverIds,ueIds(linkReceiverIds), ...
    linkDistances,linkOutcomes,linkOutcomes~="none", ...
    VariableNames=[ ...
        "TransmitterId","TransmitterUeId", ...
        "ReceiverId","ReceiverUeId", ...
        "DistanceMeters","Outcome","IsTerminal"]);
invocation = v2xsim.hook.invocations. ...
    AfterPacketFatesDeterminedInvocation( ...
        simulationTimeSeconds,string(technology),simValues.maxID, ...
        double(awarenessRangesMeters(:).'),transmitters,links);
simValues.hookDispatcher.dispatch( ...
    v2xsim.hook.points.AfterPacketFatesDetermined,invocation);
end

function ueIds = stableUeIds(simValues)
if isfield(simValues,"world") && ...
        isa(simValues.world,"v2xsim.World")
    ueIds = simValues.world.UeIds;
else
    % Retain compatibility with focused legacy harnesses that predate
    % World, while making the fallback visibly synthetic in diagnostics.
    ueIds = "UE" + string((1:simValues.maxID).');
end
ueIds = string(ueIds(:));
if numel(ueIds) ~= simValues.maxID || ...
        any(ismissing(ueIds)) || ...
        any(strlength(strip(ueIds)) == 0) || ...
        numel(unique(ueIds)) ~= numel(ueIds)
    error( ...
        "v2xsim:legacy:InvalidPacketFateIdentity", ...
        "World UE identities must uniquely map every dense legacy UE ID.");
end
end

function attemptNumbers = packetAttemptNumbers( ...
        stationManagement,transmitterIds)
attemptNumbers = nan(numel(transmitterIds),1);
if ~isfield(stationManagement,"pckTxOccurring")
    return
end
values = double( ...
    stationManagement.pckTxOccurring(transmitterIds));
values = values(:);
isValid = isfinite(values) & values >= 0 & fix(values) == values;
attemptNumbers(isValid) = values(isValid);
end

function allocationEpochs = packetAllocationEpochs( ...
        simValues,transmitterCount)
allocationEpochs = nan(transmitterCount,1);
if ~isfield(simValues,"resourceAllocationEpoch")
    return
end
allocationEpoch = double(simValues.resourceAllocationEpoch);
if ~isscalar(allocationEpoch) || ~isfinite(allocationEpoch) || ...
        allocationEpoch < 0 || fix(allocationEpoch) ~= allocationEpoch
    error( ...
        "v2xsim:legacy:InvalidResourceAllocationEpoch", ...
        "Resource-allocation epoch must be a nonnegative integer.");
end
allocationEpochs(:) = allocationEpoch;
end

function resourceIds = packetResourceIds( ...
        stationManagement,transmitterIds,attemptNumbers,technology)
resourceIds = nan(numel(transmitterIds),1);
if string(technology) == "11p" || ...
        ~isfield(stationManagement,"BRid")
    return
end
for transmitterIndex = 1:numel(transmitterIds)
    attemptNumber = attemptNumbers(transmitterIndex);
    if isnan(attemptNumber) || attemptNumber < 1 || ...
            attemptNumber > size(stationManagement.BRid,2)
        continue
    end
    resourceId = double(stationManagement.BRid( ...
        transmitterIds(transmitterIndex),attemptNumber));
    if isfinite(resourceId) && resourceId > 0 && ...
            fix(resourceId) == resourceId
        resourceIds(transmitterIndex) = resourceId;
    end
end
end
