function dispatchBlockedPacketFates( ...
        simValues,simulationTimeSeconds,technology, ...
        awarenessRangesMeters,stationManagement,positionManagement, ...
        transmitterIds,generationTimes)
%DISPATCHBLOCKEDPACKETFATES Emit allocator blocks for PRR-eligible links.
%   The technology-specific neighbor matrices are the engine snapshot of
%   receivers inside the maximum PRR range. Passing those exact receiver
%   rows to the common packet-fate dispatcher makes the global PRR and raw
%   trace recorders consume the same block-time distance snapshot.

if ~isfield(simValues,"hookDispatcher") || isempty(transmitterIds)
    return
end

transmitterIds = double(transmitterIds(:));
technology = string(technology);
if technology == "11p"
    technologyTransmitterIds = ...
        double(stationManagement.activeIDs11p(:));
    neighborIds = stationManagement.neighborsID11p;
else
    technologyTransmitterIds = ...
        double(stationManagement.activeIDsCV2X(:));
    neighborIds = stationManagement.neighborsIDLTE;
end

[knownTransmitters,transmitterRows] = ismember( ...
    transmitterIds,technologyTransmitterIds);
if ~all(knownTransmitters)
    error( ...
        "v2xsim:legacy:UnknownBlockedPacketTransmitter", ...
        "Every blocked transmitter must belong to its technology " + ...
        "population snapshot.");
end

candidateReceiverIds = double(neighborIds(transmitterRows,:));
for transmitterIndex = 1:numel(transmitterIds)
    candidateReceiverIds( ...
        transmitterIndex, ...
        candidateReceiverIds(transmitterIndex,:) == ...
            transmitterIds(transmitterIndex)) = 0;
end

dispatchAfterPacketFatesDetermined( ...
    simValues,simulationTimeSeconds,technology, ...
    awarenessRangesMeters,stationManagement,positionManagement, ...
    transmitterIds,generationTimes,candidateReceiverIds, ...
    zeros(0,2),zeros(0,2),"blocked");
end
