classdef SimulationSummaryTest < matlab.unittest.TestCase
    %SIMULATIONSUMMARYTEST Tests nested summary semantics and JSON output.

    methods (Test)
        function testBuildsSemanticCoexistenceSummary(testCase)
            [station, sim, app, phy, sinr, out, values] = ...
                testCase.makeInputs();

            summary = v2xsim.output.buildSimulationSummary( ...
                station, sim, app, phy, sinr, out, values);

            testCase.verifyEqual(summary.SchemaVersion, 2);
            testCase.verifyFalse(isfield(summary.Run, "Identifier"));
            testCase.verifyEqual(summary.Run.SimulatorVersion, "V7");
            testCase.verifyEqual( ...
                summary.Configuration.Infrastructure. ...
                RoadSideUnitCount, 2);
            testCase.verifyEqual( ...
                summary.Configuration.ResourceAllocation. ...
                Metadata.Type, "ThreeGppAutonomous");
            testCase.verifyEqual( ...
                summary.Configuration.Coexistence. ...
                EffectiveStaticCellularSidelinkDurationSeconds, 0.007, ...
                AbsTol=1e-12);
            testCase.verifyFalse( ...
                summary.Configuration.Positioning. ...
                ControlledPositioningEnabled);
            testCase.verifyEqual( ...
                summary.Configuration.Application.PacketGeneration.Mode, ...
                "EtsiCam");
            testCase.verifyTrue(isnan( ...
                summary.Configuration.Application.PacketGeneration. ...
                UniformJitterSpanSeconds));

            metrics = summary.Results.CellularSidelink. ...
                AwarenessRangeMetrics;
            testCase.verifyClass(metrics, "cell");
            testCase.verifyNumElements(metrics, 2);
            testCase.verifyEqual( ...
                metrics{1}.AwarenessRangeLowerBoundMeters, 0);
            testCase.verifyEqual( ...
                metrics{1}.AwarenessRangeUpperBoundMeters, 100);
            testCase.verifyEqual( ...
                metrics{2}.AwarenessRangeLowerBoundMeters, 100);
            testCase.verifyEqual( ...
                metrics{2}.AwarenessRangeUpperBoundMeters, 200);
            testCase.verifyEqual( ...
                metrics{1}. ...
                NonblockedTransmitterReceiverOpportunityCount, 30);
            testCase.verifyTrue(isfield( ...
                metrics{1}, ...
                "MeanSnapshotNeighborCountStandardDeviation"));
            testCase.verifyFalse(isfield(metrics{1}, "Variance"));
            testCase.verifyTrue(isfield( ...
                summary.Results.Combined.AwarenessRangeMetrics{1}, ...
                "MeanSnapshotSumOfTechnologyNeighborCount" + ...
                "StandardDeviations"));

            cellular = summary.Results.CellularSidelink;
            testCase.verifyEqual( ...
                cellular.AverageInitialTransmissionsPerUePerSecond, ...
                2, AbsTol=1e-12);
            testCase.verifyEqual( ...
                cellular.AverageTransmissionsPerPacketIncludingHarq, ...
                1.5, AbsTol=1e-12);
            testCase.verifyEqual( ...
                cellular. ...
                AverageSuccessfulReassignmentsPerUePerSecond, ...
                0.25, AbsTol=1e-12);
            testCase.verifyEqual( ...
                cellular.ChannelBusyRatio.Status, "Available");
            testCase.verifyEqual( ...
                cellular.ChannelBusyRatio.Channels{1}.Status, ...
                "Available");
            testCase.verifyEqual( ...
                cellular.ChannelBusyRatio.Channels{1}.MedianRatio, ...
                0.5, AbsTol=1e-12);

            ieee80211p = summary.Results.Ieee80211p;
            testCase.verifyEqual( ...
                ieee80211p.AverageTransmissionOpportunityRate. ...
                AwarenessRangeUpperBoundMeters, 100);
            testCase.verifyEqual( ...
                ieee80211p.AverageTransmissionOpportunityRate. ...
                PerUePerNeighborPerSecond, 0.4, AbsTol=1e-12);
            testCase.verifyTrue(isnan( ...
                ieee80211p.ChannelBusyRatio.Channels{1}. ...
                HarqCongestionControlTriggered));
        end

        function testRepresentsNrAndInactiveTechnologyExplicitly(testCase)
            [station, sim, app, phy, sinr, out, values] = ...
                testCase.makeInputs();
            sim.technology = 1;
            sim.Technology = "5G-V2X";
            sim.mode5G = 1;
            phy.SCS_NR = 30;
            phy.MCS_NR = 11;
            values.AvgNUEs11p = 0;

            summary = v2xsim.output.buildSimulationSummary( ...
                station, sim, app, phy, sinr, out, values);

            testCase.verifyEqual( ...
                summary.Configuration.CellularSidelink.Technology, ...
                "NR-V2X");
            testCase.verifyEqual( ...
                summary.Configuration.RadioAccessMode, "NR-V2X");
            testCase.verifyEqual( ...
                summary.Configuration.CellularSidelink. ...
                SubcarrierSpacingKilohertz, 30);
            testCase.verifyFalse(summary.Results.Ieee80211p.Active);
            testCase.verifyEmpty( ...
                summary.Results.Ieee80211p.AwarenessRangeMetrics);
            testCase.verifyEqual( ...
                summary.Results.Ieee80211p.ChannelBusyRatio.Status, ...
                "NotApplicable");
        end

        function testReportsChannelBusyRatioStates(testCase)
            [station, sim, app, phy, sinr, out, values] = ...
                testCase.makeInputs();

            sim.cbrActive = false;
            disabled = v2xsim.output.buildSimulationSummary( ...
                station, sim, app, phy, sinr, out, values);
            testCase.verifyEqual( ...
                disabled.Results.CellularSidelink. ...
                ChannelBusyRatio.Status, "Disabled");

            sim.cbrActive = true;
            station.cbrCV2Xvalues = zeros(3, 10);
            insufficient = v2xsim.output.buildSimulationSummary( ...
                station, sim, app, phy, sinr, out, values);
            testCase.verifyEqual( ...
                insufficient.Results.CellularSidelink. ...
                ChannelBusyRatio.Status, "InsufficientSamples");

            station.vehicleState(:) = 1;
            noEligibleUes = v2xsim.output.buildSimulationSummary( ...
                station, sim, app, phy, sinr, out, values);
            testCase.verifyEqual( ...
                noEligibleUes.Results.CellularSidelink. ...
                ChannelBusyRatio.Status, "NoEligibleUes");

            station.vehicleState = [100; 100; 1];
            station.cbrCV2Xvalues = -ones(3, 12);
            noValidSamples = v2xsim.output.buildSimulationSummary( ...
                station, sim, app, phy, sinr, out, values);
            testCase.verifyEqual( ...
                noValidSamples.Results.CellularSidelink. ...
                ChannelBusyRatio.Status, "NoValidSamples");
            testCase.verifyEqual( ...
                noValidSamples.Results.CellularSidelink. ...
                ChannelBusyRatio.Channels{1}.Status, ...
                "NoValidSamples");
        end

        function testRecordsRampAndPositionErrorProvenance(testCase)
            [station, sim, app, phy, sinr, out, values] = ...
                testCase.makeInputs();
            sim.typeOfScenario = "ExitRampHighwayScenario";
            sim.scenarioOptions = struct( ...
                "RandomSeed", 41, ...
                "VehicleCount", 80, ...
                "NLanes", 3, ...
                "LaneWidth", 4, ...
                "RoadLength", 2000, ...
                "CentralDividerWidth", 1, ...
                "MeanVehicleSpeed", 30, ...
                "VehicleSpeedStandardDeviation", 2, ...
                "RerollSpeedOnWrapAround", false, ...
                "ExitProbability", 0.4, ...
                "MergeDistance", 120);
            sim.positionErrorModuleNames = ...
                ["Gaussian", "FalseExit", "Delay"];
            sim.positionErrorOptions = struct( ...
                "Gaussian", struct( ...
                    "StandardDeviationMeters", 3, ...
                    "DisplacementRandomSeed", 1001, ...
                    "AffectedVehicleProbability", 0.4, ...
                    "SelectionRandomSeed", 1002, ...
                    "ResetAfterSeconds", Inf, ...
                    "ActiveRoutes", "Merge,Adjacent"), ...
                "FalseExit", struct( ...
                    "AffectedVehicleProbability", 0.5, ...
                    "ResetAfterSeconds", Inf, ...
                    "DisplacementScale", 0.25, ...
                    "SelectionRandomSeed", 2001), ...
                "Delay", struct("DelaySeconds", 0.5));

            summary = v2xsim.output.buildSimulationSummary( ...
                station, sim, app, phy, sinr, out, values);

            scenario = summary.Configuration.Scenario;
            testCase.verifyEqual( ...
                scenario.Options.ExitProbability, 0.4);
            testCase.verifyEqual( ...
                scenario.Options.MergeDistance, 120);
            errorChain = summary.Configuration.Positioning.ErrorChain;
            testCase.verifyTrue(errorChain.Enabled);
            testCase.verifyNumElements(errorChain.Modules, 3);
            testCase.verifyEqual( ...
                errorChain.Modules{1}.Type, ...
                "PositionErrorStatusEffectInflictor");
            testCase.verifyEqual( ...
                errorChain.Modules{1}.StatusEffect.Type, ...
                "IsotropicGaussianPositionErrorStatusEffect");
            testCase.verifyEqual( ...
                errorChain.Modules{1}.StatusEffect.Options. ...
                DisplacementRandomSeed, 1001);
            testCase.verifyFalse(isfield( ...
                errorChain.Modules{1}, "Options"));
            testCase.verifyEqual( ...
                errorChain.Modules{2}.StatusEffect.Type, ...
                "FalseExitPositionErrorStatusEffect");
            testCase.verifyEqual( ...
                errorChain.Modules{2}.StatusEffect.Options. ...
                DisplacementScale, 0.25);
            testCase.verifyEqual( ...
                errorChain.Modules{3}.Type, "PositionDelayError");
            testCase.verifyEqual( ...
                errorChain.Modules{3}.Options.DelaySeconds, 0.5);
            testCase.verifyFalse(isfield( ...
                errorChain.Modules{3}, "StatusEffect"));
        end

        function testNamesMethodAPerceivedEndAsSeconds(testCase)
            [station, sim, app, phy, sinr, out, values] = ...
                testCase.makeInputs();
            sim.coexMethod = 1;
            sim.coex_endOfLTE = 0.06;
            sim.coexA_improvements = 2;
            sim.coexA_endOfLteKnownBy11p = 0.075;

            summary = v2xsim.output.buildSimulationSummary( ...
                station, sim, app, phy, sinr, out, values);
            methodA = summary.Configuration.Coexistence.MethodA;

            testCase.verifyEqual( ...
                methodA.Ieee80211pPerceivedCellularSidelinkEndSeconds, ...
                0.075, AbsTol=1e-12);
            testCase.verifyEqual( ...
                methodA.Ieee80211pPerceivedCellularSidelinkEndMode, ...
                "Explicit");
            testCase.verifyEqual(methodA.EnhancementVariant, 2);
            testCase.verifyFalse(isfield( ...
                methodA, "CellularSidelinkEndKnownByIeee80211p"));

            sim.coexA_endOfLteKnownBy11p = -1;
            automatic = v2xsim.output.buildSimulationSummary( ...
                station, sim, app, phy, sinr, out, values);
            automaticMethodA = ...
                automatic.Configuration.Coexistence.MethodA;
            testCase.verifyEqual( ...
                automaticMethodA. ...
                Ieee80211pPerceivedCellularSidelinkEndSeconds, ...
                0.06, AbsTol=1e-12);
            testCase.verifyEqual( ...
                automaticMethodA. ...
                Ieee80211pPerceivedCellularSidelinkEndMode, ...
                "EffectiveCellularSidelinkBoundary");
        end

        function testDoesNotInventStaticDurationForDynamicCoexistence( ...
                testCase)
            [station, sim, app, phy, sinr, out, values] = ...
                testCase.makeInputs();
            sim.coex_slotManagement = 2;
            sim.coex_endOfLTE = 0.09;
            sinr.coex_NtotSubframeLTE = [5; 7; 8];

            summary = v2xsim.output.buildSimulationSummary( ...
                station, sim, app, phy, sinr, out, values);
            coexistence = summary.Configuration.Coexistence;

            testCase.verifyEqual( ...
                coexistence.SlotManagement, "Dynamic");
            testCase.verifyTrue(isnan( ...
                coexistence. ...
                EffectiveStaticCellularSidelinkDurationSeconds));
            testCase.verifyFalse(isfield( ...
                coexistence, ...
                "ConfiguredCellularSidelinkDurationSeconds"));
            testCase.verifyFalse(isfield( ...
                coexistence, ...
                "ResolvedCellularSidelinkDurationSeconds"));
        end

        function testDistinguishesControlledPositioning(testCase)
            [station, sim, app, phy, sinr, out, values] = ...
                testCase.makeInputs();
            sim.resourceAllocationType = "ReuseDistance";
            sim.posError95 = 1.96;
            sim.Tupdate = 0.25;

            summary = v2xsim.output.buildSimulationSummary( ...
                station, sim, app, phy, sinr, out, values);
            positioning = summary.Configuration.Positioning;

            testCase.verifyTrue( ...
                positioning.ControlledPositioningEnabled);
            testCase.verifyEqual( ...
                positioning.PositionError95PercentileMeters, ...
                1.96, AbsTol=1e-12);
            testCase.verifyEqual( ...
                positioning.UpdateIntervalSeconds, ...
                0.25, AbsTol=1e-12);
        end

        function testDescribesUniformJitterWithoutSentinels(testCase)
            [station, sim, app, phy, sinr, out, values] = ...
                testCase.makeInputs();
            app.variabilityGenerationInterval = 0.04;

            summary = v2xsim.output.buildSimulationSummary( ...
                station, sim, app, phy, sinr, out, values);
            packetGeneration = ...
                summary.Configuration.Application.PacketGeneration;

            testCase.verifyEqual( ...
                packetGeneration.Mode, "PerVehicleUniformJitter");
            testCase.verifyEqual( ...
                packetGeneration.UniformJitterSpanSeconds, ...
                0.04, AbsTol=1e-12);
            testCase.verifyEqual( ...
                packetGeneration.UniformJitterHalfWidthSeconds, ...
                0.02, AbsTol=1e-12);
        end

        function testPreservesUnboundedFullDuplexThresholdState(testCase)
            [station, sim, app, phy, sinr, out, values] = ...
                testCase.makeInputs();
            phy.duplexCV2X = "FD";
            phy.Ksi_dB = -110;
            phy.PDelta = Inf;

            summary = v2xsim.output.buildSimulationSummary( ...
                station, sim, app, phy, sinr, out, values);
            cellular = summary.Configuration.CellularSidelink;

            testCase.verifyEqual( ...
                cellular.ResidualSelfInterferenceDb, -110);
            testCase.verifyEqual( ...
                cellular.ResidualSelfInterferenceMode, "Finite");
            testCase.verifyEqual( ...
                cellular.SelfInterferenceThresholdMultiplierMode, ...
                "ThresholdDisabled");
            testCase.verifyFalse( ...
                cellular. ...
                SelfInterferenceThresholdAdjustmentEnabled);
            outputDirectory = testCase.makeTemporaryDirectory();
            outputFile = v2xsim.output.writeSimulationSummary( ...
                outputDirectory, summary);
            jsonText = string(fileread(outputFile));
            testCase.verifyNotEmpty(regexp( ...
                jsonText, ...
                """SelfInterferenceThresholdMultiplier""\s*:\s*null", ...
                "once"));

            phy.PDelta = 2;
            finite = v2xsim.output.buildSimulationSummary( ...
                station, sim, app, phy, sinr, out, values);
            finiteCellular = finite.Configuration.CellularSidelink;
            testCase.verifyTrue( ...
                finiteCellular. ...
                SelfInterferenceThresholdAdjustmentEnabled);
            testCase.verifyEqual( ...
                finiteCellular.SelfInterferenceThresholdMultiplier, ...
                2);
            testCase.verifyEqual( ...
                finiteCellular. ...
                SelfInterferenceThresholdMultiplierMode, "Finite");

            phy.Ksi_dB = Inf;
            infiniteResidual = ...
                v2xsim.output.buildSimulationSummary( ...
                    station, sim, app, phy, sinr, out, values);
            infiniteCellular = ...
                infiniteResidual.Configuration.CellularSidelink;
            testCase.verifyEqual( ...
                infiniteCellular.ResidualSelfInterferenceMode, ...
                "UnboundedResidualInterference");
            testCase.verifyFalse( ...
                infiniteCellular. ...
                SelfInterferenceThresholdAdjustmentEnabled);

            phy.Ksi_dB = -Inf;
            perfectCancellation = ...
                v2xsim.output.buildSimulationSummary( ...
                    station, sim, app, phy, sinr, out, values);
            perfectCellular = ...
                perfectCancellation.Configuration.CellularSidelink;
            testCase.verifyEqual( ...
                perfectCellular.ResidualSelfInterferenceMode, ...
                "PerfectCancellation");
            testCase.verifyTrue( ...
                perfectCellular. ...
                SelfInterferenceThresholdAdjustmentEnabled);
        end

        function testWritesStrictJsonAndRoundTripsNestedArrays(testCase)
            [station, sim, app, phy, sinr, out, values] = ...
                testCase.makeInputs();
            summary = v2xsim.output.buildSimulationSummary( ...
                station, sim, app, phy, sinr, out, values);
            outputDirectory = testCase.makeTemporaryDirectory();

            outputFile = v2xsim.output.writeSimulationSummary( ...
                outputDirectory, summary);

            testCase.verifyEqual( ...
                outputFile, fullfile( ...
                    outputDirectory, "simulation_summary.json"));
            jsonText = string(fileread(outputFile));
            testCase.verifyNotEmpty(regexp( ...
                jsonText, ...
                """AwarenessRangeMetrics""\s*:\s*\[", "once"));
            testCase.verifyNotEmpty(regexp( ...
                jsonText, """Channels""\s*:\s*\[", "once"));
            testCase.verifyNotEmpty(regexp( ...
                jsonText, """RangesMeters""\s*:\s*\[", "once"));
            testCase.verifyTrue(contains(jsonText, "null"));
            testCase.verifyFalse(contains(jsonText, "NaN"));
            testCase.verifyFalse(contains(jsonText, "Infinity"));

            decoded = jsondecode(jsonText);
            testCase.verifyEqual(decoded.SchemaVersion, 2);
            testCase.verifyEqual( ...
                decoded.Configuration.Infrastructure. ...
                RoadSideUnitCount, 2);
            testCase.verifyEqual( ...
                string(decoded.Configuration.ResourceAllocation. ...
                Metadata.Type), "ThreeGppAutonomous");
            testCase.verifyNumElements( ...
                decoded.Results.CellularSidelink. ...
                AwarenessRangeMetrics, 2);

            jsonFiles = dir(fullfile(outputDirectory, "*.json"));
            testCase.verifyEqual( ...
                string({jsonFiles.name}), "simulation_summary.json");
        end

        function testPreservesSingletonCollectionsAsJsonArrays(testCase)
            [station, sim, app, phy, sinr, out, values] = ...
                testCase.makeInputs();
            phy.Raw = phy.Raw(1);
            values = testCase.retainFirstRange(values);
            summary = v2xsim.output.buildSimulationSummary( ...
                station, sim, app, phy, sinr, out, values);
            outputDirectory = testCase.makeTemporaryDirectory();

            outputFile = v2xsim.output.writeSimulationSummary( ...
                outputDirectory, summary);
            jsonText = string(fileread(outputFile));

            testCase.verifyNotEmpty(regexp( ...
                jsonText, ...
                """AwarenessRangeMetrics""\s*:\s*\[\s*\{", ...
                "once"));
            testCase.verifyNotEmpty(regexp( ...
                jsonText, """Channels""\s*:\s*\[\s*\{", "once"));
            testCase.verifyNotEmpty(regexp( ...
                jsonText, """RangesMeters""\s*:\s*\[\s*100", ...
                "once"));
        end

        function testNeverOverwritesExistingSummary(testCase)
            outputDirectory = testCase.makeTemporaryDirectory();
            outputFile = fullfile( ...
                outputDirectory, "simulation_summary.json");
            testCase.writeText(outputFile, "existing result");

            testCase.verifyError( ...
                @() v2xsim.output.writeSimulationSummary( ...
                    outputDirectory, struct("SchemaVersion", 2)), ...
                "v2xsim:output:SummaryAlreadyExists");
            testCase.verifyEqual( ...
                string(fileread(outputFile)), "existing result");
        end

        function testRemovesTemporaryFileWhenSerializationFails(testCase)
            outputDirectory = testCase.makeTemporaryDirectory();
            invalidSummary = struct("Unsupported", @sin);

            testCase.verifyError( ...
                @() v2xsim.output.writeSimulationSummary( ...
                    outputDirectory, invalidSummary), ...
                "MATLAB:io:xml:writestruct:UnsupportedDatatypeInStruct");
            testCase.verifyFalse(isfile(fullfile( ...
                outputDirectory, "simulation_summary.json")));
            testCase.verifyEmpty(dir(fullfile(outputDirectory, "*.json")));
        end
    end

    methods (Access = private)
        function [station, sim, app, phy, sinr, out, values] = ...
                makeInputs(~)
            station = struct( ...
                "vehicleState", [100; 100; 1], ...
                "vehicleChannel", [1; 1; 1], ...
                "cbrCV2Xvalues", [ ...
                    -ones(1, 10), 0.2, 0.4; ...
                    -ones(1, 10), 0.6, 0.8; ...
                    -ones(1, 10), 0.1, 0.1], ...
                "cbr11pValues", [ ...
                    -ones(1, 10), 0.1, 0.1; ...
                    -ones(1, 10), 0.1, 0.1; ...
                    -ones(1, 10), 0.3, 0.7], ...
                "dccLteTriggered", true, ...
                "dccLteTriggeredHarq", false, ...
                "dcc11pTriggered", true);

            allocatorMetadata = struct( ...
                "Type", "ThreeGppAutonomous", ...
                "RandomSeed", 19, ...
                "Options", struct("KeepResourceProbability", 0.8));
            sim = struct( ...
                "CheckVersion", "V7", ...
                "seed", 17, ...
                "simulationTime", 10, ...
                "resourceAllocationType", "ThreeGppAutonomous", ...
                "fileCfg", "campaign.toml", ...
                "Technology", "COEX-STD-INTERF", ...
                "technology", 4, ...
                "mode5G", 0, ...
                "typeOfScenario", "EtsiHighwayScenario", ...
                "positionTimeResolution", 0.1, ...
                "fileObstaclesMap", false, ...
                "posError95", 1.5, ...
                "Tupdate", 0.2, ...
                "cbrActive", true, ...
                "numVehiclesLTE", 2, ...
                "numVehicles11p", 1, ...
                "coexMethod", 3, ...
                "coex_slotManagement", 1, ...
                "coex_superFlength", 0.1, ...
                "coex_endOfLTE", 0, ...
                "coexC_timegapVariant", 2, ...
                "coexC_11pDetection", true, ...
                "coexCmodifiedCW", false, ...
                "coexC_moreThanOneSubframe", true, ...
                "coex_cbrLteVariant", 3, ...
                "coex_cbrTotVariant", 1, ...
                "resourceAllocationMetadata", allocatorMetadata);

            app = struct( ...
                "nRSUs", 2, ...
                "allocationPeriod", 0.1, ...
                "beaconSizeBytes", 350, ...
                "resourcesV2V", 80, ...
                "variabilityGenerationInterval", -1, ...
                "generationInterval", 0.1, ...
                "generationIntervalAverageRandomPart", 0.02, ...
                "camDiscretizationType", "allocationAligned", ...
                "camDiscretizationIncrease", 20, ...
                "Nbeacons", 20, ...
                "RBsBeacon", 10);

            phy = struct( ...
                "Raw", [100, 200], ...
                "NsubchannelsBeacon", 2, ...
                "sizeSubchannel", 10, ...
                "ifAdjacent", true, ...
                "BwMHz", 10, ...
                "Ptx_dBm", 23, ...
                "FixedPdensity", true, ...
                "Pnoise_MHz_dBm", -105, ...
                "F_dB", 9, ...
                "Gt_dB", 3, ...
                "Gr_dB", 3, ...
                "nChannels", 1, ...
                "propVehiclesChannels", 1, ...
                "mcoPowerDeltaChannels", 0, ...
                "MCS_LTE", 7, ...
                "P_ERP_MHz_CV2X_dBm", 16, ...
                "duplexCV2X", "HD", ...
                "Ksi_dB", Inf, ...
                "pWithLTEPHY", false, ...
                "MCS_11p", 2, ...
                "P_ERP_MHz_11p_dBm", 16, ...
                "CW", 15, ...
                "AifsN", 6, ...
                "CCAthr11p_notsync", -65, ...
                "CCAthr11p_sync", -85, ...
                "rilModel11p", false, ...
                "channelModel", 1, ...
                "L0_dB", 47.86, ...
                "beta", 2.2, ...
                "Abuild_dB", 0.4, ...
                "Awall_dB", 6, ...
                "PERcurves", false, ...
                "folderPERcurves", "null", ...
                "sinrThresholdCV2X_LOS_dB", 2.5, ...
                "sinrThreshold11p_LOS_dB", 3.5, ...
                "stdDevShadowLOS_dB", 3, ...
                "stdDevShadowNLOS_dB", 4, ...
                "RawMaxCV2X", 600, ...
                "RawMaxLOSCV2X", 500, ...
                "RawMaxNLOSCV2X", 300, ...
                "RawMax11p", 550, ...
                "RawMaxLOS11p", 450, ...
                "RawMaxNLOS11p", 250, ...
                "Tsf", 0.001);

            sinr = struct("coex_NtotSubframeLTE", 7);
            out = struct("message", "focused test");
            values = struct( ...
                "computationTime", 4.25, ...
                "AvgNUEsCV2X", 2, ...
                "AvgNUEs11p", 1, ...
                "AvgNUEsTOT", 3, ...
                "NneighborsCV2X", [4, 8], ...
                "Nneighbors11p", [5, 9], ...
                "NneighborsTOT", [6, 10], ...
                "StDevNeighboursCV2X", [0.4, 0.8], ...
                "StDevNeighbours11p", [0.5, 0.9], ...
                "StDevNeighboursTOT", [0.9, 1.7], ...
                "NreassignCV2X", 0.25, ...
                "NtxBeaconsCV2X", reshape([30, 50], 1, 1, 2), ...
                "NtxBeacons11p", reshape([20, 30], 1, 1, 2), ...
                "NtxBeaconsTOT", reshape([50, 80], 1, 1, 2), ...
                "cv2xTransmissionsFirst", 40, ...
                "cv2xTransmissionsIncHarq", 60, ...
                "blockingRateCV2X", [0.1, 0.2], ...
                "blockingRate11p", [0.2, 0.3], ...
                "blockingRateTOT", [0.15, 0.25], ...
                "errorRateCV2X", [0.05, 0.1], ...
                "errorRate11p", [0.1, 0.15], ...
                "errorRateTOT", [0.075, 0.125], ...
                "packetReceptionRatioCV2X", [0.85, 0.7], ...
                "packetReceptionRatio11p", [0.7, 0.55], ...
                "packetReceptionRatioTOT", [0.775, 0.625]);
        end

        function values = retainFirstRange(~, values)
            vectorFields = [ ...
                "NneighborsCV2X", "Nneighbors11p", "NneighborsTOT", ...
                "StDevNeighboursCV2X", ...
                "StDevNeighbours11p", ...
                "StDevNeighboursTOT", ...
                "blockingRateCV2X", "blockingRate11p", ...
                "blockingRateTOT", "errorRateCV2X", ...
                "errorRate11p", "errorRateTOT", ...
                "packetReceptionRatioCV2X", ...
                "packetReceptionRatio11p", ...
                "packetReceptionRatioTOT"];
            for field = vectorFields
                fieldValues = values.(field);
                values.(field) = fieldValues(1);
            end
            cubeFields = [ ...
                "NtxBeaconsCV2X", ...
                "NtxBeacons11p", ...
                "NtxBeaconsTOT"];
            for field = cubeFields
                values.(field) = values.(field)(:, :, 1);
            end
        end

        function folder = makeTemporaryDirectory(testCase)
            fixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);
            folder = string(fixture.Folder);
        end

        function writeText(~, file, value)
            fileId = fopen(file, "wt");
            assert(fileId ~= -1);
            cleanup = onCleanup(@() fclose(fileId));
            fprintf(fileId, "%s", value);
            clear cleanup
        end
    end
end
