function simValues = applyPositionErrorChain( ...
        simParams,simValues,simulationTimeSeconds)
%APPLYPOSITIONERRORCHAIN Update controller-visible vehicle positions.
%   Position-error modules receive only named vehicle rows. Fixed RSU rows
%   remain unchanged in the complete UE estimate.

world = simValues.world;
uePositions = table( ...
    simValues.XvehicleEstimated, ...
    simValues.YvehicleEstimated, ...
    VariableNames=["X","Y"], ...
    RowNames=cellstr(world.UeIds));
apparentVehiclePositions = uePositions( ...
    cellstr(world.VehicleIds),:);
positionsBeforeErrorChain = apparentVehiclePositions;
context = createContext( ...
    world.TrafficScenario,simulationTimeSeconds, ...
    simParams.positionTimeResolution,simParams.simulationTime);
moduleDiagnostics = ...
    v2xsim.positioning.diagnostics.emptyTable();
positionErrorHookPoint = ...
    v2xsim.hook.points.AfterPositionErrorChainApplied;
collectDiagnostics = isfield(simValues, "hookDispatcher") && ...
    simValues.hookDispatcher.hasHooks(positionErrorHookPoint);

if isfield(simValues,'positionErrorChain')
    if collectDiagnostics
        [positionErrorChain, apparentVehiclePositions, ...
            moduleDiagnostics] = ...
            simValues.positionErrorChain.apply( ...
                apparentVehiclePositions,context);
    else
        [positionErrorChain, apparentVehiclePositions] = ...
            simValues.positionErrorChain.apply( ...
            apparentVehiclePositions,context);
    end
    simValues.positionErrorChain = positionErrorChain;
end

apparentVehiclePositions = apparentVehiclePositions( ...
    cellstr(world.VehicleIds),:);
uePositions(cellstr(world.VehicleIds),:) = ...
    apparentVehiclePositions;
simValues.XvehicleEstimated = uePositions.X;
simValues.YvehicleEstimated = uePositions.Y;

if isfield(simValues, "hookDispatcher")
    invocation = v2xsim.hook.invocations. ...
        AfterPositionErrorChainAppliedInvocation( ...
            positionsBeforeErrorChain, ...
            apparentVehiclePositions, ...
            simulationTimeSeconds, ...
            moduleDiagnostics);
    simValues.hookDispatcher.dispatch( ...
        positionErrorHookPoint, ...
        invocation);
end
end

function context = createContext( ...
        scenario,simulationTimeSeconds,timeStepSeconds,durationSeconds)
if isa( ...
        scenario, ...
        'v2xsim.vehicle.scenarios.ExitRampHighwayScenario')
    context = v2xsim.positioning.ExitRampPositionErrorContext( ...
        scenario,simulationTimeSeconds,timeStepSeconds,durationSeconds);
elseif isa( ...
        scenario, ...
        'v2xsim.vehicle.scenarios.RoundaboutScenario')
    context = v2xsim.positioning.RoundaboutPositionErrorContext( ...
        scenario,simulationTimeSeconds,timeStepSeconds,durationSeconds);
else
    actualPositions = ...
        scenario.VehicleKinematics(:,["X","Y"]);
    context = v2xsim.positioning.PositionErrorContext( ...
        actualPositions,simulationTimeSeconds, ...
        timeStepSeconds,durationSeconds);
end
end
