function dispatchAfterVehicleKinematicsUpdated( ...
        simValues,simulationTimeSeconds,vehicleKinematics)
%DISPATCHAFTERVEHICLEKINEMATICSUPDATED Dispatch a canonical snapshot.

if ~isfield(simValues,"hookDispatcher")
    return
end

invocation = v2xsim.hook.invocations. ...
    AfterVehicleKinematicsUpdatedInvocation( ...
        simulationTimeSeconds,vehicleKinematics);
simValues.hookDispatcher.dispatch( ...
    v2xsim.hook.points.AfterVehicleKinematicsUpdated, ...
    invocation);
end
