function result = createEchoResult(context, assignments, ~)
%CREATEECHORESULT Return unchanged assignments for allocator contract tests.

result = v2xsim.resource.ResourceAllocationResult( ...
    context.NetworkSliceId, assignments, ...
    strings(0, 1), strings(0, 1), strings(0, 1), ...
    v2xsim.resource.ResourceAllocationResult.emptyReservations());
end
